-- lua header. UTF-8 인코딩 인식을 위해 이 줄은 지우지 마세요.

INIT_SYSTEM = 
{
	LUA_SHAREABLE	= TRUE,
	UNIT_WIDTH		= 110.0,
	UNIT_LAYER		= X2_LAYER["XL_UNIT_0"],
}

INIT_DEVICE = 
{
	READY_TEXTURE = 
	{
	},
	
	READY_SOUND = 
	{        
		"Airship_High_PowerBooster.ogg",
		"Airship_High_DefenceBooster.ogg",
		"Airship_High_Slash1.ogg",
		"Airship_High_Slash2.ogg",
		"Airship_High_StandUpAttack.ogg",
		"Airship_High_WaitZero1.ogg",
		"Airship_High_WaitZero2.ogg",
		"Airship_High_Kick.ogg",
		
	},
}

INIT_MOTION = 
{
	MOTION_FILE_NAME	= "Motion_AirShip_Solder_High.X",
	MOTION_ANI_TEX_XET		= "Low_Blcw_Soldier_High_FD.xet",
	MOTION_CHANGE_TEX_XET	= "Low_Blcw_Soldier_High_FD.xet",
}

INIT_PHYSIC = 
{
	RELOAD_ACCEL		= 2000,
	G_ACCEL				= 4000,
	MAX_G_SPEED			= -2000,
	
	WALK_SPEED			= 500,
	RUN_SPEED			= 650,
	JUMP_SPEED			= 1600,
	DASH_JUMP_SPEED		= 2400,
}

INIT_COMPONENT = 
{
	MAX_HP				= 10000,
	MP_CHANGE_RATE		= 1,
	MP_CHARGE_RATE		= 130,
	

	SHADOW_SIZE			= 200,
	SHADOW_FILE_NAME	= "shadow.dds",
	
	SMALL_HP_BAR_BLUE	= "Small_HP_bar_Blue.TGA",
	SMALL_HP_BAR_RED	= "Small_HP_bar_Red.TGA",
	SMALL_HP_BAR_YELLOW = "Small_HP_bar_Yellow.TGA",
	
	
	QUESTION_MARK_SEQ		= "QuestionMarkNPC",
	EXCLAMATION_MARK_SEQ	= "ExclamationMarkNPC",
	
	HYPER_MODE_COUNT	= 0,
	MAX_HYPER_MODE_TIME	= 30,
	
	HITTED_TYPE			= HITTED_TYPE["HTD_MEAT"],
	
	FALL_DOWN			= TRUE,
	

    DEFENCE_RATE		= 2,
	

	WEAPON0 = 
	{
		WEAPON_FILE_NAME	= "Mesh_AirShip_Solder_High_Weapon_Sorted.X",
		WEAPON_BONE_NAME	= "Dummy1_Rhand",
		
		--WEAPON_ROTAION_X = 0,
		--WEAPON_ROTAION_Y = 90,
		--WEAPON_ROTAION_Z = 100,

		WEAPON_SCALE_X = 0.4,
		WEAPON_SCALE_Y = 0.4,
		WEAPON_SCALE_Z = 0.4,
		
		USE_SLASH_TRACE				= TRUE,
		SLASH_TRACE_TOP_BONE		= "TRACE_START1",
		SLASH_TRACE_BOTTOM_BONE		= "TRACE_END1",
	},

	
	
	

	
}

INIT_STATE = 
{
	{ STATE_NAME = "LOW_BLCW_SOLDIER_HIGH_FD_START",						LUA_CAMERA_MOVE_FUNC = "LOW_BLCW_SOLDIER_HIGH_FD_START_CAMERA_MOVE", },
	{ STATE_NAME = "LOW_BLCW_SOLDIER_HIGH_FD_WIN",						},
	{ STATE_NAME = "LOW_BLCW_SOLDIER_HIGH_FD_WAIT",						}, --LUA_FRAME_MOVE_FUNC = "LOW_BLCW_SOLDIER_HIGH_FD_WAIT_FRAME_MOVE" },
	{ STATE_NAME = "LOW_BLCW_SOLDIER_HIGH_FD_WAIT2",						},
	{ STATE_NAME = "LOW_BLCW_SOLDIER_HIGH_FD_WAIT3",						},
	{ STATE_NAME = "LOW_BLCW_SOLDIER_HIGH_FD_WALK",						}, --LUA_FRAME_MOVE_FUNC = "LOW_BLCW_SOLDIER_HIGH_FD_WALK_FRAME_MOVE", LUA_STATE_END_FUNC = "LOW_BLCW_SOLDIER_HIGH_FD_WALK_STATE_END"		},
	{ STATE_NAME = "LOW_BLCW_SOLDIER_HIGH_FD_JUMP_UP",					},
	{ STATE_NAME = "LOW_BLCW_SOLDIER_HIGH_FD_JUMP_DOWN",					LUA_STATE_END_FUNC = "LOW_BLCW_SOLDIER_HIGH_FD_JUMP_DOWN_STATE_END" },
	{ STATE_NAME = "LOW_BLCW_SOLDIER_HIGH_FD_JUMP_UP_DIR",				},
	{ STATE_NAME = "LOW_BLCW_SOLDIER_HIGH_FD_JUMP_DOWN_DIR",				LUA_STATE_END_FUNC = "LOW_BLCW_SOLDIER_HIGH_FD_JUMP_DOWN_DIR_STATE_END" },
	{ STATE_NAME = "LOW_BLCW_SOLDIER_HIGH_FD_JUMP_LANDING",				},
	{ STATE_NAME = "LOW_BLCW_SOLDIER_HIGH_FD_DASH",						}, --LUA_FRAME_MOVE_FUNC = "LOW_BLCW_SOLDIER_HIGH_FD_DASH_FRAME_MOVE" },
	{ STATE_NAME = "LOW_BLCW_SOLDIER_HIGH_FD_DASH_END",					},
	
	{ STATE_NAME = "LOW_BLCW_SOLDIER_HIGH_FD_COMBO1",					},
	{ STATE_NAME = "LOW_BLCW_SOLDIER_HIGH_FD_COMBO2",					LUA_FRAME_MOVE_FUNC = "LOW_BLCW_SOLDIER_HIGH_FD_COMBO2_FRAME_MOVE"	},
	{ STATE_NAME = "LOW_BLCW_SOLDIER_HIGH_FD_DASH_ATTACK",				STATE_COOL_TIME = 5,												},
	{ STATE_NAME = "LOW_BLCW_SOLDIER_HIGH_FD_JUMP_ATTACK",				},
	{ STATE_NAME = "LOW_BLCW_SOLDIER_HIGH_FD_JUMP_FOR_ATTACK",			},
	
	{ STATE_NAME = "LOW_BLCW_SOLDIER_HIGH_FD_POWER_BOOSTER",			LUA_FRAME_MOVE_FUNC = "LOW_BLCW_SOLDIER_HIGH_FD_POWER_BOOSTER_FRAME_MOVE",					
																    LUA_STATE_END_FUNC = "LOW_BLCW_SOLDIER_HIGH_FD_POWER_BOOSTER_STATE_END",					
																    STATE_COOL_TIME = 40, },	
																
    { STATE_NAME = "LOW_BLCW_SOLDIER_HIGH_FD_DEFENCE_BOOSTER",			LUA_FRAME_MOVE_FUNC = "LOW_BLCW_SOLDIER_HIGH_FD_DEFENCE_BOOSTER_FRAME_MOVE",					
																    LUA_STATE_END_FUNC = "LOW_BLCW_SOLDIER_HIGH_FD_DEFENCE_BOOSTER_STATE_END",					
																    STATE_COOL_TIME = 40, },	
																																
	{ STATE_NAME = "LOW_BLCW_SOLDIER_HIGH_FD_DEFENCE",				    STATE_COOL_TIME = 6, },
	
	--리액션 관련
	{ STATE_NAME = "LOW_BLCW_SOLDIER_HIGH_FD_DAMAGE_SMALL",					LUA_FRAME_MOVE_FUNC = "LOW_BLCW_SOLDIER_HIGH_FD_DAMAGE_SMALL_FRAME_MOVE" },
	{ STATE_NAME = "LOW_BLCW_SOLDIER_HIGH_FD_DAMAGE_BIG",					LUA_FRAME_MOVE_FUNC = "LOW_BLCW_SOLDIER_HIGH_FD_DAMAGE_BIG_FRAME_MOVE" 	},
	{ STATE_NAME = "LOW_BLCW_SOLDIER_HIGH_FD_DAMAGE_DOWN_FRONT",			LUA_FRAME_MOVE_FUNC = "LOW_BLCW_SOLDIER_HIGH_FD_DAMAGE_DOWN_FRONT_FRAME_MOVE"		},
	{ STATE_NAME = "LOW_BLCW_SOLDIER_HIGH_FD_DAMAGE_DOWN_BACK",				LUA_FRAME_MOVE_FUNC = "LOW_BLCW_SOLDIER_HIGH_FD_DAMAGE_DOWN_BACK_FRAME_MOVE"		},
	{ STATE_NAME = "LOW_BLCW_SOLDIER_HIGH_FD_DAMAGE_FLY_FRONT",			},
	{ STATE_NAME = "LOW_BLCW_SOLDIER_HIGH_FD_DAMAGE_FLY_BACK",			},
	{ STATE_NAME = "LOW_BLCW_SOLDIER_HIGH_FD_DAMAGE_AIR",				},
	{ STATE_NAME = "LOW_BLCW_SOLDIER_HIGH_FD_DAMAGE_AIR_DOWN",			},
	{ STATE_NAME = "LOW_BLCW_SOLDIER_HIGH_FD_DAMAGE_AIR_UP",				},
	{ STATE_NAME = "LOW_BLCW_SOLDIER_HIGH_FD_DAMAGE_AIR_FALL",			},	
	{ STATE_NAME = "LOW_BLCW_SOLDIER_HIGH_FD_DAMAGE_AIR_DOWN_LANDING",	LUA_FRAME_MOVE_FUNC = "LOW_BLCW_SOLDIER_HIGH_FD_DAMAGE_AIR_DOWN_LANDING_FRAME_MOVE"	},
	{ STATE_NAME = "LOW_BLCW_SOLDIER_HIGH_FD_STAND_UP_FRONT",			},
	{ STATE_NAME = "LOW_BLCW_SOLDIER_HIGH_FD_STAND_UP_BACK",				},
	{ STATE_NAME = "LOW_BLCW_SOLDIER_HIGH_FD_STAND_UP_ATTACK_FRONT",		LUA_FRAME_MOVE_FUNC = "LOW_BLCW_SOLDIER_HIGH_FD_STAND_UP_ATTACK_FRONT_FRAME_MOVE"	},
	{ STATE_NAME = "LOW_BLCW_SOLDIER_HIGH_FD_STAND_UP_ATTACK_BACK",		LUA_FRAME_MOVE_FUNC = "LOW_BLCW_SOLDIER_HIGH_FD_STAND_UP_ATTACK_BACK_FRAME_MOVE"	},
	{ STATE_NAME = "LOW_BLCW_SOLDIER_HIGH_FD_DAMAGE_REVENGE",			},

	{ STATE_NAME = "LOW_BLCW_SOLDIER_HIGH_FD_DYING_LAND_FRONT",	 },
	{ STATE_NAME = "LOW_BLCW_SOLDIER_HIGH_FD_DYING_LAND_BACK",	 },
	{ STATE_NAME = "LOW_BLCW_SOLDIER_HIGH_FD_DYING_SKY",		 },
	
	
	START_STATE					= "LOW_BLCW_SOLDIER_HIGH_FD_WAIT",
	WAIT_STATE					= "LOW_BLCW_SOLDIER_HIGH_FD_WAIT",
	DEFENCE_STATE				= "LOW_BLCW_SOLDIER_HIGH_FD_DEFENCE",
	
	SMALL_DAMAGE_LAND_FRONT		= "LOW_BLCW_SOLDIER_HIGH_FD_DAMAGE_SMALL",
	SMALL_DAMAGE_LAND_BACK		= "LOW_BLCW_SOLDIER_HIGH_FD_DAMAGE_SMALL",
	BIG_DAMAGE_LAND_FRONT		= "LOW_BLCW_SOLDIER_HIGH_FD_DAMAGE_BIG",
	BIG_DAMAGE_LAND_BACK		= "LOW_BLCW_SOLDIER_HIGH_FD_DAMAGE_BIG",
	DOWN_DAMAGE_LAND_FRONT		= "LOW_BLCW_SOLDIER_HIGH_FD_DAMAGE_DOWN_FRONT",
	DOWN_DAMAGE_LAND_BACK		= "LOW_BLCW_SOLDIER_HIGH_FD_DAMAGE_DOWN_BACK",
	FLY_DAMAGE_FRONT			= "LOW_BLCW_SOLDIER_HIGH_FD_DAMAGE_FLY_FRONT",
	FLY_DAMAGE_BACK				= "LOW_BLCW_SOLDIER_HIGH_FD_DAMAGE_FLY_BACK",
	SMALL_DAMAGE_AIR			= "LOW_BLCW_SOLDIER_HIGH_FD_DAMAGE_AIR",	
	BIG_DAMAGE_AIR				= "LOW_BLCW_SOLDIER_HIGH_FD_DAMAGE_AIR",
	DOWN_DAMAGE_AIR				= "LOW_BLCW_SOLDIER_HIGH_FD_DAMAGE_AIR_DOWN",
	DOWN_DAMAGE_AIR_LANDING				= "LOW_BLCW_SOLDIER_HIGH_FD_DAMAGE_AIR_DOWN_LANDING",
	UP_DAMAGE					= "LOW_BLCW_SOLDIER_HIGH_FD_DAMAGE_AIR_UP",
	DAMAGE_REVENGE				= "LOW_BLCW_SOLDIER_HIGH_FD_DAMAGE_REVENGE",
	
	DAMAGE_EXTRA_STATES         = { "LOW_BLCW_SOLDIER_HIGH_FD_DAMAGE_AIR_FALL", "LOW_BLCW_SOLDIER_HIGH_FD_STAND_UP_FRONT", "LOW_BLCW_SOLDIER_HIGH_FD_STAND_UP_BACK", 
	"LOW_BLCW_SOLDIER_HIGH_FD_STAND_UP_ATTACK_FRONT","LOW_BLCW_SOLDIER_HIGH_FD_STAND_UP_ATTACK_BACK","LOW_BLCW_SOLDIER_HIGH_FD_JUMP_DOWN","LOW_BLCW_SOLDIER_HIGH_FD_JUMP_LANDING", },
	
	
	DYING_LAND_FRONT			= "LOW_BLCW_SOLDIER_HIGH_FD_DYING_LAND_FRONT",
	DYING_LAND_BACK				= "LOW_BLCW_SOLDIER_HIGH_FD_DYING_LAND_BACK",
	DYING_SKY					= "LOW_BLCW_SOLDIER_HIGH_FD_DYING_SKY",

	REVENGE_ATTACK				= "",	
}

INIT_AI = 
{
	TARGET = 
	{
		TARGET_PRIORITY 			= TARGET_PRIORITY["TP_RANDOM"],
		TARGET_INTERVAL				= 1,		-- sec
		TARGET_NEAR_RANGE			= 500,		-- 이 거리보다 가까우면 TARGET_SUCCESS_RATE에 관계없이 무조건 타게팅된다
		TARGET_RANGE				= 600,		-- cm
		TARGET_LOST_RANGE			= 800,		-- cm
		TARGET_SUCCESS_RATE			= 100,  --90,		-- %
		ATTACK_TARGET_RATE			= 100, -- 90,		-- 나를 공격한 유닛을 타게팅할 확률
		PRESERVE_LAST_TARGET_RATE	= 100, -- 60,		-- 이전에 타게팅된 유닛을 계속 타게팅할 확률
	},

	CHASE_MOVE = 
	{		
		DEST_GAP			= 150,	-- 목적지에서 이 거리 안에 있으면 도착했다고 판단한다
		MOVE_GAP			= 160,
		
		DIR_CHANGE_INTERVAL = 0.7,
		
		MOVE_SPLIT_RANGE	= 600,
		WALK_INTERVAL		= 2,
		NEAR_WALK_RATE		= 100,   --  30,
		FAR_WALK_RATE		= 100,   -- 70, 
		JUMP_INTERVAL		= 5,
		UP_JUMP_RATE		= 0, -- 40,
		UP_DOWN_RATE		= 0,
		DOWN_JUMP_RATE		= 0,    --  20,
		DOWN_DOWN_RATE		= 0,
	},	
	
	PATROL_MOVE = 	
	{
		PATROL_BEGIN_RATE		= 50, --50,		
		PATROL_RANGE			= 200,
		PATROL_COOL_TIME		= 1.5,
		ONLY_THIS_LINE_GROUP	= TRUE,
	},
	
	ESCAPE_MOVE = 
	{		
		MOVE_SPLIT_RANGE	= 500,	-- cm
		ESCAPE_GAP			= 10,	-- 이 거리 보다 멀어지면 도망 성공
		
		WALK_INTERVAL		= 1,	-- 초
		NEAR_WALK_RATE		= 100,   --  10,
		FAR_WALK_RATE		= 100,   -- 10,
		
		JUMP_INTERVAL		= 10,
		UP_JUMP_RATE		= 100, -- 30,
		UP_DOWN_RATE		= 30,
		DOWN_JUMP_RATE		= 100,    --  30,
		DOWN_DOWN_RATE		= 30,
	},
	
	
}

LOW_BLCW_SOLDIER_HIGH_FD_START = 
{
	ANIM_NAME					= "WaitZero",
	PLAY_TYPE					= XSKIN_ANIM_PLAYTYPE["XAP_ONE_WAIT"],
	TRANSITION					= TRUE,
	
	CAN_PUSH_UNIT				= TRUE,
	CAN_PASS_UNIT				= FALSE,	


        SOUND_PLAY0			= { 0.485, "Airship_High_WaitZero1.ogg" },
        SOUND_PLAY1			= { 2.252, "Airship_High_WaitZero2.ogg" },
	
	
	SPEED_X						= 0,
	SPEED_Y						= 0,
	
	
	EVENT_PROCESS = 
	{		
		{ STATE_CHANGE_TYPE["SCT_CONDITION_TABLE"],		"LOW_BLCW_SOLDIER_HIGH_FD_WAIT",				"CT_LOW_BLCW_SOLDIER_HIGH_FD_WAIT"				},
	},
	
	CT_LOW_BLCW_SOLDIER_HIGH_FD_WAIT = 
	{
		STATE_TIME_OVER				= 4,
	},
	
}

LOW_BLCW_SOLDIER_HIGH_FD_WIN = 
{
	ANIM_NAME					= "Win",
	PLAY_TYPE					= XSKIN_ANIM_PLAYTYPE["XAP_ONE_WAIT"],
	TRANSITION					= TRUE,
	
	CAN_PUSH_UNIT				= TRUE,
	CAN_PASS_UNIT				= FALSE,	
	
	INVINCIBLE					= { 0, 100, },

        SOUND_PLAY0			= { 0.617, "Airship_High_Slash1.ogg" },
	
	SPEED_X						= 0,
	SPEED_Y						= 0,
	
	RIGHT						= TRUE,
	
	IMMADIATE_PACKET_SEND		= TRUE,
}

LOW_BLCW_SOLDIER_HIGH_FD_WAIT = 
{
	ANIM_NAME					= "Wait",
	PLAY_TYPE					= XSKIN_ANIM_PLAYTYPE["XAP_LOOP"],
	TRANSITION					= TRUE,
	LAND_CONNECT				= TRUE,
	
	CAN_PUSH_UNIT				= TRUE,
	CAN_PASS_UNIT				= FALSE,	
	
	SPEED_X						= 0,
	SPEED_Y						= 0,
	
	IMMADIATE_PACKET_SEND		= TRUE,
	EVENT_INTERVAL_TIME0		= 1,
	
	EVENT_PROCESS = 
	{	
		{ STATE_CHANGE_TYPE["SCT_CONDITION_FUNCTION"],		"LOW_BLCW_SOLDIER_HIGH_FD_WIN",							"CF_LOW_BLCW_SOLDIER_HIGH_FD_WIN",	},
		{ STATE_CHANGE_TYPE["SCT_FOOT_ON_LINE_FALSE_DOWN"],	"LOW_BLCW_SOLDIER_HIGH_FD_JUMP_DOWN",					},

		{ STATE_CHANGE_TYPE["SCT_CONDITION_TABLE"],			"LOW_BLCW_SOLDIER_HIGH_FD_DASH_ATTACK",					"CT_LOW_BLCW_SOLDIER_HIGH_FD_DASH_ATTACK",		},
		
		{ STATE_CHANGE_TYPE["SCT_AI_WALK"],					"LOW_BLCW_SOLDIER_HIGH_FD_WALK",							},
		{ STATE_CHANGE_TYPE["SCT_AI_DASH"],					"LOW_BLCW_SOLDIER_HIGH_FD_DASH",							},
		{ STATE_CHANGE_TYPE["SCT_AI_JUMP"],					"LOW_BLCW_SOLDIER_HIGH_FD_JUMP_UP",						},
		{ STATE_CHANGE_TYPE["SCT_AI_JUMP_DIR"],				"LOW_BLCW_SOLDIER_HIGH_FD_JUMP_UP_DIR",					},
		{ STATE_CHANGE_TYPE["SCT_AI_DOWN"],					"LOW_BLCW_SOLDIER_HIGH_FD_JUMP_DOWN",					},
		{ STATE_CHANGE_TYPE["SCT_AI_DOWN_DIR"],				"LOW_BLCW_SOLDIER_HIGH_FD_JUMP_DOWN_DIR",				},
	},	

	CT_LOW_BLCW_SOLDIER_HIGH_FD_DASH_ATTACK =
	{
		EVENT_INTERVAL_ID			= 0,
		DISTANCE_TO_TARGET_NEAR		= 500,
		RATE						= 100,
	},
}

LOW_BLCW_SOLDIER_HIGH_FD_WAIT2 = 
{
	ANIM_NAME					= "WaitZero",
	PLAY_TYPE					= XSKIN_ANIM_PLAYTYPE["XAP_ONE_WAIT"],
	TRANSITION					= FALSE,
	
	CAN_PUSH_UNIT				= TRUE,
	CAN_PASS_UNIT				= FALSE,
	IMMADIATE_PACKET_SEND		= TRUE,	

        SOUND_PLAY0			= { 0.485, "Airship_High_WaitZero1.ogg" },
        SOUND_PLAY1			= { 2.252, "Airship_High_WaitZero2.ogg" },

	
	EVENT_PROCESS = 
	{		
		{ STATE_CHANGE_TYPE["SCT_CONDITION_FUNCTION"],		"LOW_BLCW_SOLDIER_HIGH_FD_WIN",							"CF_LOW_BLCW_SOLDIER_HIGH_FD_WIN",	},
		{ STATE_CHANGE_TYPE["SCT_FOOT_ON_LINE_FALSE_DOWN"],	"LOW_BLCW_SOLDIER_HIGH_FD_JUMP_DOWN",					},
		{ STATE_CHANGE_TYPE["SCT_MOTION_END"],				"LOW_BLCW_SOLDIER_HIGH_FD_WAIT",						},
	},
}

LOW_BLCW_SOLDIER_HIGH_FD_WAIT3 =
{
	ANIM_NAME					= "WaitHabit",
	PLAY_TYPE					= XSKIN_ANIM_PLAYTYPE["XAP_ONE_WAIT"],
	TRANSITION					= TRUE,
	
	CAN_PUSH_UNIT				= TRUE,
	CAN_PASS_UNIT				= FALSE,
	IMMADIATE_PACKET_SEND		= TRUE,
	
	EVENT_PROCESS = 
	{		
		{ STATE_CHANGE_TYPE["SCT_CONDITION_FUNCTION"],		"LOW_BLCW_SOLDIER_HIGH_FD_WIN",							"CF_LOW_BLCW_SOLDIER_HIGH_FD_WIN",	},
		{ STATE_CHANGE_TYPE["SCT_FOOT_ON_LINE_FALSE_DOWN"],	"LOW_BLCW_SOLDIER_HIGH_FD_JUMP_DOWN",					},
		{ STATE_CHANGE_TYPE["SCT_MOTION_END"],				"LOW_BLCW_SOLDIER_HIGH_FD_WAIT",						},
	},
}

LOW_BLCW_SOLDIER_HIGH_FD_WALK = 
{
	ANIM_SPEED					= 0.6,
	ANIM_NAME					= "Walk",
	PLAY_TYPE					= XSKIN_ANIM_PLAYTYPE["XAP_LOOP"],
	TRANSITION					= TRUE,
	LAND_CONNECT				= TRUE,
	
	CAN_PUSH_UNIT				= TRUE,
	CAN_PASS_UNIT				= FALSE,
	
	PASSIVE_SPEED_X				= 110,
	
	ALLOW_DIR_CHANGE			= TRUE,
	IMMADIATE_PACKET_SEND		= TRUE,
	
	EVENT_INTERVAL_TIME0		= 1,
	EVENT_INTERVAL_TIME1		= 3,
	
	EVENT_PROCESS = 
	{		
		{ STATE_CHANGE_TYPE["SCT_CONDITION_FUNCTION"],		"LOW_BLCW_SOLDIER_HIGH_FD_WIN",							"CF_LOW_BLCW_SOLDIER_HIGH_FD_WIN",	},
		{ STATE_CHANGE_TYPE["SCT_FOOT_ON_LINE_FALSE_DOWN"],	"LOW_BLCW_SOLDIER_HIGH_FD_JUMP_DOWN_DIR",				},

		{ STATE_CHANGE_TYPE["SCT_CONDITION_TABLE"],			"LOW_BLCW_SOLDIER_HIGH_FD_DASH_ATTACK",					"CT_LOW_BLCW_SOLDIER_HIGH_FD_DASH_ATTACK",		},
		
		{ STATE_CHANGE_TYPE["SCT_AI_WAIT"],					"LOW_BLCW_SOLDIER_HIGH_FD_WAIT",							},
		{ STATE_CHANGE_TYPE["SCT_AI_DASH"],					"LOW_BLCW_SOLDIER_HIGH_FD_DASH",							},
		{ STATE_CHANGE_TYPE["SCT_AI_JUMP"],					"LOW_BLCW_SOLDIER_HIGH_FD_JUMP_UP",						},
		{ STATE_CHANGE_TYPE["SCT_AI_JUMP_DIR"],				"LOW_BLCW_SOLDIER_HIGH_FD_JUMP_UP_DIR",					},
		{ STATE_CHANGE_TYPE["SCT_AI_DOWN"],					"LOW_BLCW_SOLDIER_HIGH_FD_JUMP_DOWN",					},
		{ STATE_CHANGE_TYPE["SCT_AI_DOWN_DIR"],				"LOW_BLCW_SOLDIER_HIGH_FD_JUMP_DOWN_DIR",				},
	},
	
	CT_LOW_BLCW_SOLDIER_HIGH_FD_DASH_ATTACK =
	{
		EVENT_INTERVAL_ID			= 0,
		DISTANCE_TO_TARGET_NEAR		= 500,
		RATE						= 100,
	},
}


LOW_BLCW_SOLDIER_HIGH_FD_JUMP_UP = 
{
	ANIM_NAME					= "JumpUp",
	PLAY_TYPE					= XSKIN_ANIM_PLAYTYPE["XAP_LOOP"],
	TRANSITION					= TRUE,
	LAND_CONNECT				= FALSE,
	
	CAN_PUSH_UNIT				= TRUE,
	CAN_PASS_UNIT				= FALSE,
	
	SPEED_X						= 0,
	SPEED_Y						= INIT_PHYSIC["JUMP_SPEED"],
	ADD_POS_Y					= 45,
	
	IMMADIATE_PACKET_SEND		= TRUE,
	
	EVENT_PROCESS = 
	{		
		{ STATE_CHANGE_TYPE["SCT_NEGATIVE_Y_SPEED"],		"LOW_BLCW_SOLDIER_HIGH_FD_JUMP_DOWN",				},
	},
}

LOW_BLCW_SOLDIER_HIGH_FD_JUMP_DOWN = 
{
	ANIM_NAME					= "JumpDown",
	PLAY_TYPE					= XSKIN_ANIM_PLAYTYPE["XAP_LOOP"],
	TRANSITION					= TRUE,
	LAND_CONNECT				= FALSE,
	
	CAN_PUSH_UNIT				= TRUE,
	CAN_PASS_UNIT				= FALSE,
	
	
	IMMADIATE_PACKET_SEND		= TRUE,
		
	EVENT_PROCESS = 
	{		
		{ STATE_CHANGE_TYPE["SCT_FOOT_ON_LINE_TRUE"],		"LOW_BLCW_SOLDIER_HIGH_FD_JUMP_LANDING",				},
	},
}

LOW_BLCW_SOLDIER_HIGH_FD_JUMP_UP_DIR =
{
	ANIM_NAME					= "JumpUp",
	PLAY_TYPE					= XSKIN_ANIM_PLAYTYPE["XAP_LOOP"],
	TRANSITION					= TRUE,
	LAND_CONNECT				= FALSE,
	
	CAN_PUSH_UNIT				= TRUE,
	CAN_PASS_UNIT				= FALSE,
	
	PASSIVE_SPEED_X				= INIT_PHYSIC["WALK_SPEED"],
	SPEED_Y						= INIT_PHYSIC["JUMP_SPEED"],
	ADD_POS_Y					= 45,
	
	IMMADIATE_PACKET_SEND		= TRUE,
	
	EVENT_PROCESS = 
	{		
		{ STATE_CHANGE_TYPE["SCT_NEGATIVE_Y_SPEED"],		"LOW_BLCW_SOLDIER_HIGH_FD_JUMP_DOWN_DIR",				},
	},
}

LOW_BLCW_SOLDIER_HIGH_FD_JUMP_DOWN_DIR =
{
	ANIM_NAME					= "JumpDown",
	PLAY_TYPE					= XSKIN_ANIM_PLAYTYPE["XAP_LOOP"],
	TRANSITION					= TRUE,
	LAND_CONNECT				= FALSE,
	
	CAN_PUSH_UNIT				= TRUE,
	CAN_PASS_UNIT				= FALSE,
	
	PASSIVE_SPEED_X				= INIT_PHYSIC["WALK_SPEED"],
	
	
	IMMADIATE_PACKET_SEND		= TRUE,
		
	EVENT_PROCESS = 
	{		
		{ STATE_CHANGE_TYPE["SCT_FOOT_ON_LINE_TRUE"],		"LOW_BLCW_SOLDIER_HIGH_FD_JUMP_LANDING",				},
	},
}

LOW_BLCW_SOLDIER_HIGH_FD_JUMP_LANDING = 
{
	ANIM_NAME					= "JumpLanding",
	PLAY_TYPE					= XSKIN_ANIM_PLAYTYPE["XAP_ONE_WAIT"],
	TRANSITION					= TRUE,
	LAND_CONNECT				= FALSE,
	
	CAN_PUSH_UNIT				= TRUE,
	CAN_PASS_UNIT				= FALSE,
	
	SPEED_X						= 500,
	SPEED_Y						= 0,
		
	IMMADIATE_PACKET_SEND		= TRUE,

	EVENT_PROCESS = 
	{		
		{ STATE_CHANGE_TYPE["SCT_FOOT_ON_LINE_FALSE_DOWN"],	"LOW_BLCW_SOLDIER_HIGH_FD_JUMP_DOWN",				},
		{ STATE_CHANGE_TYPE["SCT_MOTION_END"],				"LOW_BLCW_SOLDIER_HIGH_FD_WAIT",					},
	},
}

LOW_BLCW_SOLDIER_HIGH_FD_DASH =
{
	ANIM_SPEED					= 0.7,
	ANIM_NAME					= "Dash",
	PLAY_TYPE					= XSKIN_ANIM_PLAYTYPE["XAP_LOOP"],
	TRANSITION					= TRUE,
	
	CAN_PUSH_UNIT				= TRUE,
	CAN_PASS_UNIT				= FALSE,
	
	PASSIVE_SPEED_X				= 300,
	
	ALLOW_DIR_CHANGE			= TRUE,
	IMMADIATE_PACKET_SEND		= TRUE,
	
	EVENT_INTERVAL_TIME0		= 1,
	
	EVENT_PROCESS = 
	{		
		{ STATE_CHANGE_TYPE["SCT_CONDITION_FUNCTION"],		"LOW_BLCW_SOLDIER_HIGH_FD_WIN",							"CF_LOW_BLCW_SOLDIER_HIGH_FD_WIN",	},
		{ STATE_CHANGE_TYPE["SCT_FOOT_ON_LINE_FALSE_DOWN"],	"LOW_BLCW_SOLDIER_HIGH_FD_JUMP_DOWN_DIR",				},
		
		{ STATE_CHANGE_TYPE["SCT_CONDITION_TABLE"],			"LOW_BLCW_SOLDIER_HIGH_FD_DASH_ATTACK",					"CT_LOW_BLCW_SOLDIER_HIGH_FD_DASH_ATTACK",		},
			
		{ STATE_CHANGE_TYPE["SCT_AI_WAIT"],					"LOW_BLCW_SOLDIER_HIGH_FD_DASH_END",							},
		{ STATE_CHANGE_TYPE["SCT_AI_WALK"],					"LOW_BLCW_SOLDIER_HIGH_FD_WALK",							},
		{ STATE_CHANGE_TYPE["SCT_AI_JUMP"],					"LOW_BLCW_SOLDIER_HIGH_FD_JUMP_UP",						},
		{ STATE_CHANGE_TYPE["SCT_AI_JUMP_DIR"],				"LOW_BLCW_SOLDIER_HIGH_FD_JUMP_UP_DIR",					},
		{ STATE_CHANGE_TYPE["SCT_AI_DOWN"],					"LOW_BLCW_SOLDIER_HIGH_FD_JUMP_DOWN",					},
		{ STATE_CHANGE_TYPE["SCT_AI_DOWN_DIR"],				"LOW_BLCW_SOLDIER_HIGH_FD_JUMP_DOWN_DIR",				},
	},
	
	CT_LOW_BLCW_SOLDIER_HIGH_FD_DASH_ATTACK =
	{
		EVENT_INTERVAL_ID			= 0,
		DISTANCE_TO_TARGET_NEAR		= 500,
		RATE						= 100,
	},
}

LOW_BLCW_SOLDIER_HIGH_FD_DASH_END = 
{
	ANIM_NAME					= "DashEnd",
	PLAY_TYPE					= XSKIN_ANIM_PLAYTYPE["XAP_ONE_WAIT"],
	TRANSITION					= TRUE,
	
	CAN_PUSH_UNIT				= TRUE,
	CAN_PASS_UNIT				= FALSE,
	
	PASSIVE_SPEED_X				= 0,
	
	ALLOW_DIR_CHANGE			= TRUE,
	IMMADIATE_PACKET_SEND		= TRUE,
	
	EVENT_PROCESS = 
	{		
		{ STATE_CHANGE_TYPE["SCT_FOOT_ON_LINE_FALSE_DOWN"],	"LOW_BLCW_SOLDIER_HIGH_FD_JUMP_DOWN_DIR",				},
		
		{ STATE_CHANGE_TYPE["SCT_MOTION_END"],				"LOW_BLCW_SOLDIER_HIGH_FD_WAIT",							},
			
		{ STATE_CHANGE_TYPE["SCT_AI_WAIT"],					"LOW_BLCW_SOLDIER_HIGH_FD_WAIT",							},
		{ STATE_CHANGE_TYPE["SCT_AI_WALK"],					"LOW_BLCW_SOLDIER_HIGH_FD_WALK",							},
		{ STATE_CHANGE_TYPE["SCT_AI_JUMP"],					"LOW_BLCW_SOLDIER_HIGH_FD_JUMP_UP",						},
		{ STATE_CHANGE_TYPE["SCT_AI_JUMP_DIR"],				"LOW_BLCW_SOLDIER_HIGH_FD_JUMP_UP_DIR",					},
		{ STATE_CHANGE_TYPE["SCT_AI_DOWN"],					"LOW_BLCW_SOLDIER_HIGH_FD_JUMP_DOWN",					},
		{ STATE_CHANGE_TYPE["SCT_AI_DOWN_DIR"],				"LOW_BLCW_SOLDIER_HIGH_FD_JUMP_DOWN_DIR",				},
	},
}


LOW_BLCW_SOLDIER_HIGH_FD_DEFENCE =
{
	ANIM_NAME					= "Defence",
	PLAY_TYPE					= XSKIN_ANIM_PLAYTYPE["XAP_ONE_WAIT"],
	TRANSITION					= FALSE,
	LAND_CONNECT				= FALSE,
	
	CAN_PUSH_UNIT				= TRUE,
	CAN_PASS_UNIT				= FALSE,

	SUPER_ARMOR					= TRUE,
	DEFENCE						= { 0, 100, 70, }, 
	
	EVENT_PROCESS = 
	{
		{ STATE_CHANGE_TYPE["SCT_CONDITION_TABLE"],		"LOW_BLCW_SOLDIER_HIGH_FD_WAIT",				"CT_WAIT"		},
	},
	
	CT_WAIT = 
	{
		STATE_TIME_OVER			= 2,
	},
}


LOW_BLCW_SOLDIER_HIGH_FD_COMBO1 = 
{
	ANIM_NAME					= "Combo1",
	PLAY_TYPE					= XSKIN_ANIM_PLAYTYPE["XAP_ONE_WAIT"],
	TRANSITION					= FALSE,
	LAND_CONNECT				= FALSE,
	
	CAN_PUSH_UNIT				= TRUE,
	CAN_PASS_UNIT				= FALSE,
	
	SPEED_X						= 0,
	SPEED_Y						= 0,	

    SOUND_PLAY0			= { 0.808, "Airship_High_Kick.ogg" },
	
	VIEW_TARGET					= TRUE,

	
	IMMADIATE_PACKET_SEND		= TRUE,
	
	DISABLE_ATTACK_BOX = 
	{
		"Benders",
		"Rfoot",
	},	
	
	EVENT_PROCESS = 
	{	
		{ STATE_CHANGE_TYPE["SCT_FOOT_ON_LINE_FALSE_DOWN"],	"LOW_BLCW_SOLDIER_HIGH_FD_JUMP_DOWN",							},
		{ STATE_CHANGE_TYPE["SCT_MOTION_END"],				"LOW_BLCW_SOLDIER_HIGH_FD_WAIT",							},	
		{ STATE_CHANGE_TYPE["SCT_CONDITION_TABLE"],			"LOW_BLCW_SOLDIER_HIGH_FD_COMBO2",		"CT_LOW_BLCW_SOLDIER_HIGH_FD_COMBO2",	},
	},
	
	CT_LOW_BLCW_SOLDIER_HIGH_FD_COMBO2 =
	{
		ANIM_EVENT_TIMER	= 0.96,
		RATE				= 50,
	},

    SLASH_TRACE					= { 0.7, 1.03 },
	ATTACK_TIME0				= { 0.79, 1.03, },
	
	DAMAGE_DATA = 
	{
		DAMAGE_TYPE		= DAMAGE_TYPE["DT_PHYSIC"],
		HIT_TYPE		= HIT_TYPE["HT_KICK_HIT"],
		REACT_TYPE		= REACT_TYPE["RT_SMALL_DAMAGE"],
		
		DAMAGE = 
		{
			PHYSIC		= 0.5,
		},
		
		BACK_SPEED_X			= INIT_PHYSIC["RUN_SPEED"],
		BACK_SPEED_Y			= 0.0,
		
		CAMERA_CRASH_GAP		= 5.0,	
		CAMERA_CRASH_TIME		= 0.2,		
	},
}

LOW_BLCW_SOLDIER_HIGH_FD_COMBO2 =
{
	ANIM_NAME					= "Combo2",
	PLAY_TYPE					= XSKIN_ANIM_PLAYTYPE["XAP_ONE_WAIT"],
	TRANSITION					= FALSE,
	LAND_CONNECT				= FALSE,
	
	CAN_PUSH_UNIT				= TRUE,
	CAN_PASS_UNIT				= FALSE,

        SOUND_PLAY0			= { 0.681, "Airship_High_Slash1.ogg" },
	
	SPEED_X						= 0,
	SPEED_Y						= 0,	
	
	VIEW_TARGET					= TRUE,

	
	IMMADIATE_PACKET_SEND		= TRUE,
	
		
	DISABLE_ATTACK_BOX = 
	{
		"Lfoot",
		"Rfoot",
	},	

		
	EVENT_PROCESS = 
	{		
		{ STATE_CHANGE_TYPE["SCT_FOOT_ON_LINE_FALSE_DOWN"],	"LOW_BLCW_SOLDIER_HIGH_FD_JUMP_DOWN",			},
		{ STATE_CHANGE_TYPE["SCT_MOTION_END"],				"LOW_BLCW_SOLDIER_HIGH_FD_WAIT",					},
	},
	
	SLASH_TRACE					= { 0, 0.83 },
	ATTACK_TIME0				= { 0.67, 0.83, },
	
	DAMAGE_DATA = 
	{
		DAMAGE_TYPE		= DAMAGE_TYPE["DT_PHYSIC"],
		HIT_TYPE		= HIT_TYPE["HT_SWORD_SLASH"],
		REACT_TYPE		= REACT_TYPE["RT_DOWN"],
		
		DAMAGE = 
		{
			PHYSIC		= 1.0,
		},
		
		BACK_SPEED_X			= INIT_PHYSIC["WALK_SPEED"],
		BACK_SPEED_Y			= 0.0,
		
		CAMERA_CRASH_GAP		= 5.0,	
		CAMERA_CRASH_TIME		= 0.2,		
	},
}

LOW_BLCW_SOLDIER_HIGH_FD_DASH_ATTACK =
{
	ANIM_NAME					= "DashAttack",
	PLAY_TYPE					= XSKIN_ANIM_PLAYTYPE["XAP_ONE_WAIT"],
	TRANSITION					= FALSE,
	LAND_CONNECT				= FALSE,
	
	CAN_PUSH_UNIT				= TRUE,
	CAN_PASS_UNIT				= FALSE,

        SOUND_PLAY0			= { 0.864, "Airship_High_Slash2.ogg" },
	
	SPEED_X						= 0,
	SPEED_Y						= 0,	
	
	VIEW_TARGET					= TRUE,

	
	IMMADIATE_PACKET_SEND		= TRUE,
	
	DISABLE_ATTACK_BOX = 
	{
		"Lfoot",
		"Rfoot",
	},
		
	EVENT_PROCESS = 
	{		
		{ STATE_CHANGE_TYPE["SCT_FOOT_ON_LINE_FALSE_DOWN"],	"LOW_BLCW_SOLDIER_HIGH_FD_JUMP_DOWN",				},
		{ STATE_CHANGE_TYPE["SCT_MOTION_END"],				"LOW_BLCW_SOLDIER_HIGH_FD_WAIT",						},
	},
	
	SLASH_TRACE					= { 0.0, 1.0 },	
	ATTACK_TIME0				= { 0.8, 0.9, },
	
	DAMAGE_DATA = 
	{
		DAMAGE_TYPE		= DAMAGE_TYPE["DT_PHYSIC"],
		HIT_TYPE		= HIT_TYPE["HT_SWORD_SLASH"],
		REACT_TYPE		= REACT_TYPE["RT_BIG_DAMAGE"],
		
		DAMAGE = 
		{
			PHYSIC		= 1.1,
		},
		
		BACK_SPEED_X			= INIT_PHYSIC["RUN_SPEED"],
		BACK_SPEED_Y			= 0.0,
		
		CAMERA_CRASH_GAP		= 5.0,	
		CAMERA_CRASH_TIME		= 0.2,		
	},
}


LOW_BLCW_SOLDIER_HIGH_FD_JUMP_ATTACK =
{
	ANIM_NAME					= "JumpAttack",
	PLAY_TYPE					= XSKIN_ANIM_PLAYTYPE["XAP_ONE_WAIT"],
	TRANSITION					= FALSE,
	LAND_CONNECT				= FALSE,
	
	CAN_PUSH_UNIT				= TRUE,
	CAN_PASS_UNIT				= FALSE,

        SOUND_PLAY0			= { 0.238, "Airship_High_Slash1.ogg" },
	
	IMMADIATE_PACKET_SEND		= TRUE,
	
	DISABLE_ATTACK_BOX = 
	{
		"Lfoot",
		"Rfoot",
	},
	

	
	EVENT_PROCESS = 
	{		
		{ STATE_CHANGE_TYPE["SCT_FOOT_ON_LINE_TRUE"],		"LOW_BLCW_SOLDIER_HIGH_FD_JUMP_LANDING",			},
	},
	
	SLASH_TRACE					= { 0.28, 100 },
	ATTACK_TIME0				= { 0.28, 100, },
	
	DAMAGE_DATA = 
	{
		DAMAGE_TYPE		= DAMAGE_TYPE["DT_PHYSIC"],
		HIT_TYPE		= HIT_TYPE["HT_SWORD_SLASH"],
		REACT_TYPE		= REACT_TYPE["RT_SMALL_DAMAGE"],
		
		DAMAGE = 
		{
			PHYSIC		= 1.0,
		},
		
		BACK_SPEED_X			= INIT_PHYSIC["WALK_SPEED"],
		BACK_SPEED_Y			= 0.0,
		
		CAMERA_CRASH_GAP		= 5.0,	
		CAMERA_CRASH_TIME		= 0.2,		
	},
}

LOW_BLCW_SOLDIER_HIGH_FD_JUMP_FOR_ATTACK =
{
	ANIM_NAME					= "JumpUp",
	PLAY_TYPE					= XSKIN_ANIM_PLAYTYPE["XAP_LOOP"],
	TRANSITION					= TRUE,
	LAND_CONNECT				= FALSE,
	
	CAN_PUSH_UNIT				= TRUE,
	CAN_PASS_UNIT				= FALSE,
	
	PASSIVE_SPEED_X				= INIT_PHYSIC["WALK_SPEED"],
	SPEED_Y						= INIT_PHYSIC["JUMP_SPEED"],
	
	VIEW_TARGET					= TRUE,
	IMMADIATE_PACKET_SEND		= TRUE,
	
	EVENT_PROCESS = 
	{		
		{ STATE_CHANGE_TYPE["SCT_NEGATIVE_Y_SPEED"],			"LOW_BLCW_SOLDIER_HIGH_FD_JUMP_ATTACK",		},
	},
}

LOW_BLCW_SOLDIER_HIGH_FD_DAMAGE_SMALL =
{
	ANIM_NAME					= "DamageSmall",
	PLAY_TYPE					= XSKIN_ANIM_PLAYTYPE["XAP_ONE_WAIT"],
	TRANSITION					= FALSE,
	LAND_CONNECT				= FALSE,
	
	CAN_PUSH_UNIT				= TRUE,
	CAN_PASS_UNIT				= FALSE,
	
	EVENT_PROCESS = 
	{
		{ STATE_CHANGE_TYPE["SCT_MOTION_END"],					"LOW_BLCW_SOLDIER_HIGH_FD_WAIT",												},
	},
}


LOW_BLCW_SOLDIER_HIGH_FD_DAMAGE_BIG = 
{
	ANIM_NAME					= "DamageBig",
	PLAY_TYPE					= XSKIN_ANIM_PLAYTYPE["XAP_ONE_WAIT"],
	TRANSITION					= FALSE,
	LAND_CONNECT				= FALSE,
	
	CAN_PUSH_UNIT				= TRUE,
	CAN_PASS_UNIT				= FALSE,
	
	EVENT_PROCESS = 
	{
		{ STATE_CHANGE_TYPE["SCT_MOTION_END"],					"LOW_BLCW_SOLDIER_HIGH_FD_WAIT",												},
	},	
}

LOW_BLCW_SOLDIER_HIGH_FD_DAMAGE_DOWN_FRONT = 
{
	ANIM_NAME					= "DamageDownFront",
	PLAY_TYPE					= XSKIN_ANIM_PLAYTYPE["XAP_ONE_WAIT"],
	TRANSITION					= FALSE,
	LAND_CONNECT				= FALSE,

	SUPER_ARMOR					= TRUE,
	DEFENCE						= { 0, 100, 50, },
	
	CAN_PUSH_UNIT				= TRUE,
	CAN_PASS_UNIT				= FALSE,
	
	EVENT_PROCESS = 
	{
		{ STATE_CHANGE_TYPE["SCT_FOOT_ON_LINE_FALSE_DOWN"],		"LOW_BLCW_SOLDIER_HIGH_FD_DAMAGE_AIR_FALL",			},
		{ STATE_CHANGE_TYPE["SCT_MOTION_END"],					"LOW_BLCW_SOLDIER_HIGH_FD_STAND_UP_FRONT",			},
	},
}

LOW_BLCW_SOLDIER_HIGH_FD_DAMAGE_DOWN_BACK = 
{
	ANIM_NAME					= "DamageDownBack",
	PLAY_TYPE					= XSKIN_ANIM_PLAYTYPE["XAP_ONE_WAIT"],
	TRANSITION					= FALSE,
	LAND_CONNECT				= FALSE,
	
	SUPER_ARMOR					= TRUE,
	DEFENCE						= { 0, 100, 50, },
	
	CAN_PUSH_UNIT				= TRUE,
	CAN_PASS_UNIT				= FALSE,
	
	EVENT_PROCESS = 
	{
		{ STATE_CHANGE_TYPE["SCT_FOOT_ON_LINE_FALSE_DOWN"],		"LOW_BLCW_SOLDIER_HIGH_FD_DAMAGE_AIR_FALL",			},
		{ STATE_CHANGE_TYPE["SCT_MOTION_END"],					"LOW_BLCW_SOLDIER_HIGH_FD_STAND_UP_BACK",			},
	},
}

LOW_BLCW_SOLDIER_HIGH_FD_DAMAGE_FLY_FRONT = 
{
	ANIM_NAME					= "DamageAirFlyFront",
	PLAY_TYPE					= XSKIN_ANIM_PLAYTYPE["XAP_ONE_WAIT"],
	TRANSITION					= FALSE,
	LAND_CONNECT				= FALSE,	
	
	CAN_PUSH_UNIT				= TRUE,
	CAN_PASS_UNIT				= FALSE,
	
	EVENT_PROCESS = 
	{
		{ STATE_CHANGE_TYPE["SCT_FOOT_ON_LINE_TRUE"],			"LOW_BLCW_SOLDIER_HIGH_FD_DAMAGE_DOWN_FRONT",		},
	},
}

LOW_BLCW_SOLDIER_HIGH_FD_DAMAGE_FLY_BACK = 
{
	ANIM_NAME					= "DamageAirFlyBack",
	PLAY_TYPE					= XSKIN_ANIM_PLAYTYPE["XAP_ONE_WAIT"],
	TRANSITION					= FALSE,
	LAND_CONNECT				= FALSE,	
	
	CAN_PUSH_UNIT				= TRUE,
	CAN_PASS_UNIT				= FALSE,
	
	EVENT_PROCESS = 
	{
		{ STATE_CHANGE_TYPE["SCT_FOOT_ON_LINE_TRUE"],			"LOW_BLCW_SOLDIER_HIGH_FD_DAMAGE_DOWN_BACK",		},
	},
}

LOW_BLCW_SOLDIER_HIGH_FD_DAMAGE_AIR = 
{
	ANIM_NAME					= "DamageAirSmall",
	PLAY_TYPE					= XSKIN_ANIM_PLAYTYPE["XAP_ONE_WAIT"],
	TRANSITION					= FALSE,
	LAND_CONNECT				= FALSE,
	
	CAN_PUSH_UNIT				= TRUE,
	CAN_PASS_UNIT				= FALSE,
	
	EVENT_PROCESS = 
	{
		{ STATE_CHANGE_TYPE["SCT_FOOT_ON_LINE_TRUE"],			"LOW_BLCW_SOLDIER_HIGH_FD_WAIT",					},
	},
}

LOW_BLCW_SOLDIER_HIGH_FD_DAMAGE_AIR_DOWN = 
{
	ANIM_NAME					= "DamageAirDown",
	PLAY_TYPE					= XSKIN_ANIM_PLAYTYPE["XAP_ONE_WAIT"],
	TRANSITION					= FALSE,
	LAND_CONNECT				= FALSE,
	
	CAN_PUSH_UNIT				= TRUE,
	CAN_PASS_UNIT				= FALSE,
	
	EVENT_PROCESS = 
	{
		{ STATE_CHANGE_TYPE["SCT_FOOT_ON_LINE_TRUE"],			"LOW_BLCW_SOLDIER_HIGH_FD_DAMAGE_AIR_DOWN_LANDING",	},
	},
}

LOW_BLCW_SOLDIER_HIGH_FD_DAMAGE_AIR_UP = 
{
	ANIM_NAME					= "DamageAirUp",
	PLAY_TYPE					= XSKIN_ANIM_PLAYTYPE["XAP_ONE_WAIT"],
	TRANSITION					= FALSE,
	LAND_CONNECT				= FALSE,
	
	CAN_PUSH_UNIT				= TRUE,
	CAN_PASS_UNIT				= FALSE,
	
	
	PASSIVE_SPEED_Y				= -1,
	SPEED_Y						= 1800.0,
	
	EVENT_PROCESS = 
	{
		{ STATE_CHANGE_TYPE["SCT_NEGATIVE_Y_SPEED"],		"LOW_BLCW_SOLDIER_HIGH_FD_DAMAGE_AIR_FALL",			},
		{ STATE_CHANGE_TYPE["SCT_FOOT_ON_LINE_TRUE"],		"LOW_BLCW_SOLDIER_HIGH_FD_DAMAGE_AIR_DOWN_LANDING",	},
	},
}

LOW_BLCW_SOLDIER_HIGH_FD_DAMAGE_AIR_FALL = 
{
	ANIM_NAME					= "DamageAirFall",
	PLAY_TYPE					= XSKIN_ANIM_PLAYTYPE["XAP_ONE_WAIT"],
	TRANSITION					= FALSE,
	LAND_CONNECT				= FALSE,
	
	CAN_PUSH_UNIT				= TRUE,
	CAN_PASS_UNIT				= FALSE,
	
	EVENT_PROCESS = 
	{
		{ STATE_CHANGE_TYPE["SCT_POSITIVE_Y_SPEED"],		"LOW_BLCW_SOLDIER_HIGH_FD_DAMAGE_AIR_UP",			},
		{ STATE_CHANGE_TYPE["SCT_FOOT_ON_LINE_TRUE"],		"LOW_BLCW_SOLDIER_HIGH_FD_DAMAGE_AIR_DOWN_LANDING",	},
	},
}

LOW_BLCW_SOLDIER_HIGH_FD_DAMAGE_AIR_DOWN_LANDING = 
{
	ANIM_NAME					= "DamageAirDownLanding",
	PLAY_TYPE					= XSKIN_ANIM_PLAYTYPE["XAP_ONE_WAIT"],
	TRANSITION					= FALSE,
	LAND_CONNECT				= FALSE,
	
	SUPER_ARMOR					= TRUE,
	DEFENCE						= { 0, 100, 50, },
	
	CAN_PUSH_UNIT				= TRUE,
	CAN_PASS_UNIT				= FALSE,
	
	EVENT_PROCESS = 
	{
		{ STATE_CHANGE_TYPE["SCT_FOOT_ON_LINE_FALSE_DOWN"],	"LOW_BLCW_SOLDIER_HIGH_FD_DAMAGE_AIR_FALL",			},
		{ STATE_CHANGE_TYPE["SCT_MOTION_END"],				"LOW_BLCW_SOLDIER_HIGH_FD_STAND_UP_FRONT",			},
	},
}

LOW_BLCW_SOLDIER_HIGH_FD_STAND_UP_FRONT = 
{
	ANIM_NAME					= "DamageStandUpFront",
	PLAY_TYPE					= XSKIN_ANIM_PLAYTYPE["XAP_ONE_WAIT"],
	TRANSITION					= FALSE,
	LAND_CONNECT				= FALSE,	
		
	SUPER_ARMOR					= TRUE,
	DEFENCE						= { 0, 100, 50, },
	
	CAN_PUSH_UNIT				= TRUE,
	CAN_PASS_UNIT				= FALSE,
	
	EVENT_PROCESS = 
	{
		{ STATE_CHANGE_TYPE["SCT_FOOT_ON_LINE_FALSE_DOWN"],	"LOW_BLCW_SOLDIER_HIGH_FD_JUMP_DOWN",			},
		{ STATE_CHANGE_TYPE["SCT_MOTION_END"],				"LOW_BLCW_SOLDIER_HIGH_FD_WAIT",				},
	},
}

LOW_BLCW_SOLDIER_HIGH_FD_STAND_UP_BACK = 
{
	ANIM_NAME					= "DamageStandUpBack",
	PLAY_TYPE					= XSKIN_ANIM_PLAYTYPE["XAP_ONE_WAIT"],
	TRANSITION					= FALSE,
	LAND_CONNECT				= FALSE,
	
	SUPER_ARMOR					= TRUE,
	DEFENCE						= { 0, 100, 50, },
		
	CAN_PUSH_UNIT				= TRUE,
	CAN_PASS_UNIT				= FALSE,
		
	EVENT_PROCESS = 
	{
		{ STATE_CHANGE_TYPE["SCT_FOOT_ON_LINE_FALSE_DOWN"],	"LOW_BLCW_SOLDIER_HIGH_FD_JUMP_DOWN", },
		{ STATE_CHANGE_TYPE["SCT_MOTION_END"],				"LOW_BLCW_SOLDIER_HIGH_FD_WAIT", },
	},		
}

LOW_BLCW_SOLDIER_HIGH_FD_STAND_UP_ATTACK_FRONT = 
{
	ANIM_NAME					= "StandUpAttackFront",
	PLAY_TYPE					= XSKIN_ANIM_PLAYTYPE["XAP_ONE_WAIT"],
	TRANSITION					= FALSE,
	LAND_CONNECT				= FALSE,	
	ANIM_WAIT_TIME				= 1,
	MIND_FLAG					= MIND_FLAG["MF_STAND_UP_ATTACK"],
	
	SUPER_ARMOR					= TRUE,
	DEFENCE						= { 0, 100, 50, },

        SOUND_PLAY0			= { 0.387, "Airship_High_StandUpAttack.ogg" },

	CAN_PUSH_UNIT				= TRUE,
	CAN_PASS_UNIT				= FALSE,	
	
	EVENT_PROCESS = 
	{
		{ STATE_CHANGE_TYPE["SCT_MOTION_END"],				"LOW_BLCW_SOLDIER_HIGH_FD_WAIT",				},
	},
	
	SLASH_TRACE					= { 0, 100 },	
	ATTACK_TIME0				= { 0.40, 0.60, },	
	ATTACK_TIME1				= { 1.00, 1.10, },	
	
	DAMAGE_DATA = 
	{
		DAMAGE_TYPE		= DAMAGE_TYPE["DT_PHYSIC"],
		HIT_TYPE		= HIT_TYPE["HT_SWORD_SLASH"],
		REACT_TYPE		= REACT_TYPE["RT_DOWN"],
		
		DAMAGE = 
		{
			PHYSIC		= 1.2,
			FIRE		= 0.0,
			ICE			= 0.0,
			EARTH		= 0.0,
			LIGHTNING	= 0.0,
			DARK		= 0.0,
			LIGHT		= 0.0,
			UNIVERSAL	= 0.0,
		},
		
		BACK_SPEED_X			= INIT_PHYSIC["RUN_SPEED"],
		BACK_SPEED_Y			= 0.0,
		
		STOP_TIME_ATT			= 0.0,		
		STOP_TIME_DEF			= 0.0,	
		CAMERA_CRASH_GAP		= 5.0,	
		CAMERA_CRASH_TIME		= 0.2,
		CLEAR_SCREEN			= 0.0,	
		CLEAR_SCREEN_COLOR_A	= 0.0,
		CLEAR_SCREEN_COLOR_R	= 1.0,
		CLEAR_SCREEN_COLOR_G	= 1.0,
		CLEAR_SCREEN_COLOR_B	= 1.0,

		RE_ATTACK				= FALSE,		
		HIT_GAP					= 0.0,				
	},
	
}

LOW_BLCW_SOLDIER_HIGH_FD_STAND_UP_ATTACK_BACK = 
{
	ANIM_NAME					= "StandUpAttackBack",
	PLAY_TYPE					= XSKIN_ANIM_PLAYTYPE["XAP_ONE_WAIT"],
	TRANSITION					= FALSE,
	LAND_CONNECT				= FALSE,
	ANIM_WAIT_TIME				= 1,
	MIND_FLAG					= MIND_FLAG["MF_STAND_UP_ATTACK"],
	
	SLASH_TRACE					= { 0, 100 },
	SUPER_ARMOR					= TRUE,
	DEFENCE						= { 0, 100, 50, },
		
	CAN_PUSH_UNIT				= TRUE,
	CAN_PASS_UNIT				= FALSE,	

        SOUND_PLAY0			= { 0.374, "Airship_High_StandUpAttack.ogg" },

	FLIP_DIR_END				= TRUE,
	
	EVENT_PROCESS = 
	{
		{ STATE_CHANGE_TYPE["SCT_FOOT_ON_LINE_FALSE_DOWN"],	"LOW_BLCW_SOLDIER_HIGH_FD_JUMP_DOWN", },
		{ STATE_CHANGE_TYPE["SCT_MOTION_END"],				"LOW_BLCW_SOLDIER_HIGH_FD_WAIT", },
	},	
	
		
	ATTACK_TIME0				= { 0.40, 0.60, },	
	ATTACK_TIME1				= { 1.00, 1.10, },	
	
	DAMAGE_DATA = 
	{
		DAMAGE_TYPE		= DAMAGE_TYPE["DT_PHYSIC"],
		HIT_TYPE		= HIT_TYPE["HT_SWORD_SLASH"],
		REACT_TYPE		= REACT_TYPE["RT_DOWN"],
		
		DAMAGE = 
		{
			PHYSIC		= 1.2,
			FIRE		= 0.0,
			ICE			= 0.0,
			EARTH		= 0.0,
			LIGHTNING	= 0.0,
			DARK		= 0.0,
			LIGHT		= 0.0,
			UNIVERSAL	= 0.0,
		},
		
		BACK_SPEED_X			= INIT_PHYSIC["RUN_SPEED"],
		BACK_SPEED_Y			= 0.0,
		
		STOP_TIME_ATT			= 0.0,		
		STOP_TIME_DEF			= 0.0,	
		CAMERA_CRASH_GAP		= 5.0,	
		CAMERA_CRASH_TIME		= 0.2,
		CLEAR_SCREEN			= 0.0,	
		CLEAR_SCREEN_COLOR_A	= 0.0,
		CLEAR_SCREEN_COLOR_R	= 1.0,
		CLEAR_SCREEN_COLOR_G	= 1.0,
		CLEAR_SCREEN_COLOR_B	= 1.0,

		RE_ATTACK				= FALSE,		
		HIT_GAP					= 0.0,				
	},
}

LOW_BLCW_SOLDIER_HIGH_FD_DAMAGE_REVENGE = 
{
	ANIM_NAME					= "DamageBig",
	PLAY_TYPE					= XSKIN_ANIM_PLAYTYPE["XAP_ONE_WAIT"],
	TRANSITION					= FALSE,
	LAND_CONNECT				= FALSE,
	
	STOP_MY_UNIT0				= { 0.2, 0.2, },
	
	CAN_PUSH_UNIT				= TRUE,
	CAN_PASS_UNIT				= FALSE,
	
	EVENT_PROCESS = 
	{
		{ STATE_CHANGE_TYPE["SCT_MOTION_END"],				"LOW_BLCW_SOLDIER_HIGH_FD_WAIT",					},
	},
}




LOW_BLCW_SOLDIER_HIGH_FD_DYING_LAND_FRONT = 
{
	ANIM_NAME					= "DamageDownFront",
	PLAY_TYPE					= XSKIN_ANIM_PLAYTYPE["XAP_ONE_WAIT"],
	TRANSITION					= FALSE,
	LAND_CONNECT				= FALSE,

	INVINCIBLE					= { 0, 100, }, 		
	
	CAN_PUSH_UNIT				= FALSE,
	CAN_PASS_UNIT				= TRUE,
	
	DYING_END					= TRUE,
	IMMADIATE_PACKET_SEND		= TRUE,
}
	
LOW_BLCW_SOLDIER_HIGH_FD_DYING_LAND_BACK = 
{
	ANIM_NAME					= "DamageDownBack",
	PLAY_TYPE					= XSKIN_ANIM_PLAYTYPE["XAP_ONE_WAIT"],
	TRANSITION					= FALSE,
	LAND_CONNECT				= FALSE,
	
	INVINCIBLE					= { 0, 100, }, 		
	
	CAN_PUSH_UNIT				= FALSE,
	CAN_PASS_UNIT				= TRUE,
	
	DYING_END					= TRUE,	
	IMMADIATE_PACKET_SEND		= TRUE,
}

LOW_BLCW_SOLDIER_HIGH_FD_DYING_SKY = 
{
	ANIM_NAME					= "DamageAirDownLanding",
	PLAY_TYPE					= XSKIN_ANIM_PLAYTYPE["XAP_ONE_WAIT"],
	TRANSITION					= FALSE,
	LAND_CONNECT				= FALSE,
	
	INVINCIBLE					= { 0, 100, }, 		
	
	CAN_PUSH_UNIT				= FALSE,
	CAN_PASS_UNIT				= TRUE,
	
	DYING_END					= TRUE,
	IMMADIATE_PACKET_SEND		= TRUE,
}


LOW_BLCW_SOLDIER_HIGH_FD_POWER_BOOSTER = 
{
	ANIM_NAME					= "AttackRing",
	PLAY_TYPE					= XSKIN_ANIM_PLAYTYPE["XAP_ONE_WAIT"],
	TRANSITION					= FALSE,
	
	CAN_PUSH_UNIT				= TRUE,
	CAN_PASS_UNIT				= FALSE,

    SOUND_PLAY0			= { 0.54, "Airship_High_PowerBooster.ogg" },

	SPEED_X						= 0,
	SPEED_Y						= 0,	
	
	VIEW_TARGET					= TRUE,
	IMMADIATE_PACKET_SEND		= TRUE,
	
	SUPER_ARMOR					= TRUE,
	
	EVENT_PROCESS = 
	{	
		{ STATE_CHANGE_TYPE["SCT_FOOT_ON_LINE_FALSE_DOWN"],	"LOW_BLCW_SOLDIER_HIGH_FD_JUMP_DOWN",									},
		{ STATE_CHANGE_TYPE["SCT_MOTION_END"],				"LOW_BLCW_SOLDIER_HIGH_FD_WAIT",											},	
	},
}

LOW_BLCW_SOLDIER_HIGH_FD_DEFENCE_BOOSTER = 
{
	ANIM_NAME					= "AttackRing",
	PLAY_TYPE					= XSKIN_ANIM_PLAYTYPE["XAP_ONE_WAIT"],
	TRANSITION					= FALSE,
	
	CAN_PUSH_UNIT				= TRUE,
	CAN_PASS_UNIT				= FALSE,

    SOUND_PLAY0			= { 0.54, "Airship_High_DefenceBooster.ogg" },

	SPEED_X						= 0,
	SPEED_Y						= 0,	
	
	VIEW_TARGET					= TRUE,
	IMMADIATE_PACKET_SEND		= TRUE,
	
	SUPER_ARMOR					= TRUE,
	
	EVENT_PROCESS = 
	{	
		{ STATE_CHANGE_TYPE["SCT_FOOT_ON_LINE_FALSE_DOWN"],	"LOW_BLCW_SOLDIER_HIGH_FD_JUMP_DOWN",									},
		{ STATE_CHANGE_TYPE["SCT_MOTION_END"],				"LOW_BLCW_SOLDIER_HIGH_FD_WAIT",											},	
	},
}





function LOW_BLCW_SOLDIER_HIGH_FD_START_CAMERA_MOVE( pKTDXApp, pX2Game, pNPCUnit )

	local pos = pNPCUnit:GetBonePos_LUA("Bip01_Head")	
	local camera = pX2Game:GetX2Camera()
	camera:PartsLookDirectCamera_LUA( pNPCUnit, pos, D3DXVECTOR3( 500, -50, -20 ), D3DXVECTOR2( 0,0 ) )

end


function CF_LOW_BLCW_SOLDIER_HIGH_FD_WIN( pKTDXApp, pX2Game, pNPCUnit )

	if pX2Game:LiveUserUnitNum() == 0 then
		return true
	else
		return false
	end

end



function LOW_BLCW_SOLDIER_HIGH_FD_WALK_STATE_END( pKTDXApp, pX2Game, pNPCUnit )

	local pMinorParticle = pX2Game:GetMinorParticle()
	pMinorParticle:GameUnitCreateSequence_LUA( pNPCUnit, "StepSmoke", pNPCUnit:GetLandPosition_LUA(), D3DXVECTOR2(100,100), D3DXVECTOR2(5,-1) )

end

function LOW_BLCW_SOLDIER_HIGH_FD_JUMP_DOWN_STATE_END( pKTDXApp, pX2Game, pNPCUnit )

	local pMinorParticle = pX2Game:GetMinorParticle()
	pMinorParticle:GameUnitCreateSequence_LUA( pNPCUnit, "StepSmoke", pNPCUnit:GetLandPosition_LUA(), D3DXVECTOR2(100,100), D3DXVECTOR2(5,-1) )

end

function LOW_BLCW_SOLDIER_HIGH_FD_JUMP_DOWN_DIR_STATE_END( pKTDXApp, pX2Game, pNPCUnit )

	local pMinorParticle = pX2Game:GetMinorParticle()
	pMinorParticle:GameUnitCreateSequence_LUA( pNPCUnit, "StepSmoke", pNPCUnit:GetLandPosition_LUA(), D3DXVECTOR2(100,100), D3DXVECTOR2(5,-1) )

end




function LOW_BLCW_SOLDIER_HIGH_FD_DAMAGE_SMALL_FRAME_MOVE( pKTDXApp, pX2Game, pNPCUnit )

	if pNPCUnit:AnimEventTimer_LUA( 0.15 ) then
		local pMinorParticle = pX2Game:GetMinorParticle()
		pMinorParticle:GameUnitCreateSequence_LUA( pNPCUnit, "StepSmoke", pNPCUnit:GetLandPosition_LUA(), D3DXVECTOR2(100,100), D3DXVECTOR2(5,-1) )
	end
	
	

	
end

function LOW_BLCW_SOLDIER_HIGH_FD_DAMAGE_BIG_FRAME_MOVE( pKTDXApp, pX2Game, pNPCUnit )

	if pNPCUnit:AnimEventTimer_LUA( 0.1 ) then
		local pMinorParticle = pX2Game:GetMinorParticle()
		pMinorParticle:GameUnitCreateSequence_LUA( pNPCUnit, "StepSmoke", pNPCUnit:GetLandPosition_LUA(), D3DXVECTOR2(100,100), D3DXVECTOR2(5,-1) )
	end
	


end

function LOW_BLCW_SOLDIER_HIGH_FD_DAMAGE_DOWN_FRONT_FRAME_MOVE( pKTDXApp, pX2Game, pNPCUnit )

	if pNPCUnit:AnimEventTimer_LUA( 0.34 ) then
		pNPCUnit:PlaySound_LUA( "Down.ogg" )
		local pMinorParticle = pX2Game:GetMinorParticle()
		pMinorParticle:GameUnitCreateSequence_LUA( pNPCUnit, "DownSmoke", pNPCUnit:GetLandPosition_LUA(), D3DXVECTOR2(100,100), D3DXVECTOR2(7,-1) )
	end

end

function LOW_BLCW_SOLDIER_HIGH_FD_DAMAGE_DOWN_BACK_FRAME_MOVE( pKTDXApp, pX2Game, pNPCUnit )

	if pNPCUnit:AnimEventTimer_LUA( 0.24 ) then
		pNPCUnit:PlaySound_LUA( "Down.ogg" )
		local pMinorParticle = pX2Game:GetMinorParticle()
		pMinorParticle:GameUnitCreateSequence_LUA( pNPCUnit, "DownSmoke", pNPCUnit:GetLandPosition_LUA(), D3DXVECTOR2(100,100), D3DXVECTOR2(7,-1) )
	end

end


function LOW_BLCW_SOLDIER_HIGH_FD_DAMAGE_AIR_DOWN_LANDING_FRAME_MOVE( pKTDXApp, pX2Game, pNPCUnit )

	if pNPCUnit:AnimEventTimer_LUA( 0.01 ) then
		pNPCUnit:PlaySound_LUA( "Down.ogg" )
		local pMinorParticle = pX2Game:GetMinorParticle()
		local pos = pNPCUnit:GetLandPosition_LUA()
		pMinorParticle:GameUnitCreateSequence_LUA( pNPCUnit, "DownSmoke", pos, D3DXVECTOR2(100,100), D3DXVECTOR2(7,-1) )
		pos.y = pos.y + 5
		pMinorParticle:GameUnitCreateSequence_LUA( pNPCUnit, "GroundShockWave", pos, D3DXVECTOR2(100,100), D3DXVECTOR2(1,-1) )
		local pParticle = pMinorParticle:GameUnitCreateSequence_LUA( pNPCUnit, "AirDownTick", pNPCUnit:GetPos(), D3DXVECTOR2(200,200), D3DXVECTOR2(10,-1) )
		if pParticle ~= nil then 
			pParticle:SetLandPosition( pos.y - 5 )
		end 
		
		if GetDistance_LUA( pNPCUnit:GetPos(), pX2Game:GetFocusUnitPos_LUA() ) < 500 then
			pX2Game:GetX2Camera():GetCamera():UpDownCrashCameraNoReset( 10.0, 0.1 )
		end		
		
	elseif pNPCUnit:AnimEventTimer_LUA( 0.44 ) then
		pNPCUnit:PlaySound_LUA( "Down.ogg" )
		local pMinorParticle = pX2Game:GetMinorParticle()
		pMinorParticle:GameUnitCreateSequence_LUA( pNPCUnit, "DownSmoke", pNPCUnit:GetLandPosition_LUA(), D3DXVECTOR2(100,100), D3DXVECTOR2(7,-1) )
	end
end



function LOW_BLCW_SOLDIER_HIGH_FD_STAND_UP_ATTACK_FRONT_FRAME_MOVE( pKTDXApp, pX2Game, pNPCUnit )

	if pNPCUnit:AnimEventTimer_LUA( 0.80 ) then
		local pMinorParticle = pX2Game:GetMinorParticle()
		pMinorParticle:GameUnitCreateSequence_LUA( pNPCUnit, "StepSmoke", pNPCUnit:GetLandPosition_LUA(), D3DXVECTOR2(100,100), D3DXVECTOR2(5,-1) )
	end

end

function LOW_BLCW_SOLDIER_HIGH_FD_STAND_UP_ATTACK_BACK_FRAME_MOVE( pKTDXApp, pX2Game, pNPCUnit )

	if pNPCUnit:AnimEventTimer_LUA( 0.72 ) then
		local pMinorParticle = pX2Game:GetMinorParticle()
		pMinorParticle:GameUnitCreateSequence_LUA( pNPCUnit, "StepSmoke", pNPCUnit:GetLandPosition_LUA(), D3DXVECTOR2(100,100), D3DXVECTOR2(5,-1) )
	end
	

end

function LOW_BLCW_SOLDIER_HIGH_FD_COMBO2_FRAME_MOVE( pKTDXApp, pX2Game, pNPCUnit )
			
	if pNPCUnit:AnimEventTimer_LUA( 0.01 ) then
		pNPCUnit:ClearHitUnitList_LUA()
	end
	
end




--[[
function LOW_BLCW_SOLDIER_HIGH_FD_DYING_LAND_STATE_START( pKTDXApp, pX2Game, pNPCUnit )
	
	pos = pNPCUnit:GetPos()
	pos.y = pos.y + 100.0
	GetMinorParticle = pX2Game:GetMinorParticle()
	
	pSeq = GetMinorParticle:GameUnitCreateSequence_LUA( pNPCUnit, "DieLight",		pos, D3DXVECTOR2(-1,-1), D3DXVECTOR2(3,-1) )
	if pSeq ~= nil then
	
		pSeq:SetLandPosition( pNPCUnit:GetLandPosition_LUA().y )
		pNPCUnit:SetDieSeq( pSeq:GetHandle() )
	
	end
	pNPCUnit:PlaySound_LUA( "DieLight.ogg" )	
	
end

--]]

function LOW_BLCW_SOLDIER_HIGH_FD_POWER_BOOSTER_FRAME_MOVE( pKTDXApp, pX2Game, pNPCUnit )

    local nUnitListSize = pX2Game:GetNPCUnitListSize()
    
	
	if pNPCUnit:AnimEventTimer_LUA( 0.750 ) then	    
	
	    for i=0, nUnitListSize-1 do 
			
			local pUnit = pX2Game:GetNPCUnit( i )
			
			if pUnit ~= nil and	pUnit:GetTeam() == pNPCUnit:GetTeam() then
			
			    if pUnit:IsUnitID(NPC_UNIT_ID["NUI_SMALLGATE_BESMA_AIR_SHIP"]) == false and
			        pUnit:IsUnitID(NPC_UNIT_ID["NUI_SMALLGATE_POST_BESMA_AIR_SHIP"]) == false and
			        pUnit:IsUnitID(NPC_UNIT_ID["NUI_BOX"]) == false and
			        pUnit:IsUnitID(NPC_UNIT_ID["NUI_CANNON_MINI_UP"]) == false and
			        pUnit:IsUnitID(NPC_UNIT_ID["NUI_CANNON_BIG"]) == false and
			        pUnit:IsUnitID(NPC_UNIT_ID["NUI_CANNON_BIG_DOWN"]) == false and
			        pUnit:IsUnitID(NPC_UNIT_ID["NUI_CANNON_MINI"]) == false and
			        pUnit:IsUnitID(NPC_UNIT_ID["NUI_CANNON_HEAVY_MACHINE_GUN"]) == false  then
			        
			        -- 공격력 증가 
				    pUnit:SetBuffFactorToGameUnitByBuffFactorID_LUA( BUFF_FACTOR_ID["BFI_NPC_PHYSIC_ATTACK_ACCEL"] )
				    
		            local vPos = pUnit:GetPos()
		            vPos.y = vPos.y + 100.0
            		        		
		            local pMajorParticle = pX2Game:GetMajorParticle()			        
		            local pParticle = pMajorParticle:GameUnitCreateSequence_LUA( pNPCUnit, "BuffAttackCore", vPos, D3DXVECTOR2(-1,-1), D3DXVECTOR2(-1,-1) )
		            if pParticle ~= nil then 
						pParticle:SetBlackHolePosition( vPos )
					end
			    end				

			end
				
		end	
	end
	
	
	
	if pNPCUnit:AnimEventTimer_LUA( 0.5 ) then	
	
		local vRotateDegree	= pNPCUnit:GetRotateDegree()
		local vPos = pNPCUnit:GetPos()
	
		local pMajorParticle = pX2Game:GetMajorParticle()	
		local pParticle = pMajorParticle:GameUnitCreateSequence_LUA( pNPCUnit, "LizardMan_Older_PowerBooster01", vPos, D3DXVECTOR2(-1,-1), D3DXVECTOR2(-1,-1) )
		if pParticle ~= nil then 
			pParticle:SetAddRotate( vRotateDegree )
			pParticle:SetAxisAngle( vRotateDegree )	
			pNPCUnit:SetMajorParticle_LUA( 0, pParticle:GetHandle() ) 
		end

		pParticle = pMajorParticle:GameUnitCreateSequence_LUA( pNPCUnit, "LizardMan_Older_PowerBooster02", vPos, D3DXVECTOR2(-1,-1), D3DXVECTOR2(-1,-1) )
		if pParticle ~= nil then 
			pParticle:SetAddRotate( vRotateDegree )
			pParticle:SetAxisAngle( vRotateDegree )	
			pNPCUnit:SetMajorParticle_LUA( 1, pParticle:GetHandle() ) 
		end
		
	end
	
	
	if pNPCUnit:GetNowAnimationTime() > 0.5 then 	
	
	    --for i=0, nUnitListSize-1 do 
    			
			--pUnit = pX2Game:GetNPCUnit( i )
    		
			--if pUnit ~= nil and pUnit:GetTeam() == pNPCUnit:GetTeam() then
    			
				local pParticle = pNPCUnit:GetMajorParticle_LUA( 0 )	
				local pMajorParticle = pX2Game:GetMajorParticle()					
		        if nil ~= pParticle then 
			        if pMajorParticle:IsLiveInstance( pParticle ) == true then 
				        local vPos = pNPCUnit:GetPos()
				        pParticle:SetPosition( vPos )		
			        else 
				        pNPCUnit:ClearMajorParticle_LUA( 0 )
			        end
		        end
            	
		        pParticle = pNPCUnit:GetMajorParticle_LUA( 1 ) 
		        if nil ~= pParticle then 
			        if pMajorParticle:IsLiveInstance( pParticle ) == true then 
				        local vPos = pNPCUnit:GetPos()
				        pParticle:SetPosition( vPos )		
			        else 
				        pNPCUnit:ClearMajorParticle_LUA( 1 )
			        end
		        end    								
			--end    				
		    	
	    --end		
	end	
	
end


------------------------------------------------------------------------------------------------------------
function LOW_BLCW_SOLDIER_HIGH_FD_POWER_BOOSTER_STATE_END( pKTDXApp, pX2Game, pNPCUnit )
--[[	
	nUnitListSize = pX2Game:GetNPCUnitListSize()
	
	
	
	for i=0, nUnitListSize-1 do 
		
		pUnit = pX2Game:GetNPCUnit( i )
		
		if pUnit ~= nil and	pUnit:GetTeam() == pNPCUnit:GetTeam() then
		
	        pMajorParticle = pX2Game:GetMajorParticle()
	        pParticle = pUnit:GetMajorParticle_LUA( 0 )
	        if pParticle ~= nil then
		        pMajorParticle:DestroyInstance( pParticle )
		        pUnit:ClearMajorParticle_LUA( 0 )
	        end
            
	        pMajorParticle = pX2Game:GetMajorParticle()
	        pParticle = pUnit:GetMajorParticle_LUA( 1 )
	        if pParticle ~= nil then
		        pMajorParticle:DestroyInstance( pParticle )
		        pUnit:ClearMajorParticle_LUA( 1 )
	        end
	        
        end
    end
--]]          	
	pNPCUnit:SetFlag_LUA(0, true)
end

function LOW_BLCW_SOLDIER_HIGH_FD_DEFENCE_BOOSTER_FRAME_MOVE( pKTDXApp, pX2Game, pNPCUnit )

    local nUnitListSize = pX2Game:GetNPCUnitListSize()
    
	
	if pNPCUnit:AnimEventTimer_LUA( 0.750 ) then	
	
	    for i=0, nUnitListSize-1 do 
			
			local pUnit = pX2Game:GetNPCUnit( i )
			
			if pUnit ~= nil and	pUnit:GetTeam() == pNPCUnit:GetTeam() then
			
			    if pUnit:IsUnitID(NPC_UNIT_ID["NUI_SMALLGATE_BESMA_AIR_SHIP"]) == false and
			        pUnit:IsUnitID(NPC_UNIT_ID["NUI_SMALLGATE_POST_BESMA_AIR_SHIP"]) == false and
			        pUnit:IsUnitID(NPC_UNIT_ID["NUI_BOX"]) == false and
			        pUnit:IsUnitID(NPC_UNIT_ID["NUI_CANNON_MINI_UP"]) == false and
			        pUnit:IsUnitID(NPC_UNIT_ID["NUI_CANNON_BIG"]) == false and
			        pUnit:IsUnitID(NPC_UNIT_ID["NUI_CANNON_BIG_DOWN"]) == false and
			        pUnit:IsUnitID(NPC_UNIT_ID["NUI_CANNON_MINI"]) == false and
			        pUnit:IsUnitID(NPC_UNIT_ID["NUI_CANNON_HEAVY_MACHINE_GUN"]) == false  then
			    
	                -- 방어력 증가             	    	    
		            pUnit:SetBuffFactorToGameUnitByBuffFactorID_LUA( BUFF_FACTOR_ID["BFI_NPC_PHYSIC_DEFENCE_ACCEL"] )
		            local vPos = pUnit:GetPos()
		            vPos.y = vPos.y + 100.0
                	
		            local pMajorParticle = pX2Game:GetMajorParticle()	
		            local pParticle = pMajorParticle:GameUnitCreateSequence_LUA( pNPCUnit, "ShieldBuffCore", vPos, D3DXVECTOR2(-1,-1), D3DXVECTOR2(-1,-1) )
		            if pParticle ~= nil then 
						pParticle:SetBlackHolePosition( vPos )
					end 
                end		            
            end	            
        end	             
    end	         
	
	
	
	if pNPCUnit:AnimEventTimer_LUA( 0.5 ) then	
	
		local vRotateDegree	= pNPCUnit:GetRotateDegree()
		local vPos = pNPCUnit:GetPos()
	
		local pMajorParticle = pX2Game:GetMajorParticle()	
		local pParticle = pMajorParticle:GameUnitCreateSequence_LUA( pNPCUnit, "LizardMan_Older_PowerBooster01", vPos, D3DXVECTOR2(-1,-1), D3DXVECTOR2(-1,-1) )
		if pParticle ~= nil then 
			pParticle:SetAddRotate( vRotateDegree )
			pParticle:SetAxisAngle( vRotateDegree )	
			pNPCUnit:SetMajorParticle_LUA( 0, pParticle:GetHandle() ) 
		end

		pParticle = pMajorParticle:GameUnitCreateSequence_LUA( pNPCUnit, "LizardMan_Older_PowerBooster02", vPos, D3DXVECTOR2(-1,-1), D3DXVECTOR2(-1,-1) )
		if pParticle ~= nil then 
			pParticle:SetAddRotate( vRotateDegree )
			pParticle:SetAxisAngle( vRotateDegree )	
			pNPCUnit:SetMajorParticle_LUA( 1, pParticle:GetHandle() ) 
		end
		
	end
	
	
	if pNPCUnit:GetNowAnimationTime() > 0.5 then 	
	
	    --for i=0, nUnitListSize-1 do 
    			
			--pUnit = pX2Game:GetNPCUnit( i )
    		
			--if pUnit ~= nil and	pUnit:GetTeam() == pNPCUnit:GetTeam() then
    			
		        local pParticle = pNPCUnit:GetMajorParticle_LUA( 0 ) 
				local pMajorParticle = pX2Game:GetMajorParticle()	
		        if nil ~= pParticle then 
			        if pMajorParticle:IsLiveInstance( pParticle ) == true then 
				        local vPos = pNPCUnit:GetPos()
				        pParticle:SetPosition( vPos )		
			        else 
				        pNPCUnit:ClearMajorParticle_LUA( 0 )
			        end
		        end
        		
		        pParticle = pNPCUnit:GetMajorParticle_LUA( 1 ) 
		        if nil ~= pParticle then 
			        if pMajorParticle:IsLiveInstance( pParticle ) == true then 
				        local vPos = pNPCUnit:GetPos()
				        pParticle:SetPosition( vPos )		
			        else 
				        pNPCUnit:ClearMajorParticle_LUA( 1 )
			        end
		        end
            --end
        --end
	end
	
	
end


------------------------------------------------------------------------------------------------------------
function LOW_BLCW_SOLDIER_HIGH_FD_DEFENCE_BOOSTER_STATE_END( pKTDXApp, pX2Game, pNPCUnit )
--[[	
	nUnitListSize = pX2Game:GetNPCUnitListSize()   
	
			
	for i=0, nUnitListSize-1 do 
		
		pUnit = pX2Game:GetNPCUnit( i )
		
		if pUnit ~= nil and	pUnit:GetTeam() == pNPCUnit:GetTeam() then
			
	        pMajorParticle = pX2Game:GetMajorParticle()
	        pParticle = pUnit:GetMajorParticle_LUA( 0 )
	        if pParticle ~= nil then
		        pMajorParticle:DestroyInstance( pParticle )
		        pUnit:ClearMajorParticle_LUA( 0 )
	        end
        	
	        pMajorParticle = pX2Game:GetMajorParticle()
	        pParticle = pUnit:GetMajorParticle_LUA( 1 )
	        if pParticle ~= nil then
		        pMajorParticle:DestroyInstance( pParticle )
		        pUnit:ClearMajorParticle_LUA( 1 )
	        end
        end	        
    end	   	
--]]    
    pNPCUnit:SetFlag_LUA(1, true)
	
end
