-- lua header. UTF-8 인코딩 인식을 위해 이 줄은 지우지 마세요.

INIT_SYSTEM = 
{
	LUA_SHAREABLE	= TRUE,
	UNIT_WIDTH		= 144.0,
	UNIT_HEIGHT		= 165.0,
	UNIT_LAYER		= X2_LAYER["XL_UNIT_0"],
	UNIT_SCALE		= 1.0,
}


INIT_DEVICE = 
{
	READY_TEXTURE = 
	{
	},
	
	READY_SOUND = 
	{
		 "Shadow_Defender_AttackA.ogg",
		 "Shadow_Defender_AttackA_Ready.ogg",
		 "Shadow_Defender_DamageDownLanding.ogg",
		 "Shadow_Defender_DamageRevenge.ogg",
		 "Shadow_Defender_SpecialAttackA.ogg",
		 "Shadow_Defender_StandUpAttackBack.ogg",
		 "Shadow_Defender_StandUpAttackFront.ogg",
		 "Shadow_Defender_WaitHabit01.ogg",
		 "Shadow_Defender_WaitHabit02.ogg",
		 "Shadow_Defender_WaitHabit03.ogg",
	},

	READY_XMESH = 
	{
	 
	},
	
	READY_XSKIN_MESH = 
	{
	 
	},
}

INIT_MOTION = 
{
	MOTION_FILE_NAME		= "Motion_SHADOW_DEFENDER.x",
	MOTION_CHANGE_TEX_XET	= "NUI_LOW_SHADOW_DEFENDER_FD.XET",
	MOTION_ANI_TEX_XET		= "NUI_LOW_SHADOW_DEFENDER_FD.XET",
}

INIT_PHYSIC = 
{
	RELOAD_ACCEL		= 2000,
	G_ACCEL				= 4000,
	MAX_G_SPEED			= -2000,
	
	WALK_SPEED			= 500,
	RUN_SPEED			= 700,
	JUMP_SPEED			= 1500,
	DASH_JUMP_SPEED		= 2300,
}


INIT_COMPONENT = 
{
	MAX_HP				= 5000,
	MP_CHANGE_RATE		= 1,
	MP_CHARGE_RATE		= 130,
	
	
	SHADOW_SIZE			= 200,
	SHADOW_FILE_NAME	= "shadow.dds",
	
	SMALL_HP_BAR_BLUE	= "Small_HP_bar_Blue.TGA",
	SMALL_HP_BAR_RED	= "Small_HP_bar_Red.TGA",
	SMALL_HP_BAR_YELLOW = "Small_HP_bar_Yellow.TGA",
	
	QUESTION_MARK_SEQ		= "QuestionMarkNPC",
	EXCLAMATION_MARK_SEQ	= "ExclamationMarkNPC",
	
	HYPER_MODE_COUNT	= 0,
	MAX_HYPER_MODE_TIME	= 30,
	
	HITTED_TYPE			= HITTED_TYPE["HTD_MEAT"],
	
	FALL_DOWN			= TRUE,
	DIE_FLY				= FALSE,
}



INIT_STATE = 
{
	{ STATE_NAME = "LOW_SHADOW_DEFENDER_FD_START",							},
	
	{ STATE_NAME = "LOW_SHADOW_DEFENDER_FD_WAIT",							},
	{ STATE_NAME = "LOW_SHADOW_DEFENDER_FD_WAIT_HABIT",						},
	
	{ STATE_NAME = "LOW_SHADOW_DEFENDER_FD_WALK",							LUA_STATE_END_FUNC = "LOW_SHADOW_DEFENDER_FD_WALK_STATE_END"							},

	
	{ STATE_NAME = "LOW_SHADOW_DEFENDER_FD_DASH",							},
	{ STATE_NAME = "LOW_SHADOW_DEFENDER_FD_DASH_END",						},
		

	{ STATE_NAME = "LOW_SHADOW_DEFENDER_FD_JUMP_UP",							},
	{ STATE_NAME = "LOW_SHADOW_DEFENDER_FD_JUMP_DOWN",						LUA_STATE_END_FUNC = "LOW_SHADOW_DEFENDER_FD_JUMP_DOWN_STATE_END"					},
	{ STATE_NAME = "LOW_SHADOW_DEFENDER_FD_JUMP_UP_DIR",						},
	{ STATE_NAME = "LOW_SHADOW_DEFENDER_FD_JUMP_DOWN_DIR",					LUA_STATE_END_FUNC = "LOW_SHADOW_DEFENDER_FD_JUMP_DOWN_DIR_STATE_END"				},
	{ STATE_NAME = "LOW_SHADOW_DEFENDER_FD_JUMP_LANDING",					},

		
	{ STATE_NAME = "LOW_SHADOW_DEFENDER_FD_ATTACK_A_READY",		LUA_FRAME_MOVE_FUNC = "LOW_SHADOW_DEFENDER_FD_ATTACK_A_READY_FRAME_MOVE",		STATE_COOL_TIME = 5, },
	{ STATE_NAME = "LOW_SHADOW_DEFENDER_FD_ATTACK_A",			LUA_FRAME_MOVE_FUNC = "LOW_SHADOW_DEFENDER_FD_ATTACK_A_FRAME_MOVE", },
	{ STATE_NAME = "LOW_SHADOW_DEFENDER_FD_ATTACK_B",			LUA_FRAME_MOVE_FUNC = "LOW_SHADOW_DEFENDER_FD_ATTACK_B_FRAME_MOVE", },
	{ STATE_NAME = "LOW_SHADOW_DEFENDER_FD_ATTACK_C",			LUA_FRAME_MOVE_FUNC = "LOW_SHADOW_DEFENDER_FD_ATTACK_C_FRAME_MOVE", },
		
	{ STATE_NAME = "LOW_SHADOW_DEFENDER_FD_SPECIAL_ATTACK_A",		LUA_FRAME_MOVE_FUNC = "LOW_SHADOW_DEFENDER_FD_SPECIAL_ATTACK_A_FRAME_MOVE",		STATE_COOL_TIME = 25, },
	
	
	{ STATE_NAME = "LOW_SHADOW_DEFENDER_FD_STAND_UP_ATTACK_FRONT", },--						LUA_FRAME_MOVE_FUNC = "LOW_SHADOW_DEFENDER_FD_STAND_UP_ATTACK_FRONT_FRAME_MOVE" , },
	{ STATE_NAME = "LOW_SHADOW_DEFENDER_FD_STAND_UP_ATTACK_BACK",	 },--				LUA_FRAME_MOVE_FUNC = "LOW_SHADOW_DEFENDER_FD_STAND_UP_ATTACK_BACK_FRAME_MOVE" , },

	
	--리액션 관련
	{ STATE_NAME = "LOW_SHADOW_DEFENDER_FD_DAMAGE_FRONT", },
	{ STATE_NAME = "LOW_SHADOW_DEFENDER_FD_DAMAGE_BACK",  },
	{ STATE_NAME = "LOW_SHADOW_DEFENDER_FD_DAMAGE_DOWN_FRONT",				LUA_FRAME_MOVE_FUNC = "LOW_SHADOW_DEFENDER_FD_DAMAGE_DOWN_FRONT_FRAME_MOVE"			},
	{ STATE_NAME = "LOW_SHADOW_DEFENDER_FD_DAMAGE_DOWN_BACK",				LUA_FRAME_MOVE_FUNC = "LOW_SHADOW_DEFENDER_FD_DAMAGE_DOWN_BACK_FRAME_MOVE"			},
	{ STATE_NAME = "LOW_SHADOW_DEFENDER_FD_DAMAGE_FLY_FRONT",				},
	{ STATE_NAME = "LOW_SHADOW_DEFENDER_FD_DAMAGE_FLY_BACK",					},
	{ STATE_NAME = "LOW_SHADOW_DEFENDER_FD_DAMAGE_AIR",						},
	{ STATE_NAME = "LOW_SHADOW_DEFENDER_FD_DAMAGE_AIR_DOWN",					},
	{ STATE_NAME = "LOW_SHADOW_DEFENDER_FD_DAMAGE_AIR_UP",					},
	{ STATE_NAME = "LOW_SHADOW_DEFENDER_FD_DAMAGE_AIR_FALL",					},
	{ STATE_NAME = "LOW_SHADOW_DEFENDER_FD_DAMAGE_AIR_DOWN_LANDING",			LUA_FRAME_MOVE_FUNC = "LOW_SHADOW_DEFENDER_FD_DAMAGE_AIR_DOWN_LANDING_FRAME_MOVE"	},
	
	{ STATE_NAME = "LOW_SHADOW_DEFENDER_FD_STAND_UP_FRONT",					},
	{ STATE_NAME = "LOW_SHADOW_DEFENDER_FD_STAND_UP_BACK",					},
	
	{ STATE_NAME = "LOW_SHADOW_DEFENDER_FD_DAMAGE_REVENGE",					},
	
	
	
	
	{ STATE_NAME = "LOW_SHADOW_DEFENDER_FD_DYING_LAND_FRONT",				LUA_STATE_START_FUNC = "LOW_SHADOW_DEFENDER_FD_DYING_LAND_STATE_START",},
	{ STATE_NAME = "LOW_SHADOW_DEFENDER_FD_DYING_LAND_BACK",					LUA_STATE_START_FUNC = "LOW_SHADOW_DEFENDER_FD_DYING_LAND_STATE_START",},
	{ STATE_NAME = "LOW_SHADOW_DEFENDER_FD_DYING_SKY",						LUA_STATE_START_FUNC = "LOW_SHADOW_DEFENDER_FD_DYING_LAND_STATE_START",},
	
	
	
	START_STATE					= "LOW_SHADOW_DEFENDER_FD_WAIT",
	WAIT_STATE					= "LOW_SHADOW_DEFENDER_FD_WAIT",
	
	
	
	SMALL_DAMAGE_LAND_FRONT		= "LOW_SHADOW_DEFENDER_FD_DAMAGE_FRONT",
	SMALL_DAMAGE_LAND_BACK		= "LOW_SHADOW_DEFENDER_FD_DAMAGE_BACK",
	BIG_DAMAGE_LAND_FRONT		= "LOW_SHADOW_DEFENDER_FD_DAMAGE_FRONT",
	BIG_DAMAGE_LAND_BACK		= "LOW_SHADOW_DEFENDER_FD_DAMAGE_BACK",
	DOWN_DAMAGE_LAND_FRONT		= "LOW_SHADOW_DEFENDER_FD_DAMAGE_DOWN_FRONT",
	DOWN_DAMAGE_LAND_BACK		= "LOW_SHADOW_DEFENDER_FD_DAMAGE_DOWN_BACK",
	FLY_DAMAGE_FRONT			= "LOW_SHADOW_DEFENDER_FD_DAMAGE_FLY_FRONT",
	FLY_DAMAGE_BACK				= "LOW_SHADOW_DEFENDER_FD_DAMAGE_FLY_BACK",
	SMALL_DAMAGE_AIR			= "LOW_SHADOW_DEFENDER_FD_DAMAGE_AIR",	
	BIG_DAMAGE_AIR				= "LOW_SHADOW_DEFENDER_FD_DAMAGE_AIR",
	DOWN_DAMAGE_AIR				= "LOW_SHADOW_DEFENDER_FD_DAMAGE_AIR_DOWN",
	DOWN_DAMAGE_AIR_LANDING				= "LOW_SHADOW_DEFENDER_FD_DAMAGE_AIR_DOWN_LANDING",
	UP_DAMAGE					= "LOW_SHADOW_DEFENDER_FD_DAMAGE_AIR_UP",
	DAMAGE_REVENGE				= "LOW_SHADOW_DEFENDER_FD_DAMAGE_REVENGE",
	
	DAMAGE_EXTRA_STATES         = {"LOW_SHADOW_DEFENDER_FD_DAMAGE_AIR_FALL",
	"LOW_SHADOW_DEFENDER_FD_STAND_UP_FRONT","LOW_SHADOW_DEFENDER_FD_STAND_UP_BACK","LOW_SHADOW_DEFENDER_FD_STAND_UP_ATTACK_FRONT","LOW_SHADOW_DEFENDER_FD_STAND_UP_ATTACK_BACK",
	"LOW_SHADOW_DEFENDER_FD_JUMP_DOWN","LOW_SHADOW_DEFENDER_FD_JUMP_LANDING",},
	
	
	DYING_LAND_FRONT			= "LOW_SHADOW_DEFENDER_FD_DYING_LAND_FRONT",
	DYING_LAND_BACK				= "LOW_SHADOW_DEFENDER_FD_DYING_LAND_BACK",
	DYING_SKY					= "LOW_SHADOW_DEFENDER_FD_DYING_SKY",

	REVENGE_ATTACK				= "",	
	
	
	COMMON_FRAME_FUNC           = "LOW_SHADOW_DEFENDER_FD_COMMON_FRAME_MOVE_FUNC",	
}



INIT_AI = 
{
	TARGET = 
	{
		TARGET_PRIORITY 			= TARGET_PRIORITY["TP_LOW_HP_FIRST"],
		TARGET_INTERVAL				= 1,		-- sec
		TARGET_NEAR_RANGE			= 800,		-- 이 거리보다 가까우면 TARGET_SUCCESS_RATE에 관계없이 무조건 타게팅된다
		TARGET_RANGE				= 900,		-- cm
		TARGET_LOST_RANGE			= 1000,		-- cm
		TARGET_SUCCESS_RATE			= 100,  --50,		-- %
		ATTACK_TARGET_RATE			= 70, -- 30,		-- 나를 공격한 유닛을 타게팅할 확률
		PRESERVE_LAST_TARGET_RATE	= 70, -- 30,		-- 이전에 타게팅된 유닛을 계속 타게팅할 확률
		TARGET_HEIGHT_LIMIT			= 50,
	},

	CHASE_MOVE = 
	{		
		MOVE_SPLIT_RANGE	= 500,
		DEST_GAP			= 800,	-- 목적지에서 이 거리 안에 있으면 도착했다고 판단한다
		MOVE_GAP			= 500,
		
		DIR_CHANGE_INTERVAL = 0.7,
		
		WALK_INTERVAL		= 2,
		NEAR_WALK_RATE		= 100,   --  70,
		FAR_WALK_RATE		= 100,   -- 30,
		
		JUMP_INTERVAL		= 5,
		UP_JUMP_RATE		= 0, -- 40,
		UP_DOWN_RATE		= 0,
		DOWN_JUMP_RATE		= 0,    --  20,
		DOWN_DOWN_RATE		= 0,
		
		LINE_END_RANGE		= 80,	-- cm
	},	
	
	PATROL_MOVE = 	
	{
		PATROL_BEGIN_RATE		= 100, --50,		
		PATROL_RANGE			= 200,
		PATROL_COOL_TIME		= 4,
		ONLY_THIS_LINE_GROUP	= TRUE,
	},
	
	ESCAPE_MOVE = 
	{		
		MOVE_SPLIT_RANGE	= 600,	-- cm
		ESCAPE_GAP			= 800,	-- 이 거리 보다 멀어지면 도망 성공
		
		WALK_INTERVAL		= 1.0,	-- 초
		NEAR_WALK_RATE		= 100,   --  10,
		FAR_WALK_RATE		= 100,   -- 10,
		
		JUMP_INTERVAL		= 10,
		UP_JUMP_RATE		= 0, -- 30,
		UP_DOWN_RATE		= 0,
		DOWN_JUMP_RATE		= 0,    --  30,
		DOWN_DOWN_RATE		= 0,
		
		LINE_END_RANGE		= 80,	-- cm
	},
	
	ESCAPE_CONDITION =
	{
		RATE				= 100,
		ESCAPE_RANGE		= 500,
	}
}




LOW_SHADOW_DEFENDER_FD_START = 
{
	ANIM_NAME					= "Wait",
	PLAY_TYPE					= XSKIN_ANIM_PLAYTYPE["XAP_LOOP"],
	TRANSITION					= FALSE,
	
	CAN_PUSH_UNIT				= TRUE,
	CAN_PASS_UNIT				= FALSE,
	IMMADIATE_PACKET_SEND		= TRUE,	
	
	EVENT_PROCESS = 
	{		
		{ STATE_CHANGE_TYPE["SCT_CONDITION_TABLE"],		"LOW_SHADOW_DEFENDER_FD_WAIT",		"CT_LOW_SHADOW_DEFENDER_FD_WAIT"				},
	},
	
	CT_LOW_SHADOW_DEFENDER_FD_WAIT = 
	{
		STATE_TIME_OVER			= 2.8,
	},
}



LOW_SHADOW_DEFENDER_FD_WAIT = 
{
	ANIM_NAME					= "Wait",
	PLAY_TYPE					= XSKIN_ANIM_PLAYTYPE["XAP_LOOP"],
	TRANSITION					= TRUE,
	LAND_CONNECT				= TRUE,
	
	CAN_PUSH_UNIT				= FALSE,
	CAN_PASS_UNIT				= FALSE,	
	
	SPEED_X						= 0,
	SPEED_Y						= 0,
	
	PASSIVE_SPEED_X				= 0,
	
	IMMADIATE_PACKET_SEND		= TRUE,
	EVENT_INTERVAL_TIME0		= 0.2,
	
	
	EVENT_PROCESS = 
	{		
		
		{ STATE_CHANGE_TYPE["SCT_FOOT_ON_LINE_FALSE_DOWN"],	"LOW_SHADOW_DEFENDER_FD_JUMP_DOWN",					},

		{ STATE_CHANGE_TYPE["SCT_CONDITION_TABLE"],			"LOW_SHADOW_DEFENDER_FD_ATTACK_A_READY",			"CT_LOW_SHADOW_DEFENDER_FD_ATTACK_A_READY",	},

		{ STATE_CHANGE_TYPE["SCT_AI_WALK"],					"LOW_SHADOW_DEFENDER_FD_WALK",						},
		{ STATE_CHANGE_TYPE["SCT_AI_DASH"],					"LOW_SHADOW_DEFENDER_FD_DASH",						},
		{ STATE_CHANGE_TYPE["SCT_AI_JUMP"],					"LOW_SHADOW_DEFENDER_FD_JUMP_UP",					},
		{ STATE_CHANGE_TYPE["SCT_AI_JUMP_DIR"],				"LOW_SHADOW_DEFENDER_FD_JUMP_UP_DIR",				},
		{ STATE_CHANGE_TYPE["SCT_AI_DOWN"],					"LOW_SHADOW_DEFENDER_FD_JUMP_DOWN",					},
		{ STATE_CHANGE_TYPE["SCT_AI_DOWN_DIR"],				"LOW_SHADOW_DEFENDER_FD_JUMP_DOWN_DIR",				},
	},
	

	CT_LOW_SHADOW_DEFENDER_FD_ATTACK_A_READY = 
	{
		HAVE_TARGET					= 1,
		DISTANCE_TO_TARGET_NEAR		= 800,
		RATE						= 100,
	},
}




LOW_SHADOW_DEFENDER_FD_WAIT_HABIT = 
{
	ANIM_NAME					= "Wait",
	PLAY_TYPE					= XSKIN_ANIM_PLAYTYPE["XAP_ONE_WAIT"],
	TRANSITION					= FALSE,
	
	CAN_PUSH_UNIT				= FALSE,
	CAN_PASS_UNIT				= FALSE,
	IMMADIATE_PACKET_SEND		= TRUE,
	
	EVENT_PROCESS = 
	{		
		{ STATE_CHANGE_TYPE["SCT_FOOT_ON_LINE_FALSE_DOWN"],	"LOW_SHADOW_DEFENDER_FD_JUMP_DOWN",				},
		{ STATE_CHANGE_TYPE["SCT_MOTION_END"],				"LOW_SHADOW_DEFENDER_FD_WAIT",						},
	},
}


LOW_SHADOW_DEFENDER_FD_WALK = 
{
	ANIM_SPEED					= 0.6,
	ANIM_NAME					= "Dash",
	PLAY_TYPE					= XSKIN_ANIM_PLAYTYPE["XAP_LOOP"],
	TRANSITION					= FALSE,
	LAND_CONNECT				= TRUE,
	
	CAN_PUSH_UNIT				= TRUE,
	CAN_PASS_UNIT				= FALSE,
	
	PASSIVE_SPEED_X				= 150,
	
	ALLOW_DIR_CHANGE			= TRUE,
	IMMADIATE_PACKET_SEND		= TRUE,
	
	EVENT_INTERVAL_TIME0		= 0.2,
	EVENT_INTERVAL_TIME1		= 3,
	
	EVENT_PROCESS = 
	{		
		
		{ STATE_CHANGE_TYPE["SCT_FOOT_ON_LINE_FALSE_DOWN"],	"LOW_SHADOW_DEFENDER_FD_JUMP_DOWN_DIR",				},
		
		{ STATE_CHANGE_TYPE["SCT_CONDITION_TABLE"],			"LOW_SHADOW_DEFENDER_FD_ATTACK_A_READY",			"CT_LOW_SHADOW_DEFENDER_FD_ATTACK_A_READY",	},
		
		{ STATE_CHANGE_TYPE["SCT_AI_WAIT"],					"LOW_SHADOW_DEFENDER_FD_WAIT",						},
		{ STATE_CHANGE_TYPE["SCT_AI_DASH"],					"LOW_SHADOW_DEFENDER_FD_DASH",						},
		{ STATE_CHANGE_TYPE["SCT_AI_JUMP"],					"LOW_SHADOW_DEFENDER_FD_JUMP_UP",					},
		{ STATE_CHANGE_TYPE["SCT_AI_JUMP_DIR"],				"LOW_SHADOW_DEFENDER_FD_JUMP_UP_DIR",				},
		{ STATE_CHANGE_TYPE["SCT_AI_DOWN"],					"LOW_SHADOW_DEFENDER_FD_JUMP_DOWN",					},
		{ STATE_CHANGE_TYPE["SCT_AI_DOWN_DIR"],				"LOW_SHADOW_DEFENDER_FD_JUMP_DOWN_DIR",				},
	},
	
	
	CT_LOW_SHADOW_DEFENDER_FD_ATTACK_A_READY = 
	{
		HAVE_TARGET					= 1,
		DISTANCE_TO_TARGET_NEAR		= 1000,
		RATE						= 100,
	},
}


LOW_SHADOW_DEFENDER_FD_DASH = 
{
	ANIM_NAME					= "Dash",
	PLAY_TYPE					= XSKIN_ANIM_PLAYTYPE["XAP_LOOP"],
	TRANSITION					= FALSE,
	LAND_CONNECT				= TRUE,
	
	--SUPER_ARMOR					= TRUE,

	CAN_PUSH_UNIT				= FALSE,
	CAN_PASS_UNIT				= FALSE,
	PASSIVE_SPEED_X				= 350,
	
	ALLOW_DIR_CHANGE			= FALSE,
	IMMADIATE_PACKET_SEND		= TRUE,
	
	EVENT_INTERVAL_TIME0		= 2,
	EVENT_PROCESS = 
	{		
		{ STATE_CHANGE_TYPE["SCT_FOOT_ON_LINE_FALSE_DOWN"],		"LOW_SHADOW_DEFENDER_FD_JUMP_DOWN_DIR",			},
		
		{ STATE_CHANGE_TYPE["SCT_AI_WAIT"],					"LOW_SHADOW_DEFENDER_FD_WAIT",						},
		{ STATE_CHANGE_TYPE["SCT_AI_WALK"],					"LOW_SHADOW_DEFENDER_FD_DASH",						},
		{ STATE_CHANGE_TYPE["SCT_AI_JUMP"],					"LOW_SHADOW_DEFENDER_FD_JUMP_UP",					},
		{ STATE_CHANGE_TYPE["SCT_AI_JUMP_DIR"],				"LOW_SHADOW_DEFENDER_FD_JUMP_UP_DIR",				},
		{ STATE_CHANGE_TYPE["SCT_AI_DOWN"],					"LOW_SHADOW_DEFENDER_FD_JUMP_DOWN",					},
		{ STATE_CHANGE_TYPE["SCT_AI_DOWN_DIR"],				"LOW_SHADOW_DEFENDER_FD_JUMP_DOWN_DIR",				},
		{ STATE_CHANGE_TYPE["SCT_CONDITION_FUNCTION"],			"LOW_SHADOW_DEFENDER_FD_DASH_END",						"CF_LOW_SHADOW_DEFENDER_FD_DASH_END",				},		
	},
}





LOW_SHADOW_DEFENDER_FD_DASH_END = 
{
	ANIM_NAME					= "DashEnd",
	PLAY_TYPE					= XSKIN_ANIM_PLAYTYPE["XAP_ONE_WAIT"],
	TRANSITION					= FALSE,
	
	LAND_CONNECT				= FALSE,

	CAN_PUSH_UNIT				= FALSE,
	CAN_PASS_UNIT				= FALSE,
	
	--SPEED_X						= INIT_PHYSIC["RUN_SPEED"],
	
	ALLOW_DIR_CHANGE			= FALSE,
	IMMADIATE_PACKET_SEND		= TRUE,
	
	EVENT_PROCESS = 
	{		
		--{ STATE_CHANGE_TYPE["SCT_FOOT_ON_LINE_FALSE_DOWN"],	"LOW_SHADOW_DEFENDER_FD_JUMP_DOWN_DIR",				},
		{ STATE_CHANGE_TYPE["SCT_MOTION_END"],				"LOW_SHADOW_DEFENDER_FD_WAIT",						},
	},
}




LOW_SHADOW_DEFENDER_FD_JUMP_UP = 
{
	ANIM_NAME					= "JumpUp",
	PLAY_TYPE					= XSKIN_ANIM_PLAYTYPE["XAP_LOOP"],
	TRANSITION					= TRUE,
	LAND_CONNECT				= FALSE,
	
	CAN_PUSH_UNIT				= TRUE,
	CAN_PASS_UNIT				= FALSE,
	
	SPEED_X						= 0,
	SPEED_Y						= INIT_PHYSIC["JUMP_SPEED"],
	
	ADD_POS_Y					= 45, 
	
	IMMADIATE_PACKET_SEND		= TRUE,
	
	EVENT_PROCESS = 
	{		
		{ STATE_CHANGE_TYPE["SCT_NEGATIVE_Y_SPEED"],		"LOW_SHADOW_DEFENDER_FD_JUMP_DOWN",			},
		
	},	
}

LOW_SHADOW_DEFENDER_FD_JUMP_DOWN = 
{
	ANIM_NAME					= "JumpDown",
	PLAY_TYPE					= XSKIN_ANIM_PLAYTYPE["XAP_LOOP"],
	TRANSITION					= TRUE,
	LAND_CONNECT				= FALSE,
	
	CAN_PUSH_UNIT				= TRUE,
	CAN_PASS_UNIT				= FALSE,
		 	
	IMMADIATE_PACKET_SEND		= TRUE,
		
	EVENT_PROCESS = 
	{		
		{ STATE_CHANGE_TYPE["SCT_FOOT_ON_LINE_TRUE"],		"LOW_SHADOW_DEFENDER_FD_JUMP_LANDING",				},
	},
}

LOW_SHADOW_DEFENDER_FD_JUMP_UP_DIR = 
{
	ANIM_NAME					= "JumpUp",
	PLAY_TYPE					= XSKIN_ANIM_PLAYTYPE["XAP_LOOP"],
	TRANSITION					= TRUE,
	LAND_CONNECT				= FALSE,
	
	CAN_PUSH_UNIT				= TRUE,
	CAN_PASS_UNIT				= FALSE,
		
	PASSIVE_SPEED_X				= INIT_PHYSIC["WALK_SPEED"],
	SPEED_Y						= INIT_PHYSIC["JUMP_SPEED"],
	
	ADD_POS_Y					= 45, 
	
	IMMADIATE_PACKET_SEND		= TRUE,
	
	EVENT_PROCESS = 
	{		
		{ STATE_CHANGE_TYPE["SCT_NEGATIVE_Y_SPEED"],		"LOW_SHADOW_DEFENDER_FD_JUMP_DOWN_DIR",				},
	},
	
}

LOW_SHADOW_DEFENDER_FD_JUMP_DOWN_DIR = 
{
	ANIM_NAME					= "JumpDown",
	PLAY_TYPE					= XSKIN_ANIM_PLAYTYPE["XAP_LOOP"],
	TRANSITION					= TRUE,
	LAND_CONNECT				= FALSE,
	
	CAN_PUSH_UNIT				= TRUE,
	CAN_PASS_UNIT				= FALSE,
	
	PASSIVE_SPEED_X				= INIT_PHYSIC["WALK_SPEED"],
	 
	IMMADIATE_PACKET_SEND		= TRUE,
		
	EVENT_PROCESS = 
	{		
		{ STATE_CHANGE_TYPE["SCT_FOOT_ON_LINE_TRUE"],		"LOW_SHADOW_DEFENDER_FD_JUMP_LANDING",				},
	},
}

LOW_SHADOW_DEFENDER_FD_JUMP_LANDING = 
{
	ANIM_NAME					= "Wait",
	PLAY_TYPE					= XSKIN_ANIM_PLAYTYPE["XAP_ONE_WAIT"],
	TRANSITION					= TRUE,
	LAND_CONNECT				= FALSE,
	
	CAN_PUSH_UNIT				= TRUE,
	CAN_PASS_UNIT				= FALSE,
	
	SPEED_X						= 300,
	SPEED_Y						= 0,

	IMMADIATE_PACKET_SEND		= TRUE,

	EVENT_PROCESS = 
	{		
		{ STATE_CHANGE_TYPE["SCT_FOOT_ON_LINE_FALSE_DOWN"],	"LOW_SHADOW_DEFENDER_FD_JUMP_DOWN",					},
		{ STATE_CHANGE_TYPE["SCT_MOTION_END"],				"LOW_SHADOW_DEFENDER_FD_WAIT",						},
	},
}

LOW_SHADOW_DEFENDER_FD_STAND_UP_ATTACK_FRONT = 
{
	ANIM_NAME					= "StandUpAttackFront",
	PLAY_TYPE					= XSKIN_ANIM_PLAYTYPE["XAP_ONE_WAIT"],
	TRANSITION					= FALSE,
	LAND_CONNECT				= FALSE,	
	MIND_FLAG					= MIND_FLAG["MF_STAND_UP_ATTACK"],
	
	SUPER_ARMOR					= TRUE,
	DEFENCE						= { 0, 100, 50, },
	
	CAN_PUSH_UNIT				= TRUE,
	CAN_PASS_UNIT				= FALSE,
	
	SOUND_PLAY0					= { 1.0, "Shadow_Defender_StandUpAttackFront.ogg" },
	
	EVENT_PROCESS = 
	{
		{ STATE_CHANGE_TYPE["SCT_FOOT_ON_LINE_FALSE_DOWN"],	"LOW_SHADOW_DEFENDER_FD_JUMP_DOWN",			},
		{ STATE_CHANGE_TYPE["SCT_MOTION_END"],				"LOW_SHADOW_DEFENDER_FD_WAIT",				},
	},

		
	ATTACK_TIME0				= { 1.233, 1.8, },	
	
	DAMAGE_DATA = 
	{
		DAMAGE_TYPE		= DAMAGE_TYPE["DT_PHYSIC"],
		HIT_TYPE		= HIT_TYPE["HT_SWORD_SLASH"],
		REACT_TYPE		= REACT_TYPE["RT_DOWN"],
		
		DAMAGE = 
		{
			PHYSIC		= 1.0,
		},
		
		BACK_SPEED_X			= INIT_PHYSIC["RUN_SPEED"],
		BACK_SPEED_Y			= 0.0,
		
		STOP_TIME_ATT			= 0.0,		
		STOP_TIME_DEF			= 0.0,	
		CAMERA_CRASH_GAP		= 5.0,	
		CAMERA_CRASH_TIME		= 0.2,
		CLEAR_SCREEN			= 0.0,	
		CLEAR_SCREEN_COLOR_A	= 0.0,
		CLEAR_SCREEN_COLOR_R	= 1.0,
		CLEAR_SCREEN_COLOR_G	= 1.0,
		CLEAR_SCREEN_COLOR_B	= 1.0,

		RE_ATTACK				= FALSE,		
		HIT_GAP					= 0.0,				
	},
}


LOW_SHADOW_DEFENDER_FD_STAND_UP_ATTACK_BACK = 
{
	ANIM_NAME					= "StandUpAttackBack",
	PLAY_TYPE					= XSKIN_ANIM_PLAYTYPE["XAP_ONE_WAIT"],
	TRANSITION					= FALSE,
	LAND_CONNECT				= FALSE,
	MIND_FLAG				= MIND_FLAG["MF_STAND_UP_ATTACK"],
	
	SUPER_ARMOR					= TRUE,
	DEFENCE						= { 0, 100, 50, },
		
	CAN_PUSH_UNIT				= TRUE,
	CAN_PASS_UNIT				= FALSE,
	
	--FLIP_DIR_END				= TRUE,
	
	SOUND_PLAY0					= { 0.8, "Shadow_Defender_StandUpAttackBack.ogg" },
	
	EVENT_PROCESS = 
	{
		{ STATE_CHANGE_TYPE["SCT_FOOT_ON_LINE_FALSE_DOWN"],	"LOW_SHADOW_DEFENDER_FD_JUMP_DOWN", },
		{ STATE_CHANGE_TYPE["SCT_MOTION_END"],					"LOW_SHADOW_DEFENDER_FD_WAIT", },
	},	
	
		
	ATTACK_TIME0				= { 0.833 , 1.5, },	
	
	DAMAGE_DATA = 
	{
		DAMAGE_TYPE		= DAMAGE_TYPE["DT_PHYSIC"],
		HIT_TYPE		= HIT_TYPE["HT_SWORD_SLASH"],
		REACT_TYPE		= REACT_TYPE["RT_DOWN"],
		
		DAMAGE = 
		{
			PHYSIC		= 1.0,
		},
		
		BACK_SPEED_X			= INIT_PHYSIC["RUN_SPEED"],
		BACK_SPEED_Y			= 0.0,
		
		STOP_TIME_ATT			= 0.0,		
		STOP_TIME_DEF			= 0.0,	
		CAMERA_CRASH_GAP		= 5.0,	
		CAMERA_CRASH_TIME		= 0.2,
		CLEAR_SCREEN			= 0.0,	
		CLEAR_SCREEN_COLOR_A	= 0.0,
		CLEAR_SCREEN_COLOR_R	= 1.0,
		CLEAR_SCREEN_COLOR_G	= 1.0,
		CLEAR_SCREEN_COLOR_B	= 1.0,

		RE_ATTACK				= FALSE,		
		HIT_GAP					= 0.0,				
	},
	
	DISABLE_ATTACK_BOX = 
	{
		"ATTACK_SPHERE1_Head",
	},
}


LOW_SHADOW_DEFENDER_FD_ATTACK_A_READY = 
{
	ANIM_NAME					= "AttackA_Ready",
	PLAY_TYPE					= XSKIN_ANIM_PLAYTYPE["XAP_ONE_WAIT"],
	TRANSITION					= TRUE,
	
	CAN_PUSH_UNIT				= TRUE,
	CAN_PASS_UNIT				= FALSE,

	SPEED_X				= 0,
	SPEED_Y						= 0,	

	SOUND_PLAY0					= { 0.2, "Shadow_Defender_AttackA_Ready.ogg" },	
	
	VIEW_TARGET					= TRUE,
	ALLOW_DIR_CHANGE			= FALSE,	
	IMMADIATE_PACKET_SEND		= TRUE,
	
	EVENT_PROCESS = 
	{		
		{ STATE_CHANGE_TYPE["SCT_CONDITION_TABLE"],				"LOW_SHADOW_DEFENDER_FD_ATTACK_A",	 "CT_LOW_SHADOW_DEFENDER_FD_ATTACK_C"	},		
	},	

	CT_LOW_SHADOW_DEFENDER_FD_ATTACK_C = 
	{
		STATE_TIME_OVER			= 1.2,
	},
}

LOW_SHADOW_DEFENDER_FD_ATTACK_A = 
{
	ANIM_NAME					= "AttackA",
	PLAY_TYPE					= XSKIN_ANIM_PLAYTYPE["XAP_ONE_WAIT"],
	TRANSITION					= TRUE,
	
	CAN_PUSH_UNIT				= TRUE,
	CAN_PASS_UNIT				= FALSE,

	SOUND_PLAY0					= { 0.001, "Shadow_Defender_AttackA.ogg" },
	
	VIEW_TARGET					= FALSE,
	ALLOW_DIR_CHANGE			= FALSE,	
	IMMADIATE_PACKET_SEND		= TRUE,
	
	EVENT_PROCESS = 
	{	
		{ STATE_CHANGE_TYPE["SCT_FOOT_ON_LINE_FALSE_DOWN"],	"LOW_SHADOW_DEFENDER_FD_JUMP_DOWN",			},
		{ STATE_CHANGE_TYPE["SCT_MOTION_END"],				"LOW_SHADOW_DEFENDER_FD_WAIT",						},
	},
	
	
}

LOW_SHADOW_DEFENDER_FD_ATTACK_B = 
{
	ANIM_NAME					= "AttackA",
	PLAY_TYPE					= XSKIN_ANIM_PLAYTYPE["XAP_ONE_WAIT"],
	TRANSITION					= TRUE,
	
	CAN_PUSH_UNIT				= TRUE,
	CAN_PASS_UNIT				= FALSE,

	SOUND_PLAY0					= { 0.001, "Shadow_Defender_AttackA.ogg" },
	
	VIEW_TARGET					= FALSE,
	ALLOW_DIR_CHANGE			= FALSE,	
	IMMADIATE_PACKET_SEND		= TRUE,
	
	EVENT_PROCESS = 
	{	
		{ STATE_CHANGE_TYPE["SCT_FOOT_ON_LINE_FALSE_DOWN"],	"LOW_SHADOW_DEFENDER_FD_JUMP_DOWN",			},
		{ STATE_CHANGE_TYPE["SCT_MOTION_END"],				"LOW_SHADOW_DEFENDER_FD_WAIT",						},
	},
	
	
}

LOW_SHADOW_DEFENDER_FD_ATTACK_C = 
{
	ANIM_NAME					= "AttackA",
	PLAY_TYPE					= XSKIN_ANIM_PLAYTYPE["XAP_ONE_WAIT"],
	TRANSITION					= TRUE,
	
	CAN_PUSH_UNIT				= TRUE,
	CAN_PASS_UNIT				= FALSE,

	SOUND_PLAY0					= { 0.001, "Shadow_Defender_AttackA.ogg" },
	
	VIEW_TARGET					= FALSE,
	ALLOW_DIR_CHANGE			= FALSE,	
	IMMADIATE_PACKET_SEND		= TRUE,
	
	EVENT_PROCESS = 
	{	
		{ STATE_CHANGE_TYPE["SCT_FOOT_ON_LINE_FALSE_DOWN"],	"LOW_SHADOW_DEFENDER_FD_JUMP_DOWN",			},
		{ STATE_CHANGE_TYPE["SCT_MOTION_END"],				"LOW_SHADOW_DEFENDER_FD_WAIT",						},
	},
	
	
}


LOW_SHADOW_DEFENDER_FD_SPECIAL_ATTACK_A =
{
	ANIM_NAME					= "SpecialAttackA",
	ANIM_SPEED					= 1.5,
	PLAY_TYPE					= XSKIN_ANIM_PLAYTYPE["XAP_ONE_WAIT"],
	TRANSITION					= FALSE,

	CAN_PUSH_UNIT				= FALSE,
	CAN_PASS_UNIT				= FALSE,
	
    SOUND_PLAY0					= { 0.7, "Shadow_Defender_SpecialAttackA.ogg" },

	SPEED_X						= 0,
	SPEED_Y						= 0,	
	
	VIEW_TARGET					= TRUE,
	ALLOW_DIR_CHANGE			= FALSE,	
	IMMADIATE_PACKET_SEND		= TRUE,
	
	EVENT_PROCESS = 
	{	
		{ STATE_CHANGE_TYPE["SCT_FOOT_ON_LINE_FALSE_DOWN"],	"LOW_SHADOW_DEFENDER_FD_JUMP_DOWN",								},
		{ STATE_CHANGE_TYPE["SCT_MOTION_END"],	"LOW_SHADOW_DEFENDER_FD_WAIT",								},
	},

	EFFECT_SET_LIST =
	{
	},
}




LOW_SHADOW_DEFENDER_FD_DAMAGE_REVENGE = 
{
	ANIM_NAME					= "DamageRevenge",
	PLAY_TYPE					= XSKIN_ANIM_PLAYTYPE["XAP_ONE_WAIT"],
	TRANSITION					= FALSE,
	LAND_CONNECT				= FALSE,
	
	CAN_PUSH_UNIT				= TRUE,
	CAN_PASS_UNIT				= FALSE,
	
	SOUND_PLAY0					= { 0.001, "Shadow_Defender_DamageRevenge.ogg" },
	
	EVENT_PROCESS = 
	{
		{ STATE_CHANGE_TYPE["SCT_MOTION_END"],					"LOW_SHADOW_DEFENDER_FD_WAIT",												},
	},
}


LOW_SHADOW_DEFENDER_FD_DAMAGE_FRONT = 
{
	ANIM_NAME					= "DamageFront",
	PLAY_TYPE					= XSKIN_ANIM_PLAYTYPE["XAP_ONE_WAIT"],
	TRANSITION					= FALSE,
	LAND_CONNECT				= FALSE,
	
	CAN_PUSH_UNIT				= TRUE,
	CAN_PASS_UNIT				= FALSE,
	
	EVENT_PROCESS = 
	{
		{ STATE_CHANGE_TYPE["SCT_MOTION_END"],					"LOW_SHADOW_DEFENDER_FD_WAIT",												},
	},
}

LOW_SHADOW_DEFENDER_FD_DAMAGE_BACK = 
{
	ANIM_NAME					= "DamageBack",
	PLAY_TYPE					= XSKIN_ANIM_PLAYTYPE["XAP_ONE_WAIT"],
	TRANSITION					= FALSE,
	LAND_CONNECT				= FALSE,
	
	CAN_PUSH_UNIT				= TRUE,
	CAN_PASS_UNIT				= FALSE,
	
	EVENT_PROCESS = 
	{
		{ STATE_CHANGE_TYPE["SCT_MOTION_END"],					"LOW_SHADOW_DEFENDER_FD_WAIT",												},
	},
}

LOW_SHADOW_DEFENDER_FD_DAMAGE_BIG_BACK = 
{
	ANIM_NAME					= "DamageBack",
	PLAY_TYPE					= XSKIN_ANIM_PLAYTYPE["XAP_ONE_WAIT"],
	TRANSITION					= FALSE,
	LAND_CONNECT				= FALSE,
	
	CAN_PUSH_UNIT				= TRUE,
	CAN_PASS_UNIT				= FALSE,
		
	EVENT_INTERVAL_TIME0		= 1,
	
	EVENT_PROCESS = 
	{
		{ STATE_CHANGE_TYPE["SCT_MOTION_END"],					"LOW_SHADOW_DEFENDER_FD_WAIT",													},
	},
}

LOW_SHADOW_DEFENDER_FD_DAMAGE_BIG_FRONT = 
{
	ANIM_NAME					= "DamageFront",
	PLAY_TYPE					= XSKIN_ANIM_PLAYTYPE["XAP_ONE_WAIT"],
	TRANSITION					= FALSE,
	LAND_CONNECT				= FALSE,
	
	CAN_PUSH_UNIT				= TRUE,
	CAN_PASS_UNIT				= FALSE,

	EVENT_INTERVAL_TIME0		= 1,
	
	EVENT_PROCESS = 
	{
		{ STATE_CHANGE_TYPE["SCT_MOTION_END"],					"LOW_SHADOW_DEFENDER_FD_WAIT",												},
	},
}





LOW_SHADOW_DEFENDER_FD_DAMAGE_DOWN_FRONT = 
{
	ANIM_NAME					= "DamageDownFront",
	PLAY_TYPE					= XSKIN_ANIM_PLAYTYPE["XAP_ONE_WAIT"],
	TRANSITION					= FALSE,
	LAND_CONNECT				= FALSE,

	SUPER_ARMOR					= TRUE,
	DEFENCE						= { 0, 100, 50, },

    CAN_PUSH_UNIT				= TRUE,
	CAN_PASS_UNIT				= FALSE,

	
	EVENT_PROCESS = 
	{
		{ STATE_CHANGE_TYPE["SCT_FOOT_ON_LINE_FALSE_DOWN"],		"LOW_SHADOW_DEFENDER_FD_DAMAGE_AIR_FALL",			},
		{ STATE_CHANGE_TYPE["SCT_MOTION_END"],					"LOW_SHADOW_DEFENDER_FD_STAND_UP_FRONT",			},
	},
}

LOW_SHADOW_DEFENDER_FD_DAMAGE_DOWN_BACK = 
{
	ANIM_NAME					= "DamageDownBack",
	PLAY_TYPE					= XSKIN_ANIM_PLAYTYPE["XAP_ONE_WAIT"],
	TRANSITION					= FALSE,
	LAND_CONNECT				= FALSE,
	
	SUPER_ARMOR					= TRUE,
	DEFENCE						= { 0, 100, 50, },

	CAN_PUSH_UNIT				= TRUE,
	CAN_PASS_UNIT				= FALSE,
	
	EVENT_PROCESS = 
	{
		{ STATE_CHANGE_TYPE["SCT_FOOT_ON_LINE_FALSE_DOWN"],		"LOW_SHADOW_DEFENDER_FD_DAMAGE_AIR_FALL",			},
		{ STATE_CHANGE_TYPE["SCT_MOTION_END"],					"LOW_SHADOW_DEFENDER_FD_STAND_UP_BACK",			},
	},
}

LOW_SHADOW_DEFENDER_FD_DAMAGE_FLY_FRONT = 
{
	ANIM_NAME					= "DamageAirFlyFront",
	PLAY_TYPE					= XSKIN_ANIM_PLAYTYPE["XAP_ONE_WAIT"],
	TRANSITION					= TRUE,
	LAND_CONNECT				= FALSE,	
		
	CAN_PUSH_UNIT				= TRUE,
	CAN_PASS_UNIT				= FALSE,
	
	EVENT_PROCESS = 
	{
		{ STATE_CHANGE_TYPE["SCT_FOOT_ON_LINE_TRUE"],			"LOW_SHADOW_DEFENDER_FD_DAMAGE_AIR_DOWN_LANDING",		},
	},
}

LOW_SHADOW_DEFENDER_FD_DAMAGE_FLY_BACK = 
{
	ANIM_NAME					= "DamageAirFlyBack",
	PLAY_TYPE					= XSKIN_ANIM_PLAYTYPE["XAP_ONE_WAIT"],
	TRANSITION					= FALSE,
	LAND_CONNECT				= FALSE,	
	
	CAN_PUSH_UNIT				= TRUE,
	CAN_PASS_UNIT				= FALSE,
	
	EVENT_PROCESS = 
	{
		{ STATE_CHANGE_TYPE["SCT_FOOT_ON_LINE_TRUE"],			"LOW_SHADOW_DEFENDER_FD_DAMAGE_DOWN_BACK",		},
	},
}

LOW_SHADOW_DEFENDER_FD_DAMAGE_AIR = 
{
	ANIM_NAME					= "DamageAirSmall",
	PLAY_TYPE					= XSKIN_ANIM_PLAYTYPE["XAP_ONE_WAIT"],
	TRANSITION					= FALSE,
	LAND_CONNECT				= FALSE,
	
	CAN_PUSH_UNIT				= TRUE,
	CAN_PASS_UNIT				= FALSE,
	
	EVENT_PROCESS = 
	{
		{ STATE_CHANGE_TYPE["SCT_FOOT_ON_LINE_TRUE"],			"LOW_SHADOW_DEFENDER_FD_WAIT",					},
	},
	
	VIEW_TARGET					= TRUE,
	ALLOW_DIR_CHANGE			= TRUE,
}

LOW_SHADOW_DEFENDER_FD_DAMAGE_AIR_DOWN = 
{
	ANIM_NAME					= "DamageAirDown",
	PLAY_TYPE					= XSKIN_ANIM_PLAYTYPE["XAP_ONE_WAIT"],
	TRANSITION					= FALSE,
	LAND_CONNECT				= FALSE,
	
	CAN_PUSH_UNIT				= TRUE,
	CAN_PASS_UNIT				= FALSE,
	
	EVENT_PROCESS = 
	{
		{ STATE_CHANGE_TYPE["SCT_FOOT_ON_LINE_TRUE"],			"LOW_SHADOW_DEFENDER_FD_DAMAGE_AIR_DOWN_LANDING",	},
	},
}

LOW_SHADOW_DEFENDER_FD_DAMAGE_AIR_UP = 
{
	ANIM_NAME					= "DamageAirUp",
	PLAY_TYPE					= XSKIN_ANIM_PLAYTYPE["XAP_ONE_WAIT"],
	TRANSITION					= FALSE,
	LAND_CONNECT				= FALSE,
	
	CAN_PUSH_UNIT				= TRUE,
	CAN_PASS_UNIT				= FALSE,
	
	--PASSIVE_SPEED_Y				= -1,
	--SPEED_Y						= INIT_PHYSIC["JUMP_SPEED"] * 0.6,
	
		
	EVENT_PROCESS = 
	{
		{ STATE_CHANGE_TYPE["SCT_NEGATIVE_Y_SPEED"],		"LOW_SHADOW_DEFENDER_FD_DAMAGE_AIR_FALL",			},
		{ STATE_CHANGE_TYPE["SCT_FOOT_ON_LINE_TRUE"],		"LOW_SHADOW_DEFENDER_FD_DAMAGE_AIR_DOWN_LANDING",	},
	},
}

LOW_SHADOW_DEFENDER_FD_DAMAGE_AIR_FALL = 
{
	ANIM_NAME					= "DamageAirFall",
	PLAY_TYPE					= XSKIN_ANIM_PLAYTYPE["XAP_ONE_WAIT"],
	TRANSITION					= FALSE,
	LAND_CONNECT				= FALSE,
	
	CAN_PUSH_UNIT				= TRUE,
	CAN_PASS_UNIT				= FALSE,
	
	EVENT_PROCESS = 
	{
		{ STATE_CHANGE_TYPE["SCT_POSITIVE_Y_SPEED"],		"LOW_SHADOW_DEFENDER_FD_DAMAGE_AIR_UP",			},
		{ STATE_CHANGE_TYPE["SCT_FOOT_ON_LINE_TRUE"],		"LOW_SHADOW_DEFENDER_FD_DAMAGE_AIR_DOWN_LANDING",	},
	},
}

LOW_SHADOW_DEFENDER_FD_DAMAGE_AIR_DOWN_LANDING = 
{
	ANIM_NAME					= "DamageAirDown",
	PLAY_TYPE					= XSKIN_ANIM_PLAYTYPE["XAP_ONE_WAIT"],
	TRANSITION					= FALSE,
	LAND_CONNECT				= FALSE,
	
	SUPER_ARMOR					= TRUE,
	DEFENCE						= { 0, 100, 50, },

	CAN_PUSH_UNIT				= TRUE,
	CAN_PASS_UNIT				= FALSE,
	
	EVENT_PROCESS = 
	{
		{ STATE_CHANGE_TYPE["SCT_FOOT_ON_LINE_FALSE_DOWN"],	"LOW_SHADOW_DEFENDER_FD_DAMAGE_AIR_FALL",			},
		{ STATE_CHANGE_TYPE["SCT_MOTION_END"],				"LOW_SHADOW_DEFENDER_FD_STAND_UP_FRONT",			},
	},
}

LOW_SHADOW_DEFENDER_FD_STAND_UP_FRONT = 
{
	ANIM_NAME					= "DamageStandUpFront",
	PLAY_TYPE					= XSKIN_ANIM_PLAYTYPE["XAP_ONE_WAIT"],
	TRANSITION					= FALSE,
	LAND_CONNECT				= FALSE,
	SUPER_ARMOR					= TRUE,
	
	DEFENCE						= { 0, 100, 50, },
	
	CAN_PUSH_UNIT				= TRUE,
	CAN_PASS_UNIT				= FALSE,
	
	EVENT_PROCESS = 
	{
		{ STATE_CHANGE_TYPE["SCT_FOOT_ON_LINE_FALSE_DOWN"],	"LOW_SHADOW_DEFENDER_FD_JUMP_DOWN",			},
		{ STATE_CHANGE_TYPE["SCT_MOTION_END"],				"LOW_SHADOW_DEFENDER_FD_WAIT",				},
	},
}

LOW_SHADOW_DEFENDER_FD_STAND_UP_BACK = 
{
	ANIM_NAME					= "DamageStandUpBack",
	PLAY_TYPE					= XSKIN_ANIM_PLAYTYPE["XAP_ONE_WAIT"],
	TRANSITION					= FALSE,
	LAND_CONNECT				= FALSE,
	SUPER_ARMOR					= TRUE,
	
	DEFENCE						= { 0, 100, 50, },
		
	CAN_PUSH_UNIT				= TRUE,
	CAN_PASS_UNIT				= FALSE,
		
	EVENT_PROCESS = 
	{
		{ STATE_CHANGE_TYPE["SCT_FOOT_ON_LINE_FALSE_DOWN"],	"LOW_SHADOW_DEFENDER_FD_JUMP_DOWN", },
		{ STATE_CHANGE_TYPE["SCT_MOTION_END"],				"LOW_SHADOW_DEFENDER_FD_WAIT", },
	},		
}



LOW_SHADOW_DEFENDER_FD_DYING_LAND_FRONT = 
{
	ANIM_NAME					= "DamageDownFront",
	PLAY_TYPE					= XSKIN_ANIM_PLAYTYPE["XAP_ONE_WAIT"],
	TRANSITION					= FALSE,
	LAND_CONNECT				= FALSE,

	INVINCIBLE					= { 0, 100, }, 		

 	CAN_PUSH_UNIT				= FALSE,
	CAN_PASS_UNIT				= TRUE,
	
	DYING_END					= TRUE,
	
	IMMADIATE_PACKET_SEND		= TRUE,
}
	
LOW_SHADOW_DEFENDER_FD_DYING_LAND_BACK = 
{
	ANIM_NAME					= "DamageDownBack",
	PLAY_TYPE					= XSKIN_ANIM_PLAYTYPE["XAP_ONE_WAIT"],
	TRANSITION					= FALSE,
	LAND_CONNECT				= FALSE,
	
	INVINCIBLE					= { 0, 100, }, 		

	CAN_PUSH_UNIT				= FALSE,
	CAN_PASS_UNIT				= TRUE,
	
	DYING_END					= TRUE,	
	
	IMMADIATE_PACKET_SEND		= TRUE,
}

LOW_SHADOW_DEFENDER_FD_DYING_SKY = 
{
	ANIM_NAME					= "DamageAirDown",
	PLAY_TYPE					= XSKIN_ANIM_PLAYTYPE["XAP_ONE_WAIT"],
	TRANSITION					= FALSE,
	LAND_CONNECT				= FALSE,
	
	INVINCIBLE					= { 0, 100, }, 		
	
	CAN_PUSH_UNIT				= FALSE,
	CAN_PASS_UNIT				= TRUE,
	
	DYING_END					= TRUE,
	
	IMMADIATE_PACKET_SEND		= TRUE,
}









--------------------------------------------------------------------
--------------------------------------------------------------------

function LOW_SHADOW_DEFENDER_FD_WALK_STATE_END( pKTDXApp, pX2Game, pNPCUnit )

	local pMinorParticle = pX2Game:GetMinorParticle()
	pMinorParticle:GameUnitCreateSequence_LUA( pNPCUnit, "StepSmoke", pNPCUnit:GetLandPosition_LUA(), D3DXVECTOR2(100,100), D3DXVECTOR2(5,-1) )

end



function LOW_SHADOW_DEFENDER_FD_JUMP_DOWN_STATE_END( pKTDXApp, pX2Game, pNPCUnit )

	local pMinorParticle = pX2Game:GetMinorParticle()
	pMinorParticle:GameUnitCreateSequence_LUA( pNPCUnit, "StepSmoke", pNPCUnit:GetLandPosition_LUA(), D3DXVECTOR2(100,100), D3DXVECTOR2(5,-1) )

end

function LOW_SHADOW_DEFENDER_FD_JUMP_DOWN_DIR_STATE_END( pKTDXApp, pX2Game, pNPCUnit )

	local pMinorParticle = pX2Game:GetMinorParticle()
	pMinorParticle:GameUnitCreateSequence_LUA( pNPCUnit, "StepSmoke", pNPCUnit:GetLandPosition_LUA(), D3DXVECTOR2(100,100), D3DXVECTOR2(5,-1) )

end



function LOW_SHADOW_DEFENDER_FD_DAMAGE_FRONT_FRAME_MOVE( pKTDXApp, pX2Game, pNPCUnit )

	if pNPCUnit:AnimEventTimer_LUA( 0.047 ) then
		local pMinorParticle = pX2Game:GetMinorParticle()
		pMinorParticle:GameUnitCreateSequence_LUA( pNPCUnit, "StepSmoke", pNPCUnit:GetLandPosition_LUA(), D3DXVECTOR2(100,100), D3DXVECTOR2(5,-1) )
	end

end

function LOW_SHADOW_DEFENDER_FD_DAMAGE_BACK_FRAME_MOVE( pKTDXApp, pX2Game, pNPCUnit )

	if pNPCUnit:AnimEventTimer_LUA( 0.06 ) then
		local pMinorParticle = pX2Game:GetMinorParticle()
		pMinorParticle:GameUnitCreateSequence_LUA( pNPCUnit, "StepSmoke", pNPCUnit:GetLandPosition_LUA(), D3DXVECTOR2(100,100), D3DXVECTOR2(5,-1) )
	end

end

function LOW_SHADOW_DEFENDER_FD_DAMAGE_DOWN_FRONT_FRAME_MOVE( pKTDXApp, pX2Game, pNPCUnit )

	if pNPCUnit:AnimEventTimer_LUA( 0.41 ) then
		pNPCUnit:PlaySound_LUA( "Down.ogg" )		
		local pMinorParticle = pX2Game:GetMinorParticle()
		pMinorParticle:GameUnitCreateSequence_LUA( pNPCUnit, "DownSmoke", pNPCUnit:GetLandPosition_LUA(), D3DXVECTOR2(100,100), D3DXVECTOR2(7,-1) )
	end

end

function LOW_SHADOW_DEFENDER_FD_DAMAGE_DOWN_BACK_FRAME_MOVE( pKTDXApp, pX2Game, pNPCUnit )

	if pNPCUnit:AnimEventTimer_LUA( 0.45 ) then
		pNPCUnit:PlaySound_LUA( "Down.ogg" )		
		local pMinorParticle = pX2Game:GetMinorParticle()
		pMinorParticle:GameUnitCreateSequence_LUA( pNPCUnit, "DownSmoke", pNPCUnit:GetLandPosition_LUA(), D3DXVECTOR2(100,100), D3DXVECTOR2(7,-1) )
	end

end

function LOW_SHADOW_DEFENDER_FD_DAMAGE_AIR_DOWN_LANDING_FRAME_MOVE( pKTDXApp, pX2Game, pNPCUnit )

	if pNPCUnit:AnimEventTimer_LUA( 0.01 ) then
		
		local pMinorParticle = pX2Game:GetMinorParticle()
		local pos = pNPCUnit:GetLandPosition_LUA()
		pMinorParticle:GameUnitCreateSequence_LUA( pNPCUnit, "DownSmoke", pos, D3DXVECTOR2(100,100), D3DXVECTOR2(7,-1) )
		pos.y = pos.y + 5
		pMinorParticle:GameUnitCreateSequence_LUA( pNPCUnit, "GroundShockWave", pos, D3DXVECTOR2(100,100), D3DXVECTOR2(1,-1) )
		local pParticle = pMinorParticle:GameUnitCreateSequence_LUA( pNPCUnit, "AirDownTick", pNPCUnit:GetPos(), D3DXVECTOR2(200,200), D3DXVECTOR2(10,-1) )
		if pParticle ~= nil then 
			pParticle:SetLandPosition( pos.y - 5 )
		end
		
		if GetDistance_LUA( pNPCUnit:GetPos(), pX2Game:GetFocusUnitPos_LUA() ) < 500 then
			pX2Game:GetX2Camera():GetCamera():UpDownCrashCameraNoReset( 10.0, 0.1 )
		end		
		
	elseif pNPCUnit:AnimEventTimer_LUA( 0.1 ) then
		
		pNPCUnit:PlaySound_LUA( "Down.ogg" )		
		local pMinorParticle = pX2Game:GetMinorParticle()
		pMinorParticle:GameUnitCreateSequence_LUA( pNPCUnit, "DownSmoke", pNPCUnit:GetLandPosition_LUA(), D3DXVECTOR2(100,100), D3DXVECTOR2(7,-1) )
		
	end

end







function LOW_SHADOW_DEFENDER_FD_DYING_LAND_STATE_START( pKTDXApp, pX2Game, pNPCUnit )

	local pos = pNPCUnit:GetPos()
	pos.y = pos.y + 100.0
	local GetMinorParticle = pX2Game:GetMinorParticle()
	
	local pSeq = GetMinorParticle:GameUnitCreateSequence_LUA( pNPCUnit, "DieLight",		pos, D3DXVECTOR2(-1,-1), D3DXVECTOR2(3,-1) )
	if pSeq ~= nil then
	
		pSeq:SetLandPosition( pNPCUnit:GetLandPosition_LUA().y )
		pNPCUnit:SetDieSeq( pSeq:GetHandle() )
	
	end
	pNPCUnit:PlaySound_LUA( "DieLight.ogg" )				
end



--------------------------------------------------------------------

function MovePos( pos, dirvector, dist )
	
	pos.x = pos.x + dist * dirvector.x
	pos.y = pos.y + dist * dirvector.y
	pos.z = pos.z + dist * dirvector.z
	
	return pos
	
end



--------------------------------------------------------------------
-- Frame move functions --
--------------------------------------------------------------------

function LOW_SHADOW_DEFENDER_FD_COMMON_FRAME_MOVE_FUNC( pKTDXApp, pX2Game, pNPCUnit )
	
	local pMajorParticle = pX2Game:GetMajorParticle()
	
	if pNPCUnit:GetTimerElapsedTime( 1 ) < 1.2 then
	
		local pParticle = pNPCUnit:GetMajorParticle_LUA(0)
		if pParticle ~= nil then
			local vPos = pNPCUnit:GetBonePos_LUA( "Dummy01" )
			pParticle:SetPosition( vPos )
		end
		
		pParticle = pNPCUnit:GetMajorParticle_LUA(1)
		if pParticle ~= nil then
			local vPos = pNPCUnit:GetBonePos_LUA( "Dummy01" )
			pParticle:SetPosition( vPos )
		end
		
	else
	
		local pParticle = pNPCUnit:GetMajorParticle_LUA(0)
		
		if pParticle ~= nil then
			pMajorParticle:DestroyInstance( pParticle )
		end
		pNPCUnit:ClearMajorParticle_LUA( pParticle )
		
		pParticle = pNPCUnit:GetMajorParticle_LUA(1)
		
		if pParticle ~= nil then
			pMajorParticle:DestroyInstance( pParticle )
		end
		pNPCUnit:ClearMajorParticle_LUA( pParticle )
		
	end
	
end


--------------------------------------------------------------------



function LOW_SHADOW_DEFENDER_FD_ATTACK_A_READY_FRAME_MOVE( pKTDXApp , pX2Game , pNPCUnit )

	if pNPCUnit:AnimEventTimer_LUA( 0.533 ) then
	
		local pMajorParticle = pX2Game:GetMajorParticle()
		
		local vRHandPos = pNPCUnit:GetBonePos_LUA( "Dummy01" )
		
		local pParticle1 = pMajorParticle:GameUnitCreateSequence_LUA( pNPCUnit, "Pa_SHADOW_DEFENDER_AttackA_Ready_Charge01" , vRHandPos, D3DXVECTOR2(100,100), D3DXVECTOR2(-5,100) )
		local pParticle2 = pMajorParticle:GameUnitCreateSequence_LUA( pNPCUnit, "Pa_SHADOW_DEFENDER_AttackA_Ready_Charge02" , vRHandPos, D3DXVECTOR2(100,100), D3DXVECTOR2(-5,100) )
		
		pNPCUnit:SetMajorParticle_LUA( 0 , pParticle1:GetHandle() )
		pNPCUnit:SetMajorParticle_LUA( 1 , pParticle2:GetHandle() )
		pNPCUnit:SetTimerRestart(1)
	end

end 

--------------------------------------------------------------------

function LOW_SHADOW_DEFENDER_FD_ATTACK_A_FRAME_MOVE( pKTDXApp, pX2Game, pNPCUnit )


	if pNPCUnit:AnimEventTimer_LUA( 0.01 ) then
		
		local pDamageEffect = pX2Game:GetDamageEffect()
		
		
		local vLandPos = pNPCUnit:GetLandPosition_LUA()
		local vRHandPos = pNPCUnit:GetBonePos_LUA( "Dummy01" )
		local vRotDegree = pNPCUnit:GetRotateDegree()
				
		local pIns = pDamageEffect:CreateInstance_LUA2( pNPCUnit, "SHADOW_DEFENDER_SPEAR", vRHandPos, vLandPos.y, vRotDegree )
		
		local pMainEffect = pIns:GetMainEffect()
		--pMainEffect:SetVelocity( D3DXVECTOR3( 800 , 900 , 0 ) )
	end	
	
end

--------------------------------------------------------------------

function LOW_SHADOW_DEFENDER_FD_ATTACK_B_FRAME_MOVE( pKTDXApp, pX2Game, pNPCUnit )


	if pNPCUnit:AnimEventTimer_LUA( 0.01 ) then
		
		local pDamageEffect = pX2Game:GetDamageEffect()
		
		
		local vLandPos = pNPCUnit:GetLandPosition_LUA()
		local vRHandPos = pNPCUnit:GetBonePos_LUA( "Dummy01" )
		local vRotDegree = pNPCUnit:GetRotateDegree()
				
		local pIns = pDamageEffect:CreateInstance_LUA2( pNPCUnit, "SHADOW_DEFENDER_SPEAR", vRHandPos, vLandPos.y, vRotDegree )
		local pMainEffect = pIns:GetMainEffect()
		--pMainEffect:SetVelocity( D3DXVECTOR3( 1100 , 900 , 0 ) )
		
	end	
	
end
--------------------------------------------------------------------

function LOW_SHADOW_DEFENDER_FD_ATTACK_C_FRAME_MOVE( pKTDXApp, pX2Game, pNPCUnit )


	if pNPCUnit:AnimEventTimer_LUA( 0.01 ) then
		
		local pDamageEffect = pX2Game:GetDamageEffect()
		
		
		local vLandPos = pNPCUnit:GetLandPosition_LUA()
		local vRHandPos = pNPCUnit:GetBonePos_LUA( "Dummy01" )
		local vRotDegree = pNPCUnit:GetRotateDegree()
		
		local pIns = pDamageEffect:CreateInstance_LUA2( pNPCUnit, "SHADOW_DEFENDER_SPEAR", vRHandPos, vLandPos.y, vRotDegree )		
	end	
	
end


--------------------------------------------------------------------


function LOW_SHADOW_DEFENDER_FD_SPECIAL_ATTACK_A_FRAME_MOVE( pKTDXApp, pX2Game, pNPCUnit )

	if pNPCUnit:AnimEventTimer_LUA( 0.01 ) then
		pNPCUnit:SetBuffFactorToGameUnitByBuffFactorID_LUA( BUFF_FACTOR_ID["BFI_SHADOW_DEFENDER_BARRIER"] )
	end	

end

--------------------------------------------------------------------


--------------------------------------------------------------------


function CF_LOW_SHADOW_DEFENDER_FD_DASH_END( pKTDXApp, pX2Game, pNPCUnit )

	if pNPCUnit:GetStateTime() < 0.1 then
		return false 
	end
	
	
 	local bIsRight = pNPCUnit:GetIsRight()
	local vStartPos = pNPCUnit:GetLineGroupStartPos()
	local vEndPos = pNPCUnit:GetLineGroupEndPos()

 	
 	if bIsRight == true and pNPCUnit:GetDistanceFrom(vEndPos) < 280.0 then
 	
 	    return true
 	    
   	end
   	
   	if bIsRight == false and pNPCUnit:GetDistanceFrom(vStartPos) < 280.0 then

		return true
  	
    end

    if pNPCUnit:GetStateTime() > 5.0 then
		return true
	end
    
    return false 	

end


