-- lua header. UTF-8 인코딩 인식을 위해 이 줄은 지우지 마세요.


-- Nasod_Spray.lua





INIT_SYSTEM = 
{
	LUA_SHAREABLE	= TRUE,
	UNIT_WIDTH		= 150.0,
	UNIT_HEIGHT		= 150.0,
	UNIT_LAYER		= X2_LAYER["XL_UNIT_0"],
}


INIT_DEVICE = 
{
	READY_TEXTURE = 
	{		
		"Smoke_Machine03.tga",
	},
	
	READY_SOUND = 
	{
		"LOW_SPRAY_FIRE_FD_Attack.ogg",
		"LOW_SPRAY_FIRE_FD_DashAEnd.ogg",
		"LOW_SPRAY_FIRE_FD_WaitStart.ogg",   --
		"LOW_SPRAY_FIRE_FD_RumbleAttack.ogg",   --
		"LOW_SPRAY_FIRE_FD_Walk.ogg",
		"LOW_SPRAY_FIRE_FD_Dash.ogg",
		"LOW_SPRAY_FIRE_FD_JumpAttack.ogg",
		"LOW_SPRAY_FIRE_FD_DashAttack1.ogg",
		"LOW_SPRAY_FIRE_FD_DashAttack2.ogg",
		"LOW_SPRAY_FIRE_FD_Fire.ogg",
		"LOW_SPRAY_FIRE_FD_JumpLand.ogg",
		"LOW_SPRAY_FIRE_FD_Down.ogg",
		"LOW_SPRAY_FIRE_FD_Fall.ogg",
        "LOW_SPRAY_FIRE_FD_FireBall1.ogg",  --
		
	},
	
		
	READY_XMESH = 
	{
	},
	
	
	READY_XSKIN_MESH = 
	{
	},
	
	
}

INIT_MOTION = 
{
	MOTION_FILE_NAME		= "Motion_Nasod_Spray.x",
	MOTION_ANI_TEX_XET		= "NUI_LOW_SPRAY_FIRE_FD.xet",
	MOTION_CHANGE_TEX_XET	= "NUI_LOW_SPRAY_FIRE_FD.xet",

}

INIT_PHYSIC = 
{
	RELOAD_ACCEL		= 2000,
	G_ACCEL				= 4000,
	MAX_G_SPEED			= -2000,
	
	WALK_SPEED			= 400,
	RUN_SPEED			= 600,
	JUMP_SPEED			= 1500,
	DASH_JUMP_SPEED		= 1800,
}


INIT_COMPONENT = 
{
	MAX_HP				= 6000,
	MP_CHANGE_RATE		= 1,
	MP_CHARGE_RATE		= 130,
	
	USE_SLASH_TRACE		= FALSE,
	
	SHADOW_SIZE			= 200,
	SHADOW_FILE_NAME	= "shadow.dds",
	
	SMALL_HP_BAR_BLUE	= "Small_HP_bar_Blue.TGA",
	SMALL_HP_BAR_RED	= "Small_HP_bar_Red.TGA",
	SMALL_HP_BAR_YELLOW = "Small_HP_bar_Yellow.TGA",
	
	QUESTION_MARK_SEQ		= "QuestionMarkNPC",
	EXCLAMATION_MARK_SEQ	= "ExclamationMarkNPC",
	--MIND_FLAG_HEIGHT		= 230,
	
	HYPER_MODE_COUNT	= 0,
	MAX_HYPER_MODE_TIME	= 30,
	
	--RAGE_COUNT_MAX		= 20,
	--RAGE_TIME_MAX		= 5,

	HITTED_TYPE			= HITTED_TYPE["HTD_MEAT"],
	
	FALL_DOWN			= TRUE,
	
	

	

}

INIT_STATE = 
{
	{ STATE_NAME = "LOW_SPRAY_FIRE_FD_START",							LUA_FRAME_MOVE_FUNC = "LOW_SPRAY_FIRE_FD_START_FRAME_MOVE",	
																LUA_STATE_END_FUNC = "LOW_SPRAY_FIRE_FD_START_STATE_END",				},
	
	{ STATE_NAME = "LOW_SPRAY_FIRE_FD_WAIT",							},
	{ STATE_NAME = "LOW_SPRAY_FIRE_FD_WAIT_START",					LUA_FRAME_MOVE_FUNC = "LOW_SPRAY_FIRE_FD_WAIT_START_FRAME_MOVE",	
																LUA_STATE_END_FUNC = "LOW_SPRAY_FIRE_FD_WAIT_START_STATE_END"				},
	
	{ STATE_NAME = "LOW_SPRAY_FIRE_FD_WALK",							LUA_STATE_END_FUNC = "LOW_SPRAY_FIRE_FD_WALK_STATE_END"						},
	
	{ STATE_NAME = "LOW_SPRAY_FIRE_FD_DASH",							},
	{ STATE_NAME = "LOW_SPRAY_FIRE_FD_DASH_END",						LUA_STATE_START_FUNC = "LOW_SPRAY_FIRE_FD_DASH_END_STATE_START"				},
	
	{ STATE_NAME = "LOW_SPRAY_FIRE_FD_JUMP_UP",						},
	{ STATE_NAME = "LOW_SPRAY_FIRE_FD_JUMP_DOWN",						LUA_STATE_END_FUNC = "LOW_SPRAY_FIRE_FD_JUMP_DOWN_STATE_END"					},
	{ STATE_NAME = "LOW_SPRAY_FIRE_FD_JUMP_UP_DIR",					},
	{ STATE_NAME = "LOW_SPRAY_FIRE_FD_JUMP_DOWN_DIR",					LUA_STATE_END_FUNC = "LOW_SPRAY_FIRE_FD_JUMP_DOWN_DIR_STATE_END"				},
	{ STATE_NAME = "LOW_SPRAY_FIRE_FD_JUMP_LANDING",					},


	{ STATE_NAME = "LOW_SPRAY_FIRE_FD_ATTACK",						},
																
	{ STATE_NAME = "LOW_SPRAY_FIRE_FD_RUMBLE_ATTACK",					LUA_FRAME_MOVE_FUNC = "LOW_SPRAY_FIRE_FD_RUMBLE_ATTACK_FRAME_MOVE",		
																LUA_STATE_END_FUNC = "LOW_SPRAY_FIRE_FD_RUMBLE_ATTACK_STATE_END",		},
	
	
	{ STATE_NAME = "LOW_SPRAY_FIRE_FD_DASH_ATTACK",					},
	{ STATE_NAME = "LOW_SPRAY_FIRE_FD_JUMP_ATTACK",					},
	{ STATE_NAME = "LOW_SPRAY_FIRE_FD_JUMP_FOR_ATTACK",				},
	
	{ STATE_NAME = "LOW_SPRAY_FIRE_FD_FIRE_BALL",				LUA_FRAME_MOVE_FUNC = "LOW_SPRAY_FIRE_FD_FIRE_BALL_FRAME_MOVE", STATE_COOL_TIME = 5,		},
	
	
	
	
	--리액션 관련
	{ STATE_NAME = "LOW_SPRAY_FIRE_FD_DAMAGE_SMALL",					LUA_FRAME_MOVE_FUNC = "LOW_SPRAY_FIRE_FD_DAMAGE_SMALL_FRAME_MOVE"				},
	{ STATE_NAME = "LOW_SPRAY_FIRE_FD_DAMAGE_BIG",					LUA_FRAME_MOVE_FUNC = "LOW_SPRAY_FIRE_FD_DAMAGE_BIG_FRAME_MOVE"				},
	{ STATE_NAME = "LOW_SPRAY_FIRE_FD_DAMAGE_DOWN_FRONT",				LUA_FRAME_MOVE_FUNC = "LOW_SPRAY_FIRE_FD_DAMAGE_DOWN_FRONT_FRAME_MOVE"		},
	{ STATE_NAME = "LOW_SPRAY_FIRE_FD_DAMAGE_DOWN_BACK",				LUA_FRAME_MOVE_FUNC = "LOW_SPRAY_FIRE_FD_DAMAGE_DOWN_BACK_FRAME_MOVE"			},
	{ STATE_NAME = "LOW_SPRAY_FIRE_FD_DAMAGE_FLY_FRONT",				},
	{ STATE_NAME = "LOW_SPRAY_FIRE_FD_DAMAGE_FLY_BACK",				},
	{ STATE_NAME = "LOW_SPRAY_FIRE_FD_DAMAGE_AIR",					},
	{ STATE_NAME = "LOW_SPRAY_FIRE_FD_DAMAGE_AIR_DOWN",				},
	{ STATE_NAME = "LOW_SPRAY_FIRE_FD_DAMAGE_AIR_UP",					},
	{ STATE_NAME = "LOW_SPRAY_FIRE_FD_DAMAGE_AIR_FALL",				},	
	{ STATE_NAME = "LOW_SPRAY_FIRE_FD_DAMAGE_AIR_DOWN_LANDING",		LUA_FRAME_MOVE_FUNC = "LOW_SPRAY_FIRE_FD_DAMAGE_AIR_DOWN_LANDING_FRAME_MOVE"	},
	{ STATE_NAME = "LOW_SPRAY_FIRE_FD_STAND_UP_FRONT",				},
	{ STATE_NAME = "LOW_SPRAY_FIRE_FD_STAND_UP_BACK",					},
	{ STATE_NAME = "LOW_SPRAY_FIRE_FD_STAND_UP_ATTACK_FRONT",			LUA_FRAME_MOVE_FUNC = "LOW_SPRAY_FIRE_FD_STAND_UP_ATTACK_FRONT_FRAME_MOVE",	
																LUA_STATE_END_FUNC = "LOW_SPRAY_FIRE_FD_STAND_UP_ATTACK_FRONT_STATE_END", },
	
	{ STATE_NAME = "LOW_SPRAY_FIRE_FD_STAND_UP_ATTACK_BACK",			LUA_FRAME_MOVE_FUNC = "LOW_SPRAY_FIRE_FD_STAND_UP_ATTACK_BACK_FRAME_MOVE",
																LUA_STATE_END_FUNC = "LOW_SPRAY_FIRE_FD_STAND_UP_ATTACK_BACK_STATE_END", },
	
	{ STATE_NAME = "LOW_SPRAY_FIRE_FD_DYING_LAND_FRONT",				LUA_STATE_START_FUNC = "LOW_SPRAY_FIRE_FD_DYING_LAND_STATE_START",},
	{ STATE_NAME = "LOW_SPRAY_FIRE_FD_DYING_LAND_BACK",				LUA_STATE_START_FUNC = "LOW_SPRAY_FIRE_FD_DYING_LAND_STATE_START",},
	{ STATE_NAME = "LOW_SPRAY_FIRE_FD_DYING_SKY",						LUA_STATE_START_FUNC = "LOW_SPRAY_FIRE_FD_DYING_LAND_STATE_START",},
	
	
	
	START_STATE					= "LOW_SPRAY_FIRE_FD_WAIT",
	WAIT_STATE					= "LOW_SPRAY_FIRE_FD_WAIT",
	
	
	SMALL_DAMAGE_LAND_FRONT		= "LOW_SPRAY_FIRE_FD_DAMAGE_SMALL",
	SMALL_DAMAGE_LAND_BACK		= "LOW_SPRAY_FIRE_FD_DAMAGE_SMALL",
	BIG_DAMAGE_LAND_FRONT		= "LOW_SPRAY_FIRE_FD_DAMAGE_BIG",
	BIG_DAMAGE_LAND_BACK		= "LOW_SPRAY_FIRE_FD_DAMAGE_BIG",
	DOWN_DAMAGE_LAND_FRONT		= "LOW_SPRAY_FIRE_FD_DAMAGE_DOWN_FRONT",
	DOWN_DAMAGE_LAND_BACK		= "LOW_SPRAY_FIRE_FD_DAMAGE_DOWN_BACK",
	FLY_DAMAGE_FRONT			= "LOW_SPRAY_FIRE_FD_DAMAGE_FLY_FRONT",
	FLY_DAMAGE_BACK				= "LOW_SPRAY_FIRE_FD_DAMAGE_FLY_BACK",
	SMALL_DAMAGE_AIR			= "LOW_SPRAY_FIRE_FD_DAMAGE_AIR",	
	BIG_DAMAGE_AIR				= "LOW_SPRAY_FIRE_FD_DAMAGE_AIR",
	DOWN_DAMAGE_AIR				= "LOW_SPRAY_FIRE_FD_DAMAGE_AIR_DOWN",
	DOWN_DAMAGE_AIR_LANDING				= "LOW_SPRAY_FIRE_FD_DAMAGE_AIR_DOWN_LANDING",
	UP_DAMAGE					= "LOW_SPRAY_FIRE_FD_DAMAGE_AIR_UP",
	DAMAGE_REVENGE				= "LOW_SPRAY_FIRE_FD_DAMAGE_SMALL",
	
	DAMAGE_EXTRA_STATES         = {"LOW_SPRAY_FIRE_FD_DAMAGE_AIR_FALL",
	"LOW_SPRAY_FIRE_FD_STAND_UP_FRONT","LOW_SPRAY_FIRE_FD_STAND_UP_BACK","LOW_SPRAY_FIRE_FD_STAND_UP_ATTACK_FRONT","LOW_SPRAY_FIRE_FD_STAND_UP_ATTACK_BACK",
		"LOW_SPRAY_FIRE_FD_JUMP_DOWN","LOW_SPRAY_FIRE_FD_JUMP_LANDING",},
	
	
	DYING_LAND_FRONT			= "LOW_SPRAY_FIRE_FD_DYING_LAND_FRONT",
	DYING_LAND_BACK				= "LOW_SPRAY_FIRE_FD_DYING_LAND_BACK",
	DYING_SKY					= "LOW_SPRAY_FIRE_FD_DYING_SKY",

	REVENGE_ATTACK				= "",	
}



INIT_AI = 
{
 TARGET =
	{
  		TARGET_PRIORITY 			= TARGET_PRIORITY["TP_LOW_HP_FIRST"],
		TARGET_INTERVAL				= 3,		-- sec
		TARGET_NEAR_RANGE			= 600,		-- 이 거리보다 가까우면 TARGET_SUCCESS_RATE에 관계없이 무조건 타게팅된다
		TARGET_RANGE				= 700,		-- cm
		TARGET_LOST_RANGE			= 800,		-- cm
		TARGET_SUCCESS_RATE			= 100,  --50,		-- %
		ATTACK_TARGET_RATE			= 100, -- 30,		-- 나를 공격한 유닛을 타게팅할 확률
		PRESERVE_LAST_TARGET_RATE	= 100, -- 30,		-- 이전에 타게팅된 유닛을 계속 타게팅할 확률
		TARGET_HEIGHT_LIMIT			= 50,
	},

	CHASE_MOVE = 
	{		
		MOVE_SPLIT_RANGE	= 600,
		DEST_GAP			= 150,	-- 목적지에서 이 거리 안에 있으면 도착했다고 판단한다
		MOVE_GAP			= 160,
		
		DIR_CHANGE_INTERVAL = 0.7,
		
		WALK_INTERVAL		= 3,
		NEAR_WALK_RATE		= 100,   --  70,
		FAR_WALK_RATE		= 100,   -- 30,
		
		JUMP_INTERVAL		= 5,
		UP_JUMP_RATE		= 0, -- 40,
		UP_DOWN_RATE		= 0,
		DOWN_JUMP_RATE		= 0,    --  20,
		DOWN_DOWN_RATE		= 0,
		
		LINE_END_RANGE		= 80,	-- cm
	},	
	
	PATROL_MOVE = 	
	{
		PATROL_BEGIN_RATE		= 50, --50,		
		PATROL_RANGE			= 150,
		PATROL_COOL_TIME		= 2,
		ONLY_THIS_LINE_GROUP	= TRUE,
	},
	
	ESCAPE_MOVE = 
	{		
		MOVE_SPLIT_RANGE	= 500,	-- cm
		ESCAPE_GAP			= 600,	-- 이 거리 보다 멀어지면 도망 성공
		
		WALK_INTERVAL		= 1.5,	-- 초
		NEAR_WALK_RATE		= 100,   --  10,
		FAR_WALK_RATE		= 100,   -- 10,
		
		JUMP_INTERVAL		= 10,
		UP_JUMP_RATE		= 100, -- 30,
		UP_DOWN_RATE		= 30,
		DOWN_JUMP_RATE		= 100,    --  30,
		DOWN_DOWN_RATE		= 30,
		
		LINE_END_RANGE		= 80,	-- cm
	},

}


LOW_SPRAY_FIRE_FD_START = 
{
	ANIM_NAME					= "WaitStart",
	PLAY_TYPE					= XSKIN_ANIM_PLAYTYPE["XAP_ONE_WAIT"],
	TRANSITION					= FALSE,

    SOUND_PLAY0			= { 0.421, "LOW_SPRAY_FIRE_FD_WaitStart.ogg" , },

	
	CAN_PUSH_UNIT				= TRUE,
	CAN_PASS_UNIT				= FALSE,
	IMMADIATE_PACKET_SEND		= TRUE,	
		
	EVENT_PROCESS = 
	{		
		{ STATE_CHANGE_TYPE["SCT_CONDITION_TABLE"],		"LOW_SPRAY_FIRE_FD_WAIT",		"CT_LOW_SPRAY_FIRE_FD_WAIT"				},
	},
	
	CT_LOW_SPRAY_FIRE_FD_WAIT = 
	{
		STATE_TIME_OVER			= 3,
	},
}



LOW_SPRAY_FIRE_FD_WAIT = 
{
	ANIM_NAME					= "Wait",
	PLAY_TYPE					= XSKIN_ANIM_PLAYTYPE["XAP_LOOP"],
	TRANSITION					= TRUE,
	LAND_CONNECT				= TRUE,
	
	CAN_PUSH_UNIT				= TRUE,
	CAN_PASS_UNIT				= FALSE,	
	
	SPEED_X						= 0,
	SPEED_Y						= 0,
	
	PASSIVE_SPEED_X				= 0,
	
	IMMADIATE_PACKET_SEND		= TRUE,
	EVENT_INTERVAL_TIME0		= 2,
	
	EVENT_PROCESS = 
	{		
		{ STATE_CHANGE_TYPE["SCT_FOOT_ON_LINE_FALSE_DOWN"],	"LOW_SPRAY_FIRE_FD_JUMP_DOWN",				},
		
		{ STATE_CHANGE_TYPE["SCT_CONDITION_TABLE"],			"LOW_SPRAY_FIRE_FD_FIRE_BALL",				"CT_LOW_SPRAY_FIRE_FD_FIRE_BALL",	},

		
		{ STATE_CHANGE_TYPE["SCT_AI_WALK"],					"LOW_SPRAY_FIRE_FD_WALK",						},
		{ STATE_CHANGE_TYPE["SCT_AI_DASH"],					"LOW_SPRAY_FIRE_FD_DASH",						},
		{ STATE_CHANGE_TYPE["SCT_AI_JUMP"],					"LOW_SPRAY_FIRE_FD_JUMP_UP",					},
		{ STATE_CHANGE_TYPE["SCT_AI_JUMP_DIR"],				"LOW_SPRAY_FIRE_FD_JUMP_UP_DIR",				},
		{ STATE_CHANGE_TYPE["SCT_AI_DOWN"],					"LOW_SPRAY_FIRE_FD_JUMP_DOWN",				},
		{ STATE_CHANGE_TYPE["SCT_AI_DOWN_DIR"],				"LOW_SPRAY_FIRE_FD_JUMP_DOWN_DIR",			},
	},
	
	CT_LOW_SPRAY_FIRE_FD_FIRE_BALL = 
	{
		EVENT_INTERVAL_ID			= 0,
		DISTANCE_TO_TARGET_NEAR		= 600,
		RATE						= 100,		
	},	
}


LOW_SPRAY_FIRE_FD_WAIT_START = 
{
	ANIM_NAME					= "WaitStart",
	PLAY_TYPE					= XSKIN_ANIM_PLAYTYPE["XAP_ONE_WAIT"],
	TRANSITION					= FALSE,
	
	CAN_PUSH_UNIT				= TRUE,
	CAN_PASS_UNIT				= FALSE,
	IMMADIATE_PACKET_SEND		= TRUE,	

    SOUND_PLAY0			= { 0.421, "LOW_SPRAY_FIRE_FD_WaitStart.ogg" },

	EVENT_PROCESS = 
	{		
		{ STATE_CHANGE_TYPE["SCT_FOOT_ON_LINE_FALSE_DOWN"],		"LOW_SPRAY_FIRE_FD_JUMP_DOWN",			},
		{ STATE_CHANGE_TYPE["SCT_MOTION_END"],					"LOW_SPRAY_FIRE_FD_WAIT",					},
	},
}



LOW_SPRAY_FIRE_FD_WALK = 
{
	ANIM_SPEED					= 0.6,
	ANIM_NAME					= "Walk",
	PLAY_TYPE					= XSKIN_ANIM_PLAYTYPE["XAP_LOOP"],
	TRANSITION					= TRUE,
	LAND_CONNECT				= TRUE,
	
	CAN_PUSH_UNIT				= TRUE,
	CAN_PASS_UNIT				= FALSE,

    SOUND_PLAY0			= { 0.058, "LOW_SPRAY_FIRE_FD_Walk.ogg" },
    SOUND_PLAY1			= { 0.488, "LOW_SPRAY_FIRE_FD_Walk.ogg" },
	
	PASSIVE_SPEED_X				= 100,
	
	ALLOW_DIR_CHANGE			= TRUE,
	IMMADIATE_PACKET_SEND		= TRUE,
	
	EVENT_INTERVAL_TIME0		= 2,
	EVENT_INTERVAL_TIME1		= 3,
	
	EVENT_PROCESS = 
	{		
		
		{ STATE_CHANGE_TYPE["SCT_FOOT_ON_LINE_FALSE_DOWN"],	"LOW_SPRAY_FIRE_FD_JUMP_DOWN_DIR",			},
				
		{ STATE_CHANGE_TYPE["SCT_CONDITION_TABLE"],			"LOW_SPRAY_FIRE_FD_FIRE_BALL",				"CT_LOW_SPRAY_FIRE_FD_FIRE_BALL",	},		
		

		{ STATE_CHANGE_TYPE["SCT_AI_WAIT"],					"LOW_SPRAY_FIRE_FD_WAIT",						},
		{ STATE_CHANGE_TYPE["SCT_AI_DASH"],					"LOW_SPRAY_FIRE_FD_DASH",						},
		{ STATE_CHANGE_TYPE["SCT_AI_JUMP"],					"LOW_SPRAY_FIRE_FD_JUMP_UP",					},
		{ STATE_CHANGE_TYPE["SCT_AI_JUMP_DIR"],				"LOW_SPRAY_FIRE_FD_JUMP_UP_DIR",				},
		{ STATE_CHANGE_TYPE["SCT_AI_DOWN"],					"LOW_SPRAY_FIRE_FD_JUMP_DOWN",				},
		{ STATE_CHANGE_TYPE["SCT_AI_DOWN_DIR"],				"LOW_SPRAY_FIRE_FD_JUMP_DOWN_DIR",			},
	},
	
	CT_LOW_SPRAY_FIRE_FD_FIRE_BALL = 
	{
		EVENT_INTERVAL_ID			= 0,
		DISTANCE_TO_TARGET_NEAR		= 600,
		RATE						= 100,		
	},
}




LOW_SPRAY_FIRE_FD_DASH = 
{
	ANIM_SPEED					= 0.7,
	ANIM_NAME					= "Dash",
	PLAY_TYPE					= XSKIN_ANIM_PLAYTYPE["XAP_LOOP"],
	TRANSITION					= FALSE,
	LAND_CONNECT				= TRUE,
	
	CAN_PUSH_UNIT				= TRUE,
	CAN_PASS_UNIT				= FALSE,

    SOUND_PLAY0			= { 0.063, "LOW_SPRAY_FIRE_FD_Dash.ogg" },
    SOUND_PLAY1			= { 0.371, "LOW_SPRAY_FIRE_FD_Dash.ogg" },
	
	PASSIVE_SPEED_X				= 300,
	
	
	EVENT_INTERVAL_TIME0		= 2,
	EVENT_INTERVAL_TIME1		= 3,
	
	EVENT_PROCESS = 
	{		
		
		{ STATE_CHANGE_TYPE["SCT_FOOT_ON_LINE_FALSE_DOWN"],	"LOW_SPRAY_FIRE_FD_JUMP_DOWN_DIR",			},
				
		{ STATE_CHANGE_TYPE["SCT_CONDITION_TABLE"],			"LOW_SPRAY_FIRE_FD_FIRE_BALL",				"CT_LOW_SPRAY_FIRE_FD_FIRE_BALL",	},	
	
		{ STATE_CHANGE_TYPE["SCT_AI_WAIT"],					"LOW_SPRAY_FIRE_FD_DASH_END",				},
		{ STATE_CHANGE_TYPE["SCT_AI_WALK"],					"LOW_SPRAY_FIRE_FD_WALK",					},
		{ STATE_CHANGE_TYPE["SCT_AI_JUMP"],					"LOW_SPRAY_FIRE_FD_JUMP_UP",					},
		{ STATE_CHANGE_TYPE["SCT_AI_JUMP_DIR"],				"LOW_SPRAY_FIRE_FD_JUMP_UP_DIR",				},
		{ STATE_CHANGE_TYPE["SCT_AI_DOWN"],					"LOW_SPRAY_FIRE_FD_JUMP_DOWN",				},
		{ STATE_CHANGE_TYPE["SCT_AI_DOWN_DIR"],				"LOW_SPRAY_FIRE_FD_JUMP_DOWN_DIR",			},
	},
	
	CT_LOW_SPRAY_FIRE_FD_FIRE_BALL = 
	{
		EVENT_INTERVAL_ID			= 0,
		DISTANCE_OVER_TARGET_NEAR	= 600,
		RATE						= 100,		
	},
}




LOW_SPRAY_FIRE_FD_DASH_END = 
{
	ANIM_SPEED					= 0.6,
	ANIM_NAME					= "DashAEnd",
	PLAY_TYPE					= XSKIN_ANIM_PLAYTYPE["XAP_ONE_WAIT"],
	TRANSITION					= FALSE,
	
	CAN_PUSH_UNIT				= TRUE,
	CAN_PASS_UNIT				= FALSE,

    SOUND_PLAY0			= { 0.213, "LOW_SPRAY_FIRE_FD_DashAEnd.ogg" },

	
	PASSIVE_SPEED_X				= -1,
	SPEED_X						= 300,
	
	ALLOW_DIR_CHANGE			= TRUE,
	IMMADIATE_PACKET_SEND		= TRUE,
	
	EVENT_PROCESS = 
	{		
		{ STATE_CHANGE_TYPE["SCT_FOOT_ON_LINE_FALSE_DOWN"],	"LOW_SPRAY_FIRE_FD_JUMP_DOWN_DIR",			},
		{ STATE_CHANGE_TYPE["SCT_MOTION_END"],				"LOW_SPRAY_FIRE_FD_WAIT",					},
	},
}



LOW_SPRAY_FIRE_FD_JUMP_UP = 
{
	ANIM_NAME					= "JumpUp",
	PLAY_TYPE					= XSKIN_ANIM_PLAYTYPE["XAP_LOOP"],
	TRANSITION					= TRUE,
	LAND_CONNECT				= FALSE,
	
	CAN_PUSH_UNIT				= TRUE,
	CAN_PASS_UNIT				= FALSE,
	
	SPEED_X						= 0,
	SPEED_Y						= INIT_PHYSIC["JUMP_SPEED"],
	
	ADD_POS_Y					= 45, 
	
	IMMADIATE_PACKET_SEND		= TRUE,
	
	EVENT_PROCESS = 
	{		
		{ STATE_CHANGE_TYPE["SCT_NEGATIVE_Y_SPEED"],		"LOW_SPRAY_FIRE_FD_JUMP_DOWN",			},
	},
}

LOW_SPRAY_FIRE_FD_JUMP_DOWN = 
{
	ANIM_NAME					= "JumpDown",
	PLAY_TYPE					= XSKIN_ANIM_PLAYTYPE["XAP_LOOP"],
	TRANSITION					= TRUE,
	LAND_CONNECT				= FALSE,
	
	CAN_PUSH_UNIT				= TRUE,
	CAN_PASS_UNIT				= FALSE,
		 
	
	IMMADIATE_PACKET_SEND		= TRUE,
		
	EVENT_PROCESS = 
	{		
		{ STATE_CHANGE_TYPE["SCT_FOOT_ON_LINE_TRUE"],		"LOW_SPRAY_FIRE_FD_JUMP_LANDING",				},
	},
}

LOW_SPRAY_FIRE_FD_JUMP_UP_DIR = 
{
	ANIM_NAME					= "JumpUp",
	PLAY_TYPE					= XSKIN_ANIM_PLAYTYPE["XAP_LOOP"],
	TRANSITION					= TRUE,
	LAND_CONNECT				= FALSE,
	
	CAN_PUSH_UNIT				= TRUE,
	CAN_PASS_UNIT				= FALSE,
		
	PASSIVE_SPEED_X				= INIT_PHYSIC["WALK_SPEED"],
	SPEED_Y						= INIT_PHYSIC["JUMP_SPEED"],
	
	ADD_POS_Y					= 45, 
	
	IMMADIATE_PACKET_SEND		= TRUE,
	
	EVENT_PROCESS = 
	{		
		{ STATE_CHANGE_TYPE["SCT_NEGATIVE_Y_SPEED"],		"LOW_SPRAY_FIRE_FD_JUMP_DOWN_DIR",				},
	},	
}

LOW_SPRAY_FIRE_FD_JUMP_DOWN_DIR = 
{
	ANIM_NAME					= "JumpDown",
	PLAY_TYPE					= XSKIN_ANIM_PLAYTYPE["XAP_LOOP"],
	TRANSITION					= TRUE,
	LAND_CONNECT				= FALSE,
	
	CAN_PUSH_UNIT				= TRUE,
	CAN_PASS_UNIT				= FALSE,
	
	PASSIVE_SPEED_X				= INIT_PHYSIC["WALK_SPEED"],
	 
	
	IMMADIATE_PACKET_SEND		= TRUE,
		
	EVENT_PROCESS = 
	{		
		{ STATE_CHANGE_TYPE["SCT_FOOT_ON_LINE_TRUE"],		"LOW_SPRAY_FIRE_FD_JUMP_LANDING",				},
	},
}

LOW_SPRAY_FIRE_FD_JUMP_LANDING = 
{
	ANIM_NAME					= "JumpLanding",
	PLAY_TYPE					= XSKIN_ANIM_PLAYTYPE["XAP_ONE_WAIT"],
	TRANSITION					= TRUE,
	LAND_CONNECT				= FALSE,
	
	CAN_PUSH_UNIT				= TRUE,
	CAN_PASS_UNIT				= FALSE,
	

    SOUND_PLAY0			= { 0.139, "LOW_SPRAY_FIRE_FD_JumpLand.ogg" },

	SPEED_X						= 300,
	SPEED_Y						= 0,
		
	IMMADIATE_PACKET_SEND		= TRUE,

	EVENT_PROCESS = 
	{		
		{ STATE_CHANGE_TYPE["SCT_FOOT_ON_LINE_FALSE_DOWN"],	"LOW_SPRAY_FIRE_FD_JUMP_DOWN",				},
		{ STATE_CHANGE_TYPE["SCT_MOTION_END"],				"LOW_SPRAY_FIRE_FD_WAIT",						},
	},
}


LOW_SPRAY_FIRE_FD_FIRE_BALL = 
{
	ANIM_NAME					= "FireBall",
	PLAY_TYPE					= XSKIN_ANIM_PLAYTYPE["XAP_ONE_WAIT"],
	TRANSITION					= FALSE,
	LAND_CONNECT				= FALSE,
	
	CAN_PUSH_UNIT				= TRUE,
	CAN_PASS_UNIT				= FALSE,

    SOUND_PLAY0			= { 1.435, "LOW_SPRAY_FIRE_FD_FireBall1.ogg" },

	
	SPEED_X						= 0,
	SPEED_Y						= 0,	
	
	VIEW_TARGET					= TRUE,
	
	IMMADIATE_PACKET_SEND		= TRUE,
	
	EVENT_PROCESS = 
	{
		{ STATE_CHANGE_TYPE["SCT_MOTION_END"],					"LOW_SPRAY_FIRE_FD_WAIT",												},
	},
}


LOW_SPRAY_FIRE_FD_ATTACK = 
{
	ANIM_NAME					= "Attack",
	PLAY_TYPE					= XSKIN_ANIM_PLAYTYPE["XAP_ONE_WAIT"],
	TRANSITION					= FALSE,
	
	CAN_PUSH_UNIT				= TRUE,
	CAN_PASS_UNIT				= FALSE,
    
    
    SOUND_PLAY0			= { 0.431, "LOW_SPRAY_FIRE_FD_Attack.ogg" },
    

	SPEED_X						= 0,
	SPEED_Y						= 0,	
	
	VIEW_TARGET					= TRUE,
	
	IMMADIATE_PACKET_SEND		= TRUE,
	
	EVENT_PROCESS = 
	{	
		{ STATE_CHANGE_TYPE["SCT_FOOT_ON_LINE_FALSE_DOWN"],	"LOW_SPRAY_FIRE_FD_JUMP_DOWN",											},
		{ STATE_CHANGE_TYPE["SCT_MOTION_END"],				"LOW_SPRAY_FIRE_FD_WAIT",												},	
	},
	
	ATTACK_TIME0				= { 1.00, 1.104, },
	
	DAMAGE_DATA = 
	{
		DAMAGE_TYPE		= DAMAGE_TYPE["DT_PHYSIC"],
		HIT_TYPE		= HIT_TYPE["HT_PUNCH_HIT"],
		REACT_TYPE		= REACT_TYPE["RT_SMALL_DAMAGE"],
		
		DAMAGE = 
		{
			PHYSIC		= 1.0,
		},
		
		BACK_SPEED_X			= 800,
		BACK_SPEED_Y			= 0.0,
		
		CAMERA_CRASH_GAP		= 5.0,	
		CAMERA_CRASH_TIME		= 0.2,		
	},
}



LOW_SPRAY_FIRE_FD_RUMBLE_ATTACK =
{
	ANIM_NAME					= "RumbleAttack",
	PLAY_TYPE					= XSKIN_ANIM_PLAYTYPE["XAP_ONE_WAIT"],
	TRANSITION					= FALSE,
	
	
	CAN_PUSH_UNIT				= TRUE,
	CAN_PASS_UNIT				= FALSE,

    SOUND_PLAY0			= { 0.2, "LOW_SPRAY_FIRE_FD_Fire.ogg" },
    SOUND_PLAY1			= { 0.224, "LOW_SPRAY_FIRE_FD_RumbleAttack.ogg" },


	SPEED_X						= INIT_PHYSIC["WALK_SPEED"],
	SPEED_Y						= 0,	
	
	VIEW_TARGET					= TRUE,

	
	IMMADIATE_PACKET_SEND		= TRUE,
		
	EVENT_PROCESS = 
	{		
		{ STATE_CHANGE_TYPE["SCT_FOOT_ON_LINE_FALSE_DOWN"],	"LOW_SPRAY_FIRE_FD_JUMP_DOWN",			},
		{ STATE_CHANGE_TYPE["SCT_MOTION_END"],				"LOW_SPRAY_FIRE_FD_WAIT",					},
	},
	
	
	ATTACK_TIME0				= { 0.853, 1.153, },
	
	
	DAMAGE_DATA = 
	{
		DAMAGE_TYPE		= DAMAGE_TYPE["DT_PHYSIC"],
		HIT_TYPE		= HIT_TYPE["HT_PUNCH_HIT"],
		REACT_TYPE		= REACT_TYPE["RT_SMALL_DAMAGE"],
		
		DAMAGE = 
		{
			PHYSIC		= 1.0,
		},
		BUFF_FACTOR =
		{
			BUFF_TEMPLET_ID = BUFF_TEMPLET_ID["BTI_DEBUFF_FIRE"],
			RATE	=
			{
				1,
			},
			IGNORE_REGIST_FOR_RATE = TRUE,

			BEHAVIOR =
			{
				COMBINATION = { BUFF_BEHAVIOR_TYPE["BBT_CHANGE_NOW_HP_PER_SECOND"], },
				
				BBT_CHANGE_NOW_HP_PER_SECOND =
				{
					BUFF_CHANGE_TYPE = BUFF_CHANGE_TYPE["BCT_RELATION_VALUE"],
					BUFF_RELATION_TYPE = BUFF_RELATION_TYPE["BRT_MIX_ATTACK"],

					MULTIPLIER =
					{
						-0.3,
					},
				},
			},
		
			FINALIZER =
			{
				COMBINATION = { BUFF_FINALIZER_TYPE["BFT_TIME"], },
			
				BFT_TIME =
				{
					BUFF_DURATION_TIME_TYPE = BUFF_DURATION_TIME_TYPE["BDTT_NORMAL_TIME"],
					NORMAL_TIME = { 6, },
				},
			},
		},
		
		BACK_SPEED_X			= INIT_PHYSIC["RUN_SPEED"] * 1.2,
		BACK_SPEED_Y			= 0.0,
		
		CAMERA_CRASH_GAP		= 5.0,	
		CAMERA_CRASH_TIME		= 0.2,		
	},
	
		
	DAMAGE_DATA_LAST = 
	{
		DAMAGE_TYPE		= DAMAGE_TYPE["DT_PHYSIC"],
		HIT_TYPE		= HIT_TYPE["HT_KICK_HIT"],
		REACT_TYPE		= REACT_TYPE["RT_DOWN"],
		
		DAMAGE = 
		{
			PHYSIC		= 1.0,
		},

		BUFF_FACTOR =
		{
			BUFF_TEMPLET_ID = BUFF_TEMPLET_ID["BTI_DEBUFF_FIRE"],
			RATE	=
			{
				1,
			},
			IGNORE_REGIST_FOR_RATE = TRUE,

			BEHAVIOR =
			{
				COMBINATION = { BUFF_BEHAVIOR_TYPE["BBT_CHANGE_NOW_HP_PER_SECOND"], },
				
				BBT_CHANGE_NOW_HP_PER_SECOND =
				{
					BUFF_CHANGE_TYPE = BUFF_CHANGE_TYPE["BCT_RELATION_VALUE"],
					BUFF_RELATION_TYPE = BUFF_RELATION_TYPE["BRT_MIX_ATTACK"],

					MULTIPLIER =
					{
						-0.3,
					},
				},
			},
		
			FINALIZER =
			{
				COMBINATION = { BUFF_FINALIZER_TYPE["BFT_TIME"], },
			
				BFT_TIME =
				{
					BUFF_DURATION_TIME_TYPE = BUFF_DURATION_TIME_TYPE["BDTT_NORMAL_TIME"],
					NORMAL_TIME = { 6, },
				},
			},
		},
		
		BACK_SPEED_X			= INIT_PHYSIC["RUN_SPEED"] * 1.5,
		BACK_SPEED_Y			= INIT_PHYSIC["JUMP_SPEED"] * 0.5,
		
		CAMERA_CRASH_GAP		= 5.0,	
		CAMERA_CRASH_TIME		= 0.2,		
	},
}




LOW_SPRAY_FIRE_FD_DASH_ATTACK = 
{
	ANIM_NAME					= "DashAttack",
	PLAY_TYPE					= XSKIN_ANIM_PLAYTYPE["XAP_ONE_WAIT"],
	TRANSITION					= FALSE,
	
	CAN_PUSH_UNIT				= TRUE,
	CAN_PASS_UNIT				= FALSE,

    SOUND_PLAY0			= { 0.356, "LOW_SPRAY_FIRE_FD_Fire.ogg" },
    SOUND_PLAY1			= { 0.470, "LOW_SPRAY_FIRE_FD_DashAttack1.ogg" },
    SOUND_PLAY2			= { 1.044, "LOW_SPRAY_FIRE_FD_DashAttack2.ogg" },
    

	SPEED_X						= 0,
	SPEED_Y						= 0,	
	
	VIEW_TARGET					= TRUE,
	
	IMMADIATE_PACKET_SEND		= TRUE,

	
	EVENT_PROCESS = 
	{	
		{ STATE_CHANGE_TYPE["SCT_FOOT_ON_LINE_FALSE_DOWN"],	"LOW_SPRAY_FIRE_FD_JUMP_DOWN",											},
		{ STATE_CHANGE_TYPE["SCT_MOTION_END"],				"LOW_SPRAY_FIRE_FD_WAIT",												},	
	},
	
	PARTICLE_SEQ = 
	{
		--Major, time, Name, weaponBonePos, Pos, StateEndDelete, bTrace, posx, posy, posz, bApplyUnitRotation, rotx, roty, rotz,
		{ TRUE, 0.01, "Nasod_Spray_RumbleAttack01", FALSE, "ATTACK_LINE_START1_Press", TRUE },
	},

	
	ATTACK_TIME0				= { 1.000, 1.106, },
	
	DAMAGE_DATA = 
	{
		DAMAGE_TYPE		= DAMAGE_TYPE["DT_PHYSIC"],
		HIT_TYPE		= HIT_TYPE["HT_KICK_SLASH"],
		REACT_TYPE		= REACT_TYPE["RT_DOWN"],
		
		DAMAGE = 
		{
			PHYSIC		= 1.0,
		},
		
		BACK_SPEED_X			= INIT_PHYSIC["WALK_SPEED"] * 1.5,
		BACK_SPEED_Y			= 0.0,
		
		CAMERA_CRASH_GAP		= 5.0,	
		CAMERA_CRASH_TIME		= 0.2,		
	},
}



LOW_SPRAY_FIRE_FD_JUMP_ATTACK = 
{
	ANIM_NAME					= "JumpAttack",
	PLAY_TYPE					= XSKIN_ANIM_PLAYTYPE["XAP_ONE_WAIT"],
	TRANSITION					= FALSE,
	LAND_CONNECT				= FALSE,
	
	
	CAN_PUSH_UNIT				= TRUE,
	CAN_PASS_UNIT				= FALSE,

    SOUND_PLAY0			= { 0.172, "LOW_SPRAY_FIRE_FD_JumpAttack.ogg" },

	IMMADIATE_PACKET_SEND		= TRUE,
	

	
	EVENT_PROCESS = 
	{	
		{ STATE_CHANGE_TYPE["SCT_FOOT_ON_LINE_TRUE"],		"LOW_SPRAY_FIRE_FD_JUMP_LANDING",			},
		
	},
	
	ATTACK_TIME0				= { 0.12, 0.3, },
	
	DAMAGE_DATA = 
	{
		DAMAGE_TYPE		= DAMAGE_TYPE["DT_PHYSIC"],
		HIT_TYPE		= HIT_TYPE["HT_PUNCH_HIT"],
		REACT_TYPE		= REACT_TYPE["RT_DOWN"],
		
		DAMAGE = 
		{
			PHYSIC		= 1.0,
		},
		
		BACK_SPEED_X			= INIT_PHYSIC["WALK_SPEED"] * 1.5,
		BACK_SPEED_Y			= 0.0,
		
		CAMERA_CRASH_GAP		= 5.0,	
		CAMERA_CRASH_TIME		= 0.2,		
	},
}



LOW_SPRAY_FIRE_FD_JUMP_FOR_ATTACK = 
{
	ANIM_NAME					= "JumpUp",
	PLAY_TYPE					= XSKIN_ANIM_PLAYTYPE["XAP_LOOP"],
	TRANSITION					= TRUE,
	LAND_CONNECT				= FALSE,
	
	CAN_PUSH_UNIT				= TRUE,
	CAN_PASS_UNIT				= FALSE,
	
	PASSIVE_SPEED_X				= INIT_PHYSIC["WALK_SPEED"],
	SPEED_Y						= INIT_PHYSIC["JUMP_SPEED"],
	
	VIEW_TARGET					= TRUE,	
	IMMADIATE_PACKET_SEND		= TRUE,
	
	EVENT_PROCESS = 
	{		
		{ STATE_CHANGE_TYPE["SCT_NEGATIVE_Y_SPEED"],			"LOW_SPRAY_FIRE_FD_JUMP_ATTACK",		},
	},
}



LOW_SPRAY_FIRE_FD_DAMAGE_SMALL = 
{
	ANIM_NAME					= "DamageSmall",		
	PLAY_TYPE					= XSKIN_ANIM_PLAYTYPE["XAP_ONE_WAIT"],
	TRANSITION					= FALSE,
	LAND_CONNECT				= FALSE,
	
	CAN_PUSH_UNIT				= TRUE,
	CAN_PASS_UNIT				= FALSE,
	
	
	EVENT_PROCESS = 
	{
		{ STATE_CHANGE_TYPE["SCT_MOTION_END"],					"LOW_SPRAY_FIRE_FD_WAIT",												},
	},
}

LOW_SPRAY_FIRE_FD_DAMAGE_BIG = 
{
	ANIM_NAME					= "DamageBig",
	PLAY_TYPE					= XSKIN_ANIM_PLAYTYPE["XAP_ONE_WAIT"],
	TRANSITION					= FALSE,
	LAND_CONNECT				= FALSE,
	
	CAN_PUSH_UNIT				= TRUE,
	CAN_PASS_UNIT				= FALSE,
	
	EVENT_PROCESS = 
	{
		{ STATE_CHANGE_TYPE["SCT_MOTION_END"],					"LOW_SPRAY_FIRE_FD_WAIT",												},
	},
}

LOW_SPRAY_FIRE_FD_DAMAGE_DOWN_FRONT = 
{
	ANIM_NAME					= "DamageDownFront",
	PLAY_TYPE					= XSKIN_ANIM_PLAYTYPE["XAP_ONE_WAIT"],
	TRANSITION					= FALSE,
	LAND_CONNECT				= FALSE,

	SUPER_ARMOR					= TRUE,
	DEFENCE						= { 0, 100, 50, },

    SOUND_PLAY0			= { 0.272, "LOW_SPRAY_FIRE_FD_Down.ogg" },
 	
	CAN_PUSH_UNIT				= TRUE,
	CAN_PASS_UNIT				= FALSE,
	
	
	EVENT_PROCESS = 
	{
		{ STATE_CHANGE_TYPE["SCT_FOOT_ON_LINE_FALSE_DOWN"],		"LOW_SPRAY_FIRE_FD_DAMAGE_AIR_FALL",			},
		{ STATE_CHANGE_TYPE["SCT_MOTION_END"],					"LOW_SPRAY_FIRE_FD_STAND_UP_FRONT",			},
	},
	
}

LOW_SPRAY_FIRE_FD_DAMAGE_DOWN_BACK = 
{
	ANIM_NAME					= "DamageDownBack",
	PLAY_TYPE					= XSKIN_ANIM_PLAYTYPE["XAP_ONE_WAIT"],
	TRANSITION					= FALSE,
	LAND_CONNECT				= FALSE,
	
	SUPER_ARMOR					= TRUE,
	DEFENCE						= { 0, 100, 50, },

    SOUND_PLAY0			= { 0.214, "LOW_SPRAY_FIRE_FD_Down.ogg" },
	
	CAN_PUSH_UNIT				= TRUE,
	CAN_PASS_UNIT				= FALSE,
	
	EVENT_PROCESS = 
	{
		{ STATE_CHANGE_TYPE["SCT_FOOT_ON_LINE_FALSE_DOWN"],		"LOW_SPRAY_FIRE_FD_DAMAGE_AIR_FALL",			},
		{ STATE_CHANGE_TYPE["SCT_MOTION_END"],					"LOW_SPRAY_FIRE_FD_STAND_UP_BACK",			},
	},
}

LOW_SPRAY_FIRE_FD_DAMAGE_FLY_FRONT = 
{
	ANIM_NAME					= "DamageAirFlyFront",
	PLAY_TYPE					= XSKIN_ANIM_PLAYTYPE["XAP_ONE_WAIT"],
	TRANSITION					= FALSE,
	LAND_CONNECT				= FALSE,	
	
	ADD_ROTATE_Z				= -45.0,	
	
	
	CAN_PUSH_UNIT				= TRUE,
	CAN_PASS_UNIT				= FALSE,
	
	EVENT_PROCESS = 
	{
		{ STATE_CHANGE_TYPE["SCT_FOOT_ON_LINE_TRUE"],			"LOW_SPRAY_FIRE_FD_DAMAGE_AIR_DOWN_LANDING",		},
	},
}

LOW_SPRAY_FIRE_FD_DAMAGE_FLY_BACK = 
{
	ANIM_NAME					= "DamageAirFlyBack",
	PLAY_TYPE					= XSKIN_ANIM_PLAYTYPE["XAP_ONE_WAIT"],
	TRANSITION					= FALSE,
	LAND_CONNECT				= FALSE,	
	
	CAN_PUSH_UNIT				= TRUE,
	CAN_PASS_UNIT				= FALSE,
	
	EVENT_PROCESS = 
	{
		{ STATE_CHANGE_TYPE["SCT_FOOT_ON_LINE_TRUE"],			"LOW_SPRAY_FIRE_FD_DAMAGE_DOWN_BACK",		},
	},
}

LOW_SPRAY_FIRE_FD_DAMAGE_AIR = 
{
	ANIM_NAME					= "DamageAirUp",
	PLAY_TYPE					= XSKIN_ANIM_PLAYTYPE["XAP_ONE_WAIT"],
	TRANSITION					= FALSE,
	LAND_CONNECT				= FALSE,
	
	CAN_PUSH_UNIT				= TRUE,
	CAN_PASS_UNIT				= FALSE,
	
	EVENT_PROCESS = 
	{
		{ STATE_CHANGE_TYPE["SCT_FOOT_ON_LINE_TRUE"],			"LOW_SPRAY_FIRE_FD_WAIT",					},
	},
}

LOW_SPRAY_FIRE_FD_DAMAGE_AIR_DOWN = 
{
	ANIM_NAME					= "DamageAirDown",
	PLAY_TYPE					= XSKIN_ANIM_PLAYTYPE["XAP_ONE_WAIT"],
	TRANSITION					= FALSE,
	LAND_CONNECT				= FALSE,
	
	CAN_PUSH_UNIT				= TRUE,
	CAN_PASS_UNIT				= FALSE,
	
	EVENT_PROCESS = 
	{
		{ STATE_CHANGE_TYPE["SCT_FOOT_ON_LINE_TRUE"],			"LOW_SPRAY_FIRE_FD_DAMAGE_AIR_DOWN_LANDING",	},
	},
}

LOW_SPRAY_FIRE_FD_DAMAGE_AIR_UP = 
{
	ANIM_NAME					= "DamageAirUp",
	PLAY_TYPE					= XSKIN_ANIM_PLAYTYPE["XAP_ONE_WAIT"],
	TRANSITION					= FALSE,
	LAND_CONNECT				= FALSE,
	
	CAN_PUSH_UNIT				= TRUE,
	CAN_PASS_UNIT				= FALSE,
	
		
	EVENT_PROCESS = 
	{
		{ STATE_CHANGE_TYPE["SCT_NEGATIVE_Y_SPEED"],		"LOW_SPRAY_FIRE_FD_DAMAGE_AIR_FALL",			},
		{ STATE_CHANGE_TYPE["SCT_FOOT_ON_LINE_TRUE"],		"LOW_SPRAY_FIRE_FD_DAMAGE_AIR_DOWN_LANDING",	},
	},
	
}

LOW_SPRAY_FIRE_FD_DAMAGE_AIR_FALL = 
{
	ANIM_NAME					= "DamageAirFall",
	PLAY_TYPE					= XSKIN_ANIM_PLAYTYPE["XAP_ONE_WAIT"],
	TRANSITION					= FALSE,
	LAND_CONNECT				= FALSE,
	
	CAN_PUSH_UNIT				= TRUE,
	CAN_PASS_UNIT				= FALSE,
	
	EVENT_PROCESS = 
	{
		{ STATE_CHANGE_TYPE["SCT_POSITIVE_Y_SPEED"],		"LOW_SPRAY_FIRE_FD_DAMAGE_AIR_UP",			},
		{ STATE_CHANGE_TYPE["SCT_FOOT_ON_LINE_TRUE"],		"LOW_SPRAY_FIRE_FD_DAMAGE_AIR_DOWN_LANDING",	},
	},
}

LOW_SPRAY_FIRE_FD_DAMAGE_AIR_DOWN_LANDING = 
{
	ANIM_NAME					= "DamageAirDownLanding",
	PLAY_TYPE					= XSKIN_ANIM_PLAYTYPE["XAP_ONE_WAIT"],
	TRANSITION					= FALSE,
	LAND_CONNECT				= FALSE,
	
	SUPER_ARMOR					= TRUE,
	DEFENCE						= { 0, 100, 50, },
	
	CAN_PUSH_UNIT				= TRUE,
	CAN_PASS_UNIT				= FALSE,

    SOUND_PLAY0			= { 0.01, "LOW_SPRAY_FIRE_FD_Fall.ogg" },
    SOUND_PLAY1			= { 0.656, "LOW_SPRAY_FIRE_FD_Down.ogg" },
	
	EVENT_PROCESS = 
	{
		{ STATE_CHANGE_TYPE["SCT_FOOT_ON_LINE_FALSE_DOWN"],	"LOW_SPRAY_FIRE_FD_DAMAGE_AIR_FALL",			},
		{ STATE_CHANGE_TYPE["SCT_MOTION_END"],				"LOW_SPRAY_FIRE_FD_STAND_UP_FRONT",			},
	},
	
}

LOW_SPRAY_FIRE_FD_STAND_UP_FRONT = 
{
	ANIM_NAME					= "DamageStandUpFront",
	PLAY_TYPE					= XSKIN_ANIM_PLAYTYPE["XAP_ONE_WAIT"],
	TRANSITION					= FALSE,
	LAND_CONNECT				= TRUE,	
	
	SUPER_ARMOR					= TRUE,
	DEFENCE						= { 0, 100, 50, },
	
	CAN_PUSH_UNIT				= TRUE,
	CAN_PASS_UNIT				= FALSE,

    SOUND_PLAY0			= { 0.709, "LOW_SPRAY_FIRE_FD_JumpLand.ogg" },

	EVENT_PROCESS = 
	{
		{ STATE_CHANGE_TYPE["SCT_FOOT_ON_LINE_FALSE_DOWN"],	"LOW_SPRAY_FIRE_FD_JUMP_DOWN",			},
		{ STATE_CHANGE_TYPE["SCT_MOTION_END"],				"LOW_SPRAY_FIRE_FD_WAIT",				},
	},
}

LOW_SPRAY_FIRE_FD_STAND_UP_BACK = 
{
	ANIM_NAME					= "DamageStandUpBack",
	PLAY_TYPE					= XSKIN_ANIM_PLAYTYPE["XAP_ONE_WAIT"],
	TRANSITION					= FALSE,
	LAND_CONNECT				= TRUE,
	
	SUPER_ARMOR					= TRUE,
	DEFENCE						= { 0, 100, 50, },
		
	CAN_PUSH_UNIT				= TRUE,
	CAN_PASS_UNIT				= FALSE,

    SOUND_PLAY0			= { 0.0746, "LOW_SPRAY_FIRE_FD_JumpLand.ogg" },

	EVENT_PROCESS = 
	{
		{ STATE_CHANGE_TYPE["SCT_FOOT_ON_LINE_FALSE_DOWN"],	"LOW_SPRAY_FIRE_FD_JUMP_DOWN", },
		{ STATE_CHANGE_TYPE["SCT_MOTION_END"],				"LOW_SPRAY_FIRE_FD_WAIT", },
	},		
}


LOW_SPRAY_FIRE_FD_STAND_UP_ATTACK_FRONT = 
{
	ANIM_NAME					= "Attack",
	PLAY_TYPE					= XSKIN_ANIM_PLAYTYPE["XAP_ONE_WAIT"],
	TRANSITION					= FALSE,
	LAND_CONNECT				= TRUE,	
	ANIM_WAIT_TIME				= 1,
	MIND_FLAG					= MIND_FLAG["MF_STAND_UP_ATTACK"],
	
	SUPER_ARMOR					= TRUE,
	DEFENCE						= { 0, 100, 50, },
	
    SOUND_PLAY0			= { 0.431, "LOW_SPRAY_FIRE_FD_Attack.ogg" },
		
	VIEW_TARGET					= TRUE,
	IMMADIATE_PACKET_SEND		= TRUE,
	
	
	CAN_PUSH_UNIT				= TRUE,
	CAN_PASS_UNIT				= FALSE,


	EVENT_PROCESS = 
	{
		{ STATE_CHANGE_TYPE["SCT_FOOT_ON_LINE_FALSE_DOWN"],	"LOW_SPRAY_FIRE_FD_JUMP_DOWN",			},
		{ STATE_CHANGE_TYPE["SCT_MOTION_END"],				"LOW_SPRAY_FIRE_FD_WAIT",				},
	},
		
	ATTACK_TIME0				= { 1.00, 1.104, },
	
	DAMAGE_DATA = 
	{
		DAMAGE_TYPE		= DAMAGE_TYPE["DT_PHYSIC"],
		HIT_TYPE		= HIT_TYPE["HT_PUNCH_HIT"],
		REACT_TYPE		= REACT_TYPE["RT_DOWN"],
		
		DAMAGE = 
		{
			PHYSIC		= 1.0,
			FIRE		= 0.0,
			ICE			= 0.0,
			EARTH		= 0.0,
			LIGHTNING	= 0.0,
			DARK		= 0.0,
			LIGHT		= 0.0,
			UNIVERSAL	= 0.0,
		},
		
		BACK_SPEED_X			= INIT_PHYSIC["RUN_SPEED"],
		BACK_SPEED_Y			= 0.0,
		
		STOP_TIME_ATT			= 0.0,		
		STOP_TIME_DEF			= 0.0,	
		CAMERA_CRASH_GAP		= 5.0,	
		CAMERA_CRASH_TIME		= 0.2,
		CLEAR_SCREEN			= 0.0,	
		CLEAR_SCREEN_COLOR_A	= 0.0,
		CLEAR_SCREEN_COLOR_R	= 1.0,
		CLEAR_SCREEN_COLOR_G	= 1.0,
		CLEAR_SCREEN_COLOR_B	= 1.0,

		RE_ATTACK				= FALSE,		
		HIT_GAP					= 0.0,				
	},
}

LOW_SPRAY_FIRE_FD_STAND_UP_ATTACK_BACK = 
{
	ANIM_NAME					= "Attack",
	PLAY_TYPE					= XSKIN_ANIM_PLAYTYPE["XAP_ONE_WAIT"],
	TRANSITION					= FALSE,
	LAND_CONNECT				= TRUE,
	ANIM_WAIT_TIME				= 1,
	MIND_FLAG					= MIND_FLAG["MF_STAND_UP_ATTACK"],

    SOUND_PLAY0			= { 0.431, "LOW_SPRAY_FIRE_FD_Attack.ogg" },
	
	SUPER_ARMOR					= TRUE,
	DEFENCE						= { 0, 100, 50, },
		
	CAN_PUSH_UNIT				= TRUE,
	CAN_PASS_UNIT				= FALSE,

		
	VIEW_TARGET					= TRUE,
	IMMADIATE_PACKET_SEND		= TRUE,
	
	
	--FLIP_DIR_END				= TRUE,
	
	EVENT_PROCESS = 
	{
		{ STATE_CHANGE_TYPE["SCT_FOOT_ON_LINE_FALSE_DOWN"],	"LOW_SPRAY_FIRE_FD_JUMP_DOWN", },
		{ STATE_CHANGE_TYPE["SCT_MOTION_END"],				"LOW_SPRAY_FIRE_FD_WAIT", },
	},	
	
		
	ATTACK_TIME0				= { 1.00, 1.104, },
	
	DAMAGE_DATA = 
	{
		DAMAGE_TYPE		= DAMAGE_TYPE["DT_PHYSIC"],
		HIT_TYPE		= HIT_TYPE["HT_PUNCH_HIT"],
		REACT_TYPE		= REACT_TYPE["RT_DOWN"],
		
		DAMAGE = 
		{
			PHYSIC		= 1.0,
			FIRE		= 0.0,
			ICE			= 0.0,
			EARTH		= 0.0,
			LIGHTNING	= 0.0,
			DARK		= 0.0,
			LIGHT		= 0.0,
			UNIVERSAL	= 0.0,
		},
		
		BACK_SPEED_X			= INIT_PHYSIC["RUN_SPEED"],
		BACK_SPEED_Y			= 0.0,
		
		STOP_TIME_ATT			= 0.0,		
		STOP_TIME_DEF			= 0.0,	
		CAMERA_CRASH_GAP		= 5.0,	
		CAMERA_CRASH_TIME		= 0.2,
		CLEAR_SCREEN			= 0.0,	
		CLEAR_SCREEN_COLOR_A	= 0.0,
		CLEAR_SCREEN_COLOR_R	= 1.0,
		CLEAR_SCREEN_COLOR_G	= 1.0,
		CLEAR_SCREEN_COLOR_B	= 1.0,

		RE_ATTACK				= FALSE,		
		HIT_GAP					= 0.0,				
	},
}



LOW_SPRAY_FIRE_FD_DYING_LAND_FRONT = 
{
	ANIM_NAME					= "DamageDownFront",
	PLAY_TYPE					= XSKIN_ANIM_PLAYTYPE["XAP_ONE_WAIT"],
	TRANSITION					= FALSE,
	LAND_CONNECT				= TRUE,

	INVINCIBLE					= { 0, 100, }, 		

    SOUND_PLAY0			= { 0.272, "LOW_SPRAY_FIRE_FD_Down.ogg" },
	
	CAN_PUSH_UNIT				= FALSE,
	CAN_PASS_UNIT				= TRUE,
	
	DYING_END					= TRUE,
	
	IMMADIATE_PACKET_SEND		= TRUE,
}
	
LOW_SPRAY_FIRE_FD_DYING_LAND_BACK = 
{
	ANIM_NAME					= "DamageDownBack",
	PLAY_TYPE					= XSKIN_ANIM_PLAYTYPE["XAP_ONE_WAIT"],
	TRANSITION					= FALSE,
	LAND_CONNECT				= TRUE,
	
	INVINCIBLE					= { 0, 100, }, 		

    SOUND_PLAY0			= { 0.214, "LOW_SPRAY_FIRE_FD_Down.ogg" },
	
	CAN_PUSH_UNIT				= FALSE,
	CAN_PASS_UNIT				= TRUE,
	
	DYING_END					= TRUE,	
	
	IMMADIATE_PACKET_SEND		= TRUE,
}

LOW_SPRAY_FIRE_FD_DYING_SKY = 
{
	ANIM_NAME					= "DamageAirDownLanding",
	PLAY_TYPE					= XSKIN_ANIM_PLAYTYPE["XAP_ONE_WAIT"],
	TRANSITION					= FALSE,
	LAND_CONNECT				= FALSE,
	
	INVINCIBLE					= { 0, 100, }, 		
	
	CAN_PUSH_UNIT				= FALSE,
	CAN_PASS_UNIT				= TRUE,

    SOUND_PLAY0			= { 0.01, "LOW_SPRAY_FIRE_FD_Fall.ogg" },
    SOUND_PLAY1			= { 0.656, "LOW_SPRAY_FIRE_FD_Down.ogg" },

	DYING_END					= TRUE,
	
	IMMADIATE_PACKET_SEND		= TRUE,
}









--------------------------------------------------------------------
--------------------------------------------------------------------


function LOW_SPRAY_FIRE_FD_START_FRAME_MOVE( pKTDXApp, pX2Game, pNPCUnit )

	LOW_SPRAY_FIRE_FD_WAIT_START_EFFECT_FRAME_MOVE( pKTDXApp, pX2Game, pNPCUnit )
	
end


function LOW_SPRAY_FIRE_FD_START_STATE_END( pKTDXApp, pX2Game, pNPCUnit )

	LOW_SPRAY_FIRE_FD_WAIT_START_EFFECT_STATE_END( pKTDXApp, pX2Game, pNPCUnit )
	
end

function LOW_SPRAY_FIRE_FD_WAIT_START_FRAME_MOVE( pKTDXApp, pX2Game, pNPCUnit )

	LOW_SPRAY_FIRE_FD_WAIT_START_EFFECT_FRAME_MOVE( pKTDXApp, pX2Game, pNPCUnit )
	
end


function LOW_SPRAY_FIRE_FD_WAIT_START_STATE_END( pKTDXApp, pX2Game, pNPCUnit )

	LOW_SPRAY_FIRE_FD_WAIT_START_EFFECT_STATE_END( pKTDXApp, pX2Game, pNPCUnit )
	
end



function LOW_SPRAY_FIRE_FD_WALK_STATE_END( pKTDXApp, pX2Game, pNPCUnit )

	local pMinorParticle = pX2Game:GetMinorParticle()
	pMinorParticle:GameUnitCreateSequence_LUA( pNPCUnit, "StepSmoke", pNPCUnit:GetLandPosition_LUA(), D3DXVECTOR2(100,100), D3DXVECTOR2(5,-1) )

end



function LOW_SPRAY_FIRE_FD_DASH_END_STATE_START( pKTDXApp, pX2Game, pNPCUnit )

	local pMinorParticle = pX2Game:GetMinorParticle()
	pMinorParticle:GameUnitCreateSequence_LUA( pNPCUnit, "StepSmoke", pNPCUnit:GetLandPosition_LUA(), D3DXVECTOR2(100,100), D3DXVECTOR2(5,-1) )

end


function LOW_SPRAY_FIRE_FD_JUMP_DOWN_STATE_END( pKTDXApp, pX2Game, pNPCUnit )

	local pMinorParticle = pX2Game:GetMinorParticle()
	pMinorParticle:GameUnitCreateSequence_LUA( pNPCUnit, "StepSmoke", pNPCUnit:GetLandPosition_LUA(), D3DXVECTOR2(100,100), D3DXVECTOR2(5,-1) )

end

function LOW_SPRAY_FIRE_FD_JUMP_DOWN_DIR_STATE_END( pKTDXApp, pX2Game, pNPCUnit )

	local pMinorParticle = pX2Game:GetMinorParticle()
	pMinorParticle:GameUnitCreateSequence_LUA( pNPCUnit, "StepSmoke", pNPCUnit:GetLandPosition_LUA(), D3DXVECTOR2(100,100), D3DXVECTOR2(5,-1) )

end





--------------------------------------------------------------------
function LOW_SPRAY_FIRE_FD_RUMBLE_ATTACK_FRAME_MOVE( pKTDXApp, pX2Game, pNPCUnit )
	
	
	if pNPCUnit:AnimEventTimer_LUA( 0.860 ) then
		pNPCUnit:ClearHitUnitList_LUA()
		pNPCUnit:SetDamageData_LUA( "DAMAGE_DATA_LAST" )
		pNPCUnit:SetSpeedX( INIT_PHYSIC["RUN_SPEED"] )
	end

	if pNPCUnit:AnimEventTimer_LUA( 0.91 ) then
		pNPCUnit:ClearHitUnitList_LUA()
		pNPCUnit:SetDamageData_LUA( "DAMAGE_DATA_LAST" )
		pNPCUnit:SetSpeedX( INIT_PHYSIC["RUN_SPEED"] )
	end	
	
	if pNPCUnit:AnimEventTimer_LUA( 0.96 ) then
		pNPCUnit:ClearHitUnitList_LUA()
		pNPCUnit:SetDamageData_LUA( "DAMAGE_DATA_LAST" )
		pNPCUnit:SetSpeedX( INIT_PHYSIC["RUN_SPEED"] )
	end
	
	if pNPCUnit:AnimEventTimer_LUA( 1.01 ) then
		pNPCUnit:ClearHitUnitList_LUA()
		pNPCUnit:SetDamageData_LUA( "DAMAGE_DATA_LAST" )
		pNPCUnit:SetSpeedX( INIT_PHYSIC["RUN_SPEED"] )
	end
	
	
	local pMajorParticle = pX2Game:GetMajorParticle()
	
	if pNPCUnit:AnimEventTimer_LUA( 0.1 ) then
	
		local vRotateDegree	= pNPCUnit:GetRotateDegree()
		local vBonePos		= pNPCUnit:GetBonePos_LUA( "ATTACK_LINE_START1_Press" )
	
		local pParticle = pMajorParticle:GameUnitCreateSequence_LUA( pNPCUnit, "Nasod_Spray_RumbleAttack01", vBonePos, D3DXVECTOR2(-1,-1), D3DXVECTOR2(-1,-1) )
		if pParticle ~= nil then 
			pParticle:SetAddRotate( vRotateDegree )
			pParticle:SetAxisAngle( vRotateDegree )	
			pNPCUnit:SetMajorParticle_LUA( 0, pParticle:GetHandle() ) 
		end 
		
	end
	
	do
		local pParticle = pNPCUnit:GetMajorParticle_LUA( 0 ) 
		if nil ~= pParticle then 
		
			if pMajorParticle:IsLiveInstance( pParticle ) == true then 
				local vBonePos		= pNPCUnit:GetBonePos_LUA( "ATTACK_LINE_START1_Press" )
				pParticle:SetPosition( vBonePos )		
			else 
				pNPCUnit:ClearMajorParticle_LUA( 0 )
			end
		
		end
	end

end



--------------------------------------------------------------------
function LOW_SPRAY_FIRE_FD_RUMBLE_ATTACK_STATE_END( pKTDXApp, pX2Game, pNPCUnit )

	local pMajorParticle = pX2Game:GetMajorParticle()

	local pParticle = pNPCUnit:GetMajorParticle_LUA( 0 ) 	
	if pParticle ~= nil then
		pMajorParticle:DestroyInstance( pParticle )
		pNPCUnit:ClearMajorParticle_LUA( 0 )
	end

end



function LOW_SPRAY_FIRE_FD_DAMAGE_SMALL_FRAME_MOVE( pKTDXApp, pX2Game, pNPCUnit )

	if pNPCUnit:AnimEventTimer_LUA( 0.047 ) then
		local pMinorParticle = pX2Game:GetMinorParticle()
		pMinorParticle:GameUnitCreateSequence_LUA( pNPCUnit, "StepSmoke", pNPCUnit:GetLandPosition_LUA(), D3DXVECTOR2(100,100), D3DXVECTOR2(5,-1) )
	end

end

function LOW_SPRAY_FIRE_FD_DAMAGE_BIG_FRAME_MOVE( pKTDXApp, pX2Game, pNPCUnit )

	if pNPCUnit:AnimEventTimer_LUA( 0.06 ) then
		local pMinorParticle = pX2Game:GetMinorParticle()
		pMinorParticle:GameUnitCreateSequence_LUA( pNPCUnit, "StepSmoke", pNPCUnit:GetLandPosition_LUA(), D3DXVECTOR2(100,100), D3DXVECTOR2(5,-1) )
	end

end

function LOW_SPRAY_FIRE_FD_DAMAGE_DOWN_FRONT_FRAME_MOVE( pKTDXApp, pX2Game, pNPCUnit )

	if pNPCUnit:AnimEventTimer_LUA( 0.41 ) then
		
		local pMinorParticle = pX2Game:GetMinorParticle()
		pMinorParticle:GameUnitCreateSequence_LUA( pNPCUnit, "DownSmoke", pNPCUnit:GetLandPosition_LUA(), D3DXVECTOR2(100,100), D3DXVECTOR2(7,-1) )
	end

end

function LOW_SPRAY_FIRE_FD_DAMAGE_DOWN_BACK_FRAME_MOVE( pKTDXApp, pX2Game, pNPCUnit )

	if pNPCUnit:AnimEventTimer_LUA( 0.45 ) then
		
		local pMinorParticle = pX2Game:GetMinorParticle()
		pMinorParticle:GameUnitCreateSequence_LUA( pNPCUnit, "DownSmoke", pNPCUnit:GetLandPosition_LUA(), D3DXVECTOR2(100,100), D3DXVECTOR2(7,-1) )
	end

end

function LOW_SPRAY_FIRE_FD_DAMAGE_AIR_DOWN_LANDING_FRAME_MOVE( pKTDXApp, pX2Game, pNPCUnit )

	if pNPCUnit:AnimEventTimer_LUA( 0.01 ) then
		
		local pMinorParticle = pX2Game:GetMinorParticle()
		local pos = pNPCUnit:GetLandPosition_LUA()
		pMinorParticle:GameUnitCreateSequence_LUA( pNPCUnit, "DownSmoke", pos, D3DXVECTOR2(100,100), D3DXVECTOR2(7,-1) )
		pos.y = pos.y + 5
		pMinorParticle:GameUnitCreateSequence_LUA( pNPCUnit, "GroundShockWave", pos, D3DXVECTOR2(100,100), D3DXVECTOR2(1,-1) )
		local pParticle = pMinorParticle:GameUnitCreateSequence_LUA( pNPCUnit, "AirDownTick", pNPCUnit:GetPos(), D3DXVECTOR2(200,200), D3DXVECTOR2(10,-1) )
		if pParticle ~= nil then
			pParticle:SetLandPosition( pos.y - 5 )
		end
		
		if GetDistance_LUA( pNPCUnit:GetPos(), pX2Game:GetFocusUnitPos_LUA() ) < 500 then
			pX2Game:GetX2Camera():GetCamera():UpDownCrashCameraNoReset( 10.0, 0.1 )
		end		
		
	elseif pNPCUnit:AnimEventTimer_LUA( 0.1 ) then
		
		local pMinorParticle = pX2Game:GetMinorParticle()
		pMinorParticle:GameUnitCreateSequence_LUA( pNPCUnit, "DownSmoke", pNPCUnit:GetLandPosition_LUA(), D3DXVECTOR2(100,100), D3DXVECTOR2(7,-1) )
		
	end

end

function LOW_SPRAY_FIRE_FD_STAND_UP_ATTACK_FRONT_FRAME_MOVE( pKTDXApp, pX2Game, pNPCUnit )

	if pNPCUnit:AnimEventTimer_LUA( 0.35 ) then
		local pMinorParticle = pX2Game:GetMinorParticle()
		pMinorParticle:GameUnitCreateSequence_LUA( pNPCUnit, "StepSmoke", pNPCUnit:GetLandPosition_LUA(), D3DXVECTOR2(100,100), D3DXVECTOR2(5,-1) )
	end
	
	--LOW_SPRAY_FIRE_FD_ATTACK_EFFECT_FRAME_MOVE( pKTDXApp, pX2Game, pNPCUnit )
	
end


function LOW_SPRAY_FIRE_FD_STAND_UP_ATTACK_FRONT_STATE_END( pKTDXApp, pX2Game, pNPCUnit )

	--LOW_SPRAY_FIRE_FD_ATTACK_EFFECT_STATE_END( pKTDXApp, pX2Game, pNPCUnit )
	
end


function LOW_SPRAY_FIRE_FD_STAND_UP_ATTACK_BACK_FRAME_MOVE( pKTDXApp, pX2Game, pNPCUnit )

	if pNPCUnit:AnimEventTimer_LUA( 0.35 ) then
		local pMinorParticle = pX2Game:GetMinorParticle()
		pMinorParticle:GameUnitCreateSequence_LUA( pNPCUnit, "StepSmoke", pNPCUnit:GetLandPosition_LUA(), D3DXVECTOR2(100,100), D3DXVECTOR2(5,-1) )
	end
	
	--LOW_SPRAY_FIRE_FD_ATTACK_EFFECT_FRAME_MOVE( pKTDXApp, pX2Game, pNPCUnit )

end


function LOW_SPRAY_FIRE_FD_STAND_UP_ATTACK_BACK_STATE_END( pKTDXApp, pX2Game, pNPCUnit )
	
	LOW_SPRAY_FIRE_FD_ATTACK_EFFECT_STATE_END( pKTDXApp, pX2Game, pNPCUnit )

end




function LOW_SPRAY_FIRE_FD_DYING_LAND_STATE_START( pKTDXApp, pX2Game, pNPCUnit )

	local pos = pNPCUnit:GetPos()
	pos.y = pos.y + 100.0
	local GetMinorParticle = pX2Game:GetMinorParticle()
	
	local pSeq = GetMinorParticle:GameUnitCreateSequence_LUA( pNPCUnit, "DieLight",		pos, D3DXVECTOR2(-1,-1), D3DXVECTOR2(3,-1) )
	if pSeq ~= nil then
	
		pSeq:SetLandPosition( pNPCUnit:GetLandPosition_LUA().y )
		pNPCUnit:SetDieSeq( pSeq:GetHandle() )
	
	end
	pNPCUnit:PlaySound_LUA( "DieLight.ogg" )
	
end











------------------------------------------------------------------------------
-- EFFECT FUNCTION
------------------------------------------------------------------------------




------------------------------------------------------------------------------
function LOW_SPRAY_FIRE_FD_WAIT_START_EFFECT_FRAME_MOVE( pKTDXApp, pX2Game, pNPCUnit )

	local pMajorParticle = pX2Game:GetMajorParticle()
	
	
	------------------------------------------------------------
	if pNPCUnit:AnimEventTimer_LUA( 0.4 ) then
	
		local vRotateDegree	= pNPCUnit:GetRotateDegree()
		local vBonePos		= pNPCUnit:GetBonePos_LUA( "ATTACK_LINE_START1_Press" )
		local vZVector = pNPCUnit:GetZVector()
		vBonePos = MovePos( vBonePos, vZVector, -50 )
	
		local pParticle = pMajorParticle:GameUnitCreateSequence_LUA( pNPCUnit, "Nasod_Spray_WaitStart01", vBonePos, D3DXVECTOR2(-1,-1), D3DXVECTOR2(-1,-1) )
		if pParticle ~= nil then  
			pParticle:SetAddRotate( vRotateDegree )
			pParticle:SetAxisAngle( vRotateDegree )	
			pNPCUnit:SetMajorParticle_LUA( 0, pParticle:GetHandle() ) 
		end 
		
	end
	
	do
		local pParticle = pNPCUnit:GetMajorParticle_LUA( 0 ) 
		if nil ~= pParticle then 
		
			if pMajorParticle:IsLiveInstance( pParticle ) == true then 
				local vBonePos		= pNPCUnit:GetBonePos_LUA( "ATTACK_LINE_START1_Press" )
				local vZVector = pNPCUnit:GetZVector()
				vBonePos = MovePos( vBonePos, vZVector, -50 )

				pParticle:SetPosition( vBonePos )		
			else 
				pNPCUnit:ClearMajorParticle_LUA( 0 )
			end
		
		end
	end
	
	
	------------------------------------------------------------
	if pNPCUnit:AnimEventTimer_LUA( 0.36 ) then
	
		local vLandPos		= pNPCUnit:GetLandPosition_LUA()
		local vRotateDegree	= pNPCUnit:GetRotateDegree()
		local vBonePos		= pNPCUnit:GetBonePos_LUA( "Bone_Rhand" )
		local vZVector = pNPCUnit:GetZVector()
		vBonePos = MovePos( vBonePos, vZVector, -50 )


	
		local pParticle = pMajorParticle:GameUnitCreateSequence_LUA( pNPCUnit, "Stone_Nasod_Spray_WaitStart", vBonePos, D3DXVECTOR2(-1,-1), D3DXVECTOR2(-1,-1) )
		pParticle:SetAddRotate( vRotateDegree )
		pParticle:SetAxisAngle( vRotateDegree )	
		pParticle:SetLandPosition( vLandPos.y )
		pNPCUnit:SetMajorParticle_LUA( 1, pParticle:GetHandle() ) 
	
	end
	
	do
		local pParticle = pNPCUnit:GetMajorParticle_LUA( 1 ) 
		if nil ~= pParticle then 
		
			if pMajorParticle:IsLiveInstance( pParticle ) == true then 
				local vBonePos		= pNPCUnit:GetBonePos_LUA( "Bone_Rhand" )
				pParticle:SetPosition( vBonePos )		
			else 
				pNPCUnit:ClearMajorParticle_LUA( 1 )
			end
		
		end
	end
	
	------------------------------------------------------------
	if pNPCUnit:AnimEventTimer_LUA( 0.5 ) then
	
		local vLandPos		= pNPCUnit:GetLandPosition_LUA()
		local vRotateDegree	= pNPCUnit:GetRotateDegree()
		local vBonePos		= pNPCUnit:GetBonePos_LUA( "Bone_Rhand" )
		local vZVector = pNPCUnit:GetZVector()
		vBonePos = MovePos( vBonePos, vZVector, -50 )

	
		local pParticle = pMajorParticle:GameUnitCreateSequence_LUA( pNPCUnit, "Stone_Nasod_Spray_WaitStart", vBonePos, D3DXVECTOR2(-1,-1), D3DXVECTOR2(-1,-1) )
		pParticle:SetAddRotate( vRotateDegree )
		pParticle:SetAxisAngle( vRotateDegree )	
		pParticle:SetLandPosition( vLandPos.y )		
		pNPCUnit:SetMajorParticle_LUA( 2, pParticle:GetHandle() ) 
	
	end
	
	do
		local pParticle = pNPCUnit:GetMajorParticle_LUA( 2 ) 
		if nil ~= pParticle then 
		
			if pMajorParticle:IsLiveInstance( pParticle ) == true then 
				local vBonePos		= pNPCUnit:GetBonePos_LUA( "Bone_Rhand" )
				pParticle:SetPosition( vBonePos )		
			else 
				pNPCUnit:ClearMajorParticle_LUA( 2 )
			end
		
		end
	end
	
	------------------------------------------------------------
	if pNPCUnit:AnimEventTimer_LUA( 0.7 ) then
	
		local vLandPos		= pNPCUnit:GetLandPosition_LUA()
		local vRotateDegree	= pNPCUnit:GetRotateDegree()
		local vBonePos		= pNPCUnit:GetBonePos_LUA( "Bone_Rhand" )
		local vZVector = pNPCUnit:GetZVector()
		vBonePos = MovePos( vBonePos, vZVector, -50 )
		
		local pParticle = pMajorParticle:GameUnitCreateSequence_LUA( pNPCUnit, "Stone_Nasod_Spray_WaitStart", vBonePos, D3DXVECTOR2(-1,-1), D3DXVECTOR2(-1,-1) )
		pParticle:SetAddRotate( vRotateDegree )
		pParticle:SetAxisAngle( vRotateDegree )	
		pParticle:SetLandPosition( vLandPos.y )		
		pNPCUnit:SetMajorParticle_LUA( 3, pParticle:GetHandle() ) 
	
	end
	
	do
		local pParticle = pNPCUnit:GetMajorParticle_LUA( 3 ) 
		if nil ~= pParticle then 
		
			if pMajorParticle:IsLiveInstance( pParticle ) == true then 
				local vBonePos		= pNPCUnit:GetBonePos_LUA( "Bone_Rhand" )
				pParticle:SetPosition( vBonePos )		
			else 
				pNPCUnit:ClearMajorParticle_LUA( 3 )
			end
		
		end
	end


	------------------------------------------------------------
	if pNPCUnit:AnimEventTimer_LUA( 0.9 ) then
	

		local vLandPos		= pNPCUnit:GetLandPosition_LUA()
		local vRotateDegree	= pNPCUnit:GetRotateDegree()
		local vBonePos		= pNPCUnit:GetBonePos_LUA( "Bone_Rhand" )
		local vZVector = pNPCUnit:GetZVector()
		vBonePos = MovePos( vBonePos, vZVector, -50 )

	
		local pParticle = pMajorParticle:GameUnitCreateSequence_LUA( pNPCUnit, "Stone_Nasod_Spray_WaitStart", vBonePos, D3DXVECTOR2(-1,-1), D3DXVECTOR2(-1,-1) )
		pParticle:SetAddRotate( vRotateDegree )
		pParticle:SetAxisAngle( vRotateDegree )
		pParticle:SetLandPosition( vLandPos.y )			
		pNPCUnit:SetMajorParticle_LUA( 4, pParticle:GetHandle() ) 
	
	end
	
	do
		local pParticle = pNPCUnit:GetMajorParticle_LUA( 4 ) 
		if nil ~= pParticle then 
		
			if pMajorParticle:IsLiveInstance( pParticle ) == true then 
				local vBonePos		= pNPCUnit:GetBonePos_LUA( "Bone_Rhand" )
				pParticle:SetPosition( vBonePos )		
			else 
				pNPCUnit:ClearMajorParticle_LUA( 4 )
			end
		
		end
	end
	
end


------------------------------------------------------------------------------
function LOW_SPRAY_FIRE_FD_WAIT_START_EFFECT_STATE_END( pKTDXApp, pX2Game, pNPCUnit )

	local pMajorParticle = pX2Game:GetMajorParticle()

	for i = 0, 4 do

		local pParticle = pNPCUnit:GetMajorParticle_LUA( i ) 	
		if pParticle ~= nil then
			pMajorParticle:DestroyInstance( pParticle )
			pNPCUnit:ClearMajorParticle_LUA( i )
		end
		
	end


end


















------------------------------------------------------------------------------
function LOW_SPRAY_FIRE_FD_ATTACK_EFFECT_FRAME_MOVE( pKTDXApp, pX2Game, pNPCUnit )


	local pMinorParticle = pX2Game:GetMinorParticle()
	local pMajorParticle = pX2Game:GetMajorParticle()


--	vUnitPos		= pNPCUnit:GetPos()
--	vRotateDegree	= pNPCUnit:GetRotateDegree()
--	vLandPos		= pNPCUnit:GetLandPosition_LUA()
--	bIsRight		= pNPCUnit:GetIsRight()
--	vDirVector		= pNPCUnit:GetDirVector()
--	vZVector		= pNPCUnit:GetZVector()
	
	
	if pNPCUnit:AnimEventTimer_LUA( 0.53 ) then
	
		local vLandPos		= pNPCUnit:GetLandPosition_LUA()
		local bIsRight		= pNPCUnit:GetIsRight()
		local vDirVector		= pNPCUnit:GetDirVector()
		local vZVector		= pNPCUnit:GetZVector()
	
	
		local vPos = pNPCUnit:GetPos()
		if bIsRight == true then 
			vPos = MovePos( vPos, vDirVector, 150 )
		else
			vPos = MovePos( vPos, vDirVector, -150 )
		end
		vPos = MovePos( vPos, vZVector, -70 )
		local pParticle = pMinorParticle:GameUnitCreateSequence_LUA( pNPCUnit, "Stone_LizardMan_High_WaitStart", vPos, D3DXVECTOR2(-1,-1), D3DXVECTOR2(-1,-1) )
		if pParticle ~= nil then
			pParticle:SetLandPosition( vLandPos.y )		
		end
		
	
		
		vPos = pNPCUnit:GetPos()
		if bIsRight == true then 
			vPos = MovePos( vPos, vDirVector, 200 )
		else
			vPos = MovePos( vPos, vDirVector, -200 )
		end
		vPos = MovePos( vPos, vZVector, -70 )
		pParticle = pMinorParticle:GameUnitCreateSequence_LUA( pNPCUnit, "Stone_LizardMan_High_WaitStart", vPos, D3DXVECTOR2(-1,-1), D3DXVECTOR2(-1,-1) )
		if pParticle ~= nil then
			pParticle:SetLandPosition( vLandPos.y )		
		end
		
	end
	
	
	if pNPCUnit:AnimEventTimer_LUA( 0.01 ) then
	
		local vRotateDegree	= pNPCUnit:GetRotateDegree()
		--vLandPos		= pNPCUnit:GetLandPosition_LUA()
		--bIsRight		= pNPCUnit:GetIsRight()
		--vDirVector		= pNPCUnit:GetDirVector()
		--vZVector		= pNPCUnit:GetZVector()
		local vBonePos		= pNPCUnit:GetBonePos_LUA( "Dummy01" )
	
		local pParticle = pMinorParticle:GameUnitCreateSequence_LUA( pNPCUnit, "Smoke_Nasod_MinerThin_Attack", vBonePos, D3DXVECTOR2(-1,-1), D3DXVECTOR2(-1,-1) )
		if pParticle ~= nil then
			pParticle:SetAddRotate( vRotateDegree )
			pParticle:SetAxisAngle( vRotateDegree )	
			pNPCUnit:SetMinorParticle_LUA( 0, pParticle:GetHandle() ) 
		end
	
	end
	
	do
		local pParticle = pNPCUnit:GetMinorParticle_LUA( 0 ) 
		if nil ~= pParticle then 
		
			if pMinorParticle:IsLiveInstance( pParticle ) == true then 
				local vBonePos		= pNPCUnit:GetBonePos_LUA( "Dummy01" )
				pParticle:SetPosition( vBonePos )		
			else 
				pNPCUnit:ClearMinorParticle_LUA( 0 )
			end
		
		end
	end
	
end


------------------------------------------------------------------------------
function LOW_SPRAY_FIRE_FD_ATTACK_EFFECT_STATE_END( pKTDXApp, pX2Game, pNPCUnit )

	local pMinorParticle = pX2Game:GetMinorParticle()
--	pMajorParticle = pX2Game:GetMajorParticle()


	local pParticle = pNPCUnit:GetMinorParticle_LUA( 0 ) 	
	if pParticle ~= nil then
		pMinorParticle:DestroyInstance( pParticle )
		pNPCUnit:ClearMinorParticle_LUA( 0 )
	end


end


function LOW_SPRAY_FIRE_FD_FIRE_BALL_FRAME_MOVE( pKTDXApp, pX2Game, pNPCUnit )
	
	if pNPCUnit:AnimEventTimer_LUA( 1.366 ) then
		
		local pDamageEffect = pX2Game:GetDamageEffect()
		local pos = pNPCUnit:GetLandPosition_LUA()		
		pDamageEffect:CreateInstance_LUA( pNPCUnit, "MONSTER_FIREBALL_DOWN", pNPCUnit:GetBonePos_LUA( "Bone_Rhand" ), pos.y)
		
	end
	
end



------------------------------------------------------------------------------
-- UTIL FUNCTION
------------------------------------------------------------------------------

------------------------------------------------------------------------------
function MovePos( pos, dirvector, dist )
	
	pos.x = pos.x + dist * dirvector.x
	pos.y = pos.y + dist * dirvector.y
	pos.z = pos.z + dist * dirvector.z
	
	return pos
	
end

