-- lua header. UTF-8 인코딩 인식을 위해 이 줄은 지우지 마세요.


-- Nasod_Healer.lua


INIT_SYSTEM = 
{
	LUA_SHAREABLE	= TRUE,
	UNIT_WIDTH		= 50.0,
	UNIT_LAYER		= X2_LAYER["XL_UNIT_0"],
}


INIT_DEVICE = 
{
	READY_TEXTURE = 
	{
		"Heal01.dds",
		"Explosion_Sphere.dds",

	},
	
	READY_SOUND = 
	{
		"Nasod_Healer_Heal.ogg",
	},
}

INIT_MOTION = 
{
	MOTION_FILE_NAME		= "Motion_Nasod_Healer.x",
}

INIT_PHYSIC = 
{
	RELOAD_ACCEL		= 2000,
	G_ACCEL				= 4000,
	MAX_G_SPEED			= -2000,
	
	WALK_SPEED			= 400,
	RUN_SPEED			= 400,
	JUMP_SPEED			= 1500,
	DASH_JUMP_SPEED		= 2300,
}


INIT_COMPONENT = 
{
	MAX_HP				= 4000,
	MP_CHANGE_RATE		= 1,
	MP_CHARGE_RATE		= 130,
	
	USE_SLASH_TRACE		= FALSE,
	
	SHADOW_SIZE			= 200,
	SHADOW_FILE_NAME	= "shadow.dds",
	
	SMALL_HP_BAR_BLUE	= "Small_HP_bar_Blue.TGA",
	SMALL_HP_BAR_RED	= "Small_HP_bar_Red.TGA",
	SMALL_HP_BAR_YELLOW = "Small_HP_bar_Yellow.TGA",
	
	QUESTION_MARK_SEQ		= "QuestionMarkNPC",
	EXCLAMATION_MARK_SEQ	= "ExclamationMarkNPC",
	
	
	HEAD_BONE_NAME			= "Bip",
	
	
	HYPER_MODE_COUNT	= 0,
	MAX_HYPER_MODE_TIME	= 30,
	
	HITTED_TYPE			= HITTED_TYPE["HTD_MEAT"],
	
	FALL_DOWN			= TRUE,
	

	

}

INIT_STATE = 
{
	{ STATE_NAME = "NASOD_HEALER_WAIT",						},
	{ STATE_NAME = "NASOD_HEALER_WALK",						},
	{ STATE_NAME = "NASOD_HEALER_JUMP_UP",					},
	{ STATE_NAME = "NASOD_HEALER_JUMP_DOWN",				LUA_STATE_END_FUNC = "NASOD_HEALER_JUMP_DOWN_STATE_END"					},
	{ STATE_NAME = "NASOD_HEALER_JUMP_UP_DIR",				},
	{ STATE_NAME = "NASOD_HEALER_JUMP_DOWN_DIR",			LUA_STATE_END_FUNC = "NASOD_HEALER_JUMP_DOWN_DIR_STATE_END"				},
	{ STATE_NAME = "NASOD_HEALER_JUMP_LANDING",				},
	
	{ STATE_NAME = "NASOD_HEALER_HEAL",						LUA_FRAME_MOVE_FUNC = "NASOD_HEALER_HEAL_FRAME_MOVE", STATE_COOL_TIME = 5, },
	
	
	--리액션 관련
	{ STATE_NAME = "NASOD_HEALER_DAMAGE",					LUA_FRAME_MOVE_FUNC = "NASOD_HEALER_DAMAGE_FRAME_MOVE"					},
	{ STATE_NAME = "NASOD_HEALER_DAMAGE",					LUA_FRAME_MOVE_FUNC = "NASOD_HEALER_DAMAGE_FRAME_MOVE"					},
	{ STATE_NAME = "NASOD_HEALER_DAMAGE_DOWN_FRONT",		LUA_FRAME_MOVE_FUNC = "NASOD_HEALER_DAMAGE_DOWN_FRONT_FRAME_MOVE"		},
	{ STATE_NAME = "NASOD_HEALER_DAMAGE_DOWN_BACK",			LUA_FRAME_MOVE_FUNC = "NASOD_HEALER_DAMAGE_DOWN_BACK_FRAME_MOVE"		},
	{ STATE_NAME = "NASOD_HEALER_DAMAGE_FLY_FRONT",			},
	{ STATE_NAME = "NASOD_HEALER_DAMAGE_FLY_BACK",			},
	{ STATE_NAME = "NASOD_HEALER_DAMAGE_AIR",				},
	{ STATE_NAME = "NASOD_HEALER_DAMAGE_AIR_DOWN",			},
	{ STATE_NAME = "NASOD_HEALER_DAMAGE_AIR_UP",			},
	{ STATE_NAME = "NASOD_HEALER_DAMAGE_AIR_FALL",			},	
	{ STATE_NAME = "NASOD_HEALER_DAMAGE_AIR_DOWN_LANDING",	LUA_FRAME_MOVE_FUNC = "NASOD_HEALER_DAMAGE_AIR_DOWN_LANDING_FRAME_MOVE"	},
	{ STATE_NAME = "NASOD_HEALER_STAND_UP_FRONT",			},
	{ STATE_NAME = "NASOD_HEALER_STAND_UP_BACK",			},
	
	{ STATE_NAME = "NASOD_HEALER_DYING_LAND_FRONT",			LUA_STATE_START_FUNC = "NASOD_HEALER_DYING_LAND_STATE_START", },
	{ STATE_NAME = "NASOD_HEALER_DYING_LAND_BACK",			LUA_STATE_START_FUNC = "NASOD_HEALER_DYING_LAND_STATE_START", },
	{ STATE_NAME = "NASOD_HEALER_DYING_SKY",				LUA_STATE_START_FUNC = "NASOD_HEALER_DYING_LAND_STATE_START", },
	

	START_STATE					= "NASOD_HEALER_WAIT",
	
	SMALL_DAMAGE_LAND_FRONT		= "NASOD_HEALER_DAMAGE",
	SMALL_DAMAGE_LAND_BACK		= "NASOD_HEALER_DAMAGE",
	BIG_DAMAGE_LAND_FRONT		= "NASOD_HEALER_DAMAGE",
	BIG_DAMAGE_LAND_BACK		= "NASOD_HEALER_DAMAGE",
	DOWN_DAMAGE_LAND_FRONT		= "NASOD_HEALER_DAMAGE_DOWN_FRONT",
	DOWN_DAMAGE_LAND_BACK		= "NASOD_HEALER_DAMAGE_DOWN_BACK",
	FLY_DAMAGE_FRONT			= "NASOD_HEALER_DAMAGE_FLY_FRONT",
	FLY_DAMAGE_BACK				= "NASOD_HEALER_DAMAGE_FLY_BACK",
	SMALL_DAMAGE_AIR			= "NASOD_HEALER_DAMAGE_AIR",	
	BIG_DAMAGE_AIR				= "NASOD_HEALER_DAMAGE_AIR",
	DOWN_DAMAGE_AIR				= "NASOD_HEALER_DAMAGE_AIR_DOWN",
	DOWN_DAMAGE_AIR_LANDING		= "NASOD_HEALER_DAMAGE_AIR_DOWN_LANDING",
	UP_DAMAGE					= "NASOD_HEALER_DAMAGE_AIR_UP",
	
	DAMAGE_EXTRA_STATES         = {"NASOD_HEALER_DAMAGE_AIR_FALL","NASOD_HEALER_STAND_UP_FRONT","NASOD_HEALER_STAND_UP_BACK",
	"NASOD_HEALER_JUMP_DOWN","NASOD_HEALER_JUMP_LANDING",},
	
	
	DYING_LAND_FRONT			= "NASOD_HEALER_DYING_LAND_FRONT",
	DYING_LAND_BACK				= "NASOD_HEALER_DYING_LAND_BACK",
	DYING_SKY					= "NASOD_HEALER_DYING_SKY",

	REVENGE_ATTACK				= "",	
}

INIT_AI = 
{
	TARGET = 
	{
		TARGET_NPC					= TRUE,
		TARGET_PRIORITY 			= TARGET_PRIORITY["TP_LOW_HP_FIRST"],
		TARGET_INTERVAL				= 3,		-- sec
		TARGET_NEAR_RANGE			= 150,		-- 이 거리보다 가까우면 TARGET_SUCCESS_RATE에 관계없이 무조건 타게팅된다
		TARGET_RANGE				= 800,		-- cm
		TARGET_LOST_RANGE			= 1000,		-- cm
		TARGET_SUCCESS_RATE			= 100,  --100,		-- %
		ATTACK_TARGET_RATE			= 100, -- 100,		-- 나를 공격한 유닛을 타게팅할 확률
		PRESERVE_LAST_TARGET_RATE	= 100, -- 30,		-- 이전에 타게팅된 유닛을 계속 타게팅할 확률
	},

	CHASE_MOVE = 
	{		
		MOVE_SPLIT_RANGE	= 600,
		DEST_GAP			= 500,	-- 목적지에서 이 거리 안에 있으면 도착했다고 판단한다
		MOVE_GAP			= 510,
		
		DIR_CHANGE_INTERVAL = 0.7,
		
		WALK_INTERVAL		= 3,
		NEAR_WALK_RATE		= 100,   --  70,
		FAR_WALK_RATE		= 100,   -- 30,
		
		JUMP_INTERVAL		= 15,
		UP_JUMP_RATE		= 100, -- 30,
		UP_DOWN_RATE		= 20,
		DOWN_JUMP_RATE		= 100,    --  20,
		DOWN_DOWN_RATE		= 40,
	},	
	
	PATROL_MOVE = 	
	{
		PATROL_BEGIN_RATE		= 100, --50,		
		PATROL_RANGE			= 200,
		PATROL_COOL_TIME		= 2,
		ONLY_THIS_LINE_GROUP	= TRUE,
	},
	
	ESCAPE_MOVE = 
	{		
		MOVE_SPLIT_RANGE	= 500,	-- cm
		ESCAPE_GAP			= 600,	-- 이 거리 보다 멀어지면 도망 성공
		
		WALK_INTERVAL		= 1.5,	-- 초
		NEAR_WALK_RATE		= 100,   --  10,
		FAR_WALK_RATE		= 100,   -- 10,
		
		JUMP_INTERVAL		= 10,
		UP_JUMP_RATE		= 100, -- 30,
		UP_DOWN_RATE		= 30,
		DOWN_JUMP_RATE		= 100,    --  30,
		DOWN_DOWN_RATE		= 30,
	},
	
	ESCAPE_CONDITION = 
	{
		RATE				= 100, -- 50,
		MY_HP				= 50,		-- %, 전체 HP에 대해 현재 HP의 비율
		ESCAPE_RANGE		= 200,		-- 이 범위 안에 들어오면 타격당하지 않아도 RATE에 지정된 확률로 도망
	}
}


NASOD_HEALER_WAIT = 
{
	ANIM_NAME					= "Wait",
	PLAY_TYPE					= XSKIN_ANIM_PLAYTYPE["XAP_LOOP"],
	TRANSITION					= TRUE,
	
	CAN_PUSH_UNIT				= TRUE,
	CAN_PASS_UNIT				= FALSE,	
	
	SPEED_X						= 0,
	SPEED_Y						= 0,
	
	IMMADIATE_PACKET_SEND		= TRUE,
	EVENT_INTERVAL_TIME0		= 2,
	
	EVENT_PROCESS = 
	{		
		{ STATE_CHANGE_TYPE["SCT_FOOT_ON_LINE_FALSE_DOWN"],	"NASOD_HEALER_JUMP_DOWN",					},
		
		{ STATE_CHANGE_TYPE["SCT_CONDITION_TABLE"],			"NASOD_HEALER_HEAL",						"CT_NASOD_HEALER_HEAL",	},
		
		{ STATE_CHANGE_TYPE["SCT_AI_WALK"],					"NASOD_HEALER_WALK",						},
		{ STATE_CHANGE_TYPE["SCT_AI_DASH"],					"NASOD_HEALER_WALK",						},
		{ STATE_CHANGE_TYPE["SCT_AI_JUMP"],					"NASOD_HEALER_JUMP_UP",						},
		{ STATE_CHANGE_TYPE["SCT_AI_JUMP_DIR"],				"NASOD_HEALER_JUMP_UP_DIR",					},
		{ STATE_CHANGE_TYPE["SCT_AI_DOWN"],					"NASOD_HEALER_JUMP_DOWN",					},
		{ STATE_CHANGE_TYPE["SCT_AI_DOWN_DIR"],				"NASOD_HEALER_JUMP_DOWN_DIR",				},
	},
	
	CT_NASOD_HEALER_HEAL = 
	{
		EVENT_INTERVAL_ID			= 0,
		DISTANCE_TO_TARGET_NEAR		= 700, 
		--ESCAPE_CHECK				= TRUE,
		RATE						= 100,
	},
	
	TALK_BOX =
	{
		EVENT_INTERVAL_ID			= 0,
		{ RATE = 7, MESSAGE = STR_ID_2570 },
	},
}


NASOD_HEALER_WALK = 
{
	ANIM_NAME					= "Walk",
	PLAY_TYPE					= XSKIN_ANIM_PLAYTYPE["XAP_LOOP"],
	TRANSITION					= TRUE,
	
	CAN_PUSH_UNIT				= TRUE,
	CAN_PASS_UNIT				= FALSE,
	
	PASSIVE_SPEED_X				= INIT_PHYSIC["WALK_SPEED"],
	
	ALLOW_DIR_CHANGE			= TRUE,
	IMMADIATE_PACKET_SEND		= TRUE,
	
	
	EVENT_INTERVAL_TIME0		= 2,
	
	EVENT_PROCESS = 
	{		
		{ STATE_CHANGE_TYPE["SCT_FOOT_ON_LINE_FALSE_DOWN"],	"NASOD_HEALER_JUMP_DOWN_DIR",				},
		
		{ STATE_CHANGE_TYPE["SCT_CONDITION_TABLE"],			"NASOD_HEALER_HEAL",						"CT_NASOD_HEALER_HEAL",			},
		
		{ STATE_CHANGE_TYPE["SCT_AI_WAIT"],					"NASOD_HEALER_WAIT",						},
		{ STATE_CHANGE_TYPE["SCT_AI_JUMP"],					"NASOD_HEALER_JUMP_UP",						},
		{ STATE_CHANGE_TYPE["SCT_AI_JUMP_DIR"],				"NASOD_HEALER_JUMP_UP_DIR",					},
		{ STATE_CHANGE_TYPE["SCT_AI_DOWN"],					"NASOD_HEALER_JUMP_DOWN",					},
		{ STATE_CHANGE_TYPE["SCT_AI_DOWN_DIR"],				"NASOD_HEALER_JUMP_DOWN_DIR",				},
	},
	
	CT_NASOD_HEALER_HEAL = 
	{
		EVENT_INTERVAL_ID			= 0,
		DISTANCE_TO_TARGET_NEAR		= 700,
		ESCAPE_CHECK				= TRUE,
		RATE						= 70,
	},
	
	TALK_BOX =
	{
		EVENT_INTERVAL_ID			= 0,
		{ RATE = 7, MESSAGE = STR_ID_2579 },
	},
	
}

NASOD_HEALER_JUMP_UP = 
{
	ANIM_NAME					= "JumpLanding",
	PLAY_TYPE					= XSKIN_ANIM_PLAYTYPE["XAP_LOOP"],
	TRANSITION					= TRUE,
	LAND_CONNECT				= FALSE,
	
	CAN_PUSH_UNIT				= TRUE,
	CAN_PASS_UNIT				= FALSE,
	
	SPEED_X						= 0,
	SPEED_Y						= INIT_PHYSIC["JUMP_SPEED"],
	ADD_POS_Y					= 45,
	
	IMMADIATE_PACKET_SEND		= TRUE,
	
	EVENT_PROCESS = 
	{		
		{ STATE_CHANGE_TYPE["SCT_NEGATIVE_Y_SPEED"],		"NASOD_HEALER_JUMP_DOWN",				},
	},
	
}

NASOD_HEALER_JUMP_DOWN = 
{
	ANIM_NAME					= "JumpLanding",
	PLAY_TYPE					= XSKIN_ANIM_PLAYTYPE["XAP_LOOP"],
	TRANSITION					= TRUE,
	LAND_CONNECT				= FALSE,
	
	CAN_PUSH_UNIT				= TRUE,
	CAN_PASS_UNIT				= FALSE,
	
	
	IMMADIATE_PACKET_SEND		= TRUE,
		
	EVENT_PROCESS = 
	{		
		{ STATE_CHANGE_TYPE["SCT_FOOT_ON_LINE_TRUE"],		"NASOD_HEALER_JUMP_LANDING",				},
	},
}

NASOD_HEALER_JUMP_UP_DIR = 
{
	ANIM_NAME					= "JumpLanding",
	PLAY_TYPE					= XSKIN_ANIM_PLAYTYPE["XAP_LOOP"],
	TRANSITION					= TRUE,
	LAND_CONNECT				= FALSE,
	
	CAN_PUSH_UNIT				= TRUE,
	CAN_PASS_UNIT				= FALSE,
	
	PASSIVE_SPEED_X				= INIT_PHYSIC["WALK_SPEED"],
	SPEED_Y						= INIT_PHYSIC["JUMP_SPEED"],
	ADD_POS_Y					= 45,
	
	IMMADIATE_PACKET_SEND		= TRUE,
	
	EVENT_PROCESS = 
	{		
		{ STATE_CHANGE_TYPE["SCT_NEGATIVE_Y_SPEED"],		"NASOD_HEALER_JUMP_DOWN_DIR",				},
	},
}

NASOD_HEALER_JUMP_DOWN_DIR = 
{
	ANIM_NAME					= "JumpLanding",
	PLAY_TYPE					= XSKIN_ANIM_PLAYTYPE["XAP_LOOP"],
	TRANSITION					= TRUE,
	LAND_CONNECT				= FALSE,
	
	CAN_PUSH_UNIT				= TRUE,
	CAN_PASS_UNIT				= FALSE,
	
	
	PASSIVE_SPEED_X				= INIT_PHYSIC["WALK_SPEED"],
	
	IMMADIATE_PACKET_SEND		= TRUE,
		
	EVENT_PROCESS = 
	{		
		{ STATE_CHANGE_TYPE["SCT_FOOT_ON_LINE_TRUE"],		"NASOD_HEALER_JUMP_LANDING",				},
	},
}

NASOD_HEALER_JUMP_LANDING = 
{
	ANIM_NAME					= "Wait",
	PLAY_TYPE					= XSKIN_ANIM_PLAYTYPE["XAP_ONE_WAIT"],
	TRANSITION					= TRUE,
	LAND_CONNECT				= FALSE,
	
	CAN_PUSH_UNIT				= TRUE,
	CAN_PASS_UNIT				= FALSE,
	
	SPEED_X						= 0,
	SPEED_Y						= 0,
		
	IMMADIATE_PACKET_SEND		= TRUE,

	EVENT_PROCESS = 
	{		
		{ STATE_CHANGE_TYPE["SCT_FOOT_ON_LINE_FALSE_DOWN"],	"NASOD_HEALER_JUMP_DOWN",				},
		{ STATE_CHANGE_TYPE["SCT_MOTION_END"],				"NASOD_HEALER_WAIT",					},
	},
}

NASOD_HEALER_HEAL = 
{
	ANIM_NAME					= "Healing",
	PLAY_TYPE					= XSKIN_ANIM_PLAYTYPE["XAP_ONE_WAIT"],
	TRANSITION					= FALSE,
	LAND_CONNECT				= FALSE,
	
	CAN_PUSH_UNIT				= TRUE,
	CAN_PASS_UNIT				= FALSE,
	
	SPEED_X						= 0,
	SPEED_Y						= 0,	

    SOUND_PLAY0			= { 0.408, "Nasod_Healer_Heal.ogg" },

	--VIEW_TARGET					= TRUE,
	
	IMMADIATE_PACKET_SEND		= TRUE,
	
	TALK_BOX = 
	{
		{ RATE = 10, MESSAGE = STR_ID_1779 },
	},
		
	EVENT_PROCESS = 
	{		
		{ STATE_CHANGE_TYPE["SCT_FOOT_ON_LINE_FALSE_DOWN"],	"NASOD_HEALER_JUMP_DOWN",				},
		{ STATE_CHANGE_TYPE["SCT_MOTION_END"],				"NASOD_HEALER_WAIT",					},
	},
	
	--ATTACK_TIME0				= { 0.36, 0.78, },

}


NASOD_HEALER_DAMAGE = 
{
	ANIM_NAME					= "Damage",
	PLAY_TYPE					= XSKIN_ANIM_PLAYTYPE["XAP_ONE_WAIT"],
	TRANSITION					= FALSE,
	LAND_CONNECT				= FALSE,
	
	CAN_PUSH_UNIT				= TRUE,
	CAN_PASS_UNIT				= FALSE,
	
	TALK_BOX = 
	{
		{ RATE = 8, MESSAGE = STR_ID_2568 },
		{ RATE = 8, MESSAGE = STR_ID_1715 },
	},
	
	EVENT_PROCESS = 
	{
		{ STATE_CHANGE_TYPE["SCT_MOTION_END"],						"NASOD_HEALER_WAIT",						},
	},
}


NASOD_HEALER_DAMAGE_DOWN_FRONT = 
{
	ANIM_NAME					= "DamageDown",
	PLAY_TYPE					= XSKIN_ANIM_PLAYTYPE["XAP_ONE_WAIT"],
	TRANSITION					= FALSE,
	LAND_CONNECT				= FALSE,

	SUPER_ARMOR					= TRUE,
	DEFENCE						= { 0, 100, 20, },
	
	CAN_PUSH_UNIT				= TRUE,
	CAN_PASS_UNIT				= FALSE,
	
	TALK_BOX = 
	{
		{ RATE = 8, MESSAGE = STR_ID_1756 },
	},
	
	EVENT_PROCESS = 
	{
		{ STATE_CHANGE_TYPE["SCT_FOOT_ON_LINE_FALSE_DOWN"],		"NASOD_HEALER_DAMAGE_AIR_FALL",			},
		{ STATE_CHANGE_TYPE["SCT_MOTION_END"],					"NASOD_HEALER_STAND_UP_FRONT",			},
	},
	
}

NASOD_HEALER_DAMAGE_DOWN_BACK = 
{
	ANIM_NAME					= "DamageDown",
	PLAY_TYPE					= XSKIN_ANIM_PLAYTYPE["XAP_ONE_WAIT"],
	TRANSITION					= FALSE,
	LAND_CONNECT				= FALSE,
	
	SUPER_ARMOR					= TRUE,
	DEFENCE						= { 0, 100, 20, },
	
	CAN_PUSH_UNIT				= TRUE,
	CAN_PASS_UNIT				= FALSE,
	
	TALK_BOX = 
	{
		{ RATE = 8, MESSAGE = STR_ID_1756 },
	},
	
	EVENT_PROCESS = 
	{
		{ STATE_CHANGE_TYPE["SCT_FOOT_ON_LINE_FALSE_DOWN"],		"NASOD_HEALER_DAMAGE_AIR_FALL",			},
		{ STATE_CHANGE_TYPE["SCT_MOTION_END"],					"NASOD_HEALER_STAND_UP_BACK",			},
	},
}


NASOD_HEALER_DAMAGE_AIR = 
{
	ANIM_NAME					= "Damage",
	PLAY_TYPE					= XSKIN_ANIM_PLAYTYPE["XAP_ONE_WAIT"],
	TRANSITION					= FALSE,
	LAND_CONNECT				= FALSE,
	
	CAN_PUSH_UNIT				= TRUE,
	CAN_PASS_UNIT				= FALSE,
	
	EVENT_PROCESS = 
	{
		{ STATE_CHANGE_TYPE["SCT_FOOT_ON_LINE_TRUE"],			"NASOD_HEALER_WAIT",					},
	},
}

NASOD_HEALER_DAMAGE_AIR_DOWN = 
{
	ANIM_NAME					= "DamageAirDown",
	PLAY_TYPE					= XSKIN_ANIM_PLAYTYPE["XAP_ONE_WAIT"],
	TRANSITION					= FALSE,
	LAND_CONNECT				= FALSE,
	
	CAN_PUSH_UNIT				= TRUE,
	CAN_PASS_UNIT				= FALSE,
	
	EVENT_PROCESS = 
	{
		{ STATE_CHANGE_TYPE["SCT_FOOT_ON_LINE_TRUE"],			"NASOD_HEALER_DAMAGE_AIR_DOWN_LANDING",	},
	},
}

NASOD_HEALER_DAMAGE_AIR_UP = 
{
	ANIM_NAME					= "DamageAirUp",
	PLAY_TYPE					= XSKIN_ANIM_PLAYTYPE["XAP_ONE_WAIT"],
	TRANSITION					= FALSE,
	LAND_CONNECT				= FALSE,
	
	CAN_PUSH_UNIT				= TRUE,
	CAN_PASS_UNIT				= FALSE,
	
	EVENT_PROCESS = 
	{
		{ STATE_CHANGE_TYPE["SCT_NEGATIVE_Y_SPEED"],		"NASOD_HEALER_DAMAGE_AIR_FALL",			},
		{ STATE_CHANGE_TYPE["SCT_FOOT_ON_LINE_TRUE"],		"NASOD_HEALER_DAMAGE_AIR_DOWN_LANDING",	},
	},
	TALK_BOX =
	{
		{ RATE = 10, MESSAGE = STR_ID_2568 },
 	},

}

NASOD_HEALER_DAMAGE_AIR_FALL = 
{
	ANIM_NAME					= "DamageAirFall",
	PLAY_TYPE					= XSKIN_ANIM_PLAYTYPE["XAP_ONE_WAIT"],
	TRANSITION					= FALSE,
	LAND_CONNECT				= FALSE,
	
	CAN_PUSH_UNIT				= TRUE,
	CAN_PASS_UNIT				= FALSE,
	
	EVENT_PROCESS = 
	{
		{ STATE_CHANGE_TYPE["SCT_POSITIVE_Y_SPEED"],		"NASOD_HEALER_DAMAGE_AIR_UP",			},
		{ STATE_CHANGE_TYPE["SCT_FOOT_ON_LINE_TRUE"],		"NASOD_HEALER_DAMAGE_AIR_DOWN_LANDING",	},
	},
}

NASOD_HEALER_DAMAGE_AIR_DOWN_LANDING = 
{
	ANIM_NAME					= "DamageAirDownLanding",
	PLAY_TYPE					= XSKIN_ANIM_PLAYTYPE["XAP_ONE_WAIT"],
	TRANSITION					= FALSE,
	LAND_CONNECT				= FALSE,
	
	SUPER_ARMOR					= TRUE,
	DEFENCE						= { 0, 100, 20, },
	
	CAN_PUSH_UNIT				= TRUE,
	CAN_PASS_UNIT				= FALSE,
	
	EVENT_PROCESS = 
	{
		{ STATE_CHANGE_TYPE["SCT_FOOT_ON_LINE_FALSE_DOWN"],	"NASOD_HEALER_DAMAGE_AIR_FALL",			},
		{ STATE_CHANGE_TYPE["SCT_MOTION_END"],				"NASOD_HEALER_STAND_UP_FRONT",			},
	},
	
}

NASOD_HEALER_DAMAGE_FLY_FRONT = 
{
	ANIM_NAME					= "DamageAirFall",
	PLAY_TYPE					= XSKIN_ANIM_PLAYTYPE["XAP_ONE_WAIT"],
	TRANSITION					= FALSE,
	LAND_CONNECT				= FALSE,	
	
	CAN_PUSH_UNIT				= TRUE,
	CAN_PASS_UNIT				= FALSE,
	
	EVENT_PROCESS = 
	{
		{ STATE_CHANGE_TYPE["SCT_FOOT_ON_LINE_TRUE"],			"NASOD_HEALER_DAMAGE_DOWN_FRONT",		},
	},
}

NASOD_HEALER_DAMAGE_FLY_BACK = 
{
	ANIM_NAME					= "DamageAirUp",
	PLAY_TYPE					= XSKIN_ANIM_PLAYTYPE["XAP_ONE_WAIT"],
	TRANSITION					= FALSE,
	LAND_CONNECT				= FALSE,	
	
	CAN_PUSH_UNIT				= TRUE,
	CAN_PASS_UNIT				= FALSE,
	
	EVENT_PROCESS = 
	{
		{ STATE_CHANGE_TYPE["SCT_FOOT_ON_LINE_TRUE"],			"NASOD_HEALER_DAMAGE_DOWN_BACK",		},
	},
}


NASOD_HEALER_STAND_UP_FRONT = 
{
	ANIM_NAME					= "DamageStandUp",
	PLAY_TYPE					= XSKIN_ANIM_PLAYTYPE["XAP_ONE_WAIT"],
	TRANSITION					= FALSE,
	LAND_CONNECT				= FALSE,	
	
	SUPER_ARMOR					= TRUE,
	DEFENCE						= { 0, 100, 20, },
	
	CAN_PUSH_UNIT				= TRUE,
	CAN_PASS_UNIT				= FALSE,
	
	EVENT_PROCESS = 
	{
		{ STATE_CHANGE_TYPE["SCT_FOOT_ON_LINE_FALSE_DOWN"],	"NASOD_HEALER_JUMP_DOWN",			},
		{ STATE_CHANGE_TYPE["SCT_MOTION_END"],				"NASOD_HEALER_WAIT",				},
	},
}

NASOD_HEALER_STAND_UP_BACK = 
{
	ANIM_NAME					= "DamageStandUp",
	PLAY_TYPE					= XSKIN_ANIM_PLAYTYPE["XAP_ONE_WAIT"],
	TRANSITION					= FALSE,
	LAND_CONNECT				= FALSE,
	
	SUPER_ARMOR					= TRUE,
	DEFENCE						= { 0, 100, 20, },
		
	CAN_PUSH_UNIT				= TRUE,
	CAN_PASS_UNIT				= FALSE,
		
	EVENT_PROCESS = 
	{
		{ STATE_CHANGE_TYPE["SCT_FOOT_ON_LINE_FALSE_DOWN"],	"NASOD_HEALER_JUMP_DOWN",		},
		{ STATE_CHANGE_TYPE["SCT_MOTION_END"],				"NASOD_HEALER_WAIT",			},
	},		
}

NASOD_HEALER_DYING_LAND_FRONT = 
{
	ANIM_NAME					= "DamageDown",
	PLAY_TYPE					= XSKIN_ANIM_PLAYTYPE["XAP_ONE_WAIT"],
	TRANSITION					= FALSE,
	LAND_CONNECT				= FALSE,

	INVINCIBLE					= { 0, 100, }, 		
	
	CAN_PUSH_UNIT				= FALSE,
	CAN_PASS_UNIT				= TRUE,
	
	DYING_END					= TRUE,
	
	IMMADIATE_PACKET_SEND		= TRUE,
}
	
NASOD_HEALER_DYING_LAND_BACK = 
{
	ANIM_NAME					= "DamageDown",
	PLAY_TYPE					= XSKIN_ANIM_PLAYTYPE["XAP_ONE_WAIT"],
	TRANSITION					= FALSE,
	LAND_CONNECT				= FALSE,
	
	INVINCIBLE					= { 0, 100, }, 		
	
	CAN_PUSH_UNIT				= FALSE,
	CAN_PASS_UNIT				= TRUE,
	
	DYING_END					= TRUE,	
	
	IMMADIATE_PACKET_SEND		= TRUE,
}

NASOD_HEALER_DYING_SKY = 
{
	ANIM_NAME					= "DamageAirDownLanding",
	PLAY_TYPE					= XSKIN_ANIM_PLAYTYPE["XAP_ONE_WAIT"],
	TRANSITION					= FALSE,
	LAND_CONNECT				= FALSE,
	
	INVINCIBLE					= { 0, 100, }, 		
	
	CAN_PUSH_UNIT				= FALSE,
	CAN_PASS_UNIT				= TRUE,
	
	DYING_END					= TRUE,
	
	IMMADIATE_PACKET_SEND		= TRUE,
}









--------------------------------------------------------------------
--------------------------------------------------------------------

function NASOD_HEALER_JUMP_DOWN_STATE_END( pKTDXApp, pX2Game, pNPCUnit )

	local pMinorParticle = pX2Game:GetMinorParticle()
	pMinorParticle:GameUnitCreateSequence_LUA( pNPCUnit, "StepSmoke", pNPCUnit:GetLandPosition_LUA(), D3DXVECTOR2(100,100), D3DXVECTOR2(5,-1) )

end

function NASOD_HEALER_JUMP_DOWN_DIR_STATE_END( pKTDXApp, pX2Game, pNPCUnit )

	local pMinorParticle = pX2Game:GetMinorParticle()
	pMinorParticle:GameUnitCreateSequence_LUA( pNPCUnit, "StepSmoke", pNPCUnit:GetLandPosition_LUA(), D3DXVECTOR2(100,100), D3DXVECTOR2(5,-1) )

end





function NASOD_HEALER_HEAL_FRAME_MOVE( pKTDXApp, pX2Game, pNPCUnit )

	
	if pNPCUnit:AnimEventTimer_LUA( 0.43 ) then
	
		local vPos = pNPCUnit:GetBonePos_LUA( "Bone_Jewelry" )
		local pMinorParticle = pX2Game:GetMinorParticle()	
		pMinorParticle:GameUnitCreateSequence_LUA( pNPCUnit, "TimeStop1", vPos, D3DXVECTOR2(100,100), D3DXVECTOR2(1,-1) )
	
	end
	
	if pNPCUnit:AnimEventTimer_LUA( 0.63 ) then
	
		local pMajorParticle = pX2Game:GetMajorParticle()	
		
		local vPos = pNPCUnit:GetBonePos_LUA( "Bone_Jewelry" )
		local fDist = 700.0
		--nCount = 0
		local nUnitListSize = pX2Game:GetNPCUnitListSize()
				
		for i=0, nUnitListSize-1 do 
			
			local pUnit = pX2Game:GetNPCUnit( i )
			
			if pUnit ~= nil and
				pUnit:GetUID() ~= pNPCUnit:GetUID() and
				pUnit:GetTeam() == pNPCUnit:GetTeam() and				
				pUnit:GetNowHP() > 0 and				
				pUnit:GetDistanceFrom(vPos) < fDist and				
				pUnit:GetNowHP() < pUnit:GetMaxHP() then
				
				pMajorParticle:GameUnitCreateSequence_LUA( pNPCUnit, "Heal_Effect01", pUnit:GetPos(), D3DXVECTOR2(-1,-1), D3DXVECTOR2(-1,-1) )
				pMajorParticle:GameUnitCreateSequence_LUA( pNPCUnit, "LobbyLevelUp01", pUnit:GetPos(), D3DXVECTOR2(-1,-1), D3DXVECTOR2(-1,-1) )
				
				--healedHP = pUnit:GetNowHP() + 5000.0 * pNPCUnit:GetHardLevel()
				local healedHP = pUnit:GetNowHP() + pUnit:GetMaxHP() * 0.3 -- 최대 HP의 20% healing
				if healedHP > pUnit:GetMaxHP() then
					
					healedHP = pUnit:GetMaxHP()
				
				end
				
				pUnit:SetNowHP_LUA( healedHP )
								
			end
				
		end
		
	end

end




function NASOD_HEALER_DAMAGE_FRAME_MOVE( pKTDXApp, pX2Game, pNPCUnit )

	if pNPCUnit:AnimEventTimer_LUA( 0.047 ) then
		local pMinorParticle = pX2Game:GetMinorParticle()
		pMinorParticle:GameUnitCreateSequence_LUA( pNPCUnit, "StepSmoke", pNPCUnit:GetLandPosition_LUA(), D3DXVECTOR2(100,100), D3DXVECTOR2(5,-1) )
	end

end

function NASOD_HEALER_DAMAGE_DOWN_FRONT_FRAME_MOVE( pKTDXApp, pX2Game, pNPCUnit )

	if pNPCUnit:AnimEventTimer_LUA( 0.3 ) then
		pNPCUnit:PlaySound_LUA( "Down.ogg" )
		local pMinorParticle = pX2Game:GetMinorParticle()
		pMinorParticle:GameUnitCreateSequence_LUA( pNPCUnit, "DownSmoke", pNPCUnit:GetLandPosition_LUA(), D3DXVECTOR2(100,100), D3DXVECTOR2(7,-1) )
	end

end

function NASOD_HEALER_DAMAGE_DOWN_BACK_FRAME_MOVE( pKTDXApp, pX2Game, pNPCUnit )

	if pNPCUnit:AnimEventTimer_LUA( 0.2 ) then
		pNPCUnit:PlaySound_LUA( "Down.ogg" )
		local pMinorParticle = pX2Game:GetMinorParticle()
		pMinorParticle:GameUnitCreateSequence_LUA( pNPCUnit, "DownSmoke", pNPCUnit:GetLandPosition_LUA(), D3DXVECTOR2(100,100), D3DXVECTOR2(7,-1) )
	end

end

function NASOD_HEALER_DAMAGE_AIR_DOWN_LANDING_FRAME_MOVE( pKTDXApp, pX2Game, pNPCUnit )

	if pNPCUnit:AnimEventTimer_LUA( 0.01 ) then
		pNPCUnit:PlaySound_LUA( "Down.ogg" )
		local pMinorParticle = pX2Game:GetMinorParticle()
		local pos = pNPCUnit:GetLandPosition_LUA()
		pMinorParticle:GameUnitCreateSequence_LUA( pNPCUnit, "DownSmoke", pos, D3DXVECTOR2(100,100), D3DXVECTOR2(7,-1) )
		pos.y = pos.y + 5
		pMinorParticle:GameUnitCreateSequence_LUA( pNPCUnit, "GroundShockWave", pos, D3DXVECTOR2(100,100), D3DXVECTOR2(1,-1) )
		local pParticle = pMinorParticle:GameUnitCreateSequence_LUA( pNPCUnit, "AirDownTick", pNPCUnit:GetPos(), D3DXVECTOR2(200,200), D3DXVECTOR2(10,-1) )
		if pParticle ~= nil then
			pParticle:SetLandPosition( pos.y - 5 )
		end
		
		if GetDistance_LUA( pNPCUnit:GetPos(), pX2Game:GetFocusUnitPos_LUA() ) < 500 then
			pX2Game:GetX2Camera():GetCamera():UpDownCrashCameraNoReset( 10.0, 0.1 )
		end		
		
	elseif pNPCUnit:AnimEventTimer_LUA( 0.44 ) then
		pNPCUnit:PlaySound_LUA( "Down.ogg" )
		local pMinorParticle = pX2Game:GetMinorParticle()
		pMinorParticle:GameUnitCreateSequence_LUA( pNPCUnit, "DownSmoke", pNPCUnit:GetLandPosition_LUA(), D3DXVECTOR2(100,100), D3DXVECTOR2(7,-1) )
	end

end



	

function NASOD_HEALER_DYING_LAND_STATE_START( pKTDXApp, pX2Game, pNPCUnit )

	
	local pos = pNPCUnit:GetPos()
	pos.y = pos.y + 100.0
	local GetMinorParticle = pX2Game:GetMinorParticle()
	
	local pSeq = GetMinorParticle:GameUnitCreateSequence_LUA( pNPCUnit, "DieLight",		pos, D3DXVECTOR2(-1,-1), D3DXVECTOR2(3,-1) )
	if pSeq ~= nil then
	
		pSeq:SetLandPosition( pNPCUnit:GetLandPosition_LUA().y )
		pNPCUnit:SetDieSeq( pSeq:GetHandle() )
	
	end
	pNPCUnit:PlaySound_LUA( "DieLight.ogg" )
	
end
