-- lua header. UTF-8 인코딩 인식을 위해 이 줄은 지우지 마세요.

g_pEventScene:AddEventSceneObject_LUA
{
	SCENE_OBJECT_NAME = "PLAYER0",

	SCENE_OBJECT_TYPE = SCENE_OBJECT_TYPE["OT_XSKINMESH"],
	
	FILE_NAME = "UI_NPC_ELSWORD.x",
	XET_NAME = "UI_NPC_ELSWORD.XET",
	SCALE = {1.1, 1.1},

	RIGHT_POS = { 300, -150 },
	LEFT_POS = { -300, -150 },
	CENTER_POS = { 0, -150 },

}

g_pEventScene:AddEventSceneObject_LUA
{
	SCENE_OBJECT_NAME = "PLAYER1",

	SCENE_OBJECT_TYPE = SCENE_OBJECT_TYPE["OT_XSKINMESH"],
	FILE_NAME = "UI_NPC_AISHA.x",
	XET_NAME = "UI_NPC_AISHA.XET",
	SCALE = {1.1, 1.1},

	RIGHT_POS = { 300, -150 },
	LEFT_POS = { -300, -150 },
	CENTER_POS = { 0, -150 },
}

g_pEventScene:AddEventSceneObject_LUA
{
	SCENE_OBJECT_NAME = "PLAYER2",

	SCENE_OBJECT_TYPE = SCENE_OBJECT_TYPE["OT_XSKINMESH"],
	FILE_NAME = "UI_NPC_RENA.x",
	XET_NAME = "UI_NPC_RENA.XET",
	SCALE = {1.1, 1.1},

	RIGHT_POS = { 300, -170 },
	LEFT_POS = { -300, -170 },
	CENTER_POS = { 0, -170 },

}

g_pEventScene:AddEventSceneObject_LUA
{
	SCENE_OBJECT_NAME = "PLAYER3",

	SCENE_OBJECT_TYPE = SCENE_OBJECT_TYPE["OT_XSKINMESH"],
	FILE_NAME = "UI_NPC_RAVEN.x",
	XET_NAME = "UI_NPC_RAVEN.XET",
	SCALE = {1.1, 1.1},

	RIGHT_POS = { 300, -150 },
	LEFT_POS = { -300, -150 },
	CENTER_POS = { 0, -150 },

}

g_pEventScene:AddEventSceneObject_LUA
{
	SCENE_OBJECT_NAME = "PLAYER4",

	SCENE_OBJECT_TYPE = SCENE_OBJECT_TYPE["OT_XSKINMESH"],
	FILE_NAME = "UI_NPC_EVE.x",
	XET_NAME = "UI_NPC_EVE.XET",
	SCALE = {-1.1, 1.1},

	RIGHT_POS = { 300, -150 },
	LEFT_POS = { -300, -150 },
	CENTER_POS = { 0, -150 },

}

g_pEventScene:AddEventSceneObject_LUA
{
	SCENE_OBJECT_NAME = "PLAYER5",

	SCENE_OBJECT_TYPE = SCENE_OBJECT_TYPE["OT_XSKINMESH"],
	FILE_NAME = "UI_NPC_Chung.x",
	XET_NAME = "UI_NPC_Chung.XET",
	SCALE = {-0.95, 0.95},

	RIGHT_POS = { 300, -185 },
	LEFT_POS = { -300, -185 },
	CENTER_POS = { 0, -185 },

}

g_pEventScene:AddEventSceneObject_LUA
{
	SCENE_OBJECT_NAME = "PLAYER6",

	SCENE_OBJECT_TYPE = SCENE_OBJECT_TYPE["OT_XSKINMESH"],
	FILE_NAME = "UI_NPC_Ara.x",
	XET_NAME = "UI_NPC_Ara.XET",
	SCALE = {-0.65, 0.65},

	RIGHT_POS = { 300, -150 },
	LEFT_POS = { -300, -150 },
	CENTER_POS = { 0, -150 },

}

g_pEventScene:AddEventSceneObject_LUA
{
	SCENE_OBJECT_NAME = "LOW",

	SCENE_OBJECT_TYPE = SCENE_OBJECT_TYPE["OT_XSKINMESH"],
	FILE_NAME = "UI_NPC_LOW.x",
	XET_NAME = "UI_NPC_LOW.XET",
	SCALE = {1.0, 1.0},

	RIGHT_POS = { 300, -150 },
	LEFT_POS = { -300, -150 },
	CENTER_POS = { 0, -150 },

}

g_pEventScene:AddEventSceneObject_LUA
{
	SCENE_OBJECT_NAME = "HAGERS",

	SCENE_OBJECT_TYPE = SCENE_OBJECT_TYPE["OT_XSKINMESH"],
	FILE_NAME = "UI_NPC_HAGERS.x",
	XET_NAME = "UI_NPC_HAGERS.XET",
	SCALE = {0.85, 0.85},

	RIGHT_POS = { 300, -200 },
	LEFT_POS = { -300, -200 },
	CENTER_POS = { 0, -200 },

}

g_pEventScene:AddEventSceneObject_LUA
{
	SCENE_OBJECT_NAME = "ADAMS",

	SCENE_OBJECT_TYPE = SCENE_OBJECT_TYPE["OT_XSKINMESH"],
	FILE_NAME = "UI_NPC_ADAMS.x",
	XET_NAME = "UI_NPC_ADAMS.XET",
	SCALE = {1.0, 1.0},

	RIGHT_POS = { 300, -140 },
	LEFT_POS = { -300, -140 },
	CENTER_POS = { 0, -140 },

}

g_pEventScene:AddEventSceneObject_LUA
{
	SCENE_OBJECT_NAME = "ANNE",

	SCENE_OBJECT_TYPE = SCENE_OBJECT_TYPE["OT_XSKINMESH"],
	FILE_NAME = "UI_NPC_ANNE.X",
	XET_NAME = "UI_NPC_ANNE.XET",
	SCALE = {1.05, 1.05},

	RIGHT_POS = { 300, -140 },
	LEFT_POS = { -300, -140 },
	CENTER_POS = { 0, -140 },

}

g_pEventScene:AddEventSceneObject_LUA
{
	SCENE_OBJECT_NAME = "HOFMANN",

	SCENE_OBJECT_TYPE = SCENE_OBJECT_TYPE["OT_XSKINMESH"],
	FILE_NAME = "UI_NPC_HOFMANN.x",
	XET_NAME = "UI_NPC_HOFMANN.XET",
	SCALE = {0.9, 0.9},

	RIGHT_POS = { 300, -170 },
	LEFT_POS = { -300, -170 },
	CENTER_POS = { 0, -170 },

}

g_pEventScene:AddEventSceneObject_LUA
{
	SCENE_OBJECT_NAME = "LENPAD",

	SCENE_OBJECT_TYPE = SCENE_OBJECT_TYPE["OT_XSKINMESH"],
	FILE_NAME = "UI_NPC_LENPAD.x",
	XET_NAME = "UI_NPC_LENPAD.XET",
	SCALE = {1.0, 1.0},

	RIGHT_POS = { 300, -170 },
	LEFT_POS = { -300, -170 },
	CENTER_POS = { 0, -170 },

}

g_pEventScene:AddEventSceneObject_LUA
{
	SCENE_OBJECT_NAME = "LUICHEL",

	SCENE_OBJECT_TYPE = SCENE_OBJECT_TYPE["OT_XSKINMESH"],
	FILE_NAME = "UI_NPC_LUICHEL.x",
	XET_NAME = "UI_NPC_LUICHEL.XET",
	SCALE = {0.95, 0.95},

	RIGHT_POS = { 300, -150 },
	LEFT_POS = { -300, -150 },
	CENTER_POS = { 0, -150 },

}

g_pEventScene:AddEventSceneObject_LUA
{
	SCENE_OBJECT_NAME = "ECHO",

	SCENE_OBJECT_TYPE = SCENE_OBJECT_TYPE["OT_XSKINMESH"],
	FILE_NAME = "UI_NPC_ECHO.x",
	XET_NAME = "UI_NPC_ECHO.XET",
	SCALE = {0.8, 0.8},

	RIGHT_POS = { 300, -200 },
	LEFT_POS = { -300, -200 },
	CENTER_POS = { 0, -200 },

}

g_pEventScene:AddEventSceneObject_LUA
{
	SCENE_OBJECT_NAME = "TOMA",

	SCENE_OBJECT_TYPE = SCENE_OBJECT_TYPE["OT_XSKINMESH"],
	FILE_NAME = "UI_NPC_TOMA.x",
	XET_NAME = "UI_NPC_TOMA.XET",
	SCALE = {1.0, 1.0},

	RIGHT_POS = { 300, -150 },
	LEFT_POS = { -300, -150 },
	CENTER_POS = { 0, -150 },

}


g_pEventScene:AddEventSceneObject_LUA
{
	SCENE_OBJECT_NAME = "STELLA",

	SCENE_OBJECT_TYPE = SCENE_OBJECT_TYPE["OT_XSKINMESH"],
	FILE_NAME = "UI_NPC_STELLA.x",
	XET_NAME = "UI_NPC_STELLA.XET",
	SCALE = {0.9, 0.9},

	RIGHT_POS = { 300, -150 },
	LEFT_POS = { -300, -150 },
	CENTER_POS = { 0, -150 },

}

g_pEventScene:AddEventSceneObject_LUA
{
	SCENE_OBJECT_NAME = "CHACHABUK",

	SCENE_OBJECT_TYPE = SCENE_OBJECT_TYPE["OT_XSKINMESH"],
	FILE_NAME = "UI_NPC_CHACHABUK.x",
	XET_NAME = "UI_NPC_CHACHABUK.XET",
	SCALE = {0.95, 0.95},

	RIGHT_POS = { 300, -150 },
	LEFT_POS = { -300, -150 },
	CENTER_POS = { 0, -150 },

}

g_pEventScene:AddEventSceneObject_LUA
{
	SCENE_OBJECT_NAME = "RICHANG",

	SCENE_OBJECT_TYPE = SCENE_OBJECT_TYPE["OT_XSKINMESH"],
	FILE_NAME = "UI_NPC_RICHANG.x",
	XET_NAME = "UI_NPC_RICHANG.XET",
	SCALE = {1.0, 1.0},

	RIGHT_POS = { 300, -130 },
	LEFT_POS = { -300, -130 },
	CENTER_POS = { 0, -130 },

}

g_pEventScene:AddEventSceneObject_LUA
{
	SCENE_OBJECT_NAME = "ADEL",

	SCENE_OBJECT_TYPE = SCENE_OBJECT_TYPE["OT_XSKINMESH"],
	FILE_NAME = "UI_NPC_ADEL.x",
	XET_NAME = "UI_NPC_ADEL.XET",
	SCALE = {0.75, 0.75},

	RIGHT_POS = { 300, -200 },
	LEFT_POS = { -300, -200 },
	CENTER_POS = { 0, -200 },

}


g_pEventScene:AddEventSceneObject_LUA
{
	SCENE_OBJECT_NAME = "AGATHA",

	SCENE_OBJECT_TYPE = SCENE_OBJECT_TYPE["OT_XSKINMESH"],
	FILE_NAME = "UI_NPC_AGATHA.x",
	XET_NAME = "UI_NPC_AGATHA.XET",
	SCALE = {0.8, 0.8},

	RIGHT_POS = { 300, -180 },
	LEFT_POS = { -300, -180 },
	CENTER_POS = { 0, -180 },

}

g_pEventScene:AddEventSceneObject_LUA
{
	SCENE_OBJECT_NAME = "AIDA",

	SCENE_OBJECT_TYPE = SCENE_OBJECT_TYPE["OT_XSKINMESH"],
	FILE_NAME = "UI_NPC_AIDA.x",
	XET_NAME = "UI_NPC_AIDA.XET",
	SCALE = {0.75, 0.75},

	RIGHT_POS = { 300, -200 },
	LEFT_POS = { -300, -200 },
	CENTER_POS = { 0, -200 },

}


g_pEventScene:AddEventSceneObject_LUA
{
	SCENE_OBJECT_NAME = "AMOS",

	SCENE_OBJECT_TYPE = SCENE_OBJECT_TYPE["OT_XSKINMESH"],
	FILE_NAME = "UI_NPC_AMOS.x",
	XET_NAME = "UI_NPC_AMOS.XET",
	SCALE = {0.8, 0.8},

	RIGHT_POS = { 300, -180 },
	LEFT_POS = { -300, -180 },
	CENTER_POS = { 0, -180 },

}

g_pEventScene:AddEventSceneObject_LUA
{
	SCENE_OBJECT_NAME = "ALLEGRO",

	SCENE_OBJECT_TYPE = SCENE_OBJECT_TYPE["OT_XSKINMESH"],
	FILE_NAME = "UI_NPC_ALLEGRO.x",
	XET_NAME = "UI_NPC_ALLEGRO.XET",
	SCALE = {0.85, 0.85},

	RIGHT_POS = { 300, -175 },
	LEFT_POS = { -300, -175 },
	CENTER_POS = { 0, -175 },

}


g_pEventScene:AddEventSceneObject_LUA
{
	SCENE_OBJECT_NAME = "LENTO",

	SCENE_OBJECT_TYPE = SCENE_OBJECT_TYPE["OT_XSKINMESH"],
	FILE_NAME = "UI_NPC_LENTO.x",
	XET_NAME = "UI_NPC_LENTO.XET",
	SCALE = {0.85, 0.85},

	RIGHT_POS = { 300, -175 },
	LEFT_POS = { -300, -175 },
	CENTER_POS = { 0, -175 },

}

g_pEventScene:AddEventSceneObject_LUA
{
	SCENE_OBJECT_NAME = "ARIEL",

	SCENE_OBJECT_TYPE = SCENE_OBJECT_TYPE["OT_XSKINMESH"],
	FILE_NAME = "UI_NPC_ARIEL.x",
	XET_NAME = "UI_NPC_ARIEL.XET",
	SCALE = {0.85, 0.85},

	RIGHT_POS = { 300, -175 },
	LEFT_POS = { -300, -175 },
	CENTER_POS = { 0, -175 },

}

g_pEventScene:AddEventSceneObject_LUA
{
	SCENE_OBJECT_NAME = "CAMILLA",

	SCENE_OBJECT_TYPE = SCENE_OBJECT_TYPE["OT_XSKINMESH"],
	FILE_NAME = "UI_NPC_CAMILLA.x",
	XET_NAME = "UI_NPC_CAMILLA.XET",
	SCALE = {0.95, 0.95},

	RIGHT_POS = { 300, -150 },
	LEFT_POS = { -300, -150 },
	CENTER_POS = { 0, -150 },

}

g_pEventScene:AddEventSceneObject_LUA
{
	SCENE_OBJECT_NAME = "BANESA",

	SCENE_OBJECT_TYPE = SCENE_OBJECT_TYPE["OT_XSKINMESH"],
	FILE_NAME = "UI_NPC_Banesa.X",
	XET_NAME = "UI_NPC_Banesa.XET",
	SCALE = {0.95, 0.95},

	RIGHT_SCREEN_OUT_POS_X = 950,
	LEFT_SCREEN_OUT_POS_X = -950,

	RIGHT_POS = { 300, -180 },
	LEFT_POS = { -300, -180 },
	CENTER_POS = { 0, -180 },

}

g_pEventScene:AddEventSceneObject_LUA
{
	SCENE_OBJECT_NAME = "NOEL",

	SCENE_OBJECT_TYPE = SCENE_OBJECT_TYPE["OT_XSKINMESH"],
	FILE_NAME = "UI_NPC_Noel.X",
	XET_NAME = "UI_NPC_Noel.XET",
	SCALE = {1.05, 1.05},

	RIGHT_POS = { 300, -170 },
	LEFT_POS = { -300, -170 },
	CENTER_POS = { 0, -170 },

}

g_pEventScene:AddEventSceneObject_LUA
{
	SCENE_OBJECT_NAME = "GLAVE",

	SCENE_OBJECT_TYPE = SCENE_OBJECT_TYPE["OT_XSKINMESH"],
	FILE_NAME = "UI_NPC_Glave.X",
	XET_NAME = "UI_NPC_Glave.XET",
	SCALE = {0.95, 0.95},

	RIGHT_POS = { 300, -150 },
	LEFT_POS = { -300, -150 },
	CENTER_POS = { 0, -150 },

}

g_pEventScene:AddEventSceneObject_LUA
{
	SCENE_OBJECT_NAME = "BILLBOARD",

	SCENE_OBJECT_TYPE = SCENE_OBJECT_TYPE["OT_XSKINMESH"],
	FILE_NAME = "Shop_Ui_Board.X",
	SCALE = {0.8, 0.8},

	RIGHT_SCREEN_OUT_POS_X = 950,
	LEFT_SCREEN_OUT_POS_X = -950,

	RIGHT_POS = { 300, -230 },
	LEFT_POS = { -300, -230 },
	CENTER_POS = { 0, -230 },

}


g_pEventScene:AddEventSceneObject_LUA
{
	SCENE_OBJECT_NAME = "GRAIL",

	SCENE_OBJECT_TYPE = SCENE_OBJECT_TYPE["OT_XSKINMESH"],
	FILE_NAME = "UI_NPC_GRAIL.X",
	XET_NAME = "UI_NPC_GRAIL.XET",
	SCALE = {1.0, 1.0},

	RIGHT_POS = { 300, -180 },
	LEFT_POS = { -300, -180 },
	CENTER_POS = { 0, -180 },
}

g_pEventScene:AddEventSceneObject_LUA
{
	SCENE_OBJECT_NAME = "HANNA",

	SCENE_OBJECT_TYPE = SCENE_OBJECT_TYPE["OT_XSKINMESH"],
	FILE_NAME = "UI_NPC_HANNA.X",
	XET_NAME = "UI_NPC_HANNA.XET",
	SCALE = {0.95, 0.95},

	RIGHT_POS = { 300, -180 },
	LEFT_POS = { -300, -180 },
	CENTER_POS = { 0, -180 },
}
g_pEventScene:AddEventSceneObject_LUA
{
	SCENE_OBJECT_NAME = "PRAUS",

	SCENE_OBJECT_TYPE = SCENE_OBJECT_TYPE["OT_XSKINMESH"],
	FILE_NAME = "UI_NPC_PRAUS.X",
	XET_NAME = "UI_NPC_PRAUS.XET",
	SCALE = {1.0, 1.0},

	RIGHT_POS = { 300, -170 },
	LEFT_POS = { -300, -170 },
	CENTER_POS = { 0, -170 },
 }

 g_pEventScene:AddEventSceneObject_LUA
{
	SCENE_OBJECT_NAME = "ANCIENTPPORU",

	SCENE_OBJECT_TYPE = SCENE_OBJECT_TYPE["OT_TEXTURE"],
	FILE_NAME = "UI_NPC_ANCIENT_PPORU.tga",

	TEXTURE_SIZE = { 768, 768 },

	RIGHT_POS = { 300, -50 },
	LEFT_POS = { -300, -50 },
	CENTER_POS = { 0, -50 },
 	CUSTOM_POS = { 0, 0 },

	RIGHT_SCREEN_OUT_POS_X = 900,
	LEFT_SCREEN_OUT_POS_X = -900,
}

g_pEventScene:AddEventSceneObject_LUA
{
	SCENE_OBJECT_NAME = "RURIEL",

	SCENE_OBJECT_TYPE = SCENE_OBJECT_TYPE["OT_XSKINMESH"],
	FILE_NAME = "UI_NPC_RURIEL.x",
	XET_NAME = "UI_NPC_RURIEL.XET",
	SCALE = {0.75, 0.75},

	RIGHT_POS = { 300, -180 },
	LEFT_POS = { -300, -180 },
	CENTER_POS = { 0, -180 },
}


g_pEventScene:AddEventSceneObject_LUA
{
	SCENE_OBJECT_NAME = "Fairy_Guardian",

	SCENE_OBJECT_TYPE = SCENE_OBJECT_TYPE["OT_XSKINMESH"],
	FILE_NAME = "UI_NPC_GUARDIAN.x",
	--XET_NAME = "UI_NPC_RURIEL.XET",
	SCALE = {0.95, 0.95},

	RIGHT_POS = { 300, -380 },
	LEFT_POS = { -300, -380 },
	CENTER_POS = { 0, -380 },
}



g_pEventScene:AddEventSceneObject_LUA
{
	SCENE_OBJECT_NAME = "Santa_Darkelf",

	SCENE_OBJECT_TYPE = SCENE_OBJECT_TYPE["OT_XSKINMESH"],
	FILE_NAME = "UI_NPC_SANTA_DARKELF.X",
	--XET_NAME = "UI_NPC_RURIEL.XET",
	SCALE = {1, 1},

	RIGHT_POS = { 300, -380 },
	LEFT_POS = { -300, -380 },
	CENTER_POS = { 0, -380 },
}

g_pEventScene:AddEventSceneObject_LUA
{
	SCENE_OBJECT_NAME = "HELLEN",

	SCENE_OBJECT_TYPE = SCENE_OBJECT_TYPE["OT_XSKINMESH"],
	FILE_NAME = "UI_NPC_HELLEN.x",
	XET_NAME = "UI_NPC_HELLEN.XET",
	SCALE = {0.95, 0.95},

	RIGHT_POS = { 300, -180 },
	LEFT_POS = { -300, -180 },
	CENTER_POS = { 0, -180 },
}

 g_pEventScene:AddEventSceneObject_LUA
{
	SCENE_OBJECT_NAME = "ETC_ENCHANT",

	SCENE_OBJECT_TYPE = SCENE_OBJECT_TYPE["OT_TEXTURE"],
	FILE_NAME = "UI_ETC_ENCHANT.TGA",

	TEXTURE_SIZE = { 512, 512 },

	RIGHT_POS = { 170, 30 },
	LEFT_POS = { -170, 30 },      -- 무기 강화 설명페이지 위치
	CENTER_POS = { 0, 30 },
 	CUSTOM_POS = { 0, 0 },

	RIGHT_SCREEN_OUT_POS_X = 900,
	LEFT_SCREEN_OUT_POS_X = -900,
}

 g_pEventScene:AddEventSceneObject_LUA
{
	SCENE_OBJECT_NAME = "ETC_MAGICSTONE",

	SCENE_OBJECT_TYPE = SCENE_OBJECT_TYPE["OT_TEXTURE"],
	FILE_NAME = "UI_ETC_MAGICSTONE.TGA",

	TEXTURE_SIZE = { 512, 512 },

	RIGHT_POS = { 170, 30 },
	LEFT_POS = { -170, 30 },   -- 마법석 설명페이지 위치
	CENTER_POS = { 0, 30 },
 	CUSTOM_POS = { 0, 0 },

	RIGHT_SCREEN_OUT_POS_X = 900,
	LEFT_SCREEN_OUT_POS_X = -900,
}

 g_pEventScene:AddEventSceneObject_LUA
{
	SCENE_OBJECT_NAME = "ETC_ATTRIB",

	SCENE_OBJECT_TYPE = SCENE_OBJECT_TYPE["OT_TEXTURE"],
	FILE_NAME = "UI_ETC_ATTRIB.TGA",

	TEXTURE_SIZE = { 512, 512 },

	RIGHT_POS = { 170, 30 },
	LEFT_POS = { -170, 30 },   -- 속성강화  설명페이지 위치
	CENTER_POS = { 0, 30 },
 	CUSTOM_POS = { 0, 0 },

	RIGHT_SCREEN_OUT_POS_X = 900,
	LEFT_SCREEN_OUT_POS_X = -900,
}

g_pEventScene:AddEventSceneObject_LUA
{
	SCENE_OBJECT_NAME = "HORATIO",

	SCENE_OBJECT_TYPE = SCENE_OBJECT_TYPE["OT_XSKINMESH"],
	FILE_NAME = "UI_NPC_HORATIO.x",
	XET_NAME = "UI_NPC_HORATIO.XET",
	SCALE = {0.75, 0.75},

	RIGHT_POS = { 300, -400 },
	LEFT_POS = { -300, -400 },
	CENTER_POS = { 0, -450 },
	
	RIGHT_SCREEN_OUT_POS_X = 900,
	LEFT_SCREEN_OUT_POS_X = -900,
}

g_pEventScene:AddEventSceneObject_LUA
{
	SCENE_OBJECT_NAME = "LUCY",

	SCENE_OBJECT_TYPE = SCENE_OBJECT_TYPE["OT_XSKINMESH"],
	FILE_NAME = "UI_NPC_LUCY.x",
	XET_NAME = "UI_NPC_LUCY.XET",
	SCALE = {0.95, 0.95},

	RIGHT_POS = { 300, -450 },
	LEFT_POS = { -300, -450 },
	CENTER_POS = { 0, -450 },
}

g_pEventScene:AddEventSceneObject_LUA
{
	SCENE_OBJECT_NAME = "DAISY",

	SCENE_OBJECT_TYPE = SCENE_OBJECT_TYPE["OT_XSKINMESH"],
	FILE_NAME = "UI_NPC_DAISY.x",
	XET_NAME = "UI_NPC_DAISY.XET",
	SCALE = {0.85, 0.85},

	RIGHT_POS = { 300, -450 },
	LEFT_POS = { -300, -450 },
	CENTER_POS = { 0, -450 },
}

g_pEventScene:AddEventSceneObject_LUA
{
	SCENE_OBJECT_NAME = "PENENSIO",

	SCENE_OBJECT_TYPE = SCENE_OBJECT_TYPE["OT_XSKINMESH"],
	FILE_NAME = "UI_NPC_PENENSIO.x",
	XET_NAME = "UI_NPC_PENENSIO.XET",
	SCALE = {0.90, 0.90},

	RIGHT_POS = { 300, -450 }, --
	LEFT_POS = { -300, -450 }, --
	CENTER_POS = { 0, -450 },
	
	RIGHT_SCREEN_OUT_POS_X = 900,
	LEFT_SCREEN_OUT_POS_X = -900,
}

g_pEventScene:AddEventSceneObject_LUA
{
	SCENE_OBJECT_NAME = "DENKA",

	SCENE_OBJECT_TYPE = SCENE_OBJECT_TYPE["OT_XSKINMESH"],
	FILE_NAME = "UI_NPC_DENKA.x",
	XET_NAME = "UI_NPC_DENKA.XET",
	SCALE = {0.85, 0.85},

	RIGHT_POS = { 300, -450 },
	LEFT_POS = { -300, -450 },
	CENTER_POS = { 0, -450 },
}

g_pEventScene:AddEventSceneObject_LUA
{
	SCENE_OBJECT_NAME = "LORDROS",

	SCENE_OBJECT_TYPE = SCENE_OBJECT_TYPE["OT_XSKINMESH"],
	FILE_NAME = "UI_NPC_LORDROS.x",
	XET_NAME = "UI_NPC_LORDROS.XET",
	SCALE = {0.95, 0.95},

	RIGHT_POS = { 300, -450 },
	LEFT_POS = { -300, -450 },
	CENTER_POS = { 0, -450 },
}

g_pEventScene:AddEventSceneObject_LUA
{
	SCENE_OBJECT_NAME = "HELLPUTT",

	SCENE_OBJECT_TYPE = SCENE_OBJECT_TYPE["OT_XSKINMESH"],
	FILE_NAME = "UI_HELLPUTT_BODY.x",
	XET_NAME = "UI_NPC_HELLPUTT.XET",
	SCALE = {0.75, 0.75},

	RIGHT_POS = { 300, -250 },
	LEFT_POS = { -300, -250 },
	CENTER_POS = { 0, -250 },
}

g_pEventScene:AddEventSceneObject_LUA
{
	SCENE_OBJECT_NAME = "LAGUZ",

	SCENE_OBJECT_TYPE = SCENE_OBJECT_TYPE["OT_XSKINMESH"],
	FILE_NAME = "UI_NPC_LAGUZ.x",
	XET_NAME = "UI_NPC_LAGUZ.XET",
	SCALE = {0.75, 0.75},

	RIGHT_POS = { 300, -400 },
	LEFT_POS = { -300, -400 },
	CENTER_POS = { 0, -400 },
}

g_pEventScene:AddEventSceneObject_LUA
{
	SCENE_OBJECT_NAME = "IS",

	SCENE_OBJECT_TYPE = SCENE_OBJECT_TYPE["OT_XSKINMESH"],
	FILE_NAME = "UI_NPC_IS.x",
	XET_NAME = "UI_NPC_IS.XET",
	SCALE = {0.75, 0.75},

	RIGHT_POS = { 300, -400 },
	LEFT_POS = { -300, -400 },
	CENTER_POS = { 0, -400 },
}

g_pEventScene:AddEventSceneObject_LUA
{
	SCENE_OBJECT_NAME = "MERMAN",

	SCENE_OBJECT_TYPE = SCENE_OBJECT_TYPE["OT_XSKINMESH"],
	FILE_NAME = "UI_NPC_MERMAN.x",
	XET_NAME = "UI_NPC_MERMAN.XET",
	SCALE = {0.8, 0.8},

	RIGHT_POS = { 300, -400 },
	LEFT_POS = { -300, -400 },
	CENTER_POS = { 0, -400 },
}

g_pEventScene:AddEventSceneObject_LUA
{
	SCENE_OBJECT_NAME = "ANCIENT_CRAB",

	SCENE_OBJECT_TYPE = SCENE_OBJECT_TYPE["OT_XSKINMESH"],
	FILE_NAME = "UI_NPC_ANCIENT_CRAB.x",
	XET_NAME = "UI_NPC_ANCIENT_CRAB.XET",
	SCALE = {0.65, 0.65},

	RIGHT_POS = { 200, -400 },
	LEFT_POS = { -200, -400 },
	CENTER_POS = { 0, -400 },
}


g_pEventScene:AddEventSceneObject_LUA
{
	SCENE_OBJECT_NAME = "SHADOW_LINKER",

	SCENE_OBJECT_TYPE = SCENE_OBJECT_TYPE["OT_XSKINMESH"],
	FILE_NAME = "UI_NPC_LINKER.x",
	XET_NAME = "UI_NPC_LINKER.XET",
	SCALE = {0.65, 0.65},

	RIGHT_POS = { 350, -400 },
	LEFT_POS = { -350, -400 },
	CENTER_POS = { 0, -400 },
}


g_pEventScene:AddEventSceneObject_LUA
{
	SCENE_OBJECT_NAME = "MANDRASSIL",

	SCENE_OBJECT_TYPE = SCENE_OBJECT_TYPE["OT_XSKINMESH"],
	FILE_NAME = "UI_NPC_GUARDIAN.x",
	--XET_NAME = "UI_NPC_GUARDIAN.XET",
	SCALE = {0.75, 0.75},

	RIGHT_POS = { 300, -380 },
	LEFT_POS = { -300, -380 },
	CENTER_POS = { 0, -380 },
}

g_pEventScene:AddEventSceneObject_LUA
{
	SCENE_OBJECT_NAME = "MU",

	SCENE_OBJECT_TYPE = SCENE_OBJECT_TYPE["OT_XSKINMESH"],
	FILE_NAME = "UI_NPC_MEW.x",
	XET_NAME = "UI_NPC_MEW.XET",
	SCALE = {0.75, 0.75},

	RIGHT_POS = { 300, -180 },
	LEFT_POS = { -300, -180 },
	CENTER_POS = { 0, -180 },
}

g_pEventScene:AddEventSceneObject_LUA
{
	SCENE_OBJECT_NAME = "RAN",

	SCENE_OBJECT_TYPE = SCENE_OBJECT_TYPE["OT_XSKINMESH"],
	FILE_NAME = "UI_NPC_RAN.x",
	XET_NAME = "UI_NPC_RAN.XET",
	SCALE = {0.95, 0.95},

	RIGHT_POS = { 300, -90 },
	LEFT_POS = { -300, -90 },
	CENTER_POS = { 0, -180 },
}

g_pEventScene:AddEventSceneObject_LUA
{
	SCENE_OBJECT_NAME = "SHASHA",

	SCENE_OBJECT_TYPE = SCENE_OBJECT_TYPE["OT_XSKINMESH"],
	FILE_NAME = "UI_NPC_SHASHA.x",
	XET_NAME = "UI_NPC_SHASHA.XET",
	SCALE = {0.95, 0.95},

	RIGHT_POS = { 300, -90 },
	LEFT_POS = { -300, -90 },
	CENTER_POS = { 0, -180 },
}

g_pEventScene:AddEventSceneObject_LUA
{
	SCENE_OBJECT_NAME = "SHASHA_SKY",

	SCENE_OBJECT_TYPE = SCENE_OBJECT_TYPE["OT_XSKINMESH"],
	FILE_NAME = "UI_NPC_SHASHA_SKY.x",
	XET_NAME = "UI_NPC_SHASHA_SKY.XET",
	SCALE = {0.95, 0.95},

	RIGHT_POS = { 300, -90 },
	LEFT_POS = { -300, -90 },
	CENTER_POS = { 0, -180 },
}

g_pEventScene:AddEventSceneObject_LUA
{
	SCENE_OBJECT_NAME = "LUTO",

	SCENE_OBJECT_TYPE = SCENE_OBJECT_TYPE["OT_XSKINMESH"],
	FILE_NAME = "HQ_UI_NPC_Luto_wait_01.X",
	--XET_NAME = "UI_NPC_SHASHA_SKY.XET",
	SCALE = {0.85, 0.85},

	RIGHT_POS = { 370, -60 },
	LEFT_POS = { -370, -60 },
	CENTER_POS = { 0, -180 },
}

g_pEventScene:AddEventSceneObject_LUA
{
	SCENE_OBJECT_NAME = "DAO",

	SCENE_OBJECT_TYPE = SCENE_OBJECT_TYPE["OT_XSKINMESH"],
	FILE_NAME = "HQ_UI_NPC_DAO.X",
	XET_NAME = "UI_NPC_DAO.XET",
	SCALE = {0.75, 0.75},

	RIGHT_POS = { 300, -130 },
	LEFT_POS = { -300, -90 },
	CENTER_POS = { 0, -180 },
}

g_pEventScene:AddEventSceneObject_LUA
{
	SCENE_OBJECT_NAME = "EVENT_APINK",

	SCENE_OBJECT_TYPE = SCENE_OBJECT_TYPE["OT_XSKINMESH"],
	FILE_NAME = "HQ_UI_NPC_EVENT_Tactical_Trooper.X",
	--XET_NAME = "UI_NPC_DAO.XET",
	SCALE = {0.85, 0.85},

	RIGHT_POS = { 300, -150 },
	LEFT_POS = { -300, -150 },
	CENTER_POS = { 0, -150 },
}


g_pEventScene:AddEventSceneObject_LUA
{
	SCENE_OBJECT_NAME = "APINK_ARCHANGEL",

	SCENE_OBJECT_TYPE = SCENE_OBJECT_TYPE["OT_XSKINMESH"],
	FILE_NAME = "HQ_UI_NPC_EVENT_Battle_Seraph.X",
	SCALE = {0.85, 0.85},

	RIGHT_POS = { 300, -150 },
	LEFT_POS = { -300, -150 },
	CENTER_POS = { 0, -150 },
}

g_pEventScene:AddEventSceneObject_LUA
{
	SCENE_OBJECT_NAME = "EMIRATE",	-- 에미리트 (샌더 촌장)

	SCENE_OBJECT_TYPE = SCENE_OBJECT_TYPE["OT_XSKINMESH"],
	FILE_NAME = "UI_NPC_EMIRATE.X",
	XET_NAME = "UI_NPC_EMIRATE.XET",
	SCALE = {0.75, 0.75},

	RIGHT_POS = { 300, -150 },
	LEFT_POS = { -300, -150 },
	CENTER_POS = { 0, -150 },
}
g_pEventScene:AddEventSceneObject_LUA
{
	SCENE_OBJECT_NAME = "ROSEANG",	-- 로즈앙 (샌더 악세)

	SCENE_OBJECT_TYPE = SCENE_OBJECT_TYPE["OT_XSKINMESH"],
	FILE_NAME = "UI_NPC_Roseang.X",
	XET_NAME = "UI_NPC_Roseang.XET",
	SCALE = {0.75, 0.75},

	RIGHT_POS = { 300, -150 },
	LEFT_POS = { -300, -150 },
	CENTER_POS = { 0, -150 },
}
g_pEventScene:AddEventSceneObject_LUA
{
	SCENE_OBJECT_NAME = "VAPOR",	-- 바포르 (샌더 연금)

	SCENE_OBJECT_TYPE = SCENE_OBJECT_TYPE["OT_XSKINMESH"],
	FILE_NAME = "UI_NPC_VAPOR.X",
	XET_NAME = "UI_NPC_VAPOR.XET",
	SCALE = {0.9, 0.9},

	RIGHT_POS = { 300, -150 },
	LEFT_POS = { -300, -150 },
	CENTER_POS = { 0, -150 },
}
g_pEventScene:AddEventSceneObject_LUA
{
	SCENE_OBJECT_NAME = "DAPPAR",	-- 다파르 (샌더 무기)

	SCENE_OBJECT_TYPE = SCENE_OBJECT_TYPE["OT_XSKINMESH"],
	FILE_NAME = "UI_NPC_DAPPAR.X",
	XET_NAME = "UI_NPC_DAPPAR.XET",
	SCALE = {0.75, 0.75},

	RIGHT_POS = { 300, -150 },
	LEFT_POS = { -300, -150 },
	CENTER_POS = { 0, -150 },
}
g_pEventScene:AddEventSceneObject_LUA
{
	SCENE_OBJECT_NAME = "STEEL_TROCK",	-- 철그락트락

	SCENE_OBJECT_TYPE = SCENE_OBJECT_TYPE["OT_XSKINMESH"],
	FILE_NAME = "UI_NPC_STEEL_TROCK.X",
	XET_NAME = "UI_NPC_STEEL_TROCK.XET",
	SCALE = {0.75, 0.75},

	RIGHT_POS = { 300, -150 },
	LEFT_POS = { -300, -150 },
	CENTER_POS = { 0, -150 },
}
g_pEventScene:AddEventSceneObject_LUA
{
	SCENE_OBJECT_NAME = "KELAINO",		-- 켈라이노

	SCENE_OBJECT_TYPE = SCENE_OBJECT_TYPE["OT_XSKINMESH"],
	FILE_NAME = "UI_NPC_Kelaino.X",
	XET_NAME = "UI_NPC_Kelaino.XET",
	SCALE = {0.75, 0.75},

	RIGHT_POS = { 300, -150 },
	LEFT_POS = { -300, -150 },
	CENTER_POS = { 0, -150 },
}
g_pEventScene:AddEventSceneObject_LUA
{
	SCENE_OBJECT_NAME = "KARU",		-- 카루

	SCENE_OBJECT_TYPE = SCENE_OBJECT_TYPE["OT_XSKINMESH"],
	FILE_NAME = "UI_NPC_KARU.X",
	XET_NAME = "UI_NPC_KARU.XET",
	SCALE = {1, 1},

	RIGHT_POS = { 300, 0 },
	LEFT_POS = { -300, 0 },
	CENTER_POS = { 0, -150 },
}
g_pEventScene:AddEventSceneObject_LUA
{
	SCENE_OBJECT_NAME = "TROCKTA",		-- 트락타

	SCENE_OBJECT_TYPE = SCENE_OBJECT_TYPE["OT_XSKINMESH"],
	FILE_NAME = "UI_NPC_TROCKTA.X",
	XET_NAME = "UI_NPC_TROCKTA.XET",
	SCALE = {1, 1},

	RIGHT_POS = { 300, -20 },
	LEFT_POS = { -300, -20 },
	CENTER_POS = { 0, -150 },
}
g_pEventScene:AddEventSceneObject_LUA
{
	SCENE_OBJECT_NAME = "EVENT_BENDERS",	-- 만우절 이벤트 NPC 앙드레 벤더스

	SCENE_OBJECT_TYPE = SCENE_OBJECT_TYPE["OT_XSKINMESH"],
	FILE_NAME = "UI_NPC_EVENT_BENDERS.x",
	XET_NAME = "UI_NPC_EVENT_BENDERS.XET",
	SCALE = {0.95, 0.95},

	RIGHT_POS = { 300, -120 },
	LEFT_POS = { -250, -120 },
	CENTER_POS = { 0, -150 },
}