-- Hamel_Resiam_Underwater_Stage3.lua



g_pWorld:SetLightPos( 50000, 50000, -100000 )
g_pWorld:SetLineMap( "Hamel_Resiam_Underwater_Stage3_LineMap.lua" )
g_pWorld:SetBGM( "Music042_Stage.ogg" )
g_pWorld:AddEffectBGM_LUA( "Amb_ResiamUnderWater_Bubble1.ogg" )
--g_pWorld:AddEffectBGM_LUA( "Amb_ResiamUnderWater_Bubble2.ogg" )
g_pWorld:AddEffectBGM_LUA( "Amb_ResiamUnderWater_Bubble3.ogg" )



g_pWorld:SetFogWorld( 2000, 5000, 1000, 10000, 0, D3DXCOLOR( 0, 0.239216, 0.486275, 1.0 ) )

-- SKY / CLOUD -- 
-- STATIC MESH -- 
g_pObjectMesh = g_pWorld:CreateObjectMesh()
g_pObjectMesh:SetXMesh(    "Hamel_Resiam_Underwater_Stage2_Sky01.Y" )
g_pObjectMesh:SetXMeshLOD( "Hamel_Resiam_Underwater_Stage2_Sky01.Y" )
g_pObjectMesh:SetLayer( X2_LAYER["XL_SKY_WORLD_BASE_0"] )
g_pObjectMesh:SetPos( D3DXVECTOR3(0, 0, 0) )
g_pObjectMesh:SetOriginalColorFactor( D3DXCOLOR(0.0784314, 0.803922, 0.882353, 1))
g_pObjectMesh:SetColorFactor( D3DXCOLOR(1,1,1,1) )
g_pObjectMesh:SetCanHide( false, false )
g_pObjectMesh:SetNotRenderWhenHidden( false )
g_pRenderParam = g_pObjectMesh:GetRenderParam()
g_pObjectMesh:SetFog( 2000, 5000, 1000, 10000, D3DXCOLOR(0, 0.239216, 0.486275, 1), 0 )


g_pObjectMesh = g_pWorld:CreateObjectMesh()
g_pObjectMesh:SetXMesh(    "Hamel_Resiam_Underwater_Stage2_Sky02.Y" )
g_pObjectMesh:SetXMeshLOD( "Hamel_Resiam_Underwater_Stage2_Sky02.Y" )
g_pObjectMesh:SetLayer( X2_LAYER["XL_SKY_WORLD_BASE_0"] )
g_pObjectMesh:SetPos( D3DXVECTOR3(0, 0, 0) )
g_pObjectMesh:SetOriginalColorFactor( D3DXCOLOR(0.0784314, 0.803922, 0.882353, 1))
g_pObjectMesh:SetColorFactor( D3DXCOLOR(1,1,1,1) )
g_pObjectMesh:SetCanHide( false, false )
g_pObjectMesh:SetNotRenderWhenHidden( false )
g_pRenderParam = g_pObjectMesh:GetRenderParam()
g_pObjectMesh:SetFog( 2000, 5000, 1000, 10000, D3DXCOLOR(0, 0.239216, 0.486275, 1), 0 )


g_pObjectMesh = g_pWorld:CreateObjectMesh()
g_pObjectMesh:SetXMesh(    "Hamel_Resiam_Underwater_Stage3_Building_Hide01.Y" )
g_pObjectMesh:SetXMeshLOD( "Hamel_Resiam_Underwater_Stage3_Building_Hide01.Y" )
g_pObjectMesh:SetLayer( X2_LAYER["XL_SKY_WORLD_OBJECT_OVER_EFFECT_1"] )
g_pObjectMesh:SetPos( D3DXVECTOR3(0, 0, 0) )
g_pObjectMesh:SetOriginalColorFactor( D3DXCOLOR(0.0784314, 0.592157, 0.882353, 1))
g_pObjectMesh:SetColorFactor( D3DXCOLOR(1,1,1,1) )
g_pObjectMesh:SetCanHide( true, true )
g_pObjectMesh:SetNotRenderWhenHidden( false )
g_pRenderParam = g_pObjectMesh:GetRenderParam()
g_pObjectMesh:SetAlphaObject( false )
g_pRenderParam.bAlphaBlend = true
g_pObjectMesh:SetFog( 2000, 5000, 1000, 10000, D3DXCOLOR(0, 0.239216, 0.486275, 1), 0 )


g_pObjectMesh = g_pWorld:CreateObjectMesh()
g_pObjectMesh:SetXMesh(    "Hamel_Resiam_Underwater_Stage3_Building_Hide02.Y" )
g_pObjectMesh:SetXMeshLOD( "Hamel_Resiam_Underwater_Stage3_Building_Hide02.Y" )
g_pObjectMesh:SetLayer( X2_LAYER["XL_SKY_WORLD_OBJECT_OVER_EFFECT_1"] )
g_pObjectMesh:SetPos( D3DXVECTOR3(0, 0, 0) )
g_pObjectMesh:SetOriginalColorFactor( D3DXCOLOR(0.0784314, 0.592157, 0.882353, 1))
g_pObjectMesh:SetColorFactor( D3DXCOLOR(1,1,1,1) )
g_pObjectMesh:SetCanHide( true, true )
g_pObjectMesh:SetNotRenderWhenHidden( false )
g_pRenderParam = g_pObjectMesh:GetRenderParam()
g_pObjectMesh:SetAlphaObject( false )
g_pRenderParam.bAlphaBlend = true
g_pObjectMesh:SetFog( 2000, 5000, 1000, 10000, D3DXCOLOR(0, 0.239216, 0.486275, 1), 0 )


g_pObjectMesh = g_pWorld:CreateObjectMesh()
g_pObjectMesh:SetXMesh(    "Hamel_Resiam_Underwater_Stage3_Coral.Y" )
g_pObjectMesh:SetXMeshLOD( "Hamel_Resiam_Underwater_Stage3_Coral.Y" )
g_pObjectMesh:SetLayer( X2_LAYER["XL_SKY_WORLD_BASE_0"] )
g_pObjectMesh:SetPos( D3DXVECTOR3(0, 0, 0) )
g_pObjectMesh:SetOriginalColorFactor( D3DXCOLOR(0.611765, 0.819608, 1, 1))
g_pObjectMesh:SetColorFactor( D3DXCOLOR(1,1,1,1) )
g_pObjectMesh:SetCanHide( false, false )
g_pObjectMesh:SetNotRenderWhenHidden( false )
g_pRenderParam = g_pObjectMesh:GetRenderParam()
g_pObjectMesh:SetFog( 2000, 5000, 1000, 10000, D3DXCOLOR(0, 0.239216, 0.486275, 1), 0 )


g_pObjectMesh = g_pWorld:CreateObjectMesh()
g_pObjectMesh:SetXMesh(    "Hamel_Resiam_Underwater_Stage3_Coral_Blue.Y" )
g_pObjectMesh:SetXMeshLOD( "Hamel_Resiam_Underwater_Stage3_Coral_Blue.Y" )
g_pObjectMesh:SetLayer( X2_LAYER["XL_SKY_WORLD_BASE_0"] )
g_pObjectMesh:SetPos( D3DXVECTOR3(0, 0, 0) )
g_pObjectMesh:SetOriginalColorFactor( D3DXCOLOR(0.686275, 0.843137, 1, 1))
g_pObjectMesh:SetColorFactor( D3DXCOLOR(1,1,1,1) )
g_pObjectMesh:SetCanHide( false, false )
g_pObjectMesh:SetNotRenderWhenHidden( false )
g_pRenderParam = g_pObjectMesh:GetRenderParam()
g_pObjectMesh:SetFog( 2000, 5000, 1000, 10000, D3DXCOLOR(0, 0.239216, 0.486275, 1), 0 )


g_pObjectMesh = g_pWorld:CreateObjectMesh()
g_pObjectMesh:SetXMesh(    "Hamel_Resiam_Underwater_Stage3_Ground_Light.Y" )
g_pObjectMesh:SetXMeshLOD( "Hamel_Resiam_Underwater_Stage3_Ground_Light.Y" )
g_pObjectMesh:SetLayer( X2_LAYER["XL_SKY_WORLD_OBJECT_OVER_EFFECT_0"] )
g_pObjectMesh:SetPos( D3DXVECTOR3(0, 0, 0) )
g_pObjectMesh:SetOriginalColorFactor( D3DXCOLOR(0, 0.756863, 1, 1))
g_pObjectMesh:SetColorFactor( D3DXCOLOR(1,1,1,1) )
g_pObjectMesh:SetCanHide( false, false )
g_pObjectMesh:SetNotRenderWhenHidden( false )
g_pRenderParam = g_pObjectMesh:GetRenderParam()
g_pObjectMesh:SetAlphaObject( true )
g_pRenderParam.bAlphaBlend = true
g_pRenderParam.srcBlend = D3DBLEND["D3DBLEND_SRCALPHA"]
g_pRenderParam.destBlend = D3DBLEND["D3DBLEND_DESTALPHA"]
g_pObjectMesh:SetFog( 2000, 5000, 1000, 10000, D3DXCOLOR(0, 0.239216, 0.486275, 1), 0 )


g_pObjectMesh = g_pWorld:CreateObjectMesh()
g_pObjectMesh:SetXMesh(    "Hamel_Resiam_Underwater_Stage3_Sea_Mustard_Far.Y" )
g_pObjectMesh:SetXMeshLOD( "Hamel_Resiam_Underwater_Stage3_Sea_Mustard_Far.Y" )
g_pObjectMesh:SetLayer( X2_LAYER["XL_SKY_DOME_1"] )
g_pObjectMesh:SetPos( D3DXVECTOR3(0, 0, 0) )
g_pObjectMesh:SetOriginalColorFactor( D3DXCOLOR(0.0784314, 0.596078, 0.882353, 1))
g_pObjectMesh:SetColorFactor( D3DXCOLOR(1,1,1,1) )
g_pObjectMesh:SetCanHide( false, false )
g_pObjectMesh:SetNotRenderWhenHidden( false )
g_pRenderParam = g_pObjectMesh:GetRenderParam()
g_pObjectMesh:SetAlphaObject( true )
g_pRenderParam.bAlphaBlend = true
g_pObjectMesh:SetFog( 2000, 5000, 1000, 10000, D3DXCOLOR(0, 0.239216, 0.486275, 1), 0 )


g_pObjectMesh = g_pWorld:CreateObjectMesh()
g_pObjectMesh:SetXMesh(    "Hamel_Resiam_Underwater_Stage3_Sea_Mustard_Far01.Y" )
g_pObjectMesh:SetXMeshLOD( "Hamel_Resiam_Underwater_Stage3_Sea_Mustard_Far01.Y" )
g_pObjectMesh:SetLayer( X2_LAYER["XL_SKY_DOME_0"] )
g_pObjectMesh:SetPos( D3DXVECTOR3(0, 0, 0) )
g_pObjectMesh:SetOriginalColorFactor( D3DXCOLOR(0.0784314, 0.596078, 0.882353, 1))
g_pObjectMesh:SetColorFactor( D3DXCOLOR(1,1,1,1) )
g_pObjectMesh:SetCanHide( false, false )
g_pObjectMesh:SetNotRenderWhenHidden( false )
g_pRenderParam = g_pObjectMesh:GetRenderParam()
g_pObjectMesh:SetAlphaObject( true )
g_pRenderParam.bAlphaBlend = true
g_pObjectMesh:SetFog( 2000, 5000, 1000, 10000, D3DXCOLOR(0, 0.239216, 0.486275, 1), 0 )


g_pObjectMesh = g_pWorld:CreateObjectMesh()
g_pObjectMesh:SetXMesh(    "Hamel_Resiam_Underwater_Stage3_Cliff_UW.Y" )
g_pObjectMesh:SetXMeshLOD( "Hamel_Resiam_Underwater_Stage3_Cliff_UW.Y" )
g_pObjectMesh:SetLayer( X2_LAYER["XL_SKY_WORLD_BASE_0"] )
g_pObjectMesh:SetPos( D3DXVECTOR3(0, 0, 0) )
g_pObjectMesh:SetOriginalColorFactor( D3DXCOLOR(0.0784314, 0.592157, 0.882353, 1))
g_pObjectMesh:SetColorFactor( D3DXCOLOR(1,1,1,1) )
g_pObjectMesh:SetCanHide( false, false )
g_pObjectMesh:SetNotRenderWhenHidden( false )
g_pRenderParam = g_pObjectMesh:GetRenderParam()
g_pObjectMesh:SetFog( 2000, 5000, 1000, 10000, D3DXCOLOR(0, 0.239216, 0.486275, 1), 0 )


g_pObjectMesh = g_pWorld:CreateObjectMesh()
g_pObjectMesh:SetXMesh(    "Hamel_Resiam_Underwater_Stage3_Ground.Y" )
g_pObjectMesh:SetXMeshLOD( "Hamel_Resiam_Underwater_Stage3_Ground.Y" )
g_pObjectMesh:SetLayer( X2_LAYER["XL_SKY_WORLD_BASE_0"] )
g_pObjectMesh:SetPos( D3DXVECTOR3(0, 0, 0) )
g_pObjectMesh:SetOriginalColorFactor( D3DXCOLOR(0.0784314, 0.592157, 0.882353, 1))
g_pObjectMesh:SetColorFactor( D3DXCOLOR(1,1,1,1) )
g_pObjectMesh:SetCanHide( false, false )
g_pObjectMesh:SetNotRenderWhenHidden( false )
g_pRenderParam = g_pObjectMesh:GetRenderParam()
g_pObjectMesh:SetFog( 2000, 5000, 1000, 10000, D3DXCOLOR(0, 0.239216, 0.486275, 1), 0 )


g_pObjectMesh = g_pWorld:CreateObjectMesh()
g_pObjectMesh:SetXMesh(    "Hamel_Resiam_Underwater_Stage3_Ground_Far.Y" )
g_pObjectMesh:SetXMeshLOD( "Hamel_Resiam_Underwater_Stage3_Ground_Far.Y" )
g_pObjectMesh:SetLayer( X2_LAYER["XL_SKY_WORLD_BASE_0"] )
g_pObjectMesh:SetPos( D3DXVECTOR3(0, 0, 0) )
g_pObjectMesh:SetOriginalColorFactor( D3DXCOLOR(0.0784314, 0.592157, 0.882353, 1))
g_pObjectMesh:SetColorFactor( D3DXCOLOR(1,1,1,1) )
g_pObjectMesh:SetCanHide( false, false )
g_pObjectMesh:SetNotRenderWhenHidden( false )
g_pRenderParam = g_pObjectMesh:GetRenderParam()
g_pObjectMesh:SetFog( 2000, 5000, 1000, 10000, D3DXCOLOR(0, 0.239216, 0.486275, 1), 0 )


g_pObjectMesh = g_pWorld:CreateObjectMesh()
g_pObjectMesh:SetXMesh(    "Hamel_Resiam_Underwater_Stage3_Mesh01.Y" )
g_pObjectMesh:SetXMeshLOD( "Hamel_Resiam_Underwater_Stage3_Mesh01.Y" )
g_pObjectMesh:SetLayer( X2_LAYER["XL_SKY_WORLD_BASE_0"] )
g_pObjectMesh:SetPos( D3DXVECTOR3(0, 0, 0) )
g_pObjectMesh:SetOriginalColorFactor( D3DXCOLOR(0.0784314, 0.592157, 0.882353, 1))
g_pObjectMesh:SetColorFactor( D3DXCOLOR(1,1,1,1) )
g_pObjectMesh:SetCanHide( false, false )
g_pObjectMesh:SetNotRenderWhenHidden( false )
g_pRenderParam = g_pObjectMesh:GetRenderParam()
g_pObjectMesh:SetFog( 2000, 5000, 1000, 10000, D3DXCOLOR(0, 0.239216, 0.486275, 1), 0 )


g_pObjectMesh = g_pWorld:CreateObjectMesh()
g_pObjectMesh:SetXMesh(    "Hamel_Resiam_Underwater_Stage3_Mesh02.Y" )
g_pObjectMesh:SetXMeshLOD( "Hamel_Resiam_Underwater_Stage3_Mesh02.Y" )
g_pObjectMesh:SetLayer( X2_LAYER["XL_SKY_WORLD_BASE_0"] )
g_pObjectMesh:SetPos( D3DXVECTOR3(0, 0, 0) )
g_pObjectMesh:SetOriginalColorFactor( D3DXCOLOR(0.0784314, 0.592157, 0.882353, 1))
g_pObjectMesh:SetColorFactor( D3DXCOLOR(1,1,1,1) )
g_pObjectMesh:SetCanHide( false, false )
g_pObjectMesh:SetNotRenderWhenHidden( false )
g_pRenderParam = g_pObjectMesh:GetRenderParam()
g_pObjectMesh:SetFog( 2000, 5000, 1000, 10000, D3DXCOLOR(0, 0.239216, 0.486275, 1), 0 )


g_pObjectMesh = g_pWorld:CreateObjectMesh()
g_pObjectMesh:SetXMesh(    "Hamel_Resiam_Underwater_Stage3_Mesh03.Y" )
g_pObjectMesh:SetXMeshLOD( "Hamel_Resiam_Underwater_Stage3_Mesh03.Y" )
g_pObjectMesh:SetLayer( X2_LAYER["XL_SKY_WORLD_BASE_0"] )
g_pObjectMesh:SetPos( D3DXVECTOR3(0, 0, 0) )
g_pObjectMesh:SetOriginalColorFactor( D3DXCOLOR(0.0784314, 0.592157, 0.882353, 1))
g_pObjectMesh:SetColorFactor( D3DXCOLOR(1,1,1,1) )
g_pObjectMesh:SetCanHide( false, false )
g_pObjectMesh:SetNotRenderWhenHidden( false )
g_pRenderParam = g_pObjectMesh:GetRenderParam()
g_pObjectMesh:SetFog( 2000, 5000, 1000, 10000, D3DXCOLOR(0, 0.239216, 0.486275, 1), 0 )


g_pObjectMesh = g_pWorld:CreateObjectMesh()
g_pObjectMesh:SetXMesh(    "Hamel_Resiam_Underwater_Stage3_Mesh04.Y" )
g_pObjectMesh:SetXMeshLOD( "Hamel_Resiam_Underwater_Stage3_Mesh04.Y" )
g_pObjectMesh:SetLayer( X2_LAYER["XL_SKY_WORLD_BASE_0"] )
g_pObjectMesh:SetPos( D3DXVECTOR3(0, 0, 0) )
g_pObjectMesh:SetOriginalColorFactor( D3DXCOLOR(0.0784314, 0.592157, 0.882353, 1))
g_pObjectMesh:SetColorFactor( D3DXCOLOR(1,1,1,1) )
g_pObjectMesh:SetCanHide( false, false )
g_pObjectMesh:SetNotRenderWhenHidden( false )
g_pRenderParam = g_pObjectMesh:GetRenderParam()
g_pObjectMesh:SetFog( 2000, 5000, 1000, 10000, D3DXCOLOR(0, 0.239216, 0.486275, 1), 0 )


-- SKIN MESH -- 
g_pObjectSkinMesh = g_pWorld:CreateObjectSkinMesh()
g_pObjectSkinMesh:SetXSkinMotion( "HAMEL_RESIAM_UNDERWATER_STAGE1_SEAMUSTARD.X" )
g_pObjectSkinMesh:AddXSkinModel( "HAMEL_RESIAM_UNDERWATER_STAGE1_SEAMUSTARD.X" )
g_pObjectSkinMesh:AddAnim( "Normal" )
g_pObjectSkinMesh:PlayAnim( WORLD_OBJECT_SKIN_MESH_PLAY_TYPE["WOSMPY_LOOP"] )
g_pObjectSkinMesh:SetLayer( X2_LAYER["XL_SKY_WORLD_OBJECT_OVER_EFFECT_0"] )
g_pObjectSkinMesh:SetPos( D3DXVECTOR3(-90, 4545, -330) )
g_pObjectSkinMesh:SetOriginalColorFactor( D3DXCOLOR(0.611765, 0.709804, 1, 1))
g_pObjectSkinMesh:SetColorFactor( D3DXCOLOR(1,1,1,1) )
g_pObjectSkinMesh:SetCanHide( false, false )
g_pRenderParam = g_pObjectSkinMesh:GetRenderParam()
g_pObjectSkinMesh:SetAlphaObject( true )
g_pRenderParam.bAlphaBlend = true
g_pObjectSkinMesh:SetFog( 2000, 5000, 1000, 10000, D3DXCOLOR(0, 0.239216, 0.486275, 1), 0 )


g_pObjectSkinMesh = g_pWorld:CreateObjectSkinMesh()
g_pObjectSkinMesh:SetXSkinMotion( "HAMEL_RESIAM_UNDERWATER_STAGE1_SEAMUSTARD_BLUE.X" )
g_pObjectSkinMesh:AddXSkinModel( "HAMEL_RESIAM_UNDERWATER_STAGE1_SEAMUSTARD_BLUE.X" )
g_pObjectSkinMesh:AddAnim( "Normal" )
g_pObjectSkinMesh:PlayAnim( WORLD_OBJECT_SKIN_MESH_PLAY_TYPE["WOSMPY_LOOP"] )
g_pObjectSkinMesh:SetLayer( X2_LAYER["XL_SKY_WORLD_BASE_0"] )
g_pObjectSkinMesh:SetPos( D3DXVECTOR3(1290, 4725, 385) )
g_pObjectSkinMesh:SetOriginalColorFactor( D3DXCOLOR(0.45098, 0.741176, 1, 1))
g_pObjectSkinMesh:SetColorFactor( D3DXCOLOR(1,1,1,1) )
g_pObjectSkinMesh:SetCanHide( false, false )
g_pRenderParam = g_pObjectSkinMesh:GetRenderParam()
g_pObjectSkinMesh:SetAlphaObject( true )
g_pRenderParam.bAlphaBlend = true
g_pObjectSkinMesh:SetFog( 2000, 5000, 1000, 10000, D3DXCOLOR(0, 0.239216, 0.486275, 1), 0 )


g_pObjectSkinMesh = g_pWorld:CreateObjectSkinMesh()
g_pObjectSkinMesh:SetXSkinMotion( "HAMEL_RESIAM_UNDERWATER_STAGE1_SEAMUSTARD_BLUE.X" )
g_pObjectSkinMesh:AddXSkinModel( "HAMEL_RESIAM_UNDERWATER_STAGE1_SEAMUSTARD_BLUE.X" )
g_pObjectSkinMesh:AddAnim( "Normal" )
g_pObjectSkinMesh:PlayAnim( WORLD_OBJECT_SKIN_MESH_PLAY_TYPE["WOSMPY_LOOP"] )
g_pObjectSkinMesh:SetLayer( X2_LAYER["XL_SKY_WORLD_BASE_0"] )
g_pObjectSkinMesh:SetPos( D3DXVECTOR3(7420, 3220, 610) )
g_pObjectSkinMesh:SetOriginalColorFactor( D3DXCOLOR(0.45098, 0.741176, 1, 1))
g_pObjectSkinMesh:SetColorFactor( D3DXCOLOR(1,1,1,1) )
g_pObjectSkinMesh:SetCanHide( false, false )
g_pRenderParam = g_pObjectSkinMesh:GetRenderParam()
g_pObjectSkinMesh:SetAlphaObject( true )
g_pRenderParam.bAlphaBlend = true
g_pObjectSkinMesh:SetFog( 2000, 5000, 1000, 10000, D3DXCOLOR(0, 0.239216, 0.486275, 1), 0 )


g_pObjectSkinMesh = g_pWorld:CreateObjectSkinMesh()
g_pObjectSkinMesh:SetXSkinMotion( "HAMEL_RESIAM_UNDERWATER_STAGE1_SEAMUSTARD.X" )
g_pObjectSkinMesh:AddXSkinModel( "HAMEL_RESIAM_UNDERWATER_STAGE1_SEAMUSTARD.X" )
g_pObjectSkinMesh:AddAnim( "Normal" )
g_pObjectSkinMesh:PlayAnim( WORLD_OBJECT_SKIN_MESH_PLAY_TYPE["WOSMPY_LOOP"] )
g_pObjectSkinMesh:SetLayer( X2_LAYER["XL_SKY_WORLD_OBJECT_OVER_EFFECT_1"] )
g_pObjectSkinMesh:SetPos( D3DXVECTOR3(4850, 3135, -590) )
g_pObjectSkinMesh:SetScale( D3DXVECTOR3( 0.8, 0.8, 1) )
g_pObjectSkinMesh:SetOriginalColorFactor( D3DXCOLOR(0.611765, 0.709804, 1, 1))
g_pObjectSkinMesh:SetColorFactor( D3DXCOLOR(1,1,1,1) )
g_pObjectSkinMesh:SetCanHide( false, false )
g_pRenderParam = g_pObjectSkinMesh:GetRenderParam()
g_pObjectSkinMesh:SetAlphaObject( true )
g_pRenderParam.bAlphaBlend = true
g_pObjectSkinMesh:SetFog( 2000, 5000, 1000, 10000, D3DXCOLOR(0, 0.239216, 0.486275, 1), 0 )


g_pObjectSkinMesh = g_pWorld:CreateObjectSkinMesh()
g_pObjectSkinMesh:SetXSkinMotion( "HAMEL_RESIAM_UNDERWATER_STAGE1_SEAMUSTARD.X" )
g_pObjectSkinMesh:AddXSkinModel( "HAMEL_RESIAM_UNDERWATER_STAGE1_SEAMUSTARD.X" )
g_pObjectSkinMesh:AddAnim( "Normal" )
g_pObjectSkinMesh:PlayAnim( WORLD_OBJECT_SKIN_MESH_PLAY_TYPE["WOSMPY_LOOP"] )
g_pObjectSkinMesh:SetLayer( X2_LAYER["XL_SKY_WORLD_OBJECT_OVER_EFFECT_0"] )
g_pObjectSkinMesh:SetPos( D3DXVECTOR3(4640, 3135, -525) )
g_pObjectSkinMesh:SetOriginalColorFactor( D3DXCOLOR(0.611765, 0.709804, 1, 1))
g_pObjectSkinMesh:SetColorFactor( D3DXCOLOR(1,1,1,1) )
g_pObjectSkinMesh:SetCanHide( false, false )
g_pRenderParam = g_pObjectSkinMesh:GetRenderParam()
g_pObjectSkinMesh:SetAlphaObject( true )
g_pRenderParam.bAlphaBlend = true
g_pObjectSkinMesh:SetFog( 2000, 5000, 1000, 10000, D3DXCOLOR(0, 0.239216, 0.486275, 1), 0 )


g_pObjectSkinMesh = g_pWorld:CreateObjectSkinMesh()
g_pObjectSkinMesh:SetXSkinMotion( "HAMEL_RESIAM_UNDERWATER_STAGE1_SEAMUSTARD_BLUE.X" )
g_pObjectSkinMesh:AddXSkinModel( "HAMEL_RESIAM_UNDERWATER_STAGE1_SEAMUSTARD_BLUE.X" )
g_pObjectSkinMesh:AddAnim( "Normal" )
g_pObjectSkinMesh:PlayAnim( WORLD_OBJECT_SKIN_MESH_PLAY_TYPE["WOSMPY_LOOP"] )
g_pObjectSkinMesh:SetLayer( X2_LAYER["XL_SKY_WORLD_BASE_0"] )
g_pObjectSkinMesh:SetPos( D3DXVECTOR3(3985, 4215, 680) )
g_pObjectSkinMesh:SetOriginalColorFactor( D3DXCOLOR(0.45098, 0.741176, 1, 1))
g_pObjectSkinMesh:SetColorFactor( D3DXCOLOR(1,1,1,1) )
g_pObjectSkinMesh:SetCanHide( false, false )
g_pRenderParam = g_pObjectSkinMesh:GetRenderParam()
g_pObjectSkinMesh:SetAlphaObject( true )
g_pRenderParam.bAlphaBlend = true
g_pObjectSkinMesh:SetFog( 2000, 5000, 1000, 10000, D3DXCOLOR(0, 0.239216, 0.486275, 1), 0 )


g_pObjectSkinMesh = g_pWorld:CreateObjectSkinMesh()
g_pObjectSkinMesh:SetXSkinMotion( "HAMEL_RESIAM_UNDERWATER_STAGE1_SEAMUSTARD_BLUE.X" )
g_pObjectSkinMesh:AddXSkinModel( "HAMEL_RESIAM_UNDERWATER_STAGE1_SEAMUSTARD_BLUE.X" )
g_pObjectSkinMesh:AddAnim( "Normal" )
g_pObjectSkinMesh:PlayAnim( WORLD_OBJECT_SKIN_MESH_PLAY_TYPE["WOSMPY_LOOP"] )
g_pObjectSkinMesh:SetLayer( X2_LAYER["XL_SKY_WORLD_BASE_0"] )
g_pObjectSkinMesh:SetPos( D3DXVECTOR3(8600, 2950, 240) )
g_pObjectSkinMesh:SetOriginalColorFactor( D3DXCOLOR(0.45098, 0.741176, 1, 1))
g_pObjectSkinMesh:SetColorFactor( D3DXCOLOR(1,1,1,1) )
g_pObjectSkinMesh:SetCanHide( false, false )
g_pRenderParam = g_pObjectSkinMesh:GetRenderParam()
g_pObjectSkinMesh:SetAlphaObject( true )
g_pRenderParam.bAlphaBlend = true
g_pObjectSkinMesh:SetFog( 2000, 5000, 1000, 10000, D3DXCOLOR(0, 0.239216, 0.486275, 1), 0 )


g_pObjectSkinMesh = g_pWorld:CreateObjectSkinMesh()
g_pObjectSkinMesh:SetXSkinMotion( "HAMEL_RESIAM_UNDERWATER_STAGE1_SEAMUSTARD_BLUE.X" )
g_pObjectSkinMesh:AddXSkinModel( "HAMEL_RESIAM_UNDERWATER_STAGE1_SEAMUSTARD_BLUE.X" )
g_pObjectSkinMesh:AddAnim( "Normal" )
g_pObjectSkinMesh:PlayAnim( WORLD_OBJECT_SKIN_MESH_PLAY_TYPE["WOSMPY_LOOP"] )
g_pObjectSkinMesh:SetLayer( X2_LAYER["XL_SKY_WORLD_BASE_1"] )
g_pObjectSkinMesh:SetPos( D3DXVECTOR3(1370, 4600, 290) )
g_pObjectSkinMesh:SetOriginalColorFactor( D3DXCOLOR(0.45098, 0.741176, 1, 1))
g_pObjectSkinMesh:SetColorFactor( D3DXCOLOR(1,1,1,1) )
g_pObjectSkinMesh:SetCanHide( false, false )
g_pRenderParam = g_pObjectSkinMesh:GetRenderParam()
g_pObjectSkinMesh:SetAlphaObject( true )
g_pRenderParam.bAlphaBlend = true
g_pObjectSkinMesh:SetFog( 2000, 5000, 1000, 10000, D3DXCOLOR(0, 0.239216, 0.486275, 1), 0 )


g_pObjectSkinMesh = g_pWorld:CreateObjectSkinMesh()
g_pObjectSkinMesh:SetXSkinMotion( "HAMEL_RESIAM_UNDERWATER_STAGE1_SEAMUSTARD.X" )
g_pObjectSkinMesh:AddXSkinModel( "HAMEL_RESIAM_UNDERWATER_STAGE1_SEAMUSTARD.X" )
g_pObjectSkinMesh:AddAnim( "Normal" )
g_pObjectSkinMesh:PlayAnim( WORLD_OBJECT_SKIN_MESH_PLAY_TYPE["WOSMPY_LOOP"] )
g_pObjectSkinMesh:SetLayer( X2_LAYER["XL_SKY_WORLD_OBJECT_OVER_EFFECT_0"] )
g_pObjectSkinMesh:SetPos( D3DXVECTOR3(-2400, 4720, -660) )
g_pObjectSkinMesh:SetOriginalColorFactor( D3DXCOLOR(0.611765, 0.709804, 1, 1))
g_pObjectSkinMesh:SetColorFactor( D3DXCOLOR(1,1,1,1) )
g_pObjectSkinMesh:SetCanHide( false, false )
g_pRenderParam = g_pObjectSkinMesh:GetRenderParam()
g_pObjectSkinMesh:SetAlphaObject( true )
g_pRenderParam.bAlphaBlend = true
g_pObjectSkinMesh:SetFog( 2000, 5000, 1000, 10000, D3DXCOLOR(0, 0.239216, 0.486275, 1), 0 )


g_pObjectSkinMesh = g_pWorld:CreateObjectSkinMesh()
g_pObjectSkinMesh:SetXSkinMotion( "HAMEL_RESIAM_UNDERWATER_STAGE1_SEAMUSTARD_BLUE.X" )
g_pObjectSkinMesh:AddXSkinModel( "HAMEL_RESIAM_UNDERWATER_STAGE1_SEAMUSTARD_BLUE.X" )
g_pObjectSkinMesh:AddAnim( "Normal" )
g_pObjectSkinMesh:PlayAnim( WORLD_OBJECT_SKIN_MESH_PLAY_TYPE["WOSMPY_LOOP"] )
g_pObjectSkinMesh:SetLayer( X2_LAYER["XL_SKY_WORLD_BASE_1"] )
g_pObjectSkinMesh:SetPos( D3DXVECTOR3(7550, 3300, 530) )
g_pObjectSkinMesh:SetOriginalColorFactor( D3DXCOLOR(0.45098, 0.741176, 1, 1))
g_pObjectSkinMesh:SetColorFactor( D3DXCOLOR(1,1,1,1) )
g_pObjectSkinMesh:SetCanHide( false, false )
g_pRenderParam = g_pObjectSkinMesh:GetRenderParam()
g_pObjectSkinMesh:SetAlphaObject( true )
g_pRenderParam.bAlphaBlend = true
g_pObjectSkinMesh:SetFog( 2000, 5000, 1000, 10000, D3DXCOLOR(0, 0.239216, 0.486275, 1), 0 )


g_pObjectSkinMesh = g_pWorld:CreateObjectSkinMesh()
g_pObjectSkinMesh:SetXSkinMotion( "HAMEL_RESIAM_UNDERWATER_STAGE1_SEAMUSTARD.X" )
g_pObjectSkinMesh:AddXSkinModel( "HAMEL_RESIAM_UNDERWATER_STAGE1_SEAMUSTARD.X" )
g_pObjectSkinMesh:AddAnim( "Normal" )
g_pObjectSkinMesh:PlayAnim( WORLD_OBJECT_SKIN_MESH_PLAY_TYPE["WOSMPY_LOOP"] )
g_pObjectSkinMesh:SetLayer( X2_LAYER["XL_SKY_WORLD_OBJECT_OVER_EFFECT_0"] )
g_pObjectSkinMesh:SetPos( D3DXVECTOR3(-1200, 4350, -650) )
g_pObjectSkinMesh:SetOriginalColorFactor( D3DXCOLOR(1, 1, 1, 1))
g_pObjectSkinMesh:SetColorFactor( D3DXCOLOR(1,1,1,1) )
g_pObjectSkinMesh:SetCanHide( false, false )
g_pRenderParam = g_pObjectSkinMesh:GetRenderParam()
g_pObjectSkinMesh:SetAlphaObject( true )
g_pRenderParam.bAlphaBlend = true
g_pObjectSkinMesh:SetFog( 2000, 5000, 1000, 10000, D3DXCOLOR(0, 0.239216, 0.486275, 1), 0 )


g_pObjectSkinMesh = g_pWorld:CreateObjectSkinMesh()
g_pObjectSkinMesh:SetXSkinMotion( "HAMEL_RESIAM_UNDERWATER_STAGE1_SEAMUSTARD_BLUE.X" )
g_pObjectSkinMesh:AddXSkinModel( "HAMEL_RESIAM_UNDERWATER_STAGE1_SEAMUSTARD_BLUE.X" )
g_pObjectSkinMesh:AddAnim( "Normal" )
g_pObjectSkinMesh:PlayAnim( WORLD_OBJECT_SKIN_MESH_PLAY_TYPE["WOSMPY_LOOP"] )
g_pObjectSkinMesh:SetLayer( X2_LAYER["XL_SKY_WORLD_BASE_1"] )
g_pObjectSkinMesh:SetPos( D3DXVECTOR3(4070, 4290, 580) )
g_pObjectSkinMesh:SetOriginalColorFactor( D3DXCOLOR(0.45098, 0.741176, 1, 1))
g_pObjectSkinMesh:SetColorFactor( D3DXCOLOR(1,1,1,1) )
g_pObjectSkinMesh:SetCanHide( false, false )
g_pRenderParam = g_pObjectSkinMesh:GetRenderParam()
g_pObjectSkinMesh:SetAlphaObject( true )
g_pRenderParam.bAlphaBlend = true
g_pObjectSkinMesh:SetFog( 2000, 5000, 1000, 10000, D3DXCOLOR(0, 0.239216, 0.486275, 1), 0 )


g_pObjectSkinMesh = g_pWorld:CreateObjectSkinMesh()
g_pObjectSkinMesh:SetXSkinMotion( "HAMEL_RESIAM_UNDERWATER_STAGE1_SEAMUSTARD.X" )
g_pObjectSkinMesh:AddXSkinModel( "HAMEL_RESIAM_UNDERWATER_STAGE1_SEAMUSTARD.X" )
g_pObjectSkinMesh:AddAnim( "Normal" )
g_pObjectSkinMesh:PlayAnim( WORLD_OBJECT_SKIN_MESH_PLAY_TYPE["WOSMPY_LOOP"] )
g_pObjectSkinMesh:SetLayer( X2_LAYER["XL_SKY_WORLD_OBJECT_OVER_EFFECT_0"] )
g_pObjectSkinMesh:SetPos( D3DXVECTOR3(100, 4400, -330) )
g_pObjectSkinMesh:SetOriginalColorFactor( D3DXCOLOR(0.611765, 0.709804, 1, 1))
g_pObjectSkinMesh:SetColorFactor( D3DXCOLOR(1,1,1,1) )
g_pObjectSkinMesh:SetCanHide( false, false )
g_pRenderParam = g_pObjectSkinMesh:GetRenderParam()
g_pObjectSkinMesh:SetAlphaObject( true )
g_pRenderParam.bAlphaBlend = true
g_pObjectSkinMesh:SetFog( 2000, 5000, 1000, 10000, D3DXCOLOR(0, 0.239216, 0.486275, 1), 0 )


g_pObjectSkinMesh = g_pWorld:CreateObjectSkinMesh()
g_pObjectSkinMesh:SetXSkinMotion( "HAMEL_RESIAM_UNDERWATER_STAGE1_SEAMUSTARD_BLUE.X" )
g_pObjectSkinMesh:AddXSkinModel( "HAMEL_RESIAM_UNDERWATER_STAGE1_SEAMUSTARD_BLUE.X" )
g_pObjectSkinMesh:AddAnim( "Normal" )
g_pObjectSkinMesh:PlayAnim( WORLD_OBJECT_SKIN_MESH_PLAY_TYPE["WOSMPY_LOOP"] )
g_pObjectSkinMesh:SetLayer( X2_LAYER["XL_SKY_WORLD_BASE_0"] )
g_pObjectSkinMesh:SetPos( D3DXVECTOR3(-2135, 5230, 1000) )
g_pObjectSkinMesh:SetOriginalColorFactor( D3DXCOLOR(0.45098, 0.741176, 1, 1))
g_pObjectSkinMesh:SetColorFactor( D3DXCOLOR(1,1,1,1) )
g_pObjectSkinMesh:SetCanHide( false, false )
g_pRenderParam = g_pObjectSkinMesh:GetRenderParam()
g_pObjectSkinMesh:SetAlphaObject( true )
g_pRenderParam.bAlphaBlend = true
g_pObjectSkinMesh:SetFog( 2000, 5000, 1000, 10000, D3DXCOLOR(0, 0.239216, 0.486275, 1), 0 )


g_pObjectSkinMesh = g_pWorld:CreateObjectSkinMesh()
g_pObjectSkinMesh:SetXSkinMotion( "HAMEL_RESIAM_UNDERWATER_STAGE1_SEAMUSTARD_BLUE.X" )
g_pObjectSkinMesh:AddXSkinModel( "HAMEL_RESIAM_UNDERWATER_STAGE1_SEAMUSTARD_BLUE.X" )
g_pObjectSkinMesh:AddAnim( "Normal" )
g_pObjectSkinMesh:PlayAnim( WORLD_OBJECT_SKIN_MESH_PLAY_TYPE["WOSMPY_LOOP"] )
g_pObjectSkinMesh:SetLayer( X2_LAYER["XL_SKY_WORLD_BASE_1"] )
g_pObjectSkinMesh:SetPos( D3DXVECTOR3(-1875, 5030, 685) )
g_pObjectSkinMesh:SetOriginalColorFactor( D3DXCOLOR(0.45098, 0.741176, 1, 1))
g_pObjectSkinMesh:SetColorFactor( D3DXCOLOR(1,1,1,1) )
g_pObjectSkinMesh:SetCanHide( false, false )
g_pRenderParam = g_pObjectSkinMesh:GetRenderParam()
g_pObjectSkinMesh:SetAlphaObject( true )
g_pRenderParam.bAlphaBlend = true
g_pObjectSkinMesh:SetFog( 2000, 5000, 1000, 10000, D3DXCOLOR(0, 0.239216, 0.486275, 1), 0 )


g_pObjectSkinMesh = g_pWorld:CreateObjectSkinMesh()
g_pObjectSkinMesh:SetXSkinMotion( "HAMEL_RESIAM_UNDERWATER_STAGE1_SEAMUSTARD.X" )
g_pObjectSkinMesh:AddXSkinModel( "HAMEL_RESIAM_UNDERWATER_STAGE1_SEAMUSTARD.X" )
g_pObjectSkinMesh:AddAnim( "Normal" )
g_pObjectSkinMesh:PlayAnim( WORLD_OBJECT_SKIN_MESH_PLAY_TYPE["WOSMPY_LOOP"] )
g_pObjectSkinMesh:SetLayer( X2_LAYER["XL_SKY_WORLD_OBJECT_OVER_EFFECT_1"] )
g_pObjectSkinMesh:SetPos( D3DXVECTOR3(-2540, 4950, -810) )
g_pObjectSkinMesh:SetOriginalColorFactor( D3DXCOLOR(0.611765, 0.709804, 1, 1))
g_pObjectSkinMesh:SetColorFactor( D3DXCOLOR(1,1,1,1) )
g_pObjectSkinMesh:SetCanHide( false, false )
g_pRenderParam = g_pObjectSkinMesh:GetRenderParam()
g_pObjectSkinMesh:SetAlphaObject( true )
g_pRenderParam.bAlphaBlend = true
g_pObjectSkinMesh:SetFog( 2000, 5000, 1000, 10000, D3DXCOLOR(0, 0.239216, 0.486275, 1), 0 )


g_pObjectSkinMesh = g_pWorld:CreateObjectSkinMesh()
g_pObjectSkinMesh:SetXSkinMotion( "HAMEL_RESIAM_UNDERWATER_STAGE2_ANCHONVY.X" )
g_pObjectSkinMesh:AddXSkinModel( "HAMEL_RESIAM_UNDERWATER_STAGE2_ANCHONVY.X" )
g_pObjectSkinMesh:AddAnim( "Normal" )
g_pObjectSkinMesh:PlayAnim( WORLD_OBJECT_SKIN_MESH_PLAY_TYPE["WOSMPY_LOOP"] )
g_pObjectSkinMesh:SetAnimSpeed( 0.2 ) 
g_pObjectSkinMesh:SetLayer( X2_LAYER["XL_SKY_DOME_2"] )
g_pObjectSkinMesh:SetPos( D3DXVECTOR3(0, 4000, 2100) )
g_pObjectSkinMesh:SetScale( D3DXVECTOR3( 0.9, 0.9, 0.9) )
g_pObjectSkinMesh:SetOriginalColorFactor( D3DXCOLOR(0.0784314, 0.592157, 0.882353, 1))
g_pObjectSkinMesh:SetColorFactor( D3DXCOLOR(1,1,1,1) )
g_pObjectSkinMesh:SetCanHide( false, false )
g_pRenderParam = g_pObjectSkinMesh:GetRenderParam()
g_pObjectSkinMesh:SetAlphaObject( true )
g_pRenderParam.bAlphaBlend = true
g_pObjectSkinMesh:SetFog( 2000, 5000, 1000, 10000, D3DXCOLOR(0, 0.239216, 0.486275, 1), 0 )


g_pObjectSkinMesh = g_pWorld:CreateObjectSkinMesh()
g_pObjectSkinMesh:SetXSkinMotion( "HAMEL_RESIAM_UNDERWATER_STAGE2_ANCHONVY.X" )
g_pObjectSkinMesh:AddXSkinModel( "HAMEL_RESIAM_UNDERWATER_STAGE2_ANCHONVY.X" )
g_pObjectSkinMesh:AddAnim( "Normal" )
g_pObjectSkinMesh:PlayAnim( WORLD_OBJECT_SKIN_MESH_PLAY_TYPE["WOSMPY_LOOP"] )
g_pObjectSkinMesh:SetAnimSpeed( 0.1 ) 
g_pObjectSkinMesh:SetLayer( X2_LAYER["XL_SKY_DOME_2"] )
g_pObjectSkinMesh:SetPos( D3DXVECTOR3(0, 6000, 1500) )
g_pObjectSkinMesh:SetOriginalColorFactor( D3DXCOLOR(0.0784314, 0.592157, 0.882353, 1))
g_pObjectSkinMesh:SetColorFactor( D3DXCOLOR(1,1,1,1) )
g_pObjectSkinMesh:SetCanHide( false, false )
g_pRenderParam = g_pObjectSkinMesh:GetRenderParam()
g_pObjectSkinMesh:SetAlphaObject( true )
g_pRenderParam.bAlphaBlend = true
g_pObjectSkinMesh:SetFog( 2000, 5000, 1000, 10000, D3DXCOLOR(0, 0.239216, 0.486275, 1), 0 )


g_pObjectSkinMesh = g_pWorld:CreateObjectSkinMesh()
g_pObjectSkinMesh:SetXSkinMotion( "HAMEL_RESIAM_UNDERWATER_STAGE1_SEAMUSTARD.X" )
g_pObjectSkinMesh:AddXSkinModel( "HAMEL_RESIAM_UNDERWATER_STAGE1_SEAMUSTARD.X" )
g_pObjectSkinMesh:AddAnim( "Normal" )
g_pObjectSkinMesh:PlayAnim( WORLD_OBJECT_SKIN_MESH_PLAY_TYPE["WOSMPY_LOOP"] )
g_pObjectSkinMesh:SetLayer( X2_LAYER["XL_SKY_WORLD_OBJECT_OVER_EFFECT_1"] )
g_pObjectSkinMesh:SetPos( D3DXVECTOR3(-1300, 4490, -715) )
g_pObjectSkinMesh:SetOriginalColorFactor( D3DXCOLOR(0.611765, 0.709804, 1, 1))
g_pObjectSkinMesh:SetColorFactor( D3DXCOLOR(1,1,1,1) )
g_pObjectSkinMesh:SetCanHide( false, false )
g_pRenderParam = g_pObjectSkinMesh:GetRenderParam()
g_pObjectSkinMesh:SetAlphaObject( true )
g_pRenderParam.bAlphaBlend = true
g_pObjectSkinMesh:SetFog( 2000, 5000, 1000, 10000, D3DXCOLOR(0, 0.239216, 0.486275, 1), 0 )


g_pObjectSkinMesh = g_pWorld:CreateObjectSkinMesh()
g_pObjectSkinMesh:SetXSkinMotion( "HAMEL_RESIAM_UNDERWATER_STAGE1_SEAMUSTARD_BLUE.X" )
g_pObjectSkinMesh:AddXSkinModel( "HAMEL_RESIAM_UNDERWATER_STAGE1_SEAMUSTARD_BLUE.X" )
g_pObjectSkinMesh:AddAnim( "Normal" )
g_pObjectSkinMesh:PlayAnim( WORLD_OBJECT_SKIN_MESH_PLAY_TYPE["WOSMPY_LOOP"] )
g_pObjectSkinMesh:SetLayer( X2_LAYER["XL_SKY_WORLD_BASE_1"] )
g_pObjectSkinMesh:SetPos( D3DXVECTOR3(8700, 3090, 190) )
g_pObjectSkinMesh:SetOriginalColorFactor( D3DXCOLOR(0.45098, 0.741176, 1, 1))
g_pObjectSkinMesh:SetColorFactor( D3DXCOLOR(1,1,1,1) )
g_pObjectSkinMesh:SetCanHide( false, false )
g_pRenderParam = g_pObjectSkinMesh:GetRenderParam()
g_pObjectSkinMesh:SetAlphaObject( true )
g_pRenderParam.bAlphaBlend = true
g_pObjectSkinMesh:SetFog( 2000, 5000, 1000, 10000, D3DXCOLOR(0, 0.239216, 0.486275, 1), 0 )


g_pObjectSkinMesh = g_pWorld:CreateObjectSkinMesh()
g_pObjectSkinMesh:SetXSkinMotion( "HAMEL_RESIAM_UNDERWATER_STAGE1_SEAMUSTARD.X" )
g_pObjectSkinMesh:AddXSkinModel( "HAMEL_RESIAM_UNDERWATER_STAGE1_SEAMUSTARD.X" )
g_pObjectSkinMesh:AddAnim( "Normal" )
g_pObjectSkinMesh:PlayAnim( WORLD_OBJECT_SKIN_MESH_PLAY_TYPE["WOSMPY_LOOP"] )
g_pObjectSkinMesh:SetLayer( X2_LAYER["XL_SKY_WORLD_OBJECT_OVER_EFFECT_1"] )
g_pObjectSkinMesh:SetPos( D3DXVECTOR3(3070, 3400, -605) )
g_pObjectSkinMesh:SetOriginalColorFactor( D3DXCOLOR(0.611765, 0.709804, 1, 1))
g_pObjectSkinMesh:SetColorFactor( D3DXCOLOR(1,1,1,1) )
g_pObjectSkinMesh:SetCanHide( false, false )
g_pRenderParam = g_pObjectSkinMesh:GetRenderParam()
g_pObjectSkinMesh:SetAlphaObject( true )
g_pRenderParam.bAlphaBlend = true
g_pObjectSkinMesh:SetFog( 2000, 5000, 1000, 10000, D3DXCOLOR(0, 0.239216, 0.486275, 1), 0 )


g_pObjectSkinMesh = g_pWorld:CreateObjectSkinMesh()
g_pObjectSkinMesh:SetXSkinMotion( "HAMEL_RESIAM_UNDERWATER_STAGE1_SEAMUSTARD.X" )
g_pObjectSkinMesh:AddXSkinModel( "HAMEL_RESIAM_UNDERWATER_STAGE1_SEAMUSTARD.X" )
g_pObjectSkinMesh:AddAnim( "Normal" )
g_pObjectSkinMesh:PlayAnim( WORLD_OBJECT_SKIN_MESH_PLAY_TYPE["WOSMPY_LOOP"] )
g_pObjectSkinMesh:SetLayer( X2_LAYER["XL_SKY_WORLD_OBJECT_OVER_EFFECT_2"] )
g_pObjectSkinMesh:SetPos( D3DXVECTOR3(2740, 3200, -720) )
g_pObjectSkinMesh:SetOriginalColorFactor( D3DXCOLOR(0.611765, 0.709804, 1, 1))
g_pObjectSkinMesh:SetColorFactor( D3DXCOLOR(1,1,1,1) )
g_pObjectSkinMesh:SetCanHide( false, false )
g_pRenderParam = g_pObjectSkinMesh:GetRenderParam()
g_pObjectSkinMesh:SetAlphaObject( true )
g_pRenderParam.bAlphaBlend = true
g_pObjectSkinMesh:SetFog( 2000, 5000, 1000, 10000, D3DXCOLOR(0, 0.239216, 0.486275, 1), 0 )


g_pObjectSkinMesh = g_pWorld:CreateObjectSkinMesh()
g_pObjectSkinMesh:SetXSkinMotion( "HAMEL_RESIAM_UNDERWATER_STAGE2_ANCHONVY.X" )
g_pObjectSkinMesh:AddXSkinModel( "HAMEL_RESIAM_UNDERWATER_STAGE2_ANCHONVY.X" )
g_pObjectSkinMesh:AddAnim( "Normal" )
g_pObjectSkinMesh:PlayAnim( WORLD_OBJECT_SKIN_MESH_PLAY_TYPE["WOSMPY_LOOP"] )
g_pObjectSkinMesh:SetAnimSpeed( 0.1 ) 
g_pObjectSkinMesh:SetLayer( X2_LAYER["XL_SKY_DOME_2"] )
g_pObjectSkinMesh:SetPos( D3DXVECTOR3(0, 3000, 1500) )
g_pObjectSkinMesh:SetOriginalColorFactor( D3DXCOLOR(0.0784314, 0.592157, 0.882353, 1))
g_pObjectSkinMesh:SetColorFactor( D3DXCOLOR(1,1,1,1) )
g_pObjectSkinMesh:SetCanHide( false, false )
g_pRenderParam = g_pObjectSkinMesh:GetRenderParam()
g_pObjectSkinMesh:SetAlphaObject( true )
g_pRenderParam.bAlphaBlend = true
g_pObjectSkinMesh:SetFog( 2000, 5000, 1000, 10000, D3DXCOLOR(0, 0.239216, 0.486275, 1), 0 )


g_pObjectSkinMesh = g_pWorld:CreateObjectSkinMesh()
g_pObjectSkinMesh:SetXSkinMotion( "HAMEL_RESIAM_UNDERWATER_STAGE1_SEAMUSTARD.X" )
g_pObjectSkinMesh:AddXSkinModel( "HAMEL_RESIAM_UNDERWATER_STAGE1_SEAMUSTARD.X" )
g_pObjectSkinMesh:AddAnim( "Normal" )
g_pObjectSkinMesh:PlayAnim( WORLD_OBJECT_SKIN_MESH_PLAY_TYPE["WOSMPY_LOOP"] )
g_pObjectSkinMesh:SetLayer( X2_LAYER["XL_SKY_WORLD_OBJECT_OVER_EFFECT_0"] )
g_pObjectSkinMesh:SetPos( D3DXVECTOR3(2780, 3340, -250) )
g_pObjectSkinMesh:SetOriginalColorFactor( D3DXCOLOR(0.611765, 0.709804, 1, 1))
g_pObjectSkinMesh:SetColorFactor( D3DXCOLOR(1,1,1,1) )
g_pObjectSkinMesh:SetCanHide( false, false )
g_pRenderParam = g_pObjectSkinMesh:GetRenderParam()
g_pObjectSkinMesh:SetAlphaObject( true )
g_pRenderParam.bAlphaBlend = true
g_pObjectSkinMesh:SetFog( 2000, 5000, 1000, 10000, D3DXCOLOR(0, 0.239216, 0.486275, 1), 0 )


g_pObjectSkinMesh = g_pWorld:CreateObjectSkinMesh()
g_pObjectSkinMesh:SetXSkinMotion( "HAMEL_RESIAM_UNDERWATER_STAGE1_SEAMUSTARD.X" )
g_pObjectSkinMesh:AddXSkinModel( "HAMEL_RESIAM_UNDERWATER_STAGE1_SEAMUSTARD.X" )
g_pObjectSkinMesh:AddAnim( "Normal" )
g_pObjectSkinMesh:PlayAnim( WORLD_OBJECT_SKIN_MESH_PLAY_TYPE["WOSMPY_LOOP"] )
g_pObjectSkinMesh:SetLayer( X2_LAYER["XL_SKY_WORLD_OBJECT_OVER_EFFECT_0"] )
g_pObjectSkinMesh:SetPos( D3DXVECTOR3(7860, 3105, -800) )
g_pObjectSkinMesh:SetOriginalColorFactor( D3DXCOLOR(0.611765, 0.709804, 1, 1))
g_pObjectSkinMesh:SetColorFactor( D3DXCOLOR(1,1,1,1) )
g_pObjectSkinMesh:SetCanHide( false, false )
g_pRenderParam = g_pObjectSkinMesh:GetRenderParam()
g_pObjectSkinMesh:SetAlphaObject( true )
g_pRenderParam.bAlphaBlend = true
g_pObjectSkinMesh:SetFog( 2000, 5000, 1000, 10000, D3DXCOLOR(0, 0.239216, 0.486275, 1), 0 )


g_pObjectSkinMesh = g_pWorld:CreateObjectSkinMesh()
g_pObjectSkinMesh:SetXSkinMotion( "HAMEL_RESIAM_UNDERWATER_STAGE1_SEAMUSTARD.X" )
g_pObjectSkinMesh:AddXSkinModel( "HAMEL_RESIAM_UNDERWATER_STAGE1_SEAMUSTARD.X" )
g_pObjectSkinMesh:AddAnim( "Normal" )
g_pObjectSkinMesh:PlayAnim( WORLD_OBJECT_SKIN_MESH_PLAY_TYPE["WOSMPY_LOOP"] )
g_pObjectSkinMesh:SetLayer( X2_LAYER["XL_SKY_WORLD_OBJECT_OVER_EFFECT_0"] )
g_pObjectSkinMesh:SetPos( D3DXVECTOR3(8050, 2960, -770) )
g_pObjectSkinMesh:SetOriginalColorFactor( D3DXCOLOR(0.611765, 0.709804, 1, 1))
g_pObjectSkinMesh:SetColorFactor( D3DXCOLOR(1,1,1,1) )
g_pObjectSkinMesh:SetCanHide( false, false )
g_pRenderParam = g_pObjectSkinMesh:GetRenderParam()
g_pObjectSkinMesh:SetAlphaObject( true )
g_pRenderParam.bAlphaBlend = true
g_pObjectSkinMesh:SetFog( 2000, 5000, 1000, 10000, D3DXCOLOR(0, 0.239216, 0.486275, 1), 0 )


g_pObjectSkinMesh = g_pWorld:CreateObjectSkinMesh()
g_pObjectSkinMesh:SetXSkinMotion( "HAMEL_RESIAM_UNDERWATER_STAGE2_ANCHONVY.X" )
g_pObjectSkinMesh:AddXSkinModel( "HAMEL_RESIAM_UNDERWATER_STAGE2_ANCHONVY.X" )
g_pObjectSkinMesh:AddAnim( "Normal" )
g_pObjectSkinMesh:PlayAnim( WORLD_OBJECT_SKIN_MESH_PLAY_TYPE["WOSMPY_LOOP"] )
g_pObjectSkinMesh:SetAnimSpeed( 0.2 ) 
g_pObjectSkinMesh:SetLayer( X2_LAYER["XL_SKY_DOME_2"] )
g_pObjectSkinMesh:SetPos( D3DXVECTOR3(0, 7000, 2100) )
g_pObjectSkinMesh:SetScale( D3DXVECTOR3( 0.9, 0.9, 0.9) )
g_pObjectSkinMesh:SetOriginalColorFactor( D3DXCOLOR(0.0784314, 0.592157, 0.882353, 1))
g_pObjectSkinMesh:SetColorFactor( D3DXCOLOR(1,1,1,1) )
g_pObjectSkinMesh:SetCanHide( false, false )
g_pRenderParam = g_pObjectSkinMesh:GetRenderParam()
g_pObjectSkinMesh:SetAlphaObject( true )
g_pRenderParam.bAlphaBlend = true
g_pObjectSkinMesh:SetFog( 2000, 5000, 1000, 10000, D3DXCOLOR(0, 0.239216, 0.486275, 1), 0 )


-- PARTICLE -- 


g_pObjectParticle = g_pWorld:CreateObjectParticle( g_pUIMinorParticle, "Pa_DeepSea_Bouble_Big" )
g_pObjectParticle:SetParticlePos( D3DXVECTOR3( 670, 4585, -15 ) )
--g_pObjectParticle:SetEmitMinMax( 20, 40 )
--g_pObjectParticle:SetTriggerCount( -1 )
--g_pObjectParticle:SetTriggerTime( -1 )
g_pObjectParticle:SetDrawCount( 1 )
g_pObjectParticle:SetCullCheck( true )
g_pObjectParticle:SetParticleType( PARTICLE_TYPE["PT_3D_PLANE"] )
g_pObjectParticle:SetLayer( X2_LAYER["XL_UNIT_2"] )


g_pObjectParticle = g_pWorld:CreateObjectParticle( g_pUIMinorParticle, "Pa_DeepSea_Bouble_Small" )
g_pObjectParticle:SetParticlePos( D3DXVECTOR3( 670, 4585, -15 ) )
--g_pObjectParticle:SetEmitMinMax( 20, 40 )
--g_pObjectParticle:SetTriggerCount( -1 )
--g_pObjectParticle:SetTriggerTime( -1 )
g_pObjectParticle:SetDrawCount( 1 )
g_pObjectParticle:SetCullCheck( true )
g_pObjectParticle:SetParticleType( PARTICLE_TYPE["PT_3D_PLANE"] )
g_pObjectParticle:SetLayer( X2_LAYER["XL_UNIT_2"] )


g_pObjectParticle = g_pWorld:CreateObjectParticle( g_pUIMinorParticle, "Pa_DeepSea_Bouble_Big" )
g_pObjectParticle:SetParticlePos( D3DXVECTOR3( 6245, 3390, -15 ) )
--g_pObjectParticle:SetEmitMinMax( 20, 40 )
--g_pObjectParticle:SetTriggerCount( -1 )
--g_pObjectParticle:SetTriggerTime( -1 )
g_pObjectParticle:SetDrawCount( 1 )
g_pObjectParticle:SetCullCheck( true )
g_pObjectParticle:SetParticleType( PARTICLE_TYPE["PT_3D_PLANE"] )
g_pObjectParticle:SetLayer( X2_LAYER["XL_UNIT_2"] )


g_pObjectParticle = g_pWorld:CreateObjectParticle( g_pUIMinorParticle, "Pa_DeepSea_Bouble_Small" )
g_pObjectParticle:SetParticlePos( D3DXVECTOR3( 6245, 3390, -15 ) )
--g_pObjectParticle:SetEmitMinMax( 20, 40 )
--g_pObjectParticle:SetTriggerCount( -1 )
--g_pObjectParticle:SetTriggerTime( -1 )
g_pObjectParticle:SetDrawCount( 1 )
g_pObjectParticle:SetCullCheck( true )
g_pObjectParticle:SetParticleType( PARTICLE_TYPE["PT_3D_PLANE"] )
g_pObjectParticle:SetLayer( X2_LAYER["XL_UNIT_2"] )
