

g_pLineMap:SetLandHeight( -100 )




-- RED, BLUE, TEAM START POS
g_pLineMap:SetTeamStartPos( true, D3DXVECTOR3( 700, 0, 0 ), true, 2 )
g_pLineMap:SetTeamStartPos( true, D3DXVECTOR3( -700, 0, 0 ), false, 2 )
g_pLineMap:SetTeamStartPos( true, D3DXVECTOR3( 800, 0, 0 ), true, 2 )
g_pLineMap:SetTeamStartPos( true, D3DXVECTOR3( -800, 0, 0 ), false, 2 )




-- NPC (or else) START POS
g_pLineMap:AddStartPos( 1, D3DXVECTOR3( -91.574, 0, 0 ), false, 2 )
g_pLineMap:AddStartPos( 2, D3DXVECTOR3( 300.574, 0, 0 ), false, 2 )





-- LINE DATA -- 
g_pLineMap:AddLine_LUA
{
	LINE_NUM		= 0, 
	LINE_TYPE 		= LINE_TYPE["LT_NORMAL"], 
	POTAL_GROUP		= 0, 
	BEFORE_LINE		= -1, 
	NEXT_LINE		= -2, 
	LINE_SET		= 0, 
	"START_POS		= D3DXVECTOR3(1400, 240, 0)", 
	"END_POS		= D3DXVECTOR3(2000, 240, 0)", 
}

g_pLineMap:AddLine_LUA
{
	LINE_NUM		= 1, 
	LINE_TYPE 		= LINE_TYPE["LT_NORMAL"], 
	POTAL_GROUP		= 0, 
	BEFORE_LINE		= -2, 
	NEXT_LINE		= -1, 
	LINE_SET		= 0, 
	"START_POS		= D3DXVECTOR3(-2000, 240, 0)", 
	"END_POS		= D3DXVECTOR3(-1400, 240, 0)", 
}

g_pLineMap:AddLine_LUA
{
	LINE_NUM		= 2, 
	LINE_TYPE 		= LINE_TYPE["LT_NORMAL"], 
	POTAL_GROUP		= 0, 
	BEFORE_LINE		= -1, 
	NEXT_LINE		= -1, 
	LINE_SET		= 0, 
	TRIGGER_ID		= 0, 
	"START_POS		= D3DXVECTOR3(-2000, 0, 0)", 
	"END_POS		= D3DXVECTOR3(2000, 0, 0)", 
}


-- CAMERA DATA 

g_pLineMap:AddCameraData_LUA
{
	FOCUS_UNIT	= FALSE,
	"EYE_POS	= D3DXVECTOR3(22.97, 1734.27, -5738.12)", 
	"LOOKAT_POS	= D3DXVECTOR3(68.24, 546.37, -1157.74)", 
}

g_pLineMap:AddTrigger_LUA
{
	TRIGGER_ID		= 0,
	TRIGGER_LOOP	= FALSE,
	TRIGGER_DATA0 =
	{
		TRIGGER_DATA_MESH0 =
		{
			TRIGGER_ACTION = TRIGGER_MESH_ACTION_TYPE["TAT_MESH_CHANGE_ANIM"],
			DELAY_TIME = 0,
			MESH_NAME = "TRIGGER_HAMEL_WATERWAY_CORE_SBOSS_BODY.X",
			ANIM_NAME = "Down",
			PLAY_TYPE = 1,
		},
		TRIGGER_DATA_MESH1 =
		{
			TRIGGER_ACTION = TRIGGER_MESH_ACTION_TYPE["TAT_MESH_CHANGE_ANIM"],
			DELAY_TIME = 0,
			MESH_NAME = "TRIGGER_HAMEL_WATERWAY_CORE_SBOSS_CHAINUV.X",
			ANIM_NAME = "Down",
			PLAY_TYPE = 1,
		},
		TRIGGER_DATA_MESH2 =
		{
			TRIGGER_ACTION = TRIGGER_MESH_ACTION_TYPE["TAT_MESH_CHANGE_ANIM"],
			DELAY_TIME = 0,
			MESH_NAME = "TRIGGER_HAMEL_WATERWAY_CORE_SBOSS_GMUEL.X",
			ANIM_NAME = "Down",
			PLAY_TYPE = 1,
		},
		TRIGGER_DATA_MESH3 =
		{
			TRIGGER_ACTION = TRIGGER_MESH_ACTION_TYPE["TAT_MESH_CHANGE_ANIM"],
			DELAY_TIME = 0,
			MESH_NAME = "TRIGGER_HAMEL_WATERWAY_CORE_SBOSS_LIGHT.X",
			ANIM_NAME = "Down",
			PLAY_TYPE = 1,
		},
		TRIGGER_DATA_MESH4 =
		{
			TRIGGER_ACTION = TRIGGER_MESH_ACTION_TYPE["TAT_MESH_CHANGE_ANIM"],
			DELAY_TIME = 0,
			MESH_NAME = "TRIGGER_HAMEL_WATERWAY_CORE_SBOSS_WATER.X",
			ANIM_NAME = "Down",
			PLAY_TYPE = 1,
		},
		TRIGGER_DATA_ETC0 =
		{
			TRIGGER_ACTION = TRIGGER_ETC_ACTION_TYPE["TAT_ETC_PLAY_SOUND"],
			DELAY_TIME = 0,
			LINE_SOUND = "Trig_WaterWayCore_PlateReach.ogg",
		},
		TRIGGER_DATA_ETC1 =
		{
			TRIGGER_ACTION = TRIGGER_ETC_ACTION_TYPE["TAT_ETC_CAMERA"],
			DELAY_TIME = 0,
			CAMERA_INDEX = 0,
			CAMERA_DURATION = 5.5,
		},
	},
}
