-- lua header. UTF-8 인코딩 인식을 위해 이 줄은 지우지 마세요.

--[[ KjTiger / 2011/1/4 / 고대 나소드 파수병/
	 AttackA, AttackB, DashAttack, SpecialAttack
--]]

INIT_SYSTEM =
{
	UNIT_WIDTH	= 200.0,
	UNIT_HEIGHT	= 180.0,
	UNIT_LAYER	= X2_LAYER["XL_UNIT_0"],
	UNIT_SCALE	= 2.5,
}
--------------------------------------------------------------------------
INIT_DEVICE =
{
	READY_TEXTURE =
	{
        "ANCIENT_NASOD_SENTRY_A.tga",
        "ANCIENT_NASOD_SENTRY_B.tga",
	},

	READY_SOUND =
	{
	"Landing_Stone01.ogg",
	"Ancient_Nasod_AttackA01.ogg",
	"Ancient_Nasod_AttackA02.ogg",
	"Ancient_Nasod_Death01.ogg",
	"Ancient_NAsod_Death02.ogg",
	"Ancient_Nasod_Growl01.ogg",
	"Ancient_Nasod_Growl02.ogg",
	"ANCIENT_NASOD_Load.ogg",
	"Ancient_Nasod_Machine01.ogg",
	"Ancient_Nasod_Machine02.ogg",
	"ANCIENT_NASOD_MagicAttackA.ogg",
	"ANCIENT_NASOD_WaitStart01.ogg",
	"ANCIENT_NASOD_WaitStart02.ogg",
	"Landing_Big_Meat02.ogg",
	},
}
--------------------------------------------------------------------------
INIT_MOTION =
{
	MOTION_FILE_NAME		= "Motion_ANCIENT_NASOD_SENTRY.x",
}
--------------------------------------------------------------------------
INIT_PHYSIC =
{
	RELOAD_ACCEL		= 2000,
	G_ACCEL				= 4000,
	MAX_G_SPEED			= -2000,

	WALK_SPEED			= 400,
	RUN_SPEED			= 600,
	JUMP_SPEED			= 1500,
	DASH_JUMP_SPEED		= 1800,
}
--------------------------------------------------------------------------
INIT_COMPONENT =
{
	--DEFAULT_ANIM_SPEED =  0.5,
	
	MAX_HP				= 20000,
	MP_CHANGE_RATE		= 1,
	MP_CHARGE_RATE		= 130,
	
	
	OUT_LINE_WIDTH_SCALE = 0.3,
	SHADOW_SIZE			= 200,
	SHADOW_FILE_NAME	= "shadow.dds",

	SMALL_HP_BAR_BLUE	= "Small_HP_bar_Blue.TGA",
	SMALL_HP_BAR_RED	= "Small_HP_bar_Red.TGA",
	SMALL_HP_BAR_YELLOW = "Small_HP_bar_Yellow.TGA",

	QUESTION_MARK_SEQ		= "QuestionMarkNPC",
	EXCLAMATION_MARK_SEQ	= "ExclamationMarkNPC",
	--MIND_FLAG_HEIGHT		= 230,

	HITTED_TYPE			= HITTED_TYPE["HTD_STONE"],

	FALL_DOWN			= TRUE,
}
--------------------------------------------------------------------------
INIT_STATE =
{
	{ STATE_NAME = "ANCIENT_NASOD_SENTRY_READY",		},
	{ STATE_NAME = "ANCIENT_NASOD_SENTRY_START",		},

	{ STATE_NAME = "ANCIENT_NASOD_SENTRY_WAIT",			},
	{ STATE_NAME = "ANCIENT_NASOD_SENTRY_WAIT_HABIT",	},

	{ STATE_NAME = "ANCIENT_NASOD_SENTRY_WALK",				LUA_STATE_END_FUNC = "ANCIENT_NASOD_SENTRY_WALK_STATE_END"	},
    { STATE_NAME = "ANCIENT_NASOD_SENTRY_DASH",				},
    { STATE_NAME = "ANCIENT_NASOD_SENTRY_DASH_FOR_ATTACK",	STATE_COOL_TIME	= 5,	},
    { STATE_NAME = "ANCIENT_NASOD_SENTRY_DASH_END",			},

	{ STATE_NAME = "ANCIENT_NASOD_SENTRY_JUMP_UP",			},
	{ STATE_NAME = "ANCIENT_NASOD_SENTRY_JUMP_DOWN",		LUA_STATE_END_FUNC = "ANCIENT_NASOD_SENTRY_JUMP_DOWN_STATE_END"		},
	{ STATE_NAME = "ANCIENT_NASOD_SENTRY_JUMP_UP_DIR",		},
	{ STATE_NAME = "ANCIENT_NASOD_SENTRY_JUMP_DOWN_DIR",	LUA_STATE_END_FUNC = "ANCIENT_NASOD_SENTRY_JUMP_DOWN_DIR_STATE_END"	},
	{ STATE_NAME = "ANCIENT_NASOD_SENTRY_JUMP_LANDING",		},

	{ STATE_NAME = "ANCIENT_NASOD_SENTRY_ATTACKA",	    	STATE_COOL_TIME	= 3,	},
	{ STATE_NAME = "ANCIENT_NASOD_SENTRY_ATTACKB",	    	STATE_COOL_TIME	= 4,	},
	{ STATE_NAME = "ANCIENT_NASOD_SENTRY_SPECIAL_ATTACK",	STATE_COOL_TIME	= 20,	},
	
	{ STATE_NAME = "ANCIENT_NASOD_SENTRY_DASH_ATTACK",			},
	{ STATE_NAME = "ANCIENT_NASOD_SENTRY_DASH_ATTACK_END",		},
	{ STATE_NAME = "ANCIENT_NASOD_SENTRY_DASH_ATTACK_READY",	},

	--리액션 관련
	{ STATE_NAME = "ANCIENT_NASOD_SENTRY_DAMAGE_SMALL_LAND_FRONT",	LUA_FRAME_MOVE_FUNC = "ANCIENT_NASOD_SENTRY_DAMAGE_SMALL_FRAME_MOVE"	    },
   	{ STATE_NAME = "ANCIENT_NASOD_SENTRY_DAMAGE_SMALL_LAND_BACK",	LUA_FRAME_MOVE_FUNC = "ANCIENT_NASOD_SENTRY_DAMAGE_SMALL_FRAME_MOVE"	  	},
	{ STATE_NAME = "ANCIENT_NASOD_SENTRY_DAMAGE_BIG_LAND_FRONT",	LUA_FRAME_MOVE_FUNC = "ANCIENT_NASOD_SENTRY_DAMAGE_BIG_FRAME_MOVE"			},
	{ STATE_NAME = "ANCIENT_NASOD_SENTRY_DAMAGE_BIG_LAND_BACK",		LUA_FRAME_MOVE_FUNC = "ANCIENT_NASOD_SENTRY_DAMAGE_BIG_FRAME_MOVE"			},
	{ STATE_NAME = "ANCIENT_NASOD_SENTRY_DAMAGE_DOWN_FRONT",		LUA_FRAME_MOVE_FUNC = "ANCIENT_NASOD_SENTRY_DAMAGE_DOWN_FRONT_FRAME_MOVE"	},
	{ STATE_NAME = "ANCIENT_NASOD_SENTRY_DAMAGE_DOWN_BACK",			LUA_FRAME_MOVE_FUNC = "ANCIENT_NASOD_SENTRY_DAMAGE_DOWN_BACK_FRAME_MOVE"	},
	{ STATE_NAME = "ANCIENT_NASOD_SENTRY_DAMAGE_FLY_FRONT",			},
	{ STATE_NAME = "ANCIENT_NASOD_SENTRY_DAMAGE_FLY_BACK",			},
	{ STATE_NAME = "ANCIENT_NASOD_SENTRY_DAMAGE_AIR_FALL",			},
	{ STATE_NAME = "ANCIENT_NASOD_SENTRY_DAMAGE_AIR_DOWN_LANDING",	LUA_FRAME_MOVE_FUNC = "ANCIENT_NASOD_SENTRY_DAMAGE_AIR_DOWN_LANDING_FRAME_MOVE"	},
    { STATE_NAME = "ANCIENT_NASOD_SENTRY_DAMAGE_REVENGE"            },
	{ STATE_NAME = "ANCIENT_NASOD_SENTRY_STAND_UP_FRONT",			},
	{ STATE_NAME = "ANCIENT_NASOD_SENTRY_STAND_UP_BACK",			},
	--{ STATE_NAME = "ANCIENT_NASOD_SENTRY_STAND_UP_ATTACK_FRONT",	LUA_FRAME_MOVE_FUNC = "ANCIENT_NASOD_SENTRY_STAND_UP_ATTACK_FRONT_FRAME_MOVE"	},
	--{ STATE_NAME = "ANCIENT_NASOD_SENTRY_STAND_UP_ATTACK_BACK",		LUA_FRAME_MOVE_FUNC = "ANCIENT_NASOD_SENTRY_STAND_UP_ATTACK_BACK_FRAME_MOVE"	},

	{ STATE_NAME = "ANCIENT_NASOD_SENTRY_DYING_LAND_FRONT",			LUA_STATE_START_FUNC = "ANCIENT_NASOD_SENTRY_DYING_LAND_STATE_START",	},
	{ STATE_NAME = "ANCIENT_NASOD_SENTRY_DYING_LAND_BACK",			LUA_STATE_START_FUNC = "ANCIENT_NASOD_SENTRY_DYING_LAND_STATE_START",	},
	{ STATE_NAME = "ANCIENT_NASOD_SENTRY_DYING_SKY",				LUA_STATE_START_FUNC = "ANCIENT_NASOD_SENTRY_DYING_LAND_STATE_START",	},

	START_STATE					= "ANCIENT_NASOD_SENTRY_READY",
	WAIT_STATE					= "ANCIENT_NASOD_SENTRY_WAIT",

	SMALL_DAMAGE_LAND_FRONT		= "ANCIENT_NASOD_SENTRY_DAMAGE_SMALL_LAND_FRONT",
	SMALL_DAMAGE_LAND_BACK		= "ANCIENT_NASOD_SENTRY_DAMAGE_SMALL_LAND_BACK",
	BIG_DAMAGE_LAND_FRONT		= "ANCIENT_NASOD_SENTRY_DAMAGE_BIG_LAND_FRONT",
	BIG_DAMAGE_LAND_BACK		= "ANCIENT_NASOD_SENTRY_DAMAGE_BIG_LAND_BACK",
	DOWN_DAMAGE_LAND_FRONT		= "ANCIENT_NASOD_SENTRY_DAMAGE_DOWN_FRONT",
	DOWN_DAMAGE_LAND_BACK		= "ANCIENT_NASOD_SENTRY_DAMAGE_DOWN_BACK",
	FLY_DAMAGE_FRONT			= "ANCIENT_NASOD_SENTRY_DAMAGE_FLY_FRONT",
	FLY_DAMAGE_BACK				= "ANCIENT_NASOD_SENTRY_DAMAGE_FLY_BACK",
	DOWN_DAMAGE_AIR_LANDING		= "ANCIENT_NASOD_SENTRY_DAMAGE_AIR_DOWN_LANDING",
	UP_DAMAGE					= "ANCIENT_NASOD_SENTRY_WAIT",
	DAMAGE_REVENGE				= "ANCIENT_NASOD_SENTRY_DAMAGE_REVENGE",
	
	DAMAGE_EXTRA_STATES         = {"ANCIENT_NASOD_SENTRY_DAMAGE_AIR_FALL","ANCIENT_NASOD_SENTRY_STAND_UP_FRONT","ANCIENT_NASOD_SENTRY_STAND_UP_BACK",
	"ANCIENT_NASOD_SENTRY_JUMP_DOWN","ANCIENT_NASOD_SENTRY_JUMP_LANDING",},
	

	DYING_LAND_FRONT			= "ANCIENT_NASOD_SENTRY_DYING_LAND_FRONT",
	DYING_LAND_BACK				= "ANCIENT_NASOD_SENTRY_DYING_LAND_BACK",
	DYING_SKY					= "ANCIENT_NASOD_SENTRY_DYING_SKY",

	REVENGE_ATTACK				= "",
}
--------------------------------------------------------------------------
INIT_AI =
{
	TARGET =
	{
		TARGET_PRIORITY 			= TARGET_PRIORITY["TP_LOW_HP_FIRST"],
		TARGET_INTERVAL				= 2,		-- sec
		TARGET_NEAR_RANGE			= 600,		-- 이 거리보다 가까우면 TARGET_SUCCESS_RATE에 관계없이 무조건 타게팅된다
		TARGET_RANGE				= 800,		-- cm
		TARGET_LOST_RANGE			= 1000,		-- cm
		TARGET_SUCCESS_RATE			= 50,  --50,		-- %
		ATTACK_TARGET_RATE			= 50, -- 30,		-- 나를 공격한 유닛을 타게팅할 확률
		PRESERVE_LAST_TARGET_RATE	= 100, -- 30,		-- 이전에 타게팅된 유닛을 계속 타게팅할 확률
	},

	CHASE_MOVE =
	{
		MOVE_SPLIT_RANGE	= 600,
		DEST_GAP			= 300,	-- 목적지에서 이 거리 안에 있으면 도착했다고 판단한다
		MOVE_GAP			= 400,

		DIR_CHANGE_INTERVAL = 0.7,

		WALK_INTERVAL		= 3,
		NEAR_WALK_RATE		= 50,   --  70,
		FAR_WALK_RATE		= 50,   -- 30,

		JUMP_INTERVAL		= 5,
		UP_JUMP_RATE		= 100, -- 40,
		UP_DOWN_RATE		= 20,
		DOWN_JUMP_RATE		= 100,    --  20,
		DOWN_DOWN_RATE		= 40,

		LINE_END_RANGE		= 80,	-- cm
	},

	PATROL_MOVE =
	{
		PATROL_BEGIN_RATE		= 50, --50,
		PATROL_RANGE			= 150,
		PATROL_COOL_TIME		= 2,
		ONLY_THIS_LINE_GROUP	= TRUE,
	},

	ESCAPE_MOVE =
	{
		MOVE_SPLIT_RANGE	= 500,	-- cm
		ESCAPE_GAP			= 600,	-- 이 거리 보다 멀어지면 도망 성공

		WALK_INTERVAL		= 1.5,	-- 초
		NEAR_WALK_RATE		= 100,   --  10,
		FAR_WALK_RATE		= 100,   -- 10,

		JUMP_INTERVAL		= 10,
		UP_JUMP_RATE		= 100, -- 30,
		UP_DOWN_RATE		= 30,
		DOWN_JUMP_RATE		= 100,    --  30,
		DOWN_DOWN_RATE		= 30,

		LINE_END_RANGE		= 80,	-- cm
	},

}
--------------------------------------------------------------------------
ANCIENT_NASOD_SENTRY_READY =
{
	RENDER_PARAM = RENDER_TYPE["RT_CARTOON"],
	ANIM_NAME	= "Start",
	PLAY_TYPE	= XSKIN_ANIM_PLAYTYPE["XAP_LOOP"],
	TRANSITION	= FALSE,

	CAN_PUSH_UNIT			= FALSE,
	CAN_PASS_UNIT			= FALSE,
	IMMADIATE_PACKET_SEND	= TRUE,
	
	--INVINCIBLE				= { 0, 100, },
	NEVER_MOVE				= TRUE,
	ALLOW_DIR_CHANGE		= FALSE,
	VIEW_TARGET				= FALSE,
	EVENT_INTERVAL_TIME0	= 0.3,

	EVENT_PROCESS =
	{
		{ STATE_CHANGE_TYPE["SCT_CONDITION_TABLE"],	"ANCIENT_NASOD_SENTRY_START",	"CT_ANCIENT_NASOD_SENTRY_START"    },
	},

	CT_ANCIENT_NASOD_SENTRY_START =
	{
		EVENT_INTERVAL_ID		= 0,
		DISTANCE_TO_TARGET_NEAR	= 800,
		RATE					= 100,
	},
}
--------------------------------------------------------------------------
ANCIENT_NASOD_SENTRY_START =
{
	ANIM_NAME	= "WaitStart",
	PLAY_TYPE	= XSKIN_ANIM_PLAYTYPE["XAP_ONE_WAIT"],
	TRANSITION	= TRUE,

	CAN_PUSH_UNIT			= FALSE,
	CAN_PASS_UNIT			= FALSE,
	IMMADIATE_PACKET_SEND	= TRUE,
	--INVINCIBLE				= { 0, 100, },
	ALLOW_DIR_CHANGE		= FALSE,
	VIEW_TARGET				= FALSE,
	SUPER_ARMOR				= TRUE,
	
	SOUND_PLAY0				= { 0.01, "ANCIENT_NASOD_WaitStart01.ogg" },
	SOUND_PLAY1				= { 0.65, "ANCIENT_NASOD_WaitStart02.ogg" },
	
	ATTACK_TIME0	= { 0.75, 1.024, },
	
	DAMAGE_DATA =
	{
		DAMAGE_TYPE		= DAMAGE_TYPE["DT_PHYSIC"],
		HIT_TYPE		= HIT_TYPE["HT_PUNCH_HIT"],
		REACT_TYPE		= REACT_TYPE["RT_BIG_DAMAGE"],

		DAMAGE =
		{
			PHYSIC	= 1.0,
		},

		BACK_SPEED_X	= 1200,
		BACK_SPEED_Y	= 0.0,

		CAMERA_CRASH_GAP	= 5.0,
		CAMERA_CRASH_TIME	= 0.2,
		
        CAN_REVENGE				= TRUE,
		
	},
	
	EVENT_PROCESS =
	{
		{ STATE_CHANGE_TYPE["SCT_CONDITION_TABLE"],	"ANCIENT_NASOD_SENTRY_WAIT",	"CT_ANCIENT_NASOD_SENTRY_WAIT"    },
	},
	
	
	CT_ANCIENT_NASOD_SENTRY_WAIT =
	{
		STATE_TIME_OVER			= 2.7,
	},
}
--------------------------------------------------------------------------
ANCIENT_NASOD_SENTRY_WAIT_HABIT =
{
	ANIM_NAME	= "WaitHabit",
	PLAY_TYPE	= XSKIN_ANIM_PLAYTYPE["XAP_ONE_WAIT"],
	TRANSITION	= TRUE,

	CAN_PUSH_UNIT			= TRUE,
	CAN_PASS_UNIT			= FALSE,
	IMMADIATE_PACKET_SEND	= TRUE,

	EVENT_PROCESS =
	{
		{ STATE_CHANGE_TYPE["SCT_FOOT_ON_LINE_FALSE_DOWN"],	"ANCIENT_NASOD_SENTRY_JUMP_DOWN",		},
		{ STATE_CHANGE_TYPE["SCT_MOTION_END"],				"ANCIENT_NASOD_SENTRY_WAIT",			},
	},
}
--------------------------------------------------------------------------
ANCIENT_NASOD_SENTRY_WAIT =
{
	ANIM_NAME					= "Wait",
	PLAY_TYPE					= XSKIN_ANIM_PLAYTYPE["XAP_LOOP"],
	TRANSITION					= TRUE,

	CAN_PUSH_UNIT				= TRUE,
	CAN_PASS_UNIT				= FALSE,

	SPEED_X						= 0,
	SPEED_Y						= 0,

	PASSIVE_SPEED_X				= 0,

	IMMADIATE_PACKET_SEND		= TRUE,
	EVENT_INTERVAL_TIME0		= 0,

	EVENT_PROCESS =
	{
		{ STATE_CHANGE_TYPE["SCT_FOOT_ON_LINE_FALSE_DOWN"],	"ANCIENT_NASOD_SENTRY_JUMP_DOWN",	},
		{ STATE_CHANGE_TYPE["SCT_CONDITION_TABLE"],	"ANCIENT_NASOD_SENTRY_WAIT_HABIT",	"CT_ANCIENT_NASOD_SENTRY_WAIT_HABIT",	},

		{ STATE_CHANGE_TYPE["SCT_CONDITION_TABLE"],	"ANCIENT_NASOD_SENTRY_ATTACKA",			"CT_ANCIENT_NASOD_SENTRY_ATTACKA",	},
		{ STATE_CHANGE_TYPE["SCT_CONDITION_TABLE"],	"ANCIENT_NASOD_SENTRY_ATTACKB",			"CT_ANCIENT_NASOD_SENTRY_ATTACKB",	},
		--{ STATE_CHANGE_TYPE["SCT_CONDITION_TABLE"],	"ANCIENT_NASOD_SENTRY_DASH_FOR_ATTACK",	"CT_ANCIENT_NASOD_SENTRY_DASH_FOR_ATTACK",	},
		{ STATE_CHANGE_TYPE["SCT_CONDITION_TABLE"],	"ANCIENT_NASOD_SENTRY_SPECIAL_ATTACK",	"CT_ANCIENT_NASOD_SENTRY_SPECIAL_ATTACK",	},
		
		{ STATE_CHANGE_TYPE["SCT_AI_WALK"],		"ANCIENT_NASOD_SENTRY_WALK",			},
		{ STATE_CHANGE_TYPE["SCT_AI_DASH"],		"ANCIENT_NASOD_SENTRY_DASH",			},
		{ STATE_CHANGE_TYPE["SCT_AI_JUMP"],		"ANCIENT_NASOD_SENTRY_JUMP_UP",			},
		{ STATE_CHANGE_TYPE["SCT_AI_JUMP_DIR"],	"ANCIENT_NASOD_SENTRY_JUMP_UP_DIR",		},
		{ STATE_CHANGE_TYPE["SCT_AI_DOWN"],		"ANCIENT_NASOD_SENTRY_JUMP_DOWN",		},
		{ STATE_CHANGE_TYPE["SCT_AI_DOWN_DIR"],	"ANCIENT_NASOD_SENTRY_JUMP_DOWN_DIR",	},
	},

	CT_ANCIENT_NASOD_SENTRY_WAIT_HABIT =
	{
		EVENT_INTERVAL_ID	= 0,
		HAVE_TARGET			= 0,
		RATE				= 30,
	},
	
	CT_ANCIENT_NASOD_SENTRY_ATTACKA =
	{
		EVENT_INTERVAL_ID		= 0,
		DISTANCE_TO_TARGET_NEAR	= 400,
		RATE					= 30,
	},
	
	CT_ANCIENT_NASOD_SENTRY_ATTACKB =
	{
		EVENT_INTERVAL_ID		= 0,
		DISTANCE_TO_TARGET_NEAR	= 500,
		RATE					= 30,
	},
	
	CT_ANCIENT_NASOD_SENTRY_SPECIAL_ATTACK =
	{
		EVENT_INTERVAL_ID		= 0,
		DISTANCE_TO_TARGET_NEAR	= 1000,
		RATE					= 30,
	},
	
	-- CT_ANCIENT_NASOD_SENTRY_DASH_FOR_ATTACK =
	-- {
		-- EVENT_INTERVAL_ID		= 0,
		-- DISTANCE_TO_TARGET_NEAR	= 800,
		-- RATE					= 30,
	-- }
}
--------------------------------------------------------------------------
ANCIENT_NASOD_SENTRY_WALK =
{
	ANIM_NAME	= "Walk",
	PLAY_TYPE	= XSKIN_ANIM_PLAYTYPE["XAP_LOOP"],
	TRANSITION	= TRUE,

	CAN_PUSH_UNIT	= TRUE,
	CAN_PASS_UNIT	= FALSE,

	PASSIVE_SPEED_X				= INIT_PHYSIC["WALK_SPEED"],

	ALLOW_DIR_CHANGE			= TRUE,
	IMMADIATE_PACKET_SEND		= TRUE,

	EVENT_INTERVAL_TIME0		= 2,
	EVENT_INTERVAL_TIME1		= 3,

	EVENT_PROCESS =
	{
		{ STATE_CHANGE_TYPE["SCT_FOOT_ON_LINE_FALSE_DOWN"],	"ANCIENT_NASOD_SENTRY_JUMP_DOWN",	},
		{ STATE_CHANGE_TYPE["SCT_CONDITION_TABLE"],	"ANCIENT_NASOD_SENTRY_WAIT_HABIT",	"CT_ANCIENT_NASOD_SENTRY_WAIT_HABIT",	},

		{ STATE_CHANGE_TYPE["SCT_CONDITION_TABLE"],	"ANCIENT_NASOD_SENTRY_ATTACKA",			"CT_ANCIENT_NASOD_SENTRY_ATTACKA",	},
		{ STATE_CHANGE_TYPE["SCT_CONDITION_TABLE"],	"ANCIENT_NASOD_SENTRY_ATTACKB",			"CT_ANCIENT_NASOD_SENTRY_ATTACKB",	},
		--{ STATE_CHANGE_TYPE["SCT_CONDITION_TABLE"],	"ANCIENT_NASOD_SENTRY_DASH_FOR_ATTACK",	"CT_ANCIENT_NASOD_SENTRY_DASH_FOR_ATTACK",	},
		{ STATE_CHANGE_TYPE["SCT_CONDITION_TABLE"],	"ANCIENT_NASOD_SENTRY_SPECIAL_ATTACK",	"CT_ANCIENT_NASOD_SENTRY_SPECIAL_ATTACK",	},
		
		{ STATE_CHANGE_TYPE["SCT_AI_WAIT"],		"ANCIENT_NASOD_SENTRY_WAIT",			},
		{ STATE_CHANGE_TYPE["SCT_AI_DASH"],		"ANCIENT_NASOD_SENTRY_DASH",			},
		{ STATE_CHANGE_TYPE["SCT_AI_JUMP"],		"ANCIENT_NASOD_SENTRY_JUMP_UP",			},
		{ STATE_CHANGE_TYPE["SCT_AI_JUMP_DIR"],	"ANCIENT_NASOD_SENTRY_JUMP_UP_DIR",		},
		{ STATE_CHANGE_TYPE["SCT_AI_DOWN"],		"ANCIENT_NASOD_SENTRY_JUMP_DOWN",		},
		{ STATE_CHANGE_TYPE["SCT_AI_DOWN_DIR"],	"ANCIENT_NASOD_SENTRY_JUMP_DOWN_DIR",	},
	},

	CT_ANCIENT_NASOD_SENTRY_WAIT_HABIT = 
	{
		EVENT_INTERVAL_ID	= 0,
		HAVE_TARGET			= 0,
		RATE				= 30,
	},
	
	CT_ANCIENT_NASOD_SENTRY_ATTACKA =
	{
		EVENT_INTERVAL_ID		= 0,
		DISTANCE_TO_TARGET_NEAR	= 400,
		RATE					= 30,
	},
	
	CT_ANCIENT_NASOD_SENTRY_ATTACKB =
	{
		EVENT_INTERVAL_ID		= 0,
		DISTANCE_TO_TARGET_NEAR	= 500,
		RATE					= 30,
	},
	
	CT_ANCIENT_NASOD_SENTRY_SPECIAL_ATTACK =
	{
		EVENT_INTERVAL_ID		= 0,
		DISTANCE_TO_TARGET_NEAR	= 1000,
		RATE					= 30,
	},
	
	-- CT_ANCIENT_NASOD_SENTRY_DASH_FOR_ATTACK =
	-- {
		-- EVENT_INTERVAL_ID		= 0,
		-- DISTANCE_TO_TARGET_NEAR	= 800,
		-- RATE					= 30,
	-- }
}
--------------------------------------------------------------------------
ANCIENT_NASOD_SENTRY_DASH =
{
	ANIM_NAME	= "Dash",
	PLAY_TYPE	= XSKIN_ANIM_PLAYTYPE["XAP_LOOP"],
	TRANSITION	= TRUE,

	CAN_PUSH_UNIT	= TRUE,
	CAN_PASS_UNIT	= FALSE,

	PASSIVE_SPEED_X		= INIT_PHYSIC["RUN_SPEED"],

	ALLOW_DIR_CHANGE		= TRUE,
	IMMADIATE_PACKET_SEND	= TRUE,

	EVENT_INTERVAL_TIME0	= 1,

	EVENT_PROCESS =
	{
		{ STATE_CHANGE_TYPE["SCT_FOOT_ON_LINE_FALSE_DOWN"],	"ANCIENT_NASOD_SENTRY_JUMP_DOWN_DIR",		},

		{ STATE_CHANGE_TYPE["SCT_CONDITION_TABLE"],			"ANCIENT_NASOD_SENTRY_DASH_ATTACK_READY",	"CT_ANCIENT_NASOD_SENTRY_DASH_ATTACK_READY",	},

		{ STATE_CHANGE_TYPE["SCT_AI_WAIT"],		"ANCIENT_NASOD_SENTRY_DASH_END",		},
		{ STATE_CHANGE_TYPE["SCT_AI_WALK"],		"ANCIENT_NASOD_SENTRY_WALK",			},
		{ STATE_CHANGE_TYPE["SCT_AI_JUMP"],		"ANCIENT_NASOD_SENTRY_JUMP_UP",		},
		{ STATE_CHANGE_TYPE["SCT_AI_JUMP_DIR"],	"ANCIENT_NASOD_SENTRY_JUMP_UP_DIR",	},
		{ STATE_CHANGE_TYPE["SCT_AI_DOWN"],		"ANCIENT_NASOD_SENTRY_JUMP_DOWN",		},
		{ STATE_CHANGE_TYPE["SCT_AI_DOWN_DIR"],	"ANCIENT_NASOD_SENTRY_JUMP_DOWN_DIR",	},
	},

	CT_ANCIENT_NASOD_SENTRY_DASH_ATTACK_READY =
	{
		EVENT_INTERVAL_ID			= 0,
		DISTANCE_TO_TARGET_NEAR		= 300,
		RATE						= 50,
	},
 }
  --------------------------------------------------------------------------
ANCIENT_NASOD_SENTRY_DASH_FOR_ATTACK =
{
	ANIM_NAME	= "Dash",
	PLAY_TYPE	= XSKIN_ANIM_PLAYTYPE["XAP_LOOP"],
	TRANSITION	= FALSE,

	CAN_PUSH_UNIT	= TRUE,
	CAN_PASS_UNIT	= FALSE,
	VIEW_TARGET		= TRUE,

	PASSIVE_SPEED_X		= INIT_PHYSIC["RUN_SPEED"],
	
	ALLOW_DIR_CHANGE		= FALSE,
	IMMADIATE_PACKET_SEND	= TRUE,

	EVENT_PROCESS =
	{
		{ STATE_CHANGE_TYPE["SCT_FOOT_ON_LINE_FALSE_DOWN"],	"ANCIENT_NASOD_SENTRY_JUMP_DOWN_DIR",		},
		{ STATE_CHANGE_TYPE["SCT_CONDITION_TABLE"],			"ANCIENT_NASOD_SENTRY_DASH_ATTACK_READY",	"CT_ANCIENT_NASOD_SENTRY_DASH_ATTACK_READY",	},
	},

	CT_ANCIENT_NASOD_SENTRY_DASH_ATTACK_READY =
	{
		ANIM_PLAY_COUNT	= 1,
	},
}
 --------------------------------------------------------------------------
ANCIENT_NASOD_SENTRY_DASH_END =
{
	ANIM_NAME					= "DashEnd",
	PLAY_TYPE					= XSKIN_ANIM_PLAYTYPE["XAP_ONE_WAIT"],
	TRANSITION					= FALSE,

	CAN_PUSH_UNIT				= FALSE,
	CAN_PASS_UNIT				= FALSE,

	SPEED_X						= INIT_PHYSIC["RUN_SPEED"],

	ALLOW_DIR_CHANGE			= FALSE,
	IMMADIATE_PACKET_SEND		= TRUE,

	EVENT_PROCESS =
	{
		{ STATE_CHANGE_TYPE["SCT_FOOT_ON_LINE_FALSE_DOWN"],	"ANCIENT_NASOD_SENTRY_JUMP_DOWN_DIR",	},
		{ STATE_CHANGE_TYPE["SCT_MOTION_END"],				"ANCIENT_NASOD_SENTRY_WAIT",			},
	},
}
--------------------------------------------------------------------------
ANCIENT_NASOD_SENTRY_JUMP_UP =
{
	ANIM_NAME		= "JumpUp",
	PLAY_TYPE		= XSKIN_ANIM_PLAYTYPE["XAP_LOOP"],
	TRANSITION		= TRUE,
	LAND_CONNECT	= FALSE,

	CAN_PUSH_UNIT	= TRUE,
	CAN_PASS_UNIT	= FALSE,

	SPEED_X		= 0,
	SPEED_Y		= INIT_PHYSIC["JUMP_SPEED"],
	ADD_POS_Y	= 45,

	IMMADIATE_PACKET_SEND	= TRUE,

	EVENT_PROCESS =
	{
		{ STATE_CHANGE_TYPE["SCT_NEGATIVE_Y_SPEED"],	"ANCIENT_NASOD_SENTRY_JUMP_DOWN",		},
	},
}
--------------------------------------------------------------------------
ANCIENT_NASOD_SENTRY_JUMP_DOWN =
{
	ANIM_NAME		= "JumpDown",
	PLAY_TYPE		= XSKIN_ANIM_PLAYTYPE["XAP_LOOP"],
	TRANSITION		= TRUE,
	LAND_CONNECT	= FALSE,

	CAN_PUSH_UNIT	= TRUE,
	CAN_PASS_UNIT	= FALSE,

	IMMADIATE_PACKET_SEND		= TRUE,

	EVENT_PROCESS =
	{
		{ STATE_CHANGE_TYPE["SCT_FOOT_ON_LINE_TRUE"],	"ANCIENT_NASOD_SENTRY_JUMP_LANDING",	},
	},
}
--------------------------------------------------------------------------
ANCIENT_NASOD_SENTRY_JUMP_UP_DIR =
{
	ANIM_NAME		= "JumpUp",
	PLAY_TYPE		= XSKIN_ANIM_PLAYTYPE["XAP_LOOP"],
	TRANSITION		= TRUE,
	LAND_CONNECT	= FALSE,

	CAN_PUSH_UNIT	= TRUE,
	CAN_PASS_UNIT	= FALSE,

	PASSIVE_SPEED_X	= INIT_PHYSIC["WALK_SPEED"],
	SPEED_Y			= INIT_PHYSIC["JUMP_SPEED"],

	ADD_POS_Y	= 45,

	IMMADIATE_PACKET_SEND	= TRUE,

	EVENT_PROCESS =
	{
		{ STATE_CHANGE_TYPE["SCT_NEGATIVE_Y_SPEED"],	"ANCIENT_NASOD_SENTRY_JUMP_DOWN_DIR",	},
	},
}
--------------------------------------------------------------------------
ANCIENT_NASOD_SENTRY_JUMP_DOWN_DIR =
{
	ANIM_NAME		= "JumpDown",
	PLAY_TYPE		= XSKIN_ANIM_PLAYTYPE["XAP_LOOP"],
	TRANSITION		= TRUE,
	LAND_CONNECT	= FALSE,

	CAN_PUSH_UNIT	= TRUE,
	CAN_PASS_UNIT	= FALSE,

	PASSIVE_SPEED_X	= INIT_PHYSIC["WALK_SPEED"],

	IMMADIATE_PACKET_SEND	= TRUE,

	EVENT_PROCESS =
	{
		{ STATE_CHANGE_TYPE["SCT_FOOT_ON_LINE_TRUE"],	"ANCIENT_NASOD_SENTRY_JUMP_LANDING",	},
	},
}
--------------------------------------------------------------------------
ANCIENT_NASOD_SENTRY_JUMP_LANDING =
{
	ANIM_NAME		= "JumpLanding",
	PLAY_TYPE		= XSKIN_ANIM_PLAYTYPE["XAP_ONE_WAIT"],
	TRANSITION		= TRUE,
	LAND_CONNECT	= FALSE,

	CAN_PUSH_UNIT	= TRUE,
	CAN_PASS_UNIT	= FALSE,

	SPEED_X		= 0,
	SPEED_Y		= 0,

	IMMADIATE_PACKET_SEND	= TRUE,

	SOUND_PLAY0 		= { 0.001, "Landing_Big_Meat02.ogg" },
	
	EVENT_PROCESS =
	{
		{ STATE_CHANGE_TYPE["SCT_FOOT_ON_LINE_FALSE_DOWN"],	"ANCIENT_NASOD_SENTRY_JUMP_DOWN",	},
		{ STATE_CHANGE_TYPE["SCT_MOTION_END"],				"ANCIENT_NASOD_SENTRY_WAIT",		},
	},
}
--------------------------------------------------------------------------
ANCIENT_NASOD_SENTRY_DAMAGE_REVENGE =
{
	ANIM_NAME		= "DamageRevenge",
	PLAY_TYPE		= XSKIN_ANIM_PLAYTYPE["XAP_ONE_WAIT"],
	TRANSITION		= TRUE,

	CAN_PUSH_UNIT	= TRUE,
	CAN_PASS_UNIT	= FALSE,

	IMMADIATE_PACKET_SEND	= TRUE,

	EVENT_PROCESS =
	{
		{ STATE_CHANGE_TYPE["SCT_FOOT_ON_LINE_FALSE_DOWN"],	"ANCIENT_NASOD_SENTRY_JUMP_DOWN",	},
		{ STATE_CHANGE_TYPE["SCT_MOTION_END"],				"ANCIENT_NASOD_SENTRY_WAIT",		},
	},
    --SOUND_PLAY0			= { 0.356, "AirShip_SwordMan_Slash2.ogg" },
}
--------------------------------------------------------------------------
ANCIENT_NASOD_SENTRY_ATTACKA =
{
	ANIM_NAME	= "AttackA",
	ANIM_SPEED 	= 0.7,
	PLAY_TYPE	= XSKIN_ANIM_PLAYTYPE["XAP_ONE_WAIT"],
	TRANSITION	= FALSE,

	CAN_PUSH_UNIT	= FALSE,
	CAN_PASS_UNIT	= FALSE,

    SOUND_PLAY0			= { 0.01, "Ancient_Nasod_Machine01.ogg" },
	SOUND_PLAY1			= { 0.90, "Ancient_Nasod_AttackA01.ogg" },
	
	SPEED_X		= 0,
	SPEED_Y		= 0,

	SUPER_ARMOR	= TRUE,
	VIEW_TARGET	= TRUE,

	IMMADIATE_PACKET_SEND	= TRUE,

	EVENT_PROCESS =
	{
		{ STATE_CHANGE_TYPE["SCT_FOOT_ON_LINE_FALSE_DOWN"],	"ANCIENT_NASOD_SENTRY_JUMP_DOWN",						},
		{ STATE_CHANGE_TYPE["SCT_MOTION_END"],				"ANCIENT_NASOD_SENTRY_WAIT",							},
	},
	
	DISABLE_ATTACK_BOX = 
	{
		"UpBody",
	},

	ENABLE_ATTACK_BOX = 
	{
		"ATTACK_SPHERE3_LHand01",
		"ATTACK_SPHERE3_RHand02",
		"ATTACK_SPHERE3_LHand03",
		"ATTACK_SPHERE3_RHand04",
	},
	
	ATTACK_TIME0	= { 0.950, 1.1, },

	DAMAGE_DATA =
	{
		DAMAGE_TYPE		= DAMAGE_TYPE["DT_PHYSIC"],
		HIT_TYPE		= HIT_TYPE["HT_PUNCH_HIT"],
		REACT_TYPE		= REACT_TYPE["RT_BIG_DAMAGE"],

		DAMAGE =
		{
			PHYSIC	= 1.0,
		},

		BACK_SPEED_X	= 1200,
		BACK_SPEED_Y	= 0.0,

		CAMERA_CRASH_GAP	= 5.0,
		CAMERA_CRASH_TIME	= 0.2,
		STOP_TIME_DEF 		= 0.5,
        CAN_REVENGE				= TRUE,
	},
}
--------------------------------------------------------------------------
ANCIENT_NASOD_SENTRY_ATTACKB =
{
	ANIM_NAME	= "AttackB",
	ANIM_SPEED	= 0.7,
	PLAY_TYPE	= XSKIN_ANIM_PLAYTYPE["XAP_ONE_WAIT"],
	TRANSITION	= FALSE,

	CAN_PUSH_UNIT	= TRUE,
	CAN_PASS_UNIT	= FALSE,
	
    SOUND_PLAY0			= { 0.65, "Ancient_Nasod_Machine02.ogg" },
	SOUND_PLAY1			= { 1.10, "Ancient_Nasod_AttackA02.ogg" },

	--SUPER_ARMOR	= TRUE,
	VIEW_TARGET	= TRUE,

	IMMADIATE_PACKET_SEND	= TRUE,

	EVENT_PROCESS =
	{
		{ STATE_CHANGE_TYPE["SCT_FOOT_ON_LINE_FALSE_DOWN"],	"ANCIENT_NASOD_SENTRY_JUMP_DOWN",	},
		{ STATE_CHANGE_TYPE["SCT_MOTION_END"],				"ANCIENT_NASOD_SENTRY_WAIT",		},
	},
	
	DISABLE_ATTACK_BOX = 
	{
		"UpBody",
	},

	-- ENABLE_ATTACK_BOX = 
	-- {
		-- "ATTACK_SPHERE3_LHand01",
		-- "ATTACK_SPHERE3_RHand02",
		-- "ATTACK_SPHERE3_LHand03",
		-- "ATTACK_SPHERE3_RHand04",
	-- },

	ATTACK_TIME0				= { 1.11, 1.20, },

	DAMAGE_DATA =
	{
		DAMAGE_TYPE		= DAMAGE_TYPE["DT_PHYSIC"],
		HIT_TYPE		= HIT_TYPE["HT_PUNCH_HIT"],
		REACT_TYPE		= REACT_TYPE["RT_UP"],

		DAMAGE =
		{
			PHYSIC		= 1.0,
		},

		BACK_SPEED_X			= 800,
		BACK_SPEED_Y			= 800,

		CAMERA_CRASH_GAP		= 5.0,
		CAMERA_CRASH_TIME		= 0.2,
        CAN_REVENGE				= TRUE,
	},
}
--------------------------------------------------------------------------
ANCIENT_NASOD_SENTRY_SPECIAL_ATTACK =
{
	ANIM_NAME	= "SpecialAttack",
	ANIM_SPEED	= 0.7,
	PLAY_TYPE	= XSKIN_ANIM_PLAYTYPE["XAP_ONE_WAIT"],
	TRANSITION	= TRUE,

	CAN_PUSH_UNIT	= TRUE,
	CAN_PASS_UNIT	= FALSE,
	
	SUPER_ARMOR	= TRUE,

    SOUND_PLAY0		= { 0.53, "Landing_Big_Metal01.ogg" },
	SOUND_PLAY1		= { 0.78, "Landing_Big_Metal02.ogg" },
	SOUND_PLAY2		= { 1.40, "Ancient_Nasod_Machine02.ogg" },
	SOUND_PLAY3		= { 1.85, "Ancient_Nasod_SpecialAttack.ogg" },

	SPEED_X		= 0,
	SPEED_Y		= 0,

	VIEW_TARGET				= TRUE,
	IMMADIATE_PACKET_SEND	= TRUE,
	
	REFLECT_MAGIC = { 1.8, 6, 0, },
	
	EFFECT_SET_LIST =
	{
		"Ancient_Nasod_Special_Attack", 0,
	},

	EVENT_PROCESS =
	{
		{ STATE_CHANGE_TYPE["SCT_FOOT_ON_LINE_FALSE_DOWN"],	"ANCIENT_NASOD_SENTRY_JUMP_DOWN",	},
		{ STATE_CHANGE_TYPE["SCT_MOTION_END"],				"ANCIENT_NASOD_SENTRY_WAIT",		},
	},
}
--------------------------------------------------------------------------
ANCIENT_NASOD_SENTRY_DASH_ATTACK_READY =
{
	ANIM_NAME	= "DashAttackReady",
	ANIM_SPEED	= 0.7,
	PLAY_TYPE	= XSKIN_ANIM_PLAYTYPE["XAP_ONE_WAIT"],
	TRANSITION	= TRUE,

	CAN_PUSH_UNIT	= TRUE,
	CAN_PASS_UNIT	= FALSE,

    SOUND_PLAY0		= { 0.55, "Ancient_Nasod_AttackA01.ogg" },
	
	SPEED_X		= 0,
	SPEED_Y		= 0,
	
	--SUPER_ARMOR				= TRUE,
	VIEW_TARGET				= TRUE,
	IMMADIATE_PACKET_SEND	= TRUE,

	EVENT_PROCESS =
	{
		{ STATE_CHANGE_TYPE["SCT_FOOT_ON_LINE_FALSE_DOWN"],	"ANCIENT_NASOD_SENTRY_JUMP_DOWN",		},
		{ STATE_CHANGE_TYPE["SCT_MOTION_END"],				"ANCIENT_NASOD_SENTRY_DASH_ATTACK",		},
	},
	
	DISABLE_ATTACK_BOX = 
	{
		"UpBody",
	},

	ENABLE_ATTACK_BOX = 
	{
		"ATTACK_SPHERE3_LHand01",
		"ATTACK_SPHERE3_RHand02",
		"ATTACK_SPHERE3_LHand03",
		"ATTACK_SPHERE3_RHand04",
	},
	
	ATTACK_TIME0			= { 0.504, 0.690 },
			
	DAMAGE_DATA = 
	{
		DAMAGE_TYPE		= DAMAGE_TYPE["DT_PHYSIC"],
		HIT_TYPE		= HIT_TYPE["HT_PUNCH_HIT"],
		REACT_TYPE		= REACT_TYPE["RT_BIG_DAMAGE"],
		
		DAMAGE = 
		{
			PHYSIC		= 0.7,
		},
				
		BACK_SPEED_X			= 1200,
		BACK_SPEED_Y			= 0,
		
		CAMERA_CRASH_GAP		= 5.0,	
		CAMERA_CRASH_TIME		= 0.2,
		
	},
}
--------------------------------------------------------------------------
ANCIENT_NASOD_SENTRY_DASH_ATTACK =
{
	ANIM_NAME	= "DashAttack",
	ANIM_SPEED	= 0.7,
	PLAY_TYPE	= XSKIN_ANIM_PLAYTYPE["XAP_ONE_WAIT"],
	TRANSITION	= TRUE,

	CAN_PUSH_UNIT	= FALSE,
	CAN_PASS_UNIT	= FALSE,

    SOUND_PLAY0	= { 0.10, "Ancient_NAsod_Death02.ogg" },
	SOUND_PLAY1	= { 0.80, "Landing_Stone01.ogg" },
	
	SPEED_X		= 0,
	SPEED_Y		= 0,
	
	PASSIVE_SPEED_X		= INIT_PHYSIC["RUN_SPEED"],
	
	SUPER_ARMOR	= TRUE,
	VIEW_TARGET	= FALSE,
	
	IMMADIATE_PACKET_SEND	= TRUE,

	EVENT_PROCESS =
	{
		{ STATE_CHANGE_TYPE["SCT_FOOT_ON_LINE_FALSE_DOWN"],	"ANCIENT_NASOD_SENTRY_JUMP_DOWN",		},
		{ STATE_CHANGE_TYPE["SCT_MOTION_END"],				"ANCIENT_NASOD_SENTRY_DASH_ATTACK_END",	},
	},
	
	-- ENABLE_ATTACK_BOX = 
	-- {
		-- "UpBody",
	-- },

	DISABLE_ATTACK_BOX = 
	{
		"LHand01",
		"RHand02",
		"LHand03",
		"RHand04",
	},
	
	ATTACK_TIME0				= { 0.85, 0.95, },

	DAMAGE_DATA =
	{
		DAMAGE_TYPE		= DAMAGE_TYPE["DT_PHYSIC"],
		HIT_TYPE		= HIT_TYPE["HT_PUNCH_HIT"],
		REACT_TYPE		= REACT_TYPE["RT_DOWN"],

		DAMAGE =
		{
			PHYSIC		= 1.0,
		},

		BACK_SPEED_X			= 0,
		BACK_SPEED_Y			= 0,
		
		CAMERA_CRASH_GAP		= 5.0,	
		CAMERA_CRASH_TIME		= 0.2,
		
		BUFF_FACTOR =
		{
			BUFF_TEMPLET_ID = BUFF_TEMPLET_ID["BTI_DEBUFF_PRESS"],
			RATE	=
			{
				1,
			},
			IGNORE_REGIST_FOR_RATE = FALSE,

			BEHAVIOR =
			{	
				COMBINATION = { BUFF_BEHAVIOR_TYPE["BBT_CHANGE_UNIT_SCALE"], BUFF_BEHAVIOR_TYPE["BBT_ATTACK_IMPOSSIBLE"], },
		
				BBT_CHANGE_UNIT_SCALE = 
				{
				},
				BBT_ATTACK_IMPOSSIBLE = 
				{
				},
			},
		
			FINALIZER =
			{
				COMBINATION = { BUFF_FINALIZER_TYPE["BFT_TIME"], },
			
				BFT_TIME =
				{
					BUFF_DURATION_TIME_TYPE = BUFF_DURATION_TIME_TYPE["BDTT_NORMAL_TIME"],
					NORMAL_TIME =
					{
						3,
					},
				},
			},
		},
	},
}
--------------------------------------------------------------------------
ANCIENT_NASOD_SENTRY_DASH_ATTACK_END =
{
	ANIM_NAME	= "DashAttackEnd",
	PLAY_TYPE	= XSKIN_ANIM_PLAYTYPE["XAP_ONE_WAIT"],
	TRANSITION	= TRUE,

	CAN_PUSH_UNIT	= FALSE,
	CAN_PASS_UNIT	= FALSE,

    SOUND_PLAY0			= { 0.10, "Ancient_Nasod_Death01.ogg" },
	
	SPEED_X		= 0,
	SPEED_Y		= 0,
	
	---SUPER_ARMOR	= TRUE,
	VIEW_TARGET				= TRUE,
	IMMADIATE_PACKET_SEND	= TRUE,

	EVENT_PROCESS =
	{
		{ STATE_CHANGE_TYPE["SCT_FOOT_ON_LINE_FALSE_DOWN"],	"ANCIENT_NASOD_SENTRY_JUMP_DOWN",	},
		{ STATE_CHANGE_TYPE["SCT_MOTION_END"],				"ANCIENT_NASOD_SENTRY_WAIT",		},
	},
}
--------------------------------------------------------------------------
ANCIENT_NASOD_SENTRY_DAMAGE_SMALL_LAND_FRONT =
{
	ANIM_NAME		= "DamageFront",
	PLAY_TYPE		= XSKIN_ANIM_PLAYTYPE["XAP_ONE_WAIT"],
	TRANSITION		= TRUE,
	LAND_CONNECT	= FALSE,

	SOUND_PLAY0		= { 0.001, "Ancient_Nasod_Growl01.ogg", 24 },
	
	CAN_PUSH_UNIT	= TRUE,
	CAN_PASS_UNIT	= FALSE,

	EVENT_PROCESS =
	{
		{ STATE_CHANGE_TYPE["SCT_MOTION_END"],	"ANCIENT_NASOD_SENTRY_WAIT",	},
	},
}
--------------------------------------------------------------------------
ANCIENT_NASOD_SENTRY_DAMAGE_SMALL_LAND_BACK =
{
	ANIM_NAME		= "DamageBack",
	PLAY_TYPE		= XSKIN_ANIM_PLAYTYPE["XAP_ONE_WAIT"],
	TRANSITION	= TRUE,
	LAND_CONNECT	= FALSE,

	CAN_PUSH_UNIT	= TRUE,
	CAN_PASS_UNIT	= FALSE,

	SOUND_PLAY0		= { 0.001, "Ancient_Nasod_Growl02.ogg", 24 },
	
	TALK_BOX =
	{
		{ RATE = 10, MESSAGE = STR_ID_1475 },
	},

	EVENT_PROCESS =
	{
		{ STATE_CHANGE_TYPE["SCT_MOTION_END"],	"ANCIENT_NASOD_SENTRY_WAIT",	},
	},
}
--------------------------------------------------------------------------
ANCIENT_NASOD_SENTRY_DAMAGE_BIG_LAND_FRONT =
{
	ANIM_NAME		= "DamageFront",
	PLAY_TYPE		= XSKIN_ANIM_PLAYTYPE["XAP_ONE_WAIT"],
	TRANSITION	= TRUE,
	LAND_CONNECT	= FALSE,

	CAN_PUSH_UNIT	= TRUE,
	CAN_PASS_UNIT	= FALSE,

	SOUND_PLAY0		= { 0.001, "Ancient_Nasod_Growl01.ogg", 24 },

	TALK_BOX =
	{
		{ RATE = 10, MESSAGE = STR_ID_1476 },
	},

	EVENT_PROCESS =
	{
		{ STATE_CHANGE_TYPE["SCT_MOTION_END"],	"ANCIENT_NASOD_SENTRY_WAIT",	},
	},
}
--------------------------------------------------------------------------
ANCIENT_NASOD_SENTRY_DAMAGE_BIG_LAND_BACK =
{
	ANIM_NAME		= "DamageBack",
	PLAY_TYPE		= XSKIN_ANIM_PLAYTYPE["XAP_ONE_WAIT"],
	TRANSITION		= TRUE,
	LAND_CONNECT	= FALSE,

	CAN_PUSH_UNIT	= TRUE,
	CAN_PASS_UNIT	= FALSE,

	SOUND_PLAY0		= { 0.001, "Ancient_Nasod_Growl02.ogg", 24 },

	TALK_BOX =
	{
		{ RATE = 10, MESSAGE = STR_ID_1476 },
	},

	EVENT_PROCESS =
	{
		{ STATE_CHANGE_TYPE["SCT_MOTION_END"],	"ANCIENT_NASOD_SENTRY_WAIT",	},
	},
}
--------------------------------------------------------------------------
ANCIENT_NASOD_SENTRY_DAMAGE_DOWN_FRONT =
{
	ANIM_NAME		= "DamageDownFront",
	PLAY_TYPE		= XSKIN_ANIM_PLAYTYPE["XAP_ONE_WAIT"],
	TRANSITION		= TRUE,
	LAND_CONNECT	= FALSE,

	SUPER_ARMOR	= TRUE,
	DEFENCE		= { 0, 100, 70, },

	CAN_PUSH_UNIT	= TRUE,
	CAN_PASS_UNIT	= FALSE,

	TALK_BOX =
	{
		{ RATE = 10, MESSAGE = STR_ID_2568 },
		{ RATE = 10, MESSAGE = STR_ID_2569 },
	},

	EVENT_PROCESS =
	{
		{ STATE_CHANGE_TYPE["SCT_FOOT_ON_LINE_FALSE_DOWN"],		"ANCIENT_NASOD_SENTRY_DAMAGE_AIR_FALL",	},
		{ STATE_CHANGE_TYPE["SCT_MOTION_END"],					"ANCIENT_NASOD_SENTRY_STAND_UP_FRONT",	},
	},
}
--------------------------------------------------------------------------
ANCIENT_NASOD_SENTRY_DAMAGE_DOWN_BACK =
{
	ANIM_NAME		= "DamageDownBack",
	PLAY_TYPE		= XSKIN_ANIM_PLAYTYPE["XAP_ONE_WAIT"],
	TRANSITION		= TRUE,
	LAND_CONNECT	= FALSE,

	SUPER_ARMOR	= TRUE,
	DEFENCE		= { 0, 100, 70, },

	CAN_PUSH_UNIT	= TRUE,
	CAN_PASS_UNIT	= FALSE,

	TALK_BOX =
	{
		{ RATE = 10, MESSAGE = STR_ID_2568 },
		{ RATE = 10, MESSAGE = STR_ID_2569 },
	},

	EVENT_PROCESS =
	{
		{ STATE_CHANGE_TYPE["SCT_FOOT_ON_LINE_FALSE_DOWN"],		"ANCIENT_NASOD_SENTRY_DAMAGE_AIR_FALL",	},
		{ STATE_CHANGE_TYPE["SCT_MOTION_END"],					"ANCIENT_NASOD_SENTRY_STAND_UP_BACK",	},
	},
}
--------------------------------------------------------------------------
ANCIENT_NASOD_SENTRY_DAMAGE_FLY_FRONT =
{
	ANIM_NAME		= "DamageAirFlyFront",
	PLAY_TYPE		= XSKIN_ANIM_PLAYTYPE["XAP_ONE_WAIT"],
	TRANSITION		= TRUE,
	LAND_CONNECT	= FALSE,

	CAN_PUSH_UNIT	= TRUE,
	CAN_PASS_UNIT	= FALSE,

	SOUND_PLAY0		= { 0.001, "Ancient_Nasod_Growl01.ogg", 24 },
	
	EVENT_PROCESS =
	{
		{ STATE_CHANGE_TYPE["SCT_FOOT_ON_LINE_TRUE"],	"ANCIENT_NASOD_SENTRY_DAMAGE_DOWN_FRONT",	},
	},
}
--------------------------------------------------------------------------
ANCIENT_NASOD_SENTRY_DAMAGE_FLY_BACK =
{
	ANIM_NAME		= "DamageAirFlyBack",
	PLAY_TYPE		= XSKIN_ANIM_PLAYTYPE["XAP_ONE_WAIT"],
	TRANSITION		= TRUE,
	LAND_CONNECT	= FALSE,

	CAN_PUSH_UNIT	= TRUE,
	CAN_PASS_UNIT	= FALSE,

	SOUND_PLAY0		= { 0.001, "Ancient_Nasod_Growl02.ogg", 24 },
	
	EVENT_PROCESS =
	{
		{ STATE_CHANGE_TYPE["SCT_FOOT_ON_LINE_TRUE"],	"ANCIENT_NASOD_SENTRY_DAMAGE_DOWN_BACK",	},
	},
}
--------------------------------------------------------------------------
ANCIENT_NASOD_SENTRY_DAMAGE_AIR =
{
	ANIM_NAME		= "DamageAirSmall",
	PLAY_TYPE		= XSKIN_ANIM_PLAYTYPE["XAP_ONE_WAIT"],
	TRANSITION		= TRUE,
	LAND_CONNECT	= FALSE,

	CAN_PUSH_UNIT	= TRUE,
	CAN_PASS_UNIT	= FALSE,

	SOUND_PLAY0		= { 0.001, "Ancient_Nasod_Growl01.ogg", 24 },
	
	EVENT_PROCESS =
	{
		{ STATE_CHANGE_TYPE["SCT_FOOT_ON_LINE_TRUE"],	"ANCIENT_NASOD_SENTRY_WAIT",	},
	},
}
--------------------------------------------------------------------------
ANCIENT_NASOD_SENTRY_DAMAGE_AIR_DOWN =
{
	ANIM_NAME		= "DamageAirDown",
	PLAY_TYPE		= XSKIN_ANIM_PLAYTYPE["XAP_ONE_WAIT"],
	TRANSITION		= TRUE,
	LAND_CONNECT	= FALSE,

	CAN_PUSH_UNIT	= TRUE,
	CAN_PASS_UNIT	= FALSE,

	EVENT_PROCESS =
	{
		{ STATE_CHANGE_TYPE["SCT_FOOT_ON_LINE_TRUE"],	"ANCIENT_NASOD_SENTRY_DAMAGE_AIR_DOWN_LANDING",	},
	},
}
--------------------------------------------------------------------------
ANCIENT_NASOD_SENTRY_DAMAGE_AIR_FALL =
{
	ANIM_NAME		= "DamageAirFall",
	PLAY_TYPE		= XSKIN_ANIM_PLAYTYPE["XAP_ONE_WAIT"],
	TRANSITION		= TRUE,
	LAND_CONNECT	= FALSE,

	CAN_PUSH_UNIT	= TRUE,
	CAN_PASS_UNIT	= FALSE,

	EVENT_PROCESS =
	{
		--{ STATE_CHANGE_TYPE["SCT_POSITIVE_Y_SPEED"],	"ANCIENT_NASOD_SENTRY_DAMAGE_AIR_UP",			},
		{ STATE_CHANGE_TYPE["SCT_FOOT_ON_LINE_TRUE"],	"ANCIENT_NASOD_SENTRY_DAMAGE_AIR_DOWN_LANDING",	},
	},
}
--------------------------------------------------------------------------
ANCIENT_NASOD_SENTRY_DAMAGE_AIR_DOWN_LANDING =
{
	ANIM_NAME		= "DamageAirDownlanding",
	PLAY_TYPE		= XSKIN_ANIM_PLAYTYPE["XAP_ONE_WAIT"],
	TRANSITION		= TRUE,
	LAND_CONNECT	= FALSE,

	SUPER_ARMOR	= TRUE,
	DEFENCE		= { 0, 100, 70, },

	CAN_PUSH_UNIT	= TRUE,
	CAN_PASS_UNIT	= FALSE,

	EVENT_PROCESS =
	{
		{ STATE_CHANGE_TYPE["SCT_FOOT_ON_LINE_FALSE_DOWN"],	"ANCIENT_NASOD_SENTRY_DAMAGE_AIR_FALL",	},
		{ STATE_CHANGE_TYPE["SCT_MOTION_END"],				"ANCIENT_NASOD_SENTRY_STAND_UP_FRONT",	},
	},
}
--------------------------------------------------------------------------
ANCIENT_NASOD_SENTRY_STAND_UP_FRONT =
{
	ANIM_NAME		= "DamageStandUpFront",
	PLAY_TYPE		= XSKIN_ANIM_PLAYTYPE["XAP_ONE_WAIT"],
	TRANSITION		= TRUE,
	LAND_CONNECT	= FALSE,

	SUPER_ARMOR	= TRUE,
	DEFENCE		= { 0, 100, 70, },

	CAN_PUSH_UNIT	= TRUE,
	CAN_PASS_UNIT	= FALSE,

	EVENT_PROCESS =
	{
		{ STATE_CHANGE_TYPE["SCT_FOOT_ON_LINE_FALSE_DOWN"],	"ANCIENT_NASOD_SENTRY_JUMP_DOWN",	},
		{ STATE_CHANGE_TYPE["SCT_MOTION_END"],				"ANCIENT_NASOD_SENTRY_WAIT",		},
	},
}
--------------------------------------------------------------------------
ANCIENT_NASOD_SENTRY_STAND_UP_BACK =
{
	ANIM_NAME		= "DamageStandUpBack",
	PLAY_TYPE		= XSKIN_ANIM_PLAYTYPE["XAP_ONE_WAIT"],
	TRANSITION		= TRUE,
	LAND_CONNECT	= FALSE,

	SUPER_ARMOR	= TRUE,
	DEFENCE		= { 0, 100, 70, },

	CAN_PUSH_UNIT	= TRUE,
	CAN_PASS_UNIT	= FALSE,

	EVENT_PROCESS =
	{
		{ STATE_CHANGE_TYPE["SCT_FOOT_ON_LINE_FALSE_DOWN"],	"ANCIENT_NASOD_SENTRY_JUMP_DOWN", },
		{ STATE_CHANGE_TYPE["SCT_MOTION_END"],				"ANCIENT_NASOD_SENTRY_WAIT",      },
	},
}
ANCIENT_NASOD_SENTRY_DYING_LAND_FRONT =
{
	ANIM_NAME		= "DamageDownFront",
	PLAY_TYPE		= XSKIN_ANIM_PLAYTYPE["XAP_ONE_WAIT"],
	TRANSITION		= TRUE,
	LAND_CONNECT	= FALSE,

	INVINCIBLE	= { 0, 100, },

	CAN_PUSH_UNIT			= TRUE,
	CAN_PASS_UNIT	= TRUE,

	DYING_END	= TRUE,

	IMMADIATE_PACKET_SEND	= TRUE,
}
--------------------------------------------------------------------------
ANCIENT_NASOD_SENTRY_DYING_LAND_BACK =
{
	ANIM_NAME		= "DamageDownBack",
	PLAY_TYPE		= XSKIN_ANIM_PLAYTYPE["XAP_ONE_WAIT"],
	TRANSITION		= TRUE,
	LAND_CONNECT	= FALSE,

	INVINCIBLE	= { 0, 100, },

	CAN_PUSH_UNIT			= TRUE,
	CAN_PASS_UNIT	= TRUE,

	DYING_END	= TRUE,

	IMMADIATE_PACKET_SEND	= TRUE,
}
--------------------------------------------------------------------------
ANCIENT_NASOD_SENTRY_DYING_SKY =
{
	ANIM_NAME		= "DamageAirDownlanding",
	PLAY_TYPE		= XSKIN_ANIM_PLAYTYPE["XAP_ONE_WAIT"],
	TRANSITION		= TRUE,
	LAND_CONNECT	= FALSE,

	INVINCIBLE	= { 0, 100, },

	CAN_PUSH_UNIT			= TRUE,
	CAN_PASS_UNIT	= TRUE,

	DYING_END	= TRUE,

	IMMADIATE_PACKET_SEND	= TRUE,
}
--------------------------------------------------------------------
function ANCIENT_NASOD_SENTRY_WALK_STATE_END( pKTDXApp, pX2Game, pNPCUnit )
	pMinorParticle = pX2Game:GetMinorParticle()
	pMinorParticle:GameUnitCreateSequence_LUA( pNPCUnit, "StepSmoke", pNPCUnit:GetLandPosition_LUA(), D3DXVECTOR2(100,100), D3DXVECTOR2(5,-1) )
end
--------------------------------------------------------------------------
function ANCIENT_NASOD_SENTRY_JUMP_DOWN_STATE_END( pKTDXApp, pX2Game, pNPCUnit )
	pMinorParticle = pX2Game:GetMinorParticle()
	pMinorParticle:GameUnitCreateSequence_LUA( pNPCUnit, "StepSmoke", pNPCUnit:GetLandPosition_LUA(), D3DXVECTOR2(100,100), D3DXVECTOR2(5,-1) )
end
--------------------------------------------------------------------------
function ANCIENT_NASOD_SENTRY_JUMP_DOWN_DIR_STATE_END( pKTDXApp, pX2Game, pNPCUnit )
	pMinorParticle = pX2Game:GetMinorParticle()
	pMinorParticle:GameUnitCreateSequence_LUA( pNPCUnit, "StepSmoke", pNPCUnit:GetLandPosition_LUA(), D3DXVECTOR2(100,100), D3DXVECTOR2(5,-1) )
end
--------------------------------------------------------------------------
function ANCIENT_NASOD_SENTRY_DAMAGE_SMALL_FRAME_MOVE( pKTDXApp, pX2Game, pNPCUnit )
	if pNPCUnit:AnimEventTimer_LUA( 0.047 ) then
		pMinorParticle = pX2Game:GetMinorParticle()
		pMinorParticle:GameUnitCreateSequence_LUA( pNPCUnit, "StepSmoke", pNPCUnit:GetLandPosition_LUA(), D3DXVECTOR2(100,100), D3DXVECTOR2(5,-1) )
	end
end
--------------------------------------------------------------------------
function ANCIENT_NASOD_SENTRY_DAMAGE_BIG_FRAME_MOVE( pKTDXApp, pX2Game, pNPCUnit )
	if pNPCUnit:AnimEventTimer_LUA( 0.06 ) then
		pMinorParticle = pX2Game:GetMinorParticle()
		pMinorParticle:GameUnitCreateSequence_LUA( pNPCUnit, "StepSmoke", pNPCUnit:GetLandPosition_LUA(), D3DXVECTOR2(100,100), D3DXVECTOR2(5,-1) )
	end
end
--------------------------------------------------------------------------
function ANCIENT_NASOD_SENTRY_DAMAGE_DOWN_FRONT_FRAME_MOVE( pKTDXApp, pX2Game, pNPCUnit )
	if pNPCUnit:AnimEventTimer_LUA( 0.41 ) then
		pNPCUnit:PlaySound_LUA( "Landing_Big_Metal01.ogg" )
		pMinorParticle = pX2Game:GetMinorParticle()
		pMinorParticle:GameUnitCreateSequence_LUA( pNPCUnit, "DownSmoke", pNPCUnit:GetLandPosition_LUA(), D3DXVECTOR2(100,100), D3DXVECTOR2(7,-1) )
	end
end
--------------------------------------------------------------------------
function ANCIENT_NASOD_SENTRY_DAMAGE_DOWN_BACK_FRAME_MOVE( pKTDXApp, pX2Game, pNPCUnit )
	if pNPCUnit:AnimEventTimer_LUA( 0.45 ) then
		pNPCUnit:PlaySound_LUA( "Landing_Big_Metal02.ogg" )
		pMinorParticle = pX2Game:GetMinorParticle()
		pMinorParticle:GameUnitCreateSequence_LUA( pNPCUnit, "DownSmoke", pNPCUnit:GetLandPosition_LUA(), D3DXVECTOR2(100,100), D3DXVECTOR2(7,-1) )
	end
end
--------------------------------------------------------------------------
function ANCIENT_NASOD_SENTRY_DAMAGE_AIR_DOWN_LANDING_FRAME_MOVE( pKTDXApp, pX2Game, pNPCUnit )
	if pNPCUnit:AnimEventTimer_LUA( 0.01 ) then
		pMinorParticle = pX2Game:GetMinorParticle()
		pos = pNPCUnit:GetLandPosition_LUA()
		pMinorParticle:GameUnitCreateSequence_LUA( pNPCUnit, "DownSmoke", pos, D3DXVECTOR2(100,100), D3DXVECTOR2(7,-1) )
		pos.y = pos.y + 5
		pMinorParticle:GameUnitCreateSequence_LUA( pNPCUnit, "GroundShockWave", pos, D3DXVECTOR2(100,100), D3DXVECTOR2(1,-1) )
		pParticle = pMinorParticle:GameUnitCreateSequence_LUA( pNPCUnit, "AirDownTick", pNPCUnit:GetPos(), D3DXVECTOR2(200,200), D3DXVECTOR2(10,-1) )
		if pParticle ~= nil then
			pParticle:SetLandPosition( pos.y - 5 )
		end

		if GetDistance_LUA( pNPCUnit:GetPos(), pX2Game:GetFocusUnitPos_LUA() ) < 500 then
			pX2Game:GetX2Camera():GetCamera():UpDownCrashCameraNoReset( 10.0, 0.1 )
		end

	elseif pNPCUnit:AnimEventTimer_LUA( 0.1 ) then
		pNPCUnit:PlaySound_LUA( "Landing_Big_Metal01.ogg" )
		pMinorParticle = pX2Game:GetMinorParticle()
		pMinorParticle:GameUnitCreateSequence_LUA( pNPCUnit, "DownSmoke", pNPCUnit:GetLandPosition_LUA(), D3DXVECTOR2(100,100), D3DXVECTOR2(7,-1) )
	end
end
--------------------------------------------------------------------------
function ANCIENT_NASOD_SENTRY_STAND_UP_ATTACK_FRONT_FRAME_MOVE( pKTDXApp, pX2Game, pNPCUnit )
	if pNPCUnit:AnimEventTimer_LUA( 0.35 ) then
		pMinorParticle = pX2Game:GetMinorParticle()
		pMinorParticle:GameUnitCreateSequence_LUA( pNPCUnit, "StepSmoke", pNPCUnit:GetLandPosition_LUA(), D3DXVECTOR2(100,100), D3DXVECTOR2(5,-1) )
	end
end
--------------------------------------------------------------------------
function ANCIENT_NASOD_SENTRY_STAND_UP_ATTACK_BACK_FRAME_MOVE( pKTDXApp, pX2Game, pNPCUnit )
	if pNPCUnit:AnimEventTimer_LUA( 0.35 ) then
		pMinorParticle = pX2Game:GetMinorParticle()
		pMinorParticle:GameUnitCreateSequence_LUA( pNPCUnit, "StepSmoke", pNPCUnit:GetLandPosition_LUA(), D3DXVECTOR2(100,100), D3DXVECTOR2(5,-1) )
	end
end
--------------------------------------------------------------------------
function ANCIENT_NASOD_SENTRY_DYING_LAND_STATE_START( pKTDXApp, pX2Game, pNPCUnit )
	pos = pNPCUnit:GetPos()
	pos.y = pos.y + 100.0
	GetMinorParticle = pX2Game:GetMinorParticle()

	pSeq = GetMinorParticle:GameUnitCreateSequence_LUA( pNPCUnit, "DieLight",		pos, D3DXVECTOR2(-1,-1), D3DXVECTOR2(3,-1) )

	if pSeq ~= nil then
		pSeq:SetLandPosition( pNPCUnit:GetLandPosition_LUA().y )
		pNPCUnit:SetDieSeq( pSeq:GetHandle() )
	end

	pNPCUnit:PlaySound_LUA( "DieLight.ogg" )
end