-- lua header. UTF-8 인코딩 인식을 위해 이 줄은 지우지 마세요.


BAT_KING_SMALL_ADD_POS_Y = 0

INIT_SYSTEM = 
{
	UNIT_WIDTH		= 80.0,
	UNIT_HEIGHT		= 150.0,
	UNIT_LAYER		= X2_LAYER["XL_UNIT_0"],
	UNIT_SCALE		= 0.4,
	
}


INIT_DEVICE = 
{
	READY_TEXTURE = 
	{
		"",
	},
	
	READY_SOUND = 
	{
		"BatBig_Small_Fly2.ogg",
		"BatBig_Small_Fly3.ogg",
		"BatBig_Small_Cry.ogg",
		"BatBig_Small_Win.ogg",
		"BatBig_Small_Sonar.ogg",

	},
}

INIT_MOTION = 
{
	MOTION_FILE_NAME	= "Motion_BatBig.x",
}

INIT_PHYSIC = 
{
	RELOAD_ACCEL		= 2000,
	G_ACCEL				= 4000,
	MAX_G_SPEED			= -2000,
	
	WALK_SPEED			= 500,
	RUN_SPEED			= 500,
	JUMP_SPEED			= 1500,
	DASH_JUMP_SPEED		= 2300,
}


INIT_COMPONENT = 
{
	MAX_HP				= 4000,
	MP_CHANGE_RATE		= 1,
	MP_CHARGE_RATE		= 130,
	
	USE_SLASH_TRACE		= FALSE,
	
	SHADOW_SIZE			= 200,
	SHADOW_FILE_NAME	= "shadow.dds",
	
	SMALL_HP_BAR_BLUE	= "Small_HP_bar_Blue.TGA",
	SMALL_HP_BAR_RED	= "Small_HP_bar_Red.TGA",
	SMALL_HP_BAR_YELLOW = "Small_HP_bar_Yellow.TGA",
	
	QUESTION_MARK_SEQ		= "QuestionMarkNPC",
	EXCLAMATION_MARK_SEQ	= "ExclamationMarkNPC",

	
	BOSS_GAGE_FACE_TEX			= "DLG_BossState.tga",
	BOSS_GAGE_FACE_TEX_PIECE	= "NUI_BAT_KING",
	BOSS_NAME_TEX				= "HQ_BOSS_NAME_BAT_KING.dds",
		
	
	HEAD_BONE_NAME			= "Bip01_Head",
	
	HYPER_MODE_COUNT	= 0,
	MAX_HYPER_MODE_TIME	= 30,
	
	HITTED_TYPE			= HITTED_TYPE["HTD_MEAT"],
	
	FALL_DOWN			= TRUE,
	
	--RAGE_COUNT_MAX		= 20,
	--RAGE_TIME_MAX		= 7,
	

	

}

INIT_STATE = 
{
	{ STATE_NAME = "BAT_KING_SMALL_START",						LUA_CAMERA_MOVE_FUNC = "BAT_KING_SMALL_START_CAMERA_MOVE",		},
	{ STATE_NAME = "BAT_KING_SMALL_START2",						},
	{ STATE_NAME = "BAT_KING_SMALL_WIN",						},
	{ STATE_NAME = "BAT_KING_SMALL_WAIT_ZERO2",					},
	{ STATE_NAME = "BAT_KING_SMALL_WAIT",						},

	{ STATE_NAME = "BAT_KING_SMALL_WALK",						},
	{ STATE_NAME = "BAT_KING_SMALL_JUMP_UP",					},
	{ STATE_NAME = "BAT_KING_SMALL_JUMP_DOWN",					LUA_STATE_END_FUNC = "BAT_KING_SMALL_JUMP_DOWN_STATE_END", },
	{ STATE_NAME = "BAT_KING_SMALL_JUMP_UP_DIR",				},
	{ STATE_NAME = "BAT_KING_SMALL_JUMP_DOWN_DIR",				LUA_STATE_END_FUNC = "BAT_KING_SMALL_JUMP_DOWN_DIR_STATE_END", },
	{ STATE_NAME = "BAT_KING_SMALL_JUMP_LANDING",				},

	{ STATE_NAME = "BAT_KING_SMALL_ATTACK_AIR_FRONT",			},
	{ STATE_NAME = "BAT_KING_SMALL_ATTACK_COMBO",				LUA_FRAME_MOVE_FUNC = "BAT_KING_SMALL_ATTACK_COMBO_FRAME_MOVE",		},
	{ STATE_NAME = "BAT_KING_SMALL_ATTACK_AIR",					LUA_FRAME_MOVE_FUNC = "BAT_KING_SMALL_ATTACK_AIR_FRAME_MOVE",		},
	
	
	--리액션 관련
	{ STATE_NAME = "BAT_KING_SMALL_DAMAGE_SMALL",				LUA_FRAME_MOVE_FUNC = "BAT_KING_SMALL_DAMAGE_SMALL_FRAME_MOVE",			},
	{ STATE_NAME = "BAT_KING_SMALL_DAMAGE_BIG",					LUA_FRAME_MOVE_FUNC = "BAT_KING_SMALL_DAMAGE_BIG_FRAME_MOVE",			},

	{ STATE_NAME = "BAT_KING_SMALL_DAMAGE_DOWN_FRONT",			LUA_FRAME_MOVE_FUNC = "BAT_KING_SMALL_DAMAGE_DOWN_FRONT_FRAME_MOVE"		},
	{ STATE_NAME = "BAT_KING_SMALL_DAMAGE_DOWN_BACK",			LUA_FRAME_MOVE_FUNC = "BAT_KING_SMALL_DAMAGE_DOWN_BACK_FRAME_MOVE"		},
	{ STATE_NAME = "BAT_KING_SMALL_DAMAGE_FLY_FRONT",			},
	{ STATE_NAME = "BAT_KING_SMALL_DAMAGE_FLY_BACK",			},
	{ STATE_NAME = "BAT_KING_SMALL_DAMAGE_AIR",					},
	{ STATE_NAME = "BAT_KING_SMALL_DAMAGE_AIR_DOWN",			},
	{ STATE_NAME = "BAT_KING_SMALL_DAMAGE_AIR_UP",				},
	{ STATE_NAME = "BAT_KING_SMALL_DAMAGE_AIR_FALL",			},
	{ STATE_NAME = "BAT_KING_SMALL_DAMAGE_AIR_DOWN_LANDING",	LUA_FRAME_MOVE_FUNC = "BAT_KING_SMALL_DAMAGE_AIR_DOWN_LANDING_FRAME_MOVE", },
	{ STATE_NAME = "BAT_KING_SMALL_DAMAGE_STAND_UP_BACK",		},
	{ STATE_NAME = "BAT_KING_SMALL_DAMAGE_STAND_UP_FRONT",		},
	{ STATE_NAME = "BAT_KING_SMALL_STAND_UP_ATTACK_FRONT",		LUA_FRAME_MOVE_FUNC = "BAT_KING_SMALL_STAND_UP_ATTACK_FRONT_FRAME_MOVE",	},
	{ STATE_NAME = "BAT_KING_SMALL_STAND_UP_ATTACK_BACK",		LUA_FRAME_MOVE_FUNC = "BAT_KING_SMALL_STAND_UP_ATTACK_BACK_FRAME_MOVE",	},
		
	
	{ STATE_NAME = "BAT_KING_SMALL_DYING_LAND_FRONT",			LUA_STATE_START_FUNC = "BAT_KING_SMALL_DYING_LAND_STATE_START", },
	{ STATE_NAME = "BAT_KING_SMALL_DYING_LAND_BACK",			LUA_STATE_START_FUNC = "BAT_KING_SMALL_DYING_LAND_STATE_START", },
	{ STATE_NAME = "BAT_KING_SMALL_DYING_SKY",					LUA_STATE_START_FUNC = "BAT_KING_SMALL_DYING_LAND_STATE_START", },

	
	
	START_STATE					= "BAT_KING_SMALL_START",
	WAIT_STATE					= "BAT_KING_SMALL_WAIT",
	
	SMALL_DAMAGE_LAND_FRONT		= "BAT_KING_SMALL_DAMAGE_SMALL",
	SMALL_DAMAGE_LAND_BACK		= "BAT_KING_SMALL_DAMAGE_SMALL",
	SMALL_DAMAGE_AIR			= "BAT_KING_SMALL_DAMAGE_AIR",
	BIG_DAMAGE_LAND_FRONT		= "BAT_KING_SMALL_DAMAGE_BIG",
	BIG_DAMAGE_LAND_BACK		= "BAT_KING_SMALL_DAMAGE_BIG",
	BIG_DAMAGE_AIR				= "BAT_KING_SMALL_DAMAGE_AIR",
	DOWN_DAMAGE_LAND_FRONT		= "BAT_KING_SMALL_DAMAGE_DOWN_FRONT",
	DOWN_DAMAGE_LAND_BACK		= "BAT_KING_SMALL_DAMAGE_DOWN_BACK",
	DOWN_DAMAGE_AIR				= "BAT_KING_SMALL_DAMAGE_AIR_DOWN",
	DOWN_DAMAGE_AIR_LANDING				= "BAT_KING_SMALL_DAMAGE_AIR_DOWN_LANDING",
	UP_DAMAGE					= "BAT_KING_SMALL_DAMAGE_AIR_UP",
	FLY_DAMAGE_FRONT			= "BAT_KING_SMALL_DAMAGE_FLY_FRONT",
	FLY_DAMAGE_BACK				= "BAT_KING_SMALL_DAMAGE_FLY_BACK",
	REVENGE_ATTACK				= "",
	DAMAGE_FLUSH_LAND_FRONT		= "BAT_KING_SMALL_DAMAGE_SMALL",
	DAMAGE_FLUSH_LAND_BACK		= "BAT_KING_SMALL_DAMAGE_SMALL",
	DAMAGE_FLUSH_AIR			= "BAT_KING_SMALL_DAMAGE_AIR",
	DAMAGE_REVENGE				= "BAT_KING_SMALL_DAMAGE_SMALL",
	
	DAMAGE_EXTRA_STATES         = {"BAT_KING_SMALL_DAMAGE_AIR_FALL","BAT_KING_SMALL_DAMAGE_STAND_UP_BACK","BAT_KING_SMALL_DAMAGE_STAND_UP_FRONT",
	"BAT_KING_SMALL_STAND_UP_ATTACK_FRONT","BAT_KING_SMALL_STAND_UP_ATTACK_BACK","BAT_KING_SMALL_JUMP_DOWN","BAT_KING_SMALL_JUMP_LANDING",},	
	
	DYING_LAND_FRONT			= "BAT_KING_SMALL_DYING_LAND_FRONT",
	DYING_LAND_BACK				= "BAT_KING_SMALL_DYING_LAND_BACK",
	DYING_SKY					= "BAT_KING_SMALL_DYING_SKY",
	
}


INIT_AI = 
{
	TARGET = 
	{
		TARGET_PRIORITY 			= TARGET_PRIORITY["TP_RANDOM"],
		TARGET_INTERVAL				= 3,		-- sec
		TARGET_NEAR_RANGE			= 250,		-- 이 거리보다 가까우면 TARGET_SUCCESS_RATE에 관계없이 무조건 타게팅된다
		TARGET_RANGE				= 800,		-- cm
		TARGET_LOST_RANGE			= 1500,		-- cm
		TARGET_SUCCESS_RATE			= 100,  --50,		-- %
		ATTACK_TARGET_RATE			= 100, -- 30,		-- 나를 공격한 유닛을 타게팅할 확률
		PRESERVE_LAST_TARGET_RATE	= 100, -- 50,		-- 이전에 타게팅된 유닛을 계속 타게팅할 확률
	},

	CHASE_MOVE = 
	{		
		DEST_GAP			= 120,	-- 목적지에서 이 거리 안에 있으면 도착했다고 판단한다
		MOVE_GAP			= 160,
		
		DIR_CHANGE_INTERVAL = 0.7,
		
		MOVE_SPLIT_RANGE	= 400,
		WALK_INTERVAL		= 1,
		NEAR_WALK_RATE		= 100,   --  70,
		FAR_WALK_RATE		= 100,   -- 30,
		
		JUMP_INTERVAL		= 10,
		UP_JUMP_RATE		= 100, -- 30,
		UP_DOWN_RATE		= 30,
		DOWN_JUMP_RATE		= 100,    --  30,
		DOWN_DOWN_RATE		= 30,
	},	
	
	PATROL_MOVE = 	
	{
		PATROL_BEGIN_RATE		= 100, --50,		
		PATROL_RANGE			= 300,
		PATROL_COOL_TIME		= 2,
		ONLY_THIS_LINE_GROUP	= TRUE,
	},
	
	ESCAPE_MOVE = 
	{		
		MOVE_SPLIT_RANGE	= 400,
		ESCAPE_GAP			= 600,	-- 이 거리 보다 멀면 도망 성공
		
		WALK_INTERVAL		= 1,
		NEAR_WALK_RATE		= 100,   --  70,
		FAR_WALK_RATE		= 100,   -- 30,
		
		JUMP_INTERVAL		= 10,
		UP_JUMP_RATE		= 100, -- 30,
		UP_DOWN_RATE		= 30,
		DOWN_JUMP_RATE		= 100,    --  30,
		DOWN_DOWN_RATE		= 30,
	},
	
	
}

BAT_KING_SMALL_WIN = 
{
	ANIM_NAME					= "Win",
	PLAY_TYPE					= XSKIN_ANIM_PLAYTYPE["XAP_ONE_WAIT"],
	TRANSITION					= TRUE,
	
	CAN_PUSH_UNIT				= TRUE,
	CAN_PASS_UNIT				= FALSE,	
	
	SPEED_X						= 0,
	SPEED_Y						= 0,
	
	INVINCIBLE					= { 0, 100, },

    SOUND_PLAY0		= { 0.164, "BatBig_Small_Fly2.ogg" },
    SOUND_PLAY1		= { 0.191, "BatBig_Small_Fly2.ogg" },
    SOUND_PLAY2		= { 0.623, "BatBig_Small_Fly2.ogg" },
    SOUND_PLAY3		= { 1.015, "BatBig_Small_Fly2.ogg" },
    SOUND_PLAY4		= { 1.406, "BatBig_Small_Fly2.ogg" },
    SOUND_PLAY5		= { 1.790, "BatBig_Small_Fly2.ogg" },
    SOUND_PLAY6		= { 2.188, "BatBig_Small_Fly2.ogg" },
    SOUND_PLAY7		= { 2.586, "BatBig_Small_Fly2.ogg" },
    SOUND_PLAY8		= { 2.664, "BatBig_Small_Cry.ogg" },
    SOUND_PLAY9		= { 2.992, "BatBig_Small_Fly2.ogg" },
	
	RIGHT						= TRUE,
	
	IMMADIATE_PACKET_SEND		= TRUE,
	
	TALK_BOX =
	{
		{ RATE = 50, MESSAGE = STR_ID_1511 },
 	},
}


BAT_KING_SMALL_START = 
{
	ANIM_NAME					= "WaitZero",
	PLAY_TYPE					= XSKIN_ANIM_PLAYTYPE["XAP_ONE_WAIT"],
	TRANSITION					= FALSE,
	LAND_CONNECT				= TRUE,
	
--	INVINCIBLE					= { 0, 100, },
	
	CAN_PUSH_UNIT				= FALSE,
	CAN_PASS_UNIT				= TRUE,
	NEVER_MOVE					= TRUE,

	IMMADIATE_PACKET_SEND		= TRUE,
	
	EVENT_INTERVAL_TIME0		= 2,
		
	EVENT_PROCESS = 
	{
		--{ STATE_CHANGE_TYPE["SCT_CONDITION_TABLE"],		"BAT_KING_SMALL_WAIT",	"CT_BAT_KING_SMALL_WAIT_ZERO_2" },
		--{ STATE_CHANGE_TYPE["SCT_CONDITION_TABLE"],		"BAT_KING_SMALL_WAIT_ZERO2",	"CT_BAT_KING_SMALL_WAIT_ZERO_2" },
		{ STATE_CHANGE_TYPE["SCT_MOTION_END"],				"BAT_KING_SMALL_START2",						},
	},
	
	CT_BAT_KING_SMALL_WAIT_ZERO_2 = 
	{
		EVENT_INTERVAL_ID			= 0,
		DISTANCE_TO_TARGET_NEAR		= 900,
		RATE						= 100,
	},	
}

BAT_KING_SMALL_START2 = 
{
	ANIM_NAME					= "WaitZero",
	PLAY_TYPE					= XSKIN_ANIM_PLAYTYPE["XAP_LOOP"],
	TRANSITION					= FALSE,
	LAND_CONNECT				= TRUE,
	
--	INVINCIBLE					= { 0, 100, },
	
	CAN_PUSH_UNIT				= FALSE,
	CAN_PASS_UNIT				= TRUE,
	NEVER_MOVE					= TRUE,

	IMMADIATE_PACKET_SEND		= TRUE,
	
	EVENT_INTERVAL_TIME0		= 2,
		
	EVENT_PROCESS = 
	{
		--{ STATE_CHANGE_TYPE["SCT_CONDITION_TABLE"],		"BAT_KING_SMALL_WAIT",	"CT_BAT_KING_SMALL_WAIT_ZERO_2" },
		{ STATE_CHANGE_TYPE["SCT_CONDITION_TABLE"],		"BAT_KING_SMALL_WAIT_ZERO2",	"CT_BAT_KING_SMALL_WAIT_ZERO_2" },
	},
	
	CT_BAT_KING_SMALL_WAIT_ZERO_2 = 
	{
		EVENT_INTERVAL_ID			= 0,
		DISTANCE_TO_TARGET_NEAR		= 1300,
		RATE						= 100,
	},	
}

BAT_KING_SMALL_WAIT_ZERO2 = 
{
	ANIM_NAME					= "WaitZero2",
	PLAY_TYPE					= XSKIN_ANIM_PLAYTYPE["XAP_ONE_WAIT"],
	TRANSITION					= FALSE,
	LAND_CONNECT				= FALSE,

	CAN_PUSH_UNIT				= TRUE,
	CAN_PASS_UNIT				= FALSE,

	IMMADIATE_PACKET_SEND		= TRUE,

    SOUND_PLAY0			= { 0.602, "BatBig_Small_Cry.ogg" , 20 },
    SOUND_PLAY1			= { 0.642, "BatBig_Small_Fly3.ogg" },

	EVENT_INTERVAL_TIME0		= 2,
	
	--SPEED_Y						= -INIT_PHYSIC["JUMP_SPEED"],
	ADD_POS_Y					= -45,
	
	G_ACCEL						= 2000,
	
	EVENT_PROCESS = 
	{
		{ STATE_CHANGE_TYPE["SCT_FOOT_ON_LINE_TRUE"],				"BAT_KING_SMALL_WAIT",						},
	},
	
	TALK_BOX =
	{
		EVENT_INTERVAL_ID			= 0,
		{ RATE = 7, MESSAGE = STR_ID_2570 },
	},
}

BAT_KING_SMALL_WAIT = 
{
	ANIM_NAME					= "Wait",
	PLAY_TYPE					= XSKIN_ANIM_PLAYTYPE["XAP_LOOP"],
	TRANSITION					= TRUE,
	
	
	CAN_PUSH_UNIT				= TRUE,
	CAN_PASS_UNIT				= FALSE,

	IMMADIATE_PACKET_SEND		= TRUE,
	
	EVENT_INTERVAL_TIME0		= 2,
	
	G_ACCEL						= 4000,
	ADD_POS_Y					= BAT_KING_SMALL_ADD_POS_Y,
	
	
	
	EVENT_PROCESS = 
	{
		{ STATE_CHANGE_TYPE["SCT_CONDITION_FUNCTION"],		"BAT_KING_SMALL_WIN",							"CF_BAT_KING_SMALL_WIN",	},
	
		{ STATE_CHANGE_TYPE["SCT_FOOT_ON_LINE_FALSE_DOWN"],	"BAT_KING_SMALL_JUMP_DOWN",							},
		
		{ STATE_CHANGE_TYPE["SCT_CONDITION_TABLE"],			"BAT_KING_SMALL_ATTACK_AIR_FRONT",			"CT_BAT_KING_SMALL_ATTACK_AIR_FRONT"		}, 
		{ STATE_CHANGE_TYPE["SCT_CONDITION_TABLE"],			"BAT_KING_SMALL_ATTACK_COMBO",				"CT_BAT_KING_SMALL_ATTACK_COMBO"		}, 

		{ STATE_CHANGE_TYPE["SCT_CONDITION_TABLE"],			"BAT_KING_SMALL_ATTACK_AIR",					"CT_BAT_KING_SMALL_ATTACK_AIR"		},
		
	

		{ STATE_CHANGE_TYPE["SCT_AI_WALK"],					"BAT_KING_SMALL_WALK",									},
		{ STATE_CHANGE_TYPE["SCT_AI_DASH"],					"BAT_KING_SMALL_WALK",									},
		{ STATE_CHANGE_TYPE["SCT_AI_JUMP"],					"BAT_KING_SMALL_JUMP_UP",								},
		{ STATE_CHANGE_TYPE["SCT_AI_JUMP_DIR"],				"BAT_KING_SMALL_JUMP_UP_DIR",							}, 
		{ STATE_CHANGE_TYPE["SCT_AI_DOWN"],					"BAT_KING_SMALL_JUMP_DOWN",							},
		{ STATE_CHANGE_TYPE["SCT_AI_DOWN_DIR"],				"BAT_KING_SMALL_JUMP_DOWN_DIR",						},
		
	},
	
	CT_BAT_KING_SMALL_ATTACK_AIR_FRONT = 
	{
		EVENT_INTERVAL_ID			= 0,
		DISTANCE_TO_TARGET_NEAR		= 400,
		RATE						= 30,
	},
	
	
	CT_BAT_KING_SMALL_ATTACK_COMBO = 
	{
		EVENT_INTERVAL_ID			= 0,
		DISTANCE_TO_TARGET_NEAR		= 300,
		RATE						= 30,
	},
	
		
	CT_BAT_KING_SMALL_ATTACK_AIR = 
	{
		EVENT_INTERVAL_ID			= 0,
		DISTANCE_TO_TARGET_NEAR		= 300,
		RATE						= 30,
	},
	
	
	TALK_BOX =
	{
		EVENT_INTERVAL_ID			= 0,
		{ RATE = 7, MESSAGE = STR_ID_2570 },
	},
}





BAT_KING_SMALL_WALK = 
{
	ANIM_NAME					= "Walk",
	PLAY_TYPE					= XSKIN_ANIM_PLAYTYPE["XAP_LOOP"],
	TRANSITION					= TRUE,
	
	CAN_PUSH_UNIT				= TRUE,
	CAN_PASS_UNIT				= FALSE,
	
	PASSIVE_SPEED_X				= INIT_PHYSIC["WALK_SPEED"],
	
	ALLOW_DIR_CHANGE			= TRUE,
	IMMADIATE_PACKET_SEND		= TRUE,
	
	EVENT_INTERVAL_TIME0		= 2,
	
	ADD_POS_Y					= BAT_KING_SMALL_ADD_POS_Y,
	
	EVENT_PROCESS = 
	{
		{ STATE_CHANGE_TYPE["SCT_CONDITION_FUNCTION"],		"BAT_KING_SMALL_WIN",							"CF_BAT_KING_SMALL_WIN",	},
	
		{ STATE_CHANGE_TYPE["SCT_FOOT_ON_LINE_FALSE_DOWN"],	"BAT_KING_SMALL_JUMP_DOWN",								},
		
		{ STATE_CHANGE_TYPE["SCT_CONDITION_TABLE"],			"BAT_KING_SMALL_ATTACK_AIR_FRONT",				"CT_BAT_KING_SMALL_ATTACK_AIR_FRONT",	},
		{ STATE_CHANGE_TYPE["SCT_CONDITION_TABLE"],			"BAT_KING_SMALL_ATTACK_COMBO",					"CT_BAT_KING_SMALL_ATTACK_COMBO"		}, 
		{ STATE_CHANGE_TYPE["SCT_CONDITION_TABLE"],			"BAT_KING_SMALL_ATTACK_AIR",						"CT_BAT_KING_SMALL_ATTACK_AIR"		},
				
		{ STATE_CHANGE_TYPE["SCT_AI_WAIT"],					"BAT_KING_SMALL_WAIT",										},
		{ STATE_CHANGE_TYPE["SCT_AI_JUMP"],					"BAT_KING_SMALL_JUMP_UP",									},
		{ STATE_CHANGE_TYPE["SCT_AI_JUMP_DIR"],				"BAT_KING_SMALL_JUMP_UP_DIR",								}, 
		{ STATE_CHANGE_TYPE["SCT_AI_DOWN"],					"BAT_KING_SMALL_JUMP_DOWN",								},
		{ STATE_CHANGE_TYPE["SCT_AI_DOWN_DIR"],				"BAT_KING_SMALL_JUMP_DOWN_DIR",							}, 
		
	},

	CT_BAT_KING_SMALL_ATTACK_AIR_FRONT = 
	{
		EVENT_INTERVAL_ID			= 0,
		DISTANCE_TO_TARGET_NEAR		= 400,
		RATE						= 30,
	},
	
	CT_BAT_KING_SMALL_ATTACK_COMBO = 
	{
		EVENT_INTERVAL_ID			= 0,
		DISTANCE_TO_TARGET_NEAR		= 400,
		RATE						= 30,
	},
	
	CT_BAT_KING_SMALL_ATTACK_AIR = 
	{
		EVENT_INTERVAL_ID			= 0,
		DISTANCE_TO_TARGET_NEAR		= 400,
		RATE						= 30,
	},
	
	
	
	TALK_BOX = 
	{
		EVENT_INTERVAL_ID			= 0,
		{ RATE = 5, MESSAGE = STR_ID_1501 },
	},
}


BAT_KING_SMALL_JUMP_UP = 
{
	ANIM_NAME					= "JumpUp",
	PLAY_TYPE					= XSKIN_ANIM_PLAYTYPE["XAP_LOOP"],
	TRANSITION					= TRUE,
	LAND_CONNECT				= FALSE,
	
	CAN_PUSH_UNIT				= TRUE,
	CAN_PASS_UNIT				= FALSE,
	
	SPEED_Y						= INIT_PHYSIC["JUMP_SPEED"],
	ADD_POS_Y					= 45 + BAT_KING_SMALL_ADD_POS_Y,
	
	IMMADIATE_PACKET_SEND		= TRUE,
	
	EVENT_PROCESS = 
	{
		{ STATE_CHANGE_TYPE["SCT_NEGATIVE_Y_SPEED"],		"BAT_KING_SMALL_JUMP_DOWN", },
	},
}

BAT_KING_SMALL_JUMP_DOWN = 
{
	ANIM_NAME					= "JumpDown",
	PLAY_TYPE					= XSKIN_ANIM_PLAYTYPE["XAP_LOOP"],
	TRANSITION					= TRUE,
	LAND_CONNECT				= FALSE,
	
	CAN_PUSH_UNIT				= TRUE,
	CAN_PASS_UNIT				= FALSE,
	
	ADD_POS_Y					= BAT_KING_SMALL_ADD_POS_Y,
	
	IMMADIATE_PACKET_SEND		= TRUE,		
		
	EVENT_PROCESS = 
	{
		{ STATE_CHANGE_TYPE["SCT_FOOT_ON_LINE_TRUE"],		"BAT_KING_SMALL_JUMP_LANDING", },
	},
}


BAT_KING_SMALL_JUMP_UP_DIR = 
{
	ANIM_NAME					= "JumpUp",
	PLAY_TYPE					= XSKIN_ANIM_PLAYTYPE["XAP_LOOP"],
	TRANSITION					= TRUE,
	LAND_CONNECT				= FALSE,
	
	CAN_PUSH_UNIT				= TRUE,
	CAN_PASS_UNIT				= FALSE,
	
	ADD_POS_Y					= 45 + BAT_KING_SMALL_ADD_POS_Y,
	
	

	
	IMMADIATE_PACKET_SEND		= TRUE,
	
	PASSIVE_SPEED_X				= INIT_PHYSIC["WALK_SPEED"],
	SPEED_Y						= INIT_PHYSIC["JUMP_SPEED"],
	
	EVENT_PROCESS = 
	{
		{ STATE_CHANGE_TYPE["SCT_NEGATIVE_Y_SPEED"],		"BAT_KING_SMALL_JUMP_DOWN_DIR", },
	},
}

BAT_KING_SMALL_JUMP_DOWN_DIR = 
{
	ANIM_NAME					= "JumpDown",
	PLAY_TYPE					= XSKIN_ANIM_PLAYTYPE["XAP_LOOP"],
	TRANSITION					= TRUE,
	LAND_CONNECT				= FALSE,
	
	CAN_PUSH_UNIT				= TRUE,
	CAN_PASS_UNIT				= FALSE,
	
	ADD_POS_Y					= BAT_KING_SMALL_ADD_POS_Y,
	
	PASSIVE_SPEED_X				= INIT_PHYSIC["WALK_SPEED"],
	
	IMMADIATE_PACKET_SEND		= TRUE,
			
	EVENT_PROCESS = 
	{
		{ STATE_CHANGE_TYPE["SCT_FOOT_ON_LINE_TRUE"],		"BAT_KING_SMALL_JUMP_LANDING", },
	},
}


BAT_KING_SMALL_JUMP_LANDING = 
{
	ANIM_NAME					= "Wait",
	PLAY_TYPE					= XSKIN_ANIM_PLAYTYPE["XAP_ONE_WAIT"],
	TRANSITION					= TRUE,
	LAND_CONNECT				= FALSE,
	
	CAN_PUSH_UNIT				= TRUE,
	CAN_PASS_UNIT				= FALSE,
	
	ADD_POS_Y					= BAT_KING_SMALL_ADD_POS_Y,
	
	SPEED_X						= 0,
	SPEED_Y						= 0,
		
	IMMADIATE_PACKET_SEND		= TRUE,

	EVENT_PROCESS = 
	{		
		{ STATE_CHANGE_TYPE["SCT_FOOT_ON_LINE_FALSE_DOWN"],	"BAT_KING_SMALL_JUMP_DOWN",				},
		{ STATE_CHANGE_TYPE["SCT_MOTION_END"],				"BAT_KING_SMALL_WAIT",						},
	},
}



BAT_KING_SMALL_ATTACK_AIR_FRONT = 
{
	ANIM_NAME					= "AttackAirFront",
	PLAY_TYPE					= XSKIN_ANIM_PLAYTYPE["XAP_ONE_WAIT"],
	TRANSITION					= FALSE,
	
	CAN_PUSH_UNIT				= TRUE,
	CAN_PASS_UNIT				= FALSE,
	
	ATTACK_TIME0				= { 1, 1.5, },
	
	
    SOUND_PLAY0			= { 0.220, "BatBig_Small_Cry.ogg" , 20 },
    SOUND_PLAY1			= { 1.003, "BatBig_Small_Fly2.ogg" },
    SOUND_PLAY2			= { 1.657, "BatBig_Small_Fly2.ogg" },
    SOUND_PLAY3			= { 2.146, "BatBig_Small_Fly2.ogg" },

	VIEW_TARGET					= TRUE,
	
	ANIM_SPEED   = 0.7,
	
	ADD_POS_Y					= BAT_KING_SMALL_ADD_POS_Y,
	
	TALK_BOX = 
	{
		{ RATE = 10, MESSAGE = STR_ID_1502 },
		{ RATE = 10, MESSAGE = STR_ID_1503 },
	},
	
	
	DISABLE_ATTACK_BOX = 
	{
		"Lfoot",
		"Rfoot",
	},
	
	EVENT_PROCESS = 
	{
--		{ STATE_CHANGE_TYPE["SCT_FOOT_ON_LINE_FALSE_DOWN"],	"BAT_KING_SMALL_JUMP_DOWN", },
		{ STATE_CHANGE_TYPE["SCT_MOTION_END"],				"BAT_KING_SMALL_WAIT", },
	},
	
	DAMAGE_DATA = 
	{
		DAMAGE_TYPE		= DAMAGE_TYPE["DT_PHYSIC"],
		HIT_TYPE		= HIT_TYPE["HT_PUNCH_HIT"],
		REACT_TYPE		= REACT_TYPE["RT_DOWN"],
		
		DAMAGE = 
		{
			PHYSIC		= 1.0,
			FIRE		= 0.0,
			ICE			= 0.0,
			EARTH		= 0.0,
			LIGHTNING	= 0.0,
			DARK		= 0.0,
			LIGHT		= 0.0,
			UNIVERSAL	= 0.0,
		},
		

		
		BACK_SPEED_X			= INIT_PHYSIC["RUN_SPEED"],
		BACK_SPEED_Y			= 0.0,
		
		STOP_TIME_ATT			= 0.0,		
		STOP_TIME_DEF			= 0.0,	
		CAMERA_CRASH_GAP		= 5.0,	
		CAMERA_CRASH_TIME		= 0.2,
		CLEAR_SCREEN			= 0.0,	
		CLEAR_SCREEN_COLOR_A	= 0.0,
		CLEAR_SCREEN_COLOR_R	= 1.0,
		CLEAR_SCREEN_COLOR_G	= 1.0,
		CLEAR_SCREEN_COLOR_B	= 1.0,

		RE_ATTACK				= FALSE,		
		HIT_GAP					= 0.0,				
	},

}


BAT_KING_SMALL_ATTACK_COMBO = 
{
	ANIM_NAME					= "AttackCombo",
	PLAY_TYPE					= XSKIN_ANIM_PLAYTYPE["XAP_ONE_WAIT"],
	TRANSITION					= FALSE,
	
	CAN_PUSH_UNIT				= TRUE,
	CAN_PASS_UNIT				= FALSE,
	
	ATTACK_TIME0				= { 0.35, 0.72, },
	ATTACK_TIME1				= { 0.99, 1.11, },
	ATTACK_TIME2				= { 2.00, 2.41, },
	
	
    SOUND_PLAY0			= { 0.542, "BatBig_Small_Fly3.ogg" },
    SOUND_PLAY1			= { 1.124, "BatBig_Small_Fly2.ogg" },
    SOUND_PLAY2			= { 1.870, "BatBig_Small_Fly3.ogg" },
    SOUND_PLAY3			= { 2.145, "BatBig_Small_Cry.ogg" },
    SOUND_PLAY4			= { 2.560, "BatBig_Small_Fly2.ogg" },

	VIEW_TARGET					= TRUE,
	
	ANIM_SPEED   = 0.7,
	
	ADD_POS_Y					= BAT_KING_SMALL_ADD_POS_Y,
	
	SPEED_X						= INIT_PHYSIC["WALK_SPEED"],
	
	TALK_BOX = 
	{
		{ RATE = 10, MESSAGE = STR_ID_1512 },
	},
	
	DISABLE_ATTACK_BOX = 
	{
		"Head",
		"Upbody",
		"Lowbody",
	},
	
	EVENT_PROCESS = 
	{
--		{ STATE_CHANGE_TYPE["SCT_FOOT_ON_LINE_FALSE_DOWN"],	"BAT_KING_SMALL_JUMP_DOWN", },
		{ STATE_CHANGE_TYPE["SCT_MOTION_END"],				"BAT_KING_SMALL_WAIT", },
	},
	
	DAMAGE_DATA = 
	{
		DAMAGE_TYPE		= DAMAGE_TYPE["DT_PHYSIC"],
		HIT_TYPE		= HIT_TYPE["HT_PUNCH_HIT"],
		REACT_TYPE		= REACT_TYPE["RT_BIG_DAMAGE"],
		
		DAMAGE = 
		{
			PHYSIC		= 1.0,
			FIRE		= 0.0,
			ICE			= 0.0,
			EARTH		= 0.0,
			LIGHTNING	= 0.0,
			DARK		= 0.0,
			LIGHT		= 0.0,
			UNIVERSAL	= 0.0,
		},
		
		BACK_SPEED_X			= 0.0,
		BACK_SPEED_Y			= 0.0,
		
		STOP_TIME_ATT			= 0.0,		
		STOP_TIME_DEF			= 0.0,	
		CAMERA_CRASH_GAP		= 5.0,	
		CAMERA_CRASH_TIME		= 0.2,
		CLEAR_SCREEN			= 0.0,	
		CLEAR_SCREEN_COLOR_A	= 0.0,
		CLEAR_SCREEN_COLOR_R	= 1.0,
		CLEAR_SCREEN_COLOR_G	= 1.0,
		CLEAR_SCREEN_COLOR_B	= 1.0,

		RE_ATTACK				= FALSE,		
		HIT_GAP					= 0.0,				
	},
	
	
	DAMAGE_DATA_LAST = 
	{
		DAMAGE_TYPE		= DAMAGE_TYPE["DT_PHYSIC"],
		HIT_TYPE		= HIT_TYPE["HT_PUNCH_HIT"],
		REACT_TYPE		= REACT_TYPE["RT_DOWN"],
		
		DAMAGE = 
		{
			PHYSIC		= 1.0,
			FIRE		= 0.0,
			ICE			= 0.0,
			EARTH		= 0.0,
			LIGHTNING	= 0.0,
			DARK		= 0.0,
			LIGHT		= 0.0,
			UNIVERSAL	= 0.0,
		},
		
		BACK_SPEED_X			= INIT_PHYSIC["WALK_SPEED"],
		BACK_SPEED_Y			= 0.0,
		
		STOP_TIME_ATT			= 0.0,		
		STOP_TIME_DEF			= 0.0,	
		CAMERA_CRASH_GAP		= 5.0,	
		CAMERA_CRASH_TIME		= 0.2,
		CLEAR_SCREEN			= 0.0,	
		CLEAR_SCREEN_COLOR_A	= 0.0,
		CLEAR_SCREEN_COLOR_R	= 1.0,
		CLEAR_SCREEN_COLOR_G	= 1.0,
		CLEAR_SCREEN_COLOR_B	= 1.0,

		RE_ATTACK				= FALSE,		
		HIT_GAP					= 0.0,				
	},

}


BAT_KING_SMALL_ATTACK_AIR = 
{
	ANIM_NAME					= "AttackAir",
	PLAY_TYPE					= XSKIN_ANIM_PLAYTYPE["XAP_ONE_WAIT"],
	TRANSITION					= FALSE,
	
	CAN_PUSH_UNIT				= TRUE,
	CAN_PASS_UNIT				= TRUE,
	
	ATTACK_TIME0				= { 1.8, 2.5, },
	ATTACK_TIME1				= { 3.9, 4.65, },
	ATTACK_TIME2				= { 5.97, 6.85, },
	
	
    SOUND_PLAY0			= { 0.471, "BatBig_Small_Fly2.ogg" },
    SOUND_PLAY1			= { 1.121, "BatBig_Small_Fly2.ogg" },
    SOUND_PLAY2			= { 1.187, "BatBig_Small_Cry.ogg" },
    SOUND_PLAY3			= { 1.810, "BatBig_Small_Fly2.ogg" },
    SOUND_PLAY4			= { 2.468, "BatBig_Small_Fly2.ogg" },
    SOUND_PLAY5			= { 3.140, "BatBig_Small_Fly2.ogg" },
    SOUND_PLAY6			= { 3.910, "BatBig_Small_Fly2.ogg" },
    SOUND_PLAY7			= { 4.573, "BatBig_Small_Fly2.ogg" },
    SOUND_PLAY8			= { 5.223, "BatBig_Small_Fly2.ogg" },
    SOUND_PLAY9			= { 5.824, "BatBig_Small_Cry.ogg" },
    SOUND_PLAY10		= { 5.971, "BatBig_Small_Cry.ogg" },
    SOUND_PLAY11		= { 6.301, "BatBig_Small_Fly2.ogg" },
    SOUND_PLAY12		= { 6.770, "BatBig_Small_Fly2.ogg" },
    SOUND_PLAY13		= { 7.487, "BatBig_Small_Fly2.ogg" },

	
	VIEW_TARGET					= TRUE,
	
	ANIM_SPEED   = 0.7,
	
	ADD_POS_Y					= BAT_KING_SMALL_ADD_POS_Y,
	
	TALK_BOX = 
	{
		{ RATE = 10, MESSAGE = STR_ID_1502 },
		{ RATE = 10, MESSAGE = STR_ID_1503 },
	},
	
	DISABLE_ATTACK_BOX = 
	{
		"Lfoot",
		"Rfoot",
	},
	
	EVENT_PROCESS = 
	{
--		{ STATE_CHANGE_TYPE["SCT_FOOT_ON_LINE_FALSE_DOWN"],	"BAT_KING_SMALL_JUMP_DOWN", },
		{ STATE_CHANGE_TYPE["SCT_MOTION_END"],				"BAT_KING_SMALL_WAIT", },
	},
	
	DAMAGE_DATA = 
	{
		DAMAGE_TYPE		= DAMAGE_TYPE["DT_PHYSIC"],
		HIT_TYPE		= HIT_TYPE["HT_PUNCH_HIT"],
		REACT_TYPE		= REACT_TYPE["RT_DOWN"],
		
		DAMAGE = 
		{
			PHYSIC		= 1.0,
			FIRE		= 0.0,
			ICE			= 0.0,
			EARTH		= 0.0,
			LIGHTNING	= 0.0,
			DARK		= 0.0,
			LIGHT		= 0.0,
			UNIVERSAL	= 0.0,
		},
		
		BACK_SPEED_X			= INIT_PHYSIC["RUN_SPEED"],
		BACK_SPEED_Y			= 0.0,
		
		STOP_TIME_ATT			= 0.0,		
		STOP_TIME_DEF			= 0.0,	
		CAMERA_CRASH_GAP		= 5.0,	
		CAMERA_CRASH_TIME		= 0.2,
		CLEAR_SCREEN			= 0.0,	
		CLEAR_SCREEN_COLOR_A	= 0.0,
		CLEAR_SCREEN_COLOR_R	= 1.0,
		CLEAR_SCREEN_COLOR_G	= 1.0,
		CLEAR_SCREEN_COLOR_B	= 1.0,

		RE_ATTACK				= FALSE,		
		HIT_GAP					= 0.0,				
	},

}








BAT_KING_SMALL_DAMAGE_SMALL = 
{
	ANIM_NAME					= "DamageSmall",
	PLAY_TYPE					= XSKIN_ANIM_PLAYTYPE["XAP_ONE_WAIT"],
	TRANSITION					= FALSE,
	LAND_CONNECT				= FALSE,
	
	CAN_PUSH_UNIT				= TRUE,
	CAN_PASS_UNIT				= FALSE,

	ADD_POS_Y					= BAT_KING_SMALL_ADD_POS_Y,
	G_ACCEL						= 4000,
	
	EVENT_PROCESS = 
	{
		{ STATE_CHANGE_TYPE["SCT_MOTION_END"],				"BAT_KING_SMALL_WAIT", },
	},
	TALK_BOX =
	{
		{ RATE = 10, MESSAGE = STR_ID_2568 },
		{ RATE = 10, MESSAGE = STR_ID_1506 },
	},
}

BAT_KING_SMALL_DAMAGE_BIG = 
{
	ANIM_NAME					= "DamageBig",
	PLAY_TYPE					= XSKIN_ANIM_PLAYTYPE["XAP_ONE_WAIT"],
	TRANSITION					= FALSE,
	LAND_CONNECT				= FALSE,
	
	CAN_PUSH_UNIT				= TRUE,
	CAN_PASS_UNIT				= FALSE,

	ADD_POS_Y					= BAT_KING_SMALL_ADD_POS_Y,
	G_ACCEL						= 4000,
	
	EVENT_PROCESS = 
	{
		{ STATE_CHANGE_TYPE["SCT_MOTION_END"],				"BAT_KING_SMALL_WAIT", },
	},
	TALK_BOX =
	{
		{ RATE = 10, MESSAGE = STR_ID_2568 },
		{ RATE = 10, MESSAGE = STR_ID_1506 },
	},
}

BAT_KING_SMALL_DAMAGE_FLY_FRONT = 
{
	ANIM_NAME					= "DamageAirFall",
	PLAY_TYPE					= XSKIN_ANIM_PLAYTYPE["XAP_ONE_WAIT"],
	TRANSITION					= FALSE,
	LAND_CONNECT				= FALSE,
	
	ADD_ROTATE_Z				= -45.0,	
		
	
	CAN_PUSH_UNIT				= TRUE,
	CAN_PASS_UNIT				= FALSE,
	
	ADD_POS_Y					= BAT_KING_SMALL_ADD_POS_Y,
	G_ACCEL						= 4000,
	
	EVENT_PROCESS = 
	{
		{ STATE_CHANGE_TYPE["SCT_FOOT_ON_LINE_TRUE"],			"BAT_KING_SMALL_DAMAGE_AIR_DOWN_LANDING",		},
	},

	TALK_BOX =
	{
		{ RATE = 10, MESSAGE = STR_ID_1507 },
  	},
}



BAT_KING_SMALL_DAMAGE_FLY_BACK = 
{
	ANIM_NAME					= "DamageAirUp",
	PLAY_TYPE					= XSKIN_ANIM_PLAYTYPE["XAP_ONE_WAIT"],
	TRANSITION					= FALSE,
	LAND_CONNECT				= FALSE,	
	
	CAN_PUSH_UNIT				= TRUE,
	CAN_PASS_UNIT				= FALSE,
	
	ADD_POS_Y					= BAT_KING_SMALL_ADD_POS_Y,
	G_ACCEL						= 4000,
	
	EVENT_PROCESS = 
	{
		{ STATE_CHANGE_TYPE["SCT_FOOT_ON_LINE_TRUE"],			"BAT_KING_SMALL_DAMAGE_DOWN_BACK",		},
	},

	TALK_BOX =
	{
		{ RATE = 10, MESSAGE = STR_ID_1507 },
  	},
}

BAT_KING_SMALL_DAMAGE_AIR = 
{
	ANIM_NAME					= "DamageAirDownLanding",
	PLAY_TYPE					= XSKIN_ANIM_PLAYTYPE["XAP_ONE_WAIT"],
	TRANSITION					= FALSE,
	LAND_CONNECT				= FALSE,
	
	CAN_PUSH_UNIT				= TRUE,
	CAN_PASS_UNIT				= FALSE,

	
	ADD_POS_Y					= BAT_KING_SMALL_ADD_POS_Y,
	G_ACCEL						= 4000,
	
	EVENT_PROCESS = 
	{
		{ STATE_CHANGE_TYPE["SCT_FOOT_ON_LINE_TRUE"],	"BAT_KING_SMALL_WAIT", },
	},
}

BAT_KING_SMALL_DAMAGE_AIR_DOWN = 
{
	ANIM_NAME					= "DamageAirDown",
	PLAY_TYPE					= XSKIN_ANIM_PLAYTYPE["XAP_ONE_WAIT"],
	TRANSITION					= FALSE,
	LAND_CONNECT				= FALSE,
	
	CAN_PUSH_UNIT				= TRUE,
	CAN_PASS_UNIT				= FALSE,

    SOUND_PLAY0			= { 0.100, "BatBig_Small_Cry.ogg" , 20 },

	ADD_POS_Y					= BAT_KING_SMALL_ADD_POS_Y,
	G_ACCEL						= 4000,
	
	EVENT_PROCESS = 
	{
		{ STATE_CHANGE_TYPE["SCT_FOOT_ON_LINE_TRUE"],			"BAT_KING_SMALL_DAMAGE_AIR_DOWN_LANDING",	},
	},
}

BAT_KING_SMALL_DAMAGE_AIR_UP = 
{
	ANIM_NAME					= "DamageAirUp",
	PLAY_TYPE					= XSKIN_ANIM_PLAYTYPE["XAP_ONE_WAIT"],
	TRANSITION					= FALSE,
	LAND_CONNECT				= FALSE,
	
	CAN_PUSH_UNIT				= TRUE,
	CAN_PASS_UNIT				= FALSE,
	
	ADD_POS_Y					= BAT_KING_SMALL_ADD_POS_Y,
	G_ACCEL						= 4000,
	
	EVENT_PROCESS = 
	{
		{ STATE_CHANGE_TYPE["SCT_NEGATIVE_Y_SPEED"],		"BAT_KING_SMALL_DAMAGE_AIR_FALL", },	
		{ STATE_CHANGE_TYPE["SCT_FOOT_ON_LINE_TRUE"],		"BAT_KING_SMALL_DAMAGE_AIR_DOWN_LANDING", },	
	},
}

BAT_KING_SMALL_DAMAGE_AIR_FALL = 
{
	ANIM_NAME					= "DamageAirFall",
	PLAY_TYPE					= XSKIN_ANIM_PLAYTYPE["XAP_ONE_WAIT"],
	TRANSITION					= FALSE,
	LAND_CONNECT				= FALSE,
	
	CAN_PUSH_UNIT				= TRUE,
	CAN_PASS_UNIT				= FALSE,
	G_ACCEL						= 4000,
	
	EVENT_PROCESS = 
	{
		{ STATE_CHANGE_TYPE["SCT_POSITIVE_Y_SPEED"],		"BAT_KING_SMALL_DAMAGE_AIR_UP", },
		{ STATE_CHANGE_TYPE["SCT_FOOT_ON_LINE_TRUE"],		"BAT_KING_SMALL_DAMAGE_AIR_DOWN_LANDING", },
	},
}

BAT_KING_SMALL_DAMAGE_DOWN_FRONT = 
{
	ANIM_NAME					= "DamageDownFront",
	PLAY_TYPE					= XSKIN_ANIM_PLAYTYPE["XAP_ONE_WAIT"],
	TRANSITION					= FALSE,
	LAND_CONNECT				= FALSE,

	SUPER_ARMOR					= TRUE,
	DEFENCE						= { 0, 100, 70, },
	
	CAN_PUSH_UNIT				= TRUE,
	CAN_PASS_UNIT				= FALSE,

    SOUND_PLAY0			= { 0.030, "BatBig_Small_Cry.ogg" , 20 },

	EVENT_PROCESS = 
	{
		{ STATE_CHANGE_TYPE["SCT_FOOT_ON_LINE_FALSE_DOWN"],		"BAT_KING_SMALL_DAMAGE_AIR_FALL",			},
		{ STATE_CHANGE_TYPE["SCT_CONDITION_TABLE"],				"BAT_KING_SMALL_STAND_UP_ATTACK_FRONT",	"CT_BAT_KING_SMALL_STAND_UP_ATTACK_FRONT", },
		{ STATE_CHANGE_TYPE["SCT_MOTION_END"],				"BAT_KING_SMALL_DAMAGE_STAND_UP_FRONT", },

	},
	
	CT_BAT_KING_SMALL_STAND_UP_ATTACK_FRONT = 
	{
		ANIM_PLAY_COUNT		= 1,
		RATE				= 20,
	},
	
	
	TALK_BOX =
 	{
		{ RATE = 10, MESSAGE = STR_ID_1449 },
	},
}

BAT_KING_SMALL_DAMAGE_DOWN_BACK = 
{
	ANIM_NAME					= "DamageDownBack",
	PLAY_TYPE					= XSKIN_ANIM_PLAYTYPE["XAP_ONE_WAIT"],
	TRANSITION					= FALSE,
	LAND_CONNECT				= FALSE,
	
	SUPER_ARMOR					= TRUE,
	DEFENCE						= { 0, 100, 70, },
	
	CAN_PUSH_UNIT				= TRUE,
	CAN_PASS_UNIT				= FALSE,

    SOUND_PLAY0			= { 0.030, "BatBig_Small_Cry.ogg" , 20 },

	EVENT_PROCESS = 
	{
		{ STATE_CHANGE_TYPE["SCT_FOOT_ON_LINE_FALSE_DOWN"],		"BAT_KING_SMALL_DAMAGE_AIR_FALL",			},
		{ STATE_CHANGE_TYPE["SCT_CONDITION_TABLE"],				"BAT_KING_SMALL_STAND_UP_ATTACK_BACK",	"CT_BAT_KING_SMALL_STAND_UP_ATTACK_BACK", },
		{ STATE_CHANGE_TYPE["SCT_MOTION_END"],					"BAT_KING_SMALL_DAMAGE_STAND_UP_BACK",	},
	},
	
	CT_BAT_KING_SMALL_STAND_UP_ATTACK_BACK = 
	{
		ANIM_PLAY_COUNT		= 1,
		RATE				= 20,
	},
	
	TALK_BOX =
 	{
		{ RATE = 10, MESSAGE = STR_ID_1449 },
	},
}

BAT_KING_SMALL_DAMAGE_AIR_DOWN_LANDING = 
{
	ANIM_NAME					= "DamageAirDownLanding",
	PLAY_TYPE					= XSKIN_ANIM_PLAYTYPE["XAP_ONE_WAIT"],
	TRANSITION					= FALSE,
	LAND_CONNECT				= FALSE,
	
	SUPER_ARMOR					= TRUE,
	DEFENCE						= { 0, 100, 70, },
	
	CAN_PUSH_UNIT				= TRUE,
	CAN_PASS_UNIT				= FALSE,
	
	EVENT_PROCESS = 
	{
		{ STATE_CHANGE_TYPE["SCT_FOOT_ON_LINE_FALSE_DOWN"],	"BAT_KING_SMALL_DAMAGE_AIR_FALL", },
		{ STATE_CHANGE_TYPE["SCT_CONDITION_TABLE"],				"BAT_KING_SMALL_STAND_UP_ATTACK_FRONT",	"CT_BAT_KING_SMALL_STAND_UP_ATTACK_FRONT", },
		{ STATE_CHANGE_TYPE["SCT_MOTION_END"],				"BAT_KING_SMALL_DAMAGE_STAND_UP_FRONT", },
	},
	
	CT_BAT_KING_SMALL_STAND_UP_ATTACK_FRONT = 
	{
		ANIM_PLAY_COUNT		= 1,
		RATE				= 20,
	},
}

BAT_KING_SMALL_STAND_UP_ATTACK_FRONT = 
{
	ANIM_NAME					= "StandUpAttackFront",
	PLAY_TYPE					= XSKIN_ANIM_PLAYTYPE["XAP_ONE_WAIT"],
	TRANSITION					= FALSE,
	LAND_CONNECT				= FALSE,	
	
	ANIM_WAIT_TIME				= 1,

	MIND_FLAG					= MIND_FLAG["MF_STAND_UP_ATTACK"],
	
	SUPER_ARMOR					= TRUE,
	DEFENCE						= { 0, 100, 70, },
	
	CAN_PUSH_UNIT				= TRUE,
	CAN_PASS_UNIT				= FALSE,
	
	EVENT_PROCESS = 
	{
		--{ STATE_CHANGE_TYPE["SCT_FOOT_ON_LINE_FALSE_DOWN"],	"BAT_KING_SMALL_JUMP_DOWN",			},
		{ STATE_CHANGE_TYPE["SCT_MOTION_END"],				"BAT_KING_SMALL_WAIT",				},
	},
	

	ATTACK_TIME0				= { 0.49, 0.77, },	

    SOUND_PLAY0			= { 0.530, "BatBig_Small_Cry.ogg" },
    SOUND_PLAY1			= { 0.815, "BatBig_Small_Fly3.ogg" },


	DAMAGE_DATA = 
	{
		DAMAGE_TYPE		= DAMAGE_TYPE["DT_PHYSIC"],
		HIT_TYPE		= HIT_TYPE["HT_SWORD_SLASH"],
		REACT_TYPE		= REACT_TYPE["RT_DOWN"],
		
		DAMAGE = 
		{
			PHYSIC		= 1.0,
			FIRE		= 0.0,
			ICE			= 0.0,
			EARTH		= 0.0,
			LIGHTNING	= 0.0,
			DARK		= 0.0,
			LIGHT		= 0.0,
			UNIVERSAL	= 0.0,
		},
		
		BACK_SPEED_X			= INIT_PHYSIC["RUN_SPEED"],
		BACK_SPEED_Y			= 0.0,
		
		STOP_TIME_ATT			= 0.0,		
		STOP_TIME_DEF			= 0.0,	
		CAMERA_CRASH_GAP		= 5.0,	
		CAMERA_CRASH_TIME		= 0.2,
		CLEAR_SCREEN			= 0.0,	
		CLEAR_SCREEN_COLOR_A	= 0.0,
		CLEAR_SCREEN_COLOR_R	= 1.0,
		CLEAR_SCREEN_COLOR_G	= 1.0,
		CLEAR_SCREEN_COLOR_B	= 1.0,

		RE_ATTACK				= FALSE,		
		HIT_GAP					= 0.0,				
	},
	
}

BAT_KING_SMALL_STAND_UP_ATTACK_BACK = 
{
	ANIM_NAME					= "StandUpAttackBack",
	PLAY_TYPE					= XSKIN_ANIM_PLAYTYPE["XAP_ONE_WAIT"],
	TRANSITION					= FALSE,
	LAND_CONNECT				= FALSE,
	
	ANIM_WAIT_TIME				= 1,

	MIND_FLAG					= MIND_FLAG["MF_STAND_UP_ATTACK"],
	
	SUPER_ARMOR					= TRUE,
	DEFENCE						= { 0, 100, 70, },
		
	CAN_PUSH_UNIT				= TRUE,
	CAN_PASS_UNIT				= FALSE,
	
	FLIP_DIR_END				= TRUE,
	
	EVENT_PROCESS = 
	{
		{ STATE_CHANGE_TYPE["SCT_FOOT_ON_LINE_FALSE_DOWN"],	"BAT_KING_SMALL_JUMP_DOWN", },
		{ STATE_CHANGE_TYPE["SCT_MOTION_END"],				"BAT_KING_SMALL_WAIT", },
	},	
	
	ATTACK_TIME0				= { 0.45, 1.07, },

    SOUND_PLAY0			= { 0.573, "BatBig_Small_Cry.ogg" },
    SOUND_PLAY1			= { 0.890, "BatBig_Small_Fly3.ogg" },

	DAMAGE_DATA = 
	{
		DAMAGE_TYPE		= DAMAGE_TYPE["DT_PHYSIC"],
		HIT_TYPE		= HIT_TYPE["HT_SWORD_SLASH"],
		REACT_TYPE		= REACT_TYPE["RT_DOWN"],
		
		DAMAGE = 
		{
			PHYSIC		= 1.0,
			FIRE		= 0.0,
			ICE			= 0.0,
			EARTH		= 0.0,
			LIGHTNING	= 0.0,
			DARK		= 0.0,
			LIGHT		= 0.0,
			UNIVERSAL	= 0.0,
		},
		
		BACK_SPEED_X			= INIT_PHYSIC["RUN_SPEED"],
		BACK_SPEED_Y			= 0.0,
		
		STOP_TIME_ATT			= 0.0,		
		STOP_TIME_DEF			= 0.0,	
		CAMERA_CRASH_GAP		= 5.0,	
		CAMERA_CRASH_TIME		= 0.2,
		CLEAR_SCREEN			= 0.0,	
		CLEAR_SCREEN_COLOR_A	= 0.0,
		CLEAR_SCREEN_COLOR_R	= 1.0,
		CLEAR_SCREEN_COLOR_G	= 1.0,
		CLEAR_SCREEN_COLOR_B	= 1.0,

		RE_ATTACK				= FALSE,		
		HIT_GAP					= 0.0,				
	},
}

BAT_KING_SMALL_DAMAGE_STAND_UP_BACK =
{
	ANIM_NAME					= "DamageStandUpBack",
	PLAY_TYPE					= XSKIN_ANIM_PLAYTYPE["XAP_ONE_WAIT"],
	TRANSITION					= TRUE,
	LAND_CONNECT				= FALSE,
	
	SUPER_ARMOR					= TRUE,
	DEFENCE						= { 0, 100, 70, },
		
	CAN_PUSH_UNIT				= TRUE,
	CAN_PASS_UNIT				= FALSE,

    SOUND_PLAY0					= { 0.776, "BatBig_Small_Fly3.ogg" },
    SOUND_PLAY1					= { 1.192, "BatBig_Small_Cry.ogg" , 20 },
    SOUND_PLAY2					= { 1.376, "BatBig_Small_Fly2.ogg" },
	

	
	EVENT_PROCESS = 
	{
		{ STATE_CHANGE_TYPE["SCT_FOOT_ON_LINE_FALSE_DOWN"],	"BAT_KING_SMALL_JUMP_DOWN", },
		{ STATE_CHANGE_TYPE["SCT_MOTION_END"],				"BAT_KING_SMALL_WAIT", },
	},	
}

BAT_KING_SMALL_DAMAGE_STAND_UP_FRONT = 
{
	ANIM_NAME					= "DamageStandUpFront",
	PLAY_TYPE					= XSKIN_ANIM_PLAYTYPE["XAP_ONE_WAIT"],
	TRANSITION					= TRUE,
	LAND_CONNECT				= FALSE,
	
	SUPER_ARMOR					= TRUE,
	DEFENCE						= { 0, 100, 70, },
		
	CAN_PUSH_UNIT				= TRUE,
	CAN_PASS_UNIT				= FALSE,

    SOUND_PLAY0					= { 0.782, "BatBig_Small_Fly3.ogg" },
    SOUND_PLAY1					= { 0.982, "BatBig_Small_Cry.ogg" , 20 },
    SOUND_PLAY2					= { 1.311, "BatBig_Small_Fly2.ogg" },
	

	
	EVENT_PROCESS = 
	{
		{ STATE_CHANGE_TYPE["SCT_FOOT_ON_LINE_FALSE_DOWN"],	"BAT_KING_SMALL_JUMP_DOWN", },
		{ STATE_CHANGE_TYPE["SCT_MOTION_END"],				"BAT_KING_SMALL_WAIT", },
	},	
}

BAT_KING_SMALL_DYING_LAND_FRONT = 
{
	ANIM_NAME					= "DamageDownFront",
	PLAY_TYPE					= XSKIN_ANIM_PLAYTYPE["XAP_ONE_WAIT"],
	TRANSITION					= FALSE,
	LAND_CONNECT				= FALSE,

	INVINCIBLE					= { 0, 100, }, 		
	
	CAN_PUSH_UNIT				= FALSE,
	CAN_PASS_UNIT				= TRUE,
	
	DYING_END					= TRUE,
	IMMADIATE_PACKET_SEND		= TRUE,
}
	
BAT_KING_SMALL_DYING_LAND_BACK = 
{
	ANIM_NAME					= "DamageDownBack",
	PLAY_TYPE					= XSKIN_ANIM_PLAYTYPE["XAP_ONE_WAIT"],
	TRANSITION					= FALSE,
	LAND_CONNECT				= FALSE,
	
	INVINCIBLE					= { 0, 100, }, 		
	
	CAN_PUSH_UNIT				= FALSE,
	CAN_PASS_UNIT				= TRUE,
	
	DYING_END					= TRUE,	
	IMMADIATE_PACKET_SEND		= TRUE,
}


BAT_KING_SMALL_DYING_SKY = 
{
	ANIM_NAME					= "DamageAirDownLanding",
	PLAY_TYPE					= XSKIN_ANIM_PLAYTYPE["XAP_ONE_WAIT"],
	TRANSITION					= FALSE,
	LAND_CONNECT				= FALSE,
	
	INVINCIBLE					= { 0, 100, }, 		
	
	CAN_PUSH_UNIT				= FALSE,
	CAN_PASS_UNIT				= TRUE,
	
	DYING_END					= TRUE,
	
	IMMADIATE_PACKET_SEND		= TRUE,
}




function BAT_KING_SMALL_START_CAMERA_MOVE( pKTDXApp, pX2Game, pNPCUnit )

	pos = pNPCUnit:GetBonePos_LUA("Bip01_Head")	
	camera = pX2Game:GetX2Camera()
	camera:PartsLookDirectCamera_LUA( pNPCUnit, pos, D3DXVECTOR3( 500, -50, -20 ), D3DXVECTOR2( 0,0 ) )

end

function CF_BAT_KING_SMALL_WIN( pKTDXApp, pX2Game, pNPCUnit )

	if pX2Game:LiveUserUnitNum() == 0 then
		return true
	else
		return false
	end

end


function CF_BAT_KING_SMALL_WAIT_ZERO2( pKTDXApp, pX2Game, pNPCUnit )

	monkeyANum = pX2Game:LiveNPCNumType_LUA( NPC_UNIT_ID["NUI_BAT_A_NODROP"] )
	if (monkeyANum == 0) then
		return true
	else
		return false
	end

end



function BAT_KING_SMALL_JUMP_DOWN_STATE_END( pKTDXApp, pX2Game, pNPCUnit )

	pMinorParticle = pX2Game:GetMinorParticle()
	pMinorParticle:GameUnitCreateSequence_LUA( pNPCUnit, "StepSmoke", pNPCUnit:GetLandPosition_LUA(), D3DXVECTOR2(100,100), D3DXVECTOR2(5,-1) )

end

function BAT_KING_SMALL_JUMP_DOWN_DIR_STATE_END( pKTDXApp, pX2Game, pNPCUnit )

	pMinorParticle = pX2Game:GetMinorParticle()
	pMinorParticle:GameUnitCreateSequence_LUA( pNPCUnit, "StepSmoke", pNPCUnit:GetLandPosition_LUA(), D3DXVECTOR2(100,100), D3DXVECTOR2(5,-1) )

end

function BAT_KING_SMALL_DAMAGE_SMALL_FRAME_MOVE( pKTDXApp, pX2Game, pNPCUnit )

	if pNPCUnit:AnimEventTimer_LUA( 0.047 ) then
	
		pMinorParticle = pX2Game:GetMinorParticle()
		pMinorParticle:GameUnitCreateSequence_LUA( pNPCUnit, "StepSmoke", pNPCUnit:GetLandPosition_LUA(), D3DXVECTOR2(100,100), D3DXVECTOR2(5,-1) )
		
		pNPCUnit:CallOtherNPC( NPC_UNIT_ID["NUI_BAT_A_NODROP"] )
		
	end

end

function BAT_KING_SMALL_DAMAGE_BIG_FRAME_MOVE( pKTDXApp, pX2Game, pNPCUnit )

	if pNPCUnit:AnimEventTimer_LUA( 0.211 ) then
	
		pMinorParticle = pX2Game:GetMinorParticle()
		pMinorParticle:GameUnitCreateSequence_LUA( pNPCUnit, "StepSmoke", pNPCUnit:GetLandPosition_LUA(), D3DXVECTOR2(100,100), D3DXVECTOR2(5,-1) )
		
		pNPCUnit:CallOtherNPC( NPC_UNIT_ID["NUI_BAT_A_NODROP"] )

	end

end

function BAT_KING_SMALL_DAMAGE_DOWN_FRAME_MOVE( pKTDXApp, pX2Game, pNPCUnit )

	if pNPCUnit:AnimEventTimer_LUA( 0.25 ) then
		pNPCUnit:PlaySound_LUA( "Down.ogg" )
		pMinorParticle = pX2Game:GetMinorParticle()
		pMinorParticle:GameUnitCreateSequence_LUA( pNPCUnit, "DownSmoke", pNPCUnit:GetLandPosition_LUA(), D3DXVECTOR2(100,100), D3DXVECTOR2(7,-1) )
	end

end



function BAT_KING_SMALL_DAMAGE_AIR_DOWN_LANDING_FRAME_MOVE( pKTDXApp, pX2Game, pNPCUnit )

	if pNPCUnit:AnimEventTimer_LUA( 0.01 ) then
		pNPCUnit:PlaySound_LUA( "Down.ogg" )
		pMinorParticle = pX2Game:GetMinorParticle()
		pos = pNPCUnit:GetLandPosition_LUA()
		pMinorParticle:GameUnitCreateSequence_LUA( pNPCUnit, "DownSmoke", pos, D3DXVECTOR2(100,100), D3DXVECTOR2(7,-1) )
		pos.y = pos.y + 5
		pMinorParticle:GameUnitCreateSequence_LUA( pNPCUnit, "GroundShockWave", pos, D3DXVECTOR2(100,100), D3DXVECTOR2(1,-1) )
		pParticle = pMinorParticle:GameUnitCreateSequence_LUA( pNPCUnit, "AirDownTick", pNPCUnit:GetPos(), D3DXVECTOR2(200,200), D3DXVECTOR2(10,-1) )
		if pParticle ~= nil then 
			pParticle:SetLandPosition( pos.y - 5 )
		end
		
		if GetDistance_LUA( pNPCUnit:GetPos(), pX2Game:GetFocusUnitPos_LUA() ) < 500 then
			pX2Game:GetX2Camera():GetCamera():UpDownCrashCameraNoReset( 10.0, 0.1 )
		end		
		
	elseif pNPCUnit:AnimEventTimer_LUA( 0.35 ) then
		pNPCUnit:PlaySound_LUA( "Down.ogg" )
		pMinorParticle = pX2Game:GetMinorParticle()
		pMinorParticle:GameUnitCreateSequence_LUA( pNPCUnit, "DownSmoke", pNPCUnit:GetLandPosition_LUA(), D3DXVECTOR2(100,100), D3DXVECTOR2(7,-1) )
	end
	
end


function BAT_KING_SMALL_DYING_LAND_STATE_START( pKTDXApp, pX2Game, pNPCUnit )
	
	pos = pNPCUnit:GetPos()
	pos.y = pos.y + 100.0
	GetMinorParticle = pX2Game:GetMinorParticle()
	--GetMinorParticle:GameUnitCreateSequence_LUA( pNPCUnit, "DieImpactRingRed",		pos, D3DXVECTOR2(-1,-1), D3DXVECTOR2(3,-1) )
	--GetMinorParticle:GameUnitCreateSequence_LUA( pNPCUnit, "DieImpactSlashRed",		pos, D3DXVECTOR2(-1,-1), D3DXVECTOR2(3,-1) )
	--GetMinorParticle:GameUnitCreateSequence_LUA( pNPCUnit, "DieSmoke",				pos, D3DXVECTOR2(-1,-1), D3DXVECTOR2(5,-1) )
	
	pSeq = GetMinorParticle:GameUnitCreateSequence_LUA( pNPCUnit, "DieLight",		pos, D3DXVECTOR2(-1,-1), D3DXVECTOR2(3,-1) )
	if pSeq ~= nil then
	
		pSeq:SetLandPosition( pNPCUnit:GetLandPosition_LUA().y )
		pNPCUnit:SetDieSeq( pSeq:GetHandle() )
	
	end
	
	pNPCUnit:PlaySound_LUA( "DieLight.ogg" )
	
end






function BAT_KING_SMALL_DAMAGE_DOWN_FRONT_FRAME_MOVE( pKTDXApp, pX2Game, pNPCUnit )

	if pNPCUnit:AnimEventTimer_LUA( 0.48 ) then
		pNPCUnit:PlaySound_LUA( "Down.ogg" )
		pMinorParticle = pX2Game:GetMinorParticle()
		pMinorParticle:GameUnitCreateSequence_LUA( pNPCUnit, "DownSmoke", pNPCUnit:GetLandPosition_LUA(), D3DXVECTOR2(100,100), D3DXVECTOR2(7,-1) )
	end

end

function BAT_KING_SMALL_DAMAGE_DOWN_BACK_FRAME_MOVE( pKTDXApp, pX2Game, pNPCUnit )

	if pNPCUnit:AnimEventTimer_LUA( 0.24 ) then
		pNPCUnit:PlaySound_LUA( "Down.ogg" )
		pMinorParticle = pX2Game:GetMinorParticle()
		pMinorParticle:GameUnitCreateSequence_LUA( pNPCUnit, "DownSmoke", pNPCUnit:GetLandPosition_LUA(), D3DXVECTOR2(100,100), D3DXVECTOR2(7,-1) )
	end

end


function BAT_KING_SMALL_ATTACK_COMBO_FRAME_MOVE( pKTDXApp, pX2Game, pNPCUnit )
	
	if pNPCUnit:AnimEventTimer_LUA( 0.73 ) then
		pNPCUnit:ClearHitUnitList_LUA()
	end
	
	if pNPCUnit:AnimEventTimer_LUA( 0.8 ) then
		pNPCUnit:SetSpeedX( INIT_PHYSIC["WALK_SPEED"] )
	end

	if pNPCUnit:AnimEventTimer_LUA( 1.12 ) then
		pNPCUnit:ClearHitUnitList_LUA()
		pNPCUnit:SetDamageData_LUA( "DAMAGE_DATA_LAST" )
	end
	
	if pNPCUnit:AnimEventTimer_LUA( 1.3 ) then
		pNPCUnit:SetSpeedX( INIT_PHYSIC["WALK_SPEED"] )
	end

end



function BAT_KING_SMALL_ATTACK_AIR_FRAME_MOVE( pKTDXApp, pX2Game, pNPCUnit )

	
	if pNPCUnit:AnimEventTimer_LUA( 3.0 ) then
		pNPCUnit:ClearHitUnitList_LUA()
	end

	if pNPCUnit:AnimEventTimer_LUA( 5.0 ) then
		pNPCUnit:ClearHitUnitList_LUA()
	end


end


function BAT_KING_SMALL_STAND_UP_ATTACK_FRONT_FRAME_MOVE( pKTDXApp, pX2Game, pNPCUnit )



	if pNPCUnit:AnimEventTimer_LUA( 0.01 ) then
	
		bonePos = pNPCUnit:GetBonePos_LUA( "Bip01_Pelvis" )
		bonePos.y = bonePos.y - 200
		
		landPos = pNPCUnit:GetLandPosition_LUA()
	
		pDamageEffect = pX2Game:GetDamageEffect()
		pDamageEffect:CreateInstance_LUA( pNPCUnit, "BAT_BIG_STAND_UP_ATTACK_SMALL", bonePos, landPos.y)
	
		bonePos.y = bonePos.y + 100
	
		pDamageEffect:CreateInstance_LUA( pNPCUnit, "BAT_BIG_STAND_UP_ATTACK2_SMALL", bonePos, landPos.y)
		
	end

	
	if pNPCUnit:AnimEventTimer_LUA( 0.71 ) then
	
		landPos = pNPCUnit:GetLandPosition_LUA()
		landPos.y = landPos.y + 15
		pMinorParticle = pX2Game:GetMinorParticle()
		pMinorParticle:GameUnitCreateSequence_LUA( pNPCUnit, "GroundShockWave", landPos, D3DXVECTOR2(100,100), D3DXVECTOR2(1,-1) )
		
	end

end


function BAT_KING_SMALL_STAND_UP_ATTACK_BACK_FRAME_MOVE( pKTDXApp, pX2Game, pNPCUnit )


	if pNPCUnit:AnimEventTimer_LUA( 0.01 ) then

		bonePos = pNPCUnit:GetBonePos_LUA( "Bip01_Pelvis" )
		bonePos.y = bonePos.y - 200
		
		landPos = pNPCUnit:GetLandPosition_LUA()

		pDamageEffect = pX2Game:GetDamageEffect()
		pDamageEffect:CreateInstance_LUA( pNPCUnit, "BAT_BIG_STAND_UP_ATTACK_SMALL", bonePos, landPos.y)
		
		bonePos.y = bonePos.y + 100
		
		pDamageEffect:CreateInstance_LUA( pNPCUnit, "BAT_BIG_STAND_UP_ATTACK2_SMALL", bonePos, landPos.y)
	
	end
	


	if pNPCUnit:AnimEventTimer_LUA( 0.71 ) then
	
		landPos = pNPCUnit:GetLandPosition_LUA()
		landPos.y = landPos.y + 15
		pMinorParticle = pX2Game:GetMinorParticle()
		pMinorParticle:GameUnitCreateSequence_LUA( pNPCUnit, "GroundShockWave", landPos, D3DXVECTOR2(100,100), D3DXVECTOR2(1,-1) )
		
	end
	
end

