-- lua header. UTF-8 인코딩 인식을 위해 이 줄은 지우지 마세요.


INIT_SYSTEM = 
{
	UNIT_WIDTH		= 100.0,
	UNIT_HEIGHT		= 150.0,
	UNIT_LAYER		= X2_LAYER["XL_UNIT_0"],
}


INIT_DEVICE = 
{
READY_SOUND = 
	{
     "Tuto_Benders_Actor.ogg",
	},
}

INIT_MOTION = 
{
	MOTION_FILE_NAME	= "Motion_Benders_Epic_Actor.x",
}

INIT_PHYSIC = 
{
	RELOAD_ACCEL		= 2000,
	G_ACCEL				= 4000,
	MAX_G_SPEED			= -2000,
	
	WALK_SPEED			= 400,
	RUN_SPEED			= 400,
	JUMP_SPEED			= 1500,
	DASH_JUMP_SPEED		= 2300,
}


INIT_COMPONENT = 
{
	MAX_HP				= 1500,
	MP_CHANGE_RATE		= 1,
	MP_CHARGE_RATE		= 130,
	
	USE_SLASH_TRACE		= FALSE,
	
	SHADOW_SIZE			= 200,
	SHADOW_FILE_NAME	= "shadow.dds",
	
	HEAD_BONE_NAME		= "Bip01_Head",
	
	HYPER_MODE_COUNT	= 0,
	MAX_HYPER_MODE_TIME	= 30,
	
	HITTED_TYPE			= HITTED_TYPE["HTD_MEAT"],
	
	FALL_DOWN			= TRUE,
	
	DAMAGE_DOWN         = FALSE,
	
	
	WEAPON0 = 
	{
		WEAPON_FILE_NAME	= "Mesh_Benders_Basic_Weapon.X",
		WEAPON_BONE_NAME	= "Dummy1_Rhand",
		
		WEAPON_ROTAION_X = 0,
		WEAPON_ROTAION_Y = 90,
		WEAPON_ROTAION_Z = 100,

		
		USE_SLASH_TRACE				= TRUE,
		SLASH_TRACE_TOP_BONE		= "TRACE_START0",
		SLASH_TRACE_BOTTOM_BONE		= "TRACE_END0",
	},
	
}

INIT_STATE = 
{
	{ STATE_NAME = "BENDERS_ACTOR_WAIT",		LUA_FRAME_MOVE_FUNC  = "BENDERS_ACTOR_WAIT_FRAME_MOVE_FUNC",},
												
	{ STATE_NAME = "BENDERS_ACTOR_START",		LUA_STATE_START_FUNC = "BENDERS_ACTOR_START_START_FUNC",},
	{ STATE_NAME = "BENDERS_ACTOR_TALK",		},
	{ STATE_NAME = "BENDERS_ACTOR_TALK2",		LUA_STATE_END_FUNC = "BENDERS_ACTOR_TALK2_END_FUNC",},
	{ STATE_NAME = "BENDERS_ACTOR_DYING",		},
	
	START_STATE					= "BENDERS_ACTOR_WAIT",
		
	DYING_LAND_FRONT			= "BENDERS_ACTOR_DYING",
	DYING_LAND_BACK				= "BENDERS_ACTOR_DYING",
	DYING_SKY					= "BENDERS_ACTOR_DYING",	
}


INIT_AI = 
{
	TARGET = 
	{
		TARGET_PRIORITY 			= TARGET_PRIORITY["TP_RANDOM"],
		TARGET_INTERVAL				= 1,		-- sec
		TARGET_NEAR_RANGE			= 2000,		-- 이 거리보다 가까우면 TARGET_SUCCESS_RATE에 관계없이 무조건 타게팅된다
		TARGET_RANGE				= 2000,		-- cm
		TARGET_LOST_RANGE			= 600,		-- cm
		TARGET_SUCCESS_RATE			= 100,  --50,		-- %
		ATTACK_TARGET_RATE			= 100, -- 10,		-- 나를 공격한 유닛을 타게팅할 확률
		PRESERVE_LAST_TARGET_RATE	= 100, -- 50,		-- 이전에 타게팅된 유닛을 계속 타게팅할 확률
	},	
}

BENDERS_ACTOR_WAIT = 
{
	ANIM_NAME					= "Wait0",
	PLAY_TYPE					= XSKIN_ANIM_PLAYTYPE["XAP_ONE_WAIT"],
	TRANSITION					= FALSE,
	
	INVINCIBLE					= { 0, 100, },
	
	CAN_PUSH_UNIT				= TRUE,
	CAN_PASS_UNIT				= TRUE,
	
	RIGHT = TRUE,
}

BENDERS_ACTOR_START = 
{
	ANIM_NAME					= "Start",
	PLAY_TYPE					= XSKIN_ANIM_PLAYTYPE["XAP_ONE_WAIT"],
	TRANSITION					= FALSE,
	
	INVINCIBLE					= { 0, 100, },
	
	CAN_PUSH_UNIT				= TRUE,
	CAN_PASS_UNIT				= TRUE,
	
	SOUND_PLAY0			= { 0.00001, "Tuto_Benders_Actor.ogg" },
	
	EVENT_PROCESS = 
	{
		{ STATE_CHANGE_TYPE["SCT_MOTION_END"],	"BENDERS_ACTOR_TALK",},	
	},	
	
	RIGHT = TRUE,
	FOCUS_CAMERA_AT_CURRENT_STATE = TRUE,
	STOP_AT_CURRENT_STATE = TRUE,
	
	PASSIVE_SPEED_X = 235,

	CAMERA = 
	{
		SUB_CAMERA_TIMING = { 0.1,},		
	
		SUB_CAMERA0 = 
		{
			CAMERA_TYPE		= CAMERA_TYPE["CT_PARTS_LOOK_DIRECT"],
			LOOK_TYPE		= LOOK_TYPE["LT_BONE"],
			LOOK_PARTS		= "Bip01",
			DISTANCE		= 1000,
			HEIGHT			= 300,
			ANGLEDEGREE		= 40,
			EYEDISTANCE		= 0,
		},
		SUB_CAMERA1 = 
		{
			CAMERA_TYPE		= CAMERA_TYPE["CT_PARTS_LOOK_TRACKING"],
			LOOK_TYPE		= LOOK_TYPE["LT_BONE"],
			LOOK_PARTS		= "Bip01_Spine1",
			DISTANCE		= 500,
			HEIGHT			= 200,
			ANGLEDEGREE		= -10,
			LOOK_OFFSET_X		= 100,
			LOOKATDISTANCE	= 50,
			TRACKINGTIME	= 2.0,
		},
	},
}

BENDERS_ACTOR_TALK = 
{
	ANIM_NAME					= "Wait0",
	PLAY_TYPE					= XSKIN_ANIM_PLAYTYPE["XAP_ONE_WAIT"],
	TRANSITION					= TRUE,
	
	INVINCIBLE					= { 0, 100, },
	
	CAN_PUSH_UNIT				= TRUE,
	CAN_PASS_UNIT				= TRUE,
	
	EVENT_PROCESS = 
	{
		{ STATE_CHANGE_TYPE["SCT_MOTION_END"],	"BENDERS_ACTOR_TALK2",},
	},
	
	TALK_BOX =
	{
		{ RATE = 100, MESSAGE = STR_ID_18142, },
	},
	
	FOCUS_CAMERA_AT_CURRENT_STATE = TRUE,
	STOP_AT_CURRENT_STATE = TRUE,
	
	CAMERA = 
	{
		SUB_CAMERA_TIMING = { 4.6,},		
	
		SUB_CAMERA0 = 
		{
			CAMERA_TYPE		= CAMERA_TYPE["CT_PARTS_LOOK_TRACKING"],
			LOOK_TYPE		= LOOK_TYPE["LT_BONE"],
			LOOK_PARTS		= "Bip01_Spine1",
			DISTANCE		= 700,
			HEIGHT			= 200,
			ANGLEDEGREE		= -30,
			EYEDISTANCE		= 0,
			LOOKATDISTANCE	= 50,
			TRACKINGTIME	= 2.0,
		},
		SUB_CAMERA1 = 
		{
			CAMERA_TYPE		= CAMERA_TYPE["CT_PARTS_LOOK_TRACKING"],
			LOOK_TYPE		= LOOK_TYPE["LT_BONE"],
			LOOK_PARTS		= "Bip01_Spine1",
			DISTANCE		= 400,
			HEIGHT			= -100,
			ANGLEDEGREE		= 0,
			EYEDISTANCE		= 0,
			LOOKATDISTANCE	= 20,
		},
	},
}

BENDERS_ACTOR_TALK2 = 
{
	ANIM_NAME					= "Dying",
	PLAY_TYPE					= XSKIN_ANIM_PLAYTYPE["XAP_ONE_WAIT"],
	TRANSITION					= TRUE,
	
	INVINCIBLE					= { 0, 100, },
	
	CAN_PUSH_UNIT				= TRUE,
	CAN_PASS_UNIT				= TRUE,
	
	EVENT_PROCESS = 
	{
		{ STATE_CHANGE_TYPE["SCT_MOTION_END"],	"BENDERS_ACTOR_DYING",},
	},
	
	TALK_BOX =
	{
		{ RATE = 100, MESSAGE = STR_ID_18143, },
	},
	
	FOCUS_CAMERA_AT_CURRENT_STATE = TRUE,
	STOP_AT_CURRENT_STATE = TRUE,
	
	CAMERA = 
	{
		SUB_CAMERA_TIMING = { 2.1,},		
	
		SUB_CAMERA0 = 
		{
			CAMERA_TYPE		= CAMERA_TYPE["CT_PARTS_LOOK_TRACKING"],
			LOOK_TYPE		= LOOK_TYPE["LT_BONE"],
			LOOK_PARTS		= "Bip01_Spine1",
			DISTANCE		= 400,
			HEIGHT			= -100,
			ANGLEDEGREE		= 0,
			EYEDISTANCE		= 0,
			LOOKATDISTANCE	= 20,
		},
		
		SUB_CAMERA1 = 
		{
			CAMERA_TYPE		= CAMERA_TYPE["CT_PARTS_LOOK_TRACKING"],
			LOOK_TYPE		= LOOK_TYPE["LT_BONE"],
			LOOK_PARTS		= "Camera_Bone_01",
			DISTANCE		= 300,
			HEIGHT			= 100,
			ANGLEDEGREE		= -50,
			EYEDISTANCE		= 0,
			TRACKINGTIME	= 1.2,
			LOOK_OFFSET_X		= 100
		},
	},
}

BENDERS_ACTOR_DYING = 
{
	ANIM_NAME					= "Dying_Walk",
	PLAY_TYPE					= XSKIN_ANIM_PLAYTYPE["XAP_ONE_WAIT"],
	TRANSITION					= TRUE,
	LAND_CONNECT				= FALSE,

	INVINCIBLE					= { 0, 100, },
	
	PASSIVE_SPEED_X = 400,
	
	
	CAN_PUSH_UNIT				= FALSE,
	CAN_PASS_UNIT				= TRUE,
	
	DYING_END					= TRUE,
}
function BENDERS_ACTOR_WAIT_FRAME_MOVE_FUNC( pKTDApp, pX2Game, pNPCUnit )
	if nil ~= pNPCUnit then
		vPos = pNPCUnit:GetNearestUserPos()
		if -500 < vPos.x then
			pNPCUnit:StateChange_LUA( "BENDERS_ACTOR_START", false )	
		end		
	end
end

function BENDERS_ACTOR_START_START_FUNC( pKTDApp, pX2Game, pNPCUnit )
	if nil ~= pX2Game then
		pX2Game:CreateNPCReq_LUA( NPC_UNIT_ID["NUI_TUTO_ZERO_EPIC_ACTOR"], 0, true, D3DXVECTOR3( 783, 0 , 0 ), false , 0, true  )		
		pX2Game:CreateNPCReq_LUA( NPC_UNIT_ID["NUI_TUTO_TOTO_ACTOR"], 0, true, D3DXVECTOR3( 1274, 0 , 0 ), false , 0, true  )		
	end
end


function BENDERS_ACTOR_TALK2_END_FUNC( pKTDApp, pX2Game, pNPCUnit )
	if nil ~= pX2Game then
		pX2Game:CreateNPCReq_LUA( NPC_UNIT_ID["NUI_TUTO_BENDERS_THIEF"], 0, true, D3DXVECTOR3( 2500, 0 , 0 ), false , 0, true  )	
	end	
end