-- lua header. UTF-8 인코딩 인식을 위해 이 줄은 지우지 마세요.


INIT_SYSTEM = 
{
	UNIT_WIDTH		= 120.0,
	UNIT_HEIGHT		= 150.0,
	UNIT_LAYER		= X2_LAYER["XL_UNIT_0"],
	UNIT_SCALE      = 1.2,
}


INIT_DEVICE = 
{
	READY_TEXTURE = 
	{
	},
	
	READY_SOUND = 
	{
	
	 "Coacktrigle_AttackA_jump1.ogg",
	 "Coacktrigle_AttackA_Jump2.ogg",
	 "CoacktrigleVoice_Damage.ogg",
	 "CoacktrigleVoice_DamageDown.ogg",
	 "CoacktrigleVoice_Dying.ogg",
	 "Coacktrigle_DyingFall.ogg",
	 "Coacktrigle_MagicAttackA.ogg",
	 "Coacktrigle_JumpLanding.ogg",
	 "Coacktriglevoice_AttackA.ogg",
	 "Coacktrigle_Walk.ogg",
	 
	
	},

	READY_XMESH = 
	{
	 "Lightning03.Y",
	},
	
	READY_XSKIN_MESH = 
	{
	 "Coackatrigle_MagicAttackA_Mesh01.X",
	},
}

INIT_MOTION = 
{
	MOTION_FILE_NAME		= "Motion_COACKATRIGLE.x",
	MOTION_CHANGE_TEX_XET	= "Motion_Coackatrigle_boss.xet",	
}

INIT_PHYSIC = 
{	
	RELOAD_ACCEL		= 2000,
	G_ACCEL				= 4000,
	MAX_G_SPEED			= -2000,
	
	WALK_SPEED			= 800,
	RUN_SPEED			= 800,
	JUMP_SPEED			= 1500,
	DASH_JUMP_SPEED		= 2300,
}


INIT_COMPONENT = 
{
	IMMUNITY_TIME_STOP = TRUE,
	MP_CHANGE_RATE		= 0,
	MP_CHARGE_RATE		= 0,
	
	--USE_SLASH_TRACE		= FALSE,
	
	--SHADOW_SIZE			= 200,
	SHADOW_FILE_NAME	= "shadow.dds",
	
	SMALL_HP_BAR_BLUE	= "Small_HP_bar_Blue.TGA",
	SMALL_HP_BAR_RED	= "Small_HP_bar_Red.TGA",
	SMALL_HP_BAR_YELLOW = "Small_HP_bar_Yellow.TGA",
	
	QUESTION_MARK_SEQ		= "QuestionMarkNPC",
	EXCLAMATION_MARK_SEQ	= "ExclamationMarkNPC",
	

	
	HYPER_MODE_COUNT	= 0,
	MAX_HYPER_MODE_TIME	= 30,
	
	HITTED_TYPE			= HITTED_TYPE["HTD_MEAT"],
	FALL_DOWN			= TRUE,
	
	DAMAGE_DOWN         = FALSE,
		
	DIE_FLY             = 0,

	RIDE_MONSTER = TRUE,

}




INIT_STATE = 
{
	{ STATE_NAME = "COACKATRIGLE_BOSS_START",				},
	{ STATE_NAME = "COACKATRIGLE_BOSS_WAIT",					},
	
	
	--리액션 관련

	{ STATE_NAME = "COACKATRIGLE_BOSS_WALK",					},
	{ STATE_NAME = "COACKATRIGLE_BOSS_PASS_WALK",			},	
	{ STATE_NAME = "COACKATRIGLE_BOSS_JUMP_UP",				},
	{ STATE_NAME = "COACKATRIGLE_BOSS_JUMP_DOWN",			},
	{ STATE_NAME = "COACKATRIGLE_BOSS_JUMP_UP_DIR",			},
	{ STATE_NAME = "COACKATRIGLE_BOSS_JUMP_DOWN_DIR",		 },
	{ STATE_NAME = "COACKATRIGLE_BOSS_JUMP_LANDING",			LUA_STATE_START_FUNC = "COACKATRIGLE_BOSS_JUMP_LANDING_STATE_START", },
	{ STATE_NAME = "COACKATRIGLE_BOSS_MAGIC_ATTACK_A_READY",		STATE_COOL_TIME = 8,        },
	{ STATE_NAME = "COACKATRIGLE_BOSS_MAGIC_ATTACK_A",			LUA_FRAME_MOVE_FUNC     = "COACKATRIGLE_BOSS_MAGIC_ATTACK_A_FRAME_MOVE",  
	                                                                LUA_STATE_END_FUNC      = "COACKATRIGLE_BOSS_MAGIC_ATTACK_A_STATE_END", },
	{ STATE_NAME = "COACKATRIGLE_BOSS_ATTACK_A",					},
	{ STATE_NAME = "COACKATRIGLE_BOSS_DAMAGE_FRONT",				},	
	{ STATE_NAME = "COACKATRIGLE_BOSS_DAMAGE_BACK",				},	

	{ STATE_NAME = "COACKATRIGLE_BOSS_RIDE_ATTACK_B_JUMP_UP_DIR",			},
	{ STATE_NAME = "COACKATRIGLE_BOSS_RIDE_ATTACK_B_JUMP_DOWN_DIR",		 },
	{ STATE_NAME = "COACKATRIGLE_BOSS_RIDE_ATTACK_B_JUMP_LANDING",			LUA_FRAME_MOVE_FUNC = "COACKATRIGLE_BOSS_RIDE_ATTACK_B_JUMP_LANDING_STATE_FRAME_MOVE",
	
																			LUA_STATE_START_FUNC = "COACKATRIGLE_BOSS_RIDE_ATTACK_B_JUMP_LANDING_STATE_START", },
			



	{ STATE_NAME = "COACKATRIGLE_BOSS_DAMAGE_DOWN",			LUA_FRAME_MOVE_FUNC = "COACKATRIGLE_BOSS_DAMAGE_DOWN_FRAME_MOVE"			},

	--{ STATE_NAME = "COACKATRIGLE_BOSS_DAMAGE_FLY_FRONT",			},
	--{ STATE_NAME = "COACKATRIGLE_BOSS_DAMAGE_FLY_BACK",			},
	{ STATE_NAME = "COACKATRIGLE_BOSS_DAMAGE_AIR",					},
	{ STATE_NAME = "COACKATRIGLE_BOSS_DAMAGE_AIR_DOWN",			},
	{ STATE_NAME = "COACKATRIGLE_BOSS_DAMAGE_AIR_UP",			LUA_STATE_START_FUNC = "COACKATRIGLE_BOSS_DAMAGE_AIR_UP_STATE_START", },
	{ STATE_NAME = "COACKATRIGLE_BOSS_DAMAGE_AIR_FALL",			},	
	{ STATE_NAME = "COACKATRIGLE_BOSS_DAMAGE_AIR_DOWN_LANDING",		LUA_FRAME_MOVE_FUNC = "COACKATRIGLE_BOSS_DAMAGE_AIR_DOWN_LANDING_FRAME_MOVE"	},
	{ STATE_NAME = "COACKATRIGLE_BOSS_STAND_UP",				},



	{ STATE_NAME = "COACKATRIGLE_BOSS_RIDE_DAMAGE_FRONT",				},	
	{ STATE_NAME = "COACKATRIGLE_BOSS_RIDE_DAMAGE_BACK",				},	





	{ STATE_NAME = "COACKATRIGLE_BOSS_DYING",				LUA_STATE_START_FUNC = "COACKATRIGLE_BOSS_DYING_STATE_START", },



	
	START_STATE					= "COACKATRIGLE_BOSS_START",
	WAIT_STATE					= "COACKATRIGLE_BOSS_WAIT",
	RIDE_STATE					= "COACKATRIGLE_BOSS_WAIT",
	
	
	RIDE_DAMAGE_FRONT		= "COACKATRIGLE_BOSS_RIDE_DAMAGE_FRONT",
	RIDE_DAMAGE_BACK		= "COACKATRIGLE_BOSS_RIDE_DAMAGE_BACK",
	
	
	SMALL_DAMAGE_LAND_FRONT		= "COACKATRIGLE_BOSS_DAMAGE_FRONT",
	SMALL_DAMAGE_LAND_BACK		= "COACKATRIGLE_BOSS_DAMAGE_BACK",
	BIG_DAMAGE_LAND_FRONT		= "COACKATRIGLE_BOSS_DAMAGE_FRONT",
	BIG_DAMAGE_LAND_BACK		= "COACKATRIGLE_BOSS_DAMAGE_BACK",
	DOWN_DAMAGE_LAND_FRONT		= "COACKATRIGLE_BOSS_DAMAGE_DOWN",
	DOWN_DAMAGE_LAND_BACK		= "COACKATRIGLE_BOSS_DAMAGE_DOWN",
	FLY_DAMAGE_FRONT			= "COACKATRIGLE_BOSS_DAMAGE_AIR_UP",
	FLY_DAMAGE_BACK				= "COACKATRIGLE_BOSS_DAMAGE_AIR_UP",
	SMALL_DAMAGE_AIR			= "COACKATRIGLE_BOSS_DAMAGE_AIR",	
	BIG_DAMAGE_AIR				= "COACKATRIGLE_BOSS_DAMAGE_AIR",
	DOWN_DAMAGE_AIR				= "COACKATRIGLE_BOSS_DAMAGE_AIR_DOWN",
	DOWN_DAMAGE_AIR_LANDING				= "COACKATRIGLE_BOSS_DAMAGE_AIR_DOWN_LANDING",
	UP_DAMAGE					= "COACKATRIGLE_BOSS_DAMAGE_AIR_UP",
	
	DAMAGE_EXTRA_STATES         = {"COACKATRIGLE_BOSS_DAMAGE_AIR_FALL","COACKATRIGLE_BOSS_STAND_UP","COACKATRIGLE_BOSS_JUMP_DOWN","COACKATRIGLE_BOSS_JUMP_LANDING",},	
	
	DYING_LAND_FRONT			= "COACKATRIGLE_BOSS_DYING",
	DYING_LAND_BACK				= "COACKATRIGLE_BOSS_DYING",
	DYING_SKY					= "COACKATRIGLE_BOSS_DYING",

	REVENGE_ATTACK				= "",	
}

INIT_AI = 
{
	TARGET = 
	{
		TARGET_PRIORITY 			= TARGET_PRIORITY["TP_LOW_HP_FIRST"],
		TARGET_INTERVAL				= 3,		-- sec
		TARGET_NEAR_RANGE			= 350,		-- 이 거리보다 가까우면 TARGET_SUCCESS_RATE에 관계없이 무조건 타게팅된다
		TARGET_RANGE				= 700,		-- cm
		TARGET_LOST_RANGE			= 800,		-- cm
		TARGET_SUCCESS_RATE			= 100,  --40,		-- %
		ATTACK_TARGET_RATE			= 100, -- 30,		-- 나를 공격한 유닛을 타게팅할 확률
		PRESERVE_LAST_TARGET_RATE	= 100, -- 30,		-- 이전에 타게팅된 유닛을 계속 타게팅할 확률	
	},

	CHASE_MOVE = 
	{		
		MOVE_SPLIT_RANGE	= 600,
		DEST_GAP			= 600,	-- 목적지에서 이 거리 안에 있으면 도착했다고 판단한다
		MOVE_GAP			= 700,
		
		DIR_CHANGE_INTERVAL = 0.7,
		
		WALK_INTERVAL		= 3,
		NEAR_WALK_RATE		= 100,   --  70,
		FAR_WALK_RATE		= 100,   -- 30,
		
		JUMP_INTERVAL		= 5,
		UP_JUMP_RATE		= 100, -- 80,
		UP_DOWN_RATE		= 20,
		DOWN_JUMP_RATE		= 100,    --  20,
		DOWN_DOWN_RATE		= 80,
	},	
	
	PATROL_MOVE = 	
	{
		PATROL_BEGIN_RATE		= 100, --50,		
		PATROL_RANGE			= 200,
		PATROL_COOL_TIME		= 2,
		ONLY_THIS_LINE_GROUP	= TRUE,
	},
	
	ESCAPE_MOVE = 
	{		
		MOVE_SPLIT_RANGE	= 500,	-- cm
		ESCAPE_GAP			= 600,	-- 이 거리 보다 멀어지면 도망 성공
		
		WALK_INTERVAL		= 1.5,	-- 초
		NEAR_WALK_RATE		= 100,   --  10,
		FAR_WALK_RATE		= 100,   -- 10,
		
		JUMP_INTERVAL		= 10,
		UP_JUMP_RATE		= 100, -- 30,
		UP_DOWN_RATE		= 30,
		DOWN_JUMP_RATE		= 100,    --  30,
		DOWN_DOWN_RATE		= 30,
	},
	
	
}



COACKATRIGLE_BOSS_START = 
{
	ANIM_NAME					= "WaitStart",
	PLAY_TYPE					= XSKIN_ANIM_PLAYTYPE["XAP_ONE_WAIT"],
	TRANSITION					= TRUE,
	
	CAN_PUSH_UNIT				= FALSE,
	CAN_PASS_UNIT				= FALSE,
	
--[[
	PARTICLE_SEQ = 
	{
		--Major, time, Name, weaponBonePos, Pos, StateEndDelete, bTrace, posx, posy, posz, bApplyUnitRotation, rotx, roty, rotz,
		{ TRUE, 0.01, "Wisp_Light01", FALSE, "Wisp_Body", FALSE },
	},
--]]	
	EVENT_PROCESS = 
	{
		{ STATE_CHANGE_TYPE["SCT_MOTION_END"],					"COACKATRIGLE_BOSS_WAIT",				},
	},
	
	
}



COACKATRIGLE_BOSS_WAIT = 
{
	ANIM_NAME					= "Wait",
	PLAY_TYPE					= XSKIN_ANIM_PLAYTYPE["XAP_LOOP"],
	TRANSITION					= TRUE,
	
	CAN_PUSH_UNIT				= TRUE,
	CAN_PASS_UNIT				= FALSE,
	

	IMMADIATE_PACKET_SEND		= TRUE,
	EVENT_INTERVAL_TIME0		= 1,

	EVENT_PROCESS = 
	{		
		{ STATE_CHANGE_TYPE["SCT_FOOT_ON_LINE_FALSE_DOWN"],	"COACKATRIGLE_BOSS_JUMP_DOWN",					},
		{ STATE_CHANGE_TYPE["SCT_CONDITION_TABLE"],			"COACKATRIGLE_BOSS_ATTACK_A",				"CT_COACKATRIGLE_BOSS_ATTACK_A",			},

		{ STATE_CHANGE_TYPE["SCT_CONDITION_TABLE"],			"COACKATRIGLE_BOSS_MAGIC_ATTACK_A_READY",				"CT_COACKATRIGLE_BOSS_MAGIC_ATTACK_A_READY",			},

		{ STATE_CHANGE_TYPE["SCT_AI_WALK"],					"COACKATRIGLE_BOSS_WALK",						},
		{ STATE_CHANGE_TYPE["SCT_AI_DASH"],					"COACKATRIGLE_BOSS_WALK",						},
		{ STATE_CHANGE_TYPE["SCT_AI_JUMP"],					"COACKATRIGLE_BOSS_JUMP_UP",						},
		{ STATE_CHANGE_TYPE["SCT_AI_JUMP_DIR"],				"COACKATRIGLE_BOSS_JUMP_UP_DIR",					},
		{ STATE_CHANGE_TYPE["SCT_AI_DOWN"],					"COACKATRIGLE_BOSS_JUMP_DOWN",					},
		{ STATE_CHANGE_TYPE["SCT_AI_DOWN_DIR"],				"COACKATRIGLE_BOSS_JUMP_DOWN_DIR",				},
	},

	CT_COACKATRIGLE_BOSS_ATTACK_A = 
	{
		EVENT_INTERVAL_ID			= 0,
		SAME_LINE_WITH_TARGET			= TRUE,
		DISTANCE_TO_TARGET_NEAR		= 600,
		RATE						= 60,
	},


	CT_COACKATRIGLE_BOSS_MAGIC_ATTACK_A_READY = 
	{
		EVENT_INTERVAL_ID			= 0,
		DISTANCE_TO_TARGET_NEAR		= 1000,
		RATE						= 100,
	},
}


COACKATRIGLE_BOSS_ATTACK_A = 
{
	ANIM_NAME					= "AttackA",
	PLAY_TYPE					= XSKIN_ANIM_PLAYTYPE["XAP_ONE_WAIT"],
	TRANSITION					= FALSE,

	ANIM_SPEED					= 1.2,
	
	CAN_PUSH_UNIT				= TRUE,
	CAN_PASS_UNIT				= FALSE,

	SOUND_PLAY0			        = { 0.371, "Coacktriglevoice_AttackA.ogg", 50 },
	SOUND_PLAY1			        = { 0.400, "Coacktrigle_AttackA_jump1.ogg" },
	SOUND_PLAY2			        = { 1.459, "Coacktrigle_AttackA_jump2.ogg" },
	
	SPEED_X						= 200,
	SPEED_Y						= 0,	

	VIEW_TARGET					= TRUE,
	ALLOW_DIR_CHANGE			= FALSE,	
	IMMADIATE_PACKET_SEND		= TRUE,
	
	EVENT_PROCESS = 
	{	
		{ STATE_CHANGE_TYPE["SCT_FOOT_ON_LINE_FALSE_DOWN"],	"COACKATRIGLE_BOSS_JUMP_DOWN",								},
		{ STATE_CHANGE_TYPE["SCT_MOTION_END"],			"COACKATRIGLE_BOSS_WAIT",								},	
	},
	

	ATTACK_TIME0				= { 0.45, 0.75, },
			
	DAMAGE_DATA = 
	{
		DAMAGE_TYPE		= DAMAGE_TYPE["DT_PHYSIC"],
		HIT_TYPE		= HIT_TYPE["HT_PUNCH_HIT"],
		REACT_TYPE		= REACT_TYPE["RT_SMALL_DAMAGE"],
		
		DAMAGE = 
		{
			PHYSIC		= 1.0,
		},
		
		
		BACK_SPEED_X			= 0,
		BACK_SPEED_Y			= 0,

        CAN_REVENGE				= TRUE,

		RE_ATTACK				= TRUE,		
		HIT_GAP					= 0.12,	
		

	},
}

COACKATRIGLE_BOSS_MAGIC_ATTACK_A_READY = 
{
	ANIM_NAME					= "MagicAttackAReady",
	PLAY_TYPE					= XSKIN_ANIM_PLAYTYPE["XAP_ONE_WAIT"],
	TRANSITION					= FALSE,
	
	--VIEW_TARGET				= TRUE,
	
	CAN_PUSH_UNIT				= TRUE,
	CAN_PASS_UNIT				= FALSE,
	
	SUPER_ARMOR					= TRUE,
	

	IMMADIATE_PACKET_SEND		= TRUE,
	EVENT_INTERVAL_TIME0		= 1,

	EVENT_PROCESS = 
	{		
		{ STATE_CHANGE_TYPE["SCT_FOOT_ON_LINE_FALSE_DOWN"],	"COACKATRIGLE_BOSS_JUMP_DOWN",					},

		{ STATE_CHANGE_TYPE["SCT_MOTION_END"],			"COACKATRIGLE_BOSS_MAGIC_ATTACK_A",					},


	},
}



COACKATRIGLE_BOSS_MAGIC_ATTACK_A = 
{
	ANIM_NAME					= "MagicAttackA",
	PLAY_TYPE					= XSKIN_ANIM_PLAYTYPE["XAP_ONE_WAIT"],
	TRANSITION					= FALSE,
	
	CAN_PUSH_UNIT				= TRUE,
	CAN_PASS_UNIT				= FALSE,
	
	SUPER_ARMOR					= TRUE,

	SPEED_X						= 0,
	SPEED_Y						= 0,	

   	SOUND_PLAY0			= { 0.001, "Coacktrigle_MagicAttackA.ogg" },

	VIEW_TARGET					= FALSE,
	ALLOW_DIR_CHANGE			= FALSE,	
	IMMADIATE_PACKET_SEND		= TRUE,
	

	TALK_BOX = 
	{
		{ RATE = 10, MESSAGE = STR_ID_1473 },
		{ RATE = 10, MESSAGE = STR_ID_1474 },
	},
--[[		
   	PARTICLE_SEQ = 
	{
		--Major, time, Name, weaponBonePos, Pos, StateEndDelete, bTrace, posx, posy, posz, bApplyUnitRotation, rotx, roty, rotz,			
		{ FALSE, 0.01, "Nasod_Element_Fire_Combo01", FALSE, "Bip01_L_Finger1Nub", TRUE, TRUE, 0, 0, 50, },
		{ FALSE, 0.36, "Nasod_Element_Fire_Combo01", FALSE, "Bip01_L_Finger1Nub", TRUE, TRUE, 0, 0, 50, },		
		
	},	
--]]

	
	EFFECT_SET_LIST =
	{
		"Coackatrigle_Magic_Attack_A", 0,	
	},
	
	DELETE_EFFECT_SET_ON_STATE_END 	= TRUE,

	EVENT_PROCESS = 
	{	
		{ STATE_CHANGE_TYPE["SCT_FOOT_ON_LINE_FALSE_DOWN"],	"COACKATRIGLE_BOSS_JUMP_DOWN",								},
		{ STATE_CHANGE_TYPE["SCT_MOTION_END"],				"COACKATRIGLE_BOSS_WAIT",									},	
	},

}


COACKATRIGLE_BOSS_DAMAGE_FRONT =
{
	ANIM_NAME					= "DamageFront",
	PLAY_TYPE					= XSKIN_ANIM_PLAYTYPE["XAP_ONE_WAIT"],
	TRANSITION					= FALSE,
	LAND_CONNECT				= FALSE,
	
	CAN_PUSH_UNIT				= TRUE,
	CAN_PASS_UNIT				= FALSE,
	
	SOUND_PLAY0			        = { 0.001, "CoacktrigleVoice_Damage.ogg", 30 },
	
	EVENT_PROCESS = 
	{
		{ STATE_CHANGE_TYPE["SCT_MOTION_END"],					"COACKATRIGLE_BOSS_WAIT",				},
	},
}


COACKATRIGLE_BOSS_DAMAGE_BACK =
{
	ANIM_NAME					= "DamageBack",
	PLAY_TYPE					= XSKIN_ANIM_PLAYTYPE["XAP_ONE_WAIT"],
	TRANSITION					= FALSE,
	LAND_CONNECT				= FALSE,
	
	CAN_PUSH_UNIT				= TRUE,
	CAN_PASS_UNIT				= FALSE,
	
	SOUND_PLAY0			        = { 0.001, "CoacktrigleVoice_Damage.ogg", 30 },
	
	EVENT_PROCESS = 
	{
		{ STATE_CHANGE_TYPE["SCT_MOTION_END"],					"COACKATRIGLE_BOSS_WAIT",				},
	},
}


COACKATRIGLE_BOSS_RIDE_DAMAGE_FRONT =
{
	ANIM_NAME					= "DamageFront",
	PLAY_TYPE					= XSKIN_ANIM_PLAYTYPE["XAP_ONE_WAIT"],
	TRANSITION					= FALSE,
	LAND_CONNECT				= FALSE,
	
	CAN_PUSH_UNIT				= TRUE,
	CAN_PASS_UNIT				= FALSE,
	
	SOUND_PLAY0			        = { 0.001, "CoacktrigleVoice_Damage.ogg", 30 },
	
	EVENT_PROCESS = 
	{
		{ STATE_CHANGE_TYPE["SCT_MOTION_END"],					"COACKATRIGLE_BOSS_WAIT",				},
	},
}


COACKATRIGLE_BOSS_RIDE_DAMAGE_BACK =
{
	ANIM_NAME					= "DamageBack",
	PLAY_TYPE					= XSKIN_ANIM_PLAYTYPE["XAP_ONE_WAIT"],
	TRANSITION					= FALSE,
	LAND_CONNECT				= FALSE,
	
	CAN_PUSH_UNIT				= TRUE,
	CAN_PASS_UNIT				= FALSE,
	
	SOUND_PLAY0			        = { 0.001, "CoacktrigleVoice_Damage.ogg", 30 },
	
	EVENT_PROCESS = 
	{
		{ STATE_CHANGE_TYPE["SCT_MOTION_END"],					"COACKATRIGLE_BOSS_WAIT",				},
	},
}



COACKATRIGLE_BOSS_WALK = 
{
	ANIM_NAME					= "Walk",
	PLAY_TYPE					= XSKIN_ANIM_PLAYTYPE["XAP_LOOP"],
	TRANSITION					= TRUE,
	
	CAN_PUSH_UNIT				= FALSE,
	CAN_PASS_UNIT				= FALSE,
	
	SOUND_PLAY0			        = { 0.001, "Coacktrigle_Walk.ogg", 20 },
	
	PASSIVE_SPEED_X				= INIT_PHYSIC["WALK_SPEED"],
	
	ALLOW_DIR_CHANGE			= TRUE,
	IMMADIATE_PACKET_SEND		= TRUE,
	
	EVENT_INTERVAL_TIME0		= 2,
	
	EVENT_PROCESS = 
	{		
		{ STATE_CHANGE_TYPE["SCT_FOOT_ON_LINE_FALSE_DOWN"],	"COACKATRIGLE_BOSS_JUMP_DOWN_DIR",				},
		
		{ STATE_CHANGE_TYPE["SCT_CONDITION_TABLE"],			"COACKATRIGLE_BOSS_ATTACK_A",				"CT_COACKATRIGLE_BOSS_ATTACK_A",			},
		-- { STATE_CHANGE_TYPE["SCT_CONDITION_TABLE"],			"COACKATRIGLE_BOSS_MAGIC_ATTACK_A_READY",				"CT_COACKATRIGLE_BOSS_MAGIC_ATTACK_A_READY",			},


		{ STATE_CHANGE_TYPE["SCT_AI_WAIT"],					"COACKATRIGLE_BOSS_WAIT",						},
		{ STATE_CHANGE_TYPE["SCT_AI_JUMP"],					"COACKATRIGLE_BOSS_JUMP_UP",						},
		{ STATE_CHANGE_TYPE["SCT_AI_JUMP_DIR"],				"COACKATRIGLE_BOSS_JUMP_UP_DIR",					},
		{ STATE_CHANGE_TYPE["SCT_AI_DOWN"],					"COACKATRIGLE_BOSS_JUMP_DOWN",					},
		{ STATE_CHANGE_TYPE["SCT_AI_DOWN_DIR"],				"COACKATRIGLE_BOSS_JUMP_DOWN_DIR",				},
		
	},
	
	CT_COACKATRIGLE_BOSS_ATTACK_A = 
	{
		EVENT_INTERVAL_ID			= 0,
		DISTANCE_TO_TARGET_NEAR		= 800,
		SAME_LINE_WITH_TARGET			= TRUE,
		RATE						= 70,
	},
}

COACKATRIGLE_BOSS_PASS_WALK = 
{
	ANIM_NAME					= "Walk",
	PLAY_TYPE					= XSKIN_ANIM_PLAYTYPE["XAP_LOOP"],
	TRANSITION					= TRUE,
	
	CAN_PUSH_UNIT				= FALSE,
	CAN_PASS_UNIT				= TRUE,
	
	SOUND_PLAY0			        = { 0.001, "Coacktrigle_Walk.ogg", 20 },
	
	PASSIVE_SPEED_X				= INIT_PHYSIC["WALK_SPEED"]*0.8,
	
	ALLOW_DIR_CHANGE			= TRUE,
	IMMADIATE_PACKET_SEND		= TRUE,
	
	EVENT_INTERVAL_TIME0		= 2,
	
	EVENT_PROCESS = 
	{		
		{ STATE_CHANGE_TYPE["SCT_FOOT_ON_LINE_FALSE_DOWN"],	"COACKATRIGLE_BOSS_JUMP_DOWN_DIR",				},
		
		{ STATE_CHANGE_TYPE["SCT_CONDITION_TABLE"],			"COACKATRIGLE_BOSS_ATTACK_A",				"CT_COACKATRIGLE_BOSS_ATTACK_A",			},
		-- { STATE_CHANGE_TYPE["SCT_CONDITION_TABLE"],			"COACKATRIGLE_BOSS_MAGIC_ATTACK_A_READY",				"CT_COACKATRIGLE_BOSS_MAGIC_ATTACK_A_READY",			},


		{ STATE_CHANGE_TYPE["SCT_AI_WAIT"],					"COACKATRIGLE_BOSS_WAIT",						},
		{ STATE_CHANGE_TYPE["SCT_AI_JUMP"],					"COACKATRIGLE_BOSS_JUMP_UP",						},
		{ STATE_CHANGE_TYPE["SCT_AI_JUMP_DIR"],				"COACKATRIGLE_BOSS_JUMP_UP_DIR",					},
		{ STATE_CHANGE_TYPE["SCT_AI_DOWN"],					"COACKATRIGLE_BOSS_JUMP_DOWN",					},
		{ STATE_CHANGE_TYPE["SCT_AI_DOWN_DIR"],				"COACKATRIGLE_BOSS_JUMP_DOWN_DIR",				},
		
	},
	
	CT_COACKATRIGLE_BOSS_ATTACK_A = 
	{
		EVENT_INTERVAL_ID			= 0,
		DISTANCE_TO_TARGET_NEAR		= 800,
		SAME_LINE_WITH_TARGET			= TRUE,
		RATE						= 70,
	},
}



COACKATRIGLE_BOSS_JUMP_UP = 
{
	ANIM_NAME					= "JumpUp",
	PLAY_TYPE					= XSKIN_ANIM_PLAYTYPE["XAP_LOOP"],
	TRANSITION					= TRUE,
	LAND_CONNECT				= FALSE,
	
	CAN_PUSH_UNIT				= FALSE,
	CAN_PASS_UNIT				= FALSE,
	
	SPEED_X						= 0,
	SPEED_Y						= INIT_PHYSIC["JUMP_SPEED"],
	ADD_POS_Y					= 45,
	
	IMMADIATE_PACKET_SEND		= TRUE,
	
	EVENT_PROCESS = 
	{		
		{ STATE_CHANGE_TYPE["SCT_NEGATIVE_Y_SPEED"],		"COACKATRIGLE_BOSS_JUMP_DOWN",				},
	},
}

COACKATRIGLE_BOSS_JUMP_DOWN = 
{
	ANIM_NAME					= "JumpDown",
	PLAY_TYPE					= XSKIN_ANIM_PLAYTYPE["XAP_LOOP"],
	TRANSITION					= TRUE,
	LAND_CONNECT				= FALSE,
	
	CAN_PUSH_UNIT				= FALSE,
	CAN_PASS_UNIT				= FALSE,
	
	
	
	IMMADIATE_PACKET_SEND		= TRUE,
		
	EVENT_PROCESS = 
	{		
		{ STATE_CHANGE_TYPE["SCT_FOOT_ON_LINE_TRUE"],		"COACKATRIGLE_BOSS_JUMP_LANDING",				},
	},
}

COACKATRIGLE_BOSS_JUMP_UP_DIR = 
{
	ANIM_NAME					= "JumpUp",
	PLAY_TYPE					= XSKIN_ANIM_PLAYTYPE["XAP_LOOP"],
	TRANSITION					= TRUE,
	LAND_CONNECT				= FALSE,
	
	CAN_PUSH_UNIT				= FALSE,
	CAN_PASS_UNIT				= FALSE,
	
	PASSIVE_SPEED_X				= INIT_PHYSIC["WALK_SPEED"],
	SPEED_Y						= INIT_PHYSIC["JUMP_SPEED"],
	ADD_POS_Y					= 45,
	
	IMMADIATE_PACKET_SEND		= TRUE,
	
	EVENT_PROCESS = 
	{		
		{ STATE_CHANGE_TYPE["SCT_NEGATIVE_Y_SPEED"],		"COACKATRIGLE_BOSS_JUMP_DOWN_DIR",				},
	},
}

COACKATRIGLE_BOSS_JUMP_DOWN_DIR = 
{
	ANIM_NAME					= "JumpDwon",
	PLAY_TYPE					= XSKIN_ANIM_PLAYTYPE["XAP_LOOP"],
	TRANSITION					= TRUE,
	LAND_CONNECT				= FALSE,
	
	CAN_PUSH_UNIT				= FALSE,
	CAN_PASS_UNIT				= FALSE,
	
	
	
	PASSIVE_SPEED_X				= INIT_PHYSIC["WALK_SPEED"],
	
	IMMADIATE_PACKET_SEND		= TRUE,
		
	EVENT_PROCESS = 
	{		
		{ STATE_CHANGE_TYPE["SCT_FOOT_ON_LINE_TRUE"],		"COACKATRIGLE_BOSS_JUMP_LANDING",				},
	},
}

COACKATRIGLE_BOSS_JUMP_LANDING = 
{
	ANIM_NAME					= "JumpLanding",
	PLAY_TYPE					= XSKIN_ANIM_PLAYTYPE["XAP_ONE_WAIT"],
	TRANSITION					= TRUE,
	LAND_CONNECT				= FALSE,
	
	CAN_PUSH_UNIT				= FALSE,
	CAN_PASS_UNIT				= FALSE,
	
	SOUND_PLAY0			        = { 0.050, "Coacktrigle_JumpLanding.ogg" },
	
	SPEED_X						= 0,
	SPEED_Y						= 0,
		
	IMMADIATE_PACKET_SEND		= TRUE,

	EVENT_PROCESS = 
	{		
		{ STATE_CHANGE_TYPE["SCT_FOOT_ON_LINE_FALSE_DOWN"],	"COACKATRIGLE_BOSS_JUMP_DOWN",				},
		{ STATE_CHANGE_TYPE["SCT_MOTION_END"],				"COACKATRIGLE_BOSS_WAIT",					},
	},
}




COACKATRIGLE_BOSS_RIDE_ATTACK_B_JUMP_UP_DIR = 
{
	ANIM_NAME					= "JumpUp",
	PLAY_TYPE					= XSKIN_ANIM_PLAYTYPE["XAP_LOOP"],
	TRANSITION					= TRUE,
	LAND_CONNECT				= FALSE,
	
	SUPER_ARMOR					= TRUE,
	
	CAN_PUSH_UNIT				= FALSE,
	CAN_PASS_UNIT				= FALSE,
	
	PASSIVE_SPEED_X				= INIT_PHYSIC["WALK_SPEED"],
	SPEED_Y						= INIT_PHYSIC["JUMP_SPEED"],
	ADD_POS_Y					= 45,
	
	IMMADIATE_PACKET_SEND		= TRUE,
	
	EVENT_PROCESS = 
	{		
		{ STATE_CHANGE_TYPE["SCT_NEGATIVE_Y_SPEED"],		"COACKATRIGLE_BOSS_RIDE_ATTACK_B_JUMP_DOWN_DIR",				},
	},
}

COACKATRIGLE_BOSS_RIDE_ATTACK_B_JUMP_DOWN_DIR = 
{
	ANIM_NAME					= "JumpDwon",
	PLAY_TYPE					= XSKIN_ANIM_PLAYTYPE["XAP_LOOP"],
	TRANSITION					= TRUE,
	LAND_CONNECT				= FALSE,
	
	CAN_PUSH_UNIT				= FALSE,
	CAN_PASS_UNIT				= FALSE,
	
	SUPER_ARMOR					= TRUE,
	
	
	PASSIVE_SPEED_X				= INIT_PHYSIC["WALK_SPEED"],
	
	IMMADIATE_PACKET_SEND		= TRUE,
		
	EVENT_PROCESS = 
	{		
		{ STATE_CHANGE_TYPE["SCT_FOOT_ON_LINE_TRUE"],		"COACKATRIGLE_BOSS_RIDE_ATTACK_B_JUMP_LANDING",				},
	},
}

COACKATRIGLE_BOSS_RIDE_ATTACK_B_JUMP_LANDING = 
{
	ANIM_NAME					= "JumpLanding",
	PLAY_TYPE					= XSKIN_ANIM_PLAYTYPE["XAP_ONE_WAIT"],
	TRANSITION					= TRUE,
	LAND_CONNECT				= FALSE,
	
	SUPER_ARMOR					= TRUE,
	
	CAN_PUSH_UNIT				= FALSE,
	CAN_PASS_UNIT				= FALSE,
	
	SOUND_PLAY0			        = { 0.050, "Coacktrigle_JumpLanding.ogg" },
	
	SPEED_X						= 0,
	SPEED_Y						= 0,
		
	IMMADIATE_PACKET_SEND		= TRUE,

	EVENT_PROCESS = 
	{		
		{ STATE_CHANGE_TYPE["SCT_FOOT_ON_LINE_FALSE_DOWN"],	"COACKATRIGLE_BOSS_JUMP_DOWN",				},
		{ STATE_CHANGE_TYPE["SCT_MOTION_END"],				"COACKATRIGLE_BOSS_WAIT",					},
	},
}





COACKATRIGLE_BOSS_DAMAGE_DOWN = 
{
	ANIM_NAME					= "DamageDown",
		
	PLAY_TYPE					= XSKIN_ANIM_PLAYTYPE["XAP_ONE_WAIT"],
	TRANSITION					= FALSE,
	LAND_CONNECT				= FALSE,

	SUPER_ARMOR					= TRUE,
	DEFENCE						= { 0, 100, 70, },
	
	CAN_PUSH_UNIT				= TRUE,
	CAN_PASS_UNIT				= FALSE,

    --SOUND_PLAY0			= { 0.1, "LizardHigh_Scream.ogg" , 50 },
	
	
	EVENT_PROCESS = 
	{
		{ STATE_CHANGE_TYPE["SCT_FOOT_ON_LINE_FALSE_DOWN"],		"COACKATRIGLE_BOSS_DAMAGE_AIR_FALL",			},
		{ STATE_CHANGE_TYPE["SCT_MOTION_END"],					"COACKATRIGLE_BOSS_STAND_UP",			},
	},
}


COACKATRIGLE_BOSS_DAMAGE_AIR = 
{
	ANIM_NAME					= "DamageAir",
	PLAY_TYPE					= XSKIN_ANIM_PLAYTYPE["XAP_ONE_WAIT"],
	TRANSITION					= FALSE,
	LAND_CONNECT				= FALSE,
	
	CAN_PUSH_UNIT				= TRUE,
	CAN_PASS_UNIT				= FALSE,
	
	EVENT_PROCESS = 
	{
		{ STATE_CHANGE_TYPE["SCT_FOOT_ON_LINE_TRUE"],			"COACKATRIGLE_BOSS_WAIT",					},
	},
}


COACKATRIGLE_BOSS_DAMAGE_AIR_DOWN = 
{
	ANIM_NAME					= "DamageAirDown",
	PLAY_TYPE					= XSKIN_ANIM_PLAYTYPE["XAP_ONE_WAIT"],
	TRANSITION					= FALSE,
	LAND_CONNECT				= FALSE,
	
	CAN_PUSH_UNIT				= TRUE,
	CAN_PASS_UNIT				= FALSE,
	
	EVENT_PROCESS = 
	{
		{ STATE_CHANGE_TYPE["SCT_FOOT_ON_LINE_TRUE"],			"COACKATRIGLE_BOSS_DAMAGE_AIR_DOWN_LANDING",	},
	},
}


COACKATRIGLE_BOSS_DAMAGE_AIR_UP = 
{
	ANIM_NAME					= "DamageAirUp",
	PLAY_TYPE					= XSKIN_ANIM_PLAYTYPE["XAP_ONE_WAIT"],
	TRANSITION					= FALSE,
	LAND_CONNECT				= FALSE,
	
	CAN_PUSH_UNIT				= TRUE,
	CAN_PASS_UNIT				= FALSE,
	
		
	EVENT_PROCESS = 
	{
		{ STATE_CHANGE_TYPE["SCT_NEGATIVE_Y_SPEED"],		"COACKATRIGLE_BOSS_DAMAGE_AIR_FALL",			},
		{ STATE_CHANGE_TYPE["SCT_FOOT_ON_LINE_TRUE"],		"COACKATRIGLE_BOSS_DAMAGE_AIR_DOWN_LANDING",	},
	},
	
}


COACKATRIGLE_BOSS_DAMAGE_AIR_FALL = 
{
	ANIM_NAME					= "DamageAirFall",
	PLAY_TYPE					= XSKIN_ANIM_PLAYTYPE["XAP_ONE_WAIT"],
	TRANSITION					= FALSE,
	LAND_CONNECT				= FALSE,
	
	CAN_PUSH_UNIT				= TRUE,
	CAN_PASS_UNIT				= FALSE,
	
	EVENT_PROCESS = 
	{
		{ STATE_CHANGE_TYPE["SCT_POSITIVE_Y_SPEED"],		"COACKATRIGLE_BOSS_DAMAGE_AIR_UP",			},
		{ STATE_CHANGE_TYPE["SCT_FOOT_ON_LINE_TRUE"],		"COACKATRIGLE_BOSS_DAMAGE_AIR_DOWN_LANDING",	},
	},
}



COACKATRIGLE_BOSS_DAMAGE_AIR_DOWN_LANDING = 
{
	ANIM_NAME					= "DamageAirDownLanding",
	PLAY_TYPE					= XSKIN_ANIM_PLAYTYPE["XAP_ONE_WAIT"],
	TRANSITION					= FALSE,
	LAND_CONNECT				= FALSE,
	
	SUPER_ARMOR					= TRUE,
	DEFENCE						= { 0, 100, 70, },
	
	CAN_PUSH_UNIT				= TRUE,
	CAN_PASS_UNIT				= FALSE,
	
	EVENT_PROCESS = 
	{
		{ STATE_CHANGE_TYPE["SCT_FOOT_ON_LINE_FALSE_DOWN"],	"COACKATRIGLE_BOSS_DAMAGE_AIR_FALL",			},
		{ STATE_CHANGE_TYPE["SCT_MOTION_END"],				"COACKATRIGLE_BOSS_STAND_UP",			},
	},
	
}


COACKATRIGLE_BOSS_STAND_UP = 
{
	ANIM_NAME					= "DamageStandUp",
	PLAY_TYPE					= XSKIN_ANIM_PLAYTYPE["XAP_ONE_WAIT"],
	TRANSITION					= FALSE,
	LAND_CONNECT				= FALSE,	
	
	SUPER_ARMOR					= TRUE,
	DEFENCE						= { 0, 100, 70, },
	
	CAN_PUSH_UNIT				= TRUE,
	CAN_PASS_UNIT				= FALSE,
	
	EVENT_PROCESS = 
	{
		{ STATE_CHANGE_TYPE["SCT_FOOT_ON_LINE_FALSE_DOWN"],	"COACKATRIGLE_BOSS_JUMP_DOWN",			},
		{ STATE_CHANGE_TYPE["SCT_MOTION_END"],				"COACKATRIGLE_BOSS_WAIT",				},
	},
}



COACKATRIGLE_BOSS_DYING = 
{
	ANIM_NAME					= "Dying",
	PLAY_TYPE					= XSKIN_ANIM_PLAYTYPE["XAP_ONE_WAIT"],
	TRANSITION					= FALSE,
	LAND_CONNECT				= FALSE,

	INVINCIBLE					= { 0, 100, }, 		
	
	CAN_PUSH_UNIT				= FALSE,
	CAN_PASS_UNIT				= TRUE,
	
	SOUND_PLAY0			        = { 0.346, "CoacktrigleVoice_Dying.ogg" },
	SOUND_PLAY1			        = { 0.718, "Coacktrigle_DyingFall.ogg" },
	
	--NEVER_MOVE					= TRUE,
	DYING_END					= TRUE,
	DYING_SPEED					= 1,
	
	IMMADIATE_PACKET_SEND		= TRUE,
}
	

function COACKATRIGLE_BOSS_JUMP_LANDING_STATE_START( pKTDXApp, pX2Game, pNPCUnit )

	pUnit = pNPCUnit:GetRideUnit_LUA()
	if pUnit ~= nil then
		pUnit:StateChange_LUA("GLITER_LANCE_GREAT_BOSS_RIDE_JUMP_LANDING", true)
	end
end


function COACKATRIGLE_BOSS_RIDE_ATTACK_B_JUMP_LANDING_STATE_START( pKTDXApp, pX2Game, pNPCUnit )

	pUnit = pNPCUnit:GetRideUnit_LUA()
	if pUnit ~= nil then
		pUnit:StateChange_LUA("GLITER_LANCE_GREAT_BOSS_RIDE_ATTACK_B_JUMP_LANDING", true)
	end
end





function COACKATRIGLE_BOSS_RIDE_ATTACK_B_JUMP_LANDING_STATE_FRAME_MOVE( pKTDXApp, pX2Game, pNPCUnit )


    if pNPCUnit:AnimEventTimer_LUA( 0.1 ) then    

        pX2Game:GetX2Camera():GetCamera():UpDownCrashCameraNoReset( 20.0, 0.5 )
        
        EffectPos = pNPCUnit:GetBonePos_LUA( "Bip01" )
        EffectPos.y = EffectPos.y - 100
        pMajorParticle = pX2Game:GetMajorParticle()
		pMajorParticle:GameUnitCreateSequence_LUA( pNPCUnit, "Smoke_Summon_Boss_JumpLanding01", EffectPos, D3DXVECTOR2(-1,-1), D3DXVECTOR2(-1,-1) )
		
    end
end





function COACKATRIGLE_BOSS_DYING_STATE_START( pKTDXApp, pX2Game, pNPCUnit )

	pUnit = pNPCUnit:GetRideUnit_LUA()
	if pUnit ~= nil then
		pUnit:RideOff_LUA()
	end
end


function COACKATRIGLE_BOSS_MAGIC_ATTACK_A_FRAME_MOVE( pKTDXApp, pX2Game, pNPCUnit )



end


function COACKATRIGLE_BOSS_MAGIC_ATTACK_A_STATE_END( pKTDXApp, pX2Game, pNPCUnit )

	
end

function COACKATRIGLE_BOSS_DAMAGE_AIR_UP_STATE_START( pKTDXApp, pX2Game, pNPCUnit )

	pUnit = pNPCUnit:GetRideUnit_LUA()
	if pUnit ~= nil then
		pUnit:RideOff_LUA()
	end
	
end




function COACKATRIGLE_BOSS_DAMAGE_DOWN_FRAME_MOVE( pKTDXApp, pX2Game, pNPCUnit )

	if pNPCUnit:AnimEventTimer_LUA( 0.01 ) then
		pUnit = pNPCUnit:GetRideUnit_LUA()
		if pUnit ~= nil then
			pUnit:RideOff_LUA()
		end
	end


	if pNPCUnit:AnimEventTimer_LUA( 0.45 ) then
		pNPCUnit:PlaySound_LUA( "Down.ogg" )		
		pMinorParticle = pX2Game:GetMinorParticle()
		pMinorParticle:GameUnitCreateSequence_LUA( pNPCUnit, "DownSmoke", pNPCUnit:GetLandPosition_LUA(), D3DXVECTOR2(100,100), D3DXVECTOR2(7,-1) )
	end

end

function COACKATRIGLE_BOSS_DAMAGE_AIR_DOWN_LANDING_FRAME_MOVE( pKTDXApp, pX2Game, pNPCUnit )

	if pNPCUnit:AnimEventTimer_LUA( 0.01 ) then
		
		pUnit = pNPCUnit:GetRideUnit_LUA()
		if pUnit ~= nil then
			pUnit:RideOff_LUA()
		end		
		
		
		pMinorParticle = pX2Game:GetMinorParticle()
		pos = pNPCUnit:GetLandPosition_LUA()
		pMinorParticle:GameUnitCreateSequence_LUA( pNPCUnit, "DownSmoke", pos, D3DXVECTOR2(100,100), D3DXVECTOR2(7,-1) )
		pos.y = pos.y + 5
		pMinorParticle:GameUnitCreateSequence_LUA( pNPCUnit, "GroundShockWave", pos, D3DXVECTOR2(100,100), D3DXVECTOR2(1,-1) )
		pParticle = pMinorParticle:GameUnitCreateSequence_LUA( pNPCUnit, "AirDownTick", pNPCUnit:GetPos(), D3DXVECTOR2(200,200), D3DXVECTOR2(10,-1) )
		if pParticle ~= nil then 
			pParticle:SetLandPosition( pos.y - 5 )
		end
		
		if GetDistance_LUA( pNPCUnit:GetPos(), pX2Game:GetFocusUnitPos_LUA() ) < 500 then
			pX2Game:GetX2Camera():GetCamera():UpDownCrashCameraNoReset( 10.0, 0.1 )
		end		
		
	elseif pNPCUnit:AnimEventTimer_LUA( 0.1 ) then
		pNPCUnit:PlaySound_LUA( "Down.ogg" )		
		pMinorParticle = pX2Game:GetMinorParticle()
		pMinorParticle:GameUnitCreateSequence_LUA( pNPCUnit, "DownSmoke", pNPCUnit:GetLandPosition_LUA(), D3DXVECTOR2(100,100), D3DXVECTOR2(7,-1) )
		
	end

end




------------------------------------------------------------------------------
-- UTIL FUNCTION
------------------------------------------------------------------------------

------------------------------------------------------------------------------
function MovePos( pos, dirvector, dist )
	
	pos.x = pos.x + dist * dirvector.x
	pos.y = pos.y + dist * dirvector.y
	pos.z = pos.z + dist * dirvector.z
	
	return pos
	
end


