-- lua header. UTF-8 인코딩 인식을 위해 이 줄은 지우지 마세요.


-- mushroom.lua


INIT_SYSTEM = 
{
	UNIT_WIDTH		= 50.0,
	UNIT_LAYER		= X2_LAYER["XL_UNIT_0"],
}


INIT_DEVICE = 
{
	READY_TEXTURE = 
	{
	},
	
	READY_SOUND = 
	{
		"PoisonPowder.ogg",
	},
	
	READY_XSKIN_MESH = 
	{
		"GuideArrow_AttackBox.X",
	},
}

INIT_MOTION = 
{
	MOTION_FILE_NAME		= "Motion_Mushroom_Poison.x",
	MOTION_ANI_TEX_XET		= "Motion_Mushroom_Poison.xet",
}

INIT_PHYSIC = 
{
	RELOAD_ACCEL		= 2000,
	G_ACCEL				= 4000,
	MAX_G_SPEED			= -2000,
	
	WALK_SPEED			= 700,
	RUN_SPEED			= 700,
	JUMP_SPEED			= 1500,
	DASH_JUMP_SPEED		= 2300,
}


INIT_COMPONENT = 
{
	MAX_HP				= 2000,
	MP_CHANGE_RATE		= 1,
	MP_CHARGE_RATE		= 130,
	
	USE_SLASH_TRACE		= FALSE,
	
	SHADOW_SIZE			= 200,
	SHADOW_FILE_NAME	= "shadow.dds",
	
	SMALL_HP_BAR_BLUE	= "Small_HP_bar_Blue.TGA",
	SMALL_HP_BAR_RED	= "Small_HP_bar_Red.TGA",
	SMALL_HP_BAR_YELLOW = "Small_HP_bar_Yellow.TGA",
	
	QUESTION_MARK_SEQ		= "QuestionMarkNPC",
	EXCLAMATION_MARK_SEQ	= "ExclamationMarkNPC",
	
	HYPER_MODE_COUNT	= 0,
	MAX_HYPER_MODE_TIME	= 30,
	
	HITTED_TYPE			= HITTED_TYPE["HTD_MEAT"],
	
	FALL_DOWN			= TRUE,
	
	DAMAGE_DOWN         = FALSE,
	
	SUMMON_TIME			= 180,
	

}

INIT_STATE = 
{

	{ STATE_NAME = "CSM_MUSHROOM_POISON_START",						},
	{ STATE_NAME = "CSM_MUSHROOM_POISON_WAIT",						},
	{ STATE_NAME = "CSM_MUSHROOM_POISON_WAIT_HABIT",				},
	
	{ STATE_NAME = "CSM_MUSHROOM_POISON_WALK",						LUA_FRAME_MOVE_FUNC = "CSM_MUSHROOM_POISON_WALK_FRAME_MOVE", LUA_STATE_END_FUNC = "CSM_MUSHROOM_POISON_WALK_STATE_END"	},
	{ STATE_NAME = "CSM_MUSHROOM_POISON_JUMP_UP",					},
	{ STATE_NAME = "CSM_MUSHROOM_POISON_JUMP_DOWN",					LUA_STATE_END_FUNC = "CSM_MUSHROOM_POISON_JUMP_DOWN_STATE_END"					},
	{ STATE_NAME = "CSM_MUSHROOM_POISON_JUMP_UP_DIR",				},
	{ STATE_NAME = "CSM_MUSHROOM_POISON_JUMP_DOWN_DIR",				LUA_STATE_END_FUNC = "CSM_MUSHROOM_POISON_JUMP_DOWN_DIR_STATE_END"				},
	{ STATE_NAME = "CSM_MUSHROOM_POISON_JUMP_LANDING",				},
	
	{ STATE_NAME = "CSM_MUSHROOM_POISON_ATTACK",					STATE_COOL_TIME = 3,			},
	{ STATE_NAME = "CSM_MUSHROOM_POISON_ATTACK_POISON_POWDER",		STATE_COOL_TIME = 8,		LUA_FRAME_MOVE_FUNC = "CSM_MUSHROOM_POISON_ATTACK_POISON_POWDER_FRAME_MOVE",	},
	
	{ STATE_NAME = "CSM_MUSHROOM_POISON_END",						},
	
	
	
	--리액션 관련

	{ STATE_NAME = "CSM_MUSHROOM_POISON_DAMAGE",					LUA_FRAME_MOVE_FUNC = "CSM_MUSHROOM_POISON_DAMAGE_FRAME_MOVE"					},
	{ STATE_NAME = "CSM_MUSHROOM_POISON_DAMAGE_DOWN_FRONT",			LUA_FRAME_MOVE_FUNC = "CSM_MUSHROOM_POISON_DAMAGE_DOWN_FRONT_FRAME_MOVE"		},
	{ STATE_NAME = "CSM_MUSHROOM_POISON_DAMAGE_DOWN_BACK",			LUA_FRAME_MOVE_FUNC = "CSM_MUSHROOM_POISON_DAMAGE_DOWN_BACK_FRAME_MOVE"		},
	{ STATE_NAME = "CSM_MUSHROOM_POISON_DAMAGE_FLY_FRONT",			},
	{ STATE_NAME = "CSM_MUSHROOM_POISON_DAMAGE_FLY_BACK",			},
	{ STATE_NAME = "CSM_MUSHROOM_POISON_DAMAGE_AIR",				},
	{ STATE_NAME = "CSM_MUSHROOM_POISON_DAMAGE_AIR_DOWN",			},
	{ STATE_NAME = "CSM_MUSHROOM_POISON_DAMAGE_AIR_UP",				},
	{ STATE_NAME = "CSM_MUSHROOM_POISON_DAMAGE_AIR_FALL",			},	
	{ STATE_NAME = "CSM_MUSHROOM_POISON_DAMAGE_AIR_DOWN_LANDING",	LUA_FRAME_MOVE_FUNC = "CSM_MUSHROOM_POISON_DAMAGE_AIR_DOWN_LANDING_FRAME_MOVE"	},
	{ STATE_NAME = "CSM_MUSHROOM_POISON_STAND_UP_FRONT",			},
	{ STATE_NAME = "CSM_MUSHROOM_POISON_STAND_UP_BACK",				},
	
	{ STATE_NAME = "CSM_MUSHROOM_POISON_DYING_LAND_FRONT",			LUA_STATE_START_FUNC = "CSM_MUSHROOM_POISON_DYING_LAND_STATE_START", },
	{ STATE_NAME = "CSM_MUSHROOM_POISON_DYING_LAND_BACK",			LUA_STATE_START_FUNC = "CSM_MUSHROOM_POISON_DYING_LAND_STATE_START", },
	{ STATE_NAME = "CSM_MUSHROOM_POISON_DYING_SKY",					LUA_STATE_START_FUNC = "CSM_MUSHROOM_POISON_DYING_LAND_STATE_START", },
	

	START_STATE					= "CSM_MUSHROOM_POISON_START",
	WAIT_STATE					= "CSM_MUSHROOM_POISON_WAIT",
	SUMMON_END_STATE			= "CSM_MUSHROOM_POISON_END",
	
	SMALL_DAMAGE_LAND_FRONT		= "CSM_MUSHROOM_POISON_DAMAGE",
	SMALL_DAMAGE_LAND_BACK		= "CSM_MUSHROOM_POISON_DAMAGE",
	BIG_DAMAGE_LAND_FRONT		= "CSM_MUSHROOM_POISON_DAMAGE",
	BIG_DAMAGE_LAND_BACK		= "CSM_MUSHROOM_POISON_DAMAGE",
	
  	-- fix!! 테스트로 임시로 안넘어지게 수정
    DOWN_DAMAGE_LAND_FRONT		= "CSM_MUSHROOM_POISON_DAMAGE_DOWN_FRONT",
    DOWN_DAMAGE_LAND_BACK		= "CSM_MUSHROOM_POISON_DAMAGE_DOWN_BACK",
    -- DOWN_DAMAGE_LAND_FRONT		= "CSM_MUSHROOM_POISON_DAMAGE",
    -- DOWN_DAMAGE_LAND_BACK		= "CSM_MUSHROOM_POISON_DAMAGE",
	
	
	
	
	
	FLY_DAMAGE_FRONT			= "CSM_MUSHROOM_POISON_DAMAGE_FLY_FRONT",
	FLY_DAMAGE_BACK				= "CSM_MUSHROOM_POISON_DAMAGE_FLY_BACK",
	SMALL_DAMAGE_AIR			= "CSM_MUSHROOM_POISON_DAMAGE_AIR",	
	BIG_DAMAGE_AIR				= "CSM_MUSHROOM_POISON_DAMAGE_AIR",
	DOWN_DAMAGE_AIR				= "CSM_MUSHROOM_POISON_DAMAGE_AIR_DOWN",
	DOWN_DAMAGE_AIR_LANDING				= "CSM_MUSHROOM_POISON_DAMAGE_AIR_DOWN_LANDING",
	UP_DAMAGE					= "CSM_MUSHROOM_POISON_DAMAGE_AIR_UP",
	
	DAMAGE_EXTRA_STATES         = {"CSM_MUSHROOM_POISON_DAMAGE_AIR_FALL","CSM_MUSHROOM_POISON_STAND_UP_FRONT","CSM_MUSHROOM_POISON_STAND_UP_BACK",
	"CSM_MUSHROOM_POISON_JUMP_DOWN","CSM_MUSHROOM_POISON_JUMP_LANDING",},	
	
	DYING_LAND_FRONT			= "CSM_MUSHROOM_POISON_DYING_LAND_FRONT",
	DYING_LAND_BACK				= "CSM_MUSHROOM_POISON_DYING_LAND_BACK",
	DYING_SKY					= "CSM_MUSHROOM_POISON_DYING_SKY",

	REVENGE_ATTACK				= "",	
}

INIT_AI = 
{
	ALLY = 
	{
		FAR_LOST_RANGE	= 1400,			-- 이 거리보다 멀어지면 유저 옆으로 텔레포트
		LOST_RANGE		= 1400,			-- 이 거리보다 멀어지면 유저 쪽으로 걸어감
	},

	TARGET =
	{
		TARGET_PRIORITY 			= TARGET_PRIORITY["TP_NEAR_FIRST"],
		TARGET_INTERVAL 			= 1,
		TARGET_NEAR_RANGE 			= 1000,
		TARGET_RANGE 				= 2000,
		TARGET_LOST_RANGE 			= 5000,
		TARGET_SUCCESS_RATE 		= 100,
		ATTACK_TARGET_RATE 			= 100,
		PRESERVE_LAST_TARGET_RATE 	= 20,
	},
	
	

	CHASE_MOVE = 
	{		
		MOVE_SPLIT_RANGE	= 600,
		DEST_GAP			= 150,	-- 목적지에서 이 거리 안에 있으면 도착했다고 판단한다
		MOVE_GAP			= 160,
		
		DIR_CHANGE_INTERVAL = 0.7,
		
		WALK_INTERVAL		= 1,
		NEAR_WALK_RATE		= 0,   --  70,
		FAR_WALK_RATE		= 0,   -- 30,
		
		JUMP_INTERVAL		= 5,
		UP_JUMP_RATE		= 100, -- 40,
		UP_DOWN_RATE		= 20,
		DOWN_JUMP_RATE		= 100,    --  20,
		DOWN_DOWN_RATE		= 40,
	},	
	
	PATROL_MOVE = 	
	{
		PATROL_BEGIN_RATE		= 0, --50,		
		PATROL_RANGE			= 200,
		PATROL_COOL_TIME		= 2,
		ONLY_THIS_LINE_GROUP	= TRUE,
	},
	
	ESCAPE_MOVE = 
	{		
		MOVE_SPLIT_RANGE	= 500,	-- cm
		ESCAPE_GAP			= 600,	-- 이 거리 보다 멀어지면 도망 성공
		
		WALK_INTERVAL		= 1.5,	-- 초
		NEAR_WALK_RATE		= 100,   --  10,
		FAR_WALK_RATE		= 100,   -- 10,
		
		JUMP_INTERVAL		= 10,
		UP_JUMP_RATE		= 100, -- 30,
		UP_DOWN_RATE		= 30,
		DOWN_JUMP_RATE		= 100,    --  30,
		DOWN_DOWN_RATE		= 30,
	},
	
	
}









------------------------------------------------------------------------------------------------------------------------

CSM_MUSHROOM_POISON_START = 
{
	ANIM_NAME					= "WaitZero",
	PLAY_TYPE					= XSKIN_ANIM_PLAYTYPE["XAP_ONE_WAIT"],
	TRANSITION					= TRUE,
	
	CAN_PUSH_UNIT				= TRUE,
	CAN_PASS_UNIT				= FALSE,	

	SPEED_X						= 0,
	SPEED_Y						= 0,
	
	RIGHT						= TRUE,
	
	IMMADIATE_PACKET_SEND		= TRUE,	
	
	EVENT_PROCESS = 
	{		
		{ STATE_CHANGE_TYPE["SCT_CONDITION_TABLE"],		"CSM_MUSHROOM_POISON_WAIT",				"CT_CSM_MUSHROOM_POISON_WAIT"				},
	},
	
	CT_CSM_MUSHROOM_POISON_WAIT = 
	{
		STATE_TIME_OVER				= 4,
		--DISTANCE_TO_TARGET_NEAR		= 800,
	},
}





CSM_MUSHROOM_POISON_WAIT = 
{
	ANIM_NAME					= "Wait",
	
	
	PLAY_TYPE					= XSKIN_ANIM_PLAYTYPE["XAP_LOOP"],
	TRANSITION					= TRUE,
	
	CAN_PUSH_UNIT				= TRUE,
	CAN_PASS_UNIT				= FALSE,	
	
	SPEED_X						= 0,
	SPEED_Y						= 0,
	
	IMMADIATE_PACKET_SEND		= TRUE,
	EVENT_INTERVAL_TIME0		= 2,
	
	EVENT_PROCESS = 
	{		
		{ STATE_CHANGE_TYPE["SCT_FOOT_ON_LINE_FALSE_DOWN"],	"CSM_MUSHROOM_POISON_JUMP_DOWN",					},
		
		{ STATE_CHANGE_TYPE["SCT_CONDITION_TABLE"],			"CSM_MUSHROOM_POISON_ATTACK_POISON_POWDER",			"CT_CSM_MUSHROOM_POISON_ATTACK_POISON_POWDER",	},
		{ STATE_CHANGE_TYPE["SCT_CONDITION_TABLE"],			"CSM_MUSHROOM_POISON_ATTACK",						"CT_CSM_MUSHROOM_POISON_ATTACK",	},
		{ STATE_CHANGE_TYPE["SCT_CONDITION_TABLE"],			"CSM_MUSHROOM_POISON_WAIT_HABIT",					"CT_CSM_MUSHROOM_POISON_WAIT_HABIT",		},
		
		{ STATE_CHANGE_TYPE["SCT_AI_WALK"],					"CSM_MUSHROOM_POISON_WALK",							},
		{ STATE_CHANGE_TYPE["SCT_AI_DASH"],					"CSM_MUSHROOM_POISON_WALK",							},
		{ STATE_CHANGE_TYPE["SCT_AI_JUMP"],					"CSM_MUSHROOM_POISON_JUMP_UP",						},
		{ STATE_CHANGE_TYPE["SCT_AI_JUMP_DIR"],				"CSM_MUSHROOM_POISON_JUMP_UP_DIR",					},
		{ STATE_CHANGE_TYPE["SCT_AI_DOWN"],					"CSM_MUSHROOM_POISON_JUMP_DOWN",					},
		{ STATE_CHANGE_TYPE["SCT_AI_DOWN_DIR"],				"CSM_MUSHROOM_POISON_JUMP_DOWN_DIR",				},
	},

	CT_CSM_MUSHROOM_POISON_ATTACK = 
	{
		EVENT_INTERVAL_ID			= 0,
		DISTANCE_TO_TARGET_NEAR		= 200,
		RATE						= 100,
	},
	
	CT_CSM_MUSHROOM_POISON_ATTACK_POISON_POWDER =
	{
		EVENT_INTERVAL_ID			= 0,
		DISTANCE_TO_TARGET_NEAR		= 200,
		RATE						= 100,
	},
	
	CT_CSM_MUSHROOM_POISON_WAIT_HABIT = 
	{
		ANIM_PLAY_COUNT				= 15,
		RATE						= 50,
	},
	
	
	TALK_BOX =
	{
		EVENT_INTERVAL_ID			= 0,
		{ RATE = 7, MESSAGE = STR_ID_2570 },
	},
}


CSM_MUSHROOM_POISON_WAIT_HABIT = 
{
	ANIM_NAME					= "WaitHabit",
	PLAY_TYPE					= XSKIN_ANIM_PLAYTYPE["XAP_ONE_WAIT"],
	TRANSITION					= TRUE,
	
	CAN_PUSH_UNIT				= TRUE,
	CAN_PASS_UNIT				= FALSE,
	IMMADIATE_PACKET_SEND		= TRUE,
	
	EVENT_PROCESS = 
	{		
		{ STATE_CHANGE_TYPE["SCT_FOOT_ON_LINE_FALSE_DOWN"],	"CSM_MUSHROOM_POISON_JUMP_DOWN",					},
		{ STATE_CHANGE_TYPE["SCT_MOTION_END"],				"CSM_MUSHROOM_POISON_WAIT",							},
	},
}


CSM_MUSHROOM_POISON_END = 
{
	ANIM_NAME					= "Wait",
	PLAY_TYPE					= XSKIN_ANIM_PLAYTYPE["XAP_ONE_WAIT"],
	TRANSITION					= TRUE,
	
	CAN_PUSH_UNIT				= FALSE,
	CAN_PASS_UNIT				= TRUE,	

    INVINCIBLE					= { 0, 100, }, 
    
	SPEED_X						= 0,
	SPEED_Y						= 0,
	
	RIGHT						= FALSE,
	
	DYING_END					= TRUE,	
	
	IMMADIATE_PACKET_SEND		= TRUE,	
}


CSM_MUSHROOM_POISON_WALK = 
{
	ANIM_NAME					= "Walk",
	PLAY_TYPE					= XSKIN_ANIM_PLAYTYPE["XAP_LOOP"],
	TRANSITION					= TRUE,
	
	CAN_PUSH_UNIT				= TRUE,
	CAN_PASS_UNIT				= FALSE,
	
	ALLOW_DIR_CHANGE			= TRUE,
	IMMADIATE_PACKET_SEND		= TRUE,
	
	EVENT_INTERVAL_TIME0		= 2,
	
	EVENT_PROCESS = 
	{		
		{ STATE_CHANGE_TYPE["SCT_FOOT_ON_LINE_FALSE_DOWN"],	"CSM_MUSHROOM_POISON_JUMP_DOWN_DIR",				},
		
		{ STATE_CHANGE_TYPE["SCT_CONDITION_TABLE"],			"CSM_MUSHROOM_POISON_ATTACK_POISON_POWDER",						"CT_CSM_MUSHROOM_POISON_ATTACK_POISON_POWDER",	},
		{ STATE_CHANGE_TYPE["SCT_CONDITION_TABLE"],			"CSM_MUSHROOM_POISON_ATTACK",						"CT_CSM_MUSHROOM_POISON_ATTACK",			},
		
		
		{ STATE_CHANGE_TYPE["SCT_AI_WAIT"],					"CSM_MUSHROOM_POISON_WAIT",							},
		{ STATE_CHANGE_TYPE["SCT_AI_JUMP"],					"CSM_MUSHROOM_POISON_JUMP_UP",						},
		{ STATE_CHANGE_TYPE["SCT_AI_JUMP_DIR"],				"CSM_MUSHROOM_POISON_JUMP_UP_DIR",					},
		{ STATE_CHANGE_TYPE["SCT_AI_DOWN"],					"CSM_MUSHROOM_POISON_JUMP_DOWN",					},
		{ STATE_CHANGE_TYPE["SCT_AI_DOWN_DIR"],				"CSM_MUSHROOM_POISON_JUMP_DOWN_DIR",				},
	},
	
	CT_CSM_MUSHROOM_POISON_ATTACK = 
	{
		IS_ANOTHER_TEAM				= TRUE,
		EVENT_INTERVAL_ID			= 0,
		DISTANCE_TO_TARGET_NEAR		= 200,
		RATE						= 100,
	},
	
	CT_CSM_MUSHROOM_POISON_ATTACK_POISON_POWDER =
	{
		IS_ANOTHER_TEAM				= TRUE,
		EVENT_INTERVAL_ID			= 0,
		DISTANCE_TO_TARGET_NEAR		= 200,
		RATE						= 100,
	},
	
	TALK_BOX =
	{
		EVENT_INTERVAL_ID			= 0,
		{ RATE = 7, MESSAGE = STR_ID_2579 },
	},
	
}

CSM_MUSHROOM_POISON_JUMP_UP = 
{
	ANIM_NAME					= "JumpUp",
	PLAY_TYPE					= XSKIN_ANIM_PLAYTYPE["XAP_LOOP"],
	TRANSITION					= TRUE,
	LAND_CONNECT				= FALSE,
	
	CAN_PUSH_UNIT				= TRUE,
	CAN_PASS_UNIT				= FALSE,
	
	SPEED_X						= 0,
	SPEED_Y						= INIT_PHYSIC["JUMP_SPEED"],
	ADD_POS_Y					= 45,
	
	IMMADIATE_PACKET_SEND		= TRUE,
	
	EVENT_PROCESS = 
	{		
		{ STATE_CHANGE_TYPE["SCT_NEGATIVE_Y_SPEED"],		"CSM_MUSHROOM_POISON_JUMP_DOWN",				},
	},
	
}

CSM_MUSHROOM_POISON_JUMP_DOWN = 
{
	ANIM_NAME					= "JumpDown",
	PLAY_TYPE					= XSKIN_ANIM_PLAYTYPE["XAP_LOOP"],
	TRANSITION					= TRUE,
	LAND_CONNECT				= FALSE,
	
	CAN_PUSH_UNIT				= TRUE,
	CAN_PASS_UNIT				= FALSE,
	
	
	
	IMMADIATE_PACKET_SEND		= TRUE,
		
	EVENT_PROCESS = 
	{		
		{ STATE_CHANGE_TYPE["SCT_FOOT_ON_LINE_TRUE"],		"CSM_MUSHROOM_POISON_JUMP_LANDING",				},
	},
}

CSM_MUSHROOM_POISON_JUMP_UP_DIR = 
{
	ANIM_NAME					= "JumpUp",
	PLAY_TYPE					= XSKIN_ANIM_PLAYTYPE["XAP_LOOP"],
	TRANSITION					= TRUE,
	LAND_CONNECT				= FALSE,
	
	CAN_PUSH_UNIT				= TRUE,
	CAN_PASS_UNIT				= FALSE,
	
	PASSIVE_SPEED_X				= INIT_PHYSIC["WALK_SPEED"],
	SPEED_Y						= INIT_PHYSIC["JUMP_SPEED"],
	ADD_POS_Y					= 45,
	
	IMMADIATE_PACKET_SEND		= TRUE,
	
	EVENT_PROCESS = 
	{		
		{ STATE_CHANGE_TYPE["SCT_NEGATIVE_Y_SPEED"],		"CSM_MUSHROOM_POISON_JUMP_DOWN_DIR",				},
	},
}

CSM_MUSHROOM_POISON_JUMP_DOWN_DIR = 
{
	ANIM_NAME					= "JumpDown",
	PLAY_TYPE					= XSKIN_ANIM_PLAYTYPE["XAP_LOOP"],
	TRANSITION					= TRUE,
	LAND_CONNECT				= FALSE,
	
	CAN_PUSH_UNIT				= TRUE,
	CAN_PASS_UNIT				= FALSE,
	
	
	PASSIVE_SPEED_X				= INIT_PHYSIC["WALK_SPEED"],
	
	IMMADIATE_PACKET_SEND		= TRUE,
		
	EVENT_PROCESS = 
	{		
		{ STATE_CHANGE_TYPE["SCT_FOOT_ON_LINE_TRUE"],		"CSM_MUSHROOM_POISON_JUMP_LANDING",				},
	},
}

CSM_MUSHROOM_POISON_JUMP_LANDING = 
{
	ANIM_NAME					= "Wait",
	PLAY_TYPE					= XSKIN_ANIM_PLAYTYPE["XAP_ONE_WAIT"],
	TRANSITION					= TRUE,
	LAND_CONNECT				= FALSE,
	
	CAN_PUSH_UNIT				= TRUE,
	CAN_PASS_UNIT				= FALSE,
	
	SPEED_X						= 0,
	SPEED_Y						= 0,
		
	IMMADIATE_PACKET_SEND		= TRUE,

	EVENT_PROCESS = 
	{		
		{ STATE_CHANGE_TYPE["SCT_FOOT_ON_LINE_FALSE_DOWN"],	"CSM_MUSHROOM_POISON_JUMP_DOWN",				},
		{ STATE_CHANGE_TYPE["SCT_MOTION_END"],				"CSM_MUSHROOM_POISON_WAIT",					},
	},
}

CSM_MUSHROOM_POISON_ATTACK = 
{
	ANIM_SPEED					= 1.5,
	ANIM_NAME					= "Attack",
	PLAY_TYPE					= XSKIN_ANIM_PLAYTYPE["XAP_ONE_WAIT"],
	TRANSITION					= FALSE,
	LAND_CONNECT				= FALSE,
	
	CAN_PUSH_UNIT				= TRUE,
	CAN_PASS_UNIT				= FALSE,
	
	SPEED_X						= 0,
	SPEED_Y						= 0,	
	
	VIEW_TARGET					= TRUE,
	
	IMMADIATE_PACKET_SEND		= TRUE,
	
	TALK_BOX = 
	{
		{ RATE = 10, MESSAGE = STR_ID_1514 },
	},
		
	EVENT_PROCESS = 
	{		
		{ STATE_CHANGE_TYPE["SCT_FOOT_ON_LINE_FALSE_DOWN"],	"CSM_MUSHROOM_POISON_JUMP_DOWN",				},
		{ STATE_CHANGE_TYPE["SCT_MOTION_END"],				"CSM_MUSHROOM_POISON_WAIT",					},
	},
	
	ATTACK_TIME0				= { 1.0, 1.066, },

	
	
	DAMAGE_DATA = 
	{
		DAMAGE_TYPE		= DAMAGE_TYPE["DT_PHYSIC"],
		HIT_TYPE		= HIT_TYPE["HT_PUNCH_HIT"],
		REACT_TYPE		= REACT_TYPE["RT_BIG_DAMAGE"],
		
		DAMAGE = 
		{
			PHYSIC		= 1.5,
		},
		
		BACK_SPEED_X			= 700,
		BACK_SPEED_Y			= 0.0,
		
		CAMERA_CRASH_GAP		= 5.0,	
		CAMERA_CRASH_TIME		= 0.2,		
	},
}

CSM_MUSHROOM_POISON_ATTACK_POISON_POWDER =
{
	ANIM_SPEED					= 1.5,
	ANIM_NAME					= "AttackPoisonPowder",
	PLAY_TYPE					= XSKIN_ANIM_PLAYTYPE["XAP_ONE_WAIT"],
	TRANSITION					= FALSE,
	LAND_CONNECT				= FALSE,
	
	CAN_PUSH_UNIT				= TRUE,
	CAN_PASS_UNIT				= FALSE,

        SOUND_PLAY0			= { 1.458, "PoisonPowder.ogg" },
	
	VIEW_TARGET					= TRUE,
	
	IMMADIATE_PACKET_SEND		= TRUE,
	
	TALK_BOX = 
	{
		{ RATE = 8, MESSAGE = STR_ID_1764 },
		{ RATE = 8, MESSAGE = STR_ID_1765 },
	},
	
	EVENT_PROCESS = 
	{
		{ STATE_CHANGE_TYPE["SCT_MOTION_END"],						"CSM_MUSHROOM_POISON_WAIT",						},
	},
}


CSM_MUSHROOM_POISON_DAMAGE = 
{
	ANIM_NAME					= "Damage",
	PLAY_TYPE					= XSKIN_ANIM_PLAYTYPE["XAP_ONE_WAIT"],
	TRANSITION					= FALSE,
	LAND_CONNECT				= FALSE,
	
	CAN_PUSH_UNIT				= TRUE,
	CAN_PASS_UNIT				= FALSE,
	
	TALK_BOX = 
	{
		{ RATE = 8, MESSAGE = STR_ID_2568 },
		{ RATE = 8, MESSAGE = STR_ID_1715 },
	},
	
	EVENT_PROCESS = 
	{
		{ STATE_CHANGE_TYPE["SCT_MOTION_END"],						"CSM_MUSHROOM_POISON_WAIT",						},
	},
}


CSM_MUSHROOM_POISON_DAMAGE_DOWN_FRONT = 
{
	ANIM_NAME					= "DamageDownFront",
	PLAY_TYPE					= XSKIN_ANIM_PLAYTYPE["XAP_ONE_WAIT"],
	TRANSITION					= FALSE,
	LAND_CONNECT				= FALSE,

	SUPER_ARMOR					= TRUE,
	DEFENCE						= { 0, 100, 20, },
	
	CAN_PUSH_UNIT				= TRUE,
	CAN_PASS_UNIT				= FALSE,
	
	TALK_BOX = 
	{
		{ RATE = 8, MESSAGE = STR_ID_1756 },
	},
	
	EVENT_PROCESS = 
	{
		{ STATE_CHANGE_TYPE["SCT_FOOT_ON_LINE_FALSE_DOWN"],		"CSM_MUSHROOM_POISON_DAMAGE_AIR_FALL",			},
		{ STATE_CHANGE_TYPE["SCT_MOTION_END"],					"CSM_MUSHROOM_POISON_STAND_UP_FRONT",			},
	},
	
}

CSM_MUSHROOM_POISON_DAMAGE_DOWN_BACK = 
{
	ANIM_NAME					= "DamageDownBack",
	PLAY_TYPE					= XSKIN_ANIM_PLAYTYPE["XAP_ONE_WAIT"],
	TRANSITION					= FALSE,
	LAND_CONNECT				= FALSE,
	
	SUPER_ARMOR					= TRUE,
	DEFENCE						= { 0, 100, 20, },
	
	CAN_PUSH_UNIT				= TRUE,
	CAN_PASS_UNIT				= FALSE,
	
	TALK_BOX = 
	{
		{ RATE = 8, MESSAGE = STR_ID_1756 },
	},
	
	EVENT_PROCESS = 
	{
		{ STATE_CHANGE_TYPE["SCT_FOOT_ON_LINE_FALSE_DOWN"],		"CSM_MUSHROOM_POISON_DAMAGE_AIR_FALL",			},
		{ STATE_CHANGE_TYPE["SCT_MOTION_END"],					"CSM_MUSHROOM_POISON_STAND_UP_BACK",			},
	},
}


CSM_MUSHROOM_POISON_DAMAGE_AIR = 
{
	ANIM_NAME					= "DamageAirSmall",
	PLAY_TYPE					= XSKIN_ANIM_PLAYTYPE["XAP_ONE_WAIT"],
	TRANSITION					= FALSE,
	LAND_CONNECT				= FALSE,
	
	CAN_PUSH_UNIT				= TRUE,
	CAN_PASS_UNIT				= FALSE,
	
	EVENT_PROCESS = 
	{
		{ STATE_CHANGE_TYPE["SCT_FOOT_ON_LINE_TRUE"],			"CSM_MUSHROOM_POISON_WAIT",					},
	},
}

CSM_MUSHROOM_POISON_DAMAGE_AIR_DOWN = 
{
	ANIM_NAME					= "DamageAirDown",
	PLAY_TYPE					= XSKIN_ANIM_PLAYTYPE["XAP_ONE_WAIT"],
	TRANSITION					= FALSE,
	LAND_CONNECT				= FALSE,
	
	CAN_PUSH_UNIT				= TRUE,
	CAN_PASS_UNIT				= FALSE,
	
	EVENT_PROCESS = 
	{
		{ STATE_CHANGE_TYPE["SCT_FOOT_ON_LINE_TRUE"],			"CSM_MUSHROOM_POISON_DAMAGE_AIR_DOWN_LANDING",	},
	},
}

CSM_MUSHROOM_POISON_DAMAGE_AIR_UP = 
{
	ANIM_NAME					= "DamageAirUp",
	PLAY_TYPE					= XSKIN_ANIM_PLAYTYPE["XAP_ONE_WAIT"],
	TRANSITION					= FALSE,
	LAND_CONNECT				= FALSE,
	
	CAN_PUSH_UNIT				= TRUE,
	CAN_PASS_UNIT				= FALSE,
	
	EVENT_PROCESS = 
	{
		{ STATE_CHANGE_TYPE["SCT_NEGATIVE_Y_SPEED"],		"CSM_MUSHROOM_POISON_DAMAGE_AIR_FALL",			},
		{ STATE_CHANGE_TYPE["SCT_FOOT_ON_LINE_TRUE"],		"CSM_MUSHROOM_POISON_DAMAGE_AIR_DOWN_LANDING",	},
	},
	TALK_BOX =
	{
		{ RATE = 10, MESSAGE = STR_ID_2568 },
 	},

}

CSM_MUSHROOM_POISON_DAMAGE_AIR_FALL = 
{
	ANIM_NAME					= "DamageAirFall",
	PLAY_TYPE					= XSKIN_ANIM_PLAYTYPE["XAP_ONE_WAIT"],
	TRANSITION					= FALSE,
	LAND_CONNECT				= FALSE,
	
	CAN_PUSH_UNIT				= TRUE,
	CAN_PASS_UNIT				= FALSE,
	
	EVENT_PROCESS = 
	{
		{ STATE_CHANGE_TYPE["SCT_POSITIVE_Y_SPEED"],		"CSM_MUSHROOM_POISON_DAMAGE_AIR_UP",			},
		{ STATE_CHANGE_TYPE["SCT_FOOT_ON_LINE_TRUE"],		"CSM_MUSHROOM_POISON_DAMAGE_AIR_DOWN_LANDING",	},
	},
}

CSM_MUSHROOM_POISON_DAMAGE_AIR_DOWN_LANDING = 
{
	ANIM_NAME					= "DamageAirDownLanding",
	PLAY_TYPE					= XSKIN_ANIM_PLAYTYPE["XAP_ONE_WAIT"],
	TRANSITION					= FALSE,
	LAND_CONNECT				= FALSE,
	
	SUPER_ARMOR					= TRUE,
	DEFENCE						= { 0, 100, 20, },
	
	CAN_PUSH_UNIT				= TRUE,
	CAN_PASS_UNIT				= FALSE,
	
	EVENT_PROCESS = 
	{
		{ STATE_CHANGE_TYPE["SCT_FOOT_ON_LINE_FALSE_DOWN"],	"CSM_MUSHROOM_POISON_DAMAGE_AIR_FALL",			},
		{ STATE_CHANGE_TYPE["SCT_MOTION_END"],				"CSM_MUSHROOM_POISON_STAND_UP_FRONT",			},
	},
	
}

CSM_MUSHROOM_POISON_DAMAGE_FLY_FRONT = 
{
	ANIM_NAME					= "DamageAirFall",
	PLAY_TYPE					= XSKIN_ANIM_PLAYTYPE["XAP_ONE_WAIT"],
	TRANSITION					= FALSE,
	LAND_CONNECT				= FALSE,
	
	ADD_ROTATE_Z				= -45.0,	
	
	
	CAN_PUSH_UNIT				= TRUE,
	CAN_PASS_UNIT				= FALSE,
	
	EVENT_PROCESS = 
	{
		{ STATE_CHANGE_TYPE["SCT_FOOT_ON_LINE_TRUE"],			"CSM_MUSHROOM_POISON_DAMAGE_AIR_DOWN_LANDING",		},
	},
}

CSM_MUSHROOM_POISON_DAMAGE_FLY_BACK = 
{
	ANIM_NAME					= "DamageAirBack",
	PLAY_TYPE					= XSKIN_ANIM_PLAYTYPE["XAP_ONE_WAIT"],
	TRANSITION					= FALSE,
	LAND_CONNECT				= FALSE,	
	
	ADD_ROTATE_Z				= -90.0,	
	
	
	CAN_PUSH_UNIT				= TRUE,
	CAN_PASS_UNIT				= FALSE,
	
	EVENT_PROCESS = 
	{
		{ STATE_CHANGE_TYPE["SCT_FOOT_ON_LINE_TRUE"],			"CSM_MUSHROOM_POISON_DAMAGE_DOWN_BACK",		},
	},
}


CSM_MUSHROOM_POISON_STAND_UP_FRONT = 
{
	ANIM_NAME					= "DamageStandupFront",
	PLAY_TYPE					= XSKIN_ANIM_PLAYTYPE["XAP_ONE_WAIT"],
	TRANSITION					= FALSE,
	LAND_CONNECT				= FALSE,	
	
	SUPER_ARMOR					= TRUE,
	DEFENCE						= { 0, 100, 20, },
	
	CAN_PUSH_UNIT				= TRUE,
	CAN_PASS_UNIT				= FALSE,
	
	EVENT_PROCESS = 
	{
		{ STATE_CHANGE_TYPE["SCT_FOOT_ON_LINE_FALSE_DOWN"],	"CSM_MUSHROOM_POISON_JUMP_DOWN",			},
		{ STATE_CHANGE_TYPE["SCT_MOTION_END"],				"CSM_MUSHROOM_POISON_WAIT",				},
	},
}

CSM_MUSHROOM_POISON_STAND_UP_BACK = 
{
	ANIM_NAME					= "DamageStandupBack",
	PLAY_TYPE					= XSKIN_ANIM_PLAYTYPE["XAP_ONE_WAIT"],
	TRANSITION					= FALSE,
	LAND_CONNECT				= FALSE,
	
	SUPER_ARMOR					= TRUE,
	DEFENCE						= { 0, 100, 20, },
		
	CAN_PUSH_UNIT				= TRUE,
	CAN_PASS_UNIT				= FALSE,
		
	EVENT_PROCESS = 
	{
		{ STATE_CHANGE_TYPE["SCT_FOOT_ON_LINE_FALSE_DOWN"],	"CSM_MUSHROOM_POISON_JUMP_DOWN",		},
		{ STATE_CHANGE_TYPE["SCT_MOTION_END"],				"CSM_MUSHROOM_POISON_WAIT",			},
	},		
}

CSM_MUSHROOM_POISON_DYING_LAND_FRONT = 
{
	ANIM_NAME					= "DamageDownFront",
	PLAY_TYPE					= XSKIN_ANIM_PLAYTYPE["XAP_ONE_WAIT"],
	TRANSITION					= FALSE,
	LAND_CONNECT				= FALSE,

	INVINCIBLE					= { 0, 100, }, 		
	
	CAN_PUSH_UNIT				= FALSE,
	CAN_PASS_UNIT				= TRUE,
	
	DYING_END					= TRUE,
	
	IMMADIATE_PACKET_SEND		= TRUE,
}
	
CSM_MUSHROOM_POISON_DYING_LAND_BACK = 
{
	ANIM_NAME					= "DamageDownBack",
	PLAY_TYPE					= XSKIN_ANIM_PLAYTYPE["XAP_ONE_WAIT"],
	TRANSITION					= FALSE,
	LAND_CONNECT				= FALSE,
	
	INVINCIBLE					= { 0, 100, }, 		
	
	CAN_PUSH_UNIT				= FALSE,
	CAN_PASS_UNIT				= TRUE,
	
	DYING_END					= TRUE,	
	
	IMMADIATE_PACKET_SEND		= TRUE,
}

CSM_MUSHROOM_POISON_DYING_SKY = 
{
	ANIM_NAME					= "DamageAirDownLanding",
	PLAY_TYPE					= XSKIN_ANIM_PLAYTYPE["XAP_ONE_WAIT"],
	TRANSITION					= FALSE,
	LAND_CONNECT				= FALSE,
	
	INVINCIBLE					= { 0, 100, }, 		
	
	CAN_PUSH_UNIT				= FALSE,
	CAN_PASS_UNIT				= TRUE,
	
	DYING_END					= TRUE,
	
	IMMADIATE_PACKET_SEND		= TRUE,
}









--------------------------------------------------------------------
--------------------------------------------------------------------

function CSM_MUSHROOM_POISON_WALK_STATE_END( pKTDXApp, pX2Game, pNPCUnit )

	pMinorParticle = pX2Game:GetMinorParticle()
	pMinorParticle:CreateSequence_LUA( "StepSmoke", pNPCUnit:GetLandPosition_LUA(), D3DXVECTOR2(100,100), D3DXVECTOR2(5,-1) )

end

function CSM_MUSHROOM_POISON_JUMP_DOWN_STATE_END( pKTDXApp, pX2Game, pNPCUnit )

	pMinorParticle = pX2Game:GetMinorParticle()
	pMinorParticle:CreateSequence_LUA( "StepSmoke", pNPCUnit:GetLandPosition_LUA(), D3DXVECTOR2(100,100), D3DXVECTOR2(5,-1) )

end

function CSM_MUSHROOM_POISON_JUMP_DOWN_DIR_STATE_END( pKTDXApp, pX2Game, pNPCUnit )

	pMinorParticle = pX2Game:GetMinorParticle()
	pMinorParticle:CreateSequence_LUA( "StepSmoke", pNPCUnit:GetLandPosition_LUA(), D3DXVECTOR2(100,100), D3DXVECTOR2(5,-1) )

end


function CSM_MUSHROOM_POISON_WALK_FRAME_MOVE( pKTDXApp, pX2Game, pNPCUnit )
	
	nowAnimTime = pNPCUnit:GetNowAnimationTime()

	if nowAnimTime < 0.13 then
		pNPCUnit:SetSpeedX( 0 );
	elseif nowAnimTime > 0.45 then
		pNPCUnit:SetSpeedX( 0 );
	end
	
	if nowAnimTime > 0.13 and nowAnimTime < 0.14 then
		pNPCUnit:SetSpeedX( pNPCUnit:GetWalkSpeed() );
	end
	
end


function CSM_MUSHROOM_POISON_DAMAGE_FRAME_MOVE( pKTDXApp, pX2Game, pNPCUnit )

	if pNPCUnit:AnimEventTimer_LUA( 0.047 ) then
		pMinorParticle = pX2Game:GetMinorParticle()
		pMinorParticle:CreateSequence_LUA( "StepSmoke", pNPCUnit:GetLandPosition_LUA(), D3DXVECTOR2(100,100), D3DXVECTOR2(5,-1) )
	end

end

function CSM_MUSHROOM_POISON_DAMAGE_DOWN_FRONT_FRAME_MOVE( pKTDXApp, pX2Game, pNPCUnit )

	if pNPCUnit:AnimEventTimer_LUA( 0.3 ) then
		pNPCUnit:PlaySound_LUA( "Down.ogg" )
		pMinorParticle = pX2Game:GetMinorParticle()
		pMinorParticle:CreateSequence_LUA( "DownSmoke", pNPCUnit:GetLandPosition_LUA(), D3DXVECTOR2(100,100), D3DXVECTOR2(7,-1) )
	end

end

function CSM_MUSHROOM_POISON_DAMAGE_DOWN_BACK_FRAME_MOVE( pKTDXApp, pX2Game, pNPCUnit )

	if pNPCUnit:AnimEventTimer_LUA( 0.2 ) then
		pNPCUnit:PlaySound_LUA( "Down.ogg" )
		pMinorParticle = pX2Game:GetMinorParticle()
		pMinorParticle:CreateSequence_LUA( "DownSmoke", pNPCUnit:GetLandPosition_LUA(), D3DXVECTOR2(100,100), D3DXVECTOR2(7,-1) )
	end

end

function CSM_MUSHROOM_POISON_DAMAGE_AIR_DOWN_LANDING_FRAME_MOVE( pKTDXApp, pX2Game, pNPCUnit )

	if pNPCUnit:AnimEventTimer_LUA( 0.01 ) then
		pNPCUnit:PlaySound_LUA( "Down.ogg" )
		pMinorParticle = pX2Game:GetMinorParticle()
		pos = pNPCUnit:GetLandPosition_LUA()
		pMinorParticle:CreateSequence_LUA( "DownSmoke", pos, D3DXVECTOR2(100,100), D3DXVECTOR2(7,-1) )
		pos.y = pos.y + 5
		pMinorParticle:CreateSequence_LUA( "GroundShockWave", pos, D3DXVECTOR2(100,100), D3DXVECTOR2(1,-1) )
		pParticle = pMinorParticle:CreateSequence_LUA( "AirDownTick", pNPCUnit:GetPos(), D3DXVECTOR2(200,200), D3DXVECTOR2(10,-1) )
		if pParticle ~= nil then 
			pParticle:SetLandPosition( pos.y - 5 )
		end
		
		if GetDistance_LUA( pNPCUnit:GetPos(), pX2Game:GetFocusUnitPos_LUA() ) < 500 then
			pX2Game:GetX2Camera():GetCamera():UpDownCrashCameraNoReset( 10.0, 0.1 )
		end		
		
	elseif pNPCUnit:AnimEventTimer_LUA( 0.44 ) then
		pNPCUnit:PlaySound_LUA( "Down.ogg" )
		pMinorParticle = pX2Game:GetMinorParticle()
		pMinorParticle:CreateSequence_LUA( "DownSmoke", pNPCUnit:GetLandPosition_LUA(), D3DXVECTOR2(100,100), D3DXVECTOR2(7,-1) )
	end

end





function CSM_MUSHROOM_POISON_DYING_LAND_STATE_START( pKTDXApp, pX2Game, pNPCUnit )

	
	pos = pNPCUnit:GetPos()
	pos.y = pos.y + 100.0
	GetMinorParticle = pX2Game:GetMinorParticle()
	
	pSeq = GetMinorParticle:CreateSequence_LUA( "DieLight",		pos, D3DXVECTOR2(-1,-1), D3DXVECTOR2(3,-1) )
	if pSeq ~= nil then
	
		pSeq:SetLandPosition( pNPCUnit:GetLandPosition_LUA().y )
		pNPCUnit:SetDieSeq( pSeq:GetHandle() )
	
	end
	pNPCUnit:PlaySound_LUA( "DieLight.ogg" )
	
end


function CSM_MUSHROOM_POISON_ATTACK_POISON_POWDER_FRAME_MOVE( pKTDXApp, pX2Game, pNPCUnit )

	if pNPCUnit:AnimEventTimer_LUA( 1.183 ) then
	
		pMajorParticle = pX2Game:GetMajorParticle()
		pMajorParticle:CreateSequence_LUA( "CSM_AttackPoisonPowder03",	pNPCUnit:GetBonePos_LUA( "Bip01_Footsteps" ), D3DXVECTOR2(-1,-1), D3DXVECTOR2(-1,-1) )
		pMajorParticle:CreateSequence_LUA( "CSM_AttackPoisonPowder03",	pNPCUnit:GetBonePos_LUA( "Bip01_Footsteps" ), D3DXVECTOR2(-1,-1), D3DXVECTOR2(-1,-1) )
		
		pDamageEffect = pX2Game:GetDamageEffect()
		pos = pNPCUnit:GetLandPosition_LUA()		
		pDamageEffect:CreateInstance_LUA( pNPCUnit, "CSM_MUSHROOM_POISON_POWDER", pNPCUnit:GetBonePos_LUA( "Bip01_Footsteps" ), pos.y )	
		
	end
	
	if pNPCUnit:AnimEventTimer_LUA( 1.683 ) then
		
		pMajorParticle = pX2Game:GetMajorParticle()
		pMajorParticle:CreateSequence_LUA( "CSM_AttackPoisonPowder03",	pNPCUnit:GetBonePos_LUA( "Bip01_Footsteps" ), D3DXVECTOR2(-1,-1), D3DXVECTOR2(-1,-1) )
		
	end

end
