-- lua header. UTF-8 인코딩 인식을 위해 이 줄은 지우지 마세요.


INIT_SYSTEM = 
{
	UNIT_WIDTH		= 100.0,
	UNIT_LAYER		= X2_LAYER["XL_UNIT_0"],
}


INIT_DEVICE = 
{
	READY_TEXTURE = 
	{
	},
	
	READY_SOUND = 
	{
		"ARMADILLO_Rolling.ogg",
		"ARMADILLO_JumpRolling.ogg",
		"ARMADILLO_Voice.ogg",
		"ARMADILLO_Voice2.ogg",
		"ARMADILLO_Walk.ogg",
		"ARMADILLO_StandUpRolling.ogg",
		"ARMADILLO_attack.ogg",
	},
}

INIT_MOTION = 
{
	MOTION_FILE_NAME		= "Motion_Armadillo.x",
}

INIT_PHYSIC = 
{
	RELOAD_ACCEL		= 2000,
	G_ACCEL				= 4000,
	MAX_G_SPEED			= -2000,
	
	WALK_SPEED			= 400,
	RUN_SPEED			= 400,
	JUMP_SPEED			= 1500,
	DASH_JUMP_SPEED		= 2000,
}


INIT_COMPONENT = 
{
	MAX_HP				= 5000,
	MP_CHANGE_RATE		= 1,
	MP_CHARGE_RATE		= 130,
	
	USE_SLASH_TRACE		= FALSE,
	
	SHADOW_SIZE			= 200,
	SHADOW_FILE_NAME	= "shadow.dds",
	
	SMALL_HP_BAR_BLUE	= "Small_HP_bar_Blue.TGA",
	SMALL_HP_BAR_RED	= "Small_HP_bar_Red.TGA",
	SMALL_HP_BAR_YELLOW = "Small_HP_bar_Yellow.TGA",
	
	QUESTION_MARK_SEQ		= "QuestionMarkNPC",
	EXCLAMATION_MARK_SEQ	= "ExclamationMarkNPC",
	
	HYPER_MODE_COUNT	= 0,
	MAX_HYPER_MODE_TIME	= 30,
	
	HITTED_TYPE			= HITTED_TYPE["HTD_MEAT"],
	
	FALL_DOWN			= TRUE,
	DEFENCE_RATE		= 10,
		
	SUMMON_TIME			= 180,
	

}

INIT_STATE = 
{
	{ STATE_NAME = "CSM_ARMADILLO_START",						},
	{ STATE_NAME = "CSM_ARMADILLO_WAIT",						},
	{ STATE_NAME = "CSM_ARMADILLO_WAIT3",						LUA_FRAME_MOVE_FUNC = "CSM_ARMADILLO_WAIT3_FRAME_MOVE"					},
	{ STATE_NAME = "CSM_ARMADILLO_WALK",						LUA_STATE_END_FUNC = "CSM_ARMADILLO_WALK_STATE_END"						},
	{ STATE_NAME = "CSM_ARMADILLO_JUMP_UP",						},
	{ STATE_NAME = "CSM_ARMADILLO_JUMP_DOWN",					LUA_STATE_END_FUNC = "CSM_ARMADILLO_JUMP_DOWN_STATE_END" },
	{ STATE_NAME = "CSM_ARMADILLO_JUMP_UP_DIR",					},
	{ STATE_NAME = "CSM_ARMADILLO_JUMP_DOWN_DIR",				LUA_STATE_END_FUNC = "CSM_ARMADILLO_JUMP_DOWN_DIR_STATE_END" },
	{ STATE_NAME = "CSM_ARMADILLO_JUMP_LANDING",				},
	
	{ STATE_NAME = "CSM_ARMADILLO_ATTACK",						STATE_COOL_TIME = 3, },
	{ STATE_NAME = "CSM_ARMADILLO_ROLLING_ATTACK",				STATE_COOL_TIME = 8,   },
	
	{ STATE_NAME = "CSM_ARMADILLO_DEFENCE",						STATE_COOL_TIME = 10, },
	
	{ STATE_NAME = "CSM_ARMADILLO_END",						},
	
	
	
	
	
	
	--리액션 관련
	{ STATE_NAME = "CSM_ARMADILLO_DAMAGE_SMALL",				LUA_FRAME_MOVE_FUNC = "CSM_ARMADILLO_DAMAGE_SMALL_FRAME_MOVE"			},
	{ STATE_NAME = "CSM_ARMADILLO_DAMAGE_BIG",					LUA_FRAME_MOVE_FUNC = "CSM_ARMADILLO_DAMAGE_BIG_FRAME_MOVE"				},
	{ STATE_NAME = "CSM_ARMADILLO_DAMAGE_DOWN_FRONT",			LUA_FRAME_MOVE_FUNC = "CSM_ARMADILLO_DAMAGE_DOWN_FRONT_FRAME_MOVE"		},
	{ STATE_NAME = "CSM_ARMADILLO_DAMAGE_DOWN_BACK",			LUA_FRAME_MOVE_FUNC = "CSM_ARMADILLO_DAMAGE_DOWN_BACK_FRAME_MOVE"		},
	{ STATE_NAME = "CSM_ARMADILLO_DAMAGE_FLY_FRONT",			},
	{ STATE_NAME = "CSM_ARMADILLO_DAMAGE_FLY_BACK",				},
	{ STATE_NAME = "CSM_ARMADILLO_DAMAGE_AIR",					},
	{ STATE_NAME = "CSM_ARMADILLO_DAMAGE_AIR_DOWN",				},
	{ STATE_NAME = "CSM_ARMADILLO_DAMAGE_AIR_UP",				},
	{ STATE_NAME = "CSM_ARMADILLO_DAMAGE_AIR_FALL",				},	
	{ STATE_NAME = "CSM_ARMADILLO_DAMAGE_AIR_DOWN_LANDING",		LUA_FRAME_MOVE_FUNC = "CSM_ARMADILLO_DAMAGE_AIR_DOWN_LANDING_FRAME_MOVE"	},
	{ STATE_NAME = "CSM_ARMADILLO_STAND_UP_FRONT",				},
	{ STATE_NAME = "CSM_ARMADILLO_STAND_UP_BACK",				},
	{ STATE_NAME = "CSM_ARMADILLO_STAND_UP_ATTACK_FRONT",		LUA_FRAME_MOVE_FUNC = "CSM_ARMADILLO_STAND_UP_ATTACK_FRONT_FRAME_MOVE"	},
	{ STATE_NAME = "CSM_ARMADILLO_STAND_UP_ATTACK_BACK",		LUA_FRAME_MOVE_FUNC = "CSM_ARMADILLO_STAND_UP_ATTACK_BACK_FRAME_MOVE"	},
	{ STATE_NAME = "CSM_ARMADILLO_DAMAGE_REVENGE",				},
	
	{ STATE_NAME = "CSM_ARMADILLO_DYING_LAND_FRONT",			LUA_STATE_START_FUNC = "CSM_ARMADILLO_DYING_LAND_STATE_START", },
	{ STATE_NAME = "CSM_ARMADILLO_DYING_LAND_BACK",				LUA_STATE_START_FUNC = "CSM_ARMADILLO_DYING_LAND_STATE_START", },
	{ STATE_NAME = "CSM_ARMADILLO_DYING_SKY",					LUA_STATE_START_FUNC = "CSM_ARMADILLO_DYING_LAND_STATE_START", },
	
	START_STATE					= "CSM_ARMADILLO_START",
	WAIT_STATE					= "CSM_ARMADILLO_WAIT",
	SUMMON_END_STATE			= "CSM_ARMADILLO_END",
	DEFENCE_STATE				= "CSM_ARMADILLO_DEFENCE",
	
	SMALL_DAMAGE_LAND_FRONT		= "CSM_ARMADILLO_DAMAGE_SMALL",
	SMALL_DAMAGE_LAND_BACK		= "CSM_ARMADILLO_DAMAGE_SMALL",
	BIG_DAMAGE_LAND_FRONT		= "CSM_ARMADILLO_DAMAGE_BIG",
	BIG_DAMAGE_LAND_BACK		= "CSM_ARMADILLO_DAMAGE_BIG",
	DOWN_DAMAGE_LAND_FRONT		= "CSM_ARMADILLO_DAMAGE_DOWN_FRONT",
	DOWN_DAMAGE_LAND_BACK		= "CSM_ARMADILLO_DAMAGE_DOWN_BACK",
	FLY_DAMAGE_FRONT			= "CSM_ARMADILLO_DAMAGE_FLY_FRONT",
	FLY_DAMAGE_BACK				= "CSM_ARMADILLO_DAMAGE_FLY_BACK",
	SMALL_DAMAGE_AIR			= "CSM_ARMADILLO_DAMAGE_AIR",	
	BIG_DAMAGE_AIR				= "CSM_ARMADILLO_DAMAGE_AIR",
	DOWN_DAMAGE_AIR				= "CSM_ARMADILLO_DAMAGE_AIR_DOWN",
	DOWN_DAMAGE_AIR_LANDING				= "CSM_ARMADILLO_DAMAGE_AIR_DOWN_LANDING",
	UP_DAMAGE					= "CSM_ARMADILLO_DAMAGE_AIR_UP",
	DAMAGE_REVENGE				= "CSM_ARMADILLO_DAMAGE_REVENGE",
	
	DAMAGE_EXTRA_STATES         = {"CSM_ARMADILLO_DAMAGE_AIR_FALL",	"CSM_ARMADILLO_STAND_UP_FRONT","CSM_ARMADILLO_STAND_UP_BACK","CSM_ARMADILLO_STAND_UP_ATTACK_FRONT","CSM_ARMADILLO_STAND_UP_ATTACK_BACK",
	"CSM_ARMADILLO_JUMP_DOWN","CSM_ARMADILLO_JUMP_LANDING",},	
	
	DYING_LAND_FRONT			= "CSM_ARMADILLO_DYING_LAND_FRONT",
	DYING_LAND_BACK				= "CSM_ARMADILLO_DYING_LAND_BACK",
	DYING_SKY					= "CSM_ARMADILLO_DYING_SKY",

	REVENGE_ATTACK				= "",	
}

INIT_AI = 
{
	ALLY = 
	{
		FAR_LOST_RANGE	= 1400,			-- 이 거리보다 멀어지면 유저 옆으로 텔레포트
		LOST_RANGE		= 1400,			-- 이 거리보다 멀어지면 유저 쪽으로 걸어감
	},

	TARGET =
	{
		TARGET_PRIORITY 			= TARGET_PRIORITY["TP_NEAR_FIRST"],
		TARGET_INTERVAL 			= 1,
		TARGET_NEAR_RANGE 			= 1000,
		TARGET_RANGE 				= 2000,
		TARGET_LOST_RANGE 			= 5000,
		TARGET_SUCCESS_RATE 		= 100,
		ATTACK_TARGET_RATE 			= 100,
		PRESERVE_LAST_TARGET_RATE 	= 20,
	},
	
	CHASE_MOVE = 
	{		
		MOVE_SPLIT_RANGE	= 600,
		DEST_GAP			= 200,	-- 목적지에서 이 거리 안에 있으면 도착했다고 판단한다
		MOVE_GAP			= 300,
		
		DIR_CHANGE_INTERVAL = 0.7,
		DIR_CHANGE_INTERVAL = 0.7,
		
		WALK_INTERVAL		= 1,
		NEAR_WALK_RATE		= 1,   --  70,
		FAR_WALK_RATE		= 1,   -- 30,
		
		JUMP_INTERVAL		= 10,
		UP_JUMP_RATE		= 100, -- 40,
		UP_DOWN_RATE		= 20,
		DOWN_JUMP_RATE		= 100,    --  20,
		DOWN_DOWN_RATE		= 40,
	},	
	
	PATROL_MOVE = 	
	{
		PATROL_BEGIN_RATE		= 1, --50,		
		PATROL_RANGE			= 100,
		PATROL_COOL_TIME		= 2,
		ONLY_THIS_LINE_GROUP	= TRUE,
	},
	
	ESCAPE_MOVE = 
	{		
		MOVE_SPLIT_RANGE	= 500,	-- cm
		ESCAPE_GAP			= 600,	-- 이 거리 보다 멀어지면 도망 성공
		
		WALK_INTERVAL		= 1.5,	-- 초
		NEAR_WALK_RATE		= 100,   --  10,
		FAR_WALK_RATE		= 100,   -- 10,
		
		JUMP_INTERVAL		= 10,
		UP_JUMP_RATE		= 100, -- 30,
		UP_DOWN_RATE		= 30,
		DOWN_JUMP_RATE		= 100,    --  30,
		DOWN_DOWN_RATE		= 30,
	},
	
	
}



CSM_ARMADILLO_START = 
{
	ANIM_NAME					= "WaitStart",
	PLAY_TYPE					= XSKIN_ANIM_PLAYTYPE["XAP_ONE_WAIT"],
	TRANSITION					= TRUE,
	
	CAN_PUSH_UNIT				= TRUE,
	CAN_PASS_UNIT				= FALSE,	
	
	RIGHT						= TRUE,
	
	SPEED_X						= 0,
	SPEED_Y						= 0,
	
	EVENT_PROCESS = 
	{
		{ STATE_CHANGE_TYPE["SCT_MOTION_END"],				"CSM_ARMADILLO_WAIT",						},
	},
}


CSM_ARMADILLO_WAIT = 
{
	ANIM_NAME					= "Wait",
	PLAY_TYPE					= XSKIN_ANIM_PLAYTYPE["XAP_LOOP"],
	TRANSITION					= TRUE,
	
	CAN_PUSH_UNIT				= TRUE,
	CAN_PASS_UNIT				= FALSE,	
	
	SPEED_X						= 0,
	SPEED_Y						= 0,
	
	IMMADIATE_PACKET_SEND		= TRUE,
	EVENT_INTERVAL_TIME0		= 2,
	
	EVENT_PROCESS = 
	{		
		{ STATE_CHANGE_TYPE["SCT_FOOT_ON_LINE_FALSE_DOWN"],	"CSM_ARMADILLO_JUMP_DOWN",					},
		
		{ STATE_CHANGE_TYPE["SCT_CONDITION_TABLE"],			"CSM_ARMADILLO_ATTACK",					"CT_CSM_ARMADILLO_ATTACK",	},
		{ STATE_CHANGE_TYPE["SCT_CONDITION_TABLE"],			"CSM_ARMADILLO_ROLLING_ATTACK",			"CT_CSM_ARMADILLO_ROLLING_ATTACK",	},
		--{ STATE_CHANGE_TYPE["SCT_CONDITION_TABLE"],			"CSM_ARMADILLO_JUMP_FOR_ATTACK",		"CT_CSM_ARMADILLO_JUMP_FOR_ATTACK",	},
		
		{ STATE_CHANGE_TYPE["SCT_AI_WALK"],					"CSM_ARMADILLO_WALK",						},
		{ STATE_CHANGE_TYPE["SCT_AI_DASH"],					"CSM_ARMADILLO_WALK",						},
		{ STATE_CHANGE_TYPE["SCT_AI_JUMP"],					"CSM_ARMADILLO_JUMP_UP",						},
		{ STATE_CHANGE_TYPE["SCT_AI_JUMP_DIR"],				"CSM_ARMADILLO_JUMP_UP_DIR",					},
		{ STATE_CHANGE_TYPE["SCT_AI_DOWN"],					"CSM_ARMADILLO_JUMP_DOWN",					},
		{ STATE_CHANGE_TYPE["SCT_AI_DOWN_DIR"],				"CSM_ARMADILLO_JUMP_DOWN_DIR",				},
		
		{ STATE_CHANGE_TYPE["SCT_CONDITION_TABLE"],			"CSM_ARMADILLO_WAIT3",						"CT_CSM_ARMADILLO_WAIT3",		},
	},

	
	CT_CSM_ARMADILLO_ATTACK = 
	{
		IS_ANOTHER_TEAM				= TRUE,
		EVENT_INTERVAL_ID			= 0,
		DISTANCE_TO_TARGET_NEAR		= 250,
		RATE						= 100,
	},

	CT_CSM_ARMADILLO_ROLLING_ATTACK = 
	{
		IS_ANOTHER_TEAM				= TRUE,
		EVENT_INTERVAL_ID			= 0,
		DISTANCE_TO_TARGET_NEAR		= 400,
		RATE						= 100,
	},
	

	CT_CSM_ARMADILLO_WAIT3 = 
	{
		ANIM_PLAY_COUNT		= 15,
		RATE				= 50,
	},
}



CSM_ARMADILLO_WAIT3 = 
{
	ANIM_NAME					= "WaitHabit",
	PLAY_TYPE					= XSKIN_ANIM_PLAYTYPE["XAP_ONE_WAIT"],
	TRANSITION					= TRUE,
	
	CAN_PUSH_UNIT				= TRUE,
	CAN_PASS_UNIT				= FALSE,
	IMMADIATE_PACKET_SEND		= TRUE,
	
	EVENT_PROCESS = 
	{		
		{ STATE_CHANGE_TYPE["SCT_FOOT_ON_LINE_FALSE_DOWN"],	"CSM_ARMADILLO_JUMP_DOWN",					},
		{ STATE_CHANGE_TYPE["SCT_MOTION_END"],				"CSM_ARMADILLO_WAIT",						},
	},
}

CSM_ARMADILLO_END = 
{
	ANIM_NAME					= "Wait",
	PLAY_TYPE					= XSKIN_ANIM_PLAYTYPE["XAP_ONE_WAIT"],
	TRANSITION					= TRUE,
	
	CAN_PUSH_UNIT				= FALSE,
	CAN_PASS_UNIT				= TRUE,	

    INVINCIBLE					= { 0, 100, }, 
    
	SPEED_X						= 0,
	SPEED_Y						= 0,
	
	RIGHT						= FALSE,
	
	DYING_END					= TRUE,	
	
	IMMADIATE_PACKET_SEND		= TRUE,	
}

CSM_ARMADILLO_WALK = 
{
	ANIM_NAME					= "Walk",
	PLAY_TYPE					= XSKIN_ANIM_PLAYTYPE["XAP_LOOP"],
	TRANSITION					= TRUE,
	
	CAN_PUSH_UNIT				= TRUE,
	CAN_PASS_UNIT				= FALSE,

    SOUND_PLAY0			= { 0.246, "ARMADILLO_Walk.ogg" },

	PASSIVE_SPEED_X				= INIT_PHYSIC["WALK_SPEED"],
	
	ALLOW_DIR_CHANGE			= TRUE,
	IMMADIATE_PACKET_SEND		= TRUE,
	
	EVENT_INTERVAL_TIME0		= 2,
	
	EVENT_PROCESS = 
	{		
		{ STATE_CHANGE_TYPE["SCT_FOOT_ON_LINE_FALSE_DOWN"],	"CSM_ARMADILLO_JUMP_DOWN_DIR",				},
		
		{ STATE_CHANGE_TYPE["SCT_CONDITION_TABLE"],			"CSM_ARMADILLO_ATTACK",						"CT_CSM_ARMADILLO_ATTACK",	},
		{ STATE_CHANGE_TYPE["SCT_CONDITION_TABLE"],			"CSM_ARMADILLO_ROLLING_ATTACK",				"CT_CSM_ARMADILLO_ROLLING_ATTACK",	},
		--{ STATE_CHANGE_TYPE["SCT_CONDITION_TABLE"],			"CSM_ARMADILLO_JUMP_FOR_ATTACK",			"CT_CSM_ARMADILLO_JUMP_FOR_ATTACK",	},
		
		
		{ STATE_CHANGE_TYPE["SCT_AI_WAIT"],					"CSM_ARMADILLO_WAIT",						},
		{ STATE_CHANGE_TYPE["SCT_AI_JUMP"],					"CSM_ARMADILLO_JUMP_UP",						},
		{ STATE_CHANGE_TYPE["SCT_AI_JUMP_DIR"],				"CSM_ARMADILLO_JUMP_UP_DIR",					},
		{ STATE_CHANGE_TYPE["SCT_AI_DOWN"],					"CSM_ARMADILLO_JUMP_DOWN",					},
		{ STATE_CHANGE_TYPE["SCT_AI_DOWN_DIR"],				"CSM_ARMADILLO_JUMP_DOWN_DIR",				},
	},
	
	CT_CSM_ARMADILLO_ATTACK = 
	{
		IS_ANOTHER_TEAM				= TRUE,
		EVENT_INTERVAL_ID			= 0,
		DISTANCE_TO_TARGET_NEAR		= 250,
		RATE						= 100,
	},
	
	CT_CSM_ARMADILLO_ROLLING_ATTACK = 
	{
		IS_ANOTHER_TEAM				= TRUE,
		EVENT_INTERVAL_ID			= 0,
		DISTANCE_TO_TARGET_NEAR		= 400,
		RATE						= 100,
	},
	
	
	TALK_BOX = 
	{
		{ RATE = 8, MESSAGE = STR_ID_1486 },
	},
}

CSM_ARMADILLO_JUMP_UP = 
{
	ANIM_NAME					= "JumpUp",
	PLAY_TYPE					= XSKIN_ANIM_PLAYTYPE["XAP_LOOP"],
	TRANSITION					= TRUE,
	LAND_CONNECT				= FALSE,
	
	CAN_PUSH_UNIT				= TRUE,
	CAN_PASS_UNIT				= FALSE,
	
	SPEED_X						= 0,
	SPEED_Y						= INIT_PHYSIC["JUMP_SPEED"],
	ADD_POS_Y					= 45,
	
	IMMADIATE_PACKET_SEND		= TRUE,
	
	EVENT_PROCESS = 
	{		
		{ STATE_CHANGE_TYPE["SCT_NEGATIVE_Y_SPEED"],		"CSM_ARMADILLO_JUMP_DOWN",				},
	},
	
}

CSM_ARMADILLO_JUMP_DOWN = 
{
	ANIM_NAME					= "JumpDown",
	PLAY_TYPE					= XSKIN_ANIM_PLAYTYPE["XAP_LOOP"],
	TRANSITION					= TRUE,
	LAND_CONNECT				= FALSE,
	
	CAN_PUSH_UNIT				= TRUE,
	CAN_PASS_UNIT				= FALSE,
	
	
	
	IMMADIATE_PACKET_SEND		= TRUE,
		
	EVENT_PROCESS = 
	{		
		{ STATE_CHANGE_TYPE["SCT_FOOT_ON_LINE_TRUE"],		"CSM_ARMADILLO_JUMP_LANDING",				},
	},
}

CSM_ARMADILLO_JUMP_UP_DIR = 
{
	ANIM_NAME					= "JumpUp",
	PLAY_TYPE					= XSKIN_ANIM_PLAYTYPE["XAP_LOOP"],
	TRANSITION					= TRUE,
	LAND_CONNECT				= FALSE,
	
	CAN_PUSH_UNIT				= TRUE,
	CAN_PASS_UNIT				= FALSE,
	
	PASSIVE_SPEED_X				= INIT_PHYSIC["WALK_SPEED"],
	SPEED_Y						= INIT_PHYSIC["JUMP_SPEED"],
	ADD_POS_Y					= 45,
	
	IMMADIATE_PACKET_SEND		= TRUE,
	
	EVENT_PROCESS = 
	{		

		{ STATE_CHANGE_TYPE["SCT_NEGATIVE_Y_SPEED"],		"CSM_ARMADILLO_JUMP_DOWN_DIR",				},
	},
	
}

CSM_ARMADILLO_JUMP_DOWN_DIR = 
{
	ANIM_NAME					= "JumpDown",
	PLAY_TYPE					= XSKIN_ANIM_PLAYTYPE["XAP_LOOP"],
	TRANSITION					= TRUE,
	LAND_CONNECT				= FALSE,
	
	CAN_PUSH_UNIT				= TRUE,
	CAN_PASS_UNIT				= FALSE,
	
	
	
	PASSIVE_SPEED_X				= INIT_PHYSIC["WALK_SPEED"],
	
	IMMADIATE_PACKET_SEND		= TRUE,
		
	EVENT_PROCESS = 
	{		
		{ STATE_CHANGE_TYPE["SCT_FOOT_ON_LINE_TRUE"],		"CSM_ARMADILLO_JUMP_LANDING",				},
	},
}

CSM_ARMADILLO_JUMP_LANDING = 
{
	ANIM_NAME					= "JumpLanding",
	PLAY_TYPE					= XSKIN_ANIM_PLAYTYPE["XAP_ONE_WAIT"],
	TRANSITION					= TRUE,
	LAND_CONNECT				= FALSE,
	
	CAN_PUSH_UNIT				= TRUE,
	CAN_PASS_UNIT				= FALSE,

    SOUND_PLAY0			= { 0.425, "ARMADILLO_Voice2.ogg" },
	
	SPEED_X						= 0,
	SPEED_Y						= 0,
		
	IMMADIATE_PACKET_SEND		= TRUE,

	EVENT_PROCESS = 
	{		
		{ STATE_CHANGE_TYPE["SCT_FOOT_ON_LINE_FALSE_DOWN"],	"CSM_ARMADILLO_JUMP_DOWN",				},
		{ STATE_CHANGE_TYPE["SCT_MOTION_END"],				"CSM_ARMADILLO_WAIT",					},
	},
}

CSM_ARMADILLO_ATTACK = 
{
	ANIM_SPEED					= 1.3,
	ANIM_NAME					= "Attack",
	PLAY_TYPE					= XSKIN_ANIM_PLAYTYPE["XAP_ONE_WAIT"],
	TRANSITION					= FALSE,
	LAND_CONNECT				= FALSE,
	
	CAN_PUSH_UNIT				= TRUE,
	CAN_PASS_UNIT				= FALSE,

    SOUND_PLAY0			= { 0.348, "ARMADILLO_attack.ogg" },

	SPEED_X						= 0,
	SPEED_Y						= 0,	
	
	VIEW_TARGET					= TRUE,
	
	IMMADIATE_PACKET_SEND		= TRUE,
	
			
	EVENT_PROCESS = 
	{		
		{ STATE_CHANGE_TYPE["SCT_FOOT_ON_LINE_FALSE_DOWN"],	"CSM_ARMADILLO_JUMP_DOWN",				},
		{ STATE_CHANGE_TYPE["SCT_MOTION_END"],				"CSM_ARMADILLO_WAIT",					},
	},
	
	ATTACK_TIME0				= { 0.930, 1.259, },
	
	DAMAGE_DATA = 
	{
		DAMAGE_TYPE		= DAMAGE_TYPE["DT_PHYSIC"],
		HIT_TYPE		= HIT_TYPE["HT_PUNCH_HIT"],
		REACT_TYPE		= REACT_TYPE["RT_BIG_DAMAGE"],
		
		DAMAGE = 
		{
			PHYSIC		= 1.5,
		},
		
		BACK_SPEED_X			= INIT_PHYSIC["WALK_SPEED"] * 2.0,
		BACK_SPEED_Y			= 0.0,
		
		CAMERA_CRASH_GAP		= 5.0,	
		CAMERA_CRASH_TIME		= 0.2,		
	},
	
	TALK_BOX =
	{
		{ RATE = 8, MESSAGE = STR_ID_1487 },
		{ RATE = 8, MESSAGE = STR_ID_1488 },
	},
}





CSM_ARMADILLO_ROLLING_ATTACK = 
{
	ANIM_SPEED					= 1.2,
	ANIM_NAME					= "RollingAttack",
	PLAY_TYPE					= XSKIN_ANIM_PLAYTYPE["XAP_ONE_WAIT"],
	TRANSITION					= FALSE,
	LAND_CONNECT				= FALSE,
	
	CAN_PUSH_UNIT				= TRUE,
	CAN_PASS_UNIT				= TRUE,	

    SOUND_PLAY0			= { 0.455, "ARMADILLO_Voice.ogg" },
    SOUND_PLAY1			= { 0.874, "ARMADILLO_Rolling.ogg" },
	
	IMMADIATE_PACKET_SEND		= TRUE,
	
	VIEW_TARGET					= TRUE,
	
	EVENT_PROCESS = 
	{		
		--{ STATE_CHANGE_TYPE["SCT_FOOT_ON_LINE_FALSE_DOWN"],	"CSM_ARMADILLO_JUMP_DOWN",				},
		{ STATE_CHANGE_TYPE["SCT_MOTION_END"],				"CSM_ARMADILLO_WAIT",					},
	},
	
	ATTACK_TIME0				= { 1.385, 1.959, },
	
	DAMAGE_DATA = 
	{
		DAMAGE_TYPE		= DAMAGE_TYPE["DT_PHYSIC"],
		HIT_TYPE		= HIT_TYPE["HT_PUNCH_HIT"],
		REACT_TYPE		= REACT_TYPE["RT_BIG_DAMAGE"],
		
		DAMAGE = 
		{
			PHYSIC		= 3.0,
		},
		
		BACK_SPEED_X			= INIT_PHYSIC["WALK_SPEED"],
		BACK_SPEED_Y			= 0.0,
		
		STOP_TIME_DEF			= 0.15,
		
		CAMERA_CRASH_GAP		= 5.0,	
		CAMERA_CRASH_TIME		= 0.2,		
	},
	
	TALK_BOX =
	{
		{ RATE = 8, MESSAGE = STR_ID_1490 },
	},
}



CSM_ARMADILLO_DEFENCE =
{
	ANIM_NAME					= "Defence",
	PLAY_TYPE					= XSKIN_ANIM_PLAYTYPE["XAP_ONE_WAIT"],
	TRANSITION					= FALSE,
	LAND_CONNECT				= FALSE,
	
	CAN_PUSH_UNIT				= TRUE,
	CAN_PASS_UNIT				= FALSE,

	SUPER_ARMOR					= TRUE,
	DEFENCE						= { 0, 100, 50, }, 
	
	EVENT_PROCESS = 
	{
		{ STATE_CHANGE_TYPE["SCT_CONDITION_TABLE"],		"CSM_ARMADILLO_WAIT",				"CT_CSM_ARMADILLO_WAIT"		},
	},
	
	CT_CSM_ARMADILLO_WAIT = 
	{
		STATE_TIME_OVER			= 2,
	},
	
	
	TALK_BOX =
	{
		{ RATE = 20, MESSAGE = STR_ID_1491 },
	},
}



CSM_ARMADILLO_DAMAGE_SMALL = 
{
	ANIM_NAME					= "DamageSmall",
	PLAY_TYPE					= XSKIN_ANIM_PLAYTYPE["XAP_ONE_WAIT"],
	TRANSITION					= FALSE,
	LAND_CONNECT				= FALSE,
	
	CAN_PUSH_UNIT				= TRUE,
	CAN_PASS_UNIT				= FALSE,

	EVENT_INTERVAL_TIME0		= 0.3,
	
	EVENT_PROCESS = 
	{
		{ STATE_CHANGE_TYPE["SCT_MOTION_END"],				"CSM_ARMADILLO_WAIT",												},
	},
	
	
	TALK_BOX =
	{
		{ RATE = 10, MESSAGE = STR_ID_1465 },
		{ RATE = 10, MESSAGE = STR_ID_1463 },
	},
}

CSM_ARMADILLO_DAMAGE_BIG = 
{
	ANIM_NAME					= "DamageBig",
	PLAY_TYPE					= XSKIN_ANIM_PLAYTYPE["XAP_ONE_WAIT"],
	TRANSITION					= FALSE,
	LAND_CONNECT				= FALSE,
	
	CAN_PUSH_UNIT				= TRUE,
	CAN_PASS_UNIT				= FALSE,
	
	EVENT_INTERVAL_TIME0		= 0.3,
	
	EVENT_PROCESS = 
	{
		{ STATE_CHANGE_TYPE["SCT_MOTION_END"],				"CSM_ARMADILLO_WAIT",												},
	},

	
	TALK_BOX = 
	{
		{ RATE = 14, MESSAGE = STR_ID_1464 },
	},

}

CSM_ARMADILLO_DAMAGE_DOWN_FRONT = 
{
	ANIM_NAME					= "DamageDownFront",
	PLAY_TYPE					= XSKIN_ANIM_PLAYTYPE["XAP_ONE_WAIT"],
	TRANSITION					= FALSE,
	LAND_CONNECT				= FALSE,

	SUPER_ARMOR					= TRUE,
	DEFENCE						= { 0, 100, 20, },
	
	CAN_PUSH_UNIT				= TRUE,
	CAN_PASS_UNIT				= FALSE,
	

	EVENT_PROCESS = 
	{
		{ STATE_CHANGE_TYPE["SCT_FOOT_ON_LINE_FALSE_DOWN"],		"CSM_ARMADILLO_DAMAGE_AIR_FALL",			},
		--{ STATE_CHANGE_TYPE["SCT_CONDITION_TABLE"],				"CSM_ARMADILLO_STAND_UP_ATTACK_FRONT",	"CT_CSM_ARMADILLO_STAND_UP_ATTACK_FRONT", },
		{ STATE_CHANGE_TYPE["SCT_MOTION_END"],					"CSM_ARMADILLO_STAND_UP_FRONT",			},
	},
	
	-- CT_CSM_ARMADILLO_STAND_UP_ATTACK_FRONT = 
	-- {
		-- ANIM_PLAY_COUNT		= 1,
		-- RATE				= 10,
	-- },
	
	TALK_BOX =
	{
		{ RATE = 10, MESSAGE = STR_ID_1465 },
		{ RATE = 10, MESSAGE = STR_ID_1463 },
	},
}

CSM_ARMADILLO_DAMAGE_DOWN_BACK = 
{
	ANIM_NAME					= "DamageDownBack",
	PLAY_TYPE					= XSKIN_ANIM_PLAYTYPE["XAP_ONE_WAIT"],
	TRANSITION					= FALSE,
	LAND_CONNECT				= FALSE,
	
	SUPER_ARMOR					= TRUE,
	DEFENCE						= { 0, 100, 20, },
	
	CAN_PUSH_UNIT				= TRUE,
	CAN_PASS_UNIT				= FALSE,
	

	
	EVENT_PROCESS = 
	{
		{ STATE_CHANGE_TYPE["SCT_FOOT_ON_LINE_FALSE_DOWN"],		"CSM_ARMADILLO_DAMAGE_AIR_FALL",			},
		--{ STATE_CHANGE_TYPE["SCT_CONDITION_TABLE"],				"CSM_ARMADILLO_STAND_UP_ATTACK_BACK",	"CT_CSM_ARMADILLO_STAND_UP_ATTACK_BACK", },
		{ STATE_CHANGE_TYPE["SCT_MOTION_END"],					"CSM_ARMADILLO_STAND_UP_BACK",			},
	},
	
	-- CT_CSM_ARMADILLO_STAND_UP_ATTACK_BACK = 
	-- {
		-- ANIM_PLAY_COUNT		= 1,
		-- RATE				= 10,
	-- },
	
	TALK_BOX =
	{
		{ RATE = 10, MESSAGE = STR_ID_1465 },
		{ RATE = 10, MESSAGE = STR_ID_1463 },
	},
}

CSM_ARMADILLO_DAMAGE_FLY_FRONT = 
{
	ANIM_NAME					= "DamageAirFlyFront",
	PLAY_TYPE					= XSKIN_ANIM_PLAYTYPE["XAP_ONE_WAIT"],
	TRANSITION					= FALSE,
	LAND_CONNECT				= FALSE,	
	
	CAN_PUSH_UNIT				= TRUE,
	CAN_PASS_UNIT				= FALSE,
	
	EVENT_PROCESS = 
	{
		{ STATE_CHANGE_TYPE["SCT_FOOT_ON_LINE_TRUE"],			"CSM_ARMADILLO_DAMAGE_DOWN_FRONT",		},
	},
	
	TALK_BOX =
	{
		{ RATE = 10, MESSAGE = STR_ID_1433 },
	},
}

CSM_ARMADILLO_DAMAGE_FLY_BACK = 
{
	ANIM_NAME					= "DamageAirFlyBack",
	PLAY_TYPE					= XSKIN_ANIM_PLAYTYPE["XAP_ONE_WAIT"],
	TRANSITION					= FALSE,
	LAND_CONNECT				= FALSE,	
	
	CAN_PUSH_UNIT				= TRUE,
	CAN_PASS_UNIT				= FALSE,
	
	EVENT_PROCESS = 
	{
		{ STATE_CHANGE_TYPE["SCT_FOOT_ON_LINE_TRUE"],			"CSM_ARMADILLO_DAMAGE_DOWN_BACK",		},
	},
	
	TALK_BOX =
	{
		{ RATE = 10, MESSAGE = STR_ID_1433 },
	},
}

CSM_ARMADILLO_DAMAGE_AIR = 
{
	ANIM_NAME					= "DamageAirSmall",
	PLAY_TYPE					= XSKIN_ANIM_PLAYTYPE["XAP_ONE_WAIT"],
	TRANSITION					= FALSE,
	LAND_CONNECT				= FALSE,
	
	CAN_PUSH_UNIT				= TRUE,
	CAN_PASS_UNIT				= FALSE,
	
	EVENT_PROCESS = 
	{
		{ STATE_CHANGE_TYPE["SCT_FOOT_ON_LINE_TRUE"],			"CSM_ARMADILLO_WAIT",					},
	},
}

CSM_ARMADILLO_DAMAGE_AIR_DOWN = 
{
	ANIM_NAME					= "DamageAirDown",
	PLAY_TYPE					= XSKIN_ANIM_PLAYTYPE["XAP_ONE_WAIT"],
	TRANSITION					= FALSE,
	LAND_CONNECT				= FALSE,
	
	CAN_PUSH_UNIT				= TRUE,
	CAN_PASS_UNIT				= FALSE,
	
	EVENT_PROCESS = 
	{
		{ STATE_CHANGE_TYPE["SCT_FOOT_ON_LINE_TRUE"],			"CSM_ARMADILLO_DAMAGE_AIR_DOWN_LANDING",	},
	},
}

CSM_ARMADILLO_DAMAGE_AIR_UP = 
{
	ANIM_NAME					= "DamageAirUp",
	PLAY_TYPE					= XSKIN_ANIM_PLAYTYPE["XAP_ONE_WAIT"],
	TRANSITION					= FALSE,
	LAND_CONNECT				= FALSE,
	
	CAN_PUSH_UNIT				= TRUE,
	CAN_PASS_UNIT				= FALSE,

	
	EVENT_PROCESS = 
	{
		{ STATE_CHANGE_TYPE["SCT_NEGATIVE_Y_SPEED"],		"CSM_ARMADILLO_DAMAGE_AIR_FALL",			},
		{ STATE_CHANGE_TYPE["SCT_FOOT_ON_LINE_TRUE"],		"CSM_ARMADILLO_DAMAGE_AIR_DOWN_LANDING",	},
	},
	
	TALK_BOX =
	{
		{ RATE = 10, MESSAGE = STR_ID_1433 },
	},
}

CSM_ARMADILLO_DAMAGE_AIR_FALL = 
{
	ANIM_NAME					= "DamageAirFall",
	PLAY_TYPE					= XSKIN_ANIM_PLAYTYPE["XAP_ONE_WAIT"],
	TRANSITION					= FALSE,
	LAND_CONNECT				= FALSE,
	
	CAN_PUSH_UNIT				= TRUE,
	CAN_PASS_UNIT				= FALSE,
	
	EVENT_PROCESS = 
	{
		{ STATE_CHANGE_TYPE["SCT_POSITIVE_Y_SPEED"],		"CSM_ARMADILLO_DAMAGE_AIR_UP",			},
		{ STATE_CHANGE_TYPE["SCT_FOOT_ON_LINE_TRUE"],		"CSM_ARMADILLO_DAMAGE_AIR_DOWN_LANDING",	},
	},
}

CSM_ARMADILLO_DAMAGE_AIR_DOWN_LANDING = 
{
	ANIM_NAME					= "DamageAirDownLanding",
	PLAY_TYPE					= XSKIN_ANIM_PLAYTYPE["XAP_ONE_WAIT"],
	TRANSITION					= FALSE,
	LAND_CONNECT				= FALSE,
	
	SUPER_ARMOR					= TRUE,
	DEFENCE						= { 0, 100, 20, },
	
	CAN_PUSH_UNIT				= TRUE,
	CAN_PASS_UNIT				= FALSE,
	
	EVENT_PROCESS = 
	{
		{ STATE_CHANGE_TYPE["SCT_FOOT_ON_LINE_FALSE_DOWN"],	"CSM_ARMADILLO_DAMAGE_AIR_FALL",			},
		--{ STATE_CHANGE_TYPE["SCT_CONDITION_TABLE"],			"CSM_ARMADILLO_STAND_UP_ATTACK_FRONT",	"CT_CSM_ARMADILLO_STAND_UP_ATTACK_FRONT", },
		{ STATE_CHANGE_TYPE["SCT_MOTION_END"],				"CSM_ARMADILLO_STAND_UP_FRONT",			},
	},
	
	-- CT_CSM_ARMADILLO_STAND_UP_ATTACK_FRONT = 
	-- {
		-- ANIM_PLAY_COUNT		= 1,
		-- RATE				= 10,
	-- },
}

CSM_ARMADILLO_STAND_UP_FRONT = 
{
	ANIM_NAME					= "DamageStandUpFront",
	PLAY_TYPE					= XSKIN_ANIM_PLAYTYPE["XAP_ONE_WAIT"],
	TRANSITION					= FALSE,
	LAND_CONNECT				= FALSE,	
	
	SUPER_ARMOR					= TRUE,
	DEFENCE						= { 0, 100, 20, },
	
	CAN_PUSH_UNIT				= TRUE,
	CAN_PASS_UNIT				= FALSE,
	
	EVENT_PROCESS = 
	{
		{ STATE_CHANGE_TYPE["SCT_FOOT_ON_LINE_FALSE_DOWN"],	"CSM_ARMADILLO_JUMP_DOWN",			},
		{ STATE_CHANGE_TYPE["SCT_MOTION_END"],				"CSM_ARMADILLO_WAIT",				},
	},
}

CSM_ARMADILLO_STAND_UP_BACK = 
{
	ANIM_NAME					= "DamageStandUpBack",
	PLAY_TYPE					= XSKIN_ANIM_PLAYTYPE["XAP_ONE_WAIT"],
	TRANSITION					= FALSE,
	LAND_CONNECT				= FALSE,
	
	SUPER_ARMOR					= TRUE,
	DEFENCE						= { 0, 100, 20, },
		
	CAN_PUSH_UNIT				= TRUE,
	CAN_PASS_UNIT				= FALSE,
		
	EVENT_PROCESS = 
	{
		{ STATE_CHANGE_TYPE["SCT_FOOT_ON_LINE_FALSE_DOWN"],	"CSM_ARMADILLO_JUMP_DOWN", },
		{ STATE_CHANGE_TYPE["SCT_MOTION_END"],				"CSM_ARMADILLO_WAIT", },
	},		
}

CSM_ARMADILLO_STAND_UP_ATTACK_FRONT = 
{
	ANIM_NAME					= "StandUpAttackFront",
	PLAY_TYPE					= XSKIN_ANIM_PLAYTYPE["XAP_ONE_WAIT"],
	TRANSITION					= FALSE,
	LAND_CONNECT				= FALSE,
	
	ANIM_WAIT_TIME				= 1,	
	
	SUPER_ARMOR					= TRUE,
	DEFENCE						= { 0, 100, 20, },

	MIND_FLAG					= MIND_FLAG["MF_STAND_UP_ATTACK"],
    SOUND_PLAY0					= { 0.375, "ARMADILLO_StandUpRolling.ogg" },

	CAN_PUSH_UNIT				= TRUE,
	CAN_PASS_UNIT				= FALSE,
	
	EVENT_PROCESS = 
	{
		--{ STATE_CHANGE_TYPE["SCT_FOOT_ON_LINE_FALSE_DOWN"],	"CSM_ARMADILLO_JUMP_DOWN",			},
		{ STATE_CHANGE_TYPE["SCT_MOTION_END"],				"CSM_ARMADILLO_WAIT",				},
	},
		
	ATTACK_TIME0				= { 0.375, 0.813, },	

	DAMAGE_DATA = 
	{
		DAMAGE_TYPE		= DAMAGE_TYPE["DT_PHYSIC"],
		HIT_TYPE		= HIT_TYPE["HT_PUNCH_HIT"],
		REACT_TYPE		= REACT_TYPE["RT_BIG_DAMAGE"],
		
		DAMAGE = 
		{
			PHYSIC		= 1.0,
		},
		
		BACK_SPEED_X			= INIT_PHYSIC["RUN_SPEED"],
		BACK_SPEED_Y			= 0.0,
		
		STOP_TIME_ATT			= 0.0,		
		STOP_TIME_DEF			= 0.0,	
		CAMERA_CRASH_GAP		= 5.0,	
		CAMERA_CRASH_TIME		= 0.2,
		CLEAR_SCREEN			= 0.0,	
		CLEAR_SCREEN_COLOR_A	= 0.0,
		CLEAR_SCREEN_COLOR_R	= 1.0,
		CLEAR_SCREEN_COLOR_G	= 1.0,
		CLEAR_SCREEN_COLOR_B	= 1.0,

		RE_ATTACK				= FALSE,		
		HIT_GAP					= 0.0,				
	},
	
}

CSM_ARMADILLO_STAND_UP_ATTACK_BACK = 
{
	ANIM_NAME					= "StandUpAttackBack",
	PLAY_TYPE					= XSKIN_ANIM_PLAYTYPE["XAP_ONE_WAIT"],
	TRANSITION					= FALSE,
	LAND_CONNECT				= FALSE,
	
	
	ANIM_WAIT_TIME				= 1,

	SUPER_ARMOR					= TRUE,
	DEFENCE						= { 0, 100, 20, },

	MIND_FLAG					= MIND_FLAG["MF_STAND_UP_ATTACK"],
    SOUND_PLAY0					= { 0.403, "ARMADILLO_StandUpRolling.ogg" },

	CAN_PUSH_UNIT				= TRUE,
	CAN_PASS_UNIT				= FALSE,


	
	FLIP_DIR_END				= TRUE,
	
	EVENT_PROCESS = 
	{
		--{ STATE_CHANGE_TYPE["SCT_FOOT_ON_LINE_FALSE_DOWN"],	"CSM_ARMADILLO_JUMP_DOWN", },
		{ STATE_CHANGE_TYPE["SCT_MOTION_END"],				"CSM_ARMADILLO_WAIT", },
	},	
	
		
	ATTACK_TIME0				= { 0.462, 0.943, },	
	
	DAMAGE_DATA = 
	{
		DAMAGE_TYPE		= DAMAGE_TYPE["DT_PHYSIC"],
		HIT_TYPE		= HIT_TYPE["HT_PUNCH_HIT"],
		REACT_TYPE		= REACT_TYPE["RT_BIG_DAMAGE"],
		
		DAMAGE = 
		{
			PHYSIC		= 1.0,
			FIRE		= 0.0,
			ICE			= 0.0,
			EARTH		= 0.0,
			LIGHTNING	= 0.0,
			DARK		= 0.0,
			LIGHT		= 0.0,
			UNIVERSAL	= 0.0,
		},
		
		BACK_SPEED_X			= INIT_PHYSIC["RUN_SPEED"],
		BACK_SPEED_Y			= 0.0,
		
		STOP_TIME_ATT			= 0.0,		
		STOP_TIME_DEF			= 0.0,	
		CAMERA_CRASH_GAP		= 5.0,	
		CAMERA_CRASH_TIME		= 0.2,
		CLEAR_SCREEN			= 0.0,	
		CLEAR_SCREEN_COLOR_A	= 0.0,
		CLEAR_SCREEN_COLOR_R	= 1.0,
		CLEAR_SCREEN_COLOR_G	= 1.0,
		CLEAR_SCREEN_COLOR_B	= 1.0,

		RE_ATTACK				= FALSE,		
		HIT_GAP					= 0.0,				
	},
}

CSM_ARMADILLO_DAMAGE_REVENGE = 
{
	ANIM_NAME					= "DamageRevenge",
	PLAY_TYPE					= XSKIN_ANIM_PLAYTYPE["XAP_ONE_WAIT"],
	TRANSITION					= FALSE,
	LAND_CONNECT				= FALSE,
	
	CAN_PUSH_UNIT				= TRUE,
	CAN_PASS_UNIT				= FALSE,
	
	EVENT_PROCESS = 
	{
		{ STATE_CHANGE_TYPE["SCT_FOOT_ON_LINE_FALSE_DOWN"],	"CSM_ARMADILLO_DAMAGE_AIR_FALL",			},
		{ STATE_CHANGE_TYPE["SCT_MOTION_END"],				"CSM_ARMADILLO_WAIT",					},
	},
}




CSM_ARMADILLO_DYING_LAND_FRONT = 
{
	ANIM_NAME					= "DamageDownFront",
	PLAY_TYPE					= XSKIN_ANIM_PLAYTYPE["XAP_ONE_WAIT"],
	TRANSITION					= FALSE,
	LAND_CONNECT				= FALSE,

	INVINCIBLE					= { 0, 100, }, 		
	
	CAN_PUSH_UNIT				= FALSE,
	CAN_PASS_UNIT				= TRUE,
	
	DYING_END					= TRUE,
	
	IMMADIATE_PACKET_SEND		= TRUE,
}
	
CSM_ARMADILLO_DYING_LAND_BACK = 
{
	ANIM_NAME					= "DamageDownBack",
	PLAY_TYPE					= XSKIN_ANIM_PLAYTYPE["XAP_ONE_WAIT"],
	TRANSITION					= FALSE,
	LAND_CONNECT				= FALSE,
	
	INVINCIBLE					= { 0, 100, }, 		
	
	CAN_PUSH_UNIT				= FALSE,
	CAN_PASS_UNIT				= TRUE,
	
	DYING_END					= TRUE,	
	
	IMMADIATE_PACKET_SEND		= TRUE,
}

CSM_ARMADILLO_DYING_SKY = 
{
	ANIM_NAME					= "DamageAirDownLanding",
	PLAY_TYPE					= XSKIN_ANIM_PLAYTYPE["XAP_ONE_WAIT"],
	TRANSITION					= FALSE,
	LAND_CONNECT				= FALSE,
	
	INVINCIBLE					= { 0, 100, }, 		
	
	CAN_PUSH_UNIT				= FALSE,
	CAN_PASS_UNIT				= TRUE,
	
	DYING_END					= TRUE,
	
	IMMADIATE_PACKET_SEND		= TRUE,
}









--------------------------------------------------------------------
--------------------------------------------------------------------


function CSM_ARMADILLO_WAIT3_FRAME_MOVE( pKTDXApp, pX2Game, pNPCUnit )

	if pNPCUnit:AnimEventTimer_LUA( 0.7 ) then
		pMinorParticle = pX2Game:GetMinorParticle()
		pMinorParticle:CreateSequence_LUA( "StepSmoke", pNPCUnit:GetLandPosition_LUA(), D3DXVECTOR2(100,100), D3DXVECTOR2(5,-1) )
	end

end

function CSM_ARMADILLO_WALK_STATE_END( pKTDXApp, pX2Game, pNPCUnit )

	pMinorParticle = pX2Game:GetMinorParticle()
	pMinorParticle:CreateSequence_LUA( "StepSmoke", pNPCUnit:GetLandPosition_LUA(), D3DXVECTOR2(100,100), D3DXVECTOR2(5,-1) )

end

function CSM_ARMADILLO_JUMP_DOWN_STATE_END( pKTDXApp, pX2Game, pNPCUnit )

	pMinorParticle = pX2Game:GetMinorParticle()
	pMinorParticle:CreateSequence_LUA( "StepSmoke", pNPCUnit:GetLandPosition_LUA(), D3DXVECTOR2(100,100), D3DXVECTOR2(5,-1) )

end

function CSM_ARMADILLO_JUMP_DOWN_DIR_STATE_END( pKTDXApp, pX2Game, pNPCUnit )

	pMinorParticle = pX2Game:GetMinorParticle()
	pMinorParticle:CreateSequence_LUA( "StepSmoke", pNPCUnit:GetLandPosition_LUA(), D3DXVECTOR2(100,100), D3DXVECTOR2(5,-1) )

end

function CSM_ARMADILLO_JUMP_ROLLING_ATTACK_FRAME_MOVE( pKTDXApp, pX2Game, pNPCUnit )

	if pNPCUnit:AnimEventTimer_LUA( 0.1 ) then
	
		pNPCUnit:SetPassiveSpeed( 0, 0 )
		pNPCUnit:SetPassiveSpeed( 800, -1 )
		
	end

end


function CSM_ARMADILLO_DAMAGE_SMALL_FRAME_MOVE( pKTDXApp, pX2Game, pNPCUnit )

	if pNPCUnit:AnimEventTimer_LUA( 0.047 ) then
		pMinorParticle = pX2Game:GetMinorParticle()
		pMinorParticle:CreateSequence_LUA( "StepSmoke", pNPCUnit:GetLandPosition_LUA(), D3DXVECTOR2(100,100), D3DXVECTOR2(5,-1) )
	end

end

function CSM_ARMADILLO_DAMAGE_BIG_FRAME_MOVE( pKTDXApp, pX2Game, pNPCUnit )

	if pNPCUnit:AnimEventTimer_LUA( 0.06 ) then
		pMinorParticle = pX2Game:GetMinorParticle()
		pMinorParticle:CreateSequence_LUA( "StepSmoke", pNPCUnit:GetLandPosition_LUA(), D3DXVECTOR2(100,100), D3DXVECTOR2(5,-1) )
	end

end

function CSM_ARMADILLO_DAMAGE_DOWN_FRONT_FRAME_MOVE( pKTDXApp, pX2Game, pNPCUnit )

	if pNPCUnit:AnimEventTimer_LUA( 0.3 ) then
		pNPCUnit:PlaySound_LUA( "Down.ogg" )
		pMinorParticle = pX2Game:GetMinorParticle()
		pMinorParticle:CreateSequence_LUA( "DownSmoke", pNPCUnit:GetLandPosition_LUA(), D3DXVECTOR2(100,100), D3DXVECTOR2(7,-1) )
	end

end

function CSM_ARMADILLO_DAMAGE_DOWN_BACK_FRAME_MOVE( pKTDXApp, pX2Game, pNPCUnit )

	if pNPCUnit:AnimEventTimer_LUA( 0.2 ) then
		pNPCUnit:PlaySound_LUA( "Down.ogg" )
		pMinorParticle = pX2Game:GetMinorParticle()
		pMinorParticle:CreateSequence_LUA( "DownSmoke", pNPCUnit:GetLandPosition_LUA(), D3DXVECTOR2(100,100), D3DXVECTOR2(7,-1) )
	end

end

function CSM_ARMADILLO_DAMAGE_AIR_DOWN_LANDING_FRAME_MOVE( pKTDXApp, pX2Game, pNPCUnit )

	if pNPCUnit:AnimEventTimer_LUA( 0.01 ) then
		pNPCUnit:PlaySound_LUA( "Down.ogg" )
		pMinorParticle = pX2Game:GetMinorParticle()
		pos = pNPCUnit:GetLandPosition_LUA()
		pMinorParticle:CreateSequence_LUA( "DownSmoke", pos, D3DXVECTOR2(100,100), D3DXVECTOR2(7,-1) )
		pos.y = pos.y + 5
		pMinorParticle:CreateSequence_LUA( "GroundShockWave", pos, D3DXVECTOR2(100,100), D3DXVECTOR2(1,-1) )
		pParticle = pMinorParticle:CreateSequence_LUA( "AirDownTick", pNPCUnit:GetPos(), D3DXVECTOR2(200,200), D3DXVECTOR2(10,-1) )
		if pParticle ~= nil then 
			pParticle:SetLandPosition( pos.y - 5 )
		end
		
		if GetDistance_LUA( pNPCUnit:GetPos(), pX2Game:GetFocusUnitPos_LUA() ) < 500 then
			pX2Game:GetX2Camera():GetCamera():UpDownCrashCameraNoReset( 10.0, 0.1 )
		end		
		
	elseif pNPCUnit:AnimEventTimer_LUA( 0.44 ) then
		pNPCUnit:PlaySound_LUA( "Down.ogg" )
		pMinorParticle = pX2Game:GetMinorParticle()
		pMinorParticle:CreateSequence_LUA( "DownSmoke", pNPCUnit:GetLandPosition_LUA(), D3DXVECTOR2(100,100), D3DXVECTOR2(7,-1) )
	end

end

function CSM_ARMADILLO_STAND_UP_ATTACK_FRONT_FRAME_MOVE( pKTDXApp, pX2Game, pNPCUnit )

	if pNPCUnit:AnimEventTimer_LUA( 0.4 ) then
		pMinorParticle = pX2Game:GetMinorParticle()
		pMinorParticle:CreateSequence_LUA( "StepSmoke", pNPCUnit:GetLandPosition_LUA(), D3DXVECTOR2(100,100), D3DXVECTOR2(5,-1) )
	end
	
	if pNPCUnit:AnimEventTimer_LUA( 0.6 ) then
		pMinorParticle = pX2Game:GetMinorParticle()
		pMinorParticle:CreateSequence_LUA( "StepSmoke", pNPCUnit:GetLandPosition_LUA(), D3DXVECTOR2(100,100), D3DXVECTOR2(5,-1) )
	end
	
	if pNPCUnit:AnimEventTimer_LUA( 0.8 ) then
		pMinorParticle = pX2Game:GetMinorParticle()
		pMinorParticle:CreateSequence_LUA( "StepSmoke", pNPCUnit:GetLandPosition_LUA(), D3DXVECTOR2(100,100), D3DXVECTOR2(5,-1) )
	end

end

function CSM_ARMADILLO_STAND_UP_ATTACK_BACK_FRAME_MOVE( pKTDXApp, pX2Game, pNPCUnit )

	if pNPCUnit:AnimEventTimer_LUA( 0.4 ) then
		pMinorParticle = pX2Game:GetMinorParticle()
		pMinorParticle:CreateSequence_LUA( "StepSmoke", pNPCUnit:GetLandPosition_LUA(), D3DXVECTOR2(100,100), D3DXVECTOR2(5,-1) )
	end
	
	if pNPCUnit:AnimEventTimer_LUA( 0.6 ) then
		pMinorParticle = pX2Game:GetMinorParticle()
		pMinorParticle:CreateSequence_LUA( "StepSmoke", pNPCUnit:GetLandPosition_LUA(), D3DXVECTOR2(100,100), D3DXVECTOR2(5,-1) )
	end
	
	if pNPCUnit:AnimEventTimer_LUA( 0.8 ) then
		pMinorParticle = pX2Game:GetMinorParticle()
		pMinorParticle:CreateSequence_LUA( "StepSmoke", pNPCUnit:GetLandPosition_LUA(), D3DXVECTOR2(100,100), D3DXVECTOR2(5,-1) )
	end

end








function CSM_ARMADILLO_DYING_LAND_STATE_START( pKTDXApp, pX2Game, pNPCUnit )
	
	pos = pNPCUnit:GetPos()
	pos.y = pos.y + 100.0
	GetMinorParticle = pX2Game:GetMinorParticle()
	
	pSeq = GetMinorParticle:CreateSequence_LUA( "DieLight",		pos, D3DXVECTOR2(-1,-1), D3DXVECTOR2(3,-1) )
	if pSeq ~= nil then
	
		pSeq:SetLandPosition( pNPCUnit:GetLandPosition_LUA().y )
		pNPCUnit:SetDieSeq( pSeq:GetHandle() )
	
	end
	pNPCUnit:PlaySound_LUA( "DieLight.ogg" )
	
end


