-- lua header. UTF-8 인코딩 인식을 위해 이 줄은 지우지 마세요.



PRE_TIME = 0.0
CUR_TIME = 0.0

ELAPSED_TIME = 0.0
COOL_TIME = 0.0


INIT_SYSTEM = 
{
	UNIT_WIDTH		= 144.0,
	UNIT_HEIGHT		= 180.0,
	UNIT_LAYER		= X2_LAYER["XL_UNIT_0"],
	UNIT_SCALE      = 1.2,
}


INIT_DEVICE = 
{
	READY_TEXTURE = 
	{
	},
	
	READY_SOUND = 
	{
	
	 "GliterGreatBossVoice_AttackRoar1.ogg",
	 "GliterGreatBossVoice_AttackRoar2.ogg",
	 "GliterGreatBossVoice_CommandAttack.ogg",
	 "GliterGreatBossVoice_CommandDefense.ogg",
	 "GliterGreatBossVoice_DeathRoar1.ogg",
	 "GliterGreatBossVoice_HurtRoar1.ogg",
	 "GliterGreatBossVoice_StandUpAttackRoar1.ogg",
	 "GliterGreatBossVoice_StandUpAttackRoar2.ogg",
	 	 
	 
	 
	 "GlitterVoice_DeathRoar.ogg",
	 "GlitterVoice_HurtRoar1.ogg",
	 "GlitterVoice_HurtRoar2.ogg",
	 
     "Glitter_Hammer_AttackB.ogg",
     "Glitter_Hammer_Combo.ogg",
     "Glitter_Hammer_JumpAttack.ogg",
	 "Glitter_Landing.ogg",
	 
	 "Gliter_Commander_Attack.ogg",
	 "Gliter_Commander_AttackCombo1.ogg",
	 "Gliter_Commander_command.ogg",
	 
	
	},
}

INIT_MOTION = 
{
	MOTION_FILE_NAME		= "NUI_GLITER_COMMANDER.x",
}

INIT_PHYSIC = 
{
	RELOAD_ACCEL		= 2000,
	G_ACCEL				= 4000,
	MAX_G_SPEED			= -2000,
	
	WALK_SPEED			= 400,
	RUN_SPEED			= 600,
	JUMP_SPEED			= 1500,
	DASH_JUMP_SPEED		= 1800,
}


INIT_COMPONENT = 
{
	MP_CHANGE_RATE		= 1,
	MP_CHARGE_RATE		= 130,

	
	SHADOW_SIZE			= 200,
	SHADOW_FILE_NAME	= "shadow.dds",
	
	SMALL_HP_BAR_BLUE	= "Small_HP_bar_Blue.TGA",
	SMALL_HP_BAR_RED	= "Small_HP_bar_Red.TGA",
	SMALL_HP_BAR_YELLOW = "Small_HP_bar_Yellow.TGA",
	
	QUESTION_MARK_SEQ		= "QuestionMarkNPC",
	EXCLAMATION_MARK_SEQ	= "ExclamationMarkNPC",
	----MIND_FLAG_HEIGHT		= 230,
	
	HYPER_MODE_COUNT	= 0,
	MAX_HYPER_MODE_TIME	= 30,
	

	HITTED_TYPE			= HITTED_TYPE["HTD_MEAT"],
	FALL_DOWN			= TRUE,
	
	WEAPON0 = 
	{
		WEAPON_FILE_NAME			= "NUI_GLITER_COMMANDER_Weapon.X",
		WEAPON_BONE_NAME			= "Dummy1_Rhand",
	},
	
	SUMMON_TIME			= 180,
}

INIT_STATE = 
{
	{ STATE_NAME = "CSM_GLITER_COMMANDER_START",							},
	
	{ STATE_NAME = "CSM_GLITER_COMMANDER_WAIT",							},


	{ STATE_NAME = "CSM_GLITER_COMMANDER_WAIT_HABIT",						},
	
	{ STATE_NAME = "CSM_GLITER_COMMANDER_WALK",							LUA_STATE_END_FUNC = "CSM_GLITER_COMMANDER_WALK_STATE_END"							},

	
	{ STATE_NAME = "CSM_GLITER_COMMANDER_DASH",							LUA_FRAME_MOVE_FUNC = "CSM_GLITER_COMMANDER_DASH_FRAME_MOVE",	},
	{ STATE_NAME = "CSM_GLITER_COMMANDER_DASH_END",						LUA_FRAME_MOVE_FUNC = "CSM_GLITER_COMMANDER_DASH_END_FRAME_MOVE",	},
		

	{ STATE_NAME = "CSM_GLITER_COMMANDER_JUMP_UP",							},
	{ STATE_NAME = "CSM_GLITER_COMMANDER_JUMP_DOWN",						LUA_STATE_END_FUNC = "CSM_GLITER_COMMANDER_JUMP_DOWN_STATE_END"					},
	{ STATE_NAME = "CSM_GLITER_COMMANDER_JUMP_UP_DIR",						},
	{ STATE_NAME = "CSM_GLITER_COMMANDER_JUMP_DOWN_DIR",					LUA_STATE_END_FUNC = "CSM_GLITER_COMMANDER_JUMP_DOWN_DIR_STATE_END"				},
	{ STATE_NAME = "CSM_GLITER_COMMANDER_JUMP_LANDING",					},
	
	{ STATE_NAME = "CSM_GLITER_COMMANDER_ATTACK",							LUA_FRAME_MOVE_FUNC = "CSM_GLITER_COMMANDER_ATTACK_FRAME_MOVE",	STATE_COOL_TIME	= 2, },
	
	{ STATE_NAME = "CSM_GLITER_COMMANDER_COMBO",							LUA_FRAME_MOVE_FUNC = "CSM_GLITER_COMMANDER_COMBO_FRAME_MOVE", 	STATE_COOL_TIME	= 6, },
	
	{ STATE_NAME = "CSM_GLITER_COMMANDER_END",						},
	


	--리액션 관련
	{ STATE_NAME = "CSM_GLITER_COMMANDER_DAMAGE_FRONT",					LUA_FRAME_MOVE_FUNC = "CSM_GLITER_COMMANDER_DAMAGE_FRONT_FRAME_MOVE"				},
	{ STATE_NAME = "CSM_GLITER_COMMANDER_DAMAGE_BACK",						LUA_FRAME_MOVE_FUNC = "CSM_GLITER_COMMANDER_DAMAGE_BACK_FRAME_MOVE"				},
	{ STATE_NAME = "CSM_GLITER_COMMANDER_DAMAGE_DOWN_FRONT",				LUA_FRAME_MOVE_FUNC = "CSM_GLITER_COMMANDER_DAMAGE_DOWN_FRONT_FRAME_MOVE"			},
	{ STATE_NAME = "CSM_GLITER_COMMANDER_DAMAGE_DOWN_BACK",				LUA_FRAME_MOVE_FUNC = "CSM_GLITER_COMMANDER_DAMAGE_DOWN_BACK_FRAME_MOVE"			},
	{ STATE_NAME = "CSM_GLITER_COMMANDER_DAMAGE_FLY_FRONT",				},
	{ STATE_NAME = "CSM_GLITER_COMMANDER_DAMAGE_FLY_BACK",					},
	{ STATE_NAME = "CSM_GLITER_COMMANDER_DAMAGE_AIR",						},
	{ STATE_NAME = "CSM_GLITER_COMMANDER_DAMAGE_AIR_DOWN",					},
	{ STATE_NAME = "CSM_GLITER_COMMANDER_DAMAGE_AIR_UP",					},
	{ STATE_NAME = "CSM_GLITER_COMMANDER_DAMAGE_AIR_FALL",					},
	{ STATE_NAME = "CSM_GLITER_COMMANDER_DAMAGE_AIR_DOWN_LANDING",			LUA_FRAME_MOVE_FUNC = "CSM_GLITER_COMMANDER_DAMAGE_AIR_DOWN_LANDING_FRAME_MOVE"	},
	
	{ STATE_NAME = "CSM_GLITER_COMMANDER_STAND_UP_FRONT",					},
	{ STATE_NAME = "CSM_GLITER_COMMANDER_STAND_UP_BACK",					},
	
	
	{ STATE_NAME = "CSM_GLITER_COMMANDER_DYING_LAND_FRONT",				LUA_STATE_START_FUNC = "CSM_GLITER_COMMANDER_DYING_LAND_STATE_START",},
	{ STATE_NAME = "CSM_GLITER_COMMANDER_DYING_LAND_BACK",					LUA_STATE_START_FUNC = "CSM_GLITER_COMMANDER_DYING_LAND_STATE_START",},
	{ STATE_NAME = "CSM_GLITER_COMMANDER_DYING_SKY",						LUA_STATE_START_FUNC = "CSM_GLITER_COMMANDER_DYING_LAND_STATE_START",},
	
	
	
	START_STATE					= "CSM_GLITER_COMMANDER_START",
	WAIT_STATE					= "CSM_GLITER_COMMANDER_WAIT",
	SUMMON_END_STATE			= "CSM_GLITER_COMMANDER_END",
	
	
	
	SMALL_DAMAGE_LAND_FRONT		= "CSM_GLITER_COMMANDER_DAMAGE_FRONT",
	SMALL_DAMAGE_LAND_BACK		= "CSM_GLITER_COMMANDER_DAMAGE_BACK",
	BIG_DAMAGE_LAND_FRONT		= "CSM_GLITER_COMMANDER_DAMAGE_FRONT",
	BIG_DAMAGE_LAND_BACK		= "CSM_GLITER_COMMANDER_DAMAGE_BACK",
	DOWN_DAMAGE_LAND_FRONT		= "CSM_GLITER_COMMANDER_DAMAGE_DOWN_FRONT",
	DOWN_DAMAGE_LAND_BACK		= "CSM_GLITER_COMMANDER_DAMAGE_DOWN_BACK",
	FLY_DAMAGE_FRONT			= "CSM_GLITER_COMMANDER_DAMAGE_FLY_FRONT",
	FLY_DAMAGE_BACK				= "CSM_GLITER_COMMANDER_DAMAGE_FLY_BACK",
	SMALL_DAMAGE_AIR			= "CSM_GLITER_COMMANDER_DAMAGE_AIR",	
	BIG_DAMAGE_AIR				= "CSM_GLITER_COMMANDER_DAMAGE_AIR",
	DOWN_DAMAGE_AIR				= "CSM_GLITER_COMMANDER_DAMAGE_AIR_DOWN",
	DOWN_DAMAGE_AIR_LANDING				= "CSM_GLITER_COMMANDER_DAMAGE_AIR_DOWN_LANDING",
	UP_DAMAGE					= "CSM_GLITER_COMMANDER_DAMAGE_AIR_UP",
	
	DAMAGE_EXTRA_STATES         = {"CSM_GLITER_COMMANDER_DAMAGE_AIR_FALL","CSM_GLITER_COMMANDER_STAND_UP_FRONT","CSM_GLITER_COMMANDER_STAND_UP_BACK",
	"CSM_GLITER_COMMANDER_JUMP_DOWN","CSM_GLITER_COMMANDER_JUMP_LANDING",},	

	DYING_LAND_FRONT			= "CSM_GLITER_COMMANDER_DYING_LAND_FRONT",
	DYING_LAND_BACK				= "CSM_GLITER_COMMANDER_DYING_LAND_BACK",
	DYING_SKY					= "CSM_GLITER_COMMANDER_DYING_SKY",

	REVENGE_ATTACK				= "",	
}


INIT_AI = 
{
	ALLY = 
	{
		FAR_LOST_RANGE	= 1400,			-- 이 거리보다 멀어지면 유저 옆으로 텔레포트
		LOST_RANGE		= 1400,			-- 이 거리보다 멀어지면 유저 쪽으로 걸어감
	},

	TARGET =
	{
		TARGET_PRIORITY 			= TARGET_PRIORITY["TP_NEAR_FIRST"],
		TARGET_INTERVAL 			= 1,
		TARGET_NEAR_RANGE 			= 1000,
		TARGET_RANGE 				= 2000,
		TARGET_LOST_RANGE 			= 5000,
		TARGET_SUCCESS_RATE 		= 100,
		ATTACK_TARGET_RATE 			= 100,
		PRESERVE_LAST_TARGET_RATE 	= 20,
	},
	
	CHASE_MOVE = 
	{		
		MOVE_SPLIT_RANGE	= 600,
		DEST_GAP			= 300,	-- 목적지에서 이 거리 안에 있으면 도착했다고 판단한다
		MOVE_GAP			= 350,
		
		DIR_CHANGE_INTERVAL = 0.5,
		
		WALK_INTERVAL		= 1,
		NEAR_WALK_RATE		= 1,   --  70,
		FAR_WALK_RATE		= 1,   -- 30,
		
		JUMP_INTERVAL		= 5,
		UP_JUMP_RATE		= 40, -- 40,
		UP_DOWN_RATE		= 0,
		DOWN_JUMP_RATE		= 20,    --  20,
		DOWN_DOWN_RATE		= 0,
		
		LINE_END_RANGE		= 80,	-- cm
	},	
	
	PATROL_MOVE = 	
	{
		PATROL_BEGIN_RATE		= 1, --50,		
		PATROL_RANGE			= 200,
		PATROL_COOL_TIME		= 2,
	},
	
	ESCAPE_MOVE = 
	{		
		MOVE_SPLIT_RANGE	= 500,	-- cm
		ESCAPE_GAP		= 700,	-- 이 거리 보다 멀어지면 도망 성공
		
		WALK_INTERVAL		= 0.5,	-- 초
		NEAR_WALK_RATE		= 100,   --  10,
		FAR_WALK_RATE		= 100,   -- 10,
		
		JUMP_INTERVAL		= 10,
		UP_JUMP_RATE		= 0, -- 30,
		UP_DOWN_RATE		= 0,
		DOWN_JUMP_RATE		= 0,    --  30,
		DOWN_DOWN_RATE		= 0,
		
		LINE_END_RANGE		= 80,	-- cm
	},
}

INIT_SUB_AI = 
{
	TARGET = 
	{
		TARGET_PRIORITY 			= TARGET_PRIORITY["TP_LOW_HP_FIRST"],
		TARGET_INTERVAL				= 2,		-- 3sec
		TARGET_NEAR_RANGE			= 450,		-- 150 이 거리보다 가까우면 TARGET_SUCCESS_RATE에 관계없이 무조건 타게팅된다
		TARGET_RANGE				= 1800,		-- 800 cm
		TARGET_LOST_RANGE			= 2200,		-- 1200cm
		TARGET_SUCCESS_RATE			= 100,  --50,		-- %
		ATTACK_TARGET_RATE			= 100, -- 30,	 100-- 나를 공격한 유닛을 타게팅할 확률
		PRESERVE_LAST_TARGET_RATE	= 0, -- 30,		-- 이전에 타게팅된 유닛을 계속 타게팅할 확률
	},

	CHASE_MOVE = 
	{		
		MOVE_SPLIT_RANGE	= 600,
		DEST_GAP			= 500,	-- 목적지에서 이 거리 안에 있으면 도착했다고 판단한다
		MOVE_GAP			= 850,
		
		DIR_CHANGE_INTERVAL = 0.5,
		
		WALK_INTERVAL		= 3,
		NEAR_WALK_RATE		= 100,   --  70,
		FAR_WALK_RATE		= 100,   -- 30,
		
		JUMP_INTERVAL		= 5,
		UP_JUMP_RATE		= 0, -- 40,
		UP_DOWN_RATE		= 0,
		DOWN_JUMP_RATE		= 0,    --  20,
		DOWN_DOWN_RATE		= 0,
		
		LINE_END_RANGE		= 80,	-- cm
	},	
	
	PATROL_MOVE = 	
	{
		PATROL_BEGIN_RATE		= 100, --50,		
		PATROL_RANGE			= 200,
		PATROL_COOL_TIME		= 2,
	},
	
	ESCAPE_MOVE = 
	{		
		MOVE_SPLIT_RANGE	= 500,	-- cm
		ESCAPE_GAP		= 600,	-- 이 거리 보다 멀어지면 도망 성공
		
		WALK_INTERVAL		= 0.5,	-- 초
		NEAR_WALK_RATE		= 10,   --  10,
		FAR_WALK_RATE		= 10,   -- 10,
		
		JUMP_INTERVAL		= 10,
		UP_JUMP_RATE		= 0, -- 30,
		UP_DOWN_RATE		= 0,
		DOWN_JUMP_RATE		= 0,    --  30,
		DOWN_DOWN_RATE		= 0,
		
		LINE_END_RANGE		= 80,	-- cm
	},

	ESCAPE_CONDITION = 
	{
		RATE				= 100,
		ESCAPE_RANGE		= 400,		-- 이 범위 안에 들어오면 타격당하지 않아도 RATE에 지정된 확률로 도망
		myHP			= 100,
	}
	


}

CSM_GLITER_COMMANDER_START = 
{
	ANIM_NAME					= "Command_Start",
	PLAY_TYPE					= XSKIN_ANIM_PLAYTYPE["XAP_ONE_WAIT"],
	TRANSITION					= FALSE,
	
	CAN_PUSH_UNIT				= TRUE,
	CAN_PASS_UNIT				= FALSE,
	IMMADIATE_PACKET_SEND		= TRUE,	
		
	EVENT_PROCESS = 
	{		
		{ STATE_CHANGE_TYPE["SCT_CONDITION_TABLE"],		"CSM_GLITER_COMMANDER_WAIT",		"CT_GLITER_COMMANDER_WAIT"				},
	},
	
	CT_GLITER_COMMANDER_WAIT = 
	{
		STATE_TIME_OVER			= 2.8,
	},
}

CSM_GLITER_COMMANDER_WAIT = 
{
	ANIM_NAME					= "Wait",
	PLAY_TYPE					= XSKIN_ANIM_PLAYTYPE["XAP_LOOP"],
	TRANSITION					= FALSE,
	
	CAN_PUSH_UNIT				= TRUE,
	CAN_PASS_UNIT				= FALSE,	
	
	SPEED_X						= 0,
	SPEED_Y						= 0,
	
	PASSIVE_SPEED_X				= 0,
	
	IMMADIATE_PACKET_SEND		= TRUE,
	EVENT_INTERVAL_TIME0		= 1,
	
	EVENT_PROCESS = 
	{		
		{ STATE_CHANGE_TYPE["SCT_FOOT_ON_LINE_FALSE_DOWN"],	"CSM_GLITER_COMMANDER_JUMP_DOWN",					},
		

		--{ STATE_CHANGE_TYPE["SCT_CONDITION_FUNCTION"],      "CSM_GLITER_COMMANDER_CALL_SHIELD",            "CF_CSM_GLITER_COMMANDER_CALL_SHIELD"    },
		--{ STATE_CHANGE_TYPE["SCT_CONDITION_FUNCTION"],      "CSM_GLITER_COMMANDER_CALL_LANCE",            "CF_CSM_GLITER_COMMANDER_CALL_LANCE"    },	
		--{ STATE_CHANGE_TYPE["SCT_CONDITION_FUNCTION"],      "CSM_GLITER_COMMANDER_CALL_HAMMER",            "CF_CSM_GLITER_COMMANDER_CALL_HAMMER"    },
		--{ STATE_CHANGE_TYPE["SCT_CONDITION_FUNCTION"],      "CSM_GLITER_COMMANDER_CALL_ARCHER",            "CF_CSM_GLITER_COMMANDER_CALL_ARCHER"    },
		
	
		{ STATE_CHANGE_TYPE["SCT_AI_WALK"],					"CSM_GLITER_COMMANDER_WALK",						},
	
		{ STATE_CHANGE_TYPE["SCT_AI_JUMP"],					"CSM_GLITER_COMMANDER_JUMP_UP",					},
		{ STATE_CHANGE_TYPE["SCT_AI_JUMP_DIR"],				"CSM_GLITER_COMMANDER_JUMP_UP_DIR",				},
		{ STATE_CHANGE_TYPE["SCT_AI_DOWN"],					"CSM_GLITER_COMMANDER_JUMP_DOWN",					},
		{ STATE_CHANGE_TYPE["SCT_AI_DOWN_DIR"],				"CSM_GLITER_COMMANDER_JUMP_DOWN_DIR",				},

		{ STATE_CHANGE_TYPE["SCT_CONDITION_TABLE"],			"CSM_GLITER_COMMANDER_ATTACK",			"CT_CSM_GLITER_COMMANDER_ATTACK",	},
		

		{ STATE_CHANGE_TYPE["SCT_CONDITION_TABLE"],			"CSM_GLITER_COMMANDER_WAIT_HABIT",					"CT_CSM_GLITER_COMMANDER_WAIT_HABIT",		},
		


	},

	CT_CSM_GLITER_COMMANDER_ATTACK = 
	{
		IS_ANOTHER_TEAM				= TRUE,
		EVENT_INTERVAL_ID			= 0,
		DISTANCE_TO_TARGET_NEAR		= 350,
		RATE						= 70,
	},
	CT_CSM_GLITER_COMMANDER_DASH =
	{
		EVENT_INTERVAL_ID			= 0,
		DISTANCE_OVER_TARGET_NEAR	= 400,
		DISTANCE_TO_TARGET_NEAR		= 1800,
		RATE						= 60,
	},
	CT_CSM_GLITER_COMMANDER_WAIT_HABIT = 
	{
		ANIM_PLAY_COUNT				= 1,
		RATE						= 60,
		HAVE_TARGET					= 0,		-- false
	},
		
}


CSM_GLITER_COMMANDER_END = 
{
	ANIM_NAME					= "Wait",
	PLAY_TYPE					= XSKIN_ANIM_PLAYTYPE["XAP_ONE_WAIT"],
	TRANSITION					= TRUE,
	
	CAN_PUSH_UNIT				= FALSE,
	CAN_PASS_UNIT				= TRUE,	

    INVINCIBLE					= { 0, 100, }, 
    
	SPEED_X						= 0,
	SPEED_Y						= 0,
	
	RIGHT						= FALSE,
	
	DYING_END					= TRUE,	
	
	IMMADIATE_PACKET_SEND		= TRUE,	
}	



---------------------------------------------------------------------------------


CSM_GLITER_COMMANDER_WAIT_HABIT = 
{
	ANIM_NAME					= "WaitHabit",
	PLAY_TYPE					= XSKIN_ANIM_PLAYTYPE["XAP_ONE_WAIT"],
	TRANSITION					= TRUE,
	
	CAN_PUSH_UNIT				= TRUE,
	CAN_PASS_UNIT				= FALSE,
	IMMADIATE_PACKET_SEND		= TRUE,

	
	EVENT_PROCESS = 
	{		
		{ STATE_CHANGE_TYPE["SCT_FOOT_ON_LINE_FALSE_DOWN"],	"CSM_GLITER_COMMANDER_JUMP_DOWN",				},
		{ STATE_CHANGE_TYPE["SCT_MOTION_END"],				"CSM_GLITER_COMMANDER_WAIT",						},
	},
}


CSM_GLITER_COMMANDER_WALK = 
{
	ANIM_NAME					= "Walk",
	PLAY_TYPE					= XSKIN_ANIM_PLAYTYPE["XAP_LOOP"],
	TRANSITION					= TRUE,
	
	CAN_PUSH_UNIT				= TRUE,
	CAN_PASS_UNIT				= FALSE,
	
	PASSIVE_SPEED_X				= INIT_PHYSIC["WALK_SPEED"],
	
	ALLOW_DIR_CHANGE			= TRUE,
	IMMADIATE_PACKET_SEND		= TRUE,
	
	EVENT_INTERVAL_TIME0		= 2,
	EVENT_INTERVAL_TIME1		= 3,
	
	EVENT_PROCESS = 
	{		
		
		{ STATE_CHANGE_TYPE["SCT_FOOT_ON_LINE_FALSE_DOWN"],	"CSM_GLITER_COMMANDER_JUMP_DOWN_DIR",				},

		{ STATE_CHANGE_TYPE["SCT_CONDITION_TABLE"],			"CSM_GLITER_COMMANDER_ATTACK",			"CT_CSM_GLITER_COMMANDER_ATTACK",	},
				

		{ STATE_CHANGE_TYPE["SCT_AI_WAIT"],					"CSM_GLITER_COMMANDER_WAIT",						},
		{ STATE_CHANGE_TYPE["SCT_AI_DASH"],					"CSM_GLITER_COMMANDER_DASH",						},
		{ STATE_CHANGE_TYPE["SCT_AI_JUMP"],					"CSM_GLITER_COMMANDER_JUMP_UP",					},
		{ STATE_CHANGE_TYPE["SCT_AI_JUMP_DIR"],				"CSM_GLITER_COMMANDER_JUMP_UP_DIR",				},
		{ STATE_CHANGE_TYPE["SCT_AI_DOWN"],					"CSM_GLITER_COMMANDER_JUMP_DOWN",					},
		{ STATE_CHANGE_TYPE["SCT_AI_DOWN_DIR"],				"CSM_GLITER_COMMANDER_JUMP_DOWN_DIR",				},


	},

	
	CT_CSM_GLITER_COMMANDER_ATTACK = 
	{
		IS_ANOTHER_TEAM				= TRUE,
		EVENT_INTERVAL_ID			= 0,
		DISTANCE_TO_TARGET_NEAR		= 250,
		RATE						= 100,
	},


	

	
	
}


CSM_GLITER_COMMANDER_DASH = 
{
	ANIM_NAME					= "Dash",
	PLAY_TYPE					= XSKIN_ANIM_PLAYTYPE["XAP_LOOP"],
	TRANSITION					= TRUE,
	
	CAN_PUSH_UNIT				= FALSE,
	CAN_PASS_UNIT				= FALSE,
	
	PASSIVE_SPEED_X				= INIT_PHYSIC["RUN_SPEED"],
	
	ALLOW_DIR_CHANGE			= TRUE,
	IMMADIATE_PACKET_SEND		= TRUE,
	
	EVENT_INTERVAL_TIME0		= 0.3,
	
	EVENT_PROCESS = 
	{		
		{ STATE_CHANGE_TYPE["SCT_FOOT_ON_LINE_FALSE_DOWN"],	"CSM_GLITER_COMMANDER_JUMP_DOWN_DIR",			},
		{ STATE_CHANGE_TYPE["SCT_CONDITION_TABLE"],			"CSM_GLITER_COMMANDER_COMBO",						"CT_CSM_GLITER_COMMANDER_COMBO",			},
		

		{ STATE_CHANGE_TYPE["SCT_AI_WAIT"],					"CSM_GLITER_COMMANDER_DASH_END",				},
		{ STATE_CHANGE_TYPE["SCT_AI_WALK"],					"CSM_GLITER_COMMANDER_DASH_END",				},
		{ STATE_CHANGE_TYPE["SCT_AI_JUMP"],					"CSM_GLITER_COMMANDER_JUMP_UP",				},
		{ STATE_CHANGE_TYPE["SCT_AI_JUMP_DIR"],				"CSM_GLITER_COMMANDER_JUMP_UP_DIR",			},
		{ STATE_CHANGE_TYPE["SCT_AI_DOWN"],					"CSM_GLITER_COMMANDER_JUMP_DOWN",				},
		{ STATE_CHANGE_TYPE["SCT_AI_DOWN_DIR"],				"CSM_GLITER_COMMANDER_JUMP_DOWN_DIR",			},
	},
	
	

	CT_CSM_GLITER_COMMANDER_COMBO = 
	{
		IS_ANOTHER_TEAM				= TRUE,
		EVENT_INTERVAL_ID			= 0,
		DISTANCE_TO_TARGET_NEAR		= 600,
		RATE						= 100,
	},
	

}



CSM_GLITER_COMMANDER_DASH_END = 
{
	ANIM_NAME					= "DashEnd",
	PLAY_TYPE					= XSKIN_ANIM_PLAYTYPE["XAP_ONE_WAIT"],
	TRANSITION					= FALSE,
	
	CAN_PUSH_UNIT				= FALSE,
	CAN_PASS_UNIT				= FALSE,
	
	SPEED_X						= INIT_PHYSIC["RUN_SPEED"],
	
	ALLOW_DIR_CHANGE			= FALSE,
	IMMADIATE_PACKET_SEND		= TRUE,
	
	EVENT_PROCESS = 
	{		
		--{ STATE_CHANGE_TYPE["SCT_CONDITION_TABLE"],			"CSM_GLITER_COMMANDER_COMBO",						"CT_CSM_GLITER_COMMANDER_COMBO",			},
		
		{ STATE_CHANGE_TYPE["SCT_FOOT_ON_LINE_FALSE_DOWN"],	"CSM_GLITER_COMMANDER_JUMP_DOWN_DIR",				},
		{ STATE_CHANGE_TYPE["SCT_MOTION_END"],				"CSM_GLITER_COMMANDER_WAIT",						},
	},
	
--[[
	CT_CSM_GLITER_COMMANDER_COMBO = 
	{
		DISTANCE_TO_TARGET_NEAR		= 400,
		RATE						= 30,
	},
--]]
}




CSM_GLITER_COMMANDER_JUMP_UP = 
{
	ANIM_NAME					= "JumpUp",
	PLAY_TYPE					= XSKIN_ANIM_PLAYTYPE["XAP_LOOP"],
	TRANSITION					= TRUE,
	LAND_CONNECT				= FALSE,
	
	CAN_PUSH_UNIT				= TRUE,
	CAN_PASS_UNIT				= FALSE,
	
	SPEED_X						= 0,
	SPEED_Y						= INIT_PHYSIC["JUMP_SPEED"],
	
	ADD_POS_Y					= 45, 
	
	IMMADIATE_PACKET_SEND		= TRUE,
	
	EVENT_PROCESS = 
	{		
		{ STATE_CHANGE_TYPE["SCT_NEGATIVE_Y_SPEED"],		"CSM_GLITER_COMMANDER_JUMP_DOWN",			},
	},
	
}

CSM_GLITER_COMMANDER_JUMP_DOWN = 
{
	ANIM_NAME					= "JumpDown",
	PLAY_TYPE					= XSKIN_ANIM_PLAYTYPE["XAP_LOOP"],
	TRANSITION					= TRUE,
	LAND_CONNECT				= FALSE,
	
	CAN_PUSH_UNIT				= TRUE,
	CAN_PASS_UNIT				= FALSE,
		 
	
	IMMADIATE_PACKET_SEND		= TRUE,
		
	EVENT_PROCESS = 
	{		
		{ STATE_CHANGE_TYPE["SCT_FOOT_ON_LINE_TRUE"],		"CSM_GLITER_COMMANDER_JUMP_LANDING",				},
	},
}

CSM_GLITER_COMMANDER_JUMP_UP_DIR = 
{
	ANIM_NAME					= "JumpUp",
	PLAY_TYPE					= XSKIN_ANIM_PLAYTYPE["XAP_LOOP"],
	TRANSITION					= TRUE,
	LAND_CONNECT				= FALSE,
	
	CAN_PUSH_UNIT				= TRUE,
	CAN_PASS_UNIT				= FALSE,
		
	PASSIVE_SPEED_X				= INIT_PHYSIC["WALK_SPEED"],
	SPEED_Y						= INIT_PHYSIC["JUMP_SPEED"],
	
	ADD_POS_Y					= 45, 
	
	IMMADIATE_PACKET_SEND		= TRUE,
	
	EVENT_PROCESS = 
	{		
		{ STATE_CHANGE_TYPE["SCT_NEGATIVE_Y_SPEED"],		"CSM_GLITER_COMMANDER_JUMP_DOWN_DIR",				},
	},
	
}

CSM_GLITER_COMMANDER_JUMP_DOWN_DIR = 
{
	ANIM_NAME					= "JumpDown",
	PLAY_TYPE					= XSKIN_ANIM_PLAYTYPE["XAP_LOOP"],
	TRANSITION					= TRUE,
	LAND_CONNECT				= FALSE,
	
	CAN_PUSH_UNIT				= TRUE,
	CAN_PASS_UNIT				= FALSE,
	
	PASSIVE_SPEED_X				= INIT_PHYSIC["WALK_SPEED"],
	 
	
	IMMADIATE_PACKET_SEND		= TRUE,
		
	EVENT_PROCESS = 
	{		
		{ STATE_CHANGE_TYPE["SCT_FOOT_ON_LINE_TRUE"],		"CSM_GLITER_COMMANDER_JUMP_LANDING",				},
	},
}

CSM_GLITER_COMMANDER_JUMP_LANDING = 
{
	ANIM_NAME					= "JumpDownLanding",
	PLAY_TYPE					= XSKIN_ANIM_PLAYTYPE["XAP_ONE_WAIT"],
	TRANSITION					= TRUE,
	LAND_CONNECT				= FALSE,
	
	CAN_PUSH_UNIT				= TRUE,
	CAN_PASS_UNIT				= FALSE,
	
    SOUND_PLAY0			= { 0.091, "Glitter_Landing.ogg" },

	SPEED_X						= 0,
	SPEED_Y						= 0,

	IMMADIATE_PACKET_SEND		= TRUE,

	EVENT_PROCESS = 
	{		
		{ STATE_CHANGE_TYPE["SCT_FOOT_ON_LINE_FALSE_DOWN"],	"CSM_GLITER_COMMANDER_JUMP_DOWN",				},
		{ STATE_CHANGE_TYPE["SCT_MOTION_END"],				"CSM_GLITER_COMMANDER_WAIT",						},
	},
}


CSM_GLITER_COMMANDER_ATTACK = 
{
	ANIM_NAME					= "Attack",
	PLAY_TYPE					= XSKIN_ANIM_PLAYTYPE["XAP_ONE_WAIT"],
	TRANSITION					= FALSE,
	
	CAN_PUSH_UNIT				= TRUE,
	CAN_PASS_UNIT				= FALSE,

	SPEED_X						= 0,
	SPEED_Y						= 0,	

    SOUND_PLAY0			= { 0.334, "GliterGreatBossVoice_AttackRoar2.ogg" },
    SOUND_PLAY1			= { 0.287, "Gliter_Commander_Attack.ogg" },

	
	VIEW_TARGET					= TRUE,
	ALLOW_DIR_CHANGE			= FALSE,	
	IMMADIATE_PACKET_SEND		= TRUE,
	
	EVENT_PROCESS = 
	{	
		{ STATE_CHANGE_TYPE["SCT_FOOT_ON_LINE_FALSE_DOWN"],	"CSM_GLITER_COMMANDER_JUMP_DOWN",								},
		{ STATE_CHANGE_TYPE["SCT_CONDITION_TABLE"],			"CSM_GLITER_COMMANDER_COMBO",		"CT_CSM_GLITER_COMMANDER_COMBO",		},
		{ STATE_CHANGE_TYPE["SCT_MOTION_END"],				"CSM_GLITER_COMMANDER_WAIT",							},	
	},
	
	ATTACK_TIME0				= { 0.32, 0.4, },
	
	CT_CSM_GLITER_COMMANDER_COMBO = 
	{
		IS_ANOTHER_TEAM				= TRUE,
		ANIM_EVENT_TIMER			= 0.6,
		ATTACK_SUCCESS				= TRUE,
		RATE					= 100,
	},

	DAMAGE_DATA = 
	{
		DAMAGE_TYPE		= DAMAGE_TYPE["DT_PHYSIC"],
		HIT_TYPE		= HIT_TYPE["HT_SWORD_SLASH"],
		REACT_TYPE		= REACT_TYPE["RT_BIG_DAMAGE"],
		
		DAMAGE = 
		{
			PHYSIC		= 1.5,
		},
		
		BACK_SPEED_X			= 0,
		BACK_SPEED_Y			= 0,
		
		CAMERA_CRASH_GAP		= 10.0,	
		CAMERA_CRASH_TIME		= 0.3,		
	},

}



CSM_GLITER_COMMANDER_COMBO = 
{
	ANIM_NAME					= "AttackCombo1",
	PLAY_TYPE					= XSKIN_ANIM_PLAYTYPE["XAP_ONE_WAIT"],
	TRANSITION					= FALSE,
	
	CAN_PUSH_UNIT				= TRUE,
	CAN_PASS_UNIT				= FALSE,

	SPEED_X						= 0,
	SPEED_Y						= 0,	

    SOUND_PLAY0			        = { 0.196, "Gliter_Commander_AttackCombo1.ogg" },
	SOUND_PLAY1			        = { 0.623, "GliterGreatBossVoice_AttackRoar1.ogg" },
	
	VIEW_TARGET					= TRUE,
	ALLOW_DIR_CHANGE			= FALSE,	
	IMMADIATE_PACKET_SEND		= TRUE,
	
	EVENT_PROCESS = 
	{	
		{ STATE_CHANGE_TYPE["SCT_FOOT_ON_LINE_FALSE_DOWN"],	"CSM_GLITER_COMMANDER_JUMP_DOWN",								},
		{ STATE_CHANGE_TYPE["SCT_MOTION_END"],				"CSM_GLITER_COMMANDER_WAIT",									},	
	},
	
	ATTACK_TIME0				= { 0.28, 0.36, },
	
	DAMAGE_DATA = 
	{
		DAMAGE_TYPE		= DAMAGE_TYPE["DT_PHYSIC"],
		HIT_TYPE		= HIT_TYPE["HT_SWORD_SLASH"],
		REACT_TYPE		= REACT_TYPE["RT_BIG_DAMAGE"],
		
		DAMAGE = 
		{
			PHYSIC		= 3.0,
		},
		
		BACK_SPEED_X			= 1000,
		BACK_SPEED_Y			= 200,
		
		CAMERA_CRASH_GAP		= 10.0,	
		CAMERA_CRASH_TIME		= 0.3,		
	},

}



CSM_GLITER_COMMANDER_DAMAGE_FRONT = 
{
	ANIM_NAME					= "DamageFront",
	PLAY_TYPE					= XSKIN_ANIM_PLAYTYPE["XAP_ONE_WAIT"],
	TRANSITION					= FALSE,
	LAND_CONNECT				= FALSE,
	
	CAN_PUSH_UNIT				= TRUE,
	CAN_PASS_UNIT				= FALSE,
	
	EVENT_PROCESS = 
	{
		{ STATE_CHANGE_TYPE["SCT_MOTION_END"],					"CSM_GLITER_COMMANDER_WAIT",												},
	},
}

CSM_GLITER_COMMANDER_DAMAGE_BACK = 
{
	ANIM_NAME					= "DamageBack",
	PLAY_TYPE					= XSKIN_ANIM_PLAYTYPE["XAP_ONE_WAIT"],
	TRANSITION					= FALSE,
	LAND_CONNECT				= FALSE,
	
	CAN_PUSH_UNIT				= TRUE,
	CAN_PASS_UNIT				= FALSE,

    SOUND_PLAY0		           	= { 0.174, "GliterGreatBossVoice_HurtRoar1.ogg" , 24 },
	
	EVENT_PROCESS = 
	{
		{ STATE_CHANGE_TYPE["SCT_MOTION_END"],					"CSM_GLITER_COMMANDER_WAIT",												},
	},
}





CSM_GLITER_COMMANDER_DAMAGE_DOWN_FRONT = 
{
	ANIM_NAME					= "DamageDownFront",
	PLAY_TYPE					= XSKIN_ANIM_PLAYTYPE["XAP_ONE_WAIT"],
	TRANSITION					= FALSE,
	LAND_CONNECT				= FALSE,

	SUPER_ARMOR					= TRUE,
	DEFENCE						= { 0, 100, 70, },

    SOUND_PLAY0			        = { 0.275, "GliterGreatBossVoice_HurtRoar1.ogg" , 24 },
	
	CAN_PUSH_UNIT				= TRUE,
	CAN_PASS_UNIT				= FALSE,

	
	EVENT_PROCESS = 
	{
		{ STATE_CHANGE_TYPE["SCT_FOOT_ON_LINE_FALSE_DOWN"],		"CSM_GLITER_COMMANDER_DAMAGE_AIR_FALL",			},
		{ STATE_CHANGE_TYPE["SCT_MOTION_END"],					"CSM_GLITER_COMMANDER_STAND_UP_FRONT",			},
	},
	
}

CSM_GLITER_COMMANDER_DAMAGE_DOWN_BACK = 
{
	ANIM_NAME					= "DamageDownBack",
	PLAY_TYPE					= XSKIN_ANIM_PLAYTYPE["XAP_ONE_WAIT"],
	TRANSITION					= FALSE,
	LAND_CONNECT				= FALSE,
	
	SUPER_ARMOR					= TRUE,
	DEFENCE						= { 0, 100, 70, },

    SOUND_PLAY0		            = { 0.174, "GliterGreatBossVoice_HurtRoar1.ogg" , 24 },
	
	CAN_PUSH_UNIT				= TRUE,
	CAN_PASS_UNIT				= FALSE,
	
	EVENT_PROCESS = 
	{
		{ STATE_CHANGE_TYPE["SCT_FOOT_ON_LINE_FALSE_DOWN"],		"CSM_GLITER_COMMANDER_DAMAGE_AIR_FALL",			},
		{ STATE_CHANGE_TYPE["SCT_MOTION_END"],					"CSM_GLITER_COMMANDER_STAND_UP_BACK",			},
	},
	
}

CSM_GLITER_COMMANDER_DAMAGE_FLY_FRONT = 
{
	ANIM_NAME					= "DamageAirFlyFront",
	PLAY_TYPE					= XSKIN_ANIM_PLAYTYPE["XAP_ONE_WAIT"],
	TRANSITION					= TRUE,
	LAND_CONNECT				= FALSE,	
	
	
	
	CAN_PUSH_UNIT				= TRUE,
	CAN_PASS_UNIT				= FALSE,
	
	EVENT_PROCESS = 
	{
		{ STATE_CHANGE_TYPE["SCT_FOOT_ON_LINE_TRUE"],			"CSM_GLITER_COMMANDER_DAMAGE_AIR_DOWN_LANDING",		},
	},
}

CSM_GLITER_COMMANDER_DAMAGE_FLY_BACK = 
{
	ANIM_NAME					= "DamageAirFlyBack",
	PLAY_TYPE					= XSKIN_ANIM_PLAYTYPE["XAP_ONE_WAIT"],
	TRANSITION					= FALSE,
	LAND_CONNECT				= FALSE,	
	
	CAN_PUSH_UNIT				= TRUE,
	CAN_PASS_UNIT				= FALSE,
	
	EVENT_PROCESS = 
	{
		{ STATE_CHANGE_TYPE["SCT_FOOT_ON_LINE_TRUE"],			"CSM_GLITER_COMMANDER_DAMAGE_DOWN_BACK",		},
	},
}

CSM_GLITER_COMMANDER_DAMAGE_AIR = 
{
	ANIM_NAME					= "DamageAirSmall",
	PLAY_TYPE					= XSKIN_ANIM_PLAYTYPE["XAP_ONE_WAIT"],
	TRANSITION					= FALSE,
	LAND_CONNECT				= FALSE,
	
	CAN_PUSH_UNIT				= TRUE,
	CAN_PASS_UNIT				= FALSE,
	
	EVENT_PROCESS = 
	{
		{ STATE_CHANGE_TYPE["SCT_FOOT_ON_LINE_TRUE"],			"CSM_GLITER_COMMANDER_WAIT",					},
	},
	
	VIEW_TARGET					= TRUE,
	ALLOW_DIR_CHANGE			= TRUE,
}

CSM_GLITER_COMMANDER_DAMAGE_AIR_DOWN = 
{
	ANIM_NAME					= "DamageAirDown",
	PLAY_TYPE					= XSKIN_ANIM_PLAYTYPE["XAP_ONE_WAIT"],
	TRANSITION					= FALSE,
	LAND_CONNECT				= FALSE,
	
	CAN_PUSH_UNIT				= TRUE,
	CAN_PASS_UNIT				= FALSE,
	
	EVENT_PROCESS = 
	{
		{ STATE_CHANGE_TYPE["SCT_FOOT_ON_LINE_TRUE"],			"CSM_GLITER_COMMANDER_DAMAGE_AIR_DOWN_LANDING",	},
	},
}

CSM_GLITER_COMMANDER_DAMAGE_AIR_UP = 
{
	ANIM_NAME					= "DamageAirUp",
	PLAY_TYPE					= XSKIN_ANIM_PLAYTYPE["XAP_ONE_WAIT"],
	TRANSITION					= FALSE,
	LAND_CONNECT				= FALSE,
	
	CAN_PUSH_UNIT				= TRUE,
	CAN_PASS_UNIT				= FALSE,
	
		
	EVENT_PROCESS = 
	{
		{ STATE_CHANGE_TYPE["SCT_NEGATIVE_Y_SPEED"],		"CSM_GLITER_COMMANDER_DAMAGE_AIR_FALL",			},
		{ STATE_CHANGE_TYPE["SCT_FOOT_ON_LINE_TRUE"],		"CSM_GLITER_COMMANDER_DAMAGE_AIR_DOWN_LANDING",	},
	},
}

CSM_GLITER_COMMANDER_DAMAGE_AIR_FALL = 
{
	ANIM_NAME					= "DamageAirFall",
	PLAY_TYPE					= XSKIN_ANIM_PLAYTYPE["XAP_ONE_WAIT"],
	TRANSITION					= FALSE,
	LAND_CONNECT				= FALSE,
	
	CAN_PUSH_UNIT				= TRUE,
	CAN_PASS_UNIT				= FALSE,
	
	EVENT_PROCESS = 
	{
		{ STATE_CHANGE_TYPE["SCT_POSITIVE_Y_SPEED"],		"CSM_GLITER_COMMANDER_DAMAGE_AIR_UP",			},
		{ STATE_CHANGE_TYPE["SCT_FOOT_ON_LINE_TRUE"],		"CSM_GLITER_COMMANDER_DAMAGE_AIR_DOWN_LANDING",	},
	},
}

CSM_GLITER_COMMANDER_DAMAGE_AIR_DOWN_LANDING = 
{
	ANIM_NAME					= "DamageAirDownLanding",
	PLAY_TYPE					= XSKIN_ANIM_PLAYTYPE["XAP_ONE_WAIT"],
	TRANSITION					= FALSE,
	LAND_CONNECT				= FALSE,
	
	SUPER_ARMOR					= TRUE,
	DEFENCE						= { 0, 100, 70, },

    SOUND_PLAY0			        = { 0.103, "GliterGreatBossVoice_HurtRoar1.ogg", 24 },
	 
	CAN_PUSH_UNIT				= TRUE,
	CAN_PASS_UNIT				= FALSE,
	
	EVENT_PROCESS = 
	{
		{ STATE_CHANGE_TYPE["SCT_FOOT_ON_LINE_FALSE_DOWN"],	"CSM_GLITER_COMMANDER_DAMAGE_AIR_FALL",			},
		{ STATE_CHANGE_TYPE["SCT_MOTION_END"],				"CSM_GLITER_COMMANDER_STAND_UP_FRONT",			},
	},
	
}

CSM_GLITER_COMMANDER_STAND_UP_FRONT = 
{
	ANIM_NAME					= "DamageStandUpFront",
	PLAY_TYPE					= XSKIN_ANIM_PLAYTYPE["XAP_ONE_WAIT"],
	TRANSITION					= FALSE,
	LAND_CONNECT				= FALSE,	
	
	SUPER_ARMOR					= TRUE,
	DEFENCE						= { 0, 100, 70, },
	
	CAN_PUSH_UNIT				= TRUE,
	CAN_PASS_UNIT				= FALSE,
	
	EVENT_PROCESS = 
	{
		{ STATE_CHANGE_TYPE["SCT_FOOT_ON_LINE_FALSE_DOWN"],	"CSM_GLITER_COMMANDER_JUMP_DOWN",			},
		{ STATE_CHANGE_TYPE["SCT_MOTION_END"],				"CSM_GLITER_COMMANDER_WAIT",				},
	},
}

CSM_GLITER_COMMANDER_STAND_UP_BACK = 
{
	ANIM_NAME					= "DamageStandUpBack",
	PLAY_TYPE					= XSKIN_ANIM_PLAYTYPE["XAP_ONE_WAIT"],
	TRANSITION					= FALSE,
	LAND_CONNECT				= FALSE,
	
	SUPER_ARMOR					= TRUE,
	DEFENCE						= { 0, 100, 70, },
		
	CAN_PUSH_UNIT				= TRUE,
	CAN_PASS_UNIT				= FALSE,
		
	EVENT_PROCESS = 
	{
		{ STATE_CHANGE_TYPE["SCT_FOOT_ON_LINE_FALSE_DOWN"],	"CSM_GLITER_COMMANDER_JUMP_DOWN", },
		{ STATE_CHANGE_TYPE["SCT_MOTION_END"],				"CSM_GLITER_COMMANDER_WAIT", },
	},		
}



CSM_GLITER_COMMANDER_DYING_LAND_FRONT = 
{
	ANIM_NAME					= "DamageDownFront",
	PLAY_TYPE					= XSKIN_ANIM_PLAYTYPE["XAP_ONE_WAIT"],
	TRANSITION					= FALSE,
	LAND_CONNECT				= FALSE,

	INVINCIBLE					= { 0, 100, }, 		

    SOUND_PLAY0			        = { 0.196, "GliterGreatBossVoice_DeathRoar1.ogg" },
	
	CAN_PUSH_UNIT				= FALSE,
	CAN_PASS_UNIT				= TRUE,
	
	DYING_END					= TRUE,
	
	IMMADIATE_PACKET_SEND		= TRUE,
}
	
CSM_GLITER_COMMANDER_DYING_LAND_BACK = 
{
	ANIM_NAME					= "DamageDownBack",
	PLAY_TYPE					= XSKIN_ANIM_PLAYTYPE["XAP_ONE_WAIT"],
	TRANSITION					= FALSE,
	LAND_CONNECT				= FALSE,
	
	INVINCIBLE					= { 0, 100, }, 		

    SOUND_PLAY0		        	= { 0.250, "GliterGreatBossVoice_DeathRoar1.ogg" },
	
	CAN_PUSH_UNIT				= FALSE,
	CAN_PASS_UNIT				= TRUE,
	
	DYING_END					= TRUE,	
	
	IMMADIATE_PACKET_SEND		= TRUE,
}

CSM_GLITER_COMMANDER_DYING_SKY = 
{
	ANIM_NAME					= "DamageAirDownLanding",
	PLAY_TYPE					= XSKIN_ANIM_PLAYTYPE["XAP_ONE_WAIT"],
	TRANSITION					= FALSE,
	LAND_CONNECT				= FALSE,
	
	INVINCIBLE					= { 0, 100, }, 		
	
	CAN_PUSH_UNIT				= FALSE,
	CAN_PASS_UNIT				= TRUE,

    SOUND_PLAY0		        	= { 0.103, "GliterGreatBossVoice_DeathRoar1.ogg" },
	
	DYING_END					= TRUE,
	
	IMMADIATE_PACKET_SEND		= TRUE,
}









--------------------------------------------------------------------
--------------------------------------------------------------------

function CSM_GLITER_COMMANDER_WALK_STATE_END( pKTDXApp, pX2Game, pNPCUnit )

	pMinorParticle = pX2Game:GetMinorParticle()
	pMinorParticle:CreateSequence_LUA( "StepSmoke", pNPCUnit:GetLandPosition_LUA(), D3DXVECTOR2(100,100), D3DXVECTOR2(5,-1) )

end



function CSM_GLITER_COMMANDER_DASH_FRAME_MOVE( pKTDXApp, pX2Game, pNPCUnit )
	if pNPCUnit:AnimEventTimer_LUA( 0.33 ) then
		pMinorParticle = pX2Game:GetMinorParticle()
		pMinorParticle:CreateSequence_LUA( "StepSmoke", pNPCUnit:GetLandPosition_LUA(), D3DXVECTOR2(100,100), D3DXVECTOR2(5,-1) )
	elseif pNPCUnit:AnimEventTimer_LUA( 0.70 ) then
		pMinorParticle = pX2Game:GetMinorParticle()
		pMinorParticle:CreateSequence_LUA( "StepSmoke", pNPCUnit:GetLandPosition_LUA(), D3DXVECTOR2(100,100), D3DXVECTOR2(5,-1) )
	end
end

function CSM_GLITER_COMMANDER_DASH_END_FRAME_MOVE( pKTDXApp, pX2Game, pNPCUnit )
	if pNPCUnit:AnimEventTimer_LUA( 0.30 ) then
		pMinorParticle = pX2Game:GetMinorParticle()
		pMinorParticle:CreateSequence_LUA( "StepSmoke", pNPCUnit:GetLandPosition_LUA(), D3DXVECTOR2(100,100), D3DXVECTOR2(7,-1) )
	end
end



function CSM_GLITER_COMMANDER_JUMP_DOWN_STATE_END( pKTDXApp, pX2Game, pNPCUnit )

	pMinorParticle = pX2Game:GetMinorParticle()
	pMinorParticle:CreateSequence_LUA( "StepSmoke", pNPCUnit:GetLandPosition_LUA(), D3DXVECTOR2(100,100), D3DXVECTOR2(5,-1) )

end

function CSM_GLITER_COMMANDER_JUMP_DOWN_DIR_STATE_END( pKTDXApp, pX2Game, pNPCUnit )

	pMinorParticle = pX2Game:GetMinorParticle()
	pMinorParticle:CreateSequence_LUA( "StepSmoke", pNPCUnit:GetLandPosition_LUA(), D3DXVECTOR2(100,100), D3DXVECTOR2(5,-1) )

end



function CSM_GLITER_COMMANDER_ATTACK_FRAME_MOVE( pKTDXApp, pX2Game, pNPCUnit )
	


end


----------------------------------------------------------------------------------
function CSM_GLITER_COMMANDER_COMBO_FRAME_MOVE( pKTDXApp, pX2Game, pNPCUnit )

    if pNPCUnit:AnimEventTimer_LUA( 0.94 ) then
      	
    end

end




function CSM_GLITER_COMMANDER_DAMAGE_FRONT_FRAME_MOVE( pKTDXApp, pX2Game, pNPCUnit )

	if pNPCUnit:AnimEventTimer_LUA( 0.047 ) then
		pMinorParticle = pX2Game:GetMinorParticle()
		pMinorParticle:CreateSequence_LUA( "StepSmoke", pNPCUnit:GetLandPosition_LUA(), D3DXVECTOR2(100,100), D3DXVECTOR2(5,-1) )
	end

end

function CSM_GLITER_COMMANDER_DAMAGE_BACK_FRAME_MOVE( pKTDXApp, pX2Game, pNPCUnit )

	if pNPCUnit:AnimEventTimer_LUA( 0.06 ) then
		pMinorParticle = pX2Game:GetMinorParticle()
		pMinorParticle:CreateSequence_LUA( "StepSmoke", pNPCUnit:GetLandPosition_LUA(), D3DXVECTOR2(100,100), D3DXVECTOR2(5,-1) )
	end

end

function CSM_GLITER_COMMANDER_DAMAGE_DOWN_FRONT_FRAME_MOVE( pKTDXApp, pX2Game, pNPCUnit )

	if pNPCUnit:AnimEventTimer_LUA( 0.41 ) then
		pNPCUnit:PlaySound_LUA( "Down.ogg" )		
		pMinorParticle = pX2Game:GetMinorParticle()
		pMinorParticle:CreateSequence_LUA( "DownSmoke", pNPCUnit:GetLandPosition_LUA(), D3DXVECTOR2(100,100), D3DXVECTOR2(7,-1) )
	end

end

function CSM_GLITER_COMMANDER_DAMAGE_DOWN_BACK_FRAME_MOVE( pKTDXApp, pX2Game, pNPCUnit )

	if pNPCUnit:AnimEventTimer_LUA( 0.45 ) then
		pNPCUnit:PlaySound_LUA( "Down.ogg" )		
		pMinorParticle = pX2Game:GetMinorParticle()
		pMinorParticle:CreateSequence_LUA( "DownSmoke", pNPCUnit:GetLandPosition_LUA(), D3DXVECTOR2(100,100), D3DXVECTOR2(7,-1) )
	end

end

function CSM_GLITER_COMMANDER_DAMAGE_AIR_DOWN_LANDING_FRAME_MOVE( pKTDXApp, pX2Game, pNPCUnit )

	if pNPCUnit:AnimEventTimer_LUA( 0.01 ) then
		
		pMinorParticle = pX2Game:GetMinorParticle()
		pos = pNPCUnit:GetLandPosition_LUA()
		pMinorParticle:CreateSequence_LUA( "DownSmoke", pos, D3DXVECTOR2(100,100), D3DXVECTOR2(7,-1) )
		pos.y = pos.y + 5
		pMinorParticle:CreateSequence_LUA( "GroundShockWave", pos, D3DXVECTOR2(100,100), D3DXVECTOR2(1,-1) )
		pParticle = pMinorParticle:CreateSequence_LUA( "AirDownTick", pNPCUnit:GetPos(), D3DXVECTOR2(200,200), D3DXVECTOR2(10,-1) )
		if pParticle ~= nil then 
			pParticle:SetLandPosition( pos.y - 5 )
		end
		
		if GetDistance_LUA( pNPCUnit:GetPos(), pX2Game:GetFocusUnitPos_LUA() ) < 500 then
			pX2Game:GetX2Camera():GetCamera():UpDownCrashCameraNoReset( 10.0, 0.1 )
		end		
		
	elseif pNPCUnit:AnimEventTimer_LUA( 0.1 ) then
		
		pNPCUnit:PlaySound_LUA( "Down.ogg" )		
		pMinorParticle = pX2Game:GetMinorParticle()
		pMinorParticle:CreateSequence_LUA( "DownSmoke", pNPCUnit:GetLandPosition_LUA(), D3DXVECTOR2(100,100), D3DXVECTOR2(7,-1) )
		
	end

end







function CSM_GLITER_COMMANDER_DYING_LAND_STATE_START( pKTDXApp, pX2Game, pNPCUnit )

	pos = pNPCUnit:GetPos()
	pos.y = pos.y + 100.0
	GetMinorParticle = pX2Game:GetMinorParticle()
	
	pSeq = GetMinorParticle:CreateSequence_LUA( "DieLight",		pos, D3DXVECTOR2(-1,-1), D3DXVECTOR2(3,-1) )
	if pSeq ~= nil then
	
		pSeq:SetLandPosition( pNPCUnit:GetLandPosition_LUA().y )
		pNPCUnit:SetDieSeq( pSeq:GetHandle() )
	
	end
	pNPCUnit:PlaySound_LUA( "DieLight.ogg" )
	
end


















