-- lua header. UTF-8 인코딩 인식을 위해 이 줄은 지우지 마세요.



INIT_SYSTEM = 
{
	UNIT_LAYER		= X2_LAYER["XL_UNIT_0"],
	UNIT_SCALE      = 1,
}

INIT_DEVICE = 
{
	READY_TEXTURE = 
	{
	},
	
	READY_SOUND = 
	{
	},
		
	READY_XMESH = 
	{
	},
	
	READY_XSKIN_MESH = 
	{
	},
}

INIT_MOTION = 
{
	MOTION_FILE_NAME = "Motion_Dry_Sander_Event_NPC_Anudran.x",	
}

INIT_PHYSIC = 
{
	RELOAD_ACCEL		= 2000,
	G_ACCEL				= 4000,
	MAX_G_SPEED			= -2000,
	
	WALK_SPEED			= 350,
	RUN_SPEED			= 450,
	JUMP_SPEED			= 1500,
	DASH_JUMP_SPEED		= 1500,
}

INIT_COMPONENT =
{
	MAX_HP              = 30000,
	MP_CHANGE_RATE		= 1,
	MP_CHARGE_RATE		= 130,
	
	USE_SLASH_TRACE		= FALSE,
	
	HYPER_MODE_COUNT	= 0,
	MAX_HYPER_MODE_TIME	= 30,
	
	HITTED_TYPE			= HITTED_TYPE["HTD_STONE"],
	
	FALL_DOWN			= TRUE,

	NOT_CULL  = TRUE,
}

INIT_STATE =
{
	{ STATE_NAME = "DRY_SANDER_EVENT_NPC_ANUDRAN_START",	LUA_STATE_START_FUNC = "DRY_SANDER_EVENT_NPC_ANUDRAN_START_START",	},	
	
	{ STATE_NAME = "DRY_SANDER_EVENT_NPC_ANUDRAN_DYING",	},	
	
	START_STATE					= "DRY_SANDER_EVENT_NPC_ANUDRAN_START",
	WAIT_STATE					= "DRY_SANDER_EVENT_NPC_ANUDRAN_START",
		
	SMALL_DAMAGE_LAND_FRONT		= "DRY_SANDER_EVENT_NPC_ANUDRAN_START",
	SMALL_DAMAGE_LAND_BACK		= "DRY_SANDER_EVENT_NPC_ANUDRAN_START",
	BIG_DAMAGE_LAND_FRONT		= "DRY_SANDER_EVENT_NPC_ANUDRAN_START",
	BIG_DAMAGE_LAND_BACK		= "DRY_SANDER_EVENT_NPC_ANUDRAN_START",
	DOWN_DAMAGE_LAND_FRONT		= "DRY_SANDER_EVENT_NPC_ANUDRAN_START",
	DOWN_DAMAGE_LAND_BACK		= "DRY_SANDER_EVENT_NPC_ANUDRAN_START",
	FLY_DAMAGE_FRONT			= "DRY_SANDER_EVENT_NPC_ANUDRAN_START",
	FLY_DAMAGE_BACK				= "DRY_SANDER_EVENT_NPC_ANUDRAN_START",
	SMALL_DAMAGE_AIR			= "DRY_SANDER_EVENT_NPC_ANUDRAN_START",	
	BIG_DAMAGE_AIR				= "DRY_SANDER_EVENT_NPC_ANUDRAN_START",
	DOWN_DAMAGE_AIR				= "DRY_SANDER_EVENT_NPC_ANUDRAN_START",
	DOWN_DAMAGE_AIR_LANDING		= "DRY_SANDER_EVENT_NPC_ANUDRAN_START",
	UP_DAMAGE					= "DRY_SANDER_EVENT_NPC_ANUDRAN_START",
	DAMAGE_REVENGE				= "",

	DYING_LAND_FRONT			= "DRY_SANDER_EVENT_NPC_ANUDRAN_DYING",
	DYING_LAND_BACK				= "DRY_SANDER_EVENT_NPC_ANUDRAN_DYING",
	DYING_SKY					= "DRY_SANDER_EVENT_NPC_ANUDRAN_DYING",
}

INIT_AI = 
{
	NO_BRAIN = TRUE,
}

----------------------------------------------------------------------------------------------------------------------------------------

DRY_SANDER_EVENT_NPC_ANUDRAN_START = 
{
	ANIM_NAME		= "Start",
	PLAY_TYPE		= XSKIN_ANIM_PLAYTYPE["XAP_ONE_WAIT"],
	TRANSITION		= FALSE,
	LAND_CONNECT	= FALSE,
	ADD_ROTATE_Y	= 180,
	
	INVINCIBLE					= { 0, 100, },
	
	CAN_PUSH_UNIT	= FALSE,
	CAN_PASS_UNIT	= FALSE,
	
	SPEED_X	= 0,
	SPEED_Y	= 0,
	
	IMMADIATE_PACKET_SEND	= TRUE,

	EVENT_PROCESS = 
	{								
		{ STATE_CHANGE_TYPE["SCT_MOTION_END"],	"DRY_SANDER_EVENT_NPC_ANUDRAN_DYING",	},
	},
	
	FOCUS_CAMERA_AT_CURRENT_STATE = TRUE,
	STOP_AT_CURRENT_STATE = TRUE,
	
	SOUND_PLAY0	= { 1.5, "ANDLAN_Scene_001.ogg", 100, FALSE, 99999, FALSE },
	SOUND_PLAY1	= { 9, "ANDLAN_Scene_002.ogg", 100, FALSE, 99999, FALSE },
	SOUND_PLAY2	= { 0.2, "Trigger_Sander01.ogg", 100, FALSE, 99999, FALSE },
	SOUND_PLAY3	= { 14.7, "Victor_SpecialAttackA_End01.ogg", 100, FALSE, 99999, FALSE },
	SOUND_PLAY4	= { 17.0, "Waldo_Trock_Voice_DamageA02.ogg", 100, FALSE, 99999, FALSE },
	
	
	CAMERA = 
	{
		SUB_CAMERA_TIMING = { 20.0,},		
	
		SUB_CAMERA0 = 
		{
			CAMERA_TYPE		= CAMERA_TYPE["CT_PARTS_LOOK_DIRECT"],
			LOOK_TYPE		= LOOK_TYPE["LT_BONE"],
			LOOK_PARTS		= "Dummy_Camera_Target",
			
			EYE_TYPE		= EYE_TYPE["ET_BONE"],
			EYE_PARTS		= "Dummy_Camera01",
		},
	},
}

function DRY_SANDER_EVENT_NPC_ANUDRAN_START_START( pKTDXApp, pX2Game, pNPCUnit )
	
	 local vPos = pNPCUnit:GetPos()
	 vPos.x = 0
	 vPos.y = 0
	 vPos.z = 0
	
	pNPCUnit:SetPositionForce( vPos )

end

----------------------------------------------------------------------------------------------------------------------------------------

DRY_SANDER_EVENT_NPC_ANUDRAN_DYING = 
{
	ANIM_NAME		= "Dying",
	PLAY_TYPE		= XSKIN_ANIM_PLAYTYPE["XAP_ONE_WAIT"],
	TRANSITION		= FALSE,
	LAND_CONNECT	= FALSE,
	
	INVINCIBLE					= { 0, 100, },
	
	CAN_PUSH_UNIT	= FALSE,
	CAN_PASS_UNIT	= TRUE,
	
	DYING_END		= TRUE,
	
	IMMADIATE_PACKET_SEND		= TRUE,
}


