-- lua header. UTF-8 인코딩 인식을 위해 이 줄은 지우지 마세요.



INIT_SYSTEM = 
{
	UNIT_WIDTH		= 120.0,
	UNIT_HEIGHT		= 150.0,
	UNIT_LAYER		= X2_LAYER["XL_UNIT_0"],
	UNIT_SCALE      = 1.2,
}


INIT_DEVICE = 
{
	READY_TEXTURE = 
	{
	},
	
	READY_SOUND = 
	{
	
	 "Glitter_Lance_Attack1.ogg",
	 "Glitter_LAnce_Attack2.ogg",
	 "Glitter_Lance_Combo.ogg",
	 "Glitter_StandUp.ogg",
	 "Glitter_Dash.ogg",
	 "Glitter_Landing.ogg",
	 "Glitter_SiegeReady.ogg",
     "Glitter_Lance_DashAttackReady.ogg",
	 "Glitter_DashEnd.ogg",

	 
	 "GlitterVoice_AttackRoar1.ogg",
	 "GlitterVoice_AttackRoar2.ogg",
	 
	 "GlitterVoice_DeathRoar.ogg",
	 "GlitterVoice_HurtRoar1.ogg",
	 "GlitterVoice_HurtRoar2.ogg",

     "Glitter_Lance_AttackB.ogg",
	 "Glitter_Lance_AttackBCombo1.ogg",
	 "Glitter_Lance_AttackBCombo2.ogg",
	 "Glitter_Lance_SpecialAttackA.ogg",
	 "Glitter_Lance_Start.ogg",
	 "Glitter_Lance_Win.ogg",
	 
	},
}

INIT_MOTION = 
{
	MOTION_FILE_NAME		= "NUI_GLITER_LANCE_GREAT.x",
}

INIT_PHYSIC = 
{
	RELOAD_ACCEL		= 2000,
	G_ACCEL				= 4000,
	MAX_G_SPEED			= -2000,
	
	WALK_SPEED			= 400,
	RUN_SPEED			= 600,
	JUMP_SPEED			= 1500,
	DASH_JUMP_SPEED		= 1800,
}


INIT_COMPONENT = 
{
	MP_CHANGE_RATE		= 1,
	MP_CHARGE_RATE		= 130,

	
	SHADOW_SIZE			= 200,
	SHADOW_FILE_NAME	= "shadow.dds",
	
	SMALL_HP_BAR_BLUE	= "Small_HP_bar_Blue.TGA",
	SMALL_HP_BAR_RED	= "Small_HP_bar_Red.TGA",
	SMALL_HP_BAR_YELLOW = "Small_HP_bar_Yellow.TGA",
	
	QUESTION_MARK_SEQ		= "QuestionMarkNPC",
	EXCLAMATION_MARK_SEQ	= "ExclamationMarkNPC",
	----MIND_FLAG_HEIGHT		= 230,
	
	HYPER_MODE_COUNT	= 0,
	MAX_HYPER_MODE_TIME	= 30,
	

	HITTED_TYPE			= HITTED_TYPE["HTD_MEAT"],
	FALL_DOWN			= TRUE,
	
	WEAPON0 = 
	{
		WEAPON_FILE_NAME			= "NUI_GLITER_GREAT_Lance.X",
		WEAPON_BONE_NAME			= "Dummy1_Rhand",
			
		USE_SLASH_TRACE				= TRUE,						
		SLASH_TRACE_TOP_BONE		= "TRACE_START0",
		SLASH_TRACE_BOTTOM_BONE		= "TRACE_END0",
	},
}

INIT_STATE = 
{
	--6     = 0x06
	{ STATE_NAME = "GLITER_LANCE_GREAT_START",						}, 
		
	{ STATE_NAME = "GLITER_LANCE_GREAT_SIEGE_READY",					},
	{ STATE_NAME = "GLITER_LANCE_GREAT_SIEGE_WAIT",					},
	{ STATE_NAME = "GLITER_LANCE_GREAT_SIEGE_ATTACK",},
	
	--9	= 0x09 
	{ STATE_NAME = "GLITER_LANCE_GREAT_WAIT",							},
	{ STATE_NAME = "GLITER_LANCE_GREAT_WAIT_HABIT",					},

	{ STATE_NAME = "GLITER_LANCE_GREAT_SELF_COMMAND_TRANSIT",					LUA_STATE_START_FUNC = "GLITER_LANCE_GREAT_SELF_COMMAND_TRANSIT_STATE_START" 		},

	
	--11	= 0x0b
	{ STATE_NAME = "GLITER_LANCE_GREAT_WALK",							LUA_STATE_END_FUNC = "GLITER_LANCE_GREAT_WALK_STATE_END"						},
	{ STATE_NAME = "GLITER_LANCE_GREAT_FORCED_WALK",							LUA_STATE_END_FUNC = "GLITER_LANCE_GREAT_WALK_STATE_END"						},

	

	{ STATE_NAME = "GLITER_LANCE_GREAT_JUMP_UP",						},
	{ STATE_NAME = "GLITER_LANCE_GREAT_JUMP_DOWN",					LUA_STATE_END_FUNC = "GLITER_LANCE_GREAT_JUMP_DOWN_STATE_END"					},
	--14	= 0x0e
	{ STATE_NAME = "GLITER_LANCE_GREAT_JUMP_UP_DIR",					},
	--15	= 0x0f
	{ STATE_NAME = "GLITER_LANCE_GREAT_JUMP_DOWN_DIR",				LUA_STATE_END_FUNC = "GLITER_LANCE_GREAT_JUMP_DOWN_DIR_STATE_END"				},
	--16	= 0x10
	{ STATE_NAME = "GLITER_LANCE_GREAT_JUMP_LANDING",					},

	--18	= 0x12
	{ STATE_NAME = "GLITER_LANCE_GREAT_ATTACK",						LUA_FRAME_MOVE_FUNC = "GLITER_LANCE_GREAT_ATTACK_FRAME_MOVE",	STATE_COOL_TIME = 3, },
	{ STATE_NAME = "GLITER_LANCE_GREAT_COMBO",						LUA_FRAME_MOVE_FUNC = "GLITER_LANCE_GREAT_COMBO_FRAME_MOVE",	},
	
	
	{ STATE_NAME = "GLITER_LANCE_GREAT_DASH_ATTACK_READY",				LUA_STATE_END_FUNC = "GLITER_LANCE_GREAT_DASH_ATTACK_READY_STATE_END", STATE_COOL_TIME = 5,  },
	{ STATE_NAME = "GLITER_LANCE_GREAT_DASH_ATTACK",					LUA_FRAME_MOVE_FUNC = "GLITER_LANCE_GREAT_DASH_ATTACK_FRAME_MOVE",		},
	
	{ STATE_NAME = "GLITER_LANCE_GREAT_DASH",							},
	{ STATE_NAME = "GLITER_LANCE_GREAT_DASH_END",						},
	
	--리액션 관련
	{ STATE_NAME = "GLITER_LANCE_GREAT_DAMAGE_FRONT",					LUA_FRAME_MOVE_FUNC = "GLITER_LANCE_GREAT_DAMAGE_FRONT_FRAME_MOVE"				},
	{ STATE_NAME = "GLITER_LANCE_GREAT_DAMAGE_BACK",					LUA_FRAME_MOVE_FUNC = "GLITER_LANCE_GREAT_DAMAGE_BACK_FRAME_MOVE"				},
	{ STATE_NAME = "GLITER_LANCE_GREAT_DAMAGE_DOWN_FRONT",			LUA_FRAME_MOVE_FUNC = "GLITER_LANCE_GREAT_DAMAGE_DOWN_FRONT_FRAME_MOVE"		},
	{ STATE_NAME = "GLITER_LANCE_GREAT_DAMAGE_DOWN_BACK",				LUA_FRAME_MOVE_FUNC = "GLITER_LANCE_GREAT_DAMAGE_DOWN_BACK_FRAME_MOVE"			},
	{ STATE_NAME = "GLITER_LANCE_GREAT_DAMAGE_FLY_FRONT",				},
	{ STATE_NAME = "GLITER_LANCE_GREAT_DAMAGE_FLY_BACK",				},
	{ STATE_NAME = "GLITER_LANCE_GREAT_DAMAGE_AIR",					},
	{ STATE_NAME = "GLITER_LANCE_GREAT_DAMAGE_AIR_DOWN",				},
	{ STATE_NAME = "GLITER_LANCE_GREAT_DAMAGE_AIR_UP",				},
	{ STATE_NAME = "GLITER_LANCE_GREAT_DAMAGE_AIR_FALL",				},
	{ STATE_NAME = "GLITER_LANCE_GREAT_DAMAGE_AIR_DOWN_LANDING",		LUA_FRAME_MOVE_FUNC = "GLITER_LANCE_GREAT_DAMAGE_AIR_DOWN_LANDING_FRAME_MOVE"	},
	
	{ STATE_NAME = "GLITER_LANCE_GREAT_STAND_UP_FRONT",				},
	{ STATE_NAME = "GLITER_LANCE_GREAT_STAND_UP_BACK",				},
	
	{ STATE_NAME = "GLITER_LANCE_GREAT_DAMAGE_REVENGE",				},
	
	
	
	
	{ STATE_NAME = "GLITER_LANCE_GREAT_DYING_LAND_FRONT",				LUA_STATE_START_FUNC = "GLITER_LANCE_GREAT_DYING_LAND_STATE_START",},
	{ STATE_NAME = "GLITER_LANCE_GREAT_DYING_LAND_BACK",				LUA_STATE_START_FUNC = "GLITER_LANCE_GREAT_DYING_LAND_STATE_START",},
	{ STATE_NAME = "GLITER_LANCE_GREAT_DYING_SKY",					LUA_STATE_START_FUNC = "GLITER_LANCE_GREAT_DYING_LAND_STATE_START",},
	
	
	
	START_STATE					= "GLITER_LANCE_GREAT_START",
	WAIT_STATE					= "GLITER_LANCE_GREAT_WAIT",
	SIEGE_STATE					= "GLITER_LANCE_GREAT_SIEGE_READY",
	
	
	SMALL_DAMAGE_LAND_FRONT		= "GLITER_LANCE_GREAT_DAMAGE_FRONT",
	SMALL_DAMAGE_LAND_BACK		= "GLITER_LANCE_GREAT_DAMAGE_BACK",
	BIG_DAMAGE_LAND_FRONT		= "GLITER_LANCE_GREAT_DAMAGE_FRONT",
	BIG_DAMAGE_LAND_BACK		= "GLITER_LANCE_GREAT_DAMAGE_BACK",
	DOWN_DAMAGE_LAND_FRONT		= "GLITER_LANCE_GREAT_DAMAGE_DOWN_FRONT",
	DOWN_DAMAGE_LAND_BACK		= "GLITER_LANCE_GREAT_DAMAGE_DOWN_BACK",
	FLY_DAMAGE_FRONT			= "GLITER_LANCE_GREAT_DAMAGE_FLY_FRONT",
	FLY_DAMAGE_BACK				= "GLITER_LANCE_GREAT_DAMAGE_FLY_BACK",
	SMALL_DAMAGE_AIR			= "GLITER_LANCE_GREAT_DAMAGE_AIR",	
	BIG_DAMAGE_AIR				= "GLITER_LANCE_GREAT_DAMAGE_AIR",
	DOWN_DAMAGE_AIR				= "GLITER_LANCE_GREAT_DAMAGE_AIR",
	DOWN_DAMAGE_AIR_LANDING				= "GLITER_LANCE_GREAT_DAMAGE_AIR_DOWN_LANDING",
	UP_DAMAGE					= "GLITER_LANCE_GREAT_DAMAGE_AIR_UP",
	DAMAGE_REVENGE				= "GLITER_LANCE_GREAT_DAMAGE_REVENGE",
	
	DAMAGE_EXTRA_STATES         = {"GLITER_LANCE_GREAT_DAMAGE_AIR_DOWN","GLITER_LANCE_GREAT_DAMAGE_AIR_FALL","GLITER_LANCE_GREAT_STAND_UP_FRONT","GLITER_LANCE_GREAT_STAND_UP_BACK",
	"GLITER_LANCE_GREAT_JUMP_DOWN","GLITER_LANCE_GREAT_JUMP_LANDING",},	
	
	DYING_LAND_FRONT			= "GLITER_LANCE_GREAT_DYING_LAND_FRONT",
	DYING_LAND_BACK				= "GLITER_LANCE_GREAT_DYING_LAND_BACK",
	DYING_SKY					= "GLITER_LANCE_GREAT_DYING_SKY",

	REVENGE_ATTACK				= "",	
}



INIT_AI = 
{

	TARGET = 
	{
		TARGET_PRIORITY 			= TARGET_PRIORITY["TP_LOW_HP_FIRST"],
		TARGET_INTERVAL				= 3,		-- sec
		TARGET_NEAR_RANGE			= 250,		-- 이 거리보다 가까우면 TARGET_SUCCESS_RATE에 관계없이 무조건 타게팅된다
		TARGET_RANGE				= 800,		-- cm
		TARGET_LOST_RANGE			= 1200,		-- cm
		TARGET_SUCCESS_RATE			= 100,  --50,		-- %
		ATTACK_TARGET_RATE			= 100, -- 30,		-- 나를 공격한 유닛을 타게팅할 확률
		PRESERVE_LAST_TARGET_RATE	= 100, -- 30,		-- 이전에 타게팅된 유닛을 계속 타게팅할 확률
	},

	CHASE_MOVE = 
	{		
		MOVE_SPLIT_RANGE	= 600,
		DEST_GAP			= 150,	-- 목적지에서 이 거리 안에 있으면 도착했다고 판단한다
		MOVE_GAP			= 160,
		
		DIR_CHANGE_INTERVAL = 0.7,
		
		WALK_INTERVAL		= 3,
		NEAR_WALK_RATE		= 100,   --  70,
		FAR_WALK_RATE		= 100,   -- 30,
		
		JUMP_INTERVAL		= 5,
		UP_JUMP_RATE		= 100, -- 40,
		UP_DOWN_RATE		= 20,
		DOWN_JUMP_RATE		= 100,    --  20,
		DOWN_DOWN_RATE		= 40,
		
		--LINE_END_RANGE		= 100,	-- cm
	},	
	
	PATROL_MOVE = 	
	{
		PATROL_BEGIN_RATE		= 100, --50,		
		PATROL_RANGE			= 200,
		PATROL_COOL_TIME		= 2,
		ONLY_THIS_LINE_GROUP	= TRUE,
	},
	
	ESCAPE_MOVE = 
	{		
		MOVE_SPLIT_RANGE	= 500,	-- cm
		ESCAPE_GAP			= 600,	-- 이 거리 보다 멀어지면 도망 성공
		
		WALK_INTERVAL		= 1.5,	-- 초
		NEAR_WALK_RATE		= 100,   --  10,
		FAR_WALK_RATE		= 100,   -- 10,
		
		JUMP_INTERVAL		= 10,
		UP_JUMP_RATE		= 100, -- 30,
		UP_DOWN_RATE		= 30,
		DOWN_JUMP_RATE		= 100,    --  30,
		DOWN_DOWN_RATE		= 30,
		
		--LINE_END_RANGE		= 80,	-- cm
	},

}

------------------------------------------
GLITER_LANCE_GREAT_SIEGE_READY = 
{
	ANIM_NAME					= "SiegeReady",
	PLAY_TYPE					= XSKIN_ANIM_PLAYTYPE["XAP_ONE_WAIT"],
	TRANSITION					= TRUE,
		
	ANIM_SPEED			= 1.6,

	CAN_PUSH_UNIT				= FALSE,
	CAN_PASS_UNIT				= FALSE,
	
	IMMADIATE_PACKET_SEND		= TRUE,
	VIEW_TARGET				= TRUE,

	
	EVENT_PROCESS = 
	{		
		{ STATE_CHANGE_TYPE["SCT_MOTION_END"],				"GLITER_LANCE_GREAT_SIEGE_WAIT",						},
	},
}




GLITER_LANCE_GREAT_SIEGE_WAIT = 
{
	ANIM_NAME					= "Siege",
	PLAY_TYPE					= XSKIN_ANIM_PLAYTYPE["XAP_LOOP"],
	TRANSITION					= TRUE,
	
	CAN_PUSH_UNIT				= FALSE,
	CAN_PASS_UNIT				= FALSE,	
	
	SPEED_X						= 0,
	SPEED_Y						= 0,
	
	IMMADIATE_PACKET_SEND		= TRUE,
	NEVER_MOVE					= TRUE,
	FALL_DOWN					= FALSE,
	EVENT_INTERVAL_TIME0		= 1,		

	EVENT_PROCESS = 
	{
		{ STATE_CHANGE_TYPE["SCT_CONDITION_TABLE"],			"GLITER_LANCE_GREAT_WAIT",			"CT_GLITER_LANCE_GREAT_WAIT",		},			
		{ STATE_CHANGE_TYPE["SCT_CONDITION_TABLE"],			"GLITER_LANCE_GREAT_SIEGE_ATTACK",			"CT_GLITER_LANCE_GREAT_SIEGE_ATTACK",	},
	},
	

	CT_GLITER_LANCE_GREAT_WAIT = 
	{
		COMMAND_FALSE0				= GROUP_AI_COMMAND["GAI_CMD_SKILL_B"],	
		COMMAND_FALSE1				= GROUP_AI_COMMAND["GAI_CMD_SKILL_C"],	
		RATE					= 100,
	},	

	CT_GLITER_LANCE_GREAT_SIEGE_ATTACK = 
	{
		COMMAND_TRUE0				= GROUP_AI_COMMAND["GAI_CMD_SKILL_C"],	
		DISTANCE_TO_TARGET_NEAR			= 800,
		RATE					= 100,
		ATTACK_SUCCESS				= TRUE,
	},

	ATTACK_TIME0				= { 0, 10000, },

	DISABLE_ATTACK_BOX = 
	{
		"Lance01",
		"Lance02",
	},
	DAMAGE_DATA = 
	{
		DAMAGE_TYPE		= DAMAGE_TYPE["DT_PHYSIC"],
		HIT_TYPE		= HIT_TYPE["HT_SWORD_SLASH"],
		REACT_TYPE		= REACT_TYPE["RT_FLY"],
		
		DAMAGE = 
		{
			PHYSIC		= 1,
		},
		
		BACK_SPEED_X			= 600,
		BACK_SPEED_Y			= 1200,
		
		CAMERA_CRASH_GAP		= 5.0,	
		CAMERA_CRASH_TIME		= 0.2,		
		CAN_REVENGE			= TRUE,	
	},
}

GLITER_LANCE_GREAT_SIEGE_ATTACK = 
{
	ANIM_NAME					= "SiegeAttack",
	PLAY_TYPE					= XSKIN_ANIM_PLAYTYPE["XAP_ONE_WAIT"],
	TRANSITION					= FALSE,
	LAND_CONNECT				= FALSE,
	
	CAN_PUSH_UNIT				= TRUE,
	CAN_PASS_UNIT				= FALSE,
	
	SPEED_X						= 0,
	SPEED_Y						= 0,	

	

	VIEW_TARGET					= TRUE,
	IMMADIATE_PACKET_SEND		= TRUE,
	NEVER_MOVE					= TRUE,
	FALL_DOWN					= FALSE,
	
			
	EVENT_PROCESS = 
	{		
		{ STATE_CHANGE_TYPE["SCT_MOTION_END"],				"GLITER_LANCE_GREAT_SIEGE_WAIT",					},
	},

	ATTACK_TIME0				= { 0.15, 0.25, },
	
	DISABLE_ATTACK_BOX = 
	{
		"Lance01",
		"Lance02",
	},

	DAMAGE_DATA = 
	{
		DAMAGE_TYPE		= DAMAGE_TYPE["DT_PHYSIC"],
		HIT_TYPE		= HIT_TYPE["HT_SWORD_SLASH"],
		REACT_TYPE		= REACT_TYPE["RT_FLY"],
		
		DAMAGE = 
		{
			PHYSIC		= 1,
		},
		
		BACK_SPEED_X			= 1000,
		BACK_SPEED_Y			= 1200,
		
		CAMERA_CRASH_GAP		= 5.0,	
		CAMERA_CRASH_TIME		= 0.2,		
		CAN_REVENGE			= TRUE,	
	},

	
}



GLITER_LANCE_GREAT_START = 
{
	ANIM_NAME					= "WaitHabit",
	PLAY_TYPE					= XSKIN_ANIM_PLAYTYPE["XAP_ONE_WAIT"],
	TRANSITION					= FALSE,
	
	CAN_PUSH_UNIT				= TRUE,
	CAN_PASS_UNIT				= FALSE,
	IMMADIATE_PACKET_SEND		= TRUE,	
		
	EVENT_PROCESS = 
	{		
		{ STATE_CHANGE_TYPE["SCT_CONDITION_TABLE"],		"GLITER_LANCE_GREAT_WAIT",		"CT_GLITER_LANCE_GREAT_WAIT"				},
	},
	
	CT_GLITER_LANCE_GREAT_WAIT = 
	{
		STATE_TIME_OVER			= 2.8,
	},
}



GLITER_LANCE_GREAT_WAIT = 
{
	ANIM_NAME					= "Wait",
	PLAY_TYPE					= XSKIN_ANIM_PLAYTYPE["XAP_LOOP"],
	TRANSITION					= TRUE,
	
	CAN_PUSH_UNIT				= TRUE,
	CAN_PASS_UNIT				= FALSE,	
	
	SPEED_X						= 0,
	SPEED_Y						= 0,
	
	PASSIVE_SPEED_X				= 0,
	
	ALLOW_DIR_CHANGE			= TRUE,
	IMMADIATE_PACKET_SEND			= TRUE,
	VIEW_TARGET				= TRUE,
	EVENT_INTERVAL_TIME0		= 1,
	
	EVENT_PROCESS = 
	{
		{ STATE_CHANGE_TYPE["SCT_AI_SELF_COMMAND_TRANSIT"],	"GLITER_LANCE_GREAT_SELF_COMMAND_TRANSIT",				},
		
		{ STATE_CHANGE_TYPE["SCT_FOOT_ON_LINE_FALSE_DOWN"],	"GLITER_LANCE_GREAT_JUMP_DOWN",				},
		
		{ STATE_CHANGE_TYPE["SCT_CONDITION_TABLE"],			"GLITER_LANCE_GREAT_ATTACK",				"CT_GLITER_LANCE_GREAT_ATTACK",			},
		{ STATE_CHANGE_TYPE["SCT_CONDITION_TABLE"],			"GLITER_LANCE_GREAT_DASH_ATTACK_READY",		"CT_GLITER_LANCE_GREAT_DASH_ATTACK_READY",			},
		{ STATE_CHANGE_TYPE["SCT_CONDITION_TABLE"],			"GLITER_LANCE_GREAT_DASH_ATTACK_READY",		"CT_GLITER_LANCE_GREAT_DASH_ATTACK_COMMAND",		},
		{ STATE_CHANGE_TYPE["SCT_CONDITION_TABLE"],			"GLITER_LANCE_GREAT_SIEGE_READY",		"CT_GLITER_LANCE_GREAT_SIEGE_READY",			},
		{ STATE_CHANGE_TYPE["SCT_CONDITION_TABLE"],			"GLITER_LANCE_GREAT_SIEGE_READY",		"CT_GLITER_LANCE_GREAT_SIEGE_READY_2",			},

	
	
	
		{ STATE_CHANGE_TYPE["SCT_CONDITION_TABLE"],			"GLITER_LANCE_GREAT_WAIT_HABIT",				"CT_GLITER_LANCE_GREAT_WAIT_HABIT",		},
		
		{ STATE_CHANGE_TYPE["SCT_AI_WALK"],					"GLITER_LANCE_GREAT_WALK",						},
		{ STATE_CHANGE_TYPE["SCT_AI_DASH"],					"GLITER_LANCE_GREAT_FORCED_WALK",						},
		{ STATE_CHANGE_TYPE["SCT_AI_JUMP"],					"GLITER_LANCE_GREAT_JUMP_UP",					},
		{ STATE_CHANGE_TYPE["SCT_AI_JUMP_DIR"],				"GLITER_LANCE_GREAT_JUMP_UP_DIR",				},
		{ STATE_CHANGE_TYPE["SCT_AI_DOWN"],					"GLITER_LANCE_GREAT_JUMP_DOWN",				},
		{ STATE_CHANGE_TYPE["SCT_AI_DOWN_DIR"],				"GLITER_LANCE_GREAT_JUMP_DOWN_DIR",			},

	},

	CT_GLITER_LANCE_GREAT_ATTACK = 
	{
		COMMAND_FALSE0				= GROUP_AI_COMMAND["GAI_CMD_FORCED_MOVE"],
		COMMAND_FALSE1				= GROUP_AI_COMMAND["GAI_CMD_SKILL_A"],	
		COMMAND_FALSE2				= GROUP_AI_COMMAND["GAI_CMD_SKILL_B"],
		COMMAND_FALSE3				= GROUP_AI_COMMAND["GAI_CMD_SKILL_C"],
		EVENT_INTERVAL_ID			= 0,
		DISTANCE_TO_TARGET_NEAR			= 400,
		RATE					= 80,
	},
	
	CT_GLITER_LANCE_GREAT_DASH_ATTACK_READY = 
	{
		EVENT_INTERVAL_ID			= 0,
		DISTANCE_TO_TARGET_NEAR		= 1000,
		DISTANCE_OVER_TARGET_NEAR	= 400,
		RATE						= 30,
	},

	CT_GLITER_LANCE_GREAT_DASH_ATTACK_COMMAND = 
	{
		COMMAND_TRUE0				= GROUP_AI_COMMAND["GAI_CMD_SKILL_A"],
		EVENT_INTERVAL_ID			= 0,
		RATE						= 100,
	},
	
	
	CT_GLITER_LANCE_GREAT_SIEGE_READY =
	{
		COMMAND_TRUE0				= GROUP_AI_COMMAND["GAI_CMD_SKILL_B"],	
		EVENT_INTERVAL_ID			= 0,
		RATE					= 100,		
	},
	
	CT_GLITER_LANCE_GREAT_SIEGE_READY_2 =
	{
		COMMAND_TRUE0				= GROUP_AI_COMMAND["GAI_CMD_SKILL_C"],	
		EVENT_INTERVAL_ID			= 0,
		RATE					= 100,		
	},
		
	
	
	CT_GLITER_LANCE_GREAT_WAIT_HABIT = 
	{
		ANIM_PLAY_COUNT				= 1,
		RATE					= 60,
		HAVE_TARGET				= 0,		-- false
	},
	
		
}




----------------------------------------------------------------------------

GLITER_LANCE_GREAT_SELF_COMMAND_TRANSIT = 
{
	ANIM_NAME					= "Wait",
	PLAY_TYPE					= XSKIN_ANIM_PLAYTYPE["XAP_ONE_WAIT"],
	TRANSITION					= FALSE,
	
	CAN_PUSH_UNIT				= TRUE,
	CAN_PASS_UNIT				= FALSE,
	IMMADIATE_PACKET_SEND		= TRUE,	

	EVENT_PROCESS = 
	{		
	        { STATE_CHANGE_TYPE["SCT_CONDITION_TABLE"],	"GLITER_LANCE_GREAT_WAIT",	"CT_GLITER_LANCE_GREAT_WAIT",	},
 	},

	CT_GLITER_LANCE_GREAT_WAIT = 
	{
		RATE						= 100,
	},
}

GLITER_LANCE_GREAT_WAIT_HABIT = 
{
	ANIM_NAME					= "WaitHabit",
	PLAY_TYPE					= XSKIN_ANIM_PLAYTYPE["XAP_ONE_WAIT"],
	TRANSITION					= TRUE,
	
	CAN_PUSH_UNIT				= TRUE,
	CAN_PASS_UNIT				= FALSE,
	IMMADIATE_PACKET_SEND		= TRUE,

	
	EVENT_PROCESS = 
	{		
		{ STATE_CHANGE_TYPE["SCT_FOOT_ON_LINE_FALSE_DOWN"],	"GLITER_LANCE_GREAT_JUMP_DOWN",				},
		{ STATE_CHANGE_TYPE["SCT_MOTION_END"],				"GLITER_LANCE_GREAT_WAIT",						},
	},
}


GLITER_LANCE_GREAT_WALK = 
{
	ANIM_NAME					= "Walk",
	PLAY_TYPE					= XSKIN_ANIM_PLAYTYPE["XAP_LOOP"],
	TRANSITION					= TRUE,
	
	CAN_PUSH_UNIT				= TRUE,
	CAN_PASS_UNIT				= FALSE,
	
	PASSIVE_SPEED_X				= INIT_PHYSIC["WALK_SPEED"],
	
	ALLOW_DIR_CHANGE			= TRUE,
	IMMADIATE_PACKET_SEND		= TRUE,
	
	EVENT_INTERVAL_TIME0		= 2,
	EVENT_INTERVAL_TIME1		= 3,
	
	EVENT_PROCESS = 
	{		
		{ STATE_CHANGE_TYPE["SCT_FOOT_ON_LINE_FALSE_DOWN"],	"GLITER_LANCE_GREAT_JUMP_DOWN_DIR",			},
				
		{ STATE_CHANGE_TYPE["SCT_CONDITION_TABLE"],			"GLITER_LANCE_GREAT_ATTACK",					"CT_GLITER_LANCE_GREAT_ATTACK",				},
		{ STATE_CHANGE_TYPE["SCT_CONDITION_TABLE"],			"GLITER_LANCE_GREAT_DASH_ATTACK_READY",		"CT_GLITER_LANCE_GREAT_DASH_ATTACK_READY",			},
		{ STATE_CHANGE_TYPE["SCT_CONDITION_TABLE"],			"GLITER_LANCE_GREAT_DASH_ATTACK_READY",		"CT_GLITER_LANCE_GREAT_DASH_ATTACK_COMMAND",		},		
		{ STATE_CHANGE_TYPE["SCT_CONDITION_TABLE"],			"GLITER_LANCE_GREAT_SIEGE_READY",		"CT_GLITER_LANCE_GREAT_SIEGE_READY",			},
		{ STATE_CHANGE_TYPE["SCT_CONDITION_TABLE"],			"GLITER_LANCE_GREAT_SIEGE_READY",		"CT_GLITER_LANCE_GREAT_SIEGE_READY_2",			},

		{ STATE_CHANGE_TYPE["SCT_AI_WAIT"],					"GLITER_LANCE_GREAT_WAIT",					},
		{ STATE_CHANGE_TYPE["SCT_AI_DASH"],					"GLITER_LANCE_GREAT_FORCED_WALK",					},
		{ STATE_CHANGE_TYPE["SCT_AI_JUMP"],					"GLITER_LANCE_GREAT_JUMP_UP",					},
		{ STATE_CHANGE_TYPE["SCT_AI_JUMP_DIR"],				"GLITER_LANCE_GREAT_JUMP_UP_DIR",				},
		{ STATE_CHANGE_TYPE["SCT_AI_DOWN"],					"GLITER_LANCE_GREAT_JUMP_DOWN",				},
		{ STATE_CHANGE_TYPE["SCT_AI_DOWN_DIR"],				"GLITER_LANCE_GREAT_JUMP_DOWN_DIR",			},
	},

	CT_GLITER_LANCE_GREAT_ATTACK = 
	{
		COMMAND_FALSE0				= GROUP_AI_COMMAND["GAI_CMD_FORCED_MOVE"],
		COMMAND_FALSE1				= GROUP_AI_COMMAND["GAI_CMD_SKILL_A"],	
		COMMAND_FALSE2				= GROUP_AI_COMMAND["GAI_CMD_SKILL_B"],
		COMMAND_FALSE3				= GROUP_AI_COMMAND["GAI_CMD_SKILL_C"],	
		EVENT_INTERVAL_ID			= 0,
		DISTANCE_TO_TARGET_NEAR			= 500,
		RATE					= 80,
	},
	
	CT_GLITER_LANCE_GREAT_DASH_ATTACK_READY = 
	{
		EVENT_INTERVAL_ID			= 0,
		DISTANCE_TO_TARGET_NEAR			= 1000,
		DISTANCE_OVER_TARGET_NEAR = 400,
		RATE					= 30,
	},

	CT_GLITER_LANCE_GREAT_DASH_ATTACK_COMMAND = 
	{
		COMMAND_TRUE0				= GROUP_AI_COMMAND["GAI_CMD_SKILL_A"],
		EVENT_INTERVAL_ID			= 0,
		RATE						= 100,
	},


	CT_GLITER_LANCE_GREAT_SIEGE_READY =
	{
		COMMAND_TRUE0				= GROUP_AI_COMMAND["GAI_CMD_SKILL_B"],	
		EVENT_INTERVAL_ID			= 0,
		RATE					= 100,		
	},

	CT_GLITER_LANCE_GREAT_SIEGE_READY_2 =
	{
		COMMAND_TRUE0				= GROUP_AI_COMMAND["GAI_CMD_SKILL_C"],	
		EVENT_INTERVAL_ID			= 0,
		RATE					= 100,		
	},
	
}



GLITER_LANCE_GREAT_FORCED_WALK = 
{
	ANIM_NAME					= "Walk",
	PLAY_TYPE					= XSKIN_ANIM_PLAYTYPE["XAP_LOOP"],
	TRANSITION					= TRUE,
	
	CAN_PUSH_UNIT				= TRUE,
	CAN_PASS_UNIT				= FALSE,
	
	PASSIVE_SPEED_X				= INIT_PHYSIC["RUN_SPEED"],
	
	ALLOW_DIR_CHANGE			= TRUE,
	IMMADIATE_PACKET_SEND		= TRUE,
	
	EVENT_INTERVAL_TIME0		= 2,
	EVENT_INTERVAL_TIME1		= 3,
	
	EVENT_PROCESS = 
	{		
		{ STATE_CHANGE_TYPE["SCT_FOOT_ON_LINE_FALSE_DOWN"],	"GLITER_LANCE_GREAT_JUMP_DOWN_DIR",			},
				
		{ STATE_CHANGE_TYPE["SCT_CONDITION_TABLE"],			"GLITER_LANCE_GREAT_ATTACK",					"CT_GLITER_LANCE_GREAT_ATTACK",				},
		{ STATE_CHANGE_TYPE["SCT_CONDITION_TABLE"],			"GLITER_LANCE_GREAT_DASH_ATTACK_READY",		"CT_GLITER_LANCE_GREAT_DASH_ATTACK_READY",			},		
		{ STATE_CHANGE_TYPE["SCT_CONDITION_TABLE"],			"GLITER_LANCE_GREAT_SIEGE_READY",		"CT_GLITER_LANCE_GREAT_SIEGE_READY",			},
		{ STATE_CHANGE_TYPE["SCT_CONDITION_TABLE"],			"GLITER_LANCE_GREAT_SIEGE_READY",		"CT_GLITER_LANCE_GREAT_SIEGE_READY_2",			},

		{ STATE_CHANGE_TYPE["SCT_AI_WAIT"],					"GLITER_LANCE_GREAT_WAIT",					},
		{ STATE_CHANGE_TYPE["SCT_AI_WALK"],					"GLITER_LANCE_GREAT_WALK",					},
		{ STATE_CHANGE_TYPE["SCT_AI_JUMP"],					"GLITER_LANCE_GREAT_JUMP_UP",					},
		{ STATE_CHANGE_TYPE["SCT_AI_JUMP_DIR"],				"GLITER_LANCE_GREAT_JUMP_UP_DIR",				},
		{ STATE_CHANGE_TYPE["SCT_AI_DOWN"],					"GLITER_LANCE_GREAT_JUMP_DOWN",				},
		{ STATE_CHANGE_TYPE["SCT_AI_DOWN_DIR"],				"GLITER_LANCE_GREAT_JUMP_DOWN_DIR",			},
	},

	CT_GLITER_LANCE_GREAT_ATTACK = 
	{
		COMMAND_FALSE0				= GROUP_AI_COMMAND["GAI_CMD_FORCED_MOVE"],
		COMMAND_FALSE1				= GROUP_AI_COMMAND["GAI_CMD_SKILL_A"],	
		COMMAND_FALSE2				= GROUP_AI_COMMAND["GAI_CMD_SKILL_B"],
		COMMAND_FALSE3				= GROUP_AI_COMMAND["GAI_CMD_SKILL_C"],
		EVENT_INTERVAL_ID			= 0,
		DISTANCE_TO_TARGET_NEAR			= 400,
		RATE					= 80,
	},
	
	CT_GLITER_LANCE_GREAT_DASH_ATTACK_READY = 
	{
		COMMAND_TRUE0				= GROUP_AI_COMMAND["GAI_CMD_SKILL_A"],
		EVENT_INTERVAL_ID			= 0,
		DISTANCE_TO_TARGET_NEAR			= 1000,
		RATE					= 100,
	},

	CT_GLITER_LANCE_GREAT_SIEGE_READY =
	{
		COMMAND_TRUE0				= GROUP_AI_COMMAND["GAI_CMD_SKILL_B"],	
		EVENT_INTERVAL_ID			= 0,
		RATE					= 100,		
	},

	CT_GLITER_LANCE_GREAT_SIEGE_READY_2 =
	{
		COMMAND_TRUE0				= GROUP_AI_COMMAND["GAI_CMD_SKILL_C"],	
		EVENT_INTERVAL_ID			= 0,
		RATE					= 100,		
	},
}






GLITER_LANCE_GREAT_DASH = 
{
	ANIM_NAME					= "Dash",
	PLAY_TYPE					= XSKIN_ANIM_PLAYTYPE["XAP_LOOP"],
	TRANSITION					= TRUE,
	
	CAN_PUSH_UNIT				= FALSE,
	CAN_PASS_UNIT				= FALSE,
	
	PASSIVE_SPEED_X				= INIT_PHYSIC["RUN_SPEED"],
	
	ALLOW_DIR_CHANGE			= TRUE,
	IMMADIATE_PACKET_SEND		= TRUE,
	
	EVENT_INTERVAL_TIME0		= 1,
	
	EVENT_PROCESS = 
	{		
		{ STATE_CHANGE_TYPE["SCT_FOOT_ON_LINE_FALSE_DOWN"],	"GLITER_LANCE_GREAT_JUMP_DOWN_DIR",			},
				
		{ STATE_CHANGE_TYPE["SCT_CONDITION_TABLE"],			"GLITER_LANCE_GREAT_DASH_ATTACK",					"CT_GLITER_LANCE_GREAT_DASH_ATTACK",				},

		{ STATE_CHANGE_TYPE["SCT_AI_WAIT"],					"GLITER_LANCE_GREAT_WAIT",					},
		{ STATE_CHANGE_TYPE["SCT_AI_WALK"],					"GLITER_LANCE_GREAT_WALK",					},
		{ STATE_CHANGE_TYPE["SCT_AI_JUMP"],					"GLITER_LANCE_GREAT_JUMP_UP",					},
		{ STATE_CHANGE_TYPE["SCT_AI_JUMP_DIR"],				"GLITER_LANCE_GREAT_JUMP_UP_DIR",				},
		{ STATE_CHANGE_TYPE["SCT_AI_DOWN"],					"GLITER_LANCE_GREAT_JUMP_DOWN",				},
		{ STATE_CHANGE_TYPE["SCT_AI_DOWN_DIR"],				"GLITER_LANCE_GREAT_JUMP_DOWN_DIR",			},
	},
	
	CT_GLITER_LANCE_GREAT_DASH_ATTACK = 
	{
		EVENT_INTERVAL_ID			= 0,
		DISTANCE_TO_TARGET_NEAR		= 500,
		RATE						= 30,
	},

}



GLITER_LANCE_GREAT_DASH_END = 
{
	ANIM_NAME					= "DashEnd",
	PLAY_TYPE					= XSKIN_ANIM_PLAYTYPE["XAP_ONE_WAIT"],
	TRANSITION					= FALSE,
	
	CAN_PUSH_UNIT				= FALSE,
	CAN_PASS_UNIT				= FALSE,
	
	SPEED_X						= INIT_PHYSIC["RUN_SPEED"],
	
	ALLOW_DIR_CHANGE			= FALSE,
	IMMADIATE_PACKET_SEND		= TRUE,
	
	EVENT_PROCESS = 
	{		
		{ STATE_CHANGE_TYPE["SCT_FOOT_ON_LINE_FALSE_DOWN"],	"GLITER_LANCE_GREAT_JUMP_DOWN_DIR",				},
		{ STATE_CHANGE_TYPE["SCT_MOTION_END"],				"GLITER_LANCE_GREAT_WAIT",							},
	},
}








GLITER_LANCE_GREAT_DASH_ATTACK_READY = 
{
	ANIM_NAME					= "DashAttackReady",
	PLAY_TYPE					= XSKIN_ANIM_PLAYTYPE["XAP_ONE_WAIT"],
	TRANSITION					= TRUE,
	
	CAN_PUSH_UNIT				= TRUE,
	CAN_PASS_UNIT				= FALSE,
	
	IMMADIATE_PACKET_SEND		= TRUE,

    SOUND_PLAY0			= { 0.352, "Glitter_Lance_DashAttackReady.ogg" },
	
	VIEW_TARGET					= TRUE,
	ALLOW_DIR_CHANGE			= FALSE,
	IMMADIATE_PACKET_SEND		= TRUE,
	
	EVENT_PROCESS = 
	{		
		{ STATE_CHANGE_TYPE["SCT_FOOT_ON_LINE_FALSE_DOWN"],	"GLITER_LANCE_GREAT_JUMP_DOWN",				},
		{ STATE_CHANGE_TYPE["SCT_MOTION_END"],				"GLITER_LANCE_GREAT_DASH_ATTACK",				},		
	},
}




GLITER_LANCE_GREAT_DASH_ATTACK =
{
	ANIM_NAME					= "DashAttack",
	PLAY_TYPE					= XSKIN_ANIM_PLAYTYPE["XAP_LOOP"],
	TRANSITION					= FALSE,
	LAND_CONNECT				= FALSE,
	
	CAN_PUSH_UNIT				= TRUE,
	CAN_PASS_UNIT				= FALSE,

	PASSIVE_SPEED_X				= 1000,

    SOUND_PLAY0			= { 0.140, "GlitterVoice_AttackRoar2.ogg" },
	
	ALLOW_DIR_CHANGE			= FALSE,
	IMMADIATE_PACKET_SEND		= TRUE,
	
	EVENT_INTERVAL_TIME0		= 0.1,
		
	EVENT_PROCESS = 
	{		
		{ STATE_CHANGE_TYPE["SCT_CONDITION_TABLE"],				"GLITER_LANCE_GREAT_DASH_END",	"CT_GLITER_LANCE_GREAT_DASH_END"		},
	},
		
	CT_GLITER_LANCE_GREAT_DASH_END = 
	{
		EVENT_INTERVAL_ID		= 0,	
		STATE_TIME_OVER			= 0.72,
	},
	
	
	ATTACK_TIME0				= { 0.01, 100, },
	
	DAMAGE_DATA = 
	{
		DAMAGE_TYPE		= DAMAGE_TYPE["DT_PHYSIC"],
		HIT_TYPE		= HIT_TYPE["HT_PUNCH_HIT"],
		REACT_TYPE		= REACT_TYPE["RT_DOWN"],
		
		DAMAGE = 
		{
			PHYSIC		= 1.0,
		},
		
		
		CAMERA_CRASH_GAP		= 5.0,	
		CAMERA_CRASH_TIME		= 0.2,	
		
		BACK_SPEED_X		= 1800,
		BACK_SPEED_Y		= 1200,
		CAN_REVENGE			= TRUE,	
		
	},
}



GLITER_LANCE_GREAT_JUMP_UP = 
{
	ANIM_NAME					= "JumpUp",
	PLAY_TYPE					= XSKIN_ANIM_PLAYTYPE["XAP_LOOP"],
	TRANSITION					= TRUE,
	LAND_CONNECT				= FALSE,
	
	CAN_PUSH_UNIT				= TRUE,
	CAN_PASS_UNIT				= FALSE,
	
	SPEED_X						= 0,
	SPEED_Y						= INIT_PHYSIC["JUMP_SPEED"],
	
	ADD_POS_Y					= 45, 
	
	IMMADIATE_PACKET_SEND		= TRUE,
	
	EVENT_PROCESS = 
	{		
		{ STATE_CHANGE_TYPE["SCT_NEGATIVE_Y_SPEED"],		"GLITER_LANCE_GREAT_JUMP_DOWN",			},
	},
	
}

GLITER_LANCE_GREAT_JUMP_DOWN = 
{
	ANIM_NAME					= "JumpDown",
	PLAY_TYPE					= XSKIN_ANIM_PLAYTYPE["XAP_LOOP"],
	TRANSITION					= TRUE,
	LAND_CONNECT				= FALSE,
	
	CAN_PUSH_UNIT				= TRUE,
	CAN_PASS_UNIT				= FALSE,
		 
	
	IMMADIATE_PACKET_SEND		= TRUE,
		
	EVENT_PROCESS = 
	{		
		{ STATE_CHANGE_TYPE["SCT_FOOT_ON_LINE_TRUE"],		"GLITER_LANCE_GREAT_JUMP_LANDING",				},
	},
}

GLITER_LANCE_GREAT_JUMP_UP_DIR = 
{
	ANIM_NAME					= "JumpUp",
	PLAY_TYPE					= XSKIN_ANIM_PLAYTYPE["XAP_LOOP"],
	TRANSITION					= TRUE,
	LAND_CONNECT				= FALSE,
	
	CAN_PUSH_UNIT				= TRUE,
	CAN_PASS_UNIT				= FALSE,
		
	PASSIVE_SPEED_X				= INIT_PHYSIC["WALK_SPEED"],
	SPEED_Y						= INIT_PHYSIC["JUMP_SPEED"],
	
	ADD_POS_Y					= 45, 
	
	IMMADIATE_PACKET_SEND		= TRUE,
	
	EVENT_PROCESS = 
	{		
		{ STATE_CHANGE_TYPE["SCT_NEGATIVE_Y_SPEED"],		"GLITER_LANCE_GREAT_JUMP_DOWN_DIR",				},
	},
	
}

GLITER_LANCE_GREAT_JUMP_DOWN_DIR = 
{
	ANIM_NAME					= "JumpDown",
	PLAY_TYPE					= XSKIN_ANIM_PLAYTYPE["XAP_LOOP"],
	TRANSITION					= TRUE,
	LAND_CONNECT				= FALSE,
	
	CAN_PUSH_UNIT				= TRUE,
	CAN_PASS_UNIT				= FALSE,
	
	PASSIVE_SPEED_X				= INIT_PHYSIC["WALK_SPEED"],
	 
	
	IMMADIATE_PACKET_SEND		= TRUE,
		
	EVENT_PROCESS = 
	{		
		{ STATE_CHANGE_TYPE["SCT_FOOT_ON_LINE_TRUE"],		"GLITER_LANCE_GREAT_JUMP_LANDING",				},
	},
}

GLITER_LANCE_GREAT_JUMP_LANDING = 
{
	ANIM_NAME					= "JumpLanding",
	PLAY_TYPE					= XSKIN_ANIM_PLAYTYPE["XAP_ONE_WAIT"],
	TRANSITION					= TRUE,
	LAND_CONNECT				= FALSE,
	
	CAN_PUSH_UNIT				= TRUE,
	CAN_PASS_UNIT				= FALSE,
	
    SOUND_PLAY0			= { 0.121, "Glitter_Landing.ogg" },

	SPEED_X						= 0,
	SPEED_Y						= 0,

	IMMADIATE_PACKET_SEND		= TRUE,

	EVENT_PROCESS = 
	{		
		{ STATE_CHANGE_TYPE["SCT_FOOT_ON_LINE_FALSE_DOWN"],	"GLITER_LANCE_GREAT_JUMP_DOWN",				},
		{ STATE_CHANGE_TYPE["SCT_MOTION_END"],				"GLITER_LANCE_GREAT_WAIT",						},
	},
}


GLITER_LANCE_GREAT_ATTACK = 
{
	ANIM_NAME					= "Attack",
	PLAY_TYPE					= XSKIN_ANIM_PLAYTYPE["XAP_ONE_WAIT"],
	TRANSITION					= FALSE,
	ANIM_MOVE					= FALSE,
	
	ANIM_SPEED					= 0.9,
	
	CAN_PUSH_UNIT				= TRUE,
	CAN_PASS_UNIT				= FALSE,

	SPEED_X						= 0,
	SPEED_Y						= 0,	

    SOUND_PLAY0			= { 0.706, "Glitter_Lance_Attack1.ogg" },
    SOUND_PLAY1			= { 0.704, "GlitterVoice_Attack2.ogg" },
    SOUND_PLAY2			= { 1.304, "Glitter_Lance_Attack2.ogg" },
	
	
	VIEW_TARGET					= TRUE,
	IMMADIATE_PACKET_SEND		= TRUE,
	
	EVENT_PROCESS = 
	{	
		{ STATE_CHANGE_TYPE["SCT_FOOT_ON_LINE_FALSE_DOWN"],	"GLITER_LANCE_GREAT_JUMP_DOWN",										},
		{ STATE_CHANGE_TYPE["SCT_CONDITION_TABLE"],			"GLITER_LANCE_GREAT_COMBO",			"CT_GLITER_LANCE_GREAT_COMBO",	},
		{ STATE_CHANGE_TYPE["SCT_MOTION_END"],				"GLITER_LANCE_GREAT_WAIT",												},	
	},

	ATTACK_TIME0				= { 0.66, 0.73, },
	ATTACK_TIME1				= { 1.3, 1.38, },
	
	CT_GLITER_LANCE_GREAT_COMBO = 
	{
		ANIM_EVENT_TIMER			= 1.5,
		ATTACK_SUCCESS				= TRUE,
		RATE					= 100,
	},
	
	DAMAGE_DATA = 
	{
		DAMAGE_TYPE		= DAMAGE_TYPE["DT_PHYSIC"],
		HIT_TYPE		= HIT_TYPE["HT_SWORD_SLASH"],
		REACT_TYPE		= REACT_TYPE["RT_SMALL_DAMAGE"],
		
		DAMAGE = 
		{
			PHYSIC		= 1,
		},
		
		BACK_SPEED_X			= 800,
		BACK_SPEED_Y			= 0.0,
		
		CAMERA_CRASH_GAP		= 5.0,	
		CAMERA_CRASH_TIME		= 0.2,		
		CAN_REVENGE			= TRUE,	
	},
	
	
	DAMAGE_DATA_LAST = 
	{
		DAMAGE_TYPE		= DAMAGE_TYPE["DT_PHYSIC"],
		HIT_TYPE		= HIT_TYPE["HT_SWORD_SLASH"],
		REACT_TYPE		= REACT_TYPE["RT_BIG_DAMAGE"],
		
		DAMAGE = 
		{
			PHYSIC		= 1,
		},
		
		BACK_SPEED_X			= 1200,
		BACK_SPEED_Y			= 0.0,
		
		CAMERA_CRASH_GAP		= 5.0,	
		CAMERA_CRASH_TIME		= 0.2,
		CAN_REVENGE			= TRUE,			
	},
}



GLITER_LANCE_GREAT_COMBO =
{
	ANIM_NAME					= "Combo",
	PLAY_TYPE					= XSKIN_ANIM_PLAYTYPE["XAP_ONE_WAIT"],
	TRANSITION					= FALSE,
	ANIM_MOVE					= FALSE,
	
	CAN_PUSH_UNIT				= TRUE,
	CAN_PASS_UNIT				= FALSE,


    SOUND_PLAY0			= { 0.812, "Glitter_Lance_Combo.ogg" },
   	SOUND_PLAY1			= { 0.855, "GlitterVoice_AttackRoar1.ogg" },
	
	VIEW_TARGET					= TRUE,
	IMMADIATE_PACKET_SEND		= TRUE,
		
	EVENT_PROCESS = 
	{		
		{ STATE_CHANGE_TYPE["SCT_FOOT_ON_LINE_FALSE_DOWN"],	"GLITER_LANCE_GREAT_JUMP_DOWN",			},
		{ STATE_CHANGE_TYPE["SCT_MOTION_END"],				"GLITER_LANCE_GREAT_WAIT",					},
	},
	
	
	ATTACK_TIME0				= { 0.83, 0.93, },
	
	DAMAGE_DATA = 
	{
		DAMAGE_TYPE		= DAMAGE_TYPE["DT_PHYSIC"],
		HIT_TYPE		= HIT_TYPE["HT_SWORD_SLASH"],
		REACT_TYPE		= REACT_TYPE["RT_DOWN"],
		
		DAMAGE = 
		{
			PHYSIC		= 1,
		},
		
		BACK_SPEED_X			= 600,
		BACK_SPEED_Y			= -2000,
		
		CAMERA_CRASH_GAP		= 10.0,	
		CAMERA_CRASH_TIME		= 0.2,		
		CAN_REVENGE			= TRUE,		
	},
}




GLITER_LANCE_GREAT_DAMAGE_REVENGE = 
{
	ANIM_NAME					= "DamageRevenge",
	PLAY_TYPE					= XSKIN_ANIM_PLAYTYPE["XAP_ONE_WAIT"],
	TRANSITION					= FALSE,
	LAND_CONNECT				= FALSE,
	
	CAN_PUSH_UNIT				= TRUE,
	CAN_PASS_UNIT				= FALSE,
	
	EVENT_PROCESS = 
	{
		{ STATE_CHANGE_TYPE["SCT_MOTION_END"],					"GLITER_LANCE_GREAT_WAIT",												},
	},
}


GLITER_LANCE_GREAT_DAMAGE_FRONT = 
{
	ANIM_NAME					= "DamageFront",
	PLAY_TYPE					= XSKIN_ANIM_PLAYTYPE["XAP_ONE_WAIT"],
	TRANSITION					= FALSE,
	LAND_CONNECT				= FALSE,
	
	CAN_PUSH_UNIT				= TRUE,
	CAN_PASS_UNIT				= FALSE,

    SOUND_PLAY0			= { 0.174, "GlitterVoice_HurtRoar1.ogg" , 24 },
	
	EVENT_PROCESS = 
	{
		{ STATE_CHANGE_TYPE["SCT_MOTION_END"],					"GLITER_LANCE_GREAT_WAIT",												},
	},
}

GLITER_LANCE_GREAT_DAMAGE_BACK = 
{
	ANIM_NAME					= "DamageBack",
	PLAY_TYPE					= XSKIN_ANIM_PLAYTYPE["XAP_ONE_WAIT"],
	TRANSITION					= FALSE,
	LAND_CONNECT				= FALSE,
	
	CAN_PUSH_UNIT				= TRUE,
	CAN_PASS_UNIT				= FALSE,


    SOUND_PLAY0			= { 0.160, "GlitterVoice_HurtRoar1.ogg" , 24 },
	
	EVENT_PROCESS = 
	{
		{ STATE_CHANGE_TYPE["SCT_MOTION_END"],					"GLITER_LANCE_GREAT_WAIT",												},
	},
}





GLITER_LANCE_GREAT_DAMAGE_DOWN_FRONT = 
{
	ANIM_NAME					= "DamageDownFront",
	PLAY_TYPE					= XSKIN_ANIM_PLAYTYPE["XAP_ONE_WAIT"],
	TRANSITION					= FALSE,
	LAND_CONNECT				= FALSE,

	SUPER_ARMOR					= TRUE,
	DEFENCE						= { 0, 100, 70, },

    SOUND_PLAY0			= { 0.172, "GlitterVoice_HurtRoar1.ogg" , 24 },
	
	CAN_PUSH_UNIT				= TRUE,
	CAN_PASS_UNIT				= FALSE,

	
	EVENT_PROCESS = 
	{
		{ STATE_CHANGE_TYPE["SCT_FOOT_ON_LINE_FALSE_DOWN"],		"GLITER_LANCE_GREAT_DAMAGE_AIR_FALL",			},
		{ STATE_CHANGE_TYPE["SCT_MOTION_END"],					"GLITER_LANCE_GREAT_STAND_UP_FRONT",			},
	},
	
}

GLITER_LANCE_GREAT_DAMAGE_DOWN_BACK = 
{
	ANIM_NAME					= "DamageDownBack",
	PLAY_TYPE					= XSKIN_ANIM_PLAYTYPE["XAP_ONE_WAIT"],
	TRANSITION					= FALSE,
	LAND_CONNECT				= FALSE,
	
	SUPER_ARMOR					= TRUE,
	DEFENCE						= { 0, 100, 70, },

    SOUND_PLAY0			= { 0.357, "GlitterVoice_HurtRoar1.ogg" , 24 },
	
	CAN_PUSH_UNIT				= TRUE,
	CAN_PASS_UNIT				= FALSE,
	
	EVENT_PROCESS = 
	{
		{ STATE_CHANGE_TYPE["SCT_FOOT_ON_LINE_FALSE_DOWN"],		"GLITER_LANCE_GREAT_DAMAGE_AIR_FALL",			},
		{ STATE_CHANGE_TYPE["SCT_MOTION_END"],					"GLITER_LANCE_GREAT_STAND_UP_BACK",			},
	},
	
}

GLITER_LANCE_GREAT_DAMAGE_FLY_FRONT = 
{
	ANIM_NAME					= "DamageAirFlyFront",
	PLAY_TYPE					= XSKIN_ANIM_PLAYTYPE["XAP_ONE_WAIT"],
	TRANSITION					= TRUE,
	LAND_CONNECT				= FALSE,	
	
	
	
	CAN_PUSH_UNIT				= TRUE,
	CAN_PASS_UNIT				= FALSE,
	
	EVENT_PROCESS = 
	{
		{ STATE_CHANGE_TYPE["SCT_FOOT_ON_LINE_TRUE"],			"GLITER_LANCE_GREAT_DAMAGE_AIR_DOWN_LANDING",		},
	},
}

GLITER_LANCE_GREAT_DAMAGE_FLY_BACK = 
{
	ANIM_NAME					= "DamageAirFlyBack",
	PLAY_TYPE					= XSKIN_ANIM_PLAYTYPE["XAP_ONE_WAIT"],
	TRANSITION					= FALSE,
	LAND_CONNECT				= FALSE,	
	
	CAN_PUSH_UNIT				= TRUE,
	CAN_PASS_UNIT				= FALSE,
	
	EVENT_PROCESS = 
	{
		{ STATE_CHANGE_TYPE["SCT_FOOT_ON_LINE_TRUE"],			"GLITER_LANCE_GREAT_DAMAGE_DOWN_BACK",		},
	},
}

GLITER_LANCE_GREAT_DAMAGE_AIR = 
{
	ANIM_NAME					= "DamageAirSmall",
	PLAY_TYPE					= XSKIN_ANIM_PLAYTYPE["XAP_ONE_WAIT"],
	TRANSITION					= FALSE,
	LAND_CONNECT				= FALSE,
	
	CAN_PUSH_UNIT				= TRUE,
	CAN_PASS_UNIT				= FALSE,
	
	EVENT_PROCESS = 
	{
		{ STATE_CHANGE_TYPE["SCT_FOOT_ON_LINE_TRUE"],			"GLITER_LANCE_GREAT_WAIT",					},
	},
	
	VIEW_TARGET					= TRUE,
	ALLOW_DIR_CHANGE			= TRUE,

	
	
	ATTACK_TIME0				= { 0.15, 0.24, },
	
	DAMAGE_DATA = 
	{
		DAMAGE_TYPE		= DAMAGE_TYPE["DT_PHYSIC"],
		HIT_TYPE		= HIT_TYPE["HT_PUNCH_HIT"],
		REACT_TYPE		= REACT_TYPE["RT_FLY"],
		
		DAMAGE = 
		{
			PHYSIC		= 1.0,
		},
		
		
		CAMERA_CRASH_GAP		= 10.0,	
		CAMERA_CRASH_TIME		= 0.2,	
		
		BACK_SPEED_X		= 1500,
		BACK_SPEED_Y		= -1000,
		
	},
	
}

GLITER_LANCE_GREAT_DAMAGE_AIR_DOWN = 
{
	ANIM_NAME					= "DamageAirDown",
	PLAY_TYPE					= XSKIN_ANIM_PLAYTYPE["XAP_ONE_WAIT"],
	TRANSITION					= FALSE,
	LAND_CONNECT				= FALSE,
	
	CAN_PUSH_UNIT				= TRUE,
	CAN_PASS_UNIT				= FALSE,
	
	EVENT_PROCESS = 
	{
		{ STATE_CHANGE_TYPE["SCT_FOOT_ON_LINE_TRUE"],			"GLITER_LANCE_GREAT_DAMAGE_AIR_DOWN_LANDING",	},
	},
}

GLITER_LANCE_GREAT_DAMAGE_AIR_UP = 
{
	ANIM_NAME					= "DamageAirUp",
	PLAY_TYPE					= XSKIN_ANIM_PLAYTYPE["XAP_ONE_WAIT"],
	TRANSITION					= FALSE,
	LAND_CONNECT				= FALSE,
	
	CAN_PUSH_UNIT				= TRUE,
	CAN_PASS_UNIT				= FALSE,
	
		
	EVENT_PROCESS = 
	{
		{ STATE_CHANGE_TYPE["SCT_NEGATIVE_Y_SPEED"],		"GLITER_LANCE_GREAT_DAMAGE_AIR_FALL",			},
		{ STATE_CHANGE_TYPE["SCT_FOOT_ON_LINE_TRUE"],		"GLITER_LANCE_GREAT_DAMAGE_AIR_DOWN_LANDING",	},
	},
}

GLITER_LANCE_GREAT_DAMAGE_AIR_FALL = 
{
	ANIM_NAME					= "DamageAirFall",
	PLAY_TYPE					= XSKIN_ANIM_PLAYTYPE["XAP_ONE_WAIT"],
	TRANSITION					= FALSE,
	LAND_CONNECT				= FALSE,
	
	CAN_PUSH_UNIT				= TRUE,
	CAN_PASS_UNIT				= FALSE,
	
	EVENT_PROCESS = 
	{
		{ STATE_CHANGE_TYPE["SCT_POSITIVE_Y_SPEED"],		"GLITER_LANCE_GREAT_DAMAGE_AIR_UP",			},
		{ STATE_CHANGE_TYPE["SCT_FOOT_ON_LINE_TRUE"],		"GLITER_LANCE_GREAT_DAMAGE_AIR_DOWN_LANDING",	},
	},
}

GLITER_LANCE_GREAT_DAMAGE_AIR_DOWN_LANDING = 
{
	ANIM_NAME					= "DamageAirDownLanding",
	PLAY_TYPE					= XSKIN_ANIM_PLAYTYPE["XAP_ONE_WAIT"],
	TRANSITION					= FALSE,
	LAND_CONNECT				= FALSE,
	
	SUPER_ARMOR					= TRUE,
	DEFENCE						= { 0, 100, 70, },
	
	CAN_PUSH_UNIT				= TRUE,
	CAN_PASS_UNIT				= FALSE,
	
	EVENT_PROCESS = 
	{
		{ STATE_CHANGE_TYPE["SCT_FOOT_ON_LINE_FALSE_DOWN"],	"GLITER_LANCE_GREAT_DAMAGE_AIR_FALL",			},
		{ STATE_CHANGE_TYPE["SCT_MOTION_END"],				"GLITER_LANCE_GREAT_STAND_UP_FRONT",			},
	},
	
}

GLITER_LANCE_GREAT_STAND_UP_FRONT = 
{
	ANIM_NAME					= "DamageStandUpFront",
	PLAY_TYPE					= XSKIN_ANIM_PLAYTYPE["XAP_ONE_WAIT"],
	TRANSITION					= FALSE,
	LAND_CONNECT				= FALSE,	
	
	SUPER_ARMOR					= TRUE,
	DEFENCE						= { 0, 100, 70, },
	
	CAN_PUSH_UNIT				= TRUE,
	CAN_PASS_UNIT				= FALSE,
	
	EVENT_PROCESS = 
	{
		{ STATE_CHANGE_TYPE["SCT_FOOT_ON_LINE_FALSE_DOWN"],	"GLITER_LANCE_GREAT_JUMP_DOWN",			},
		{ STATE_CHANGE_TYPE["SCT_MOTION_END"],				"GLITER_LANCE_GREAT_WAIT",				},
	},
}

GLITER_LANCE_GREAT_STAND_UP_BACK = 
{
	ANIM_NAME					= "DamageStandUpBack",
	PLAY_TYPE					= XSKIN_ANIM_PLAYTYPE["XAP_ONE_WAIT"],
	TRANSITION					= FALSE,
	LAND_CONNECT				= FALSE,
	
	SUPER_ARMOR					= TRUE,
	DEFENCE						= { 0, 100, 70, },

    SOUND_PLAY0			= { 0.283, "Glitter_StandUp.ogg" },
	
	CAN_PUSH_UNIT				= TRUE,
	CAN_PASS_UNIT				= FALSE,
		
	EVENT_PROCESS = 
	{
		{ STATE_CHANGE_TYPE["SCT_FOOT_ON_LINE_FALSE_DOWN"],	"GLITER_LANCE_GREAT_JUMP_DOWN", },
		{ STATE_CHANGE_TYPE["SCT_MOTION_END"],				"GLITER_LANCE_GREAT_WAIT", },
	},		
}



GLITER_LANCE_GREAT_DYING_LAND_FRONT = 
{
	ANIM_NAME					= "DamageDownFront",
	PLAY_TYPE					= XSKIN_ANIM_PLAYTYPE["XAP_ONE_WAIT"],
	TRANSITION					= FALSE,
	LAND_CONNECT				= FALSE,

	INVINCIBLE					= { 0, 100, }, 		
	
	CAN_PUSH_UNIT				= FALSE,
	CAN_PASS_UNIT				= TRUE,

    SOUND_PLAY0			= { 0.175, "GlitterVoice_DeathRoar.ogg" },
	
	DYING_END					= TRUE,
	
	IMMADIATE_PACKET_SEND		= TRUE,
}
	
GLITER_LANCE_GREAT_DYING_LAND_BACK = 
{
	ANIM_NAME					= "DamageDownBack",
	PLAY_TYPE					= XSKIN_ANIM_PLAYTYPE["XAP_ONE_WAIT"],
	TRANSITION					= FALSE,
	LAND_CONNECT				= FALSE,
	
	INVINCIBLE					= { 0, 100, }, 		

    SOUND_PLAY0			= { 0.399, "GlitterVoice_DeathRoar.ogg" },
	
	CAN_PUSH_UNIT				= FALSE,
	CAN_PASS_UNIT				= TRUE,
	
	DYING_END					= TRUE,	
	
	IMMADIATE_PACKET_SEND		= TRUE,
}

GLITER_LANCE_GREAT_DYING_SKY = 
{
	ANIM_NAME					= "DamageAirDownLanding",
	PLAY_TYPE					= XSKIN_ANIM_PLAYTYPE["XAP_ONE_WAIT"],
	TRANSITION					= FALSE,
	LAND_CONNECT				= FALSE,
	
	INVINCIBLE					= { 0, 100, }, 		

    SOUND_PLAY0			= { 0.105, "GlitterVoice_DeathRoar.ogg" },
	
	CAN_PUSH_UNIT				= FALSE,
	CAN_PASS_UNIT				= TRUE,
	
	DYING_END					= TRUE,
	
	IMMADIATE_PACKET_SEND		= TRUE,
}




-- GROUP AI -----------------------------------------------------------------------




--------------------------------------------------------------------
--------------------------------------------------------------------

function GLITER_LANCE_GREAT_WALK_STATE_END( pKTDXApp, pX2Game, pNPCUnit )

	pMinorParticle = pX2Game:GetMinorParticle()
	pMinorParticle:GameUnitCreateSequence_LUA( pNPCUnit, "StepSmoke", pNPCUnit:GetLandPosition_LUA(), D3DXVECTOR2(100,100), D3DXVECTOR2(5,-1) )

end



function GLITER_LANCE_GREAT_JUMP_DOWN_STATE_END( pKTDXApp, pX2Game, pNPCUnit )

	pMinorParticle = pX2Game:GetMinorParticle()
	pMinorParticle:GameUnitCreateSequence_LUA( pNPCUnit, "StepSmoke", pNPCUnit:GetLandPosition_LUA(), D3DXVECTOR2(100,100), D3DXVECTOR2(5,-1) )

end

function GLITER_LANCE_GREAT_JUMP_DOWN_DIR_STATE_END( pKTDXApp, pX2Game, pNPCUnit )

	pMinorParticle = pX2Game:GetMinorParticle()
	pMinorParticle:GameUnitCreateSequence_LUA( pNPCUnit, "StepSmoke", pNPCUnit:GetLandPosition_LUA(), D3DXVECTOR2(100,100), D3DXVECTOR2(5,-1) )

end



function GLITER_LANCE_GREAT_ATTACK_FRAME_MOVE( pKTDXApp, pX2Game, pNPCUnit )
	
	if pNPCUnit:AnimEventTimer_LUA( 1.0 ) then
		pNPCUnit:ClearHitUnitList_LUA()
		pNPCUnit:SetDamageData_LUA( "DAMAGE_DATA_LAST" )
		pNPCUnit:SetSpeedX( INIT_PHYSIC["RUN_SPEED"] )
	end

end



function GLITER_LANCE_GREAT_DAMAGE_FRONT_FRAME_MOVE( pKTDXApp, pX2Game, pNPCUnit )

	if pNPCUnit:AnimEventTimer_LUA( 0.047 ) then
		pMinorParticle = pX2Game:GetMinorParticle()
		pMinorParticle:GameUnitCreateSequence_LUA( pNPCUnit, "StepSmoke", pNPCUnit:GetLandPosition_LUA(), D3DXVECTOR2(100,100), D3DXVECTOR2(5,-1) )
	end

end

function GLITER_LANCE_GREAT_DAMAGE_BACK_FRAME_MOVE( pKTDXApp, pX2Game, pNPCUnit )

	if pNPCUnit:AnimEventTimer_LUA( 0.06 ) then
		pMinorParticle = pX2Game:GetMinorParticle()
		pMinorParticle:GameUnitCreateSequence_LUA( pNPCUnit, "StepSmoke", pNPCUnit:GetLandPosition_LUA(), D3DXVECTOR2(100,100), D3DXVECTOR2(5,-1) )
	end

end

function GLITER_LANCE_GREAT_DAMAGE_DOWN_FRONT_FRAME_MOVE( pKTDXApp, pX2Game, pNPCUnit )

	if pNPCUnit:AnimEventTimer_LUA( 0.41 ) then
		pNPCUnit:PlaySound_LUA( "Down.ogg" )		
		pMinorParticle = pX2Game:GetMinorParticle()
		pMinorParticle:GameUnitCreateSequence_LUA( pNPCUnit, "DownSmoke", pNPCUnit:GetLandPosition_LUA(), D3DXVECTOR2(100,100), D3DXVECTOR2(7,-1) )
	end

end

function GLITER_LANCE_GREAT_DAMAGE_DOWN_BACK_FRAME_MOVE( pKTDXApp, pX2Game, pNPCUnit )

	if pNPCUnit:AnimEventTimer_LUA( 0.45 ) then
		pNPCUnit:PlaySound_LUA( "Down.ogg" )		
		pMinorParticle = pX2Game:GetMinorParticle()
		pMinorParticle:GameUnitCreateSequence_LUA( pNPCUnit, "DownSmoke", pNPCUnit:GetLandPosition_LUA(), D3DXVECTOR2(100,100), D3DXVECTOR2(7,-1) )
	end

end

function GLITER_LANCE_GREAT_DAMAGE_AIR_DOWN_LANDING_FRAME_MOVE( pKTDXApp, pX2Game, pNPCUnit )

	if pNPCUnit:AnimEventTimer_LUA( 0.01 ) then
		
		pMinorParticle = pX2Game:GetMinorParticle()
		pos = pNPCUnit:GetLandPosition_LUA()
		pMinorParticle:GameUnitCreateSequence_LUA( pNPCUnit, "DownSmoke", pos, D3DXVECTOR2(100,100), D3DXVECTOR2(7,-1) )
		pos.y = pos.y + 5
		pMinorParticle:GameUnitCreateSequence_LUA( pNPCUnit, "GroundShockWave", pos, D3DXVECTOR2(100,100), D3DXVECTOR2(1,-1) )
		pParticle = pMinorParticle:GameUnitCreateSequence_LUA( pNPCUnit, "AirDownTick", pNPCUnit:GetPos(), D3DXVECTOR2(200,200), D3DXVECTOR2(10,-1) )
		if pParticle ~= nil then 
			pParticle:SetLandPosition( pos.y - 5 )
		end
		
		if GetDistance_LUA( pNPCUnit:GetPos(), pX2Game:GetFocusUnitPos_LUA() ) < 500 then
			pX2Game:GetX2Camera():GetCamera():UpDownCrashCameraNoReset( 10.0, 0.1 )
		end		
		
	elseif pNPCUnit:AnimEventTimer_LUA( 0.1 ) then
		
		pNPCUnit:PlaySound_LUA( "Down.ogg" )		
		pMinorParticle = pX2Game:GetMinorParticle()
		pMinorParticle:GameUnitCreateSequence_LUA( pNPCUnit, "DownSmoke", pNPCUnit:GetLandPosition_LUA(), D3DXVECTOR2(100,100), D3DXVECTOR2(7,-1) )
		
	end

end







function GLITER_LANCE_GREAT_DYING_LAND_STATE_START( pKTDXApp, pX2Game, pNPCUnit )

	pos = pNPCUnit:GetPos()
	pos.y = pos.y + 100.0
	GetMinorParticle = pX2Game:GetMinorParticle()
	
	pSeq = GetMinorParticle:GameUnitCreateSequence_LUA( pNPCUnit, "DieLight",		pos, D3DXVECTOR2(-1,-1), D3DXVECTOR2(3,-1) )
	if pSeq ~= nil then
	
		pSeq:SetLandPosition( pNPCUnit:GetLandPosition_LUA().y )
		pNPCUnit:SetDieSeq( pSeq:GetHandle() )
	
	end
	pNPCUnit:PlaySound_LUA( "DieLight.ogg" )
	
end






--------------------------------------------------------------------
function GLITER_LANCE_GREAT_COMBO_FRAME_MOVE( pKTDXApp, pX2Game, pNPCUnit )

    if pNPCUnit:AnimEventTimer_LUA( 0.94 ) then
      	
      	pMinorParticle = pX2Game:GetMinorParticle()
		pos = pNPCUnit:GetLandPosition_LUA()
		
		vDirVector		= pNPCUnit:GetDirVector()
		bIsRight		= pNPCUnit:GetIsRight()
		
		
		if bIsRight == true then 
			pos = MovePos( pos, vDirVector, 270 )
		else
			pos = MovePos( pos, vDirVector, -270 )
		end
		
		
		pMinorParticle:GameUnitCreateSequence_LUA( pNPCUnit, "DownSmoke", pos, D3DXVECTOR2(100,100), D3DXVECTOR2(7,-1) )
		pos.y = pos.y + 5
		pMinorParticle:GameUnitCreateSequence_LUA( pNPCUnit, "GroundShockWave", pos, D3DXVECTOR2(100,100), D3DXVECTOR2(1,-1) )

		
		if GetDistance_LUA( pNPCUnit:GetPos(), pX2Game:GetFocusUnitPos_LUA() ) < 800 then
			pX2Game:GetX2Camera():GetCamera():UpDownCrashCameraNoReset( 15.0, 0.2 )
		end		
        
    end
    
end






--------------------------------------------------------------------
function GLITER_LANCE_GREAT_DASH_ATTACK_FRAME_MOVE( pKTDXApp, pX2Game, pNPCUnit )

    if pNPCUnit:AnimEventTimer_LUA( 0.15 ) then
        pMinorParticle = pX2Game:GetMinorParticle()
        if pMinorParticle ~= nil then
	        pMinorParticle:GameUnitCreateSequence_LUA( pNPCUnit, "StepSmoke", pNPCUnit:GetLandPosition_LUA(), D3DXVECTOR2(100,100), D3DXVECTOR2(5,-1) )
        end
        
		if GetDistance_LUA( pNPCUnit:GetPos(), pX2Game:GetFocusUnitPos_LUA() ) < 800 then
			pX2Game:GetX2Camera():GetCamera():UpDownCrashCameraNoReset( 10.0, 0.2 )
		end		
        
    end
    
    if pNPCUnit:AnimEventTimer_LUA( 0.35 ) then
        pMinorParticle = pX2Game:GetMinorParticle()
        if pMinorParticle ~= nil then
	        pMinorParticle:GameUnitCreateSequence_LUA( pNPCUnit, "StepSmoke", pNPCUnit:GetLandPosition_LUA(), D3DXVECTOR2(100,100), D3DXVECTOR2(5,-1) )
        end	        

		if GetDistance_LUA( pNPCUnit:GetPos(), pX2Game:GetFocusUnitPos_LUA() ) < 800 then
			pX2Game:GetX2Camera():GetCamera():UpDownCrashCameraNoReset( 10.0, 0.2 )
		end		
        
    end
    
end






function GLITER_LANCE_GREAT_DASH_ATTACK_READY_STATE_END( pKTDXApp, pX2Game, pNPCUnit )

	pNPCUnit:SetGroupAISelfCommandTransit_LUA( true )
end




------------------------------------------------------------------------------
function MovePos( pos, dirvector, dist )
	
	pos.x = pos.x + dist * dirvector.x
	pos.y = pos.y + dist * dirvector.y
	pos.z = pos.z + dist * dirvector.z
	
	return pos
	
end



function GLITER_LANCE_GREAT_SELF_COMMAND_TRANSIT_STATE_START( pKTDXApp, pX2Game, pNPCUnit )

	--pNPCUnit:SetPrevAIMessage_LUA( STATE_CHANGE_TYPE["SCT_NO_CHANGE"] )

	if pNPCUnit:GetGroupAICommand_LUA() == GROUP_AI_COMMAND["GAI_CMD_FORCED_MOVE"] then
		
		pUnit = pNPCUnit:GetOnlyConsultedNPC_LUA( NPC_UNIT_ID["NUI_GLITER_COMMANDER"] )
		if pUnit == nil then
			return
		end		

		if pUnit:GetFlag_LUA(6) == true or pUnit:GetFlag_LUA(7) == true or pUnit:GetFlag_LUA(8) == true or pUnit:GetFlag_LUA(9) == true then
			local pUserUnit = pX2Game:GetNearestUserUnit_LUA( pNPCUnit:GetPos() )

			if pUserUnit ~= nil then
				pNPCUnit:COMMAND_ATTACK_MOVE_LUA( pUserUnit ) 
			end
			return
		else			
			local pUserUnit = pX2Game:GetNearestUserUnit_LUA( pNPCUnit:GetPos() )

			if pUserUnit ~= nil then
				pNPCUnit:COMMAND_SKILL_LUA( GROUP_AI_COMMAND["GAI_CMD_SKILL_C"], pUserUnit ) 
			end
			return		
		end
	end

	if pNPCUnit:GetGroupAICommand_LUA() == GROUP_AI_COMMAND["GAI_CMD_SKILL_A"] then

		local pUserUnit = pX2Game:GetNearestUserUnit_LUA( pNPCUnit:GetPos() )

		if pUserUnit ~= nil then
			pNPCUnit:COMMAND_ATTACK_MOVE_LUA( pUserUnit ) 
		end
		return
	end

end

