-- lua header. UTF-8 인코딩 인식을 위해 이 줄은 지우지 마세요.

INIT_SYSTEM = 
{
	UNIT_WIDTH		= 150.0,
	UNIT_HEIGHT		= 200.0,
	UNIT_LAYER		= X2_LAYER["XL_UNIT_0"],
	
	UNIT_SCALE      = 2.3,	
	APPLY_EFFECTSET_SCALE = TRUE, --거인 소인 되었을때 이펙트 크기도 변하게 하는 옵션 

}


INIT_DEVICE = 
{
	READY_TEXTURE = 
	{		
	},
	
	READY_SOUND = 
	{

     "Glitter_Necromancer_AttackReady.ogg",
     "Glitter_Necromancer_AttackShot.ogg",
     "Glitter_Necromancer_DarkCloudReady.ogg",
	 "Glitter_Landing.ogg",
	 "GlitterNecroVoice_AttackRoar1.ogg",
	 "GlitterNecroVoice_AttackRoar2.ogg",
	 
	 "Hoakin_Voice_Dying01.ogg",
	 "GlitterNecroVoice_HurtRoar2.ogg",
	 "GlitterNecroVoice_Laugh.ogg",

     "Gliter_Alchemyst_AttackBComboCloud.ogg",
	 "Gliter_Alchemyst_SlashStick.ogg",
     "Gliter_Alchemyst_DrinkPotion.ogg",
	 
	 "ALCHEMYST_SECRET_MagicAttack_B01.ogg",
	 "ALCHEMYST_SECRET_MagicAttack_B02.ogg",
	 "ALCHEMYST_SECRET_MagicAttack_C01.ogg",
	 "ALCHEMYST_SECRET_MagicAttack_C02.ogg",
	 "ALCHEMYST_SECRET_MagicAttack_E01.ogg",
	 "ALCHEMYST_SECRET_MagicAttackC_CcomboStart_01.ogg",
	 "ALCHEMYST_SECRET_MagicAttackC_CcomboEnd_01.ogg",
	 "Huge_Swing01.ogg",
	 "ALCHEMYST_SECRET_SpecialAttackD01.ogg",
	 "Hoakin_Voice_WaitStart01.ogg",
	 "Hoakin_Voice_HurtRoar01.ogg",
	 "Hoakin_Voice_HurtRoar02.ogg",
	 "Hoakin_Voice_Roar01.ogg",
	 "Hoakin_Voice_Roar02.ogg",
	 "Hoakin_Voice_Roar03.ogg",
	 "Hoakin_Voice_Roar04.ogg",
	 "Hoakin_Voice_Stage03_SummonA01.ogg",
	 "Hoakin_Voice_SpeacialAttackA01.ogg",
	 "ALCHEMYST_GREAT_BOSS_Stage1_WaitStart01.ogg",
    },
	
		
	READY_XMESH = 
	{
	},
	
	READY_XSKIN_MESH = 
	{
		"Motion_GLITER_TOMBSTONE.x",
		"NUI_VELDER_WRECK1.x",
		"NUI_VELDER_WRECK2.x",
		"NUI_VELDER_WRECK3.x",
		"NUI_VELDER_WRECK4.x",
		"NUI_VELDER_WRECK5.x",
		"Motion_CRAZY_PUPPET_SMALL_TRUE.x",
	},
}

INIT_MOTION = 
{
	MOTION_FILE_NAME		= "Motion_GLITER_ALCHEMYST_BOSS.x",	
	MOTION_CHANGE_TEX_XET	= "NUI_GLITER_ALCHEMYST_GREAT_BOSS_STAGE0.xet",
	MOTION_ANI_TEX_XET		= "NUI_GLITER_ALCHEMYST_GREAT_BOSS_STAGE0.xet",
}

INIT_PHYSIC = 
{
	RELOAD_ACCEL		= 2000,
	G_ACCEL				= 4000,
	MAX_G_SPEED			= -2000,
	
	WALK_SPEED			= 350,
	RUN_SPEED			= 450,
	JUMP_SPEED			= 1500,
	DASH_JUMP_SPEED		= 1500,
}



INIT_COMPONENT =
{
	IMMUNITY_TIME_STOP = TRUE,
	MAX_HP               = 30000,
	OUT_LINE_WIDTH_SCALE = 0.3,
	MP_CHANGE_RATE		 = 1,
	MP_CHARGE_RATE		 = 130,
	
	USE_SLASH_TRACE		= FALSE,
	
	SHADOW_SIZE			= 200,
	SHADOW_FILE_NAME	= "shadow.dds",
	
	SMALL_HP_BAR_BLUE	= "Small_HP_bar_Blue.TGA",
	SMALL_HP_BAR_RED	= "Small_HP_bar_Red.TGA",
	SMALL_HP_BAR_YELLOW = "Small_HP_bar_Yellow.TGA",
	
	QUESTION_MARK_SEQ		= "QuestionMarkNPC",
	EXCLAMATION_MARK_SEQ	= "ExclamationMarkNPC",
	--MIND_FLAG_HEIGHT		= 230,
	
    BOSS_GAGE_FACE_TEX			= "DLG_BossState.tga",
	BOSS_GAGE_FACE_TEX_PIECE	= "NUI_HOAKIN",
	BOSS_NAME_TEX				= "HQ_BOSS_NAME_HOAKIN.DDS",
	
	HYPER_MODE_COUNT	= 0,
	MAX_HYPER_MODE_TIME	= 30,

	RAGE_COUNT_MAX		= 30,
	RAGE_TIME_MAX		= 3,
	
	HITTED_TYPE			= HITTED_TYPE["HTD_MEAT"],
	
	FALL_DOWN			= FALSE,

	NOT_CULL  = TRUE,
	DIE_FLY				= 0,
}


INIT_STATE = 
{
	{ STATE_NAME = "GLITER_ALCHEMYST_SECRET_BOSS_START",						},
	{ STATE_NAME = "GLITER_ALCHEMYST_SECRET_BOSS_WAIT",							},
	{ STATE_NAME = "GLITER_ALCHEMYST_SECRET_BOSS_WAITHABIT",					},

	{ STATE_NAME = "GLITER_ALCHEMYST_SECRET_BOSS_WALK",							},
	{ STATE_NAME = "GLITER_ALCHEMYST_SECRET_BOSS_DASH",							LUA_STATE_END_FUNC = "GLITER_ALCHEMYST_SECRET_BOSS_DASH_STATE_END"						},
	{ STATE_NAME = "GLITER_ALCHEMYST_SECRET_BOSS_JUMP_UP",						},
	{ STATE_NAME = "GLITER_ALCHEMYST_SECRET_BOSS_JUMP_DOWN",					},
	{ STATE_NAME = "GLITER_ALCHEMYST_SECRET_BOSS_JUMP_UP_DIR",					},
	{ STATE_NAME = "GLITER_ALCHEMYST_SECRET_BOSS_JUMP_DOWN_DIR",				},
	{ STATE_NAME = "GLITER_ALCHEMYST_SECRET_BOSS_JUMP_LANDING",					LUA_STATE_START_FUNC = "GLITER_ALCHEMYST_SECRET_BOSS_JUMP_LANDING_STATE_START", },
 	{ STATE_NAME = "GLITER_ALCHEMYST_SECRET_BOSS_DASH_JUMP_UP_DIR",				},
	{ STATE_NAME = "GLITER_ALCHEMYST_SECRET_BOSS_DASH_JUMP_DOWN_DIR",			},
		
	{ STATE_NAME = "GLITER_ALCHEMYST_SECRET_BOSS_MAGIC_ATTACK_A",				LUA_FRAME_MOVE_FUNC = "GLITER_ALCHEMYST_SECRET_BOSS_MAGIC_ATTACK_A_FRAME_MOVE",	STATE_COOL_TIME = 5, },
	{ STATE_NAME = "GLITER_ALCHEMYST_SECRET_BOSS_MAGIC_ATTACK_B",				LUA_FRAME_MOVE_FUNC = "GLITER_ALCHEMYST_SECRET_BOSS_MAGIC_ATTACK_B_FRAME_MOVE",	STATE_COOL_TIME = 5, },
	{ STATE_NAME = "GLITER_ALCHEMYST_SECRET_BOSS_MAGIC_ATTACK_C",				LUA_STATE_START_FUNC = "GLITER_ALCHEMYST_SECRET_BOSS_MAGIC_ATTACK_C_STATE_START", STATE_COOL_TIME = 10,	},
	{ STATE_NAME = "GLITER_ALCHEMYST_SECRET_BOSS_MAGIC_ATTACK_D",				},
	{ STATE_NAME = "GLITER_ALCHEMYST_SECRET_BOSS_MAGIC_ATTACK_C_COMBO",			LUA_FRAME_MOVE_FUNC = "GLITER_ALCHEMYST_SECRET_BOSS_MAGIC_ATTACK_C_COMBO_FRAME_MOVE",	},
	{ STATE_NAME = "GLITER_ALCHEMYST_SECRET_BOSS_MAGIC_ATTACK_C_END",			LUA_STATE_START_FUNC = "GLITER_ALCHEMYST_SECRET_BOSS_MAGIC_ATTACK_C_END_STATE_START",	},	
	{ STATE_NAME = "GLITER_ALCHEMYST_SECRET_BOSS_MAGIC_ATTACK_E",				LUA_FRAME_MOVE_FUNC = "GLITER_ALCHEMYST_SECRET_BOSS_MAGIC_ATTACK_E_FRAME_MOVE",			STATE_COOL_TIME = 90,	},
		
	{ STATE_NAME = "GLITER_ALCHEMYST_SECRET_BOSS_SPECIAL_ATTACK_A",				LUA_STATE_START_FUNC = "GLITER_ALCHEMYST_SECRET_BOSS_SPECIAL_ATTACK_A_STATE_START",
																				LUA_FRAME_MOVE_FUNC = "GLITER_ALCHEMYST_SECRET_BOSS_SPECIAL_ATTACK_A_FRAME_MOVE",		STATE_COOL_TIME = 10, },
	{ STATE_NAME = "GLITER_ALCHEMYST_SECRET_BOSS_SPECIAL_ATTACK_B",				LUA_FRAME_MOVE_FUNC = "GLITER_ALCHEMYST_SECRET_BOSS_SPECIAL_ATTACK_B_FRAME_MOVE",		STATE_COOL_TIME = 100, },
	{ STATE_NAME = "GLITER_ALCHEMYST_SECRET_BOSS_SPECIAL_ATTACK_C",				LUA_FRAME_MOVE_FUNC = "GLITER_ALCHEMYST_SECRET_BOSS_SPECIAL_ATTACK_C_FRAME_MOVE",		STATE_COOL_TIME = 50,	},
	{ STATE_NAME = "GLITER_ALCHEMYST_SECRET_BOSS_REAL_SPECIAL_ATTACK",			LUA_STATE_START_FUNC = "GLITER_ALCHEMYST_SECRET_BOSS_REAL_SPECIAL_ATTACK_STATE_START",
																				LUA_FRAME_MOVE_FUNC = "GLITER_ALCHEMYST_SECRET_BOSS_REAL_SPECIAL_ATTACK_FRAME_MOVE",	STATE_COOL_TIME = 60, },

	{ STATE_NAME = "GLITER_ALCHEMYST_SECRET_BOSS_DRINK_POTION",					LUA_FRAME_MOVE_FUNC = "GLITER_ALCHEMYST_SECRET_BOSS_DRINK_POTION_FRAME_MOVE",			STATE_COOL_TIME = 10, },
	{ STATE_NAME = "GLITER_ALCHEMYST_SECRET_BOSS_DRINK_POTION_COMBO",			LUA_FRAME_MOVE_FUNC = "GLITER_ALCHEMYST_SECRET_BOSS_DRINK_POTION_COMBO_FRAME_MOVE",	},

	--리액션 관련
	{ STATE_NAME = "GLITER_ALCHEMYST_SECRET_BOSS_DAMAGE_BACK",					LUA_FRAME_MOVE_FUNC = "GLITER_ALCHEMYST_SECRET_BOSS_DAMAGE_BACK_FRAME_MOVE",	},
	{ STATE_NAME = "GLITER_ALCHEMYST_SECRET_BOSS_DAMAGE_FRONT",					LUA_FRAME_MOVE_FUNC = "GLITER_ALCHEMYST_SECRET_BOSS_DAMAGE_FRONT_FRAME_MOVE",	},

	{ STATE_NAME = "GLITER_ALCHEMYST_SECRET_BOSS_DAMAGE_DOWN_FRONT",			LUA_STATE_START_FUNC = "GLITER_ALCHEMYST_SECRET_BOSS_DAMAGE_DOWN_FRONT_STATE_START",		},
	{ STATE_NAME = "GLITER_ALCHEMYST_SECRET_BOSS_DAMAGE_DOWN_BACK",				LUA_STATE_START_FUNC = "GLITER_ALCHEMYST_SECRET_BOSS_DAMAGE_DOWN_BACK_STATE_START",		},
	{ STATE_NAME = "GLITER_ALCHEMYST_SECRET_BOSS_DAMAGE_FLY_FRONT",				},
	{ STATE_NAME = "GLITER_ALCHEMYST_SECRET_BOSS_DAMAGE_FLY_BACK",				},
	{ STATE_NAME = "GLITER_ALCHEMYST_SECRET_BOSS_DAMAGE_AIR",					},
	{ STATE_NAME = "GLITER_ALCHEMYST_SECRET_BOSS_DAMAGE_AIR_DOWN",				},
	{ STATE_NAME = "GLITER_ALCHEMYST_SECRET_BOSS_DAMAGE_AIR_UP",				},
	{ STATE_NAME = "GLITER_ALCHEMYST_SECRET_BOSS_DAMAGE_AIR_FALL",				},	
	{ STATE_NAME = "GLITER_ALCHEMYST_SECRET_BOSS_DAMAGE_AIR_DOWN_LANDING",		LUA_STATE_START_FUNC = "GLITER_ALCHEMYST_SECRET_BOSS_DAMAGE_AIR_DOWN_LANDING_STATE_START",	},
	{ STATE_NAME = "GLITER_ALCHEMYST_SECRET_BOSS_STAND_UP_FRONT",				LUA_FRAME_MOVE_FUNC = "GLITER_ALCHEMYST_SECRET_BOSS_STAND_UP_FRONT_FRAME_MOVE", 	},
	{ STATE_NAME = "GLITER_ALCHEMYST_SECRET_BOSS_STAND_UP_BACK",				LUA_FRAME_MOVE_FUNC = "GLITER_ALCHEMYST_SECRET_BOSS_STAND_UP_BACK_FRAME_MOVE"		},
	
	{ STATE_NAME = "GLITER_ALCHEMYST_SECRET_BOSS_DAMAGE_REVENGE",				},
		
	{ STATE_NAME = "GLITER_ALCHEMYST_SECRET_BOSS_DYING_LAND_FRONT",			},
	{ STATE_NAME = "GLITER_ALCHEMYST_SECRET_BOSS_DYING_LAND_BACK",			},
	{ STATE_NAME = "GLITER_ALCHEMYST_SECRET_BOSS_DYING_SKY",					},
		
	
	START_STATE					= "GLITER_ALCHEMYST_SECRET_BOSS_START",
	WAIT_STATE					= "GLITER_ALCHEMYST_SECRET_BOSS_WAIT",
	
	
	SMALL_DAMAGE_LAND_FRONT		= "GLITER_ALCHEMYST_SECRET_BOSS_DAMAGE_FRONT",
	SMALL_DAMAGE_LAND_BACK		= "GLITER_ALCHEMYST_SECRET_BOSS_DAMAGE_BACK",
	BIG_DAMAGE_LAND_FRONT		= "GLITER_ALCHEMYST_SECRET_BOSS_DAMAGE_FRONT",
	BIG_DAMAGE_LAND_BACK		= "GLITER_ALCHEMYST_SECRET_BOSS_DAMAGE_BACK",
	DOWN_DAMAGE_LAND_FRONT		= "GLITER_ALCHEMYST_SECRET_BOSS_DAMAGE_DOWN_FRONT",
	DOWN_DAMAGE_LAND_BACK		= "GLITER_ALCHEMYST_SECRET_BOSS_DAMAGE_DOWN_BACK",
	FLY_DAMAGE_FRONT			= "GLITER_ALCHEMYST_SECRET_BOSS_DAMAGE_FLY_FRONT",
	FLY_DAMAGE_BACK				= "GLITER_ALCHEMYST_SECRET_BOSS_DAMAGE_FLY_BACK",
	SMALL_DAMAGE_AIR			= "GLITER_ALCHEMYST_SECRET_BOSS_DAMAGE_AIR",	
	BIG_DAMAGE_AIR				= "GLITER_ALCHEMYST_SECRET_BOSS_DAMAGE_AIR",
	DOWN_DAMAGE_AIR				= "GLITER_ALCHEMYST_SECRET_BOSS_DAMAGE_AIR_DOWN",
	DOWN_DAMAGE_AIR_LANDING		= "GLITER_ALCHEMYST_SECRET_BOSS_DAMAGE_AIR_DOWN_LANDING",
	UP_DAMAGE					= "GLITER_ALCHEMYST_SECRET_BOSS_DAMAGE_AIR_UP",
	DAMAGE_REVENGE				= "GLITER_ALCHEMYST_SECRET_BOSS_DAMAGE_REVENGE",
	
	DAMAGE_EXTRA_STATES         = {"GLITER_ALCHEMYST_SECRET_BOSS_DAMAGE_AIR_FALL","GLITER_ALCHEMYST_SECRET_BOSS_STAND_UP_FRONT","GLITER_ALCHEMYST_SECRET_BOSS_STAND_UP_BACK",
	"GLITER_ALCHEMYST_SECRET_BOSS_JUMP_DOWN","GLITER_ALCHEMYST_SECRET_BOSS_JUMP_LANDING",	},	

	DYING_LAND_FRONT			= "GLITER_ALCHEMYST_SECRET_BOSS_DYING_LAND_FRONT",
	DYING_LAND_BACK				= "GLITER_ALCHEMYST_SECRET_BOSS_DYING_LAND_BACK",
	DYING_SKY					= "GLITER_ALCHEMYST_SECRET_BOSS_DYING_SKY",
	
	REVENGE_ATTACK				= "",

	COMMON_FRAME_FUNC           = "",	
}

INIT_AI = 
{
	TARGET = 
	{
		TARGET_PRIORITY 			= TARGET_PRIORITY["TP_LOW_HP_FIRST"],
		TARGET_INTERVAL				= 3,		-- sec
		TARGET_NEAR_RANGE			= 600,		-- 이 거리보다 가까우면 TARGET_SUCCESS_RATE에 관계없이 무조건 타게팅된다
		TARGET_RANGE				= 9900,		-- cm
		TARGET_LOST_RANGE			= 9990,		-- cm
		TARGET_SUCCESS_RATE			= 100,  --80,		-- %
		ATTACK_TARGET_RATE			= 100, -- 40,		-- 나를 공격한 유닛을 타게팅할 확률
		PRESERVE_LAST_TARGET_RATE	= 100, -- 60,		-- 이전에 타게팅된 유닛을 계속 타게팅할 확률                                            
	},

	CHASE_MOVE = 
	{		
		MOVE_SPLIT_RANGE	= 600,
		DEST_GAP			= 1000,	-- 목적지에서 이 거리 안에 있으면 도착했다고 판단한다
		MOVE_GAP			= 1100,
		
		DIR_CHANGE_INTERVAL = 0.7,
		
		WALK_INTERVAL		= 3,
		NEAR_WALK_RATE		= 100,   --  70,
		FAR_WALK_RATE		= 100,   -- 30,
		
		JUMP_INTERVAL		= 8,
		UP_JUMP_RATE		= 100, -- 30,
		UP_DOWN_RATE		= 10,
		DOWN_JUMP_RATE		= 100,    --  10,
		DOWN_DOWN_RATE		= 40,
		
		--LINE_END_RANGE		= 80,	-- cm
	},	
	
	PATROL_MOVE = 	
	{
		PATROL_BEGIN_RATE		= 100, --50,		
		PATROL_RANGE			= 200,
		PATROL_COOL_TIME		= 2,
		ONLY_THIS_LINE_GROUP	= TRUE,
	},
	
	ESCAPE_MOVE = 
	{		
		MOVE_SPLIT_RANGE	= 500,	-- cm
		ESCAPE_GAP			= 600,	-- 이 거리 보다 멀어지면 도망 성공
		
		WALK_INTERVAL		= 6,	-- 초
		NEAR_WALK_RATE		= 100,   --  10,
		FAR_WALK_RATE		= 100,   -- 10,
		
		JUMP_INTERVAL		= 10,
		UP_JUMP_RATE		= 100, -- 30,
		UP_DOWN_RATE		= 30,
		DOWN_JUMP_RATE		= 100,    --  30,
		DOWN_DOWN_RATE		= 30,
		
		--**LINE_END_RANGE		= 80,	-- cm
	},
	
	ESCAPE_CONDITION = 
	{
		RATE				= 80,
		ESCAPE_RANGE		= 400,		-- 이 범위 안에 들어오면 타격당하지 않아도 RATE에 지정된 확률로 도망
	}
}

GLITER_ALCHEMYST_SECRET_BOSS_START =
{
	ANIM_NAME					= "WaitHabit",
	PLAY_TYPE					= XSKIN_ANIM_PLAYTYPE["XAP_ONE_WAIT"],
	TRANSITION					= FALSE,

	CAN_PUSH_UNIT				= TRUE,
	CAN_PASS_UNIT				= FALSE,
	IMMADIATE_PACKET_SEND		= TRUE,

	SOUND_PLAY0					= { 0.01, "Hoakin_Voice_WaitStart01.ogg", 100, FALSE, 50000, }, --예비
	
	SOUND_PLAY1					= { 0.02, "Hoakin_Voice_WaitStart01.ogg", 100, FALSE, 50000, },
	
	EVENT_PROCESS =
	{
		{ STATE_CHANGE_TYPE["SCT_FOOT_ON_LINE_FALSE_DOWN"],	"GLITER_ALCHEMYST_SECRET_BOSS_JUMP_DOWN",					},
		{ STATE_CHANGE_TYPE["SCT_MOTION_END"],				"GLITER_ALCHEMYST_SECRET_BOSS_WAIT",						},
	},
}

GLITER_ALCHEMYST_SECRET_BOSS_WAIT = 
{
	ANIM_NAME					= "Wait",
	PLAY_TYPE					= XSKIN_ANIM_PLAYTYPE["XAP_LOOP"],
	TRANSITION					= TRUE,
	--SUPER_ARMOR					= TRUE,
	
	CAN_PUSH_UNIT				= TRUE,
	CAN_PASS_UNIT				= FALSE,	
	
	SPEED_X						= 0,
	SPEED_Y						= 0,
	
	PASSIVE_SPEED_X				= 0,
	
	IMMADIATE_PACKET_SEND		= TRUE,
	EVENT_INTERVAL_TIME0		= 0.1,
	
	ALLOW_DIR_CHANGE			= TRUE,
	VIEW_TARGET					= TRUE,
	
	EVENT_PROCESS = 
	{		
		{ STATE_CHANGE_TYPE["SCT_FOOT_ON_LINE_FALSE_DOWN"],	"GLITER_ALCHEMYST_SECRET_BOSS_JUMP_DOWN",				},
		{ STATE_CHANGE_TYPE["SCT_CONDITION_TABLE"],			"GLITER_ALCHEMYST_SECRET_BOSS_WAITHABIT",				"CT_GLITER_ALCHEMYST_SECRET_BOSS_WAITHABIT",			},
		
		{ STATE_CHANGE_TYPE["SCT_CONDITION_FUNCTION"],		"GLITER_ALCHEMYST_SECRET_BOSS_MAGIC_ATTACK_C",			"CF_GLITER_ALCHEMYST_SECRET_BOSS_MAGIC_ATTACK_C",		},
		{ STATE_CHANGE_TYPE["SCT_CONDITION_TABLE"],			"GLITER_ALCHEMYST_SECRET_BOSS_REAL_SPECIAL_ATTACK",		"CT_GLITER_ALCHEMYST_SECRET_BOSS_REAL_SPECIAL_ATTACK",	},		

		{ STATE_CHANGE_TYPE["SCT_CONDITION_TABLE"],			"GLITER_ALCHEMYST_SECRET_BOSS_SPECIAL_ATTACK_A",		"CT_GLITER_ALCHEMYST_SECRET_BOSS_SPECIAL_ATTACK_A",		},
		{ STATE_CHANGE_TYPE["SCT_CONDITION_TABLE"],			"GLITER_ALCHEMYST_SECRET_BOSS_SPECIAL_ATTACK_B",		"CT_GLITER_ALCHEMYST_SECRET_BOSS_SPECIAL_ATTACK_B",		},
		{ STATE_CHANGE_TYPE["SCT_CONDITION_TABLE"],			"GLITER_ALCHEMYST_SECRET_BOSS_SPECIAL_ATTACK_C",		"CT_GLITER_ALCHEMYST_SECRET_BOSS_SPECIAL_ATTACK_C",		},

		{ STATE_CHANGE_TYPE["SCT_CONDITION_FUNCTION"],		"GLITER_ALCHEMYST_SECRET_BOSS_DRINK_POTION",			"CF_GLITER_ALCHEMYST_SECRET_BOSS_DRINK_POTION",	},	

		{ STATE_CHANGE_TYPE["SCT_CONDITION_TABLE"],			"GLITER_ALCHEMYST_SECRET_BOSS_MAGIC_ATTACK_A",			"CT_GLITER_ALCHEMYST_SECRET_BOSS_MAGIC_ATTACK_A",		},
		{ STATE_CHANGE_TYPE["SCT_CONDITION_TABLE"],			"GLITER_ALCHEMYST_SECRET_BOSS_MAGIC_ATTACK_B",			"CT_GLITER_ALCHEMYST_SECRET_BOSS_MAGIC_ATTACK_B",		},		
		{ STATE_CHANGE_TYPE["SCT_CONDITION_TABLE"],			"GLITER_ALCHEMYST_SECRET_BOSS_MAGIC_ATTACK_D",			"CT_GLITER_ALCHEMYST_SECRET_BOSS_MAGIC_ATTACK_D",		},		
		{ STATE_CHANGE_TYPE["SCT_CONDITION_TABLE"],			"GLITER_ALCHEMYST_SECRET_BOSS_MAGIC_ATTACK_E",			"CT_GLITER_ALCHEMYST_SECRET_BOSS_MAGIC_ATTACK_E",		},	
		
		{ STATE_CHANGE_TYPE["SCT_AI_WALK"],					"GLITER_ALCHEMYST_SECRET_BOSS_WALK",					},
		{ STATE_CHANGE_TYPE["SCT_AI_DASH"],					"GLITER_ALCHEMYST_SECRET_BOSS_DASH",					},
		{ STATE_CHANGE_TYPE["SCT_AI_JUMP"],					"GLITER_ALCHEMYST_SECRET_BOSS_JUMP_UP",					},
		{ STATE_CHANGE_TYPE["SCT_AI_JUMP_DIR"],				"GLITER_ALCHEMYST_SECRET_BOSS_JUMP_UP_DIR",				},
		{ STATE_CHANGE_TYPE["SCT_AI_DOWN"],					"GLITER_ALCHEMYST_SECRET_BOSS_JUMP_DOWN",				},
		{ STATE_CHANGE_TYPE["SCT_AI_DOWN_DIR"],				"GLITER_ALCHEMYST_SECRET_BOSS_JUMP_DOWN_DIR",			},
		
	},
	
	CT_GLITER_ALCHEMYST_SECRET_BOSS_WAITHABIT = 
	{
		ANIM_PLAY_COUNT				= 2,
		RATE						= 50,
		HAVE_TARGET					= 0,		-- false
	},
	CT_GLITER_ALCHEMYST_SECRET_BOSS_MAGIC_ATTACK_A = 
	{
		EVENT_INTERVAL_ID			= 0,
		DISTANCE_TO_TARGET_NEAR		= 1200,
		RATE						= 20,
	},
	CT_GLITER_ALCHEMYST_SECRET_BOSS_MAGIC_ATTACK_B = 
	{
		EVENT_INTERVAL_ID			= 0,		
		DISTANCE_TO_TARGET_NEAR		= 2000,
		RATE						= 20,
	},
	CT_GLITER_ALCHEMYST_SECRET_BOSS_MAGIC_ATTACK_D = 
	{
		EVENT_INTERVAL_ID			= 0,
		DISTANCE_TO_TARGET_NEAR		= 1400,
		RATE						= 20,
	},
	CT_GLITER_ALCHEMYST_SECRET_BOSS_MAGIC_ATTACK_E = 
	{
		EVENT_INTERVAL_ID			= 0,
		HAVE_TARGET					= 1,
		ALIVE_USER_MORE_THAN		= 2,
		DISTANCE_TO_TARGET_NEAR		= 1200,
		RATE						= 100,
	},
	CT_GLITER_ALCHEMYST_SECRET_BOSS_SPECIAL_ATTACK_A = 
	{
		EVENT_INTERVAL_ID			= 0,
		DISTANCE_TO_TARGET_NEAR		= 3000,
		RATE						= 20,
	},	
	CT_GLITER_ALCHEMYST_SECRET_BOSS_SPECIAL_ATTACK_B = 
	{
		EVENT_INTERVAL_ID			= 0,
		DISTANCE_TO_TARGET_NEAR		= 3000,
		RATE						= 100,
	},	
	CT_GLITER_ALCHEMYST_SECRET_BOSS_SPECIAL_ATTACK_C = 
	{
		EVENT_INTERVAL_ID			= 0,
		DISTANCE_TO_TARGET_NEAR		= 3000,
		RATE						= 100,
	},	
	CT_GLITER_ALCHEMYST_SECRET_BOSS_REAL_SPECIAL_ATTACK = 
	{
		EVENT_INTERVAL_ID			= 0,
		DISTANCE_TO_TARGET_NEAR		= 3000,
		--IS_RAGEMODE					= TRUE,
		RATE						= 100,
	},
		
}


GLITER_ALCHEMYST_SECRET_BOSS_WAITHABIT =
{
	ANIM_NAME					= "WaitHabit",
	PLAY_TYPE					= XSKIN_ANIM_PLAYTYPE["XAP_ONE_WAIT"],
	TRANSITION					= FALSE,

	CAN_PUSH_UNIT				= TRUE,
	CAN_PASS_UNIT				= FALSE,
	IMMADIATE_PACKET_SEND		= TRUE,

	EVENT_PROCESS =
	{
		{ STATE_CHANGE_TYPE["SCT_FOOT_ON_LINE_FALSE_DOWN"],	"GLITER_ALCHEMYST_SECRET_BOSS_JUMP_DOWN",					},
		{ STATE_CHANGE_TYPE["SCT_MOTION_END"],				"GLITER_ALCHEMYST_SECRET_BOSS_WAIT",						},
	},
}


GLITER_ALCHEMYST_SECRET_BOSS_WALK = 
{
	ANIM_NAME					= "Walk",
	PLAY_TYPE					= XSKIN_ANIM_PLAYTYPE["XAP_LOOP"],
	TRANSITION					= TRUE,
	
	CAN_PUSH_UNIT				= TRUE,
	CAN_PASS_UNIT				= FALSE,

	
	PASSIVE_SPEED_X				= INIT_PHYSIC["WALK_SPEED"],
	
	ALLOW_DIR_CHANGE			= TRUE,
	VIEW_TARGET					= TRUE,
	
	IMMADIATE_PACKET_SEND		= TRUE,
	
	EVENT_INTERVAL_TIME0		= 2,
 	EVENT_INTERVAL_TIME1		= 3,

	EVENT_PROCESS = 
	{		
		
		{ STATE_CHANGE_TYPE["SCT_FOOT_ON_LINE_FALSE_DOWN"],	"GLITER_ALCHEMYST_SECRET_BOSS_JUMP_DOWN_DIR",			},

		{ STATE_CHANGE_TYPE["SCT_CONDITION_FUNCTION"],		"GLITER_ALCHEMYST_SECRET_BOSS_MAGIC_ATTACK_C",			"CF_GLITER_ALCHEMYST_SECRET_BOSS_MAGIC_ATTACK_C",		},		
		{ STATE_CHANGE_TYPE["SCT_CONDITION_TABLE"],			"GLITER_ALCHEMYST_SECRET_BOSS_REAL_SPECIAL_ATTACK",		"CT_GLITER_ALCHEMYST_SECRET_BOSS_REAL_SPECIAL_ATTACK",	},		

		{ STATE_CHANGE_TYPE["SCT_CONDITION_TABLE"],			"GLITER_ALCHEMYST_SECRET_BOSS_SPECIAL_ATTACK_A",		"CT_GLITER_ALCHEMYST_SECRET_BOSS_SPECIAL_ATTACK_A",		},
		{ STATE_CHANGE_TYPE["SCT_CONDITION_TABLE"],			"GLITER_ALCHEMYST_SECRET_BOSS_SPECIAL_ATTACK_B",		"CT_GLITER_ALCHEMYST_SECRET_BOSS_SPECIAL_ATTACK_B",		},
		{ STATE_CHANGE_TYPE["SCT_CONDITION_TABLE"],			"GLITER_ALCHEMYST_SECRET_BOSS_SPECIAL_ATTACK_C",		"CT_GLITER_ALCHEMYST_SECRET_BOSS_SPECIAL_ATTACK_C",		},

		{ STATE_CHANGE_TYPE["SCT_CONDITION_FUNCTION"],		"GLITER_ALCHEMYST_SECRET_BOSS_DRINK_POTION",			"CF_GLITER_ALCHEMYST_SECRET_BOSS_DRINK_POTION",	},	

		{ STATE_CHANGE_TYPE["SCT_CONDITION_TABLE"],			"GLITER_ALCHEMYST_SECRET_BOSS_MAGIC_ATTACK_A",			"CT_GLITER_ALCHEMYST_SECRET_BOSS_MAGIC_ATTACK_A",		},
		{ STATE_CHANGE_TYPE["SCT_CONDITION_TABLE"],			"GLITER_ALCHEMYST_SECRET_BOSS_MAGIC_ATTACK_B",			"CT_GLITER_ALCHEMYST_SECRET_BOSS_MAGIC_ATTACK_B",		},		
		{ STATE_CHANGE_TYPE["SCT_CONDITION_TABLE"],			"GLITER_ALCHEMYST_SECRET_BOSS_MAGIC_ATTACK_D",			"CT_GLITER_ALCHEMYST_SECRET_BOSS_MAGIC_ATTACK_D",		},		
		{ STATE_CHANGE_TYPE["SCT_CONDITION_TABLE"],			"GLITER_ALCHEMYST_SECRET_BOSS_MAGIC_ATTACK_E",			"CT_GLITER_ALCHEMYST_SECRET_BOSS_MAGIC_ATTACK_E",		},	
		
		{ STATE_CHANGE_TYPE["SCT_AI_WAIT"],					"GLITER_ALCHEMYST_SECRET_BOSS_WAIT",						},
		{ STATE_CHANGE_TYPE["SCT_AI_DASH"],					"GLITER_ALCHEMYST_SECRET_BOSS_DASH",						},
		{ STATE_CHANGE_TYPE["SCT_AI_JUMP"],					"GLITER_ALCHEMYST_SECRET_BOSS_JUMP_UP",					},
		{ STATE_CHANGE_TYPE["SCT_AI_JUMP_DIR"],				"GLITER_ALCHEMYST_SECRET_BOSS_JUMP_UP_DIR",				},
		{ STATE_CHANGE_TYPE["SCT_AI_DOWN"],					"GLITER_ALCHEMYST_SECRET_BOSS_JUMP_DOWN",				},
		{ STATE_CHANGE_TYPE["SCT_AI_DOWN_DIR"],				"GLITER_ALCHEMYST_SECRET_BOSS_JUMP_DOWN_DIR",			},
	},

	CT_GLITER_ALCHEMYST_SECRET_BOSS_MAGIC_ATTACK_A = 
	{
		EVENT_INTERVAL_ID			= 0,
		DISTANCE_TO_TARGET_NEAR		= 1200,
		RATE						= 20,
	},
	CT_GLITER_ALCHEMYST_SECRET_BOSS_MAGIC_ATTACK_B = 
	{
		EVENT_INTERVAL_ID			= 0,		
		DISTANCE_TO_TARGET_NEAR		= 2000,
		RATE						= 20,
	},
	CT_GLITER_ALCHEMYST_SECRET_BOSS_MAGIC_ATTACK_D = 
	{
		EVENT_INTERVAL_ID			= 0,
		DISTANCE_TO_TARGET_NEAR		= 1400,
		RATE						= 20,
	},
	CT_GLITER_ALCHEMYST_SECRET_BOSS_MAGIC_ATTACK_E = 
	{
		EVENT_INTERVAL_ID			= 0,
		HAVE_TARGET					= 1,
		ALIVE_USER_MORE_THAN		= 2,
		DISTANCE_TO_TARGET_NEAR		= 1200,
		RATE						= 100,
	},
	CT_GLITER_ALCHEMYST_SECRET_BOSS_SPECIAL_ATTACK_A = 
	{
		EVENT_INTERVAL_ID			= 0,
		DISTANCE_TO_TARGET_NEAR		= 3000,
		RATE						= 20,
	},	
	CT_GLITER_ALCHEMYST_SECRET_BOSS_SPECIAL_ATTACK_B = 
	{
		EVENT_INTERVAL_ID			= 0,
		DISTANCE_TO_TARGET_NEAR		= 3000,
		RATE						= 100,
	},	
	CT_GLITER_ALCHEMYST_SECRET_BOSS_SPECIAL_ATTACK_C = 
	{
		EVENT_INTERVAL_ID			= 0,
		DISTANCE_TO_TARGET_NEAR		= 3000,
		RATE						= 100,
	},	
	CT_GLITER_ALCHEMYST_SECRET_BOSS_REAL_SPECIAL_ATTACK = 
	{
		EVENT_INTERVAL_ID			= 0,
		DISTANCE_TO_TARGET_NEAR		= 3000,
		--IS_RAGEMODE					= TRUE,
		RATE						= 100,
	},
}

GLITER_ALCHEMYST_SECRET_BOSS_DASH =
{
	ANIM_NAME					= "Dash",
	PLAY_TYPE					= XSKIN_ANIM_PLAYTYPE["XAP_LOOP"],
	TRANSITION					= TRUE,

	CAN_PUSH_UNIT				= TRUE,
	CAN_PASS_UNIT				= FALSE,


	PASSIVE_SPEED_X				= INIT_PHYSIC["RUN_SPEED"],

	ALLOW_DIR_CHANGE			= TRUE,
	IMMADIATE_PACKET_SEND		= TRUE,

	EVENT_INTERVAL_TIME0		= 2,
	EVENT_INTERVAL_TIME1		= 3,

	EVENT_PROCESS =
	{

		{ STATE_CHANGE_TYPE["SCT_FOOT_ON_LINE_FALSE_DOWN"],	"GLITER_ALCHEMYST_SECRET_BOSS_JUMP_DOWN_DIR",			},

		{ STATE_CHANGE_TYPE["SCT_CONDITION_FUNCTION"],		"GLITER_ALCHEMYST_SECRET_BOSS_MAGIC_ATTACK_C",			"CF_GLITER_ALCHEMYST_SECRET_BOSS_MAGIC_ATTACK_C",		},
		{ STATE_CHANGE_TYPE["SCT_CONDITION_TABLE"],			"GLITER_ALCHEMYST_SECRET_BOSS_REAL_SPECIAL_ATTACK",		"CT_GLITER_ALCHEMYST_SECRET_BOSS_REAL_SPECIAL_ATTACK",	},		

		{ STATE_CHANGE_TYPE["SCT_CONDITION_TABLE"],			"GLITER_ALCHEMYST_SECRET_BOSS_SPECIAL_ATTACK_A",		"CT_GLITER_ALCHEMYST_SECRET_BOSS_SPECIAL_ATTACK_A",		},
		{ STATE_CHANGE_TYPE["SCT_CONDITION_TABLE"],			"GLITER_ALCHEMYST_SECRET_BOSS_SPECIAL_ATTACK_B",		"CT_GLITER_ALCHEMYST_SECRET_BOSS_SPECIAL_ATTACK_B",		},
		{ STATE_CHANGE_TYPE["SCT_CONDITION_TABLE"],			"GLITER_ALCHEMYST_SECRET_BOSS_SPECIAL_ATTACK_C",		"CT_GLITER_ALCHEMYST_SECRET_BOSS_SPECIAL_ATTACK_C",		},

		{ STATE_CHANGE_TYPE["SCT_CONDITION_FUNCTION"],		"GLITER_ALCHEMYST_SECRET_BOSS_DRINK_POTION",			"CF_GLITER_ALCHEMYST_SECRET_BOSS_DRINK_POTION",	},	

		{ STATE_CHANGE_TYPE["SCT_CONDITION_TABLE"],			"GLITER_ALCHEMYST_SECRET_BOSS_MAGIC_ATTACK_A",			"CT_GLITER_ALCHEMYST_SECRET_BOSS_MAGIC_ATTACK_A",		},
		{ STATE_CHANGE_TYPE["SCT_CONDITION_TABLE"],			"GLITER_ALCHEMYST_SECRET_BOSS_MAGIC_ATTACK_B",			"CT_GLITER_ALCHEMYST_SECRET_BOSS_MAGIC_ATTACK_B",		},
		{ STATE_CHANGE_TYPE["SCT_CONDITION_TABLE"],			"GLITER_ALCHEMYST_SECRET_BOSS_MAGIC_ATTACK_D",			"CT_GLITER_ALCHEMYST_SECRET_BOSS_MAGIC_ATTACK_D",		},		
		{ STATE_CHANGE_TYPE["SCT_CONDITION_TABLE"],			"GLITER_ALCHEMYST_SECRET_BOSS_MAGIC_ATTACK_E",			"CT_GLITER_ALCHEMYST_SECRET_BOSS_MAGIC_ATTACK_E",		},	
		
		{ STATE_CHANGE_TYPE["SCT_AI_WAIT"],					"GLITER_ALCHEMYST_SECRET_BOSS_WAIT",						},
		{ STATE_CHANGE_TYPE["SCT_AI_DASH"],					"GLITER_ALCHEMYST_SECRET_BOSS_DASH",						},
		{ STATE_CHANGE_TYPE["SCT_AI_JUMP"],					"GLITER_ALCHEMYST_SECRET_BOSS_JUMP_UP",					},
		{ STATE_CHANGE_TYPE["SCT_AI_JUMP_DIR"],				"GLITER_ALCHEMYST_SECRET_BOSS_DASH_JUMP_UP_DIR",				},
		{ STATE_CHANGE_TYPE["SCT_AI_DOWN"],					"GLITER_ALCHEMYST_SECRET_BOSS_JUMP_DOWN",				},
		{ STATE_CHANGE_TYPE["SCT_AI_DOWN_DIR"],				"GLITER_ALCHEMYST_SECRET_BOSS_JUMP_DOWN_DIR",			},
	},

	CT_GLITER_ALCHEMYST_SECRET_BOSS_MAGIC_ATTACK_A = 
	{
		EVENT_INTERVAL_ID			= 0,
		DISTANCE_TO_TARGET_NEAR		= 1200,
		RATE						= 20,
	},
	CT_GLITER_ALCHEMYST_SECRET_BOSS_MAGIC_ATTACK_B = 
	{
		EVENT_INTERVAL_ID			= 0,		
		DISTANCE_TO_TARGET_NEAR		= 2000,
		RATE						= 20,
	},
	CT_GLITER_ALCHEMYST_SECRET_BOSS_MAGIC_ATTACK_D = 
	{
		EVENT_INTERVAL_ID			= 0,
		DISTANCE_TO_TARGET_NEAR		= 1400,
		RATE						= 20,
	},
	CT_GLITER_ALCHEMYST_SECRET_BOSS_MAGIC_ATTACK_E = 
	{
		EVENT_INTERVAL_ID			= 0,
		HAVE_TARGET					= 1,
		ALIVE_USER_MORE_THAN		= 2,
		DISTANCE_TO_TARGET_NEAR		= 1200,
		RATE						= 100,
	},
	CT_GLITER_ALCHEMYST_SECRET_BOSS_SPECIAL_ATTACK_A = 
	{
		EVENT_INTERVAL_ID			= 0,
		DISTANCE_TO_TARGET_NEAR		= 3000,
		RATE						= 20,
	},	
	CT_GLITER_ALCHEMYST_SECRET_BOSS_SPECIAL_ATTACK_B = 
	{
		EVENT_INTERVAL_ID			= 0,
		DISTANCE_TO_TARGET_NEAR		= 3000,
		RATE						= 100,
	},	
	CT_GLITER_ALCHEMYST_SECRET_BOSS_SPECIAL_ATTACK_C = 
	{
		EVENT_INTERVAL_ID			= 0,
		DISTANCE_TO_TARGET_NEAR		= 3000,
		RATE						= 100,
	},	
	CT_GLITER_ALCHEMYST_SECRET_BOSS_REAL_SPECIAL_ATTACK = 
	{
		EVENT_INTERVAL_ID			= 0,
		DISTANCE_TO_TARGET_NEAR		= 3000,
		--IS_RAGEMODE					= TRUE,
		RATE						= 100,
	},	
    
}




GLITER_ALCHEMYST_SECRET_BOSS_JUMP_UP = 
{
	ANIM_NAME					= "JumpUp",
	PLAY_TYPE					= XSKIN_ANIM_PLAYTYPE["XAP_LOOP"],
	TRANSITION					= TRUE,
	LAND_CONNECT				= FALSE,
	
	CAN_PUSH_UNIT				= TRUE,
	CAN_PASS_UNIT				= FALSE,
	
	SPEED_X						= 0,
	SPEED_Y						= INIT_PHYSIC["JUMP_SPEED"],
	
	ADD_POS_Y					= 45, 
	
	IMMADIATE_PACKET_SEND		= TRUE,

	EVENT_PROCESS = 
	{		
		{ STATE_CHANGE_TYPE["SCT_NEGATIVE_Y_SPEED"],		"GLITER_ALCHEMYST_SECRET_BOSS_JUMP_DOWN",			},
	},
}

GLITER_ALCHEMYST_SECRET_BOSS_JUMP_DOWN = 
{
	ANIM_NAME					= "JumpDown",
	PLAY_TYPE					= XSKIN_ANIM_PLAYTYPE["XAP_LOOP"],
	TRANSITION					= TRUE,
	LAND_CONNECT				= FALSE,
	
	CAN_PUSH_UNIT				= TRUE,
	CAN_PASS_UNIT				= FALSE,
		 
	
	IMMADIATE_PACKET_SEND		= TRUE,
		
	EVENT_PROCESS = 
	{		
		{ STATE_CHANGE_TYPE["SCT_FOOT_ON_LINE_TRUE"],		"GLITER_ALCHEMYST_SECRET_BOSS_JUMP_LANDING",				},
	},
}

GLITER_ALCHEMYST_SECRET_BOSS_JUMP_UP_DIR = 
{
	ANIM_NAME					= "JumpUp",
	PLAY_TYPE					= XSKIN_ANIM_PLAYTYPE["XAP_LOOP"],
	TRANSITION					= TRUE,
	LAND_CONNECT				= FALSE,
	
	CAN_PUSH_UNIT				= TRUE,
	CAN_PASS_UNIT				= FALSE,
		
	PASSIVE_SPEED_X				= INIT_PHYSIC["WALK_SPEED"],
	SPEED_Y						= INIT_PHYSIC["JUMP_SPEED"],
	
	ADD_POS_Y					= 45, 
	
	IMMADIATE_PACKET_SEND		= TRUE,
	
	EVENT_PROCESS = 
	{		
		{ STATE_CHANGE_TYPE["SCT_NEGATIVE_Y_SPEED"],		"GLITER_ALCHEMYST_SECRET_BOSS_JUMP_DOWN_DIR",				},
	},
}

GLITER_ALCHEMYST_SECRET_BOSS_JUMP_DOWN_DIR = 
{
	ANIM_NAME					= "JumpDown",
	PLAY_TYPE					= XSKIN_ANIM_PLAYTYPE["XAP_LOOP"],
	TRANSITION					= TRUE,
	LAND_CONNECT				= FALSE,
	
	CAN_PUSH_UNIT				= TRUE,
	CAN_PASS_UNIT				= FALSE,
	
	PASSIVE_SPEED_X				= INIT_PHYSIC["WALK_SPEED"],
	 
	
	IMMADIATE_PACKET_SEND		= TRUE,
		
	EVENT_PROCESS = 
	{		
		{ STATE_CHANGE_TYPE["SCT_FOOT_ON_LINE_TRUE"],		"GLITER_ALCHEMYST_SECRET_BOSS_JUMP_LANDING",				},
	},
}



GLITER_ALCHEMYST_SECRET_BOSS_DASH_JUMP_UP_DIR =
{
	ANIM_NAME					= "JumpUp",
	PLAY_TYPE					= XSKIN_ANIM_PLAYTYPE["XAP_LOOP"],
	TRANSITION					= TRUE,
	LAND_CONNECT				= FALSE,

	CAN_PUSH_UNIT				= TRUE,
	CAN_PASS_UNIT				= FALSE,

	PASSIVE_SPEED_X				= INIT_PHYSIC["RUN_SPEED"],
	SPEED_Y						= INIT_PHYSIC["DASH_JUMP_SPEED"],

	ADD_POS_Y					= 45,

	IMMADIATE_PACKET_SEND		= TRUE,

	EVENT_PROCESS =
	{
		{ STATE_CHANGE_TYPE["SCT_NEGATIVE_Y_SPEED"],		"GLITER_ALCHEMYST_SECRET_BOSS_JUMP_DOWN_DIR",				},
	},
}

GLITER_ALCHEMYST_SECRET_BOSS_DASH_JUMP_DOWN_DIR =
{
	ANIM_NAME					= "JumpDown",
	PLAY_TYPE					= XSKIN_ANIM_PLAYTYPE["XAP_LOOP"],
	TRANSITION					= TRUE,
	LAND_CONNECT				= FALSE,

	CAN_PUSH_UNIT				= TRUE,
	CAN_PASS_UNIT				= FALSE,

	PASSIVE_SPEED_X				= INIT_PHYSIC["RUN_SPEED"],


	IMMADIATE_PACKET_SEND		= TRUE,

	EVENT_PROCESS =
	{
		{ STATE_CHANGE_TYPE["SCT_FOOT_ON_LINE_TRUE"],		"GLITER_ALCHEMYST_SECRET_BOSS_JUMP_LANDING",				},
	},
}

GLITER_ALCHEMYST_SECRET_BOSS_JUMP_LANDING = 
{
	ANIM_NAME					= "JumpLanding",
	PLAY_TYPE					= XSKIN_ANIM_PLAYTYPE["XAP_ONE_WAIT"],
	TRANSITION					= TRUE,
	LAND_CONNECT				= FALSE,
	
	CAN_PUSH_UNIT				= TRUE,
	CAN_PASS_UNIT				= FALSE,

	SPEED_X						= 0,
	SPEED_Y						= 0,

    SOUND_PLAY0			= { 0.118, "Glitter_Landing.ogg" },
	
	IMMADIATE_PACKET_SEND		= TRUE,

	EVENT_PROCESS = 
	{		
		{ STATE_CHANGE_TYPE["SCT_FOOT_ON_LINE_FALSE_DOWN"],	"GLITER_ALCHEMYST_SECRET_BOSS_JUMP_DOWN",				},
		{ STATE_CHANGE_TYPE["SCT_MOTION_END"],				"GLITER_ALCHEMYST_SECRET_BOSS_WAIT",						},
	},
}



GLITER_ALCHEMYST_SECRET_BOSS_DAMAGE_FRONT =
{
	ANIM_NAME					= "DamageFront",
	PLAY_TYPE					= XSKIN_ANIM_PLAYTYPE["XAP_ONE_WAIT"],
	TRANSITION					= FALSE,
	LAND_CONNECT				= FALSE,
	
	CAN_PUSH_UNIT				= TRUE,
	CAN_PASS_UNIT				= FALSE,

	SOUND_PLAY0			= { 0.124, "Hoakin_Voice_HurtRoar01.ogg" , 30 },
	EVENT_INTERVAL_TIME0		= 5,
	
    EVENT_PROCESS = 
	{	
		{ STATE_CHANGE_TYPE["SCT_CONDITION_FUNCTION"],		"GLITER_ALCHEMYST_SECRET_BOSS_MAGIC_ATTACK_C",			"CF_GLITER_ALCHEMYST_SECRET_BOSS_MAGIC_ATTACK_C",		},
		{ STATE_CHANGE_TYPE["SCT_CONDITION_TABLE"],			"GLITER_ALCHEMYST_SECRET_BOSS_MAGIC_ATTACK_A",			"CT_GLITER_ALCHEMYST_SECRET_BOSS_MAGIC_ATTACK_A",		},
		{ STATE_CHANGE_TYPE["SCT_CONDITION_TABLE"],			"GLITER_ALCHEMYST_SECRET_BOSS_MAGIC_ATTACK_B",			"CT_GLITER_ALCHEMYST_SECRET_BOSS_MAGIC_ATTACK_B",		},							
		{ STATE_CHANGE_TYPE["SCT_CONDITION_TABLE"],			"GLITER_ALCHEMYST_SECRET_BOSS_MAGIC_ATTACK_D",			"CT_GLITER_ALCHEMYST_SECRET_BOSS_MAGIC_ATTACK_D",		},		
		{ STATE_CHANGE_TYPE["SCT_CONDITION_TABLE"],			"GLITER_ALCHEMYST_SECRET_BOSS_SPECIAL_ATTACK_A",		"CT_GLITER_ALCHEMYST_SECRET_BOSS_SPECIAL_ATTACK_A",		},		

		{ STATE_CHANGE_TYPE["SCT_MOTION_END"],			"GLITER_ALCHEMYST_SECRET_BOSS_WAIT",												},
	},	

	CT_GLITER_ALCHEMYST_SECRET_BOSS_MAGIC_ATTACK_A = 
	{
		EVENT_INTERVAL_ID			= 0,
		DISTANCE_TO_TARGET_NEAR		= 1200,
		RATE						= 5,
	},
	CT_GLITER_ALCHEMYST_SECRET_BOSS_MAGIC_ATTACK_B = 
	{
		EVENT_INTERVAL_ID			= 0,		
		DISTANCE_TO_TARGET_NEAR		= 2000,
		RATE						= 5,
	},
	CT_GLITER_ALCHEMYST_SECRET_BOSS_MAGIC_ATTACK_D = 
	{
		EVENT_INTERVAL_ID			= 0,
		DISTANCE_TO_TARGET_NEAR		= 1400,
		RATE						= 5,
	},	
	CT_GLITER_ALCHEMYST_SECRET_BOSS_SPECIAL_ATTACK_A = 
	{
		EVENT_INTERVAL_ID			= 0,
		DISTANCE_TO_TARGET_NEAR		= 3000,
		RATE						= 5,
	},	
}


GLITER_ALCHEMYST_SECRET_BOSS_DAMAGE_BACK =
{
	ANIM_NAME					= "DamageBack",
	PLAY_TYPE					= XSKIN_ANIM_PLAYTYPE["XAP_ONE_WAIT"],
	TRANSITION					= FALSE,
	LAND_CONNECT				= FALSE,
	
	CAN_PUSH_UNIT				= TRUE,
	CAN_PASS_UNIT				= FALSE,

    SOUND_PLAY0			= { 0.164, "Hoakin_Voice_HurtRoar02.ogg" , 30 },
	EVENT_INTERVAL_TIME0		= 5,
	
	EVENT_PROCESS = 
	{
		{ STATE_CHANGE_TYPE["SCT_CONDITION_FUNCTION"],		"GLITER_ALCHEMYST_SECRET_BOSS_MAGIC_ATTACK_C",			"CF_GLITER_ALCHEMYST_SECRET_BOSS_MAGIC_ATTACK_C",		},
		{ STATE_CHANGE_TYPE["SCT_CONDITION_TABLE"],			"GLITER_ALCHEMYST_SECRET_BOSS_MAGIC_ATTACK_A",			"CT_GLITER_ALCHEMYST_SECRET_BOSS_MAGIC_ATTACK_A",		},
		{ STATE_CHANGE_TYPE["SCT_CONDITION_TABLE"],			"GLITER_ALCHEMYST_SECRET_BOSS_MAGIC_ATTACK_B",			"CT_GLITER_ALCHEMYST_SECRET_BOSS_MAGIC_ATTACK_B",		},							
		{ STATE_CHANGE_TYPE["SCT_CONDITION_TABLE"],			"GLITER_ALCHEMYST_SECRET_BOSS_MAGIC_ATTACK_D",			"CT_GLITER_ALCHEMYST_SECRET_BOSS_MAGIC_ATTACK_D",		},		
		{ STATE_CHANGE_TYPE["SCT_CONDITION_TABLE"],			"GLITER_ALCHEMYST_SECRET_BOSS_SPECIAL_ATTACK_A",		"CT_GLITER_ALCHEMYST_SECRET_BOSS_SPECIAL_ATTACK_A",		},		

		{ STATE_CHANGE_TYPE["SCT_MOTION_END"],			"GLITER_ALCHEMYST_SECRET_BOSS_WAIT",												},
	},

	CT_GLITER_ALCHEMYST_SECRET_BOSS_MAGIC_ATTACK_A = 
	{
		EVENT_INTERVAL_ID			= 0,
		DISTANCE_TO_TARGET_NEAR		= 1200,
		RATE						= 5,
	},
	CT_GLITER_ALCHEMYST_SECRET_BOSS_MAGIC_ATTACK_B = 
	{
		EVENT_INTERVAL_ID			= 0,		
		DISTANCE_TO_TARGET_NEAR		= 2000,
		RATE						= 5,
	},
	CT_GLITER_ALCHEMYST_SECRET_BOSS_MAGIC_ATTACK_D = 
	{
		EVENT_INTERVAL_ID			= 0,
		DISTANCE_TO_TARGET_NEAR		= 1400,
		RATE						= 5,
	},	
	CT_GLITER_ALCHEMYST_SECRET_BOSS_SPECIAL_ATTACK_A = 
	{
		EVENT_INTERVAL_ID			= 0,
		DISTANCE_TO_TARGET_NEAR		= 3000,
		RATE						= 5,
	},	

}


GLITER_ALCHEMYST_SECRET_BOSS_DAMAGE_DOWN_FRONT = 
{
	ANIM_NAME					= "DamageDownFront",
	PLAY_TYPE					= XSKIN_ANIM_PLAYTYPE["XAP_ONE_WAIT"],
	TRANSITION					= FALSE,
	LAND_CONNECT				= FALSE,

	SUPER_ARMOR					= TRUE,
	DEFENCE						= { 0, 100, 70, },
	
	CAN_PUSH_UNIT				= TRUE,
	CAN_PASS_UNIT				= FALSE,

    SOUND_PLAY0			= { 0.145, "Hoakin_Voice_HurtRoar01.ogg" , 30 },
		
    EVENT_PROCESS = 
	{
		{ STATE_CHANGE_TYPE["SCT_MOTION_END"],					"GLITER_ALCHEMYST_SECRET_BOSS_STAND_UP_FRONT",												},
	},
	
}


GLITER_ALCHEMYST_SECRET_BOSS_DAMAGE_DOWN_BACK = 
{
	ANIM_NAME					= "DamageDownBack",
	PLAY_TYPE					= XSKIN_ANIM_PLAYTYPE["XAP_ONE_WAIT"],
	TRANSITION					= FALSE,
	LAND_CONNECT				= FALSE,
	
	SUPER_ARMOR					= TRUE,
	DEFENCE						= { 0, 100, 70, },

	CAN_PUSH_UNIT				= TRUE,
	CAN_PASS_UNIT				= FALSE,

	    SOUND_PLAY0			= { 0.399, "Hoakin_Voice_HurtRoar02.ogg" , 30 },

   	EVENT_PROCESS = 
	{
		{ STATE_CHANGE_TYPE["SCT_FOOT_ON_LINE_FALSE_DOWN"],		"GLITER_ALCHEMYST_SECRET_BOSS_DAMAGE_AIR_FALL",			},
		{ STATE_CHANGE_TYPE["SCT_MOTION_END"],					"GLITER_ALCHEMYST_SECRET_BOSS_STAND_UP_BACK",			},
	},
}



GLITER_ALCHEMYST_SECRET_BOSS_DAMAGE_FLY_FRONT = 
{
	ANIM_NAME					= "DamageAirFlyFront",
	PLAY_TYPE					= XSKIN_ANIM_PLAYTYPE["XAP_ONE_WAIT"],
	TRANSITION					= FALSE,
	LAND_CONNECT				= FALSE,	
	
	CAN_PUSH_UNIT				= TRUE,
	CAN_PASS_UNIT				= FALSE,


	EVENT_PROCESS = 
	{
		{ STATE_CHANGE_TYPE["SCT_FOOT_ON_LINE_TRUE"],			"GLITER_ALCHEMYST_SECRET_BOSS_DAMAGE_DOWN_FRONT",		},
	},
}

GLITER_ALCHEMYST_SECRET_BOSS_DAMAGE_FLY_BACK = 
{
	ANIM_NAME					= "DamageAirFlyBack",
	PLAY_TYPE					= XSKIN_ANIM_PLAYTYPE["XAP_ONE_WAIT"],
	TRANSITION					= FALSE,
	LAND_CONNECT				= FALSE,	
	
	CAN_PUSH_UNIT				= TRUE,
	CAN_PASS_UNIT				= FALSE,
	
	EVENT_PROCESS = 
	{
		{ STATE_CHANGE_TYPE["SCT_FOOT_ON_LINE_TRUE"],			"GLITER_ALCHEMYST_SECRET_BOSS_DAMAGE_DOWN_BACK",		},
	},
}

GLITER_ALCHEMYST_SECRET_BOSS_DAMAGE_AIR = 
{
	ANIM_NAME					= "DamageAirSmall",
	PLAY_TYPE					= XSKIN_ANIM_PLAYTYPE["XAP_ONE_WAIT"],
	TRANSITION					= FALSE,
	LAND_CONNECT				= FALSE,
	
	CAN_PUSH_UNIT				= TRUE,
	CAN_PASS_UNIT				= FALSE,
	
	EVENT_PROCESS = 
	{
		{ STATE_CHANGE_TYPE["SCT_FOOT_ON_LINE_TRUE"],			"GLITER_ALCHEMYST_SECRET_BOSS_WAIT",					},
	},
}


GLITER_ALCHEMYST_SECRET_BOSS_DAMAGE_AIR_DOWN = 
{
	ANIM_NAME					= "DamageAirDown",
	PLAY_TYPE					= XSKIN_ANIM_PLAYTYPE["XAP_ONE_WAIT"],
	TRANSITION					= FALSE,
	LAND_CONNECT				= FALSE,
	
	CAN_PUSH_UNIT				= TRUE,
	CAN_PASS_UNIT				= FALSE,
	
	EVENT_PROCESS = 
	{
		{ STATE_CHANGE_TYPE["SCT_FOOT_ON_LINE_TRUE"],			"GLITER_ALCHEMYST_SECRET_BOSS_DAMAGE_AIR_DOWN_LANDING",	},
	},
}


GLITER_ALCHEMYST_SECRET_BOSS_DAMAGE_AIR_UP = 
{
	ANIM_NAME					= "DamageAirUp",
	PLAY_TYPE					= XSKIN_ANIM_PLAYTYPE["XAP_ONE_WAIT"],
	TRANSITION					= FALSE,
	LAND_CONNECT				= FALSE,
	
	CAN_PUSH_UNIT				= TRUE,
	CAN_PASS_UNIT				= FALSE,

	
	EVENT_PROCESS = 
	{
		{ STATE_CHANGE_TYPE["SCT_NEGATIVE_Y_SPEED"],		"GLITER_ALCHEMYST_SECRET_BOSS_DAMAGE_AIR_FALL",			},
		{ STATE_CHANGE_TYPE["SCT_FOOT_ON_LINE_TRUE"],		"GLITER_ALCHEMYST_SECRET_BOSS_DAMAGE_AIR_DOWN_LANDING",	},
	},
}


GLITER_ALCHEMYST_SECRET_BOSS_DAMAGE_AIR_FALL = 
{
	ANIM_NAME					= "DamageAirFall",
	PLAY_TYPE					= XSKIN_ANIM_PLAYTYPE["XAP_ONE_WAIT"],
	TRANSITION					= FALSE,
	LAND_CONNECT				= FALSE,
	
	CAN_PUSH_UNIT				= TRUE,
	CAN_PASS_UNIT				= FALSE,
	
	EVENT_PROCESS = 
	{
		{ STATE_CHANGE_TYPE["SCT_POSITIVE_Y_SPEED"],		"GLITER_ALCHEMYST_SECRET_BOSS_DAMAGE_AIR_UP",			},
		{ STATE_CHANGE_TYPE["SCT_FOOT_ON_LINE_TRUE"],		"GLITER_ALCHEMYST_SECRET_BOSS_DAMAGE_AIR_DOWN_LANDING",	},
	},
}

GLITER_ALCHEMYST_SECRET_BOSS_DAMAGE_AIR_DOWN_LANDING = 
{
	ANIM_NAME					= "DamageAirDownLanding",
	PLAY_TYPE					= XSKIN_ANIM_PLAYTYPE["XAP_ONE_WAIT"],
	TRANSITION					= FALSE,
	LAND_CONNECT				= FALSE,
	
	SUPER_ARMOR					= TRUE,
	DEFENCE						= { 0, 100, 70, },
	
	CAN_PUSH_UNIT				= TRUE,
	CAN_PASS_UNIT				= FALSE,
	
	EVENT_PROCESS = 
	{
		{ STATE_CHANGE_TYPE["SCT_FOOT_ON_LINE_FALSE_DOWN"],	"GLITER_ALCHEMYST_SECRET_BOSS_DAMAGE_AIR_FALL",			},
		{ STATE_CHANGE_TYPE["SCT_MOTION_END"],				"GLITER_ALCHEMYST_SECRET_BOSS_STAND_UP_FRONT",			},
	},
}

GLITER_ALCHEMYST_SECRET_BOSS_STAND_UP_FRONT = 
{
	ANIM_NAME					= "DamageStandUpFront",
	PLAY_TYPE					= XSKIN_ANIM_PLAYTYPE["XAP_ONE_WAIT"],
	TRANSITION					= FALSE,
	LAND_CONNECT				= FALSE,	
	
	SUPER_ARMOR					= TRUE,
	DEFENCE						= { 0, 100, 70, },
	
	CAN_PUSH_UNIT				= TRUE,
	CAN_PASS_UNIT				= FALSE,
	
	EVENT_PROCESS = 
	{
		{ STATE_CHANGE_TYPE["SCT_FOOT_ON_LINE_FALSE_DOWN"],	"GLITER_ALCHEMYST_SECRET_BOSS_JUMP_DOWN",			},
		{ STATE_CHANGE_TYPE["SCT_MOTION_END"],				"GLITER_ALCHEMYST_SECRET_BOSS_WAIT",				},
	},
}

GLITER_ALCHEMYST_SECRET_BOSS_STAND_UP_BACK = 
{
	ANIM_NAME					= "DamageStandUpBack",
	PLAY_TYPE					= XSKIN_ANIM_PLAYTYPE["XAP_ONE_WAIT"],
	TRANSITION					= FALSE,
	LAND_CONNECT				= FALSE,
	
	SUPER_ARMOR					= TRUE,
	DEFENCE						= { 0, 100, 70, },
		
	CAN_PUSH_UNIT				= TRUE,
	CAN_PASS_UNIT				= FALSE,
		
	EVENT_PROCESS = 
	{
		{ STATE_CHANGE_TYPE["SCT_FOOT_ON_LINE_FALSE_DOWN"],	"GLITER_ALCHEMYST_SECRET_BOSS_JUMP_DOWN", },
		{ STATE_CHANGE_TYPE["SCT_MOTION_END"],				"GLITER_ALCHEMYST_SECRET_BOSS_WAIT", },
	},		
}

GLITER_ALCHEMYST_SECRET_BOSS_DAMAGE_REVENGE = 
{
	ANIM_NAME					= "DamageFront",
	PLAY_TYPE					= XSKIN_ANIM_PLAYTYPE["XAP_ONE_WAIT"],
	TRANSITION					= FALSE,
	LAND_CONNECT				= FALSE,
	
	CAN_PUSH_UNIT				= TRUE,
	CAN_PASS_UNIT				= FALSE,

	
	EVENT_PROCESS = 
	{
		{ STATE_CHANGE_TYPE["SCT_FOOT_ON_LINE_FALSE_DOWN"],	"GLITER_ALCHEMYST_SECRET_BOSS_DAMAGE_AIR_FALL",			},
		{ STATE_CHANGE_TYPE["SCT_MOTION_END"],				"GLITER_ALCHEMYST_SECRET_BOSS_WAIT",					},
	},
}

GLITER_ALCHEMYST_SECRET_BOSS_DYING_LAND_FRONT = 
{
	ANIM_NAME					= "DamageDownFront",
	PLAY_TYPE					= XSKIN_ANIM_PLAYTYPE["XAP_ONE_WAIT"],
	TRANSITION					= FALSE,
	LAND_CONNECT				= FALSE,

	INVINCIBLE					= { 0, 100, }, 		

	CAN_PUSH_UNIT				= FALSE,
	CAN_PASS_UNIT				= TRUE,

    SOUND_PLAY0			= { 0.186, "Hoakin_Voice_Dying01.ogg" },
	
	DYING_END					= TRUE,
	
	IMMADIATE_PACKET_SEND		= TRUE,
}
	
GLITER_ALCHEMYST_SECRET_BOSS_DYING_LAND_BACK = 
{
	ANIM_NAME					= "DamageDownBack",
	PLAY_TYPE					= XSKIN_ANIM_PLAYTYPE["XAP_ONE_WAIT"],
	TRANSITION					= FALSE,
	LAND_CONNECT				= FALSE,
	
	INVINCIBLE					= { 0, 100, }, 		

	CAN_PUSH_UNIT				= FALSE,
	CAN_PASS_UNIT				= TRUE,

    SOUND_PLAY0			= { 0.291, "Hoakin_Voice_Dying01.ogg" },
	
	DYING_END					= TRUE,	
	
	IMMADIATE_PACKET_SEND		= TRUE,
}

GLITER_ALCHEMYST_SECRET_BOSS_DYING_SKY = 
{
	ANIM_NAME					= "DamageAirDownLanding",
	PLAY_TYPE					= XSKIN_ANIM_PLAYTYPE["XAP_ONE_WAIT"],
	TRANSITION					= FALSE,
	LAND_CONNECT				= FALSE,
	
	CAN_PUSH_UNIT				= FALSE,
	CAN_PASS_UNIT				= TRUE,

    SOUND_PLAY0			= { 0.186, "Hoakin_Voice_Dying01.ogg" },
	
	DYING_END					= TRUE,
	
	IMMADIATE_PACKET_SEND		= TRUE,
}


-- ATTACK


GLITER_ALCHEMYST_SECRET_BOSS_MAGIC_ATTACK_A =
{
	ANIM_NAME					= "Magic_Attack_A",
	PLAY_TYPE					= XSKIN_ANIM_PLAYTYPE["XAP_ONE_WAIT"],
	TRANSITION					= FALSE,
	LAND_CONNECT				= FALSE,
	
	CAN_PUSH_UNIT				= FALSE,
	CAN_PASS_UNIT				= FALSE,
	
	SUPER_ARMOR					= TRUE,

	SOUND_PLAY0 = 	{ 1.2, "Huge_Swing01.ogg", },

	
	EVENT_PROCESS = 
	{
		{ STATE_CHANGE_TYPE["SCT_FOOT_ON_LINE_FALSE_DOWN"],	"GLITER_ALCHEMYST_SECRET_BOSS_JUMP_DOWN",			},
		{ STATE_CHANGE_TYPE["SCT_MOTION_END"],				"GLITER_ALCHEMYST_SECRET_BOSS_WAIT",					},
	},
}

function GLITER_ALCHEMYST_SECRET_BOSS_MAGIC_ATTACK_A_FRAME_MOVE( pKTDXApp, pX2Game, pNPCUnit )

	if pNPCUnit:AnimEventTimer_LUA( 1.2 ) then
		
		local extraDamage = { "CURSE", "POISON", "REVERSE", "FIRE", "SLOW" }
		local num = pNPCUnit:GetRandVal() % 5 + 1
		local damageEffectName = "GLITER_ALCHEMYST_SECRET_MAGIC_ATTACK_A_" .. extraDamage[num]		
		local pDamageEffect = pX2Game:GetDamageEffect()
		local landPos = pNPCUnit:GetLandPosition_LUA()
		local pos = pNPCUnit:GetPos()
		pos.y = pos.y + 150
		pDamageEffect:CreateInstance_LUA( pNPCUnit, damageEffectName, pos, landPos.y )
	end
end


GLITER_ALCHEMYST_SECRET_BOSS_MAGIC_ATTACK_B =
{
	ANIM_NAME					= "MAGIC_ATTACK_B",
	PLAY_TYPE					= XSKIN_ANIM_PLAYTYPE["XAP_ONE_WAIT"],
	TRANSITION					= FALSE,
	LAND_CONNECT				= FALSE,
	
	CAN_PUSH_UNIT				= FALSE,
	CAN_PASS_UNIT				= FALSE,

	SUPER_ARMOR					= TRUE,
	
	SOUND_PLAY0 = 	{ 1.0, "ALCHEMYST_SECRET_MagicAttack_B01.ogg", },
	SOUND_PLAY1 = 	{ 2.45, "ALCHEMYST_SECRET_MagicAttack_B02.ogg", },
	SOUND_PLAY2	=   { 0.55, "Hoakin_Voice_Roar03.ogg" , 60 },
	
	EVENT_PROCESS = 
	{
		{ STATE_CHANGE_TYPE["SCT_FOOT_ON_LINE_FALSE_DOWN"],	"GLITER_ALCHEMYST_SECRET_BOSS_JUMP_DOWN",			},
		{ STATE_CHANGE_TYPE["SCT_MOTION_END"],				"GLITER_ALCHEMYST_SECRET_BOSS_WAIT",					},
	},
}

function GLITER_ALCHEMYST_SECRET_BOSS_MAGIC_ATTACK_B_FRAME_MOVE( pKTDXApp, pX2Game, pNPCUnit )

	if pNPCUnit:AnimEventTimer_LUA( 1.23 ) then
		local numUser = pX2Game:GetUserUnitNum_LUA()
		local numLiveUser = pX2Game:LiveUserUnitNum()		
		if numLiveUser > 0 then
			local pEffectSet = pX2Game:GetEffectSet()			
			local extraDamage = { "CURSE", "POISON", "REVERSE", "FIRE", "SLOW" }

			local numMagicAttackB = 1
			if numLiveUser >= 2 and numLiveUser <= 3 then
				numMagicAttackB = 2
			elseif numLiveUser >= 4 then
				numMagicAttackB = 3
			end

			local nUserInx = pNPCUnit:GetRandVal(0) % numUser			

			local nEffect = 1	
			while nEffect <= numMagicAttackB do
				local pTargetUser = pX2Game:GetUserUnit(nUserInx)
				if pTargetUser ~= nil and pTargetUser:GetNowHP() > 0.0 then
					local num = pNPCUnit:GetRandVal( numUser + nEffect ) % 5 + 1
					local effectsetName = "Effectset_ALCHEMYST_SECRET_BOSS_MAGIC_ATTACK_B_" .. extraDamage[num]			
					
					local vPos = pTargetUser:GetLandPosition_LUA()
					pEffectSet:PlayEffectSetWithCustomPos_LUA( effectsetName, pNPCUnit, vPos, D3DXVECTOR3( 0, 0, 0 ) )

					nEffect = nEffect + 1
				end

				nUserInx = nUserInx + 1
				if nUserInx >= numUser then
					nUserInx = 0
				end
			end

		end
	end
end

GLITER_ALCHEMYST_SECRET_BOSS_MAGIC_ATTACK_C =
{
	ANIM_NAME					= "MAGIC_ATTACK_C",
	PLAY_TYPE					= XSKIN_ANIM_PLAYTYPE["XAP_ONE_WAIT"],
	TRANSITION					= FALSE,
	LAND_CONNECT				= FALSE,
	
	CAN_PUSH_UNIT				= FALSE,
	CAN_PASS_UNIT				= FALSE,

	SUPER_ARMOR					= TRUE,
	SUPER_ARMOR_NOT_RED = TRUE,
	DEFENCE						= { 0, 100, 100, },
	NEVER_MOVE					= TRUE,

	IMMADIATE_PACKET_SEND		= TRUE,
	
	SOUND_PLAY0 = 	{ 0.85, "ALCHEMYST_SECRET_MagicAttack_C01.ogg", },
	SOUND_PLAY1 = 	{ 0.95, "ALCHEMYST_SECRET_MagicAttack_C02.ogg", },
	
	ALARM =
	{
		DANGER  				 = TRUE,  				    	    --DANGER 표시
		ALARM_MESSAGE 			 = STR_ID_15225,  		  		    --경고 문구
		DELAY   				 = 0,  				    	 		--이 스테이트가 시작되고 이 시간이 경과 후에 경고가 나갑니다.
		REPEAT   				 = TRUE,  		 		   		    --한 번만 반복 FALSE, 이 스테이트 취할때 마다 반복 TRUE
		ALARM_COLOR_TYPE		 = ALARM_COLOR_TYPE["ACT_ORANGE"],  --경고 문구 색깔 (ACT_RED, ACT_BLUE, ACT_YELLOW ,ACT_ORANGE, ACT_MAGENTA
		DISAPPEAR_TIME  		 = 6, 				  			    -- 표시 지속 시간
	},

	EVENT_PROCESS = 
	{
		{ STATE_CHANGE_TYPE["SCT_FOOT_ON_LINE_FALSE_DOWN"],	"GLITER_ALCHEMYST_SECRET_BOSS_JUMP_DOWN",			},
		{ STATE_CHANGE_TYPE["SCT_MOTION_END"],				"GLITER_ALCHEMYST_SECRET_BOSS_MAGIC_ATTACK_C_COMBO",					},
	},
}

function CF_GLITER_ALCHEMYST_SECRET_BOSS_MAGIC_ATTACK_C( pKTDXApp, pX2Game, pNPCUnit )

	local bIsChangedGameUnitScale = pNPCUnit:IsChangedGameUnitScaleByBuff()
	
	local maxHp = pNPCUnit:GetMaxHP()
	local nowHp = pNPCUnit:GetNowHP_LUA()

	local bOnLine = pNPCUnit:IsOnSomething_LUA()

	if bOnLine == true and false == bIsChangedGameUnitScale  then
		if pNPCUnit:GetFlag_LUA(0) == false and (nowHp / maxHp) < 0.7 then
			pNPCUnit:SetFlag_LUA(0, true)
			return true
		elseif pNPCUnit:GetFlag_LUA(1) == false and (nowHp / maxHp) < 0.4 then
			pNPCUnit:SetFlag_LUA(1, true)
			return true
		elseif pNPCUnit:GetFlag_LUA(2) == false and (nowHp / maxHp) < 0.1 then
			pNPCUnit:SetFlag_LUA(2, true)
			return true
		-- elseif pNPCUnit:GetFlag_LUA(2) == false and (nowHp / maxHp) < 0.2 then
			-- pNPCUnit:SetFlag_LUA(2, true)
			-- return true	
		else
			return false
		end
	else
		return false
	end
end

function GLITER_ALCHEMYST_SECRET_BOSS_MAGIC_ATTACK_C_STATE_START( pKTDXApp, pX2Game, pNPCUnit )
	
	pNPCUnit:SetInt_LUA( 0, 0 )
	pNPCUnit:SetInt_LUA( 1, 1 )	-- * 0.8 하여 animEventTimer로 사용

	local pEffectSet = pX2Game:GetEffectSet()
	local hEffectAttackC = pEffectSet:PlayEffectSet_LUA( "Effectset_ALCHEMYST_SECRET_BOSS_MAGIC_ATTACK_C", pNPCUnit )
	pNPCUnit:SetEffectSet_LUA( 0, hEffectAttackC )

end

GLITER_ALCHEMYST_SECRET_BOSS_MAGIC_ATTACK_C_COMBO =
{
	ANIM_NAME					= "MAGIC_ATTACK_C_COMBO_Start",
	PLAY_TYPE					= XSKIN_ANIM_PLAYTYPE["XAP_ONE_WAIT"],
	TRANSITION					= FALSE,
	LAND_CONNECT				= FALSE,
	
	CAN_PUSH_UNIT				= FALSE,
	CAN_PASS_UNIT				= FALSE,

	SUPER_ARMOR					= TRUE,
	SUPER_ARMOR_NOT_RED = TRUE,
	DEFENCE						= { 0, 100, 100, },
	NEVER_MOVE					= TRUE,

	IMMADIATE_PACKET_SEND		= TRUE,
	
	SOUND_PLAY0 = 	{ 0.7, "ALCHEMYST_SECRET_MagicAttackC_CcomboStart_01.ogg", },
	
	EVENT_PROCESS = 
	{
		{ STATE_CHANGE_TYPE["SCT_FOOT_ON_LINE_FALSE_DOWN"],	"GLITER_ALCHEMYST_SECRET_BOSS_JUMP_DOWN",			},
		{ STATE_CHANGE_TYPE["SCT_MOTION_END"],				"GLITER_ALCHEMYST_SECRET_BOSS_MAGIC_ATTACK_C_END",					},
	},
		
}

function GLITER_ALCHEMYST_SECRET_BOSS_MAGIC_ATTACK_C_COMBO_FRAME_MOVE( pKTDXApp, pX2Game, pNPCUnit )

	local nCount = pNPCUnit:GetInt_LUA( 1 )
	local HealTime = 0.8
	HealTime = HealTime * nCount
	
	if pNPCUnit:AnimEventTimer_LUA( HealTime ) then
		local maxHp = pNPCUnit:GetMaxHP()
		local nowHp = pNPCUnit:GetNowHP_LUA()
		pNPCUnit:SetNowHP_LUA( nowHp + maxHp * 0.03 )

		pNPCUnit:SetInt_LUA( 1, nCount + 1 )

		local pEffectSet = pX2Game:GetEffectSet()
		pEffectSet:PlayEffectSet_LUA( "EffectSet_ALCHEMYST_AIRELINNA_Heal", pNPCUnit )
	end

	if pNPCUnit:GetDamagedThisFrame() == true then
		local nAlchemystSecretBossDamageCount = pNPCUnit:GetInt_LUA( 0 )
		nAlchemystSecretBossDamageCount = nAlchemystSecretBossDamageCount + 1
		
		local pEffectSet = pX2Game:GetEffectSet()
		
		if nAlchemystSecretBossDamageCount >= 61 then ----- 91 대 째 마지면 피 체우는거 스탑
			pNPCUnit:StateChange_LUA( "GLITER_ALCHEMYST_SECRET_BOSS_MAGIC_ATTACK_C_END", true )
			local hEffectAttackC2 = pNPCUnit:GetEffectSet_LUA( 2 )
			if hEffectAttackC2 ~= 0 then
				pEffectSet:StopEffectSet_LUA( hEffectAttackC2 )
			end
			
			local hEffectAttackC1 = pNPCUnit:GetEffectSet_LUA( 1 )
			if hEffectAttackC1 ~= 0 then
				pEffectSet:StopEffectSet_LUA( hEffectAttackC1 )
			end
			
			local hEffectAttackC = pNPCUnit:GetEffectSet_LUA( 0 )
			if hEffectAttackC ~= 0 then
				pEffectSet:StopEffectSet_LUA( hEffectAttackC )
			end
		elseif nAlchemystSecretBossDamageCount >= 60 then  ---------90대에 마지막 보막 깨짐 
			
			local hEffectAttackC2 = pNPCUnit:GetEffectSet_LUA( 2 )
			if hEffectAttackC2 ~= 0 then
				pEffectSet:StopEffectSet_LUA( hEffectAttackC2 )
			end
			
			local hEffectAttackC1 = pNPCUnit:GetEffectSet_LUA( 1 )
			if hEffectAttackC1 ~= 0 then
				pEffectSet:StopEffectSet_LUA( hEffectAttackC1 )
			end
		elseif nAlchemystSecretBossDamageCount >= 40 then ---60대에서 깨짐(아래꺼 누적)
			local hEffectAttackC1 = pNPCUnit:GetEffectSet_LUA( 1 )
			if hEffectAttackC1 ~= 0 then
				pEffectSet:StopEffectSet_LUA( hEffectAttackC1 )
			end
			
			local hEffectAttackC = pNPCUnit:GetEffectSet_LUA( 0 )
			if hEffectAttackC ~= 0 then
				pEffectSet:StopEffectSet_LUA( hEffectAttackC )
			end
			
			local hEffectAttackC2 = pNPCUnit:GetEffectSet_LUA( 2 )
			if hEffectAttackC2 == 0 then
				hEffectAttackC2 = pEffectSet:PlayEffectSet_LUA( "Effectset_ALCHEMYST_SECRET_BOSS_MAGIC_ATTACK_C03", pNPCUnit )
				pNPCUnit:SetEffectSet_LUA( 2 )
			end
		elseif nAlchemystSecretBossDamageCount >= 20 then  --누적으로 들어감 (첫번째 보막 깨지는 타격 30대에서 깨짐)
			local hEffectAttackC = pNPCUnit:GetEffectSet_LUA( 0 )
			if hEffectAttackC ~= 0 then
				pEffectSet:StopEffectSet_LUA( hEffectAttackC )
			end
			
			local hEffectAttackC1 = pNPCUnit:GetEffectSet_LUA( 1 )
			if hEffectAttackC1 == 0 then
				hEffectAttackC1 = pEffectSet:PlayEffectSet_LUA( "Effectset_ALCHEMYST_SECRET_BOSS_MAGIC_ATTACK_C02", pNPCUnit )
				pNPCUnit:SetEffectSet_LUA( 1 )
			end
		end
	end

end

GLITER_ALCHEMYST_SECRET_BOSS_MAGIC_ATTACK_C_END =
{
	ANIM_NAME					= "MAGIC_ATTACK_C_COMBO_End",
	PLAY_TYPE					= XSKIN_ANIM_PLAYTYPE["XAP_ONE_WAIT"],
	TRANSITION					= FALSE,
	LAND_CONNECT				= FALSE,
	
	CAN_PUSH_UNIT				= FALSE,
	CAN_PASS_UNIT				= FALSE,
	
	SUPER_ARMOR					= TRUE,

	IMMADIATE_PACKET_SEND		= TRUE,
	
	SOUND_PLAY0 = 	{ 0.45, "ALCHEMYST_SECRET_MagicAttackC_CcomboEnd_01.ogg", },

	EVENT_PROCESS = 
	{
		{ STATE_CHANGE_TYPE["SCT_FOOT_ON_LINE_FALSE_DOWN"],	"GLITER_ALCHEMYST_SECRET_BOSS_JUMP_DOWN",			},
		{ STATE_CHANGE_TYPE["SCT_MOTION_END"],				"GLITER_ALCHEMYST_SECRET_BOSS_WAIT",					},
	},
}

function GLITER_ALCHEMYST_SECRET_BOSS_MAGIC_ATTACK_C_END_STATE_START( pKTDXApp, pX2Game, pNPCUnit )
	local pEffectSet = pX2Game:GetEffectSet()
	
	local hEffectAttackC2 = pNPCUnit:GetEffectSet_LUA( 2 )
	if hEffectAttackC2 ~= 0 then
		pEffectSet:StopEffectSet_LUA( hEffectAttackC2 )
	end
	
	local hEffectAttackC1 = pNPCUnit:GetEffectSet_LUA( 1 )
	if hEffectAttackC1 ~= 0 then
		pEffectSet:StopEffectSet_LUA( hEffectAttackC1 )
	end
	
	local hEffectAttackC = pNPCUnit:GetEffectSet_LUA( 0 )
	if hEffectAttackC ~= 0 then
		pEffectSet:StopEffectSet_LUA( hEffectAttackC )
	end
end

GLITER_ALCHEMYST_SECRET_BOSS_MAGIC_ATTACK_D =
{
	ANIM_NAME					= "Magic_Attack_D",
	PLAY_TYPE					= XSKIN_ANIM_PLAYTYPE["XAP_ONE_WAIT"],
	TRANSITION					= FALSE,
	LAND_CONNECT				= TRUE,
	
	CAN_PUSH_UNIT				= TRUE,
	CAN_PASS_UNIT				= FALSE,
	
	SUPER_ARMOR					= TRUE,
	NEVER_MOVE					= TRUE,

	VIEW_TARGET					= TRUE,
	IMMADIATE_PACKET_SEND		= TRUE,
	
	EVENT_PROCESS = 
	{		
		{ STATE_CHANGE_TYPE["SCT_FOOT_ON_LINE_FALSE_DOWN"],	"GLITER_ALCHEMYST_SECRET_BOSS_JUMP_DOWN",			},
		{ STATE_CHANGE_TYPE["SCT_MOTION_END"],				"GLITER_ALCHEMYST_SECRET_BOSS_WAIT",				},
	},

	SOUND_PLAY0 = 	{ 0.929, "Gliter_Alchemyst_AttackBComboCloud.ogg", },
	SOUND_PLAY1 = 	{ 2.221, "Gliter_Alchemyst_SlashStick.ogg", },
	SOUND_PLAY2	=   { 1.75, "Hoakin_Voice_Roar02.ogg", 60 },
	
	EFFECT_SET_LIST =
	{
		"ALCHEMYST_SECRET_BOSS_MAGIC_ATTACK_D", 0.0,
	},
}

GLITER_ALCHEMYST_SECRET_BOSS_MAGIC_ATTACK_E =
{
	ANIM_NAME					= "Magic_Attack_E",
	PLAY_TYPE					= XSKIN_ANIM_PLAYTYPE["XAP_ONE_WAIT"],
	TRANSITION					= FALSE,
	LAND_CONNECT				= FALSE,
	
	CAN_PUSH_UNIT				= FALSE,
	CAN_PASS_UNIT				= FALSE,

	SUPER_ARMOR					= TRUE,
	NEVER_MOVE					= TRUE,

	IMMADIATE_PACKET_SEND		= TRUE,

	SOUND_PLAY0 = 	{ 0.2, "ALCHEMYST_SECRET_MagicAttack_E01.ogg", },
	
	ALARM =
	{
		DANGER  				 = TRUE,  				    	    --DANGER 표시
		ALARM_MESSAGE 			 = STR_ID_15226,  		  		    --경고 문구
		DELAY   				 = 0,  				    	 		--이 스테이트가 시작되고 이 시간이 경과 후에 경고가 나갑니다.
		REPEAT   				 = TRUE,  		 		   		    --한 번만 반복 FALSE, 이 스테이트 취할때 마다 반복 TRUE
		ALARM_COLOR_TYPE		 = ALARM_COLOR_TYPE["ACT_ORANGE"],  --경고 문구 색깔 (ACT_RED, ACT_BLUE, ACT_YELLOW ,ACT_ORANGE, ACT_MAGENTA
		DISAPPEAR_TIME  		 = 5, 				  			    -- 표시 지속 시간
	},
	
	EVENT_PROCESS = 
	{
		{ STATE_CHANGE_TYPE["SCT_FOOT_ON_LINE_FALSE_DOWN"],	"GLITER_ALCHEMYST_SECRET_BOSS_JUMP_DOWN",			},
		{ STATE_CHANGE_TYPE["SCT_MOTION_END"],				"GLITER_ALCHEMYST_SECRET_BOSS_WAIT",					},
	},

	EFFECT_SET_LIST =
	{
		"Effectset_ALCHEMYST_SECRET_BOSS_SPECIAL_ATTACK_E", 0.0,
	},	
	DELETE_EFFECT_SET_ON_STATE_END = TRUE,
}

function GLITER_ALCHEMYST_SECRET_BOSS_MAGIC_ATTACK_E_FRAME_MOVE( pKTDXApp, pX2Game, pNPCUnit )

	if pNPCUnit:AnimEventTimer_LUA( 3.0 ) then
		
		local numUser = pX2Game:GetUserUnitListSize() - 1
		local numLiveUser = pX2Game:LiveUserUnitNum()		
		if numLiveUser > 0 then
			
			local nUserInx = pNPCUnit:GetRandVal(0) % numLiveUser			

			local iIndex = 0
			local nCount = 0

			for iIndex = 0, numUser do
				local pTargetUser = pX2Game:GetUserUnit(iIndex)
				if pTargetUser ~= nil and pTargetUser:GetNowHP() > 0.0 then
					nCount = nCount + 1

					if nCount - 1 == nUserInx then
						pTargetUser:SetBuffFactorToGameUnitByBuffFactorID_LUA( BUFF_FACTOR_ID["BFI_DEBUFF_ATTACK_ALL_TEAM"] )
						return
					end
				end 
			end
		end
	end
end

GLITER_ALCHEMYST_SECRET_BOSS_SPECIAL_ATTACK_A =
{
	ANIM_NAME					= "SPECIAL_ATTACK_A",
	PLAY_TYPE					= XSKIN_ANIM_PLAYTYPE["XAP_ONE_WAIT"],
	TRANSITION					= FALSE,
	LAND_CONNECT				= FALSE,
	
	CAN_PUSH_UNIT				= FALSE,
	CAN_PASS_UNIT				= FALSE,

	SUPER_ARMOR					= TRUE,
	NEVER_MOVE					= TRUE,
	
	SOUND_PLAY0				= { 0.45, "Hoakin_Voice_SpeacialAttackA01.ogg", 100 },
	
	EVENT_PROCESS = 
	{
		{ STATE_CHANGE_TYPE["SCT_FOOT_ON_LINE_FALSE_DOWN"],	"GLITER_ALCHEMYST_SECRET_BOSS_JUMP_DOWN",			},
		{ STATE_CHANGE_TYPE["SCT_MOTION_END"],				"GLITER_ALCHEMYST_SECRET_BOSS_WAIT",					},
	},

	EFFECT_SET_LIST =
	{
		"Effectset_VELDER_SECRET_BOSS_SPECIAL_ATTACK_A", 0.0,
	},	
}

function GLITER_ALCHEMYST_SECRET_BOSS_SPECIAL_ATTACK_A_STATE_START( pKTDXApp, pX2Game, pNPCUnit )
	pX2Game:KillNPC( NPC_UNIT_ID["NUI_VELDER_WRECK1"], 4 )
	pX2Game:KillNPC( NPC_UNIT_ID["NUI_VELDER_WRECK2"], 4 )
	pX2Game:KillNPC( NPC_UNIT_ID["NUI_VELDER_WRECK4"], 4 )
end

function GLITER_ALCHEMYST_SECRET_BOSS_SPECIAL_ATTACK_A_FRAME_MOVE( pKTDXApp, pX2Game, pNPCUnit )

	if pNPCUnit:AnimEventTimer_LUA( 2.0 ) then

		-- 건물 소환
		local summonNpcG = { NPC_UNIT_ID["NUI_VELDER_WRECK1"], NPC_UNIT_ID["NUI_VELDER_WRECK2"], NPC_UNIT_ID["NUI_VELDER_WRECK4"], }
		local summonG1 = { 29, 28, 27, 26, 25, 24, }
		local summonG2 = { 23, 22, 21, 20, 19, 18, 17, }
		local summonG3 = { 16, 15, 14, 1, 2, 3, 4, }
		local summonG4 = { 5, 6, 7, 11, 12, 13, }

		local randStartPosIndex = pNPCUnit:GetRandVal(0) % 6 +1
		local summonStartPos1 = summonG1[ randStartPosIndex ]
		randStartPosIndex = pNPCUnit:GetRandVal(1) % 7 +1
		local summonStartPos2 = summonG2[ randStartPosIndex ]
		randStartPosIndex = pNPCUnit:GetRandVal(2) % 7 +1
		local summonStartPos3 = summonG3[ randStartPosIndex ]
		randStartPosIndex = pNPCUnit:GetRandVal(3) % 6 +1
		local summonStartPos4 = summonG4[ randStartPosIndex ]
				

		local summonNpc = pNPCUnit:GetRandVal(4) % 3 +1
		local vSummonPos = pX2Game:GetLineMap():GetStartPosition( summonStartPos1 )
		pX2Game:PushCreateNPCReq_Lua( summonNpcG[summonNpc], pNPCUnit:GetHardLevel(), false, vSummonPos, true, 0.5, true, 0  )
		
		summonNpc = pNPCUnit:GetRandVal(5) % 3 +1
		vSummonPos = pX2Game:GetLineMap():GetStartPosition( summonStartPos2 )
		pX2Game:PushCreateNPCReq_Lua( summonNpcG[summonNpc], pNPCUnit:GetHardLevel(), false, vSummonPos, true, 1.5, true, 0  )

		summonNpc = pNPCUnit:GetRandVal(6) % 3 +1
		vSummonPos = pX2Game:GetLineMap():GetStartPosition( summonStartPos3 )
		pX2Game:PushCreateNPCReq_Lua( summonNpcG[summonNpc], pNPCUnit:GetHardLevel(), false, vSummonPos, true, 1.5, true, 0  )

		summonNpc = pNPCUnit:GetRandVal(7) % 3 +1
		vSummonPos = pX2Game:GetLineMap():GetStartPosition( summonStartPos4 )
		pX2Game:PushCreateNPCReq_Lua( summonNpcG[summonNpc], pNPCUnit:GetHardLevel(), false, vSummonPos, true, 1.5, true, 0  )
		
		pX2Game:FlushCreateNPCReq()
	end
end

GLITER_ALCHEMYST_SECRET_BOSS_SPECIAL_ATTACK_B =
{
	ANIM_NAME					= "SPECIAL_ATTACK_B",
	PLAY_TYPE					= XSKIN_ANIM_PLAYTYPE["XAP_ONE_WAIT"],
	TRANSITION					= FALSE,
	LAND_CONNECT				= FALSE,
	
	CAN_PUSH_UNIT				= FALSE,
	CAN_PASS_UNIT				= FALSE,

	SUPER_ARMOR					= TRUE,
	NEVER_MOVE					= TRUE,
	
	SOUND_PLAY0				= { 0.45, "Hoakin_Voice_Stage03_SummonA01.ogg", 100 },
	
	EVENT_PROCESS = 
	{
		{ STATE_CHANGE_TYPE["SCT_FOOT_ON_LINE_FALSE_DOWN"],	"GLITER_ALCHEMYST_SECRET_BOSS_JUMP_DOWN",			},
		{ STATE_CHANGE_TYPE["SCT_MOTION_END"],				"GLITER_ALCHEMYST_SECRET_BOSS_WAIT",					},
	},

}

function GLITER_ALCHEMYST_SECRET_BOSS_SPECIAL_ATTACK_B_FRAME_MOVE( pKTDXApp, pX2Game, pNPCUnit )

	if pNPCUnit:AnimEventTimer_LUA( 2.0 ) then
		
		local numLiveNpc = pX2Game:LiveNPCNumType_LUA( NPC_UNIT_ID["NUI_GLITER_TOMBSTONE"] )
	
		if numLiveNpc >= 1 then
			return
		end
				
		local vSummonPos = pX2Game:GetLineMap():GetStartPosition(29)
		pX2Game:PushCreateNPCReq_Lua( NPC_UNIT_ID["NUI_GLITER_TOMBSTONE"], pNPCUnit:GetHardLevel(), false, vSummonPos, false, 0.7, true, 0  )
				
		vSummonPos = pX2Game:GetLineMap():GetStartPosition(13)
		pX2Game:PushCreateNPCReq_Lua( NPC_UNIT_ID["NUI_GLITER_TOMBSTONE"], pNPCUnit:GetHardLevel(), false, vSummonPos, true, 0.7, true, 0  )

		pX2Game:FlushCreateNPCReq()
	end
end

GLITER_ALCHEMYST_SECRET_BOSS_SPECIAL_ATTACK_C =
{
	ANIM_NAME					= "SPECIAL_ATTACK_C",
	PLAY_TYPE					= XSKIN_ANIM_PLAYTYPE["XAP_ONE_WAIT"],
	TRANSITION					= FALSE,
	LAND_CONNECT				= FALSE,
	
	CAN_PUSH_UNIT				= FALSE,
	CAN_PASS_UNIT				= FALSE,

	SUPER_ARMOR					= TRUE,
	NEVER_MOVE					= TRUE,
	
	SOUND_PLAY0				= { 2.05, "Hoakin_Voice_Roar04.ogg", 60 },
	
	EVENT_PROCESS = 
	{
		{ STATE_CHANGE_TYPE["SCT_FOOT_ON_LINE_FALSE_DOWN"],	"GLITER_ALCHEMYST_SECRET_BOSS_JUMP_DOWN",			},
		{ STATE_CHANGE_TYPE["SCT_MOTION_END"],				"GLITER_ALCHEMYST_SECRET_BOSS_WAIT",					},
	},

	EFFECT_SET_LIST =
	{
		"Effectset_VELDER_SECRET_BOSS_SPECIAL_C", 0.0,
	},	
	
}

function GLITER_ALCHEMYST_SECRET_BOSS_SPECIAL_ATTACK_C_FRAME_MOVE( pKTDXApp, pX2Game, pNPCUnit )

	if pNPCUnit:AnimEventTimer_LUA( 2.2 ) then
				
		local numLiveNpc = pX2Game:LiveNPCNumType_LUA( NPC_UNIT_ID["NUI_CRAZY_PUPPET_DOLL"] )
	
		if numLiveNpc >= 6 then
			return
		end

		local iRandStart = pX2Game:GetLineMap():GetRandomStartPosIndex_LUA()
		local vSummonPos = pX2Game:GetLineMap():GetStartPosition(iRandStart)
		pX2Game:PushCreateNPCReq_Lua( NPC_UNIT_ID["NUI_CRAZY_PUPPET_DOLL"], pNPCUnit:GetHardLevel(), true, vSummonPos, true, 0.5, true, 0  )
				
		iRandStart = pX2Game:GetLineMap():GetRandomStartPosIndex_LUA()
		vSummonPos = pX2Game:GetLineMap():GetStartPosition(iRandStart)
		pX2Game:PushCreateNPCReq_Lua( NPC_UNIT_ID["NUI_CRAZY_PUPPET_DOLL"], pNPCUnit:GetHardLevel(), true, vSummonPos, false, 0.5, true, 0  )

		iRandStart = pX2Game:GetLineMap():GetRandomStartPosIndex_LUA()
		vSummonPos = pX2Game:GetLineMap():GetStartPosition(iRandStart)
		pX2Game:PushCreateNPCReq_Lua( NPC_UNIT_ID["NUI_CRAZY_PUPPET_DOLL"], pNPCUnit:GetHardLevel(), true, vSummonPos, true, 1, true, 0  )
				
		iRandStart = pX2Game:GetLineMap():GetRandomStartPosIndex_LUA()
		vSummonPos = pX2Game:GetLineMap():GetStartPosition(iRandStart)
		pX2Game:PushCreateNPCReq_Lua( NPC_UNIT_ID["NUI_CRAZY_PUPPET_DOLL"], pNPCUnit:GetHardLevel(), true, vSummonPos, true, 1, true, 0  )

		iRandStart = pX2Game:GetLineMap():GetRandomStartPosIndex_LUA()
		vSummonPos = pX2Game:GetLineMap():GetStartPosition(iRandStart)
		pX2Game:PushCreateNPCReq_Lua( NPC_UNIT_ID["NUI_CRAZY_PUPPET_DOLL"], pNPCUnit:GetHardLevel(), true, vSummonPos, false, 1.5, true, 0  )

		iRandStart = pX2Game:GetLineMap():GetRandomStartPosIndex_LUA()
		vSummonPos = pX2Game:GetLineMap():GetStartPosition(iRandStart)
		pX2Game:PushCreateNPCReq_Lua( NPC_UNIT_ID["NUI_CRAZY_PUPPET_DOLL"], pNPCUnit:GetHardLevel(), true, vSummonPos, false, 1.5, true, 0  )

		pX2Game:FlushCreateNPCReq()
	end
end

GLITER_ALCHEMYST_SECRET_BOSS_REAL_SPECIAL_ATTACK =
{
	ANIM_NAME					= "Special_Attack_D",
	PLAY_TYPE					= XSKIN_ANIM_PLAYTYPE["XAP_ONE_WAIT"],
	TRANSITION					= FALSE,
	LAND_CONNECT				= FALSE,
	
	CAN_PUSH_UNIT				= FALSE,
	CAN_PASS_UNIT				= FALSE,

	SUPER_ARMOR					= TRUE,
	NEVER_MOVE					= TRUE,
	
	SOUND_PLAY0				= { 0.75, "ALCHEMYST_SECRET_SpecialAttackD01.ogg",100,FALSE, -1, FALSE },
	SOUND_PLAY1				= { 0.45, "Hoakin_Voice_Roar02.ogg", 60 },
	
	EVENT_PROCESS = 
	{
		{ STATE_CHANGE_TYPE["SCT_FOOT_ON_LINE_FALSE_DOWN"],	"GLITER_ALCHEMYST_SECRET_BOSS_JUMP_DOWN",			},
		{ STATE_CHANGE_TYPE["SCT_MOTION_END"],				"GLITER_ALCHEMYST_SECRET_BOSS_WAIT",					},
	},
	

	EFFECT_SET_LIST =
	{
		"EffectSet_Velder_Secret_Boss_SpecialAttack_Cloud", 0.0,
	},	
}

function GLITER_ALCHEMYST_SECRET_BOSS_REAL_SPECIAL_ATTACK_STATE_START( pKTDXApp, pX2Game, pNPCUnit )
	fAttackTime = 1
	pX2Game:SetWorldColor_LUA( D3DXCOLOR(0.2,0.2,0.2,1) )
end

function GLITER_ALCHEMYST_SECRET_BOSS_REAL_SPECIAL_ATTACK_FRAME_MOVE( pKTDXApp, pX2Game, pNPCUnit )

	if fAttackTime >= 10 then
		return
	end

	if pNPCUnit:AnimEventTimer_LUA( fAttackTime ) then

		local pEffectSet = pX2Game:GetEffectSet()
		local userListSize = pX2Game:GetUserUnitNum_LUA() - 1
	
		for i = 0, userListSize do
			local pUser = pX2Game:GetUserUnit( i )
			if pUser ~= nil then
				if pUser:GetNowHP() > 0 then
					local vCenterPos = pNPCUnit:GetLandPosition_LUA()
					local vPos = pUser:GetLandPosition_LUA()
					if GetDistance_LUA( vCenterPos, vPos ) < 1700 then
						pEffectSet:PlayEffectSetWithCustomPos_LUA( "EffectSet_Velder_Secret_Boss_SpecialAttack_Lightning", pNPCUnit, vPos, D3DXVECTOR3( 0, 0, 0 ) )
					end
				end
			end
		end

		fAttackTime = fAttackTime + 1.2
	end
end

GLITER_ALCHEMYST_SECRET_BOSS_DRINK_POTION =
{
	ANIM_NAME					= "DrinkPotion",
	PLAY_TYPE					= XSKIN_ANIM_PLAYTYPE["XAP_ONE_WAIT"],
	TRANSITION					= FALSE,
	LAND_CONNECT				= FALSE,
	
	CAN_PUSH_UNIT				= FALSE,
	CAN_PASS_UNIT				= FALSE,

	SUPER_ARMOR					= TRUE,
	
	SOUND_PLAY0 = 	{ 0.7, "Gliter_Alchemyst_DrinkPotion.ogg", },
	
	ALARM =
	{
		DANGER  				 = TRUE,  				    	    --DANGER 표시
		ALARM_MESSAGE 			 = STR_ID_15223,  		  		    --경고 문구
		DELAY   				 = 0,  				    	 		--이 스테이트가 시작되고 이 시간이 경과 후에 경고가 나갑니다.
		REPEAT   				 = TRUE,  		 		   		    --한 번만 반복 FALSE, 이 스테이트 취할때 마다 반복 TRUE
		ALARM_COLOR_TYPE		 = ALARM_COLOR_TYPE["ACT_ORANGE"],  --경고 문구 색깔 (ACT_RED, ACT_BLUE, ACT_YELLOW ,ACT_ORANGE, ACT_MAGENTA
		DISAPPEAR_TIME  		 = 5, 				  			    -- 표시 지속 시간
	},
	
	EVENT_PROCESS = 
	{
		{ STATE_CHANGE_TYPE["SCT_FOOT_ON_LINE_FALSE_DOWN"],	"GLITER_ALCHEMYST_SECRET_BOSS_JUMP_DOWN",			},
		{ STATE_CHANGE_TYPE["SCT_MOTION_END"],				"GLITER_ALCHEMYST_SECRET_BOSS_DRINK_POTION_COMBO",					},
	},
		
}

function CF_GLITER_ALCHEMYST_SECRET_BOSS_DRINK_POTION( pKTDXApp, pX2Game, pNPCUnit )
	local bIsChangedGameUnitScale = pNPCUnit:IsChangedGameUnitScaleByBuff()
	
	local maxHp = pNPCUnit:GetMaxHP()
	local nowHp = pNPCUnit:GetNowHP_LUA()

	local bOnLine = pNPCUnit:IsOnSomething_LUA()

	if bOnLine == true and false == bIsChangedGameUnitScale then
		if pNPCUnit:GetFlag_LUA(3) == false and (nowHp / maxHp) < 0.8 then
			pNPCUnit:SetFlag_LUA(3, true)
			return true
		elseif pNPCUnit:GetFlag_LUA(4) == false and (nowHp / maxHp) < 0.6 then
			pNPCUnit:SetFlag_LUA(4, true)
			return true
		elseif pNPCUnit:GetFlag_LUA(5) == false and (nowHp / maxHp) < 0.4 then
			pNPCUnit:SetFlag_LUA(5, true)
			return true
		elseif pNPCUnit:GetFlag_LUA(6) == false and (nowHp / maxHp) < 0.2 then
			pNPCUnit:SetFlag_LUA(6, true)
			return true
		else
			return false
		end
	else
		return false
	end
end

function GLITER_ALCHEMYST_SECRET_BOSS_DRINK_POTION_FRAME_MOVE( pKTDXApp, pX2Game, pNPCUnit )
	
end

GLITER_ALCHEMYST_SECRET_BOSS_DRINK_POTION_COMBO =
{
	ANIM_NAME					= "DarkCloud",
	PLAY_TYPE					= XSKIN_ANIM_PLAYTYPE["XAP_ONE_WAIT"],
	TRANSITION					= FALSE,
	LAND_CONNECT				= FALSE,
	
	CAN_PUSH_UNIT				= FALSE,
	CAN_PASS_UNIT				= FALSE,

	SUPER_ARMOR					= TRUE,
	
	SOUND_PLAY0				= { 0.45, "Hoakin_Voice_Roar01.ogg", 100 },
	SOUND_PLAY1				= { 0.65, "ALCHEMYST_GREAT_BOSS_Stage1_WaitStart01.ogg", 100, FALSE, -1.0, FALSE },
	
	EVENT_PROCESS = 
	{
		{ STATE_CHANGE_TYPE["SCT_FOOT_ON_LINE_FALSE_DOWN"],	"GLITER_ALCHEMYST_SECRET_BOSS_JUMP_DOWN",			},
		{ STATE_CHANGE_TYPE["SCT_MOTION_END"],				"GLITER_ALCHEMYST_SECRET_BOSS_WAIT",					},
	},
}

function GLITER_ALCHEMYST_SECRET_BOSS_DRINK_POTION_COMBO_FRAME_MOVE( pKTDXApp, pX2Game, pNPCUnit )

	if pNPCUnit:AnimEventTimer_LUA( 1.54 ) then
		local pDamageEffect = pX2Game:GetDamageEffect()
		local vPos = pNPCUnit:GetBonePos_LUA("Bip01_Spine")		
		local vLandPos = pNPCUnit:GetLandPosition_LUA()		

		local vOriRotDegree = pNPCUnit:GetRotateDegree()
		local vRot1 = pNPCUnit:GetRotateDegree()
		local vRot2 = pNPCUnit:GetRotateDegree()
		local vRot3 = pNPCUnit:GetRotateDegree()
		local vRot4 = pNPCUnit:GetRotateDegree()
		local vRotInv1 = pNPCUnit:GetRotateDegree()
		local vRotInv2 = pNPCUnit:GetRotateDegree()
		local vRotInv3 = pNPCUnit:GetRotateDegree()
		local vRotInv4 = pNPCUnit:GetRotateDegree()

		vRot1.z = vOriRotDegree.z + 20
		vRot2.z = vOriRotDegree.z + 40
		vRot3.z = vOriRotDegree.z + 60
		vRot4.z = vOriRotDegree.z + 80
		vRotInv1.z = vOriRotDegree.z - 20
		vRotInv2.z = vOriRotDegree.z - 40
		vRotInv3.z = vOriRotDegree.z - 60
		vRotInv4.z = vOriRotDegree.z - 80
		
		pDamageEffect:CreateInstance_LUA2( pNPCUnit, "ALCHEMYST_SECRET_BOSS_GHOS_INVERSE", vPos, vLandPos.y, vOriRotDegree )
		pDamageEffect:CreateInstance_LUA2( pNPCUnit, "ALCHEMYST_SECRET_BOSS_GHOS_INVERSE", vPos, vLandPos.y, vRotInv1 )
		pDamageEffect:CreateInstance_LUA2( pNPCUnit, "ALCHEMYST_SECRET_BOSS_GHOS_INVERSE", vPos, vLandPos.y, vRotInv2 )
		pDamageEffect:CreateInstance_LUA2( pNPCUnit, "ALCHEMYST_SECRET_BOSS_GHOS_INVERSE", vPos, vLandPos.y, vRotInv3 )
		pDamageEffect:CreateInstance_LUA2( pNPCUnit, "ALCHEMYST_SECRET_BOSS_GHOS_INVERSE", vPos, vLandPos.y, vRotInv4 )
		
		pDamageEffect:CreateInstance_LUA2( pNPCUnit, "ALCHEMYST_SECRET_BOSS_GHOS", vPos, vLandPos.y, vOriRotDegree )
		pDamageEffect:CreateInstance_LUA2( pNPCUnit, "ALCHEMYST_SECRET_BOSS_GHOS", vPos, vLandPos.y, vRot1 )
		pDamageEffect:CreateInstance_LUA2( pNPCUnit, "ALCHEMYST_SECRET_BOSS_GHOS", vPos, vLandPos.y, vRot2 )
		pDamageEffect:CreateInstance_LUA2( pNPCUnit, "ALCHEMYST_SECRET_BOSS_GHOS", vPos, vLandPos.y, vRot3 )
		pDamageEffect:CreateInstance_LUA2( pNPCUnit, "ALCHEMYST_SECRET_BOSS_GHOS", vPos, vLandPos.y, vRot4 )
		
	end

	if pNPCUnit:AnimEventTimer_LUA( 1.6 ) then
		pNPCUnit:SetBuffFactorToGameUnitByBuffFactorID_LUA( BUFF_FACTOR_ID["BFI_NPC_ALCHEMYST_SECRET_BOSS_TRANSFORM_SCALE"] )
	end
end

-- 걸어다닐때 연기 

--**
function GLITER_ALCHEMYST_SECRET_BOSS_JUMP_LANDING_STATE_START( pKTDXApp, pX2Game, pNPCUnit )
	local pMinorParticle = pX2Game:GetMinorParticle()
	pMinorParticle:GameUnitCreateSequence_LUA( pNPCUnit, "StepSmoke", pNPCUnit:GetLandPosition_LUA(), D3DXVECTOR2(100,100), D3DXVECTOR2(5,-1) )
end

--**
function GLITER_ALCHEMYST_SECRET_BOSS_DASH_STATE_END( pKTDXApp, pX2Game, pNPCUnit )
	local pMinorParticle = pX2Game:GetMinorParticle()
	pMinorParticle:GameUnitCreateSequence_LUA( pNPCUnit, "StepSmoke", pNPCUnit:GetLandPosition_LUA(), D3DXVECTOR2(100,100), D3DXVECTOR2(5,-1) )
end

--**
function GLITER_ALCHEMYST_SECRET_BOSS_DAMAGE_BACK_FRAME_MOVE( pKTDXApp, pX2Game, pNPCUnit )
	if pNPCUnit:AnimEventTimer_LUA( 0.500 ) then
		local pMinorParticle = pX2Game:GetMinorParticle()
		pMinorParticle:GameUnitCreateSequence_LUA( pNPCUnit, "StepSmoke", pNPCUnit:GetLandPosition_LUA(), D3DXVECTOR2(100,100), D3DXVECTOR2(5,-1) )
	end
end

--**
function GLITER_ALCHEMYST_SECRET_BOSS_DAMAGE_FRONT_FRAME_MOVE( pKTDXApp, pX2Game, pNPCUnit )
	if pNPCUnit:AnimEventTimer_LUA( 0.577 ) then
		local pMinorParticle = pX2Game:GetMinorParticle()
		pMinorParticle:GameUnitCreateSequence_LUA( pNPCUnit, "StepSmoke", pNPCUnit:GetLandPosition_LUA(), D3DXVECTOR2(100,100), D3DXVECTOR2(5,-1) )
	end
end

--**
function GLITER_ALCHEMYST_SECRET_BOSS_DAMAGE_DOWN_FRONT_STATE_START( pKTDXApp, pX2Game, pNPCUnit )
	local pMinorParticle = pX2Game:GetMinorParticle()
	pMinorParticle:GameUnitCreateSequence_LUA( pNPCUnit, "StepSmoke", pNPCUnit:GetLandPosition_LUA(), D3DXVECTOR2(100,100), D3DXVECTOR2(5,-1) )

end

--**
function GLITER_ALCHEMYST_SECRET_BOSS_DAMAGE_DOWN_BACK_STATE_START( pKTDXApp, pX2Game, pNPCUnit )
 	local pMinorParticle = pX2Game:GetMinorParticle()
	pMinorParticle:GameUnitCreateSequence_LUA( pNPCUnit, "StepSmoke", pNPCUnit:GetLandPosition_LUA(), D3DXVECTOR2(100,100), D3DXVECTOR2(5,-1) )
end

--**
function GLITER_ALCHEMYST_SECRET_BOSS_DAMAGE_AIR_DOWN_LANDING_STATE_START( pKTDXApp, pX2Game, pNPCUnit )
	local pMinorParticle = pX2Game:GetMinorParticle()
	pMinorParticle:GameUnitCreateSequence_LUA( pNPCUnit, "StepSmoke", pNPCUnit:GetLandPosition_LUA(), D3DXVECTOR2(150,200), D3DXVECTOR2(10,-1) )

end

--**
function GLITER_ALCHEMYST_SECRET_BOSS_STAND_UP_FRONT_FRAME_MOVE( pKTDXApp, pX2Game, pNPCUnit )
	if pNPCUnit:AnimEventTimer_LUA( 0.332 ) then
		local pMinorParticle = pX2Game:GetMinorParticle()
		pMinorParticle:GameUnitCreateSequence_LUA( pNPCUnit, "StepSmoke", pNPCUnit:GetLandPosition_LUA(), D3DXVECTOR2(100,100), D3DXVECTOR2(5,-1) )
	end
end

--**
function GLITER_ALCHEMYST_SECRET_BOSS_STAND_UP_BACK_FRAME_MOVE( pKTDXApp, pX2Game, pNPCUnit )
	if pNPCUnit:AnimEventTimer_LUA( 0.400 ) then
		local pMinorParticle = pX2Game:GetMinorParticle()
		pMinorParticle:GameUnitCreateSequence_LUA( pNPCUnit, "StepSmoke", pNPCUnit:GetLandPosition_LUA(), D3DXVECTOR2(100,100), D3DXVECTOR2(5,-1) )
	end
end
