-- lua header. UTF-8 인코딩 인식을 위해 이 줄은 지우지 마세요.



INIT_SYSTEM = 
{
	UNIT_WIDTH		= 180.0,
	UNIT_HEIGHT		= 150.0,
	UNIT_LAYER		= X2_LAYER["XL_UNIT_0"],
	UNIT_SCALE      = 0.8,
}


INIT_DEVICE = 
{
	READY_TEXTURE = 
	{
		"BerserkerBlade02.tga",
		"Pa_Ran_SpaD_Smoke02A.DDS",
		"Explosion_Sphere.dds",
		"KARUSO_ASSASSIN_BOSS_JA_Ef.tga",
	},
	
	READY_XMESH =
	{
		"KARUSO_ASSASSIN_BOSS_Attack_A_Hide.Y",
	},
	
	READY_SOUND = 
	{
	},
}

INIT_MOTION = 
{
	MOTION_FILE_NAME		= "Motion_KARUSO_ASSASSIN.x",
}

INIT_PHYSIC = 
{
	RELOAD_ACCEL		= 2000,
	G_ACCEL				= 4000,
	MAX_G_SPEED			= -2000,
	
	WALK_SPEED			= 400,
	RUN_SPEED			= 600,
	JUMP_SPEED			= 1500,
	DASH_JUMP_SPEED		= 1800,
}


INIT_COMPONENT = 
{
	MP_CHANGE_RATE		= 1,
	MP_CHARGE_RATE		= 130,

	
	SHADOW_SIZE			= 200,
	SHADOW_FILE_NAME	= "shadow.dds",
	
	SMALL_HP_BAR_BLUE	= "Small_HP_bar_Blue.TGA",
	SMALL_HP_BAR_RED	= "Small_HP_bar_Red.TGA",
	SMALL_HP_BAR_YELLOW = "Small_HP_bar_Yellow.TGA",
	
	QUESTION_MARK_SEQ		= "QuestionMarkNPC",
	EXCLAMATION_MARK_SEQ	= "ExclamationMarkNPC",
	----MIND_FLAG_HEIGHT		= 230,
	
	HYPER_MODE_COUNT	= 0,
	MAX_HYPER_MODE_TIME	= 30,
	

	HITTED_TYPE			= HITTED_TYPE["HTD_MEAT"],
	FALL_DOWN			= TRUE,	
	
	USE_GUARD_COLLISION_BOX		= FALSE,
}

INIT_STATE = 
{
	--6     = 0x06
	{ STATE_NAME = "KARUSO_ASSASSIN_START",						}, 
		
	--9	= 0x09 
	{ STATE_NAME = "KARUSO_ASSASSIN_WAIT",							},
	
	--11	= 0x0b
	{ STATE_NAME = "KARUSO_ASSASSIN_WALK",							LUA_STATE_END_FUNC = "KARUSO_ASSASSIN_WALK_STATE_END"						},
		

	{ STATE_NAME = "KARUSO_ASSASSIN_JUMP_UP",						},
	{ STATE_NAME = "KARUSO_ASSASSIN_JUMP_DOWN",					LUA_STATE_END_FUNC = "KARUSO_ASSASSIN_JUMP_DOWN_STATE_END"					},
	--14	= 0x0e
	{ STATE_NAME = "KARUSO_ASSASSIN_JUMP_UP_DIR",					},
	--15	= 0x0f
	{ STATE_NAME = "KARUSO_ASSASSIN_JUMP_DOWN_DIR",				LUA_STATE_END_FUNC = "KARUSO_ASSASSIN_JUMP_DOWN_DIR_STATE_END"				},
	--16	= 0x10
	{ STATE_NAME = "KARUSO_ASSASSIN_JUMP_DOWN_LANDING",					},

	--18	= 0x12
	{ STATE_NAME = "KARUSO_ASSASSIN_ATTACK_A_START",				STATE_COOL_TIME = 7, },
	{ STATE_NAME = "KARUSO_ASSASSIN_ATTACK_A",						},
	{ STATE_NAME = "KARUSO_ASSASSIN_A_COMBO1",						},
	
	{ STATE_NAME = "KARUSO_ASSASSIN_JUMP_ATTACK",						STATE_COOL_TIME = 7, },
		
	--리액션 관련
	{ STATE_NAME = "KARUSO_ASSASSIN_DAMAGE_FRONT",					LUA_FRAME_MOVE_FUNC = "KARUSO_ASSASSIN_DAMAGE_FRONT_FRAME_MOVE"				},
	{ STATE_NAME = "KARUSO_ASSASSIN_DAMAGE_BACK",					LUA_FRAME_MOVE_FUNC = "KARUSO_ASSASSIN_DAMAGE_BACK_FRAME_MOVE"				},
	{ STATE_NAME = "KARUSO_ASSASSIN_DAMAGE_DOWN_FRONT",			LUA_FRAME_MOVE_FUNC = "KARUSO_ASSASSIN_DAMAGE_DOWN_FRONT_FRAME_MOVE"		},
	{ STATE_NAME = "KARUSO_ASSASSIN_DAMAGE_DOWN_BACK",				LUA_FRAME_MOVE_FUNC = "KARUSO_ASSASSIN_DAMAGE_DOWN_BACK_FRAME_MOVE"			},
	{ STATE_NAME = "KARUSO_ASSASSIN_DAMAGE_FLY_FRONT",				},
	{ STATE_NAME = "KARUSO_ASSASSIN_DAMAGE_FLY_BACK",				},
	{ STATE_NAME = "KARUSO_ASSASSIN_DAMAGE_AIR",					},
	{ STATE_NAME = "KARUSO_ASSASSIN_DAMAGE_AIR_DOWN",				},
	{ STATE_NAME = "KARUSO_ASSASSIN_DAMAGE_AIR_UP",				},
	{ STATE_NAME = "KARUSO_ASSASSIN_DAMAGE_AIR_FALL",				},
	{ STATE_NAME = "KARUSO_ASSASSIN_DAMAGE_AIR_DOWN_LANDING",		LUA_FRAME_MOVE_FUNC = "KARUSO_ASSASSIN_DAMAGE_AIR_DOWN_LANDING_FRAME_MOVE"	},
	
	{ STATE_NAME = "KARUSO_ASSASSIN_STAND_UP_FRONT",				},
	{ STATE_NAME = "KARUSO_ASSASSIN_STAND_UP_BACK",				},
	
	{ STATE_NAME = "KARUSO_ASSASSIN_DAMAGE_REVENGE",				},
	
	
	
	
	{ STATE_NAME = "KARUSO_ASSASSIN_DYING_LAND_FRONT",				LUA_STATE_START_FUNC = "KARUSO_ASSASSIN_DYING_LAND_STATE_START",},
	{ STATE_NAME = "KARUSO_ASSASSIN_DYING_LAND_BACK",				LUA_STATE_START_FUNC = "KARUSO_ASSASSIN_DYING_LAND_STATE_START",},
	{ STATE_NAME = "KARUSO_ASSASSIN_DYING_SKY",					LUA_STATE_START_FUNC = "KARUSO_ASSASSIN_DYING_LAND_STATE_START",},
	
	
	
	START_STATE					= "KARUSO_ASSASSIN_START",
	WAIT_STATE					= "KARUSO_ASSASSIN_WAIT",
		
	SMALL_DAMAGE_LAND_FRONT		= "KARUSO_ASSASSIN_DAMAGE_FRONT",
	SMALL_DAMAGE_LAND_BACK		= "KARUSO_ASSASSIN_DAMAGE_BACK",
	BIG_DAMAGE_LAND_FRONT		= "KARUSO_ASSASSIN_DAMAGE_FRONT",
	BIG_DAMAGE_LAND_BACK		= "KARUSO_ASSASSIN_DAMAGE_BACK",
	DOWN_DAMAGE_LAND_FRONT		= "KARUSO_ASSASSIN_DAMAGE_DOWN_FRONT",
	DOWN_DAMAGE_LAND_BACK		= "KARUSO_ASSASSIN_DAMAGE_DOWN_BACK",
	FLY_DAMAGE_FRONT			= "KARUSO_ASSASSIN_DAMAGE_FLY_FRONT",
	FLY_DAMAGE_BACK				= "KARUSO_ASSASSIN_DAMAGE_FLY_BACK",
	SMALL_DAMAGE_AIR			= "KARUSO_ASSASSIN_DAMAGE_AIR",	
	BIG_DAMAGE_AIR				= "KARUSO_ASSASSIN_DAMAGE_AIR",
	DOWN_DAMAGE_AIR				= "KARUSO_ASSASSIN_DAMAGE_AIR",
	DOWN_DAMAGE_AIR_LANDING				= "KARUSO_ASSASSIN_DAMAGE_AIR_DOWN_LANDING",
	UP_DAMAGE					= "KARUSO_ASSASSIN_DAMAGE_AIR_UP",
	DAMAGE_REVENGE				= "KARUSO_ASSASSIN_DAMAGE_REVENGE",
	
	DAMAGE_EXTRA_STATES         = {"KARUSO_ASSASSIN_DAMAGE_AIR_DOWN","KARUSO_ASSASSIN_DAMAGE_AIR_FALL",
	"KARUSO_ASSASSIN_STAND_UP_FRONT","KARUSO_ASSASSIN_STAND_UP_BACK","KARUSO_ASSASSIN_JUMP_DOWN","KARUSO_ASSASSIN_JUMP_DOWN_LANDING",	},	
	
	DYING_LAND_FRONT			= "KARUSO_ASSASSIN_DYING_LAND_FRONT",
	DYING_LAND_BACK				= "KARUSO_ASSASSIN_DYING_LAND_BACK",
	DYING_SKY					= "KARUSO_ASSASSIN_DYING_SKY",

	REVENGE_ATTACK				= "",	
}



INIT_AI = 
{

	TARGET = 
	{
		TARGET_PRIORITY 			= TARGET_PRIORITY["TP_LOW_HP_FIRST"],
		TARGET_INTERVAL				= 3,		-- sec
		TARGET_NEAR_RANGE			= 500,		-- 이 거리보다 가까우면 TARGET_SUCCESS_RATE에 관계없이 무조건 타게팅된다
		TARGET_RANGE				= 800,		-- cm
		TARGET_LOST_RANGE			= 1200,		-- cm
		TARGET_SUCCESS_RATE			= 100,  --50,		-- %
		ATTACK_TARGET_RATE			= 100, -- 30,		-- 나를 공격한 유닛을 타게팅할 확률
		PRESERVE_LAST_TARGET_RATE	= 100, -- 30,		-- 이전에 타게팅된 유닛을 계속 타게팅할 확률
	},

	CHASE_MOVE = 
	{		
		MOVE_SPLIT_RANGE	= 600,
		DEST_GAP			= 500,	-- 목적지에서 이 거리 안에 있으면 도착했다고 판단한다
		MOVE_GAP			= 600,
		
		DIR_CHANGE_INTERVAL = 0.7,
		
		WALK_INTERVAL		= 3,
		NEAR_WALK_RATE		= 100,   --  70,
		FAR_WALK_RATE		= 100,   -- 30,
		
		JUMP_INTERVAL		= 5,
		UP_JUMP_RATE		= 0, -- 40,
		UP_DOWN_RATE		= 0,
		DOWN_JUMP_RATE		= 0,    --  20,
		DOWN_DOWN_RATE		= 0,
		
		--LINE_END_RANGE		= 100,	-- cm
	},	
	
	PATROL_MOVE = 	
	{
		PATROL_BEGIN_RATE		= 0, --50,		
		PATROL_RANGE			= 200,
		PATROL_COOL_TIME		= 2,
		ONLY_THIS_LINE_GROUP	= TRUE,
	},
	
	ESCAPE_MOVE = 
	{		
		MOVE_SPLIT_RANGE	= 500,	-- cm
		ESCAPE_GAP			= 600,	-- 이 거리 보다 멀어지면 도망 성공
		
		WALK_INTERVAL		= 1.5,	-- 초
		NEAR_WALK_RATE		= 100,   --  10,
		FAR_WALK_RATE		= 100,   -- 10,
		
		JUMP_INTERVAL		= 10,
		UP_JUMP_RATE		= 100, -- 30,
		UP_DOWN_RATE		= 30,
		DOWN_JUMP_RATE		= 100,    --  30,
		DOWN_DOWN_RATE		= 30,
		
		--LINE_END_RANGE		= 80,	-- cm
	},

}

KARUSO_ASSASSIN_START = 
{
	ANIM_NAME					= "Start",
	PLAY_TYPE					= XSKIN_ANIM_PLAYTYPE["XAP_ONE_WAIT"],
	TRANSITION					= FALSE,
	
	CAN_PUSH_UNIT				= TRUE,
	CAN_PASS_UNIT				= FALSE,
	IMMADIATE_PACKET_SEND		= TRUE,	

	SOUND_PLAY0 = { 0.11, "Sword_Out_Shing.ogg"},
	SOUND_PLAY1 = { 1.11, "Thief_Thin_Zero_Slash2.ogg"},
	
	EVENT_PROCESS = 
	{		
		{ STATE_CHANGE_TYPE["SCT_CONDITION_TABLE"],		"KARUSO_ASSASSIN_WAIT",		"CT_KARUSO_ASSASSIN_WAIT"				},
	},
	
	CT_KARUSO_ASSASSIN_WAIT = 
	{
		STATE_TIME_OVER			= 2.8,
	},
}



KARUSO_ASSASSIN_WAIT = 
{
	ANIM_NAME					= "Wait",
	PLAY_TYPE					= XSKIN_ANIM_PLAYTYPE["XAP_LOOP"],
	TRANSITION					= TRUE,
	
	CAN_PUSH_UNIT				= TRUE,
	CAN_PASS_UNIT				= FALSE,	
	
	SPEED_X						= 0,
	SPEED_Y						= 0,
	
	PASSIVE_SPEED_X				= 0,
	
	ALLOW_DIR_CHANGE			= TRUE,
	IMMADIATE_PACKET_SEND			= TRUE,
	VIEW_TARGET				= TRUE,
	
	EVENT_INTERVAL_TIME0		= 1,
	EVENT_INTERVAL_TIME1		= 1.5,
	
	EVENT_PROCESS = 
	{
		{ STATE_CHANGE_TYPE["SCT_FOOT_ON_LINE_FALSE_DOWN"],	"KARUSO_ASSASSIN_JUMP_DOWN",				},
		
		{ STATE_CHANGE_TYPE["SCT_CONDITION_TABLE"],			"KARUSO_ASSASSIN_JUMP_ATTACK",				"CT_KARUSO_ASSASSIN_JUMP_ATTACK",			},
		{ STATE_CHANGE_TYPE["SCT_CONDITION_TABLE"],			"KARUSO_ASSASSIN_ATTACK_A_START",				"CT_KARUSO_ASSASSIN_ATTACK_A_START",			},
		
		
		{ STATE_CHANGE_TYPE["SCT_AI_WALK"],					"KARUSO_ASSASSIN_WALK",						},
		{ STATE_CHANGE_TYPE["SCT_AI_JUMP"],					"KARUSO_ASSASSIN_JUMP_UP",					},
		{ STATE_CHANGE_TYPE["SCT_AI_JUMP_DIR"],				"KARUSO_ASSASSIN_JUMP_UP_DIR",				},
		{ STATE_CHANGE_TYPE["SCT_AI_DOWN"],					"KARUSO_ASSASSIN_JUMP_DOWN",				},
		{ STATE_CHANGE_TYPE["SCT_AI_DOWN_DIR"],				"KARUSO_ASSASSIN_JUMP_DOWN_DIR",			},

	},

	CT_KARUSO_ASSASSIN_JUMP_ATTACK = 
	{
		EVENT_INTERVAL_ID				= 0,
		DISTANCE_TO_TARGET_NEAR			= 400,
		RATE							= 100,
	},
	
	CT_KARUSO_ASSASSIN_ATTACK_A_START = 
	{
		EVENT_INTERVAL_ID				= 1,
		DISTANCE_TO_TARGET_NEAR			= 500,
		RATE							= 100,
	},
}


----------------------------------------------------------------------------

KARUSO_ASSASSIN_WALK = 
{
	ANIM_NAME					= "Walk",
	PLAY_TYPE					= XSKIN_ANIM_PLAYTYPE["XAP_LOOP"],
	TRANSITION					= TRUE,
	
	CAN_PUSH_UNIT				= TRUE,
	CAN_PASS_UNIT				= FALSE,
	
	PASSIVE_SPEED_X				= INIT_PHYSIC["WALK_SPEED"],
	
	ALLOW_DIR_CHANGE			= TRUE,
	IMMADIATE_PACKET_SEND		= TRUE,
	
	EVENT_INTERVAL_TIME0		= 2,
	EVENT_INTERVAL_TIME1		= 3,
	
	EVENT_PROCESS = 
	{		
		{ STATE_CHANGE_TYPE["SCT_FOOT_ON_LINE_FALSE_DOWN"],	"KARUSO_ASSASSIN_JUMP_DOWN_DIR",			},
				
		{ STATE_CHANGE_TYPE["SCT_CONDITION_TABLE"],			"KARUSO_ASSASSIN_JUMP_ATTACK",				"CT_KARUSO_ASSASSIN_JUMP_ATTACK",			},
		{ STATE_CHANGE_TYPE["SCT_CONDITION_TABLE"],			"KARUSO_ASSASSIN_ATTACK_A_START",			"CT_KARUSO_ASSASSIN_ATTACK_A_START",			},
		
		{ STATE_CHANGE_TYPE["SCT_AI_WAIT"],					"KARUSO_ASSASSIN_WAIT",					},
		{ STATE_CHANGE_TYPE["SCT_AI_JUMP"],					"KARUSO_ASSASSIN_JUMP_UP",					},
		{ STATE_CHANGE_TYPE["SCT_AI_JUMP_DIR"],				"KARUSO_ASSASSIN_JUMP_UP_DIR",				},
		{ STATE_CHANGE_TYPE["SCT_AI_DOWN"],					"KARUSO_ASSASSIN_JUMP_DOWN",				},
		{ STATE_CHANGE_TYPE["SCT_AI_DOWN_DIR"],				"KARUSO_ASSASSIN_JUMP_DOWN_DIR",			},
	},

	CT_KARUSO_ASSASSIN_JUMP_ATTACK = 
	{
		EVENT_INTERVAL_ID			= 0,
		DISTANCE_TO_TARGET_NEAR			= 400,
		RATE					= 60,
	},
	
	CT_KARUSO_ASSASSIN_ATTACK_A_START = 
	{
		EVENT_INTERVAL_ID			= 1,
		DISTANCE_TO_TARGET_NEAR			= 500,
		RATE					= 70,
	},
}

KARUSO_ASSASSIN_JUMP_UP = 
{
	ANIM_NAME					= "JumpUp",
	PLAY_TYPE					= XSKIN_ANIM_PLAYTYPE["XAP_LOOP"],
	TRANSITION					= TRUE,
	LAND_CONNECT				= FALSE,
	
	CAN_PUSH_UNIT				= TRUE,
	CAN_PASS_UNIT				= FALSE,
	
	SPEED_X						= 0,
	SPEED_Y						= INIT_PHYSIC["JUMP_SPEED"],
	
	ADD_POS_Y					= 45, 
	
	IMMADIATE_PACKET_SEND		= TRUE,
	
	EVENT_PROCESS = 
	{		
		{ STATE_CHANGE_TYPE["SCT_NEGATIVE_Y_SPEED"],		"KARUSO_ASSASSIN_JUMP_DOWN",			},
	},
	
}

KARUSO_ASSASSIN_JUMP_DOWN = 
{
	ANIM_NAME					= "JumpDown",
	PLAY_TYPE					= XSKIN_ANIM_PLAYTYPE["XAP_LOOP"],
	TRANSITION					= TRUE,
	LAND_CONNECT				= FALSE,
	
	CAN_PUSH_UNIT				= TRUE,
	CAN_PASS_UNIT				= FALSE,
		 
	
	IMMADIATE_PACKET_SEND		= TRUE,
		
	EVENT_PROCESS = 
	{		
		{ STATE_CHANGE_TYPE["SCT_FOOT_ON_LINE_TRUE"],		"KARUSO_ASSASSIN_JUMP_DOWN_LANDING",				},
	},
}

KARUSO_ASSASSIN_JUMP_UP_DIR = 
{
	ANIM_NAME					= "JumpUp",
	PLAY_TYPE					= XSKIN_ANIM_PLAYTYPE["XAP_LOOP"],
	TRANSITION					= TRUE,
	LAND_CONNECT				= FALSE,
	
	CAN_PUSH_UNIT				= TRUE,
	CAN_PASS_UNIT				= FALSE,
		
	PASSIVE_SPEED_X				= INIT_PHYSIC["WALK_SPEED"],
	SPEED_Y						= INIT_PHYSIC["JUMP_SPEED"],
	
	ADD_POS_Y					= 45, 
	
	IMMADIATE_PACKET_SEND		= TRUE,
	
	EVENT_PROCESS = 
	{		
		{ STATE_CHANGE_TYPE["SCT_NEGATIVE_Y_SPEED"],		"KARUSO_ASSASSIN_JUMP_DOWN_DIR",				},
	},
	
}

KARUSO_ASSASSIN_JUMP_DOWN_DIR = 
{
	ANIM_NAME					= "JumpDown",
	PLAY_TYPE					= XSKIN_ANIM_PLAYTYPE["XAP_LOOP"],
	TRANSITION					= TRUE,
	LAND_CONNECT				= FALSE,
	
	CAN_PUSH_UNIT				= TRUE,
	CAN_PASS_UNIT				= FALSE,
	
	PASSIVE_SPEED_X				= INIT_PHYSIC["WALK_SPEED"],
	 
	
	IMMADIATE_PACKET_SEND		= TRUE,
		
	EVENT_PROCESS = 
	{		
		{ STATE_CHANGE_TYPE["SCT_FOOT_ON_LINE_TRUE"],		"KARUSO_ASSASSIN_JUMP_DOWN_LANDING",				},
	},
}

KARUSO_ASSASSIN_JUMP_DOWN_LANDING = 
{
	ANIM_NAME					= "JumpDownLanding",
	PLAY_TYPE					= XSKIN_ANIM_PLAYTYPE["XAP_ONE_WAIT"],
	TRANSITION					= TRUE,
	LAND_CONNECT				= FALSE,
	
	CAN_PUSH_UNIT				= TRUE,
	CAN_PASS_UNIT				= FALSE,
	
    SPEED_X						= 0,
	SPEED_Y						= 0,

	IMMADIATE_PACKET_SEND		= TRUE,

	EVENT_PROCESS = 
	{		
		{ STATE_CHANGE_TYPE["SCT_FOOT_ON_LINE_FALSE_DOWN"],	"KARUSO_ASSASSIN_JUMP_DOWN",				},
		{ STATE_CHANGE_TYPE["SCT_MOTION_END"],				"KARUSO_ASSASSIN_WAIT",						},
	},
}

KARUSO_ASSASSIN_ATTACK_A_START = 
{
	ANIM_NAME					= "Attack_A_Start",
	PLAY_TYPE					= XSKIN_ANIM_PLAYTYPE["XAP_ONE_WAIT"],
	TRANSITION					= TRUE,
	LAND_CONNECT				= FALSE,
	
	CAN_PUSH_UNIT				= TRUE,
	CAN_PASS_UNIT				= FALSE,
	
    -- SPEED_X						= 1000,
	-- SPEED_Y						= 0,

	SOUND_PLAY0 = { 0.01, "Landing_Meat04.ogg"},
	
	IMMADIATE_PACKET_SEND		= TRUE,

	EFFECT_SET_LIST =
	{
		"EFFECTSET_KARUSO_ASSASSIN_ATTACK_A", 0.0,
	},
	
	DELETE_EFFECT_SET_ON_STATE_END = TRUE,
	
	EVENT_PROCESS = 
	{		
		{ STATE_CHANGE_TYPE["SCT_FOOT_ON_LINE_FALSE_DOWN"],	"KARUSO_ASSASSIN_JUMP_DOWN",				},
		{ STATE_CHANGE_TYPE["SCT_CONDITION_TABLE"],			"KARUSO_ASSASSIN_ATTACK_A",			"CT_KARUSO_ASSASSIN_ATTACK_A",	},
		{ STATE_CHANGE_TYPE["SCT_MOTION_END"],				"KARUSO_ASSASSIN_ATTACK_A",						},
	},
	
	CT_KARUSO_ASSASSIN_ATTACK_A = 
	{
		DISTANCE_TO_TARGET_NEAR		= 300,
		RATE						= 100,
	},
}

KARUSO_ASSASSIN_ATTACK_A = 
{
	ANIM_NAME					= "Attack_A",
	PLAY_TYPE					= XSKIN_ANIM_PLAYTYPE["XAP_ONE_WAIT"],
	TRANSITION					= FALSE,
	ANIM_MOVE					= FALSE,
	
	ANIM_SPEED					= 1.5,
	
	SUPER_ARMOR_TIME0			= { 0.0, 0.5, },
	
	CAN_PUSH_UNIT				= TRUE,
	CAN_PASS_UNIT				= FALSE,

	SOUND_PLAY0 = { 0.11, "Thief_Thin_Zero_Slash1.ogg"},
	
	SPEED_X						= 0,
	SPEED_Y						= 0,	

    VIEW_TARGET					= TRUE,
	IMMADIATE_PACKET_SEND		= TRUE,

	EVENT_PROCESS = 
	{	
		{ STATE_CHANGE_TYPE["SCT_FOOT_ON_LINE_FALSE_DOWN"],	"KARUSO_ASSASSIN_JUMP_DOWN",										},
		{ STATE_CHANGE_TYPE["SCT_CONDITION_TABLE"],			"KARUSO_ASSASSIN_A_COMBO1",			"CT_KARUSO_ASSASSIN_A_COMBO1",	},
		{ STATE_CHANGE_TYPE["SCT_MOTION_END"],				"KARUSO_ASSASSIN_WAIT",												},	
	},

	ATTACK_TIME0				= { 0.15, 0.21, },
	
	CT_KARUSO_ASSASSIN_A_COMBO1 = 
	{
		ANIM_EVENT_TIMER			= 1.3,
		ATTACK_SUCCESS				= TRUE,
		RATE					= 80,
	},
	
	DAMAGE_DATA = 
	{
		DAMAGE_TYPE		= DAMAGE_TYPE["DT_PHYSIC"],
		HIT_TYPE		= HIT_TYPE["HT_SWORD_SLASH"],
		REACT_TYPE		= REACT_TYPE["RT_SMALL_DAMAGE"],
		
		DAMAGE = 
		{
			PHYSIC		= 1,
		},
		
		BUFF_FACTOR =
		{
			BUFF_TEMPLET_ID = BUFF_TEMPLET_ID["BTI_DEBUFF_BLEEDING"],
			RATE	=
			{
				1,
			},
			IGNORE_REGIST_FOR_RATE = FALSE,
			BEHAVIOR =
			{
				COMBINATION = { BUFF_BEHAVIOR_TYPE["BBT_CHANGE_NOW_HP_PER_SECOND"], },
				
				BBT_CHANGE_NOW_HP_PER_SECOND =
				{
					BUFF_CHANGE_TYPE = BUFF_CHANGE_TYPE["BCT_RELATION_VALUE"],
					BUFF_RELATION_TYPE = BUFF_RELATION_TYPE["BRT_MIX_ATTACK"],

					MULTIPLIER =
					{
						-0.25,
					},
				},
			},
		
			FINALIZER =
			{
				COMBINATION = { BUFF_FINALIZER_TYPE["BFT_TIME"], },
			
				BFT_TIME =
				{
					BUFF_DURATION_TIME_TYPE = BUFF_DURATION_TIME_TYPE["BDTT_NORMAL_TIME"],
					NORMAL_TIME =
					{
						5,
					},
				},
			},
		},
		BACK_SPEED_X			= -1200,
		BACK_SPEED_Y			= 0.0,
		
		ARRANGED_FLY			= TRUE,
		
		CAMERA_CRASH_GAP		= 5.0,	
		CAMERA_CRASH_TIME		= 0.2,		
		CAN_REVENGE			= TRUE,	
	},
}

KARUSO_ASSASSIN_A_COMBO1 =
{
	ANIM_NAME					= "Attack_A_Combo1",
	PLAY_TYPE					= XSKIN_ANIM_PLAYTYPE["XAP_ONE_WAIT"],
	TRANSITION					= FALSE,
	ANIM_MOVE					= FALSE,
	
	CAN_PUSH_UNIT				= TRUE,
	CAN_PASS_UNIT				= FALSE,
	SUPER_ARMOR_TIME0			= { 0.0, 1.0, },


    VIEW_TARGET					= TRUE,
	IMMADIATE_PACKET_SEND		= TRUE,

		SOUND_PLAY0 = { 0.41, "Thief_Thin_Zero_Slash1.ogg"},
	
	EFFECT_SET_LIST =
	{
		"EFFECTSET_KARUSO_ASSASSIN_ATTACK_A_COMBO1", 0.0,
	},
	
	DELETE_EFFECT_SET_ON_STATE_END = TRUE,
	
	EVENT_PROCESS = 
	{		
		{ STATE_CHANGE_TYPE["SCT_FOOT_ON_LINE_FALSE_DOWN"],	"KARUSO_ASSASSIN_JUMP_DOWN",			},
		{ STATE_CHANGE_TYPE["SCT_MOTION_END"],				"KARUSO_ASSASSIN_WAIT",					},
	},
	
	
	ATTACK_TIME0				= { 1.08, 1.17, },
	
	DAMAGE_DATA = 
	{
		DAMAGE_TYPE		= DAMAGE_TYPE["DT_PHYSIC"],
		HIT_TYPE		= HIT_TYPE["HT_SWORD_SLASH"],
		REACT_TYPE		= REACT_TYPE["RT_DOWN"],
		
		DAMAGE = 
		{
			PHYSIC		= 1,
		},
		
		BUFF_FACTOR =
		{
			BUFF_TEMPLET_ID = BUFF_TEMPLET_ID["BTI_DEBUFF_BLEEDING"],
			RATE	=
			{
				1,
			},
			IGNORE_REGIST_FOR_RATE = FALSE,
			BEHAVIOR =
			{
				COMBINATION = { BUFF_BEHAVIOR_TYPE["BBT_CHANGE_NOW_HP_PER_SECOND"], },
				
				BBT_CHANGE_NOW_HP_PER_SECOND =
				{
					BUFF_CHANGE_TYPE = BUFF_CHANGE_TYPE["BCT_RELATION_VALUE"],
					BUFF_RELATION_TYPE = BUFF_RELATION_TYPE["BRT_MIX_ATTACK"],

					MULTIPLIER =
					{
						-0.25,
					},
				},
			},
		
			FINALIZER =
			{
				COMBINATION = { BUFF_FINALIZER_TYPE["BFT_TIME"], },
			
				BFT_TIME =
				{
					BUFF_DURATION_TIME_TYPE = BUFF_DURATION_TIME_TYPE["BDTT_NORMAL_TIME"],
					NORMAL_TIME =
					{
						5,
					},
				},
			},
		},
		BACK_SPEED_X			= 600,
		BACK_SPEED_Y			= 0,
		
		CAMERA_CRASH_GAP		= 10.0,	
		CAMERA_CRASH_TIME		= 0.2,		
		CAN_REVENGE			= TRUE,		
	},
}

KARUSO_ASSASSIN_JUMP_ATTACK =	-- 칼로 어퍼 컷
{
	ANIM_NAME					= "Jump_Attack",
	PLAY_TYPE					= XSKIN_ANIM_PLAYTYPE["XAP_ONE_WAIT"],
	TRANSITION					= FALSE,
	ANIM_MOVE					= FALSE,
	
	ANIM_SPEED					= 1,

	SOUND_PLAY0 = { 0.51, "Thief_Thin_Zero_Slash1.ogg"},
	
	CAN_PUSH_UNIT				= TRUE,
	CAN_PASS_UNIT				= FALSE,

	SPEED_X						= 0,
	SPEED_Y						= 0,	

  	VIEW_TARGET					= TRUE,
	IMMADIATE_PACKET_SEND		= TRUE,

	EFFECT_SET_LIST =
	{
		"EFFECTSET_KARUSO_ASSASSIN_JUMP_ATTACK", 0.0,
	},
	
	DELETE_EFFECT_SET_ON_STATE_END = TRUE,
	
	EVENT_PROCESS = 
	{	
		{ STATE_CHANGE_TYPE["SCT_FOOT_ON_LINE_FALSE_DOWN"],	"KARUSO_ASSASSIN_JUMP_DOWN",										},
		{ STATE_CHANGE_TYPE["SCT_MOTION_END"],				"KARUSO_ASSASSIN_WAIT",												},	
	},

	ATTACK_TIME0				= { 0.594, 0.63, },
	
	DAMAGE_DATA =
	{
		DAMAGE_TYPE		= DAMAGE_TYPE["DT_PHYSIC"],
		HIT_TYPE		= HIT_TYPE["HT_SWORD_SLASH"],
		REACT_TYPE		= REACT_TYPE["RT_FLY"],
		
		DAMAGE = 
		{
			PHYSIC		= 2,
		},
		
		BUFF_FACTOR =
		{
			BUFF_TEMPLET_ID = BUFF_TEMPLET_ID["BTI_DEBUFF_BLEEDING"],
			RATE	=
			{
				1,
			},
			IGNORE_REGIST_FOR_RATE = FALSE,
			BEHAVIOR =
			{
				COMBINATION = { BUFF_BEHAVIOR_TYPE["BBT_CHANGE_NOW_HP_PER_SECOND"], },
				
				BBT_CHANGE_NOW_HP_PER_SECOND =
				{
					BUFF_CHANGE_TYPE = BUFF_CHANGE_TYPE["BCT_RELATION_VALUE"],
					BUFF_RELATION_TYPE = BUFF_RELATION_TYPE["BRT_MIX_ATTACK"],

					MULTIPLIER =
					{
						-0.25,
					},
				},
			},
		
			FINALIZER =
			{
				COMBINATION = { BUFF_FINALIZER_TYPE["BFT_TIME"], },
			
				BFT_TIME =
				{
					BUFF_DURATION_TIME_TYPE = BUFF_DURATION_TIME_TYPE["BDTT_NORMAL_TIME"],
					NORMAL_TIME =
					{
						5,
					},
				},
			},
		},
		BACK_SPEED_X			= 700,
		BACK_SPEED_Y			= 1700,
		
		CAMERA_CRASH_GAP		= 5.0,	
		CAMERA_CRASH_TIME		= 0.2,
		CAN_REVENGE			= TRUE,			
	},
}






KARUSO_ASSASSIN_DAMAGE_REVENGE = 
{
	ANIM_NAME					= "DamageRevenge",
	PLAY_TYPE					= XSKIN_ANIM_PLAYTYPE["XAP_ONE_WAIT"],
	TRANSITION					= FALSE,
	LAND_CONNECT				= FALSE,

	SOUND_PLAY0 = { 0.01, "Karuso_Suppression_Voice_DamageA01.ogg",30},
	
	CAN_PUSH_UNIT				= TRUE,
	CAN_PASS_UNIT				= FALSE,
	
	EVENT_PROCESS = 
	{
		{ STATE_CHANGE_TYPE["SCT_MOTION_END"],					"KARUSO_ASSASSIN_WAIT",												},
	},
}


KARUSO_ASSASSIN_DAMAGE_FRONT = 
{
	ANIM_NAME					= "DamageFront",
	PLAY_TYPE					= XSKIN_ANIM_PLAYTYPE["XAP_ONE_WAIT"],
	TRANSITION					= FALSE,
	LAND_CONNECT				= FALSE,
	
	CAN_PUSH_UNIT				= TRUE,
	CAN_PASS_UNIT				= FALSE,

    EVENT_PROCESS = 
	{
		{ STATE_CHANGE_TYPE["SCT_MOTION_END"],					"KARUSO_ASSASSIN_WAIT",												},
	},
}

KARUSO_ASSASSIN_DAMAGE_BACK = 
{
	ANIM_NAME					= "DamageBack",
	PLAY_TYPE					= XSKIN_ANIM_PLAYTYPE["XAP_ONE_WAIT"],
	TRANSITION					= FALSE,
	LAND_CONNECT				= FALSE,
	
	CAN_PUSH_UNIT				= TRUE,
	CAN_PASS_UNIT				= FALSE,

	SOUND_PLAY0 = { 0.01, "Karuso_Suppression_Voice_DamageA01.ogg",30},

	
    EVENT_PROCESS = 
	{
		{ STATE_CHANGE_TYPE["SCT_MOTION_END"],					"KARUSO_ASSASSIN_WAIT",												},
	},
}





KARUSO_ASSASSIN_DAMAGE_DOWN_FRONT = 
{
	ANIM_NAME					= "DamageDownFront",
	PLAY_TYPE					= XSKIN_ANIM_PLAYTYPE["XAP_ONE_WAIT"],
	TRANSITION					= FALSE,
	LAND_CONNECT				= FALSE,

	SUPER_ARMOR					= TRUE,
	DEFENCE						= { 0, 100, 70, },

    CAN_PUSH_UNIT				= TRUE,
	CAN_PASS_UNIT				= FALSE,
	
	EVENT_PROCESS = 
	{
		{ STATE_CHANGE_TYPE["SCT_FOOT_ON_LINE_FALSE_DOWN"],		"KARUSO_ASSASSIN_DAMAGE_AIR_FALL",			},
		{ STATE_CHANGE_TYPE["SCT_MOTION_END"],					"KARUSO_ASSASSIN_STAND_UP_FRONT",			},
	},
	
}

KARUSO_ASSASSIN_DAMAGE_DOWN_BACK = 
{
	ANIM_NAME					= "DamageDownBack",
	PLAY_TYPE					= XSKIN_ANIM_PLAYTYPE["XAP_ONE_WAIT"],
	TRANSITION					= FALSE,
	LAND_CONNECT				= FALSE,
	
	SUPER_ARMOR					= TRUE,
	DEFENCE						= { 0, 100, 70, },

    CAN_PUSH_UNIT				= TRUE,
	CAN_PASS_UNIT				= FALSE,
	
	EVENT_PROCESS = 
	{
		{ STATE_CHANGE_TYPE["SCT_FOOT_ON_LINE_FALSE_DOWN"],		"KARUSO_ASSASSIN_DAMAGE_AIR_FALL",			},
		{ STATE_CHANGE_TYPE["SCT_MOTION_END"],					"KARUSO_ASSASSIN_STAND_UP_BACK",			},
	},
	
}

KARUSO_ASSASSIN_DAMAGE_FLY_FRONT = 
{
	ANIM_NAME					= "DamageAirFlyFront",
	PLAY_TYPE					= XSKIN_ANIM_PLAYTYPE["XAP_ONE_WAIT"],
	TRANSITION					= TRUE,
	LAND_CONNECT				= FALSE,	
	
		SOUND_PLAY0 = { 0.01, "Karuso_Suppression_Voice_DamageA01.ogg",30},
	
	
	CAN_PUSH_UNIT				= TRUE,
	CAN_PASS_UNIT				= FALSE,
	
	EVENT_PROCESS = 
	{
		{ STATE_CHANGE_TYPE["SCT_FOOT_ON_LINE_TRUE"],			"KARUSO_ASSASSIN_DAMAGE_AIR_DOWN_LANDING",		},
	},
}

KARUSO_ASSASSIN_DAMAGE_FLY_BACK = 
{
	ANIM_NAME					= "DamageAirFlyBack",
	PLAY_TYPE					= XSKIN_ANIM_PLAYTYPE["XAP_ONE_WAIT"],
	TRANSITION					= FALSE,
	LAND_CONNECT				= FALSE,	
	
	CAN_PUSH_UNIT				= TRUE,
	CAN_PASS_UNIT				= FALSE,

	SOUND_PLAY0 = { 0.01, "Karuso_Suppression_Voice_DamageB01.ogg",30},
	
	EVENT_PROCESS = 
	{
		{ STATE_CHANGE_TYPE["SCT_FOOT_ON_LINE_TRUE"],			"KARUSO_ASSASSIN_DAMAGE_DOWN_BACK",		},
	},
}

KARUSO_ASSASSIN_DAMAGE_AIR = 
{
	ANIM_NAME					= "DamageAir",
	PLAY_TYPE					= XSKIN_ANIM_PLAYTYPE["XAP_ONE_WAIT"],
	TRANSITION					= FALSE,
	LAND_CONNECT				= FALSE,
	
	CAN_PUSH_UNIT				= TRUE,
	CAN_PASS_UNIT				= FALSE,

		SOUND_PLAY0 = { 0.01, "Karuso_Suppression_Voice_DamageA01.ogg",30},
	
	EVENT_PROCESS = 
	{
		{ STATE_CHANGE_TYPE["SCT_FOOT_ON_LINE_TRUE"],			"KARUSO_ASSASSIN_WAIT",					},
	},
	
	VIEW_TARGET					= TRUE,
	ALLOW_DIR_CHANGE			= TRUE,

	
	
	ATTACK_TIME0				= { 0.15, 0.24, },
	
	DAMAGE_DATA = 
	{
		DAMAGE_TYPE		= DAMAGE_TYPE["DT_PHYSIC"],
		HIT_TYPE		= HIT_TYPE["HT_PUNCH_HIT"],
		REACT_TYPE		= REACT_TYPE["RT_FLY"],
		
		DAMAGE = 
		{
			PHYSIC		= 1.0,
		},
		
		
		CAMERA_CRASH_GAP		= 10.0,	
		CAMERA_CRASH_TIME		= 0.2,	
		
		BACK_SPEED_X		= 1500,
		BACK_SPEED_Y		= -1000,
		
	},
	
}

KARUSO_ASSASSIN_DAMAGE_AIR_DOWN = 
{
	ANIM_NAME					= "DamageAirDown",
	PLAY_TYPE					= XSKIN_ANIM_PLAYTYPE["XAP_ONE_WAIT"],
	TRANSITION					= FALSE,
	LAND_CONNECT				= FALSE,
	
	CAN_PUSH_UNIT				= TRUE,
	CAN_PASS_UNIT				= FALSE,
	
	EVENT_PROCESS = 
	{
		{ STATE_CHANGE_TYPE["SCT_FOOT_ON_LINE_TRUE"],			"KARUSO_ASSASSIN_DAMAGE_AIR_DOWN_LANDING",	},
	},
}

KARUSO_ASSASSIN_DAMAGE_AIR_UP = 
{
	ANIM_NAME					= "DamageAirUp",
	PLAY_TYPE					= XSKIN_ANIM_PLAYTYPE["XAP_ONE_WAIT"],
	TRANSITION					= FALSE,
	LAND_CONNECT				= FALSE,
	
	CAN_PUSH_UNIT				= TRUE,
	CAN_PASS_UNIT				= FALSE,
	
		
	EVENT_PROCESS = 
	{
		{ STATE_CHANGE_TYPE["SCT_NEGATIVE_Y_SPEED"],		"KARUSO_ASSASSIN_DAMAGE_AIR_FALL",			},
		{ STATE_CHANGE_TYPE["SCT_FOOT_ON_LINE_TRUE"],		"KARUSO_ASSASSIN_DAMAGE_AIR_DOWN_LANDING",	},
	},
}

KARUSO_ASSASSIN_DAMAGE_AIR_FALL = 
{
	ANIM_NAME					= "DamageAirFall",
	PLAY_TYPE					= XSKIN_ANIM_PLAYTYPE["XAP_ONE_WAIT"],
	TRANSITION					= FALSE,
	LAND_CONNECT				= FALSE,
	
	CAN_PUSH_UNIT				= TRUE,
	CAN_PASS_UNIT				= FALSE,
	
	EVENT_PROCESS = 
	{
		{ STATE_CHANGE_TYPE["SCT_POSITIVE_Y_SPEED"],		"KARUSO_ASSASSIN_DAMAGE_AIR_UP",			},
		{ STATE_CHANGE_TYPE["SCT_FOOT_ON_LINE_TRUE"],		"KARUSO_ASSASSIN_DAMAGE_AIR_DOWN_LANDING",	},
	},
}

KARUSO_ASSASSIN_DAMAGE_AIR_DOWN_LANDING = 
{
	ANIM_NAME					= "DamageAirDownLanding",
	PLAY_TYPE					= XSKIN_ANIM_PLAYTYPE["XAP_ONE_WAIT"],
	TRANSITION					= FALSE,
	LAND_CONNECT				= FALSE,
	
	SUPER_ARMOR					= TRUE,
	DEFENCE						= { 0, 100, 70, },
	
	CAN_PUSH_UNIT				= TRUE,
	CAN_PASS_UNIT				= FALSE,
	
	EVENT_PROCESS = 
	{
		{ STATE_CHANGE_TYPE["SCT_FOOT_ON_LINE_FALSE_DOWN"],	"KARUSO_ASSASSIN_DAMAGE_AIR_FALL",			},
		{ STATE_CHANGE_TYPE["SCT_MOTION_END"],				"KARUSO_ASSASSIN_STAND_UP_FRONT",			},
	},
	
}

KARUSO_ASSASSIN_STAND_UP_FRONT = 
{
	ANIM_NAME					= "DamageStandUpFront",
	PLAY_TYPE					= XSKIN_ANIM_PLAYTYPE["XAP_ONE_WAIT"],
	TRANSITION					= FALSE,
	LAND_CONNECT				= FALSE,	
	
	SUPER_ARMOR					= TRUE,
	DEFENCE						= { 0, 100, 70, },
	
	CAN_PUSH_UNIT				= TRUE,
	CAN_PASS_UNIT				= FALSE,
	
	EVENT_PROCESS = 
	{
		{ STATE_CHANGE_TYPE["SCT_FOOT_ON_LINE_FALSE_DOWN"],	"KARUSO_ASSASSIN_JUMP_DOWN",			},
		{ STATE_CHANGE_TYPE["SCT_MOTION_END"],				"KARUSO_ASSASSIN_WAIT",				},
	},
}

KARUSO_ASSASSIN_STAND_UP_BACK = 
{
	ANIM_NAME					= "DamageStandUpBack",
	PLAY_TYPE					= XSKIN_ANIM_PLAYTYPE["XAP_ONE_WAIT"],
	TRANSITION					= FALSE,
	LAND_CONNECT				= FALSE,
	
	SUPER_ARMOR					= TRUE,
	DEFENCE						= { 0, 100, 70, },

    CAN_PUSH_UNIT				= TRUE,
	CAN_PASS_UNIT				= FALSE,
		
	EVENT_PROCESS = 
	{
		{ STATE_CHANGE_TYPE["SCT_FOOT_ON_LINE_FALSE_DOWN"],	"KARUSO_ASSASSIN_JUMP_DOWN", },
		{ STATE_CHANGE_TYPE["SCT_MOTION_END"],				"KARUSO_ASSASSIN_WAIT", },
	},		
}



KARUSO_ASSASSIN_DYING_LAND_FRONT = 
{
	ANIM_NAME					= "DamageDownFront",
	PLAY_TYPE					= XSKIN_ANIM_PLAYTYPE["XAP_ONE_WAIT"],
	TRANSITION					= FALSE,
	LAND_CONNECT				= FALSE,

	INVINCIBLE					= { 0, 100, }, 		
	
	CAN_PUSH_UNIT				= FALSE,
	CAN_PASS_UNIT				= TRUE,

    DYING_END					= TRUE,
	
	IMMADIATE_PACKET_SEND		= TRUE,
}
	
KARUSO_ASSASSIN_DYING_LAND_BACK = 
{
	ANIM_NAME					= "DamageDownBack",
	PLAY_TYPE					= XSKIN_ANIM_PLAYTYPE["XAP_ONE_WAIT"],
	TRANSITION					= FALSE,
	LAND_CONNECT				= FALSE,
	
	INVINCIBLE					= { 0, 100, }, 		

    CAN_PUSH_UNIT				= FALSE,
	CAN_PASS_UNIT				= TRUE,
	
	DYING_END					= TRUE,	
	
	IMMADIATE_PACKET_SEND		= TRUE,
}

KARUSO_ASSASSIN_DYING_SKY = 
{
	ANIM_NAME					= "DamageAirDownLanding",
	PLAY_TYPE					= XSKIN_ANIM_PLAYTYPE["XAP_ONE_WAIT"],
	TRANSITION					= FALSE,
	LAND_CONNECT				= FALSE,
	
	INVINCIBLE					= { 0, 100, }, 		

    CAN_PUSH_UNIT				= FALSE,
	CAN_PASS_UNIT				= TRUE,
	
	DYING_END					= TRUE,
	
	IMMADIATE_PACKET_SEND		= TRUE,
}


--------------------------------------------------------------------
--------------------------------------------------------------------

function KARUSO_ASSASSIN_WALK_STATE_END( pKTDXApp, pX2Game, pNPCUnit )

	local pMinorParticle = pX2Game:GetMinorParticle()
	pMinorParticle:GameUnitCreateSequence_LUA( pNPCUnit, "StepSmoke", pNPCUnit:GetLandPosition_LUA(), D3DXVECTOR2(100,100), D3DXVECTOR2(5,-1) )

end



function KARUSO_ASSASSIN_JUMP_DOWN_STATE_END( pKTDXApp, pX2Game, pNPCUnit )

	local pMinorParticle = pX2Game:GetMinorParticle()
	pMinorParticle:GameUnitCreateSequence_LUA( pNPCUnit, "StepSmoke", pNPCUnit:GetLandPosition_LUA(), D3DXVECTOR2(100,100), D3DXVECTOR2(5,-1) )

end

function KARUSO_ASSASSIN_JUMP_DOWN_DIR_STATE_END( pKTDXApp, pX2Game, pNPCUnit )

	local pMinorParticle = pX2Game:GetMinorParticle()
	pMinorParticle:GameUnitCreateSequence_LUA( pNPCUnit, "StepSmoke", pNPCUnit:GetLandPosition_LUA(), D3DXVECTOR2(100,100), D3DXVECTOR2(5,-1) )

end


function KARUSO_ASSASSIN_DAMAGE_FRONT_FRAME_MOVE( pKTDXApp, pX2Game, pNPCUnit )

	if pNPCUnit:AnimEventTimer_LUA( 0.047 ) then
		local pMinorParticle = pX2Game:GetMinorParticle()
		pMinorParticle:GameUnitCreateSequence_LUA( pNPCUnit, "StepSmoke", pNPCUnit:GetLandPosition_LUA(), D3DXVECTOR2(100,100), D3DXVECTOR2(5,-1) )
	end

end

function KARUSO_ASSASSIN_DAMAGE_BACK_FRAME_MOVE( pKTDXApp, pX2Game, pNPCUnit )

	if pNPCUnit:AnimEventTimer_LUA( 0.06 ) then
		local pMinorParticle = pX2Game:GetMinorParticle()
		pMinorParticle:GameUnitCreateSequence_LUA( pNPCUnit, "StepSmoke", pNPCUnit:GetLandPosition_LUA(), D3DXVECTOR2(100,100), D3DXVECTOR2(5,-1) )
	end

end

function KARUSO_ASSASSIN_DAMAGE_DOWN_FRONT_FRAME_MOVE( pKTDXApp, pX2Game, pNPCUnit )

	if pNPCUnit:AnimEventTimer_LUA( 0.41 ) then
		pNPCUnit:PlaySound_LUA( "Down.ogg" )		
		local pMinorParticle = pX2Game:GetMinorParticle()
		pMinorParticle:GameUnitCreateSequence_LUA( pNPCUnit, "DownSmoke", pNPCUnit:GetLandPosition_LUA(), D3DXVECTOR2(100,100), D3DXVECTOR2(7,-1) )
	end

end

function KARUSO_ASSASSIN_DAMAGE_DOWN_BACK_FRAME_MOVE( pKTDXApp, pX2Game, pNPCUnit )

	if pNPCUnit:AnimEventTimer_LUA( 0.45 ) then
		pNPCUnit:PlaySound_LUA( "Down.ogg" )		
		local pMinorParticle = pX2Game:GetMinorParticle()
		pMinorParticle:GameUnitCreateSequence_LUA( pNPCUnit, "DownSmoke", pNPCUnit:GetLandPosition_LUA(), D3DXVECTOR2(100,100), D3DXVECTOR2(7,-1) )
	end

end

function KARUSO_ASSASSIN_DAMAGE_AIR_DOWN_LANDING_FRAME_MOVE( pKTDXApp, pX2Game, pNPCUnit )

	if pNPCUnit:AnimEventTimer_LUA( 0.01 ) then
		
		local pMinorParticle = pX2Game:GetMinorParticle()
		local pos = pNPCUnit:GetLandPosition_LUA()
		
		pMinorParticle:GameUnitCreateSequence_LUA( pNPCUnit, "DownSmoke", pos, D3DXVECTOR2(100,100), D3DXVECTOR2(7,-1) )
		pos.y = pos.y + 5
		pMinorParticle:GameUnitCreateSequence_LUA( pNPCUnit, "GroundShockWave", pos, D3DXVECTOR2(100,100), D3DXVECTOR2(1,-1) )
		
		local pParticle = pMinorParticle:GameUnitCreateSequence_LUA( pNPCUnit, "AirDownTick", pNPCUnit:GetPos(), D3DXVECTOR2(200,200), D3DXVECTOR2(10,-1) )
		if pParticle ~= nil then 
			pParticle:SetLandPosition( pos.y - 5 )
		end
		
		if GetDistance_LUA( pNPCUnit:GetPos(), pX2Game:GetFocusUnitPos_LUA() ) < 500 then
			pX2Game:GetX2Camera():GetCamera():UpDownCrashCameraNoReset( 10.0, 0.1 )
		end		
		
	elseif pNPCUnit:AnimEventTimer_LUA( 0.1 ) then
		
		pNPCUnit:PlaySound_LUA( "Down.ogg" )		
		local pMinorParticle = pX2Game:GetMinorParticle()
		pMinorParticle:GameUnitCreateSequence_LUA( pNPCUnit, "DownSmoke", pNPCUnit:GetLandPosition_LUA(), D3DXVECTOR2(100,100), D3DXVECTOR2(7,-1) )
		
	end

end







function KARUSO_ASSASSIN_DYING_LAND_STATE_START( pKTDXApp, pX2Game, pNPCUnit )

	local pos = pNPCUnit:GetPos()
	pos.y = pos.y + 100.0
	
	local GetMinorParticle = pX2Game:GetMinorParticle()
	
	local pSeq = GetMinorParticle:GameUnitCreateSequence_LUA( pNPCUnit, "DieLight",		pos, D3DXVECTOR2(-1,-1), D3DXVECTOR2(3,-1) )
	if pSeq ~= nil then
	
		pSeq:SetLandPosition( pNPCUnit:GetLandPosition_LUA().y )
		pNPCUnit:SetDieSeq( pSeq:GetHandle() )
	
	end
	pNPCUnit:PlaySound_LUA( "DieLight.ogg" )
	
end

------------------------------------------------------------------------------
function MovePos( pos, dirvector, dist )
	
	pos.x = pos.x + dist * dirvector.x
	pos.y = pos.y + dist * dirvector.y
	pos.z = pos.z + dist * dirvector.z
	
	return pos
	
end