-- lua header. UTF-8 인코딩 인식을 위해 이 줄은 지우지 마세요.


-- Lizardman_ShamanKing.lua

INIT_SYSTEM = 
{
	UNIT_WIDTH		= 50.0,
	UNIT_HEIGHT		= 200.0,
	UNIT_LAYER		= X2_LAYER["XL_UNIT_0"],
	
	UNIT_SCALE		= 1.25,
}


INIT_DEVICE = 
{
	READY_TEXTURE = 
	{		
		"Gate_Light2.dds",
		"smoke02.dds",		
	},
	
	READY_SOUND = 
	{
		"LizardMan_Shaman_Slash.ogg",
		"LizardShaman_DrainHit.ogg",
		"Lizard_HyperFrame.ogg",
		"LizardShaman_SP_FireWall.ogg",
		"LizardShaman_Laugh.ogg",
		"LizardShaman_Shout1.ogg",
		"LizardShaman_Summon.ogg",
		"LizardShaman_Scream1.ogg",
        "Fire3.ogg",
	},
	
	READY_XSKIN_MESH = 
	{
		"FireBall01_GhostMagician.X",	
		"Effect_ElSword_FlameGager.X",
	},
	
}


INIT_MOTION = 
{
	MOTION_FILE_NAME		= "Motion_LizardMan_ShamanKing.x",
}

INIT_PHYSIC = 
{
	RELOAD_ACCEL		= 2000,
	G_ACCEL				= 4000,
	MAX_G_SPEED			= -2000,
	
	WALK_SPEED			= 600,
	RUN_SPEED			= 600,
	JUMP_SPEED			= 1500,
	DASH_JUMP_SPEED		= 1800,
}


INIT_COMPONENT = 
{
	IMMUNITY_TIME_STOP = TRUE,
	MAX_HP				= 30000,
	MP_CHANGE_RATE		= 3,
	MP_CHARGE_RATE		= 130,
	
	
	DRAW_SMALL_MP_BAR	= TRUE,
	
	
	SHADOW_SIZE			= 200,
	SHADOW_FILE_NAME	= "shadow.dds",
	
	SMALL_HP_BAR_BLUE	= "Small_HP_bar_Blue.TGA",
	SMALL_HP_BAR_RED	= "Small_HP_bar_Red.TGA",
	SMALL_HP_BAR_YELLOW = "Small_HP_bar_Yellow.TGA",
	
	QUESTION_MARK_SEQ		= "QuestionMarkNPC",
	EXCLAMATION_MARK_SEQ	= "ExclamationMarkNPC",
	--MIND_FLAG_HEIGHT		= 230,
	
	HYPER_MODE_COUNT	= 0,
	MAX_HYPER_MODE_TIME	= 30,
	
 	RAGE_COUNT_MAX		= 20,
	RAGE_TIME_MAX		= 3,

	HITTED_TYPE			= HITTED_TYPE["HTD_MEAT"],
	
	FALL_DOWN			= TRUE,
	
	
	
	WEAPON0 = 
	{
		WEAPON_FILE_NAME	= "Mesh_LizardMan_ShamanKing_Weapon.X",
		WEAPON_BONE_NAME	= "Dummy1_Rhand",
			
		USE_SLASH_TRACE		= FALSE,
	},
	
	
	
	BOSS_GAGE_FACE_TEX			= "DLG_BossState.tga",
	BOSS_GAGE_FACE_TEX_PIECE	= "Lizard_Man_Shamanking",		
	BOSS_NAME_TEX				= "HQ_BOSS_NAME_LIZARD_MAN_SHAMAN_KING.dds",
	
	

	

}

INIT_STATE = 
{
	{ STATE_NAME = "LIZARDMAN_SHAMAN_KING_EXPERT_START",					LUA_CAMERA_MOVE_FUNC = "LIZARDMAN_SHAMAN_KING_EXPERT_START_CAMERA_MOVE",},
	
	{ STATE_NAME = "LIZARDMAN_SHAMAN_KING_EXPERT_WAIT",					LUA_FRAME_MOVE_FUNC  = "LIZARDMAN_SHAMAN_KING_EXPERT_WAIT_FRAME_MOVE",	},
	{ STATE_NAME = "LIZARDMAN_SHAMAN_KING_EXPERT_WAIT_START",				},
		
	{ STATE_NAME = "LIZARDMAN_SHAMAN_KING_EXPERT_WALK",					LUA_FRAME_MOVE_FUNC  = "LIZARDMAN_SHAMAN_KING_EXPERT_WALK_FRAME_MOVE",
																	LUA_STATE_END_FUNC = "LIZARDMAN_SHAMAN_KING_EXPERT_WALK_STATE_END"						},
		
	{ STATE_NAME = "LIZARDMAN_SHAMAN_KING_EXPERT_JUMP_UP",					},
	{ STATE_NAME = "LIZARDMAN_SHAMAN_KING_EXPERT_JUMP_DOWN",				LUA_STATE_END_FUNC = "LIZARDMAN_SHAMAN_KING_EXPERT_JUMP_DOWN_STATE_END"					},
	{ STATE_NAME = "LIZARDMAN_SHAMAN_KING_EXPERT_JUMP_UP_DIR",				},
	{ STATE_NAME = "LIZARDMAN_SHAMAN_KING_EXPERT_JUMP_DOWN_DIR",			LUA_STATE_END_FUNC = "LIZARDMAN_SHAMAN_KING_EXPERT_JUMP_DOWN_DIR_STATE_END"				},
	{ STATE_NAME = "LIZARDMAN_SHAMAN_KING_EXPERT_JUMP_LANDING",			},


	{ STATE_NAME = "LIZARDMAN_SHAMAN_KING_EXPERT_ATTACK",					},	
	{ STATE_NAME = "LIZARDMAN_SHAMAN_KING_EXPERT_DRAIN_HIT",				LUA_STATE_START_FUNC = "LIZARDMAN_SHAMAN_KING_EXPERT_DRAIN_HIT_STATE_START",
																	LUA_FRAME_MOVE_FUNC  = "LIZARDMAN_SHAMAN_KING_EXPERT_DRAIN_HIT_FRAME_MOVE",					
																	LUA_STATE_END_FUNC   = "LIZARDMAN_SHAMAN_KING_EXPERT_DRAIN_HIT_STATE_END",			},
	
	{ STATE_NAME = "LIZARDMAN_SHAMAN_KING_EXPERT_COMBO",					LUA_FRAME_MOVE_FUNC = "LIZARDMAN_SHAMAN_KING_EXPERT_COMBO_FRAME_MOVE",						},	
	{ STATE_NAME = "LIZARDMAN_SHAMAN_KING_EXPERT_SP_HYPER_FRAME",			LUA_FRAME_MOVE_FUNC = "LIZARDMAN_SHAMAN_KING_EXPERT_SP_HYPER_FRAME_FRAME_MOVE",			
																	LUA_STATE_END_FUNC  = "LIZARDMAN_SHAMAN_KING_EXPERT_SP_HYPER_FRAME_STATE_END",			},
	
	
	{ STATE_NAME = "LIZARDMAN_SHAMAN_KING_EXPERT_SP_FIREWALL",				LUA_STATE_START_FUNC = "LIZARDMAN_SHAMAN_KING_EXPERT_SP_FIREWALL_STATE_START",
																	LUA_FRAME_MOVE_FUNC  = "LIZARDMAN_SHAMAN_KING_EXPERT_SP_FIREWALL_FRAME_MOVE",
																	LUA_STATE_END_FUNC   = "LIZARDMAN_SHAMAN_KING_EXPERT_SP_FIREWALL_STATE_END",			},
	
	
	{ STATE_NAME = "LIZARDMAN_SHAMAN_KING_EXPERT_SUMMON",					LUA_FRAME_MOVE_FUNC  = "LIZARDMAN_SHAMAN_KING_EXPERT_SUMMON_FRAME_MOVE",				
																	STATE_COOL_TIME = 5, 		},
	
	
	--리액션 관련
	{ STATE_NAME = "LIZARDMAN_SHAMAN_KING_EXPERT_DAMAGE_SMALL",			LUA_FRAME_MOVE_FUNC = "LIZARDMAN_SHAMAN_KING_EXPERT_DAMAGE_SMALL_FRAME_MOVE"				},
	{ STATE_NAME = "LIZARDMAN_SHAMAN_KING_EXPERT_DAMAGE_BIG",				LUA_FRAME_MOVE_FUNC = "LIZARDMAN_SHAMAN_KING_EXPERT_DAMAGE_BIG_FRAME_MOVE"				},
	{ STATE_NAME = "LIZARDMAN_SHAMAN_KING_EXPERT_DAMAGE_DOWN_FRONT",		LUA_FRAME_MOVE_FUNC = "LIZARDMAN_SHAMAN_KING_EXPERT_DAMAGE_DOWN_FRONT_FRAME_MOVE"		},
	{ STATE_NAME = "LIZARDMAN_SHAMAN_KING_EXPERT_DAMAGE_DOWN_BACK",		LUA_FRAME_MOVE_FUNC = "LIZARDMAN_SHAMAN_KING_EXPERT_DAMAGE_DOWN_BACK_FRAME_MOVE"			},
	{ STATE_NAME = "LIZARDMAN_SHAMAN_KING_EXPERT_DAMAGE_FLY_FRONT",		},
	{ STATE_NAME = "LIZARDMAN_SHAMAN_KING_EXPERT_DAMAGE_FLY_BACK",			},
	{ STATE_NAME = "LIZARDMAN_SHAMAN_KING_EXPERT_DAMAGE_AIR",				},
	{ STATE_NAME = "LIZARDMAN_SHAMAN_KING_EXPERT_DAMAGE_AIR_DOWN",			},
	{ STATE_NAME = "LIZARDMAN_SHAMAN_KING_EXPERT_DAMAGE_AIR_UP",			},
	{ STATE_NAME = "LIZARDMAN_SHAMAN_KING_EXPERT_DAMAGE_AIR_FALL",			},	
	{ STATE_NAME = "LIZARDMAN_SHAMAN_KING_EXPERT_DAMAGE_AIR_DOWN_LANDING",	LUA_FRAME_MOVE_FUNC = "LIZARDMAN_SHAMAN_KING_EXPERT_DAMAGE_AIR_DOWN_LANDING_FRAME_MOVE"	},
	{ STATE_NAME = "LIZARDMAN_SHAMAN_KING_EXPERT_STAND_UP_FRONT",			},
	{ STATE_NAME = "LIZARDMAN_SHAMAN_KING_EXPERT_STAND_UP_BACK",			},
	{ STATE_NAME = "LIZARDMAN_SHAMAN_KING_EXPERT_STAND_UP_ATTACK_FRONT",	LUA_FRAME_MOVE_FUNC = "LIZARDMAN_SHAMAN_KING_EXPERT_STAND_UP_ATTACK_FRONT_FRAME_MOVE"	},
	{ STATE_NAME = "LIZARDMAN_SHAMAN_KING_EXPERT_STAND_UP_ATTACK_BACK",	LUA_FRAME_MOVE_FUNC = "LIZARDMAN_SHAMAN_KING_EXPERT_STAND_UP_ATTACK_BACK_FRAME_MOVE"		},
	
	{ STATE_NAME = "LIZARDMAN_SHAMAN_KING_EXPERT_DYING_LAND_FRONT",		LUA_STATE_START_FUNC = "LIZARDMAN_SHAMAN_KING_EXPERT_DYING_LAND_STATE_START",},
	{ STATE_NAME = "LIZARDMAN_SHAMAN_KING_EXPERT_DYING_LAND_BACK",			LUA_STATE_START_FUNC = "LIZARDMAN_SHAMAN_KING_EXPERT_DYING_LAND_STATE_START",},
	{ STATE_NAME = "LIZARDMAN_SHAMAN_KING_EXPERT_DYING_SKY",				LUA_STATE_START_FUNC = "LIZARDMAN_SHAMAN_KING_EXPERT_DYING_LAND_STATE_START",},
	
	{ STATE_NAME = "LIZARDMAN_SHAMAN_KING_EXPERT_WIN", 						},
	
	
	START_STATE					= "LIZARDMAN_SHAMAN_KING_EXPERT_START",
	WAIT_STATE					= "LIZARDMAN_SHAMAN_KING_EXPERT_WAIT",
	
	SMALL_DAMAGE_LAND_FRONT		= "LIZARDMAN_SHAMAN_KING_EXPERT_DAMAGE_SMALL",
	SMALL_DAMAGE_LAND_BACK		= "LIZARDMAN_SHAMAN_KING_EXPERT_DAMAGE_SMALL",
	BIG_DAMAGE_LAND_FRONT		= "LIZARDMAN_SHAMAN_KING_EXPERT_DAMAGE_BIG",
	BIG_DAMAGE_LAND_BACK		= "LIZARDMAN_SHAMAN_KING_EXPERT_DAMAGE_BIG",
	DOWN_DAMAGE_LAND_FRONT		= "LIZARDMAN_SHAMAN_KING_EXPERT_DAMAGE_DOWN_FRONT",
	DOWN_DAMAGE_LAND_BACK		= "LIZARDMAN_SHAMAN_KING_EXPERT_DAMAGE_DOWN_BACK",
	FLY_DAMAGE_FRONT			= "LIZARDMAN_SHAMAN_KING_EXPERT_DAMAGE_FLY_FRONT",
	FLY_DAMAGE_BACK				= "LIZARDMAN_SHAMAN_KING_EXPERT_DAMAGE_FLY_BACK",
	SMALL_DAMAGE_AIR			= "LIZARDMAN_SHAMAN_KING_EXPERT_DAMAGE_AIR",	
	BIG_DAMAGE_AIR				= "LIZARDMAN_SHAMAN_KING_EXPERT_DAMAGE_AIR",
	DOWN_DAMAGE_AIR				= "LIZARDMAN_SHAMAN_KING_EXPERT_DAMAGE_AIR_DOWN",
	DOWN_DAMAGE_AIR_LANDING				= "LIZARDMAN_SHAMAN_KING_EXPERT_DAMAGE_AIR_DOWN_LANDING",
	UP_DAMAGE					= "LIZARDMAN_SHAMAN_KING_EXPERT_DAMAGE_AIR_UP",
	DAMAGE_REVENGE				= "LIZARDMAN_SHAMAN_KING_EXPERT_DAMAGE_SMALL",
	
	DAMAGE_EXTRA_STATES         = {"LIZARDMAN_SHAMAN_KING_EXPERT_DAMAGE_AIR_FALL","LIZARDMAN_SHAMAN_KING_EXPERT_STAND_UP_FRONT","LIZARDMAN_SHAMAN_KING_EXPERT_STAND_UP_BACK",
	"LIZARDMAN_SHAMAN_KING_EXPERT_STAND_UP_ATTACK_FRONT","LIZARDMAN_SHAMAN_KING_EXPERT_STAND_UP_ATTACK_BACK",
	"LIZARDMAN_SHAMAN_KING_EXPERT_JUMP_DOWN","LIZARDMAN_SHAMAN_KING_EXPERT_JUMP_LANDING",},	
	
	DYING_LAND_FRONT			= "LIZARDMAN_SHAMAN_KING_EXPERT_DYING_LAND_FRONT",
	DYING_LAND_BACK				= "LIZARDMAN_SHAMAN_KING_EXPERT_DYING_LAND_BACK",
	DYING_SKY					= "LIZARDMAN_SHAMAN_KING_EXPERT_DYING_SKY",

	REVENGE_ATTACK				= "",	
}



INIT_AI = 
{
	TARGET = 
	{
		TARGET_PRIORITY 			= TARGET_PRIORITY["TP_LOW_HP_FIRST"],
		TARGET_INTERVAL				= 2,		-- sec
		TARGET_NEAR_RANGE			= 400,		-- 이 거리보다 가까우면 TARGET_SUCCESS_RATE에 관계없이 무조건 타게팅된다
		TARGET_RANGE				= 800,		-- cm
		TARGET_LOST_RANGE			= 1200,		-- cm
		TARGET_SUCCESS_RATE			= 100,  --50,		-- %
		ATTACK_TARGET_RATE			= 100, -- 30,		-- 나를 공격한 유닛을 타게팅할 확률
		PRESERVE_LAST_TARGET_RATE	= 100, -- 30,		-- 이전에 타게팅된 유닛을 계속 타게팅할 확률
	},

	CHASE_MOVE = 
	{		
		MOVE_SPLIT_RANGE	= 600,
		DEST_GAP			= 150,	-- 목적지에서 이 거리 안에 있으면 도착했다고 판단한다
		MOVE_GAP			= 160,
		
		DIR_CHANGE_INTERVAL = 0.7,
		
		WALK_INTERVAL		= 3,
		NEAR_WALK_RATE		= 100,   --  70,
		FAR_WALK_RATE		= 100,   -- 30,
		
		JUMP_INTERVAL		= 5,
		UP_JUMP_RATE		= 100, -- 40,
		UP_DOWN_RATE		= 20,
		DOWN_JUMP_RATE		= 100,    --  20,
		DOWN_DOWN_RATE		= 40,
		
		LINE_END_RANGE		= 80,	-- cm
	},	
	
	PATROL_MOVE = 	
	{
		PATROL_BEGIN_RATE		= 100, --50,		
		PATROL_RANGE			= 200,
		PATROL_COOL_TIME		= 2,
		ONLY_THIS_LINE_GROUP	= TRUE,
	},
	
	ESCAPE_MOVE = 
	{		
		MOVE_SPLIT_RANGE	= 500,	-- cm
		ESCAPE_GAP			= 600,	-- 이 거리 보다 멀어지면 도망 성공
		
		WALK_INTERVAL		= 1.5,	-- 초
		NEAR_WALK_RATE		= 100,   --  10,
		FAR_WALK_RATE		= 100,   -- 10,
		
		JUMP_INTERVAL		= 10,
		UP_JUMP_RATE		= 100, -- 30,
		UP_DOWN_RATE		= 30,
		DOWN_JUMP_RATE		= 100,    --  30,
		DOWN_DOWN_RATE		= 30,
		
		LINE_END_RANGE		= 80,	-- cm
	},

}




LIZARDMAN_SHAMAN_KING_EXPERT_WIN = 
{
	ANIM_NAME					= "Win",
	PLAY_TYPE					= XSKIN_ANIM_PLAYTYPE["XAP_ONE_WAIT"],
	TRANSITION					= TRUE,
	
	CAN_PUSH_UNIT				= TRUE,
	CAN_PASS_UNIT				= FALSE,	
	
	INVINCIBLE					= { 0, 100, },

    SOUND_PLAY0			= { 1.190, "LizardShaman_Laugh.ogg" },
	
	SPEED_X						= 0,
	SPEED_Y						= 0,

	RIGHT						= TRUE,
	
	IMMADIATE_PACKET_SEND		= TRUE,
}


LIZARDMAN_SHAMAN_KING_EXPERT_START = 
{
	ANIM_NAME					= "WaitStart",
	PLAY_TYPE					= XSKIN_ANIM_PLAYTYPE["XAP_ONE_WAIT"],
	TRANSITION					= FALSE,
	
	CAN_PUSH_UNIT				= TRUE,
	CAN_PASS_UNIT				= FALSE,
	IMMADIATE_PACKET_SEND		= TRUE,	

    SOUND_PLAY0			= { 0.008, "LizardShaman_Laugh.ogg" },
	
	EVENT_PROCESS = 
	{		
		{ STATE_CHANGE_TYPE["SCT_CONDITION_TABLE"],		"LIZARDMAN_SHAMAN_KING_EXPERT_WAIT",		"CT_LIZARDMAN_SHAMAN_KING_EXPERT_WAIT"				},
	},
	
	CT_LIZARDMAN_SHAMAN_KING_EXPERT_WAIT = 
	{
		STATE_TIME_OVER			= 3,
	},
}



LIZARDMAN_SHAMAN_KING_EXPERT_WAIT = 
{
	ANIM_NAME					= "Wait",
	PLAY_TYPE					= XSKIN_ANIM_PLAYTYPE["XAP_LOOP"],
	TRANSITION					= TRUE,
	
	CAN_PUSH_UNIT				= TRUE,
	CAN_PASS_UNIT				= FALSE,	
	
	SPEED_X						= 0,
	SPEED_Y						= 0,
	
	PASSIVE_SPEED_X				= 0,
	
	IMMADIATE_PACKET_SEND		= TRUE,
	EVENT_INTERVAL_TIME0		= 2,
	
	EVENT_PROCESS = 
	{		
		
		{ STATE_CHANGE_TYPE["SCT_FOOT_ON_LINE_FALSE_DOWN"],	"LIZARDMAN_SHAMAN_KING_EXPERT_JUMP_DOWN",				},
		{ STATE_CHANGE_TYPE["SCT_CONDITION_FUNCTION"],		"LIZARDMAN_SHAMAN_KING_EXPERT_WIN",					"CF_LIZARDMAN_SHAMAN_KING_EXPERT_WIN",	},	
		
		{ STATE_CHANGE_TYPE["SCT_CONDITION_FUNCTION"],		"LIZARDMAN_SHAMAN_KING_EXPERT_SUMMON",					"CF_LIZARDMAN_SHAMAN_KING_EXPERT_SUMMON",	},	

		{ STATE_CHANGE_TYPE["SCT_CONDITION_TABLE"],			"LIZARDMAN_SHAMAN_KING_EXPERT_SP_FIREWALL",			"CT_LIZARDMAN_SHAMAN_KING_EXPERT_SP_FIREWALL",		},
		{ STATE_CHANGE_TYPE["SCT_CONDITION_TABLE"],			"LIZARDMAN_SHAMAN_KING_EXPERT_SP_HYPER_FRAME",			"CT_LIZARDMAN_SHAMAN_KING_EXPERT_SP_HYPER_FRAME",	},
		
		
		
		
		{ STATE_CHANGE_TYPE["SCT_CONDITION_TABLE"],			"LIZARDMAN_SHAMAN_KING_EXPERT_ATTACK",					"CT_LIZARDMAN_SHAMAN_KING_EXPERT_ATTACK",			},
		{ STATE_CHANGE_TYPE["SCT_CONDITION_TABLE"],			"LIZARDMAN_SHAMAN_KING_EXPERT_DRAIN_HIT",				"CT_LIZARDMAN_SHAMAN_KING_EXPERT_DRAIN_HIT",		},
		{ STATE_CHANGE_TYPE["SCT_CONDITION_TABLE"],			"LIZARDMAN_SHAMAN_KING_EXPERT_COMBO",					"CT_LIZARDMAN_SHAMAN_KING_EXPERT_COMBO",			},
	
		{ STATE_CHANGE_TYPE["SCT_CONDITION_TABLE"],			"LIZARDMAN_SHAMAN_KING_EXPERT_WAIT_START",				"CT_LIZARDMAN_SHAMAN_KING_EXPERT_WAIT_START",		},
		
		{ STATE_CHANGE_TYPE["SCT_AI_WALK"],					"LIZARDMAN_SHAMAN_KING_EXPERT_WALK",					},
		{ STATE_CHANGE_TYPE["SCT_AI_DASH"],					"LIZARDMAN_SHAMAN_KING_EXPERT_WALK",					},
		{ STATE_CHANGE_TYPE["SCT_AI_JUMP"],					"LIZARDMAN_SHAMAN_KING_EXPERT_JUMP_UP",					},
		{ STATE_CHANGE_TYPE["SCT_AI_JUMP_DIR"],				"LIZARDMAN_SHAMAN_KING_EXPERT_JUMP_UP_DIR",				},
		{ STATE_CHANGE_TYPE["SCT_AI_DOWN"],					"LIZARDMAN_SHAMAN_KING_EXPERT_JUMP_DOWN",				},
		{ STATE_CHANGE_TYPE["SCT_AI_DOWN_DIR"],				"LIZARDMAN_SHAMAN_KING_EXPERT_JUMP_DOWN_DIR",			},
	},
	
	CT_LIZARDMAN_SHAMAN_KING_EXPERT_ATTACK = 
	{
		EVENT_INTERVAL_ID			= 0,
		DISTANCE_TO_TARGET_NEAR		= 400,
		RATE						= 50,
	},
		
	CT_LIZARDMAN_SHAMAN_KING_EXPERT_DRAIN_HIT =
	{
		EVENT_INTERVAL_ID			= 0,
		DISTANCE_TO_TARGET_NEAR		= 600,
		RATE						= 50,
	},
	
	CT_LIZARDMAN_SHAMAN_KING_EXPERT_COMBO =
	{
		EVENT_INTERVAL_ID			= 0,
		DISTANCE_TO_TARGET_NEAR		= 600,
		RATE						= 50,
	},
	
	CT_LIZARDMAN_SHAMAN_KING_EXPERT_SP_HYPER_FRAME = 
	{
		EVENT_INTERVAL_ID			= 0,
		DISTANCE_TO_TARGET_NEAR		= 800,
		MY_MP_MORE_THAN_PERCENT		= 80,
		RATE						= 30,
	},
	
	CT_LIZARDMAN_SHAMAN_KING_EXPERT_SP_FIREWALL = 
	{
		EVENT_INTERVAL_ID			= 0,
		DISTANCE_TO_TARGET_NEAR		= 800,
		MY_MP_MORE_THAN_PERCENT		= 80,
		RATE						= 30,
	},
		
	CT_LIZARDMAN_SHAMAN_KING_EXPERT_WAIT_START = 
	{
		ANIM_PLAY_COUNT				= 2,
		RATE						= 60,
		HAVE_TARGET					= 0,		-- false
	},
	
    TALK_BOX =
	{
		EVENT_INTERVAL_ID			= 0,
 		{ RATE = 10,		MESSAGE = STR_ID_1659 },
 	},
		
}






LIZARDMAN_SHAMAN_KING_EXPERT_WAIT_START = 
{
	ANIM_NAME					= "WaitStart",
	PLAY_TYPE					= XSKIN_ANIM_PLAYTYPE["XAP_ONE_WAIT"],
	TRANSITION					= FALSE,
	
	CAN_PUSH_UNIT				= TRUE,
	CAN_PASS_UNIT				= FALSE,
	IMMADIATE_PACKET_SEND		= TRUE,	
	
	EVENT_PROCESS = 
	{		
		{ STATE_CHANGE_TYPE["SCT_FOOT_ON_LINE_FALSE_DOWN"],		"LIZARDMAN_SHAMAN_KING_EXPERT_JUMP_DOWN",			},
		{ STATE_CHANGE_TYPE["SCT_MOTION_END"],					"LIZARDMAN_SHAMAN_KING_EXPERT_WAIT",					},
	},
	
	TALK_BOX =
	{
		EVENT_INTERVAL_ID			= 0,
 		{ RATE = 30, MESSAGE = STR_ID_2567 },
 	},

}




LIZARDMAN_SHAMAN_KING_EXPERT_WALK = 
{
	ANIM_NAME					= "Walk",
	PLAY_TYPE					= XSKIN_ANIM_PLAYTYPE["XAP_LOOP"],
	TRANSITION					= TRUE,
	
	CAN_PUSH_UNIT				= TRUE,
	CAN_PASS_UNIT				= FALSE,
	
	PASSIVE_SPEED_X				= INIT_PHYSIC["WALK_SPEED"],
	
	ALLOW_DIR_CHANGE			= TRUE,
	IMMADIATE_PACKET_SEND		= TRUE,
	
	EVENT_INTERVAL_TIME0		= 2,
	EVENT_INTERVAL_TIME1		= 3,
	
	EVENT_PROCESS = 
	{		
		
		{ STATE_CHANGE_TYPE["SCT_FOOT_ON_LINE_FALSE_DOWN"],	"LIZARDMAN_SHAMAN_KING_EXPERT_JUMP_DOWN",			},
		{ STATE_CHANGE_TYPE["SCT_CONDITION_FUNCTION"],		"LIZARDMAN_SHAMAN_KING_EXPERT_WIN",					"CF_LIZARDMAN_SHAMAN_KING_EXPERT_WIN",	},	
		{ STATE_CHANGE_TYPE["SCT_CONDITION_FUNCTION"],		"LIZARDMAN_SHAMAN_KING_EXPERT_SUMMON",					"CF_LIZARDMAN_SHAMAN_KING_EXPERT_SUMMON",	},	
		
		
		{ STATE_CHANGE_TYPE["SCT_CONDITION_TABLE"],			"LIZARDMAN_SHAMAN_KING_EXPERT_SP_FIREWALL",			"CT_LIZARDMAN_SHAMAN_KING_EXPERT_SP_FIREWALL",			},
		{ STATE_CHANGE_TYPE["SCT_CONDITION_TABLE"],			"LIZARDMAN_SHAMAN_KING_EXPERT_SP_HYPER_FRAME",			"CT_LIZARDMAN_SHAMAN_KING_EXPERT_SP_HYPER_FRAME",			},
		
		{ STATE_CHANGE_TYPE["SCT_CONDITION_TABLE"],			"LIZARDMAN_SHAMAN_KING_EXPERT_ATTACK",					"CT_LIZARDMAN_SHAMAN_KING_EXPERT_ATTACK",				},
		{ STATE_CHANGE_TYPE["SCT_CONDITION_TABLE"],			"LIZARDMAN_SHAMAN_KING_EXPERT_DRAIN_HIT",				"CT_LIZARDMAN_SHAMAN_KING_EXPERT_DRAIN_HIT",			},
		{ STATE_CHANGE_TYPE["SCT_CONDITION_TABLE"],			"LIZARDMAN_SHAMAN_KING_EXPERT_COMBO",					"CT_LIZARDMAN_SHAMAN_KING_EXPERT_COMBO",			},

		{ STATE_CHANGE_TYPE["SCT_AI_WAIT"],					"LIZARDMAN_SHAMAN_KING_EXPERT_WAIT",						},
		{ STATE_CHANGE_TYPE["SCT_AI_DASH"],					"LIZARDMAN_SHAMAN_KING_EXPERT_WALK",						},
		{ STATE_CHANGE_TYPE["SCT_AI_JUMP"],					"LIZARDMAN_SHAMAN_KING_EXPERT_JUMP_UP",					},
		{ STATE_CHANGE_TYPE["SCT_AI_JUMP_DIR"],				"LIZARDMAN_SHAMAN_KING_EXPERT_JUMP_UP_DIR",				},
		{ STATE_CHANGE_TYPE["SCT_AI_DOWN"],					"LIZARDMAN_SHAMAN_KING_EXPERT_JUMP_DOWN",				},
		{ STATE_CHANGE_TYPE["SCT_AI_DOWN_DIR"],				"LIZARDMAN_SHAMAN_KING_EXPERT_JUMP_DOWN_DIR",			},
	},
	
	CT_LIZARDMAN_SHAMAN_KING_EXPERT_ATTACK = 
	{
		EVENT_INTERVAL_ID			= 0,
		DISTANCE_TO_TARGET_NEAR		= 400,
		RATE						= 50,
	},
	CT_LIZARDMAN_SHAMAN_KING_EXPERT_DRAIN_HIT = 
	{
		EVENT_INTERVAL_ID			= 0,
		DISTANCE_TO_TARGET_NEAR		= 600,
		RATE						= 50,
	},	
		
	CT_LIZARDMAN_SHAMAN_KING_EXPERT_COMBO = 
	{
		EVENT_INTERVAL_ID			= 0,
		DISTANCE_TO_TARGET_NEAR		= 600,
		RATE						= 50,
	},	
	
	CT_LIZARDMAN_SHAMAN_KING_EXPERT_SP_HYPER_FRAME = 
	{
		EVENT_INTERVAL_ID			= 0,
		DISTANCE_TO_TARGET_NEAR		= 800,
		MY_MP_MORE_THAN_PERCENT		= 80,
		RATE						= 30,
	},
	
	CT_LIZARDMAN_SHAMAN_KING_EXPERT_SP_FIREWALL = 
	{
		EVENT_INTERVAL_ID			= 0,
		DISTANCE_TO_TARGET_NEAR		= 800,
		MY_MP_MORE_THAN_PERCENT		= 80,
		RATE						= 30,
	},
		

	
	TALK_BOX =
 	{
 		EVENT_INTERVAL_ID		= 1,
		{ RATE = 10, MESSAGE = STR_ID_2574 },
		{ RATE = 10, MESSAGE = STR_ID_1472 },
	},
}



LIZARDMAN_SHAMAN_KING_EXPERT_JUMP_UP = 
{
	ANIM_NAME					= "JumpUp",
	PLAY_TYPE					= XSKIN_ANIM_PLAYTYPE["XAP_LOOP"],
	TRANSITION					= TRUE,
	LAND_CONNECT				= FALSE,
	
	CAN_PUSH_UNIT				= TRUE,
	CAN_PASS_UNIT				= FALSE,
	
	SPEED_X						= 0,
	SPEED_Y						= INIT_PHYSIC["JUMP_SPEED"],
	
	ADD_POS_Y					= 45, 
	
	IMMADIATE_PACKET_SEND		= TRUE,
	
	EVENT_PROCESS = 
	{		
		{ STATE_CHANGE_TYPE["SCT_NEGATIVE_Y_SPEED"],		"LIZARDMAN_SHAMAN_KING_EXPERT_JUMP_DOWN",			},
	},
	
	
}

LIZARDMAN_SHAMAN_KING_EXPERT_JUMP_DOWN = 
{
	ANIM_NAME					= "JumpDown",
	PLAY_TYPE					= XSKIN_ANIM_PLAYTYPE["XAP_LOOP"],
	TRANSITION					= TRUE,
	LAND_CONNECT				= FALSE,
	
	CAN_PUSH_UNIT				= TRUE,
	CAN_PASS_UNIT				= FALSE,
		 
	
	IMMADIATE_PACKET_SEND		= TRUE,
		
	EVENT_PROCESS = 
	{		
		{ STATE_CHANGE_TYPE["SCT_FOOT_ON_LINE_TRUE"],		"LIZARDMAN_SHAMAN_KING_EXPERT_JUMP_LANDING",				},
	},
}

LIZARDMAN_SHAMAN_KING_EXPERT_JUMP_UP_DIR = 
{
	ANIM_NAME					= "JumpUp",
	PLAY_TYPE					= XSKIN_ANIM_PLAYTYPE["XAP_LOOP"],
	TRANSITION					= TRUE,
	LAND_CONNECT				= FALSE,
	
	CAN_PUSH_UNIT				= TRUE,
	CAN_PASS_UNIT				= FALSE,
		
	PASSIVE_SPEED_X				= INIT_PHYSIC["WALK_SPEED"],
	SPEED_Y						= INIT_PHYSIC["JUMP_SPEED"],
	
	ADD_POS_Y					= 45, 
	
	IMMADIATE_PACKET_SEND		= TRUE,
	
	EVENT_PROCESS = 
	{		
		
		{ STATE_CHANGE_TYPE["SCT_NEGATIVE_Y_SPEED"],		"LIZARDMAN_SHAMAN_KING_EXPERT_JUMP_DOWN_DIR",				},
	},
	

}

LIZARDMAN_SHAMAN_KING_EXPERT_JUMP_DOWN_DIR = 
{
	ANIM_NAME					= "JumpDown",
	PLAY_TYPE					= XSKIN_ANIM_PLAYTYPE["XAP_LOOP"],
	TRANSITION					= TRUE,
	LAND_CONNECT				= FALSE,
	
	CAN_PUSH_UNIT				= TRUE,
	CAN_PASS_UNIT				= FALSE,
	
	PASSIVE_SPEED_X				= INIT_PHYSIC["WALK_SPEED"],
	 
	
	IMMADIATE_PACKET_SEND		= TRUE,
		
	EVENT_PROCESS = 
	{		
		{ STATE_CHANGE_TYPE["SCT_FOOT_ON_LINE_TRUE"],		"LIZARDMAN_SHAMAN_KING_EXPERT_JUMP_LANDING",				},
	},
}

LIZARDMAN_SHAMAN_KING_EXPERT_JUMP_LANDING = 
{
	ANIM_NAME					= "JumpLanding",
	PLAY_TYPE					= XSKIN_ANIM_PLAYTYPE["XAP_ONE_WAIT"],
	TRANSITION					= TRUE,
	LAND_CONNECT				= FALSE,
	
	CAN_PUSH_UNIT				= TRUE,
	CAN_PASS_UNIT				= FALSE,
	
    SOUND_PLAY0			= { 0.121, "JumpLand.ogg" },

	SPEED_X						= 0,
	SPEED_Y						= 0,
		
	IMMADIATE_PACKET_SEND		= TRUE,

	EVENT_PROCESS = 
	{		
		{ STATE_CHANGE_TYPE["SCT_FOOT_ON_LINE_FALSE_DOWN"],	"LIZARDMAN_SHAMAN_KING_EXPERT_JUMP_DOWN",				},
		{ STATE_CHANGE_TYPE["SCT_MOTION_END"],				"LIZARDMAN_SHAMAN_KING_EXPERT_WAIT",						},
	},
}


LIZARDMAN_SHAMAN_KING_EXPERT_ATTACK = 
{
	ANIM_NAME					= "Attack",
	PLAY_TYPE					= XSKIN_ANIM_PLAYTYPE["XAP_ONE_WAIT"],
	TRANSITION					= FALSE,
	
	CAN_PUSH_UNIT				= TRUE,
	CAN_PASS_UNIT				= FALSE,

    SOUND_PLAY0			= { 0.438, "LizardMan_Shaman_Slash.ogg" },
    SOUND_PLAY1			= { 0.442, "LizardShaman_Shout1.ogg" },

	SPEED_X						= 0,
	SPEED_Y						= 0,	
	
	VIEW_TARGET					= TRUE,
	
	IMMADIATE_PACKET_SEND		= TRUE,
	
	TALK_BOX = 
	{
		{ RATE = 10, MESSAGE = STR_ID_1473 },
		{ RATE = 10, MESSAGE = STR_ID_1474 },
	},
	
	EVENT_PROCESS = 
	{	
		{ STATE_CHANGE_TYPE["SCT_FOOT_ON_LINE_FALSE_DOWN"],	"LIZARDMAN_SHAMAN_KING_EXPERT_JUMP_DOWN",					},
		{ STATE_CHANGE_TYPE["SCT_MOTION_END"],				"LIZARDMAN_SHAMAN_KING_EXPERT_WAIT",						},	

	},
		
	ATTACK_TIME0				= { 0.44, 0.51, },
	
	DAMAGE_DATA = 
	{
		DAMAGE_TYPE		= DAMAGE_TYPE["DT_PHYSIC"],
		HIT_TYPE		= HIT_TYPE["HT_ROD_SLASH"],
		REACT_TYPE		= REACT_TYPE["RT_SMALL_DAMAGE"],
		
		DAMAGE = 
		{
			PHYSIC		= 1.0,
		},
		
		BACK_SPEED_X			= INIT_PHYSIC["WALK_SPEED"],
		BACK_SPEED_Y			= 0.0,
		
		CAMERA_CRASH_GAP		= 5.0,	
		CAMERA_CRASH_TIME		= 0.2,		
	},
}






LIZARDMAN_SHAMAN_KING_EXPERT_DRAIN_HIT = 
{
	ANIM_NAME					= "DrainHit",
	PLAY_TYPE					= XSKIN_ANIM_PLAYTYPE["XAP_ONE_WAIT"],
	TRANSITION					= FALSE,
	
	CAN_PUSH_UNIT				= TRUE,
	CAN_PASS_UNIT				= FALSE,

	    SOUND_PLAY0			= { 0.433, "LizardShaman_DrainHit.ogg" },

	SPEED_X						= 0,
	SPEED_Y						= 0,
	
	SUPER_ARMOR					= TRUE,	
	
	VIEW_TARGET					= TRUE,
	
	IMMADIATE_PACKET_SEND		= TRUE,
	
	EVENT_PROCESS = 
	{	
		{ STATE_CHANGE_TYPE["SCT_FOOT_ON_LINE_FALSE_DOWN"],	"LIZARDMAN_SHAMAN_KING_EXPERT_JUMP_DOWN",										},
		{ STATE_CHANGE_TYPE["SCT_MOTION_END"],				"LIZARDMAN_SHAMAN_KING_EXPERT_WAIT",											},	

	},
}




LIZARDMAN_SHAMAN_KING_EXPERT_COMBO = 
{
	ANIM_NAME					= "Combo",
	PLAY_TYPE					= XSKIN_ANIM_PLAYTYPE["XAP_ONE_WAIT"],
	TRANSITION					= FALSE,
	
	CAN_PUSH_UNIT				= TRUE,
	CAN_PASS_UNIT				= FALSE,

	SPEED_X						= 0,
	SPEED_Y						= 0,	

    SOUND_PLAY0			= { 1.062, "LizardShaman_Shout1.ogg" },
    SOUND_PLAY1			= { 1.813, "LizardShaman_Shout1.ogg" },
    SOUND_PLAY2			= { 2.558, "LizardShaman_Shout1.ogg" },
	
	VIEW_TARGET					= TRUE,
	
	IMMADIATE_PACKET_SEND		= TRUE,
	
	EVENT_PROCESS = 
	{	
		{ STATE_CHANGE_TYPE["SCT_FOOT_ON_LINE_FALSE_DOWN"],	"LIZARDMAN_SHAMAN_KING_EXPERT_JUMP_DOWN",										},
		{ STATE_CHANGE_TYPE["SCT_MOTION_END"],				"LIZARDMAN_SHAMAN_KING_EXPERT_WAIT",											},	

	},

}


LIZARDMAN_SHAMAN_KING_EXPERT_SP_HYPER_FRAME = 
{
	ANIM_NAME					= "SP_HyperFrame",
	PLAY_TYPE					= XSKIN_ANIM_PLAYTYPE["XAP_ONE_WAIT"],
	TRANSITION					= FALSE,
	
	CAN_PUSH_UNIT				= TRUE,
	CAN_PASS_UNIT				= FALSE,

	SPEED_X						= 0,
	SPEED_Y						= 0,	

    SOUND_PLAY0			= { 0.779, "Lizard_HyperFrame.ogg" },
	
	VIEW_TARGET					= TRUE,
	
	IMMADIATE_PACKET_SEND		= TRUE,
	
	SUPER_ARMOR					= TRUE,
	
	EVENT_PROCESS = 
	{	
		{ STATE_CHANGE_TYPE["SCT_FOOT_ON_LINE_FALSE_DOWN"],	"LIZARDMAN_SHAMAN_KING_EXPERT_JUMP_DOWN",										},
		{ STATE_CHANGE_TYPE["SCT_MOTION_END"],				"LIZARDMAN_SHAMAN_KING_EXPERT_WAIT",											},	

	},

}




LIZARDMAN_SHAMAN_KING_EXPERT_SP_FIREWALL = 
{
	ANIM_NAME					= "SP_FireWall",
	PLAY_TYPE					= XSKIN_ANIM_PLAYTYPE["XAP_ONE_WAIT"],
	TRANSITION					= FALSE,
	
	CAN_PUSH_UNIT				= TRUE,
	CAN_PASS_UNIT				= FALSE,

	SPEED_X						= 0,
	SPEED_Y						= 0,	

    SOUND_PLAY0			= { 0.087, "LizardShaman_SP_FireWall.ogg" },
    SOUND_PLAY1			= { 0.097, "Fire3.ogg" },
	
	VIEW_TARGET					= TRUE,
	
	IMMADIATE_PACKET_SEND		= TRUE,
	
	SUPER_ARMOR					= TRUE,
	
	EVENT_PROCESS = 
	{	
		{ STATE_CHANGE_TYPE["SCT_FOOT_ON_LINE_FALSE_DOWN"],	"LIZARDMAN_SHAMAN_KING_EXPERT_JUMP_DOWN",										},
		{ STATE_CHANGE_TYPE["SCT_MOTION_END"],				"LIZARDMAN_SHAMAN_KING_EXPERT_WAIT",											},	
	},
}



LIZARDMAN_SHAMAN_KING_EXPERT_SUMMON = 
{
	ANIM_NAME					= "HighDarkCall",
	PLAY_TYPE					= XSKIN_ANIM_PLAYTYPE["XAP_ONE_WAIT"],
	TRANSITION					= FALSE,
	
	CAN_PUSH_UNIT				= TRUE,
	CAN_PASS_UNIT				= FALSE,

	SPEED_X						= 0,
	SPEED_Y						= 0,	

    SOUND_PLAY0			= { 0.584, "LizardShaman_Summon.ogg" },

	IMMADIATE_PACKET_SEND		= TRUE,
	SUPER_ARMOR					= TRUE,
	
	
	EVENT_PROCESS = 
	{	
		{ STATE_CHANGE_TYPE["SCT_FOOT_ON_LINE_FALSE_DOWN"],	"LIZARDMAN_SHAMAN_KING_EXPERT_JUMP_DOWN",										},
		{ STATE_CHANGE_TYPE["SCT_MOTION_END"],				"LIZARDMAN_SHAMAN_KING_EXPERT_WAIT",											},	
	},
}


LIZARDMAN_SHAMAN_KING_EXPERT_DAMAGE_SMALL = 
{
	ANIM_NAME					= "DamageSmall",
	PLAY_TYPE					= XSKIN_ANIM_PLAYTYPE["XAP_ONE_WAIT"],
	TRANSITION					= FALSE,
	LAND_CONNECT				= FALSE,
	
	CAN_PUSH_UNIT				= TRUE,
	CAN_PASS_UNIT				= FALSE,
	
	TALK_BOX = 
	{
		{ RATE = 10, MESSAGE = STR_ID_1475 },
	},
	
	EVENT_PROCESS = 
	{
		{ STATE_CHANGE_TYPE["SCT_MOTION_END"],					"LIZARDMAN_SHAMAN_KING_EXPERT_WAIT",												},
	},
}

LIZARDMAN_SHAMAN_KING_EXPERT_DAMAGE_BIG = 
{
	ANIM_NAME					= "DamageBig",
	PLAY_TYPE					= XSKIN_ANIM_PLAYTYPE["XAP_ONE_WAIT"],
	TRANSITION					= FALSE,
	LAND_CONNECT				= FALSE,
	
	CAN_PUSH_UNIT				= TRUE,
	CAN_PASS_UNIT				= FALSE,

    SOUND_PLAY0			= { 0.01, "LizardShaman_Scream1.ogg" , 50 },	

	TALK_BOX = 
	{
		{ RATE = 10, MESSAGE = STR_ID_1476 },
	},
	
	EVENT_PROCESS = 
	{
		{ STATE_CHANGE_TYPE["SCT_MOTION_END"],					"LIZARDMAN_SHAMAN_KING_EXPERT_WAIT",												},
	},
}

LIZARDMAN_SHAMAN_KING_EXPERT_DAMAGE_DOWN_FRONT = 
{
	ANIM_NAME					= "DamageDownFront",
	PLAY_TYPE					= XSKIN_ANIM_PLAYTYPE["XAP_ONE_WAIT"],
	TRANSITION					= FALSE,
	LAND_CONNECT				= FALSE,

	SUPER_ARMOR					= TRUE,
	DEFENCE						= { 0, 100, 70, },

    SOUND_PLAY0			= { 0.05, "LizardShaman_Scream1.ogg" },	
	
	CAN_PUSH_UNIT				= TRUE,
	CAN_PASS_UNIT				= FALSE,
	
	TALK_BOX = 
	{
		{ RATE = 10, MESSAGE = STR_ID_2568 },
		{ RATE = 10, MESSAGE = STR_ID_2569 },
	},
	
	EVENT_PROCESS = 
	{
		{ STATE_CHANGE_TYPE["SCT_FOOT_ON_LINE_FALSE_DOWN"],		"LIZARDMAN_SHAMAN_KING_EXPERT_DAMAGE_AIR_FALL",			},
		{ STATE_CHANGE_TYPE["SCT_CONDITION_TABLE"],				"LIZARDMAN_SHAMAN_KING_EXPERT_STAND_UP_ATTACK_FRONT",	"CT_LIZARDMAN_SHAMAN_KING_EXPERT_STAND_UP_ATTACK_FRONT", },
		{ STATE_CHANGE_TYPE["SCT_MOTION_END"],					"LIZARDMAN_SHAMAN_KING_EXPERT_STAND_UP_FRONT",			},
	},
	
	CT_LIZARDMAN_SHAMAN_KING_EXPERT_STAND_UP_ATTACK_FRONT = 
	{
		ANIM_PLAY_COUNT		= 1,
		RATE				= 20,
	},
}

LIZARDMAN_SHAMAN_KING_EXPERT_DAMAGE_DOWN_BACK = 
{
	ANIM_NAME					= "DamageDownBack",
	PLAY_TYPE					= XSKIN_ANIM_PLAYTYPE["XAP_ONE_WAIT"],
	TRANSITION					= FALSE,
	LAND_CONNECT				= FALSE,
	
	SUPER_ARMOR					= TRUE,
	DEFENCE						= { 0, 100, 70, },

    SOUND_PLAY0			= { 0.05, "LizardShaman_Scream1.ogg" },	
	
	CAN_PUSH_UNIT				= TRUE,
	CAN_PASS_UNIT				= FALSE,
	
	TALK_BOX = 
	{
		{ RATE = 10, MESSAGE = STR_ID_2568 },
		{ RATE = 10, MESSAGE = STR_ID_2569 },
	},
	
	EVENT_PROCESS = 
	{
		{ STATE_CHANGE_TYPE["SCT_FOOT_ON_LINE_FALSE_DOWN"],		"LIZARDMAN_SHAMAN_KING_EXPERT_DAMAGE_AIR_FALL",			},
		{ STATE_CHANGE_TYPE["SCT_CONDITION_TABLE"],				"LIZARDMAN_SHAMAN_KING_EXPERT_STAND_UP_ATTACK_BACK",	"CT_LIZARDMAN_SHAMAN_KING_EXPERT_STAND_UP_ATTACK_BACK", },
		{ STATE_CHANGE_TYPE["SCT_MOTION_END"],					"LIZARDMAN_SHAMAN_KING_EXPERT_STAND_UP_BACK",			},
	},
	
	CT_LIZARDMAN_SHAMAN_KING_EXPERT_STAND_UP_ATTACK_BACK = 
	{
		ANIM_PLAY_COUNT		= 1,
		RATE				= 20,
	},
}

LIZARDMAN_SHAMAN_KING_EXPERT_DAMAGE_FLY_FRONT = 
{
	ANIM_NAME					= "DamageAirFlyFront",
	PLAY_TYPE					= XSKIN_ANIM_PLAYTYPE["XAP_ONE_WAIT"],
	TRANSITION					= FALSE,
	LAND_CONNECT				= FALSE,	
	
	
	CAN_PUSH_UNIT				= TRUE,
	CAN_PASS_UNIT				= FALSE,
	
	EVENT_PROCESS = 
	{
		{ STATE_CHANGE_TYPE["SCT_FOOT_ON_LINE_TRUE"],			"LIZARDMAN_SHAMAN_KING_EXPERT_DAMAGE_DOWN_FRONT",		},
	},
}

LIZARDMAN_SHAMAN_KING_EXPERT_DAMAGE_FLY_BACK = 
{
	ANIM_NAME					= "DamageAirFlyBack",
	PLAY_TYPE					= XSKIN_ANIM_PLAYTYPE["XAP_ONE_WAIT"],
	TRANSITION					= FALSE,
	LAND_CONNECT				= FALSE,	
	
	CAN_PUSH_UNIT				= TRUE,
	CAN_PASS_UNIT				= FALSE,
	
	EVENT_PROCESS = 
	{
		{ STATE_CHANGE_TYPE["SCT_FOOT_ON_LINE_TRUE"],			"LIZARDMAN_SHAMAN_KING_EXPERT_DAMAGE_DOWN_BACK",		},
	},
}

LIZARDMAN_SHAMAN_KING_EXPERT_DAMAGE_AIR = 
{
	ANIM_NAME					= "DamageAirSmall",
	PLAY_TYPE					= XSKIN_ANIM_PLAYTYPE["XAP_ONE_WAIT"],
	TRANSITION					= FALSE,
	LAND_CONNECT				= FALSE,
	
	CAN_PUSH_UNIT				= TRUE,
	CAN_PASS_UNIT				= FALSE,
	
	EVENT_PROCESS = 
	{
		{ STATE_CHANGE_TYPE["SCT_FOOT_ON_LINE_TRUE"],			"LIZARDMAN_SHAMAN_KING_EXPERT_WAIT",					},
	},
}

LIZARDMAN_SHAMAN_KING_EXPERT_DAMAGE_AIR_DOWN = 
{
	ANIM_NAME					= "DamageAirDown",
	PLAY_TYPE					= XSKIN_ANIM_PLAYTYPE["XAP_ONE_WAIT"],
	TRANSITION					= FALSE,
	LAND_CONNECT				= FALSE,
	
	CAN_PUSH_UNIT				= TRUE,
	CAN_PASS_UNIT				= FALSE,
	
	EVENT_PROCESS = 
	{
		{ STATE_CHANGE_TYPE["SCT_FOOT_ON_LINE_TRUE"],			"LIZARDMAN_SHAMAN_KING_EXPERT_DAMAGE_AIR_DOWN_LANDING",	},
	},
}

LIZARDMAN_SHAMAN_KING_EXPERT_DAMAGE_AIR_UP = 
{
	ANIM_NAME					= "DamageAirUp",
	PLAY_TYPE					= XSKIN_ANIM_PLAYTYPE["XAP_ONE_WAIT"],
	TRANSITION					= FALSE,
	LAND_CONNECT				= FALSE,
	
	CAN_PUSH_UNIT				= TRUE,
	CAN_PASS_UNIT				= FALSE,
	
		
	EVENT_PROCESS = 
	{
		{ STATE_CHANGE_TYPE["SCT_NEGATIVE_Y_SPEED"],		"LIZARDMAN_SHAMAN_KING_EXPERT_DAMAGE_AIR_FALL",			},
		{ STATE_CHANGE_TYPE["SCT_FOOT_ON_LINE_TRUE"],		"LIZARDMAN_SHAMAN_KING_EXPERT_DAMAGE_AIR_DOWN_LANDING",	},
	},
	
	TALK_BOX =
	{
		{ RATE = 10, MESSAGE = STR_ID_2568 },
		{ RATE = 10, MESSAGE = STR_ID_2569 },
	},
}

LIZARDMAN_SHAMAN_KING_EXPERT_DAMAGE_AIR_FALL = 
{
	ANIM_NAME					= "DamageAirFall",
	PLAY_TYPE					= XSKIN_ANIM_PLAYTYPE["XAP_ONE_WAIT"],
	TRANSITION					= FALSE,
	LAND_CONNECT				= FALSE,
	
	CAN_PUSH_UNIT				= TRUE,
	CAN_PASS_UNIT				= FALSE,
	
	EVENT_PROCESS = 
	{
		{ STATE_CHANGE_TYPE["SCT_POSITIVE_Y_SPEED"],		"LIZARDMAN_SHAMAN_KING_EXPERT_DAMAGE_AIR_UP",			},
		{ STATE_CHANGE_TYPE["SCT_FOOT_ON_LINE_TRUE"],		"LIZARDMAN_SHAMAN_KING_EXPERT_DAMAGE_AIR_DOWN_LANDING",	},
	},
}

LIZARDMAN_SHAMAN_KING_EXPERT_DAMAGE_AIR_DOWN_LANDING = 
{
	ANIM_NAME					= "DamageAirDownLanding",
	PLAY_TYPE					= XSKIN_ANIM_PLAYTYPE["XAP_ONE_WAIT"],
	TRANSITION					= FALSE,
	LAND_CONNECT				= FALSE,
	
	SUPER_ARMOR					= TRUE,
	DEFENCE						= { 0, 100, 70, },
	
	CAN_PUSH_UNIT				= TRUE,
	CAN_PASS_UNIT				= FALSE,
	
	EVENT_PROCESS = 
	{
		{ STATE_CHANGE_TYPE["SCT_FOOT_ON_LINE_FALSE_DOWN"],	"LIZARDMAN_SHAMAN_KING_EXPERT_DAMAGE_AIR_FALL",			},
		{ STATE_CHANGE_TYPE["SCT_CONDITION_TABLE"],			"LIZARDMAN_SHAMAN_KING_EXPERT_STAND_UP_ATTACK_FRONT",	"CT_LIZARDMAN_SHAMAN_KING_EXPERT_STAND_UP_ATTACK_FRONT", },
		{ STATE_CHANGE_TYPE["SCT_MOTION_END"],				"LIZARDMAN_SHAMAN_KING_EXPERT_STAND_UP_FRONT",			},
	},
	
	CT_LIZARDMAN_SHAMAN_KING_EXPERT_STAND_UP_ATTACK_FRONT = 
	{
		ANIM_PLAY_COUNT		= 1,
		RATE				= 20,
	},
}

LIZARDMAN_SHAMAN_KING_EXPERT_STAND_UP_FRONT = 
{
	ANIM_NAME					= "DamageStandUpFront",
		
	PLAY_TYPE					= XSKIN_ANIM_PLAYTYPE["XAP_ONE_WAIT"],
	TRANSITION					= FALSE,
	LAND_CONNECT				= FALSE,	
	
	SUPER_ARMOR					= TRUE,
	DEFENCE						= { 0, 100, 70, },
	
	CAN_PUSH_UNIT				= TRUE,
	CAN_PASS_UNIT				= FALSE,
	
	EVENT_PROCESS = 
	{
		{ STATE_CHANGE_TYPE["SCT_FOOT_ON_LINE_FALSE_DOWN"],	"LIZARDMAN_SHAMAN_KING_EXPERT_JUMP_DOWN",			},
		{ STATE_CHANGE_TYPE["SCT_MOTION_END"],				"LIZARDMAN_SHAMAN_KING_EXPERT_WAIT",				},
	},
}

LIZARDMAN_SHAMAN_KING_EXPERT_STAND_UP_BACK = 
{
	ANIM_NAME					= "DamageStandUpBack",		
	
	PLAY_TYPE					= XSKIN_ANIM_PLAYTYPE["XAP_ONE_WAIT"],
	TRANSITION					= FALSE,
	LAND_CONNECT				= FALSE,
	
	SUPER_ARMOR					= TRUE,
	DEFENCE						= { 0, 100, 70, },
		
	CAN_PUSH_UNIT				= TRUE,
	CAN_PASS_UNIT				= FALSE,
		
	EVENT_PROCESS = 
	{
		{ STATE_CHANGE_TYPE["SCT_FOOT_ON_LINE_FALSE_DOWN"],	"LIZARDMAN_SHAMAN_KING_EXPERT_JUMP_DOWN", },
		{ STATE_CHANGE_TYPE["SCT_MOTION_END"],				"LIZARDMAN_SHAMAN_KING_EXPERT_WAIT", },
	},		
}

LIZARDMAN_SHAMAN_KING_EXPERT_STAND_UP_ATTACK_FRONT = 
{
	ANIM_NAME					= "StandAttackFront",
	PLAY_TYPE					= XSKIN_ANIM_PLAYTYPE["XAP_ONE_WAIT"],
	TRANSITION					= FALSE,
	LAND_CONNECT				= FALSE,	
	ANIM_WAIT_TIME				= 1,
	MIND_FLAG					= MIND_FLAG["MF_STAND_UP_ATTACK"],
	
	SUPER_ARMOR					= TRUE,
	DEFENCE						= { 0, 100, 70, },

    SOUND_PLAY0			= { 0.234, "LizardMan_Shaman_Slash.ogg" },

	CAN_PUSH_UNIT				= TRUE,
	CAN_PASS_UNIT				= FALSE,
	

	EVENT_PROCESS = 
	{
		{ STATE_CHANGE_TYPE["SCT_FOOT_ON_LINE_FALSE_DOWN"],	"LIZARDMAN_SHAMAN_KING_EXPERT_JUMP_DOWN",			},
		{ STATE_CHANGE_TYPE["SCT_MOTION_END"],				"LIZARDMAN_SHAMAN_KING_EXPERT_WAIT",				},
	},
		
	
	ATTACK_TIME0				= { 0.21, 0.28, },	
	
	DAMAGE_DATA = 
	{
		DAMAGE_TYPE		= DAMAGE_TYPE["DT_PHYSIC"],
		HIT_TYPE		= HIT_TYPE["HT_SWORD_SLASH"],
		REACT_TYPE		= REACT_TYPE["RT_DOWN"],
		
		DAMAGE = 
		{
			PHYSIC		= 1.5,
			FIRE		= 0.0,
			ICE			= 0.0,
			EARTH		= 0.0,
			LIGHTNING	= 0.0,
			DARK		= 0.0,
			LIGHT		= 0.0,
			UNIVERSAL	= 0.0,
		},
		
		BACK_SPEED_X			= INIT_PHYSIC["RUN_SPEED"],
		BACK_SPEED_Y			= 0.0,
		
		STOP_TIME_ATT			= 0.0,		
		STOP_TIME_DEF			= 0.0,	
		CAMERA_CRASH_GAP		= 5.0,	
		CAMERA_CRASH_TIME		= 0.2,
		CLEAR_SCREEN			= 0.0,	
		CLEAR_SCREEN_COLOR_A	= 0.0,
		CLEAR_SCREEN_COLOR_R	= 1.0,
		CLEAR_SCREEN_COLOR_G	= 1.0,
		CLEAR_SCREEN_COLOR_B	= 1.0,

		RE_ATTACK				= FALSE,		
		HIT_GAP					= 0.0,				
	},
	
	TALK_BOX =
	{
		{ RATE = 10, MESSAGE = STR_ID_2568 },
	},
	
}

LIZARDMAN_SHAMAN_KING_EXPERT_STAND_UP_ATTACK_BACK = 
{
	ANIM_NAME					= "StandAttackBack",
	PLAY_TYPE					= XSKIN_ANIM_PLAYTYPE["XAP_ONE_WAIT"],
	TRANSITION					= FALSE,
	LAND_CONNECT				= FALSE,
	ANIM_WAIT_TIME				= 1,
	MIND_FLAG					= MIND_FLAG["MF_STAND_UP_ATTACK"],
	
	SUPER_ARMOR					= TRUE,
	DEFENCE						= { 0, 100, 70, },

    SOUND_PLAY0			= { 0.410, "LizardMan_Shaman_Slash.ogg" },

	CAN_PUSH_UNIT				= TRUE,
	CAN_PASS_UNIT				= FALSE,

	
	FLIP_DIR_END				= TRUE,
	
	EVENT_PROCESS = 
	{
		{ STATE_CHANGE_TYPE["SCT_FOOT_ON_LINE_FALSE_DOWN"],	"LIZARDMAN_SHAMAN_KING_EXPERT_JUMP_DOWN", },
		{ STATE_CHANGE_TYPE["SCT_MOTION_END"],				"LIZARDMAN_SHAMAN_KING_EXPERT_WAIT", },
	},	
	
		
	ATTACK_TIME0				= { 0.41, 0.51, },	
	
	DAMAGE_DATA = 
	{
		DAMAGE_TYPE		= DAMAGE_TYPE["DT_PHYSIC"],
		HIT_TYPE		= HIT_TYPE["HT_SWORD_SLASH"],
		REACT_TYPE		= REACT_TYPE["RT_DOWN"],
		
		DAMAGE = 
		{
			PHYSIC		= 1.5,
			FIRE		= 0.0,
			ICE			= 0.0,
			EARTH		= 0.0,
			LIGHTNING	= 0.0,
			DARK		= 0.0,
			LIGHT		= 0.0,
			UNIVERSAL	= 0.0,
		},
		
		BACK_SPEED_X			= INIT_PHYSIC["RUN_SPEED"],
		BACK_SPEED_Y			= 0.0,
		
		STOP_TIME_ATT			= 0.0,		
		STOP_TIME_DEF			= 0.0,	
		CAMERA_CRASH_GAP		= 5.0,	
		CAMERA_CRASH_TIME		= 0.2,
		CLEAR_SCREEN			= 0.0,	
		CLEAR_SCREEN_COLOR_A	= 0.0,
		CLEAR_SCREEN_COLOR_R	= 1.0,
		CLEAR_SCREEN_COLOR_G	= 1.0,
		CLEAR_SCREEN_COLOR_B	= 1.0,

		RE_ATTACK				= FALSE,		
		HIT_GAP					= 0.0,				
	},
	TALK_BOX =
	{
		{ RATE = 10, MESSAGE = STR_ID_1477 },

	},
}


LIZARDMAN_SHAMAN_KING_EXPERT_DYING_LAND_FRONT = 
{
	ANIM_NAME					= "DamageDownFront",
	PLAY_TYPE					= XSKIN_ANIM_PLAYTYPE["XAP_ONE_WAIT"],
	TRANSITION					= FALSE,
	LAND_CONNECT				= FALSE,

	INVINCIBLE					= { 0, 100, }, 		
	
	CAN_PUSH_UNIT				= FALSE,
	CAN_PASS_UNIT				= TRUE,
	
	DYING_END					= TRUE,
	
	IMMADIATE_PACKET_SEND		= TRUE,
}
	
LIZARDMAN_SHAMAN_KING_EXPERT_DYING_LAND_BACK = 
{
	ANIM_NAME					= "DamageDownBack",
	PLAY_TYPE					= XSKIN_ANIM_PLAYTYPE["XAP_ONE_WAIT"],
	TRANSITION					= FALSE,
	LAND_CONNECT				= FALSE,
	
	INVINCIBLE					= { 0, 100, }, 		
	
	CAN_PUSH_UNIT				= FALSE,
	CAN_PASS_UNIT				= TRUE,
	
	DYING_END					= TRUE,	
	
	IMMADIATE_PACKET_SEND		= TRUE,
}

LIZARDMAN_SHAMAN_KING_EXPERT_DYING_SKY = 
{
	ANIM_NAME					= "DamageAirDownLanding",
	PLAY_TYPE					= XSKIN_ANIM_PLAYTYPE["XAP_ONE_WAIT"],
	TRANSITION					= FALSE,
	LAND_CONNECT				= FALSE,
	
	INVINCIBLE					= { 0, 100, }, 		
	
	CAN_PUSH_UNIT				= FALSE,
	CAN_PASS_UNIT				= TRUE,
	
	DYING_END					= TRUE,
	
	IMMADIATE_PACKET_SEND		= TRUE,
}




--------------------------------------------------------------------
function CF_LIZARDMAN_SHAMAN_KING_EXPERT_WIN( pKTDXApp, pX2Game, pNPCUnit )

	if pX2Game:LiveUserUnitNum() == 0 then
		return true
	else
		return false
	end

end



function CF_LIZARDMAN_SHAMAN_KING_EXPERT_SUMMON( pKTDXApp, pX2Game, pNPCUnit )
		
	if pNPCUnit:GetNowHP() <= 0 or pNPCUnit:GetMaxHP() <= 0 then
		return false
	end
			
	fHPRate = 100.0 * pNPCUnit:GetNowHP_LUA() / pNPCUnit:GetMaxHP()
	if fHPRate < 40.0 then 
	
		npcNum = pX2Game:LiveNPCNumType_LUA( NPC_UNIT_ID["NUI_LIZARDMAN_HIGH_DARK"] )
		if npcNum == 0 then 
			return true
		end
	end
	
	return false

end





--------------------------------------------------------------------

function LIZARDMAN_SHAMAN_KING_EXPERT_START_CAMERA_MOVE( pKTDXApp, pX2Game, pNPCUnit )

	pos = pNPCUnit:GetBonePos_LUA("Bip01_Head")	
	camera = pX2Game:GetX2Camera()
	camera:PartsLookDirectCamera_LUA( pNPCUnit, pos, D3DXVECTOR3( 500, -50, -20 ), D3DXVECTOR2( 0,0 ) )

end


--------------------------------------------------------------------
function LIZARDMAN_SHAMAN_KING_EXPERT_WAIT_FRAME_MOVE( pKTDXApp, pX2Game, pNPCUnit )

	if pNPCUnit:GetDamagedThisFrame() then 
		fRemainHPRate = pNPCUnit:GetNowHP() / pNPCUnit:GetMaxHP()
		if fRemainHPRate < 0.7 then	
			pNPCUnit:CallOtherNPC( NPC_UNIT_ID["NUI_LIZARDMAN_HIGH_DARK"] )
			
		end
	end
	
end


--------------------------------------------------------------------
function LIZARDMAN_SHAMAN_KING_EXPERT_WALK_FRAME_MOVE( pKTDXApp, pX2Game, pNPCUnit )

	if pNPCUnit:GetDamagedThisFrame() then 
		fRemainHPRate = pNPCUnit:GetNowHP() / pNPCUnit:GetMaxHP()
		if fRemainHPRate < 0.7 then	
			pNPCUnit:CallOtherNPC( NPC_UNIT_ID["NUI_LIZARDMAN_HIGH_DARK"] )
			
		end
	end
	
end



--------------------------------------------------------------------
function LIZARDMAN_SHAMAN_KING_EXPERT_WALK_STATE_END( pKTDXApp, pX2Game, pNPCUnit )

	pMinorParticle = pX2Game:GetMinorParticle()
	pMinorParticle:GameUnitCreateSequence_LUA( pNPCUnit, "StepSmoke", pNPCUnit:GetLandPosition_LUA(), D3DXVECTOR2(100,100), D3DXVECTOR2(5,-1) )

end



function LIZARDMAN_SHAMAN_KING_EXPERT_JUMP_DOWN_STATE_END( pKTDXApp, pX2Game, pNPCUnit )

	pMinorParticle = pX2Game:GetMinorParticle()
	pMinorParticle:GameUnitCreateSequence_LUA( pNPCUnit, "StepSmoke", pNPCUnit:GetLandPosition_LUA(), D3DXVECTOR2(100,100), D3DXVECTOR2(5,-1) )

end

function LIZARDMAN_SHAMAN_KING_EXPERT_JUMP_DOWN_DIR_STATE_END( pKTDXApp, pX2Game, pNPCUnit )

	pMinorParticle = pX2Game:GetMinorParticle()
	pMinorParticle:GameUnitCreateSequence_LUA( pNPCUnit, "StepSmoke", pNPCUnit:GetLandPosition_LUA(), D3DXVECTOR2(100,100), D3DXVECTOR2(5,-1) )

end




------------------------------------------------------------------------------------------------------------
function LIZARDMAN_SHAMAN_KING_EXPERT_DRAIN_HIT_STATE_START( pKTDXApp, pX2Game, pNPCUnit )

	vPos = pNPCUnit:GetWeaponBonePos_LUA( 0, "ATTACK_LINE_START0" )
	rotDegree = pNPCUnit:GetRotateDegree()	

	pMinorParticle = pX2Game:GetMinorParticle()
	
	Particle1 = pMinorParticle:GameUnitCreateSequence_LUA( pNPCUnit, "LizardMan_Shaman_Charge02", vPos, D3DXVECTOR2(-1,-1), D3DXVECTOR2(-1,-1) )
	if Particle1 ~= nil then 
		Particle1:SetAddRotate( rotDegree )
		Particle1:SetAxisAngle( rotDegree )

		pNPCUnit:SetMinorParticle_LUA( 0, Particle1:GetHandle() ) 
	end 
	
	
end


------------------------------------------------------------------------------------------------------------
function LIZARDMAN_SHAMAN_KING_EXPERT_DRAIN_HIT_FRAME_MOVE( pKTDXApp, pX2Game, pNPCUnit )

	if pNPCUnit:AnimEventTimer_LUA( 1.4 ) then

		iFireCount = 1
	
		fRemainHPRate = pNPCUnit:GetNowHP() / pNPCUnit:GetMaxHP()
		if fRemainHPRate < 0.2 then	
			iFireCount = 3
		end
		

		pDamageEffect = pX2Game:GetDamageEffect()
		
		landPos = pNPCUnit:GetLandPosition_LUA()
		LHandPos = pNPCUnit:GetBonePos_LUA( "Bip01_L_Hand" )
		
		for i=1, iFireCount do
		
			pCEffect = pDamageEffect:CreateInstance_LUA( pNPCUnit, "LIZARDMAN_DRAIN_HIT", LHandPos, landPos.y )
			
			if pCEffect ~= nil then
			
				pNPCUnit:SetLockOnTarget( pCEffect )
			
			end
		
		end
	
	end
		
		
	if pNPCUnit:AnimEventTimer_LUA( 1.2 ) then
	
		vPos = pNPCUnit:GetWeaponBonePos_LUA( 0, "ATTACK_LINE_START0" )
		vPos.y = vPos.y - 40.0
		
		rotDegree = pNPCUnit:GetRotateDegree()	
		pMinorParticle = pX2Game:GetMinorParticle()
		
		Particle1 = pMinorParticle:GameUnitCreateSequence_LUA( pNPCUnit, "LizardMan_Shamanking_DrainHit01", vPos, D3DXVECTOR2(-1,-1), D3DXVECTOR2(-1,-1) )
		if Particle1 ~= nil then 
			
			Particle1:SetAddRotate( rotDegree )
			Particle1:SetAxisAngle( rotDegree )
		end 
		
	end
	
	
	
	pMinorParticle = pX2Game:GetMinorParticle()	
	Particle1 = pNPCUnit:GetMinorParticle_LUA( 0 ) 	
	
	if Particle1 ~= nil and pMinorParticle:IsLiveInstance( Particle1 ) == true then 
		
		vPos = pNPCUnit:GetWeaponBonePos_LUA( 0, "ATTACK_LINE_START0" )
		rotDegree = pNPCUnit:GetRotateDegree()
		
		Particle1:SetPosition( vPos )
		Particle1:SetAddRotate( rotDegree )
		Particle1:SetAxisAngle( rotDegree )
		
	end
	
end
	
	
------------------------------------------------------------------------------------------------------------
function LIZARDMAN_SHAMAN_KING_EXPERT_DRAIN_HIT_STATE_END( pKTDXApp, pX2Game, pNPCUnit )

	Particle1 = pNPCUnit:GetMinorParticle_LUA( 0 ) 
	pMinorParticle = pX2Game:GetMinorParticle()
	
	if Particle1 ~= nil then
		
		pMinorParticle:DestroyInstance( Particle1 )
		pNPCUnit:ClearMinorParticle_LUA( 0 )
		
	end
	
end




------------------------------------------------------------------------------------------------------------
function LIZARDMAN_SHAMAN_KING_EXPERT_COMBO_FRAME_MOVE( pKTDXApp, pX2Game, pNPCUnit )

	if pNPCUnit:AnimEventTimer_LUA( 0.96 ) then
	
		pDamageEffect = pX2Game:GetDamageEffect()
		pos = pNPCUnit:GetLandPosition_LUA()		
		pCEffect = pDamageEffect:CreateInstance_LUA( pNPCUnit, "MONSTER_FIREBALL", pNPCUnit:GetBonePos_LUA( "Bip01_L_Hand" ), pos.y )
		
	end


	if pNPCUnit:AnimEventTimer_LUA( 1.65 ) then
	
		pDamageEffect = pX2Game:GetDamageEffect()
		pos = pNPCUnit:GetLandPosition_LUA()		
		pCEffect = pDamageEffect:CreateInstance_LUA( pNPCUnit, "MONSTER_FIREBALL", pNPCUnit:GetBonePos_LUA( "Bip01_L_Hand" ), pos.y )
		
	end



	if pNPCUnit:AnimEventTimer_LUA( 2.4 ) then
	
		pDamageEffect = pX2Game:GetDamageEffect()
		pos = pNPCUnit:GetLandPosition_LUA()		
		pCEffect = pDamageEffect:CreateInstance_LUA( pNPCUnit, "GHOST_MAGICIAN_RED_BIGFIREBALL", pNPCUnit:GetBonePos_LUA( "Bip01_L_Hand" ), pos.y )
		
	end
	
end








------------------------------------------------------------------------------------------------------------
function LIZARDMAN_SHAMAN_KING_EXPERT_SP_HYPER_FRAME_FRAME_MOVE( pKTDXApp, pX2Game, pNPCUnit )


	pParticle1 = pNPCUnit:GetMinorParticle_LUA( 0 ) 
	if nil ~= pParticle1 then 

		pMinorParticle = pX2Game:GetMinorParticle()
		
		if pMinorParticle:IsLiveInstance( pParticle1 ) == true then 
		
			LHandPos = pNPCUnit:GetBonePos_LUA( "Dummy2_Lhand" )
			LHandPos.y = LHandPos.y + 50.0
			
			pParticle1:SetPosition( LHandPos )		
		
		else 
		
			pNPCUnit:ClearMinorParticle_LUA( 0 )
			
		end
	
	end


	if pNPCUnit:AnimEventTimer_LUA( 0.76 ) then

		LHandPos = pNPCUnit:GetBonePos_LUA( "Dummy2_Lhand" )
		LHandPos.y = LHandPos.y + 50.0
		pMinorParticle = pX2Game:GetMinorParticle()
		pParticle1 = pMinorParticle:GameUnitCreateSequence_LUA( pNPCUnit, "LizardMan_ShamanKing_SP_HyperFrame01", LHandPos, D3DXVECTOR2(-1,-1), D3DXVECTOR2(-1,-1) )
		if pParticle1 ~= nil then 
		
		
			pNPCUnit:SetMinorParticle_LUA( 0, pParticle1:GetHandle() ) 
		end 
	end
	


		
	for i=0, 3 do
	
		fTime = 0.9 + i * 0.25 
		
		if pNPCUnit:AnimEventTimer_LUA( fTime ) then
		
			vDirVector = pNPCUnit:GetDirVector()
			
			posL = pNPCUnit:GetPos()
			posR = pNPCUnit:GetPos()
					

			posL.x = posL.x + vDirVector.x * 270.0 * (i+1)
			posL.y = posL.y + vDirVector.y * 270.0 * (i+1)
			posL.z = posL.z + vDirVector.z * 270.0 * (i+1)
		
			posR.x = posR.x - vDirVector.x * 270.0 * (i+1)
			posR.y = posR.y - vDirVector.y * 270.0 * (i+1)
			posR.z = posR.z - vDirVector.z * 270.0 * (i+1)
			
			landPos = pNPCUnit:GetLandPosition_LUA()
		
			pMinorParticle = pX2Game:GetMinorParticle()
			pMinorParticle:GameUnitCreateSequence_LUA( pNPCUnit, "LizardMan_ShamanKing_SP_HyperFrame01_Warning", posL, D3DXVECTOR2(-1,-1), D3DXVECTOR2(-1,-1) )
			pMinorParticle:GameUnitCreateSequence_LUA( pNPCUnit, "LizardMan_ShamanKing_SP_HyperFrame01_Warning", posR, D3DXVECTOR2(-1,-1), D3DXVECTOR2(-1,-1) )
			
		end	
	
	end
	



		
	for i=0, 3 do
	
		fTime = 1.8 + i * 0.25 
		
		if pNPCUnit:AnimEventTimer_LUA( fTime ) then
		
			vDirVector = pNPCUnit:GetDirVector()
			
			posL = pNPCUnit:GetPos()
			posR = pNPCUnit:GetPos()
					

			posL.x = posL.x + vDirVector.x * 270.0 * (i+1)
			posL.y = posL.y + vDirVector.y * 270.0 * (i+1)
			posL.z = posL.z + vDirVector.z * 270.0 * (i+1)
		
			posR.x = posR.x - vDirVector.x * 270.0 * (i+1)
			posR.y = posR.y - vDirVector.y * 270.0 * (i+1)
			posR.z = posR.z - vDirVector.z * 270.0 * (i+1)
			
			landPos = pNPCUnit:GetLandPosition_LUA()
			
			pDamageEffect = pX2Game:GetDamageEffect()
			pDamageEffect:CreateInstance_LUA( pNPCUnit, "TRIPLE_GEYSER_SHAMAN_KING", posL, landPos.y )
			pDamageEffect:CreateInstance_LUA( pNPCUnit, "TRIPLE_GEYSER_SHAMAN_KING", posR, landPos.y )
			
			pNPCUnit:PlaySound_LUA( "fire.ogg" )
			
			
			pNPCUnit:SetNowMP(0)
			
		end	
	
	end
	
	
end



------------------------------------------------------------------------------------------------------------
function LIZARDMAN_SHAMAN_KING_EXPERT_SP_HYPER_FRAME_STATE_END( pKTDXApp, pX2Game, pNPCUnit )

	pParticle1 = pNPCUnit:GetMinorParticle_LUA( 0 ) 	
	pMinorParticle = pX2Game:GetMinorParticle()
	
	if pParticle1 ~= nil then
		
		pMinorParticle:DestroyInstance( pParticle1 )
		pNPCUnit:ClearMinorParticle_LUA( 0 )
		
	end
end





------------------------------------------------------------------------------------------------------------
function LIZARDMAN_SHAMAN_KING_EXPERT_SP_FIREWALL_STATE_START( pKTDXApp, pX2Game, pNPCUnit )

	vPos = pNPCUnit:GetWeaponBonePos_LUA( 0, "ATTACK_LINE_START0" )
		
	pMajorParticle = pX2Game:GetMajorParticle()
	pParticle1 = pMajorParticle:GameUnitCreateSequence_LUA( pNPCUnit, "LizardMan_ShamanKing_FireWall01", vPos, D3DXVECTOR2(-1,-1), D3DXVECTOR2(-1,-1) )
	if pParticle1 ~= nil then 

		rotDegree = pNPCUnit:GetRotateDegree()
		
		pParticle1:SetAddRotate( rotDegree )
		pParticle1:SetAxisAngle( rotDegree )
			
		pNPCUnit:SetMajorParticle_LUA( 0, pParticle1:GetHandle() ) 
	end 
	
	
end


	
------------------------------------------------------------------------------------------------------------
function LIZARDMAN_SHAMAN_KING_EXPERT_SP_FIREWALL_FRAME_MOVE( pKTDXApp, pX2Game, pNPCUnit )

	pParticle1 = pNPCUnit:GetMajorParticle_LUA( 0 ) 	
	pMajorParticle = pX2Game:GetMajorParticle()

    if pMajorParticle ~= nil then		
	    if pParticle1 ~= nil and pMajorParticle:IsLiveInstance( pParticle1 ) == true then 
    	
		    vPos = pNPCUnit:GetWeaponBonePos_LUA( 0, "ATTACK_LINE_START0" )
		    --vPos.z = vPos.z - 20.0
    		
		    rotDegree = pNPCUnit:GetRotateDegree()
    		
		    pParticle1:SetPosition( vPos )		
		    pParticle1:SetAddRotate( rotDegree )
		    pParticle1:SetAxisAngle( rotDegree )
    		
	    end
    end	    
	
	
	
	
	if pNPCUnit:AnimEventTimer_LUA( 0.83333 ) then
	
		vDirVector = pNPCUnit:GetDirVector()
	
		bIsRight = pNPCUnit:GetIsRight()
		vPos = pNPCUnit:GetPos()
		if bIsRight == true then 
			vPos.x = vPos.x + 90.0		* vDirVector.x
			vPos.z = vPos.z - 150.0		* vDirVector.z
		else
			vPos.x = vPos.x - 90.0		* vDirVector.x
			vPos.z = vPos.z - 150.0		* vDirVector.z
		end
		
		pMinorParticle = pX2Game:GetMinorParticle()
		if pMinorParticle ~= nil then
		    pMinorParticle:GameUnitCreateSequence_LUA( pNPCUnit, "Stone_LizardMan_High_WaitStart", vPos, D3DXVECTOR2(-1,-1), D3DXVECTOR2(-1,-1)) 
		end
		
				
				
		vDirVector = pNPCUnit:GetDirVector()
		
		posL = pNPCUnit:GetPos()
		posR = pNPCUnit:GetPos()

		posL.x = posL.x + vDirVector.x * 250.0
		posL.y = posL.y + vDirVector.y * 250.0
		posL.z = posL.z + vDirVector.z * 250.0
		
		posR.x = posR.x - vDirVector.x * 250.0
		posR.y = posR.y - vDirVector.y * 250.0
		posR.z = posR.z - vDirVector.z * 250.0
		
		
		landPos = pNPCUnit:GetLandPosition_LUA()
			
		pDamageEffect = pX2Game:GetDamageEffect()
		if pDamageEffect ~= nil then
		    pLeftFire  = pDamageEffect:CreateInstance_LUA( pNPCUnit, "LIZARDMAN_FIREWALL2", posL, landPos.y )
		    pRightFire = pDamageEffect:CreateInstance_LUA( pNPCUnit, "LIZARDMAN_FIREWALL2", posR, landPos.y )
		end
		
		LeftTargetPos	= pNPCUnit:GetPos()
		RightTargetPos	= pNPCUnit:GetPos()

		LeftTargetPos.x 	= LeftTargetPos.x + vDirVector.x * 500.0
		--LeftTargetPos.y 	= LeftTargetPos.y + vDirVector.y * 500.0
		LeftTargetPos.z 	= LeftTargetPos.z + vDirVector.z * 500.0
		
		RightTargetPos.x 	= RightTargetPos.x - vDirVector.x * 500.0
		--RightTargetPos.y 	= RightTargetPos.y - vDirVector.y * 500.0
		RightTargetPos.z 	= RightTargetPos.z - vDirVector.z * 500.0
		
		pNPCUnit:SetLockOnPos( pLeftFire, LeftTargetPos )
		pNPCUnit:SetLockOnPos( pRightFire, RightTargetPos )
		
		
		pNPCUnit:SetNowMP(0)
	
	end
	
end


------------------------------------------------------------------------------------------------------------
function LIZARDMAN_SHAMAN_KING_EXPERT_SP_FIREWALL_STATE_END( pKTDXApp, pX2Game, pNPCUnit )

	pParticle1 = pNPCUnit:GetMajorParticle_LUA( 0 ) 	
	pMajorParticle = pX2Game:GetMajorParticle()
	
	if pParticle1 ~= nil then
		
		pMajorParticle:DestroyInstance( pParticle1 )
		pNPCUnit:ClearMajorParticle_LUA( 0 )
		
	end
	
end







function LIZARDMAN_SHAMAN_KING_EXPERT_SUMMON_FRAME_MOVE( pKTDXApp, pX2Game, pNPCUnit )

	--pX2Game:SetWorldColor_LUA( D3DXCOLOR(0.2,0.2,0.2,1) )
	

	if pNPCUnit:AnimEventTimer_LUA( 0.55 ) then
	
		vPos = pNPCUnit:GetLandPosition_LUA()		
		vPos.y = vPos.y + 600.0 
		
		rotDegree = pNPCUnit:GetRotateDegree()	
		pMinorParticle = pX2Game:GetMinorParticle()
		Particle1 = pMinorParticle:GameUnitCreateSequence_LUA( pNPCUnit, "LizardMan_Shaman_Charge02", vPos, D3DXVECTOR2(-1,-1), D3DXVECTOR2(-1,-1) )
		if Particle1 ~= nil then 
			Particle1:SetAddRotate( rotDegree )
			Particle1:SetAxisAngle( rotDegree )
		end 
		
	end
		
	
	if pNPCUnit:AnimEventTimer_LUA( 2.0 ) then	
	
		pMajorParticle = pX2Game:GetMajorParticle()
		
		vPos = pNPCUnit:GetLandPosition_LUA()		
		vPos.y = vPos.y + 600.0 
		
		pParticle = pMajorParticle:GameUnitCreateSequence_LUA( pNPCUnit, "SummonLight",	vPos, D3DXVECTOR2(-1,-1), D3DXVECTOR2(1,-1) )
		if pParticle ~= nil then 
			pParticle:SetLandPosition( pNPCUnit:GetLandPosition_LUA().y )
			pos = pX2Game:GetLineMap():GetRandomPositionDir( pNPCUnit:GetPos(), 500, true, true )
			pParticle:SetBlackHolePosition( pos )
		end 
		pX2Game:PushCreateNPCReq_Lua( NPC_UNIT_ID["NUI_LIZARDMAN_HIGH_DARK"], pNPCUnit:GetHardLevel(), false, pos, true, 1.9, true, 0 )
	
		pX2Game:FlushCreateNPCReq()
	end

end



function LIZARDMAN_SHAMAN_KING_EXPERT_DAMAGE_SMALL_FRAME_MOVE( pKTDXApp, pX2Game, pNPCUnit )

	if pNPCUnit:AnimEventTimer_LUA( 0.047 ) then
		pMinorParticle = pX2Game:GetMinorParticle()
		pMinorParticle:GameUnitCreateSequence_LUA( pNPCUnit, "StepSmoke", pNPCUnit:GetLandPosition_LUA(), D3DXVECTOR2(100,100), D3DXVECTOR2(5,-1) )
	end
	
	if pNPCUnit:GetDamagedThisFrame() then 
		fRemainHPRate = pNPCUnit:GetNowHP() / pNPCUnit:GetMaxHP()
		if fRemainHPRate < 0.7 then	
			pNPCUnit:CallOtherNPC( NPC_UNIT_ID["NUI_LIZARDMAN_HIGH_DARK"] )
			
		end
	end

end

function LIZARDMAN_SHAMAN_KING_EXPERT_DAMAGE_BIG_FRAME_MOVE( pKTDXApp, pX2Game, pNPCUnit )

	if pNPCUnit:AnimEventTimer_LUA( 0.06 ) then
		pMinorParticle = pX2Game:GetMinorParticle()
		pMinorParticle:GameUnitCreateSequence_LUA( pNPCUnit, "StepSmoke", pNPCUnit:GetLandPosition_LUA(), D3DXVECTOR2(100,100), D3DXVECTOR2(5,-1) )
	end
	
	if pNPCUnit:GetDamagedThisFrame() then 
		fRemainHPRate = pNPCUnit:GetNowHP() / pNPCUnit:GetMaxHP()
		if fRemainHPRate < 0.7 then	
			pNPCUnit:CallOtherNPC( NPC_UNIT_ID["NUI_LIZARDMAN_HIGH_DARK"] )
			
		end
	end

end

function LIZARDMAN_SHAMAN_KING_EXPERT_DAMAGE_DOWN_FRONT_FRAME_MOVE( pKTDXApp, pX2Game, pNPCUnit )

	if pNPCUnit:AnimEventTimer_LUA( 0.41 ) then
		pNPCUnit:PlaySound_LUA( "Down.ogg" )		
		pMinorParticle = pX2Game:GetMinorParticle()
		pMinorParticle:GameUnitCreateSequence_LUA( pNPCUnit, "DownSmoke", pNPCUnit:GetLandPosition_LUA(), D3DXVECTOR2(100,100), D3DXVECTOR2(7,-1) )
	end

end

function LIZARDMAN_SHAMAN_KING_EXPERT_DAMAGE_DOWN_BACK_FRAME_MOVE( pKTDXApp, pX2Game, pNPCUnit )

	if pNPCUnit:AnimEventTimer_LUA( 0.45 ) then
		pNPCUnit:PlaySound_LUA( "Down.ogg" )		
		pMinorParticle = pX2Game:GetMinorParticle()
		pMinorParticle:GameUnitCreateSequence_LUA( pNPCUnit, "DownSmoke", pNPCUnit:GetLandPosition_LUA(), D3DXVECTOR2(100,100), D3DXVECTOR2(7,-1) )
	end

end

function LIZARDMAN_SHAMAN_KING_EXPERT_DAMAGE_AIR_DOWN_LANDING_FRAME_MOVE( pKTDXApp, pX2Game, pNPCUnit )

	if pNPCUnit:AnimEventTimer_LUA( 0.01 ) then
		
		pMinorParticle = pX2Game:GetMinorParticle()
		pos = pNPCUnit:GetLandPosition_LUA()
		pMinorParticle:GameUnitCreateSequence_LUA( pNPCUnit, "DownSmoke", pos, D3DXVECTOR2(100,100), D3DXVECTOR2(7,-1) )
		pos.y = pos.y + 5
		pMinorParticle:GameUnitCreateSequence_LUA( pNPCUnit, "GroundShockWave", pos, D3DXVECTOR2(100,100), D3DXVECTOR2(1,-1) )
		pParticle = pMinorParticle:GameUnitCreateSequence_LUA( pNPCUnit, "AirDownTick", pNPCUnit:GetPos(), D3DXVECTOR2(200,200), D3DXVECTOR2(10,-1) )
		if pParticle ~= nil then 
			pParticle:SetLandPosition( pos.y - 5 )
		end
		
		if GetDistance_LUA( pNPCUnit:GetPos(), pX2Game:GetFocusUnitPos_LUA() ) < 500 then
			pX2Game:GetX2Camera():GetCamera():UpDownCrashCameraNoReset( 10.0, 0.1 )
		end		
		
	elseif pNPCUnit:AnimEventTimer_LUA( 0.1 ) then
		pNPCUnit:PlaySound_LUA( "Down.ogg" )		
		pMinorParticle = pX2Game:GetMinorParticle()
		pMinorParticle:GameUnitCreateSequence_LUA( pNPCUnit, "DownSmoke", pNPCUnit:GetLandPosition_LUA(), D3DXVECTOR2(100,100), D3DXVECTOR2(7,-1) )
		
	end

end

function LIZARDMAN_SHAMAN_KING_EXPERT_STAND_UP_ATTACK_FRONT_FRAME_MOVE( pKTDXApp, pX2Game, pNPCUnit )

	if pNPCUnit:AnimEventTimer_LUA( 0.35 ) then
		pMinorParticle = pX2Game:GetMinorParticle()
		pMinorParticle:GameUnitCreateSequence_LUA( pNPCUnit, "StepSmoke", pNPCUnit:GetLandPosition_LUA(), D3DXVECTOR2(100,100), D3DXVECTOR2(5,-1) )
	end

end

function LIZARDMAN_SHAMAN_KING_EXPERT_STAND_UP_ATTACK_BACK_FRAME_MOVE( pKTDXApp, pX2Game, pNPCUnit )

	if pNPCUnit:AnimEventTimer_LUA( 0.35 ) then
		pMinorParticle = pX2Game:GetMinorParticle()
		pMinorParticle:GameUnitCreateSequence_LUA( pNPCUnit, "StepSmoke", pNPCUnit:GetLandPosition_LUA(), D3DXVECTOR2(100,100), D3DXVECTOR2(5,-1) )
	end

end



function LIZARDMAN_SHAMAN_KING_EXPERT_DYING_LAND_STATE_START( pKTDXApp, pX2Game, pNPCUnit )

	pos = pNPCUnit:GetPos()
	pos.y = pos.y + 100.0
	GetMinorParticle = pX2Game:GetMinorParticle()
	
	pSeq = GetMinorParticle:GameUnitCreateSequence_LUA( pNPCUnit, "DieLight",		pos, D3DXVECTOR2(-1,-1), D3DXVECTOR2(3,-1) )
	if pSeq ~= nil then
	
		pSeq:SetLandPosition( pNPCUnit:GetLandPosition_LUA().y )
		pNPCUnit:SetDieSeq( pSeq:GetHandle() )
	
	end
	pNPCUnit:PlaySound_LUA( "DieLight.ogg" )
	
end



