-- lua header. UTF-8 인코딩 인식을 위해 이 줄은 지우지 마세요.




INIT_SYSTEM = 
{
	UNIT_WIDTH		= 250.0,
	UNIT_HEIGHT		= 200.0,
	UNIT_LAYER		= X2_LAYER["XL_UNIT_0"],
	UNIT_SCALE		= 1.45,
}

                                                                                 
INIT_DEVICE = 
{
	READY_TEXTURE = 
	{		
		"Smoke_Machine03.tga",
		"ColorBallFire.dds",
		"smoke02.dds",
		"stone_AirShip.dds",
	},
	
	READY_SOUND = 
	{
		"Nasod_Driller_AttackA_Winding.ogg",
		"Nasod_Driller_AttackB_Winding.ogg",
		"Nasod_Driller_AttackB_3.ogg",
		"Nasod_MinerC_Fat_Down.ogg",
        "Nasod_MinerC_Fat_Down2.ogg",
		"Nasod_Miner_Fat_Walk.ogg",
        "Nasod_Miner_Fat_DamageStandUpBack1.ogg",
        "Nasod_Miner_Fat_DamageStandUpBack2.ogg",
        "Nasod_Miner_Fat_DamageStandUpFront.ogg",
		"Nasod_Miner_Fat_Dash.ogg",
        "Nasod_MinerC_StepLanding.ogg",
        "Nasod_Miner_Fat_DashEnd.ogg",
		"Nasod_Miner_Fat_Attack.ogg",
		"Nasod_Miner_Fat_Attack2.ogg",
		"Nasod_Driller_ComboFinal.ogg",
		"Nasod_Driller_Missile1.ogg",
		"Nasod_Driller_Missile2.ogg",
		"Nasod_Driller_Combo_Winding.ogg",
		
		"Nasod_Driller_CannonAttack1.ogg",
		"Nasod_Driller_CannonAttack2.ogg",
		"Nasod_Driller_CannonAttack3.ogg",

		"Nasod_Driller_HyperCannon1.ogg",
		"Nasod_Driller_HyperCannon2.ogg",
		"Nasod_Driller_HyperCannon3.ogg",
		
	},
	
		
	READY_XMESH = 
	{
		"Thief_Fat_JumpAttackA_Stone01.y",
		"Thief_Fat_JumpAttackA_Stone02.y",
		
		"Stone01_AirShip.Y",
		"Stone02_AirShip.Y",
		
		
	},
	
	
	READY_XSKIN_MESH = 
	{
	    "Nasod_Bullet01.X",
		"Motion_Stone.x",
		"Dynamite_Nasod_Driller.X",
		"DummyAttackBox_50x50x50.x",
		"Altera_Mine_None.X",
		
	},
	
}

INIT_MOTION = 
{
	MOTION_FILE_NAME		= "Motion_Nasod_Driller_Cannon.x",
	MOTION_CHANGE_TEX_XET	= "Nasod_Driller_Cannon.xet",

}


INIT_PHYSIC = 
{
	RELOAD_ACCEL		= 2000,
	G_ACCEL				= 4000,
	MAX_G_SPEED			= -2000,
	
	WALK_SPEED			= 400,
	RUN_SPEED			= 600,
	JUMP_SPEED			= 1400,
	DASH_JUMP_SPEED		= 1600,
}


INIT_COMPONENT = 
{
	MAX_HP				= 9000,
	MP_CHANGE_RATE		= 2,
	MP_CHARGE_RATE		= 130,
	
	USE_SLASH_TRACE		= FALSE,
	
	SHADOW_SIZE			= 200,
	SHADOW_FILE_NAME	= "shadow.dds",
	
	SMALL_HP_BAR_BLUE	= "Small_HP_bar_Blue.TGA",
	SMALL_HP_BAR_RED	= "Small_HP_bar_Red.TGA",
	SMALL_HP_BAR_YELLOW = "Small_HP_bar_Yellow.TGA",
	
	DRAW_SMALL_MP_BAR	= TRUE,	
	
	QUESTION_MARK_SEQ		= "QuestionMarkNPC",
	EXCLAMATION_MARK_SEQ	= "ExclamationMarkNPC",
	--MIND_FLAG_HEIGHT		= 230,
	
	HYPER_MODE_COUNT	= 0,
	MAX_HYPER_MODE_TIME	= 30,
	
	RAGE_COUNT_MAX		= 20,
	RAGE_TIME_MAX		= 3,

	HITTED_TYPE			= HITTED_TYPE["HTD_MEAT"],
	
	FALL_DOWN			= TRUE,
	DEFENCE_RATE		= 10,
	
	BOSS_GAGE_FACE_TEX			= "DLG_BossState.tga",
	BOSS_GAGE_FACE_TEX_PIECE	= "Nasod_Driller_Cannon",						
	BOSS_NAME_TEX				= "HQ_BOSS_NAME_NASOD_DRILLER_CANNON.dds",	
	
}

INIT_STATE = 
{
	{ STATE_NAME = "NASOD_DRILLER_CANNON_START",					LUA_CAMERA_MOVE_FUNC = "NASOD_DRILLER_CANNON_START_CAMERA_MOVE",
	                                                                LUA_FRAME_MOVE_FUNC = "NASOD_DRILLER_CANNON_START_FRAME_MOVE",
																    LUA_STATE_END_FUNC = "NASOD_DRILLER_CANNON_START_STATE_END",					},
																	
	{ STATE_NAME = "NASOD_DRILLER_CANNON_WAIT",						},
	{ STATE_NAME = "NASOD_DRILLER_CANNON_WAIT_START",				LUA_FRAME_MOVE_FUNC = "NASOD_DRILLER_CANNON_WAIT_START_FRAME_MOVE",
																    LUA_STATE_END_FUNC = "NASOD_DRILLER_CANNON_WAIT_START_STATE_END",				},
																	
	{ STATE_NAME = "NASOD_DRILLER_CANNON_WALK",						LUA_FRAME_MOVE_FUNC = "NASOD_DRILLER_CANNON_WALK_FRAME_MOVE",	
																    LUA_STATE_END_FUNC = "NASOD_DRILLER_CANNON_WALK_STATE_END"						},
	
	{ STATE_NAME = "NASOD_DRILLER_CANNON_DASH",						LUA_FRAME_MOVE_FUNC = "NASOD_DRILLER_CANNON_DASH_FRAME_MOVE",					},
	{ STATE_NAME = "NASOD_DRILLER_CANNON_DASH_END",					LUA_STATE_START_FUNC = "NASOD_DRILLER_CANNON_DASH_END_STATE_START"				},
	
	{ STATE_NAME = "NASOD_DRILLER_CANNON_JUMP_UP",					},
	{ STATE_NAME = "NASOD_DRILLER_CANNON_JUMP_DOWN",				LUA_STATE_END_FUNC = "NASOD_DRILLER_CANNON_JUMP_DOWN_STATE_END"					},
	{ STATE_NAME = "NASOD_DRILLER_CANNON_JUMP_UP_DIR",				},
	{ STATE_NAME = "NASOD_DRILLER_CANNON_JUMP_DOWN_DIR",			LUA_STATE_END_FUNC = "NASOD_DRILLER_CANNON_JUMP_DOWN_DIR_STATE_END"				},
	{ STATE_NAME = "NASOD_DRILLER_CANNON_JUMP_LANDING",				},


	{ STATE_NAME = "NASOD_DRILLER_CANNON_ATTACK_A",					LUA_FRAME_MOVE_FUNC = "NASOD_DRILLER_CANNON_ATTACK_A_FRAME_MOVE",	
																    LUA_STATE_END_FUNC = "NASOD_DRILLER_CANNON_ATTACK_A_STATE_END",					},

    { STATE_NAME = "NASOD_DRILLER_CANNON_ATTACK_MINE",				LUA_FRAME_MOVE_FUNC = "NASOD_DRILLER_CANNON_ATTACK_B_FRAME_MOVE",	    		
																    LUA_STATE_END_FUNC = "NASOD_DRILLER_CANNON_ATTACK_B_STATE_END",
																    STATE_COOL_TIME = 5,  															},
																    															
	{ STATE_NAME = "NASOD_DRILLER_CANNON_ATTACK_B",					LUA_FRAME_MOVE_FUNC = "NASOD_DRILLER_CANNON_ATTACK_B_FRAME_MOVE",	
																    LUA_STATE_END_FUNC = "NASOD_DRILLER_CANNON_ATTACK_B_STATE_END",					},
																
	{ STATE_NAME = "NASOD_DRILLER_CANNON_COMBO",					LUA_FRAME_MOVE_FUNC = "NASOD_DRILLER_CANNON_COMBO_FRAME_MOVE",
																    LUA_STATE_END_FUNC = "NASOD_DRILLER_CANNON_COMBO_STATE_END",					},
																	
    { STATE_NAME = "NASOD_DRILLER_CANNON_CANNON_ATTACK",			LUA_FRAME_MOVE_FUNC = "NASOD_DRILLER_CANNON_CANNON_CANNON_ATTACK_FRAME_MOVE",
																	LUA_STATE_END_FUNC = "NASOD_DRILLER_CANNON_CANNON_CANNON_ATTACK_STATE_END",		
																	STATE_COOL_TIME = 30, 															},

	{ STATE_NAME = "NASOD_DRILLER_CANNON_SP_HYPER_CANNON",			LUA_FRAME_MOVE_FUNC = "NASOD_DRILLER_CANNON_CANNON_SP_HYPER_CANNON_FRAME_MOVE",
																	LUA_STATE_END_FUNC = "NASOD_DRILLER_CANNON_CANNON_SP_HYPER_CANNON_STATE_END",	},														
																
	{ STATE_NAME = "NASOD_DRILLER_CANNON_DEFENCE",					STATE_COOL_TIME= 15,															},
	
	
	--리액션 관련
	{ STATE_NAME = "NASOD_DRILLER_CANNON_DAMAGE_SMALL",				LUA_FRAME_MOVE_FUNC = "NASOD_DRILLER_CANNON_DAMAGE_SMALL_FRAME_MOVE",			},
	{ STATE_NAME = "NASOD_DRILLER_CANNON_DAMAGE_BIG",				LUA_FRAME_MOVE_FUNC = "NASOD_DRILLER_CANNON_DAMAGE_BIG_FRAME_MOVE",				},
	{ STATE_NAME = "NASOD_DRILLER_CANNON_DAMAGE_DOWN_FRONT",		LUA_FRAME_MOVE_FUNC = "NASOD_DRILLER_CANNON_DAMAGE_DOWN_FRONT_FRAME_MOVE",		},
	{ STATE_NAME = "NASOD_DRILLER_CANNON_DAMAGE_DOWN_BACK",			LUA_FRAME_MOVE_FUNC = "NASOD_DRILLER_CANNON_DAMAGE_DOWN_BACK_FRAME_MOVE",		},
	{ STATE_NAME = "NASOD_DRILLER_CANNON_DAMAGE_FLY_FRONT",			},
	{ STATE_NAME = "NASOD_DRILLER_CANNON_DAMAGE_FLY_BACK",			},
	{ STATE_NAME = "NASOD_DRILLER_CANNON_DAMAGE",					},
	{ STATE_NAME = "NASOD_DRILLER_CANNON_DAMAGE_DOWN",				},
	{ STATE_NAME = "NASOD_DRILLER_CANNON_DAMAGE_UP",				},
	{ STATE_NAME = "NASOD_DRILLER_CANNON_DAMAGE_FALL",				},
	{ STATE_NAME = "NASOD_DRILLER_CANNON_DAMAGE_DOWN_LANDING",		LUA_FRAME_MOVE_FUNC = "NASOD_DRILLER_CANNON_DAMAGE_DOWN_LANDING_FRAME_MOVE"	,	},
	{ STATE_NAME = "NASOD_DRILLER_CANNON_STAND_UP_FRONT",			},
	{ STATE_NAME = "NASOD_DRILLER_CANNON_STAND_UP_BACK",			},
	{ STATE_NAME = "NASOD_DRILLER_CANNON_STAND_UP_ATTACK_FRONT",	LUA_FRAME_MOVE_FUNC = "NASOD_DRILLER_CANNON_STAND_UP_ATTACK_FRONT_FRAME_MOVE",
																	LUA_STATE_END_FUNC = "NASOD_DRILLER_CANNON_STAND_UP_ATTACK_FRONT_STATE_END",	},
	{ STATE_NAME = "NASOD_DRILLER_CANNON_STAND_UP_ATTACK_BACK",		LUA_FRAME_MOVE_FUNC = "NASOD_DRILLER_CANNON_STAND_UP_ATTACK_BACK_FRAME_MOVE",
																	--LUA_STATE_END_FUNC = "NASOD_DRILLER_CANNON_STAND_UP_ATTACK_BACK_STATE_END",		
																	},
	
	{ STATE_NAME = "NASOD_DRILLER_CANNON_DYING_LAND_FRONT",			LUA_STATE_START_FUNC = "NASOD_DRILLER_CANNON_DYING_LAND_STATE_START",			},
	{ STATE_NAME = "NASOD_DRILLER_CANNON_DYING_LAND_BACK",			LUA_STATE_START_FUNC = "NASOD_DRILLER_CANNON_DYING_LAND_STATE_START",			},
	{ STATE_NAME = "NASOD_DRILLER_CANNON_DYING_SKY",				LUA_STATE_START_FUNC = "NASOD_DRILLER_CANNON_DYING_LAND_STATE_START",			},
	
	
	
	START_STATE					= "NASOD_DRILLER_CANNON_START",
	WAIT_STATE					= "NASOD_DRILLER_CANNON_WAIT",
	DEFENCE_STATE				= "NASOD_DRILLER_CANNON_DEFENCE",
	
	
	SMALL_DAMAGE_LAND_FRONT		= "NASOD_DRILLER_CANNON_DAMAGE_SMALL",
	SMALL_DAMAGE_LAND_BACK		= "NASOD_DRILLER_CANNON_DAMAGE_SMALL",
	BIG_DAMAGE_LAND_FRONT		= "NASOD_DRILLER_CANNON_DAMAGE_BIG",
	BIG_DAMAGE_LAND_BACK		= "NASOD_DRILLER_CANNON_DAMAGE_BIG",
	DOWN_DAMAGE_LAND_FRONT		= "NASOD_DRILLER_CANNON_DAMAGE_DOWN_FRONT",
	DOWN_DAMAGE_LAND_BACK		= "NASOD_DRILLER_CANNON_DAMAGE_DOWN_BACK",
	FLY_DAMAGE_FRONT			= "NASOD_DRILLER_CANNON_DAMAGE_FLY_FRONT",
	FLY_DAMAGE_BACK				= "NASOD_DRILLER_CANNON_DAMAGE_FLY_BACK",
	SMALL_DAMAGE_AIR			= "NASOD_DRILLER_CANNON_DAMAGE",	
	BIG_DAMAGE_AIR				= "NASOD_DRILLER_CANNON_DAMAGE",
	DOWN_DAMAGE_AIR				= "NASOD_DRILLER_CANNON_DAMAGE_DOWN",
	UP_DAMAGE					= "NASOD_DRILLER_CANNON_DAMAGE_UP",
	DAMAGE_REVENGE				= "NASOD_DRILLER_CANNON_DAMAGE_SMALL",
	
	DAMAGE_EXTRA_STATES         = { "NASOD_DRILLER_CANNON_DAMAGE_FALL","NASOD_DRILLER_CANNON_DAMAGE_DOWN_LANDING",
	"NASOD_DRILLER_CANNON_STAND_UP_FRONT","NASOD_DRILLER_CANNON_STAND_UP_BACK","NASOD_DRILLER_CANNON_STAND_UP_ATTACK_FRONT","NASOD_DRILLER_CANNON_STAND_UP_ATTACK_BACK",
	"NASOD_DRILLER_CANNON_JUMP_DOWN","NASOD_DRILLER_CANNON_JUMP_LANDING",	},	
	
	DYING_LAND_FRONT			= "NASOD_DRILLER_CANNON_DYING_LAND_FRONT",
	DYING_LAND_BACK				= "NASOD_DRILLER_CANNON_DYING_LAND_BACK",
	DYING_SKY					= "NASOD_DRILLER_CANNON_DYING_SKY",

	REVENGE_ATTACK				= "",	
}



INIT_AI = 
{
	TARGET = 
	{
		TARGET_PRIORITY 			= TARGET_PRIORITY["TP_LOW_HP_FIRST"],
		TARGET_INTERVAL				= 3,		-- sec
		TARGET_NEAR_RANGE			= 150,		-- 이 거리보다 가까우면 TARGET_SUCCESS_RATE에 관계없이 무조건 타게팅된다
		TARGET_RANGE				= 800,		-- cm
		TARGET_LOST_RANGE			= 10000,		-- cm
		TARGET_SUCCESS_RATE			= 100,  --50,		-- %
		ATTACK_TARGET_RATE			= 100, -- 30,		-- 나를 공격한 유닛을 타게팅할 확률
		PRESERVE_LAST_TARGET_RATE	= 100, -- 30,		-- 이전에 타게팅된 유닛을 계속 타게팅할 확률
	},

	CHASE_MOVE = 
	{		
		MOVE_SPLIT_RANGE	= 600,
		DEST_GAP			= 150,	-- 목적지에서 이 거리 안에 있으면 도착했다고 판단한다
		MOVE_GAP			= 160,
		
		DIR_CHANGE_INTERVAL = 0.7,
		
		WALK_INTERVAL		= 3,
		NEAR_WALK_RATE		= 50,   --  70,
		FAR_WALK_RATE		= 50,   -- 30,
		
		JUMP_INTERVAL		= 5,
		UP_JUMP_RATE		= 100, -- 40,
		UP_DOWN_RATE		= 20,
		DOWN_JUMP_RATE		= 100,    --  20,
		DOWN_DOWN_RATE		= 40,
		
		LINE_END_RANGE		= 80,	-- cm
	},	
	
	PATROL_MOVE = 	
	{
		PATROL_BEGIN_RATE		= 100, --50,		
		PATROL_RANGE			= 200,
		PATROL_COOL_TIME		= 2,
		ONLY_THIS_LINE_GROUP	= TRUE,
	},
	
	ESCAPE_MOVE = 
	{		
		MOVE_SPLIT_RANGE	= 500,	-- cm
		ESCAPE_GAP			= 600,	-- 이 거리 보다 멀어지면 도망 성공
		
		WALK_INTERVAL		= 1.5,	-- 초
		NEAR_WALK_RATE		= 100,   --  10,
		FAR_WALK_RATE		= 100,   -- 10,
		
		JUMP_INTERVAL		= 10,
		UP_JUMP_RATE		= 100, -- 30,
		UP_DOWN_RATE		= 30,
		DOWN_JUMP_RATE		= 100,    --  30,
		DOWN_DOWN_RATE		= 30,
		
		LINE_END_RANGE		= 80,	-- cm
	},

}


NASOD_DRILLER_CANNON_START = 
{
	ANIM_NAME					= "WaitStart",
	PLAY_TYPE					= XSKIN_ANIM_PLAYTYPE["XAP_ONE_WAIT"],
	TRANSITION					= FALSE,
	
	CAN_PUSH_UNIT				= TRUE,
	CAN_PASS_UNIT				= FALSE,
	RIGHT					= TRUE,
	IMMADIATE_PACKET_SEND		= TRUE,	

    SOUND_PLAY0			= { 0.200, "Nasod_Driller_AttackA_Winding.ogg" },
    SOUND_PLAY1			= { 1.772, "Nasod_Miner_Fat_Attack.ogg" },
		
	EVENT_PROCESS = 
	{		
		{ STATE_CHANGE_TYPE["SCT_CONDITION_TABLE"],		"NASOD_DRILLER_CANNON_WAIT",		"CT_NASOD_DRILLER_CANNON_WAIT"				},
	},
	
	CT_NASOD_DRILLER_CANNON_WAIT = 
	{
		STATE_TIME_OVER			= 3,
	},
}


NASOD_DRILLER_CANNON_WAIT_START = 
{
	ANIM_NAME					= "WaitStart",
	PLAY_TYPE					= XSKIN_ANIM_PLAYTYPE["XAP_ONE_WAIT"],
	TRANSITION					= FALSE,
	
	CAN_PUSH_UNIT				= TRUE,
	CAN_PASS_UNIT				= FALSE,
	IMMADIATE_PACKET_SEND		= TRUE,	

    SOUND_PLAY0			= { 0.200, "Nasod_Miner_Fat_Attack2.ogg" },
    SOUND_PLAY1			= { 1.772, "Nasod_Miner_Fat_Attack2.ogg" },
	
	EVENT_PROCESS = 
	{		
		{ STATE_CHANGE_TYPE["SCT_FOOT_ON_LINE_FALSE_DOWN"],		"NASOD_DRILLER_CANNON_JUMP_DOWN",			},
		{ STATE_CHANGE_TYPE["SCT_MOTION_END"],					"NASOD_DRILLER_CANNON_WAIT",					},
	},
	
	TALK_BOX =
	{
		EVENT_INTERVAL_ID			= 0,
 		{ RATE = 30, MESSAGE = STR_ID_2567 },
 	},

}



NASOD_DRILLER_CANNON_WAIT = 
{
	ANIM_NAME					= "Wait",
	PLAY_TYPE					= XSKIN_ANIM_PLAYTYPE["XAP_LOOP"],
	TRANSITION					= TRUE,
	
	CAN_PUSH_UNIT				= TRUE,
	CAN_PASS_UNIT				= FALSE,	
	
	SPEED_X						= 0,
	SPEED_Y						= 0,
	
	PASSIVE_SPEED_X				= 0,
	
	IMMADIATE_PACKET_SEND		= TRUE,
	EVENT_INTERVAL_TIME0		= 2,
	
	EVENT_PROCESS = 
	{		
		
		{ STATE_CHANGE_TYPE["SCT_FOOT_ON_LINE_FALSE_DOWN"],	"NASOD_DRILLER_CANNON_JUMP_DOWN",				},
        
		{ STATE_CHANGE_TYPE["SCT_CONDITION_TABLE"],			"NASOD_DRILLER_CANNON_ATTACK_A",				"CT_NASOD_DRILLER_CANNON_ATTACK_A",			},
		{ STATE_CHANGE_TYPE["SCT_CONDITION_TABLE"],			"NASOD_DRILLER_CANNON_ATTACK_B",				"CT_NASOD_DRILLER_CANNON_ATTACK_B",			},
	--	{ STATE_CHANGE_TYPE["SCT_CONDITION_TABLE"],			"NASOD_DRILLER_CANNON_COMBO",					"CT_NASOD_DRILLER_CANNON_COMBO",			},
		
		{ STATE_CHANGE_TYPE["SCT_CONDITION_TABLE"],			"NASOD_DRILLER_CANNON_SP_HYPER_CANNON",			"CT_NASOD_DRILLER_CANNON_SP_HYPER_CANNON",	},
	--	{ STATE_CHANGE_TYPE["SCT_CONDITION_TABLE"],			"NASOD_DRILLER_CANNON_CANNON_ATTACK",			"CT_NASOD_DRILLER_CANNON_CANNON_ATTACK",	},
		
		{ STATE_CHANGE_TYPE["SCT_CONDITION_TABLE"],			"NASOD_DRILLER_CANNON_WAIT_START",				"CT_NASOD_DRILLER_CANNON_WAIT_START",		},
		
		{ STATE_CHANGE_TYPE["SCT_AI_WALK"],					"NASOD_DRILLER_CANNON_WALK",					},		
		{ STATE_CHANGE_TYPE["SCT_AI_DASH"],					"NASOD_DRILLER_CANNON_DASH",					},
		{ STATE_CHANGE_TYPE["SCT_AI_JUMP"],					"NASOD_DRILLER_CANNON_JUMP_UP",					},
		{ STATE_CHANGE_TYPE["SCT_AI_JUMP_DIR"],				"NASOD_DRILLER_CANNON_JUMP_UP_DIR",				},
		{ STATE_CHANGE_TYPE["SCT_AI_DOWN"],					"NASOD_DRILLER_CANNON_JUMP_DOWN",				},
		{ STATE_CHANGE_TYPE["SCT_AI_DOWN_DIR"],				"NASOD_DRILLER_CANNON_JUMP_DOWN_DIR",			},
		
		{ STATE_CHANGE_TYPE["SCT_CONDITION_TABLE"],			"NASOD_DRILLER_CANNON_ATTACK_MINE",				"CT_NASOD_DRILLER_CANNON_ATTACK_MINE",		},
	},
	
	CT_NASOD_DRILLER_CANNON_CANNON_ATTACK = 
	{
		EVENT_INTERVAL_ID			= 0,
		DISTANCE_TO_TARGET_NEAR		= 800,
		RATE						= 30,
	},
		
	CT_NASOD_DRILLER_CANNON_SP_HYPER_CANNON =
	{
		EVENT_INTERVAL_ID			= 0,
		DISTANCE_OVER_TARGET_NEAR	= 500,
		MY_MP_MORE_THAN_PERCENT		= 70,
		RATE						= 100,
	},
	CT_NASOD_DRILLER_CANNON_ATTACK_A = 
	{
		EVENT_INTERVAL_ID			= 0,
		DISTANCE_TO_TARGET_NEAR		= 400,
		RATE						= 50,
	},
	
	CT_NASOD_DRILLER_CANNON_ATTACK_B = 
	{
		EVENT_INTERVAL_ID			= 0,
		DISTANCE_TO_TARGET_NEAR		= 400,
		RATE						= 50,
	},
	
	CT_NASOD_DRILLER_CANNON_COMBO = 
	{
		EVENT_INTERVAL_ID			= 0,
		DISTANCE_TO_TARGET_NEAR		= 400,
		RATE						= 50,
	},

	CT_NASOD_DRILLER_CANNON_WAIT_START = 
	{
		ANIM_PLAY_COUNT				= 2,
		RATE						= 60,
		HAVE_TARGET					= 0,		-- false
	},
	
	CT_NASOD_DRILLER_CANNON_ATTACK_MINE =
	{
	    EVENT_INTERVAL_ID			= 0,		
		RATE						= 30,   
	},	
	
    TALK_BOX =
	{
		EVENT_INTERVAL_ID			= 0,
 		{ RATE = 10,		MESSAGE = STR_ID_1659 },
 	},
		
}




NASOD_DRILLER_CANNON_WALK = 
{
	ANIM_NAME					= "Walk",
	PLAY_TYPE					= XSKIN_ANIM_PLAYTYPE["XAP_LOOP"],
	TRANSITION					= TRUE,
	
	CAN_PUSH_UNIT				= TRUE,
	CAN_PASS_UNIT				= FALSE,
	
	PASSIVE_SPEED_X				= INIT_PHYSIC["WALK_SPEED"],

    SOUND_PLAY0			= { 0.01, "Nasod_Miner_Fat_Walk.ogg" },
	
	ALLOW_DIR_CHANGE			= TRUE,
	IMMADIATE_PACKET_SEND		= TRUE,
	
	EVENT_INTERVAL_TIME0		= 2,
	EVENT_INTERVAL_TIME1		= 3,
	
	EVENT_PROCESS = 
	{		
		{ STATE_CHANGE_TYPE["SCT_FOOT_ON_LINE_FALSE_DOWN"],	"NASOD_DRILLER_CANNON_JUMP_DOWN_DIR",			},
				
		{ STATE_CHANGE_TYPE["SCT_CONDITION_TABLE"],			"NASOD_DRILLER_CANNON_ATTACK_A",				"CT_NASOD_DRILLER_CANNON_ATTACK_A",				},
		{ STATE_CHANGE_TYPE["SCT_CONDITION_TABLE"],			"NASOD_DRILLER_CANNON_ATTACK_B",				"CT_NASOD_DRILLER_CANNON_ATTACK_B",				},
		{ STATE_CHANGE_TYPE["SCT_CONDITION_TABLE"],			"NASOD_DRILLER_CANNON_COMBO",					"CT_NASOD_DRILLER_CANNON_COMBO",			},
		
		{ STATE_CHANGE_TYPE["SCT_CONDITION_TABLE"],			"NASOD_DRILLER_CANNON_SP_HYPER_CANNON",			"CT_NASOD_DRILLER_CANNON_SP_HYPER_CANNON",	},
		{ STATE_CHANGE_TYPE["SCT_CONDITION_TABLE"],			"NASOD_DRILLER_CANNON_CANNON_ATTACK",			"CT_NASOD_DRILLER_CANNON_CANNON_ATTACK",	},
		
		{ STATE_CHANGE_TYPE["SCT_AI_WAIT"],					"NASOD_DRILLER_CANNON_WAIT",					},
		{ STATE_CHANGE_TYPE["SCT_AI_DASH"],					"NASOD_DRILLER_CANNON_DASH",					},
		{ STATE_CHANGE_TYPE["SCT_AI_JUMP"],					"NASOD_DRILLER_CANNON_JUMP_UP",					},
		{ STATE_CHANGE_TYPE["SCT_AI_JUMP_DIR"],				"NASOD_DRILLER_CANNON_JUMP_UP_DIR",				},
		{ STATE_CHANGE_TYPE["SCT_AI_DOWN"],					"NASOD_DRILLER_CANNON_JUMP_DOWN",				},
		{ STATE_CHANGE_TYPE["SCT_AI_DOWN_DIR"],				"NASOD_DRILLER_CANNON_JUMP_DOWN_DIR",			},
		
		{ STATE_CHANGE_TYPE["SCT_CONDITION_TABLE"],			"NASOD_DRILLER_CANNON_ATTACK_MINE",				"CT_NASOD_DRILLER_CANNON_ATTACK_MINE",		},
	},
	
	CT_NASOD_DRILLER_CANNON_CANNON_ATTACK = 
	{
		EVENT_INTERVAL_ID			= 0,
		DISTANCE_TO_TARGET_NEAR		= 500,
		RATE						= 60,
	},
		
	CT_NASOD_DRILLER_CANNON_SP_HYPER_CANNON =
	{
		EVENT_INTERVAL_ID			= 0,
		DISTANCE_TO_TARGET_NEAR		= 800,
		MY_MP_MORE_THAN_PERCENT		= 100,
		RATE						= 60,
	},
	CT_NASOD_DRILLER_CANNON_ATTACK_A = 
	{
		EVENT_INTERVAL_ID			= 0,
		DISTANCE_TO_TARGET_NEAR		= 400,
		RATE						= 50,
	},
	CT_NASOD_DRILLER_CANNON_ATTACK_B = 
	{
		EVENT_INTERVAL_ID			= 0,
		DISTANCE_TO_TARGET_NEAR		= 400,
		RATE						= 50,
	},

	CT_NASOD_DRILLER_CANNON_COMBO = 
	{
		EVENT_INTERVAL_ID			= 0,
		DISTANCE_TO_TARGET_NEAR		= 400,
		RATE						= 50,
	},

    CT_NASOD_DRILLER_CANNON_ATTACK_MINE =
	{
	    EVENT_INTERVAL_ID			= 0,		
		RATE						= 50,   
	},	
		
	TALK_BOX =
 	{
 		EVENT_INTERVAL_ID		= 1,
		{ RATE = 10, MESSAGE = STR_ID_2574 },
		{ RATE = 10, MESSAGE = STR_ID_1472 },
	},
}




NASOD_DRILLER_CANNON_DASH = 
{
	ANIM_NAME					= "Dash",
	PLAY_TYPE					= XSKIN_ANIM_PLAYTYPE["XAP_LOOP"],
	TRANSITION					= FALSE,
	
	CAN_PUSH_UNIT				= TRUE,
	CAN_PASS_UNIT				= FALSE,

--    SOUND_PLAY0			= { 0.01, "Nasod_Miner_Fat_Dash.ogg" },
	
	PASSIVE_SPEED_X				= INIT_PHYSIC["RUN_SPEED"],
	
	ALLOW_DIR_CHANGE			= FALSE,
	IMMADIATE_PACKET_SEND		= TRUE,
	
	EVENT_INTERVAL_TIME0		= 2,
	EVENT_INTERVAL_TIME1		= 3,
	EVENT_INTERVAL_TIME2		= 0.2,	
	
	EVENT_PROCESS = 
	{		
		{ STATE_CHANGE_TYPE["SCT_FOOT_ON_LINE_FALSE_DOWN"],	"NASOD_DRILLER_CANNON_JUMP_DOWN_DIR",			},
				
		{ STATE_CHANGE_TYPE["SCT_CONDITION_TABLE"],			"NASOD_DRILLER_CANNON_ATTACK_A",				"CT_NASOD_DRILLER_CANNON_ATTACK_A",				},
		{ STATE_CHANGE_TYPE["SCT_CONDITION_TABLE"],			"NASOD_DRILLER_CANNON_ATTACK_B",				"CT_NASOD_DRILLER_CANNON_ATTACK_B",				},
		{ STATE_CHANGE_TYPE["SCT_CONDITION_TABLE"],			"NASOD_DRILLER_CANNON_COMBO",					"CT_NASOD_DRILLER_CANNON_COMBO",			},
		{ STATE_CHANGE_TYPE["SCT_CONDITION_TABLE"],			"NASOD_DRILLER_CANNON_COMBO",					"CT_NASOD_DRILLER_CANNON_COMBO2",			},
		
		{ STATE_CHANGE_TYPE["SCT_CONDITION_TABLE"],			"NASOD_DRILLER_CANNON_DASH_END",				"CT_NASOD_DRILLER_CANNON_DASH_END",			},
	
		{ STATE_CHANGE_TYPE["SCT_AI_WAIT"],					"NASOD_DRILLER_CANNON_DASH_END",				},
		{ STATE_CHANGE_TYPE["SCT_AI_WALK"],					"NASOD_DRILLER_CANNON_WALK",					},
		{ STATE_CHANGE_TYPE["SCT_AI_JUMP"],					"NASOD_DRILLER_CANNON_JUMP_UP",					},
		{ STATE_CHANGE_TYPE["SCT_AI_JUMP_DIR"],				"NASOD_DRILLER_CANNON_JUMP_UP_DIR",				},
		{ STATE_CHANGE_TYPE["SCT_AI_DOWN"],					"NASOD_DRILLER_CANNON_JUMP_DOWN",				},
		{ STATE_CHANGE_TYPE["SCT_AI_DOWN_DIR"],				"NASOD_DRILLER_CANNON_JUMP_DOWN_DIR",			},
	},
	
	CT_NASOD_DRILLER_CANNON_ATTACK_A = 
	{
		EVENT_INTERVAL_ID			= 0,
		DISTANCE_TO_TARGET_NEAR		= 400,
		RATE						= 100,
	},
	CT_NASOD_DRILLER_CANNON_ATTACK_B = 
	{
		EVENT_INTERVAL_ID			= 0,
		DISTANCE_TO_TARGET_NEAR		= 400,
		RATE						= 50,
	},

		
	CT_NASOD_DRILLER_CANNON_COMBO = 
	{
		EVENT_INTERVAL_ID			= 0,
		DISTANCE_TO_TARGET_NEAR		= 400,
		RATE						= 50,
	},
	
	CT_NASOD_DRILLER_CANNON_COMBO2 = 
	{
		EVENT_INTERVAL_ID			= 2,
		ATTACK_SUCCESS				= TRUE,
		STATE_TIME_OVER				= 1.6,
		RATE						= 80,
	},
	
	CT_NASOD_DRILLER_CANNON_DASH_END =
	{
		EVENT_INTERVAL_ID			= 2,
		STATE_TIME_OVER				= 2.0,
	},
	
	ATTACK_TIME0				= { 0.01, 100 },
	
	DAMAGE_DATA = 
	{
		DAMAGE_TYPE		= DAMAGE_TYPE["DT_PHYSIC"],
		HIT_TYPE		= HIT_TYPE["HT_PUNCH_HIT"],
		REACT_TYPE		= REACT_TYPE["RT_BIG_DAMAGE"],
		

		DAMAGE =
		{
			PHYSIC		= 0.3,
		},

		BACK_SPEED_X			= 1000,
		BACK_SPEED_Y			= 0.0,

		CAMERA_CRASH_GAP		= 10.0,
		CAMERA_CRASH_TIME		= 0.2,

		RE_ATTACK				= TRUE,
		HIT_GAP					= 0.25,
	},
		
			
	TALK_BOX =
 	{
 		EVENT_INTERVAL_ID		= 1,
		{ RATE = 10, MESSAGE = STR_ID_2574 },
		{ RATE = 10, MESSAGE = STR_ID_1472 },
	},
}




NASOD_DRILLER_CANNON_DASH_END = 
{
	ANIM_NAME					= "DashEnd",
	PLAY_TYPE					= XSKIN_ANIM_PLAYTYPE["XAP_ONE_WAIT"],
	TRANSITION					= FALSE,
	
	CAN_PUSH_UNIT				= TRUE,
	CAN_PASS_UNIT				= FALSE,

    SOUND_PLAY0			= { 0.01, "Nasod_Miner_Fat_DashEnd.ogg" },

	PASSIVE_SPEED_X				= -1,
	SPEED_X						= INIT_PHYSIC["RUN_SPEED"],
	
	ALLOW_DIR_CHANGE			= TRUE,
	IMMADIATE_PACKET_SEND		= TRUE,
	
	EVENT_PROCESS = 
	{		
		{ STATE_CHANGE_TYPE["SCT_FOOT_ON_LINE_FALSE_DOWN"],	"NASOD_DRILLER_CANNON_JUMP_DOWN_DIR",			},
		{ STATE_CHANGE_TYPE["SCT_MOTION_END"],				"NASOD_DRILLER_CANNON_WAIT",					},
	},
}



NASOD_DRILLER_CANNON_JUMP_UP = 
{
	ANIM_NAME					= "JumpUp",
	PLAY_TYPE					= XSKIN_ANIM_PLAYTYPE["XAP_LOOP"],
	TRANSITION					= TRUE,
	LAND_CONNECT				= FALSE,
	
	CAN_PUSH_UNIT				= TRUE,
	CAN_PASS_UNIT				= FALSE,
	
	SPEED_X						= 0,
	SPEED_Y						= INIT_PHYSIC["JUMP_SPEED"],
	
	ADD_POS_Y					= 45, 
	
	IMMADIATE_PACKET_SEND		= TRUE,
	
	EVENT_PROCESS = 
	{		
		{ STATE_CHANGE_TYPE["SCT_NEGATIVE_Y_SPEED"],		"NASOD_DRILLER_CANNON_JUMP_DOWN",			},
	},
	
}

NASOD_DRILLER_CANNON_JUMP_DOWN = 
{
	ANIM_NAME					= "JumpDown",
	PLAY_TYPE					= XSKIN_ANIM_PLAYTYPE["XAP_LOOP"],
	TRANSITION					= TRUE,
	LAND_CONNECT				= FALSE,
	
	CAN_PUSH_UNIT				= TRUE,
	CAN_PASS_UNIT				= FALSE,
		 
	
	IMMADIATE_PACKET_SEND		= TRUE,
		
	EVENT_PROCESS = 
	{		
		{ STATE_CHANGE_TYPE["SCT_FOOT_ON_LINE_TRUE"],		"NASOD_DRILLER_CANNON_JUMP_LANDING",				},
	},
}

NASOD_DRILLER_CANNON_JUMP_UP_DIR = 
{
	ANIM_NAME					= "JumpUp",
	PLAY_TYPE					= XSKIN_ANIM_PLAYTYPE["XAP_LOOP"],
	TRANSITION					= TRUE,
	LAND_CONNECT				= FALSE,
	
	CAN_PUSH_UNIT				= TRUE,
	CAN_PASS_UNIT				= FALSE,
		
	PASSIVE_SPEED_X				= INIT_PHYSIC["WALK_SPEED"],
	SPEED_Y						= INIT_PHYSIC["JUMP_SPEED"],
	
	ADD_POS_Y					= 45, 
	
	IMMADIATE_PACKET_SEND		= TRUE,
	
	EVENT_PROCESS = 
	{		
		{ STATE_CHANGE_TYPE["SCT_NEGATIVE_Y_SPEED"],		"NASOD_DRILLER_CANNON_JUMP_DOWN_DIR",				},
	},
	
}

NASOD_DRILLER_CANNON_JUMP_DOWN_DIR = 
{
	ANIM_NAME					= "JumpDown",
	PLAY_TYPE					= XSKIN_ANIM_PLAYTYPE["XAP_LOOP"],
	TRANSITION					= TRUE,
	LAND_CONNECT				= FALSE,
	
	CAN_PUSH_UNIT				= TRUE,
	CAN_PASS_UNIT				= FALSE,
	
	PASSIVE_SPEED_X				= INIT_PHYSIC["WALK_SPEED"],
	 
	
	IMMADIATE_PACKET_SEND		= TRUE,
		
	EVENT_PROCESS = 
	{		
		{ STATE_CHANGE_TYPE["SCT_FOOT_ON_LINE_TRUE"],		"NASOD_DRILLER_CANNON_JUMP_LANDING",				},
	},
}

NASOD_DRILLER_CANNON_JUMP_LANDING = 
{
	ANIM_NAME					= "JumpLanding",
	PLAY_TYPE					= XSKIN_ANIM_PLAYTYPE["XAP_ONE_WAIT"],
	TRANSITION					= TRUE,
	LAND_CONNECT				= FALSE,
	
	CAN_PUSH_UNIT				= TRUE,
	CAN_PASS_UNIT				= FALSE,

    SOUND_PLAY0			= { 0.123, "Nasod_MinerC_StepLanding.ogg" },
	

	SPEED_X						= 0,
	SPEED_Y						= 0,
		
	IMMADIATE_PACKET_SEND		= TRUE,

	EVENT_PROCESS = 
	{		
		{ STATE_CHANGE_TYPE["SCT_FOOT_ON_LINE_FALSE_DOWN"],	"NASOD_DRILLER_CANNON_JUMP_DOWN",					},
		{ STATE_CHANGE_TYPE["SCT_MOTION_END"],				"NASOD_DRILLER_CANNON_WAIT",						},
	},
}


NASOD_DRILLER_CANNON_ATTACK_A = 
{
	ANIM_NAME					= "AttackA",
	PLAY_TYPE					= XSKIN_ANIM_PLAYTYPE["XAP_ONE_WAIT"],
	TRANSITION					= FALSE,
	
	CAN_PUSH_UNIT				= TRUE,
	CAN_PASS_UNIT				= FALSE,

	SPEED_X						= 0,
	SPEED_Y						= 0,	

    SOUND_PLAY0			= { 0.275, "Nasod_Driller_AttackA_Winding.ogg" },
    SOUND_PLAY1			= { 0.557, "Nasod_Miner_Fat_Attack2.ogg" },
	
	VIEW_TARGET					= TRUE,
	
	IMMADIATE_PACKET_SEND		= TRUE,
	
	TALK_BOX = 
	{
		{ RATE = 10, MESSAGE = STR_ID_1473 },
		{ RATE = 10, MESSAGE = STR_ID_1474 },
	},
	
	EVENT_PROCESS = 
	{	
		{ STATE_CHANGE_TYPE["SCT_FOOT_ON_LINE_FALSE_DOWN"],	"NASOD_DRILLER_CANNON_JUMP_DOWN",											},
		{ STATE_CHANGE_TYPE["SCT_MOTION_END"],				"NASOD_DRILLER_CANNON_WAIT",												},	
	},
	
	
	DISABLE_ATTACK_BOX = 
	{
		"Lowbody",
		"Upbody",
		"Lhand",
		"L_hand",
		"R_hand",
	},
	
	ATTACK_TIME0				= { 0.890, 2.340, },
	
	DAMAGE_DATA =
	{
		DAMAGE_TYPE		= DAMAGE_TYPE["DT_PHYSIC"],
		HIT_TYPE		= HIT_TYPE["HT_SWORD_SLASH"],
		REACT_TYPE		= REACT_TYPE["RT_FLY"],

		DAMAGE =
		{
			PHYSIC		= 0.3,
		},

		BACK_SPEED_X			= 800,
		BACK_SPEED_Y			= 800,

		CAMERA_CRASH_GAP		= 5.0,
		CAMERA_CRASH_TIME		= 0.2,
	},
}




NASOD_DRILLER_CANNON_ATTACK_B = 
{
	ANIM_NAME					= "AttackB",
	PLAY_TYPE					= XSKIN_ANIM_PLAYTYPE["XAP_ONE_WAIT"],
	TRANSITION					= FALSE,
	
	CAN_PUSH_UNIT				= TRUE,
	CAN_PASS_UNIT				= FALSE,

    SOUND_PLAY0			= { 0.320, "Nasod_Driller_AttackB_Winding.ogg" },
    SOUND_PLAY1			= { 0.739, "Nasod_Miner_Fat_Attack2.ogg" },
    SOUND_PLAY2			= { 0.836, "Nasod_Driller_AttackB_3.ogg" },

	SPEED_X						= 0,
	SPEED_Y						= 0,	
	
	VIEW_TARGET					= TRUE,
	
	IMMADIATE_PACKET_SEND		= TRUE,
	--SUPER_ARMOR					= TRUE,
	
	TALK_BOX = 
	{
		{ RATE = 10, MESSAGE = STR_ID_1473 },
		{ RATE = 10, MESSAGE = STR_ID_1474 },
	},
	
	EVENT_PROCESS = 
	{	
		{ STATE_CHANGE_TYPE["SCT_FOOT_ON_LINE_FALSE_DOWN"],	"NASOD_DRILLER_CANNON_JUMP_DOWN",											},
		{ STATE_CHANGE_TYPE["SCT_MOTION_END"],				"NASOD_DRILLER_CANNON_WAIT",												},	
	},
	
	ATTACK_TIME0				= { 0.766, 1.666, },
	DISABLE_ATTACK_BOX = 
	{
		"Lowbody",
		"Upbody",
		"L_hand",
		"Lhand",
		"R_hand",
	},
	
	DAMAGE_DATA = 
	{
		DAMAGE_TYPE		= DAMAGE_TYPE["DT_PHYSIC"],
		HIT_TYPE		= HIT_TYPE["HT_SWORD_SLASH"],
		REACT_TYPE		= REACT_TYPE["RT_BIG_DAMAGE"],
		
		DAMAGE = 
		{
			PHYSIC		= 0.15,
		},
		
		BACK_SPEED_X			= INIT_PHYSIC["WALK_SPEED"] * 1.5,
		BACK_SPEED_Y			= 0.0,
		
		CAMERA_CRASH_GAP		= 5.0,	
		CAMERA_CRASH_TIME		= 0.2,		
	},
}

NASOD_DRILLER_CANNON_ATTACK_MINE = 
{
	ANIM_NAME					= "AttackB",
	PLAY_TYPE					= XSKIN_ANIM_PLAYTYPE["XAP_ONE_WAIT"],
	TRANSITION					= FALSE,
	
	CAN_PUSH_UNIT				= TRUE,
	CAN_PASS_UNIT				= FALSE,

    SOUND_PLAY0			= { 0.320, "Nasod_Driller_AttackB_Winding.ogg" },
    SOUND_PLAY1			= { 0.739, "Nasod_Miner_Fat_Attack2.ogg" },
    SOUND_PLAY2			= { 0.836, "Nasod_Driller_AttackB_3.ogg" },

	SPEED_X						= 0,
	SPEED_Y						= 0,	
	
	VIEW_TARGET					= TRUE,
	
	IMMADIATE_PACKET_SEND		= TRUE,
	SUPER_ARMOR					= TRUE,
	
	TALK_BOX = 
	{
		{ RATE = 10, MESSAGE = STR_ID_1473 },
		{ RATE = 10, MESSAGE = STR_ID_1474 },
	},
	
	
	EVENT_PROCESS = 
	{	
		{ STATE_CHANGE_TYPE["SCT_FOOT_ON_LINE_FALSE_DOWN"],	"NASOD_DRILLER_CANNON_JUMP_DOWN",											},
		{ STATE_CHANGE_TYPE["SCT_MOTION_END"],				"NASOD_DRILLER_CANNON_WAIT",												},	
	},
	
	ATTACK_TIME0				= { 0.766, 1.666, },
	DISABLE_ATTACK_BOX = 
	{
		"Lowbody",
		"Upbody",
		"Lhand",
		"L_hand",
		"R_hand",
	},
	
	DAMAGE_DATA = 
	{
		DAMAGE_TYPE		= DAMAGE_TYPE["DT_PHYSIC"],
		HIT_TYPE		= HIT_TYPE["HT_SWORD_SLASH"],
		REACT_TYPE		= REACT_TYPE["RT_BIG_DAMAGE"],
		
		DAMAGE = 
		{
			PHYSIC		= 0.18,
		},
		
		BACK_SPEED_X			= INIT_PHYSIC["WALK_SPEED"] * 1.5,
		BACK_SPEED_Y			= 0.0,
		
		CAMERA_CRASH_GAP		= 5.0,	
		CAMERA_CRASH_TIME		= 0.2,		
	},
}


NASOD_DRILLER_CANNON_COMBO =
{
	ANIM_NAME					= "Combo",
	PLAY_TYPE					= XSKIN_ANIM_PLAYTYPE["XAP_ONE_WAIT"],
	TRANSITION					= FALSE,
	
	CAN_PUSH_UNIT				= TRUE,
	CAN_PASS_UNIT				= FALSE,

    SOUND_PLAY0			= { 0.270, "Nasod_Driller_Combo_Winding.ogg" },
    SOUND_PLAY1			= { 0.461, "Nasod_Miner_Fat_Attack.ogg" },
    SOUND_PLAY2			= { 1.020, "Nasod_Miner_Fat_Attack2.ogg" },
    SOUND_PLAY3			= { 1.690, "Nasod_Miner_Fat_Attack.ogg" },
    SOUND_PLAY4			= { 2.044, "Nasod_Driller_ComboFinal.ogg" },
	
	SPEED_X						= INIT_PHYSIC["WALK_SPEED"],
	SPEED_Y						= 0,	
	
	VIEW_TARGET					= TRUE,
	IMMADIATE_PACKET_SEND		= TRUE,
	
	TALK_BOX = 
	{
		{ RATE = 10, MESSAGE = STR_ID_1473 },
		{ RATE = 10, MESSAGE = STR_ID_1474 },
	},
		
	EVENT_PROCESS = 
	{		
		{ STATE_CHANGE_TYPE["SCT_FOOT_ON_LINE_FALSE_DOWN"],	"NASOD_DRILLER_CANNON_JUMP_DOWN",			},
		{ STATE_CHANGE_TYPE["SCT_MOTION_END"],				"NASOD_DRILLER_CANNON_WAIT",					},
	},
	
	ATTACK_TIME0				= { 1.010, 1.110, },
	ATTACK_TIME1				= { 1.550, 1.610, },
	ATTACK_TIME2				= { 2.210, 3.310, },
	--ATTACK_TIME3				= { 1.966, 2.83, },
	
	DISABLE_ATTACK_BOX = 
	{
		"Lowbody",
		"Upbody",
	},
	
 	DAMAGE_DATA =
	{
		DAMAGE_TYPE		= DAMAGE_TYPE["DT_PHYSIC"],
		HIT_TYPE		= HIT_TYPE["HT_SWORD_SLASH"],
		REACT_TYPE		= REACT_TYPE["RT_SMALL_DAMAGE"],

		DAMAGE =
		{
			PHYSIC		= 0.5,
		},

		BACK_SPEED_X			= INIT_PHYSIC["WALK_SPEED"] * 1.2,
		BACK_SPEED_Y			= 0.0,

		CAMERA_CRASH_GAP		= 5.0,
		CAMERA_CRASH_TIME		= 0.2,

		RE_ATTACK				= FALSE,
	},


	DAMAGE_DATA_LAST =
	{
		DAMAGE_TYPE		= DAMAGE_TYPE["DT_PHYSIC"],
		HIT_TYPE		= HIT_TYPE["HT_SWORD_SLASH"],
		REACT_TYPE		= REACT_TYPE["RT_SMALL_DAMAGE"],

		DAMAGE =
		{
			PHYSIC		= 0.3,
		},

		BACK_SPEED_X			= INIT_PHYSIC["WALK_SPEED"],
		BACK_SPEED_Y			= 0,

		CAMERA_CRASH_GAP		= 8.0,
		CAMERA_CRASH_TIME		= 0.14,

		RE_ATTACK				= TRUE,
		HIT_GAP					= 0.14,
	},
}





NASOD_DRILLER_CANNON_CANNON_ATTACK = 
{
	ANIM_NAME					= "CannonAttack",
	PLAY_TYPE					= XSKIN_ANIM_PLAYTYPE["XAP_ONE_WAIT"],
	TRANSITION					= FALSE,
	
	CAN_PUSH_UNIT				= TRUE,
	CAN_PASS_UNIT				= FALSE,

    SOUND_PLAY0			= { 0.328, "Nasod_Driller_CannonAttack1.ogg" },
    SOUND_PLAY1			= { 0.962, "Nasod_Driller_CannonAttack2.ogg" },
    SOUND_PLAY2			= { 1.001, "Nasod_Driller_CannonAttack3.ogg" },

	
	SPEED_X						= 0,
	SPEED_Y						= 0,	
	
	IMMADIATE_PACKET_SEND		= TRUE,
	SUPER_ARMOR					= TRUE,
	VIEW_TARGET					= TRUE,
	
	
	PARTICLE_SEQ = 
	{
		--Major, time, Name, weaponBonePos, Pos, StateEndDelete, bTrace, posx, posy, posz, bApplyUnitRotation, rotx, roty, rotz,
		--{ TRUE, 1.0, "Nasod_Driller_Cannon_CannonAttack01", FALSE, "", TRUE, },
		{ TRUE, 1.05, "Smoke_Nasod_Diriler_Cannon_CannonAttack02", FALSE, "", TRUE, FALSE, -200, 0, -100, },
		{ TRUE, 1.0, "Flare_Nasod_Diriler_Cannon_CannonAttack03", FALSE, "Dummy2_Cannon", TRUE, },
	},

	
	EVENT_PROCESS = 
	{	
		{ STATE_CHANGE_TYPE["SCT_FOOT_ON_LINE_FALSE_DOWN"],	"NASOD_DRILLER_CANNON_JUMP_DOWN",										},
		{ STATE_CHANGE_TYPE["SCT_MOTION_END"],				"NASOD_DRILLER_CANNON_WAIT",											},	
	},
	
	DISABLE_ATTACK_BOX = 
	{
		"Lowbody",
		"Upbody",
		"Lhand",
		"L_hand",
		"Rhand",		
		"R_hand",
	},
}

NASOD_DRILLER_CANNON_SP_HYPER_CANNON = 
{
	ANIM_NAME					= "SP_HyperCannon",
	PLAY_TYPE					= XSKIN_ANIM_PLAYTYPE["XAP_ONE_WAIT"],
	TRANSITION					= FALSE,
	
	CAN_PUSH_UNIT				= TRUE,
	CAN_PASS_UNIT				= FALSE,

	SPEED_X						= 0,
	SPEED_Y						= 0,	

    SOUND_PLAY0			= { 0.588, "Nasod_Driller_HyperCannon1.ogg" },
    SOUND_PLAY1			= { 1.804, "Nasod_Driller_HyperCannon2.ogg" },
    SOUND_PLAY2			= { 2.235, "Nasod_Driller_HyperCannon3.ogg" },

	
	IMMADIATE_PACKET_SEND		= TRUE,
	SUPER_ARMOR					= TRUE,
	VIEW_TARGET					= TRUE,
	
	ALARM =
	{
		DANGER  				 = TRUE,  				    	    --DANGER 표시
		ALARM_MESSAGE 			 = STR_ID_15108,  		  		    --경고 문구
		DELAY   				 = 0,  				    	 		--이 스테이트가 시작되고 이 시간이 경과 후에 경고가 나갑니다.
		REPEAT   				 = TRUE,  		 		   		    --한 번만 반복 FALSE, 이 스테이트 취할때 마다 반복 TRUE
		ALARM_COLOR_TYPE		 = ALARM_COLOR_TYPE["ACT_ORANGE"],  --경고 문구 색깔 (ACT_RED, ACT_BLUE, ACT_YELLOW ,ACT_ORANGE, ACT_MAGENTA
		DISAPPEAR_TIME  		 = 5, 				  			    -- 표시 지속 시간
	},
	

	PARTICLE_SEQ = 
	{
		--Major, time, Name, weaponBonePos, Pos, StateEndDelete, bTrace, posx, posy, posz, bApplyUnitRotation, rotx, roty, rotz,
		{ TRUE, 1.0, "Nasod_Driller_Cannon_CannonAttack01", FALSE, "Dummy01", TRUE, },
		{ TRUE, 1.866, "Smoke_Nasod_Diriler_Cannon_CannonAttack02", FALSE, "", TRUE, FALSE, -250, 0, -100, },
		{ TRUE, 1.8, "Flare_Nasod_Diriler_Cannon_CannonAttack03", FALSE, "Dummy2_Cannon", TRUE, },
		{ TRUE, 0.43, "Flare_Nasod_Diriler_Cannon_HyperCannon02", FALSE, "Dummy2_Cannon", TRUE, TRUE, -5, -2, -30, },
		{ TRUE, 1.87, "Smoke_Nasod_Diriler_Cannon_HyperCannon01", FALSE, "", TRUE, FALSE, 0, 0, -100, },
		{ TRUE, 2.1, "Flare_Nasod_Diriler_Cannon_HyperCannon03", FALSE, "", TRUE, FALSE, 900, 270, 0, },
		{ TRUE, 2.0, "Flare_Nasod_Diriler_Cannon_HyperCannon04", FALSE, "", TRUE, FALSE, 900, 270, 0, },
	},

	EVENT_PROCESS = 
	{	
		{ STATE_CHANGE_TYPE["SCT_FOOT_ON_LINE_FALSE_DOWN"],	"NASOD_DRILLER_CANNON_JUMP_DOWN",										},
		{ STATE_CHANGE_TYPE["SCT_MOTION_END"],				"NASOD_DRILLER_CANNON_WAIT",											},	
	},
	
	DISABLE_ATTACK_BOX = 
	{
		"Lowbody",
		"Upbody",
		"Lhand",
		"L_hand",
		"Rhand",
		"R_hand",
	},
}




NASOD_DRILLER_CANNON_DEFENCE = 
{
	ANIM_NAME					= "Defence",
	PLAY_TYPE					= XSKIN_ANIM_PLAYTYPE["XAP_ONE_WAIT"],
	TRANSITION					= FALSE,
	LAND_CONNECT				= FALSE,
	
	CAN_PUSH_UNIT				= TRUE,
	CAN_PASS_UNIT				= FALSE,

	SUPER_ARMOR					= TRUE,
	DEFENCE						= { 0, 100, 50, }, 
	
	EVENT_PROCESS = 
	{
		{ STATE_CHANGE_TYPE["SCT_CONDITION_TABLE"],		"NASOD_DRILLER_CANNON_WAIT",				"CT_NASOD_DRILLER_CANNON_WAIT"		},
	},
	
	CT_NASOD_DRILLER_CANNON_WAIT = 
	{
		STATE_TIME_OVER			= 2,
	},
	
	TALK_BOX =
	{
		{ RATE = 20, MESSAGE = STR_ID_1491 },
	},
}



NASOD_DRILLER_CANNON_DAMAGE_SMALL = 
{
	ANIM_NAME					= "DamageSmall",		
	PLAY_TYPE					= XSKIN_ANIM_PLAYTYPE["XAP_ONE_WAIT"],
	TRANSITION					= FALSE,
	LAND_CONNECT				= FALSE,
	
	CAN_PUSH_UNIT				= TRUE,
	CAN_PASS_UNIT				= FALSE,
	
	TALK_BOX = 
	{
		{ RATE = 10, MESSAGE = STR_ID_1475 },
	},
	
	EVENT_PROCESS = 
	{
		{ STATE_CHANGE_TYPE["SCT_MOTION_END"],				"NASOD_DRILLER_CANNON_WAIT",												},
	},
}


NASOD_DRILLER_CANNON_DAMAGE_BIG = 
{
	ANIM_NAME					= "DamageBig",
	PLAY_TYPE					= XSKIN_ANIM_PLAYTYPE["XAP_ONE_WAIT"],
	TRANSITION					= FALSE,
	LAND_CONNECT				= FALSE,
	
	CAN_PUSH_UNIT				= TRUE,
	CAN_PASS_UNIT				= FALSE,
	
	TALK_BOX = 
	{
		{ RATE = 10, MESSAGE = STR_ID_1476 },
	},
	
	EVENT_PROCESS = 
	{
		{ STATE_CHANGE_TYPE["SCT_MOTION_END"],					"NASOD_DRILLER_CANNON_WAIT",												},
	},
	

}

NASOD_DRILLER_CANNON_DAMAGE_DOWN_FRONT = 
{
	ANIM_NAME					= "DamageDownFront",
	PLAY_TYPE					= XSKIN_ANIM_PLAYTYPE["XAP_ONE_WAIT"],
	TRANSITION					= FALSE,
	LAND_CONNECT				= FALSE,

	SUPER_ARMOR					= TRUE,
	DEFENCE						= { 0, 100, 50, },

    SOUND_PLAY0			= { 0.483, "Nasod_MinerC_Fat_Down.ogg" },

	CAN_PUSH_UNIT				= TRUE,
	CAN_PASS_UNIT				= FALSE,
	
	TALK_BOX = 
	{
		{ RATE = 10, MESSAGE = STR_ID_2568 },
		{ RATE = 10, MESSAGE = STR_ID_2569 },
	},
	
	EVENT_PROCESS = 
	{
		{ STATE_CHANGE_TYPE["SCT_FOOT_ON_LINE_FALSE_DOWN"],		"NASOD_DRILLER_CANNON_DAMAGE_FALL",			},
		{ STATE_CHANGE_TYPE["SCT_MOTION_END"],					"NASOD_DRILLER_CANNON_STAND_UP_FRONT",			},
	},
	
}

NASOD_DRILLER_CANNON_DAMAGE_DOWN_BACK = 
{
	ANIM_NAME					= "DamageDownBack",
	PLAY_TYPE					= XSKIN_ANIM_PLAYTYPE["XAP_ONE_WAIT"],
	TRANSITION					= FALSE,
	LAND_CONNECT				= FALSE,
	
	SUPER_ARMOR					= TRUE,
	DEFENCE						= { 0, 100, 50, },
	
	CAN_PUSH_UNIT				= TRUE,
	CAN_PASS_UNIT				= FALSE,

    SOUND_PLAY0			= { 0.410, "Nasod_MinerC_Fat_Down2.ogg" },

	TALK_BOX = 
	{
		{ RATE = 10, MESSAGE = STR_ID_2568 },
		{ RATE = 10, MESSAGE = STR_ID_2569 },
	},                       
	
	EVENT_PROCESS = 
	{
		{ STATE_CHANGE_TYPE["SCT_FOOT_ON_LINE_FALSE_DOWN"],		"NASOD_DRILLER_CANNON_DAMAGE_FALL",			},
		{ STATE_CHANGE_TYPE["SCT_CONDITION_TABLE"],				"NASOD_DRILLER_CANNON_STAND_UP_ATTACK_BACK",	"CT_NASOD_DRILLER_CANNON_STAND_UP_ATTACK_BACK", },
		{ STATE_CHANGE_TYPE["SCT_MOTION_END"],					"NASOD_DRILLER_CANNON_STAND_UP_BACK",			},
	},
	
	CT_NASOD_DRILLER_CANNON_STAND_UP_ATTACK_BACK = 
	{
		ANIM_PLAY_COUNT		= 1,
		RATE				= 10,
	},
}

NASOD_DRILLER_CANNON_DAMAGE_FLY_FRONT = 
{
	ANIM_NAME					= "DamageBig",
	PLAY_TYPE					= XSKIN_ANIM_PLAYTYPE["XAP_ONE_WAIT"],
	TRANSITION					= FALSE,
	LAND_CONNECT				= FALSE,	
	
	
	CAN_PUSH_UNIT				= TRUE,
	CAN_PASS_UNIT				= FALSE,
	
	EVENT_PROCESS = 
	{
		{ STATE_CHANGE_TYPE["SCT_FOOT_ON_LINE_TRUE"],			"NASOD_DRILLER_CANNON_DAMAGE_DOWN_LANDING",		},
	},
}

NASOD_DRILLER_CANNON_DAMAGE_FLY_BACK = 
{
	ANIM_NAME					= "DamageBig",
	PLAY_TYPE					= XSKIN_ANIM_PLAYTYPE["XAP_ONE_WAIT"],
	TRANSITION					= FALSE,
	LAND_CONNECT				= FALSE,	
	
	CAN_PUSH_UNIT				= TRUE,
	CAN_PASS_UNIT				= FALSE,
	
	EVENT_PROCESS = 
	{
		{ STATE_CHANGE_TYPE["SCT_FOOT_ON_LINE_TRUE"],			"NASOD_DRILLER_CANNON_DAMAGE_DOWN_BACK",		},
	},
}

NASOD_DRILLER_CANNON_DAMAGE = 
{
	ANIM_NAME					= "DamageAirSmall",
	PLAY_TYPE					= XSKIN_ANIM_PLAYTYPE["XAP_ONE_WAIT"],
	TRANSITION					= FALSE,
	LAND_CONNECT				= FALSE,
	
	CAN_PUSH_UNIT				= TRUE,
	CAN_PASS_UNIT				= FALSE,
	
	EVENT_PROCESS = 
	{
		{ STATE_CHANGE_TYPE["SCT_FOOT_ON_LINE_TRUE"],			"NASOD_DRILLER_CANNON_WAIT",					},
	},
}

NASOD_DRILLER_CANNON_DAMAGE_DOWN = 
{
	ANIM_NAME					= "DamageAirDown",
	PLAY_TYPE					= XSKIN_ANIM_PLAYTYPE["XAP_ONE_WAIT"],
	TRANSITION					= FALSE,
	LAND_CONNECT				= FALSE,
	
	CAN_PUSH_UNIT				= TRUE,
	CAN_PASS_UNIT				= FALSE,
	
	EVENT_PROCESS = 
	{
		{ STATE_CHANGE_TYPE["SCT_FOOT_ON_LINE_TRUE"],			"NASOD_DRILLER_CANNON_DAMAGE_DOWN_LANDING",	},
	},
}

NASOD_DRILLER_CANNON_DAMAGE_UP = 
{
	ANIM_NAME					= "DamageAirUp",
	PLAY_TYPE					= XSKIN_ANIM_PLAYTYPE["XAP_ONE_WAIT"],
	TRANSITION					= FALSE,
	LAND_CONNECT				= FALSE,
	
	CAN_PUSH_UNIT				= TRUE,
	CAN_PASS_UNIT				= FALSE,
	
    SPEED_Y						= 1400.0,
		
	EVENT_PROCESS = 
	{
		{ STATE_CHANGE_TYPE["SCT_NEGATIVE_Y_SPEED"],		"NASOD_DRILLER_CANNON_DAMAGE_FALL",			},
		{ STATE_CHANGE_TYPE["SCT_FOOT_ON_LINE_TRUE"],		"NASOD_DRILLER_CANNON_DAMAGE_DOWN_LANDING",	},
	},
	
	TALK_BOX =
	{
		{ RATE = 10, MESSAGE = STR_ID_2568 },
		{ RATE = 10, MESSAGE = STR_ID_2569 },
	},
}

NASOD_DRILLER_CANNON_DAMAGE_FALL = 
{
	ANIM_NAME					= "DamageAirFall",
	PLAY_TYPE					= XSKIN_ANIM_PLAYTYPE["XAP_ONE_WAIT"],
	TRANSITION					= FALSE,
	LAND_CONNECT				= FALSE,
	
	CAN_PUSH_UNIT				= TRUE,
	CAN_PASS_UNIT				= FALSE,
	
	EVENT_PROCESS = 
	{
		{ STATE_CHANGE_TYPE["SCT_POSITIVE_Y_SPEED"],		"NASOD_DRILLER_CANNON_DAMAGE_UP",			},
		{ STATE_CHANGE_TYPE["SCT_FOOT_ON_LINE_TRUE"],		"NASOD_DRILLER_CANNON_DAMAGE_DOWN_LANDING",	},
	},
}

NASOD_DRILLER_CANNON_DAMAGE_DOWN_LANDING = 
{
	ANIM_NAME					= "DamageAirDownLanding",
	PLAY_TYPE					= XSKIN_ANIM_PLAYTYPE["XAP_ONE_WAIT"],
	TRANSITION					= FALSE,
	LAND_CONNECT				= FALSE,

    SOUND_PLAY0			= { 0.090, "Nasod_MinerC_Fat_Down.ogg" },

	SUPER_ARMOR					= TRUE,
	DEFENCE						= { 0, 100, 50, },
	
	CAN_PUSH_UNIT				= TRUE,
	CAN_PASS_UNIT				= FALSE,
	
	EVENT_PROCESS = 
	{
		{ STATE_CHANGE_TYPE["SCT_FOOT_ON_LINE_FALSE_DOWN"],	"NASOD_DRILLER_CANNON_DAMAGE_FALL",			},
		{ STATE_CHANGE_TYPE["SCT_MOTION_END"],				"NASOD_DRILLER_CANNON_STAND_UP_FRONT",			},
	},
	
}

NASOD_DRILLER_CANNON_STAND_UP_FRONT = 
{
	ANIM_NAME					= "DamageStandUpFront",
	PLAY_TYPE					= XSKIN_ANIM_PLAYTYPE["XAP_ONE_WAIT"],
	TRANSITION					= FALSE,
	LAND_CONNECT				= TRUE,	
	
	SUPER_ARMOR					= TRUE,
	DEFENCE						= { 0, 100, 50, },

    SOUND_PLAY0			= { 0.100, "Nasod_Miner_Fat_DamageStandUpFront.ogg" },
	
	CAN_PUSH_UNIT				= TRUE,
	CAN_PASS_UNIT				= FALSE,
	
	EVENT_PROCESS = 
	{
		{ STATE_CHANGE_TYPE["SCT_FOOT_ON_LINE_FALSE_DOWN"],	"NASOD_DRILLER_CANNON_JUMP_DOWN",			},
		{ STATE_CHANGE_TYPE["SCT_CONDITION_TABLE"],			"NASOD_DRILLER_CANNON_STAND_UP_ATTACK_FRONT",		"CT_NASOD_DRILLER_CANNON_STAND_UP_ATTACK_FRONT", },
		{ STATE_CHANGE_TYPE["SCT_MOTION_END"],				"NASOD_DRILLER_CANNON_WAIT",				},
	},
	
	CT_NASOD_DRILLER_CANNON_STAND_UP_ATTACK_FRONT = 
	{
		ANIM_EVENT_TIMER	= 1.4,
		RATE				= 10,
	},

}

NASOD_DRILLER_CANNON_STAND_UP_BACK = 
{
	ANIM_NAME					= "DamageStandUpBack",
	PLAY_TYPE					= XSKIN_ANIM_PLAYTYPE["XAP_ONE_WAIT"],
	TRANSITION					= FALSE,
	LAND_CONNECT				= TRUE,
	
	SUPER_ARMOR					= TRUE,
	DEFENCE						= { 0, 100, 50, },

    SOUND_PLAY0			= { 0.01, "Nasod_Miner_Fat_DamageStandUpBack1.ogg" },
    SOUND_PLAY1			= { 1.387, "Nasod_Miner_Fat_DamageStandUpBack2.ogg" },
		
	CAN_PUSH_UNIT				= TRUE,
	CAN_PASS_UNIT				= FALSE,
		
	EVENT_PROCESS = 
	{
		{ STATE_CHANGE_TYPE["SCT_FOOT_ON_LINE_FALSE_DOWN"],	"NASOD_DRILLER_CANNON_JUMP_DOWN", },
		{ STATE_CHANGE_TYPE["SCT_CONDITION_TABLE"],			"NASOD_DRILLER_CANNON_STAND_UP_ATTACK_BACK",		"CT_NASOD_DRILLER_CANNON_STAND_UP_ATTACK_BACK", },
		{ STATE_CHANGE_TYPE["SCT_MOTION_END"],				"NASOD_DRILLER_CANNON_WAIT", },
	},	
	
	CT_NASOD_DRILLER_CANNON_STAND_UP_ATTACK_BACK = 
	{
		ANIM_EVENT_TIMER	= 1.55,
		RATE				= 10,
	},	
}


NASOD_DRILLER_CANNON_STAND_UP_ATTACK_FRONT = 
{
	ANIM_NAME					= "AttackB",
	PLAY_TYPE					= XSKIN_ANIM_PLAYTYPE["XAP_ONE_WAIT"],
	TRANSITION					= FALSE,
	LAND_CONNECT				= TRUE,	
	ANIM_WAIT_TIME				= 1,
	MIND_FLAG					= MIND_FLAG["MF_STAND_UP_ATTACK"],
	
	SUPER_ARMOR					= TRUE,
	DEFENCE						= { 0, 100, 50, },
		
	VIEW_TARGET					= TRUE,
	IMMADIATE_PACKET_SEND		= TRUE,
	
	
	CAN_PUSH_UNIT				= TRUE,
	CAN_PASS_UNIT				= FALSE,

    SOUND_PLAY0			= { 0.538, "Nasod_Miner_Fat_Attack.ogg" },


	EVENT_PROCESS = 
	{
		{ STATE_CHANGE_TYPE["SCT_FOOT_ON_LINE_FALSE_DOWN"],	"NASOD_DRILLER_CANNON_JUMP_DOWN",			},
		{ STATE_CHANGE_TYPE["SCT_MOTION_END"],				"NASOD_DRILLER_CANNON_WAIT",				},
	},
		
	ATTACK_TIME0				= { 0.55, 0.61, },	
	DISABLE_ATTACK_BOX = 
	{
		"Lowbody",
		"Upbody",
		"Lhand",
		"L_hand",
		"R_hand",
	},
	
	DAMAGE_DATA = 
	{
		DAMAGE_TYPE		= DAMAGE_TYPE["DT_PHYSIC"],
		HIT_TYPE		= HIT_TYPE["HT_SWORD_SLASH"],
		REACT_TYPE		= REACT_TYPE["RT_DOWN"],
		
		DAMAGE = 
		{
			PHYSIC		= 1.5,
			FIRE		= 0.0,
			ICE			= 0.0,
			EARTH		= 0.0,
			LIGHTNING	= 0.0,
			DARK		= 0.0,
			LIGHT		= 0.0,
			UNIVERSAL	= 0.0,
		},
		
		BACK_SPEED_X			= INIT_PHYSIC["RUN_SPEED"],
		BACK_SPEED_Y			= 0.0,
		
		STOP_TIME_ATT			= 0.0,		
		STOP_TIME_DEF			= 0.0,	
		CAMERA_CRASH_GAP		= 5.0,	
		CAMERA_CRASH_TIME		= 0.2,
		CLEAR_SCREEN			= 0.0,	
		CLEAR_SCREEN_COLOR_A	= 0.0,
		CLEAR_SCREEN_COLOR_R	= 1.0,
		CLEAR_SCREEN_COLOR_G	= 1.0,
		CLEAR_SCREEN_COLOR_B	= 1.0,

		RE_ATTACK				= FALSE,		
		HIT_GAP					= 0.0,				
	},
}

NASOD_DRILLER_CANNON_STAND_UP_ATTACK_BACK = 
{
	ANIM_NAME					= "AttackB",
	PLAY_TYPE					= XSKIN_ANIM_PLAYTYPE["XAP_ONE_WAIT"],
	TRANSITION					= FALSE,
	LAND_CONNECT				= TRUE,
	ANIM_WAIT_TIME				= 1,
	MIND_FLAG					= MIND_FLAG["MF_STAND_UP_ATTACK"],
	
	SUPER_ARMOR					= TRUE,
	DEFENCE						= { 0, 100, 50, },
		
	CAN_PUSH_UNIT				= TRUE,
	CAN_PASS_UNIT				= FALSE,

    SOUND_PLAY0			= { 0.538, "Nasod_Miner_Fat_Attack.ogg" },

		
	VIEW_TARGET					= TRUE,
	IMMADIATE_PACKET_SEND		= TRUE,
	
	
	--FLIP_DIR_END				= TRUE,
	
	EVENT_PROCESS = 
	{
		{ STATE_CHANGE_TYPE["SCT_FOOT_ON_LINE_FALSE_DOWN"],	"NASOD_DRILLER_CANNON_JUMP_DOWN", },
		{ STATE_CHANGE_TYPE["SCT_MOTION_END"],				"NASOD_DRILLER_CANNON_WAIT", },
	},	
	
		
	ATTACK_TIME0				= { 0.55, 0.61, },	
	DISABLE_ATTACK_BOX = 
	{
		"Lowbody",
		"Upbody",
		"Lhand",
		"L_hand",
		"R_hand",
	},
	
	DAMAGE_DATA = 
	{
		DAMAGE_TYPE		= DAMAGE_TYPE["DT_PHYSIC"],
		HIT_TYPE		= HIT_TYPE["HT_SWORD_SLASH"],
		REACT_TYPE		= REACT_TYPE["RT_DOWN"],
		
		DAMAGE = 
		{
			PHYSIC		= 1.5,
			FIRE		= 0.0,
			ICE			= 0.0,
			EARTH		= 0.0,
			LIGHTNING	= 0.0,
			DARK		= 0.0,
			LIGHT		= 0.0,
			UNIVERSAL	= 0.0,
		},
		
		BACK_SPEED_X			= INIT_PHYSIC["RUN_SPEED"],
		BACK_SPEED_Y			= 0.0,
		
		STOP_TIME_ATT			= 0.0,		
		STOP_TIME_DEF			= 0.0,	
		CAMERA_CRASH_GAP		= 5.0,	
		CAMERA_CRASH_TIME		= 0.2,
		CLEAR_SCREEN			= 0.0,	
		CLEAR_SCREEN_COLOR_A	= 0.0,
		CLEAR_SCREEN_COLOR_R	= 1.0,
		CLEAR_SCREEN_COLOR_G	= 1.0,
		CLEAR_SCREEN_COLOR_B	= 1.0,

		RE_ATTACK				= FALSE,		
		HIT_GAP					= 0.0,				
	},
}



NASOD_DRILLER_CANNON_DYING_LAND_FRONT = 
{
	ANIM_NAME					= "DamageDownFront",
	PLAY_TYPE					= XSKIN_ANIM_PLAYTYPE["XAP_ONE_WAIT"],
	TRANSITION					= FALSE,
	LAND_CONNECT				= TRUE,

	INVINCIBLE					= { 0, 100, }, 		

    SOUND_PLAY0			= { 0.483, "Nasod_MinerC_Fat_Down.ogg" },

	CAN_PUSH_UNIT				= FALSE,
	CAN_PASS_UNIT				= TRUE,
	
	DYING_END					= TRUE,
	
	IMMADIATE_PACKET_SEND		= TRUE,
}
	
NASOD_DRILLER_CANNON_DYING_LAND_BACK = 
{
	ANIM_NAME					= "DamageDownBack",
	PLAY_TYPE					= XSKIN_ANIM_PLAYTYPE["XAP_ONE_WAIT"],
	TRANSITION					= FALSE,
	LAND_CONNECT				= TRUE,
	
	INVINCIBLE					= { 0, 100, }, 		
	
	CAN_PUSH_UNIT				= FALSE,
	CAN_PASS_UNIT				= TRUE,

    SOUND_PLAY0			= { 0.807, "Nasod_MinerC_Fat_Down2.ogg" },

	DYING_END					= TRUE,	
	
	IMMADIATE_PACKET_SEND		= TRUE,
}

NASOD_DRILLER_CANNON_DYING_SKY = 
{
	ANIM_NAME					= "DamageAirDownLanding",
	PLAY_TYPE					= XSKIN_ANIM_PLAYTYPE["XAP_ONE_WAIT"],
	TRANSITION					= FALSE,
	LAND_CONNECT				= FALSE,
	
	INVINCIBLE					= { 0, 100, }, 		

    SOUND_PLAY0			= { 0.096, "Nasod_MinerC_Fat_Down.ogg" },

	CAN_PUSH_UNIT				= FALSE,
	CAN_PASS_UNIT				= TRUE,
	
	DYING_END					= TRUE,
	
	IMMADIATE_PACKET_SEND		= TRUE,
}










------------------------------------------------------------------------------
function NASOD_DRILLER_CANNON_START_FRAME_MOVE( pKTDXApp, pX2Game, pNPCUnit )

	NASOD_DRILLER_CANNON_WAIT_START_EFFECT_FRAME_MOVE( pKTDXApp, pX2Game, pNPCUnit )

end



------------------------------------------------------------------------------
function NASOD_DRILLER_CANNON_START_STATE_END( pKTDXApp, pX2Game, pNPCUnit )

	NASOD_DRILLER_CANNON_WAIT_START_EFFECT_STATE_END( pKTDXApp, pX2Game, pNPCUnit )

end



------------------------------------------------------------------------------
function NASOD_DRILLER_CANNON_WAIT_START_FRAME_MOVE( pKTDXApp, pX2Game, pNPCUnit )

	NASOD_DRILLER_CANNON_WAIT_START_EFFECT_FRAME_MOVE( pKTDXApp, pX2Game, pNPCUnit )

end



------------------------------------------------------------------------------
function NASOD_DRILLER_CANNON_WAIT_START_STATE_END( pKTDXApp, pX2Game, pNPCUnit )

	NASOD_DRILLER_CANNON_WAIT_START_EFFECT_STATE_END( pKTDXApp, pX2Game, pNPCUnit )

end



function NASOD_DRILLER_CANNON_WALK_FRAME_MOVE( pKTDXApp, pX2Game, pNPCUnit )

	for i = 0, 5 do
	
		fTime = 0.15 * i 
		if pNPCUnit:AnimEventTimer_LUA( fTime ) then

			pMinorParticle = pX2Game:GetMinorParticle()
			
			vPos = pNPCUnit:GetLandPosition_LUA()
			--pNPCUnit:PlaySound_LUA( "Nasod_Miner_Fat_Walk.ogg" )
			
		
			vDirVector = pNPCUnit:GetDirVector()
			bIsRight = pNPCUnit:GetIsRight()
			
			if bIsRight == true then 
				vPos.x = vPos.x - 150.0		* vDirVector.x
				vPos.z = vPos.z - 150.0		* vDirVector.z
			else
				vPos.x = vPos.x + 150.0		* vDirVector.x
				vPos.z = vPos.z + 150.0		* vDirVector.z
			end
			
			pMinorParticle:GameUnitCreateSequence_LUA( pNPCUnit, "StepSmoke", vPos, D3DXVECTOR2(100,100), D3DXVECTOR2(5,-1) )
			
			pNPCUnit:ClearEventCheck( fTime )
		
		end
	
	end

end


function NASOD_DRILLER_CANNON_WALK_STATE_END( pKTDXApp, pX2Game, pNPCUnit )

	pMinorParticle = pX2Game:GetMinorParticle()
	pMinorParticle:GameUnitCreateSequence_LUA( pNPCUnit, "StepSmoke", pNPCUnit:GetLandPosition_LUA(), D3DXVECTOR2(100,100), D3DXVECTOR2(5,-1) )

end


function NASOD_DRILLER_CANNON_DASH_FRAME_MOVE( pKTDXApp, pX2Game, pNPCUnit )

	for i = 0, 7 do
	
		fTime = 0.1 * i 
		if pNPCUnit:AnimEventTimer_LUA( fTime ) then

			pMinorParticle = pX2Game:GetMinorParticle()
			pNPCUnit:PlaySound_LUA( "Nasod_Miner_Fat_Dash.ogg" )
			
			vPos = pNPCUnit:GetLandPosition_LUA()
			
			vDirVector = pNPCUnit:GetDirVector()
			bIsRight = pNPCUnit:GetIsRight()
			
			if bIsRight == true then 
				vPos.x = vPos.x - 150.0		* vDirVector.x
				vPos.z = vPos.z - 150.0		* vDirVector.z
			else
				vPos.x = vPos.x + 150.0		* vDirVector.x
				vPos.z = vPos.z + 150.0		* vDirVector.z
			end
			
			pMinorParticle:GameUnitCreateSequence_LUA( pNPCUnit, "StepSmoke", vPos, D3DXVECTOR2(100,100), D3DXVECTOR2(5,-1) )
			
			pNPCUnit:ClearEventCheck( fTime )
		
		end
	
	end

end

function NASOD_DRILLER_CANNON_DASH_END_STATE_START( pKTDXApp, pX2Game, pNPCUnit )

	pMinorParticle = pX2Game:GetMinorParticle()
	pMinorParticle:GameUnitCreateSequence_LUA( pNPCUnit, "StepSmoke", pNPCUnit:GetLandPosition_LUA(), D3DXVECTOR2(100,100), D3DXVECTOR2(5,-1) )

end


function NASOD_DRILLER_CANNON_JUMP_DOWN_STATE_END( pKTDXApp, pX2Game, pNPCUnit )

	pMinorParticle = pX2Game:GetMinorParticle()
	pMinorParticle:GameUnitCreateSequence_LUA( pNPCUnit, "StepSmoke", pNPCUnit:GetLandPosition_LUA(), D3DXVECTOR2(100,100), D3DXVECTOR2(5,-1) )

end

function NASOD_DRILLER_CANNON_JUMP_DOWN_DIR_STATE_END( pKTDXApp, pX2Game, pNPCUnit )

	pMinorParticle = pX2Game:GetMinorParticle()
	pMinorParticle:GameUnitCreateSequence_LUA( pNPCUnit, "StepSmoke", pNPCUnit:GetLandPosition_LUA(), D3DXVECTOR2(100,100), D3DXVECTOR2(5,-1) )

end



------------------------------------------------------------------------------
function NASOD_DRILLER_CANNON_ATTACK_A_FRAME_MOVE( pKTDXApp, pX2Game, pNPCUnit )


	pParticle0 = pNPCUnit:GetMinorParticle_LUA( 0 ) 
	if nil ~= pParticle0 then 

		pMinorParticle = pX2Game:GetMinorParticle()
		
		if pMinorParticle:IsLiveInstance( pParticle0 ) == true then 
			vPos = pNPCUnit:GetBonePos_LUA( "Dummy01" )
			pParticle0:SetPosition( vPos )		
		else 
			pNPCUnit:ClearMinorParticle_LUA( 0 )
		end
	
	end

	pParticle1 = pNPCUnit:GetMinorParticle_LUA( 1 ) 
	if nil ~= pParticle1 then 

		pMinorParticle = pX2Game:GetMinorParticle()
		
		if pMinorParticle:IsLiveInstance( pParticle1 ) == true then 
			vPos = pNPCUnit:GetBonePos_LUA( "Bone_Rhand" )
			pParticle1:SetPosition( vPos )		
		else 
			pNPCUnit:ClearMinorParticle_LUA( 1 )
		end
	
	end


	if pNPCUnit:AnimEventTimer_LUA( 0.01 ) then
	
		pMinorParticle = pX2Game:GetMinorParticle()

		vBonePos = pNPCUnit:GetBonePos_LUA( "Bone_Rhand" )
		pParticle1 = pMinorParticle:GameUnitCreateSequence_LUA( pNPCUnit, "Flare_Nasod_DR_Attack01", vBonePos, D3DXVECTOR2(-1,-1), D3DXVECTOR2(-1,-1) )
		if pParticle1 ~= nil then 
			pParticle1:SetLandPosition( pNPCUnit:GetLandPosition_LUA().y )
			pNPCUnit:SetMinorParticle_LUA( 1, pParticle1:GetHandle() ) 
			
			rotDegree = pNPCUnit:GetRotateDegree()			
			pParticle1:SetAddRotate( rotDegree )
			pParticle1:SetAxisAngle( rotDegree )
		end
	end
		
		
	if pNPCUnit:AnimEventTimer_LUA( 0.5 ) then	
		
	    pNPCUnit:PlaySound_LUA( "Nasod_Engine_Big.ogg" )					
		
	end
	


end


------------------------------------------------------------------------------
function NASOD_DRILLER_CANNON_ATTACK_A_STATE_END( pKTDXApp, pX2Game, pNPCUnit )

	pMinorParticle = pX2Game:GetMinorParticle()
	

	pParticle0 = pNPCUnit:GetMinorParticle_LUA( 0 ) 	
	if pParticle0 ~= nil then
		pMinorParticle:DestroyInstance( pParticle0 )
		pNPCUnit:ClearMinorParticle_LUA( 0 )
	end
	
	pParticle1 = pNPCUnit:GetMinorParticle_LUA( 1 ) 	
	if pParticle1 ~= nil then
		pMinorParticle:DestroyInstance( pParticle1 )
		pNPCUnit:ClearMinorParticle_LUA( 1 )
	end

end



------------------------------------------------------------------------------
function NASOD_DRILLER_CANNON_ATTACK_B_FRAME_MOVE( pKTDXApp, pX2Game, pNPCUnit )



	pParticle0 = pNPCUnit:GetMinorParticle_LUA( 0 ) 
	if nil ~= pParticle0 then 

		pMinorParticle = pX2Game:GetMinorParticle()
		
		if pMinorParticle:IsLiveInstance( pParticle0 ) == true then 
			vPos = pNPCUnit:GetBonePos_LUA( "Dummy01" )
			pParticle0:SetPosition( vPos )		
		else 
			pNPCUnit:ClearMinorParticle_LUA( 0 )
		end
	
	end
	
		
	if pNPCUnit:AnimEventTimer_LUA( 0.3 ) then
	    pNPCUnit:PlaySound_LUA( "Nasod_Engine_Big.ogg" )
	end
		

	if pNPCUnit:AnimEventTimer_LUA( 0.8 ) then
	
		pMajorParticle = pX2Game:GetMajorParticle()
		
		bIsRight		= pNPCUnit:GetIsRight()
		vDirVector		= pNPCUnit:GetDirVector()
		vZVector		= pNPCUnit:GetZVector()
		vPos			= pNPCUnit:GetPos()
		
		if bIsRight == true then 
			vPos = MovePos( vPos, vDirVector, 300 )
		else
			vPos = MovePos( vPos, vDirVector, -300 )
		end
		vPos = MovePos( vPos, vZVector, -50 )
		
		pMajorParticle:GameUnitCreateSequence_LUA( pNPCUnit, "Stone_Nasod_Driller01", vPos, D3DXVECTOR2(-1,-1), D3DXVECTOR2(-1,-1) )
		pMajorParticle:GameUnitCreateSequence_LUA( pNPCUnit, "Flare_Nasod_DR_Attack02", vPos, D3DXVECTOR2(-1,-1), D3DXVECTOR2(-1,-1) )
		pMajorParticle:GameUnitCreateSequence_LUA( pNPCUnit, "Nasod_Driller_AttackB_MeshParticle01", vPos, D3DXVECTOR2(-1,-1), D3DXVECTOR2(-1,-1) )
		pMajorParticle:GameUnitCreateSequence_LUA( pNPCUnit, "Nasod_Driller_AttackB_MeshParticle02", vPos, D3DXVECTOR2(-1,-1), D3DXVECTOR2(-1,-1) )
		
		
		-- invisible damage effect
		vPos = MovePos( vPos, vZVector, 50 )
		vPos.y = vPos.y + 150.0
		vLandPos = pNPCUnit:GetLandPosition_LUA()
		
		pDamageEffect = pX2Game:GetDamageEffect()
		pDamageEffect:CreateInstance_LUA( pNPCUnit, "NASOD_DRILLER_ATTACK_B", vPos, vLandPos.y )
		
		pNPCUnit:SetVector_LUA(0, pNPCUnit:GetPos())
		pNPCUnit:SetVector_LUA(1, pNPCUnit:GetDirVector())
	
	end

    -- if pNPCUnit:AnimEventTimer_LUA( 1.77 ) then
        -- -- 지뢰 매설	
	    -- bIsRight		= pNPCUnit:GetIsRight()
    	-- vPos = pNPCUnit:GetVector_LUA(0)
    	-- vDirVector = pNPCUnit:GetVector_LUA(1)
    	
	    -- if bIsRight == true then 
		    -- vPos = MovePos( vPos, vDirVector, 300 )
	    -- else
		    -- vPos = MovePos( vPos, vDirVector, -300 )
	    -- end	    
	    
	    -- pUID = pX2Game:GetNearNPCUnitUID_LUA( vPos, NPC_UNIT_ID["NUI_ALTERA_MINE_NONE"], 150 )
	    -- if pUID ~= 0 then
	        -- return
	    -- end
	    
	    -- vStartPos = pNPCUnit:GetLineGroupStartPos()
	    -- vEndPos = pNPCUnit:GetLineGroupEndPos()

        -- --print(pNPCUnit:GetDistanceFrom(vStartPos), pNPCUnit:GetDistanceFrom(vStartPos))
     	
 	    -- if bIsRight == true and pNPCUnit:GetDistanceFrom(vEndPos) >= 500.0 then       	
	        -- pX2Game:PushCreateNPCReq_Lua( NPC_UNIT_ID["NUI_ALTERA_MINE_NONE"], pNPCUnit:GetHardLevel(), false, vPos, true, 0.01, true, 0 )			
	        -- pX2Game:FlushCreateNPCReq()
        -- end	        
        
        -- if bIsRight == false and pNPCUnit:GetDistanceFrom(vStartPos) >= 500.0 then
            -- pX2Game:PushCreateNPCReq_Lua( NPC_UNIT_ID["NUI_ALTERA_MINE_NONE"], pNPCUnit:GetHardLevel(), false, vPos, true, 0.01, true, 0 )			
	        -- pX2Game:FlushCreateNPCReq()
        -- end	 
    --end
    	    
end




------------------------------------------------------------------------------
function NASOD_DRILLER_CANNON_ATTACK_B_STATE_END( pKTDXApp, pX2Game, pNPCUnit )

	pMinorParticle = pX2Game:GetMinorParticle()

	pParticle0 = pNPCUnit:GetMinorParticle_LUA( 0 ) 	
	if pParticle0 ~= nil then
		pMinorParticle:DestroyInstance( pParticle0 )
		pNPCUnit:ClearMinorParticle_LUA( 0 )
	end
	
	
end



------------------------------------------------------------------------------
function NASOD_DRILLER_CANNON_COMBO_FRAME_MOVE( pKTDXApp, pX2Game, pNPCUnit )
	
	if pNPCUnit:AnimEventTimer_LUA( 0.8 ) or
		pNPCUnit:AnimEventTimer_LUA( 1.5 ) then
		pNPCUnit:ClearHitUnitList_LUA()
		pNPCUnit:SetSpeedX( INIT_PHYSIC["RUN_SPEED"] )
	end
	
	if pNPCUnit:AnimEventTimer_LUA( 2.1 ) then
		pNPCUnit:ClearHitUnitList_LUA()
		pNPCUnit:SetDamageData_LUA( "DAMAGE_DATA_LAST" )
	end
	



	-- create particles
	if pNPCUnit:AnimEventTimer_LUA( 0.01 ) then
	
		pMinorParticle = pX2Game:GetMinorParticle()

		vBonePos = pNPCUnit:GetBonePos_LUA( "Dummy01" )
	    pNPCUnit:PlaySound_LUA( "Nasod_Engine_Big.ogg" )
		pParticle = pMinorParticle:GameUnitCreateSequence_LUA( pNPCUnit, "Smoke_Nasod_DR_Combo01", vBonePos, D3DXVECTOR2(-1,-1), D3DXVECTOR2(-1,-1) )
		
		if pParticle ~= nil then
			pParticle:SetLandPosition( pNPCUnit:GetLandPosition_LUA().y )
			pNPCUnit:SetMinorParticle_LUA( 0, pParticle:GetHandle() ) 
			
			
			rotDegree = pNPCUnit:GetRotateDegree()			
			pParticle:SetAddRotate( rotDegree )
			pParticle:SetAxisAngle( rotDegree )
		end 
		
		
		vBonePos = pNPCUnit:GetBonePos_LUA( "Bone_Rhand" )
		pParticle = pMinorParticle:GameUnitCreateSequence_LUA( pNPCUnit, "Flare_Nasod_DR_Combo01", vBonePos, D3DXVECTOR2(-1,-1), D3DXVECTOR2(-1,-1) )
		if pParticle ~= nil then
			pParticle:SetLandPosition( pNPCUnit:GetLandPosition_LUA().y )
			pNPCUnit:SetMinorParticle_LUA( 1, pParticle:GetHandle() ) 
			
			
			rotDegree = pNPCUnit:GetRotateDegree()			
			pParticle:SetAddRotate( rotDegree )
			pParticle:SetAxisAngle( rotDegree )
		end

	end

	if pNPCUnit:AnimEventTimer_LUA( 0.6 ) then
	
		pMinorParticle = pX2Game:GetMinorParticle()

		vBonePos = pNPCUnit:GetBonePos_LUA( "Bone_Lhand" )
		pParticle = pMinorParticle:GameUnitCreateSequence_LUA( pNPCUnit, "Flare_Nasod_DR_Combo01", vBonePos, D3DXVECTOR2(-1,-1), D3DXVECTOR2(-1,-1) )
		if pParticle ~= nil then
			pParticle:SetLandPosition( pNPCUnit:GetLandPosition_LUA().y )
			pNPCUnit:SetMinorParticle_LUA( 2, pParticle:GetHandle() ) 
			
			
			rotDegree = pNPCUnit:GetRotateDegree()			
			pParticle:SetAddRotate( rotDegree )
			pParticle:SetAxisAngle( rotDegree )
		end 
		
	end
	
	if pNPCUnit:AnimEventTimer_LUA( 1.5 ) then
	
		pMinorParticle = pX2Game:GetMinorParticle()

		vBonePos = pNPCUnit:GetBonePos_LUA( "Bone_Rhand" )
		
		vZVector = pNPCUnit:GetZVector()
		vBonePos = MovePos( vBonePos, vZVector, -100 )


		pParticle = pMinorParticle:GameUnitCreateSequence_LUA( pNPCUnit, "Flare_Nasod_DR_Combo01", vBonePos, D3DXVECTOR2(-1,-1), D3DXVECTOR2(-1,-1) )
		if pParticle ~= nil then
			pParticle:SetLandPosition( pNPCUnit:GetLandPosition_LUA().y )
			pNPCUnit:SetMinorParticle_LUA( 3, pParticle:GetHandle() ) 
			
			rotDegree = pNPCUnit:GetRotateDegree()			
			pParticle:SetAddRotate( rotDegree )
			pParticle:SetAxisAngle( rotDegree )
		end
		
	end
	
	if pNPCUnit:AnimEventTimer_LUA( 1.8 ) then
	
		pMinorParticle = pX2Game:GetMinorParticle()

		vBonePos = pNPCUnit:GetBonePos_LUA( "Dummy01" )
	    pNPCUnit:PlaySound_LUA( "Nasod_Engine_Big.ogg" )
		pParticle = pMinorParticle:GameUnitCreateSequence_LUA( pNPCUnit, "Smoke_Nasod_DR_Combo02", vBonePos, D3DXVECTOR2(-1,-1), D3DXVECTOR2(-1,-1) )
		if pParticle ~= nil then
			pParticle:SetLandPosition( pNPCUnit:GetLandPosition_LUA().y )
			pNPCUnit:SetMinorParticle_LUA( 4, pParticle:GetHandle() ) 
			
			rotDegree = pNPCUnit:GetRotateDegree()			
			pParticle:SetAddRotate( rotDegree )
			pParticle:SetAxisAngle( rotDegree )
		end
		
	end
	
	if pNPCUnit:AnimEventTimer_LUA( 1.9 ) then
	
		pMinorParticle = pX2Game:GetMinorParticle()

		vBonePos = pNPCUnit:GetBonePos_LUA( "Bone_Lhand" )
		
		vZVector = pNPCUnit:GetZVector()
		vBonePos = MovePos( vBonePos, vZVector, -100 )
				
		pParticle = pMinorParticle:GameUnitCreateSequence_LUA( pNPCUnit, "Flare_Nasod_DR_Combo01", vBonePos, D3DXVECTOR2(-1,-1), D3DXVECTOR2(-1,-1) )
		if pParticle ~= nil then
			pParticle:SetLandPosition( pNPCUnit:GetLandPosition_LUA().y )
			pNPCUnit:SetMinorParticle_LUA( 5, pParticle:GetHandle() ) 
			
			
			rotDegree = pNPCUnit:GetRotateDegree()			
			pParticle:SetAddRotate( rotDegree )
			pParticle:SetAxisAngle( rotDegree )
		end
		
	end
	
	
	
	-- particle framemove
	pParticle = pNPCUnit:GetMinorParticle_LUA( 0 ) 
	if nil ~= pParticle then 

		pMinorParticle = pX2Game:GetMinorParticle()
		
		if pMinorParticle:IsLiveInstance( pParticle ) == true then 
			vBonePos = pNPCUnit:GetBonePos_LUA( "Dummy01" )
			pParticle:SetPosition( vBonePos )		
		else 
			pNPCUnit:ClearMinorParticle_LUA( 0 )
		end
	
	end
	
	
	pParticle = pNPCUnit:GetMinorParticle_LUA( 1 ) 
	if nil ~= pParticle then 

		pMinorParticle = pX2Game:GetMinorParticle()
		
		if pMinorParticle:IsLiveInstance( pParticle ) == true then 
			vBonePos = pNPCUnit:GetBonePos_LUA( "Bone_Rhand" )
			pParticle:SetPosition( vBonePos )		
		else 
			pNPCUnit:ClearMinorParticle_LUA( 1 )
		end
	
	end
	
	pParticle = pNPCUnit:GetMinorParticle_LUA( 2 ) 
	if nil ~= pParticle then 

		pMinorParticle = pX2Game:GetMinorParticle()
		
		if pMinorParticle:IsLiveInstance( pParticle ) == true then 
			vBonePos = pNPCUnit:GetBonePos_LUA( "Bone_Lhand" )
			pParticle:SetPosition( vBonePos )		
		else 
			pNPCUnit:ClearMinorParticle_LUA( 2 )
		end
	
	end
	
	pParticle = pNPCUnit:GetMinorParticle_LUA( 3 ) 
	if nil ~= pParticle then 

		pMinorParticle = pX2Game:GetMinorParticle()
		
		if pMinorParticle:IsLiveInstance( pParticle ) == true then 
			vBonePos = pNPCUnit:GetBonePos_LUA( "Bone_Rhand" )
			vZVector = pNPCUnit:GetZVector()
			vBonePos = MovePos( vBonePos, vZVector, -100 )

			pParticle:SetPosition( vBonePos )		
		else 
			pNPCUnit:ClearMinorParticle_LUA( 3 )
		end
	
	end
	
	
		
	pParticle = pNPCUnit:GetMinorParticle_LUA( 4 ) 
	if nil ~= pParticle then 

		pMinorParticle = pX2Game:GetMinorParticle()
		
		if pMinorParticle:IsLiveInstance( pParticle ) == true then 
			vBonePos = pNPCUnit:GetBonePos_LUA( "Dummy01" )
			pParticle:SetPosition( vBonePos )		
		else 
			pNPCUnit:ClearMinorParticle_LUA( 4 )
		end
	
	end
	
	
		
	pParticle = pNPCUnit:GetMinorParticle_LUA( 5 ) 
	if nil ~= pParticle then 

		pMinorParticle = pX2Game:GetMinorParticle()
		
		if pMinorParticle:IsLiveInstance( pParticle ) == true then 
			vBonePos = pNPCUnit:GetBonePos_LUA( "Bone_Lhand" )
			vZVector = pNPCUnit:GetZVector()
			vBonePos = MovePos( vBonePos, vZVector, -100 )

			pParticle:SetPosition( vBonePos )		
		else 
			pNPCUnit:ClearMinorParticle_LUA( 5 )
		end
	
	end
	
	

end



------------------------------------------------------------------------------
function NASOD_DRILLER_CANNON_COMBO_STATE_END( pKTDXApp, pX2Game, pNPCUnit )

	pMinorParticle = pX2Game:GetMinorParticle()
	
	for i= 0, 5 do 
		
		pParticle = pNPCUnit:GetMinorParticle_LUA( i ) 	
		if pParticle ~= nil then
			pMinorParticle:DestroyInstance( pParticle )
			pNPCUnit:ClearMinorParticle_LUA( i )
		end
	
	end
	
end









function NASOD_DRILLER_CANNON_DAMAGE_SMALL_FRAME_MOVE( pKTDXApp, pX2Game, pNPCUnit )

	if pNPCUnit:AnimEventTimer_LUA( 0.047 ) then
		pMinorParticle = pX2Game:GetMinorParticle()
		pMinorParticle:GameUnitCreateSequence_LUA( pNPCUnit, "StepSmoke", pNPCUnit:GetLandPosition_LUA(), D3DXVECTOR2(100,100), D3DXVECTOR2(5,-1) )
	end

end

function NASOD_DRILLER_CANNON_DAMAGE_BIG_FRAME_MOVE( pKTDXApp, pX2Game, pNPCUnit )

	if pNPCUnit:AnimEventTimer_LUA( 0.06 ) then
		pMinorParticle = pX2Game:GetMinorParticle()
		pMinorParticle:GameUnitCreateSequence_LUA( pNPCUnit, "StepSmoke", pNPCUnit:GetLandPosition_LUA(), D3DXVECTOR2(100,100), D3DXVECTOR2(5,-1) )
	end

end

function NASOD_DRILLER_CANNON_DAMAGE_DOWN_FRONT_FRAME_MOVE( pKTDXApp, pX2Game, pNPCUnit )

	if pNPCUnit:AnimEventTimer_LUA( 0.41 ) then
		
		pMinorParticle = pX2Game:GetMinorParticle()
		pMinorParticle:GameUnitCreateSequence_LUA( pNPCUnit, "DownSmoke", pNPCUnit:GetLandPosition_LUA(), D3DXVECTOR2(100,100), D3DXVECTOR2(7,-1) )
	end

end

function NASOD_DRILLER_CANNON_DAMAGE_DOWN_BACK_FRAME_MOVE( pKTDXApp, pX2Game, pNPCUnit )

	if pNPCUnit:AnimEventTimer_LUA( 0.45 ) then
		
		pMinorParticle = pX2Game:GetMinorParticle()
		pMinorParticle:GameUnitCreateSequence_LUA( pNPCUnit, "DownSmoke", pNPCUnit:GetLandPosition_LUA(), D3DXVECTOR2(100,100), D3DXVECTOR2(7,-1) )
	end

end

function NASOD_DRILLER_CANNON_DAMAGE_DOWN_LANDING_FRAME_MOVE( pKTDXApp, pX2Game, pNPCUnit )

	if pNPCUnit:AnimEventTimer_LUA( 0.01 ) then
		
		pMinorParticle = pX2Game:GetMinorParticle()
		pos = pNPCUnit:GetLandPosition_LUA()
		pMinorParticle:GameUnitCreateSequence_LUA( pNPCUnit, "DownSmoke", pos, D3DXVECTOR2(100,100), D3DXVECTOR2(7,-1) )
		pos.y = pos.y + 5
		pMinorParticle:GameUnitCreateSequence_LUA( pNPCUnit, "GroundShockWave", pos, D3DXVECTOR2(100,100), D3DXVECTOR2(1,-1) )
		pParticle = pMinorParticle:GameUnitCreateSequence_LUA( pNPCUnit, "AirDownTick", pNPCUnit:GetPos(), D3DXVECTOR2(200,200), D3DXVECTOR2(10,-1) )
		if pParticle ~= nil then
			pParticle:SetLandPosition( pos.y - 5 )
		end
		
		if GetDistance_LUA( pNPCUnit:GetPos(), pX2Game:GetFocusUnitPos_LUA() ) < 500 then
			pX2Game:GetX2Camera():GetCamera():UpDownCrashCameraNoReset( 10.0, 0.1 )
		end		
		
	elseif pNPCUnit:AnimEventTimer_LUA( 0.1 ) then
		
		pMinorParticle = pX2Game:GetMinorParticle()
		pMinorParticle:GameUnitCreateSequence_LUA( pNPCUnit, "DownSmoke", pNPCUnit:GetLandPosition_LUA(), D3DXVECTOR2(100,100), D3DXVECTOR2(7,-1) )
		
	end

end




------------------------------------------------------------------------------
function NASOD_DRILLER_CANNON_STAND_UP_ATTACK_FRONT_FRAME_MOVE( pKTDXApp, pX2Game, pNPCUnit )


	if pNPCUnit:AnimEventTimer_LUA( 0.35 ) then
		pMinorParticle = pX2Game:GetMinorParticle()
		pMinorParticle:GameUnitCreateSequence_LUA( pNPCUnit, "StepSmoke", pNPCUnit:GetLandPosition_LUA(), D3DXVECTOR2(100,100), D3DXVECTOR2(5,-1) )
	end

end


------------------------------------------------------------------------------
function NASOD_DRILLER_CANNON_STAND_UP_ATTACK_FRONT_STATE_END( pKTDXApp, pX2Game, pNPCUnit )

end




------------------------------------------------------------------------------
function NASOD_DRILLER_CANNON_STAND_UP_ATTACK_BACK_FRAME_MOVE( pKTDXApp, pX2Game, pNPCUnit )

	if pNPCUnit:AnimEventTimer_LUA( 0.35 ) then
		pMinorParticle = pX2Game:GetMinorParticle()
		pMinorParticle:GameUnitCreateSequence_LUA( pNPCUnit, "StepSmoke", pNPCUnit:GetLandPosition_LUA(), D3DXVECTOR2(100,100), D3DXVECTOR2(5,-1) )
	end

	

end




function NASOD_DRILLER_CANNON_DYING_LAND_STATE_START( pKTDXApp, pX2Game, pNPCUnit )

	pos = pNPCUnit:GetPos()
	pos.y = pos.y + 100.0
	GetMinorParticle = pX2Game:GetMinorParticle()
	
	pSeq = GetMinorParticle:GameUnitCreateSequence_LUA( pNPCUnit, "DieLight",		pos, D3DXVECTOR2(-1,-1), D3DXVECTOR2(3,-1) )
	if pSeq ~= nil then
	
		pSeq:SetLandPosition( pNPCUnit:GetLandPosition_LUA().y )
		pNPCUnit:SetDieSeq( pSeq:GetHandle() )
	
	end
	pNPCUnit:PlaySound_LUA( "DieLight.ogg" )
	
end


------------------------------------------------------------------------------
function NASOD_DRILLER_CANNON_CANNON_CANNON_ATTACK_FRAME_MOVE( pKTDXApp, pX2Game, pNPCUnit )


	if pNPCUnit:AnimEventTimer_LUA( 1.0 ) then

		pX2Game:GetX2Camera():GetCamera():UpDownCrashCameraNoReset( 40.0, 0.3 )
	
	end

	if pNPCUnit:AnimEventTimer_LUA( 1.05 ) then
    	
--[[    	
    	pDamageEffect = pX2Game:GetDamageEffect()
		vLandPos = pNPCUnit:GetLandPosition_LUA()
		vBonePos = pNPCUnit:GetBonePos_LUA( "Dummy2_Cannon" )
		
		pDamageEffect:CreateInstance_LUA( pNPCUnit, "NASODDRILLER_CANNON_ATTACK", vBonePos, vLandPos.y )
--]]
        
		
		pDamageEffect = pX2Game:GetDamageEffect()
				
		pos = pNPCUnit:GetLandPosition_LUA()	
		vPos = pNPCUnit:GetPos()					
		vRot = pNPCUnit:GetRotateDegree()
		vRot.z = vRot.z + 25
		
		bIsRight = pNPCUnit:GetIsRight()	
		--[[	
			if bIsRight == true then
				--vRot.y = vRot.y + 180
				print("right")
				vRot.z = vRot.z + 180 - 25
        	else
        	    print("left")
        	    vRot.z = vRot.z + 25
			end
		--]]
		
		if pDamageEffect ~= nil then
		    if bIsRight == true then
                pDamageEffect:CreateInstance_LUA2( pNPCUnit, "DRILLER_CANNON_ATTACK_RIGHT", pNPCUnit:GetBonePos_LUA( "Dummy2_Cannon" ), pos.y, vRot )            
            else
                pDamageEffect:CreateInstance_LUA2( pNPCUnit, "DRILLER_CANNON_ATTACK_LEFT", pNPCUnit:GetBonePos_LUA( "Dummy2_Cannon" ), pos.y, vRot )            
            end                                
        end				
				
	end

end		



------------------------------------------------------------------------------
function NASOD_DRILLER_CANNON_CANNON_CANNON_ATTACK_STATE_END( pKTDXApp, pX2Game, pNPCUnit )

end





------------------------------------------------------------------------------
         
function NASOD_DRILLER_CANNON_CANNON_SP_HYPER_CANNON_FRAME_MOVE( pKTDXApp, pX2Game, pNPCUnit )
	
	if pNPCUnit:AnimEventTimer_LUA( 0.43 ) then
	
		pMajorParticle = pX2Game:GetMajorParticle()
			
		vBonePos = pNPCUnit:GetBonePos_LUA( "Dummy2_Cannon" )
		pParticle0 = pMajorParticle:GameUnitCreateSequence_LUA( pNPCUnit, "Flare_Nasod_Diriler_Cannon_HyperCannon01", vBonePos, D3DXVECTOR2(-1,-1), D3DXVECTOR2(-1,-1) )
		if pParticle0 ~= nil then 
			pParticle0:SetBlackHolePosition( vBonePos )
		end 
		
	end
	
	if pNPCUnit:AnimEventTimer_LUA( 1.75 ) then 
	
		pX2Game:GetX2Camera():GetCamera():UpDownCrashCameraNoReset( 40.0, 0.3 )
		
	end
	
	

	if pNPCUnit:AnimEventTimer_LUA( 2.0 ) then 
			
		bIsRight		= pNPCUnit:GetIsRight()
		vDirVector		= pNPCUnit:GetDirVector()
		vZVector		= pNPCUnit:GetZVector()
		vPos			= pNPCUnit:GetPos()
		
		if bIsRight == true then 
			vPos = MovePos( vPos, vDirVector, 850 )
		else
			vPos = MovePos( vPos, vDirVector, -850 )
		end
		
		vPos.y = vPos.y + 300
		
		pDamageEffect = pX2Game:GetDamageEffect()
		pDamageEffect:CreateInstance_LUA( pNPCUnit, "NASODDRILLER_CANNON_HYPER_CANNON", vPos, vPos.y )
		
		pNPCUnit:SetNowMP( 0 )
		
		pX2Game:GetX2Camera():GetCamera():UpDownCrashCameraNoReset( 60.0, 3.0 )
		
	end
	
end		



------------------------------------------------------------------------------
function NASOD_DRILLER_CANNON_CANNON_SP_HYPER_CANNON_STATE_END( pKTDXApp, pX2Game, pNPCUnit )

end







------------------------------------------------------------------------------
-- UTIL FUNCTION
------------------------------------------------------------------------------




------------------------------------------------------------------------------
function NASOD_DRILLER_CANNON_WAIT_START_EFFECT_FRAME_MOVE( pKTDXApp, pX2Game, pNPCUnit )
	
	-- particle creation
	if pNPCUnit:AnimEventTimer_LUA( 0.01 ) then
	
		pNPCUnit:PlaySound_LUA( "Nasod_Engine_Big.ogg" )
	
		pMinorParticle = pX2Game:GetMinorParticle()
		
		vRotateDegree	= pNPCUnit:GetRotateDegree()
		vBonePos		= pNPCUnit:GetBonePos_LUA( "Dummy01" )
		pParticle = pMinorParticle:GameUnitCreateSequence_LUA( pNPCUnit, "Smoke_Nasod_DR_Combo01", vBonePos, D3DXVECTOR2(-1,-1), D3DXVECTOR2(-1,-1) )
		if pParticle ~= nil then
			pParticle:SetAddRotate( vRotateDegree )
			pParticle:SetAxisAngle( vRotateDegree )	
			pNPCUnit:SetMinorParticle_LUA( 0, pParticle:GetHandle() ) 
		end
	
		vBonePos		= pNPCUnit:GetBonePos_LUA( "Bone_Rhand" )
		pParticle = pMinorParticle:GameUnitCreateSequence_LUA( pNPCUnit, "Flare_Nasod_DR_Combo01", vBonePos, D3DXVECTOR2(-1,-1), D3DXVECTOR2(-1,-1) )
		if pParticle ~= nil then
			pParticle:SetAddRotate( vRotateDegree )
			pParticle:SetAxisAngle( vRotateDegree )	
			pNPCUnit:SetMinorParticle_LUA( 1, pParticle:GetHandle() ) 
		end
	
	end
	
	
	
	if pNPCUnit:AnimEventTimer_LUA( 1.5 ) then
	
		pMinorParticle = pX2Game:GetMinorParticle()
	
		vRotateDegree	= pNPCUnit:GetRotateDegree()
		vBonePos		= pNPCUnit:GetBonePos_LUA( "Bone_Lhand" )
		pParticle = pMinorParticle:GameUnitCreateSequence_LUA( pNPCUnit, "Flare_Nasod_DR_Combo01", vBonePos, D3DXVECTOR2(-1,-1), D3DXVECTOR2(-1,-1) )
		if pParticle ~= nil then
			pParticle:SetAddRotate( vRotateDegree )
			pParticle:SetAxisAngle( vRotateDegree )	
			pNPCUnit:SetMinorParticle_LUA( 2, pParticle:GetHandle() ) 
		end
		
	
		vBonePos = pNPCUnit:GetBonePos_LUA( "Bone_Rhand" )
		vZVector = pNPCUnit:GetZVector()
		vBonePos = MovePos( vBonePos, vZVector, -100 )		
		pParticle = pMinorParticle:GameUnitCreateSequence_LUA( pNPCUnit, "Flare_Nasod_DR_Combo01", vBonePos, D3DXVECTOR2(-1,-1), D3DXVECTOR2(-1,-1) )
		if pParticle ~= nil then
			pParticle:SetAddRotate( vRotateDegree )
			pParticle:SetAxisAngle( vRotateDegree )	
			pNPCUnit:SetMinorParticle_LUA( 3, pParticle:GetHandle() ) 
		end
	
	end
	
	
	
	
	
	-- particle framemove
	pParticle = pNPCUnit:GetMinorParticle_LUA( 0 ) 
	if nil ~= pParticle then 
	
		if pMinorParticle:IsLiveInstance( pParticle ) == true then 
			vBonePos		= pNPCUnit:GetBonePos_LUA( "Dummy01" )
			pParticle:SetPosition( vBonePos )		
		else 
			pNPCUnit:ClearMinorParticle_LUA( 0 )
		end
	
	end
	
	
	pParticle = pNPCUnit:GetMinorParticle_LUA( 1 ) 
	if nil ~= pParticle then 
	
		if pMinorParticle:IsLiveInstance( pParticle ) == true then 
			vBonePos		= pNPCUnit:GetBonePos_LUA( "Bone_Rhand" )
			pParticle:SetPosition( vBonePos )		
		else 
			pNPCUnit:ClearMinorParticle_LUA( 1 )
		end
	
	end
	
	
	pParticle = pNPCUnit:GetMinorParticle_LUA( 2 ) 
	if nil ~= pParticle then 
	
		if pMinorParticle:IsLiveInstance( pParticle ) == true then 
			vBonePos		= pNPCUnit:GetBonePos_LUA( "Bone_Lhand" )
			pParticle:SetPosition( vBonePos )		
		else 
			pNPCUnit:ClearMinorParticle_LUA( 2 )
		end
	
	end
	
	pParticle = pNPCUnit:GetMinorParticle_LUA( 3 ) 
	if nil ~= pParticle then 
	
		if pMinorParticle:IsLiveInstance( pParticle ) == true then 
			vBonePos		= pNPCUnit:GetBonePos_LUA( "Bone_Rhand" )
			pParticle:SetPosition( vBonePos )		
		else 
			pNPCUnit:ClearMinorParticle_LUA( 3 )
		end
	
	end
	
	
end


------------------------------------------------------------------------------
function NASOD_DRILLER_CANNON_WAIT_START_EFFECT_STATE_END( pKTDXApp, pX2Game, pNPCUnit )

	pMinorParticle = pX2Game:GetMinorParticle()

	for i=0, 3 do

		pParticle = pNPCUnit:GetMinorParticle_LUA( i ) 	
		if pParticle ~= nil then
			pMinorParticle:DestroyInstance( pParticle )
			pNPCUnit:ClearMinorParticle_LUA( i )
		end

	end

end


----------------------------------------------------------
function NASOD_DRILLER_CANNON_START_CAMERA_MOVE( pKTDXApp, pX2Game, pNPCUnit )

	pos = pNPCUnit:GetBonePos_LUA("Bip01_Head")	
	camera = pX2Game:GetX2Camera()
	camera:PartsLookDirectCamera_LUA( pNPCUnit, pos, D3DXVECTOR3( 500, -50, -20 ), D3DXVECTOR2( 0,0 ) )

   
end


------------------------------------------------------------------------------
function MovePos( pos, dirvector, dist )
	
	pos.x = pos.x + dist * dirvector.x
	pos.y = pos.y + dist * dirvector.y
	pos.z = pos.z + dist * dirvector.z
	
	return pos
	
end

