-- lua header. UTF-8 인코딩 인식을 위해 이 줄은 지우지 마세요.



INIT_SYSTEM = 
{
	UNIT_WIDTH		= 200.0,
	UNIT_HEIGHT		= 228.0,
	UNIT_LAYER		= X2_LAYER["XL_UNIT_0"],
	
	UNIT_SCALE		= 1.05,
}


INIT_DEVICE = 
{
	READY_TEXTURE = 
	{		
	    "Ice_Particle01.dds", 
	    "smoke02.dds",
	    "Spark01_BCMI.dds",
	    "Particle_Flame01.tga",	
	    "FireWave01.tga",  
	    "MeteoStone01.tga",
	    "MeteoStone01_Mesh.tga",
	    "ColorBallFire.tga",
	    "Lightning02.tga",    
	      
	},
	
	READY_SOUND = 
	{  
        "Nasod_Element_Slash1.ogg",
        "Nasod_Element_Slash2.ogg",
--        "Nasod_Element_FastWalk.ogg",
		"Nasod_Element_HitGround.ogg",
        "Nasod_Element_JumpLanding1.ogg",
--        "Nasod_Element_JumpLanding2.ogg",
        "Nasod_Element_JumpUp.ogg",
        "Nasod_Element_StandUpAttack.ogg",
        "Nasod_Element_IceWave1.ogg",
        "Nasod_Element_Wave.ogg",
        "Nasod_Element_WaitStart1.ogg",
		"Nasod_Element_Teleport.ogg",
		
        "Nasod_Element_ReadyStorm.ogg",
        "Nasod_Element_BurstStorm.ogg",
		"Nasod_Element_SmallMeteo1.ogg",
--		"Nasod_Element_SmallMeteo2.ogg",
        "Nasod_Element_BarrierHit.ogg",
		
	},
	
		
	READY_XMESH = 
	{
	    "Lightning03.Y",
	    "Lightning02.Y",
	    "Particle_Motion_Flame01.Y",
	    "FireWave01.Y",
	},
	
	READY_XSKIN_MESH = 
	{
	    "MeteoStone01.X",
	    "MeteoStone02.X",
	    "Nasod_Element_Fire_PerfectStorm01.X",
	    "DummyAttackBox_50x50x50.x",
	},
}

INIT_MOTION = 
{
	MOTION_FILE_NAME		= "Motion_Nasod_Element_Fire.x",
}

INIT_PHYSIC = 
{
	RELOAD_ACCEL		= 2000,
	G_ACCEL				= 4000,
	MAX_G_SPEED			= -2000,
	
	WALK_SPEED			= 750,
	RUN_SPEED			= 800,
	JUMP_SPEED			= 1500,
	DASH_JUMP_SPEED		= 1800,
}


INIT_COMPONENT = 
{
	MAX_HP				= 20000,
	MP_CHANGE_RATE		= 3,
	MP_CHARGE_RATE		= 1200,
	
	
	
	SHADOW_SIZE			= 200,
	SHADOW_FILE_NAME	= "shadow.dds",
	
	SMALL_HP_BAR_BLUE	= "Small_HP_bar_Blue.TGA",
	SMALL_HP_BAR_RED	= "Small_HP_bar_Red.TGA",
	SMALL_HP_BAR_YELLOW = "Small_HP_bar_Yellow.TGA",
	
	--DRAW_SMALL_MP_BAR	= TRUE,
	
	QUESTION_MARK_SEQ		= "QuestionMarkNPC",
	EXCLAMATION_MARK_SEQ	= "ExclamationMarkNPC",
	--MIND_FLAG_HEIGHT		= 230,
	
	HYPER_MODE_COUNT	= 0,
	MAX_HYPER_MODE_TIME	= 30,
	
	RAGE_COUNT_MAX		= 30,
	RAGE_TIME_MAX		= 3,

	HITTED_TYPE			= HITTED_TYPE["HTD_METAL"],
	
	FALL_DOWN			= TRUE,
		
	BOSS_GAGE_FACE_TEX			= "DLG_BossState.tga",
	BOSS_GAGE_FACE_TEX_PIECE	= "NUI_NASOD_ELEMENT_FIRE",	
--	BOSS_NAME_TEX				= "HQ_BOSS_NAME_NASOD_ELEMENT.dds",
	
	
}

INIT_STATE = 
{
	{ STATE_NAME = "NASOD_ELEMENT_FIRE_WIN",						},																	
	{ STATE_NAME = "NASOD_ELEMENT_FIRE_START",				        LUA_CAMERA_MOVE_FUNC = "NASOD_ELEMENT_FIRE_START_CAMERA_MOVE",
	                                                                LUA_STATE_START_FUNC = "NASOD_ELEMENT_FIRE_START_STATE_START",
	                                                                LUA_FRAME_MOVE_FUNC = "NASOD_ELEMENT_FIRE_START_FRAME_MOVE",			},
	
	
	{ STATE_NAME = "NASOD_ELEMENT_FIRE_WAIT",						},
	{ STATE_NAME = "NASOD_ELEMENT_FIRE_WAIT_START",					LUA_STATE_START_FUNC = "NASOD_ELEMENT_FIRE_WAIT_START_STATE_START",
	                                                                LUA_FRAME_MOVE_FUNC = "NASOD_ELEMENT_FIRE_WAIT_START_FRAME_MOVE",		},
		
	{ STATE_NAME = "NASOD_ELEMENT_FIRE_WALK",						LUA_STATE_END_FUNC = "NASOD_ELEMENT_FIRE_WALK_STATE_END"						},
	{ STATE_NAME = "NASOD_ELEMENT_FIRE_TELEPORT",					LUA_STATE_START_FUNC = "NASOD_ELEMENT_FIRE_TELEPORT_STATE_START",
	                                                                LUA_FRAME_MOVE_FUNC = "NASOD_ELEMENT_FIRE_TELEPORT_FRAME_MOVE"					},

	{ STATE_NAME = "NASOD_ELEMENT_FIRE_JUMP_UP",					},
	{ STATE_NAME = "NASOD_ELEMENT_FIRE_JUMP_DOWN",					LUA_STATE_END_FUNC = "NASOD_ELEMENT_FIRE_JUMP_DOWN_STATE_END"					},
	{ STATE_NAME = "NASOD_ELEMENT_FIRE_JUMP_UP_DIR",				},
	{ STATE_NAME = "NASOD_ELEMENT_FIRE_JUMP_DOWN_DIR",				LUA_STATE_END_FUNC = "NASOD_ELEMENT_FIRE_JUMP_DOWN_DIR_STATE_END"				},
	{ STATE_NAME = "NASOD_ELEMENT_FIRE_JUMP_LANDING",				},
	
	{ STATE_NAME = "NASOD_ELEMENT_FIRE_JUMP_ATTACK",				},
	{ STATE_NAME = "NASOD_ELEMENT_FIRE_JUMP_FOR_ATTACK",			},	
	{ STATE_NAME = "NASOD_ELEMENT_FIRE_ATTACK_COMBO",				LUA_FRAME_MOVE_FUNC     = "NASOD_ELEMENT_FIRE_ATTACK_COMBO_FRAME_MOVE",
	                                                                STATE_COOL_TIME = 3,        },	
	{ STATE_NAME = "NASOD_ELEMENT_FIRE_FLAME_ATTACK",				LUA_FRAME_MOVE_FUNC     = "NASOD_ELEMENT_FIRE_FLAME_ATTACK_FRAME_MOVE",  
	                                                                LUA_STATE_END_FUNC      = "NASOD_ELEMENT_FIRE_FLAME_ATTACK_STATE_END",
	                                                                STATE_COOL_TIME = 5,        },
    { STATE_NAME = "NASOD_ELEMENT_FIRE_SMALLMETEO1",				LUA_STATE_START_FUNC    = "NASOD_ELEMENT_FIRE_SMALLMETE_STATE_START",
                                                                    LUA_FRAME_MOVE_FUNC     = "NASOD_ELEMENT_FIRE_SMALLMETEO1_FRAME_MOVE",                                                                    
                                                                    STATE_COOL_TIME = 7,       },	    
                                                                    
    --{ STATE_NAME = "NASOD_ELEMENT_FIRE_FRAMEWAVE",				    LUA_FRAME_MOVE_FUNC     = "NASOD_ELEMENT_FIRE_FRAMEWAVE_FRAME_MOVE",   },   
    { STATE_NAME = "NASOD_ELEMENT_FIRE_PERFECTSTORM",				LUA_FRAME_MOVE_FUNC     = "NASOD_ELEMENT_FIRE_PERFECTSTORM_FRAME_MOVE",   },
	
	--리액션 관련
	{ STATE_NAME = "NASOD_ELEMENT_FIRE_DAMAGE_SMALL",				LUA_FRAME_MOVE_FUNC = "NASOD_ELEMENT_FIRE_DAMAGE_SMALL_FRAME_MOVE"				},
	{ STATE_NAME = "NASOD_ELEMENT_FIRE_DAMAGE_BIG",					LUA_FRAME_MOVE_FUNC = "NASOD_ELEMENT_FIRE_DAMAGE_BIG_FRAME_MOVE"				},
	{ STATE_NAME = "NASOD_ELEMENT_FIRE_DAMAGE_DOWN_FRONT",			LUA_FRAME_MOVE_FUNC = "NASOD_ELEMENT_FIRE_DAMAGE_DOWN_FRONT_FRAME_MOVE"			},
	{ STATE_NAME = "NASOD_ELEMENT_FIRE_DAMAGE_DOWN_BACK",			LUA_FRAME_MOVE_FUNC = "NASOD_ELEMENT_FIRE_DAMAGE_DOWN_BACK_FRAME_MOVE"			},
	{ STATE_NAME = "NASOD_ELEMENT_FIRE_DAMAGE_FLY_FRONT",			},
	{ STATE_NAME = "NASOD_ELEMENT_FIRE_DAMAGE_FLY_BACK",			},
	{ STATE_NAME = "NASOD_ELEMENT_FIRE_DAMAGE_AIR",					},
	{ STATE_NAME = "NASOD_ELEMENT_FIRE_DAMAGE_AIR_DOWN",			},
	{ STATE_NAME = "NASOD_ELEMENT_FIRE_DAMAGE_AIR_UP",				},
	{ STATE_NAME = "NASOD_ELEMENT_FIRE_DAMAGE_AIR_FALL",			},	
	{ STATE_NAME = "NASOD_ELEMENT_FIRE_DAMAGE_AIR_DOWN_LANDING",	LUA_FRAME_MOVE_FUNC = "NASOD_ELEMENT_FIRE_DAMAGE_AIR_DOWN_LANDING_FRAME_MOVE"	},
	{ STATE_NAME = "NASOD_ELEMENT_FIRE_STAND_UP_FRONT",				},
	{ STATE_NAME = "NASOD_ELEMENT_FIRE_STAND_UP_BACK",				},
	{ STATE_NAME = "NASOD_ELEMENT_FIRE_STAND_UP_ATTACK_FRONT",		LUA_FRAME_MOVE_FUNC = "NASOD_ELEMENT_FIRE_STAND_UP_ATTACK_FRONT_FRAME_MOVE"		},
	{ STATE_NAME = "NASOD_ELEMENT_FIRE_STAND_UP_ATTACK_BACK",		LUA_FRAME_MOVE_FUNC = "NASOD_ELEMENT_FIRE_STAND_UP_ATTACK_BACK_FRAME_MOVE"		},
	
	{ STATE_NAME = "NASOD_ELEMENT_FIRE_DYING_LAND_FRONT",			LUA_STATE_START_FUNC = "NASOD_ELEMENT_FIRE_DYING_LAND_STATE_START",},
	{ STATE_NAME = "NASOD_ELEMENT_FIRE_DYING_LAND_BACK",			LUA_STATE_START_FUNC = "NASOD_ELEMENT_FIRE_DYING_LAND_STATE_START",},
	{ STATE_NAME = "NASOD_ELEMENT_FIRE_DYING_SKY",					LUA_STATE_START_FUNC = "NASOD_ELEMENT_FIRE_DYING_LAND_STATE_START",},
	
	
	
	START_STATE					= "NASOD_ELEMENT_FIRE_START",
	WAIT_STATE					= "NASOD_ELEMENT_FIRE_WAIT",
	
	SMALL_DAMAGE_LAND_FRONT		= "NASOD_ELEMENT_FIRE_DAMAGE_SMALL",
	SMALL_DAMAGE_LAND_BACK		= "NASOD_ELEMENT_FIRE_DAMAGE_SMALL",
	BIG_DAMAGE_LAND_FRONT		= "NASOD_ELEMENT_FIRE_DAMAGE_BIG",
	BIG_DAMAGE_LAND_BACK		= "NASOD_ELEMENT_FIRE_DAMAGE_BIG",
	DOWN_DAMAGE_LAND_FRONT		= "NASOD_ELEMENT_FIRE_DAMAGE_DOWN_FRONT",
	DOWN_DAMAGE_LAND_BACK		= "NASOD_ELEMENT_FIRE_DAMAGE_DOWN_BACK",
	FLY_DAMAGE_FRONT			= "NASOD_ELEMENT_FIRE_DAMAGE_FLY_FRONT",
	FLY_DAMAGE_BACK				= "NASOD_ELEMENT_FIRE_DAMAGE_FLY_BACK",
	SMALL_DAMAGE_AIR			= "NASOD_ELEMENT_FIRE_DAMAGE_AIR",	
	BIG_DAMAGE_AIR				= "NASOD_ELEMENT_FIRE_DAMAGE_AIR",
	DOWN_DAMAGE_AIR				= "NASOD_ELEMENT_FIRE_DAMAGE_AIR_DOWN",
	DOWN_DAMAGE_AIR_LANDING				= "NASOD_ELEMENT_FIRE_DAMAGE_AIR_DOWN_LANDING",
	UP_DAMAGE					= "NASOD_ELEMENT_FIRE_DAMAGE_AIR_UP",
	DAMAGE_REVENGE				= "NASOD_ELEMENT_FIRE_DAMAGE_SMALL",
	
	DAMAGE_EXTRA_STATES         = {"NASOD_ELEMENT_FIRE_DAMAGE_AIR_FALL","NASOD_ELEMENT_FIRE_STAND_UP_FRONT","NASOD_ELEMENT_FIRE_STAND_UP_BACK",
	"NASOD_ELEMENT_FIRE_STAND_UP_ATTACK_FRONT","NASOD_ELEMENT_FIRE_STAND_UP_ATTACK_BACK","NASOD_ELEMENT_FIRE_JUMP_DOWN","NASOD_ELEMENT_FIRE_JUMP_LANDING",},	
	
	DYING_LAND_FRONT			= "NASOD_ELEMENT_FIRE_DYING_LAND_FRONT",
	DYING_LAND_BACK				= "NASOD_ELEMENT_FIRE_DYING_LAND_BACK",
	DYING_SKY					= "NASOD_ELEMENT_FIRE_DYING_SKY",

	--REVENGE_ATTACK				= "NASOD_ELEMENT_FIRE_REVENGE_ATTACK",	
	
	--COMMON_FRAME_FUNC           = "NASOD_ELEMENT_FIRE_COMMON_FRAME_MOVE",
}



INIT_AI = 
{
	TARGET = 
	{
		TARGET_PRIORITY 			= TARGET_PRIORITY["TP_LOW_HP_FIRST"],
		TARGET_INTERVAL				= 2,		-- sec
		TARGET_NEAR_RANGE			= 1000,		-- 이 거리보다 가까우면 TARGET_SUCCESS_RATE에 관계없이 무조건 타게팅된다
		TARGET_RANGE				= 1700,		-- cm
		TARGET_LOST_RANGE			= 1800,		-- cm
		TARGET_SUCCESS_RATE			= 100,  --80,		-- %
		ATTACK_TARGET_RATE			= 100, -- 100,		-- 나를 공격한 유닛을 타게팅할 확률
		PRESERVE_LAST_TARGET_RATE	= 100, -- 50,		-- 이전에 타게팅된 유닛을 계속 타게팅할 확률
	},

	CHASE_MOVE = 
	{		
		MOVE_SPLIT_RANGE	= 600,
		DEST_GAP			= 400,	-- 목적지에서 이 거리 안에 있으면 도착했다고 판단한다
		MOVE_GAP			= 210,
		
		DIR_CHANGE_INTERVAL = 0.7,
		
		WALK_INTERVAL		= 3,
		NEAR_WALK_RATE		= 100,   --  70,
		FAR_WALK_RATE		= 100,   -- 30,
		
		JUMP_INTERVAL		= 5,
		UP_JUMP_RATE		= 100, -- 40,
		UP_DOWN_RATE		= 20,
		DOWN_JUMP_RATE		= 100,    --  20,
		DOWN_DOWN_RATE		= 40,
		
		LINE_END_RANGE		= 80,	-- cm
	},	
	
	PATROL_MOVE = 	
	{
		PATROL_BEGIN_RATE		= 100, --50,		
		PATROL_RANGE			= 200,
		PATROL_COOL_TIME		= 2,
		ONLY_THIS_LINE_GROUP	= TRUE,
	},
	
	ESCAPE_MOVE = 
	{		
		MOVE_SPLIT_RANGE	= 500,	-- cm
		ESCAPE_GAP			= 600,	-- 이 거리 보다 멀어지면 도망 성공
		
		WALK_INTERVAL		= 1.5,	-- 초
		NEAR_WALK_RATE		= 100,   --  10,
		FAR_WALK_RATE		= 100,   -- 10,
		
		JUMP_INTERVAL		= 10,
		UP_JUMP_RATE		= 100, -- 30,
		UP_DOWN_RATE		= 30,
		DOWN_JUMP_RATE		= 100,    --  30,
		DOWN_DOWN_RATE		= 30,
		
		LINE_END_RANGE		= 80,	-- cm
	},

}


NASOD_ELEMENT_FIRE_WIN = 
{
	ANIM_NAME					= "Win",
	PLAY_TYPE					= XSKIN_ANIM_PLAYTYPE["XAP_ONE_WAIT"],
	TRANSITION					= TRUE,
	
	CAN_PUSH_UNIT				= TRUE,
	CAN_PASS_UNIT				= FALSE,	
	
	INVINCIBLE					= { 0, 100, },


	SPEED_X						= 0,
	SPEED_Y						= 0,

	RIGHT						= TRUE,
	
	IMMADIATE_PACKET_SEND		= TRUE,
}



NASOD_ELEMENT_FIRE_START = 
{
	ANIM_NAME					= "WaitStart",
	PLAY_TYPE					= XSKIN_ANIM_PLAYTYPE["XAP_ONE_WAIT"],
	TRANSITION					= FALSE,
	
	CAN_PUSH_UNIT				= TRUE,
	CAN_PASS_UNIT				= FALSE,
	IMMADIATE_PACKET_SEND		= TRUE,	
	
    SOUND_PLAY0			= { 1.336, "Nasod_Element_WaitStart1.ogg" },
    SOUND_PLAY1			= { 2.861, "Nasod_Element_JumpLanding1.ogg" },


    PARTICLE_SEQ = 
	{
		--Major, time, Name, weaponBonePos, Pos, StateEndDelete, bTrace, posx, posy, posz, bApplyUnitRotation, rotx, roty, rotz,			
		{ FALSE, 0.3, "Nasod_Element_Fire_WaitStart01", FALSE, "ATTACK_SPHERE2_Rhand", TRUE, TRUE, 0, 0, 50, },
		{ FALSE, 0.3, "Nasod_Element_Fire_WaitStart01", FALSE, "ATTACK_SPHERE4_Lhand", TRUE, TRUE, 0, 0, 50, },
		{ FALSE, 0.6, "Nasod_Element_Fire_WaitStart01", FALSE, "COLLISION_SPHERE2_Upbody", TRUE, TRUE, 25, 0, 50, },
		{ FALSE, 1.2, "Fire_Particle_Nasod_Element_Fire_WaitStart02", FALSE, "ATTACK_SPHERE2_Rhand", TRUE, TRUE, 0, 0, 0, },
		{ FALSE, 1.2, "Fire_Particle_Nasod_Element_Fire_WaitStart02", FALSE, "ATTACK_SPHERE4_Lhand", TRUE, TRUE, 0, 0, 0, },
		
	},	
	
	EVENT_PROCESS = 
	{		
		{ STATE_CHANGE_TYPE["SCT_CONDITION_TABLE"],		"NASOD_ELEMENT_FIRE_WAIT",		"CT_NASOD_ELEMENT_FIRE_WAIT"				},
	},
	
	CT_NASOD_ELEMENT_FIRE_WAIT = 
	{
		STATE_TIME_OVER			= 3,
	},
}


NASOD_ELEMENT_FIRE_WAIT = 
{
	ANIM_NAME					= "Wait",
	PLAY_TYPE					= XSKIN_ANIM_PLAYTYPE["XAP_LOOP"],
	TRANSITION					= TRUE,
	
	CAN_PUSH_UNIT				= TRUE,
	CAN_PASS_UNIT				= FALSE,	
	
	SPEED_X						= 0,
	SPEED_Y						= 0,
	
	PASSIVE_SPEED_X				= 0,	
	
	IMMADIATE_PACKET_SEND		= TRUE,
	EVENT_INTERVAL_TIME0		= 2,
	
	EVENT_PROCESS = 
	{	
		{ STATE_CHANGE_TYPE["SCT_FOOT_ON_LINE_FALSE_DOWN"],	"NASOD_ELEMENT_FIRE_JUMP_DOWN",					},	
		{ STATE_CHANGE_TYPE["SCT_CONDITION_FUNCTION"],		"NASOD_ELEMENT_FIRE_WIN",						"CF_NASOD_ELEMENT_FIRE_WIN",	},			
		        		
		{ STATE_CHANGE_TYPE["SCT_CONDITION_TABLE"],			"NASOD_ELEMENT_FIRE_ATTACK_COMBO",			    "CT_NASOD_ELEMENT_FIRE_ATTACK_COMBO",	},
		{ STATE_CHANGE_TYPE["SCT_CONDITION_TABLE"],			"NASOD_ELEMENT_FIRE_JUMP_FOR_ATTACK",			"CT_NASOD_ELEMENT_FIRE_JUMP_FOR_ATTACK",	},
		{ STATE_CHANGE_TYPE["SCT_CONDITION_TABLE"],			"NASOD_ELEMENT_FIRE_FLAME_ATTACK",			    "CT_NASOD_ELEMENT_FIRE_FLAME_ATTACK",	},		
		
		--{ STATE_CHANGE_TYPE["SCT_CONDITION_TABLE"],			"NASOD_ELEMENT_FIRE_FRAMEWAVE",		            "CT_NASOD_ELEMENT_FIRE_FRAMEWAVE",	},
		{ STATE_CHANGE_TYPE["SCT_CONDITION_TABLE"],			"NASOD_ELEMENT_FIRE_PERFECTSTORM",		            "CT_NASOD_ELEMENT_FIRE_PERFECTSTORM",	},
        { STATE_CHANGE_TYPE["SCT_CONDITION_TABLE"],			"NASOD_ELEMENT_FIRE_SMALLMETEO1",			    "CT_NASOD_ELEMENT_FIRE_SMALLMETEO1",	},				
        
						
		{ STATE_CHANGE_TYPE["SCT_AI_WALK"],					"NASOD_ELEMENT_FIRE_WALK",						},
		{ STATE_CHANGE_TYPE["SCT_AI_DASH"],					"NASOD_ELEMENT_FIRE_WALK",						},
		{ STATE_CHANGE_TYPE["SCT_AI_JUMP"],					"NASOD_ELEMENT_FIRE_JUMP_UP",					},
		{ STATE_CHANGE_TYPE["SCT_AI_JUMP_DIR"],				"NASOD_ELEMENT_FIRE_JUMP_UP_DIR",				},
		{ STATE_CHANGE_TYPE["SCT_AI_DOWN"],					"NASOD_ELEMENT_FIRE_JUMP_DOWN",					},
		{ STATE_CHANGE_TYPE["SCT_AI_DOWN_DIR"],				"NASOD_ELEMENT_FIRE_JUMP_DOWN_DIR",				},
	},
	
	
	
	CT_NASOD_ELEMENT_FIRE_ATTACK_COMBO = 
	{
		EVENT_INTERVAL_ID			= 0,
		DISTANCE_TO_TARGET_NEAR		= 500,
		RATE						= 50,
	},
	
	CT_NASOD_ELEMENT_FIRE_JUMP_FOR_ATTACK = 
	{
		EVENT_INTERVAL_ID			= 0,
		DISTANCE_TO_TARGET_NEAR		= 600,
		RATE						= 20,
	},
	
	CT_NASOD_ELEMENT_FIRE_FLAME_ATTACK = 
	{
		EVENT_INTERVAL_ID			= 0,
		DISTANCE_TO_TARGET_NEAR		= 800,
		RATE						= 40,
	},
	
	CT_NASOD_ELEMENT_FIRE_SMALLMETEO1 = 
	{
		EVENT_INTERVAL_ID			= 0,
		DISTANCE_TO_TARGET_NEAR		= 1300,
		RATE						= 30,
	},
	

	CT_NASOD_ELEMENT_FIRE_FRAMEWAVE =
	{
		EVENT_INTERVAL_ID			= 0,
		DISTANCE_TO_TARGET_NEAR		= 2000,
		MY_MP_MORE_THAN_PERCENT		= 100,
		RATE						= 80,
	},

	CT_NASOD_ELEMENT_FIRE_PERFECTSTORM =
    {
        EVENT_INTERVAL_ID			= 0,
		DISTANCE_TO_TARGET_NEAR		= 800,
		--MY_MP_MORE_THAN_PERCENT		= 100,
		RATE	                    = 50,
    },
	
    TALK_BOX =
	{
		EVENT_INTERVAL_ID			= 0,
 		{ RATE = 10,		MESSAGE = STR_ID_1469 },
 	},
		
}


NASOD_ELEMENT_FIRE_WAIT_START = 
{
	ANIM_NAME					= "WaitStart",
	PLAY_TYPE					= XSKIN_ANIM_PLAYTYPE["XAP_ONE_WAIT"],
	TRANSITION					= FALSE,
	
	CAN_PUSH_UNIT				= TRUE,
	CAN_PASS_UNIT				= FALSE,
	
	RIGHT						= TRUE,
	
	INVINCIBLE					= { 0, 100, },
	
	IMMADIATE_PACKET_SEND		= TRUE,	

    SOUND_PLAY0			= { 2.861, "Nasod_Element_JumpLanding1.ogg" },

	EVENT_PROCESS = 
	{		
		{ STATE_CHANGE_TYPE["SCT_FOOT_ON_LINE_FALSE_DOWN"],		"NASOD_ELEMENT_FIRE_JUMP_DOWN",			},
		{ STATE_CHANGE_TYPE["SCT_MOTION_END"],					"NASOD_ELEMENT_FIRE_WAIT",					},
	},
	
	PARTICLE_SEQ = 
	{
		--Major, time, Name, weaponBonePos, Pos, StateEndDelete, bTrace, posx, posy, posz, bApplyUnitRotation, rotx, roty, rotz,			
		{ FALSE, 0.11, "RespawnLanding_P01", FALSE, "", FALSE, FALSE, 0, 0, 0, FALSE, 0, 0, 0, 2.0, 2.0, 2.0},
		{ FALSE, 0.11, "RespawnLanding_P02", FALSE, "", FALSE, FALSE, 0, 0, 0, FALSE, 0, 0, 0, 2.0, 2.0, 2.0},
		{ FALSE, 0.11, "RespawnLanding_P03", FALSE, "", FALSE, FALSE, 0, 0, 0, FALSE, 0, 0, 0, 2.0, 2.0, 2.0},
		{ FALSE, 0.21, "RespawnLanding_P04", FALSE, "", FALSE, FALSE, 0, 50, 0, FALSE, 0, 0, 0, 2.0, 2.0, 2.0},
		{ FALSE, 0.24, "RespawnLanding_P04", FALSE, "", FALSE, FALSE, 0, 100, 0, FALSE, 0, 0, 0, 2.0, 2.0, 2.0},
		{ FALSE, 0.37, "RespawnLanding_P04", FALSE, "", FALSE, FALSE, 0, 200, 0, FALSE, 0, 0, 0, 2.0, 2.0, 2.0},
		{ FALSE, 0.50, "RespawnLanding_P04", FALSE, "", FALSE, FALSE, 0, 300, 0, FALSE, 0, 0, 0, 2.0, 2.0, 2.0},
		{ FALSE, 0.63, "RespawnLanding_P04", FALSE, "", FALSE, FALSE, 0, 450, 0, FALSE, 0, 0, 0, 2.0, 2.0, 2.0},
	},	
	
	TALK_BOX =
	{
		EVENT_INTERVAL_ID			= 0,
 		{ RATE = 30, MESSAGE = STR_ID_2567 },
 	},

}

NASOD_ELEMENT_FIRE_TELEPORT = 
{
	ANIM_NAME					= "JumpUp",
	PLAY_TYPE					= XSKIN_ANIM_PLAYTYPE["XAP_ONE_WAIT"],
	TRANSITION					= TRUE,
	
	--CAN_PUSH_UNIT				= TRUE,
	--CAN_PASS_UNIT				= FALSE,	
	
	INVINCIBLE					= { 0, 100, },

--    SOUND_PLAY0			= { 0.448, "AirShip_SwordMan_Slash1.ogg" },
--    SOUND_PLAY1			= { 0.521, "AirShip_SwordMan_WinShout.ogg" },

	SPEED_X						= 0,
	SPEED_Y						= 0,

	RIGHT						= TRUE,
	
	IMMADIATE_PACKET_SEND		= TRUE,
	
	EVENT_PROCESS = 
	{
	    { STATE_CHANGE_TYPE["SCT_MOTION_END"],					"NASOD_ELEMENT_FIRE_WAIT_START",					},
	},
	
	PARTICLE_SEQ = 
	{
		--Major, time, Name, weaponBonePos, Pos, StateEndDelete, bTrace, posx, posy, posz, bApplyUnitRotation, rotx, roty, rotz,			
		{ FALSE, 0.11, "RespawnLanding_P01", FALSE, "", FALSE, FALSE, 0, 0, 0, FALSE, 0, 0, 0, 2.0, 2.0, 2.0},
		{ FALSE, 0.11, "RespawnLanding_P02", FALSE, "", FALSE, FALSE, 0, 0, 0, FALSE, 0, 0, 0, 2.0, 2.0, 2.0},
		{ FALSE, 0.11, "RespawnLanding_P03", FALSE, "", FALSE, FALSE, 0, 0, 0, FALSE, 0, 0, 0, 2.0, 2.0, 2.0},
		{ FALSE, 0.21, "RespawnLanding_P04", FALSE, "", FALSE, FALSE, 0, 50, 0, FALSE, 0, 0, 0, 2.0, 2.0, 2.0},
		{ FALSE, 0.24, "RespawnLanding_P04", FALSE, "", FALSE, FALSE, 0, 100, 0, FALSE, 0, 0, 0, 2.0, 2.0, 2.0},
		{ FALSE, 0.37, "RespawnLanding_P04", FALSE, "", FALSE, FALSE, 0, 200, 0, FALSE, 0, 0, 0, 2.0, 2.0, 2.0},
		{ FALSE, 0.50, "RespawnLanding_P04", FALSE, "", FALSE, FALSE, 0, 300, 0, FALSE, 0, 0, 0, 2.0, 2.0, 2.0},
		{ FALSE, 0.63, "RespawnLanding_P04", FALSE, "", FALSE, FALSE, 0, 450, 0, FALSE, 0, 0, 0, 2.0, 2.0, 2.0},
	},	
}

NASOD_ELEMENT_FIRE_WALK = 
{
	ANIM_NAME					= "FastWalk",
	PLAY_TYPE					= XSKIN_ANIM_PLAYTYPE["XAP_LOOP"],
	TRANSITION					= TRUE,
	
	CAN_PUSH_UNIT				= TRUE,
	CAN_PASS_UNIT				= FALSE,

	
	PASSIVE_SPEED_X				= INIT_PHYSIC["WALK_SPEED"],
	
	ALLOW_DIR_CHANGE			= TRUE,
	IMMADIATE_PACKET_SEND		= TRUE,
	
	EVENT_INTERVAL_TIME0		= 2,
	EVENT_INTERVAL_TIME1		= 3,
	
	EVENT_PROCESS = 
	{		
		{ STATE_CHANGE_TYPE["SCT_FOOT_ON_LINE_FALSE_DOWN"],	"NASOD_ELEMENT_FIRE_JUMP_DOWN_DIR",			},
		{ STATE_CHANGE_TYPE["SCT_CONDITION_FUNCTION"],		"NASOD_ELEMENT_FIRE_WIN",						"CF_NASOD_ELEMENT_FIRE_WIN",	},	
        
		{ STATE_CHANGE_TYPE["SCT_CONDITION_TABLE"],			"NASOD_ELEMENT_FIRE_ATTACK_COMBO",				"CT_NASOD_ELEMENT_FIRE_ATTACK_COMBO",		},
		{ STATE_CHANGE_TYPE["SCT_CONDITION_TABLE"],			"NASOD_ELEMENT_FIRE_JUMP_FOR_ATTACK",			"CT_NASOD_ELEMENT_FIRE_JUMP_FOR_ATTACK",	},
		{ STATE_CHANGE_TYPE["SCT_CONDITION_TABLE"],			"NASOD_ELEMENT_FIRE_FLAME_ATTACK",			    "CT_NASOD_ELEMENT_FIRE_FLAME_ATTACK",	},
		
		--{ STATE_CHANGE_TYPE["SCT_CONDITION_TABLE"],			"NASOD_ELEMENT_FIRE_FRAMEWAVE",		            "CT_NASOD_ELEMENT_FIRE_FRAMEWAVE",	},			
		{ STATE_CHANGE_TYPE["SCT_CONDITION_TABLE"],			"NASOD_ELEMENT_FIRE_PERFECTSTORM",		            "CT_NASOD_ELEMENT_FIRE_PERFECTSTORM",	},			--
		{ STATE_CHANGE_TYPE["SCT_CONDITION_TABLE"],			"NASOD_ELEMENT_FIRE_SMALLMETEO1",			    "CT_NASOD_ELEMENT_FIRE_SMALLMETEO1",	},				
		
		{ STATE_CHANGE_TYPE["SCT_AI_WAIT"],					"NASOD_ELEMENT_FIRE_WAIT",						},
		{ STATE_CHANGE_TYPE["SCT_AI_DASH"],					"NASOD_ELEMENT_FIRE_WALK",						},
		{ STATE_CHANGE_TYPE["SCT_AI_JUMP"],					"NASOD_ELEMENT_FIRE_JUMP_UP",					},
		{ STATE_CHANGE_TYPE["SCT_AI_JUMP_DIR"],				"NASOD_ELEMENT_FIRE_JUMP_UP_DIR",				},
		{ STATE_CHANGE_TYPE["SCT_AI_DOWN"],					"NASOD_ELEMENT_FIRE_JUMP_DOWN",				},
		{ STATE_CHANGE_TYPE["SCT_AI_DOWN_DIR"],				"NASOD_ELEMENT_FIRE_JUMP_DOWN_DIR",			},
	},
	
	
	CT_NASOD_ELEMENT_FIRE_ATTACK_COMBO = 
	{
		EVENT_INTERVAL_ID			= 0,
		DISTANCE_TO_TARGET_NEAR		= 500,
		RATE						= 50,
	},
		
	CT_NASOD_ELEMENT_FIRE_JUMP_FOR_ATTACK = 
	{
		EVENT_INTERVAL_ID			= 0,
		DISTANCE_TO_TARGET_NEAR		= 600,
		RATE						= 30,
	},
	
	CT_NASOD_ELEMENT_FIRE_FLAME_ATTACK = 
	{
		EVENT_INTERVAL_ID			= 0,
		DISTANCE_TO_TARGET_NEAR		= 800,
		RATE						= 30,
	},
		
	CT_NASOD_ELEMENT_FIRE_SMALLMETEO1 = 
	{
		EVENT_INTERVAL_ID			= 0,
		DISTANCE_TO_TARGET_NEAR		= 1300,
		RATE						= 20,
	},
	
	
	
	CT_NASOD_ELEMENT_FIRE_FRAMEWAVE =
	{
		EVENT_INTERVAL_ID			= 0,
		DISTANCE_TO_TARGET_NEAR		= 2000,
		MY_MP_MORE_THAN_PERCENT		= 100,
		RATE						= 80,
	},
	CT_NASOD_ELEMENT_FIRE_PERFECTSTORM =
    {
        EVENT_INTERVAL_ID			= 0,
		DISTANCE_TO_TARGET_NEAR		= 800,
		--MY_MP_MORE_THAN_PERCENT		= 100,
		RATE	                    = 50,
    },
	
	TALK_BOX =
 	{
 		EVENT_INTERVAL_ID		= 1,
		{ RATE = 10, MESSAGE = STR_ID_1471 },
		{ RATE = 10, MESSAGE = STR_ID_1472 },
	},
}



NASOD_ELEMENT_FIRE_JUMP_UP = 
{
	ANIM_NAME					= "JumpUp",
	PLAY_TYPE					= XSKIN_ANIM_PLAYTYPE["XAP_LOOP"],
	TRANSITION					= TRUE,
	LAND_CONNECT				= FALSE,
	
	CAN_PUSH_UNIT				= TRUE,
	CAN_PASS_UNIT				= FALSE,
	
	SPEED_X						= 0,
	SPEED_Y						= INIT_PHYSIC["JUMP_SPEED"],
	
	ADD_POS_Y					= 45, 
	
	SUPER_ARMOR					= TRUE,
	
	IMMADIATE_PACKET_SEND		= TRUE,
	
	EVENT_PROCESS = 
	{		
		{ STATE_CHANGE_TYPE["SCT_CONDITION_TABLE"],			"NASOD_ELEMENT_FIRE_JUMP_ATTACK",			"CT_NASOD_ELEMENT_FIRE_JUMP_ATTACK",	},
		{ STATE_CHANGE_TYPE["SCT_NEGATIVE_Y_SPEED"],		"NASOD_ELEMENT_FIRE_JUMP_DOWN",			},
	},
	
	CT_NASOD_ELEMENT_FIRE_JUMP_ATTACK = 
	{
		DISTANCE_TO_TARGET_NEAR		= 600,
		SMALL_THEN_Y_SPEED			= 0,
		RATE						= 40,
	},
}

NASOD_ELEMENT_FIRE_JUMP_DOWN = 
{
	ANIM_NAME					= "JumpDown",
	PLAY_TYPE					= XSKIN_ANIM_PLAYTYPE["XAP_LOOP"],
	TRANSITION					= TRUE,
	LAND_CONNECT				= FALSE,
	
	CAN_PUSH_UNIT				= TRUE,
	CAN_PASS_UNIT				= FALSE,
		 
	
	IMMADIATE_PACKET_SEND		= TRUE,
		
	EVENT_PROCESS = 
	{		
		{ STATE_CHANGE_TYPE["SCT_FOOT_ON_LINE_TRUE"],		"NASOD_ELEMENT_FIRE_JUMP_LANDING",				},
	},
}

NASOD_ELEMENT_FIRE_JUMP_UP_DIR = 
{
	ANIM_NAME					= "JumpUp",
	PLAY_TYPE					= XSKIN_ANIM_PLAYTYPE["XAP_LOOP"],
	TRANSITION					= TRUE,
	LAND_CONNECT				= FALSE,
	
	CAN_PUSH_UNIT				= TRUE,
	CAN_PASS_UNIT				= FALSE,
		
	PASSIVE_SPEED_X				= INIT_PHYSIC["WALK_SPEED"],
	SPEED_Y						= INIT_PHYSIC["JUMP_SPEED"],
	
	ADD_POS_Y					= 45, 
	
	SUPER_ARMOR					= TRUE,
	IMMADIATE_PACKET_SEND		= TRUE,
	
	EVENT_PROCESS = 
	{		
		{ STATE_CHANGE_TYPE["SCT_CONDITION_TABLE"],			"NASOD_ELEMENT_FIRE_JUMP_ATTACK",				"CT_NASOD_ELEMENT_FIRE_JUMP_ATTACK",	},
		{ STATE_CHANGE_TYPE["SCT_NEGATIVE_Y_SPEED"],		"NASOD_ELEMENT_FIRE_JUMP_DOWN_DIR",				},
	},
	
	CT_NASOD_ELEMENT_FIRE_JUMP_ATTACK = 
	{
		DISTANCE_TO_TARGET_NEAR		= 600,
		SMALL_THEN_Y_SPEED			= 0,
		RATE						= 40,
	},
}

NASOD_ELEMENT_FIRE_JUMP_DOWN_DIR = 
{
	ANIM_NAME					= "JumpDown",
	PLAY_TYPE					= XSKIN_ANIM_PLAYTYPE["XAP_LOOP"],
	TRANSITION					= TRUE,
	LAND_CONNECT				= FALSE,
	
	CAN_PUSH_UNIT				= TRUE,
	CAN_PASS_UNIT				= FALSE,
	
	PASSIVE_SPEED_X				= INIT_PHYSIC["WALK_SPEED"],
	 
	
	IMMADIATE_PACKET_SEND		= TRUE,
		
	EVENT_PROCESS = 
	{		
		{ STATE_CHANGE_TYPE["SCT_FOOT_ON_LINE_TRUE"],		"NASOD_ELEMENT_FIRE_JUMP_LANDING",				},
	},
}

NASOD_ELEMENT_FIRE_JUMP_LANDING = 
{
	ANIM_NAME					= "JumpLanding",
	PLAY_TYPE					= XSKIN_ANIM_PLAYTYPE["XAP_ONE_WAIT"],
	TRANSITION					= TRUE,
	LAND_CONNECT				= FALSE,
	
	CAN_PUSH_UNIT				= TRUE,
	CAN_PASS_UNIT				= FALSE,

    SOUND_PLAY0			= { 0.078, "Nasod_Element_JumpLanding1.ogg" },
--    SOUND_PLAY1			= { 0.781, "Nasod_Element_JumpLanding2.ogg" },
	

	SPEED_X						= 0,
	SPEED_Y						= 0,

    		
	IMMADIATE_PACKET_SEND		= TRUE,

	EVENT_PROCESS = 
	{		
		{ STATE_CHANGE_TYPE["SCT_FOOT_ON_LINE_FALSE_DOWN"],	"NASOD_ELEMENT_FIRE_JUMP_DOWN",					},
		{ STATE_CHANGE_TYPE["SCT_MOTION_END"],				"NASOD_ELEMENT_FIRE_WAIT",						},
	},
}



NASOD_ELEMENT_FIRE_ATTACK_COMBO =
{
	ANIM_NAME					= "Combo",
	PLAY_TYPE					= XSKIN_ANIM_PLAYTYPE["XAP_ONE_WAIT"],
	TRANSITION					= FALSE,
	
	
	CAN_PUSH_UNIT				= TRUE,
	CAN_PASS_UNIT				= FALSE,


    SOUND_PLAY0			= { 0.477, "Nasod_Element_Slash1.ogg" },
    SOUND_PLAY1			= { 0.988, "Nasod_Element_Slash2.ogg" },
    SOUND_PLAY2			= { 1.552, "Nasod_Element_Slash1.ogg" },


	
	SPEED_X						= INIT_PHYSIC["WALK_SPEED"],
	SPEED_Y						= 0,	
	
	VIEW_TARGET					= TRUE,
	
	IMMADIATE_PACKET_SEND		= TRUE,
	
	TALK_BOX = 
	{
		{ RATE = 10, MESSAGE = STR_ID_1473 },
		{ RATE = 10, MESSAGE = STR_ID_1474 },
	},
		
    PARTICLE_SEQ = 
	{
		--Major, time, Name, weaponBonePos, Pos, StateEndDelete, bTrace, posx, posy, posz, bApplyUnitRotation, rotx, roty, rotz,			
		{ FALSE, 0.01, "Nasod_Element_Fire_Combo01", FALSE, "ATTACK_SPHERE2_Rhand", TRUE, TRUE, 0, 0, 50, },
		{ FALSE, 0.91, "Nasod_Element_Fire_Combo01", FALSE, "ATTACK_SPHERE2_Rhand", TRUE, TRUE, 0, 0, 50, },
		{ FALSE, 1.48, "Nasod_Element_Fire_Combo01", FALSE, "ATTACK_SPHERE2_Rhand", TRUE, TRUE, 25, 0, 50, },
		
	},	
	
	EVENT_PROCESS = 
	{		
		{ STATE_CHANGE_TYPE["SCT_FOOT_ON_LINE_FALSE_DOWN"],	"NASOD_ELEMENT_FIRE_JUMP_DOWN",				},
		{ STATE_CHANGE_TYPE["SCT_MOTION_END"],				"NASOD_ELEMENT_FIRE_WAIT",					},		
	},
		
		
	ATTACK_TIME0				= { 0.466, 0.533, },
	ATTACK_TIME1				= { 0.966, 1.033, },
	ATTACK_TIME2				= { 1.506, 1.666, },
	
	DAMAGE_DATA = 
	{
		DAMAGE_TYPE		= DAMAGE_TYPE["DT_PHYSIC"],
		HIT_TYPE		= HIT_TYPE["HT_PUNCH_HIT"],
		REACT_TYPE		= REACT_TYPE["RT_BIG_DAMAGE"],
		
		DAMAGE = 
		{
			PHYSIC		= 1,
		},
		
		BACK_SPEED_X			= INIT_PHYSIC["WALK_SPEED"] * 1.5,
		BACK_SPEED_Y			= INIT_PHYSIC["JUMP_SPEED"] * 1.1,
		
		CAMERA_CRASH_GAP		= 5.0,	
		CAMERA_CRASH_TIME		= 0.2,		
	},
	
	DAMAGE_DATA_NEXT = 
	{
		DAMAGE_TYPE		= DAMAGE_TYPE["DT_PHYSIC"],
		HIT_TYPE		= HIT_TYPE["HT_PUNCH_HIT"],
		REACT_TYPE		= REACT_TYPE["RT_BIG_DAMAGE"],
		
		DAMAGE = 
		{
			PHYSIC		= 1.01,
		},
		
		BACK_SPEED_X			= INIT_PHYSIC["WALK_SPEED"],
		BACK_SPEED_Y			= INIT_PHYSIC["JUMP_SPEED"] * 0.2,
		
		CAMERA_CRASH_GAP		= 0.0,	
		CAMERA_CRASH_TIME		= 0.0,		
	},
	
		
	DAMAGE_DATA_LAST = 
	{
		DAMAGE_TYPE		= DAMAGE_TYPE["DT_PHYSIC"],
		HIT_TYPE		= HIT_TYPE["HT_PUNCH_HIT"],
		REACT_TYPE		= REACT_TYPE["RT_FLY"],
		
		DAMAGE = 
		{
			PHYSIC		= 1.2,
		},
		
		BACK_SPEED_X			= INIT_PHYSIC["RUN_SPEED"] * 2.0,
		BACK_SPEED_Y			= INIT_PHYSIC["JUMP_SPEED"] * 0.5,
		
		CAMERA_CRASH_GAP		= 5.0,	
		CAMERA_CRASH_TIME		= 0.2,		
	},
}

NASOD_ELEMENT_FIRE_SMALLMETEO1 =
{
    ANIM_NAME					= "SmallFrozenMissile",
	PLAY_TYPE					= XSKIN_ANIM_PLAYTYPE["XAP_ONE_WAIT"],
	TRANSITION					= FALSE,
	
	
	CAN_PUSH_UNIT				= TRUE,
	CAN_PASS_UNIT				= FALSE,


    SOUND_PLAY0			= { 0.470, "Nasod_Element_SmallMeteo2.ogg" },
    SOUND_PLAY1			= { 1.533, "Nasod_Element_Slash1.ogg" },
    SOUND_PLAY2			= { 1.543, "Nasod_Element_Slash2.ogg" },

	
	SPEED_X						= 0,
	SPEED_Y						= 0,	
	
--	VIEW_TARGET					= TRUE,
    RIGHT						= TRUE,
    
	IMMADIATE_PACKET_SEND		= TRUE,
	
	TALK_BOX = 
	{
		{ RATE = 10, MESSAGE = STR_ID_1473 },
		{ RATE = 10, MESSAGE = STR_ID_1474 },
	},
		
    PARTICLE_SEQ = 
	{
		--Major, time, Name, weaponBonePos, Pos, StateEndDelete, bTrace, posx, posy, posz, bApplyUnitRotation, rotx, roty, rotz,			
		{ FALSE, 0.4, "Nasod_Element_Fire_SmallMeteo01", FALSE, "ATTACK_SPHERE2_Rhand", TRUE, TRUE, 0, 0, 50, },
		{ FALSE, 0.4, "Nasod_Element_Fire_SmallMeteo01", FALSE, "ATTACK_SPHERE4_Lhand", TRUE, TRUE, 0, 0, 50, },		
		
	},	
	
	EVENT_PROCESS = 
	{		
		{ STATE_CHANGE_TYPE["SCT_FOOT_ON_LINE_FALSE_DOWN"],	"NASOD_ELEMENT_FIRE_JUMP_DOWN",				},
		{ STATE_CHANGE_TYPE["SCT_MOTION_END"],				"NASOD_ELEMENT_FIRE_WAIT",					},		
	},
}


NASOD_ELEMENT_FIRE_FLAME_ATTACK =
{
    ANIM_NAME					= "Fire_FlameAttack",
	PLAY_TYPE					= XSKIN_ANIM_PLAYTYPE["XAP_ONE_WAIT"],
	TRANSITION					= FALSE,
	
	
	CAN_PUSH_UNIT				= TRUE,
	CAN_PASS_UNIT				= FALSE,	


	
	SPEED_X						= 0,
	SPEED_Y						= 0,	
	
	VIEW_TARGET					= TRUE,
	IMMADIATE_PACKET_SEND		= TRUE,
	
	TALK_BOX = 
	{
		{ RATE = 10, MESSAGE = STR_ID_1473 },
		{ RATE = 10, MESSAGE = STR_ID_1474 },
	},
		
    PARTICLE_SEQ = 
	{
		--Major, time, Name, weaponBonePos, Pos, StateEndDelete, bTrace, posx, posy, posz, bApplyUnitRotation, rotx, roty, rotz,			
		{ FALSE, 0.01, "Nasod_Element_Fire_Combo01", FALSE, "ATTACK_SPHERE2_Rhand", TRUE, TRUE, 0, 0, 50, },
		{ FALSE, 0.36, "Nasod_Element_Fire_Combo01", FALSE, "ATTACK_SPHERE2_Rhand", TRUE, TRUE, 0, 0, 50, },		
		
	},	
	
	EVENT_PROCESS = 
	{		
		{ STATE_CHANGE_TYPE["SCT_FOOT_ON_LINE_FALSE_DOWN"],	"NASOD_ELEMENT_FIRE_JUMP_DOWN",				},
		{ STATE_CHANGE_TYPE["SCT_MOTION_END"],				"NASOD_ELEMENT_FIRE_WAIT",					},		
	},
}

NASOD_ELEMENT_FIRE_FRAMEWAVE = 
{
    ANIM_NAME					= "IceWave",
	PLAY_TYPE					= XSKIN_ANIM_PLAYTYPE["XAP_ONE_WAIT"],
	TRANSITION					= FALSE,
	
	
	CAN_PUSH_UNIT				= TRUE,
	CAN_PASS_UNIT				= FALSE,


    SOUND_PLAY0			= { 0.155, "Nasod_Element_IceWave1.ogg" },
    SOUND_PLAY1			= { 0.756, "Nasod_Element_JumpUp.ogg" },
    SOUND_PLAY2			= { 1.256, "Nasod_Element_JumpLanding1.ogg" },

	
	SPEED_X						= 0,
	SPEED_Y						= 0,	
	
	
--	VIEW_TARGET					= TRUE,
	SUPER_ARMOR					= TRUE,
	DEFENCE						= { 0, 100, 70, },
	IMMADIATE_PACKET_SEND		= TRUE,
	
	RIGHT                       = TRUE,	
	
	TALK_BOX = 
	{
		{ RATE = 10, MESSAGE = STR_ID_1473 },
		{ RATE = 10, MESSAGE = STR_ID_1474 },
	},
		
		
    PARTICLE_SEQ = 
	{
		--Major, time, Name, weaponBonePos, Pos, StateEndDelete, bTrace, posx, posy, posz, bApplyUnitRotation, rotx, roty, rotz,			
		{ FALSE, 0.73, "Smoke_FireWave04_Nasod_Element_Fire", FALSE, "Dummy1_Rhand", TRUE, FALSE, 0, 0, 0, },
		{ FALSE, 0.73, "Smoke_FireWave05_Nasod_Element_Fire", FALSE, "Dummy1_Rhand", TRUE, FALSE, 0, 0, 0, },		
		
	},	

	
	EVENT_PROCESS = 
	{		
		{ STATE_CHANGE_TYPE["SCT_FOOT_ON_LINE_FALSE_DOWN"],	"NASOD_ELEMENT_FIRE_JUMP_DOWN",				},
		{ STATE_CHANGE_TYPE["SCT_MOTION_END"],				"NASOD_ELEMENT_FIRE_WAIT",					},		
	},
}

NASOD_ELEMENT_FIRE_JUMP_ATTACK = 
{
	ANIM_NAME					= "JumpAttack",
	PLAY_TYPE					= XSKIN_ANIM_PLAYTYPE["XAP_ONE_WAIT"],
	TRANSITION					= FALSE,
	LAND_CONNECT				= FALSE,
	
	CAN_PUSH_UNIT				= TRUE,
	CAN_PASS_UNIT				= FALSE,	

	
    SOUND_PLAY0			= { 0.270, "Nasod_Element_Slash1.ogg" },

    SUPER_ARMOR					= TRUE,
	IMMADIATE_PACKET_SEND		= TRUE,
	
	EVENT_PROCESS = 
	{		
		{ STATE_CHANGE_TYPE["SCT_FOOT_ON_LINE_TRUE"],		"NASOD_ELEMENT_FIRE_JUMP_LANDING",			},
	},
	
	ATTACK_TIME0				= { 0.266, 0.333, },
	
	DAMAGE_DATA = 
	{
		DAMAGE_TYPE		= DAMAGE_TYPE["DT_PHYSIC"],
		HIT_TYPE		= HIT_TYPE["HT_PUNCH_HIT"],
		REACT_TYPE		= REACT_TYPE["RT_DOWN"],
		
		DAMAGE = 
		{
			PHYSIC		= 1.0,
		},
		
		BACK_SPEED_X			= INIT_PHYSIC["WALK_SPEED"],
		BACK_SPEED_Y			= 0.0,
		
		CAMERA_CRASH_GAP		= 5.0,	
		CAMERA_CRASH_TIME		= 0.2,		
	},
}

NASOD_ELEMENT_FIRE_PERFECTSTORM = 
{
    ANIM_NAME					= "IceHellStone",
	PLAY_TYPE					= XSKIN_ANIM_PLAYTYPE["XAP_ONE_WAIT"],
	TRANSITION					= FALSE,
	
	
	CAN_PUSH_UNIT				= TRUE,
	CAN_PASS_UNIT				= FALSE,


    SOUND_PLAY0			= { 0.189, "Nasod_Element_Slash1.ogg" },
    SOUND_PLAY1			= { 0.400, "Nasod_Element_HitGround.ogg" },
    SOUND_PLAY2			= { 0.465, "Nasod_Element_ReadyStorm.ogg" },


	
	SPEED_X						= 0,
	SPEED_Y						= 0,	
	
	
	VIEW_TARGET					= TRUE,	
	DEFENCE						= { 0, 100, 70, },
	IMMADIATE_PACKET_SEND		= TRUE,
	
	
	TALK_BOX = 
	{
		{ RATE = 10, MESSAGE = STR_ID_1473 },
		{ RATE = 10, MESSAGE = STR_ID_1474 },
	},
		
		
    PARTICLE_SEQ = 
	{
		--Major, time, Name, weaponBonePos, Pos, StateEndDelete, bTrace, posx, posy, posz, bApplyUnitRotation, rotx, roty, rotz,	
		{ FALSE, 0.01, "Nasod_Element_Fire_Combo01", FALSE, "ATTACK_SPHERE2_Rhand", TRUE, TRUE, 0, 0, 0, },				
		{ FALSE, 0.8,   "Nasod_Element_Fire_Combo01", FALSE, "ATTACK_SPHERE2_Rhand", TRUE, TRUE, 0, 0, 0, },		
	},	

	
	EVENT_PROCESS = 
	{		
		{ STATE_CHANGE_TYPE["SCT_FOOT_ON_LINE_FALSE_DOWN"],	"NASOD_ELEMENT_FIRE_JUMP_DOWN",				},
		{ STATE_CHANGE_TYPE["SCT_MOTION_END"],				"NASOD_ELEMENT_FIRE_WAIT",					},		
	},
}

NASOD_ELEMENT_FIRE_JUMP_FOR_ATTACK = 
{
	ANIM_NAME					= "JumpUp",
	PLAY_TYPE					= XSKIN_ANIM_PLAYTYPE["XAP_LOOP"],
	TRANSITION					= TRUE,
	LAND_CONNECT				= FALSE,
	
	CAN_PUSH_UNIT				= TRUE,
	CAN_PASS_UNIT				= FALSE,
	
	PASSIVE_SPEED_X				= INIT_PHYSIC["WALK_SPEED"],
	SPEED_Y						= INIT_PHYSIC["JUMP_SPEED"],
	
	VIEW_TARGET					= TRUE,
	
	IMMADIATE_PACKET_SEND		= TRUE,
	
	EVENT_PROCESS = 
	{		
		{ STATE_CHANGE_TYPE["SCT_NEGATIVE_Y_SPEED"],			"NASOD_ELEMENT_FIRE_JUMP_ATTACK",		},
	},
}

NASOD_ELEMENT_FIRE_DAMAGE_SMALL = 
{
	ANIM_NAME					= "DamageSmall",
	PLAY_TYPE					= XSKIN_ANIM_PLAYTYPE["XAP_ONE_WAIT"],
	TRANSITION					= FALSE,
	LAND_CONNECT				= FALSE,
	
	CAN_PUSH_UNIT				= TRUE,
	CAN_PASS_UNIT				= FALSE,

	
	TALK_BOX = 
	{
		{ RATE = 10, MESSAGE = STR_ID_1475 },
	},
	
	EVENT_PROCESS = 
	{
		{ STATE_CHANGE_TYPE["SCT_MOTION_END"],					"NASOD_ELEMENT_FIRE_WAIT",												},
	},
}

NASOD_ELEMENT_FIRE_DAMAGE_BIG = 
{
	ANIM_NAME					= "DamageBig",
	PLAY_TYPE					= XSKIN_ANIM_PLAYTYPE["XAP_ONE_WAIT"],
	TRANSITION					= FALSE,
	LAND_CONNECT				= FALSE,
	
	CAN_PUSH_UNIT				= TRUE,
	CAN_PASS_UNIT				= FALSE,

--    SOUND_PLAY0			= { 0.015, "AirShip_SwordMan_Scream.ogg" , 30 },
	
	TALK_BOX = 
	{
		{ RATE = 10, MESSAGE = STR_ID_1476 },
	},
	
	EVENT_PROCESS = 
	{
		{ STATE_CHANGE_TYPE["SCT_MOTION_END"],					"NASOD_ELEMENT_FIRE_WAIT",												},
	},
}

NASOD_ELEMENT_FIRE_DAMAGE_DOWN_FRONT = 
{
	ANIM_NAME					= "DamageDownFront",
		
	PLAY_TYPE					= XSKIN_ANIM_PLAYTYPE["XAP_ONE_WAIT"],
	TRANSITION					= FALSE,
	LAND_CONNECT				= FALSE,

	SUPER_ARMOR					= TRUE,
	DEFENCE						= { 0, 100, 70, },
	
	CAN_PUSH_UNIT				= TRUE,
	CAN_PASS_UNIT				= FALSE,

--    SOUND_PLAY0			= { 0.1, "AirShip_SwordMan_Scream.ogg" , 50 },
	
	TALK_BOX = 
	{
		{ RATE = 10, MESSAGE = STR_ID_2568 },
		{ RATE = 10, MESSAGE = STR_ID_2569 },
	},
	
	EVENT_PROCESS = 
	{
		{ STATE_CHANGE_TYPE["SCT_FOOT_ON_LINE_FALSE_DOWN"],		"NASOD_ELEMENT_FIRE_DAMAGE_AIR_FALL",			},
		{ STATE_CHANGE_TYPE["SCT_CONDITION_TABLE"],				"NASOD_ELEMENT_FIRE_STAND_UP_ATTACK_FRONT",	"CT_NASOD_ELEMENT_FIRE_STAND_UP_ATTACK_FRONT", },
		{ STATE_CHANGE_TYPE["SCT_MOTION_END"],					"NASOD_ELEMENT_FIRE_STAND_UP_FRONT",			},
	},
	
	CT_NASOD_ELEMENT_FIRE_STAND_UP_ATTACK_FRONT = 
	{
		ANIM_PLAY_COUNT		= 1,
		RATE				= 20,
	},
}

NASOD_ELEMENT_FIRE_DAMAGE_DOWN_BACK = 
{
	ANIM_NAME					= "DamageDownBack",
	PLAY_TYPE					= XSKIN_ANIM_PLAYTYPE["XAP_ONE_WAIT"],
	TRANSITION					= FALSE,
	LAND_CONNECT				= FALSE,
	
	SUPER_ARMOR					= TRUE,
	DEFENCE						= { 0, 100, 70, },


	
	CAN_PUSH_UNIT				= TRUE,
	CAN_PASS_UNIT				= FALSE,
	
	TALK_BOX = 
	{
		{ RATE = 10, MESSAGE = STR_ID_2568 },
		{ RATE = 10, MESSAGE = STR_ID_2569 },
	},
	
	EVENT_PROCESS = 
	{
		{ STATE_CHANGE_TYPE["SCT_FOOT_ON_LINE_FALSE_DOWN"],		"NASOD_ELEMENT_FIRE_DAMAGE_AIR_FALL",			},
		{ STATE_CHANGE_TYPE["SCT_CONDITION_TABLE"],				"NASOD_ELEMENT_FIRE_STAND_UP_ATTACK_BACK",	"CT_NASOD_ELEMENT_FIRE_STAND_UP_ATTACK_BACK", },
		{ STATE_CHANGE_TYPE["SCT_MOTION_END"],					"NASOD_ELEMENT_FIRE_STAND_UP_BACK",			},
	},
	
	CT_NASOD_ELEMENT_FIRE_STAND_UP_ATTACK_BACK = 
	{
		ANIM_PLAY_COUNT		= 1,
		RATE				= 20,
	},
}

NASOD_ELEMENT_FIRE_DAMAGE_FLY_FRONT = 
{
	ANIM_NAME					= "DamageAirFlyFront",
	PLAY_TYPE					= XSKIN_ANIM_PLAYTYPE["XAP_ONE_WAIT"],
	TRANSITION					= FALSE,
	LAND_CONNECT				= FALSE,
				
	CAN_PUSH_UNIT				= TRUE,
	CAN_PASS_UNIT				= FALSE,
	
	EVENT_PROCESS = 
	{
		{ STATE_CHANGE_TYPE["SCT_FOOT_ON_LINE_TRUE"],			"NASOD_ELEMENT_FIRE_DAMAGE_DOWN_FRONT",		},
	},
}

NASOD_ELEMENT_FIRE_DAMAGE_FLY_BACK = 
{
	ANIM_NAME					= "DamageAirFlyBack",
	PLAY_TYPE					= XSKIN_ANIM_PLAYTYPE["XAP_ONE_WAIT"],
	TRANSITION					= FALSE,
	LAND_CONNECT				= FALSE,	
	
	CAN_PUSH_UNIT				= TRUE,
	CAN_PASS_UNIT				= FALSE,
	
	EVENT_PROCESS = 
	{
		{ STATE_CHANGE_TYPE["SCT_FOOT_ON_LINE_TRUE"],			"NASOD_ELEMENT_FIRE_DAMAGE_DOWN_BACK",		},
	},
}

NASOD_ELEMENT_FIRE_DAMAGE_AIR = 
{
	ANIM_NAME					= "DamageAirSmall",
	PLAY_TYPE					= XSKIN_ANIM_PLAYTYPE["XAP_ONE_WAIT"],
	TRANSITION					= FALSE,
	LAND_CONNECT				= FALSE,
	
	CAN_PUSH_UNIT				= TRUE,
	CAN_PASS_UNIT				= FALSE,
	
	EVENT_PROCESS = 
	{
		{ STATE_CHANGE_TYPE["SCT_FOOT_ON_LINE_TRUE"],			"NASOD_ELEMENT_FIRE_WAIT",					},
	},
}

NASOD_ELEMENT_FIRE_DAMAGE_AIR_DOWN = 
{
	ANIM_NAME					= "DamageAirDown",
	PLAY_TYPE					= XSKIN_ANIM_PLAYTYPE["XAP_ONE_WAIT"],
	TRANSITION					= FALSE,
	LAND_CONNECT				= FALSE,
	
	CAN_PUSH_UNIT				= TRUE,
	CAN_PASS_UNIT				= FALSE,
	
	EVENT_PROCESS = 
	{
		{ STATE_CHANGE_TYPE["SCT_FOOT_ON_LINE_TRUE"],			"NASOD_ELEMENT_FIRE_DAMAGE_AIR_DOWN_LANDING",	},
	},
}

NASOD_ELEMENT_FIRE_DAMAGE_AIR_UP = 
{
	ANIM_NAME					= "DamageAirUp",
	PLAY_TYPE					= XSKIN_ANIM_PLAYTYPE["XAP_ONE_WAIT"],
	TRANSITION					= FALSE,
	LAND_CONNECT				= FALSE,
	
	CAN_PUSH_UNIT				= TRUE,
	CAN_PASS_UNIT				= FALSE,
	
		
	EVENT_PROCESS = 
	{
		{ STATE_CHANGE_TYPE["SCT_NEGATIVE_Y_SPEED"],		"NASOD_ELEMENT_FIRE_DAMAGE_AIR_FALL",			},
		{ STATE_CHANGE_TYPE["SCT_FOOT_ON_LINE_TRUE"],		"NASOD_ELEMENT_FIRE_DAMAGE_AIR_DOWN_LANDING",	},
	},
	
	TALK_BOX =
	{
		{ RATE = 10, MESSAGE = STR_ID_2568 },
		{ RATE = 10, MESSAGE = STR_ID_2569 },
	},
}

NASOD_ELEMENT_FIRE_DAMAGE_AIR_FALL = 
{
	ANIM_NAME					= "DamageAirFall",
	PLAY_TYPE					= XSKIN_ANIM_PLAYTYPE["XAP_ONE_WAIT"],
	TRANSITION					= FALSE,
	LAND_CONNECT				= FALSE,
	
	CAN_PUSH_UNIT				= TRUE,
	CAN_PASS_UNIT				= FALSE,
	
	EVENT_PROCESS = 
	{
		{ STATE_CHANGE_TYPE["SCT_POSITIVE_Y_SPEED"],		"NASOD_ELEMENT_FIRE_DAMAGE_AIR_UP",			},
		{ STATE_CHANGE_TYPE["SCT_FOOT_ON_LINE_TRUE"],		"NASOD_ELEMENT_FIRE_DAMAGE_AIR_DOWN_LANDING",	},
	},
}

NASOD_ELEMENT_FIRE_DAMAGE_AIR_DOWN_LANDING = 
{
	ANIM_NAME					= "DamageAirDownLanding",
	PLAY_TYPE					= XSKIN_ANIM_PLAYTYPE["XAP_ONE_WAIT"],
	TRANSITION					= FALSE,
	LAND_CONNECT				= FALSE,
	
	SUPER_ARMOR					= TRUE,
	DEFENCE						= { 0, 100, 70, },
	
	CAN_PUSH_UNIT				= TRUE,
	CAN_PASS_UNIT				= FALSE,
	
	EVENT_PROCESS = 
	{
		{ STATE_CHANGE_TYPE["SCT_FOOT_ON_LINE_FALSE_DOWN"],	"NASOD_ELEMENT_FIRE_DAMAGE_AIR_FALL",			},
		{ STATE_CHANGE_TYPE["SCT_CONDITION_TABLE"],			"NASOD_ELEMENT_FIRE_STAND_UP_ATTACK_FRONT",	"CT_NASOD_ELEMENT_FIRE_STAND_UP_ATTACK_FRONT", },
		{ STATE_CHANGE_TYPE["SCT_MOTION_END"],				"NASOD_ELEMENT_FIRE_STAND_UP_FRONT",			},
	},
	
	CT_NASOD_ELEMENT_FIRE_STAND_UP_ATTACK_FRONT = 
	{
		ANIM_PLAY_COUNT		= 1,
		RATE				= 20,
	},
}

NASOD_ELEMENT_FIRE_STAND_UP_FRONT = 
{
	ANIM_NAME					= "DamageStandUpFront",
	PLAY_TYPE					= XSKIN_ANIM_PLAYTYPE["XAP_ONE_WAIT"],
	TRANSITION					= FALSE,
	LAND_CONNECT				= FALSE,	
	
	SUPER_ARMOR					= TRUE,
	DEFENCE						= { 0, 100, 70, },
	
	CAN_PUSH_UNIT				= TRUE,
	CAN_PASS_UNIT				= FALSE,
	
	EVENT_PROCESS = 
	{
		{ STATE_CHANGE_TYPE["SCT_FOOT_ON_LINE_FALSE_DOWN"],	"NASOD_ELEMENT_FIRE_JUMP_DOWN",			},
		{ STATE_CHANGE_TYPE["SCT_MOTION_END"],				"NASOD_ELEMENT_FIRE_WAIT",				},
	},
}

NASOD_ELEMENT_FIRE_STAND_UP_BACK = 
{
	ANIM_NAME					= "DamageStandUpBack",
	PLAY_TYPE					= XSKIN_ANIM_PLAYTYPE["XAP_ONE_WAIT"],
	TRANSITION					= FALSE,
	LAND_CONNECT				= FALSE,
	
	SUPER_ARMOR					= TRUE,
	DEFENCE						= { 0, 100, 70, },
		
	CAN_PUSH_UNIT				= TRUE,
	CAN_PASS_UNIT				= FALSE,
		
	EVENT_PROCESS = 
	{
		{ STATE_CHANGE_TYPE["SCT_FOOT_ON_LINE_FALSE_DOWN"],	"NASOD_ELEMENT_FIRE_JUMP_DOWN", },
		{ STATE_CHANGE_TYPE["SCT_MOTION_END"],				"NASOD_ELEMENT_FIRE_WAIT", },
	},		
}

NASOD_ELEMENT_FIRE_STAND_UP_ATTACK_FRONT = 
{
	ANIM_NAME					= "StandUpAttackFront",
	PLAY_TYPE					= XSKIN_ANIM_PLAYTYPE["XAP_ONE_WAIT"],
	TRANSITION					= FALSE,
	LAND_CONNECT				= FALSE,	
	
	ANIM_WAIT_TIME				= 1,

	MIND_FLAG					= MIND_FLAG["MF_STAND_UP_ATTACK"],
	
	SUPER_ARMOR					= TRUE,
	DEFENCE						= { 0, 100, 70, },
	
	CAN_PUSH_UNIT				= TRUE,
	CAN_PASS_UNIT				= FALSE,

    SOUND_PLAY0			= { 0.453, "Nasod_Element_StandUpAttack.ogg" },



	EVENT_PROCESS = 
	{
		{ STATE_CHANGE_TYPE["SCT_FOOT_ON_LINE_FALSE_DOWN"],	"NASOD_ELEMENT_FIRE_JUMP_DOWN",			},
		{ STATE_CHANGE_TYPE["SCT_MOTION_END"],				"NASOD_ELEMENT_FIRE_WAIT",				},
	},
		
	ATTACK_TIME0				= { 0.2, 0.27, },	
	
	
	DAMAGE_DATA = 
	{
		DAMAGE_TYPE		= DAMAGE_TYPE["DT_PHYSIC"],
		HIT_TYPE		= HIT_TYPE["HT_SWORD_SLASH"],
		REACT_TYPE		= REACT_TYPE["RT_DOWN"],
		
		DAMAGE = 
		{
			PHYSIC		= 1.5,
			FIRE		= 0.0,
			ICE			= 0.0,
			EARTH		= 0.0,
			LIGHTNING	= 0.0,
			DARK		= 0.0,
			LIGHT		= 0.0,
			UNIVERSAL	= 0.0,
		},
		
		BACK_SPEED_X			= INIT_PHYSIC["RUN_SPEED"],
		BACK_SPEED_Y			= 0.0,
		
		STOP_TIME_ATT			= 0.0,		
		STOP_TIME_DEF			= 0.0,	
		CAMERA_CRASH_GAP		= 5.0,	
		CAMERA_CRASH_TIME		= 0.2,
		CLEAR_SCREEN			= 0.0,	
		CLEAR_SCREEN_COLOR_A	= 0.0,
		CLEAR_SCREEN_COLOR_R	= 1.0,
		CLEAR_SCREEN_COLOR_G	= 1.0,
		CLEAR_SCREEN_COLOR_B	= 1.0,

		RE_ATTACK				= FALSE,		
		HIT_GAP					= 0.0,				
	},
	
	TALK_BOX =
	{
		{ RATE = 10, MESSAGE = STR_ID_2568 },
	},
	
}

NASOD_ELEMENT_FIRE_STAND_UP_ATTACK_BACK = 
{
	ANIM_NAME					= "StandUpAttackBack",
	PLAY_TYPE					= XSKIN_ANIM_PLAYTYPE["XAP_ONE_WAIT"],
	TRANSITION					= FALSE,
	LAND_CONNECT				= FALSE,
	
	ANIM_WAIT_TIME				= 1,

	MIND_FLAG					= MIND_FLAG["MF_STAND_UP_ATTACK"],
	
	SUPER_ARMOR					= TRUE,
	DEFENCE						= { 0, 100, 70, },
		
	CAN_PUSH_UNIT				= TRUE,
	CAN_PASS_UNIT				= FALSE,

	
    SOUND_PLAY0			= { 0.729, "Nasod_Element_StandUpAttack.ogg" },

	
	FLIP_DIR_END				= TRUE,
	
	EVENT_PROCESS = 
	{
		{ STATE_CHANGE_TYPE["SCT_FOOT_ON_LINE_FALSE_DOWN"],	"NASOD_ELEMENT_FIRE_JUMP_DOWN", },
		{ STATE_CHANGE_TYPE["SCT_MOTION_END"],				"NASOD_ELEMENT_FIRE_WAIT", },
	},	
	
		
	ATTACK_TIME0				= { 0.4, 0.47, },	
	
	
	DAMAGE_DATA = 
	{
		DAMAGE_TYPE		= DAMAGE_TYPE["DT_PHYSIC"],
		HIT_TYPE		= HIT_TYPE["HT_SWORD_SLASH"],
		REACT_TYPE		= REACT_TYPE["RT_DOWN"],
		
		DAMAGE = 
		{
			PHYSIC		= 1.5,
			FIRE		= 0.0,
			ICE			= 0.0,
			EARTH		= 0.0,
			LIGHTNING	= 0.0,
			DARK		= 0.0,
			LIGHT		= 0.0,
			UNIVERSAL	= 0.0,
		},
		
		BACK_SPEED_X			= INIT_PHYSIC["RUN_SPEED"],
		BACK_SPEED_Y			= 0.0,
		
		STOP_TIME_ATT			= 0.0,		
		STOP_TIME_DEF			= 0.0,	
		CAMERA_CRASH_GAP		= 5.0,	
		CAMERA_CRASH_TIME		= 0.2,
		CLEAR_SCREEN			= 0.0,	
		CLEAR_SCREEN_COLOR_A	= 0.0,
		CLEAR_SCREEN_COLOR_R	= 1.0,
		CLEAR_SCREEN_COLOR_G	= 1.0,
		CLEAR_SCREEN_COLOR_B	= 1.0,

		RE_ATTACK				= FALSE,		
		HIT_GAP					= 0.0,				
	},
	TALK_BOX =
	{
		{ RATE = 10, MESSAGE = STR_ID_1477 },

	},
}


NASOD_ELEMENT_FIRE_DYING_LAND_FRONT = 
{
	ANIM_NAME					= "DamageDownFront",
	PLAY_TYPE					= XSKIN_ANIM_PLAYTYPE["XAP_ONE_WAIT"],
	TRANSITION					= FALSE,
	LAND_CONNECT				= FALSE,

	INVINCIBLE					= { 0, 100, }, 		

	
	CAN_PUSH_UNIT				= FALSE,
	CAN_PASS_UNIT				= TRUE,
	
	DYING_END					= TRUE,
	
	IMMADIATE_PACKET_SEND		= TRUE,
}
	
NASOD_ELEMENT_FIRE_DYING_LAND_BACK = 
{
	ANIM_NAME					= "DamageDownBack",
	PLAY_TYPE					= XSKIN_ANIM_PLAYTYPE["XAP_ONE_WAIT"],
	TRANSITION					= FALSE,
	LAND_CONNECT				= FALSE,
	
	INVINCIBLE					= { 0, 100, }, 		

	
	CAN_PUSH_UNIT				= FALSE,
	CAN_PASS_UNIT				= TRUE,
	
	DYING_END					= TRUE,	
	
	IMMADIATE_PACKET_SEND		= TRUE,
}

NASOD_ELEMENT_FIRE_DYING_SKY = 
{
	ANIM_NAME					= "DamageAirDownLanding",
	PLAY_TYPE					= XSKIN_ANIM_PLAYTYPE["XAP_ONE_WAIT"],
	TRANSITION					= FALSE,
	LAND_CONNECT				= FALSE,
	
	INVINCIBLE					= { 0, 100, }, 		


	
	CAN_PUSH_UNIT				= FALSE,
	CAN_PASS_UNIT				= TRUE,
	
	DYING_END					= TRUE,
	
	IMMADIATE_PACKET_SEND		= TRUE,
}






--------------------------------------------------------------------
--------------------------------------------------------------------


function CF_NASOD_ELEMENT_FIRE_WIN( pKTDXApp, pX2Game, pNPCUnit )

	if pX2Game:LiveUserUnitNum() == 0 then
		return true
	else
		return false
	end

end







--------------------------------------------------------------------
--------------------------------------------------------------------
function NASOD_ELEMENT_FIRE_START_STATE_START( pKTDXApp, pX2Game, pNPCUnit )
    pNPCUnit:SetFlag_LUA(0, false)
    pNPCUnit:SetShowBossGage(true)
    --pNPCUnit:SetShow(true)
end

function NASOD_ELEMENT_FIRE_START_FRAME_MOVE( pKTDXApp, pX2Game, pNPCUnit )
	
end

function NASOD_ELEMENT_FIRE_WAIT_START_STATE_START( pKTDXApp, pX2Game, pNPCUnit )    
    -- 텔레포트 (나타날때) 
    pNPCUnit:PlaySound_LUA( "Nasod_Element_Teleport.ogg" )
	--pNPCUnit:SetShow(true)	
end

function NASOD_ELEMENT_FIRE_WAIT_START_FRAME_MOVE( pKTDXApp, pX2Game, pNPCUnit )    	
	
	if pNPCUnit:AnimEventTimer_LUA( 0.1 ) then
	    pos = pNPCUnit:GetPos()
        rotDegree 	= pNPCUnit:GetRotateDegree()
        pMinorXMeshPlayer = pX2Game:GetMinorXMeshPlayer()          
       
        rotDegree.y = 0
        
        if pMinorXMeshPlayer ~= nil then
            pMeshPlayer = pMinorXMeshPlayer:CreateInstance_LUA( "RespawnLanding01", pos, rotDegree, rotDegree, 14 )        
            if pMeshPlayer ~= nil then
                pMeshPlayer:SetManualSize(2.0, 2.0, 2.0)
            end    
            pMeshPlayer = pMinorXMeshPlayer:CreateInstance_LUA( "RespawnLanding02", pos, rotDegree, rotDegree, 14 )        
            if pMeshPlayer ~= nil then
                pMeshPlayer:SetManualSize(2.0, 2.0, 2.0)
            end
        end
    end        
end




function NASOD_ELEMENT_FIRE_WALK_STATE_END( pKTDXApp, pX2Game, pNPCUnit )

	pMinorParticle = pX2Game:GetMinorParticle()
	
	if pMinorParticle ~= nil then
	    pMinorParticle:GameUnitCreateSequence_LUA( pNPCUnit, "StepSmoke", pNPCUnit:GetLandPosition_LUA(), D3DXVECTOR2(100,100), D3DXVECTOR2(5,-1) )
    end	    

end



function NASOD_ELEMENT_FIRE_JUMP_DOWN_STATE_END( pKTDXApp, pX2Game, pNPCUnit )

	pMinorParticle = pX2Game:GetMinorParticle()
	
	if pMinorParticle ~= nil then
	    pMinorParticle:GameUnitCreateSequence_LUA( pNPCUnit, "StepSmoke", pNPCUnit:GetLandPosition_LUA(), D3DXVECTOR2(100,100), D3DXVECTOR2(5,-1) )
    end	    

end

function NASOD_ELEMENT_FIRE_JUMP_DOWN_DIR_STATE_END( pKTDXApp, pX2Game, pNPCUnit )

	pMinorParticle = pX2Game:GetMinorParticle()
	
	if pMinorParticle ~= nil then
	    pMinorParticle:GameUnitCreateSequence_LUA( pNPCUnit, "StepSmoke", pNPCUnit:GetLandPosition_LUA(), D3DXVECTOR2(100,100), D3DXVECTOR2(5,-1) )
    end	    

end



function NASOD_ELEMENT_FIRE_ATTACK_COMBO_FRAME_MOVE( pKTDXApp, pX2Game, pNPCUnit )
				
	if pNPCUnit:AnimEventTimer_LUA( 1.0 ) then
		pNPCUnit:ClearHitUnitList_LUA()
		pNPCUnit:SetDamageData_LUA( "DAMAGE_DATA_NEXT" )
	end	
			
	if pNPCUnit:AnimEventTimer_LUA( 1.615 ) then
		pNPCUnit:ClearHitUnitList_LUA()
		pNPCUnit:SetDamageData_LUA( "DAMAGE_DATA_LAST" )
	end
end




function NASOD_ELEMENT_FIRE_DAMAGE_SMALL_FRAME_MOVE( pKTDXApp, pX2Game, pNPCUnit )

	if pNPCUnit:AnimEventTimer_LUA( 0.047 ) then
		pMinorParticle = pX2Game:GetMinorParticle()
		if pMinorParticle ~= nil then
		    pMinorParticle:GameUnitCreateSequence_LUA( pNPCUnit, "StepSmoke", pNPCUnit:GetLandPosition_LUA(), D3DXVECTOR2(100,100), D3DXVECTOR2(5,-1) )
        end		    
	end

end

function NASOD_ELEMENT_FIRE_DAMAGE_BIG_FRAME_MOVE( pKTDXApp, pX2Game, pNPCUnit )

	if pNPCUnit:AnimEventTimer_LUA( 0.06 ) then
		pMinorParticle = pX2Game:GetMinorParticle()
		if pMinorParticle ~= nil then
		    pMinorParticle:GameUnitCreateSequence_LUA( pNPCUnit, "StepSmoke", pNPCUnit:GetLandPosition_LUA(), D3DXVECTOR2(100,100), D3DXVECTOR2(5,-1) )
        end		    
	end

end

function NASOD_ELEMENT_FIRE_DAMAGE_DOWN_FRONT_FRAME_MOVE( pKTDXApp, pX2Game, pNPCUnit )

	if pNPCUnit:AnimEventTimer_LUA( 0.41 ) then
		pNPCUnit:PlaySound_LUA( "Down2.ogg" )		
		pMinorParticle = pX2Game:GetMinorParticle()
		if pMinorParticle ~= nil then
		    pMinorParticle:GameUnitCreateSequence_LUA( pNPCUnit, "DownSmoke", pNPCUnit:GetLandPosition_LUA(), D3DXVECTOR2(100,100), D3DXVECTOR2(7,-1) )
        end		    
	end

end

function NASOD_ELEMENT_FIRE_DAMAGE_DOWN_BACK_FRAME_MOVE( pKTDXApp, pX2Game, pNPCUnit )

	if pNPCUnit:AnimEventTimer_LUA( 0.45 ) then
		pNPCUnit:PlaySound_LUA( "Down2.ogg" )		
		pMinorParticle = pX2Game:GetMinorParticle()
		if pMinorParticle ~= nil then
		    pMinorParticle:GameUnitCreateSequence_LUA( pNPCUnit, "DownSmoke", pNPCUnit:GetLandPosition_LUA(), D3DXVECTOR2(100,100), D3DXVECTOR2(7,-1) )
        end		    
	end

end

function NASOD_ELEMENT_FIRE_DAMAGE_AIR_DOWN_LANDING_FRAME_MOVE( pKTDXApp, pX2Game, pNPCUnit )

	if pNPCUnit:AnimEventTimer_LUA( 0.01 ) then
		
		pMinorParticle = pX2Game:GetMinorParticle()
		
		if pMinorParticle ~= nil then
		    pos = pNPCUnit:GetLandPosition_LUA()
		    pMinorParticle:GameUnitCreateSequence_LUA( pNPCUnit, "DownSmoke", pos, D3DXVECTOR2(100,100), D3DXVECTOR2(7,-1) )
		    pos.y = pos.y + 5
		    pMinorParticle:GameUnitCreateSequence_LUA( pNPCUnit, "GroundShockWave", pos, D3DXVECTOR2(100,100), D3DXVECTOR2(1,-1) )
		    
		    pParticle = pMinorParticle:GameUnitCreateSequence_LUA( pNPCUnit, "AirDownTick", pNPCUnit:GetPos(), D3DXVECTOR2(200,200), D3DXVECTOR2(10,-1) )
		    if pParticle ~= nil then 
			    pParticle:SetLandPosition( pos.y - 5 )
		    end
		end
		
		if GetDistance_LUA( pNPCUnit:GetPos(), pX2Game:GetFocusUnitPos_LUA() ) < 500 then
			pX2Game:GetX2Camera():GetCamera():UpDownCrashCameraNoReset( 10.0, 0.1 )
		end		
		
	elseif pNPCUnit:AnimEventTimer_LUA( 0.1 ) then
	
		pNPCUnit:PlaySound_LUA( "Down2.ogg" )		
		pMinorParticle = pX2Game:GetMinorParticle()
		if pMinorParticle ~= nil then
		    pMinorParticle:GameUnitCreateSequence_LUA( pNPCUnit, "DownSmoke", pNPCUnit:GetLandPosition_LUA(), D3DXVECTOR2(100,100), D3DXVECTOR2(7,-1) )
        end		
	end

end

function NASOD_ELEMENT_FIRE_STAND_UP_ATTACK_FRONT_FRAME_MOVE( pKTDXApp, pX2Game, pNPCUnit )

	if pNPCUnit:AnimEventTimer_LUA( 0.35 ) then
		pMinorParticle = pX2Game:GetMinorParticle()
		if pMinorParticle ~= nil then
		    pMinorParticle:GameUnitCreateSequence_LUA( pNPCUnit, "StepSmoke", pNPCUnit:GetLandPosition_LUA(), D3DXVECTOR2(100,100), D3DXVECTOR2(5,-1) )
        end		    
	end

end

function NASOD_ELEMENT_FIRE_STAND_UP_ATTACK_BACK_FRAME_MOVE( pKTDXApp, pX2Game, pNPCUnit )

	if pNPCUnit:AnimEventTimer_LUA( 0.35 ) then
		pMinorParticle = pX2Game:GetMinorParticle()
		if pMinorParticle ~= nil then
		    pMinorParticle:GameUnitCreateSequence_LUA( pNPCUnit, "StepSmoke", pNPCUnit:GetLandPosition_LUA(), D3DXVECTOR2(100,100), D3DXVECTOR2(5,-1) )
        end		    
	end

end

function NASOD_ELEMENT_FIRE_DYING_LAND_STATE_START( pKTDXApp, pX2Game, pNPCUnit )

    pEffect = pNPCUnit:GetDamageEffect_LUA( 0 )
	if pEffect ~= nil then
	
		pDamageEffect = pX2Game:GetDamageEffect()
		pDamageEffect:DestroyInstance( pEffect )
		
	end
	
	pNPCUnit:ClearDamageEffect_LUA( 0 )
	
	pEffect = pNPCUnit:GetDamageEffect_LUA( 1 )
	if pEffect ~= nil then
	
		pDamageEffect = pX2Game:GetDamageEffect()
		pDamageEffect:DestroyInstance( pEffect )
		
	end
	
	pNPCUnit:ClearDamageEffect_LUA( 1 )

	pos = pNPCUnit:GetPos()
	pos.y = pos.y + 100.0
	GetMinorParticle = pX2Game:GetMinorParticle()
	
	if GetMinorParticle ~= nil then
	    pSeq = GetMinorParticle:GameUnitCreateSequence_LUA( pNPCUnit, "DieLight",		pos, D3DXVECTOR2(-1,-1), D3DXVECTOR2(3,-1) )
	    if pSeq ~= nil then
    	
		    pSeq:SetLandPosition( pNPCUnit:GetLandPosition_LUA().y )
		    pNPCUnit:SetDieSeq( pSeq:GetHandle() )
    	
	    end
    end	    
	pNPCUnit:PlaySound_LUA( "DieLight.ogg" )

	
end


function NASOD_ELEMENT_FIRE_FLAME_ATTACK_FRAME_MOVE( pKTDXApp, pX2Game, pNPCUnit )

    if pNPCUnit:AnimEventTimer_LUA( 1.0 ) then
	
		vBonePos = pNPCUnit:GetBonePos_LUA("Dummy1_Rhand")	
		vRotateDegree	= pNPCUnit:GetRotateDegree()
		
		pMajorParticle = pX2Game:GetMajorParticle()
		if pMajorParticle ~= nil then
		    pParticle = pMajorParticle:GameUnitCreateSequence_LUA( pNPCUnit, "Nasod_Element_Fire_FlameAttack01", vBonePos, D3DXVECTOR2(-1,-1), D3DXVECTOR2(-1,-1) )
		    
		    if pParticle ~= nil then
		        pParticle:SetAddRotate( vRotateDegree )
		        pParticle:SetAxisAngle( vRotateDegree )			        
		    end
		    --pNPCUnit:SetMajorParticle_LUA(0, pParticle)
		end				
	end
--[[	
	if pNPCUnit:AnimEventTimer_LUA( 1.0 ) or
	    pNPCUnit:AnimEventTimer_LUA( 1.5 ) or
	    pNPCUnit:AnimEventTimer_LUA( 2.0 ) or
	    pNPCUnit:AnimEventTimer_LUA( 2.5 ) then
	    
	    vBoneDummy = pNPCUnit:GetBonePos_LUA("Dummy1_Rhand")
	    vDirVector = pNPCUnit:GetDirVector()	
		bIsRight = pNPCUnit:GetIsRight()
	    
	    if bIsRight == true then			
			vBoneDummy = MovePos( vBoneDummy, vDirVector, -120 )	
		else			
			vBoneDummy = MovePos( vBoneDummy, vDirVector, 120 )		
		end
		
		landPos = pNPCUnit:GetLandPosition_LUA()
		pDamageEffect = pX2Game:GetDamageEffect()
		if pDamageEffect ~= nil then
		    pDamageDummy = pDamageEffect:CreateInstance_LUA( pNPCUnit, "NASOD_DUMMY_ATTACK", vBoneDummy, landPos.y )
        end		    
    end	 
--]]    
	if pNPCUnit:AnimEventTimer_LUA( 1.01 ) then
	
		vBonePos = pNPCUnit:GetBonePos_LUA("Dummy1_Rhand")	
		vDirVector = pNPCUnit:GetDirVector()	
		bIsRight = pNPCUnit:GetIsRight()
		
		if bIsRight == true then
			vBonePos = MovePos( vBonePos, vDirVector, 230 )	
		else
			vBonePos = MovePos( vBonePos, vDirVector, -230 )	
		end
		
		vBonePos.y = vBonePos.y + 50.0
		
		landPos = pNPCUnit:GetLandPosition_LUA()
		pDamageEffect = pX2Game:GetDamageEffect()
		if pDamageEffect ~= nil then
		    pDamage = pDamageEffect:CreateInstance_LUA( pNPCUnit, "NASOD_ELEMENT_FIRE_FRAMEATTACK1", vBonePos, landPos.y )
		    pNPCUnit:SetDamageEffect_LUA(0, pDamage)
		end
		
		
	
	end
	
	if pNPCUnit:AnimEventTimer_LUA( 3.0 ) then
	
		vBonePos = pNPCUnit:GetBonePos_LUA("Dummy1_Rhand")	
		vDirVector = pNPCUnit:GetDirVector()	
		bIsRight = pNPCUnit:GetIsRight()
		
		if bIsRight == true then
			vBonePos = MovePos( vBonePos, vDirVector, 230 )	
		else
			vBonePos = MovePos( vBonePos, vDirVector, -230 )	
		end
		
		vBonePos.y = vBonePos.y + 50.0
		
		landPos = pNPCUnit:GetLandPosition_LUA()
		pDamageEffect = pX2Game:GetDamageEffect()
		if pDamageEffect ~= nil then
		    pDamage = pDamageEffect:CreateInstance_LUA( pNPCUnit, "NASOD_ELEMENT_FIRE_FRAMEATTACK2", vBonePos, landPos.y )
		    pNPCUnit:SetDamageEffect_LUA(1, pDamage)
        end		    
	
	    
	end
end

function NASOD_ELEMENT_FIRE_FLAME_ATTACK_STATE_END( pKTDXApp, pX2Game, pNPCUnit )
--[[    
    pParticle = pNPCUnit:GetMajorParticle_LUA( 0 )
	if pParticle ~= nil then
		pParticle:SetAutoDie()
		pNPCUnit:ClearMajorParticle_LUA( 0 )
	end
--]]	
	pEffect = pNPCUnit:GetDamageEffect_LUA( 0 )
	if pEffect ~= nil then
	
		pDamageEffect = pX2Game:GetDamageEffect()
		pDamageEffect:DestroyInstance( pEffect )
		
	end
	
	pNPCUnit:ClearDamageEffect_LUA( 0 )
	
	pEffect = pNPCUnit:GetDamageEffect_LUA( 1 )
	if pEffect ~= nil then
	
		pDamageEffect = pX2Game:GetDamageEffect()
		pDamageEffect:DestroyInstance( pEffect )
		
	end
	
	pNPCUnit:ClearDamageEffect_LUA( 1 )
	
	
end


function NASOD_ELEMENT_FIRE_SMALLMETE_STATE_START( pKTDXApp, pX2Game, pNPCUnit )
    meteoKind = (pNPCUnit:GetRandVal() % 3) + 1
    
            
    if meteoKind == 1 then
        NASOD_ELEMENT_FIRE_SMALLMETEO1_STATE_START( pKTDXApp, pX2Game, pNPCUnit )
        return
    end        
    
    if meteoKind == 2 then
        NASOD_ELEMENT_FIRE_SMALLMETEO2_STATE_START( pKTDXApp, pX2Game, pNPCUnit )
        return
    end        
    
    if meteoKind == 2 then
        NASOD_ELEMENT_FIRE_SMALLMETEO3_STATE_START( pKTDXApp, pX2Game, pNPCUnit )
        return
    end
    
    NASOD_ELEMENT_FIRE_SMALLMETEO1_STATE_START( pKTDXApp, pX2Game, pNPCUnit )
    
end

function NASOD_ELEMENT_FIRE_SMALLMETEO1_STATE_START( pKTDXApp, pX2Game, pNPCUnit )
    
    -- 메테오가 떨어질 위치를 결정한다.
    -- 술자 중심
    
    vDirVector	= pNPCUnit:GetDirVector()
    
	-- 1
	landPos1 = pNPCUnit:GetLandPosition_LUA()		
	landPos1 = MovePos(landPos1, vDirVector, -2200)
	
	posR = pX2Game:GetLineMap():GetRandomPositionDir( landPos1, 300, true, false )	
	--posR.y = posR.y + 1000
	--posR = pX2Game:GetLineMap():GetNearest_LUA(posR)	
	posR.y = posR.y + 1200.0	
	pNPCUnit:SetVector_LUA(0, posR)
	randInx = (pNPCUnit:GetRandVal() % 3) + 1 
	pNPCUnit:SetInt_LUA(0, randInx)
	
	-- 2
	landPos2 = pNPCUnit:GetLandPosition_LUA()
	landPos2 = MovePos(landPos2, vDirVector, -1500)
	
	posR = pX2Game:GetLineMap():GetRandomPositionDir( landPos2, 250, true, false )	
	--posR.y = posR.y + 1000
	--posR = pX2Game:GetLineMap():GetNearest_LUA(posR)	
	posR.y = posR.y + 1200.0	
	pNPCUnit:SetVector_LUA(1, posR)
	randInx = (pNPCUnit:GetRandVal() % 3) + 1
	pNPCUnit:SetInt_LUA(1, randInx)
	
	-- 3
	landPos3 = pNPCUnit:GetLandPosition_LUA()
	landPos3 = MovePos(landPos3, vDirVector, -900)
	
	posR = pX2Game:GetLineMap():GetRandomPositionDir( landPos3, 200, true, true )
	--posR.y = posR.y + 1000
	--posR = pX2Game:GetLineMap():GetNearest_LUA(posR)		
	posR.y = posR.y + 1200.0	
	pNPCUnit:SetVector_LUA(2, posR)
	randInx = (pNPCUnit:GetRandVal() % 3) + 1
	pNPCUnit:SetInt_LUA(2, randInx)	
	
	-- 4
	landPos4 = pNPCUnit:GetLandPosition_LUA()
	landPos4 = MovePos(landPos4, vDirVector, -200)
	
	posR = pX2Game:GetLineMap():GetRandomPositionDir( landPos4, 300, true, true )
	--posR.y = posR.y + 1000
	--posR = pX2Game:GetLineMap():GetNearest_LUA(posR)		
	posR.y = posR.y + 1200.0	
	pNPCUnit:SetVector_LUA(3, posR)	
	randInx = (pNPCUnit:GetRandVal() % 3) + 1
	pNPCUnit:SetInt_LUA(3, randInx)
	
end

function NASOD_ELEMENT_FIRE_SMALLMETEO2_STATE_START( pKTDXApp, pX2Game, pNPCUnit )
    
    -- 메테오가 떨어질 위치를 결정한다.
    -- 술자 전방
    isRight = pNPCUnit:GetIsRight()
    vDirVector	= pNPCUnit:GetDirVector()
    
    if pNPCUnit:GetIsRight() == true then
        vStep = 1300
    else
        vStep = -1300        
    end
    
	-- 1
	landPos1 = pNPCUnit:GetLandPosition_LUA()		
	landPos1 = MovePos(landPos1, vDirVector, -2200 + vStep)
	
	posR = pX2Game:GetLineMap():GetRandomPositionDir( landPos1, 300, true, false )	
	--posR.y = posR.y + 1000
	--posR = pX2Game:GetLineMap():GetNearest_LUA(posR)	
	posR.y = posR.y + 1200.0	
	pNPCUnit:SetVector_LUA(0, posR)
	randInx = (pNPCUnit:GetRandVal() % 3) + 1
	pNPCUnit:SetInt_LUA(0, randInx)
	
	-- 2
	landPos2 = pNPCUnit:GetLandPosition_LUA()
	landPos2 = MovePos(landPos2, vDirVector, -1500 + vStep)
	
	posR = pX2Game:GetLineMap():GetRandomPositionDir( landPos2, 250, true, false )	
	--posR.y = posR.y + 1000
	--posR = pX2Game:GetLineMap():GetNearest_LUA(posR)	
	posR.y = posR.y + 1200.0	
	pNPCUnit:SetVector_LUA(1, posR)
	randInx = (pNPCUnit:GetRandVal() % 3) + 1
	pNPCUnit:SetInt_LUA(1, randInx)
	
	-- 3
	landPos3 = pNPCUnit:GetLandPosition_LUA()
	landPos3 = MovePos(landPos3, vDirVector, -900 + vStep)
	
	posR = pX2Game:GetLineMap():GetRandomPositionDir( landPos3, 200, true, true )
	--posR.y = posR.y + 1000
	--posR = pX2Game:GetLineMap():GetNearest_LUA(posR)		
	posR.y = posR.y + 1200.0	
	pNPCUnit:SetVector_LUA(2, posR)
	randInx = (pNPCUnit:GetRandVal() % 3) + 1
	pNPCUnit:SetInt_LUA(2, randInx)	
	
	-- 4
	landPos4 = pNPCUnit:GetLandPosition_LUA()
	landPos4 = MovePos(landPos4, vDirVector, -200 + vStep)
	
	posR = pX2Game:GetLineMap():GetRandomPositionDir( landPos4, 300, true, true )	
	--posR.y = posR.y + 1000
	--posR = pX2Game:GetLineMap():GetNearest_LUA(posR)	
	posR.y = posR.y + 1200.0	
	pNPCUnit:SetVector_LUA(3, posR)	
	randInx = (pNPCUnit:GetRandVal() % 3) + 1
	pNPCUnit:SetInt_LUA(3, randInx)
	
end

function NASOD_ELEMENT_FIRE_SMALLMETEO3_STATE_START( pKTDXApp, pX2Game, pNPCUnit )
    
    -- 메테오가 떨어질 위치를 결정한다.
    -- 고르게 분포
    
    vDirVector	= pNPCUnit:GetDirVector()
    
	-- 1
	landPos1 = pNPCUnit:GetLandPosition_LUA()		
	landPos1 = MovePos(landPos1, vDirVector, -4000)	
	
	posR = pX2Game:GetLineMap():GetRandomPositionDir( landPos1, 300, true, false )	
	--posR.y = posR.y + 1000
	--posR = pX2Game:GetLineMap():GetNearest_LUA(posR)
	
	posR.y = posR.y + 1200.0	
	pNPCUnit:SetVector_LUA(0, posR)
	randInx = (pNPCUnit:GetRandVal() % 3) + 1
	pNPCUnit:SetInt_LUA(0, randInx)
	
	-- 2
	landPos2 = pNPCUnit:GetLandPosition_LUA()
	landPos2 = MovePos(landPos2, vDirVector, -2200)
	
	posR = pX2Game:GetLineMap():GetRandomPositionDir( landPos2, 250, true, false )		
	--posR.y = posR.y + 1000
	--posR = pX2Game:GetLineMap():GetNearest_LUA(posR)
	posR.y = posR.y + 1200.0	
	pNPCUnit:SetVector_LUA(1, posR)
	randInx = (pNPCUnit:GetRandVal() % 3) + 1
	pNPCUnit:SetInt_LUA(1, randInx)
	
	-- 3
	landPos3 = pNPCUnit:GetLandPosition_LUA()
	landPos3 = MovePos(landPos3, vDirVector, -200)
	
	posR = pX2Game:GetLineMap():GetRandomPositionDir( landPos3, 200, true, true )	
	--posR.y = posR.y + 1000
	--posR = pX2Game:GetLineMap():GetNearest_LUA(posR)
	posR.y = posR.y + 1200.0	
	pNPCUnit:SetVector_LUA(2, posR)
	randInx = (pNPCUnit:GetRandVal() % 3) + 1
	pNPCUnit:SetInt_LUA(2, randInx)	
	
	-- 4
	landPos4 = pNPCUnit:GetLandPosition_LUA()
	landPos4 = MovePos(landPos4, vDirVector, 1800)
	
	posR = pX2Game:GetLineMap():GetRandomPositionDir( landPos4, 300, true, true )
	--posR.y = posR.y + 1000
	--posR = pX2Game:GetLineMap():GetNearest_LUA(posR)
	posR.y = posR.y + 1200.0	
	pNPCUnit:SetVector_LUA(3, posR)	
	randInx = (pNPCUnit:GetRandVal() % 3) + 1
	pNPCUnit:SetInt_LUA(3, randInx)
	
end

function NASOD_ELEMENT_FIRE_SMALLMETEO1_FRAME_MOVE( pKTDXApp, pX2Game, pNPCUnit )

    pDamageEffect = pX2Game:GetDamageEffect()
    	
	landPos = pNPCUnit:GetLandPosition_LUA()	
	
	vRot = pNPCUnit:GetRotateDegree()
	if pNPCUnit:GetIsRight() == false then
		vRot.y = vRot.y + 180.0
	end
	    
	
    for i = 0, 3 do        
	    randInx = ((8 - pNPCUnit:GetInt_LUA(i)) * (i+pNPCUnit:GetInt_LUA(i))) % 3 + 1
	    
	    --print(randInx)
	        
	    if randInx == 1 then
	        if pNPCUnit:AnimEventTimer_LUA( 1.2 ) then 
	            posR = pNPCUnit:GetVector_LUA(i)
	            if pDamageEffect ~= nil then
		            pDamageEffect:CreateInstance_LUA2( pNPCUnit, "NASOD_ELEMENT_FIRE_SMALLMETEO2", posR, landPos.y, vRot)
		            pDamageEffect:CreateInstance_LUA2( pNPCUnit, "NASOD_ELEMENT_FIRE_SMALLMETEO1", posR, landPos.y, vRot )
                end		            
	        end
	    end
	    
	    if randInx == 2 then
	        if pNPCUnit:AnimEventTimer_LUA( 1.4 ) then
	            posR = pNPCUnit:GetVector_LUA(i)
	            if pDamageEffect ~= nil then
		            pDamageEffect:CreateInstance_LUA2( pNPCUnit, "NASOD_ELEMENT_FIRE_SMALLMETEO2", posR, landPos.y, vRot)
		            pDamageEffect:CreateInstance_LUA2( pNPCUnit, "NASOD_ELEMENT_FIRE_SMALLMETEO1", posR, landPos.y, vRot ) 
                end		            
	        end
	    end
	    
	    if randInx == 3 then
	        if pNPCUnit:AnimEventTimer_LUA( 1.6 ) then
	            posR = pNPCUnit:GetVector_LUA(i)
	            if pDamageEffect ~= nil then
		            pDamageEffect:CreateInstance_LUA2( pNPCUnit, "NASOD_ELEMENT_FIRE_SMALLMETEO2", posR, landPos.y, vRot)
		            pDamageEffect:CreateInstance_LUA2( pNPCUnit, "NASOD_ELEMENT_FIRE_SMALLMETEO1", posR, landPos.y, vRot ) 
                end		            
	        end
	    end	        
	end       
end


function NASOD_ELEMENT_FIRE_FRAMEWAVE_FRAME_MOVE( pKTDXApp, pX2Game, pNPCUnit )

    pX2Game:SetWorldColor_LUA( D3DXCOLOR(0.2,0.2,0.2,1) )
		
    if pNPCUnit:AnimEventTimer_LUA( 0.73 ) then	
        
        if GetDistance_LUA( pNPCUnit:GetPos(), pX2Game:GetFocusUnitPos_LUA() ) < 1200 then
		    pX2Game:GetX2Camera():GetCamera():UpDownCrashCameraNoReset( 5.0, 0.3 )
	    end		
    end	    


    if pNPCUnit:AnimEventTimer_LUA( 0.733 ) then
        pDamageEffect = pX2Game:GetDamageEffect()
        landPos = pNPCUnit:GetLandPosition_LUA()	
	    vPos = pNPCUnit:GetPos()
	    vPos.y = vPos.y + 240
	    vRot1 = pNPCUnit:GetRotateDegree()
	    vRot2 = pNPCUnit:GetRotateDegree()
	    if pNPCUnit:GetIsRight() == false then
		    vRot2.y = vRot2.y + 180.0
        else
            vRot1.y = vRot1.y + 180.0		    
	    end        
        
        if pDamageEffect ~= nil then	
            pDamageEffect:CreateInstance_LUA2( pNPCUnit, "NASOD_ELEMENT_FIRE_FLAMEWAVE_RIGHT", vPos, landPos.y, vRot1)    -- right
            pDamageEffect:CreateInstance_LUA2( pNPCUnit, "NASOD_ELEMENT_FIRE_FLAMEWAVE_LEFT",  vPos, landPos.y, vRot2)    -- left                       
        end            
    end    
    
    if pNPCUnit:AnimEventTimer_LUA( 0.8 ) then
        pDamageEffect = pX2Game:GetDamageEffect()
        landPos = pNPCUnit:GetLandPosition_LUA()	
	    vPos1 = pNPCUnit:GetPos()
	    vPos2 = pNPCUnit:GetPos()
	    vPos1.x = vPos1.x - 220
	    vPos1.y = vPos1.y + 220
	    vPos2.x = vPos2.x + 220
	    vPos2.y = vPos2.y + 220
	    
	    vRot1 = pNPCUnit:GetRotateDegree()  
	    vRot2 = pNPCUnit:GetRotateDegree()
	    if pNPCUnit:GetIsRight() == false then	        
		    vRot2.y = vRot2.y + 180.0
        else            
            vRot1.y = vRot1.y + 180.0		    
	    end   	    
        
        if pDamageEffect ~= nil then	
            pDamageEffect:CreateInstance_LUA2( pNPCUnit, "NASOD_ELEMENT_FLAMEWAVE_TAIL", vPos1, landPos.y, vRot1)    -- right
            pDamageEffect:CreateInstance_LUA2( pNPCUnit, "NASOD_ELEMENT_FLAMEWAVE_TAIL", vPos2, landPos.y, vRot2)    -- left                        
        end            
        
        --pNPCUnit:SetNowMP(0)
    end 

end


function NASOD_ELEMENT_FIRE_PERFECTSTORM_FRAME_MOVE( pKTDXApp, pX2Game, pNPCUnit )
    
    pX2Game:SetWorldColor_LUA( D3DXCOLOR(0.2,0.2,0.2,1) )
    
    if pNPCUnit:AnimEventTimer_LUA( 0.3 ) then
        pMajorParticle = pX2Game:GetMajorParticle()
        vPos = pNPCUnit:GetPos()
        if pNPCUnit:GetIsRight() == false then
            vPos.x = vPos.x - 250
        else            
            vPos.x = vPos.x + 250
        end  
        vPos.y = vPos.y + 1
            
        if pMajorParticle ~= nil then
		    pMajorParticle:GameUnitCreateSequence_LUA( pNPCUnit, "Flare_Nasod_Element_Fire_PerfectStrom02", vPos, D3DXVECTOR2(-1,-1), D3DXVECTOR2(-1,-1) )
        end		
    
        --pNPCUnit:SetNowMP(0)
	end
	
    if pNPCUnit:AnimEventTimer_LUA( 0.9 ) then
        pDamageEffect = pX2Game:GetDamageEffect()
        pMajorParticle = pX2Game:GetMajorParticle()
        
        vRot = pNPCUnit:GetRotateDegree()
	    if pNPCUnit:GetIsRight() == false then	        
		    vRot.y = vRot.y + 180.0            
	    end   	    
        landPos = pNPCUnit:GetLandPosition_LUA()	
        vPos = pNPCUnit:GetPos()
        vPosCenter = pNPCUnit:GetPos()
        
        vPosCenter.z = vPosCenter.z + 200
        
        if pNPCUnit:GetIsRight() == false then
            vPos.x = vPos.x - 250
            vPosCenter.x = vPosCenter.x - 250  
        else            
            vPos.x = vPos.x + 250
            vPosCenter.x = vPosCenter.x + 250                   
        end  
        
        
        if pDamageEffect ~= nil then	
            if pNPCUnit:GetIsRight() == false then
                pDamageEffect:CreateInstance_LUA( pNPCUnit, "NASOD_ELEMENT_FIRE_PERFECTSTORM", vPos, landPos.y) 
                
                if pMajorParticle ~= nil then
		            pMajorParticle:GameUnitCreateSequence_LUA( pNPCUnit, "Flare_Nasod_Element_Fire_PerfectStrom01", vPosCenter, D3DXVECTOR2(-1,-1), D3DXVECTOR2(-1,-1) )
                end		            
            else
                pDamageEffect:CreateInstance_LUA( pNPCUnit, "NASOD_ELEMENT_FIRE_PERFECTSTORM", vPos, landPos.y)
                
                if pMajorParticle ~= nil then
		            pMajorParticle:GameUnitCreateSequence_LUA( pNPCUnit, "Flare_Nasod_Element_Fire_PerfectStrom01", vPosCenter, D3DXVECTOR2(-1,-1), D3DXVECTOR2(-1,-1) )
                end		            
            end                                    
        end           
    end        
end

function NASOD_ELEMENT_FIRE_COMMON_FRAME_MOVE( pKTDXApp, pX2Game, pNPCUnit )
   
    if pNPCUnit:GetNowHP() <= 0 then
        
	    return
    end
   
    bLiveBarrierMachineIce = false
    nUnitListSize = pX2Game:GetNPCUnitListSize() 

    for i=0, nUnitListSize-1 do         		
	    pUnit = pX2Game:GetNPCUnit( i )
	    if pUnit ~= nil then		    
		    if pUnit:IsUnitID(NPC_UNIT_ID["NUI_BARRIERMACHINE_FIRE"]) == true and pUnit:GetFlag_LUA(3) == true then
		        bLiveBarrierMachineIce = true
		        break
		    end
        end 
    end

    if bLiveBarrierMachineIce == true then
        pNPCUnit:SetSuperArmor(true)
    end        



    bDamage = pNPCUnit:GetDamagedThisFrame()        
    if bDamage == true and bLiveBarrierMachineIce == true then
        
        --pNPCUnit:SetSuperArmor(true)                    
        pMajorParticle1 = pX2Game:GetMajorParticle() 
                
        if pMajorParticle1 ~= nil then
                    
            vPos = pNPCUnit:GetPos()
            vPos.y = vPos.y + 180                        
            vRotateDegree	= pNPCUnit:GetRotateDegree()                
            
            if pNPCUnit:GetAttackFront() == false then
                vRotateDegree.y = vRotateDegree.y + 180
            end
                        
                        
            pParticle1 = pNPCUnit:GetMajorParticle_LUA(1)                                            
            
            if pParticle1 ~= nil then
                if pMajorParticle1:IsLiveInstance( pParticle1 ) == true then
                    		
		            pParticle1:SetPosition( vPos ) 
        		    
		            pParticle1:SetAddRotate( vRotateDegree )
		            pParticle1:SetAxisAngle( vRotateDegree )	   
		        else
		            pNPCUnit:ClearMajorParticle_LUA( 1 )
		        end
        		
            else  
                                    
                pParticle1 = pMajorParticle1:GameUnitCreateSequence_LUA( pNPCUnit, "Count_Barrier01", vPos, D3DXVECTOR2(-1,-1), D3DXVECTOR2(1,-1) )
                if pParticle1 ~= nil then 
                
					pParticle1:SetAddRotate( vRotateDegree )
					pParticle1:SetAxisAngle( vRotateDegree )
					pNPCUnit:SetMajorParticle_LUA(1, pParticle1:GetHandle() )
				end 
            end                                                


            pNPCUnit:PlaySound_LUA( "Nasod_Element_BarrierHit.ogg" )
            -- 배리어 효과음(?)
            
        end
        
    end
end

function NASOD_ELEMENT_FIRE_TELEPORT_STATE_START( pKTDXApp, pX2Game, pNPCUnit )

    -- 텔레포트 (사라질때) 
    pNPCUnit:PlaySound_LUA( "Nasod_Element_Teleport.ogg" )
    
    pos = pNPCUnit:GetPos()
    rotDegree 	= pNPCUnit:GetRotateDegree()
    pMinorXMeshPlayer = pX2Game:GetMinorXMeshPlayer()          
   
   rotDegree.y = 0
    
    if pMinorXMeshPlayer ~= nil then
        pMeshPlayer = pMinorXMeshPlayer:CreateInstance_LUA( "RespawnLanding01", pos, rotDegree, rotDegree, 14 )        
        if pMeshPlayer ~= nil then
            pMeshPlayer:SetManualSize(2.0, 2.0, 2.0)
        end    
        pMeshPlayer = pMinorXMeshPlayer:CreateInstance_LUA( "RespawnLanding02", pos, rotDegree, rotDegree, 14 )        
        if pMeshPlayer ~= nil then
            pMeshPlayer:SetManualSize(2.0, 2.0, 2.0)
        end
    end
end

function NASOD_ELEMENT_FIRE_TELEPORT_FRAME_MOVE( pKTDXApp, pX2Game, pNPCUnit )
    
    if pNPCUnit:AnimEventTimer_LUA( 0.8 ) then
        nUnitListSize = pX2Game:GetNPCUnitListSize()    	
    	
	    pUID = pX2Game:GetNearNPCUnitUID_LUA( pNPCUnit:GetPos(), NPC_UNIT_ID["NUI_BARRIERMACHINE_FIRE"], 999999 )
    	
	    if pUID ~= 0 then
    	
	        for i=0, nUnitListSize-1 do 
        		
		        pUnit = pX2Game:GetNPCUnit( i )
        		
		        if pUnit ~= nil then
		            if pUnit:GetUID() == pUID then    		
	                    --pNPCUnit:SetShow(false)
	                    vSummonPos = pX2Game:GetLineMap():GetStartPosition( 5 )	   
	                    vSummonPos.y = vSummonPos.y + 150                 
	                    pNPCUnit:SetPosition(vSummonPos, true) 
                        return
                    end
                end	            
            end	             
        end		            
    end
end

function NASOD_ELEMENT_FIRE_START_CAMERA_MOVE( pKTDXApp, pX2Game, pNPCUnit )

	pos = pNPCUnit:GetBonePos_LUA("Bip01_Head")	
	camera = pX2Game:GetX2Camera()
	camera:PartsLookDirectCamera_LUA( pNPCUnit, pos, D3DXVECTOR3( 500, -50, -20 ), D3DXVECTOR2( 0,0 ) )

end
------------------------------------------------------------------------------
-- UTIL FUNCTION
------------------------------------------------------------------------------

------------------------------------------------------------------------------
function MovePos( pos, dirvector, dist )
	
	pos.x = pos.x + dist * dirvector.x
	pos.y = pos.y + dist * dirvector.y
	pos.z = pos.z + dist * dirvector.z
	
	return pos
	
end
