-- lua header. UTF-8 인코딩 인식을 위해 이 줄은 지우지 마세요.



-- Nasod_Rail_Cart.lua



INIT_SYSTEM = 
{
	UNIT_WIDTH		= 180.0,
	UNIT_HEIGHT		= 100.0,
	UNIT_LAYER		= X2_LAYER["XL_UNIT_0"],
	
	UNIT_SCALE		= 0.85,
	
	RENDER_PARAM	= RENDER_TYPE["RT_CARTOON"],
}


INIT_DEVICE = 
{
	READY_TEXTURE = 
	{
	},
	
	READY_SOUND = 
	{
        "Cart_Break.ogg",		
	},
}

INIT_MOTION = 
{
	MOTION_FILE_NAME		= "Motion_Nasod_Railer_Cart.X",
	MOTION_CHANGE_TEX_XET	= "Motion_Nasod_Railer_Cart_Event_Tree_day.xet",
	
}

INIT_PHYSIC = 
{
	RELOAD_ACCEL		= 2000,
	G_ACCEL				= 0,
	MAX_G_SPEED			= 0,
	
	WALK_SPEED			= 0,
	RUN_SPEED			= 0,
	JUMP_SPEED			= 0,
	DASH_JUMP_SPEED		= 0,
}


INIT_COMPONENT = 
{
	MAX_HP				= 1000,
	MP_CHANGE_RATE		= 0,
	MP_CHARGE_RATE		= 0,
	
	USE_SLASH_TRACE		= FALSE,
	
	SHADOW_SIZE			= 0,
	SHADOW_FILE_NAME	= "shadow.dds",
	
	SMALL_HP_BAR_BLUE	= "Small_HP_bar_Blue.TGA",
	SMALL_HP_BAR_RED	= "Small_HP_bar_Red.TGA",
	--SMALL_HP_BAR_YELLOW = "Small_HP_bar_Yellow.TGA",
	
	QUESTION_MARK_SEQ		= "",
	EXCLAMATION_MARK_SEQ	= "",
	
	HEAD_BONE_NAME			= "Object01",
	
	HYPER_MODE_COUNT	= 0,
	MAX_HYPER_MODE_TIME	= 30,
	
	HITTED_TYPE			= HITTED_TYPE["HTD_WOOD"],
	
	DAMAGE_DOWN         = FALSE,
	
	DIE_FLY             = 0,
	
	NOT_EXTRA_DAMAGE	= TRUE,
}




INIT_STATE = 
{
	{ STATE_NAME = "NASOD_RAIL_CART_WAIT",					},
	
	--리액션 관련
	{ STATE_NAME = "NASOD_RAIL_CART_DAMAGE",				},	
	{ STATE_NAME = "NASOD_RAIL_CART_DYING",					},
	
	START_STATE					= "NASOD_RAIL_CART_WAIT",
	
	SMALL_DAMAGE_LAND_FRONT		= "NASOD_RAIL_CART_DAMAGE",
	SMALL_DAMAGE_LAND_BACK		= "NASOD_RAIL_CART_DAMAGE",
	BIG_DAMAGE_LAND_FRONT		= "NASOD_RAIL_CART_DAMAGE",
	BIG_DAMAGE_LAND_BACK		= "NASOD_RAIL_CART_DAMAGE",
	DOWN_DAMAGE_LAND_FRONT		= "NASOD_RAIL_CART_DAMAGE",
	DOWN_DAMAGE_LAND_BACK		= "NASOD_RAIL_CART_DAMAGE",
	FLY_DAMAGE_FRONT			= "NASOD_RAIL_CART_DAMAGE",
	FLY_DAMAGE_BACK				= "NASOD_RAIL_CART_DAMAGE",
	SMALL_DAMAGE_AIR			= "NASOD_RAIL_CART_DAMAGE",	
	BIG_DAMAGE_AIR				= "NASOD_RAIL_CART_DAMAGE",
	DOWN_DAMAGE_AIR				= "NASOD_RAIL_CART_DAMAGE",
	UP_DAMAGE					= "NASOD_RAIL_CART_DAMAGE",
	DAMAGE_REVENGE				= "NASOD_RAIL_CART_DAMAGE",
	
	DYING_LAND_FRONT			= "NASOD_RAIL_CART_DYING",
	DYING_LAND_BACK				= "NASOD_RAIL_CART_DYING",
	DYING_SKY					= "NASOD_RAIL_CART_DYING",

	REVENGE_ATTACK				= "",	
}

INIT_AI = 
{
	TARGET = 
	{
		TARGET_PRIORITY 			= TARGET_PRIORITY["TP_LOW_HP_FIRST"],
		TARGET_INTERVAL				= 99999,	-- sec
		TARGET_NEAR_RANGE			= 0,		-- 이 거리보다 가까우면 TARGET_SUCCESS_RATE에 관계없이 무조건 타게팅된다
		TARGET_RANGE				= 0,		-- cm
		TARGET_LOST_RANGE			= 0,		-- cm
		TARGET_SUCCESS_RATE			= 0,		-- %
		ATTACK_TARGET_RATE			= 0,		-- 나를 공격한 유닛을 타게팅할 확률
		PRESERVE_LAST_TARGET_RATE	= 0,		-- 이전에 타게팅된 유닛을 계속 타게팅할 확률
	},

	CHASE_MOVE = 
	{		
		DEST_GAP			= 150,	-- 목적지에서 이 거리 안에 있으면 도착했다고 판단한다
		MOVE_GAP			= 160,
		
		DIR_CHANGE_INTERVAL = 0.7,
		
		MOVE_SPLIT_RANGE	= 600,
		WALK_INTERVAL		= 3,
		NEAR_WALK_RATE		= 100,   --  70,
		FAR_WALK_RATE		= 100,   -- 30,
		
		JUMP_INTERVAL		= 5,
		UP_JUMP_RATE		= 100, -- 40,
		UP_DOWN_RATE		= 20,
		DOWN_JUMP_RATE		= 100,    --  20,
		DOWN_DOWN_RATE		= 40,
	},	
	
	PATROL_MOVE = 	
	{
		PATROL_BEGIN_RATE		= 100, --50,		
		PATROL_RANGE			= 300,
		PATROL_COOL_TIME		= 1,
		ONLY_THIS_LINE_GROUP	= TRUE,
	},
	
	ESCAPE_MOVE = 
	{		
		MOVE_SPLIT_RANGE	= 500,	-- cm
		ESCAPE_GAP			= 600,	-- 이 거리 보다 멀어지면 도망 성공
		
		WALK_INTERVAL		= 1,	-- 초
		NEAR_WALK_RATE		= 100,   --  10,
		FAR_WALK_RATE		= 100,   -- 10,
		
		JUMP_INTERVAL		= 10,
		UP_JUMP_RATE		= 100, -- 30,
		UP_DOWN_RATE		= 30,
		DOWN_JUMP_RATE		= 100,    --  30,
		DOWN_DOWN_RATE		= 30,
	},
	
	ESCAPE_CONDITION = 
	{
		RATE				= 100, -- 50,
		MY_HP				= 20,		-- %, 전체 HP에 대해 현재 HP의 비율
		ESCAPE_RANGE		= 600,		-- 이 범위 안에 들어오면 타격당하지 않아도 RATE에 지정된 확률로 도망
	}
}


NASOD_RAIL_CART_WAIT = 
{
	ANIM_NAME					= "Wait",
	PLAY_TYPE					= XSKIN_ANIM_PLAYTYPE["XAP_ONE_WAIT"],
	TRANSITION					= FALSE,
	LAND_CONNECT				= TRUE,
	
	CAN_PUSH_UNIT				= FALSE,
	CAN_PASS_UNIT				= FALSE,	
	
	PASSIVE_SPEED_X				= 0,
	PASSIVE_SPEED_Y				= 0,
	
	NEVER_MOVE					= TRUE,
		
}

NASOD_RAIL_CART_DAMAGE =
{
	ANIM_NAME					= "Damage",
	PLAY_TYPE					= XSKIN_ANIM_PLAYTYPE["XAP_ONE_WAIT"],
	TRANSITION					= TRUE,
	LAND_CONNECT				= TRUE,
	
	CAN_PUSH_UNIT				= FALSE,
	CAN_PASS_UNIT				= FALSE,	
	
	PASSIVE_SPEED_X				= 0,
	PASSIVE_SPEED_Y				= 0,
	
	NEVER_MOVE					= TRUE,
	
	EVENT_PROCESS = 
	{
		{ STATE_CHANGE_TYPE["SCT_MOTION_END"],					"NASOD_RAIL_CART_WAIT",				},
	},
}

NASOD_RAIL_CART_DYING = 
{
	ANIM_NAME					= "Broken",
	PLAY_TYPE					= XSKIN_ANIM_PLAYTYPE["XAP_ONE_WAIT"],
	TRANSITION					= FALSE,
	LAND_CONNECT				= TRUE,
	

	INVINCIBLE					= { 0, 100, }, 		
	
	CAN_PUSH_UNIT				= FALSE,
	CAN_PASS_UNIT				= TRUE,

    SOUND_PLAY0			= { 0.01, "Cart_Break.ogg" },
	
	NEVER_MOVE					= TRUE,
	DYING_END					= TRUE,
	
	IMMADIATE_PACKET_SEND		= TRUE,
}
	





