-- lua header. UTF-8 인코딩 인식을 위해 이 줄은 지우지 마세요.


INIT_SYSTEM = 
{
	UNIT_WIDTH		= 220.0,
	UNIT_HEIGHT		= 100.0,
	UNIT_LAYER		= X2_LAYER["XL_UNIT_0"],
	UNIT_SCALE		 = 1.3,
	
}


INIT_DEVICE = 
{
	READY_TEXTURE = 
	{
	},
	
	READY_SOUND = 
	{
		"DashEnd.ogg",
	},
}

INIT_MOTION = 
{
	MOTION_FILE_NAME		= "Motion_peng_santa.x",
}

INIT_PHYSIC = 
{
	RELOAD_ACCEL		= 2000,
	G_ACCEL				= 4000,
	MAX_G_SPEED			= -2000,
	
	WALK_SPEED			= 400,
	RUN_SPEED			= 600,
	JUMP_SPEED			= 1500,
	DASH_JUMP_SPEED		= 2300,
}


INIT_COMPONENT = 
{
	
	MP_CHANGE_RATE		= 1,
	MP_CHARGE_RATE		= 130,
	
	
	SHADOW_SIZE			= 200,
	SHADOW_FILE_NAME	= "shadow.dds",
	
	SMALL_HP_BAR_BLUE	= "Small_HP_bar_Blue.TGA",
	SMALL_HP_BAR_RED	= "Small_HP_bar_Red.TGA",
	SMALL_HP_BAR_YELLOW = "Small_HP_bar_Yellow.TGA",
	
	QUESTION_MARK_SEQ		= "QuestionMarkNPC",
	EXCLAMATION_MARK_SEQ	= "ExclamationMarkNPC",
	
	HYPER_MODE_COUNT	= 0,
	MAX_HYPER_MODE_TIME	= 30,
	
	HITTED_TYPE			= HITTED_TYPE["HTD_MEAT"],

	FALL_DOWN			= TRUE,
	
	DAMAGE_DOWN         = FALSE,

	SUMMON_TIME			= 5400,

}

INIT_STATE = 
{

	{ STATE_NAME = "PENG_SANTA_START",						},
	{ STATE_NAME = "PENG_SANTA_WAIT",						},
	{ STATE_NAME = "PENG_SANTA_WALK",						LUA_STATE_END_FUNC = "PENG_SANTA_WALK_STATE_END"						},
	{ STATE_NAME = "PENG_SANTA_JUMP_UP",					},
	{ STATE_NAME = "PENG_SANTA_JUMP_DOWN",					LUA_STATE_END_FUNC = "PENG_SANTA_JUMP_DOWN_STATE_END" },
	{ STATE_NAME = "PENG_SANTA_JUMP_UP_DIR",				},
	{ STATE_NAME = "PENG_SANTA_JUMP_DOWN_DIR",				LUA_STATE_END_FUNC = "PENG_SANTA_JUMP_DOWN_DIR_STATE_END" },
	{ STATE_NAME = "PENG_SANTA_JUMP_LANDING",				},
	{ STATE_NAME = "PENG_SANTA_DASH",						},
	{ STATE_NAME = "PENG_SANTA_DASH_END",					},
	
	--리액션 관련
	{ STATE_NAME = "PENG_SANTA_DAMAGE",						LUA_FRAME_MOVE_FUNC = "PENG_SANTA_DAMAGE_FRAME_MOVE"			},
	{ STATE_NAME = "PENG_SANTA_DAMAGE_AIR",				},
	
	{ STATE_NAME = "PENG_SANTA_DYING",						LUA_STATE_START_FUNC = "PENG_SANTA_DYING_STATE_START", },
	
	START_STATE					= "PENG_SANTA_START",
	WAIT_STATE					= "PENG_SANTA_WAIT",
	
	SMALL_DAMAGE_LAND_FRONT		= "PENG_SANTA_DAMAGE",
	SMALL_DAMAGE_LAND_BACK		= "PENG_SANTA_DAMAGE",
	BIG_DAMAGE_LAND_FRONT		= "PENG_SANTA_DAMAGE",
	BIG_DAMAGE_LAND_BACK		= "PENG_SANTA_DAMAGE",
	
	-- fix!! 안넘어지게 테스트
	DOWN_DAMAGE_LAND_FRONT		= "PENG_SANTA_DAMAGE",
	DOWN_DAMAGE_LAND_BACK		= "PENG_SANTA_DAMAGE",
	
	FLY_DAMAGE_FRONT			= "PENG_SANTA_DAMAGE",
	FLY_DAMAGE_BACK				= "PENG_SANTA_DAMAGE",
	SMALL_DAMAGE_AIR			= "PENG_SANTA_DAMAGE_AIR",
	BIG_DAMAGE_AIR				= "PENG_SANTA_DAMAGE_AIR",
	DOWN_DAMAGE_AIR				= "PENG_SANTA_DAMAGE_AIR",
	DOWN_DAMAGE_AIR_LANDING		= "PENG_SANTA_DAMAGE",
	UP_DAMAGE					= "PENG_SANTA_DAMAGE",
	DAMAGE_REVENGE				= "PENG_SANTA_DAMAGE",
	
	DYING_LAND_FRONT			= "PENG_SANTA_DYING",
	DYING_LAND_BACK				= "PENG_SANTA_DYING",
	DYING_SKY					= "PENG_SANTA_DYING",

	REVENGE_ATTACK				= "",	
}

INIT_AI = 
{
	ALLY = 
	{
		FAR_LOST_RANGE	= 1000,			-- 이 거리보다 멀어지면 유저 옆으로 텔레포트
		LOST_RANGE		= 1000,			-- 이 거리보다 멀어지면 유저 쪽으로 걸어감
	},

	TARGET =
	{
		TARGET_PRIORITY 			= TARGET_PRIORITY["TP_NEAR_FIRST"],
		TARGET_INTERVAL 			= 2,
		TARGET_NEAR_RANGE 			= 1000,
		TARGET_RANGE 				= 2000,
		TARGET_LOST_RANGE 			= 5000,
		TARGET_SUCCESS_RATE 		= 0,
		ATTACK_TARGET_RATE 			= 0,
		PRESERVE_LAST_TARGET_RATE 	= 0,
	},
	
	CHASE_MOVE = 
	{		
		MOVE_SPLIT_RANGE	= 400,
		DEST_GAP			= 300,	-- 목적지에서 이 거리 안에 있으면 도착했다고 판단한다
		MOVE_GAP			= 500,
		
		DIR_CHANGE_INTERVAL = 0.5,
		
		WALK_INTERVAL		= 0.5,
		NEAR_WALK_RATE		= 100,   --  70,
		FAR_WALK_RATE		= 100,   -- 30,
		
		JUMP_INTERVAL		= 0.5,
		UP_JUMP_RATE		= 100, -- 40,
		UP_DOWN_RATE		= 20,
		DOWN_JUMP_RATE		= 100,    --  20,
		DOWN_DOWN_RATE		= 40,
		
		LINE_END_RANGE		= 80,	-- cm
	},	
}



PENG_SANTA_START =
{
	ANIM_NAME					= "Wait",
	PLAY_TYPE					= XSKIN_ANIM_PLAYTYPE["XAP_ONE_WAIT"],
	TRANSITION					= TRUE,
	
	CAN_PUSH_UNIT				= TRUE,
	CAN_PASS_UNIT				= FALSE,	

	SPEED_X						= 0,
	SPEED_Y						= 0,
	
	
	
	IMMADIATE_PACKET_SEND		= TRUE,	
	
	EVENT_PROCESS = 
	{		
		{ STATE_CHANGE_TYPE["SCT_CONDITION_TABLE"],		"PENG_SANTA_WAIT",				"CT_PENG_SANTA_WAIT"				},
	},
	
	CT_PENG_SANTA_WAIT = 
	{
		STATE_TIME_OVER				= 3,
	},
	
	TALK_BOX =
	{
		{ RATE = 100, MESSAGE = STR_ID_29050 },
	},
}


PENG_SANTA_WAIT = 
{
	ANIM_NAME					= "Wait",
	PLAY_TYPE					= XSKIN_ANIM_PLAYTYPE["XAP_LOOP"],
	TRANSITION					= TRUE,
	
	CAN_PUSH_UNIT				= TRUE,
	CAN_PASS_UNIT				= FALSE,	
	
	SPEED_X						= 0,
	SPEED_Y						= 0,
	
	IMMADIATE_PACKET_SEND		= TRUE,
	EVENT_INTERVAL_TIME0		= 2,
	
	EVENT_PROCESS = 
	{		
		{ STATE_CHANGE_TYPE["SCT_FOOT_ON_LINE_FALSE_DOWN"],	"PENG_SANTA_JUMP_DOWN",					},
		
		{ STATE_CHANGE_TYPE["SCT_AI_WALK"],					"PENG_SANTA_WALK",						},
		{ STATE_CHANGE_TYPE["SCT_AI_DASH"],					"PENG_SANTA_DASH",						},
		{ STATE_CHANGE_TYPE["SCT_AI_JUMP"],					"PENG_SANTA_JUMP_UP",						},
		{ STATE_CHANGE_TYPE["SCT_AI_JUMP_DIR"],				"PENG_SANTA_JUMP_UP_DIR",					},
		{ STATE_CHANGE_TYPE["SCT_AI_DOWN"],					"PENG_SANTA_JUMP_DOWN",					},
		{ STATE_CHANGE_TYPE["SCT_AI_DOWN_DIR"],				"PENG_SANTA_JUMP_DOWN_DIR",				},
	},
}

PENG_SANTA_WALK = 
{
	ANIM_NAME					= "Dash",
	PLAY_TYPE					= XSKIN_ANIM_PLAYTYPE["XAP_LOOP"],
	TRANSITION					= TRUE,
	
	CAN_PUSH_UNIT				= TRUE,
	CAN_PASS_UNIT				= FALSE,
	
	PASSIVE_SPEED_X				= INIT_PHYSIC["RUN_SPEED"],
	
	ALLOW_DIR_CHANGE			= TRUE,
	IMMADIATE_PACKET_SEND		= TRUE,
	
	EVENT_INTERVAL_TIME0		= 2,
	
	EVENT_PROCESS = 
	{		
		{ STATE_CHANGE_TYPE["SCT_FOOT_ON_LINE_FALSE_DOWN"],	"PENG_SANTA_JUMP_DOWN_DIR",				},
		
		{ STATE_CHANGE_TYPE["SCT_AI_WAIT"],					"PENG_SANTA_WAIT",						},
		{ STATE_CHANGE_TYPE["SCT_AI_DASH"],					"PENG_SANTA_DASH",						},
		{ STATE_CHANGE_TYPE["SCT_AI_JUMP"],					"PENG_SANTA_JUMP_UP",					},
		{ STATE_CHANGE_TYPE["SCT_AI_JUMP_DIR"],				"PENG_SANTA_JUMP_UP_DIR",				},
		{ STATE_CHANGE_TYPE["SCT_AI_DOWN"],					"PENG_SANTA_JUMP_DOWN",					},
		{ STATE_CHANGE_TYPE["SCT_AI_DOWN_DIR"],				"PENG_SANTA_JUMP_DOWN_DIR",				},
	},
	
}

PENG_SANTA_JUMP_UP = 
{
	ANIM_NAME					= "JumpUp",
	PLAY_TYPE					= XSKIN_ANIM_PLAYTYPE["XAP_LOOP"],
	TRANSITION					= TRUE,
	LAND_CONNECT				= FALSE,
	
	CAN_PUSH_UNIT				= TRUE,
	CAN_PASS_UNIT				= FALSE,
	
	SPEED_X						= 0,
	SPEED_Y						= INIT_PHYSIC["JUMP_SPEED"],
	ADD_POS_Y					= 45,
	
	IMMADIATE_PACKET_SEND		= TRUE,
	
	EVENT_PROCESS = 
	{		
		{ STATE_CHANGE_TYPE["SCT_NEGATIVE_Y_SPEED"],		"PENG_SANTA_JUMP_DOWN",				},
	},

}

PENG_SANTA_JUMP_DOWN = 
{
	ANIM_NAME					= "JumpDown",
	PLAY_TYPE					= XSKIN_ANIM_PLAYTYPE["XAP_LOOP"],
	TRANSITION					= TRUE,
	LAND_CONNECT				= FALSE,
	
	CAN_PUSH_UNIT				= TRUE,
	CAN_PASS_UNIT				= FALSE,
	
	
	
	IMMADIATE_PACKET_SEND		= TRUE,
		
	EVENT_PROCESS = 
	{		
		{ STATE_CHANGE_TYPE["SCT_FOOT_ON_LINE_TRUE"],		"PENG_SANTA_JUMP_LANDING",				},
	},
}

PENG_SANTA_JUMP_UP_DIR = 
{
	ANIM_NAME					= "JumpUp",
	PLAY_TYPE					= XSKIN_ANIM_PLAYTYPE["XAP_LOOP"],
	TRANSITION					= TRUE,
	LAND_CONNECT				= FALSE,
	
	CAN_PUSH_UNIT				= TRUE,
	CAN_PASS_UNIT				= FALSE,
	
	PASSIVE_SPEED_X				= INIT_PHYSIC["WALK_SPEED"],
	SPEED_Y						= INIT_PHYSIC["JUMP_SPEED"],
	ADD_POS_Y					= 45,
	
	IMMADIATE_PACKET_SEND		= TRUE,
	
	EVENT_PROCESS = 
	{		
		{ STATE_CHANGE_TYPE["SCT_NEGATIVE_Y_SPEED"],		"PENG_SANTA_JUMP_DOWN_DIR",				},
	},
	
}

PENG_SANTA_JUMP_DOWN_DIR = 
{
	ANIM_NAME					= "JumpDown",
	PLAY_TYPE					= XSKIN_ANIM_PLAYTYPE["XAP_LOOP"],
	TRANSITION					= TRUE,
	LAND_CONNECT				= FALSE,
	
	CAN_PUSH_UNIT				= TRUE,
	CAN_PASS_UNIT				= FALSE,
	
	
	
	PASSIVE_SPEED_X				= INIT_PHYSIC["WALK_SPEED"],
	
	IMMADIATE_PACKET_SEND		= TRUE,
		
	EVENT_PROCESS = 
	{		
		{ STATE_CHANGE_TYPE["SCT_FOOT_ON_LINE_TRUE"],		"PENG_SANTA_JUMP_LANDING",				},
	},
}

PENG_SANTA_JUMP_LANDING = 
{
	ANIM_NAME					= "JumpDownLanding",
	PLAY_TYPE					= XSKIN_ANIM_PLAYTYPE["XAP_ONE_WAIT"],
	TRANSITION					= TRUE,
	LAND_CONNECT				= FALSE,
	
	CAN_PUSH_UNIT				= TRUE,
	CAN_PASS_UNIT				= FALSE,

	SOUND_PLAY0					= { 0.093, "JumpLand.ogg" },
	
	SPEED_X						= 0,
	SPEED_Y						= 0,
		
	IMMADIATE_PACKET_SEND		= TRUE,

	EVENT_PROCESS = 
	{		
		{ STATE_CHANGE_TYPE["SCT_FOOT_ON_LINE_FALSE_DOWN"],	"PENG_SANTA_JUMP_DOWN",				},
		{ STATE_CHANGE_TYPE["SCT_MOTION_END"],				"PENG_SANTA_WAIT",					},
	},
}


PENG_SANTA_DASH =
{
	ANIM_NAME					= "Dash",
	PLAY_TYPE					= XSKIN_ANIM_PLAYTYPE["XAP_LOOP"],
	TRANSITION					= TRUE,
	
	CAN_PUSH_UNIT				= TRUE,
	CAN_PASS_UNIT				= FALSE,


	PASSIVE_SPEED_X				= INIT_PHYSIC["RUN_SPEED"],
	
	ALLOW_DIR_CHANGE			= TRUE,
	IMMADIATE_PACKET_SEND		= TRUE,
	
	EVENT_INTERVAL_TIME0		= 1,
	
	EVENT_PROCESS = 
	{		
		{ STATE_CHANGE_TYPE["SCT_FOOT_ON_LINE_FALSE_DOWN"],	"PENG_SANTA_JUMP_DOWN_DIR",				},

		{ STATE_CHANGE_TYPE["SCT_AI_WAIT"],					"PENG_SANTA_DASH_END",							},
		{ STATE_CHANGE_TYPE["SCT_AI_WALK"],					"PENG_SANTA_WALK",							},
		{ STATE_CHANGE_TYPE["SCT_AI_JUMP"],					"PENG_SANTA_JUMP_UP",						},
		{ STATE_CHANGE_TYPE["SCT_AI_JUMP_DIR"],				"PENG_SANTA_JUMP_UP_DIR",					},
		{ STATE_CHANGE_TYPE["SCT_AI_DOWN"],					"PENG_SANTA_JUMP_DOWN",					},
		{ STATE_CHANGE_TYPE["SCT_AI_DOWN_DIR"],				"PENG_SANTA_JUMP_DOWN_DIR",				},
	},
	
}

PENG_SANTA_DASH_END = 
{
	ANIM_NAME					= "DashEnd",
	PLAY_TYPE					= XSKIN_ANIM_PLAYTYPE["XAP_ONE_WAIT"],
	TRANSITION					= FALSE,
	
	CAN_PUSH_UNIT				= TRUE,
	CAN_PASS_UNIT				= FALSE,

	SOUND_PLAY0					= { 0.188, "DashEnd.ogg" },
	
	PASSIVE_SPEED_X				= 100,
	
	ALLOW_DIR_CHANGE			= TRUE,
	IMMADIATE_PACKET_SEND		= TRUE,
	
	
	
	EVENT_PROCESS = 
	{		
		{ STATE_CHANGE_TYPE["SCT_FOOT_ON_LINE_FALSE_DOWN"],	"PENG_SANTA_JUMP_DOWN_DIR",				},
		
		{ STATE_CHANGE_TYPE["SCT_MOTION_END"],				"PENG_SANTA_WAIT",							},
			
		{ STATE_CHANGE_TYPE["SCT_AI_WAIT"],					"PENG_SANTA_WAIT",							},
		{ STATE_CHANGE_TYPE["SCT_AI_WALK"],					"PENG_SANTA_WALK",							},
		{ STATE_CHANGE_TYPE["SCT_AI_JUMP"],					"PENG_SANTA_JUMP_UP",						},
		{ STATE_CHANGE_TYPE["SCT_AI_JUMP_DIR"],				"PENG_SANTA_JUMP_UP_DIR",					},
		{ STATE_CHANGE_TYPE["SCT_AI_DOWN"],					"PENG_SANTA_JUMP_DOWN",					},
		{ STATE_CHANGE_TYPE["SCT_AI_DOWN_DIR"],				"PENG_SANTA_JUMP_DOWN_DIR",				},
	},
}

PENG_SANTA_DAMAGE = 
{
	ANIM_NAME					= "Damage",
	PLAY_TYPE					= XSKIN_ANIM_PLAYTYPE["XAP_ONE_WAIT"],
	TRANSITION					= FALSE,
	LAND_CONNECT				= FALSE,
	
	CAN_PUSH_UNIT				= TRUE,
	CAN_PASS_UNIT				= FALSE,
	
	EVENT_PROCESS = 
	{
		{ STATE_CHANGE_TYPE["SCT_MOTION_END"],					"PENG_SANTA_WAIT",												},
	},
}

PENG_SANTA_DAMAGE_AIR = 
{
	ANIM_NAME					= "DamageAirDown",
	PLAY_TYPE					= XSKIN_ANIM_PLAYTYPE["XAP_ONE_WAIT"],
	TRANSITION					= FALSE,
	LAND_CONNECT				= FALSE,
	
	CAN_PUSH_UNIT				= TRUE,
	CAN_PASS_UNIT				= FALSE,
	
	EVENT_PROCESS = 
	{
		{ STATE_CHANGE_TYPE["SCT_MOTION_END"],					"PENG_SANTA_JUMP_DOWN",				},
		{ STATE_CHANGE_TYPE["SCT_FOOT_ON_LINE_TRUE"],			"PENG_SANTA_WAIT",					},
	},
}

PENG_SANTA_DYING = 
{
	ANIM_NAME					= "Dying",
	PLAY_TYPE					= XSKIN_ANIM_PLAYTYPE["XAP_ONE_WAIT"],
	TRANSITION					= FALSE,
	LAND_CONNECT				= FALSE,

	INVINCIBLE					= { 0, 100, }, 		
	
	CAN_PUSH_UNIT				= FALSE,
	CAN_PASS_UNIT				= TRUE,
	
	DYING_END					= TRUE,
	
	IMMADIATE_PACKET_SEND		= TRUE,
}
	








--------------------------------------------------------------------
--------------------------------------------------------------------
function PENG_SANTA_WALK_STATE_END( pKTDXApp, pX2Game, pNPCUnit )

	pMinorParticle = pX2Game:GetMinorParticle()
	pMinorParticle:GameUnitCreateSequence_LUA( pNPCUnit, "StepSmoke", pNPCUnit:GetLandPosition_LUA(), D3DXVECTOR2(100,100), D3DXVECTOR2(5,-1) )

end

function PENG_SANTA_JUMP_DOWN_STATE_END( pKTDXApp, pX2Game, pNPCUnit )

	pMinorParticle = pX2Game:GetMinorParticle()
	pMinorParticle:GameUnitCreateSequence_LUA( pNPCUnit, "StepSmoke", pNPCUnit:GetLandPosition_LUA(), D3DXVECTOR2(100,100), D3DXVECTOR2(5,-1) )

end

function PENG_SANTA_JUMP_DOWN_DIR_STATE_END( pKTDXApp, pX2Game, pNPCUnit )

	pMinorParticle = pX2Game:GetMinorParticle()
	pMinorParticle:GameUnitCreateSequence_LUA( pNPCUnit, "StepSmoke", pNPCUnit:GetLandPosition_LUA(), D3DXVECTOR2(100,100), D3DXVECTOR2(5,-1) )

end

function PENG_SANTA_DAMAGE_FRAME_MOVE( pKTDXApp, pX2Game, pNPCUnit )

	if pNPCUnit:AnimEventTimer_LUA( 0.047 ) then
		pMinorParticle = pX2Game:GetMinorParticle()
		pMinorParticle:GameUnitCreateSequence_LUA( pNPCUnit, "StepSmoke", pNPCUnit:GetLandPosition_LUA(), D3DXVECTOR2(100,100), D3DXVECTOR2(5,-1) )
	end

end



function PENG_SANTA_DYING_STATE_START( pKTDXApp, pX2Game, pNPCUnit )
	
	pos = pNPCUnit:GetPos()
	pos.y = pos.y + 100.0
	GetMinorParticle = pX2Game:GetMinorParticle()
	
	pSeq = GetMinorParticle:GameUnitCreateSequence_LUA( pNPCUnit, "DieLight",		pos, D3DXVECTOR2(-1,-1), D3DXVECTOR2(3,-1) )
	if pSeq ~= nil then
	
		pSeq:SetLandPosition( pNPCUnit:GetLandPosition_LUA().y )
		pNPCUnit:SetDieSeq( pSeq:GetHandle() )
	
	end
	pNPCUnit:PlaySound_LUA( "DieLight.ogg" )
	
end

