-- lua header. UTF-8 인코딩 인식을 위해 이 줄은 지우지 마세요.

SOUND_FIX_TIME = -0.05

INIT_SYSTEM =
{
	UNIT_LAYER		= X2_LAYER["XL_UNIT_0"],
	UNIT_SCALE		= 1.0,
}


INIT_DEVICE =
{
	READY_XSKIN_MESH =
	{
		"DummyAttackBox_50x50x50.X"
	},

	READY_TEXTURE =
	{
	},

	READY_SOUND =
	{
	"Pet_Hungry.ogg",
	"Pet_Stuffed.ogg",
	"Pet_Eat01.ogg",
	"Pet_SHERIFF_Attack_A.ogg",
	"Pet_DashEnd.ogg",
	--"Pet_SHERIFF_Hello.ogg",
	--"Pet_SHERIFF_Cute1.ogg",
	--"Pet_SHERIFF_Cute2.ogg",
	"Pet_SHERIFF_Cute2.ogg",
	"Airship_Gunner_GunShot.ogg",
	},
}

INIT_MOTION =
{
	MOTION_FILE_NAME		= "Motion_PET_SHERIFF_STEB_1.x",
	MOTION_ANI_TEX_XET		= "PET_SHERIFF_STEB_1_EYE.xet",	
	--MOTION_CHANGE_TEX_XET	= "PET_SHERIFF_NORM_STEB_2.xet",
}


INIT_COMPONENT =
{
	MAX_HP				= 6000,
	MP_CHANGE_RATE		= 1,
	MP_CHARGE_RATE		= 130,


	SHADOW_SIZE			= 200,
	SHADOW_FILE_NAME	= "shadow.dds",

	SMALL_HP_BAR_BLUE	= "Small_HP_bar_Blue.TGA",
	SMALL_HP_BAR_RED	= "Small_HP_bar_Red.TGA",
	SMALL_HP_BAR_YELLOW = "Small_HP_bar_Yellow.TGA",

	QUESTION_MARK_SEQ		= "QuestionMarkNPC",
	EXCLAMATION_MARK_SEQ	= "ExclamationMarkNPC",

	HYPER_MODE_COUNT	= 0,
	MAX_HYPER_MODE_TIME	= 30,

	HITTED_TYPE			= HITTED_TYPE["HTD_MEAT"],

	FALL_DOWN			= TRUE,



}

INIT_STATE =
{
	{ STATE_NAME = "SHERIFF_NORM_STEB_1_SUMMON",			},
	{ STATE_NAME = "SHERIFF_NORM_STEB_1_WAIT_HABIT",		STATE_COOL_TIME = 20, },
	{ STATE_NAME = "SHERIFF_NORM_STEB_1_WAIT",						},
	{ STATE_NAME = "SHERIFF_NORM_STEB_1_WALK",						},
	{ STATE_NAME = "SHERIFF_NORM_STEB_1_DASH",						},
	{ STATE_NAME = "SHERIFF_NORM_STEB_1_DASH_END",					},
	{ STATE_NAME = "SHERIFF_NORM_STEB_1_JUMP_UP",					},
	{ STATE_NAME = "SHERIFF_NORM_STEB_1_JUMP_DOWN",				},
	{ STATE_NAME = "SHERIFF_NORM_STEB_1_JUMP_UP_DIR",				},
	{ STATE_NAME = "SHERIFF_NORM_STEB_1_JUMP_DOWN_DIR",			},
	{ STATE_NAME = "SHERIFF_NORM_STEB_1_JUMP_LANDING",				},
	{ STATE_NAME = "SHERIFF_NORM_STEB_1_EAT",				},
	{ STATE_NAME = "SHERIFF_NORM_STEB_1_HUNGRY",				},
	{ STATE_NAME = "SHERIFF_NORM_STEB_1_STUFFED",				},
	{ STATE_NAME = "SHERIFF_NORM_STEB_1_SLEEP_START",				},
	{ STATE_NAME = "SHERIFF_NORM_STEB_1_SLEEP_LOOP",				},
	{ STATE_NAME = "SHERIFF_NORM_STEB_1_SLEEP_END",				},
	{ STATE_NAME = "SHERIFF_NORM_STEB_1_AFRAID",				STATE_COOL_TIME = 10, },
	{ STATE_NAME = "SHERIFF_NORM_STEB_1_HELLO",				},
	{ STATE_NAME = "SHERIFF_NORM_STEB_1_HAPPY1",				},
	{ STATE_NAME = "SHERIFF_NORM_STEB_1_HAPPY2",				},
  { STATE_NAME = "SHERIFF_NORM_STEB_1_CUTE1",				STATE_COOL_TIME = 10, },
  { STATE_NAME = "SHERIFF_NORM_STEB_1_CUTE2",				STATE_COOL_TIME = 10, },
  { STATE_NAME = "SHERIFF_NORM_STEB_1_SAD",				},
  { STATE_NAME = "SHERIFF_NORM_STEB_1_CHEER",			LUA_FRAME_MOVE_FUNC = "SHERIFF_NORM_STEB_1_CHEER_FRAME_MOVE",	STATE_COOL_TIME = 180,	},
  { STATE_NAME = "SHERIFF_NORM_STEB_1_SPECIAL",				},
  { STATE_NAME = "SHERIFF_NORM_STEB_1_ATTACK",			LUA_FRAME_MOVE_FUNC = "SHERIFF_NORM_STEB_1_ATTACK_FRAME_MOVE",	},
  { STATE_NAME = "SHERIFF_NORM_STEB_1_SIT_START",				},
  { STATE_NAME = "SHERIFF_NORM_STEB_1_SIT_LOOP",				},
  { STATE_NAME = "SHERIFF_NORM_STEB_1_SIT_END",				},
  { STATE_NAME = "SHERIFF_NORM_STEB_1_NOTKNOW",				},

  START_STATE					= "SHERIFF_NORM_STEB_1_SUMMON",
  WAIT_HABIT					= "SHERIFF_NORM_STEB_1_WAIT_HABIT",
	WAIT_STATE					= "SHERIFF_NORM_STEB_1_WAIT",
	EAT_STATE           = "SHERIFF_NORM_STEB_1_EAT",
	HUNGRY_STATE       = "SHERIFF_NORM_STEB_1_HUNGRY",
	STUFFED_STATE       = "SHERIFF_NORM_STEB_1_STUFFED",
	SLEEP_START_STATE   = "SHERIFF_NORM_STEB_1_SLEEP_START",
	SLEEP_LOOP_STATE   = "SHERIFF_NORM_STEB_1_SLEEP_LOOP",
  SLEEP_END_STATE     = "SHERIFF_NORM_STEB_1_SLEEP_END",
  AFRAID_STATE        = "SHERIFF_NORM_STEB_1_AFRAID",
  HELLO_STATE         = "SHERIFF_NORM_STEB_1_HELLO",
  HAPPY1_STATE         = "SHERIFF_NORM_STEB_1_HAPPY1",
  HAPPY2_STATE         = "SHERIFF_NORM_STEB_1_HAPPY2",
  CUTE1_STATE          = "SHERIFF_NORM_STEB_1_CUTE1",
  CUTE2_STATE          = "SHERIFF_NORM_STEB_1_CUTE2",
  SAD_STATE           = "SHERIFF_NORM_STEB_1_SAD",
  CHEER_STATE         = "SHERIFF_NORM_STEB_1_CHEER",
  SPECIAL_STATE       = "SHERIFF_NORM_STEB_1_SPECIAL",
  ATTACK_STATE      = "SHERIFF_NORM_STEB_1_ATTACK",
  SIT_START_STATE     = "SHERIFF_NORM_STEB_1_SIT_START",
  SIT_LOOP_STATE     = "SHERIFF_NORM_STEB_1_SIT_LOOP",
  SIT_END_STATE       = "SHERIFF_NORM_STEB_1_SIT_END",
  NOTKNOW_STATE       = "SHERIFF_NORM_STEB_1_NOTKNOW",
}

INIT_AI =
{
	TARGET =
	{
		TARGET_PRIORITY 			= TARGET_PRIORITY["TP_LOW_HP_FIRST"],
		TARGET_INTERVAL				= 0.5,		-- sec
		TARGET_NEAR_RANGE			= 200,		-- 이 거리보다 가까우면 TARGET_SUCCESS_RATE에 관계없이 무조건 타게팅된다
		TARGET_RANGE				= 10000,		-- cm
		TARGET_LOST_RANGE			= 2000,	-- cm
		TARGET_SUCCESS_RATE			= 100,  --70,		-- %
		ATTACK_TARGET_RATE			= 100, -- 80,		-- 나를 공격한 유닛을 타게팅할 확률
		PRESERVE_LAST_TARGET_RATE	= 100, -- 80,		-- 이전에 타게팅된 유닛을 계속 타게팅할 확률
	},

	CHASE_MOVE =
	{
		MOVE_SPLIT_RANGE	= 100,
		DEST_GAP			= 200,	-- 목적지에서 이 거리 안에 있으면 도착했다고 판단한다
		MOVE_GAP			= 100,
		RUN_GAP				= 500,

		DIR_CHANGE_INTERVAL = 0.3,

		WALK_INTERVAL		= 1,
		NEAR_WALK_RATE		= 100,   --  70,
		FAR_WALK_RATE		= 100,   -- 30,

		JUMP_INTERVAL		= 0,
		UP_JUMP_RATE		= 0, -- 40,
		UP_DOWN_RATE		= 0,
		DOWN_JUMP_RATE		= 0,    --  20,
		DOWN_DOWN_RATE		= 0,
	},

}

SHERIFF_NORM_STEB_1_SUMMON =
{
	ANIM_NAME					= "Wait",
	PLAY_TYPE					= XSKIN_ANIM_PLAYTYPE["XAP_ONE_WAIT"],
	TRANSITION					= TRUE,

	MOVE_TYPE           = 0,

	CAN_PUSH_UNIT				= TRUE,
	CAN_PASS_UNIT				= FALSE,
	IMMADIATE_PACKET_SEND		= TRUE,

	ALLOW_DIR_CHANGE			= FALSE,

	EVENT_PROCESS =
	{
		{ STATE_CHANGE_TYPE["SCT_FOOT_ON_LINE_FALSE_DOWN"],	"SHERIFF_NORM_STEB_1_JUMP_DOWN",					},
		{ STATE_CHANGE_TYPE["SCT_MOTION_END"],				"SHERIFF_NORM_STEB_1_WAIT",						},
	},
}

SHERIFF_NORM_STEB_1_WAIT =
{
	ANIM_NAME					= "Wait",
	PLAY_TYPE					= XSKIN_ANIM_PLAYTYPE["XAP_LOOP"],
	TRANSITION					= TRUE,

	MOVE_TYPE           = 0,

	IMMADIATE_PACKET_SEND		= TRUE,
	EVENT_INTERVAL_TIME0		= 2,

	EVENT_PROCESS =
	{
		{ STATE_CHANGE_TYPE["SCT_FOOT_ON_LINE_FALSE_DOWN"],	"SHERIFF_NORM_STEB_1_JUMP_DOWN",					},

		{ STATE_CHANGE_TYPE["SCT_CONDITION_FUNCTION"],      "SHERIFF_NORM_STEB_1_ATTACK",						"CF_PETATTACK_SHERIFF_NORM_STEB_1"    },

		{ STATE_CHANGE_TYPE["SCT_AI_DIR_CHANGE"],			"SHERIFF_NORM_STEB_1_WALK",						},

		{ STATE_CHANGE_TYPE["SCT_AI_WALK"],					"SHERIFF_NORM_STEB_1_WALK",						},
		{ STATE_CHANGE_TYPE["SCT_AI_DASH"],					"SHERIFF_NORM_STEB_1_DASH",						},
		{ STATE_CHANGE_TYPE["SCT_AI_JUMP"],					"SHERIFF_NORM_STEB_1_JUMP_UP",						},
		{ STATE_CHANGE_TYPE["SCT_AI_JUMP_DIR"],				"SHERIFF_NORM_STEB_1_JUMP_UP_DIR",					},
		{ STATE_CHANGE_TYPE["SCT_AI_DOWN"],					"SHERIFF_NORM_STEB_1_JUMP_DOWN",					},
		{ STATE_CHANGE_TYPE["SCT_AI_DOWN_DIR"],				"SHERIFF_NORM_STEB_1_JUMP_DOWN_DIR",				},
	},
}


SHERIFF_NORM_STEB_1_WALK =
{
	ANIM_NAME					= "Walk",
	PLAY_TYPE					= XSKIN_ANIM_PLAYTYPE["XAP_LOOP"],
	TRANSITION					= TRUE,

	CAN_PUSH_UNIT				= TRUE,
	CAN_PASS_UNIT				= FALSE,

	MOVE_TYPE           = 1,
	PASSIVE_SPEED_X_BY_USER			= 1.2,

	IMMADIATE_PACKET_SEND		= TRUE,

	EVENT_INTERVAL_TIME0		= 2,

	EVENT_PROCESS =
	{
		{ STATE_CHANGE_TYPE["SCT_FOOT_ON_LINE_FALSE_DOWN"],	"SHERIFF_NORM_STEB_1_JUMP_DOWN_DIR",				},

		{ STATE_CHANGE_TYPE["SCT_CONDITION_FUNCTION"],      "SHERIFF_NORM_STEB_1_ATTACK",						"CF_PETATTACK_SHERIFF_NORM_STEB_1"    },

		{ STATE_CHANGE_TYPE["SCT_AI_WAIT"],					"SHERIFF_NORM_STEB_1_WAIT",						},
		{ STATE_CHANGE_TYPE["SCT_AI_DASH"],					"SHERIFF_NORM_STEB_1_DASH",						},

		{ STATE_CHANGE_TYPE["SCT_AI_JUMP"],					"SHERIFF_NORM_STEB_1_JUMP_UP",						},
		{ STATE_CHANGE_TYPE["SCT_AI_JUMP_DIR"],				"SHERIFF_NORM_STEB_1_JUMP_UP_DIR",					},
		{ STATE_CHANGE_TYPE["SCT_AI_DOWN"],					"SHERIFF_NORM_STEB_1_JUMP_DOWN",					},
		{ STATE_CHANGE_TYPE["SCT_AI_DOWN_DIR"],				"SHERIFF_NORM_STEB_1_JUMP_DOWN_DIR",				},
	},

}

SHERIFF_NORM_STEB_1_DASH =
{
	ANIM_NAME					= "Dash",
	PLAY_TYPE					= XSKIN_ANIM_PLAYTYPE["XAP_LOOP"],
	TRANSITION					= TRUE,

	CAN_PUSH_UNIT				= TRUE,
	CAN_PASS_UNIT				= FALSE,


	MOVE_TYPE           = 2,
	PASSIVE_SPEED_X_BY_USER			= 1.4,

	ALLOW_DIR_CHANGE			= TRUE,
	IMMADIATE_PACKET_SEND		= TRUE,

	EVENT_INTERVAL_TIME0		= 1,

	EVENT_PROCESS =
	{
		{ STATE_CHANGE_TYPE["SCT_FOOT_ON_LINE_FALSE_DOWN"],	"SHERIFF_NORM_STEB_1_JUMP_DOWN_DIR",				},

		{ STATE_CHANGE_TYPE["SCT_CONDITION_FUNCTION"],      "SHERIFF_NORM_STEB_1_ATTACK",						"CF_PETATTACK_SHERIFF_NORM_STEB_1"    },

		{ STATE_CHANGE_TYPE["SCT_AI_WAIT"],					"SHERIFF_NORM_STEB_1_DASH_END",							},
		{ STATE_CHANGE_TYPE["SCT_AI_WALK"],					"SHERIFF_NORM_STEB_1_WALK",							},
		{ STATE_CHANGE_TYPE["SCT_AI_JUMP"],					"SHERIFF_NORM_STEB_1_JUMP_UP",						},
		{ STATE_CHANGE_TYPE["SCT_AI_JUMP_DIR"],				"SHERIFF_NORM_STEB_1_JUMP_UP_DIR",					},
		{ STATE_CHANGE_TYPE["SCT_AI_DOWN"],					"SHERIFF_NORM_STEB_1_JUMP_DOWN",					},
		{ STATE_CHANGE_TYPE["SCT_AI_DOWN_DIR"],				"SHERIFF_NORM_STEB_1_JUMP_DOWN_DIR",				},
	},
	
	TALK_BOX_1 =
	{
		{ RATE = 7, MESSAGE = STR_ID_24096  },
		{ RATE = 7, MESSAGE = STR_ID_24097  },
		{ RATE = 7, MESSAGE = STR_ID_24098  },
	},
	TALK_BOX_2 =
	{
		{ RATE = 7, MESSAGE = STR_ID_24096  },
		{ RATE = 7, MESSAGE = STR_ID_24099  },
		{ RATE = 7, MESSAGE = STR_ID_24098  },
	},
	TALK_BOX =
	{
		{ RATE = 7, MESSAGE = STR_ID_24100  },
		{ RATE = 7, MESSAGE = STR_ID_24101  },
		{ RATE = 7, MESSAGE = STR_ID_24102  },
	},


}

SHERIFF_NORM_STEB_1_DASH_END =
{
	ANIM_NAME					= "DashEnd",
	PLAY_TYPE					= XSKIN_ANIM_PLAYTYPE["XAP_ONE_WAIT"],
	TRANSITION					= FALSE,

	CAN_PUSH_UNIT				= TRUE,
	CAN_PASS_UNIT				= FALSE,

	SPEED_X				= 700,

	SOUND_PLAY0					= { 0.01, "Pet_DashEnd.ogg" },

	ALLOW_DIR_CHANGE			= TRUE,
	IMMADIATE_PACKET_SEND		= TRUE,

	EVENT_PROCESS =
	{
		{ STATE_CHANGE_TYPE["SCT_FOOT_ON_LINE_FALSE_DOWN"],	"SHERIFF_NORM_STEB_1_JUMP_DOWN_DIR",				},

		{ STATE_CHANGE_TYPE["SCT_MOTION_END"],				"SHERIFF_NORM_STEB_1_WAIT",							},

		{ STATE_CHANGE_TYPE["SCT_AI_WAIT"],					"SHERIFF_NORM_STEB_1_WAIT",							},
		{ STATE_CHANGE_TYPE["SCT_AI_WALK"],					"SHERIFF_NORM_STEB_1_WALK",							},
		{ STATE_CHANGE_TYPE["SCT_AI_JUMP"],					"SHERIFF_NORM_STEB_1_JUMP_UP",						},
		{ STATE_CHANGE_TYPE["SCT_AI_JUMP_DIR"],				"SHERIFF_NORM_STEB_1_JUMP_UP_DIR",					},
		{ STATE_CHANGE_TYPE["SCT_AI_DOWN"],					"SHERIFF_NORM_STEB_1_JUMP_DOWN",					},
		{ STATE_CHANGE_TYPE["SCT_AI_DOWN_DIR"],				"SHERIFF_NORM_STEB_1_JUMP_DOWN_DIR",				},
	},
}


SHERIFF_NORM_STEB_1_JUMP_UP =
{
	ANIM_NAME					= "JumpUp",
	PLAY_TYPE					= XSKIN_ANIM_PLAYTYPE["XAP_LOOP"],
	TRANSITION					= TRUE,
	LAND_CONNECT				= FALSE,

	CAN_PUSH_UNIT				= TRUE,
	CAN_PASS_UNIT				= FALSE,

	MOVE_TYPE           = 3,
	SPEED_Y_BY_USER			= 1,
	ADD_POS_Y					= 45,

	IMMADIATE_PACKET_SEND		= TRUE,

	EVENT_PROCESS =
	{

		{ STATE_CHANGE_TYPE["SCT_NEGATIVE_Y_SPEED"],		"SHERIFF_NORM_STEB_1_JUMP_DOWN",				},
	},


}

SHERIFF_NORM_STEB_1_JUMP_DOWN =
{
	ANIM_NAME					= "JumpDown",
	PLAY_TYPE					= XSKIN_ANIM_PLAYTYPE["XAP_LOOP"],
	TRANSITION					= TRUE,
	LAND_CONNECT				= FALSE,

	CAN_PUSH_UNIT				= TRUE,
	CAN_PASS_UNIT				= FALSE,



	IMMADIATE_PACKET_SEND		= TRUE,

	EVENT_PROCESS =
	{
		{ STATE_CHANGE_TYPE["SCT_FOOT_ON_LINE_TRUE"],		"SHERIFF_NORM_STEB_1_JUMP_LANDING",				},
	},
}

SHERIFF_NORM_STEB_1_JUMP_UP_DIR =
{
	ANIM_NAME					= "JumpUp",
	PLAY_TYPE					= XSKIN_ANIM_PLAYTYPE["XAP_LOOP"],
	TRANSITION					= TRUE,
	LAND_CONNECT				= FALSE,

	CAN_PUSH_UNIT				= TRUE,
	CAN_PASS_UNIT				= FALSE,

	MOVE_TYPE           = 4,
	PASSIVE_SPEED_X_BY_USER = 1.2,
	SPEED_Y_BY_USER			= 1,
	ADD_POS_Y					= 45,

	IMMADIATE_PACKET_SEND		= TRUE,

	EVENT_PROCESS =
	{

		{ STATE_CHANGE_TYPE["SCT_NEGATIVE_Y_SPEED"],		"SHERIFF_NORM_STEB_1_JUMP_DOWN_DIR",				},
	},


}

SHERIFF_NORM_STEB_1_JUMP_DOWN_DIR =
{
	ANIM_NAME					= "JumpDown",
	PLAY_TYPE					= XSKIN_ANIM_PLAYTYPE["XAP_LOOP"],
	TRANSITION					= TRUE,
	LAND_CONNECT				= FALSE,

	CAN_PUSH_UNIT				= TRUE,
	CAN_PASS_UNIT				= FALSE,


	MOVE_TYPE           = 1,
	PASSIVE_SPEED_X_BY_USER = 1,

	IMMADIATE_PACKET_SEND		= TRUE,

	EVENT_PROCESS =
	{
		{ STATE_CHANGE_TYPE["SCT_FOOT_ON_LINE_TRUE"],		"SHERIFF_NORM_STEB_1_JUMP_LANDING",				},
	},
}

SHERIFF_NORM_STEB_1_JUMP_LANDING =
{
	ANIM_NAME					= "JumpDownLanding",
	PLAY_TYPE					= XSKIN_ANIM_PLAYTYPE["XAP_ONE_WAIT"],
	TRANSITION					= TRUE,
	LAND_CONNECT				= FALSE,

	CAN_PUSH_UNIT				= TRUE,
	CAN_PASS_UNIT				= FALSE,

	SOUND_PLAY0					= { 0.093, "JumpLand.ogg" },

	MOVE_TYPE = 0,

	IMMADIATE_PACKET_SEND		= TRUE,

	EVENT_PROCESS =
	{
		{ STATE_CHANGE_TYPE["SCT_FOOT_ON_LINE_FALSE_DOWN"],	"SHERIFF_NORM_STEB_1_JUMP_DOWN",				},
		{ STATE_CHANGE_TYPE["SCT_MOTION_END"],				"SHERIFF_NORM_STEB_1_WAIT",					},
	},

}



SHERIFF_NORM_STEB_1_WAIT_HABIT =
{
	ANIM_NAME					= "WaitHabit",
	PLAY_TYPE					= XSKIN_ANIM_PLAYTYPE["XAP_ONE_WAIT"],
	TRANSITION					= TRUE,

	MOVE_TYPE           = 0,
	
	--SOUND_PLAY0					= { 0.24, "Pet_PANDA_STICK_WaitHabit.ogg" },

	CAN_PUSH_UNIT				= TRUE,
	CAN_PASS_UNIT				= FALSE,
	IMMADIATE_PACKET_SEND		= TRUE,

	ALLOW_DIR_CHANGE			= FALSE,

	EVENT_PROCESS =
	{
		{ STATE_CHANGE_TYPE["SCT_FOOT_ON_LINE_FALSE_DOWN"],	"SHERIFF_NORM_STEB_1_JUMP_DOWN",					},
		{ STATE_CHANGE_TYPE["SCT_MOTION_END"],				"SHERIFF_NORM_STEB_1_WAIT",						},
	},

	TALK_BOX_1 =
	{
		{ RATE = 7, MESSAGE = STR_ID_24114  },
		{ RATE = 7, MESSAGE = STR_ID_24115  },
		{ RATE = 7, MESSAGE = STR_ID_24116  },
	},
	TALK_BOX_2 =
	{
		{ RATE = 7, MESSAGE = STR_ID_24117  },
		{ RATE = 7, MESSAGE = STR_ID_24118  },
		{ RATE = 7, MESSAGE = STR_ID_24119  },
	},
	TALK_BOX =
	{
		{ RATE = 7, MESSAGE = STR_ID_24120  },
		{ RATE = 7, MESSAGE = STR_ID_24121  },
		{ RATE = 7, MESSAGE = STR_ID_24122  },
	},
}

SHERIFF_NORM_STEB_1_EAT =
{
	ANIM_NAME					= "Eat",
	PLAY_TYPE					= XSKIN_ANIM_PLAYTYPE["XAP_ONE_WAIT"],
	TRANSITION					= TRUE,

	MOVE_TYPE           = 0,
	
	SOUND_PLAY0					= { 0.9, "Pet_Eat01.ogg" },


	IMMADIATE_PACKET_SEND		= TRUE,

		ALLOW_DIR_CHANGE			= FALSE,

	EVENT_PROCESS =
	{
		{ STATE_CHANGE_TYPE["SCT_FOOT_ON_LINE_FALSE_DOWN"],	"SHERIFF_NORM_STEB_1_JUMP_DOWN",					},
		{ STATE_CHANGE_TYPE["SCT_MOTION_END"],				"SHERIFF_NORM_STEB_1_WAIT",						},
	},

	TALK_BOX_1 =
	{
		{ RATE = 34, MESSAGE = STR_ID_24133,   },
		{ RATE = 33, MESSAGE = STR_ID_24134,   },
		{ RATE = 33, MESSAGE = STR_ID_24135,   },
	},
	TALK_BOX_2 =
	{
		{ RATE = 34, MESSAGE = STR_ID_24133,   },
		{ RATE = 33, MESSAGE = STR_ID_24134,   },
		{ RATE = 33, MESSAGE = STR_ID_24135,   },
	},
	TALK_BOX =
	{
		{ RATE = 34, MESSAGE = STR_ID_24136,   },
		{ RATE = 33, MESSAGE = STR_ID_24137,   },
		{ RATE = 33, MESSAGE = STR_ID_24138,   },
	},
}

SHERIFF_NORM_STEB_1_HUNGRY =
{
	ANIM_NAME					= "Hungry",
	PLAY_TYPE					= XSKIN_ANIM_PLAYTYPE["XAP_ONE_WAIT"],
	TRANSITION					= TRUE,

	MOVE_TYPE           = 0,

	SOUND_PLAY0					= { 0.031, "Pet_Hungry.ogg" },

	IMMADIATE_PACKET_SEND		= TRUE,

		ALLOW_DIR_CHANGE			= FALSE,

	EVENT_PROCESS =
	{
		{ STATE_CHANGE_TYPE["SCT_FOOT_ON_LINE_FALSE_DOWN"],	"SHERIFF_NORM_STEB_1_JUMP_DOWN",					},
		{ STATE_CHANGE_TYPE["SCT_MOTION_END"],				"SHERIFF_NORM_STEB_1_WAIT",						},
	},

	TALK_BOX_1 =
	{
		{ RATE = 34, MESSAGE = STR_ID_24144 },
		{ RATE = 33, MESSAGE = STR_ID_24145 },
		{ RATE = 33, MESSAGE = STR_ID_24146 },
	},
	TALK_BOX_2 =
	{
		{ RATE = 34, MESSAGE = STR_ID_24147 },
		{ RATE = 33, MESSAGE = STR_ID_24148 },
		{ RATE = 33, MESSAGE = STR_ID_24149 },
	},
	TALK_BOX =
	{
		{ RATE = 34, MESSAGE = STR_ID_24150 },
		{ RATE = 33, MESSAGE = STR_ID_24151 },
		{ RATE = 33, MESSAGE = STR_ID_24152 },
	},
}


SHERIFF_NORM_STEB_1_STUFFED =
{
	ANIM_NAME					= "Stuffed",
	PLAY_TYPE					= XSKIN_ANIM_PLAYTYPE["XAP_ONE_WAIT"],
	TRANSITION					= TRUE,

	MOVE_TYPE           = 0,

	SOUND_PLAY0					= { 0.442, "Pet_Stuffed.ogg" },

	IMMADIATE_PACKET_SEND		= TRUE,

		ALLOW_DIR_CHANGE			= FALSE,

	EVENT_PROCESS =
	{
		{ STATE_CHANGE_TYPE["SCT_FOOT_ON_LINE_FALSE_DOWN"],	"SHERIFF_NORM_STEB_1_JUMP_DOWN",					},
		{ STATE_CHANGE_TYPE["SCT_MOTION_END"],				"SHERIFF_NORM_STEB_1_WAIT",						},
	},

	TALK_BOX_1 =
	{
		{ RATE = 34, MESSAGE = STR_ID_24159 },
		{ RATE = 33, MESSAGE = STR_ID_24160 },
		{ RATE = 33, MESSAGE = STR_ID_24161 },
	},
	TALK_BOX_2 =
	{
		{ RATE = 34, MESSAGE = STR_ID_24162 },
		{ RATE = 33, MESSAGE = STR_ID_24163 },
		{ RATE = 33, MESSAGE = STR_ID_24164 },
	},
	TALK_BOX =
	{
		{ RATE = 34, MESSAGE = STR_ID_24165 },
		{ RATE = 33, MESSAGE = STR_ID_24166 },
		{ RATE = 33, MESSAGE = STR_ID_24167 },
	},
}
---sleep 할 차례임
SHERIFF_NORM_STEB_1_SLEEP_START =
{
	ANIM_NAME					= "Sleep",
	PLAY_TYPE					= XSKIN_ANIM_PLAYTYPE["XAP_ONE_WAIT"],
	TRANSITION					= TRUE,

	MOVE_TYPE           = 0,


	IMMADIATE_PACKET_SEND		= TRUE,

		ALLOW_DIR_CHANGE			= FALSE,

	EVENT_PROCESS =
	{
		{ STATE_CHANGE_TYPE["SCT_FOOT_ON_LINE_FALSE_DOWN"],	"SHERIFF_NORM_STEB_1_JUMP_DOWN",					},
		{ STATE_CHANGE_TYPE["SCT_MOTION_END"],				"SHERIFF_NORM_STEB_1_SLEEP_LOOP",						},
	},
	TALK_BOX_1 =
	{
		{ RATE = 34, MESSAGE = STR_ID_24175,   },
		{ RATE = 33, MESSAGE = STR_ID_24114,   },
		{ RATE = 33, MESSAGE = STR_ID_24176,   },
	},
	TALK_BOX_2 =
	{
		{ RATE = 34, MESSAGE = STR_ID_24177,   },
		{ RATE = 33, MESSAGE = STR_ID_24178,   },
		{ RATE = 33, MESSAGE = STR_ID_24179,   },
	},
	TALK_BOX =
	{
		{ RATE = 34, MESSAGE = STR_ID_24180,   },
		{ RATE = 33, MESSAGE = STR_ID_24181,   },
		{ RATE = 33, MESSAGE = STR_ID_24182,   },
	},
}

SHERIFF_NORM_STEB_1_SLEEP_LOOP =
{
	ANIM_NAME					= "SleepLoop",
	PLAY_TYPE					= XSKIN_ANIM_PLAYTYPE["XAP_LOOP"],
	TRANSITION					= TRUE,

	MOVE_TYPE           = 0,
	
	--SOUND_PLAY0					= { 0.17, "Pet_PANDA_STICK_SleepLoop.ogg" },

	IMMADIATE_PACKET_SEND		= TRUE,

		ALLOW_DIR_CHANGE			= FALSE,

	EVENT_PROCESS =
	{
		{ STATE_CHANGE_TYPE["SCT_FOOT_ON_LINE_FALSE_DOWN"],	"SHERIFF_NORM_STEB_1_JUMP_DOWN",					},
	},
}

SHERIFF_NORM_STEB_1_SLEEP_END =
{
	ANIM_NAME					= "SleepEnd",
	PLAY_TYPE					= XSKIN_ANIM_PLAYTYPE["XAP_ONE_WAIT"],
	TRANSITION					= TRUE,

	MOVE_TYPE           = 0,


	IMMADIATE_PACKET_SEND		= TRUE,

	ALLOW_DIR_CHANGE			= FALSE,

	EVENT_PROCESS =
	{
		{ STATE_CHANGE_TYPE["SCT_FOOT_ON_LINE_FALSE_DOWN"],	"SHERIFF_NORM_STEB_1_JUMP_DOWN",					},
		{ STATE_CHANGE_TYPE["SCT_MOTION_END"],				"SHERIFF_NORM_STEB_1_WAIT",						},
	},

	TALK_BOX_1 =
	{
		{ RATE = 34, MESSAGE = STR_ID_24193,   },
		{ RATE = 33, MESSAGE = STR_ID_24194,   },
		{ RATE = 33, MESSAGE = STR_ID_24195,   },
	},
	TALK_BOX_2 =
	{
		{ RATE = 34, MESSAGE = STR_ID_24196,   },
		{ RATE = 33, MESSAGE = STR_ID_24197,   },
		{ RATE = 33, MESSAGE = STR_ID_24198,   },
	},
	TALK_BOX =
	{
		{ RATE = 34, MESSAGE = STR_ID_24199,   },
		{ RATE = 33, MESSAGE = STR_ID_24200,   },
		{ RATE = 33, MESSAGE = STR_ID_24201,   },
	},

}

SHERIFF_NORM_STEB_1_AFRAID =
{
	ANIM_NAME					= "Afraid",
	PLAY_TYPE					= XSKIN_ANIM_PLAYTYPE["XAP_ONE_WAIT"],
	TRANSITION					= TRUE,

	MOVE_TYPE           = 0,


	IMMADIATE_PACKET_SEND		= TRUE,

	ALLOW_DIR_CHANGE			= FALSE,

	EVENT_PROCESS =
	{
		{ STATE_CHANGE_TYPE["SCT_FOOT_ON_LINE_FALSE_DOWN"],	"SHERIFF_NORM_STEB_1_JUMP_DOWN",					},
		{ STATE_CHANGE_TYPE["SCT_MOTION_END"],				"SHERIFF_NORM_STEB_1_WAIT",						},
	},

	TALK_BOX_1 =
	{
		{ RATE = 34, MESSAGE = STR_ID_24205,  },
		{ RATE = 33, MESSAGE = STR_ID_24206,  },
		{ RATE = 33, MESSAGE = STR_ID_24207,  },
	},
	TALK_BOX_2 =
	{
		{ RATE = 34, MESSAGE = STR_ID_24208,  },
		{ RATE = 33, MESSAGE = STR_ID_24209,  },
		{ RATE = 33, MESSAGE = STR_ID_24210,  },
	},
	TALK_BOX =
	{
		{ RATE = 34, MESSAGE = STR_ID_24211,  },
		{ RATE = 33, MESSAGE = STR_ID_24212,  },
		{ RATE = 33, MESSAGE = STR_ID_24213,  },
	},
}

SHERIFF_NORM_STEB_1_HELLO =
{
	ANIM_NAME					= "Hello",
	PLAY_TYPE					= XSKIN_ANIM_PLAYTYPE["XAP_ONE_WAIT"],
	TRANSITION					= TRUE,

	MOVE_TYPE           = 0,

	--SOUND_PLAY0					= { 0.54, "Pet_PANDA_STICK_Hello.ogg" },

	IMMADIATE_PACKET_SEND		= TRUE,

	ALLOW_DIR_CHANGE			= FALSE,

	EVENT_PROCESS =
	{
		{ STATE_CHANGE_TYPE["SCT_FOOT_ON_LINE_FALSE_DOWN"],	"SHERIFF_NORM_STEB_1_JUMP_DOWN",					},
		{ STATE_CHANGE_TYPE["SCT_MOTION_END"],				"SHERIFF_NORM_STEB_1_WAIT",						},
	},

	TALK_BOX_1 =
	{
		{ RATE = 34, MESSAGE = STR_ID_24217,  },
		{ RATE = 33, MESSAGE = STR_ID_24218,  },
		{ RATE = 33, MESSAGE = STR_ID_24219,  },
	},
	TALK_BOX_2 =
	{
		{ RATE = 34, MESSAGE = STR_ID_24220,  },
		{ RATE = 33, MESSAGE = STR_ID_24217,  },
		{ RATE = 33, MESSAGE = STR_ID_24219,  },
	},
	TALK_BOX =
	{
		{ RATE = 34, MESSAGE = STR_ID_24221,  },
		{ RATE = 33, MESSAGE = STR_ID_24222,  },
		{ RATE = 33, MESSAGE = STR_ID_24223,  },
	},
}

SHERIFF_NORM_STEB_1_HAPPY1 =
{
	ANIM_NAME					= "Cute1",
	PLAY_TYPE					= XSKIN_ANIM_PLAYTYPE["XAP_ONE_WAIT"],
	TRANSITION					= TRUE,

	MOVE_TYPE           = 0,

	SOUND_PLAY0					= { 0.35, "Pet_PettePporu_Cute2.ogg" },

	IMMADIATE_PACKET_SEND		= TRUE,

	ALLOW_DIR_CHANGE			= FALSE,

	EVENT_PROCESS =
	{
		{ STATE_CHANGE_TYPE["SCT_FOOT_ON_LINE_FALSE_DOWN"],	"SHERIFF_NORM_STEB_1_JUMP_DOWN",					},
		{ STATE_CHANGE_TYPE["SCT_MOTION_END"],				"SHERIFF_NORM_STEB_1_WAIT",						},
	},

	TALK_BOX_1 =
	{
		{ RATE = 34, MESSAGE = STR_ID_24224,  },
		{ RATE = 33, MESSAGE = STR_ID_24225,  },
		{ RATE = 33, MESSAGE = STR_ID_24226,  },
	},
	TALK_BOX_2 =
	{
		{ RATE = 34, MESSAGE = STR_ID_24227,  },
		{ RATE = 33, MESSAGE = STR_ID_24228,  },
		{ RATE = 33, MESSAGE = STR_ID_24229,  },
	},
	TALK_BOX =
	{
		{ RATE = 34, MESSAGE = STR_ID_24230,  },
		{ RATE = 33, MESSAGE = STR_ID_24231,  },
		{ RATE = 33, MESSAGE = STR_ID_24232,  },
	},
}

SHERIFF_NORM_STEB_1_HAPPY2 =
{
	ANIM_NAME					= "Cute2",
	PLAY_TYPE					= XSKIN_ANIM_PLAYTYPE["XAP_ONE_WAIT"],
	TRANSITION					= TRUE,

	MOVE_TYPE           = 0,

	SOUND_PLAY0					= { 0.6, "Pet_SHERIFF_Cute2.ogg" },
	SOUND_PLAY1					= { 1.1, "Pet_SHERIFF_Cute2.ogg" },
	SOUND_PLAY2					= { 1.6, "Pet_SHERIFF_Cute2.ogg" },
	SOUND_PLAY3					= { 2.1, "Pet_SHERIFF_Cute2.ogg" },
	SOUND_PLAY4					= { 2.6, "Pet_SHERIFF_Cute2.ogg" },
	SOUND_PLAY5					= { 3.1, "Pet_SHERIFF_Cute2.ogg" },
	SOUND_PLAY6					= { 3.6, "Pet_SHERIFF_Cute2.ogg" },
	SOUND_PLAY7					= { 4.1, "Pet_SHERIFF_Cute2.ogg" },

	IMMADIATE_PACKET_SEND		= TRUE,

	ALLOW_DIR_CHANGE			= FALSE,

	EVENT_PROCESS =
	{
		{ STATE_CHANGE_TYPE["SCT_FOOT_ON_LINE_FALSE_DOWN"],	"SHERIFF_NORM_STEB_1_JUMP_DOWN",					},
		{ STATE_CHANGE_TYPE["SCT_MOTION_END"],				"SHERIFF_NORM_STEB_1_WAIT",						},
	},

	TALK_BOX_1 =
	{
		{ RATE = 34, MESSAGE = STR_ID_24224,  },
		{ RATE = 33, MESSAGE = STR_ID_24225,  },
		{ RATE = 33, MESSAGE = STR_ID_24226,  },
	},
	TALK_BOX_2 =
	{
		{ RATE = 34, MESSAGE = STR_ID_24227,  },
		{ RATE = 33, MESSAGE = STR_ID_24228,  },
		{ RATE = 33, MESSAGE = STR_ID_24229,  },
	},
	TALK_BOX =
	{
		{ RATE = 34, MESSAGE = STR_ID_24230,  },
		{ RATE = 33, MESSAGE = STR_ID_24231,  },
		{ RATE = 33, MESSAGE = STR_ID_24232,  },
	},
}

SHERIFF_NORM_STEB_1_CUTE1 =
{
	ANIM_NAME					= "Cute1",
	PLAY_TYPE					= XSKIN_ANIM_PLAYTYPE["XAP_ONE_WAIT"],
	TRANSITION					= TRUE,

	MOVE_TYPE           = 0,

	SOUND_PLAY0					= { 0.35, "Pet_PettePporu_Cute2.ogg" },

	IMMADIATE_PACKET_SEND		= TRUE,

	ALLOW_DIR_CHANGE			= FALSE,

	EVENT_PROCESS =
	{
		{ STATE_CHANGE_TYPE["SCT_FOOT_ON_LINE_FALSE_DOWN"],	"SHERIFF_NORM_STEB_1_JUMP_DOWN",					},
		{ STATE_CHANGE_TYPE["SCT_MOTION_END"],				"SHERIFF_NORM_STEB_1_WAIT",						},
	},

	TALK_BOX_1 =
	{
		{ RATE = 34, MESSAGE = STR_ID_24237,  },
		{ RATE = 33, MESSAGE = STR_ID_24238,  },
		{ RATE = 33, MESSAGE = STR_ID_24239,  },
	},
	TALK_BOX_2 =
	{
		{ RATE = 34, MESSAGE = STR_ID_24240,  },
		{ RATE = 33, MESSAGE = STR_ID_24241,  },
		{ RATE = 33, MESSAGE = STR_ID_24242,  },
	},
	TALK_BOX =
	{
		{ RATE = 34, MESSAGE = STR_ID_24243,  },
		{ RATE = 33, MESSAGE = STR_ID_24244,  },
		{ RATE = 33, MESSAGE = STR_ID_24245,  },
	},

}

SHERIFF_NORM_STEB_1_CUTE2 =
{
	ANIM_NAME					= "Cute2",
	PLAY_TYPE					= XSKIN_ANIM_PLAYTYPE["XAP_ONE_WAIT"],
	TRANSITION					= TRUE,

	MOVE_TYPE           = 0,

	SOUND_PLAY0					= { 0.6, "Pet_SHERIFF_Cute2.ogg" },
	SOUND_PLAY1					= { 1.1, "Pet_SHERIFF_Cute2.ogg" },
	SOUND_PLAY2					= { 1.6, "Pet_SHERIFF_Cute2.ogg" },
	SOUND_PLAY3					= { 2.1, "Pet_SHERIFF_Cute2.ogg" },
	SOUND_PLAY4					= { 2.6, "Pet_SHERIFF_Cute2.ogg" },
	SOUND_PLAY5					= { 3.1, "Pet_SHERIFF_Cute2.ogg" },
	SOUND_PLAY6					= { 3.6, "Pet_SHERIFF_Cute2.ogg" },
	SOUND_PLAY7					= { 4.1, "Pet_SHERIFF_Cute2.ogg" },

	IMMADIATE_PACKET_SEND		= TRUE,

	ALLOW_DIR_CHANGE			= FALSE,

	EVENT_PROCESS =
	{
		{ STATE_CHANGE_TYPE["SCT_FOOT_ON_LINE_FALSE_DOWN"],	"SHERIFF_NORM_STEB_1_JUMP_DOWN",					},
		{ STATE_CHANGE_TYPE["SCT_MOTION_END"],				"SHERIFF_NORM_STEB_1_WAIT",						},
	},

	TALK_BOX_1 =
	{
		{ RATE = 34, MESSAGE = STR_ID_24237,  },
		{ RATE = 33, MESSAGE = STR_ID_24238,  },
		{ RATE = 33, MESSAGE = STR_ID_24239,  },
	},
	TALK_BOX_2 =
	{
		{ RATE = 34, MESSAGE = STR_ID_24240,  },
		{ RATE = 33, MESSAGE = STR_ID_24241,  },
		{ RATE = 33, MESSAGE = STR_ID_24242,  },
	},
	TALK_BOX =
	{
		{ RATE = 34, MESSAGE = STR_ID_24243,  },
		{ RATE = 33, MESSAGE = STR_ID_24244,  },
		{ RATE = 33, MESSAGE = STR_ID_24245,  },
	},
}

SHERIFF_NORM_STEB_1_SAD =
{
	ANIM_NAME					= "Afraid",
	PLAY_TYPE					= XSKIN_ANIM_PLAYTYPE["XAP_ONE_WAIT"],
	TRANSITION					= TRUE,

	MOVE_TYPE           = 0,


	IMMADIATE_PACKET_SEND		= TRUE,

	ALLOW_DIR_CHANGE			= FALSE,

	EVENT_PROCESS =
	{
		{ STATE_CHANGE_TYPE["SCT_FOOT_ON_LINE_FALSE_DOWN"],	"SHERIFF_NORM_STEB_1_JUMP_DOWN",					},
		{ STATE_CHANGE_TYPE["SCT_MOTION_END"],				"SHERIFF_NORM_STEB_1_WAIT",						},
	},

	TALK_BOX_1 =
	{
		{ RATE = 34, MESSAGE = STR_ID_24255,  },
		{ RATE = 33, MESSAGE = STR_ID_24256,  },
		{ RATE = 33, MESSAGE = STR_ID_24210,  },
	},
	TALK_BOX_2 =
	{
		{ RATE = 34, MESSAGE = STR_ID_24257,  },
		{ RATE = 33, MESSAGE = STR_ID_24258,  },
		{ RATE = 33, MESSAGE = STR_ID_24259,  },
	},
	TALK_BOX =
	{
		{ RATE = 34, MESSAGE = STR_ID_24260,  },
		{ RATE = 33, MESSAGE = STR_ID_24261,  },
		{ RATE = 33, MESSAGE = STR_ID_24262,  },
	},

}

SHERIFF_NORM_STEB_1_CHEER =
{
	ANIM_NAME					= "Cheer",
	PLAY_TYPE					= XSKIN_ANIM_PLAYTYPE["XAP_ONE_WAIT"],
	TRANSITION					= TRUE,

	MOVE_TYPE           = 0,

	SOUND_PLAY0					= { 0.005, "Pet_Cheer_Common.ogg" },
	
	SOUND_PLAY1					= { 1.4+SOUND_FIX_TIME, "Chung_CannonGun_Trigger.ogg" },
	SOUND_PLAY2					= { 1.6+SOUND_FIX_TIME, "Chung_CannonGun_Trigger.ogg" },
	SOUND_PLAY3					= { 1.93+SOUND_FIX_TIME, "Chung_CannonGun_Trigger.ogg" },
	SOUND_PLAY4					= { 2.2+SOUND_FIX_TIME, "Chung_CannonGun_Trigger.ogg" },
	SOUND_PLAY5					= { 2.47+SOUND_FIX_TIME, "Chung_CannonGun_Trigger.ogg" },
	SOUND_PLAY6					= { 2.72+SOUND_FIX_TIME, "Chung_CannonGun_Trigger.ogg" },

	IMMADIATE_PACKET_SEND		= TRUE,

	ALLOW_DIR_CHANGE			= FALSE,

	EVENT_PROCESS =
	{
		{ STATE_CHANGE_TYPE["SCT_FOOT_ON_LINE_FALSE_DOWN"],	"SHERIFF_NORM_STEB_1_JUMP_DOWN",					},
		{ STATE_CHANGE_TYPE["SCT_MOTION_END"],				"SHERIFF_NORM_STEB_1_WAIT",						},
	},

	TALK_BOX_1 =
	{
		{ RATE = 33, MESSAGE = STR_ID_24264 },
		{ RATE = 34, MESSAGE = STR_ID_24265 },
		{ RATE = 33, MESSAGE = STR_ID_24266 },
	},
	TALK_BOX_2 =
	{
		{ RATE = 33, MESSAGE = STR_ID_24264 },
		{ RATE = 34, MESSAGE = STR_ID_24265 },
		{ RATE = 33, MESSAGE = STR_ID_24266 },
	},
	TALK_BOX =
	{
		{ RATE = 33, MESSAGE = STR_ID_24267 },
		{ RATE = 34, MESSAGE = STR_ID_24268 },
		{ RATE = 33, MESSAGE = STR_ID_24269 },
	},
}

SHERIFF_NORM_STEB_1_SPECIAL =
{
	ANIM_NAME					= "Special_A",
	PLAY_TYPE					= XSKIN_ANIM_PLAYTYPE["XAP_ONE_WAIT"],
	TRANSITION					= TRUE,

	MOVE_TYPE           = 0,

	--SOUND_PLAY0					= { 0.9, "Chung_CannonGun_Trigger.ogg" },

	IMMADIATE_PACKET_SEND		= TRUE,

	ALLOW_DIR_CHANGE			= FALSE,

	EVENT_PROCESS =
	{
		{ STATE_CHANGE_TYPE["SCT_FOOT_ON_LINE_FALSE_DOWN"],	"SHERIFF_NORM_STEB_1_JUMP_DOWN",					},
		{ STATE_CHANGE_TYPE["SCT_MOTION_END"],				"SHERIFF_NORM_STEB_1_WAIT",						},
	},

	TALK_BOX_1 =
	{
		{ RATE = 34, MESSAGE = STR_ID_24273 },
		{ RATE = 33, MESSAGE = STR_ID_24274 },
		{ RATE = 33, MESSAGE = STR_ID_24275 },
	},
	TALK_BOX_2 =
	{
		{ RATE = 34, MESSAGE = STR_ID_24273 },
		{ RATE = 33, MESSAGE = STR_ID_24274 },
		{ RATE = 33, MESSAGE = STR_ID_24275 },
	},
	TALK_BOX =
	{
		{ RATE = 34, MESSAGE = STR_ID_24276 },
		{ RATE = 33, MESSAGE = STR_ID_24277 },
		{ RATE = 33, MESSAGE = STR_ID_24278 },
	},
}


SHERIFF_NORM_STEB_1_ATTACK =
{
	ANIM_NAME					= "Attack_A",
	PLAY_TYPE					= XSKIN_ANIM_PLAYTYPE["XAP_ONE_WAIT"],
	TRANSITION					= TRUE,

	MOVE_TYPE           = 0,
	VIEW_TARGET			= TRUE,

	SOUND_PLAY0					= { 0.65+SOUND_FIX_TIME, "Pet_SHERIFF_Attack_A.ogg" },
	SOUND_PLAY1					= { 1.32+SOUND_FIX_TIME, "Pet_SHERIFF_Attack_A.ogg" },
	SOUND_PLAY2					= { 1.7+SOUND_FIX_TIME, "Pet_SHERIFF_Attack_A.ogg" },

	IMMADIATE_PACKET_SEND		= TRUE,

	EVENT_PROCESS =
	{
		{ STATE_CHANGE_TYPE["SCT_FOOT_ON_LINE_FALSE_DOWN"],	"SHERIFF_NORM_STEB_1_JUMP_DOWN",					},
		{ STATE_CHANGE_TYPE["SCT_MOTION_END"],				"SHERIFF_NORM_STEB_1_WAIT",						},
	},

	TALK_BOX_1 =
	{
		{ RATE = 34, MESSAGE = STR_ID_24282 },
		{ RATE = 33, MESSAGE = STR_ID_24283 },
		{ RATE = 33, MESSAGE = STR_ID_24284 },
	},
	TALK_BOX_2 =
	{
		{ RATE = 34, MESSAGE = STR_ID_24282 },
		{ RATE = 33, MESSAGE = STR_ID_24283 },
		{ RATE = 33, MESSAGE = STR_ID_24284 },
	},
	TALK_BOX =
	{
		{ RATE = 34, MESSAGE = STR_ID_24285 },
		{ RATE = 33, MESSAGE = STR_ID_24286 },
		{ RATE = 33, MESSAGE = STR_ID_24287 },
	},
}


SHERIFF_NORM_STEB_1_SIT_START =
{
	ANIM_NAME					= "SitReady",
	PLAY_TYPE					= XSKIN_ANIM_PLAYTYPE["XAP_ONE_WAIT"],
	TRANSITION					= TRUE,

	MOVE_TYPE           = 0,


	IMMADIATE_PACKET_SEND		= TRUE,

	ALLOW_DIR_CHANGE			= FALSE,

	EVENT_PROCESS =
	{
		{ STATE_CHANGE_TYPE["SCT_FOOT_ON_LINE_FALSE_DOWN"],	"SHERIFF_NORM_STEB_1_JUMP_DOWN",					},
		{ STATE_CHANGE_TYPE["SCT_MOTION_END"],				"SHERIFF_NORM_STEB_1_SIT_LOOP",						},
	},

	TALK_BOX_1 =
	{
		{ RATE = 33, MESSAGE = STR_ID_24295,  },
		{ RATE = 33, MESSAGE = STR_ID_24295,  },
		{ RATE = 34, MESSAGE = STR_ID_24295,  },
	},
	TALK_BOX_2 =
	{
		{ RATE = 33, MESSAGE = STR_ID_24295,  },
		{ RATE = 33, MESSAGE = STR_ID_24295,  },
		{ RATE = 34, MESSAGE = STR_ID_24295,  },
	},
	TALK_BOX =
	{
		{ RATE = 33, MESSAGE = STR_ID_24295,  },
		{ RATE = 33, MESSAGE = STR_ID_24295,  },
		{ RATE = 34, MESSAGE = STR_ID_24295,  },
	},
}

SHERIFF_NORM_STEB_1_SIT_LOOP =
{
	ANIM_NAME					= "Sit",
	PLAY_TYPE					= XSKIN_ANIM_PLAYTYPE["XAP_LOOP"],
	TRANSITION					= TRUE,

	MOVE_TYPE           = 0,


	IMMADIATE_PACKET_SEND		= TRUE,

	ALLOW_DIR_CHANGE			= FALSE,

	EVENT_PROCESS =
	{
		{ STATE_CHANGE_TYPE["SCT_FOOT_ON_LINE_FALSE_DOWN"],	"SHERIFF_NORM_STEB_1_JUMP_DOWN",					},
	},
}

SHERIFF_NORM_STEB_1_SIT_END =
{
	ANIM_NAME					= "SitEnd",
	PLAY_TYPE					= XSKIN_ANIM_PLAYTYPE["XAP_ONE_WAIT"],
	TRANSITION					= TRUE,

	MOVE_TYPE           = 0,


	IMMADIATE_PACKET_SEND		= TRUE,

	ALLOW_DIR_CHANGE			= FALSE,

	EVENT_PROCESS =
	{
		{ STATE_CHANGE_TYPE["SCT_FOOT_ON_LINE_FALSE_DOWN"],	"SHERIFF_NORM_STEB_1_JUMP_DOWN",					},
		{ STATE_CHANGE_TYPE["SCT_MOTION_END"],				"SHERIFF_NORM_STEB_1_WAIT",						},
	},

	TALK_BOX_1 =
	{
		{ RATE = 33, MESSAGE = STR_ID_24298,   },
		{ RATE = 33, MESSAGE = STR_ID_24298,   },
		{ RATE = 34, MESSAGE = STR_ID_24298,   },
	},
	TALK_BOX_2 =
	{
		{ RATE = 33, MESSAGE = STR_ID_24298,   },
		{ RATE = 33, MESSAGE = STR_ID_24298,   },
		{ RATE = 34, MESSAGE = STR_ID_24298,   },
	},
	TALK_BOX =
	{
		{ RATE = 33, MESSAGE = STR_ID_24298,   },
		{ RATE = 33, MESSAGE = STR_ID_24298,   },
		{ RATE = 34, MESSAGE = STR_ID_24298,   },
	},
}

SHERIFF_NORM_STEB_1_NOTKNOW =
{
	ANIM_NAME					= "DoNotKnow",
	PLAY_TYPE					= XSKIN_ANIM_PLAYTYPE["XAP_ONE_WAIT"],
	TRANSITION					= TRUE,

	MOVE_TYPE           = 0,


	IMMADIATE_PACKET_SEND		= TRUE,

	ALLOW_DIR_CHANGE			= FALSE,

	EVENT_PROCESS =
	{
		{ STATE_CHANGE_TYPE["SCT_FOOT_ON_LINE_FALSE_DOWN"],	"SHERIFF_NORM_STEB_1_JUMP_DOWN",					},
		{ STATE_CHANGE_TYPE["SCT_MOTION_END"],				"SHERIFF_NORM_STEB_1_WAIT",						},
	},

	-- TALK_BOX_1 =
 	-- {
		-- { RATE = 20, MESSAGE = STR_ID_5600,   },
		-- { RATE = 20, MESSAGE = STR_ID_5601,   },
		-- { RATE = 20, MESSAGE = STR_ID_5602,   },
		-- { RATE = 20, MESSAGE = STR_ID_5603,   },
		-- { RATE = 20, MESSAGE = STR_ID_5604,   },
	-- },
	-- TALK_BOX_2 =
 	-- {
		-- { RATE = 20, MESSAGE = STR_ID_5600,   },
		-- { RATE = 20, MESSAGE = STR_ID_5601,   },
		-- { RATE = 20, MESSAGE = STR_ID_5602,   },
		-- { RATE = 20, MESSAGE = STR_ID_5603,   },
		-- { RATE = 20, MESSAGE = STR_ID_5604,   },
	-- },
	-- TALK_BOX =
 	-- {
		-- { RATE = 20, MESSAGE = STR_ID_5600,   },
		-- { RATE = 20, MESSAGE = STR_ID_5601,   },
		-- { RATE = 20, MESSAGE = STR_ID_5602,   },
		-- { RATE = 20, MESSAGE = STR_ID_5603,   },
		-- { RATE = 20, MESSAGE = STR_ID_5604,   },
	-- },
}





function SHERIFF_NORM_STEB_1_ATTACK_FRAME_MOVE( pKTDXApp, pX2Game, pPet )

	if pPet:AnimEventTimer( 0.65 ) then
		ShotLeftGunBulletFirst_Norm01( pKTDXApp, pX2Game, pPet )
	end
	-- 1타
	if pPet:AnimEventTimer( 1.32 ) then
		ShotLeftGunBulletFirst_Norm01( pKTDXApp, pX2Game, pPet )
	end	
	-- 2타
	if pPet:AnimEventTimer( 1.7 ) then
		ShotRightGunBulletFirst_Norm01( pKTDXApp, pX2Game, pPet )
	end	
	
end

function CF_PETATTACK_SHERIFF_NORM_STEB_1( pKTDXApp, pX2Game, pPet )

	if pX2Game ~= nil then
		if pX2Game:IsHost() == false then
			return false
		end
	end

	if pPet:IsAttacking() == true then

		local fDist = pPet:GetDistTarget()
		if fDist <= 300 then
			return true
		end
	end

	return false
	
end

-- 총알 쏘는 함수 ( 왼쪽 )
function ShotLeftGunBulletFirst_Norm01( pKTDXApp, pX2Game, pPet )
	local pDamageEffect = pX2Game:GetDamageEffect()

	if pDamageEffect ~= nil then
		local vLandPos = pPet:GetLandPosition_LUA()
		local vPos = pPet:GetBonePos_LUA("Bip01_L_Finger1Nub")
		local vRot = pPet:GetRotateDegree()
		
		
		local pMasterUnit = pPet:GetMaster()
		if pMasterUnit ~= nil and pMasterUnit:GetNowHP() > 0 then
			pDamageEffect:CreateInstanceByPet_LUA( pMasterUnit, "PET_SHERIFF_NORM_STEP_01_ATTACK_FIRST", vPos, vLandPos, vRot )
			--pPet:PlaySound_LUA( "Chung_Pistol_Trigger.ogg" )
		end
	end
end

-- 총알 쏘는 함수 ( 오른쪽 )
function ShotRightGunBulletFirst_Norm01( pKTDXApp, pX2Game, pPet )
	local pDamageEffect = pX2Game:GetDamageEffect()

	if pDamageEffect ~= nil then
		local vLandPos = pPet:GetLandPosition_LUA()
		local vPos = pPet:GetBonePos_LUA("Bip01_R_Finger1Nub")
		local vRot = pPet:GetRotateDegree()

		local pMasterUnit = pPet:GetMaster()
		if pMasterUnit ~= nil and pMasterUnit:GetNowHP() > 0 then
			pDamageEffect:CreateInstanceByPet_LUA( pMasterUnit, "PET_SHERIFF_NORM_STEP_01_ATTACK_FIRST", vPos, vLandPos, vRot )
			--pPet:PlaySound_LUA( "Chung_Pistol_Trigger.ogg" )
		end
	end
end

function SHERIFF_NORM_STEB_1_CHEER_FRAME_MOVE( pKTDXApp, pX2Game, pPet )
	
	if pPet:AnimEventTimer( 1.4 ) then
		ShotRightForCheer_Norm01( pKTDXApp, pX2Game, pPet )
	end
	if pPet:AnimEventTimer( 1.6 ) then
		ShotLeftForCheer_Norm01( pKTDXApp, pX2Game, pPet )
	end	
	if pPet:AnimEventTimer( 1.93 ) then
		ShotRightForCheer_Norm01( pKTDXApp, pX2Game, pPet )
	end	

	if pPet:AnimEventTimer( 2.2 ) then
		ShotLeftForCheer_Norm01( pKTDXApp, pX2Game, pPet )
	end	
	if pPet:AnimEventTimer( 2.47 ) then
		ShotRightForCheer_Norm01( pKTDXApp, pX2Game, pPet )
	end
	if pPet:AnimEventTimer( 2.72 ) then
		ShotLeftForCheer_Norm01( pKTDXApp, pX2Game, pPet )
	end
end

-- 격려용 총 쏘는 함수
function ShotRightForCheer_Norm01( pKTDXApp, pX2Game, pPet )
	local pMajorParticle = pX2Game:GetMajorParticle()

	if pMajorParticle ~= nil then
		local vPos = pPet:GetBonePos_LUA("Dummy02")

		local pMasterUnit = pPet:GetMaster()
		if pMasterUnit ~= nil and pMasterUnit:GetNowHP() > 0 then
			pMajorParticle:CreateSequence_LUA( "Pet_Sheriff_Norm_Step1_Attack02", vPos, D3DXVECTOR2(1000,1000), D3DXVECTOR2(1,1) )
		end
	end
end

function ShotLeftForCheer_Norm01( pKTDXApp, pX2Game, pPet )
	local pMajorParticle = pX2Game:GetMajorParticle()

	if pMajorParticle ~= nil then
		local vPos = pPet:GetBonePos_LUA("Dummy01")

		local pMasterUnit = pPet:GetMaster()
		if pMasterUnit ~= nil and pMasterUnit:GetNowHP() > 0 then
			pMajorParticle:CreateSequence_LUA( "Pet_Sheriff_Norm_Step1_Attack02", vPos, D3DXVECTOR2(1000,1000), D3DXVECTOR2(1,1) )
		end
	end
end