-- lua header. UTF-8 인코딩 인식을 위해 이 줄은 지우지 마세요.


INIT_SYSTEM =
{
	UNIT_LAYER		= X2_LAYER["XL_UNIT_0"],
	UNIT_SCALE		= 1,
}


INIT_DEVICE =
{
	READY_XSKIN_MESH =
	{

	},

	READY_TEXTURE =
	{
	},

	READY_SOUND =
	{
	 "Pet_SNOWBUMP_Special_Attack_B.ogg",
	 "Pet_SNOWBUMP_Special_Hello.ogg",
	 "Pet_SNOWBUMP_Special_Cute1.ogg",
	 "Pet_SNOWBUMP_Special_Cute2.ogg",
	 "Pet_SNOWBUMP_Special.ogg",
	 "Pet_SNOWBUMP_Habit.ogg",
	 "Pet_SNOWBUMP_Special_DashEnd.ogg",
	 "Pet_SNOWBUMP_Special_SleepLoop.ogg",
	 "Pet_DashEnd.ogg",
	 "JumpLand.ogg",
	 "Pet_Hungry.ogg",
	 "Pet_Stuffed.ogg",
	 },
}

INIT_MOTION =
{
	MOTION_FILE_NAME		= "Motion_PET_SNOWBUMP_STEB_3.x",	
	--MOTION_ANI_TEX_XET		= "Pet_HALLOWEEN_PUMPKIN_ELDENA_SLEEP_3.xet",
}
--[[
ATTACHED_PARTICLE =
{
    { 
        PARTICLE_NAME = "EffectSet_PUMPKIN_ELDENA_Wait",
        BONE_NAME = "Dummy_Weapon",
    },
    { 
        PARTICLE_NAME = "EffectSet_PUMPKIN_ELDENA_Wait02",
        BONE_NAME = "Dummy_Weapon",
    },
}
--]]
INIT_COMPONENT =
{
	MAX_HP				= 6000,
	MP_CHANGE_RATE		= 1,
	MP_CHARGE_RATE		= 130,


	SHADOW_SIZE			= 200,
	SHADOW_FILE_NAME	= "shadow.dds",

	SMALL_HP_BAR_BLUE	= "Small_HP_bar_Blue.TGA",
	SMALL_HP_BAR_RED	= "Small_HP_bar_Red.TGA",
	SMALL_HP_BAR_YELLOW = "Small_HP_bar_Yellow.TGA",

	QUESTION_MARK_SEQ		= "QuestionMarkNPC",
	EXCLAMATION_MARK_SEQ	= "ExclamationMarkNPC",

	HYPER_MODE_COUNT	= 0,
	MAX_HYPER_MODE_TIME	= 30,

	HITTED_TYPE			= HITTED_TYPE["HTD_MEAT"],

	FALL_DOWN			= TRUE,



}

INIT_STATE =
{
	{ STATE_NAME = "PETIT_SNOW_BUMP_SUMMON",			},
	{ STATE_NAME = "PETIT_SNOW_BUMP_WAIT_HABIT",		STATE_COOL_TIME = 20, },
	{ STATE_NAME = "PETIT_SNOW_BUMP_WAIT",						},
	{ STATE_NAME = "PETIT_SNOW_BUMP_WALK",						},
	{ STATE_NAME = "PETIT_SNOW_BUMP_DASH",			}, 
	{ STATE_NAME = "PETIT_SNOW_BUMP_DASH_END",					},
	{ STATE_NAME = "PETIT_SNOW_BUMP_JUMP_UP",					},
	{ STATE_NAME = "PETIT_SNOW_BUMP_JUMP_DOWN",				},
	{ STATE_NAME = "PETIT_SNOW_BUMP_JUMP_UP_DIR",				},
	{ STATE_NAME = "PETIT_SNOW_BUMP_JUMP_DOWN_DIR",			},
	{ STATE_NAME = "PETIT_SNOW_BUMP_JUMP_LANDING",				},
	{ STATE_NAME = "PETIT_SNOW_BUMP_EAT",				},
	{ STATE_NAME = "PETIT_SNOW_BUMP_HUNGRY",				},
	{ STATE_NAME = "PETIT_SNOW_BUMP_STUFFED",				},
	{ STATE_NAME = "PETIT_SNOW_BUMP_SLEEP_START",				},
	{ STATE_NAME = "PETIT_SNOW_BUMP_SLEEP_LOOP",				},
	{ STATE_NAME = "PETIT_SNOW_BUMP_SLEEP_END",				},
	{ STATE_NAME = "PETIT_SNOW_BUMP_AFRAID",				STATE_COOL_TIME = 10, },
	{ STATE_NAME = "PETIT_SNOW_BUMP_HELLO",				},
	{ STATE_NAME = "PETIT_SNOW_BUMP_HAPPY1",				},
	{ STATE_NAME = "PETIT_SNOW_BUMP_HAPPY2",				},
	{ STATE_NAME = "PETIT_SNOW_BUMP_CUTE1",				STATE_COOL_TIME = 10, },
	{ STATE_NAME = "PETIT_SNOW_BUMP_CUTE2",				STATE_COOL_TIME = 10, },	
	{ STATE_NAME = "PETIT_SNOW_BUMP_SAD",				},
	{ STATE_NAME = "PETIT_SNOW_BUMP_CHEER",			STATE_COOL_TIME = 180,	},
	{ STATE_NAME = "PETIT_SNOW_BUMP_SPECIAL",			LUA_FRAME_MOVE_FUNC = "PETIT_SNOW_BUMP_SPECIAL_FRAME_MOVE",	},
	{ STATE_NAME = "PETIT_SNOW_BUMP_ATTACK",			LUA_FRAME_MOVE_FUNC = "PETIT_SNOW_BUMP_ATTACK_FRAME_MOVE",	},
	{ STATE_NAME = "PETIT_SNOW_BUMP_SIT_START",				},
	{ STATE_NAME = "PETIT_SNOW_BUMP_SIT_LOOP",				},
	{ STATE_NAME = "PETIT_SNOW_BUMP_SIT_END",				},
	{ STATE_NAME = "PETIT_SNOW_BUMP_NOTKNOW",				},

	START_STATE					= "PETIT_SNOW_BUMP_SUMMON",
	WAIT_HABIT					= "PETIT_SNOW_BUMP_WAIT_HABIT",
	WAIT_STATE					= "PETIT_SNOW_BUMP_WAIT",
	EAT_STATE           = "PETIT_SNOW_BUMP_EAT",
	HUNGRY_STATE       = "PETIT_SNOW_BUMP_HUNGRY",
	STUFFED_STATE       = "PETIT_SNOW_BUMP_STUFFED",
	SLEEP_START_STATE   = "PETIT_SNOW_BUMP_SLEEP_START",
	SLEEP_LOOP_STATE   = "PETIT_SNOW_BUMP_SLEEP_LOOP",
	SLEEP_END_STATE     = "PETIT_SNOW_BUMP_SLEEP_END",
	AFRAID_STATE        = "PETIT_SNOW_BUMP_AFRAID",
	HELLO_STATE         = "PETIT_SNOW_BUMP_HELLO",
	HAPPY1_STATE         = "PETIT_SNOW_BUMP_HAPPY1",
	HAPPY2_STATE         = "PETIT_SNOW_BUMP_HAPPY2",
	CUTE1_STATE          = "PETIT_SNOW_BUMP_CUTE1",
	CUTE2_STATE          = "PETIT_SNOW_BUMP_CUTE2",
	SAD_STATE           = "PETIT_SNOW_BUMP_SAD",
	CHEER_STATE         = "PETIT_SNOW_BUMP_CHEER",
	SPECIAL_STATE       = "PETIT_SNOW_BUMP_SPECIAL",
	ATTACK_STATE      = "PETIT_SNOW_BUMP_ATTACK",
	SIT_START_STATE     = "PETIT_SNOW_BUMP_SIT_START",
	SIT_LOOP_STATE     = "PETIT_SNOW_BUMP_SIT_LOOP",
	SIT_END_STATE       = "PETIT_SNOW_BUMP_SIT_END",
	NOTKNOW_STATE       = "PETIT_SNOW_BUMP_NOTKNOW",
}

INIT_AI =
{
	TARGET =
	{
		TARGET_PRIORITY 			= TARGET_PRIORITY["TP_LOW_HP_FIRST"],
		TARGET_INTERVAL				= 0.5,		-- sec
		TARGET_NEAR_RANGE			= 200,		-- 이 거리보다 가까우면 TARGET_SUCCESS_RATE에 관계없이 무조건 타게팅된다
		TARGET_RANGE				= 10000,		-- cm
		TARGET_LOST_RANGE			= 2000,	-- cm
		TARGET_SUCCESS_RATE			= 100,  --70,		-- %
		ATTACK_TARGET_RATE			= 100, -- 80,		-- 나를 공격한 유닛을 타게팅할 확률
		PRESERVE_LAST_TARGET_RATE	= 100, -- 80,		-- 이전에 타게팅된 유닛을 계속 타게팅할 확률
	},

	CHASE_MOVE =
	{
		MOVE_SPLIT_RANGE	= 100,
		DEST_GAP			= 200,	-- 목적지에서 이 거리 안에 있으면 도착했다고 판단한다
		MOVE_GAP			= 100,
		RUN_GAP				= 500,

		DIR_CHANGE_INTERVAL = 0.3,

		WALK_INTERVAL		= 1,
		NEAR_WALK_RATE		= 100,   --  70,
		FAR_WALK_RATE		= 100,   -- 30,

		JUMP_INTERVAL		= 0,
		UP_JUMP_RATE		= 0, -- 40,
		UP_DOWN_RATE		= 0,
		DOWN_JUMP_RATE		= 0,    --  20,
		DOWN_DOWN_RATE		= 0,
	},

}

PETIT_SNOW_BUMP_SUMMON =
{
	ANIM_NAME					= "Wait",
	PLAY_TYPE					= XSKIN_ANIM_PLAYTYPE["XAP_ONE_WAIT"],
	TRANSITION					= TRUE,

	MOVE_TYPE           = 0,

	CAN_PUSH_UNIT				= TRUE,
	CAN_PASS_UNIT				= FALSE,
	IMMADIATE_PACKET_SEND		= TRUE,

	ALLOW_DIR_CHANGE			= FALSE,

	EVENT_PROCESS =
	{
		{ STATE_CHANGE_TYPE["SCT_FOOT_ON_LINE_FALSE_DOWN"],	"PETIT_SNOW_BUMP_JUMP_DOWN",					},
		{ STATE_CHANGE_TYPE["SCT_MOTION_END"],				"PETIT_SNOW_BUMP_WAIT",						},
	},
}

PETIT_SNOW_BUMP_WAIT =
{
	ANIM_NAME					= "Wait",
	PLAY_TYPE					= XSKIN_ANIM_PLAYTYPE["XAP_LOOP"],
	TRANSITION					= TRUE,

	MOVE_TYPE           = 0,

	IMMADIATE_PACKET_SEND		= TRUE,
	EVENT_INTERVAL_TIME0		= 2,

	EVENT_PROCESS =
	{
		{ STATE_CHANGE_TYPE["SCT_FOOT_ON_LINE_FALSE_DOWN"],	"PETIT_SNOW_BUMP_JUMP_DOWN",					},

		{ STATE_CHANGE_TYPE["SCT_CONDITION_FUNCTION"],      "PETIT_SNOW_BUMP_ATTACK",						"CF_PETATTACK_PETIT_SNOW_BUMP"    },

		{ STATE_CHANGE_TYPE["SCT_AI_DIR_CHANGE"],			"PETIT_SNOW_BUMP_WALK",						},

		{ STATE_CHANGE_TYPE["SCT_AI_WALK"],					"PETIT_SNOW_BUMP_WALK",						},
		{ STATE_CHANGE_TYPE["SCT_AI_DASH"],					"PETIT_SNOW_BUMP_DASH",						},
		{ STATE_CHANGE_TYPE["SCT_AI_JUMP"],					"PETIT_SNOW_BUMP_JUMP_UP",						},
		{ STATE_CHANGE_TYPE["SCT_AI_JUMP_DIR"],				"PETIT_SNOW_BUMP_JUMP_UP_DIR",					},
		{ STATE_CHANGE_TYPE["SCT_AI_DOWN"],					"PETIT_SNOW_BUMP_JUMP_DOWN",					},
		{ STATE_CHANGE_TYPE["SCT_AI_DOWN_DIR"],				"PETIT_SNOW_BUMP_JUMP_DOWN_DIR",				},
	},
}


PETIT_SNOW_BUMP_WALK =
{
	ANIM_NAME					= "Walk",
	PLAY_TYPE					= XSKIN_ANIM_PLAYTYPE["XAP_LOOP"],
	TRANSITION					= TRUE,

	CAN_PUSH_UNIT				= TRUE,
	CAN_PASS_UNIT				= FALSE,

	MOVE_TYPE           = 1,
	PASSIVE_SPEED_X_BY_USER			= 1.2,

	IMMADIATE_PACKET_SEND		= TRUE,

	EVENT_INTERVAL_TIME0		= 2,

	EVENT_PROCESS =
	{
		{ STATE_CHANGE_TYPE["SCT_FOOT_ON_LINE_FALSE_DOWN"],	"PETIT_SNOW_BUMP_JUMP_DOWN_DIR",				},

		{ STATE_CHANGE_TYPE["SCT_CONDITION_FUNCTION"],      "PETIT_SNOW_BUMP_ATTACK",						"CF_PETATTACK_PETIT_SNOW_BUMP"    },

		{ STATE_CHANGE_TYPE["SCT_AI_WAIT"],					"PETIT_SNOW_BUMP_WAIT",						},
		{ STATE_CHANGE_TYPE["SCT_AI_DASH"],					"PETIT_SNOW_BUMP_DASH",						},

		{ STATE_CHANGE_TYPE["SCT_AI_JUMP"],					"PETIT_SNOW_BUMP_JUMP_UP",						},
		{ STATE_CHANGE_TYPE["SCT_AI_JUMP_DIR"],				"PETIT_SNOW_BUMP_JUMP_UP_DIR",					},
		{ STATE_CHANGE_TYPE["SCT_AI_DOWN"],					"PETIT_SNOW_BUMP_JUMP_DOWN",					},
		{ STATE_CHANGE_TYPE["SCT_AI_DOWN_DIR"],				"PETIT_SNOW_BUMP_JUMP_DOWN_DIR",				},
	},

}

PETIT_SNOW_BUMP_DASH =
{
	ANIM_NAME					= "Dash",
	PLAY_TYPE					= XSKIN_ANIM_PLAYTYPE["XAP_LOOP"],
	TRANSITION					= TRUE,

	CAN_PUSH_UNIT				= TRUE,
	CAN_PASS_UNIT				= FALSE,


	MOVE_TYPE           = 2,
	PASSIVE_SPEED_X_BY_USER			= 1.4,

	ALLOW_DIR_CHANGE			= TRUE,
	IMMADIATE_PACKET_SEND		= TRUE,

	EVENT_INTERVAL_TIME0		= 1,

	EVENT_PROCESS =
	{
		{ STATE_CHANGE_TYPE["SCT_FOOT_ON_LINE_FALSE_DOWN"],	"PETIT_SNOW_BUMP_JUMP_DOWN_DIR",				},

		{ STATE_CHANGE_TYPE["SCT_CONDITION_FUNCTION"],      "PETIT_SNOW_BUMP_ATTACK",						"CF_PETATTACK_PETIT_SNOW_BUMP"    },

		{ STATE_CHANGE_TYPE["SCT_AI_WAIT"],					"PETIT_SNOW_BUMP_DASH_END",							},
		{ STATE_CHANGE_TYPE["SCT_AI_WALK"],					"PETIT_SNOW_BUMP_WALK",							},
		{ STATE_CHANGE_TYPE["SCT_AI_JUMP"],					"PETIT_SNOW_BUMP_JUMP_UP",						},
		{ STATE_CHANGE_TYPE["SCT_AI_JUMP_DIR"],				"PETIT_SNOW_BUMP_JUMP_UP_DIR",					},
		{ STATE_CHANGE_TYPE["SCT_AI_DOWN"],					"PETIT_SNOW_BUMP_JUMP_DOWN",					},
		{ STATE_CHANGE_TYPE["SCT_AI_DOWN_DIR"],				"PETIT_SNOW_BUMP_JUMP_DOWN_DIR",				},
	},

	TALK_BOX_1 =	
	{	
		{ RATE = 7, MESSAGE = STR_ID_29073 }, --난 천천히 걷는게 더 좋은데..
		{ RATE = 7, MESSAGE = STR_ID_29074 }, --널 위해서 날아볼께 ~
		{ RATE = 7, MESSAGE = STR_ID_29075 }, --천천히 가~ 나 힘들어~
	},	
	TALK_BOX_2 =	
	{	
		{ RATE = 7, MESSAGE = STR_ID_29076 }, --후훗, 이정도는 따라 갈수 있어
		{ RATE = 7, MESSAGE = STR_ID_29077 }, --내 하루 종일도 날수 있어 ~
		{ RATE = 7, MESSAGE = STR_ID_29078 }, --훨~훨~ 우와하게 날기 ♡
	},	
	TALK_BOX =	
	{	
		{ RATE = 7, MESSAGE = STR_ID_29079 }, --함께 한다면야 어디든.. 
		{ RATE = 7, MESSAGE = STR_ID_29080 }, --난 더 높게 날꺼야 ♡
		{ RATE = 7, MESSAGE = STR_ID_29081 }, --사탕 주면 더 빨리 날께 ♡
	},	


}

PETIT_SNOW_BUMP_DASH_END =
{
	ANIM_NAME					= "DashEnd",
	PLAY_TYPE					= XSKIN_ANIM_PLAYTYPE["XAP_ONE_WAIT"],
	TRANSITION					= FALSE,

	CAN_PUSH_UNIT				= TRUE,
	CAN_PASS_UNIT				= FALSE,

	SPEED_X				= 700,

	SOUND_PLAY0					= { 0.001, "Pet_SNOWBUMP_Special_DashEnd.ogg" },

	ALLOW_DIR_CHANGE			= TRUE,
	IMMADIATE_PACKET_SEND		= TRUE,

	EVENT_PROCESS =
	{
		{ STATE_CHANGE_TYPE["SCT_FOOT_ON_LINE_FALSE_DOWN"],	"PETIT_SNOW_BUMP_JUMP_DOWN_DIR",				},

		{ STATE_CHANGE_TYPE["SCT_MOTION_END"],				"PETIT_SNOW_BUMP_WAIT",							},

		{ STATE_CHANGE_TYPE["SCT_AI_WAIT"],					"PETIT_SNOW_BUMP_WAIT",							},
		{ STATE_CHANGE_TYPE["SCT_AI_WALK"],					"PETIT_SNOW_BUMP_WALK",							},
		{ STATE_CHANGE_TYPE["SCT_AI_JUMP"],					"PETIT_SNOW_BUMP_JUMP_UP",						},
		{ STATE_CHANGE_TYPE["SCT_AI_JUMP_DIR"],				"PETIT_SNOW_BUMP_JUMP_UP_DIR",					},
		{ STATE_CHANGE_TYPE["SCT_AI_DOWN"],					"PETIT_SNOW_BUMP_JUMP_DOWN",					},
		{ STATE_CHANGE_TYPE["SCT_AI_DOWN_DIR"],				"PETIT_SNOW_BUMP_JUMP_DOWN_DIR",				},
	},
}


PETIT_SNOW_BUMP_JUMP_UP =
{
	ANIM_NAME					= "JumpUp",
	PLAY_TYPE					= XSKIN_ANIM_PLAYTYPE["XAP_LOOP"],
	TRANSITION					= TRUE,
	LAND_CONNECT				= FALSE,

	CAN_PUSH_UNIT				= TRUE,
	CAN_PASS_UNIT				= FALSE,

	MOVE_TYPE           = 3,
	SPEED_Y_BY_USER			= 1,
	ADD_POS_Y					= 45,

	IMMADIATE_PACKET_SEND		= TRUE,

	EVENT_PROCESS =
	{

		{ STATE_CHANGE_TYPE["SCT_NEGATIVE_Y_SPEED"],		"PETIT_SNOW_BUMP_JUMP_DOWN",				},
	},


}

PETIT_SNOW_BUMP_JUMP_DOWN =
{
	ANIM_NAME					= "JumpDown",
	PLAY_TYPE					= XSKIN_ANIM_PLAYTYPE["XAP_LOOP"],
	TRANSITION					= TRUE,
	LAND_CONNECT				= FALSE,

	CAN_PUSH_UNIT				= TRUE,
	CAN_PASS_UNIT				= FALSE,



	IMMADIATE_PACKET_SEND		= TRUE,

	EVENT_PROCESS =
	{
		{ STATE_CHANGE_TYPE["SCT_FOOT_ON_LINE_TRUE"],		"PETIT_SNOW_BUMP_JUMP_LANDING",				},
	},
}


PETIT_SNOW_BUMP_JUMP_UP_DIR =
{
	ANIM_NAME					= "JumpUp",
	PLAY_TYPE					= XSKIN_ANIM_PLAYTYPE["XAP_LOOP"],
	TRANSITION					= TRUE,
	LAND_CONNECT				= FALSE,

	CAN_PUSH_UNIT				= TRUE,
	CAN_PASS_UNIT				= FALSE,

	MOVE_TYPE           = 4,
	PASSIVE_SPEED_X_BY_USER = 1.2,
	SPEED_Y_BY_USER			= 1,
	ADD_POS_Y					= 45,

	IMMADIATE_PACKET_SEND		= TRUE,

	EVENT_PROCESS =
	{

		{ STATE_CHANGE_TYPE["SCT_NEGATIVE_Y_SPEED"],		"PETIT_SNOW_BUMP_JUMP_DOWN_DIR",				},
	},


}

PETIT_SNOW_BUMP_JUMP_DOWN_DIR =
{
	ANIM_NAME					= "JumpDown",
	PLAY_TYPE					= XSKIN_ANIM_PLAYTYPE["XAP_LOOP"],
	TRANSITION					= TRUE,
	LAND_CONNECT				= FALSE,

	CAN_PUSH_UNIT				= TRUE,
	CAN_PASS_UNIT				= FALSE,


	MOVE_TYPE           = 1,
	PASSIVE_SPEED_X_BY_USER = 1,

	IMMADIATE_PACKET_SEND		= TRUE,

	EVENT_PROCESS =
	{
		{ STATE_CHANGE_TYPE["SCT_FOOT_ON_LINE_TRUE"],		"PETIT_SNOW_BUMP_JUMP_LANDING",				},
	},
}

PETIT_SNOW_BUMP_JUMP_LANDING =
{
	ANIM_NAME					= "JumpDownLanding",
	PLAY_TYPE					= XSKIN_ANIM_PLAYTYPE["XAP_ONE_WAIT"],
	TRANSITION					= TRUE,
	LAND_CONNECT				= FALSE,

	CAN_PUSH_UNIT				= TRUE,
	CAN_PASS_UNIT				= FALSE,

	SOUND_PLAY0					= { 0.093, "JumpLand.ogg" },

	MOVE_TYPE = 0,

	IMMADIATE_PACKET_SEND		= TRUE,

	EVENT_PROCESS =
	{
		{ STATE_CHANGE_TYPE["SCT_FOOT_ON_LINE_FALSE_DOWN"],	"PETIT_SNOW_BUMP_JUMP_DOWN",				},
		{ STATE_CHANGE_TYPE["SCT_MOTION_END"],				"PETIT_SNOW_BUMP_WAIT",					},
	},

}



PETIT_SNOW_BUMP_WAIT_HABIT =
{
	ANIM_NAME					= "WaitHabit",
	PLAY_TYPE					= XSKIN_ANIM_PLAYTYPE["XAP_ONE_WAIT"],
	TRANSITION					= TRUE,

	MOVE_TYPE           = 0,


	CAN_PUSH_UNIT				= TRUE,
	CAN_PASS_UNIT				= FALSE,
	IMMADIATE_PACKET_SEND		= TRUE,

	ALLOW_DIR_CHANGE			= FALSE,

	EVENT_PROCESS =
	{
		{ STATE_CHANGE_TYPE["SCT_FOOT_ON_LINE_FALSE_DOWN"],	"PETIT_SNOW_BUMP_JUMP_DOWN",					},
		{ STATE_CHANGE_TYPE["SCT_MOTION_END"],				"PETIT_SNOW_BUMP_WAIT",						},
	},

	TALK_BOX_1 =	
	{	
		{ RATE = 7, MESSAGE = STR_ID_29082 }, --나 잠시 쉬어도 돼?
		{ RATE = 7, MESSAGE = STR_ID_29083 }, --미인은 잠꾸러기야
		{ RATE = 7, MESSAGE = STR_ID_29084 }, --아~ 오늘은 한가하네? 데이트 할까?
	},	
	TALK_BOX_2 =	
	{	
		{ RATE = 7, MESSAGE = STR_ID_29085 }, --오늘은 나른한거 같아~ 
		{ RATE = 7, MESSAGE = STR_ID_29086 }, --내 스타일, 어때?  마음에 들어?
		{ RATE = 7, MESSAGE = STR_ID_29087 }, --난 막대 사탕을 좋아해, 기억해둬, 후훗
	},	
	TALK_BOX =	
	{	
		{ RATE = 7, MESSAGE = STR_ID_29088 }, --하루 종일 나랑 같이 있어줘~ ♡
		{ RATE = 7, MESSAGE = STR_ID_29089 }, --나에게 어떤 애칭을 만들어 줄꺼야? ♡
		{ RATE = 7, MESSAGE = STR_ID_29090 }, --나 이뻐? 사탕이 더 좋아? 내가 더 좋아?
	},	

}

PETIT_SNOW_BUMP_EAT =
{
	ANIM_NAME					= "Eat",
	PLAY_TYPE					= XSKIN_ANIM_PLAYTYPE["XAP_ONE_WAIT"],
	TRANSITION					= TRUE,

	MOVE_TYPE           = 0,


	IMMADIATE_PACKET_SEND		= TRUE,

		ALLOW_DIR_CHANGE			= FALSE,

	EVENT_PROCESS =
	{
		{ STATE_CHANGE_TYPE["SCT_FOOT_ON_LINE_FALSE_DOWN"],	"PETIT_SNOW_BUMP_JUMP_DOWN",					},
		{ STATE_CHANGE_TYPE["SCT_MOTION_END"],				"PETIT_SNOW_BUMP_WAIT",						},
	},

	TALK_BOX_1 =	
	{	
		{ RATE = 34, MESSAGE = STR_ID_29091, APPLY_INTIMACY = TRUE, }, --후훗, 먹을만 한거지?
		{ RATE = 33, MESSAGE = STR_ID_29092, APPLY_INTIMACY = TRUE, }, --아앙~ 난 고급스러운게 좋아 ♡
		{ RATE = 33, MESSAGE = STR_ID_29093, APPLY_INTIMACY = TRUE, }, --맛있어, 고마워 ~
	},	
	TALK_BOX_2 =	
	{	
		{ RATE = 34, MESSAGE = STR_ID_29094, APPLY_INTIMACY = TRUE, }, --꺄아~ 잘먹겠습니다~
		{ RATE = 33, MESSAGE = STR_ID_29095, APPLY_INTIMACY = TRUE, }, --음~ 맛있어 ♡
		{ RATE = 33, MESSAGE = STR_ID_29096, APPLY_INTIMACY = TRUE, }, --아앙~ 너도 한입 먹을래~?
	},	
	TALK_BOX =	
	{	
		{ RATE = 34, MESSAGE = STR_ID_29097, APPLY_INTIMACY = TRUE, }, --너가 주는 음식은 질리지 않아 ♡
		{ RATE = 33, MESSAGE = STR_ID_29098, APPLY_INTIMACY = TRUE, }, --난 달콤한게 좋아 ♡
		{ RATE = 33, MESSAGE = STR_ID_29099, APPLY_INTIMACY = TRUE, }, --맛.있.어 ♡
	},	

}

PETIT_SNOW_BUMP_HUNGRY =
{
	ANIM_NAME					= "Hungry",
	PLAY_TYPE					= XSKIN_ANIM_PLAYTYPE["XAP_ONE_WAIT"],
	TRANSITION					= TRUE,

	MOVE_TYPE           = 0,

	SOUND_PLAY0					= { 0.021, "Pet_Hungry.ogg" },

	IMMADIATE_PACKET_SEND		= TRUE,

		ALLOW_DIR_CHANGE			= FALSE,

	EVENT_PROCESS =
	{
		{ STATE_CHANGE_TYPE["SCT_FOOT_ON_LINE_FALSE_DOWN"],	"PETIT_SNOW_BUMP_JUMP_DOWN",					},
		{ STATE_CHANGE_TYPE["SCT_MOTION_END"],				"PETIT_SNOW_BUMP_WAIT",						},
	},

	TALK_BOX_1 =	
	{	
		{ RATE = 34, MESSAGE = STR_ID_29100 }, --꼬륵. 어머 부끄러워라. 
		{ RATE = 33, MESSAGE = STR_ID_29101 }, --꼬르륵.. 눈치게 없으시네
		{ RATE = 33, MESSAGE = STR_ID_29102 }, --나 배고파
	},	
	TALK_BOX_2 =	
	{	
		{ RATE = 34, MESSAGE = STR_ID_29103 }, --나 맛있는거 줄꺼야?
		{ RATE = 33, MESSAGE = STR_ID_29104 }, --맛있는거 안주면 나 울꺼야
		{ RATE = 33, MESSAGE = STR_ID_29105 }, --꼬르륵, 난 배고프게 내버려두다니,,
	},	
	TALK_BOX =	
	{	
		{ RATE = 34, MESSAGE = STR_ID_29106 }, --아앙 맛있는거 줘 ♡
		{ RATE = 33, MESSAGE = STR_ID_29107 }, --맛있는거 주면 내가 고마워 할께
		{ RATE = 33, MESSAGE = STR_ID_29108 }, --나에게 맛있는거 줄꺼야?
	},	

}


PETIT_SNOW_BUMP_STUFFED =
{
	ANIM_NAME					= "Stuffed",
	PLAY_TYPE					= XSKIN_ANIM_PLAYTYPE["XAP_ONE_WAIT"],
	TRANSITION					= TRUE,

	MOVE_TYPE           = 0,

    SOUND_PLAY0					= { 0.021, "Pet_Stuffed.ogg" },

	IMMADIATE_PACKET_SEND		= TRUE,

		ALLOW_DIR_CHANGE			= FALSE,

	EVENT_PROCESS =
	{
		{ STATE_CHANGE_TYPE["SCT_FOOT_ON_LINE_FALSE_DOWN"],	"PETIT_SNOW_BUMP_JUMP_DOWN",					},
		{ STATE_CHANGE_TYPE["SCT_MOTION_END"],				"PETIT_SNOW_BUMP_WAIT",						},
	},

	TALK_BOX_1 =	
	{	
		{ RATE = 34, MESSAGE = STR_ID_29109 }, --이제 됐어~ 
		{ RATE = 33, MESSAGE = STR_ID_29110 }, --배불러~ 
		{ RATE = 33, MESSAGE = STR_ID_29111 }, --지금이 딱 좋아 ♡
	},	
	TALK_BOX_2 =	
	{	
		{ RATE = 34, MESSAGE = STR_ID_29112 }, --아, 여기까지
		{ RATE = 33, MESSAGE = STR_ID_29113 }, --이제 그만~♡
		{ RATE = 33, MESSAGE = STR_ID_29114 }, --후훗, 통이 크네~ 그만~
	},	
	TALK_BOX =	
	{	
		{ RATE = 34, MESSAGE = STR_ID_29115 }, --웰빙이 좋아
		{ RATE = 33, MESSAGE = STR_ID_29116 }, --인제 안먹을꺼야
		{ RATE = 33, MESSAGE = STR_ID_29117 }, --인제 그만 먹고싶어 ♡
	},	

}
---sleep 할 차례임
PETIT_SNOW_BUMP_SLEEP_START =
{
	ANIM_NAME					= "Sleep",
	PLAY_TYPE					= XSKIN_ANIM_PLAYTYPE["XAP_ONE_WAIT"],
	TRANSITION					= TRUE,

	MOVE_TYPE           = 0,


	IMMADIATE_PACKET_SEND		= TRUE,

		ALLOW_DIR_CHANGE			= FALSE,

	EVENT_PROCESS =
	{
		{ STATE_CHANGE_TYPE["SCT_FOOT_ON_LINE_FALSE_DOWN"],	"PETIT_SNOW_BUMP_JUMP_DOWN",					},
		{ STATE_CHANGE_TYPE["SCT_MOTION_END"],				"PETIT_SNOW_BUMP_SLEEP_LOOP",						},
	},
	TALK_BOX_1 =	
	{	
		{ RATE = 34, MESSAGE = STR_ID_29118, APPLY_INTIMACY = TRUE, }, --나 졸려 ♡
		{ RATE = 33, MESSAGE = STR_ID_29119, APPLY_INTIMACY = TRUE, }, --쿠…쿠…쿠울..
		{ RATE = 33, MESSAGE = STR_ID_29120, APPLY_INTIMACY = TRUE, }, --어머?나 코골았어?
	},	
	TALK_BOX_2 =	
	{	
		{ RATE = 34, MESSAGE = STR_ID_29121, APPLY_INTIMACY = TRUE, }, --미인은 잠도 이쁘게 자
		{ RATE = 33, MESSAGE = STR_ID_29122, APPLY_INTIMACY = TRUE, }, --꿈속에서 놀자 ♡
		{ RATE = 33, MESSAGE = STR_ID_29123, APPLY_INTIMACY = TRUE, }, --요정은 어떤 꿈은 꾸게?
	},	
	TALK_BOX =	
	{	
		{ RATE = 34, MESSAGE = STR_ID_29124, APPLY_INTIMACY = TRUE, }, --졸린거 참는건 어려워~♡
		{ RATE = 33, MESSAGE = STR_ID_29125, APPLY_INTIMACY = TRUE, }, --쿠..쿠… 쿠울..
		{ RATE = 33, MESSAGE = STR_ID_29126, APPLY_INTIMACY = TRUE, }, --이따가 깨워~♡
	},	

}

PETIT_SNOW_BUMP_SLEEP_LOOP =
{
	ANIM_NAME					= "SleepLoop",
	PLAY_TYPE					= XSKIN_ANIM_PLAYTYPE["XAP_LOOP"],
	TRANSITION					= TRUE,

	MOVE_TYPE           = 0,

	SOUND_PLAY0					= { 0.001, "Pet_SNOWBUMP_Special_SleepLoop.ogg" },	

	IMMADIATE_PACKET_SEND		= TRUE,

		ALLOW_DIR_CHANGE			= FALSE,

	EVENT_PROCESS =
	{
		{ STATE_CHANGE_TYPE["SCT_FOOT_ON_LINE_FALSE_DOWN"],	"PETIT_SNOW_BUMP_JUMP_DOWN",					},
	},
}

PETIT_SNOW_BUMP_SLEEP_END =
{
	ANIM_NAME					= "SleepEnd",
	PLAY_TYPE					= XSKIN_ANIM_PLAYTYPE["XAP_ONE_WAIT"],
	TRANSITION					= TRUE,

	MOVE_TYPE           = 0,
	
	IMMADIATE_PACKET_SEND		= TRUE,

	ALLOW_DIR_CHANGE			= FALSE,

	EVENT_PROCESS =
	{
		{ STATE_CHANGE_TYPE["SCT_FOOT_ON_LINE_FALSE_DOWN"],	"PETIT_SNOW_BUMP_JUMP_DOWN",					},
		{ STATE_CHANGE_TYPE["SCT_MOTION_END"],				"PETIT_SNOW_BUMP_WAIT",						},
	},

	TALK_BOX_1 =	
	{	
		{ RATE = 34, MESSAGE = STR_ID_29127, APPLY_INTIMACY = TRUE, }, --하~아~암~ 
		{ RATE = 33, MESSAGE = STR_ID_29128, APPLY_INTIMACY = TRUE, }, --잘 잤어?♡
		{ RATE = 33, MESSAGE = STR_ID_29129, APPLY_INTIMACY = TRUE, }, --날 깨우다니.. 보고싶엇어? ♡
	},	
	TALK_BOX_2 =	
	{	
		{ RATE = 34, MESSAGE = STR_ID_29130, APPLY_INTIMACY = TRUE, }, --나 아직 덜 잤어 ♡
		{ RATE = 33, MESSAGE = STR_ID_29131, APPLY_INTIMACY = TRUE, }, --조금만 더 자면 안돼? ♡
		{ RATE = 33, MESSAGE = STR_ID_29132, APPLY_INTIMACY = TRUE, }, --아잉~ 일어나기 싫어~ ♡
	},	
	TALK_BOX =	
	{	
		{ RATE = 34, MESSAGE = STR_ID_29133, APPLY_INTIMACY = TRUE, }, --으음, 몇시지?
		{ RATE = 33, MESSAGE = STR_ID_29134, APPLY_INTIMACY = TRUE, }, --미인은 잠꾸러기라니까..
		{ RATE = 33, MESSAGE = STR_ID_29135, APPLY_INTIMACY = TRUE, }, --벌써 깨웠어?
	},	

}

PETIT_SNOW_BUMP_AFRAID =
{
	ANIM_NAME					= "Afraid",
	PLAY_TYPE					= XSKIN_ANIM_PLAYTYPE["XAP_ONE_WAIT"],
	TRANSITION					= TRUE,

	MOVE_TYPE           = 0,


	IMMADIATE_PACKET_SEND		= TRUE,

	ALLOW_DIR_CHANGE			= FALSE,

	EVENT_PROCESS =
	{
		{ STATE_CHANGE_TYPE["SCT_FOOT_ON_LINE_FALSE_DOWN"],	"PETIT_SNOW_BUMP_JUMP_DOWN",					},
		{ STATE_CHANGE_TYPE["SCT_MOTION_END"],				"PETIT_SNOW_BUMP_WAIT",						},
	},

	TALK_BOX_1 =	
	{	
		{ RATE = 34, MESSAGE = STR_ID_29136, APPLY_INTIMACY = TRUE, }, --나 무섭게 하지마..
		{ RATE = 33, MESSAGE = STR_ID_29137, APPLY_INTIMACY = TRUE, }, --무서워서 움직일 수가 없어..
		{ RATE = 33, MESSAGE = STR_ID_29138, APPLY_INTIMACY = TRUE, }, --나 무섭게 내버려둘꺼야?
	},	
	TALK_BOX_2 =	
	{	
		{ RATE = 34, MESSAGE = STR_ID_29139, APPLY_INTIMACY = TRUE, }, --아…안…안돼..
		{ RATE = 33, MESSAGE = STR_ID_29140, APPLY_INTIMACY = TRUE, }, --이렇게 무서운건 처음이야
		{ RATE = 33, MESSAGE = STR_ID_29141, APPLY_INTIMACY = TRUE, }, --꺄~ 무서워 ♡
	},	
	TALK_BOX =	
	{	
		{ RATE = 34, MESSAGE = STR_ID_29142, APPLY_INTIMACY = TRUE, }, --나 무서워.. 바보
		{ RATE = 33, MESSAGE = STR_ID_29143, APPLY_INTIMACY = TRUE, }, --꺄~ 무서워 ♡
		{ RATE = 33, MESSAGE = STR_ID_29144, APPLY_INTIMACY = TRUE, }, --꺄~ 안돼!!
	},	

}

PETIT_SNOW_BUMP_HELLO =
{
	ANIM_NAME					= "Hello",
	PLAY_TYPE					= XSKIN_ANIM_PLAYTYPE["XAP_ONE_WAIT"],
	TRANSITION					= TRUE,

	MOVE_TYPE           = 0,

	SOUND_PLAY0					= { 0.23, "Pet_SNOWBUMP_Special_Hello.ogg" },

	IMMADIATE_PACKET_SEND		= TRUE,

	ALLOW_DIR_CHANGE			= FALSE,

	EVENT_PROCESS =
	{
		{ STATE_CHANGE_TYPE["SCT_FOOT_ON_LINE_FALSE_DOWN"],	"PETIT_SNOW_BUMP_JUMP_DOWN",					},
		{ STATE_CHANGE_TYPE["SCT_MOTION_END"],				"PETIT_SNOW_BUMP_WAIT",						},
	},

	TALK_BOX_1 =	
	{	
		{ RATE = 34, MESSAGE = STR_ID_29145, APPLY_INTIMACY = TRUE, }, --후훗.. 안녕
		{ RATE = 33, MESSAGE = STR_ID_29146, APPLY_INTIMACY = TRUE, }, --안녕? 귀엽다 ~ ♡
		{ RATE = 33, MESSAGE = STR_ID_29147, APPLY_INTIMACY = TRUE, }, --나에게 인사해줘~♡
	},	
	TALK_BOX_2 =	
	{	
		{ RATE = 34, MESSAGE = STR_ID_29148, APPLY_INTIMACY = TRUE, }, --아잉~ 안녕~?
		{ RATE = 33, MESSAGE = STR_ID_29149, APPLY_INTIMACY = TRUE, }, --헬로~ 
		{ RATE = 33, MESSAGE = STR_ID_29150, APPLY_INTIMACY = TRUE, }, --오늘 날씨도 좋은데,,
	},	
	TALK_BOX =	
	{	
		{ RATE = 34, MESSAGE = STR_ID_29151, APPLY_INTIMACY = TRUE, }, --좋은 하루 ♡ 좋은 너 ♡
		{ RATE = 33, MESSAGE = STR_ID_29152, APPLY_INTIMACY = TRUE, }, --다시 만나서 반가워 ♡
		{ RATE = 33, MESSAGE = STR_ID_29153, APPLY_INTIMACY = TRUE, }, --하이 ♡
	},	

}

PETIT_SNOW_BUMP_HAPPY1 =
{
	ANIM_NAME					= "Cute1",
	PLAY_TYPE					= XSKIN_ANIM_PLAYTYPE["XAP_ONE_WAIT"],
	TRANSITION					= TRUE,

	MOVE_TYPE           = 0,

	SOUND_PLAY0					= { 0.7, "Pet_SNOWBUMP_Special_Cute1.ogg" },

	IMMADIATE_PACKET_SEND		= TRUE,

	ALLOW_DIR_CHANGE			= FALSE,

	EVENT_PROCESS =
	{
		{ STATE_CHANGE_TYPE["SCT_FOOT_ON_LINE_FALSE_DOWN"],	"PETIT_SNOW_BUMP_JUMP_DOWN",					},
		{ STATE_CHANGE_TYPE["SCT_MOTION_END"],				"PETIT_SNOW_BUMP_WAIT",						},
	},

	TALK_BOX_1 =	
	{	
		{ RATE = 34, MESSAGE = STR_ID_29154, APPLY_INTIMACY = TRUE, }, --이쁘다고 해줘~ 더 기분 좋아지게~ ♡
		{ RATE = 33, MESSAGE = STR_ID_29155, APPLY_INTIMACY = TRUE, }, --즐거워 ♡
		{ RATE = 33, MESSAGE = STR_ID_29156, APPLY_INTIMACY = TRUE, }, --나 지금 너무 좋은거 같아
	},	
	TALK_BOX_2 =	
	{	
		{ RATE = 34, MESSAGE = STR_ID_29157, APPLY_INTIMACY = TRUE, }, --꺄 ~ 좋아 ~ ♡
		{ RATE = 33, MESSAGE = STR_ID_29158, APPLY_INTIMACY = TRUE, }, --한마디로 좋아 ♡
		{ RATE = 33, MESSAGE = STR_ID_29159, APPLY_INTIMACY = TRUE, }, --행복한거 같아 ♡
	},	
	TALK_BOX =	
	{	
		{ RATE = 34, MESSAGE = STR_ID_29160, APPLY_INTIMACY = TRUE, }, --나 너무 기뻐 ♡
		{ RATE = 33, MESSAGE = STR_ID_29161, APPLY_INTIMACY = TRUE, }, --날 기쁘게 해줘서 고마워~ ♡
		{ RATE = 33, MESSAGE = STR_ID_29162, APPLY_INTIMACY = TRUE, }, --너 정말 대단한데? 날 이렇게 기쁘게 해주다니. 
	},	

}

PETIT_SNOW_BUMP_HAPPY2 =
{
	ANIM_NAME					= "Cute2",
	PLAY_TYPE					= XSKIN_ANIM_PLAYTYPE["XAP_ONE_WAIT"],
	TRANSITION					= TRUE,

	MOVE_TYPE           = 0,

	SOUND_PLAY0					= { 1.01, "Pet_SNOWBUMP_Special_Cute2.ogg" },

	IMMADIATE_PACKET_SEND		= TRUE,

	ALLOW_DIR_CHANGE			= FALSE,

	EVENT_PROCESS =
	{
		{ STATE_CHANGE_TYPE["SCT_FOOT_ON_LINE_FALSE_DOWN"],	"PETIT_SNOW_BUMP_JUMP_DOWN",					},
		{ STATE_CHANGE_TYPE["SCT_MOTION_END"],				"PETIT_SNOW_BUMP_WAIT",						},
	},

	TALK_BOX_1 =	
	{	
		{ RATE = 34, MESSAGE = STR_ID_29154, APPLY_INTIMACY = TRUE, }, --이쁘다고 해줘~ 더 기분 좋아지게~ ♡
		{ RATE = 33, MESSAGE = STR_ID_29155, APPLY_INTIMACY = TRUE, }, --즐거워 ♡
		{ RATE = 33, MESSAGE = STR_ID_29156, APPLY_INTIMACY = TRUE, }, --나 지금 너무 좋은거 같아
	},	
	TALK_BOX_2 =	
	{	
		{ RATE = 34, MESSAGE = STR_ID_29157, APPLY_INTIMACY = TRUE, }, --꺄 ~ 좋아 ~ ♡
		{ RATE = 33, MESSAGE = STR_ID_29158, APPLY_INTIMACY = TRUE, }, --한마디로 좋아 ♡
		{ RATE = 33, MESSAGE = STR_ID_29159, APPLY_INTIMACY = TRUE, }, --행복한거 같아 ♡
	},	
	TALK_BOX =	
	{	
		{ RATE = 34, MESSAGE = STR_ID_29160, APPLY_INTIMACY = TRUE, }, --나 너무 기뻐 ♡
		{ RATE = 33, MESSAGE = STR_ID_29161, APPLY_INTIMACY = TRUE, }, --날 기쁘게 해줘서 고마워~ ♡
		{ RATE = 33, MESSAGE = STR_ID_29162, APPLY_INTIMACY = TRUE, }, --너 정말 대단한데? 날 이렇게 기쁘게 해주다니. 
	},	

}

PETIT_SNOW_BUMP_CUTE1 =
{
	ANIM_NAME					= "Cute1",
	PLAY_TYPE					= XSKIN_ANIM_PLAYTYPE["XAP_ONE_WAIT"],
	TRANSITION					= TRUE,

	MOVE_TYPE           = 0,

	SOUND_PLAY0					= { 0.7, "Pet_SNOWBUMP_Special_Cute1.ogg" },

	IMMADIATE_PACKET_SEND		= TRUE,

	ALLOW_DIR_CHANGE			= FALSE,

	EVENT_PROCESS =
	{
		{ STATE_CHANGE_TYPE["SCT_FOOT_ON_LINE_FALSE_DOWN"],	"PETIT_SNOW_BUMP_JUMP_DOWN",					},
		{ STATE_CHANGE_TYPE["SCT_MOTION_END"],				"PETIT_SNOW_BUMP_WAIT",						},
	},

	TALK_BOX_1 =	
	{	
		{ RATE = 34, MESSAGE = STR_ID_29163, APPLY_INTIMACY = TRUE, }, --후훗 ♡
		{ RATE = 33, MESSAGE = STR_ID_29164, APPLY_INTIMACY = TRUE, }, --이정도는 돼야지? ♡
		{ RATE = 33, MESSAGE = STR_ID_29165, APPLY_INTIMACY = TRUE, }, --살짝 웃는게 매력이야 ♡
	},	
	TALK_BOX_2 =	
	{	
		{ RATE = 34, MESSAGE = STR_ID_29166, APPLY_INTIMACY = TRUE, }, --내 얘교는 이정도? ♡
		{ RATE = 33, MESSAGE = STR_ID_29167, APPLY_INTIMACY = TRUE, }, --나를 봐봐 ♡
		{ RATE = 33, MESSAGE = STR_ID_29168, APPLY_INTIMACY = TRUE, }, --후훗 ♡
	},	
	TALK_BOX =	
	{	
		{ RATE = 34, MESSAGE = STR_ID_29169, APPLY_INTIMACY = TRUE, }, --후훗. 나 어때?
		{ RATE = 33, MESSAGE = STR_ID_29170, APPLY_INTIMACY = TRUE, }, --나에게 빠져 들지? ♡
		{ RATE = 33, MESSAGE = STR_ID_29171, APPLY_INTIMACY = TRUE, }, --나 밖에 안보일껄? ♡
	},	

}

PETIT_SNOW_BUMP_CUTE2 =
{
	ANIM_NAME					= "Cute2",
	PLAY_TYPE					= XSKIN_ANIM_PLAYTYPE["XAP_ONE_WAIT"],
	TRANSITION					= TRUE,

	MOVE_TYPE           = 0,

	SOUND_PLAY0					= { 1.01, "Pet_SNOWBUMP_Special_Cute2.ogg" },

	IMMADIATE_PACKET_SEND		= TRUE,

	ALLOW_DIR_CHANGE			= FALSE,

	EVENT_PROCESS =
	{
		{ STATE_CHANGE_TYPE["SCT_FOOT_ON_LINE_FALSE_DOWN"],	"PETIT_SNOW_BUMP_JUMP_DOWN",					},
		{ STATE_CHANGE_TYPE["SCT_MOTION_END"],				"PETIT_SNOW_BUMP_WAIT",						},
	},

	TALK_BOX_1 =	
	{	
		{ RATE = 34, MESSAGE = STR_ID_29163, APPLY_INTIMACY = TRUE, }, --후훗 ♡
		{ RATE = 33, MESSAGE = STR_ID_29164, APPLY_INTIMACY = TRUE, }, --이정도는 돼야지? ♡
		{ RATE = 33, MESSAGE = STR_ID_29165, APPLY_INTIMACY = TRUE, }, --살짝 웃는게 매력이야 ♡
	},	
	TALK_BOX_2 =	
	{	
		{ RATE = 34, MESSAGE = STR_ID_29166, APPLY_INTIMACY = TRUE, }, --내 얘교는 이정도? ♡
		{ RATE = 33, MESSAGE = STR_ID_29167, APPLY_INTIMACY = TRUE, }, --나를 봐봐 ♡
		{ RATE = 33, MESSAGE = STR_ID_29168, APPLY_INTIMACY = TRUE, }, --후훗 ♡
	},	
	TALK_BOX =	
	{	
		{ RATE = 34, MESSAGE = STR_ID_29169, APPLY_INTIMACY = TRUE, }, --후훗. 나 어때?
		{ RATE = 33, MESSAGE = STR_ID_29170, APPLY_INTIMACY = TRUE, }, --나에게 빠져 들지? ♡
		{ RATE = 33, MESSAGE = STR_ID_29171, APPLY_INTIMACY = TRUE, }, --나 밖에 안보일껄? ♡
	},	

}

PETIT_SNOW_BUMP_SAD =
{
	ANIM_NAME					= "Afraid",
	PLAY_TYPE					= XSKIN_ANIM_PLAYTYPE["XAP_ONE_WAIT"],
	TRANSITION					= TRUE,

	MOVE_TYPE           = 0,


	IMMADIATE_PACKET_SEND		= TRUE,

	ALLOW_DIR_CHANGE			= FALSE,

	EVENT_PROCESS =
	{
		{ STATE_CHANGE_TYPE["SCT_FOOT_ON_LINE_FALSE_DOWN"],	"PETIT_SNOW_BUMP_JUMP_DOWN",					},
		{ STATE_CHANGE_TYPE["SCT_MOTION_END"],				"PETIT_SNOW_BUMP_WAIT",						},
	},

	TALK_BOX_1 =	
	{	
		{ RATE = 34, MESSAGE = STR_ID_29172, APPLY_INTIMACY = TRUE, }, --슬퍼지려 해..
		{ RATE = 33, MESSAGE = STR_ID_29173, APPLY_INTIMACY = TRUE, }, --나.. 울꺼야 
		{ RATE = 33, MESSAGE = STR_ID_29174, APPLY_INTIMACY = TRUE, }, --나 눈물 안나게 해줘..
	},	
	TALK_BOX_2 =	
	{	
		{ RATE = 34, MESSAGE = STR_ID_29175, APPLY_INTIMACY = TRUE, }, --나 너무 슬퍼..
		{ RATE = 33, MESSAGE = STR_ID_29176, APPLY_INTIMACY = TRUE, }, --나 눈물나게 할꺼야?
		{ RATE = 33, MESSAGE = STR_ID_29177, APPLY_INTIMACY = TRUE, }, --슬퍼지려 해..
	},	
	TALK_BOX =	
	{	
		{ RATE = 34, MESSAGE = STR_ID_29178, APPLY_INTIMACY = TRUE, }, --나 울어도 돼..?
		{ RATE = 33, MESSAGE = STR_ID_29179, APPLY_INTIMACY = TRUE, }, --내가 울면 너도 슬프잖아?
		{ RATE = 33, MESSAGE = STR_ID_29180, APPLY_INTIMACY = TRUE, }, --훌쩍.. 나.. 울꺼야
	},	

}

PETIT_SNOW_BUMP_CHEER =
{
	ANIM_NAME					= "Cheer",
	PLAY_TYPE					= XSKIN_ANIM_PLAYTYPE["XAP_ONE_WAIT"],
	TRANSITION					= TRUE,

	MOVE_TYPE           = 0,

	SOUND_PLAY0					= { 0.005, "Pet_Cheer_Common.ogg" },

	IMMADIATE_PACKET_SEND		= TRUE,

	ALLOW_DIR_CHANGE			= FALSE,

	EVENT_PROCESS =
	{
		{ STATE_CHANGE_TYPE["SCT_FOOT_ON_LINE_FALSE_DOWN"],	"PETIT_SNOW_BUMP_JUMP_DOWN",					},
		{ STATE_CHANGE_TYPE["SCT_MOTION_END"],				"PETIT_SNOW_BUMP_WAIT",						},
	},

	TALK_BOX_1 =	
	{	
		{ RATE = 33, MESSAGE = STR_ID_29181 }, --너가 잘할수 있다는거 알아
		{ RATE = 34, MESSAGE = STR_ID_29181 }, --이정도야 껌이지?
		{ RATE = 33, MESSAGE = STR_ID_29181 }, --잘 할수 있는거 믿어 ♡
	},	
	TALK_BOX_2 =	
	{	
		{ RATE = 33, MESSAGE = STR_ID_29182 }, --역시 넌 멋있어 ♡
		{ RATE = 34, MESSAGE = STR_ID_29182 }, --힘낼줄 알았다니까 ♡
		{ RATE = 33, MESSAGE = STR_ID_29182 }, --힘내~ ♡
	},	
	TALK_BOX =	
	{	
		{ RATE = 33, MESSAGE = STR_ID_29183 }, --역시 넌 멋있어 ♡
		{ RATE = 34, MESSAGE = STR_ID_29183 }, --힘낼줄 알았다니까 ♡
		{ RATE = 33, MESSAGE = STR_ID_29183 }, --후훗. 날 위해 힘낼꺼지? ♡
	},	

}

PETIT_SNOW_BUMP_SPECIAL =
{
	ANIM_NAME					= "Special_A",
	PLAY_TYPE					= XSKIN_ANIM_PLAYTYPE["XAP_ONE_WAIT"],
	TRANSITION					= TRUE,

	MOVE_TYPE           = 0,
	
	LAND_CONNECT		= FALSE,
	
	
	SOUND_PLAY0					= { 1.02, "Pet_SNOWBUMP_Special.ogg" },

	IMMADIATE_PACKET_SEND		= TRUE,

	ALLOW_DIR_CHANGE			= FALSE,

	EVENT_PROCESS =
	{
		{ STATE_CHANGE_TYPE["SCT_FOOT_ON_LINE_FALSE_DOWN"],	"PETIT_SNOW_BUMP_JUMP_DOWN",					},
		{ STATE_CHANGE_TYPE["SCT_MOTION_END"],				"PETIT_SNOW_BUMP_WAIT",						},
	},

	TALK_BOX_1 =	
	{	
		{ RATE = 34, MESSAGE = STR_ID_29184 }, --너가 생각하는 그런 호박이 아냐 ♡
		{ RATE = 33, MESSAGE = STR_ID_29184 }, --후훗. 날 따라해볼래? ♡
		{ RATE = 33, MESSAGE = STR_ID_29184 }, --이정도면 돼겠어? ♡
	},	
	TALK_BOX_2 =	
	{	
		{ RATE = 34, MESSAGE = STR_ID_29185 }, --너가 생각하는 그런 호박이 아냐 ♡
		{ RATE = 33, MESSAGE = STR_ID_29185 }, --후훗. 날 따라해볼래? ♡
		{ RATE = 33, MESSAGE = STR_ID_29185 }, --이정도면 돼겠어? ♡
	},	
	TALK_BOX =	
	{	
		{ RATE = 34, MESSAGE = STR_ID_29186 }, --너가 생각하는 그런 호박이 아냐 ♡
		{ RATE = 33, MESSAGE = STR_ID_29186 }, --후훗. 날 따라해볼래? ♡
		{ RATE = 33, MESSAGE = STR_ID_29186 }, --이정도면 돼겠어? ♡
	},	

}

PETIT_SNOW_BUMP_ATTACK =
{
	ANIM_NAME					= "Attack_C",
	PLAY_TYPE					= XSKIN_ANIM_PLAYTYPE["XAP_ONE_WAIT"],
	TRANSITION					= TRUE,
	
	MOVE_TYPE           = 0,
	
	CAN_PUSH_UNIT				= TRUE,
	CAN_PASS_UNIT				= FALSE,
	
	LAND_CONNECT		= FALSE,
	VIEW_TARGET			= TRUE,
    --1차
	SPEED_TIME0 = { -1200.0, 0.0, 0.080, 2, },
	SPEED_TIME1 = { 1600.0, 0.0, 0.777, 2, },
	SPEED_TIME2 = { 1400.0, 0.0, 0.877, 2, },
	SPEED_TIME3 = { 1200.0, 0.0, 0.977, 2, },
	SPEED_TIME4 = { 1000.0, 0.0, 1.077, 2, },
	SPEED_TIME5 = { 900.0, 0.0, 1.177, 2, },
	SPEED_TIME6 = { 800.0, 0.0, 1.277, 2, },
	SPEED_TIME7 = { 700.0, 0.0, 1.377, 2, },
	SPEED_TIME8 = { 650.0, 0.0, 1.477, 2, },
	SPEED_TIME9 = { 600.0, 0.0, 1.577, 2, },
	SPEED_TIME10 = { 550.0, 0.0, 1.677, 2, },
	SPEED_TIME11 = { 500.0, 0.0, 1.777, 2, },
	SPEED_TIME12 = { 500.0, 0.0, 1.877, 2, },
	SPEED_TIME13 = { 450.0, 0.0, 1.977, 2, },
	SPEED_TIME14 = { 400.0, 0.0, 2.077, 2, },
	SPEED_TIME15 = { 300.0, 0.0, 2.177, 2, },
	SPEED_TIME16 = { 200.0, 0.0, 2.277, 2, },
	SPEED_TIME17 = { 100.0, 0.0, 2.377, 2, },
	SPEED_TIME18 = { 1.0, 0.0, 2.500, 2, },

	
	SOUND_PLAY0					= { 0.3, "Pet_SNOWBUMP_Special_Attack_B.ogg" },


	IMMADIATE_PACKET_SEND		= TRUE,
	
	
	EVENT_PROCESS =
	{
		--{ STATE_CHANGE_TYPE["SCT_FOOT_ON_LINE_FALSE_DOWN"],	"PETIT_SNOW_BUMP_JUMP_DOWN_ATTACK",					},
		{ STATE_CHANGE_TYPE["SCT_MOTION_END"],				"PETIT_SNOW_BUMP_WAIT",						},
	},

	TALK_BOX_1 =	
	{	
		{ RATE = 34, MESSAGE = STR_ID_29187 }, --후훗, 내 힘을 잘 봐둬 ♡
		{ RATE = 33, MESSAGE = STR_ID_29187 }, --나의 힘을 잊지 못할꺼야 ♡
		{ RATE = 33, MESSAGE = STR_ID_29187 }, --요정의 힘은 대단한거야 ♡
	},	
	TALK_BOX_2 =	
	{	
		{ RATE = 34, MESSAGE = STR_ID_29188 }, --후훗, 내 힘을 잘 봐둬 ♡
		{ RATE = 33, MESSAGE = STR_ID_29188 }, --나의 힘을 잊지 못할꺼야 ♡
		{ RATE = 33, MESSAGE = STR_ID_29188 }, --요정의 힘은 대단한거야 ♡
	},	
	TALK_BOX =	
	{	
		{ RATE = 34, MESSAGE = STR_ID_29189 }, --후훗, 내 힘을 잘 봐둬 ♡
		{ RATE = 33, MESSAGE = STR_ID_29189 }, --나의 힘을 잊지 못할꺼야 ♡
		{ RATE = 33, MESSAGE = STR_ID_29189 }, --요정의 힘은 대단한거야 ♡
	},	

}


PETIT_SNOW_BUMP_SIT_START =
{
	ANIM_NAME					= "Sit_Ready",
	PLAY_TYPE					= XSKIN_ANIM_PLAYTYPE["XAP_ONE_WAIT"],
	TRANSITION					= TRUE,

	MOVE_TYPE           = 0,


	IMMADIATE_PACKET_SEND		= TRUE,

	ALLOW_DIR_CHANGE			= FALSE,

	EVENT_PROCESS =
	{
		{ STATE_CHANGE_TYPE["SCT_FOOT_ON_LINE_FALSE_DOWN"],	"PETIT_SNOW_BUMP_JUMP_DOWN",					},
		{ STATE_CHANGE_TYPE["SCT_MOTION_END"],				"PETIT_SNOW_BUMP_SIT_LOOP",						},
	},

	TALK_BOX_1 =	
	{	
		{ RATE = 34, MESSAGE = STR_ID_29190, APPLY_INTIMACY = TRUE, }, --후훗 ~
		{ RATE = 33, MESSAGE = STR_ID_29190, APPLY_INTIMACY = TRUE, }, --실례 ~
		{ RATE = 33, MESSAGE = STR_ID_29190, APPLY_INTIMACY = TRUE, }, --잠시 ~
	},	
	TALK_BOX_2 =	
	{	
		{ RATE = 34, MESSAGE = STR_ID_29190, APPLY_INTIMACY = TRUE, }, --후훗 ~
		{ RATE = 33, MESSAGE = STR_ID_29190, APPLY_INTIMACY = TRUE, }, --실례 ~
		{ RATE = 33, MESSAGE = STR_ID_29190, APPLY_INTIMACY = TRUE, }, --잠시 ~
	},	
	TALK_BOX =	
	{	
		{ RATE = 34, MESSAGE = STR_ID_29190, APPLY_INTIMACY = TRUE, }, --후훗 ~
		{ RATE = 33, MESSAGE = STR_ID_29190, APPLY_INTIMACY = TRUE, }, --실례 ~
		{ RATE = 33, MESSAGE = STR_ID_29190, APPLY_INTIMACY = TRUE, }, --잠시 ~
	},	

}

PETIT_SNOW_BUMP_SIT_LOOP =
{
	ANIM_NAME					= "Sit",
	PLAY_TYPE					= XSKIN_ANIM_PLAYTYPE["XAP_LOOP"],
	TRANSITION					= TRUE,

	MOVE_TYPE           = 0,


	IMMADIATE_PACKET_SEND		= TRUE,

	ALLOW_DIR_CHANGE			= FALSE,

	EVENT_PROCESS =
	{
		{ STATE_CHANGE_TYPE["SCT_FOOT_ON_LINE_FALSE_DOWN"],	"PETIT_SNOW_BUMP_JUMP_DOWN",					},
	},
}

PETIT_SNOW_BUMP_SIT_END =
{
	ANIM_NAME					= "Sit_End",
	PLAY_TYPE					= XSKIN_ANIM_PLAYTYPE["XAP_ONE_WAIT"],
	TRANSITION					= TRUE,

	MOVE_TYPE           = 0,


	IMMADIATE_PACKET_SEND		= TRUE,

	ALLOW_DIR_CHANGE			= FALSE,

	EVENT_PROCESS =
	{
		{ STATE_CHANGE_TYPE["SCT_FOOT_ON_LINE_FALSE_DOWN"],	"PETIT_SNOW_BUMP_JUMP_DOWN",					},
		{ STATE_CHANGE_TYPE["SCT_MOTION_END"],				"PETIT_SNOW_BUMP_WAIT",						},
	},

	TALK_BOX_1 =	
	{	
		{ RATE = 34, MESSAGE = STR_ID_29191, APPLY_INTIMACY = TRUE, }, --음?
		{ RATE = 33, MESSAGE = STR_ID_29191, APPLY_INTIMACY = TRUE, }, --음?
		{ RATE = 33, MESSAGE = STR_ID_29191, APPLY_INTIMACY = TRUE, }, --음?
	},	
	TALK_BOX_2 =	
	{	
		{ RATE = 34, MESSAGE = STR_ID_29191, APPLY_INTIMACY = TRUE, }, --음?
		{ RATE = 33, MESSAGE = STR_ID_29191, APPLY_INTIMACY = TRUE, }, --음?
		{ RATE = 33, MESSAGE = STR_ID_29191, APPLY_INTIMACY = TRUE, }, --음?
	},	
	TALK_BOX =	
	{	
		{ RATE = 34, MESSAGE = STR_ID_29191, APPLY_INTIMACY = TRUE, }, --음?
		{ RATE = 33, MESSAGE = STR_ID_29191, APPLY_INTIMACY = TRUE, }, --음?
		{ RATE = 33, MESSAGE = STR_ID_29191, APPLY_INTIMACY = TRUE, }, --음?
	},	

}

PETIT_SNOW_BUMP_NOTKNOW =
{
	ANIM_NAME					= "DoNotKnow",
	PLAY_TYPE					= XSKIN_ANIM_PLAYTYPE["XAP_ONE_WAIT"],
	TRANSITION					= TRUE,

	MOVE_TYPE           = 0,


	IMMADIATE_PACKET_SEND		= TRUE,

	ALLOW_DIR_CHANGE			= FALSE,

	EVENT_PROCESS =
	{
		{ STATE_CHANGE_TYPE["SCT_FOOT_ON_LINE_FALSE_DOWN"],	"PETIT_SNOW_BUMP_JUMP_DOWN",					},
		{ STATE_CHANGE_TYPE["SCT_MOTION_END"],				"PETIT_SNOW_BUMP_WAIT",						},
	},
}

function PETIT_SNOW_BUMP_DASH_FRAME_MOVE( pKTDXApp, pX2Game, pPet )

	
end


function PETIT_SNOW_BUMP_CUTE2_FRAME_MOVE( pKTDXApp, pX2Game, pPet )

    
end

function PETIT_SNOW_BUMP_ATTACK_FRAME_MOVE( pKTDXApp, pX2Game, pPet )

	if pPet:AnimEventTimer( 0.1 ) then
				local pEffectSet = pX2Game:GetEffectSet()
				if pEffectSet ~= nil then
					local hEffect =  pEffectSet:PlayEffectSetByPet_LUA( "EffectSet_PET_SNOWBUMP_Attack_C", pPet )
				end
	end		

end

function CF_PETATTACK_PETIT_SNOW_BUMP( pKTDXApp, pX2Game, pPet )

	if pX2Game ~= nil then
		if pX2Game:IsHost() == false then
			return false
		end
	end

	if pPet:IsAttacking() == true then

		local fDist = pPet:GetDistTarget()
		if fDist < 300 then
			return true
		end
	end

	return false
end

function PETIT_SNOW_BUMP_SPECIAL_FRAME_MOVE( pKTDXApp, pX2Game, pPet )

end