-- lua header. UTF-8 인코딩 인식을 위해 이 줄은 지우지 마세요.


INIT_SYSTEM =
{
	UNIT_LAYER		= X2_LAYER["XL_UNIT_0"],
	UNIT_SCALE		= 0.9,
}


INIT_DEVICE =
{
	READY_XSKIN_MESH =
	{
		"Pet_Bboru_Attack01.X",
	},

	READY_TEXTURE =
	{
	},

	READY_SOUND =
	{
     "Pet_DashEnd.ogg",
	 "Pet_Hungry.ogg",
	 "Pet_Stuffed.ogg",
	 "Pet_PettePporu_Attack.ogg",
	 "Pet_PettePporu_Special.ogg",
	 "Pet_PettePporu_Hello.ogg",
     "Pet_PettePporu_Cute1.ogg",
     "Pet_PettePporu_Cute2.ogg",
     "Pet_Cheer_Common.ogg",
	 "Pet_PettePporu_Cheer.ogg",
	},
}

INIT_MOTION =
{
	MOTION_FILE_NAME		= "Motion_PETTE_Bboru_STEB_1.x",
	MOTION_CHANGE_TEX_XET		= "PET_PETTE_PPORU_YoungByung_STEB_1.xet",
	MOTION_ANI_TEX_XET		= "PET_PETTE_PPORU_YoungByung_STEB_1_EYE.xet",
}


INIT_COMPONENT =
{
	MAX_HP				= 6000,
	MP_CHANGE_RATE		= 1,
	MP_CHARGE_RATE		= 130,


	SHADOW_SIZE			= 200,
	SHADOW_FILE_NAME	= "shadow.dds",

	SMALL_HP_BAR_BLUE	= "Small_HP_bar_Blue.TGA",
	SMALL_HP_BAR_RED	= "Small_HP_bar_Red.TGA",
	SMALL_HP_BAR_YELLOW = "Small_HP_bar_Yellow.TGA",

	QUESTION_MARK_SEQ		= "QuestionMarkNPC",
	EXCLAMATION_MARK_SEQ	= "ExclamationMarkNPC",

	HYPER_MODE_COUNT	= 0,
	MAX_HYPER_MODE_TIME	= 30,

	HITTED_TYPE			= HITTED_TYPE["HTD_MEAT"],

	FALL_DOWN			= TRUE,



}

INIT_STATE =
{
	{ STATE_NAME = "PETTE_PPORU_STEB_1_SUMMON",			},
	{ STATE_NAME = "PETTE_PPORU_STEB_1_WAIT_HABIT",		STATE_COOL_TIME = 20, },
	{ STATE_NAME = "PETTE_PPORU_STEB_1_WAIT",						},
	{ STATE_NAME = "PETTE_PPORU_STEB_1_WALK",						},
	{ STATE_NAME = "PETTE_PPORU_STEB_1_DASH",						},
	{ STATE_NAME = "PETTE_PPORU_STEB_1_DASH_END",					},
	{ STATE_NAME = "PETTE_PPORU_STEB_1_JUMP_UP",					},
	{ STATE_NAME = "PETTE_PPORU_STEB_1_JUMP_DOWN",				},
	{ STATE_NAME = "PETTE_PPORU_STEB_1_JUMP_UP_DIR",				},
	{ STATE_NAME = "PETTE_PPORU_STEB_1_JUMP_DOWN_DIR",			},
	{ STATE_NAME = "PETTE_PPORU_STEB_1_JUMP_LANDING",				},
	{ STATE_NAME = "PETTE_PPORU_STEB_1_EAT",				},
	{ STATE_NAME = "PETTE_PPORU_STEB_1_HUNGRY",				},
	{ STATE_NAME = "PETTE_PPORU_STEB_1_STUFFED",				},
	{ STATE_NAME = "PETTE_PPORU_STEB_1_SLEEP_START",				},
	{ STATE_NAME = "PETTE_PPORU_STEB_1_SLEEP_LOOP",				},
	{ STATE_NAME = "PETTE_PPORU_STEB_1_SLEEP_END",				},
	{ STATE_NAME = "PETTE_PPORU_STEB_1_AFRAID",				STATE_COOL_TIME = 10, },
	{ STATE_NAME = "PETTE_PPORU_STEB_1_HELLO",				},
	{ STATE_NAME = "PETTE_PPORU_STEB_1_HAPPY1",				},
	{ STATE_NAME = "PETTE_PPORU_STEB_1_HAPPY2",				},
  { STATE_NAME = "PETTE_PPORU_STEB_1_CUTE1",				STATE_COOL_TIME = 10, },
  { STATE_NAME = "PETTE_PPORU_STEB_1_CUTE2",				STATE_COOL_TIME = 10, },
  { STATE_NAME = "PETTE_PPORU_STEB_1_SAD",				},
  { STATE_NAME = "PETTE_PPORU_STEB_1_CHEER",			STATE_COOL_TIME = 180,	},
  { STATE_NAME = "PETTE_PPORU_STEB_1_SPECIAL",				},
  { STATE_NAME = "PETTE_PPORU_STEB_1_ATTACK",			LUA_FRAME_MOVE_FUNC = "PETTE_PPORU_STEB_1_ATTACK_FRAME_MOVE",	},
  { STATE_NAME = "PETTE_PPORU_STEB_1_SIT_START",				},
  { STATE_NAME = "PETTE_PPORU_STEB_1_SIT_LOOP",				},
  { STATE_NAME = "PETTE_PPORU_STEB_1_SIT_END",				},
  { STATE_NAME = "PETTE_PPORU_STEB_1_NOTKNOW",				},

  START_STATE					= "PETTE_PPORU_STEB_1_SUMMON",
  WAIT_HABIT					= "PETTE_PPORU_STEB_1_WAIT_HABIT",
	WAIT_STATE					= "PETTE_PPORU_STEB_1_WAIT",
	EAT_STATE           = "PETTE_PPORU_STEB_1_EAT",
	HUNGRY_STATE       = "PETTE_PPORU_STEB_1_HUNGRY",
	STUFFED_STATE       = "PETTE_PPORU_STEB_1_STUFFED",
	SLEEP_START_STATE   = "PETTE_PPORU_STEB_1_SLEEP_START",
	SLEEP_LOOP_STATE   = "PETTE_PPORU_STEB_1_SLEEP_LOOP",
  SLEEP_END_STATE     = "PETTE_PPORU_STEB_1_SLEEP_END",
  AFRAID_STATE        = "PETTE_PPORU_STEB_1_AFRAID",
  HELLO_STATE         = "PETTE_PPORU_STEB_1_HELLO",
  HAPPY1_STATE         = "PETTE_PPORU_STEB_1_HAPPY1",
  HAPPY2_STATE         = "PETTE_PPORU_STEB_1_HAPPY2",
  CUTE1_STATE          = "PETTE_PPORU_STEB_1_CUTE1",
  CUTE2_STATE          = "PETTE_PPORU_STEB_1_CUTE2",
  SAD_STATE           = "PETTE_PPORU_STEB_1_SAD",
  CHEER_STATE         = "PETTE_PPORU_STEB_1_CHEER",
  SPECIAL_STATE       = "PETTE_PPORU_STEB_1_SPECIAL",
  ATTACK_STATE      = "PETTE_PPORU_STEB_1_ATTACK",
  SIT_START_STATE     = "PETTE_PPORU_STEB_1_SIT_START",
  SIT_LOOP_STATE     = "PETTE_PPORU_STEB_1_SIT_LOOP",
  SIT_END_STATE       = "PETTE_PPORU_STEB_1_SIT_END",
  NOTKNOW_STATE       = "PETTE_PPORU_STEB_1_NOTKNOW",
}

INIT_AI =
{
	TARGET =
	{
		TARGET_PRIORITY 			= TARGET_PRIORITY["TP_LOW_HP_FIRST"],
		TARGET_INTERVAL				= 0.5,		-- sec
		TARGET_NEAR_RANGE			= 200,		-- 이 거리보다 가까우면 TARGET_SUCCESS_RATE에 관계없이 무조건 타게팅된다
		TARGET_RANGE				= 10000,		-- cm
		TARGET_LOST_RANGE			= 2000,	-- cm
		TARGET_SUCCESS_RATE			= 100,  --70,		-- %
		ATTACK_TARGET_RATE			= 100, -- 80,		-- 나를 공격한 유닛을 타게팅할 확률
		PRESERVE_LAST_TARGET_RATE	= 100, -- 80,		-- 이전에 타게팅된 유닛을 계속 타게팅할 확률
	},

	CHASE_MOVE =
	{
		MOVE_SPLIT_RANGE	= 100,
		DEST_GAP			= 200,	-- 목적지에서 이 거리 안에 있으면 도착했다고 판단한다
		MOVE_GAP			= 100,
		RUN_GAP				= 500,

		DIR_CHANGE_INTERVAL = 0.3,

		WALK_INTERVAL		= 1,
		NEAR_WALK_RATE		= 100,   --  70,
		FAR_WALK_RATE		= 100,   -- 30,

		JUMP_INTERVAL		= 0,
		UP_JUMP_RATE		= 0, -- 40,
		UP_DOWN_RATE		= 0,
		DOWN_JUMP_RATE		= 0,    --  20,
		DOWN_DOWN_RATE		= 0,
	},

}

PETTE_PPORU_STEB_1_SUMMON =
{
	ANIM_NAME					= "Wait",
	PLAY_TYPE					= XSKIN_ANIM_PLAYTYPE["XAP_ONE_WAIT"],
	TRANSITION					= TRUE,

	MOVE_TYPE           = 0,

	CAN_PUSH_UNIT				= TRUE,
	CAN_PASS_UNIT				= FALSE,
	IMMADIATE_PACKET_SEND		= TRUE,

	ALLOW_DIR_CHANGE			= FALSE,

	EVENT_PROCESS =
	{
		{ STATE_CHANGE_TYPE["SCT_FOOT_ON_LINE_FALSE_DOWN"],	"PETTE_PPORU_STEB_1_JUMP_DOWN",					},
		{ STATE_CHANGE_TYPE["SCT_MOTION_END"],				"PETTE_PPORU_STEB_1_WAIT",						},
	},
}

PETTE_PPORU_STEB_1_WAIT =
{
	ANIM_NAME					= "Wait",
	PLAY_TYPE					= XSKIN_ANIM_PLAYTYPE["XAP_LOOP"],
	TRANSITION					= TRUE,

	MOVE_TYPE           = 0,

	IMMADIATE_PACKET_SEND		= TRUE,
	EVENT_INTERVAL_TIME0		= 2,

	EVENT_PROCESS =
	{
		{ STATE_CHANGE_TYPE["SCT_FOOT_ON_LINE_FALSE_DOWN"],	"PETTE_PPORU_STEB_1_JUMP_DOWN",					},

		{ STATE_CHANGE_TYPE["SCT_CONDITION_FUNCTION"],      "PETTE_PPORU_STEB_1_ATTACK",						"CF_PETATTACK_PETTE_PPORU_STEB_1"    },

		{ STATE_CHANGE_TYPE["SCT_AI_DIR_CHANGE"],			"PETTE_PPORU_STEB_1_WALK",						},

		{ STATE_CHANGE_TYPE["SCT_AI_WALK"],					"PETTE_PPORU_STEB_1_WALK",						},
		{ STATE_CHANGE_TYPE["SCT_AI_DASH"],					"PETTE_PPORU_STEB_1_DASH",						},
		{ STATE_CHANGE_TYPE["SCT_AI_JUMP"],					"PETTE_PPORU_STEB_1_JUMP_UP",						},
		{ STATE_CHANGE_TYPE["SCT_AI_JUMP_DIR"],				"PETTE_PPORU_STEB_1_JUMP_UP_DIR",					},
		{ STATE_CHANGE_TYPE["SCT_AI_DOWN"],					"PETTE_PPORU_STEB_1_JUMP_DOWN",					},
		{ STATE_CHANGE_TYPE["SCT_AI_DOWN_DIR"],				"PETTE_PPORU_STEB_1_JUMP_DOWN_DIR",				},
	},
}


PETTE_PPORU_STEB_1_WALK =
{
	ANIM_NAME					= "Walk",
	PLAY_TYPE					= XSKIN_ANIM_PLAYTYPE["XAP_LOOP"],
	TRANSITION					= TRUE,

	CAN_PUSH_UNIT				= TRUE,
	CAN_PASS_UNIT				= FALSE,

	MOVE_TYPE           = 1,
	PASSIVE_SPEED_X_BY_USER			= 1.2,

	IMMADIATE_PACKET_SEND		= TRUE,

	EVENT_INTERVAL_TIME0		= 2,

	EVENT_PROCESS =
	{
		{ STATE_CHANGE_TYPE["SCT_FOOT_ON_LINE_FALSE_DOWN"],	"PETTE_PPORU_STEB_1_JUMP_DOWN_DIR",				},

		{ STATE_CHANGE_TYPE["SCT_CONDITION_FUNCTION"],      "PETTE_PPORU_STEB_1_ATTACK",						"CF_PETATTACK_PETTE_PPORU_STEB_1"    },

		{ STATE_CHANGE_TYPE["SCT_AI_WAIT"],					"PETTE_PPORU_STEB_1_WAIT",						},
		{ STATE_CHANGE_TYPE["SCT_AI_DASH"],					"PETTE_PPORU_STEB_1_DASH",						},

		{ STATE_CHANGE_TYPE["SCT_AI_JUMP"],					"PETTE_PPORU_STEB_1_JUMP_UP",						},
		{ STATE_CHANGE_TYPE["SCT_AI_JUMP_DIR"],				"PETTE_PPORU_STEB_1_JUMP_UP_DIR",					},
		{ STATE_CHANGE_TYPE["SCT_AI_DOWN"],					"PETTE_PPORU_STEB_1_JUMP_DOWN",					},
		{ STATE_CHANGE_TYPE["SCT_AI_DOWN_DIR"],				"PETTE_PPORU_STEB_1_JUMP_DOWN_DIR",				},
	},

}

PETTE_PPORU_STEB_1_DASH =
{
	ANIM_NAME					= "Dash",
	PLAY_TYPE					= XSKIN_ANIM_PLAYTYPE["XAP_LOOP"],
	TRANSITION					= TRUE,

	CAN_PUSH_UNIT				= TRUE,
	CAN_PASS_UNIT				= FALSE,


	MOVE_TYPE           = 2,
	PASSIVE_SPEED_X_BY_USER			= 1.4,

	ALLOW_DIR_CHANGE			= TRUE,
	IMMADIATE_PACKET_SEND		= TRUE,

	EVENT_INTERVAL_TIME0		= 1,

	EVENT_PROCESS =
	{
		{ STATE_CHANGE_TYPE["SCT_FOOT_ON_LINE_FALSE_DOWN"],	"PETTE_PPORU_STEB_1_JUMP_DOWN_DIR",				},

		{ STATE_CHANGE_TYPE["SCT_CONDITION_FUNCTION"],      "PETTE_PPORU_STEB_1_ATTACK",						"CF_PETATTACK_PETTE_PPORU_STEB_1"    },

		{ STATE_CHANGE_TYPE["SCT_AI_WAIT"],					"PETTE_PPORU_STEB_1_DASH_END",							},
		{ STATE_CHANGE_TYPE["SCT_AI_WALK"],					"PETTE_PPORU_STEB_1_WALK",							},
		{ STATE_CHANGE_TYPE["SCT_AI_JUMP"],					"PETTE_PPORU_STEB_1_JUMP_UP",						},
		{ STATE_CHANGE_TYPE["SCT_AI_JUMP_DIR"],				"PETTE_PPORU_STEB_1_JUMP_UP_DIR",					},
		{ STATE_CHANGE_TYPE["SCT_AI_DOWN"],					"PETTE_PPORU_STEB_1_JUMP_DOWN",					},
		{ STATE_CHANGE_TYPE["SCT_AI_DOWN_DIR"],				"PETTE_PPORU_STEB_1_JUMP_DOWN_DIR",				},
	},
	
	TALK_BOX_1 =
	{
		{ RATE = 7, MESSAGE = STR_ID_5854  },
		{ RATE = 7, MESSAGE = STR_ID_5855  },
		{ RATE = 7, MESSAGE = STR_ID_5856  },
	},
	TALK_BOX_2 =
	{
		{ RATE = 7, MESSAGE = STR_ID_5857  },
		{ RATE = 7, MESSAGE = STR_ID_5858  },
		{ RATE = 7, MESSAGE = STR_ID_5859  },
	},
	TALK_BOX =
	{
		{ RATE = 7, MESSAGE = STR_ID_5860  },
		{ RATE = 7, MESSAGE = STR_ID_5861  },
		{ RATE = 7, MESSAGE = STR_ID_5862  },
	},


}

PETTE_PPORU_STEB_1_DASH_END =
{
	ANIM_NAME					= "DashEnd",
	PLAY_TYPE					= XSKIN_ANIM_PLAYTYPE["XAP_ONE_WAIT"],
	TRANSITION					= FALSE,

	CAN_PUSH_UNIT				= TRUE,
	CAN_PASS_UNIT				= FALSE,

	SPEED_X				= 700,

    SOUND_PLAY0					= { 0.021, "Pet_DashEnd.ogg" },

	ALLOW_DIR_CHANGE			= TRUE,
	IMMADIATE_PACKET_SEND		= TRUE,

	EVENT_PROCESS =
	{
		{ STATE_CHANGE_TYPE["SCT_FOOT_ON_LINE_FALSE_DOWN"],	"PETTE_PPORU_STEB_1_JUMP_DOWN_DIR",				},

		{ STATE_CHANGE_TYPE["SCT_MOTION_END"],				"PETTE_PPORU_STEB_1_WAIT",							},

		{ STATE_CHANGE_TYPE["SCT_AI_WAIT"],					"PETTE_PPORU_STEB_1_WAIT",							},
		{ STATE_CHANGE_TYPE["SCT_AI_WALK"],					"PETTE_PPORU_STEB_1_WALK",							},
		{ STATE_CHANGE_TYPE["SCT_AI_JUMP"],					"PETTE_PPORU_STEB_1_JUMP_UP",						},
		{ STATE_CHANGE_TYPE["SCT_AI_JUMP_DIR"],				"PETTE_PPORU_STEB_1_JUMP_UP_DIR",					},
		{ STATE_CHANGE_TYPE["SCT_AI_DOWN"],					"PETTE_PPORU_STEB_1_JUMP_DOWN",					},
		{ STATE_CHANGE_TYPE["SCT_AI_DOWN_DIR"],				"PETTE_PPORU_STEB_1_JUMP_DOWN_DIR",				},
	},
}


PETTE_PPORU_STEB_1_JUMP_UP =
{
	ANIM_NAME					= "JumpUp",
	PLAY_TYPE					= XSKIN_ANIM_PLAYTYPE["XAP_LOOP"],
	TRANSITION					= TRUE,
	LAND_CONNECT				= FALSE,

	CAN_PUSH_UNIT				= TRUE,
	CAN_PASS_UNIT				= FALSE,

	MOVE_TYPE           = 3,
	SPEED_Y_BY_USER			= 1,
	ADD_POS_Y					= 45,

	IMMADIATE_PACKET_SEND		= TRUE,

	EVENT_PROCESS =
	{

		{ STATE_CHANGE_TYPE["SCT_NEGATIVE_Y_SPEED"],		"PETTE_PPORU_STEB_1_JUMP_DOWN",				},
	},


}

PETTE_PPORU_STEB_1_JUMP_DOWN =
{
	ANIM_NAME					= "JumpDown",
	PLAY_TYPE					= XSKIN_ANIM_PLAYTYPE["XAP_LOOP"],
	TRANSITION					= TRUE,
	LAND_CONNECT				= FALSE,

	CAN_PUSH_UNIT				= TRUE,
	CAN_PASS_UNIT				= FALSE,



	IMMADIATE_PACKET_SEND		= TRUE,

	EVENT_PROCESS =
	{
		{ STATE_CHANGE_TYPE["SCT_FOOT_ON_LINE_TRUE"],		"PETTE_PPORU_STEB_1_JUMP_LANDING",				},
	},
}

PETTE_PPORU_STEB_1_JUMP_UP_DIR =
{
	ANIM_NAME					= "JumpUp",
	PLAY_TYPE					= XSKIN_ANIM_PLAYTYPE["XAP_LOOP"],
	TRANSITION					= TRUE,
	LAND_CONNECT				= FALSE,

	CAN_PUSH_UNIT				= TRUE,
	CAN_PASS_UNIT				= FALSE,

	MOVE_TYPE           = 4,
	PASSIVE_SPEED_X_BY_USER = 1.2,
	SPEED_Y_BY_USER			= 1,
	ADD_POS_Y					= 45,

	IMMADIATE_PACKET_SEND		= TRUE,

	EVENT_PROCESS =
	{

		{ STATE_CHANGE_TYPE["SCT_NEGATIVE_Y_SPEED"],		"PETTE_PPORU_STEB_1_JUMP_DOWN_DIR",				},
	},


}

PETTE_PPORU_STEB_1_JUMP_DOWN_DIR =
{
	ANIM_NAME					= "JumpDown",
	PLAY_TYPE					= XSKIN_ANIM_PLAYTYPE["XAP_LOOP"],
	TRANSITION					= TRUE,
	LAND_CONNECT				= FALSE,

	CAN_PUSH_UNIT				= TRUE,
	CAN_PASS_UNIT				= FALSE,


	MOVE_TYPE           = 1,
	PASSIVE_SPEED_X_BY_USER = 1,

	IMMADIATE_PACKET_SEND		= TRUE,

	EVENT_PROCESS =
	{
		{ STATE_CHANGE_TYPE["SCT_FOOT_ON_LINE_TRUE"],		"PETTE_PPORU_STEB_1_JUMP_LANDING",				},
	},
}

PETTE_PPORU_STEB_1_JUMP_LANDING =
{
	ANIM_NAME					= "JumpDownLanding",
	PLAY_TYPE					= XSKIN_ANIM_PLAYTYPE["XAP_ONE_WAIT"],
	TRANSITION					= TRUE,
	LAND_CONNECT				= FALSE,

	CAN_PUSH_UNIT				= TRUE,
	CAN_PASS_UNIT				= FALSE,

	SOUND_PLAY0					= { 0.093, "JumpLand.ogg" },

	MOVE_TYPE = 0,

	IMMADIATE_PACKET_SEND		= TRUE,

	EVENT_PROCESS =
	{
		{ STATE_CHANGE_TYPE["SCT_FOOT_ON_LINE_FALSE_DOWN"],	"PETTE_PPORU_STEB_1_JUMP_DOWN",				},
		{ STATE_CHANGE_TYPE["SCT_MOTION_END"],				"PETTE_PPORU_STEB_1_WAIT",					},
	},

}



PETTE_PPORU_STEB_1_WAIT_HABIT =
{
	ANIM_NAME					= "WaitHabit",
	PLAY_TYPE					= XSKIN_ANIM_PLAYTYPE["XAP_ONE_WAIT"],
	TRANSITION					= TRUE,

	MOVE_TYPE           = 0,

	CAN_PUSH_UNIT				= TRUE,
	CAN_PASS_UNIT				= FALSE,
	IMMADIATE_PACKET_SEND		= TRUE,

	ALLOW_DIR_CHANGE			= FALSE,

	EVENT_PROCESS =
	{
		{ STATE_CHANGE_TYPE["SCT_FOOT_ON_LINE_FALSE_DOWN"],	"PETTE_PPORU_STEB_1_JUMP_DOWN",					},
		{ STATE_CHANGE_TYPE["SCT_MOTION_END"],				"PETTE_PPORU_STEB_1_WAIT",						},
	},

	TALK_BOX_1 =
	{
		{ RATE = 7, MESSAGE = STR_ID_5863  },
		{ RATE = 7, MESSAGE = STR_ID_5864  },
		{ RATE = 7, MESSAGE = STR_ID_5865  },
	},
	TALK_BOX_2 =
	{
		{ RATE = 7, MESSAGE = STR_ID_5866  },
		{ RATE = 7, MESSAGE = STR_ID_5867  },
		{ RATE = 7, MESSAGE = STR_ID_5868  },
	},
	TALK_BOX =
	{
		{ RATE = 7, MESSAGE = STR_ID_5869  },
		{ RATE = 7, MESSAGE = STR_ID_5870  },
		{ RATE = 7, MESSAGE = STR_ID_5871  },
	},
}

PETTE_PPORU_STEB_1_EAT =
{
	ANIM_NAME					= "Eat",
	PLAY_TYPE					= XSKIN_ANIM_PLAYTYPE["XAP_ONE_WAIT"],
	TRANSITION					= TRUE,

	MOVE_TYPE           = 0,


	IMMADIATE_PACKET_SEND		= TRUE,

		ALLOW_DIR_CHANGE			= FALSE,

	EVENT_PROCESS =
	{
		{ STATE_CHANGE_TYPE["SCT_FOOT_ON_LINE_FALSE_DOWN"],	"PETTE_PPORU_STEB_1_JUMP_DOWN",					},
		{ STATE_CHANGE_TYPE["SCT_MOTION_END"],				"PETTE_PPORU_STEB_1_WAIT",						},
	},

	TALK_BOX_1 =
	{
		{ RATE = 34, MESSAGE = STR_ID_5872, APPLY_INTIMACY = TRUE,  },
		{ RATE = 33, MESSAGE = STR_ID_5873, APPLY_INTIMACY = TRUE,  },
		{ RATE = 33, MESSAGE = STR_ID_5874, APPLY_INTIMACY = TRUE,  },
	},
	TALK_BOX_2 =
	{
		{ RATE = 34, MESSAGE = STR_ID_5875, APPLY_INTIMACY = TRUE,  },
		{ RATE = 33, MESSAGE = STR_ID_5876, APPLY_INTIMACY = TRUE,  },
		{ RATE = 33, MESSAGE = STR_ID_5877, APPLY_INTIMACY = TRUE,  },
	},
	TALK_BOX =
	{
		{ RATE = 34, MESSAGE = STR_ID_5878, APPLY_INTIMACY = TRUE,  },
		{ RATE = 33, MESSAGE = STR_ID_5879, APPLY_INTIMACY = TRUE,  },
		{ RATE = 33, MESSAGE = STR_ID_5880, APPLY_INTIMACY = TRUE,  },
	},
}

PETTE_PPORU_STEB_1_HUNGRY =
{
	ANIM_NAME					= "Hungry",
	PLAY_TYPE					= XSKIN_ANIM_PLAYTYPE["XAP_ONE_WAIT"],
	TRANSITION					= TRUE,

	MOVE_TYPE           = 0,

    SOUND_PLAY0					= { 0.021, "Pet_Hungry.ogg" },

	IMMADIATE_PACKET_SEND		= TRUE,

		ALLOW_DIR_CHANGE			= FALSE,

	EVENT_PROCESS =
	{
		{ STATE_CHANGE_TYPE["SCT_FOOT_ON_LINE_FALSE_DOWN"],	"PETTE_PPORU_STEB_1_JUMP_DOWN",					},
		{ STATE_CHANGE_TYPE["SCT_MOTION_END"],				"PETTE_PPORU_STEB_1_WAIT",						},
	},

	TALK_BOX_1 =
	{
		{ RATE = 34, MESSAGE = STR_ID_5881 },
		{ RATE = 33, MESSAGE = STR_ID_5882 },
		{ RATE = 33, MESSAGE = STR_ID_5883 },
	},
	TALK_BOX_2 =
	{
		{ RATE = 34, MESSAGE = STR_ID_5884 },
		{ RATE = 33, MESSAGE = STR_ID_5885 },
		{ RATE = 33, MESSAGE = STR_ID_5886 },
	},
	TALK_BOX =
	{
		{ RATE = 34, MESSAGE = STR_ID_5887 },
		{ RATE = 33, MESSAGE = STR_ID_5888 },
		{ RATE = 33, MESSAGE = STR_ID_5889 },
	},
}


PETTE_PPORU_STEB_1_STUFFED =
{
	ANIM_NAME					= "Stuffed",
	PLAY_TYPE					= XSKIN_ANIM_PLAYTYPE["XAP_ONE_WAIT"],
	TRANSITION					= TRUE,

	MOVE_TYPE           = 0,

    SOUND_PLAY0					= { 0.021, "Pet_Stuffed.ogg" },

	IMMADIATE_PACKET_SEND		= TRUE,

		ALLOW_DIR_CHANGE			= FALSE,

	EVENT_PROCESS =
	{
		{ STATE_CHANGE_TYPE["SCT_FOOT_ON_LINE_FALSE_DOWN"],	"PETTE_PPORU_STEB_1_JUMP_DOWN",					},
		{ STATE_CHANGE_TYPE["SCT_MOTION_END"],				"PETTE_PPORU_STEB_1_WAIT",						},
	},

	TALK_BOX_1 =
	{
		{ RATE = 34, MESSAGE = STR_ID_5890 },
		{ RATE = 33, MESSAGE = STR_ID_5891 },
		{ RATE = 33, MESSAGE = STR_ID_5892 },
	},
	TALK_BOX_2 =
	{
		{ RATE = 34, MESSAGE = STR_ID_5893 },
		{ RATE = 33, MESSAGE = STR_ID_5894 },
		{ RATE = 33, MESSAGE = STR_ID_5895 },
	},
	TALK_BOX =
	{
		{ RATE = 34, MESSAGE = STR_ID_5896 },
		{ RATE = 33, MESSAGE = STR_ID_5897 },
		{ RATE = 33, MESSAGE = STR_ID_5898 },
	},
}
---sleep 할 차례임
PETTE_PPORU_STEB_1_SLEEP_START =
{
	ANIM_NAME					= "Sleep",
	PLAY_TYPE					= XSKIN_ANIM_PLAYTYPE["XAP_ONE_WAIT"],
	TRANSITION					= TRUE,

	MOVE_TYPE           = 0,


	IMMADIATE_PACKET_SEND		= TRUE,

		ALLOW_DIR_CHANGE			= FALSE,

	EVENT_PROCESS =
	{
		{ STATE_CHANGE_TYPE["SCT_FOOT_ON_LINE_FALSE_DOWN"],	"PETTE_PPORU_STEB_1_JUMP_DOWN",					},
		{ STATE_CHANGE_TYPE["SCT_MOTION_END"],				"PETTE_PPORU_STEB_1_SLEEP_LOOP",						},
	},
	TALK_BOX_1 =
	{
		{ RATE = 34, MESSAGE = STR_ID_5899, APPLY_INTIMACY = TRUE,  },
		{ RATE = 33, MESSAGE = STR_ID_5900, APPLY_INTIMACY = TRUE,  },
		{ RATE = 33, MESSAGE = STR_ID_5901, APPLY_INTIMACY = TRUE,  },
	},
	TALK_BOX_2 =
	{
		{ RATE = 34, MESSAGE = STR_ID_5902, APPLY_INTIMACY = TRUE,  },
		{ RATE = 33, MESSAGE = STR_ID_5903, APPLY_INTIMACY = TRUE,  },
		{ RATE = 33, MESSAGE = STR_ID_5904, APPLY_INTIMACY = TRUE,  },
	},
	TALK_BOX =
	{
		{ RATE = 34, MESSAGE = STR_ID_5905, APPLY_INTIMACY = TRUE,  },
		{ RATE = 33, MESSAGE = STR_ID_5906, APPLY_INTIMACY = TRUE,  },
		{ RATE = 33, MESSAGE = STR_ID_5907, APPLY_INTIMACY = TRUE,  },
	},
}

PETTE_PPORU_STEB_1_SLEEP_LOOP =
{
	ANIM_NAME					= "SleepLoop",
	PLAY_TYPE					= XSKIN_ANIM_PLAYTYPE["XAP_LOOP"],
	TRANSITION					= TRUE,

	MOVE_TYPE           = 0,


	IMMADIATE_PACKET_SEND		= TRUE,

		ALLOW_DIR_CHANGE			= FALSE,

	EVENT_PROCESS =
	{
		{ STATE_CHANGE_TYPE["SCT_FOOT_ON_LINE_FALSE_DOWN"],	"PETTE_PPORU_STEB_1_JUMP_DOWN",					},
	},
}

PETTE_PPORU_STEB_1_SLEEP_END =
{
	ANIM_NAME					= "SleepEnd",
	PLAY_TYPE					= XSKIN_ANIM_PLAYTYPE["XAP_ONE_WAIT"],
	TRANSITION					= TRUE,

	MOVE_TYPE           = 0,


	IMMADIATE_PACKET_SEND		= TRUE,

	ALLOW_DIR_CHANGE			= FALSE,

	EVENT_PROCESS =
	{
		{ STATE_CHANGE_TYPE["SCT_FOOT_ON_LINE_FALSE_DOWN"],	"PETTE_PPORU_STEB_1_JUMP_DOWN",					},
		{ STATE_CHANGE_TYPE["SCT_MOTION_END"],				"PETTE_PPORU_STEB_1_WAIT",						},
	},

	TALK_BOX_1 =
	{
		{ RATE = 34, MESSAGE = STR_ID_5908, APPLY_INTIMACY = TRUE,  },
		{ RATE = 33, MESSAGE = STR_ID_5909, APPLY_INTIMACY = TRUE,  },
		{ RATE = 33, MESSAGE = STR_ID_5910, APPLY_INTIMACY = TRUE,  },
	},
	TALK_BOX_2 =
	{
		{ RATE = 34, MESSAGE = STR_ID_5911, APPLY_INTIMACY = TRUE,  },
		{ RATE = 33, MESSAGE = STR_ID_5912, APPLY_INTIMACY = TRUE,  },
		{ RATE = 33, MESSAGE = STR_ID_5913, APPLY_INTIMACY = TRUE,  },
	},
	TALK_BOX =
	{
		{ RATE = 34, MESSAGE = STR_ID_5914, APPLY_INTIMACY = TRUE,  },
		{ RATE = 33, MESSAGE = STR_ID_5915, APPLY_INTIMACY = TRUE,  },
		{ RATE = 33, MESSAGE = STR_ID_5916, APPLY_INTIMACY = TRUE,  },
	},

}

PETTE_PPORU_STEB_1_AFRAID =
{
	ANIM_NAME					= "Afraid",
	PLAY_TYPE					= XSKIN_ANIM_PLAYTYPE["XAP_ONE_WAIT"],
	TRANSITION					= TRUE,

	MOVE_TYPE           = 0,


	IMMADIATE_PACKET_SEND		= TRUE,

	ALLOW_DIR_CHANGE			= FALSE,

	EVENT_PROCESS =
	{
		{ STATE_CHANGE_TYPE["SCT_FOOT_ON_LINE_FALSE_DOWN"],	"PETTE_PPORU_STEB_1_JUMP_DOWN",					},
		{ STATE_CHANGE_TYPE["SCT_MOTION_END"],				"PETTE_PPORU_STEB_1_WAIT",						},
	},

	TALK_BOX_1 =
	{
		{ RATE = 34, MESSAGE = STR_ID_5917, APPLY_INTIMACY = TRUE, },
		{ RATE = 33, MESSAGE = STR_ID_5918, APPLY_INTIMACY = TRUE, },
		{ RATE = 33, MESSAGE = STR_ID_5919, APPLY_INTIMACY = TRUE, },
	},
	TALK_BOX_2 =
	{
		{ RATE = 34, MESSAGE = STR_ID_5920, APPLY_INTIMACY = TRUE, },
		{ RATE = 33, MESSAGE = STR_ID_5921, APPLY_INTIMACY = TRUE, },
		{ RATE = 33, MESSAGE = STR_ID_5922, APPLY_INTIMACY = TRUE, },
	},
	TALK_BOX =
	{
		{ RATE = 34, MESSAGE = STR_ID_5923, APPLY_INTIMACY = TRUE, },
		{ RATE = 33, MESSAGE = STR_ID_5924, APPLY_INTIMACY = TRUE, },
		{ RATE = 33, MESSAGE = STR_ID_5925, APPLY_INTIMACY = TRUE, },
	},
}

PETTE_PPORU_STEB_1_HELLO =
{
	ANIM_NAME					= "Hello",
	PLAY_TYPE					= XSKIN_ANIM_PLAYTYPE["XAP_ONE_WAIT"],
	TRANSITION					= TRUE,

	MOVE_TYPE           = 0,

    SOUND_PLAY0					= { 0.606, "Pet_PettePporu_Hello.ogg" },

	IMMADIATE_PACKET_SEND		= TRUE,

	ALLOW_DIR_CHANGE			= FALSE,

	EVENT_PROCESS =
	{
		{ STATE_CHANGE_TYPE["SCT_FOOT_ON_LINE_FALSE_DOWN"],	"PETTE_PPORU_STEB_1_JUMP_DOWN",					},
		{ STATE_CHANGE_TYPE["SCT_MOTION_END"],				"PETTE_PPORU_STEB_1_WAIT",						},
	},

	TALK_BOX_1 =
	{
		{ RATE = 34, MESSAGE = STR_ID_5926, APPLY_INTIMACY = TRUE, },
		{ RATE = 33, MESSAGE = STR_ID_5927, APPLY_INTIMACY = TRUE, },
		{ RATE = 33, MESSAGE = STR_ID_5928, APPLY_INTIMACY = TRUE, },
	},
	TALK_BOX_2 =
	{
		{ RATE = 34, MESSAGE = STR_ID_5929, APPLY_INTIMACY = TRUE, },
		{ RATE = 33, MESSAGE = STR_ID_5930, APPLY_INTIMACY = TRUE, },
		{ RATE = 33, MESSAGE = STR_ID_5931, APPLY_INTIMACY = TRUE, },
	},
	TALK_BOX =
	{
		{ RATE = 34, MESSAGE = STR_ID_5932, APPLY_INTIMACY = TRUE, },
		{ RATE = 33, MESSAGE = STR_ID_5933, APPLY_INTIMACY = TRUE, },
		{ RATE = 33, MESSAGE = STR_ID_5934, APPLY_INTIMACY = TRUE, },
	},
}

PETTE_PPORU_STEB_1_HAPPY1 =
{
	ANIM_NAME					= "Cute1",
	PLAY_TYPE					= XSKIN_ANIM_PLAYTYPE["XAP_ONE_WAIT"],
	TRANSITION					= TRUE,

	MOVE_TYPE           = 0,

    SOUND_PLAY0					= { 0.286, "Pet_PettePporu_Cute1.ogg" },

	IMMADIATE_PACKET_SEND		= TRUE,

	ALLOW_DIR_CHANGE			= FALSE,

	EVENT_PROCESS =
	{
		{ STATE_CHANGE_TYPE["SCT_FOOT_ON_LINE_FALSE_DOWN"],	"PETTE_PPORU_STEB_1_JUMP_DOWN",					},
		{ STATE_CHANGE_TYPE["SCT_MOTION_END"],				"PETTE_PPORU_STEB_1_WAIT",						},
	},

	TALK_BOX_1 =
	{
		{ RATE = 34, MESSAGE = STR_ID_5935, APPLY_INTIMACY = TRUE, },
		{ RATE = 33, MESSAGE = STR_ID_5936, APPLY_INTIMACY = TRUE, },
		{ RATE = 33, MESSAGE = STR_ID_5937, APPLY_INTIMACY = TRUE, },
	},
	TALK_BOX_2 =
	{
		{ RATE = 34, MESSAGE = STR_ID_5938, APPLY_INTIMACY = TRUE, },
		{ RATE = 33, MESSAGE = STR_ID_5939, APPLY_INTIMACY = TRUE, },
		{ RATE = 33, MESSAGE = STR_ID_5940, APPLY_INTIMACY = TRUE, },
	},
	TALK_BOX =
	{
		{ RATE = 34, MESSAGE = STR_ID_5941, APPLY_INTIMACY = TRUE, },
		{ RATE = 33, MESSAGE = STR_ID_5942, APPLY_INTIMACY = TRUE, },
		{ RATE = 33, MESSAGE = STR_ID_5943, APPLY_INTIMACY = TRUE, },
	},
}

PETTE_PPORU_STEB_1_HAPPY2 =
{
	ANIM_NAME					= "Cute2",
	PLAY_TYPE					= XSKIN_ANIM_PLAYTYPE["XAP_ONE_WAIT"],
	TRANSITION					= TRUE,

	MOVE_TYPE           = 0,

    SOUND_PLAY0					= { 0.286, "Pet_PettePporu_Cute2.ogg" },

	IMMADIATE_PACKET_SEND		= TRUE,

	ALLOW_DIR_CHANGE			= FALSE,

	EVENT_PROCESS =
	{
		{ STATE_CHANGE_TYPE["SCT_FOOT_ON_LINE_FALSE_DOWN"],	"PETTE_PPORU_STEB_1_JUMP_DOWN",					},
		{ STATE_CHANGE_TYPE["SCT_MOTION_END"],				"PETTE_PPORU_STEB_1_WAIT",						},
	},

	TALK_BOX_1 =
	{
		{ RATE = 34, MESSAGE = STR_ID_5944, APPLY_INTIMACY = TRUE, },
		{ RATE = 33, MESSAGE = STR_ID_5945, APPLY_INTIMACY = TRUE, },
		{ RATE = 33, MESSAGE = STR_ID_5946, APPLY_INTIMACY = TRUE, },
	},
	TALK_BOX_2 =
	{
		{ RATE = 34, MESSAGE = STR_ID_5947, APPLY_INTIMACY = TRUE, },
		{ RATE = 33, MESSAGE = STR_ID_5948, APPLY_INTIMACY = TRUE, },
		{ RATE = 33, MESSAGE = STR_ID_5949, APPLY_INTIMACY = TRUE, },
	},
	TALK_BOX =
	{
		{ RATE = 34, MESSAGE = STR_ID_5950, APPLY_INTIMACY = TRUE, },
		{ RATE = 33, MESSAGE = STR_ID_5951, APPLY_INTIMACY = TRUE, },
		{ RATE = 33, MESSAGE = STR_ID_5952, APPLY_INTIMACY = TRUE, },
	},
}

PETTE_PPORU_STEB_1_CUTE1 =
{
	ANIM_NAME					= "Cute1",
	PLAY_TYPE					= XSKIN_ANIM_PLAYTYPE["XAP_ONE_WAIT"],
	TRANSITION					= TRUE,

	MOVE_TYPE           = 0,

    SOUND_PLAY0					= { 0.286, "Pet_PettePporu_Cute1.ogg" },

	IMMADIATE_PACKET_SEND		= TRUE,

	ALLOW_DIR_CHANGE			= FALSE,

	EVENT_PROCESS =
	{
		{ STATE_CHANGE_TYPE["SCT_FOOT_ON_LINE_FALSE_DOWN"],	"PETTE_PPORU_STEB_1_JUMP_DOWN",					},
		{ STATE_CHANGE_TYPE["SCT_MOTION_END"],				"PETTE_PPORU_STEB_1_WAIT",						},
	},

	TALK_BOX_1 =
	{
		{ RATE = 33, MESSAGE = STR_ID_5953, APPLY_INTIMACY = TRUE, },
		{ RATE = 34, MESSAGE = STR_ID_5954, APPLY_INTIMACY = TRUE, },
		{ RATE = 33, MESSAGE = STR_ID_5955, APPLY_INTIMACY = TRUE, },
	},
	TALK_BOX_2 =
	{
		{ RATE = 33, MESSAGE = STR_ID_5956, APPLY_INTIMACY = TRUE, },
		{ RATE = 34, MESSAGE = STR_ID_5957, APPLY_INTIMACY = TRUE, },
		{ RATE = 33, MESSAGE = STR_ID_5958, APPLY_INTIMACY = TRUE, },
	},
	TALK_BOX =
	{
		{ RATE = 33, MESSAGE = STR_ID_5959, APPLY_INTIMACY = TRUE, },
		{ RATE = 34, MESSAGE = STR_ID_5960, APPLY_INTIMACY = TRUE, },
		{ RATE = 33, MESSAGE = STR_ID_5961, APPLY_INTIMACY = TRUE, },
	},

}

PETTE_PPORU_STEB_1_CUTE2 =
{
	ANIM_NAME					= "Cute2",
	PLAY_TYPE					= XSKIN_ANIM_PLAYTYPE["XAP_ONE_WAIT"],
	TRANSITION					= TRUE,

	MOVE_TYPE           = 0,

    SOUND_PLAY0					= { 1.2, "Pet_PettePporu_Cute2.ogg" },

	IMMADIATE_PACKET_SEND		= TRUE,

	ALLOW_DIR_CHANGE			= FALSE,

	EVENT_PROCESS =
	{
		{ STATE_CHANGE_TYPE["SCT_FOOT_ON_LINE_FALSE_DOWN"],	"PETTE_PPORU_STEB_1_JUMP_DOWN",					},
		{ STATE_CHANGE_TYPE["SCT_MOTION_END"],				"PETTE_PPORU_STEB_1_WAIT",						},
	},

	TALK_BOX_1 =
	{
		{ RATE = 33, MESSAGE = STR_ID_5962, APPLY_INTIMACY = TRUE, },
		{ RATE = 34, MESSAGE = STR_ID_5963, APPLY_INTIMACY = TRUE, },
		{ RATE = 33, MESSAGE = STR_ID_5964, APPLY_INTIMACY = TRUE, },
	},
	TALK_BOX_2 =
	{
		{ RATE = 33, MESSAGE = STR_ID_5965, APPLY_INTIMACY = TRUE, },
		{ RATE = 34, MESSAGE = STR_ID_5966, APPLY_INTIMACY = TRUE, },
		{ RATE = 33, MESSAGE = STR_ID_5967, APPLY_INTIMACY = TRUE, },
	},
	TALK_BOX =
	{
		{ RATE = 33, MESSAGE = STR_ID_5968, APPLY_INTIMACY = TRUE, },
		{ RATE = 34, MESSAGE = STR_ID_5969, APPLY_INTIMACY = TRUE, },
		{ RATE = 33, MESSAGE = STR_ID_5970, APPLY_INTIMACY = TRUE, },
	},
}

PETTE_PPORU_STEB_1_SAD =
{
	ANIM_NAME					= "Afraid",
	PLAY_TYPE					= XSKIN_ANIM_PLAYTYPE["XAP_ONE_WAIT"],
	TRANSITION					= TRUE,

	MOVE_TYPE           = 0,


	IMMADIATE_PACKET_SEND		= TRUE,

	ALLOW_DIR_CHANGE			= FALSE,

	EVENT_PROCESS =
	{
		{ STATE_CHANGE_TYPE["SCT_FOOT_ON_LINE_FALSE_DOWN"],	"PETTE_PPORU_STEB_1_JUMP_DOWN",					},
		{ STATE_CHANGE_TYPE["SCT_MOTION_END"],				"PETTE_PPORU_STEB_1_WAIT",						},
	},

	TALK_BOX_1 =
	{
		{ RATE = 33, MESSAGE = STR_ID_5971, APPLY_INTIMACY = TRUE, },
		{ RATE = 34, MESSAGE = STR_ID_5972, APPLY_INTIMACY = TRUE, },
		{ RATE = 33, MESSAGE = STR_ID_5973, APPLY_INTIMACY = TRUE, },
	},
	TALK_BOX_2 =
	{
		{ RATE = 33, MESSAGE = STR_ID_5974, APPLY_INTIMACY = TRUE, },
		{ RATE = 34, MESSAGE = STR_ID_5975, APPLY_INTIMACY = TRUE, },
		{ RATE = 33, MESSAGE = STR_ID_5976, APPLY_INTIMACY = TRUE, },
	},
	TALK_BOX =
	{
		{ RATE = 33, MESSAGE = STR_ID_5977, APPLY_INTIMACY = TRUE, },
		{ RATE = 34, MESSAGE = STR_ID_5978, APPLY_INTIMACY = TRUE, },
		{ RATE = 33, MESSAGE = STR_ID_5979, APPLY_INTIMACY = TRUE, },
	},

}

PETTE_PPORU_STEB_1_CHEER =
{
	ANIM_NAME					= "Cheer",
	PLAY_TYPE					= XSKIN_ANIM_PLAYTYPE["XAP_ONE_WAIT"],
	TRANSITION					= TRUE,

	MOVE_TYPE           = 0,

    SOUND_PLAY0					= { 0.005, "Pet_Cheer_Common.ogg" },
    SOUND_PLAY1					= { 1.165, "Pet_PettePporu_Cheer.ogg" },

	IMMADIATE_PACKET_SEND		= TRUE,

	ALLOW_DIR_CHANGE			= FALSE,

	EVENT_PROCESS =
	{
		{ STATE_CHANGE_TYPE["SCT_FOOT_ON_LINE_FALSE_DOWN"],	"PETTE_PPORU_STEB_1_JUMP_DOWN",					},
		{ STATE_CHANGE_TYPE["SCT_MOTION_END"],				"PETTE_PPORU_STEB_1_WAIT",						},
	},

	TALK_BOX_1 =
	{
		{ RATE = 33, MESSAGE = STR_ID_5980 },
		{ RATE = 34, MESSAGE = STR_ID_5981 },
		{ RATE = 33, MESSAGE = STR_ID_5982 },
	},
	TALK_BOX_2 =
	{
		{ RATE = 33, MESSAGE = STR_ID_5983 },
		{ RATE = 34, MESSAGE = STR_ID_5984 },
		{ RATE = 33, MESSAGE = STR_ID_5985 },
	},
	TALK_BOX =
	{
		{ RATE = 33, MESSAGE = STR_ID_5986 },
		{ RATE = 34, MESSAGE = STR_ID_5987 },
		{ RATE = 33, MESSAGE = STR_ID_5988 },
	},
}

PETTE_PPORU_STEB_1_SPECIAL =
{
	ANIM_NAME					= "Special_A",
	PLAY_TYPE					= XSKIN_ANIM_PLAYTYPE["XAP_ONE_WAIT"],
	TRANSITION					= TRUE,

	MOVE_TYPE           = 0,

    SOUND_PLAY0					= { 0.306, "Pet_PettePporu_Special.ogg" },

	IMMADIATE_PACKET_SEND		= TRUE,

	ALLOW_DIR_CHANGE			= FALSE,

	EVENT_PROCESS =
	{
		{ STATE_CHANGE_TYPE["SCT_FOOT_ON_LINE_FALSE_DOWN"],	"PETTE_PPORU_STEB_1_JUMP_DOWN",					},
		{ STATE_CHANGE_TYPE["SCT_MOTION_END"],				"PETTE_PPORU_STEB_1_WAIT",						},
	},

	TALK_BOX_1 =
	{
		{ RATE = 34, MESSAGE = STR_ID_5989 },
		{ RATE = 33, MESSAGE = STR_ID_5990 },
		{ RATE = 33, MESSAGE = STR_ID_5991 },
	},
	TALK_BOX_2 =
	{
		{ RATE = 34, MESSAGE = STR_ID_5992 },
		{ RATE = 33, MESSAGE = STR_ID_5993 },
		{ RATE = 33, MESSAGE = STR_ID_5994 },
	},
	TALK_BOX =
	{
		{ RATE = 34, MESSAGE = STR_ID_5995 },
		{ RATE = 33, MESSAGE = STR_ID_5996 },
		{ RATE = 33, MESSAGE = STR_ID_5997 },
	},
}

PETTE_PPORU_STEB_1_ATTACK =
{
	ANIM_NAME					= "Attack_A",
	PLAY_TYPE					= XSKIN_ANIM_PLAYTYPE["XAP_ONE_WAIT"],
	TRANSITION					= TRUE,

	MOVE_TYPE           = 0,
	VIEW_TARGET			= TRUE,

	SOUND_PLAY0					= { 0.241, "Pet_PettePporu_Attack.ogg" },

	IMMADIATE_PACKET_SEND		= TRUE,

	EVENT_PROCESS =
	{
		{ STATE_CHANGE_TYPE["SCT_FOOT_ON_LINE_FALSE_DOWN"],	"PETTE_PPORU_STEB_1_JUMP_DOWN",					},
		{ STATE_CHANGE_TYPE["SCT_MOTION_END"],				"PETTE_PPORU_STEB_1_WAIT",						},
	},

	TALK_BOX_1 =
	{
		{ RATE = 34, MESSAGE = STR_ID_6001 },
		{ RATE = 33, MESSAGE = STR_ID_5999 },
		{ RATE = 33, MESSAGE = STR_ID_6000 },
	},
	TALK_BOX_2 =
	{
		{ RATE = 34, MESSAGE = STR_ID_6004 },
		{ RATE = 33, MESSAGE = STR_ID_6002 },
		{ RATE = 33, MESSAGE = STR_ID_6003 },
	},
	TALK_BOX =
	{
		{ RATE = 34, MESSAGE = STR_ID_6007 },
		{ RATE = 33, MESSAGE = STR_ID_6005 },
		{ RATE = 33, MESSAGE = STR_ID_6006 },
	},
}


PETTE_PPORU_STEB_1_SIT_START =
{
	ANIM_NAME					= "Sit_Ready",
	PLAY_TYPE					= XSKIN_ANIM_PLAYTYPE["XAP_ONE_WAIT"],
	TRANSITION					= TRUE,

	MOVE_TYPE           = 0,


	IMMADIATE_PACKET_SEND		= TRUE,

	ALLOW_DIR_CHANGE			= FALSE,

	EVENT_PROCESS =
	{
		{ STATE_CHANGE_TYPE["SCT_FOOT_ON_LINE_FALSE_DOWN"],	"PETTE_PPORU_STEB_1_JUMP_DOWN",					},
		{ STATE_CHANGE_TYPE["SCT_MOTION_END"],				"PETTE_PPORU_STEB_1_SIT_LOOP",						},
	},

	TALK_BOX_1 =
	{
		{ RATE = 33, MESSAGE = STR_ID_6007, APPLY_INTIMACY = TRUE, },
		{ RATE = 33, MESSAGE = STR_ID_6008, APPLY_INTIMACY = TRUE, },
		{ RATE = 34, MESSAGE = STR_ID_6009, APPLY_INTIMACY = TRUE, },
	},
	TALK_BOX_2 =
	{
		{ RATE = 33, MESSAGE = STR_ID_6010, APPLY_INTIMACY = TRUE, },
		{ RATE = 33, MESSAGE = STR_ID_6011, APPLY_INTIMACY = TRUE, },
		{ RATE = 34, MESSAGE = STR_ID_6012, APPLY_INTIMACY = TRUE, },
	},
	TALK_BOX =
	{
		{ RATE = 33, MESSAGE = STR_ID_6013, APPLY_INTIMACY = TRUE, },
		{ RATE = 33, MESSAGE = STR_ID_6014, APPLY_INTIMACY = TRUE, },
		{ RATE = 34, MESSAGE = STR_ID_6015, APPLY_INTIMACY = TRUE, },
	},
}

PETTE_PPORU_STEB_1_SIT_LOOP =
{
	ANIM_NAME					= "Sit",
	PLAY_TYPE					= XSKIN_ANIM_PLAYTYPE["XAP_LOOP"],
	TRANSITION					= TRUE,

	MOVE_TYPE           = 0,


	IMMADIATE_PACKET_SEND		= TRUE,

	ALLOW_DIR_CHANGE			= FALSE,

	EVENT_PROCESS =
	{
		{ STATE_CHANGE_TYPE["SCT_FOOT_ON_LINE_FALSE_DOWN"],	"PETTE_PPORU_STEB_1_JUMP_DOWN",					},
	},
}

PETTE_PPORU_STEB_1_SIT_END =
{
	ANIM_NAME					= "Sit_End",
	PLAY_TYPE					= XSKIN_ANIM_PLAYTYPE["XAP_ONE_WAIT"],
	TRANSITION					= TRUE,

	MOVE_TYPE           = 0,


	IMMADIATE_PACKET_SEND		= TRUE,

	ALLOW_DIR_CHANGE			= FALSE,

	EVENT_PROCESS =
	{
		{ STATE_CHANGE_TYPE["SCT_FOOT_ON_LINE_FALSE_DOWN"],	"PETTE_PPORU_STEB_1_JUMP_DOWN",					},
		{ STATE_CHANGE_TYPE["SCT_MOTION_END"],				"PETTE_PPORU_STEB_1_WAIT",						},
	},

	TALK_BOX_1 =
	{
		{ RATE = 33, MESSAGE = STR_ID_6016, APPLY_INTIMACY = TRUE,  },
		{ RATE = 33, MESSAGE = STR_ID_6017, APPLY_INTIMACY = TRUE,  },
		{ RATE = 34, MESSAGE = STR_ID_6018, APPLY_INTIMACY = TRUE,  },
	},
	TALK_BOX_2 =
	{
		{ RATE = 33, MESSAGE = STR_ID_6019, APPLY_INTIMACY = TRUE,  },
		{ RATE = 33, MESSAGE = STR_ID_6020, APPLY_INTIMACY = TRUE,  },
		{ RATE = 34, MESSAGE = STR_ID_6021, APPLY_INTIMACY = TRUE,  },
	},
	TALK_BOX =
	{
		{ RATE = 33, MESSAGE = STR_ID_6022, APPLY_INTIMACY = TRUE,  },
		{ RATE = 33, MESSAGE = STR_ID_6023, APPLY_INTIMACY = TRUE,  },
		{ RATE = 34, MESSAGE = STR_ID_6024, APPLY_INTIMACY = TRUE,  },
	},
}

PETTE_PPORU_STEB_1_NOTKNOW =
{
	ANIM_NAME					= "DoNotKnow",
	PLAY_TYPE					= XSKIN_ANIM_PLAYTYPE["XAP_ONE_WAIT"],
	TRANSITION					= TRUE,

	MOVE_TYPE           = 0,


	IMMADIATE_PACKET_SEND		= TRUE,

	ALLOW_DIR_CHANGE			= FALSE,

	EVENT_PROCESS =
	{
		{ STATE_CHANGE_TYPE["SCT_FOOT_ON_LINE_FALSE_DOWN"],	"PETTE_PPORU_STEB_1_JUMP_DOWN",					},
		{ STATE_CHANGE_TYPE["SCT_MOTION_END"],				"PETTE_PPORU_STEB_1_WAIT",						},
	},

	-- TALK_BOX_1 =
 	-- {
		-- { RATE = 20, MESSAGE = STR_ID_5600, APPLY_INTIMACY = TRUE,  },
		-- { RATE = 20, MESSAGE = STR_ID_5601, APPLY_INTIMACY = TRUE,  },
		-- { RATE = 20, MESSAGE = STR_ID_5602, APPLY_INTIMACY = TRUE,  },
		-- { RATE = 20, MESSAGE = STR_ID_5603, APPLY_INTIMACY = TRUE,  },
		-- { RATE = 20, MESSAGE = STR_ID_5604, APPLY_INTIMACY = TRUE,  },
	-- },
	-- TALK_BOX_2 =
 	-- {
		-- { RATE = 20, MESSAGE = STR_ID_5600, APPLY_INTIMACY = TRUE,  },
		-- { RATE = 20, MESSAGE = STR_ID_5601, APPLY_INTIMACY = TRUE,  },
		-- { RATE = 20, MESSAGE = STR_ID_5602, APPLY_INTIMACY = TRUE,  },
		-- { RATE = 20, MESSAGE = STR_ID_5603, APPLY_INTIMACY = TRUE,  },
		-- { RATE = 20, MESSAGE = STR_ID_5604, APPLY_INTIMACY = TRUE,  },
	-- },
	-- TALK_BOX =
 	-- {
		-- { RATE = 20, MESSAGE = STR_ID_5600, APPLY_INTIMACY = TRUE,  },
		-- { RATE = 20, MESSAGE = STR_ID_5601, APPLY_INTIMACY = TRUE,  },
		-- { RATE = 20, MESSAGE = STR_ID_5602, APPLY_INTIMACY = TRUE,  },
		-- { RATE = 20, MESSAGE = STR_ID_5603, APPLY_INTIMACY = TRUE,  },
		-- { RATE = 20, MESSAGE = STR_ID_5604, APPLY_INTIMACY = TRUE,  },
	-- },
}





function PETTE_PPORU_STEB_1_ATTACK_FRAME_MOVE( pKTDXApp, pX2Game, pPet )

    if pPet:AnimEventTimer( 0.25 ) then
		local pDamageEffect = pX2Game:GetDamageEffect()

		if pDamageEffect ~= nil then
			local vLandPos = pPet:GetLandPosition_LUA()
			local vPos = pPet:GetBonePos_LUA("Bip01_R_Hand")
			local vRot = pPet:GetRotateDegree()
			vPos.y = vPos.y + 35

	        local pMasterUnit = pPet:GetMaster()
	        if pMasterUnit ~= nil and pMasterUnit:GetNowHP() > 0 then
				pDamageEffect:CreateInstanceByPet_LUA( pMasterUnit, "PET_PETTE_PPORU_ATTACK1", vPos, vLandPos, vRot )
			end
		end
	end
end

function CF_PETATTACK_PETTE_PPORU_STEB_1( pKTDXApp, pX2Game, pPet )

	if pX2Game ~= nil then
		if pX2Game:IsHost() == false then
			return false
		end
	end

	if pPet:IsAttacking() == true then

		local fDist = pPet:GetDistTarget()
		if fDist <= 300 then
			return true
		end
	end

	return false
end