-- lua header. UTF-8 인코딩 인식을 위해 이 줄은 지우지 마세요.

SOUND_FIX_TIME = -0.05

INIT_SYSTEM =
{
	UNIT_LAYER		= X2_LAYER["XL_UNIT_0"],
	UNIT_SCALE		= 1.0,
}


INIT_DEVICE =
{
	READY_XSKIN_MESH =
	{
		"DummyAttackBox_50x50x50.X"
	},

	READY_TEXTURE =
	{
	},

	READY_SOUND =
	{
	"JumpLand.ogg",
	"Pet_Cheer_Common.ogg",
	"Pet_Hungry.ogg",
	"Pet_Stuffed.ogg",
	"Pet_Eat01.ogg",
	"Pet_RAINCOAT_CAT_Habit.ogg",
	"Pet_RAINCOAT_CAT_Special.ogg",
	"Pet_RAINCOAT_CAT_Special_Attack_A.ogg",
	"Pet_RAINCOAT_CAT_Special_Cute1.ogg",
	"Pet_RAINCOAT_CAT_Special_Cute2.ogg",
	"Pet_RAINCOAT_CAT_Special_DashEnd.ogg",
	"Pet_RAINCOAT_CAT_Special_Hello.ogg",
	"Pet_RAINCOAT_CAT_Special_SleepLoop.ogg",
	},
}

INIT_MOTION =
{
	MOTION_FILE_NAME		= "Motion_PET_RAINCOAT_CAT_YELLOW_STEB_1.x",
	MOTION_ANI_TEX_XET		= "PET_RAINCOAT_CAT_YELLOW_FACE_SLEEP_1.xet",	
	--MOTION_CHANGE_TEX_XET		= "PET_RAINCOAT_CAT_STEB_1.xet",
}


INIT_COMPONENT =
{
	MAX_HP				= 6000,
	MP_CHANGE_RATE		= 1,
	MP_CHARGE_RATE		= 130,


	SHADOW_SIZE			= 200,
	SHADOW_FILE_NAME	= "shadow.dds",

	SMALL_HP_BAR_BLUE	= "Small_HP_bar_Blue.TGA",
	SMALL_HP_BAR_RED	= "Small_HP_bar_Red.TGA",
	SMALL_HP_BAR_YELLOW = "Small_HP_bar_Yellow.TGA",

	QUESTION_MARK_SEQ		= "QuestionMarkNPC",
	EXCLAMATION_MARK_SEQ	= "ExclamationMarkNPC",

	HYPER_MODE_COUNT	= 0,
	MAX_HYPER_MODE_TIME	= 30,

	HITTED_TYPE			= HITTED_TYPE["HTD_MEAT"],

	FALL_DOWN			= TRUE,



}

INIT_STATE =
{
	{ STATE_NAME = "RAINCOAT_CAT_STEB_1_SUMMON",			},
	{ STATE_NAME = "RAINCOAT_CAT_STEB_1_WAIT_HABIT",		STATE_COOL_TIME = 20, },
	{ STATE_NAME = "RAINCOAT_CAT_STEB_1_WAIT",						},
	{ STATE_NAME = "RAINCOAT_CAT_STEB_1_WALK",						},
	{ STATE_NAME = "RAINCOAT_CAT_STEB_1_DASH",						},
	{ STATE_NAME = "RAINCOAT_CAT_STEB_1_DASH_END",					},
	{ STATE_NAME = "RAINCOAT_CAT_STEB_1_JUMP_UP",					},
	{ STATE_NAME = "RAINCOAT_CAT_STEB_1_JUMP_DOWN",				},
	{ STATE_NAME = "RAINCOAT_CAT_STEB_1_JUMP_UP_DIR",				},
	{ STATE_NAME = "RAINCOAT_CAT_STEB_1_JUMP_DOWN_DIR",			},
	{ STATE_NAME = "RAINCOAT_CAT_STEB_1_JUMP_LANDING",				},
	{ STATE_NAME = "RAINCOAT_CAT_STEB_1_EAT",				},
	{ STATE_NAME = "RAINCOAT_CAT_STEB_1_HUNGRY",				},
	{ STATE_NAME = "RAINCOAT_CAT_STEB_1_STUFFED",				},
	{ STATE_NAME = "RAINCOAT_CAT_STEB_1_SLEEP_START",				},
	{ STATE_NAME = "RAINCOAT_CAT_STEB_1_SLEEP_LOOP",				},
	{ STATE_NAME = "RAINCOAT_CAT_STEB_1_SLEEP_END",				},
	{ STATE_NAME = "RAINCOAT_CAT_STEB_1_AFRAID",				STATE_COOL_TIME = 10, },
	{ STATE_NAME = "RAINCOAT_CAT_STEB_1_HELLO",				},
	{ STATE_NAME = "RAINCOAT_CAT_STEB_1_HAPPY1",				},
	{ STATE_NAME = "RAINCOAT_CAT_STEB_1_HAPPY2",				},
  { STATE_NAME = "RAINCOAT_CAT_STEB_1_CUTE1",				STATE_COOL_TIME = 10, },
  { STATE_NAME = "RAINCOAT_CAT_STEB_1_CUTE2",				STATE_COOL_TIME = 10, },
  { STATE_NAME = "RAINCOAT_CAT_STEB_1_SAD",				},
  { STATE_NAME = "RAINCOAT_CAT_STEB_1_CHEER",			LUA_FRAME_MOVE_FUNC = "RAINCOAT_CAT_STEB_1_CHEER_FRAME_MOVE",	STATE_COOL_TIME = 180,	},
  { STATE_NAME = "RAINCOAT_CAT_STEB_1_SPECIAL",				},
  { STATE_NAME = "RAINCOAT_CAT_STEB_1_ATTACK",			LUA_FRAME_MOVE_FUNC = "RAINCOAT_CAT_STEB_1_ATTACK_FRAME_MOVE",	},
  { STATE_NAME = "RAINCOAT_CAT_STEB_1_SIT_START",				},
  { STATE_NAME = "RAINCOAT_CAT_STEB_1_SIT_LOOP",				},
  { STATE_NAME = "RAINCOAT_CAT_STEB_1_SIT_END",				},
  { STATE_NAME = "RAINCOAT_CAT_STEB_1_NOTKNOW",				},

  START_STATE					= "RAINCOAT_CAT_STEB_1_SUMMON",
  WAIT_HABIT					= "RAINCOAT_CAT_STEB_1_WAIT_HABIT",
	WAIT_STATE					= "RAINCOAT_CAT_STEB_1_WAIT",
	EAT_STATE           = "RAINCOAT_CAT_STEB_1_EAT",
	HUNGRY_STATE       = "RAINCOAT_CAT_STEB_1_HUNGRY",
	STUFFED_STATE       = "RAINCOAT_CAT_STEB_1_STUFFED",
	SLEEP_START_STATE   = "RAINCOAT_CAT_STEB_1_SLEEP_START",
	SLEEP_LOOP_STATE   = "RAINCOAT_CAT_STEB_1_SLEEP_LOOP",
  SLEEP_END_STATE     = "RAINCOAT_CAT_STEB_1_SLEEP_END",
  AFRAID_STATE        = "RAINCOAT_CAT_STEB_1_AFRAID",
  HELLO_STATE         = "RAINCOAT_CAT_STEB_1_HELLO",
  HAPPY1_STATE         = "RAINCOAT_CAT_STEB_1_HAPPY1",
  HAPPY2_STATE         = "RAINCOAT_CAT_STEB_1_HAPPY2",
  CUTE1_STATE          = "RAINCOAT_CAT_STEB_1_CUTE1",
  CUTE2_STATE          = "RAINCOAT_CAT_STEB_1_CUTE2",
  SAD_STATE           = "RAINCOAT_CAT_STEB_1_SAD",
  CHEER_STATE         = "RAINCOAT_CAT_STEB_1_CHEER",
  SPECIAL_STATE       = "RAINCOAT_CAT_STEB_1_SPECIAL",
  ATTACK_STATE      = "RAINCOAT_CAT_STEB_1_ATTACK",
  SIT_START_STATE     = "RAINCOAT_CAT_STEB_1_SIT_START",
  SIT_LOOP_STATE     = "RAINCOAT_CAT_STEB_1_SIT_LOOP",
  SIT_END_STATE       = "RAINCOAT_CAT_STEB_1_SIT_END",
  NOTKNOW_STATE       = "RAINCOAT_CAT_STEB_1_NOTKNOW",
}

INIT_AI =
{
	TARGET =
	{
		TARGET_PRIORITY 			= TARGET_PRIORITY["TP_LOW_HP_FIRST"],
		TARGET_INTERVAL				= 0.5,		-- sec
		TARGET_NEAR_RANGE			= 200,		-- 이 거리보다 가까우면 TARGET_SUCCESS_RATE에 관계없이 무조건 타게팅된다
		TARGET_RANGE				= 10000,		-- cm
		TARGET_LOST_RANGE			= 2000,	-- cm
		TARGET_SUCCESS_RATE			= 100,  --70,		-- %
		ATTACK_TARGET_RATE			= 100, -- 80,		-- 나를 공격한 유닛을 타게팅할 확률
		PRESERVE_LAST_TARGET_RATE	= 100, -- 80,		-- 이전에 타게팅된 유닛을 계속 타게팅할 확률
	},

	CHASE_MOVE =
	{
		MOVE_SPLIT_RANGE	= 100,
		DEST_GAP			= 200,	-- 목적지에서 이 거리 안에 있으면 도착했다고 판단한다
		MOVE_GAP			= 100,
		RUN_GAP				= 500,

		DIR_CHANGE_INTERVAL = 0.3,

		WALK_INTERVAL		= 1,
		NEAR_WALK_RATE		= 100,   --  70,
		FAR_WALK_RATE		= 100,   -- 30,

		JUMP_INTERVAL		= 0,
		UP_JUMP_RATE		= 0, -- 40,
		UP_DOWN_RATE		= 0,
		DOWN_JUMP_RATE		= 0,    --  20,
		DOWN_DOWN_RATE		= 0,
	},

}

RAINCOAT_CAT_STEB_1_SUMMON =
{
	ANIM_NAME					= "Wait",
	PLAY_TYPE					= XSKIN_ANIM_PLAYTYPE["XAP_ONE_WAIT"],
	TRANSITION					= TRUE,

	MOVE_TYPE           = 0,

	CAN_PUSH_UNIT				= TRUE,
	CAN_PASS_UNIT				= FALSE,
	IMMADIATE_PACKET_SEND		= TRUE,

	ALLOW_DIR_CHANGE			= FALSE,

	EVENT_PROCESS =
	{
		{ STATE_CHANGE_TYPE["SCT_FOOT_ON_LINE_FALSE_DOWN"],	"RAINCOAT_CAT_STEB_1_JUMP_DOWN",					},
		{ STATE_CHANGE_TYPE["SCT_MOTION_END"],				"RAINCOAT_CAT_STEB_1_WAIT",						},
	},
}

RAINCOAT_CAT_STEB_1_WAIT =
{
	ANIM_NAME					= "Wait",
	PLAY_TYPE					= XSKIN_ANIM_PLAYTYPE["XAP_LOOP"],
	TRANSITION					= TRUE,

	MOVE_TYPE           = 0,

	IMMADIATE_PACKET_SEND		= TRUE,
	EVENT_INTERVAL_TIME0		= 2,

	EVENT_PROCESS =
	{
		{ STATE_CHANGE_TYPE["SCT_FOOT_ON_LINE_FALSE_DOWN"],	"RAINCOAT_CAT_STEB_1_JUMP_DOWN",					},

		{ STATE_CHANGE_TYPE["SCT_CONDITION_FUNCTION"],      "RAINCOAT_CAT_STEB_1_ATTACK",						"CF_PETATTACK_RAINCOAT_CAT_STEB_1"    },

		{ STATE_CHANGE_TYPE["SCT_AI_DIR_CHANGE"],			"RAINCOAT_CAT_STEB_1_WALK",						},

		{ STATE_CHANGE_TYPE["SCT_AI_WALK"],					"RAINCOAT_CAT_STEB_1_WALK",						},
		{ STATE_CHANGE_TYPE["SCT_AI_DASH"],					"RAINCOAT_CAT_STEB_1_DASH",						},
		{ STATE_CHANGE_TYPE["SCT_AI_JUMP"],					"RAINCOAT_CAT_STEB_1_JUMP_UP",						},
		{ STATE_CHANGE_TYPE["SCT_AI_JUMP_DIR"],				"RAINCOAT_CAT_STEB_1_JUMP_UP_DIR",					},
		{ STATE_CHANGE_TYPE["SCT_AI_DOWN"],					"RAINCOAT_CAT_STEB_1_JUMP_DOWN",					},
		{ STATE_CHANGE_TYPE["SCT_AI_DOWN_DIR"],				"RAINCOAT_CAT_STEB_1_JUMP_DOWN_DIR",				},
	},
}


RAINCOAT_CAT_STEB_1_WALK =
{
	ANIM_NAME					= "Walk",
	PLAY_TYPE					= XSKIN_ANIM_PLAYTYPE["XAP_LOOP"],
	TRANSITION					= TRUE,

	CAN_PUSH_UNIT				= TRUE,
	CAN_PASS_UNIT				= FALSE,

	MOVE_TYPE           = 1,
	PASSIVE_SPEED_X_BY_USER			= 1.2,

	IMMADIATE_PACKET_SEND		= TRUE,

	EVENT_INTERVAL_TIME0		= 2,

	EVENT_PROCESS =
	{
		{ STATE_CHANGE_TYPE["SCT_FOOT_ON_LINE_FALSE_DOWN"],	"RAINCOAT_CAT_STEB_1_JUMP_DOWN_DIR",				},

		{ STATE_CHANGE_TYPE["SCT_CONDITION_FUNCTION"],      "RAINCOAT_CAT_STEB_1_ATTACK",						"CF_PETATTACK_RAINCOAT_CAT_STEB_1"    },

		{ STATE_CHANGE_TYPE["SCT_AI_WAIT"],					"RAINCOAT_CAT_STEB_1_WAIT",						},
		{ STATE_CHANGE_TYPE["SCT_AI_DASH"],					"RAINCOAT_CAT_STEB_1_DASH",						},

		{ STATE_CHANGE_TYPE["SCT_AI_JUMP"],					"RAINCOAT_CAT_STEB_1_JUMP_UP",						},
		{ STATE_CHANGE_TYPE["SCT_AI_JUMP_DIR"],				"RAINCOAT_CAT_STEB_1_JUMP_UP_DIR",					},
		{ STATE_CHANGE_TYPE["SCT_AI_DOWN"],					"RAINCOAT_CAT_STEB_1_JUMP_DOWN",					},
		{ STATE_CHANGE_TYPE["SCT_AI_DOWN_DIR"],				"RAINCOAT_CAT_STEB_1_JUMP_DOWN_DIR",				},
	},

}

RAINCOAT_CAT_STEB_1_DASH =
{
	ANIM_NAME					= "Dash",
	PLAY_TYPE					= XSKIN_ANIM_PLAYTYPE["XAP_LOOP"],
	TRANSITION					= TRUE,

	CAN_PUSH_UNIT				= TRUE,
	CAN_PASS_UNIT				= FALSE,


	MOVE_TYPE           = 2,
	PASSIVE_SPEED_X_BY_USER			= 1.4,

	ALLOW_DIR_CHANGE			= TRUE,
	IMMADIATE_PACKET_SEND		= TRUE,

	EVENT_INTERVAL_TIME0		= 1,

	EVENT_PROCESS =
	{
		{ STATE_CHANGE_TYPE["SCT_FOOT_ON_LINE_FALSE_DOWN"],	"RAINCOAT_CAT_STEB_1_JUMP_DOWN_DIR",				},

		{ STATE_CHANGE_TYPE["SCT_CONDITION_FUNCTION"],      "RAINCOAT_CAT_STEB_1_ATTACK",						"CF_PETATTACK_RAINCOAT_CAT_STEB_1"    },

		{ STATE_CHANGE_TYPE["SCT_AI_WAIT"],					"RAINCOAT_CAT_STEB_1_DASH_END",							},
		{ STATE_CHANGE_TYPE["SCT_AI_WALK"],					"RAINCOAT_CAT_STEB_1_WALK",							},
		{ STATE_CHANGE_TYPE["SCT_AI_JUMP"],					"RAINCOAT_CAT_STEB_1_JUMP_UP",						},
		{ STATE_CHANGE_TYPE["SCT_AI_JUMP_DIR"],				"RAINCOAT_CAT_STEB_1_JUMP_UP_DIR",					},
		{ STATE_CHANGE_TYPE["SCT_AI_DOWN"],					"RAINCOAT_CAT_STEB_1_JUMP_DOWN",					},
		{ STATE_CHANGE_TYPE["SCT_AI_DOWN_DIR"],				"RAINCOAT_CAT_STEB_1_JUMP_DOWN_DIR",				},
	},
	
	TALK_BOX_1 =
	{
		{ RATE = 7, MESSAGE = STR_ID_27077  },
		{ RATE = 7, MESSAGE = STR_ID_27078  },
		{ RATE = 7, MESSAGE = STR_ID_27079  },
	},
	TALK_BOX_2 =
	{
		{ RATE = 7, MESSAGE = STR_ID_27080  },
		{ RATE = 7, MESSAGE = STR_ID_27081  },
		{ RATE = 7, MESSAGE = STR_ID_27082  },
	},
	TALK_BOX =
	{
		{ RATE = 7, MESSAGE = STR_ID_27083  },
		{ RATE = 7, MESSAGE = STR_ID_27084  },
		{ RATE = 7, MESSAGE = STR_ID_27085  },
	},


}

RAINCOAT_CAT_STEB_1_DASH_END =
{
	ANIM_NAME					= "DashEnd",
	PLAY_TYPE					= XSKIN_ANIM_PLAYTYPE["XAP_ONE_WAIT"],
	TRANSITION					= FALSE,

	CAN_PUSH_UNIT				= TRUE,
	CAN_PASS_UNIT				= FALSE,

	SPEED_X				= 700,

	SOUND_PLAY0					= { 0.237, "Pet_RAINCOAT_CAT_Special_DashEnd.ogg" },

	ALLOW_DIR_CHANGE			= TRUE,
	IMMADIATE_PACKET_SEND		= TRUE,

	EVENT_PROCESS =
	{
		{ STATE_CHANGE_TYPE["SCT_FOOT_ON_LINE_FALSE_DOWN"],	"RAINCOAT_CAT_STEB_1_JUMP_DOWN_DIR",				},

		{ STATE_CHANGE_TYPE["SCT_MOTION_END"],				"RAINCOAT_CAT_STEB_1_WAIT",							},

		{ STATE_CHANGE_TYPE["SCT_AI_WAIT"],					"RAINCOAT_CAT_STEB_1_WAIT",							},
		{ STATE_CHANGE_TYPE["SCT_AI_WALK"],					"RAINCOAT_CAT_STEB_1_WALK",							},
		{ STATE_CHANGE_TYPE["SCT_AI_JUMP"],					"RAINCOAT_CAT_STEB_1_JUMP_UP",						},
		{ STATE_CHANGE_TYPE["SCT_AI_JUMP_DIR"],				"RAINCOAT_CAT_STEB_1_JUMP_UP_DIR",					},
		{ STATE_CHANGE_TYPE["SCT_AI_DOWN"],					"RAINCOAT_CAT_STEB_1_JUMP_DOWN",					},
		{ STATE_CHANGE_TYPE["SCT_AI_DOWN_DIR"],				"RAINCOAT_CAT_STEB_1_JUMP_DOWN_DIR",				},
	},
}


RAINCOAT_CAT_STEB_1_JUMP_UP =
{
	ANIM_NAME					= "JumpUp",
	PLAY_TYPE					= XSKIN_ANIM_PLAYTYPE["XAP_LOOP"],
	TRANSITION					= TRUE,
	LAND_CONNECT				= FALSE,

	CAN_PUSH_UNIT				= TRUE,
	CAN_PASS_UNIT				= FALSE,

	MOVE_TYPE           = 3,
	SPEED_Y_BY_USER			= 1,
	ADD_POS_Y					= 45,

	IMMADIATE_PACKET_SEND		= TRUE,

	EVENT_PROCESS =
	{

		{ STATE_CHANGE_TYPE["SCT_NEGATIVE_Y_SPEED"],		"RAINCOAT_CAT_STEB_1_JUMP_DOWN",				},
	},


}

RAINCOAT_CAT_STEB_1_JUMP_DOWN =
{
	ANIM_NAME					= "JumpDown",
	PLAY_TYPE					= XSKIN_ANIM_PLAYTYPE["XAP_LOOP"],
	TRANSITION					= TRUE,
	LAND_CONNECT				= FALSE,

	CAN_PUSH_UNIT				= TRUE,
	CAN_PASS_UNIT				= FALSE,



	IMMADIATE_PACKET_SEND		= TRUE,

	EVENT_PROCESS =
	{
		{ STATE_CHANGE_TYPE["SCT_FOOT_ON_LINE_TRUE"],		"RAINCOAT_CAT_STEB_1_JUMP_LANDING",				},
	},
}

RAINCOAT_CAT_STEB_1_JUMP_UP_DIR =
{
	ANIM_NAME					= "JumpUp",
	PLAY_TYPE					= XSKIN_ANIM_PLAYTYPE["XAP_LOOP"],
	TRANSITION					= TRUE,
	LAND_CONNECT				= FALSE,

	CAN_PUSH_UNIT				= TRUE,
	CAN_PASS_UNIT				= FALSE,

	MOVE_TYPE           = 4,
	PASSIVE_SPEED_X_BY_USER = 1.2,
	SPEED_Y_BY_USER			= 1,
	ADD_POS_Y					= 45,

	IMMADIATE_PACKET_SEND		= TRUE,

	EVENT_PROCESS =
	{

		{ STATE_CHANGE_TYPE["SCT_NEGATIVE_Y_SPEED"],		"RAINCOAT_CAT_STEB_1_JUMP_DOWN_DIR",				},
	},


}

RAINCOAT_CAT_STEB_1_JUMP_DOWN_DIR =
{
	ANIM_NAME					= "JumpDown",
	PLAY_TYPE					= XSKIN_ANIM_PLAYTYPE["XAP_LOOP"],
	TRANSITION					= TRUE,
	LAND_CONNECT				= FALSE,

	CAN_PUSH_UNIT				= TRUE,
	CAN_PASS_UNIT				= FALSE,


	MOVE_TYPE           = 1,
	PASSIVE_SPEED_X_BY_USER = 1,

	IMMADIATE_PACKET_SEND		= TRUE,

	EVENT_PROCESS =
	{
		{ STATE_CHANGE_TYPE["SCT_FOOT_ON_LINE_TRUE"],		"RAINCOAT_CAT_STEB_1_JUMP_LANDING",				},
	},
}

RAINCOAT_CAT_STEB_1_JUMP_LANDING =
{
	ANIM_NAME					= "JumpDownLanding",
	PLAY_TYPE					= XSKIN_ANIM_PLAYTYPE["XAP_ONE_WAIT"],
	TRANSITION					= TRUE,
	LAND_CONNECT				= FALSE,

	CAN_PUSH_UNIT				= TRUE,
	CAN_PASS_UNIT				= FALSE,

	SOUND_PLAY0					= { 0.093, "JumpLand.ogg" },

	MOVE_TYPE = 0,

	IMMADIATE_PACKET_SEND		= TRUE,

	EVENT_PROCESS =
	{
		{ STATE_CHANGE_TYPE["SCT_FOOT_ON_LINE_FALSE_DOWN"],	"RAINCOAT_CAT_STEB_1_JUMP_DOWN",				},
		{ STATE_CHANGE_TYPE["SCT_MOTION_END"],				"RAINCOAT_CAT_STEB_1_WAIT",					},
	},

}



RAINCOAT_CAT_STEB_1_WAIT_HABIT =
{
	ANIM_NAME					= "WaitHabit",
	PLAY_TYPE					= XSKIN_ANIM_PLAYTYPE["XAP_ONE_WAIT"],
	TRANSITION					= TRUE,

	MOVE_TYPE           = 0,
	
	SOUND_PLAY0					= { 1.155, "Pet_RAINCOAT_CAT_Habit.ogg" },

	CAN_PUSH_UNIT				= TRUE,
	CAN_PASS_UNIT				= FALSE,
	IMMADIATE_PACKET_SEND		= TRUE,

	ALLOW_DIR_CHANGE			= FALSE,

	EVENT_PROCESS =
	{
		{ STATE_CHANGE_TYPE["SCT_FOOT_ON_LINE_FALSE_DOWN"],	"RAINCOAT_CAT_STEB_1_JUMP_DOWN",					},
		{ STATE_CHANGE_TYPE["SCT_MOTION_END"],				"RAINCOAT_CAT_STEB_1_WAIT",						},
	},

	TALK_BOX_1 =
	{
		{ RATE = 7, MESSAGE = STR_ID_27091  },
		{ RATE = 7, MESSAGE = STR_ID_27092  },
		{ RATE = 7, MESSAGE = STR_ID_27093  },
	},
	TALK_BOX_2 =
	{
		{ RATE = 7, MESSAGE = STR_ID_27091  },
		{ RATE = 7, MESSAGE = STR_ID_27092  },
		{ RATE = 7, MESSAGE = STR_ID_27093  },
	},
	TALK_BOX =
	{
		{ RATE = 7, MESSAGE = STR_ID_27091  },
		{ RATE = 7, MESSAGE = STR_ID_27094  },
		{ RATE = 7, MESSAGE = STR_ID_27093  },
	},
}

RAINCOAT_CAT_STEB_1_EAT =
{
	ANIM_NAME					= "Eat",
	PLAY_TYPE					= XSKIN_ANIM_PLAYTYPE["XAP_ONE_WAIT"],
	TRANSITION					= TRUE,

	MOVE_TYPE           = 0,
	
	SOUND_PLAY0					= { 0.9, "Pet_Eat01.ogg" },


	IMMADIATE_PACKET_SEND		= TRUE,

		ALLOW_DIR_CHANGE			= FALSE,

	EVENT_PROCESS =
	{
		{ STATE_CHANGE_TYPE["SCT_FOOT_ON_LINE_FALSE_DOWN"],	"RAINCOAT_CAT_STEB_1_JUMP_DOWN",					},
		{ STATE_CHANGE_TYPE["SCT_MOTION_END"],				"RAINCOAT_CAT_STEB_1_WAIT",						},
	},

	TALK_BOX_1 =
	{
		{ RATE = 34, MESSAGE = STR_ID_27095,   },
		{ RATE = 33, MESSAGE = STR_ID_27096,   },
		{ RATE = 33, MESSAGE = STR_ID_27097,   },
	},
	TALK_BOX_2 =
	{
		{ RATE = 34, MESSAGE = STR_ID_27104,   },
		{ RATE = 33, MESSAGE = STR_ID_27099,   },
		{ RATE = 33, MESSAGE = STR_ID_27100,   },
	},
	TALK_BOX =
	{
		{ RATE = 34, MESSAGE = STR_ID_27101,   },
		{ RATE = 33, MESSAGE = STR_ID_27102,   },
		{ RATE = 33, MESSAGE = STR_ID_27103,   },
	},
}

RAINCOAT_CAT_STEB_1_HUNGRY =
{
	ANIM_NAME					= "Hungry",
	PLAY_TYPE					= XSKIN_ANIM_PLAYTYPE["XAP_ONE_WAIT"],
	TRANSITION					= TRUE,

	MOVE_TYPE           = 0,

	SOUND_PLAY0					= { 0.031, "Pet_Hungry.ogg" },

	IMMADIATE_PACKET_SEND		= TRUE,

		ALLOW_DIR_CHANGE			= FALSE,

	EVENT_PROCESS =
	{
		{ STATE_CHANGE_TYPE["SCT_FOOT_ON_LINE_FALSE_DOWN"],	"RAINCOAT_CAT_STEB_1_JUMP_DOWN",					},
		{ STATE_CHANGE_TYPE["SCT_MOTION_END"],				"RAINCOAT_CAT_STEB_1_WAIT",						},
	},

	TALK_BOX_1 =
	{
		{ RATE = 34, MESSAGE = STR_ID_27109 },
		{ RATE = 33, MESSAGE = STR_ID_27110 },
		{ RATE = 33, MESSAGE = STR_ID_27111 },
	},
	TALK_BOX_2 =
	{
		{ RATE = 34, MESSAGE = STR_ID_27112 },
		{ RATE = 33, MESSAGE = STR_ID_27113 },
		{ RATE = 33, MESSAGE = STR_ID_27114 },
	},
	TALK_BOX =
	{
		{ RATE = 34, MESSAGE = STR_ID_27115 },
		{ RATE = 33, MESSAGE = STR_ID_27116 },
		{ RATE = 33, MESSAGE = STR_ID_27117 },
	},
}


RAINCOAT_CAT_STEB_1_STUFFED =
{
	ANIM_NAME					= "Stuffed",
	PLAY_TYPE					= XSKIN_ANIM_PLAYTYPE["XAP_ONE_WAIT"],
	TRANSITION					= TRUE,

	MOVE_TYPE           = 0,

	SOUND_PLAY0					= { 0.442, "Pet_Stuffed.ogg" },

	IMMADIATE_PACKET_SEND		= TRUE,

		ALLOW_DIR_CHANGE			= FALSE,

	EVENT_PROCESS =
	{
		{ STATE_CHANGE_TYPE["SCT_FOOT_ON_LINE_FALSE_DOWN"],	"RAINCOAT_CAT_STEB_1_JUMP_DOWN",					},
		{ STATE_CHANGE_TYPE["SCT_MOTION_END"],				"RAINCOAT_CAT_STEB_1_WAIT",						},
	},

	TALK_BOX_1 =
	{
		{ RATE = 34, MESSAGE = STR_ID_27120 },
		{ RATE = 33, MESSAGE = STR_ID_27121 },
		{ RATE = 33, MESSAGE = STR_ID_27122 },
	},
	TALK_BOX_2 =
	{
		{ RATE = 34, MESSAGE = STR_ID_27123 },
		{ RATE = 33, MESSAGE = STR_ID_27124 },
		{ RATE = 33, MESSAGE = STR_ID_27125 },
	},
	TALK_BOX =
	{
		{ RATE = 34, MESSAGE = STR_ID_27126 },
		{ RATE = 33, MESSAGE = STR_ID_27127 },
		{ RATE = 33, MESSAGE = STR_ID_27128 },
	},
}
---sleep 할 차례임
RAINCOAT_CAT_STEB_1_SLEEP_START =
{
	ANIM_NAME					= "Sleep",
	PLAY_TYPE					= XSKIN_ANIM_PLAYTYPE["XAP_ONE_WAIT"],
	TRANSITION					= TRUE,

	MOVE_TYPE           = 0,


	IMMADIATE_PACKET_SEND		= TRUE,

		ALLOW_DIR_CHANGE			= FALSE,

	EVENT_PROCESS =
	{
		{ STATE_CHANGE_TYPE["SCT_FOOT_ON_LINE_FALSE_DOWN"],	"RAINCOAT_CAT_STEB_1_JUMP_DOWN",					},
		{ STATE_CHANGE_TYPE["SCT_MOTION_END"],				"RAINCOAT_CAT_STEB_1_SLEEP_LOOP",						},
	},
	TALK_BOX_1 =
	{
		{ RATE = 34, MESSAGE = STR_ID_27129,   },
		{ RATE = 33, MESSAGE = STR_ID_27130,   },
		{ RATE = 33, MESSAGE = STR_ID_27131,   },
	},
	TALK_BOX_2 =
	{
		{ RATE = 34, MESSAGE = STR_ID_27132,   },
		{ RATE = 33, MESSAGE = STR_ID_27133,   },
		{ RATE = 33, MESSAGE = STR_ID_27134,   },
	},
	TALK_BOX =
	{
		{ RATE = 34, MESSAGE = STR_ID_27135,   },
		{ RATE = 33, MESSAGE = STR_ID_27136,   },
		{ RATE = 33, MESSAGE = STR_ID_27137,   },
	},
}

RAINCOAT_CAT_STEB_1_SLEEP_LOOP =
{
	ANIM_NAME					= "SleepLoop",
	PLAY_TYPE					= XSKIN_ANIM_PLAYTYPE["XAP_LOOP"],
	TRANSITION					= TRUE,

	MOVE_TYPE           = 0,
	
	SOUND_PLAY0					= { 0.001, "Pet_RAINCOAT_CAT_Special_SleepLoop.ogg" },

	IMMADIATE_PACKET_SEND		= TRUE,

		ALLOW_DIR_CHANGE			= FALSE,

	EVENT_PROCESS =
	{
		{ STATE_CHANGE_TYPE["SCT_FOOT_ON_LINE_FALSE_DOWN"],	"RAINCOAT_CAT_STEB_1_JUMP_DOWN",					},
	},
}

RAINCOAT_CAT_STEB_1_SLEEP_END =
{
	ANIM_NAME					= "SleepEnd",
	PLAY_TYPE					= XSKIN_ANIM_PLAYTYPE["XAP_ONE_WAIT"],
	TRANSITION					= TRUE,

	MOVE_TYPE           = 0,


	IMMADIATE_PACKET_SEND		= TRUE,

	ALLOW_DIR_CHANGE			= FALSE,

	EVENT_PROCESS =
	{
		{ STATE_CHANGE_TYPE["SCT_FOOT_ON_LINE_FALSE_DOWN"],	"RAINCOAT_CAT_STEB_1_JUMP_DOWN",					},
		{ STATE_CHANGE_TYPE["SCT_MOTION_END"],				"RAINCOAT_CAT_STEB_1_WAIT",						},
	},

	TALK_BOX_1 =
	{
		{ RATE = 34, MESSAGE = STR_ID_27138,   },
		{ RATE = 33, MESSAGE = STR_ID_27139,   },
		{ RATE = 33, MESSAGE = STR_ID_27140,   },
	},
	TALK_BOX_2 =
	{
		{ RATE = 34, MESSAGE = STR_ID_27141,   },
		{ RATE = 33, MESSAGE = STR_ID_27142,   },
		{ RATE = 33, MESSAGE = STR_ID_27143,   },
	},
	TALK_BOX =
	{
		{ RATE = 34, MESSAGE = STR_ID_27144,   },
		{ RATE = 33, MESSAGE = STR_ID_27145,   },
		{ RATE = 33, MESSAGE = STR_ID_27146,   },
	},

}

RAINCOAT_CAT_STEB_1_AFRAID =
{
	ANIM_NAME					= "Afraid",
	PLAY_TYPE					= XSKIN_ANIM_PLAYTYPE["XAP_ONE_WAIT"],
	TRANSITION					= TRUE,

	MOVE_TYPE           = 0,


	IMMADIATE_PACKET_SEND		= TRUE,

	ALLOW_DIR_CHANGE			= FALSE,

	EVENT_PROCESS =
	{
		{ STATE_CHANGE_TYPE["SCT_FOOT_ON_LINE_FALSE_DOWN"],	"RAINCOAT_CAT_STEB_1_JUMP_DOWN",					},
		{ STATE_CHANGE_TYPE["SCT_MOTION_END"],				"RAINCOAT_CAT_STEB_1_WAIT",						},
	},

	TALK_BOX_1 =
	{
		{ RATE = 34, MESSAGE = STR_ID_27147,  },
		{ RATE = 33, MESSAGE = STR_ID_27093,  },
		{ RATE = 33, MESSAGE = STR_ID_27149,  },
	},
	TALK_BOX_2 =
	{
		{ RATE = 34, MESSAGE = STR_ID_27150,  },
		{ RATE = 33, MESSAGE = STR_ID_27151,  },
		{ RATE = 33, MESSAGE = STR_ID_27152,  },
	},
	TALK_BOX =
	{
		{ RATE = 34, MESSAGE = STR_ID_27153,  },
		{ RATE = 33, MESSAGE = STR_ID_27154,  },
		{ RATE = 33, MESSAGE = STR_ID_27155,  },
	},
}

RAINCOAT_CAT_STEB_1_HELLO =
{
	ANIM_NAME					= "Hello",
	PLAY_TYPE					= XSKIN_ANIM_PLAYTYPE["XAP_ONE_WAIT"],
	TRANSITION					= TRUE,

	MOVE_TYPE           = 0,

	SOUND_PLAY0					= { 0.425, "Pet_RAINCOAT_CAT_Special_Hello.ogg" },

	IMMADIATE_PACKET_SEND		= TRUE,

	ALLOW_DIR_CHANGE			= FALSE,

	EVENT_PROCESS =
	{
		{ STATE_CHANGE_TYPE["SCT_FOOT_ON_LINE_FALSE_DOWN"],	"RAINCOAT_CAT_STEB_1_JUMP_DOWN",					},
		{ STATE_CHANGE_TYPE["SCT_MOTION_END"],				"RAINCOAT_CAT_STEB_1_WAIT",						},
	},

	TALK_BOX_1 =
	{
		{ RATE = 34, MESSAGE = STR_ID_27143,  },
		{ RATE = 33, MESSAGE = STR_ID_27158,  },
		{ RATE = 33, MESSAGE = STR_ID_27159,  },
	},
	TALK_BOX_2 =
	{
		{ RATE = 34, MESSAGE = STR_ID_27160,  },
		{ RATE = 33, MESSAGE = STR_ID_27161,  },
		{ RATE = 33, MESSAGE = STR_ID_27162,  },
	},
	TALK_BOX =
	{
		{ RATE = 34, MESSAGE = STR_ID_27163,  },
		{ RATE = 33, MESSAGE = STR_ID_27164,  },
		{ RATE = 33, MESSAGE = STR_ID_27165,  },
	},
}

RAINCOAT_CAT_STEB_1_HAPPY1 =
{
	ANIM_NAME					= "Cute1",
	PLAY_TYPE					= XSKIN_ANIM_PLAYTYPE["XAP_ONE_WAIT"],
	TRANSITION					= TRUE,

	MOVE_TYPE           = 0,

	SOUND_PLAY0					= { 2.477, "Pet_RAINCOAT_CAT_Special_Cute1.ogg" },

	IMMADIATE_PACKET_SEND		= TRUE,

	ALLOW_DIR_CHANGE			= FALSE,

	EVENT_PROCESS =
	{
		{ STATE_CHANGE_TYPE["SCT_FOOT_ON_LINE_FALSE_DOWN"],	"RAINCOAT_CAT_STEB_1_JUMP_DOWN",					},
		{ STATE_CHANGE_TYPE["SCT_MOTION_END"],				"RAINCOAT_CAT_STEB_1_WAIT",						},
	},

	TALK_BOX_1 =
	{
		{ RATE = 34, MESSAGE = STR_ID_27166,  },
		{ RATE = 33, MESSAGE = STR_ID_27143,  },
		{ RATE = 33, MESSAGE = STR_ID_27167,  },
	},
	TALK_BOX_2 =
	{
		{ RATE = 34, MESSAGE = STR_ID_27168,  },
		{ RATE = 33, MESSAGE = STR_ID_27158,  },
		{ RATE = 33, MESSAGE = STR_ID_27169,  },
	},
	TALK_BOX =
	{
		{ RATE = 34, MESSAGE = STR_ID_27170,  },
		{ RATE = 33, MESSAGE = STR_ID_27171,  },
		{ RATE = 33, MESSAGE = STR_ID_27172,  },
	},
}

RAINCOAT_CAT_STEB_1_HAPPY2 =
{
	ANIM_NAME					= "Cute2",
	PLAY_TYPE					= XSKIN_ANIM_PLAYTYPE["XAP_ONE_WAIT"],
	TRANSITION					= TRUE,

	MOVE_TYPE           = 0,

	SOUND_PLAY0					= { 0.001, "Pet_RAINCOAT_CAT_Special_Cute2.ogg" },

	IMMADIATE_PACKET_SEND		= TRUE,

	ALLOW_DIR_CHANGE			= FALSE,

	EVENT_PROCESS =
	{
		{ STATE_CHANGE_TYPE["SCT_FOOT_ON_LINE_FALSE_DOWN"],	"RAINCOAT_CAT_STEB_1_JUMP_DOWN",					},
		{ STATE_CHANGE_TYPE["SCT_MOTION_END"],				"RAINCOAT_CAT_STEB_1_WAIT",						},
	},

	TALK_BOX_1 =
	{
		{ RATE = 34, MESSAGE = STR_ID_27166,  },
		{ RATE = 33, MESSAGE = STR_ID_27143,  },
		{ RATE = 33, MESSAGE = STR_ID_27167,  },
	},
	TALK_BOX_2 =
	{
		{ RATE = 34, MESSAGE = STR_ID_27168,  },
		{ RATE = 33, MESSAGE = STR_ID_27158,  },
		{ RATE = 33, MESSAGE = STR_ID_27169,  },
	},
	TALK_BOX =
	{
		{ RATE = 34, MESSAGE = STR_ID_27170,  },
		{ RATE = 33, MESSAGE = STR_ID_27171,  },
		{ RATE = 33, MESSAGE = STR_ID_27172,  },
	},
}

RAINCOAT_CAT_STEB_1_CUTE1 =
{
	ANIM_NAME					= "Cute1",
	PLAY_TYPE					= XSKIN_ANIM_PLAYTYPE["XAP_ONE_WAIT"],
	TRANSITION					= TRUE,

	MOVE_TYPE           = 0,

	SOUND_PLAY0					= { 2.477, "Pet_RAINCOAT_CAT_Special_Cute1.ogg" },

	IMMADIATE_PACKET_SEND		= TRUE,

	ALLOW_DIR_CHANGE			= FALSE,

	EVENT_PROCESS =
	{
		{ STATE_CHANGE_TYPE["SCT_FOOT_ON_LINE_FALSE_DOWN"],	"RAINCOAT_CAT_STEB_1_JUMP_DOWN",					},
		{ STATE_CHANGE_TYPE["SCT_MOTION_END"],				"RAINCOAT_CAT_STEB_1_WAIT",						},
	},

	TALK_BOX_1 =
	{
		{ RATE = 34, MESSAGE = STR_ID_27175,  },
		{ RATE = 33, MESSAGE = STR_ID_27175,  },
		{ RATE = 33, MESSAGE = STR_ID_27176,  },
	},
	TALK_BOX_2 =
	{
		{ RATE = 34, MESSAGE = STR_ID_27177,  },
		{ RATE = 33, MESSAGE = STR_ID_27178,  },
		{ RATE = 33, MESSAGE = STR_ID_27179,  },
	},
	TALK_BOX =
	{
		{ RATE = 34, MESSAGE = STR_ID_27180,  },
		{ RATE = 33, MESSAGE = STR_ID_27181,  },
		{ RATE = 33, MESSAGE = STR_ID_27182,  },
	},

}

RAINCOAT_CAT_STEB_1_CUTE2 =
{
	ANIM_NAME					= "Cute2",
	PLAY_TYPE					= XSKIN_ANIM_PLAYTYPE["XAP_ONE_WAIT"],
	TRANSITION					= TRUE,

	MOVE_TYPE           = 0,

	SOUND_PLAY0					= { 0.001, "Pet_RAINCOAT_CAT_Special_Cute2.ogg" },

	IMMADIATE_PACKET_SEND		= TRUE,

	ALLOW_DIR_CHANGE			= FALSE,

	EVENT_PROCESS =
	{
		{ STATE_CHANGE_TYPE["SCT_FOOT_ON_LINE_FALSE_DOWN"],	"RAINCOAT_CAT_STEB_1_JUMP_DOWN",					},
		{ STATE_CHANGE_TYPE["SCT_MOTION_END"],				"RAINCOAT_CAT_STEB_1_WAIT",						},
	},

	TALK_BOX_1 =
	{
		{ RATE = 34, MESSAGE = STR_ID_27175,  },
		{ RATE = 33, MESSAGE = STR_ID_27175,  },
		{ RATE = 33, MESSAGE = STR_ID_27176,  },
	},
	TALK_BOX_2 =
	{
		{ RATE = 34, MESSAGE = STR_ID_27177,  },
		{ RATE = 33, MESSAGE = STR_ID_27178,  },
		{ RATE = 33, MESSAGE = STR_ID_27179,  },
	},
	TALK_BOX =
	{
		{ RATE = 34, MESSAGE = STR_ID_27180,  },
		{ RATE = 33, MESSAGE = STR_ID_27181,  },
		{ RATE = 33, MESSAGE = STR_ID_27182,  },
	},
}

RAINCOAT_CAT_STEB_1_SAD =
{
	ANIM_NAME					= "Afraid",
	PLAY_TYPE					= XSKIN_ANIM_PLAYTYPE["XAP_ONE_WAIT"],
	TRANSITION					= TRUE,

	MOVE_TYPE           = 0,


	IMMADIATE_PACKET_SEND		= TRUE,

	ALLOW_DIR_CHANGE			= FALSE,

	EVENT_PROCESS =
	{
		{ STATE_CHANGE_TYPE["SCT_FOOT_ON_LINE_FALSE_DOWN"],	"RAINCOAT_CAT_STEB_1_JUMP_DOWN",					},
		{ STATE_CHANGE_TYPE["SCT_MOTION_END"],				"RAINCOAT_CAT_STEB_1_WAIT",						},
	},

	TALK_BOX_1 =
	{
		{ RATE = 34, MESSAGE = STR_ID_27186,  },
		{ RATE = 33, MESSAGE = STR_ID_27187,  },
		{ RATE = 33, MESSAGE = STR_ID_27188,  },
	},
	TALK_BOX_2 =
	{
		{ RATE = 34, MESSAGE = STR_ID_27189,  },
		{ RATE = 33, MESSAGE = STR_ID_27190,  },
		{ RATE = 33, MESSAGE = STR_ID_27191,  },
	},
	TALK_BOX =
	{
		{ RATE = 34, MESSAGE = STR_ID_27192,  },
		{ RATE = 33, MESSAGE = STR_ID_27193,  },
		{ RATE = 33, MESSAGE = STR_ID_27194,  },
	},

}

RAINCOAT_CAT_STEB_1_CHEER =
{
	ANIM_NAME					= "Cheer",
	PLAY_TYPE					= XSKIN_ANIM_PLAYTYPE["XAP_ONE_WAIT"],
	TRANSITION					= TRUE,

	MOVE_TYPE           = 0,

	SOUND_PLAY0					= { 0.005, "Pet_Cheer_Common.ogg" },


	IMMADIATE_PACKET_SEND		= TRUE,

	ALLOW_DIR_CHANGE			= FALSE,

	EVENT_PROCESS =
	{
		{ STATE_CHANGE_TYPE["SCT_FOOT_ON_LINE_FALSE_DOWN"],	"RAINCOAT_CAT_STEB_1_JUMP_DOWN",					},
		{ STATE_CHANGE_TYPE["SCT_MOTION_END"],				"RAINCOAT_CAT_STEB_1_WAIT",						},
	},

	TALK_BOX_1 =
	{
		{ RATE = 33, MESSAGE = STR_ID_27197 },
		{ RATE = 34, MESSAGE = STR_ID_27198 },
		{ RATE = 33, MESSAGE = STR_ID_27199 },
	},
	TALK_BOX_2 =
	{
		{ RATE = 33, MESSAGE = STR_ID_27200 },
		{ RATE = 34, MESSAGE = STR_ID_27201 },
		{ RATE = 33, MESSAGE = STR_ID_27202 },
	},
	TALK_BOX =
	{
		{ RATE = 33, MESSAGE = STR_ID_27203 },
		{ RATE = 34, MESSAGE = STR_ID_27204 },
		{ RATE = 33, MESSAGE = STR_ID_27205 },
	},
}

RAINCOAT_CAT_STEB_1_SPECIAL =
{
	ANIM_NAME					= "Special_A",
	PLAY_TYPE					= XSKIN_ANIM_PLAYTYPE["XAP_ONE_WAIT"],
	TRANSITION					= TRUE,

	MOVE_TYPE           = 0,

	SOUND_PLAY0					= { 1.724, "Pet_RAINCOAT_CAT_Special.ogg" },

	IMMADIATE_PACKET_SEND		= TRUE,

	ALLOW_DIR_CHANGE			= FALSE,

	EVENT_PROCESS =
	{
		{ STATE_CHANGE_TYPE["SCT_FOOT_ON_LINE_FALSE_DOWN"],	"RAINCOAT_CAT_STEB_1_JUMP_DOWN",					},
		{ STATE_CHANGE_TYPE["SCT_MOTION_END"],				"RAINCOAT_CAT_STEB_1_WAIT",						},
	},

	TALK_BOX_1 =
	{
		{ RATE = 34, MESSAGE = STR_ID_27208 },
		{ RATE = 33, MESSAGE = STR_ID_27209 },
		{ RATE = 33, MESSAGE = STR_ID_27143 },
	},
	TALK_BOX_2 =
	{
		{ RATE = 34, MESSAGE = STR_ID_27210 },
		{ RATE = 33, MESSAGE = STR_ID_27211 },
		{ RATE = 33, MESSAGE = STR_ID_27212 },
	},
	TALK_BOX =
	{
		{ RATE = 34, MESSAGE = STR_ID_27213 },
		{ RATE = 33, MESSAGE = STR_ID_27214 },
		{ RATE = 33, MESSAGE = STR_ID_27215 },
	},
}


RAINCOAT_CAT_STEB_1_ATTACK =
{
	ANIM_NAME					= "Attack_A",
	PLAY_TYPE					= XSKIN_ANIM_PLAYTYPE["XAP_ONE_WAIT"],
	TRANSITION					= TRUE,

	MOVE_TYPE           = 0,
	VIEW_TARGET			= TRUE,

	SOUND_PLAY0					= { 0.125+SOUND_FIX_TIME, "Pet_RAINCOAT_CAT_Special_Attack_A.ogg" },


	IMMADIATE_PACKET_SEND		= TRUE,

	EVENT_PROCESS =
	{
		{ STATE_CHANGE_TYPE["SCT_FOOT_ON_LINE_FALSE_DOWN"],	"RAINCOAT_CAT_STEB_1_JUMP_DOWN",					},
		{ STATE_CHANGE_TYPE["SCT_MOTION_END"],				"RAINCOAT_CAT_STEB_1_WAIT",						},
	},

	TALK_BOX_1 =
	{
		{ RATE = 34, MESSAGE = STR_ID_27216 },
		{ RATE = 33, MESSAGE = STR_ID_27217 },
		{ RATE = 33, MESSAGE = STR_ID_27218 },
	},
	TALK_BOX_2 =
	{
		{ RATE = 34, MESSAGE = STR_ID_27219 },
		{ RATE = 33, MESSAGE = STR_ID_27220 },
		{ RATE = 33, MESSAGE = STR_ID_27221 },
	},
	TALK_BOX =
	{
		{ RATE = 34, MESSAGE = STR_ID_27222 },
		{ RATE = 33, MESSAGE = STR_ID_27223 },
		{ RATE = 33, MESSAGE = STR_ID_27224 },
	},
}


RAINCOAT_CAT_STEB_1_SIT_START =
{
	ANIM_NAME					= "SitReady",
	PLAY_TYPE					= XSKIN_ANIM_PLAYTYPE["XAP_ONE_WAIT"],
	TRANSITION					= TRUE,

	MOVE_TYPE           = 0,


	IMMADIATE_PACKET_SEND		= TRUE,

	ALLOW_DIR_CHANGE			= FALSE,

	EVENT_PROCESS =
	{
		{ STATE_CHANGE_TYPE["SCT_FOOT_ON_LINE_FALSE_DOWN"],	"RAINCOAT_CAT_STEB_1_JUMP_DOWN",					},
		{ STATE_CHANGE_TYPE["SCT_MOTION_END"],				"RAINCOAT_CAT_STEB_1_SIT_LOOP",						},
	},

	TALK_BOX_1 =
	{
		{ RATE = 33, MESSAGE = STR_ID_27234,  },
		{ RATE = 33, MESSAGE = STR_ID_27234,  },
		{ RATE = 34, MESSAGE = STR_ID_27234,  },
	},
	TALK_BOX_2 =
	{
		{ RATE = 33, MESSAGE = STR_ID_27234,  },
		{ RATE = 33, MESSAGE = STR_ID_27234,  },
		{ RATE = 34, MESSAGE = STR_ID_27234,  },
	},
	TALK_BOX =
	{
		{ RATE = 33, MESSAGE = STR_ID_27234,  },
		{ RATE = 33, MESSAGE = STR_ID_27234,  },
		{ RATE = 34, MESSAGE = STR_ID_27234,  },
	},
}

RAINCOAT_CAT_STEB_1_SIT_LOOP =
{
	ANIM_NAME					= "Sit",
	PLAY_TYPE					= XSKIN_ANIM_PLAYTYPE["XAP_LOOP"],
	TRANSITION					= TRUE,

	MOVE_TYPE           = 0,


	IMMADIATE_PACKET_SEND		= TRUE,

	ALLOW_DIR_CHANGE			= FALSE,

	EVENT_PROCESS =
	{
		{ STATE_CHANGE_TYPE["SCT_FOOT_ON_LINE_FALSE_DOWN"],	"RAINCOAT_CAT_STEB_1_JUMP_DOWN",					},
	},
}

RAINCOAT_CAT_STEB_1_SIT_END =
{
	ANIM_NAME					= "SitEnd",
	PLAY_TYPE					= XSKIN_ANIM_PLAYTYPE["XAP_ONE_WAIT"],
	TRANSITION					= TRUE,

	MOVE_TYPE           = 0,


	IMMADIATE_PACKET_SEND		= TRUE,

	ALLOW_DIR_CHANGE			= FALSE,

	EVENT_PROCESS =
	{
		{ STATE_CHANGE_TYPE["SCT_FOOT_ON_LINE_FALSE_DOWN"],	"RAINCOAT_CAT_STEB_1_JUMP_DOWN",					},
		{ STATE_CHANGE_TYPE["SCT_MOTION_END"],				"RAINCOAT_CAT_STEB_1_WAIT",						},
	},

	TALK_BOX_1 =
	{
		{ RATE = 33, MESSAGE = STR_ID_27236,   },
		{ RATE = 33, MESSAGE = STR_ID_27236,   },
		{ RATE = 34, MESSAGE = STR_ID_27236,   },
	},
	TALK_BOX_2 =
	{
		{ RATE = 33, MESSAGE = STR_ID_27236,   },
		{ RATE = 33, MESSAGE = STR_ID_27236,   },
		{ RATE = 34, MESSAGE = STR_ID_27236,   },
	},
	TALK_BOX =
	{
		{ RATE = 33, MESSAGE = STR_ID_27236,   },
		{ RATE = 33, MESSAGE = STR_ID_27236,   },
		{ RATE = 34, MESSAGE = STR_ID_27236,   },
	},
}

RAINCOAT_CAT_STEB_1_NOTKNOW =
{
	ANIM_NAME					= "DoNotKnow",
	PLAY_TYPE					= XSKIN_ANIM_PLAYTYPE["XAP_ONE_WAIT"],
	TRANSITION					= TRUE,

	MOVE_TYPE           = 0,


	IMMADIATE_PACKET_SEND		= TRUE,

	ALLOW_DIR_CHANGE			= FALSE,

	EVENT_PROCESS =
	{
		{ STATE_CHANGE_TYPE["SCT_FOOT_ON_LINE_FALSE_DOWN"],	"RAINCOAT_CAT_STEB_1_JUMP_DOWN",					},
		{ STATE_CHANGE_TYPE["SCT_MOTION_END"],				"RAINCOAT_CAT_STEB_1_WAIT",						},
	},

	-- TALK_BOX_1 =
 	-- {
		-- { RATE = 20, MESSAGE = STR_ID_5600,   },
		-- { RATE = 20, MESSAGE = STR_ID_5601,   },
		-- { RATE = 20, MESSAGE = STR_ID_5602,   },
		-- { RATE = 20, MESSAGE = STR_ID_5603,   },
		-- { RATE = 20, MESSAGE = STR_ID_5604,   },
	-- },
	-- TALK_BOX_2 =
 	-- {
		-- { RATE = 20, MESSAGE = STR_ID_5600,   },
		-- { RATE = 20, MESSAGE = STR_ID_5601,   },
		-- { RATE = 20, MESSAGE = STR_ID_5602,   },
		-- { RATE = 20, MESSAGE = STR_ID_5603,   },
		-- { RATE = 20, MESSAGE = STR_ID_5604,   },
	-- },
	-- TALK_BOX =
 	-- {
		-- { RATE = 20, MESSAGE = STR_ID_5600,   },
		-- { RATE = 20, MESSAGE = STR_ID_5601,   },
		-- { RATE = 20, MESSAGE = STR_ID_5602,   },
		-- { RATE = 20, MESSAGE = STR_ID_5603,   },
		-- { RATE = 20, MESSAGE = STR_ID_5604,   },
	-- },
}





function RAINCOAT_CAT_STEB_1_ATTACK_FRAME_MOVE( pKTDXApp, pX2Game, pPet )

	if pPet:AnimEventTimer( 1.1 ) then
		RainCoatCatPandemonium( pKTDXApp, pX2Game, pPet )
	end	
	
end

function CF_PETATTACK_RAINCOAT_CAT_STEB_1( pKTDXApp, pX2Game, pPet )

	if pX2Game ~= nil then
		if pX2Game:IsHost() == false then
			return false
		end
	end

	if pPet:IsAttacking() == true then

		local fDist = pPet:GetDistTarget()
		if fDist <= 300 then
			return true
		end
	end

	return false
	
end

-- 고양이 판데모니움
function RainCoatCatPandemonium( pKTDXApp, pX2Game, pPet )
	local pEffectSet = pX2Game:GetEffectSet()
	local pDamageEffect = pX2Game:GetDamageEffect()
	
	if pEffectSet ~= nil and pDamageEffect ~= nil then
		local vLandPos = pPet:GetLandPosition_LUA()
		local vPos = pPet:GetBonePos_LUA("Bip01_Head")
		local vRot = pPet:GetRotateDegree()
				
		local pMasterUnit = pPet:GetMaster()
		if pMasterUnit ~= nil and pMasterUnit:GetNowHP() > 0 then
			pEffectSet:PlayEffectSetByPet_LUA( "EffectSet_PET_RAINCOAT_CAT_YELLOW_ATTACK_A", pPet )
			pDamageEffect:CreateInstanceByPet_LUA( pMasterUnit, "DAMAGE_EFFECT_RAINCOAT_CAT_STEB1_ATTACK_A", vPos, vLandPos, vRot )
		end
	end
end

function RAINCOAT_CAT_STEB_1_CHEER_FRAME_MOVE( pKTDXApp, pX2Game, pPet )
	
	if pPet:AnimEventTimer( 1.4 ) then
		ShotRightForCheer_White01( pKTDXApp, pX2Game, pPet )
	end
	if pPet:AnimEventTimer( 1.6 ) then
		ShotLeftForCheer_White01( pKTDXApp, pX2Game, pPet )
	end	
	if pPet:AnimEventTimer( 1.93 ) then
		ShotRightForCheer_White01( pKTDXApp, pX2Game, pPet )
	end	

	if pPet:AnimEventTimer( 2.2 ) then
		ShotLeftForCheer_White01( pKTDXApp, pX2Game, pPet )
	end	
	if pPet:AnimEventTimer( 2.47 ) then
		ShotRightForCheer_White01( pKTDXApp, pX2Game, pPet )
	end
	if pPet:AnimEventTimer( 2.72 ) then
		ShotLeftForCheer_White01( pKTDXApp, pX2Game, pPet )
	end
end

-- 격려용 총 쏘는 함수
function ShotRightForCheer_White01( pKTDXApp, pX2Game, pPet )
	local pMajorParticle = pX2Game:GetMajorParticle()

	if pMajorParticle ~= nil then
		local vPos = pPet:GetBonePos_LUA("Dummy02")

		local pMasterUnit = pPet:GetMaster()
		if pMasterUnit ~= nil and pMasterUnit:GetNowHP() > 0 then
			pMajorParticle:CreateSequence_LUA( "Pet_Sheriff_Norm_Step1_Attack02", vPos, D3DXVECTOR2(1000,1000), D3DXVECTOR2(1,1) )
		end
	end
end

function ShotLeftForCheer_White01( pKTDXApp, pX2Game, pPet )
	local pMajorParticle = pX2Game:GetMajorParticle()

	if pMajorParticle ~= nil then
		local vPos = pPet:GetBonePos_LUA("Dummy01")

		local pMasterUnit = pPet:GetMaster()
		if pMasterUnit ~= nil and pMasterUnit:GetNowHP() > 0 then
			pMajorParticle:CreateSequence_LUA( "Pet_Sheriff_Norm_Step1_Attack02", vPos, D3DXVECTOR2(1000,1000), D3DXVECTOR2(1,1) )
		end
	end
end