-- lua header. UTF-8 인코딩 인식을 위해 이 줄은 지우지 마세요.


INIT_SYSTEM =
{
	UNIT_LAYER		= X2_LAYER["XL_UNIT_0"],
	UNIT_SCALE		= 1.2,

	CULL_MODE     = TRUE,
	
	RENDER_PARAM = RENDER_TYPE["RT_REAL_COLOR"],
	--CARTOON_TEX_TYPE = CARTOON_TEX_TYPE["CTT_NORMAL"],
	NOT_CHANGE_COLOR = TRUE,
	ALPHA_BLEND   = TRUE,	
	SRC_BLEND = D3DBLEND["D3DBLEND_SRCCOLOR"],
	DEST_BLEND = D3DBLEND["D3DBLEND_SRCCOLOR"],
	--PET_COLOR_A = 255,
	--PET_COLOR_R = 255,
	--PET_COLOR_G = 255,
	--PET_COLOR_B = 255,
}


INIT_DEVICE =
{
	READY_XSKIN_MESH =
	{
		"Raven_RRF_Ground_Impact_AttackBox01.X",
	},

	READY_TEXTURE =
	{
		"Fire_Smoke01.tga",
	},

	READY_SOUND =
	{
     "Pet_DashEnd.ogg",
	 "Pet_Hungry.ogg",
	 "Pet_Stuffed.ogg",
	 "Pet_AncientPporu_Attack3.ogg",
     "Pet_Cheer_Common.ogg",
     "Pet_AncientPporu_Cheer3.ogg",
     "Pet_AncientPporu_Cute2_2.ogg",
     "Pet_AncientPporu_Cute1_2.ogg",
     "Pet_AncientPporu_Special2.ogg",
     "Pet_AncientPporu_Hello.ogg",
     "Pet_AncientPporu_Cheer2.ogg",
	},
}

INIT_MOTION =
{
	MOTION_FILE_NAME		= "Motion_PETIT_ANCIENT_HALLOW_DARK.x",	
	MOTION_ANI_TEX_XET		= "PETIT_ANCIENT_HALLOW_DARK_EYE.xet",	
}


INIT_COMPONENT =
{
	MAX_HP				= 6000,
	MP_CHANGE_RATE		= 1,
	MP_CHARGE_RATE		= 130,


	SHADOW_SIZE			= 200,
	SHADOW_FILE_NAME	= "shadow.dds",

	SMALL_HP_BAR_BLUE	= "Small_HP_bar_Blue.TGA",
	SMALL_HP_BAR_RED	= "Small_HP_bar_Red.TGA",
	SMALL_HP_BAR_YELLOW = "Small_HP_bar_Yellow.TGA",

	QUESTION_MARK_SEQ		= "QuestionMarkNPC",
	EXCLAMATION_MARK_SEQ	= "ExclamationMarkNPC",

	HYPER_MODE_COUNT	= 0,
	MAX_HYPER_MODE_TIME	= 30,

	HITTED_TYPE			= HITTED_TYPE["HTD_MEAT"],

	FALL_DOWN			= TRUE,



}

INIT_STATE =
{

	{ STATE_NAME = "ANCIENT_PPORU_HALLOW_DARK_SUMMON",			LUA_STATE_START_FUNC = "ANCIENT_PPORU_HALLOW_DARK_SUMMON_START", },
	{ STATE_NAME = "ANCIENT_PPORU_HALLOW_DARK_WAIT_HABIT",		STATE_COOL_TIME = 20, },
	{ STATE_NAME = "ANCIENT_PPORU_HALLOW_DARK_WAIT",						},
	{ STATE_NAME = "ANCIENT_PPORU_HALLOW_DARK_WALK",						},
	{ STATE_NAME = "ANCIENT_PPORU_HALLOW_DARK_DASH",						},
	{ STATE_NAME = "ANCIENT_PPORU_HALLOW_DARK_DASH_END",					},
	{ STATE_NAME = "ANCIENT_PPORU_HALLOW_DARK_JUMP_UP",					},
	{ STATE_NAME = "ANCIENT_PPORU_HALLOW_DARK_JUMP_DOWN",				},
	{ STATE_NAME = "ANCIENT_PPORU_HALLOW_DARK_JUMP_UP_DIR",				},
	{ STATE_NAME = "ANCIENT_PPORU_HALLOW_DARK_JUMP_DOWN_DIR",			},
	{ STATE_NAME = "ANCIENT_PPORU_HALLOW_DARK_JUMP_LANDING",				},
	{ STATE_NAME = "ANCIENT_PPORU_HALLOW_DARK_EAT",				},
	{ STATE_NAME = "ANCIENT_PPORU_HALLOW_DARK_HUNGRY",				},
	{ STATE_NAME = "ANCIENT_PPORU_HALLOW_DARK_STUFFED",				},
	{ STATE_NAME = "ANCIENT_PPORU_HALLOW_DARK_SLEEP_START",				},
	{ STATE_NAME = "ANCIENT_PPORU_HALLOW_DARK_SLEEP_LOOP",				},
	{ STATE_NAME = "ANCIENT_PPORU_HALLOW_DARK_SLEEP_END",				},
	{ STATE_NAME = "ANCIENT_PPORU_HALLOW_DARK_AFRAID",				STATE_COOL_TIME = 10, },
	{ STATE_NAME = "ANCIENT_PPORU_HALLOW_DARK_HELLO",				},
	{ STATE_NAME = "ANCIENT_PPORU_HALLOW_DARK_HAPPY1",				},
	{ STATE_NAME = "ANCIENT_PPORU_HALLOW_DARK_HAPPY2",				},
  { STATE_NAME = "ANCIENT_PPORU_HALLOW_DARK_CUTE1",				STATE_COOL_TIME = 10, },
  { STATE_NAME = "ANCIENT_PPORU_HALLOW_DARK_CUTE2",				STATE_COOL_TIME = 10, },
  { STATE_NAME = "ANCIENT_PPORU_HALLOW_DARK_SAD",				},
  { STATE_NAME = "ANCIENT_PPORU_HALLOW_DARK_CHEER",			STATE_COOL_TIME = 180,	},
  { STATE_NAME = "ANCIENT_PPORU_HALLOW_DARK_SPECIAL",				},
  { STATE_NAME = "ANCIENT_PPORU_HALLOW_DARK_ATTACK",			LUA_FRAME_MOVE_FUNC = "ANCIENT_PPORU_HALLOW_DARK_ATTACK_FRAME_MOVE",	},
  { STATE_NAME = "ANCIENT_PPORU_HALLOW_DARK_SIT_START",				},
  { STATE_NAME = "ANCIENT_PPORU_HALLOW_DARK_SIT_LOOP",				},
  { STATE_NAME = "ANCIENT_PPORU_HALLOW_DARK_SIT_END",				},
  { STATE_NAME = "ANCIENT_PPORU_HALLOW_DARK_NOTKNOW",				},

  START_STATE					= "ANCIENT_PPORU_HALLOW_DARK_SUMMON",
  WAIT_HABIT					= "ANCIENT_PPORU_HALLOW_DARK_WAIT_HABIT",
	WAIT_STATE					= "ANCIENT_PPORU_HALLOW_DARK_WAIT",
	EAT_STATE           = "ANCIENT_PPORU_HALLOW_DARK_EAT",
	HUNGRY_STATE       = "ANCIENT_PPORU_HALLOW_DARK_HUNGRY",
	STUFFED_STATE       = "ANCIENT_PPORU_HALLOW_DARK_STUFFED",
	SLEEP_START_STATE   = "ANCIENT_PPORU_HALLOW_DARK_SLEEP_START",
	SLEEP_LOOP_STATE   = "ANCIENT_PPORU_HALLOW_DARK_SLEEP_LOOP",
  SLEEP_END_STATE     = "ANCIENT_PPORU_HALLOW_DARK_SLEEP_END",
  AFRAID_STATE        = "ANCIENT_PPORU_HALLOW_DARK_AFRAID",
  HELLO_STATE         = "ANCIENT_PPORU_HALLOW_DARK_HELLO",
  HAPPY1_STATE         = "ANCIENT_PPORU_HALLOW_DARK_HAPPY1",
  HAPPY2_STATE         = "ANCIENT_PPORU_HALLOW_DARK_HAPPY2",
  CUTE1_STATE          = "ANCIENT_PPORU_HALLOW_DARK_CUTE1",
  CUTE2_STATE          = "ANCIENT_PPORU_HALLOW_DARK_CUTE2",
  SAD_STATE           = "ANCIENT_PPORU_HALLOW_DARK_SAD",
  CHEER_STATE         = "ANCIENT_PPORU_HALLOW_DARK_CHEER",
  SPECIAL_STATE       = "ANCIENT_PPORU_HALLOW_DARK_SPECIAL",
  ATTACK_STATE      = "ANCIENT_PPORU_HALLOW_DARK_ATTACK",
  SIT_START_STATE     = "ANCIENT_PPORU_HALLOW_DARK_SIT_START",
  SIT_LOOP_STATE     = "ANCIENT_PPORU_HALLOW_DARK_SIT_LOOP",
  SIT_END_STATE       = "ANCIENT_PPORU_HALLOW_DARK_SIT_END",
  NOTKNOW_STATE       = "ANCIENT_PPORU_HALLOW_DARK_NOTKNOW",
}

INIT_AI =
{
	TARGET =
	{
		TARGET_PRIORITY 			= TARGET_PRIORITY["TP_LOW_HP_FIRST"],
		TARGET_INTERVAL				= 0.5,		-- sec
		TARGET_NEAR_RANGE			= 200,		-- 이 거리보다 가까우면 TARGET_SUCCESS_RATE에 관계없이 무조건 타게팅된다
		TARGET_RANGE				= 10000,		-- cm
		TARGET_LOST_RANGE			= 2000,	-- cm
		TARGET_SUCCESS_RATE			= 100,  --70,		-- %
		ATTACK_TARGET_RATE			= 100, -- 80,		-- 나를 공격한 유닛을 타게팅할 확률
		PRESERVE_LAST_TARGET_RATE	= 100, -- 80,		-- 이전에 타게팅된 유닛을 계속 타게팅할 확률
	},

	CHASE_MOVE =
	{
		MOVE_SPLIT_RANGE	= 100,
		DEST_GAP			= 200,	-- 목적지에서 이 거리 안에 있으면 도착했다고 판단한다
		MOVE_GAP			= 100,
		RUN_GAP				= 500,

		DIR_CHANGE_INTERVAL = 0.3,

		WALK_INTERVAL		= 1,
		NEAR_WALK_RATE		= 100,   --  70,
		FAR_WALK_RATE		= 100,   -- 30,

		JUMP_INTERVAL		= 0,
		UP_JUMP_RATE		= 0, -- 40,
		UP_DOWN_RATE		= 0,
		DOWN_JUMP_RATE		= 0,    --  20,
		DOWN_DOWN_RATE		= 0,
	},

}

ANCIENT_PPORU_HALLOW_DARK_SUMMON =
{
	ANIM_NAME					= "Wait",
	PLAY_TYPE					= XSKIN_ANIM_PLAYTYPE["XAP_ONE_WAIT"],
	TRANSITION					= TRUE,

	MOVE_TYPE           = 0,

	CAN_PUSH_UNIT				= TRUE,
	CAN_PASS_UNIT				= FALSE,
	IMMADIATE_PACKET_SEND		= TRUE,

	ALLOW_DIR_CHANGE			= FALSE,

	EVENT_PROCESS =
	{
		{ STATE_CHANGE_TYPE["SCT_FOOT_ON_LINE_FALSE_DOWN"],	"ANCIENT_PPORU_HALLOW_DARK_JUMP_DOWN",					},
		{ STATE_CHANGE_TYPE["SCT_MOTION_END"],				"ANCIENT_PPORU_HALLOW_DARK_WAIT",						},
	},
}

ANCIENT_PPORU_HALLOW_DARK_WAIT =
{
	ANIM_NAME					= "Wait",
	PLAY_TYPE					= XSKIN_ANIM_PLAYTYPE["XAP_LOOP"],
	TRANSITION					= TRUE,

	MOVE_TYPE           = 0,

	IMMADIATE_PACKET_SEND		= TRUE,
	EVENT_INTERVAL_TIME0		= 2,

	EVENT_PROCESS =
	{
		{ STATE_CHANGE_TYPE["SCT_FOOT_ON_LINE_FALSE_DOWN"],	"ANCIENT_PPORU_HALLOW_DARK_JUMP_DOWN",					},

		{ STATE_CHANGE_TYPE["SCT_CONDITION_FUNCTION"],      "ANCIENT_PPORU_HALLOW_DARK_ATTACK",						"CF_PETATTACK_ANCIENT_PPORU_3"    },

		{ STATE_CHANGE_TYPE["SCT_AI_DIR_CHANGE"],			"ANCIENT_PPORU_HALLOW_DARK_WALK",						},

		{ STATE_CHANGE_TYPE["SCT_AI_WALK"],					"ANCIENT_PPORU_HALLOW_DARK_WALK",						},
		{ STATE_CHANGE_TYPE["SCT_AI_DASH"],					"ANCIENT_PPORU_HALLOW_DARK_DASH",						},
		{ STATE_CHANGE_TYPE["SCT_AI_JUMP"],					"ANCIENT_PPORU_HALLOW_DARK_JUMP_UP",						},
		{ STATE_CHANGE_TYPE["SCT_AI_JUMP_DIR"],				"ANCIENT_PPORU_HALLOW_DARK_JUMP_UP_DIR",					},
		{ STATE_CHANGE_TYPE["SCT_AI_DOWN"],					"ANCIENT_PPORU_HALLOW_DARK_JUMP_DOWN",					},
		{ STATE_CHANGE_TYPE["SCT_AI_DOWN_DIR"],				"ANCIENT_PPORU_HALLOW_DARK_JUMP_DOWN_DIR",				},
	},



}


ANCIENT_PPORU_HALLOW_DARK_WALK =
{
	ANIM_NAME					= "Walk",
	PLAY_TYPE					= XSKIN_ANIM_PLAYTYPE["XAP_LOOP"],
	TRANSITION					= TRUE,

	CAN_PUSH_UNIT				= TRUE,
	CAN_PASS_UNIT				= FALSE,

	MOVE_TYPE           = 1,
	PASSIVE_SPEED_X_BY_USER			= 1.2,

	IMMADIATE_PACKET_SEND		= TRUE,

	EVENT_INTERVAL_TIME0		= 2,

	EVENT_PROCESS =
	{
		{ STATE_CHANGE_TYPE["SCT_FOOT_ON_LINE_FALSE_DOWN"],	"ANCIENT_PPORU_HALLOW_DARK_JUMP_DOWN_DIR",				},

		{ STATE_CHANGE_TYPE["SCT_CONDITION_FUNCTION"],      "ANCIENT_PPORU_HALLOW_DARK_ATTACK",						"CF_PETATTACK_ANCIENT_PPORU_3"    },

		{ STATE_CHANGE_TYPE["SCT_AI_WAIT"],					"ANCIENT_PPORU_HALLOW_DARK_WAIT",						},
		{ STATE_CHANGE_TYPE["SCT_AI_DASH"],					"ANCIENT_PPORU_HALLOW_DARK_DASH",						},

		{ STATE_CHANGE_TYPE["SCT_AI_JUMP"],					"ANCIENT_PPORU_HALLOW_DARK_JUMP_UP",						},
		{ STATE_CHANGE_TYPE["SCT_AI_JUMP_DIR"],				"ANCIENT_PPORU_HALLOW_DARK_JUMP_UP_DIR",					},
		{ STATE_CHANGE_TYPE["SCT_AI_DOWN"],					"ANCIENT_PPORU_HALLOW_DARK_JUMP_DOWN",					},
		{ STATE_CHANGE_TYPE["SCT_AI_DOWN_DIR"],				"ANCIENT_PPORU_HALLOW_DARK_JUMP_DOWN_DIR",				},
	},

}

ANCIENT_PPORU_HALLOW_DARK_DASH =
{
	ANIM_NAME					= "Dash",
	PLAY_TYPE					= XSKIN_ANIM_PLAYTYPE["XAP_LOOP"],
	TRANSITION					= TRUE,

	CAN_PUSH_UNIT				= TRUE,
	CAN_PASS_UNIT				= FALSE,


	MOVE_TYPE           = 2,
	PASSIVE_SPEED_X_BY_USER			= 1.4,

	ALLOW_DIR_CHANGE			= TRUE,
	IMMADIATE_PACKET_SEND		= TRUE,

	EVENT_INTERVAL_TIME0		= 1,

	EVENT_PROCESS =
	{
		{ STATE_CHANGE_TYPE["SCT_FOOT_ON_LINE_FALSE_DOWN"],	"ANCIENT_PPORU_HALLOW_DARK_JUMP_DOWN_DIR",				},

		{ STATE_CHANGE_TYPE["SCT_CONDITION_FUNCTION"],      "ANCIENT_PPORU_HALLOW_DARK_ATTACK",						"CF_PETATTACK_ANCIENT_PPORU_3"    },

		{ STATE_CHANGE_TYPE["SCT_AI_WAIT"],					"ANCIENT_PPORU_HALLOW_DARK_DASH_END",							},
		{ STATE_CHANGE_TYPE["SCT_AI_WALK"],					"ANCIENT_PPORU_HALLOW_DARK_WALK",							},
		{ STATE_CHANGE_TYPE["SCT_AI_JUMP"],					"ANCIENT_PPORU_HALLOW_DARK_JUMP_UP",						},
		{ STATE_CHANGE_TYPE["SCT_AI_JUMP_DIR"],				"ANCIENT_PPORU_HALLOW_DARK_JUMP_UP_DIR",					},
		{ STATE_CHANGE_TYPE["SCT_AI_DOWN"],					"ANCIENT_PPORU_HALLOW_DARK_JUMP_DOWN",					},
		{ STATE_CHANGE_TYPE["SCT_AI_DOWN_DIR"],				"ANCIENT_PPORU_HALLOW_DARK_JUMP_DOWN_DIR",				},
	},
	
	TALK_BOX_1 =
	{
		{ RATE = 7, MESSAGE = STR_ID_14624 },
		{ RATE = 7, MESSAGE = STR_ID_14625 },
		{ RATE = 7, MESSAGE = STR_ID_14626 },
	},
	TALK_BOX_2 =
	{
		{ RATE = 7, MESSAGE = STR_ID_14627 },
		{ RATE = 7, MESSAGE = STR_ID_14628 },
		{ RATE = 7, MESSAGE = STR_ID_14629 },
	},
	TALK_BOX =
	{
		{ RATE = 7, MESSAGE = STR_ID_14630 },
		{ RATE = 7, MESSAGE = STR_ID_14631 },
		{ RATE = 7, MESSAGE = STR_ID_14632 },
	},
	
	
}

ANCIENT_PPORU_HALLOW_DARK_DASH_END =
{
	ANIM_NAME					= "DashEnd",
	PLAY_TYPE					= XSKIN_ANIM_PLAYTYPE["XAP_ONE_WAIT"],
	TRANSITION					= FALSE,

	CAN_PUSH_UNIT				= TRUE,
	CAN_PASS_UNIT				= FALSE,

	SPEED_X				= 700,

    SOUND_PLAY0					= { 0.021, "Pet_DashEnd.ogg" },

	ALLOW_DIR_CHANGE			= TRUE,
	IMMADIATE_PACKET_SEND		= TRUE,

	EVENT_PROCESS =
	{
		{ STATE_CHANGE_TYPE["SCT_FOOT_ON_LINE_FALSE_DOWN"],	"ANCIENT_PPORU_HALLOW_DARK_JUMP_DOWN_DIR",				},

		{ STATE_CHANGE_TYPE["SCT_MOTION_END"],				"ANCIENT_PPORU_HALLOW_DARK_WAIT",							},

		{ STATE_CHANGE_TYPE["SCT_AI_WAIT"],					"ANCIENT_PPORU_HALLOW_DARK_WAIT",							},
		{ STATE_CHANGE_TYPE["SCT_AI_WALK"],					"ANCIENT_PPORU_HALLOW_DARK_WALK",							},
		{ STATE_CHANGE_TYPE["SCT_AI_JUMP"],					"ANCIENT_PPORU_HALLOW_DARK_JUMP_UP",						},
		{ STATE_CHANGE_TYPE["SCT_AI_JUMP_DIR"],				"ANCIENT_PPORU_HALLOW_DARK_JUMP_UP_DIR",					},
		{ STATE_CHANGE_TYPE["SCT_AI_DOWN"],					"ANCIENT_PPORU_HALLOW_DARK_JUMP_DOWN",					},
		{ STATE_CHANGE_TYPE["SCT_AI_DOWN_DIR"],				"ANCIENT_PPORU_HALLOW_DARK_JUMP_DOWN_DIR",				},
	},
}


ANCIENT_PPORU_HALLOW_DARK_JUMP_UP =
{
	ANIM_NAME					= "JumpUp",
	PLAY_TYPE					= XSKIN_ANIM_PLAYTYPE["XAP_LOOP"],
	TRANSITION					= TRUE,
	LAND_CONNECT				= FALSE,

	CAN_PUSH_UNIT				= TRUE,
	CAN_PASS_UNIT				= FALSE,

	MOVE_TYPE           = 3,
	SPEED_Y_BY_USER			= 1,
	ADD_POS_Y					= 45,

	IMMADIATE_PACKET_SEND		= TRUE,

	EVENT_PROCESS =
	{

		{ STATE_CHANGE_TYPE["SCT_NEGATIVE_Y_SPEED"],		"ANCIENT_PPORU_HALLOW_DARK_JUMP_DOWN",				},
	},


}

ANCIENT_PPORU_HALLOW_DARK_JUMP_DOWN =
{
	ANIM_NAME					= "JumpDown",
	PLAY_TYPE					= XSKIN_ANIM_PLAYTYPE["XAP_LOOP"],
	TRANSITION					= TRUE,
	LAND_CONNECT				= FALSE,

	CAN_PUSH_UNIT				= TRUE,
	CAN_PASS_UNIT				= FALSE,



	IMMADIATE_PACKET_SEND		= TRUE,

	EVENT_PROCESS =
	{
		{ STATE_CHANGE_TYPE["SCT_FOOT_ON_LINE_TRUE"],		"ANCIENT_PPORU_HALLOW_DARK_JUMP_LANDING",				},
	},
}

ANCIENT_PPORU_HALLOW_DARK_JUMP_UP_DIR =
{
	ANIM_NAME					= "JumpUp",
	PLAY_TYPE					= XSKIN_ANIM_PLAYTYPE["XAP_LOOP"],
	TRANSITION					= TRUE,
	LAND_CONNECT				= FALSE,

	CAN_PUSH_UNIT				= TRUE,
	CAN_PASS_UNIT				= FALSE,

	MOVE_TYPE           = 4,
	PASSIVE_SPEED_X_BY_USER = 1.2,
	SPEED_Y_BY_USER			= 1,
	ADD_POS_Y					= 45,

	IMMADIATE_PACKET_SEND		= TRUE,

	EVENT_PROCESS =
	{

		{ STATE_CHANGE_TYPE["SCT_NEGATIVE_Y_SPEED"],		"ANCIENT_PPORU_HALLOW_DARK_JUMP_DOWN_DIR",				},
	},


}

ANCIENT_PPORU_HALLOW_DARK_JUMP_DOWN_DIR =
{
	ANIM_NAME					= "JumpDown",
	PLAY_TYPE					= XSKIN_ANIM_PLAYTYPE["XAP_LOOP"],
	TRANSITION					= TRUE,
	LAND_CONNECT				= FALSE,

	CAN_PUSH_UNIT				= TRUE,
	CAN_PASS_UNIT				= FALSE,


	MOVE_TYPE           = 1,
	PASSIVE_SPEED_X_BY_USER = 1,

	IMMADIATE_PACKET_SEND		= TRUE,

	EVENT_PROCESS =
	{
		{ STATE_CHANGE_TYPE["SCT_FOOT_ON_LINE_TRUE"],		"ANCIENT_PPORU_HALLOW_DARK_JUMP_LANDING",				},
	},
}

ANCIENT_PPORU_HALLOW_DARK_JUMP_LANDING =
{
	ANIM_NAME					= "JumpDownLanding",
	PLAY_TYPE					= XSKIN_ANIM_PLAYTYPE["XAP_ONE_WAIT"],
	TRANSITION					= TRUE,
	LAND_CONNECT				= FALSE,

	CAN_PUSH_UNIT				= TRUE,
	CAN_PASS_UNIT				= FALSE,

	SOUND_PLAY0					= { 0.093, "JumpLand.ogg" },

	MOVE_TYPE = 0,

	IMMADIATE_PACKET_SEND		= TRUE,

	EVENT_PROCESS =
	{
		{ STATE_CHANGE_TYPE["SCT_FOOT_ON_LINE_FALSE_DOWN"],	"ANCIENT_PPORU_HALLOW_DARK_JUMP_DOWN",				},
		{ STATE_CHANGE_TYPE["SCT_MOTION_END"],				"ANCIENT_PPORU_HALLOW_DARK_WAIT",					},
	},
}



ANCIENT_PPORU_HALLOW_DARK_WAIT_HABIT =
{
	ANIM_NAME					= "WaitHabit",
	PLAY_TYPE					= XSKIN_ANIM_PLAYTYPE["XAP_ONE_WAIT"],
	TRANSITION					= TRUE,

	MOVE_TYPE           = 0,

	CAN_PUSH_UNIT				= TRUE,
	CAN_PASS_UNIT				= FALSE,
	IMMADIATE_PACKET_SEND		= TRUE,

	ALLOW_DIR_CHANGE			= FALSE,

	EVENT_PROCESS =
	{
		{ STATE_CHANGE_TYPE["SCT_FOOT_ON_LINE_FALSE_DOWN"],	"ANCIENT_PPORU_HALLOW_DARK_JUMP_DOWN",					},
		{ STATE_CHANGE_TYPE["SCT_MOTION_END"],				"ANCIENT_PPORU_HALLOW_DARK_WAIT",						},
	},

	TALK_BOX_1 =
	{
		{ RATE = 7, MESSAGE = STR_ID_14633 },
		{ RATE = 7, MESSAGE = STR_ID_14634 },
		{ RATE = 7, MESSAGE = STR_ID_14635 },
	},
	TALK_BOX_2 =
	{
		{ RATE = 7, MESSAGE = STR_ID_14636 },
		{ RATE = 7, MESSAGE = STR_ID_14637 },
		{ RATE = 7, MESSAGE = STR_ID_14638 },
	},
	TALK_BOX =
	{
		{ RATE = 7, MESSAGE = STR_ID_14639 },
		{ RATE = 7, MESSAGE = STR_ID_14640 },
		{ RATE = 7, MESSAGE = STR_ID_14641 },
	},
}

ANCIENT_PPORU_HALLOW_DARK_EAT =
{
	ANIM_NAME					= "Eat",
	PLAY_TYPE					= XSKIN_ANIM_PLAYTYPE["XAP_ONE_WAIT"],
	TRANSITION					= TRUE,

	MOVE_TYPE           = 0,


	IMMADIATE_PACKET_SEND		= TRUE,

		ALLOW_DIR_CHANGE			= FALSE,

	EVENT_PROCESS =
	{
		{ STATE_CHANGE_TYPE["SCT_FOOT_ON_LINE_FALSE_DOWN"],	"ANCIENT_PPORU_HALLOW_DARK_JUMP_DOWN",					},
		{ STATE_CHANGE_TYPE["SCT_MOTION_END"],				"ANCIENT_PPORU_HALLOW_DARK_WAIT",						},
	},

	TALK_BOX_1 =
	{
		{ RATE = 34, MESSAGE = STR_ID_14642, APPLY_INTIMACY = TRUE, },
		{ RATE = 33, MESSAGE = STR_ID_14643, APPLY_INTIMACY = TRUE, },
		{ RATE = 33, MESSAGE = STR_ID_14644, APPLY_INTIMACY = TRUE, },
	},
	TALK_BOX_2 =
	{
		{ RATE = 34, MESSAGE = STR_ID_14645, APPLY_INTIMACY = TRUE, },
		{ RATE = 33, MESSAGE = STR_ID_14646, APPLY_INTIMACY = TRUE, },
		{ RATE = 33, MESSAGE = STR_ID_14647, APPLY_INTIMACY = TRUE, },
	},
	TALK_BOX =
	{
		{ RATE = 34, MESSAGE = STR_ID_14648, APPLY_INTIMACY = TRUE, },
		{ RATE = 33, MESSAGE = STR_ID_14649, APPLY_INTIMACY = TRUE, },
		{ RATE = 33, MESSAGE = STR_ID_14650, APPLY_INTIMACY = TRUE, },
	},
}

ANCIENT_PPORU_HALLOW_DARK_HUNGRY =
{
	ANIM_NAME					= "Hungry",
	PLAY_TYPE					= XSKIN_ANIM_PLAYTYPE["XAP_ONE_WAIT"],
	TRANSITION					= TRUE,

	MOVE_TYPE           = 0,

    SOUND_PLAY0					= { 0.021, "Pet_Hungry.ogg" },

	IMMADIATE_PACKET_SEND		= TRUE,

		ALLOW_DIR_CHANGE			= FALSE,

	EVENT_PROCESS =
	{
		{ STATE_CHANGE_TYPE["SCT_FOOT_ON_LINE_FALSE_DOWN"],	"ANCIENT_PPORU_HALLOW_DARK_JUMP_DOWN",					},
		{ STATE_CHANGE_TYPE["SCT_MOTION_END"],				"ANCIENT_PPORU_HALLOW_DARK_WAIT",						},
	},

	TALK_BOX_1 =
	{
		{ RATE = 34, MESSAGE = STR_ID_14651 },
		{ RATE = 33, MESSAGE = STR_ID_14652 },
		{ RATE = 33, MESSAGE = STR_ID_14653 },
	},
	TALK_BOX_2 =
	{
		{ RATE = 34, MESSAGE = STR_ID_14654 },
		{ RATE = 33, MESSAGE = STR_ID_14655 },
		{ RATE = 33, MESSAGE = STR_ID_14656 },
	},
	TALK_BOX =
	{
		{ RATE = 34, MESSAGE = STR_ID_14657 },
		{ RATE = 33, MESSAGE = STR_ID_14658 },
		{ RATE = 33, MESSAGE = STR_ID_14659 },
	},
}


ANCIENT_PPORU_HALLOW_DARK_STUFFED =
{
	ANIM_NAME					= "Stuffed",
	PLAY_TYPE					= XSKIN_ANIM_PLAYTYPE["XAP_ONE_WAIT"],
	TRANSITION					= TRUE,

	MOVE_TYPE           = 0,

    SOUND_PLAY0					= { 0.021, "Pet_Stuffed.ogg" },

	IMMADIATE_PACKET_SEND		= TRUE,

		ALLOW_DIR_CHANGE			= FALSE,

	EVENT_PROCESS =
	{
		{ STATE_CHANGE_TYPE["SCT_FOOT_ON_LINE_FALSE_DOWN"],	"ANCIENT_PPORU_HALLOW_DARK_JUMP_DOWN",					},
		{ STATE_CHANGE_TYPE["SCT_MOTION_END"],				"ANCIENT_PPORU_HALLOW_DARK_WAIT",						},
	},

	TALK_BOX_1 =
	{
		{ RATE = 34, MESSAGE = STR_ID_14660 },
		{ RATE = 33, MESSAGE = STR_ID_14661 },
		{ RATE = 33, MESSAGE = STR_ID_14662 },
	},
	TALK_BOX_2 =
	{
		{ RATE = 34, MESSAGE = STR_ID_14663 },
		{ RATE = 33, MESSAGE = STR_ID_14664 },
		{ RATE = 33, MESSAGE = STR_ID_14665 },
	},
	TALK_BOX =
	{
		{ RATE = 34, MESSAGE = STR_ID_14666 },
		{ RATE = 33, MESSAGE = STR_ID_14667 },
		{ RATE = 33, MESSAGE = STR_ID_14668 },
	},
}

ANCIENT_PPORU_HALLOW_DARK_SLEEP_START =
{
	ANIM_NAME					= "Sleep",
	PLAY_TYPE					= XSKIN_ANIM_PLAYTYPE["XAP_ONE_WAIT"],
	TRANSITION					= TRUE,

	MOVE_TYPE           = 0,


	IMMADIATE_PACKET_SEND		= TRUE,

		ALLOW_DIR_CHANGE			= FALSE,

	EVENT_PROCESS =
	{
		{ STATE_CHANGE_TYPE["SCT_FOOT_ON_LINE_FALSE_DOWN"],	"ANCIENT_PPORU_HALLOW_DARK_JUMP_DOWN",					},
		{ STATE_CHANGE_TYPE["SCT_MOTION_END"],				"ANCIENT_PPORU_HALLOW_DARK_SLEEP_LOOP",						},
	},

	TALK_BOX_1 =
	{
		{ RATE = 34, MESSAGE = STR_ID_14669, APPLY_INTIMACY = TRUE, },
		{ RATE = 33, MESSAGE = STR_ID_14670, APPLY_INTIMACY = TRUE, },
		{ RATE = 33, MESSAGE = STR_ID_14671, APPLY_INTIMACY = TRUE, },
	},
	TALK_BOX_2 =
	{
		{ RATE = 34, MESSAGE = STR_ID_14672, APPLY_INTIMACY = TRUE, },
		{ RATE = 33, MESSAGE = STR_ID_14673, APPLY_INTIMACY = TRUE, },
		{ RATE = 33, MESSAGE = STR_ID_14674, APPLY_INTIMACY = TRUE, },
	},
	TALK_BOX =
	{
		{ RATE = 34, MESSAGE = STR_ID_14675, APPLY_INTIMACY = TRUE, },
		{ RATE = 33, MESSAGE = STR_ID_14676, APPLY_INTIMACY = TRUE, },
		{ RATE = 33, MESSAGE = STR_ID_14677, APPLY_INTIMACY = TRUE, },
	},
}

ANCIENT_PPORU_HALLOW_DARK_SLEEP_LOOP =
{
	ANIM_NAME					= "SleepLoop",
	PLAY_TYPE					= XSKIN_ANIM_PLAYTYPE["XAP_LOOP"],
	TRANSITION					= TRUE,

	MOVE_TYPE           = 0,


	IMMADIATE_PACKET_SEND		= TRUE,

		ALLOW_DIR_CHANGE			= FALSE,

	EVENT_PROCESS =
	{
		{ STATE_CHANGE_TYPE["SCT_FOOT_ON_LINE_FALSE_DOWN"],	"ANCIENT_PPORU_HALLOW_DARK_JUMP_DOWN",					},
	},
}

ANCIENT_PPORU_HALLOW_DARK_SLEEP_END =
{
	ANIM_NAME					= "SleepEnd",
	PLAY_TYPE					= XSKIN_ANIM_PLAYTYPE["XAP_ONE_WAIT"],
	TRANSITION					= TRUE,

	MOVE_TYPE           = 0,


	IMMADIATE_PACKET_SEND		= TRUE,

	ALLOW_DIR_CHANGE			= FALSE,

	EVENT_PROCESS =
	{
		{ STATE_CHANGE_TYPE["SCT_FOOT_ON_LINE_FALSE_DOWN"],	"ANCIENT_PPORU_HALLOW_DARK_JUMP_DOWN",					},
		{ STATE_CHANGE_TYPE["SCT_MOTION_END"],				"ANCIENT_PPORU_HALLOW_DARK_WAIT",						},
	},

	TALK_BOX_1 =
	{
		{ RATE = 34, MESSAGE = STR_ID_14678, APPLY_INTIMACY = TRUE, },
		{ RATE = 33, MESSAGE = STR_ID_14679, APPLY_INTIMACY = TRUE, },
		{ RATE = 33, MESSAGE = STR_ID_14680, APPLY_INTIMACY = TRUE, },
	},
	TALK_BOX_2 =
	{
		{ RATE = 34, MESSAGE = STR_ID_14681, APPLY_INTIMACY = TRUE, },
		{ RATE = 33, MESSAGE = STR_ID_14682, APPLY_INTIMACY = TRUE, },
		{ RATE = 33, MESSAGE = STR_ID_14683, APPLY_INTIMACY = TRUE, },
	},
	TALK_BOX =
	{
		{ RATE = 34, MESSAGE = STR_ID_14684, APPLY_INTIMACY = TRUE, },
		{ RATE = 33, MESSAGE = STR_ID_14685, APPLY_INTIMACY = TRUE, },
		{ RATE = 33, MESSAGE = STR_ID_14686, APPLY_INTIMACY = TRUE, },
	},

}

ANCIENT_PPORU_HALLOW_DARK_AFRAID =
{
	ANIM_NAME					= "Afraid",
	PLAY_TYPE					= XSKIN_ANIM_PLAYTYPE["XAP_ONE_WAIT"],
	TRANSITION					= TRUE,

	MOVE_TYPE           = 0,


	IMMADIATE_PACKET_SEND		= TRUE,

	ALLOW_DIR_CHANGE			= FALSE,

	EVENT_PROCESS =
	{
		{ STATE_CHANGE_TYPE["SCT_FOOT_ON_LINE_FALSE_DOWN"],	"ANCIENT_PPORU_HALLOW_DARK_JUMP_DOWN",					},
		{ STATE_CHANGE_TYPE["SCT_MOTION_END"],				"ANCIENT_PPORU_HALLOW_DARK_WAIT",						},
	},

	TALK_BOX_1 =
	{
		{ RATE = 34, MESSAGE = STR_ID_14687, APPLY_INTIMACY = TRUE, },
		{ RATE = 33, MESSAGE = STR_ID_14688, APPLY_INTIMACY = TRUE, },
		{ RATE = 33, MESSAGE = STR_ID_14689, APPLY_INTIMACY = TRUE, },
	},
	TALK_BOX_2 =
	{
		{ RATE = 34, MESSAGE = STR_ID_14690, APPLY_INTIMACY = TRUE, },
		{ RATE = 33, MESSAGE = STR_ID_14691, APPLY_INTIMACY = TRUE, },
		{ RATE = 33, MESSAGE = STR_ID_14692, APPLY_INTIMACY = TRUE, },
	},
	TALK_BOX =
	{
		{ RATE = 34, MESSAGE = STR_ID_14693, APPLY_INTIMACY = TRUE, },
		{ RATE = 33, MESSAGE = STR_ID_14694, APPLY_INTIMACY = TRUE, },
		{ RATE = 33, MESSAGE = STR_ID_14695, APPLY_INTIMACY = TRUE, },
	},
}

ANCIENT_PPORU_HALLOW_DARK_HELLO =
{
	ANIM_NAME					= "Hello",
	PLAY_TYPE					= XSKIN_ANIM_PLAYTYPE["XAP_ONE_WAIT"],
	TRANSITION					= TRUE,

	MOVE_TYPE           = 0,

    SOUND_PLAY0					= { 0.456, "Pet_AncientPporu_Hello.ogg" },

	IMMADIATE_PACKET_SEND		= TRUE,

	ALLOW_DIR_CHANGE			= FALSE,

	EVENT_PROCESS =
	{
		{ STATE_CHANGE_TYPE["SCT_FOOT_ON_LINE_FALSE_DOWN"],	"ANCIENT_PPORU_HALLOW_DARK_JUMP_DOWN",					},
		{ STATE_CHANGE_TYPE["SCT_MOTION_END"],				"ANCIENT_PPORU_HALLOW_DARK_WAIT",						},
	},

	TALK_BOX_1 =
	{
		{ RATE = 34, MESSAGE = STR_ID_14696, APPLY_INTIMACY = TRUE, },
		{ RATE = 33, MESSAGE = STR_ID_14697, APPLY_INTIMACY = TRUE, },
		{ RATE = 33, MESSAGE = STR_ID_14698, APPLY_INTIMACY = TRUE, },
	},
	TALK_BOX_2 =
	{
		{ RATE = 34, MESSAGE = STR_ID_14699, APPLY_INTIMACY = TRUE, },
		{ RATE = 33, MESSAGE = STR_ID_14700, APPLY_INTIMACY = TRUE, },
		{ RATE = 33, MESSAGE = STR_ID_14701, APPLY_INTIMACY = TRUE, },
	},
	TALK_BOX =
	{
		{ RATE = 34, MESSAGE = STR_ID_14702, APPLY_INTIMACY = TRUE, },
		{ RATE = 33, MESSAGE = STR_ID_14703, APPLY_INTIMACY = TRUE, },
		{ RATE = 33, MESSAGE = STR_ID_14704, APPLY_INTIMACY = TRUE, },
	},
}

ANCIENT_PPORU_HALLOW_DARK_HAPPY1 =
{
	ANIM_NAME					= "Cute1",
	PLAY_TYPE					= XSKIN_ANIM_PLAYTYPE["XAP_ONE_WAIT"],
	TRANSITION					= TRUE,

	MOVE_TYPE           = 0,

    SOUND_PLAY0					= { 0.445, "Pet_AncientPporu_Cute1_2.ogg" },

	IMMADIATE_PACKET_SEND		= TRUE,

	ALLOW_DIR_CHANGE			= FALSE,

	EVENT_PROCESS =
	{
		{ STATE_CHANGE_TYPE["SCT_FOOT_ON_LINE_FALSE_DOWN"],	"ANCIENT_PPORU_HALLOW_DARK_JUMP_DOWN",					},
		{ STATE_CHANGE_TYPE["SCT_MOTION_END"],				"ANCIENT_PPORU_HALLOW_DARK_WAIT",						},
	},

	TALK_BOX_1 =
	{
		{ RATE = 34, MESSAGE = STR_ID_14705, APPLY_INTIMACY = TRUE, },
		{ RATE = 33, MESSAGE = STR_ID_14706, APPLY_INTIMACY = TRUE, },
		{ RATE = 33, MESSAGE = STR_ID_14707, APPLY_INTIMACY = TRUE, },
	},
	TALK_BOX_2 =
	{
		{ RATE = 34, MESSAGE = STR_ID_14708, APPLY_INTIMACY = TRUE, },
		{ RATE = 33, MESSAGE = STR_ID_14709, APPLY_INTIMACY = TRUE, },
		{ RATE = 33, MESSAGE = STR_ID_14710, APPLY_INTIMACY = TRUE, },
	},
	TALK_BOX =
	{
		{ RATE = 34, MESSAGE = STR_ID_14711, APPLY_INTIMACY = TRUE, },
		{ RATE = 33, MESSAGE = STR_ID_14712, APPLY_INTIMACY = TRUE, },
		{ RATE = 33, MESSAGE = STR_ID_14713, APPLY_INTIMACY = TRUE, },
	},
}

ANCIENT_PPORU_HALLOW_DARK_HAPPY2 =
{
	ANIM_NAME					= "Cute2",
	PLAY_TYPE					= XSKIN_ANIM_PLAYTYPE["XAP_ONE_WAIT"],
	TRANSITION					= TRUE,

	MOVE_TYPE           = 0,

    SOUND_PLAY0					= { 0.445, "Pet_AncientPporu_Cute2_2.ogg" },

	IMMADIATE_PACKET_SEND		= TRUE,

	ALLOW_DIR_CHANGE			= FALSE,

	EVENT_PROCESS =
	{
		{ STATE_CHANGE_TYPE["SCT_FOOT_ON_LINE_FALSE_DOWN"],	"ANCIENT_PPORU_HALLOW_DARK_JUMP_DOWN",					},
		{ STATE_CHANGE_TYPE["SCT_MOTION_END"],				"ANCIENT_PPORU_HALLOW_DARK_WAIT",						},
	},

	TALK_BOX_1 =
	{
		{ RATE = 34, MESSAGE = STR_ID_14705, APPLY_INTIMACY = TRUE, },
		{ RATE = 33, MESSAGE = STR_ID_14706, APPLY_INTIMACY = TRUE, },
		{ RATE = 33, MESSAGE = STR_ID_14707, APPLY_INTIMACY = TRUE, },
	},
	TALK_BOX_2 =
	{
		{ RATE = 34, MESSAGE = STR_ID_14708, APPLY_INTIMACY = TRUE, },
		{ RATE = 33, MESSAGE = STR_ID_14709, APPLY_INTIMACY = TRUE, },
		{ RATE = 33, MESSAGE = STR_ID_14710, APPLY_INTIMACY = TRUE, },
	},
	TALK_BOX =
	{
		{ RATE = 34, MESSAGE = STR_ID_14711, APPLY_INTIMACY = TRUE, },
		{ RATE = 33, MESSAGE = STR_ID_14712, APPLY_INTIMACY = TRUE, },
		{ RATE = 33, MESSAGE = STR_ID_14713, APPLY_INTIMACY = TRUE, },
	},
}

ANCIENT_PPORU_HALLOW_DARK_CUTE1 =
{
	ANIM_NAME					= "Cute1",
	PLAY_TYPE					= XSKIN_ANIM_PLAYTYPE["XAP_ONE_WAIT"],
	TRANSITION					= TRUE,

	MOVE_TYPE           = 0,

    SOUND_PLAY0					= { 0.445, "Pet_AncientPporu_Cute1_2.ogg" },

	IMMADIATE_PACKET_SEND		= TRUE,

	ALLOW_DIR_CHANGE			= FALSE,

	EVENT_PROCESS =
	{
		{ STATE_CHANGE_TYPE["SCT_FOOT_ON_LINE_FALSE_DOWN"],	"ANCIENT_PPORU_HALLOW_DARK_JUMP_DOWN",					},
		{ STATE_CHANGE_TYPE["SCT_MOTION_END"],				"ANCIENT_PPORU_HALLOW_DARK_WAIT",						},
	},

	TALK_BOX_1 =
	{
		{ RATE = 34, MESSAGE = STR_ID_14714, APPLY_INTIMACY = TRUE, },
		{ RATE = 33, MESSAGE = STR_ID_14715, APPLY_INTIMACY = TRUE, },
		{ RATE = 33, MESSAGE = STR_ID_14716, APPLY_INTIMACY = TRUE, },
	},
	TALK_BOX_2 =
	{
		{ RATE = 34, MESSAGE = STR_ID_14717, APPLY_INTIMACY = TRUE, },
		{ RATE = 33, MESSAGE = STR_ID_14718, APPLY_INTIMACY = TRUE, },
		{ RATE = 33, MESSAGE = STR_ID_14719, APPLY_INTIMACY = TRUE, },
	},
	TALK_BOX =
	{
		{ RATE = 34, MESSAGE = STR_ID_14720, APPLY_INTIMACY = TRUE, },
		{ RATE = 33, MESSAGE = STR_ID_14721, APPLY_INTIMACY = TRUE, },
		{ RATE = 33, MESSAGE = STR_ID_14722, APPLY_INTIMACY = TRUE, },
	},
}

ANCIENT_PPORU_HALLOW_DARK_CUTE2 =
{
	ANIM_NAME					= "Cute2",
	PLAY_TYPE					= XSKIN_ANIM_PLAYTYPE["XAP_ONE_WAIT"],
	TRANSITION					= TRUE,

	MOVE_TYPE           = 0,

    SOUND_PLAY0					= { 0.372, "Pet_AncientPporu_Cute2_2.ogg" },

	IMMADIATE_PACKET_SEND		= TRUE,

	ALLOW_DIR_CHANGE			= FALSE,

	EVENT_PROCESS =
	{
		{ STATE_CHANGE_TYPE["SCT_FOOT_ON_LINE_FALSE_DOWN"],	"ANCIENT_PPORU_HALLOW_DARK_JUMP_DOWN",					},
		{ STATE_CHANGE_TYPE["SCT_MOTION_END"],				"ANCIENT_PPORU_HALLOW_DARK_WAIT",						},
	},

	TALK_BOX_1 =
	{
		{ RATE = 34, MESSAGE = STR_ID_14723, APPLY_INTIMACY = TRUE, },
		{ RATE = 33, MESSAGE = STR_ID_14724, APPLY_INTIMACY = TRUE, },
		{ RATE = 33, MESSAGE = STR_ID_14725, APPLY_INTIMACY = TRUE, },
	},
	TALK_BOX_2 =
	{
		{ RATE = 34, MESSAGE = STR_ID_14726, APPLY_INTIMACY = TRUE, },
		{ RATE = 33, MESSAGE = STR_ID_14727, APPLY_INTIMACY = TRUE, },
		{ RATE = 33, MESSAGE = STR_ID_14728, APPLY_INTIMACY = TRUE, },
	},
	TALK_BOX =
	{
		{ RATE = 34, MESSAGE = STR_ID_14729, APPLY_INTIMACY = TRUE, },
		{ RATE = 33, MESSAGE = STR_ID_14730, APPLY_INTIMACY = TRUE, },
		{ RATE = 33, MESSAGE = STR_ID_14731, APPLY_INTIMACY = TRUE, },
	},
}

ANCIENT_PPORU_HALLOW_DARK_SAD =
{
	ANIM_NAME					= "Afraid",
	PLAY_TYPE					= XSKIN_ANIM_PLAYTYPE["XAP_ONE_WAIT"],
	TRANSITION					= TRUE,

	MOVE_TYPE           = 0,


	IMMADIATE_PACKET_SEND		= TRUE,

	ALLOW_DIR_CHANGE			= FALSE,

	EVENT_PROCESS =
	{
		{ STATE_CHANGE_TYPE["SCT_FOOT_ON_LINE_FALSE_DOWN"],	"ANCIENT_PPORU_HALLOW_DARK_JUMP_DOWN",					},
		{ STATE_CHANGE_TYPE["SCT_MOTION_END"],				"ANCIENT_PPORU_HALLOW_DARK_WAIT",						},
	},

	TALK_BOX_1 =
	{
		{ RATE = 34, MESSAGE = STR_ID_14732 },
		{ RATE = 33, MESSAGE = STR_ID_14733 },
		{ RATE = 33, MESSAGE = STR_ID_14734 },
	},
	TALK_BOX_2 =
	{
		{ RATE = 34, MESSAGE = STR_ID_14735},
		{ RATE = 33, MESSAGE = STR_ID_14736 },
		{ RATE = 33, MESSAGE = STR_ID_14737 },
	},
	TALK_BOX =
	{
		{ RATE = 34, MESSAGE = STR_ID_14738},
		{ RATE = 33, MESSAGE = STR_ID_14739 },
		{ RATE = 33, MESSAGE = STR_ID_14740 },
	},
}

ANCIENT_PPORU_HALLOW_DARK_CHEER =
{
	ANIM_NAME					= "Cheer",
	PLAY_TYPE					= XSKIN_ANIM_PLAYTYPE["XAP_ONE_WAIT"],
	TRANSITION					= TRUE,

	MOVE_TYPE           = 0,

    SOUND_PLAY0					= { 0.005, "Pet_Cheer_Common.ogg" },
    SOUND_PLAY1					= { 0.472, "Pet_AncientPporu_Cheer3.ogg" },

	IMMADIATE_PACKET_SEND		= TRUE,

	ALLOW_DIR_CHANGE			= FALSE,

	EVENT_PROCESS =
	{
		{ STATE_CHANGE_TYPE["SCT_FOOT_ON_LINE_FALSE_DOWN"],	"ANCIENT_PPORU_HALLOW_DARK_JUMP_DOWN",					},
		{ STATE_CHANGE_TYPE["SCT_MOTION_END"],				"ANCIENT_PPORU_HALLOW_DARK_WAIT",						},
	},

	TALK_BOX_1 =
	{
		{ RATE = 34, MESSAGE = STR_ID_14741 },
		{ RATE = 33, MESSAGE = STR_ID_14742 },
		{ RATE = 33, MESSAGE = STR_ID_14743 },
	},
	TALK_BOX_2 =
	{
		{ RATE = 34, MESSAGE = STR_ID_14744 },
		{ RATE = 33, MESSAGE = STR_ID_14745 },
		{ RATE = 33, MESSAGE = STR_ID_14746 },
	},
	TALK_BOX =
	{
		{ RATE = 34, MESSAGE = STR_ID_14747 },
		{ RATE = 33, MESSAGE = STR_ID_14748 },
		{ RATE = 33, MESSAGE = STR_ID_14749 },
	},
}

ANCIENT_PPORU_HALLOW_DARK_SPECIAL =
{
	ANIM_NAME					= "Special_A",
	PLAY_TYPE					= XSKIN_ANIM_PLAYTYPE["XAP_ONE_WAIT"],
	TRANSITION					= TRUE,

	MOVE_TYPE           = 0,

    SOUND_PLAY0					= { 0.489, "Pet_AncientPporu_Special2.ogg" },

	IMMADIATE_PACKET_SEND		= TRUE,

	ALLOW_DIR_CHANGE			= FALSE,

	EVENT_PROCESS =
	{
		{ STATE_CHANGE_TYPE["SCT_FOOT_ON_LINE_FALSE_DOWN"],	"ANCIENT_PPORU_HALLOW_DARK_JUMP_DOWN",					},
		{ STATE_CHANGE_TYPE["SCT_MOTION_END"],				"ANCIENT_PPORU_HALLOW_DARK_WAIT",						},
	},

	TALK_BOX_1 =
	{
		{ RATE = 34, MESSAGE = STR_ID_14750, APPLY_INTIMACY = TRUE, },
		{ RATE = 33, MESSAGE = STR_ID_14751, APPLY_INTIMACY = TRUE, },
		{ RATE = 33, MESSAGE = STR_ID_14752, APPLY_INTIMACY = TRUE, },
	},
	TALK_BOX_2 =
	{
		{ RATE = 34, MESSAGE = STR_ID_14753, APPLY_INTIMACY = TRUE, },
		{ RATE = 33, MESSAGE = STR_ID_14754, APPLY_INTIMACY = TRUE, },
		{ RATE = 33, MESSAGE = STR_ID_14755, APPLY_INTIMACY = TRUE, },
	},
	TALK_BOX =
	{
		{ RATE = 34, MESSAGE = STR_ID_14756, APPLY_INTIMACY = TRUE, },
		{ RATE = 33, MESSAGE = STR_ID_14757, APPLY_INTIMACY = TRUE, },
		{ RATE = 33, MESSAGE = STR_ID_14758, APPLY_INTIMACY = TRUE, },
	},
}

ANCIENT_PPORU_HALLOW_DARK_ATTACK =
{
	ANIM_NAME					= "Attack_C",
	PLAY_TYPE					= XSKIN_ANIM_PLAYTYPE["XAP_ONE_WAIT"],
	TRANSITION					= TRUE,

	MOVE_TYPE           = 0,
	VIEW_TARGET			= TRUE,

    SOUND_PLAY0					= { 0.33, "Pet_AncientPporu_Attack3.ogg" },


	IMMADIATE_PACKET_SEND		= TRUE,

	EVENT_PROCESS =
	{
		{ STATE_CHANGE_TYPE["SCT_FOOT_ON_LINE_FALSE_DOWN"],	"ANCIENT_PPORU_HALLOW_DARK_JUMP_DOWN",					},
		{ STATE_CHANGE_TYPE["SCT_MOTION_END"],				"ANCIENT_PPORU_HALLOW_DARK_WAIT",						},
	},

	TALK_BOX_1 =
	{
		{ RATE = 34, MESSAGE = STR_ID_14759 },
		{ RATE = 33, MESSAGE = STR_ID_14760 },
		{ RATE = 33, MESSAGE = STR_ID_14761 },
	},
	TALK_BOX_2 =
	{
		{ RATE = 34, MESSAGE = STR_ID_14762 },
		{ RATE = 33, MESSAGE = STR_ID_14763 },
		{ RATE = 33, MESSAGE = STR_ID_14764 },
	},
	TALK_BOX =
	{
		{ RATE = 34, MESSAGE = STR_ID_14765 },
		{ RATE = 33, MESSAGE = STR_ID_14766 },
		{ RATE = 33, MESSAGE = STR_ID_14767 },
	},
}


ANCIENT_PPORU_HALLOW_DARK_SIT_START =
{
	ANIM_NAME					= "Sit_Ready",
	PLAY_TYPE					= XSKIN_ANIM_PLAYTYPE["XAP_ONE_WAIT"],
	TRANSITION					= TRUE,

	MOVE_TYPE           = 0,


	IMMADIATE_PACKET_SEND		= TRUE,

	ALLOW_DIR_CHANGE			= FALSE,

	EVENT_PROCESS =
	{
		{ STATE_CHANGE_TYPE["SCT_FOOT_ON_LINE_FALSE_DOWN"],	"ANCIENT_PPORU_HALLOW_DARK_JUMP_DOWN",					},
		{ STATE_CHANGE_TYPE["SCT_MOTION_END"],				"ANCIENT_PPORU_HALLOW_DARK_SIT_LOOP",						},
	},

	TALK_BOX_1 =
	{
		{ RATE = 34, MESSAGE = STR_ID_14768, APPLY_INTIMACY = TRUE, },
		{ RATE = 33, MESSAGE = STR_ID_14769, APPLY_INTIMACY = TRUE, },
		{ RATE = 33, MESSAGE = STR_ID_14770, APPLY_INTIMACY = TRUE, },
	},
	TALK_BOX_2 =
	{
		{ RATE = 34, MESSAGE = STR_ID_14771, APPLY_INTIMACY = TRUE, },
		{ RATE = 33, MESSAGE = STR_ID_14772, APPLY_INTIMACY = TRUE, },
		{ RATE = 33, MESSAGE = STR_ID_14773, APPLY_INTIMACY = TRUE, },
	},
	TALK_BOX =
	{
		{ RATE = 34, MESSAGE = STR_ID_14774, APPLY_INTIMACY = TRUE, },
		{ RATE = 33, MESSAGE = STR_ID_14775, APPLY_INTIMACY = TRUE, },
		{ RATE = 33, MESSAGE = STR_ID_14776, APPLY_INTIMACY = TRUE, },
	},
}

ANCIENT_PPORU_HALLOW_DARK_SIT_LOOP =
{
	ANIM_NAME					= "Sit",
	PLAY_TYPE					= XSKIN_ANIM_PLAYTYPE["XAP_LOOP"],
	TRANSITION					= TRUE,

	MOVE_TYPE           = 0,


	IMMADIATE_PACKET_SEND		= TRUE,

	ALLOW_DIR_CHANGE			= FALSE,

	EVENT_PROCESS =
	{
		{ STATE_CHANGE_TYPE["SCT_FOOT_ON_LINE_FALSE_DOWN"],	"ANCIENT_PPORU_HALLOW_DARK_JUMP_DOWN",					},
	},
}

ANCIENT_PPORU_HALLOW_DARK_SIT_END =
{
	ANIM_NAME					= "Sit_End",
	PLAY_TYPE					= XSKIN_ANIM_PLAYTYPE["XAP_ONE_WAIT"],
	TRANSITION					= TRUE,

	MOVE_TYPE           = 0,


	IMMADIATE_PACKET_SEND		= TRUE,

	ALLOW_DIR_CHANGE			= FALSE,

	EVENT_PROCESS =
	{
		{ STATE_CHANGE_TYPE["SCT_FOOT_ON_LINE_FALSE_DOWN"],	"ANCIENT_PPORU_HALLOW_DARK_JUMP_DOWN",					},
		{ STATE_CHANGE_TYPE["SCT_MOTION_END"],				"ANCIENT_PPORU_HALLOW_DARK_WAIT",						},
	},

	TALK_BOX_1 =
	{
		{ RATE = 34, MESSAGE = STR_ID_14777, APPLY_INTIMACY = TRUE, },
		{ RATE = 33, MESSAGE = STR_ID_14778, APPLY_INTIMACY = TRUE, },
		{ RATE = 33, MESSAGE = STR_ID_14779, APPLY_INTIMACY = TRUE, },
	},
	TALK_BOX_2 =
	{
		{ RATE = 34, MESSAGE = STR_ID_14780, APPLY_INTIMACY = TRUE, },
		{ RATE = 33, MESSAGE = STR_ID_14781, APPLY_INTIMACY = TRUE, },
		{ RATE = 33, MESSAGE = STR_ID_14782, APPLY_INTIMACY = TRUE, },
	},
	TALK_BOX =
	{
		{ RATE = 34, MESSAGE = STR_ID_14783, APPLY_INTIMACY = TRUE, },
		{ RATE = 33, MESSAGE = STR_ID_14784, APPLY_INTIMACY = TRUE, },
		{ RATE = 33, MESSAGE = STR_ID_14785, APPLY_INTIMACY = TRUE, },
	},
}

ANCIENT_PPORU_HALLOW_DARK_NOTKNOW =
{
	ANIM_NAME					= "DoNotKnow",
	PLAY_TYPE					= XSKIN_ANIM_PLAYTYPE["XAP_ONE_WAIT"],
	TRANSITION					= TRUE,

	MOVE_TYPE           = 0,


	IMMADIATE_PACKET_SEND		= TRUE,

	ALLOW_DIR_CHANGE			= FALSE,

	EVENT_PROCESS =
	{
		{ STATE_CHANGE_TYPE["SCT_FOOT_ON_LINE_FALSE_DOWN"],	"ANCIENT_PPORU_HALLOW_DARK_JUMP_DOWN",					},
		{ STATE_CHANGE_TYPE["SCT_MOTION_END"],				"ANCIENT_PPORU_HALLOW_DARK_WAIT",						},
	},

	-- TALK_BOX_1 =
	-- {
		-- { RATE = 50, MESSAGE = STR_ID_5413, APPLY_INTIMACY = TRUE, },
		-- { RATE = 50, MESSAGE = STR_ID_5414, APPLY_INTIMACY = TRUE, },
	-- },
	-- TALK_BOX_2 =
	-- {
		-- { RATE = 50, MESSAGE = STR_ID_5413, APPLY_INTIMACY = TRUE, },
		-- { RATE = 50, MESSAGE = STR_ID_5414, APPLY_INTIMACY = TRUE, },
	-- },
	-- TALK_BOX =
	-- {
		-- { RATE = 50, MESSAGE = STR_ID_5413, APPLY_INTIMACY = TRUE, },
		-- { RATE = 50, MESSAGE = STR_ID_5414, APPLY_INTIMACY = TRUE, },
	-- },
}





function ANCIENT_PPORU_HALLOW_DARK_ATTACK_FRAME_MOVE( pKTDXApp, pX2Game, pPet )

    if pPet:AnimEventTimer( 0.001 ) then
		local pEffectSet = pX2Game:GetEffectSet()
		if pEffectSet ~= nil then
			pEffectSet:PlayEffectSetByPet_LUA( "EffectSet_Pet_Ancient_pporu_Dark", pPet )
		end
	end
end


function CF_PETATTACK_ANCIENT_PPORU_3( pKTDXApp, pX2Game, pPet )

	if pX2Game ~= nil then
		if pX2Game:IsHost() == false then
			return false
		end
	end

	if pPet:IsAttacking() == true then

		local fDist = pPet:GetDistTarget()
		if fDist <= 300 then
			return true
		end
	end

	return false
end

function ANCIENT_PPORU_HALLOW_DARK_SUMMON_START( pKTDXApp, pX2Game, pPet )

	local pEffectSet = pPet:GetUIEffectSet()
	if pEffectSet ~= nil then
		pEffectSet:PlayEffectSetByPet_LUA( "EffectSet_Pet_Ancient_Dark", pPet )
	end
end
