-- lua header. UTF-8 인코딩 인식을 위해 이 줄은 지우지 마세요.


INIT_SYSTEM = 
{
	UNIT_WIDTH		= 50.0,
	UNIT_HEIGHT		= 100.0,
	UNIT_LAYER		= X2_LAYER["XL_UNIT_0"],	
}


INIT_DEVICE = 
{
	READY_TEXTURE = 
	{
	},
	
	READY_SOUND = 
	{
	},
}

INIT_MOTION = 
{
	MOTION_FILE_NAME		= "Motion_PIRANHA.x",
}

INIT_PHYSIC = 
{	
	RELOAD_ACCEL		= 2000,
	G_ACCEL				= 0,
	MAX_G_SPEED			= 0,
	
	WALK_SPEED			= 300,
	RUN_SPEED			= 300,
	JUMP_SPEED			= 1500,
	DASH_JUMP_SPEED		= 2300,
}


INIT_COMPONENT = 
{
	MAX_HP				= 2000,
	MP_CHANGE_RATE		= 0,
	MP_CHARGE_RATE		= 0,
	
	USE_SLASH_TRACE		= FALSE,
	
	--SHADOW_SIZE			= 200,
	SHADOW_FILE_NAME	= "shadow.dds",
	
	--SMALL_HP_BAR_BLUE	= "Small_HP_bar_Blue.TGA",
	--SMALL_HP_BAR_RED	= "Small_HP_bar_Red.TGA",
	--SMALL_HP_BAR_YELLOW = "Small_HP_bar_Yellow.TGA",
	
	QUESTION_MARK_SEQ		= "QuestionMarkNPC",
	EXCLAMATION_MARK_SEQ	= "ExclamationMarkNPC",
	
	HEAD_BONE_NAME			= "COLLISION_SPHERE1",
	
	HYPER_MODE_COUNT	= 0,
	MAX_HYPER_MODE_TIME	= 30,
	
	HITTED_TYPE			= HITTED_TYPE["HTD_MEAT"],
	FALL_DOWN			= FALSE,	
		
  SKY_DIE             = TRUE,		
	DAMAGE_DOWN         = FALSE,		
	DIE_FLY             = 0,
}




INIT_STATE = 
{
	{ STATE_NAME = "PIRANHA_LAND_START",						},	
	{ STATE_NAME = "PIRANHA_LAND_WAIT",						},
	{ STATE_NAME = "PIRANHA_LAND_WAITHIBIT",				},
	{ STATE_NAME = "PIRANHA_LAND_WALK",						},
		
	{  STATE_NAME = "PIRANHA_LAND_ATTACKA_READY",				},
	{  STATE_NAME = "PIRANHA_LAND_ATTACKB_READY",				},
  { STATE_NAME = "PIRANHA_LAND_ATTACKA",				},
  { STATE_NAME = "PIRANHA_LAND_ATTACKB",				},
 	{  STATE_NAME = "PIRANHA_LAND_ATTACK_END",				},
		
	--리액션 관련
	{ STATE_NAME = "PIRANHA_LAND_DAMAGE_FRONT",				},
	{ STATE_NAME = "PIRANHA_LAND_DAMAGE_BACK",				},
	{ STATE_NAME = "PIRANHA_LAND_DAMAGEREVENGE",				},	
	{ STATE_NAME = "PIRANHA_LAND_DYING",						LUA_STATE_START_FUNC = "PIRANHA_LAND_DYING_STATE_START" },	
	
	START_STATE					= "PIRANHA_LAND_START",
	WAIT_STATE					= "PIRANHA_LAND_WAIT",
	
	SMALL_DAMAGE_LAND_FRONT		= "PIRANHA_LAND_DAMAGE_FRONT",
	SMALL_DAMAGE_LAND_BACK		= "PIRANHA_LAND_DAMAGE_BACK",
	BIG_DAMAGE_LAND_FRONT		= "PIRANHA_LAND_DAMAGE_FRONT",
	BIG_DAMAGE_LAND_BACK		= "PIRANHA_LAND_DAMAGE_BACK",
	DOWN_DAMAGE_LAND_FRONT		= "PIRANHA_LAND_DAMAGE_FRONT",
	DOWN_DAMAGE_LAND_BACK		= "PIRANHA_LAND_DAMAGE_BACK",
	FLY_DAMAGE_FRONT			= "PIRANHA_LAND_DAMAGE_FRONT",
	FLY_DAMAGE_BACK				= "PIRANHA_LAND_DAMAGE_BACK",
	
	SMALL_DAMAGE_AIR_FRONT		= "PIRANHA_LAND_DAMAGE_FRONT",
	SMALL_DAMAGE_AIR_BACK		= "PIRANHA_LAND_DAMAGE_BACK",
	
	BIG_DAMAGE_AIR_FRONT		= "PIRANHA_LAND_DAMAGE_FRONT",
	BIG_DAMAGE_AIR_BACK			= "PIRANHA_LAND_DAMAGE_BACK",
	
	DOWN_DAMAGE_AIR				= "PIRANHA_LAND_DAMAGE_FRONT",
	UP_DAMAGE					= "PIRANHA_LAND_DAMAGE_FRONT",
	DAMAGE_REVENGE				= "PIRANHA_LAND_DAMAGEREVENGE",
	
	DYING_LAND_FRONT			= "PIRANHA_LAND_DYING",
	DYING_LAND_BACK				= "PIRANHA_LAND_DYING",
	DYING_SKY					= "PIRANHA_LAND_DYING",

	REVENGE_ATTACK				= "PIRANHA_LAND_WAIT",	
}

INIT_AI = 
{
	TARGET = 
	{
		TARGET_PRIORITY 			= TARGET_PRIORITY["TP_RANDOM"],
		TARGET_INTERVAL				= 3,		-- sec
		TARGET_NEAR_RANGE			= 600,		-- 이 거리보다 가까우면 TARGET_SUCCESS_RATE에 관계없이 무조건 타게팅된다
		TARGET_RANGE				= 1200,		-- cm
		TARGET_LOST_RANGE			= 800,		-- cm
		TARGET_SUCCESS_RATE			= 100,  --50,		-- %
		ATTACK_TARGET_RATE			= 100, -- 30,		-- 나를 공격한 유닛을 타게팅할 확률
		PRESERVE_LAST_TARGET_RATE	= 100, -- 50,		-- 이전에 타게팅된 유닛을 계속 타게팅할 확률
	},

	CHASE_MOVE = 
	{		
		DEST_GAP			= 300,	-- 목적지에서 이 거리 안에 있으면 도착했다고 판단한다
		MOVE_GAP			= 160,
		
		DIR_CHANGE_INTERVAL = 0.7,
		
		MOVE_SPLIT_RANGE	= 700,
		WALK_INTERVAL		= 1,
		NEAR_WALK_RATE		= 100,   --  70,
		FAR_WALK_RATE		= 100,   -- 30,
		
		JUMP_INTERVAL		= 10,
		UP_JUMP_RATE		= 0, -- 30,
		UP_DOWN_RATE		= 0,
		DOWN_JUMP_RATE		= 0,    --  30,
		DOWN_DOWN_RATE		= 0,
	},	
	
	PATROL_MOVE = 	
	{
		PATROL_BEGIN_RATE		= 50, --50,		
		PATROL_RANGE			= 500,
		PATROL_COOL_TIME		= 2,
		ONLY_THIS_LINE_GROUP	= TRUE,
	},
	
	ESCAPE_MOVE = 
	{		
		MOVE_SPLIT_RANGE	= 400,
		ESCAPE_GAP			= 600,	-- 이 거리 보다 멀면 도망 성공
		
		WALK_INTERVAL		= 1,
		NEAR_WALK_RATE		= 100,   --  70,
		FAR_WALK_RATE		= 100,   -- 30,
		
		JUMP_INTERVAL		= 10,
		UP_JUMP_RATE		= 100, -- 30,
		UP_DOWN_RATE		= 30,
		DOWN_JUMP_RATE		= 100,    --  30,
		DOWN_DOWN_RATE		= 30,
	},
	
	
}


PIRANHA_LAND_START = 
{
	ANIM_NAME					= "WaitHabit",
	PLAY_TYPE					= XSKIN_ANIM_PLAYTYPE["XAP_ONE_WAIT"],
	TRANSITION					= TRUE,
	--LAND_CONNECT				= FALSE,
	
	CAN_PUSH_UNIT				= FALSE,
	CAN_PASS_UNIT				= TRUE,
	
	INVINCIBLE					= { 0, 100, }, 
	
	NOTUSE_LANDCONNECT  = TRUE,
	
	EVENT_PROCESS = 
	{
		{ STATE_CHANGE_TYPE["SCT_MOTION_END"],					"PIRANHA_LAND_WAIT",				},
	},	
}

PIRANHA_LAND_WAITHIBIT =
{
  ANIM_NAME					= "WaitHabit",
	PLAY_TYPE					= XSKIN_ANIM_PLAYTYPE["XAP_ONE_WAIT"],
	TRANSITION					= TRUE,
	--LAND_CONNECT				= FALSE,
	
	CAN_PUSH_UNIT				= FALSE,
	CAN_PASS_UNIT				= TRUE,
		
	NOTUSE_LANDCONNECT  = TRUE,
	
	EVENT_PROCESS = 
	{
		{ STATE_CHANGE_TYPE["SCT_MOTION_END"],					"PIRANHA_LAND_WAIT",				},
	},	
}

PIRANHA_LAND_WAIT = 
{
	ANIM_NAME					= "Wait",
	PLAY_TYPE					= XSKIN_ANIM_PLAYTYPE["XAP_LOOP"],
	TRANSITION					= TRUE,
	--LAND_CONNECT				= FALSE,
	
	CAN_PUSH_UNIT				= FALSE,
	CAN_PASS_UNIT				= TRUE,	
	
	PASSIVE_SPEED_Y     = 0,
	PASSIVE_SPEED_X     = 0,
	
  --NOTUSE_LANDCONNECT  = TRUE,
	
	EVENT_PROCESS = 
	{		
		{ STATE_CHANGE_TYPE["SCT_FOOT_ON_LINE_FALSE_DOWN"],	"PIRANHA_LAND_START",					},
		
		--{ STATE_CHANGE_TYPE["SCT_CONDITION_TABLE"],			"PIRANHA_LAND_AttackA_Ready",		"CT_PIRANHA_LAND_AttackA",		},
    { STATE_CHANGE_TYPE["SCT_AI_WALK"],					"PIRANHA_LAND_WALK",						},
		{ STATE_CHANGE_TYPE["SCT_AI_DASH"],					"PIRANHA_LAND_WALK",						},			
		
		{ STATE_CHANGE_TYPE["SCT_CONDITION_TABLE"],			"PIRANHA_LAND_ATTACKA_READY",		      "CT_PIRANHA_LAND_ATTACKA",	},	    
    { STATE_CHANGE_TYPE["SCT_CONDITION_TABLE"],			"PIRANHA_LAND_ATTACKB_READY",		      "CT_PIRANHA_LAND_ATTACKB",	},
    { STATE_CHANGE_TYPE["SCT_CONDITION_TABLE"],			"PIRANHA_LAND_WAITHIBIT",		      "CT_PIRANHA_LAND_WAITHIBIT",	},
    
	},
	
	CT_PIRANHA_LAND_ATTACKA =
	{
	  EVENT_INTERVAL_ID           = 0,
		DISTANCE_TO_TARGET_NEAR	= 700,
		RATE                    = 60,
	},
	CT_PIRANHA_LAND_ATTACKB =
	{
    EVENT_INTERVAL_ID           = 0,
    DISTANCE_TO_TARGET_NEAR	= 1100,
	  RATE                    = 60,
	},	
	CT_PIRANHA_LAND_WAITHIBIT =
	{
		ANIM_PLAY_COUNT		= 15,
		RATE				= 50,
	},
}

PIRANHA_LAND_WALK = 
{
	ANIM_NAME					= "Walk",
	PLAY_TYPE					= XSKIN_ANIM_PLAYTYPE["XAP_LOOP"],
	TRANSITION					= TRUE,
	--LAND_CONNECT				= FALSE,
	
	CAN_PUSH_UNIT				= FALSE,
	CAN_PASS_UNIT				= TRUE,
	
	PASSIVE_SPEED_X				= INIT_PHYSIC["WALK_SPEED"],
	PASSIVE_SPEED_Y     = 0,
	
	ALLOW_DIR_CHANGE			= TRUE,
	IMMADIATE_PACKET_SEND		= TRUE,
	
	--NOTUSE_LANDCONNECT  = TRUE,
	
	EVENT_INTERVAL_TIME0		= 2,
	
	EVENT_PROCESS = 
	{		
		{ STATE_CHANGE_TYPE["SCT_FOOT_ON_LINE_FALSE_DOWN"],	"PIRANHA_LAND_START",				},
		
		--{ STATE_CHANGE_TYPE["SCT_CONDITION_TABLE"],			"PIRANHA_LAND_AttackA_Ready",		"CT_PIRANHA_LAND_AttackA",		},		
		
		{ STATE_CHANGE_TYPE["SCT_AI_WAIT"],					"PIRANHA_LAND_WAIT",						},				
	},
	
	CT_PIRANHA_LAND_AttackA = 
	{
		EVENT_INTERVAL_ID			= 0,
		DISTANCE_TO_TARGET_NEAR		= 600,
		RATE						= 30,
	},	
}


PIRANHA_LAND_ATTACKA_READY =
{
	ANIM_NAME					= "AttackA_Ready",
	PLAY_TYPE					= XSKIN_ANIM_PLAYTYPE["XAP_ONE_WAIT"],
	TRANSITION					= TRUE,
	LAND_CONNECT				= FALSE,
	
	CAN_PUSH_UNIT				= FALSE,
	CAN_PASS_UNIT				= TRUE,		
		
	SPEED_X						= 0,
	SPEED_Y						= 0,	
	PASSIVE_SPEED_Y				= 0,
	
	ENABLE_HEIGHT_FIX           = TRUE,
	
	--FLY_AI                      = FALSE,
	
	EVENT_PROCESS = 
	{
		{ STATE_CHANGE_TYPE["SCT_MOTION_END"],				"PIRANHA_LAND_ATTACKA", },
	},	
}

PIRANHA_LAND_ATTACKB_READY =
{
	ANIM_NAME					= "AttackA_Ready",
	PLAY_TYPE					= XSKIN_ANIM_PLAYTYPE["XAP_ONE_WAIT"],
	TRANSITION					= TRUE,
	LAND_CONNECT				= FALSE,
	
	CAN_PUSH_UNIT				= FALSE,
	CAN_PASS_UNIT				= TRUE,		
		
	SPEED_X						= 0,
	SPEED_Y						= 0,	
	PASSIVE_SPEED_Y				= 0,
	
	ENABLE_HEIGHT_FIX           = TRUE,
	
	--FLY_AI                      = FALSE,
	
	EVENT_PROCESS = 
	{
		{ STATE_CHANGE_TYPE["SCT_MOTION_END"],				"PIRANHA_LAND_ATTACKB", },
	},
	
}

PIRANHA_LAND_ATTACK_END =
{
	ANIM_NAME					= "AttackA_End",
	PLAY_TYPE					= XSKIN_ANIM_PLAYTYPE["XAP_ONE_WAIT"],
	TRANSITION					= TRUE,
	LAND_CONNECT				= FALSE,
	
	CAN_PUSH_UNIT				= FALSE,
	CAN_PASS_UNIT				= TRUE,		
		
	SPEED_X						= 100,
	SPEED_Y						= 0,	
	PASSIVE_SPEED_X				= 0,
	PASSIVE_SPEED_Y				= 0,
	
	ENABLE_HEIGHT_FIX           = TRUE,
	
	--FLY_AI                      = FALSE,
	
	EVENT_PROCESS = 
	{
		{ STATE_CHANGE_TYPE["SCT_MOTION_END"],				"PIRANHA_LAND_WAIT", },
	},	
}

PIRANHA_LAND_ATTACKA =
{
	ANIM_NAME					= "AttackA",
	PLAY_TYPE					= XSKIN_ANIM_PLAYTYPE["XAP_ONE_WAIT"],
	TRANSITION					= TRUE,
	LAND_CONNECT				= FALSE,
	
	CAN_PUSH_UNIT				= FALSE,
	CAN_PASS_UNIT				= TRUE,		
	
	ALLOW_DIR_CHANGE			= FALSE,
		
	SPEED_X						= 0,
	SPEED_Y						= 0,	
	PASSIVE_SPEED_X   = 1000,
	PASSIVE_SPEED_Y				= 0,
	
	
	ATTACK_TIME0				= { 0.01, 0.72, },
	
	DAMAGE_DATA = 
	{
		DAMAGE_TYPE		= DAMAGE_TYPE["DT_PHYSIC"],
		HIT_TYPE		= HIT_TYPE["HT_SWORD_SLASH2"],
		REACT_TYPE		= REACT_TYPE["RT_SMALL_DAMAGE"],
		
		DAMAGE = 
		{
			PHYSIC		= 1.5,

		},
				
		BACK_SPEED_X			= 0,
		BACK_SPEED_Y			= 0,
		
		CAMERA_CRASH_GAP		= 5.0,	
		CAMERA_CRASH_TIME		= 0.2,		
	},
	
	EVENT_PROCESS = 
	{
		{ STATE_CHANGE_TYPE["SCT_MOTION_END"],				"PIRANHA_LAND_ATTACK_END", },
	},
	
}

PIRANHA_LAND_ATTACKB =
{
	ANIM_NAME					= "AttackA",
	PLAY_TYPE					= XSKIN_ANIM_PLAYTYPE["XAP_ONE_WAIT"],
	TRANSITION					= TRUE,
	LAND_CONNECT				= FALSE,
	
	CAN_PUSH_UNIT				= FALSE,
	CAN_PASS_UNIT				= TRUE,		
	
	ALLOW_DIR_CHANGE			= FALSE,
		
	SPEED_X						= 0,
	SPEED_Y						= 0,	
	PASSIVE_SPEED_X       = 1500,
	PASSIVE_SPEED_Y				= 0,
		
	
	DAMAGE_DATA = 
	{
		DAMAGE_TYPE		= DAMAGE_TYPE["DT_PHYSIC"],
		HIT_TYPE		= HIT_TYPE["HT_SWORD_SLASH2"],
		REACT_TYPE		= REACT_TYPE["RT_BIG_DAMAGE"],
		
		DAMAGE = 
		{
			PHYSIC		= 1.5,

		},
		
		
		BACK_SPEED_X			= 0,
		BACK_SPEED_Y			= 0,
		
		CAMERA_CRASH_GAP		= 5.0,	
		CAMERA_CRASH_TIME		= 0.2,	
	},
	
	EVENT_PROCESS = 
	{
		{ STATE_CHANGE_TYPE["SCT_MOTION_END"],				"PIRANHA_LAND_ATTACK_END", },
	},
	
}

PIRANHA_LAND_DAMAGEREVENGE = 
{
	ANIM_NAME					= "DamageRevenge",
	PLAY_TYPE					= XSKIN_ANIM_PLAYTYPE["XAP_ONE_WAIT"],
	TRANSITION					= TRUE,
	--LAND_CONNECT				= FALSE,
	
	CAN_PUSH_UNIT				= FALSE,
	CAN_PASS_UNIT				= TRUE,		
	
	PASSIVE_SPEED_Y     = 0,
	PASSIVE_SPEED_X     = 0,
		
	
	--NOTUSE_LANDCONNECT  = TRUE,
	
	EVENT_PROCESS = 
	{
		{ STATE_CHANGE_TYPE["SCT_MOTION_END"],				"PIRANHA_LAND_WAIT", },
	},
	
}

PIRANHA_LAND_DAMAGE_FRONT = 
{
	ANIM_NAME					= "DamageFront",
	PLAY_TYPE					= XSKIN_ANIM_PLAYTYPE["XAP_ONE_WAIT"],
	TRANSITION					= TRUE,
	--LAND_CONNECT				= FALSE,
	
	CAN_PUSH_UNIT				= FALSE,
	CAN_PASS_UNIT				= TRUE,		
	
	PASSIVE_SPEED_Y     = 0,
	PASSIVE_SPEED_X     = 0,
		
	
	--NOTUSE_LANDCONNECT  = TRUE,
	
	EVENT_PROCESS = 
	{
		{ STATE_CHANGE_TYPE["SCT_MOTION_END"],				"PIRANHA_LAND_WAIT", },
	},
	
}

PIRANHA_LAND_DAMAGE_BACK = 
{
	ANIM_NAME					= "DamageBack",
	PLAY_TYPE					= XSKIN_ANIM_PLAYTYPE["XAP_ONE_WAIT"],
	TRANSITION					= TRUE,
	--LAND_CONNECT				= FALSE,
	
	CAN_PUSH_UNIT				= FALSE,
	CAN_PASS_UNIT				= TRUE,
	
	PASSIVE_SPEED_Y     = 0,
	PASSIVE_SPEED_X     = 0,
	
	--NOTUSE_LANDCONNECT  = TRUE,
			
	EVENT_PROCESS = 
	{
		{ STATE_CHANGE_TYPE["SCT_MOTION_END"],				"PIRANHA_LAND_WAIT", },
	},
	
}

PIRANHA_LAND_DYING = 
{
	ANIM_NAME					= "Dying",
	PLAY_TYPE					= XSKIN_ANIM_PLAYTYPE["XAP_ONE_WAIT"],
	TRANSITION					= FALSE,
	--LAND_CONNECT				= FALSE,

	INVINCIBLE					= { 0, 100, }, 		
	
	PASSIVE_SPEED_X				= 0,
	PASSIVE_SPEED_Y     = 0,
	
	CAN_PUSH_UNIT				= FALSE,
	CAN_PASS_UNIT				= TRUE,
	
	--NOTUSE_LANDCONNECT  = TRUE,
	
	--NEVER_MOVE					= TRUE,
	DYING_END					= TRUE,
	DYING_SPEED					= 1,
	
	IMMADIATE_PACKET_SEND		= TRUE,
}


function PIRANHA_LAND_DYING_STATE_START( pKTDXApp, pX2Game, pNPCUnit )
	

	pos = pNPCUnit:GetPos()
	pos.y = pos.y + 100.0
	GetMinorParticle = pX2Game:GetMinorParticle()
	
	pSeq = GetMinorParticle:GameUnitCreateSequence_LUA( pNPCUnit, "DieLight",		pos, D3DXVECTOR2(-1,-1), D3DXVECTOR2(3,-1) )
	if pSeq ~= nil then
	
		pSeq:SetLandPosition( pNPCUnit:GetLandPosition_LUA().y )
		pNPCUnit:SetDieSeq( pSeq:GetHandle() )
	
	end
	
	GetMajorParticle = pX2Game:GetMajorParticle()
	GetMajorParticle:GameUnitCreateSequence_LUA( pNPCUnit, "DamageImpact",			pos, D3DXVECTOR2(100,200), D3DXVECTOR2(2,10) )
	GetMajorParticle:GameUnitCreateSequence_LUA( pNPCUnit, "DamageImpactCore",		pos, D3DXVECTOR2(100,200), D3DXVECTOR2(2,10) )
	GetMajorParticle:GameUnitCreateSequence_LUA( pNPCUnit, "DamageImpactRingRed",		pos, D3DXVECTOR2(100,200), D3DXVECTOR2(2,10) )
	
	pNPCUnit:PlaySound_LUA( "DieLight.ogg" )
	
end


