-- lua header. UTF-8 인코딩 인식을 위해 이 줄은 지우지 마세요.

-- NUI_TARANVASH_THE_SHINE_FAKE_?

INIT_SYSTEM = 
{
	UNIT_WIDTH		= 400.0,
	UNIT_HEIGHT		= 150.0,
	UNIT_LAYER		= X2_LAYER["XL_UNIT_0"],
	UNIT_SCALE		= 1,
	--APPLY_EFFECTSET_SCALE = TRUE,
}


INIT_DEVICE = 
{
	READY_TEXTURE = 
	{
		"stone.dds",
		"PlusHPMP.dds",
		"ColorBallGray.dds",
		"ColorBallBlue.dds",
		"Water_Ball01.dds",
		"Particle_Blur.dds",
		"Sap_Gray01.dds",
		"GroundShockWave02.dds",
		"steam_BP.dds",
		"Ring.dds",
		"AeroTornado04.dds",
		"Condense_Light01.dds",
		"CenterLight_Gray01.dds",
		"Circle_Light02.dds",
		"GuideArrow01.dds",
	},
	
	READY_SOUND = 
	{	 
		"Swing_Medium01.ogg",
		"Swing_Medium02.ogg",
		"Landing_RawMeat01.ogg",
		"Landing_RawMeat02.ogg",
		"Landing_Big_Meat01.ogg",
		"Landing_Big_Meat02.ogg",
		"Taranvash_MagicAttackA01.ogg",
		"Taranvash_MagicAttackB01.ogg",
		"Taranvash_MagicAttackB02.ogg",
		"Taranvash_SpecialAttackA01.ogg",
		"Taranvash_SpecialAttackA02.ogg",
		"Taranvash_SpecialAttackB01.ogg",
		"Taranvash_SpecialAttackC01.ogg",
		"Taranvash_DashEnd.ogg",
		"Taranvash_Fake_WaitStart01.ogg",
	},

	READY_XMESH = 
	{
		"Thief_Fat_JumpAttackA_Stone02.Y",
		"Lire_Uplight01.Y",
		"Water_Impact01.Y",
		"Laser_Impact01.Y",
		"Jump_Wind01.Y",
		"Cube_Gray01.Y",
		"Arme_ChargeMp2.Y",
	},
	
	READY_XSKIN_MESH = 
	{
		"Taranvash_AttackA_Mesh01.X",
		"Taranvash_AttackA_Mesh02.X",
		"Taranvash_StandUpAttackFront_Mesh01.X",
		"Taranvash_MagicAttackA_Mesh01.X",
		"DummyAttackBox_50x50x50.X",
		"Taranvash_SpecialAttackA_Mesh01.X",
		"Taranvash_SpecialAttackA_Mesh02.X",
		"Taranvash_SpecialAttackA_Mesh03.X",
		"Taranvash_SpecialAttackC_Mesh01.X",
		"FlowWind01.X",
		"Taranvash_MirrorImageOn_Mesh01.X",
		"Taranvash_MirrorImageOn_Mesh02.X",
	},

}

INIT_MOTION = 
{
	MOTION_FILE_NAME		= "Motion_TARANVASH.x",
	MOTION_MULTI_TEX_XET	= "Taranvash.xet",
	MULTI_TEX_SPEED			= { 2, 0, 0.5, },
}

INIT_PHYSIC = 
{
	RELOAD_ACCEL		= 2000,
	G_ACCEL				= 4000,
	MAX_G_SPEED			= -5000,
	
	WALK_SPEED			= 300,
	RUN_SPEED			= 700,
	JUMP_SPEED			= 2000,
	DASH_JUMP_SPEED		= 2300,
}


INIT_COMPONENT = 
{
	IMMUNITY_TIME_STOP = TRUE,
	--HP_CHANGE_RATE		= 500,
	MP_CHANGE_RATE		= 1,
	MP_CHARGE_RATE		= 130,

	
	SHADOW_SIZE			= 300,
	SHADOW_FILE_NAME	= "shadow.dds",
	
	SMALL_HP_BAR_BLUE	= "Small_HP_bar_Blue.TGA",
	SMALL_HP_BAR_RED	= "Small_HP_bar_Red.TGA",
	SMALL_HP_BAR_YELLOW = "Small_HP_bar_Yellow.TGA",
	
	QUESTION_MARK_SEQ		= "QuestionMarkNPC",
	EXCLAMATION_MARK_SEQ	= "ExclamationMarkNPC",
	--MIND_FLAG_HEIGHT		= 230,
	HEAD_BONE_NAME			= "Bip01_Head",
		
	--NOT_CULL  = TRUE,
  	
	RAGE_COUNT_MAX		= 30,
	RAGE_TIME_MAX		= 5,
		
	HITTED_TYPE			= HITTED_TYPE["HTD_MEAT"],
	FALL_DOWN			= TRUE,
	DIE_FLY				= 0,

}

INIT_STATE = 
{
	{ STATE_NAME = "TARANVASH_FAKE_WAITSTART",						},
	
	{ STATE_NAME = "TARANVASH_FAKE_WIN",							},
	
	{ STATE_NAME = "TARANVASH_FAKE_WAIT",							},
	
	{ STATE_NAME = "TARANVASH_FAKE_WALK",							LUA_STATE_END_FUNC = "TARANVASH_FAKE_WALK_STATE_END",							},

	
	{ STATE_NAME = "TARANVASH_FAKE_DASH",							},
	{ STATE_NAME = "TARANVASH_FAKE_DASH_END",						},		
	

	{ STATE_NAME = "TARANVASH_FAKE_JUMP_UP_READY",					},
	{ STATE_NAME = "TARANVASH_FAKE_JUMP_UP",							},
	{ STATE_NAME = "TARANVASH_FAKE_JUMP_DOWN",						LUA_STATE_END_FUNC = "TARANVASH_FAKE_JUMP_DOWN_STATE_END",			},
	{ STATE_NAME = "TARANVASH_FAKE_JUMP_UP_DIR_READY",				},
	{ STATE_NAME = "TARANVASH_FAKE_JUMP_UP_DIR",						},
	{ STATE_NAME = "TARANVASH_FAKE_JUMP_DOWN_DIR",					LUA_STATE_END_FUNC = "TARANVASH_FAKE_JUMP_DOWN_DIR_STATE_END",	},
	{ STATE_NAME = "TARANVASH_FAKE_JUMP_LANDING",					},	
	
	{ STATE_NAME = "TARANVASH_FAKE_STAND_UP_ATTACK_FRONT",			},
	{ STATE_NAME = "TARANVASH_FAKE_STAND_UP_ATTACK_BACK",			},
	{ STATE_NAME = "TARANVASH_FAKE_ATTACKA",							LUA_FRAME_MOVE_FUNC = "TARANVASH_FAKE_ATTACKA_FRAME_MOVE", },
	
	{ STATE_NAME = "TARANVASH_FAKE_MAGICATTACKA",					},
	{ STATE_NAME = "TARANVASH_FAKE_MAGICATTACKB",					},
	{ STATE_NAME = "TARANVASH_FAKE_SPECIALATTACK_A",					},
	{ STATE_NAME = "TARANVASH_FAKE_SPECIALATTACK_B",					STATE_COOL_TIME	= 20, },
	{ STATE_NAME = "TARANVASH_FAKE_SPECIALATTACK_C",					LUA_FRAME_MOVE_FUNC		= "TARANVASH_FAKE_SPECIALATTACK_C_FRAME_MOVE",		},
	{ STATE_NAME = "TARANVASH_FAKE_SPECIALATTACK_C_COMBO",			LUA_STATE_START_FUNC	= "TARANVASH_FAKE_SPECIALATTACK_C_COMBO_STATE_START",
																LUA_FRAME_MOVE_FUNC		= "TARANVASH_FAKE_SPECIALATTACK_C_COMBO_FRAME_MOVE",	},
	
	--리액션 관련
	{ STATE_NAME = "TARANVASH_FAKE_DAMAGE_FRONT",					LUA_FRAME_MOVE_FUNC = "TARANVASH_FAKE_DAMAGE_FRONT_FRAME_MOVE"				},
	{ STATE_NAME = "TARANVASH_FAKE_DAMAGE_BACK",						LUA_FRAME_MOVE_FUNC = "TARANVASH_FAKE_DAMAGE_BACK_FRAME_MOVE"				},
	{ STATE_NAME = "TARANVASH_FAKE_DAMAGE_DOWN_FRONT",				LUA_FRAME_MOVE_FUNC = "TARANVASH_FAKE_DAMAGE_DOWN_FRONT_FRAME_MOVE"			},
	{ STATE_NAME = "TARANVASH_FAKE_DAMAGE_DOWN_BACK",				LUA_FRAME_MOVE_FUNC = "TARANVASH_FAKE_DAMAGE_DOWN_BACK_FRAME_MOVE"			},
	{ STATE_NAME = "TARANVASH_FAKE_DAMAGE_FLY_FRONT",				},
	{ STATE_NAME = "TARANVASH_FAKE_DAMAGE_FLY_BACK",					},
	{ STATE_NAME = "TARANVASH_FAKE_DAMAGE_AIR",						},
	{ STATE_NAME = "TARANVASH_FAKE_DAMAGE_AIR_DOWN",					},
	{ STATE_NAME = "TARANVASH_FAKE_DAMAGE_AIR_UP",					},
	{ STATE_NAME = "TARANVASH_FAKE_DAMAGE_AIR_FALL",					},
	{ STATE_NAME = "TARANVASH_FAKE_DAMAGE_AIR_DOWN_LANDING",			LUA_FRAME_MOVE_FUNC = "TARANVASH_FAKE_DAMAGE_AIR_DOWN_LANDING_FRAME_MOVE"	},
	
	{ STATE_NAME = "TARANVASH_FAKE_STAND_UP_FRONT",					},
	{ STATE_NAME = "TARANVASH_FAKE_STAND_UP_BACK",					},
	
	{ STATE_NAME = "TARANVASH_FAKE_DAMAGE_REVENGE",					},	
	
	
	{ STATE_NAME = "TARANVASH_FAKE_DYING_LAND_FRONT",				},
	{ STATE_NAME = "TARANVASH_FAKE_DYING_LAND_BACK",				},
	{ STATE_NAME = "TARANVASH_FAKE_DYING_SKY",						},
	
	
	
	START_STATE					= "TARANVASH_FAKE_WAITSTART",
	WAIT_STATE					= "TARANVASH_FAKE_WAIT",
	
	
	
	SMALL_DAMAGE_LAND_FRONT		= "TARANVASH_FAKE_DAMAGE_FRONT",
	SMALL_DAMAGE_LAND_BACK		= "TARANVASH_FAKE_DAMAGE_BACK",
	BIG_DAMAGE_LAND_FRONT		= "TARANVASH_FAKE_DAMAGE_FRONT",
	BIG_DAMAGE_LAND_BACK		= "TARANVASH_FAKE_DAMAGE_BACK",
	DOWN_DAMAGE_LAND_FRONT		= "TARANVASH_FAKE_DAMAGE_DOWN_FRONT",
	DOWN_DAMAGE_LAND_BACK		= "TARANVASH_FAKE_DAMAGE_DOWN_BACK",
	FLY_DAMAGE_FRONT			= "TARANVASH_FAKE_DAMAGE_FLY_FRONT",
	FLY_DAMAGE_BACK				= "TARANVASH_FAKE_DAMAGE_FLY_BACK",
	SMALL_DAMAGE_AIR			= "TARANVASH_FAKE_DAMAGE_AIR",	
	BIG_DAMAGE_AIR				= "TARANVASH_FAKE_DAMAGE_AIR",
	DOWN_DAMAGE_AIR				= "TARANVASH_FAKE_DAMAGE_AIR_DOWN",
	DOWN_DAMAGE_AIR_LANDING				= "TARANVASH_FAKE_DAMAGE_AIR_DOWN_LANDING",
	UP_DAMAGE					= "TARANVASH_FAKE_DAMAGE_AIR_UP",
	DAMAGE_REVENGE				= "TARANVASH_FAKE_DAMAGE_REVENGE",
	
	DAMAGE_EXTRA_STATES         = { "TARANVASH_FAKE_DAMAGE_AIR_FALL","TARANVASH_FAKE_STAND_UP_FRONT","TARANVASH_FAKE_STAND_UP_BACK",
		"TARANVASH_FAKE_STAND_UP_ATTACK_FRONT","TARANVASH_FAKE_STAND_UP_ATTACK_BACK",
		"TARANVASH_FAKE_JUMP_DOWN","TARANVASH_FAKE_JUMP_LANDING",},	
	
	DYING_LAND_FRONT			= "TARANVASH_FAKE_DYING_LAND_FRONT",
	DYING_LAND_BACK				= "TARANVASH_FAKE_DYING_LAND_BACK",
	DYING_SKY					= "TARANVASH_FAKE_DYING_SKY",

	REVENGE_ATTACK				= "",	
	
	COMMON_FRAME_FUNC			= "TARANVASH_FAKE_COMMON_FRAME_MOVE",
}



INIT_AI = 
{
	TARGET = 
	{
		TARGET_PRIORITY 			= TARGET_PRIORITY["TP_LOW_HP_FIRST"],
		TARGET_INTERVAL				= 2,		-- sec
		TARGET_NEAR_RANGE			= 8000,		-- 이 거리보다 가까우면 TARGET_SUCCESS_RATE에 관계없이 무조건 타게팅된다
		TARGET_RANGE				= 9000,		-- cm
		TARGET_LOST_RANGE			= 9000,		-- cm
		TARGET_SUCCESS_RATE			= 100,  --50,		-- %
		ATTACK_TARGET_RATE			= 100, -- 30,		-- 나를 공격한 유닛을 타게팅할 확률
		PRESERVE_LAST_TARGET_RATE	= 100, -- 30,		-- 이전에 타게팅된 유닛을 계속 타게팅할 확률
	},

	CHASE_MOVE = 
	{		
		MOVE_SPLIT_RANGE	= 1000,
		DEST_GAP			= 400,	
		MOVE_GAP			= 600,
		
		DIR_CHANGE_INTERVAL = 0.1,
		
		WALK_INTERVAL		= 1,
		NEAR_WALK_RATE		= 60,   --  70,
		FAR_WALK_RATE		= 50,   -- 30,
		
		JUMP_INTERVAL		= 5,
		UP_JUMP_RATE		= 0, -- 40,
		UP_DOWN_RATE		= 20,
		DOWN_JUMP_RATE		= 100,    --  20,
		DOWN_DOWN_RATE		= 40,
		
		LINE_END_RANGE		= 80,	-- cm
	},	
	
	PATROL_MOVE = 	
	{
		PATROL_BEGIN_RATE		= 100, --50,		
		PATROL_RANGE			= 200,
		PATROL_COOL_TIME		= 2,
		ONLY_THIS_LINE_GROUP	= TRUE,
	},
	
	ESCAPE_MOVE = 
	{		
		MOVE_SPLIT_RANGE	= 500,	-- cm
		ESCAPE_GAP			= 600,	-- 이 거리 보다 멀어지면 도망 성공
		
		WALK_INTERVAL		= 1.5,	-- 초
		NEAR_WALK_RATE		= 100,   --  10,
		FAR_WALK_RATE		= 100,   -- 10,
		
		JUMP_INTERVAL		= 10,
		UP_JUMP_RATE		= 100, -- 30,
		UP_DOWN_RATE		= 30,
		DOWN_JUMP_RATE		= 100,    --  30,
		DOWN_DOWN_RATE		= 30,
		
		LINE_END_RANGE		= 80,	-- cm
	},

}






TARANVASH_FAKE_WAITSTART = 
{
	ANIM_NAME					= "Win",
	PLAY_TYPE					= XSKIN_ANIM_PLAYTYPE["XAP_LOOP"],
	TRANSITION					= FALSE,
	
	CAN_PUSH_UNIT				= FALSE,
	CAN_PASS_UNIT				= TRUE,
	
	INVINCIBLE					= { 0, 100, }, 		

	IMMADIATE_PACKET_SEND		= TRUE,	
	
	SOUND_PLAY0					= { 0.01, "Taranvash_Fake_WaitStart01.ogg" },
		
	EVENT_PROCESS = 
	{		
		{ STATE_CHANGE_TYPE["SCT_MOTION_END"],				"TARANVASH_FAKE_WAIT",	},
	},
	
	EFFECT_SET_LIST =
	{
		"EFFECTSET_TARANVASH_MIRRORIMAGEON", 0.0,
	},
	DELETE_EFFECT_SET_ON_STATE_END = TRUE,	
}


TARANVASH_FAKE_WIN =
{
	ANIM_NAME					= "Win",
	PLAY_TYPE					= XSKIN_ANIM_PLAYTYPE["XAP_ONE_WAIT"],
	TRANSITION					= TRUE,
	
	INVINCIBLE					= { 0, 100, },
	
	CAN_PUSH_UNIT				= FALSE,
	CAN_PASS_UNIT				= FALSE,	
	
	SPEED_X = 0,
	SPEED_Y = 0,
	
	NEVER_MOVE					= TRUE,
	RIGHT						= TRUE,

	IMMADIATE_PACKET_SEND		= TRUE,
	
}

TARANVASH_FAKE_WAIT = 
{
	ANIM_NAME					= "Wait",
	PLAY_TYPE					= XSKIN_ANIM_PLAYTYPE["XAP_LOOP"],
	TRANSITION					= FALSE,
	
	CAN_PUSH_UNIT				= FALSE,
	CAN_PASS_UNIT				= FALSE,	
	
	SPEED_X						= 0,
	SPEED_Y						= 0,
	
	SHOW						= TRUE,
	
	PASSIVE_SPEED_X				= 0,
	VIEW_TARGET					  = TRUE,
	ALLOW_DIR_CHANGE			= TRUE,
	
	IMMADIATE_PACKET_SEND		= TRUE,
	EVENT_INTERVAL_TIME0		= 0.2,
	
	EVENT_PROCESS = 
	{		
		{ STATE_CHANGE_TYPE["SCT_CONDITION_FUNCTION"],		"TARANVASH_FAKE_WIN",						"CF_TARANVASH_FAKE_WIN",	},	
		
		{ STATE_CHANGE_TYPE["SCT_FOOT_ON_LINE_FALSE_DOWN"],	"TARANVASH_FAKE_JUMP_DOWN",					},
		
		{ STATE_CHANGE_TYPE["SCT_CONDITION_TABLE"],			"TARANVASH_FAKE_ATTACKA",						"CT_TARANVASH_FAKE_ATTACKA",				},	
		{ STATE_CHANGE_TYPE["SCT_CONDITION_TABLE"],			"TARANVASH_FAKE_MAGICATTACKA",					"CT_TARANVASH_FAKE_MAGICATTACKA",		},	
		{ STATE_CHANGE_TYPE["SCT_CONDITION_TABLE"],			"TARANVASH_FAKE_MAGICATTACKB",					"CT_TARANVASH_FAKE_MAGICATTACKB",		},	
		{ STATE_CHANGE_TYPE["SCT_CONDITION_TABLE"],			"TARANVASH_FAKE_SPECIALATTACK_A",				"CT_TARANVASH_FAKE_SPECIALATTACK_A",		},	
		{ STATE_CHANGE_TYPE["SCT_CONDITION_TABLE"],			"TARANVASH_FAKE_SPECIALATTACK_B",				"CT_TARANVASH_FAKE_SPECIALATTACK_B",		},	
		{ STATE_CHANGE_TYPE["SCT_CONDITION_TABLE"],			"TARANVASH_FAKE_SPECIALATTACK_C",				"CT_TARANVASH_FAKE_SPECIALATTACK_C",		},	
		


		
		{ STATE_CHANGE_TYPE["SCT_AI_WALK"],					"TARANVASH_FAKE_WALK",						},
		{ STATE_CHANGE_TYPE["SCT_AI_DASH"],					"TARANVASH_FAKE_DASH",						},
		{ STATE_CHANGE_TYPE["SCT_AI_JUMP"],					"TARANVASH_FAKE_JUMP_UP_READY",				},
		{ STATE_CHANGE_TYPE["SCT_AI_JUMP_DIR"],				"TARANVASH_FAKE_JUMP_UP_DIR_READY",			},
		{ STATE_CHANGE_TYPE["SCT_AI_DOWN"],					"TARANVASH_FAKE_JUMP_DOWN",					},
		{ STATE_CHANGE_TYPE["SCT_AI_DOWN_DIR"],				"TARANVASH_FAKE_JUMP_DOWN_DIR",				},
	},

	CT_TARANVASH_FAKE_ATTACKA = 
	{
		EVENT_INTERVAL_ID			= 0,
		DISTANCE_TO_TARGET_NEAR		= 800,
		RATE						= 30,
	},	
	CT_TARANVASH_FAKE_MAGICATTACKA = 
	{
		EVENT_INTERVAL_ID			= 0,
		DISTANCE_OVER_TARGET_NEAR	= 800,
		RATE						= 30,
	},	
	CT_TARANVASH_FAKE_MAGICATTACKB = 
	{
		EVENT_INTERVAL_ID			= 0,
		DISTANCE_TO_TARGET_NEAR		= 800,
		RATE						= 30,
	},	
	CT_TARANVASH_FAKE_SPECIALATTACK_A = 
	{
		EVENT_INTERVAL_ID			= 0,
		DISTANCE_OVER_TARGET_NEAR	= 500,
		RATE						= 30,
	},	
	CT_TARANVASH_FAKE_SPECIALATTACK_B = 
	{
		EVENT_INTERVAL_ID			= 0,
		DISTANCE_OVER_TARGET_NEAR	= 1000,
		RATE						= 30,
	},
	CT_TARANVASH_FAKE_SPECIALATTACK_C = 
	{
		EVENT_INTERVAL_ID			= 0,
		DISTANCE_OVER_TARGET_NEAR	= 800,
		RATE						= 30,
	},	
	
	

}


TARANVASH_FAKE_WALK = 
{
	ANIM_NAME					= "Walk",
	PLAY_TYPE					= XSKIN_ANIM_PLAYTYPE["XAP_LOOP"],
	TRANSITION					= FALSE,
	
	CAN_PUSH_UNIT				= FALSE,
	CAN_PASS_UNIT				= FALSE,
	
	PASSIVE_SPEED_X				= INIT_PHYSIC["WALK_SPEED"],
	
	ALLOW_DIR_CHANGE			= TRUE,
	IMMADIATE_PACKET_SEND		= TRUE,
	
	EVENT_INTERVAL_TIME0		= 0.2,
	EVENT_INTERVAL_TIME1		= 3,
	
	EVENT_PROCESS = 
	{		
		{ STATE_CHANGE_TYPE["SCT_CONDITION_FUNCTION"],		"TARANVASH_FAKE_WIN",							"CF_TARANVASH_FAKE_WIN",	},	
		
		{ STATE_CHANGE_TYPE["SCT_FOOT_ON_LINE_FALSE_DOWN"],	"TARANVASH_FAKE_JUMP_DOWN_DIR",				},
		
		{ STATE_CHANGE_TYPE["SCT_AI_WAIT"],					"TARANVASH_FAKE_WAIT",						},
		{ STATE_CHANGE_TYPE["SCT_AI_DASH"],					"TARANVASH_FAKE_DASH",						},
		{ STATE_CHANGE_TYPE["SCT_AI_JUMP"],					"TARANVASH_FAKE_JUMP_UP_READY",					},
		{ STATE_CHANGE_TYPE["SCT_AI_JUMP_DIR"],				"TARANVASH_FAKE_JUMP_UP_DIR_READY",				},
		{ STATE_CHANGE_TYPE["SCT_AI_DOWN"],					"TARANVASH_FAKE_JUMP_DOWN",					},
		{ STATE_CHANGE_TYPE["SCT_AI_DOWN_DIR"],				"TARANVASH_FAKE_JUMP_DOWN_DIR",				},
	},
	

	
}


TARANVASH_FAKE_DASH = 
{
	ANIM_NAME					= "Dash",
	PLAY_TYPE					= XSKIN_ANIM_PLAYTYPE["XAP_LOOP"],
	TRANSITION					= FALSE,

	LAND_CONNECT					= FALSE,
	
	--SUPER_ARMOR					= TRUE,

	CAN_PUSH_UNIT				= FALSE,
	CAN_PASS_UNIT				= FALSE,
	
	SOUND_PLAY0			= { 0.59, "Landing_RawMeat01.ogg" },
	SOUND_PLAY1			= { 0.30, "Landing_RawMeat02.ogg" },
	
	PASSIVE_SPEED_X				= 1200,
	
	ALLOW_DIR_CHANGE			= FALSE,
	IMMADIATE_PACKET_SEND		= TRUE,
	
	EVENT_INTERVAL_TIME0		= 2,
	EVENT_PROCESS = 
	{		
		{ STATE_CHANGE_TYPE["SCT_FOOT_ON_LINE_FALSE_DOWN"],		"TARANVASH_FAKE_JUMP_DOWN_DIR",			},				
		{ STATE_CHANGE_TYPE["SCT_AI_WAIT"],						"TARANVASH_FAKE_DASH_END",				},
		{ STATE_CHANGE_TYPE["SCT_CONDITION_FUNCTION"],			"TARANVASH_FAKE_DASH_END",						"CF_TARANVASH_FAKE_DASH_END",				},
	},
	
}





TARANVASH_FAKE_DASH_END = 
{
	ANIM_NAME					= "DashEnd",
	PLAY_TYPE					= XSKIN_ANIM_PLAYTYPE["XAP_ONE_WAIT"],
	TRANSITION					= FALSE,
	
	LAND_CONNECT				= FALSE,

	CAN_PUSH_UNIT				= FALSE,
	CAN_PASS_UNIT				= FALSE,
	
	SOUND_PLAY0					= { 0.001, "Taranvash_DashEnd.ogg" },
	
	SPEED_X						= 0,
	
	ALLOW_DIR_CHANGE			= FALSE,
	IMMADIATE_PACKET_SEND		= TRUE,
	
	ATTACK_TIME0				= { 0, 0.34, },
	DISABLE_ATTACK_BOX = 
	{		
		--"RHand",
		--"LHand",
		"Tail01",
		"Tail02",
		
	},
	
	DAMAGE_DATA = 
	{
		DAMAGE_TYPE		= DAMAGE_TYPE["DT_PHYSIC"],
		HIT_TYPE		= HIT_TYPE["HT_PUNCH_HIT"],
		REACT_TYPE		= REACT_TYPE["RT_BIG_DAMAGE"],
		
		DAMAGE = 
		{
			PHYSIC		= 1,
		},
		
		BACK_SPEED_X			= 700,
		BACK_SPEED_Y			= 0,
		
		CAMERA_CRASH_GAP		= 5.0,	
		CAMERA_CRASH_TIME		= 0.2,	

		RE_ATTACK				= FALSE,		
		HIT_GAP					= 00,		
	},
	
	EVENT_PROCESS = 
	{		
		--{ STATE_CHANGE_TYPE["SCT_FOOT_ON_LINE_FALSE_DOWN"],	"TARANVASH_FAKE_JUMP_DOWN_DIR",				},
		{ STATE_CHANGE_TYPE["SCT_MOTION_END"],				"TARANVASH_FAKE_WAIT",						},
	},
}


TARANVASH_FAKE_JUMP_UP_READY = 
{
	ANIM_NAME					= "JumpReady",
	PLAY_TYPE					= XSKIN_ANIM_PLAYTYPE["XAP_LOOP"],
	TRANSITION					= TRUE,
	LAND_CONNECT				= FALSE,
	
	CAN_PUSH_UNIT				= FALSE,
	CAN_PASS_UNIT				= FALSE,
	
	SPEED_X						= 0,
	SPEED_Y						= 0,
	
	
	IMMADIATE_PACKET_SEND		= TRUE,
	
	EVENT_PROCESS = 
	{		
		{ STATE_CHANGE_TYPE["SCT_MOTION_END"],				"TARANVASH_FAKE_JUMP_UP",						},
	},
	
}

TARANVASH_FAKE_JUMP_UP = 
{
	ANIM_NAME					= "JumpUp",
	PLAY_TYPE					= XSKIN_ANIM_PLAYTYPE["XAP_LOOP"],
	TRANSITION					= TRUE,
	LAND_CONNECT				= FALSE,
	
	CAN_PUSH_UNIT				= FALSE,
	CAN_PASS_UNIT				= FALSE,	
	
	SPEED_X						= 0,
	SPEED_Y						= INIT_PHYSIC["JUMP_SPEED"],
	
	IMMADIATE_PACKET_SEND		= TRUE,
	
	EVENT_PROCESS = 
	{		
		{ STATE_CHANGE_TYPE["SCT_NEGATIVE_Y_SPEED"],		"TARANVASH_FAKE_JUMP_DOWN",			},
	},
}

TARANVASH_FAKE_JUMP_DOWN = 
{
	ANIM_NAME					= "JumpDown",
	PLAY_TYPE					= XSKIN_ANIM_PLAYTYPE["XAP_LOOP"],
	TRANSITION					= TRUE,
	LAND_CONNECT				= FALSE,
	
	CAN_PUSH_UNIT				= FALSE,
	CAN_PASS_UNIT				= FALSE,
		 
	
	IMMADIATE_PACKET_SEND		= TRUE,
		
	EVENT_PROCESS = 
	{		
		{ STATE_CHANGE_TYPE["SCT_FOOT_ON_LINE_TRUE"],		"TARANVASH_FAKE_JUMP_LANDING",				},
	},
}

TARANVASH_FAKE_JUMP_UP_DIR_READY = 
{
	ANIM_NAME					= "JumpReady",
	PLAY_TYPE					= XSKIN_ANIM_PLAYTYPE["XAP_LOOP"],
	TRANSITION					= TRUE,
	LAND_CONNECT				= FALSE,
	
	CAN_PUSH_UNIT				= FALSE,
	CAN_PASS_UNIT				= FALSE,
		
	
	SPEED_X						= 0,
	SPEED_Y						= 0,
	
	
	IMMADIATE_PACKET_SEND		= TRUE,
	
	EVENT_PROCESS = 
	{		
		{ STATE_CHANGE_TYPE["SCT_MOTION_END"],				"TARANVASH_FAKE_JUMP_UP_DIR",						},
	},
	
}

TARANVASH_FAKE_JUMP_UP_DIR = 
{
	ANIM_NAME					= "JumpUp",
	PLAY_TYPE					= XSKIN_ANIM_PLAYTYPE["XAP_LOOP"],
	TRANSITION					= TRUE,
	LAND_CONNECT				= FALSE,
	
	CAN_PUSH_UNIT				= FALSE,
	CAN_PASS_UNIT				= FALSE,
		
	PASSIVE_SPEED_X				= INIT_PHYSIC["WALK_SPEED"],
	SPEED_Y						= INIT_PHYSIC["JUMP_SPEED"],
			
	IMMADIATE_PACKET_SEND		= TRUE,
	
	EVENT_PROCESS = 
	{		
		{ STATE_CHANGE_TYPE["SCT_NEGATIVE_Y_SPEED"],		"TARANVASH_FAKE_JUMP_DOWN_DIR",				},
	},
	
}

TARANVASH_FAKE_JUMP_DOWN_DIR = 
{
	ANIM_NAME					= "JumpDown",
	PLAY_TYPE					= XSKIN_ANIM_PLAYTYPE["XAP_LOOP"],
	TRANSITION					= TRUE,
	LAND_CONNECT				= FALSE,
	
	CAN_PUSH_UNIT				= FALSE,
	CAN_PASS_UNIT				= FALSE,
	
	PASSIVE_SPEED_X				= INIT_PHYSIC["WALK_SPEED"],
	 
	
	IMMADIATE_PACKET_SEND		= TRUE,
		
	EVENT_PROCESS = 
	{		
		{ STATE_CHANGE_TYPE["SCT_FOOT_ON_LINE_TRUE"],		"TARANVASH_FAKE_JUMP_LANDING",				},
	},
}

TARANVASH_FAKE_JUMP_LANDING = 
{
	ANIM_NAME					= "JumpLanding",
	PLAY_TYPE					= XSKIN_ANIM_PLAYTYPE["XAP_ONE_WAIT"],
	TRANSITION					= TRUE,
	LAND_CONNECT				= FALSE,
	
	CAN_PUSH_UNIT				= FALSE,
	CAN_PASS_UNIT				= FALSE,
	
	SOUND_PLAY0					= { 0.01, "Landing_Big_Metal01.ogg" },

	SPEED_X						= 0,
	SPEED_Y						= 0,

	IMMADIATE_PACKET_SEND		= TRUE,

	EVENT_PROCESS = 
	{		
		{ STATE_CHANGE_TYPE["SCT_FOOT_ON_LINE_FALSE_DOWN"],	"TARANVASH_FAKE_JUMP_DOWN",				},
		{ STATE_CHANGE_TYPE["SCT_MOTION_END"],				"TARANVASH_FAKE_WAIT",						},
	},
}


TARANVASH_FAKE_DAMAGE_REVENGE = 
{
	ANIM_NAME					= "DamageRevenge",
	PLAY_TYPE					= XSKIN_ANIM_PLAYTYPE["XAP_ONE_WAIT"],
	TRANSITION					= FALSE,
	LAND_CONNECT				= FALSE,
	
	CAN_PUSH_UNIT				= FALSE,
	CAN_PASS_UNIT				= FALSE,
	
	CUSTOM_STATE_DELETE_EFFECT_SET	= TRUE,
	
	
	EVENT_PROCESS = 
	{
		{ STATE_CHANGE_TYPE["SCT_MOTION_END"],					"TARANVASH_FAKE_WAIT",												},
	},
}


TARANVASH_FAKE_DAMAGE_FRONT = 
{
	ANIM_NAME					= "DamageFront",
	PLAY_TYPE					= XSKIN_ANIM_PLAYTYPE["XAP_ONE_WAIT"],
	TRANSITION					= FALSE,
	LAND_CONNECT				= FALSE,
	
	CAN_PUSH_UNIT				= FALSE,
	CAN_PASS_UNIT				= FALSE,
	
	EVENT_PROCESS = 
	{
		{ STATE_CHANGE_TYPE["SCT_MOTION_END"],					"TARANVASH_FAKE_WAIT",												},
	},
}

TARANVASH_FAKE_DAMAGE_BACK = 
{
	ANIM_NAME					= "DamageBack",
	PLAY_TYPE					= XSKIN_ANIM_PLAYTYPE["XAP_ONE_WAIT"],
	TRANSITION					= FALSE,
	LAND_CONNECT				= FALSE,
	
	CAN_PUSH_UNIT				= FALSE,
	CAN_PASS_UNIT				= FALSE,

	
	EVENT_PROCESS = 
	{
		{ STATE_CHANGE_TYPE["SCT_MOTION_END"],					"TARANVASH_FAKE_WAIT",												},
	},
}





TARANVASH_FAKE_DAMAGE_DOWN_FRONT = 
{
	ANIM_NAME					= "DamageDownFront",
	PLAY_TYPE					= XSKIN_ANIM_PLAYTYPE["XAP_ONE_WAIT"],
	TRANSITION					= FALSE,
	LAND_CONNECT				= FALSE,

	SUPER_ARMOR					= TRUE,
	DEFENCE						= { 0, 100, 70, },

    SOUND_PLAY0			= { 0.275, "UnohoundVoice_Damage.ogg" , 24 },
	SOUND_PLAY1			= { 0.322, "Unohound_StandUp1.ogg" },
	
	CAN_PUSH_UNIT				= FALSE,
	CAN_PASS_UNIT				= FALSE,

	
	EVENT_PROCESS = 
	{
		{ STATE_CHANGE_TYPE["SCT_FOOT_ON_LINE_FALSE_DOWN"],		"TARANVASH_FAKE_DAMAGE_AIR_FALL",			},
		{ STATE_CHANGE_TYPE["SCT_CONDITION_TABLE"],				"TARANVASH_FAKE_STAND_UP_ATTACK_FRONT",	"CT_TARANVASH_FAKE_STAND_UP_ATTACK_FRONT", },
		{ STATE_CHANGE_TYPE["SCT_MOTION_END"],					"TARANVASH_FAKE_STAND_UP_FRONT",			},
	},
	
	CT_TARANVASH_FAKE_STAND_UP_ATTACK_FRONT = 
	{
		ANIM_PLAY_COUNT		= 1,
		RATE				= 30,
	},
}

TARANVASH_FAKE_DAMAGE_DOWN_BACK = 
{
	ANIM_NAME					= "DamageDownBack",
	PLAY_TYPE					= XSKIN_ANIM_PLAYTYPE["XAP_ONE_WAIT"],
	TRANSITION					= FALSE,
	LAND_CONNECT				= FALSE,
	
	SUPER_ARMOR					= TRUE,
	DEFENCE						= { 0, 100, 70, },

    SOUND_PLAY0			= { 0.275, "UnohoundVoice_Damage.ogg" , 24 },
	SOUND_PLAY1			= { 0.421, "Unohound_StandUp1.ogg" },
	
	CAN_PUSH_UNIT				= FALSE,
	CAN_PASS_UNIT				= FALSE,
	
	EVENT_PROCESS = 
	{
		{ STATE_CHANGE_TYPE["SCT_FOOT_ON_LINE_FALSE_DOWN"],		"TARANVASH_FAKE_DAMAGE_AIR_FALL",			},
		{ STATE_CHANGE_TYPE["SCT_CONDITION_TABLE"],				"TARANVASH_FAKE_STAND_UP_ATTACK_BACK",	"CT_TARANVASH_FAKE_STAND_UP_ATTACK_BACK", },
		{ STATE_CHANGE_TYPE["SCT_MOTION_END"],					"TARANVASH_FAKE_STAND_UP_BACK",			},
	},
	
	CT_TARANVASH_FAKE_STAND_UP_ATTACK_BACK = 
	{
		ANIM_PLAY_COUNT		= 1,
		RATE				= 30,
	},
}

TARANVASH_FAKE_DAMAGE_FLY_FRONT = 
{
	ANIM_NAME					= "DamageFlyFront",
	PLAY_TYPE					= XSKIN_ANIM_PLAYTYPE["XAP_ONE_WAIT"],
	TRANSITION					= TRUE,
	LAND_CONNECT				= FALSE,	
	
	
	CAN_PUSH_UNIT				= FALSE,
	CAN_PASS_UNIT				= FALSE,
	
	EVENT_PROCESS = 
	{
		{ STATE_CHANGE_TYPE["SCT_FOOT_ON_LINE_TRUE"],			"TARANVASH_FAKE_DAMAGE_AIR_DOWN_LANDING",		},
	},
}

TARANVASH_FAKE_DAMAGE_FLY_BACK = 
{
	ANIM_NAME					= "DamageFlyBack",
	PLAY_TYPE					= XSKIN_ANIM_PLAYTYPE["XAP_ONE_WAIT"],
	TRANSITION					= FALSE,
	LAND_CONNECT				= FALSE,	
	
	CAN_PUSH_UNIT				= FALSE,
	CAN_PASS_UNIT				= FALSE,
	
	EVENT_PROCESS = 
	{
		{ STATE_CHANGE_TYPE["SCT_FOOT_ON_LINE_TRUE"],			"TARANVASH_FAKE_DAMAGE_DOWN_BACK",		},
	},
}

TARANVASH_FAKE_DAMAGE_AIR = 
{
	ANIM_NAME					= "DamageAirSmall",
	PLAY_TYPE					= XSKIN_ANIM_PLAYTYPE["XAP_ONE_WAIT"],
	TRANSITION					= FALSE,
	LAND_CONNECT				= FALSE,
	
	CAN_PUSH_UNIT				= FALSE,
	CAN_PASS_UNIT				= FALSE,
	
	EVENT_PROCESS = 
	{
		{ STATE_CHANGE_TYPE["SCT_FOOT_ON_LINE_TRUE"],			"TARANVASH_FAKE_WAIT",					},
	},
	
	VIEW_TARGET					= TRUE,
	ALLOW_DIR_CHANGE			= TRUE,
}

TARANVASH_FAKE_DAMAGE_AIR_DOWN = 
{
	ANIM_NAME					= "DamageAirDown",
	PLAY_TYPE					= XSKIN_ANIM_PLAYTYPE["XAP_ONE_WAIT"],
	TRANSITION					= FALSE,
	LAND_CONNECT				= FALSE,
	
	CAN_PUSH_UNIT				= FALSE,
	CAN_PASS_UNIT				= FALSE,
	
--	SOUND_PLAY0			= { 0.001, "Unohound_DamageAirDown.ogg" },
	
	EVENT_PROCESS = 
	{
		{ STATE_CHANGE_TYPE["SCT_FOOT_ON_LINE_TRUE"],			"TARANVASH_FAKE_DAMAGE_AIR_DOWN_LANDING",	},
	},
}

TARANVASH_FAKE_DAMAGE_AIR_UP = 
{
	ANIM_NAME					= "DamageAirUp",
	PLAY_TYPE					= XSKIN_ANIM_PLAYTYPE["XAP_ONE_WAIT"],
	TRANSITION					= FALSE,
	LAND_CONNECT				= FALSE,
	
	CAN_PUSH_UNIT				= FALSE,
	CAN_PASS_UNIT				= FALSE,
	
	PASSIVE_SPEED_Y				= -1,
	SPEED_Y						= INIT_PHYSIC["JUMP_SPEED"] * 0.6,
	
		
	EVENT_PROCESS = 
	{
		{ STATE_CHANGE_TYPE["SCT_NEGATIVE_Y_SPEED"],		"TARANVASH_FAKE_DAMAGE_AIR_FALL",			},
		{ STATE_CHANGE_TYPE["SCT_FOOT_ON_LINE_TRUE"],		"TARANVASH_FAKE_DAMAGE_AIR_DOWN_LANDING",	},
	},
}

TARANVASH_FAKE_DAMAGE_AIR_FALL = 
{
	ANIM_NAME					= "DamageAirFall",
	PLAY_TYPE					= XSKIN_ANIM_PLAYTYPE["XAP_ONE_WAIT"],
	TRANSITION					= FALSE,
	LAND_CONNECT				= FALSE,
	
	CAN_PUSH_UNIT				= FALSE,
	CAN_PASS_UNIT				= FALSE,
	
	EVENT_PROCESS = 
	{
		{ STATE_CHANGE_TYPE["SCT_POSITIVE_Y_SPEED"],		"TARANVASH_FAKE_DAMAGE_AIR_UP",			},
		{ STATE_CHANGE_TYPE["SCT_FOOT_ON_LINE_TRUE"],		"TARANVASH_FAKE_DAMAGE_AIR_DOWN_LANDING",	},
	},
}

TARANVASH_FAKE_DAMAGE_AIR_DOWN_LANDING = 
{
	ANIM_NAME					= "DamageAirDownLanding",
	PLAY_TYPE					= XSKIN_ANIM_PLAYTYPE["XAP_ONE_WAIT"],
	TRANSITION					= FALSE,
	LAND_CONNECT				= FALSE,
	
	SUPER_ARMOR					= TRUE,
	DEFENCE						= { 0, 100, 70, },

    SOUND_PLAY0			= { 0.103, "UnohoundVoice_Damage.ogg", 24 },
	SOUND_PLAY1			= { 0.040, "Unohound_DamageAirDownLanding.ogg" },
	
	CAN_PUSH_UNIT				= FALSE,
	CAN_PASS_UNIT				= FALSE,
	
	EVENT_PROCESS = 
	{
		{ STATE_CHANGE_TYPE["SCT_FOOT_ON_LINE_FALSE_DOWN"],	"TARANVASH_FAKE_DAMAGE_AIR_FALL",			},
		{ STATE_CHANGE_TYPE["SCT_CONDITION_TABLE"],			"TARANVASH_FAKE_STAND_UP_ATTACK_FRONT",	"CT_TARANVASH_FAKE_STAND_UP_ATTACK_FRONT", },
		{ STATE_CHANGE_TYPE["SCT_MOTION_END"],				"TARANVASH_FAKE_STAND_UP_FRONT",			},
	},
	
	CT_TARANVASH_FAKE_STAND_UP_ATTACK_FRONT = 
	{
		ANIM_PLAY_COUNT		= 1,
		RATE				= 30,
	},
	
}

TARANVASH_FAKE_STAND_UP_FRONT = 
{
	ANIM_NAME					= "DamageStandUpFront",
	PLAY_TYPE					= XSKIN_ANIM_PLAYTYPE["XAP_ONE_WAIT"],
	TRANSITION					= FALSE,
	LAND_CONNECT				= FALSE,	
	
	SUPER_ARMOR					= TRUE,
	DEFENCE						= { 0, 100, 70, },
	
	CAN_PUSH_UNIT				= FALSE,
	CAN_PASS_UNIT				= FALSE,
	
	SOUND_PLAY0			= { 0.290, "Unohound_StandUp2.ogg" },	
	
	EVENT_PROCESS = 
	{
		{ STATE_CHANGE_TYPE["SCT_FOOT_ON_LINE_FALSE_DOWN"],	"TARANVASH_FAKE_JUMP_DOWN",			},
		{ STATE_CHANGE_TYPE["SCT_MOTION_END"],				"TARANVASH_FAKE_WAIT",				},
	},
}

TARANVASH_FAKE_STAND_UP_BACK = 
{
	ANIM_NAME					= "DamageStandUpBack",
	PLAY_TYPE					= XSKIN_ANIM_PLAYTYPE["XAP_ONE_WAIT"],
	TRANSITION					= FALSE,
	LAND_CONNECT				= FALSE,
	
	SUPER_ARMOR					= TRUE,
	DEFENCE						= { 0, 100, 70, },
		
	CAN_PUSH_UNIT				= FALSE,
	CAN_PASS_UNIT				= FALSE,
		
	SOUND_PLAY0			= { 0.290, "Unohound_StandUp2.ogg" },	
		
	EVENT_PROCESS = 
	{
		{ STATE_CHANGE_TYPE["SCT_FOOT_ON_LINE_FALSE_DOWN"],	"TARANVASH_FAKE_JUMP_DOWN", },
		{ STATE_CHANGE_TYPE["SCT_MOTION_END"],				"TARANVASH_FAKE_WAIT", },
	},		
}



TARANVASH_FAKE_DYING_LAND_FRONT = 
{
	ANIM_NAME					= "Wait",
	PLAY_TYPE					= XSKIN_ANIM_PLAYTYPE["XAP_ONE_WAIT"],
	TRANSITION					= FALSE,
	LAND_CONNECT				= FALSE,

	INVINCIBLE					= { 0, 100, }, 		
	

	CAN_PUSH_UNIT				= FALSE,
	CAN_PASS_UNIT				= TRUE,
	
	DYING_END					= TRUE,
	
	IMMADIATE_PACKET_SEND		= TRUE,
	
	EFFECT_SET_LIST =
	{
		"EFFECTSET_TARANVASH_MIRRORIMAGEOFF", 0.0,
	},
	DELETE_EFFECT_SET_ON_STATE_END = TRUE,	
}
	
TARANVASH_FAKE_DYING_LAND_BACK = 
{
	ANIM_NAME					= "Wait",
	PLAY_TYPE					= XSKIN_ANIM_PLAYTYPE["XAP_ONE_WAIT"],
	TRANSITION					= FALSE,
	LAND_CONNECT				= FALSE,
	
	INVINCIBLE					= { 0, 100, }, 	
	
	CAN_PUSH_UNIT				= FALSE,
	CAN_PASS_UNIT				= TRUE,
	
	DYING_END					= TRUE,	
	
	IMMADIATE_PACKET_SEND		= TRUE,
	
	EFFECT_SET_LIST =
	{
		"EFFECTSET_TARANVASH_MIRRORIMAGEOFF", 0.0,
	},
	DELETE_EFFECT_SET_ON_STATE_END = TRUE,	
}

TARANVASH_FAKE_DYING_SKY = 
{
	ANIM_NAME					= "Wait",
	PLAY_TYPE					= XSKIN_ANIM_PLAYTYPE["XAP_ONE_WAIT"],
	TRANSITION					= FALSE,
	LAND_CONNECT				= FALSE,
	
	INVINCIBLE					= { 0, 100, }, 		
	
	CAN_PUSH_UNIT				= FALSE,
	CAN_PASS_UNIT				= TRUE,	
	
	DYING_END					= TRUE,
	
	IMMADIATE_PACKET_SEND		= TRUE,
	
	EFFECT_SET_LIST =
	{
		"EFFECTSET_TARANVASH_MIRRORIMAGEOFF", 0.0,
	},
	DELETE_EFFECT_SET_ON_STATE_END = TRUE,	
}


--- Attack-------------------------------------------------------------------	

TARANVASH_FAKE_STAND_UP_ATTACK_FRONT = 
{
	ANIM_NAME					= "StandUpAttackFront",
	PLAY_TYPE					= XSKIN_ANIM_PLAYTYPE["XAP_ONE_WAIT"],
	TRANSITION					= FALSE,
	LAND_CONNECT				= FALSE,	
	ANIM_WAIT_TIME				= 1,
	MIND_FLAG					= MIND_FLAG["MF_STAND_UP_ATTACK"],
	
	SUPER_ARMOR					= TRUE,
	
	CAN_PUSH_UNIT				= FALSE,
	CAN_PASS_UNIT				= FALSE,
	
	SOUND_PLAY0					= { 0.6 , "Swing_Medium01.ogg" },
	
	ATTACK_TIME0				= { 0.524, 0.7, },
	DISABLE_ATTACK_BOX = 
	{		
		--"RHand",
		--"LHand",
		"Tail01",
		"Tail02",
		
	},
	
	DAMAGE_DATA = 
	{
		DAMAGE_TYPE		= DAMAGE_TYPE["DT_PHYSIC"],
		HIT_TYPE		= HIT_TYPE["HT_PUNCH_HIT"],
		REACT_TYPE		= REACT_TYPE["RT_BIG_DAMAGE"],
		
		DAMAGE = 
		{
			PHYSIC		= 1,
		},
		
		BACK_SPEED_X			= 700,
		BACK_SPEED_Y			= 0,
		
		CAMERA_CRASH_GAP		= 5.0,	
		CAMERA_CRASH_TIME		= 0.2,	

		RE_ATTACK				= FALSE,		
		HIT_GAP					= 00,		
	},
	
	EVENT_PROCESS = 
	{
		{ STATE_CHANGE_TYPE["SCT_FOOT_ON_LINE_FALSE_DOWN"],	"TARANVASH_FAKE_JUMP_DOWN",			},
		{ STATE_CHANGE_TYPE["SCT_MOTION_END"],				"TARANVASH_FAKE_WAIT",				},
	},
	
	EFFECT_SET_LIST =
	{
		"EFFECTSET_TARANVASH_STANDUP_ATTACK_FRONT", 0.0,
	},
	DELETE_EFFECT_SET_ON_STATE_END = TRUE,
}

TARANVASH_FAKE_STAND_UP_ATTACK_BACK = 
{
	ANIM_NAME					= "StandUpAttackBack",
	PLAY_TYPE					= XSKIN_ANIM_PLAYTYPE["XAP_ONE_WAIT"],
	TRANSITION					= FALSE,
	LAND_CONNECT				= FALSE,	
	ANIM_WAIT_TIME				= 1,
	MIND_FLAG					= MIND_FLAG["MF_STAND_UP_ATTACK"],
	
	SUPER_ARMOR					= TRUE,
	
	CAN_PUSH_UNIT				= FALSE,
	CAN_PASS_UNIT				= FALSE,
	
	SOUND_PLAY0					= { 0.7, "Swing_Medium02.ogg" },
	
	ATTACK_TIME0				= { 0.7, 100, },
	DISABLE_ATTACK_BOX = 
	{		
		"RHand",
		"LHand",
		--"Tail01",
		--"Tail02",
		
	},
	
	DAMAGE_DATA = 
	{
		DAMAGE_TYPE		= DAMAGE_TYPE["DT_PHYSIC"],
		HIT_TYPE		= HIT_TYPE["HT_PUNCH_HIT"],
		REACT_TYPE		= REACT_TYPE["RT_BIG_DAMAGE"],
		
		DAMAGE = 
		{
			PHYSIC		= 1,
		},
		
		BACK_SPEED_X			= 700,
		BACK_SPEED_Y			= 0,
		
		CAMERA_CRASH_GAP		= 5.0,	
		CAMERA_CRASH_TIME		= 0.2,	

		RE_ATTACK				= FALSE,		
		HIT_GAP					= 00,		
	},
	
	EVENT_PROCESS = 
	{
		{ STATE_CHANGE_TYPE["SCT_FOOT_ON_LINE_FALSE_DOWN"],	"TARANVASH_FAKE_JUMP_DOWN",			},
		{ STATE_CHANGE_TYPE["SCT_MOTION_END"],				"TARANVASH_FAKE_WAIT",				},
	},
	
	EFFECT_SET_LIST =
	{
		"EFFECTSET_TARANVASH_STANDUP_ATTACK_BACK", 0.0,
	},
	DELETE_EFFECT_SET_ON_STATE_END = TRUE,
}

TARANVASH_FAKE_ATTACKA = 
{
	ANIM_NAME					= "AttackA",
	PLAY_TYPE					= XSKIN_ANIM_PLAYTYPE["XAP_ONE_WAIT"],
	TRANSITION					= FALSE,
	LAND_CONNECT				= FALSE,
	
	SUPER_ARMOR					= TRUE,
	
	CAN_PUSH_UNIT				= FALSE,
	CAN_PASS_UNIT				= FALSE,

	SOUND_PLAY0					= { 0.36 , "Swing_Medium01.ogg" },
	SOUND_PLAY1 				= { 1.10 , "Swing_Medium02.ogg" },
	
	DISABLE_ATTACK_BOX = 
	{		
		"RHand",
		"LHand",
		"Tail01",
		"Tail02",
		
	},		
	ATTACK_TIME0				= { 0.38, 0.7, },
	ATTACK_TIME1				= { 1.15, 1.45, },
	DAMAGE_DATA = 
	{
		DAMAGE_TYPE		= DAMAGE_TYPE["DT_PHYSIC"],
		HIT_TYPE		= HIT_TYPE["HT_PUNCH_HIT"],
		REACT_TYPE		= REACT_TYPE["RT_BIG_DAMAGE"],
		
		DAMAGE = 
		{
			PHYSIC		= 1,
		},
		
		ENABLE_ATTACKBOX =
		{
			"RHand",
		},
		DISABLE_ATTACKBOX = 
		{
			"LHand",
		},
		
		--BACK_SPEED_X			= 1000,
		BACK_SPEED_Y			= 0,
		
		CAMERA_CRASH_GAP		= 5.0,	
		CAMERA_CRASH_TIME		= 0.2,	

		RE_ATTACK				= FALSE,		
		HIT_GAP					= 0.2,		
	},
	DAMAGE_DATA_LAST = 
	{
		DAMAGE_TYPE		= DAMAGE_TYPE["DT_PHYSIC"],
		HIT_TYPE		= HIT_TYPE["HT_PUNCH_HIT"],
		REACT_TYPE		= REACT_TYPE["RT_BIG_DAMAGE"],
		
		DAMAGE = 
		{
			PHYSIC		= 1,
		},
		
		ENABLE_ATTACKBOX =
		{
			"LHand",
		},
		DISABLE_ATTACKBOX = 
		{
			"RHand",
		},
		
		--BACK_SPEED_X			= 1000,
		BACK_SPEED_Y			= 0,
		
		CAMERA_CRASH_GAP		= 5.0,	
		CAMERA_CRASH_TIME		= 0.2,	

		RE_ATTACK				= FALSE,		
		HIT_GAP					= 0.2,		
	},
			
	EVENT_PROCESS = 
	{
		{ STATE_CHANGE_TYPE["SCT_FOOT_ON_LINE_FALSE_DOWN"],	"TARANVASH_FAKE_JUMP_DOWN",			},
		{ STATE_CHANGE_TYPE["SCT_MOTION_END"],				"TARANVASH_FAKE_WAIT",				},
	},
	
	EFFECT_SET_LIST =
	{
		"EFFECTSET_TARANVASH_ATTACKA", 0.0,
	},
	DELETE_EFFECT_SET_ON_STATE_END = TRUE,
}

TARANVASH_FAKE_MAGICATTACKA = 
{
	ANIM_NAME					= "MagicAttackA",
	PLAY_TYPE					= XSKIN_ANIM_PLAYTYPE["XAP_ONE_WAIT"],
	TRANSITION					= FALSE,
	LAND_CONNECT				= FALSE,
	
	SUPER_ARMOR					= TRUE,
	
	CAN_PUSH_UNIT				= FALSE,
	CAN_PASS_UNIT				= FALSE,
	
	SOUND_PLAY0					= { 0.15, "Taranvash_SpecialAttackA01.ogg" },
	SOUND_PLAY1					= { 2.09, "Taranvash_MagicAttackA01.ogg" },
			
	EVENT_PROCESS = 
	{
		{ STATE_CHANGE_TYPE["SCT_FOOT_ON_LINE_FALSE_DOWN"],	"TARANVASH_FAKE_JUMP_DOWN",			},
		{ STATE_CHANGE_TYPE["SCT_MOTION_END"],				"TARANVASH_FAKE_WAIT",				},
	},
	
	EFFECT_SET_LIST =
	{
		"EFFECTSET_TARANVASH_MAGIC_ATTACK_A", 0.0,
	},
	DELETE_EFFECT_SET_ON_STATE_END = TRUE,
}

TARANVASH_FAKE_MAGICATTACKB = 
{
	ANIM_NAME					= "MagicAttackB",
	PLAY_TYPE					= XSKIN_ANIM_PLAYTYPE["XAP_ONE_WAIT"],
	TRANSITION					= FALSE,
	LAND_CONNECT				= FALSE,
	
	SUPER_ARMOR					= TRUE,
	
	CAN_PUSH_UNIT				= FALSE,
	CAN_PASS_UNIT				= FALSE,
	
	SOUND_PLAY0					= { 0.25, "Taranvash_MagicAttackB01.ogg"},
	SOUND_PLAY1					= { 1.65, "Taranvash_MagicAttackB02.ogg"},
	
	EVENT_PROCESS = 
	{
		{ STATE_CHANGE_TYPE["SCT_FOOT_ON_LINE_FALSE_DOWN"],	"TARANVASH_FAKE_JUMP_DOWN",			},
		{ STATE_CHANGE_TYPE["SCT_MOTION_END"],				"TARANVASH_FAKE_WAIT",				},
	},
	
	EFFECT_SET_LIST =
	{
		"EFFECTSET_TARANVASH_MAGIC_ATTACK_B", 0.0,
	},
	DELETE_EFFECT_SET_ON_STATE_END = TRUE,
}

TARANVASH_FAKE_SPECIALATTACK_A = 
{
	ANIM_NAME					= "SpecialAttackA",
	PLAY_TYPE					= XSKIN_ANIM_PLAYTYPE["XAP_ONE_WAIT"],
	TRANSITION					= FALSE,
	LAND_CONNECT				= FALSE,
	
	SUPER_ARMOR					= TRUE,
	
	CAN_PUSH_UNIT				= FALSE,
	CAN_PASS_UNIT				= FALSE,
	
	SOUND_PLAY0					= { 0.25, "Taranvash_SpecialAttackA01.ogg"},
	SOUND_PLAY1					= { 1.95, "Taranvash_SpecialAttackA02.ogg"},
	
	EVENT_PROCESS = 
	{
		{ STATE_CHANGE_TYPE["SCT_FOOT_ON_LINE_FALSE_DOWN"],	"TARANVASH_FAKE_JUMP_DOWN",			},
		{ STATE_CHANGE_TYPE["SCT_MOTION_END"],				"TARANVASH_FAKE_WAIT",				},
	},
	
	EFFECT_SET_LIST =
	{
		"EFFECTSET_TARANVASH_SPECIAL_ATTACK_A", 0.0,
	},
	DELETE_EFFECT_SET_ON_STATE_END = TRUE,
}

TARANVASH_FAKE_SPECIALATTACK_B = 
{
	ANIM_NAME					= "SpecialAttackB",
	PLAY_TYPE					= XSKIN_ANIM_PLAYTYPE["XAP_ONE_WAIT"],
	TRANSITION					= FALSE,
	LAND_CONNECT				= FALSE,
	
	SUPER_ARMOR					= TRUE,
	
	CAN_PUSH_UNIT				= FALSE,
	CAN_PASS_UNIT				= FALSE,
	
	REFLECT_MAGIC = { 1.6, 10, },
	
	SOUND_PLAY0					= { 0.01, "Taranvash_SpecialAttackB01.ogg"},
	
	EVENT_PROCESS = 
	{
		{ STATE_CHANGE_TYPE["SCT_FOOT_ON_LINE_FALSE_DOWN"],	"TARANVASH_FAKE_JUMP_DOWN",			},
		{ STATE_CHANGE_TYPE["SCT_MOTION_END"],				"TARANVASH_FAKE_WAIT",				},
	},
	

	EFFECT_SET_LIST =
	{
		"EFFECTSET_TARANVASH_SPECIAL_ATTACK_B", 0.0,
	},
	DELETE_EFFECT_SET_ON_STATE_END = TRUE,

}

TARANVASH_FAKE_SPECIALATTACK_C = 
{
	ANIM_NAME					= "SpecialAttackC",
	PLAY_TYPE					= XSKIN_ANIM_PLAYTYPE["XAP_ONE_WAIT"],
	TRANSITION					= FALSE,
	LAND_CONNECT				= FALSE,
	
	SUPER_ARMOR					= TRUE,
	
	CAN_PUSH_UNIT				= FALSE,
	CAN_PASS_UNIT				= FALSE,
			
	EVENT_PROCESS = 
	{	
		{ STATE_CHANGE_TYPE["SCT_MOTION_END"],				"TARANVASH_FAKE_SPECIALATTACK_C_COMBO",				},
	},	
}

TARANVASH_FAKE_SPECIALATTACK_C_COMBO = 
{
	ANIM_NAME					= "SpecialAttackC_Combo",
	PLAY_TYPE					= XSKIN_ANIM_PLAYTYPE["XAP_ONE_WAIT"],
	TRANSITION					= FALSE,
	LAND_CONNECT				= FALSE,
	
	SUPER_ARMOR					= TRUE,
	
	CAN_PUSH_UNIT				= FALSE,
	CAN_PASS_UNIT				= FALSE,
	
	SOUND_PLAY0					= { 0.250, "Swing_Medium01.ogg" },
	SOUND_PLAY1					= { 0.01, "Taranvash_SpecialAttackC01.ogg" },
	
	EVENT_PROCESS = 
	{
		{ STATE_CHANGE_TYPE["SCT_FOOT_ON_LINE_FALSE_DOWN"],	"TARANVASH_FAKE_JUMP_DOWN",			},
		{ STATE_CHANGE_TYPE["SCT_MOTION_END"],				"TARANVASH_FAKE_WAIT",				},
	},

	EFFECT_SET_LIST =
	{
		"EFFECTSET_TARANVASH_SPECIALATTACK_C", 0.0,
	},
	DELETE_EFFECT_SET_ON_STATE_END = TRUE,

}


--------------------------------------------------------------------
--------------------------------------------------------------------
function TARANVASH_FAKE_ATTACKA_FRAME_MOVE( pKTDXApp, pX2Game, pNPCUnit )
	
	if pNPCUnit:AnimEventTimer_LUA( 1.0 ) then
		pNPCUnit:ClearHitUnitList_LUA()
		pNPCUnit:SetDamageData_LUA( "DAMAGE_DATA_LAST" )
	end
	
end

function TARANVASH_FAKE_WALK_STATE_END( pKTDXApp, pX2Game, pNPCUnit )

	local pMinorParticle = pX2Game:GetMinorParticle()
	pMinorParticle:GameUnitCreateSequence_LUA( pNPCUnit, "StepSmokeBig", pNPCUnit:GetLandPosition_LUA(), D3DXVECTOR2(100,100), D3DXVECTOR2(5,-1) )

end



function TARANVASH_FAKE_JUMP_DOWN_STATE_END( pKTDXApp, pX2Game, pNPCUnit )

	local pMinorParticle = pX2Game:GetMinorParticle()
	pMinorParticle:GameUnitCreateSequence_LUA( pNPCUnit, "StepSmokeBig", pNPCUnit:GetLandPosition_LUA(), D3DXVECTOR2(100,100), D3DXVECTOR2(5,-1) )

end

function TARANVASH_FAKE_JUMP_DOWN_DIR_STATE_END( pKTDXApp, pX2Game, pNPCUnit )

	local pMinorParticle = pX2Game:GetMinorParticle()
	pMinorParticle:GameUnitCreateSequence_LUA( pNPCUnit, "StepSmokeBig", pNPCUnit:GetLandPosition_LUA(), D3DXVECTOR2(100,100), D3DXVECTOR2(5,-1) )

end



function TARANVASH_FAKE_DAMAGE_FRONT_FRAME_MOVE( pKTDXApp, pX2Game, pNPCUnit )

	if pNPCUnit:AnimEventTimer_LUA( 0.047 ) then
		local pMinorParticle = pX2Game:GetMinorParticle()
		pMinorParticle:GameUnitCreateSequence_LUA( pNPCUnit, "StepSmokeBig", pNPCUnit:GetLandPosition_LUA(), D3DXVECTOR2(100,100), D3DXVECTOR2(5,-1) )
	end

end

function TARANVASH_FAKE_DAMAGE_BACK_FRAME_MOVE( pKTDXApp, pX2Game, pNPCUnit )

	if pNPCUnit:AnimEventTimer_LUA( 0.06 ) then
		local pMinorParticle = pX2Game:GetMinorParticle()
		pMinorParticle:GameUnitCreateSequence_LUA( pNPCUnit, "StepSmokeBig", pNPCUnit:GetLandPosition_LUA(), D3DXVECTOR2(100,100), D3DXVECTOR2(5,-1) )
	end

end

function TARANVASH_FAKE_DAMAGE_DOWN_FRONT_FRAME_MOVE( pKTDXApp, pX2Game, pNPCUnit )

	if pNPCUnit:AnimEventTimer_LUA( 0.41 ) then
		pNPCUnit:PlaySound_LUA( "Landing_Big_Metal01.ogg" )		
		local pMinorParticle = pX2Game:GetMinorParticle()
		pMinorParticle:GameUnitCreateSequence_LUA( pNPCUnit, "DownSmokeBig", pNPCUnit:GetLandPosition_LUA(), D3DXVECTOR2(100,100), D3DXVECTOR2(7,-1) )
	end

end

function TARANVASH_FAKE_DAMAGE_DOWN_BACK_FRAME_MOVE( pKTDXApp, pX2Game, pNPCUnit )

	if pNPCUnit:AnimEventTimer_LUA( 0.45 ) then
		pNPCUnit:PlaySound_LUA( "Landing_Big_Metal02.ogg" )		
		local pMinorParticle = pX2Game:GetMinorParticle()
		pMinorParticle:GameUnitCreateSequence_LUA( pNPCUnit, "DownSmokeBig", pNPCUnit:GetLandPosition_LUA(), D3DXVECTOR2(100,100), D3DXVECTOR2(7,-1) )
	end

end

function TARANVASH_FAKE_DAMAGE_AIR_DOWN_LANDING_FRAME_MOVE( pKTDXApp, pX2Game, pNPCUnit )

	if pNPCUnit:AnimEventTimer_LUA( 0.01 ) then
		
		local pMinorParticle = pX2Game:GetMinorParticle()
		local pos = pNPCUnit:GetLandPosition_LUA()
		pMinorParticle:GameUnitCreateSequence_LUA( pNPCUnit, "DownSmokeBig", pos, D3DXVECTOR2(100,100), D3DXVECTOR2(7,-1) )
		pos.y = pos.y + 5
		pMinorParticle:GameUnitCreateSequence_LUA( pNPCUnit, "GroundShockWave", pos, D3DXVECTOR2(100,100), D3DXVECTOR2(1,-1) )
		local pParticle = pMinorParticle:GameUnitCreateSequence_LUA( pNPCUnit, "AirDownTick", pNPCUnit:GetPos(), D3DXVECTOR2(200,200), D3DXVECTOR2(10,-1) )
		if pParticle ~= nil then 
			pParticle:SetLandPosition( pos.y - 5 )
		end
		
		if GetDistance_LUA( pNPCUnit:GetPos(), pX2Game:GetFocusUnitPos_LUA() ) < 500 then
			pX2Game:GetX2Camera():GetCamera():UpDownCrashCameraNoReset( 10.0, 0.1 )
		end		
		
	elseif pNPCUnit:AnimEventTimer_LUA( 0.1 ) then
		
		pNPCUnit:PlaySound_LUA( "Landing_Big_Metal01.ogg" )		
		local pMinorParticle = pX2Game:GetMinorParticle()
		pMinorParticle:GameUnitCreateSequence_LUA( pNPCUnit, "DownSmokeBig", pNPCUnit:GetLandPosition_LUA(), D3DXVECTOR2(100,100), D3DXVECTOR2(7,-1) )
		
	end

end






------------------------------------------------------------------------------
function MovePos( pos, dirvector, dist )
	
	pos.x = pos.x + dist * dirvector.x
	pos.y = pos.y + dist * dirvector.y
	pos.z = pos.z + dist * dirvector.z
	
	return pos
	
end



--------------------------------------------------------------------

function CF_TARANVASH_FAKE_DASH_END( pKTDXApp, pX2Game, pNPCUnit )

	if pNPCUnit:GetStateTime() < 0.1 then
		return false 
	end
	
	
 	local bIsRight = pNPCUnit:GetIsRight()
	local vStartPos = pNPCUnit:GetLineGroupStartPos()
	local vEndPos = pNPCUnit:GetLineGroupEndPos()

 	
 	if bIsRight == true and pNPCUnit:GetDistanceFrom(vEndPos) < 300.0 then
 	
 	    return true
 	    
   	end
   	
   	if bIsRight == false and pNPCUnit:GetDistanceFrom(vStartPos) < 300.0 then

		return true
  	
    end

     if pNPCUnit:GetStateTime() > 5.0 then
		return true
	end
    
    return false 	

end

function CF_TARANVASH_FAKE_WIN( pKTDXApp, pX2Game, pNPCUnit )

	if pX2Game:LiveUserUnitNum() == 0 then
		return true
	else
		return false
	end

end


function TARANVASH_FAKE_SPECIALATTACK_C_FRAME_MOVE( pKTDXApp, pX2Game, pNPCUnit )
-- Fade Start    

    if pNPCUnit:AnimEventTimer_LUA(0.001) then
        pNPCUnit:SetUnitFadeStart(RENDER_TYPE["RT_CARTOON_FADE"], 1.0, 1.0, 1.0, 1.0, false, true)
        pNPCUnit:SetUnitFadeMove(0.6, 0.0, 0.0, 0.0, -0.04)
    end
    
    if pNPCUnit:AnimEventTimer_LUA(0.3) then
        pNPCUnit:SetUnitFadeStart(RENDER_TYPE["RT_CARTOON_FADE_NONTEX"], 1.0, 1.0, 1.0, 1.0, true, true)
        pNPCUnit:SetUnitFadeMove(0.3, 0.0, 0.0, 0.0, -0.1)
       -- pNPCUnit:SetUnitFadeScale(0.4, -0.1, 0.1, -0.1)
    end  

-- Fade End    
end

function TARANVASH_FAKE_SPECIALATTACK_C_COMBO_STATE_START( pKTDXApp, pX2Game, pNPCUnit )
	local pUser = pNPCUnit:GetTargetUser()    
    if pUser ~= nil then
        local unitPos = pUser:GetPos() 
        if pNPCUnit:GetRandVal() % 2 == 0 then
            -- 유저기준 오른쪽            
            WalkPos = pX2Game:GetLineMap():GetRandomPositionDir( unitPos, 800, true, true )
            bIsRight = false                
        else
            -- 유저기준 왼쪽
            WalkPos = pX2Game:GetLineMap():GetRandomPositionDir( unitPos, 800, true, false )
            bIsRight = true                
        end
        WalkLandPos = pX2Game:GetLineMap():GetLandPosition_LUA( WalkPos )
        pNPCUnit:SetPosition( WalkLandPos , bIsRight)
    end
end

function TARANVASH_FAKE_SPECIALATTACK_C_COMBO_FRAME_MOVE( pKTDXApp, pX2Game, pNPCUnit )
-- Fade Start 
    if pNPCUnit:AnimEventTimer_LUA(0.001) then
        pNPCUnit:SetUnitFadeStart(RENDER_TYPE["RT_CARTOON_FADE_NONTEX"], 1.0, 1.0, 1.0, 0.0, true, true)
        pNPCUnit:SetUnitFadeMove(0.2, 0.0, 0.0, 0.0, 0.01)
    end  

    if pNPCUnit:AnimEventTimer_LUA(0.23) then
        pNPCUnit:SetUnitFadeStart(RENDER_TYPE["RT_CARTOON_FADE"], 1.0, 1.0, 1.0, 0.0, false, true)
        pNPCUnit:SetUnitFadeMove(0.1, 0.0, 0.0, 0.0, 0.02)        
    end
-- Fade End
end

function TARANVASH_FAKE_COMMON_FRAME_MOVE( pKTDXApp, pX2Game, pNPCUnit )
	local pXSkinAnim = pNPCUnit:GetXSkinAnim()

	if pNPCUnit:GetReflectMagic_LUA() == true then		
		pXSkinAnim:SetUseTex( 2, true )
	else
		pXSkinAnim:SetUseTex( 2, false )
	end	
end
