-- lua header. UTF-8 인코딩 인식을 위해 이 줄은 지우지 마세요.


INIT_SYSTEM = 
{
	UNIT_WIDTH		= 50.0,
	UNIT_LAYER		= X2_LAYER["XL_UNIT_0"],
	
	--ALPHA_BLEND		= TRUE,
}


INIT_DEVICE = 
{
	READY_XSKIN_MESH = 
	{	   
	},
}

INIT_MOTION = 
{
	--MOTION_FILE_NAME		= "Dummy_Ani_Wait.X",
	MOTION_FILE_NAME		= "Motion_Flame.x",
}

INIT_PHYSIC = 
{
	RELOAD_ACCEL		= 0,
	G_ACCEL				= 0,
	MAX_G_SPEED			= 0,
	
	WALK_SPEED			= 0,
	RUN_SPEED			= 0,
	JUMP_SPEED			= 0,
	DASH_JUMP_SPEED		= 0,
}


INIT_COMPONENT = 
{	
	SHOW_ON_MINIMAP		= FALSE,
}

INIT_STATE = 
{
    
    { STATE_NAME = "VALENTINE_DROP_MONSTER2_START",				LUA_STATE_START_FUNC = "VALENTINE_DROP_MONSTER2_START_STATE_START", },
	{ STATE_NAME = "VALENTINE_DROP_MONSTER2_DIE", },
    
    
	START_STATE					= "VALENTINE_DROP_MONSTER2_START",
	WAIT_STATE					= "VALENTINE_DROP_MONSTER2_DIE",
	
	DYING_LAND_FRONT			= "VALENTINE_DROP_MONSTER2_DIE",
	DYING_LAND_BACK				= "VALENTINE_DROP_MONSTER2_DIE",
	DYING_SKY					= "VALENTINE_DROP_MONSTER2_DIE",

}

INIT_AI = 
{
}

VALENTINE_DROP_MONSTER2_START = 
{
	SHOW						= FALSE,

	ANIM_NAME					= "Wait",
	PLAY_TYPE					= XSKIN_ANIM_PLAYTYPE["XAP_ONE_WAIT"],
	  
	TRANSITION					= FALSE,
	INVINCIBLE					= { 0, 100, },
	NEVER_MOVE					= TRUE,
		
	CAN_PUSH_UNIT				= FALSE,
	CAN_PASS_UNIT				= TRUE,
	IMMADIATE_PACKET_SEND		= TRUE,	
		
	EVENT_PROCESS = 
	{		
		{ STATE_CHANGE_TYPE["SCT_CONDITION_TABLE"],		"VALENTINE_DROP_MONSTER2_DIE",		"CT_VALENTINE_DROP_MONSTER2_DIE"				},
	},
	
	CT_VALENTINE_DROP_MONSTER2_DIE = 
	{
		STATE_TIME_OVER			= 0.1,
	},
	EFFECT_SET_LIST =
	{
		"EffectSet_Flame_BLUE_Event_WAIT", 0,	
	},
}

function VALENTINE_DROP_MONSTER2_START_STATE_START( pKTDXApp, pX2Game, pNPCUnit )
	pNPCUnit:SetAIEnable( false )
end
VALENTINE_DROP_MONSTER2_DIE = 
{
    SHOW                        = FALSE,
    
	ANIM_NAME					= "Dying",
	PLAY_TYPE					= XSKIN_ANIM_PLAYTYPE["XAP_ONE_WAIT"],
	
	TRANSITION					= FALSE,
	INVINCIBLE					= { 0, 100, },
	NEVER_MOVE					= TRUE,
	
	CAN_PUSH_UNIT				= FALSE,
	CAN_PASS_UNIT				= TRUE,	
	
	SPEED_X						= 0,
	SPEED_Y						= 0,
		
	NEVER_MOVE					= TRUE,
	ALLOW_DIR_CHANGE			= FALSE,
	VIEW_TARGET					= FALSE,	
	
	DYING_END					= TRUE,
	
	IMMADIATE_PACKET_SEND		= TRUE,
	EFFECT_SET_LIST =
	{
		"EffectSet_Flame_BLUE_Event_Dying", 0,	
	},
}