-- lua header. UTF-8 인코딩 인식을 위해 이 줄은 지우지 마세요.


INIT_SYSTEM = 
{
	UNIT_WIDTH		= 150.0,
	UNIT_HEIGHT		= 250.0,
	UNIT_LAYER		= X2_LAYER["XL_UNIT_0"],
}

INIT_DEVICE = 
{
	READY_TEXTURE = 
	{		
		"Dark_Smoke.dds",
		"Steam_BP.tga",
	},
	
	READY_SOUND = 
	{
		"Wally9_Combo.ogg",
		"Wally9_Slash.ogg",
		"Wally9_SwordOut.ogg",
		"Wally9_SwordIn.ogg",
		"Wally9_DashAttack.ogg",
		"Wally9_Rampage1.ogg",
		"Wally9_Rampage2.ogg",
		"Wally9_Rampage3.ogg",
		"Wally9_Rampage4.ogg",
		"Wally9_WaitStart.ogg",
		"Wally9_Win.ogg",
		"Wally9_StandUpAttack.ogg",
		"Wally9_AttackB.ogg",
		"Wally9_StepLanding.ogg",
		"Wally9_JumpAttack.ogg",
		"Wally9_DashEnd.ogg",
		"Wally9_HitGround.ogg",
		"Wally9_StartSmoke.ogg",
		"BreakGround.ogg",
		"Wally9_LaserAttack.ogg",
		"Wally9_Barrier.ogg",
		
	},
	
	
	READY_XMESH = 
	{
		"Thief_Fat_JumpAttackA_Stone01.Y",
		"Thief_Fat_JumpAttackA_Stone02.y",
		"Wally9th_Armor_Broken.X",
		
	},
	
	READY_XSKIN_MESH = 
	{
		"Wally9th_LazerAttack01.X",	
		"Wally9th_RampageLaser01.X",
	},

	
}

INIT_MOTION = 
{
	MOTION_FILE_NAME	= "Motion_Wally9th.x",
}

INIT_PHYSIC = 
{
	RELOAD_ACCEL		= 2000,
	G_ACCEL				= 4000,
	MAX_G_SPEED			= -2000,
	
	WALK_SPEED			= 700,
	RUN_SPEED			= 1200,
	JUMP_SPEED			= 2000,
	DASH_JUMP_SPEED		= 2500,
}

INIT_COMPONENT = 
{
	MAX_HP				= 40000, 
	MP_CHANGE_RATE		= 1,
	MP_CHARGE_RATE		= 130,

	
	SHADOW_SIZE			= 200,
	SHADOW_FILE_NAME	= "shadow.dds",
	
	SMALL_HP_BAR_BLUE	= "Small_HP_bar_Blue.TGA",
	SMALL_HP_BAR_RED	= "Small_HP_bar_Red.TGA",
	SMALL_HP_BAR_YELLOW = "Small_HP_bar_Yellow.TGA",
	
	DRAW_SMALL_MP_BAR	= TRUE,
	
	QUESTION_MARK_SEQ		= "QuestionMarkNPC",
	EXCLAMATION_MARK_SEQ	= "ExclamationMarkNPC",
	--MIND_FLAG_HEIGHT		= 230,
	
	HYPER_MODE_COUNT	= 0,
	MAX_HYPER_MODE_TIME	= 30,
	
	HITTED_TYPE			= HITTED_TYPE["HTD_MEAT"],
	
	FALL_DOWN			= TRUE,
	
	BOSS_GAGE_FACE_TEX			= "DLG_BossState.tga",
	BOSS_GAGE_FACE_TEX_PIECE	= "Willy_9th",	
	BOSS_NAME_TEX				= "HQ_BOSS_NAME_WALLY_9TH.dds",
	
 	RAGE_COUNT_MAX		= 60,
	RAGE_TIME_MAX		= 3,

    DIE_FLY             = 0,
    
	WEAPON0 = 
	{
		WEAPON_FILE_NAME			= "Wally9th_Weapon01.X",
		WEAPON_BONE_NAME			= "Dummy1_Rhand",
		
		ALPHA_OBJECT				= TRUE,
			
		USE_SLASH_TRACE				= TRUE,
		SLASH_TRACE_TOP_BONE		= "TRACE_START1",
		SLASH_TRACE_BOTTOM_BONE		= "TRACE_END1",
	},

	WEAPON1 = 
	{
		WEAPON_FILE_NAME			= "Wally9th_Weapon02.X",
		WEAPON_BONE_NAME			= "Dummy2_Lhand",
		
		ALPHA_OBJECT				= TRUE,		
			
		USE_SLASH_TRACE				= TRUE,
		SLASH_TRACE_TOP_BONE		= "TRACE_START2",
		SLASH_TRACE_BOTTOM_BONE		= "TRACE_END2",
	},

	

	

	
	--[[

	

	--]]
	
}

INIT_STATE = 
{
	{ STATE_NAME = "WALLY_9TH_EXPERT_DISABLED",					},

	{ STATE_NAME = "WALLY_9TH_EXPERT_START",						LUA_CAMERA_MOVE_FUNC = "WALLY_9TH_EXPERT_START_CAMERA_MOVE",						},
	{ STATE_NAME = "WALLY_9TH_EXPERT_WIN",							},
	{ STATE_NAME = "WALLY_9TH_EXPERT_WAIT",						},
	
	{ STATE_NAME = "WALLY_9TH_EXPERT_WALK",						LUA_STATE_END_FUNC = "WALLY_9TH_EXPERT_WALK_STATE_END"								},
	
	{ STATE_NAME = "WALLY_9TH_EXPERT_JUMP_UP_DIR_FOR_ATTACK",		},
	
	{ STATE_NAME = "WALLY_9TH_EXPERT_JUMP_UP",						},
	
	{ STATE_NAME = "WALLY_9TH_EXPERT_JUMP_DOWN",					LUA_STATE_END_FUNC = "WALLY_9TH_EXPERT_JUMP_DOWN_STATE_END"						},
															
	{ STATE_NAME = "WALLY_9TH_EXPERT_JUMP_UP_DIR",					},
	
	{ STATE_NAME = "WALLY_9TH_EXPERT_JUMP_DOWN_DIR",				LUA_STATE_END_FUNC = "WALLY_9TH_EXPERT_JUMP_DOWN_DIR_STATE_END"					},
	{ STATE_NAME = "WALLY_9TH_EXPERT_JUMP_LANDING",				LUA_STATE_START_FUNC = "WALLY_9TH_EXPERT_JUMP_LANDING_STATE_START",				},
	
	{ STATE_NAME = "WALLY_9TH_EXPERT_DASH",						LUA_STATE_START_FUNC = "WALLY_9TH_EXPERT_DASH_STATE_START", 
															LUA_FRAME_MOVE_FUNC = "WALLY_9TH_EXPERT_DASH_FRAME_MOVE",							
															LUA_STATE_END_FUNC = "WALLY_9TH_EXPERT_DASH_STATE_END"								},
															
	{ STATE_NAME = "WALLY_9TH_EXPERT_DASH_END",					LUA_STATE_START_FUNC = "WALLY_9TH_EXPERT_DASH_END_STATE_START", 					},
	
	{ STATE_NAME = "WALLY_9TH_EXPERT_ATTACKB",						},
	{ STATE_NAME = "WALLY_9TH_EXPERT_COMBO",						LUA_FRAME_MOVE_FUNC = "WALLY_9TH_EXPERT_COMBO_FRAME_MOVE",	STATE_COOL_TIME = 8,							},
	{ STATE_NAME = "WALLY_9TH_EXPERT_LASER_ATTACK",				LUA_FRAME_MOVE_FUNC = "WALLY_9TH_EXPERT_LASER_ATTACK_FRAME_MOVE",				
															LUA_STATE_END_FUNC = "WALLY_9TH_EXPERT_LASER_ATTACK_STATE_END",	STATE_COOL_TIME = 30,	},
	
	{ STATE_NAME = "WALLY_9TH_EXPERT_DASH_ATTACK",					LUA_FRAME_MOVE_FUNC = "WALLY_9TH_EXPERT_DASH_ATTACK_FRAME_MOVE",	STATE_COOL_TIME = 6,					},
	{ STATE_NAME = "WALLY_9TH_EXPERT_JUMP_ATTACK",					},
	{ STATE_NAME = "WALLY_9TH_EXPERT_SP_RAMPAGE",					LUA_FRAME_MOVE_FUNC = "WALLY_9TH_EXPERT_SP_RAMPAGE_FRAME_MOVE"						},
	
	
	{ STATE_NAME = "WALLY_9TH_EXPERT_BARRIER",						LUA_FRAME_MOVE_FUNC = "WALLY_9TH_EXPERT_BARRIER_FRAME_MOVE",
															STATE_COOL_TIME = 60,				},
	
	
	
	
	--리액션 관련
	{ STATE_NAME = "WALLY_9TH_EXPERT_DAMAGE_SMALL",				LUA_FRAME_MOVE_FUNC = "WALLY_9TH_EXPERT_DAMAGE_SMALL_FRAME_MOVE"					},
															
	{ STATE_NAME = "WALLY_9TH_EXPERT_DAMAGE_BIG",					LUA_FRAME_MOVE_FUNC = "WALLY_9TH_EXPERT_DAMAGE_BIG_FRAME_MOVE" 					},
	
	{ STATE_NAME = "WALLY_9TH_EXPERT_DAMAGE_DOWN_FRONT",			LUA_FRAME_MOVE_FUNC = "WALLY_9TH_EXPERT_DAMAGE_DOWN_FRONT_FRAME_MOVE"				},
	{ STATE_NAME = "WALLY_9TH_EXPERT_DAMAGE_DOWN_BACK",			LUA_FRAME_MOVE_FUNC = "WALLY_9TH_EXPERT_DAMAGE_DOWN_BACK_FRAME_MOVE"				},
		
	{ STATE_NAME = "WALLY_9TH_EXPERT_DAMAGE_FLY_FRONT",			},
	{ STATE_NAME = "WALLY_9TH_EXPERT_DAMAGE_FLY_BACK",				},
		
	{ STATE_NAME = "WALLY_9TH_EXPERT_DAMAGE_AIR",					},
	{ STATE_NAME = "WALLY_9TH_EXPERT_DAMAGE_AIR_UP",				},
	{ STATE_NAME = "WALLY_9TH_EXPERT_DAMAGE_AIR_DOWN",				},
	{ STATE_NAME = "WALLY_9TH_EXPERT_DAMAGE_AIR_FALL",				},	
	{ STATE_NAME = "WALLY_9TH_EXPERT_DAMAGE_AIR_DOWN_LANDING",		LUA_FRAME_MOVE_FUNC = "WALLY_9TH_EXPERT_DAMAGE_AIR_DOWN_LANDING_FRAME_MOVE"		},
	{ STATE_NAME = "WALLY_9TH_EXPERT_STAND_UP_FRONT",				LUA_FRAME_MOVE_FUNC = "WALLY_9TH_EXPERT_STAND_UP_FRONT_FRAME_MOVE"					},
	{ STATE_NAME = "WALLY_9TH_EXPERT_STAND_UP_BACK",				LUA_FRAME_MOVE_FUNC = "WALLY_9TH_EXPERT_STAND_UP_BACK_FRAME_MOVE"					},
	{ STATE_NAME = "WALLY_9TH_EXPERT_STAND_UP_ATTACK_FRONT",		LUA_FRAME_MOVE_FUNC = "WALLY_9TH_EXPERT_STAND_UP_ATTACK_FRONT_FRAME_MOVE"			},
	{ STATE_NAME = "WALLY_9TH_EXPERT_STAND_UP_ATTACK_BACK",		LUA_FRAME_MOVE_FUNC = "WALLY_9TH_EXPERT_STAND_UP_ATTACK_BACK_FRAME_MOVE"			},
	{ STATE_NAME = "WALLY_9TH_EXPERT_DAMAGE_REVENGE",				},

	{ STATE_NAME = "WALLY_9TH_EXPERT_DYING_LAND_FRONT",			LUA_STATE_START_FUNC = "WALLY_9TH_EXPERT_DYING_LAND_STATE_START" 					},
	{ STATE_NAME = "WALLY_9TH_EXPERT_DYING_LAND_BACK",				LUA_STATE_START_FUNC = "WALLY_9TH_EXPERT_DYING_LAND_STATE_START" 					},
	{ STATE_NAME = "WALLY_9TH_EXPERT_DYING_SKY",					LUA_STATE_START_FUNC = "WALLY_9TH_EXPERT_DYING_LAND_STATE_START" 					},

	
	
	START_STATE					= "WALLY_9TH_EXPERT_START",
	WAIT_STATE					= "WALLY_9TH_EXPERT_WAIT",
	DISABLED_STATE				= "WALLY_9TH_EXPERT_DISABLED",
	
	SMALL_DAMAGE_LAND_FRONT		= "WALLY_9TH_EXPERT_DAMAGE_SMALL",
	SMALL_DAMAGE_LAND_BACK		= "WALLY_9TH_EXPERT_DAMAGE_SMALL",
	BIG_DAMAGE_LAND_FRONT		= "WALLY_9TH_EXPERT_DAMAGE_BIG",
	BIG_DAMAGE_LAND_BACK		= "WALLY_9TH_EXPERT_DAMAGE_BIG",
	DOWN_DAMAGE_LAND_FRONT		= "WALLY_9TH_EXPERT_DAMAGE_DOWN_FRONT",
	DOWN_DAMAGE_LAND_BACK		= "WALLY_9TH_EXPERT_DAMAGE_DOWN_BACK",
	FLY_DAMAGE_FRONT			= "WALLY_9TH_EXPERT_DAMAGE_FLY_FRONT",
	FLY_DAMAGE_BACK				= "WALLY_9TH_EXPERT_DAMAGE_FLY_BACK",
	SMALL_DAMAGE_AIR			= "WALLY_9TH_EXPERT_DAMAGE_AIR",	
	BIG_DAMAGE_AIR				= "WALLY_9TH_EXPERT_DAMAGE_AIR",
	DOWN_DAMAGE_AIR				= "WALLY_9TH_EXPERT_DAMAGE_AIR_DOWN",
	DOWN_DAMAGE_AIR_LANDING				= "WALLY_9TH_EXPERT_DAMAGE_AIR_DOWN_LANDING",
	UP_DAMAGE					= "WALLY_9TH_EXPERT_DAMAGE_AIR_UP",
	DAMAGE_REVENGE				= "WALLY_9TH_EXPERT_DAMAGE_REVENGE",
	
	DAMAGE_EXTRA_STATES         = { "WALLY_9TH_EXPERT_DAMAGE_AIR_FALL","WALLY_9TH_EXPERT_STAND_UP_FRONT","WALLY_9TH_EXPERT_STAND_UP_BACK",
		"WALLY_9TH_EXPERT_STAND_UP_ATTACK_FRONT","WALLY_9TH_EXPERT_STAND_UP_ATTACK_BACK","WALLY_9TH_EXPERT_JUMP_DOWN","WALLY_9TH_EXPERT_JUMP_LANDING",	},		
	
	DYING_LAND_FRONT			= "WALLY_9TH_EXPERT_DYING_LAND_FRONT",
	DYING_LAND_BACK				= "WALLY_9TH_EXPERT_DYING_LAND_BACK",
	DYING_SKY					= "WALLY_9TH_EXPERT_DYING_SKY",

	REVENGE_ATTACK				= "",	
}


INIT_AI = 
{
	TARGET = 
	{
		TARGET_PRIORITY 			= TARGET_PRIORITY["TP_NEAR_FIRST"],
		TARGET_INTERVAL				= 2,		-- sec
		TARGET_NEAR_RANGE			= 90000,		-- 이 거리보다 가까우면 TARGET_SUCCESS_RATE에 관계없이 무조건 타게팅된다
		TARGET_RANGE				= 90000,		-- cm
		TARGET_LOST_RANGE			= 91000,		-- cm
		TARGET_SUCCESS_RATE			= 100,  --100,		-- %
		ATTACK_TARGET_RATE			= 100, -- 90,		-- 나를 공격한 유닛을 타게팅할 확률
		PRESERVE_LAST_TARGET_RATE	= 100, -- 60,		-- 이전에 타게팅된 유닛을 계속 타게팅할 확률
	},

	CHASE_MOVE = 
	{		
		DEST_GAP			= 100,	-- 목적지에서 이 거리 안에 있으면 도착했다고 판단한다
		MOVE_GAP			= 310,
		
		DIR_CHANGE_INTERVAL = 0.7,
		
		MOVE_SPLIT_RANGE	= 600,
		WALK_INTERVAL		= 2,
		NEAR_WALK_RATE		= 50,   --  90,
		FAR_WALK_RATE		= 50,   -- 70, 
		
		JUMP_INTERVAL		= 5,
		UP_JUMP_RATE		= 100, -- 10,
		UP_DOWN_RATE		= 10,
		DOWN_JUMP_RATE		= 100,    --  10,
		DOWN_DOWN_RATE		= 10,
	},	
	
	PATROL_MOVE = 	
	{
		PATROL_BEGIN_RATE		= 50, --50,		
		PATROL_RANGE			= 500,
		PATROL_COOL_TIME		= 1.5,
		ONLY_THIS_LINE_GROUP	= TRUE,
	},
}







--------------------------------------------------------------------------------------------------------
WALLY_9TH_EXPERT_DISABLED = 
{
	SHOW						= FALSE,

	ANIM_NAME					= "Wait",
	PLAY_TYPE					= XSKIN_ANIM_PLAYTYPE["XAP_ONE_WAIT"],
	TRANSITION					= TRUE,
	
	LAND_CONNECT				= FALSE,
	CAN_PUSH_UNIT				= FALSE,
	CAN_PASS_UNIT				= TRUE,		
	
	FALL_DOWN					= FALSE,
	
	SPEED_X						= 0,
	SPEED_Y						= 0,
		
	IMMADIATE_PACKET_SEND		= TRUE,
	
	INVINCIBLE					= { 0, 99999.0 },

--[[	
	DISABLE_COLLISION_BOX =
	{
		"COLLISION_SPHERE1_Face",
		"COLLISION_SPHERE2_Upbody",
		"COLLISION_SPHERE3_Lowbody",
	},
--]]	
}





--------------------------------------------------------------------------------------------------------
WALLY_9TH_EXPERT_START = 
{
	SHOW						= TRUE,
	
	ANIM_NAME					= "WaitStart",
	PLAY_TYPE					= XSKIN_ANIM_PLAYTYPE["XAP_ONE_WAIT"],
	TRANSITION					= TRUE,
	
	LAND_CONNECT				= TRUE,
	CAN_PUSH_UNIT				= TRUE,
	CAN_PASS_UNIT				= FALSE,		

    SOUND_PLAY0			= { 0.01, "Wally9_StartSmoke.ogg" },
    SOUND_PLAY1			= { 2.667, "Wally9_SwordOut.ogg" },
    SOUND_PLAY2			= { 2.863, "Wally9_WaitStart.ogg" },

	SPEED_X						= 0,
	SPEED_Y						= 0,
	
	NEVER_MOVE					= TRUE,
	RIGHT						= FALSE,
	IMMADIATE_PACKET_SEND		= TRUE,
	
	SLASH_TRACE					= { 2.8, 3.0 },
	SLASH_TRACE0				= { 2.8, 3.0, 1 }, 
	
	
	PARTICLE_SEQ = 
	{
		--Major, time, Name, weaponBonePos, Pos, StateEndDelete, bTrace, posx, posy, posz, bApplyUnitRotation, rotx, roty, rotz,
		{ TRUE, 0.01, "Wally9th_Armor_Event_BrokenMesh", FALSE, "", TRUE, FALSE, },
		{ TRUE, 0.1, "Wally_9th_Death_Dark_Smoke", FALSE, "", TRUE, FALSE, -190, 50, 50, },
		{ TRUE, 0.2, "Wally_9th_Death_Dark_Smoke", FALSE, "", TRUE, FALSE, 220, 0, -100, },
		
		{ TRUE, 0.01, "Wally_9th_Death_White_Smoke", FALSE, "Bip01_Spine1", TRUE, TRUE, 0, 0, -100, },
		{ TRUE, 0.01, "Wally_9th_Death_White_Smoke", FALSE, "", TRUE, TRUE, 0, 0, -50, },
		
		{ TRUE, 0.01, "Wally_9th_Death_White_Smoke", FALSE, "", TRUE, FALSE, -200, 100, 0, },
		{ TRUE, 0.01, "Wally_9th_Death_White_Smoke", FALSE, "", TRUE, FALSE, 200, 150, 0, },
		
		{ FALSE, 0.01, "Wally_8th_Spark", FALSE, "", TRUE, FALSE, -130, 120, -150, },
		{ FALSE, 0.01, "Wally_8th_Spark", FALSE, "", TRUE, FALSE, 170, 50, -150, },

	},
	

	
	EVENT_PROCESS = 
	{
		{ STATE_CHANGE_TYPE["SCT_MOTION_END"],				"WALLY_9TH_EXPERT_WAIT",						},
	},
}


WALLY_9TH_EXPERT_WIN = 
{
	ANIM_NAME					= "Win",
	PLAY_TYPE					= XSKIN_ANIM_PLAYTYPE["XAP_ONE_WAIT"],
	TRANSITION					= TRUE,
	
	INVINCIBLE					= { 0, 100, },
	
	CAN_PUSH_UNIT				= TRUE,
	CAN_PASS_UNIT				= FALSE,	

    SOUND_PLAY0			= { 0.818, "Wally9_Win.ogg" },
	
	SPEED_X						= 0,
	SPEED_Y						= 0,
	
	RIGHT						= TRUE,
	
	IMMADIATE_PACKET_SEND		= TRUE,
	
	TALK_BOX =
	{
		{ RATE = 50, MESSAGE = STR_ID_1550 },
 	},
}

WALLY_9TH_EXPERT_WAIT = 
{
	ANIM_NAME					= "Wait",
	PLAY_TYPE					= XSKIN_ANIM_PLAYTYPE["XAP_LOOP"],
	TRANSITION					= TRUE,
	LAND_CONNECT				= TRUE,
	
	CAN_PUSH_UNIT				= TRUE,
	CAN_PASS_UNIT				= FALSE,	
	
	SPEED_X						= 0,
	SPEED_Y						= 0,
	
	IMMADIATE_PACKET_SEND		= TRUE,
	EVENT_INTERVAL_TIME0		= 1,
	
	SHOW						= TRUE,
	
	
	EVENT_PROCESS = 
	{	
		{ STATE_CHANGE_TYPE["SCT_CONDITION_FUNCTION"],		"WALLY_9TH_EXPERT_WIN",						"CF_WALLY_9TH_EXPERT_WIN",	},
		{ STATE_CHANGE_TYPE["SCT_FOOT_ON_LINE_FALSE_DOWN"],	"WALLY_9TH_EXPERT_JUMP_DOWN",					},

		{ STATE_CHANGE_TYPE["SCT_CONDITION_TABLE"],			"WALLY_9TH_EXPERT_SP_RAMPAGE",					"CT_WALLY_9TH_EXPERT_SP_RAMPAGE",			},
		{ STATE_CHANGE_TYPE["SCT_CONDITION_TABLE"],			"WALLY_9TH_EXPERT_ATTACKB",					"CT_WALLY_9TH_EXPERT_ATTACKB",				},
		{ STATE_CHANGE_TYPE["SCT_CONDITION_TABLE"],			"WALLY_9TH_EXPERT_COMBO",						"CT_WALLY_9TH_EXPERT_COMBO",				},
		{ STATE_CHANGE_TYPE["SCT_CONDITION_TABLE"],			"WALLY_9TH_EXPERT_BARRIER",					"CT_WALLY_9TH_EXPERT_BARRIER",				},
		{ STATE_CHANGE_TYPE["SCT_CONDITION_TABLE"],			"WALLY_9TH_EXPERT_JUMP_UP_DIR_FOR_ATTACK",		"CT_WALLY_9TH_EXPERT_JUMP_ATTACK",			},
		{ STATE_CHANGE_TYPE["SCT_CONDITION_TABLE"],			"WALLY_9TH_EXPERT_DASH_ATTACK",				"CT_WALLY_9TH_EXPERT_DASH_ATTACK",			},
		{ STATE_CHANGE_TYPE["SCT_CONDITION_TABLE"],			"WALLY_9TH_EXPERT_LASER_ATTACK",				"CT_WALLY_9TH_EXPERT_LASER_ATTACK",		},

		{ STATE_CHANGE_TYPE["SCT_AI_WALK"],					"WALLY_9TH_EXPERT_WALK",						}, 
		{ STATE_CHANGE_TYPE["SCT_AI_DASH"],					"WALLY_9TH_EXPERT_DASH",						},
		{ STATE_CHANGE_TYPE["SCT_AI_JUMP"],					"WALLY_9TH_EXPERT_JUMP_UP",					},
		{ STATE_CHANGE_TYPE["SCT_AI_JUMP_DIR"],				"WALLY_9TH_EXPERT_JUMP_UP_DIR",				},
		{ STATE_CHANGE_TYPE["SCT_AI_DOWN"],					"WALLY_9TH_EXPERT_JUMP_DOWN",					},
		{ STATE_CHANGE_TYPE["SCT_AI_DOWN_DIR"],				"WALLY_9TH_EXPERT_JUMP_DOWN_DIR",				},

	},
	
	CT_WALLY_9TH_EXPERT_ATTACKB =
	{
		EVENT_INTERVAL_ID			= 0,
		DISTANCE_TO_TARGET_NEAR		= 300,
		RATE						= 30,
	},
	
	CT_WALLY_9TH_EXPERT_COMBO =
	{
		EVENT_INTERVAL_ID			= 0,
		DISTANCE_TO_TARGET_NEAR		= 300,
		RATE						= 20,
	},
	
	CT_WALLY_9TH_EXPERT_BARRIER =
	{
		EVENT_INTERVAL_ID			= 0,
		DISTANCE_TO_TARGET_NEAR		= 500,
 		RATE						= 20,
	},
		
	CT_WALLY_9TH_EXPERT_DASH_ATTACK =
	{
		EVENT_INTERVAL_ID			= 0,
		DISTANCE_TO_TARGET_NEAR		= 500,
		RATE						= 30,
	},
		
	CT_WALLY_9TH_EXPERT_JUMP_ATTACK = 
	{
		EVENT_INTERVAL_ID			= 0,
		DISTANCE_TO_TARGET_NEAR		= 300,
		RATE						= 30,
	},
	
	CT_WALLY_9TH_EXPERT_LASER_ATTACK = 
	{
		EVENT_INTERVAL_ID			= 0,
		DISTANCE_OVER_TARGET_NEAR	= 600,
		RATE						= 20, 
	},
	
	CT_WALLY_9TH_EXPERT_SP_RAMPAGE =
	{
		EVENT_INTERVAL_ID			= 0,
		DISTANCE_TO_TARGET_NEAR		= 400,
		MY_MP_MORE_THAN_PERCENT		= 100,
		RATE						= 0, 
	},
	
}



WALLY_9TH_EXPERT_WALK = 
{
	ANIM_NAME					= "Walk",
	PLAY_TYPE					= XSKIN_ANIM_PLAYTYPE["XAP_LOOP"],
	TRANSITION					= TRUE,
	
	CAN_PUSH_UNIT				= TRUE,
	CAN_PASS_UNIT				= FALSE,

       
	PASSIVE_SPEED_X				= INIT_PHYSIC["WALK_SPEED"],
	
	ALLOW_DIR_CHANGE			= TRUE,
	IMMADIATE_PACKET_SEND		= TRUE,
	
	EVENT_INTERVAL_TIME0		= 1,
	EVENT_INTERVAL_TIME1		= 3,
	
	EVENT_PROCESS = 
	{		

		{ STATE_CHANGE_TYPE["SCT_CONDITION_FUNCTION"],		"WALLY_9TH_EXPERT_WIN",						"CF_WALLY_9TH_EXPERT_WIN",					},
		{ STATE_CHANGE_TYPE["SCT_FOOT_ON_LINE_FALSE_DOWN"],	"WALLY_9TH_EXPERT_JUMP_DOWN_DIR",				},

		{ STATE_CHANGE_TYPE["SCT_CONDITION_TABLE"],			"WALLY_9TH_EXPERT_SP_RAMPAGE",					"CT_WALLY_9TH_EXPERT_SP_RAMPAGE",			},
		{ STATE_CHANGE_TYPE["SCT_CONDITION_TABLE"],			"WALLY_9TH_EXPERT_ATTACKB",					"CT_WALLY_9TH_EXPERT_ATTACKB",				},
		{ STATE_CHANGE_TYPE["SCT_CONDITION_TABLE"],			"WALLY_9TH_EXPERT_COMBO",						"CT_WALLY_9TH_EXPERT_COMBO",				},
		{ STATE_CHANGE_TYPE["SCT_CONDITION_TABLE"],			"WALLY_9TH_EXPERT_DASH_ATTACK",				"CT_WALLY_9TH_EXPERT_DASH_ATTACK",			},
		{ STATE_CHANGE_TYPE["SCT_CONDITION_TABLE"],			"WALLY_9TH_EXPERT_BARRIER",					"CT_WALLY_9TH_EXPERT_BARRIER",				},		
		{ STATE_CHANGE_TYPE["SCT_CONDITION_TABLE"],			"WALLY_9TH_EXPERT_JUMP_UP_DIR_FOR_ATTACK",		"CT_WALLY_9TH_EXPERT_JUMP_ATTACK",			},
		{ STATE_CHANGE_TYPE["SCT_CONDITION_TABLE"],			"WALLY_9TH_EXPERT_LASER_ATTACK",				"CT_WALLY_9TH_EXPERT_LASER_ATTACK",		},		
		
		{ STATE_CHANGE_TYPE["SCT_AI_WAIT"],					"WALLY_9TH_EXPERT_WAIT",						},
		{ STATE_CHANGE_TYPE["SCT_AI_DASH"],					"WALLY_9TH_EXPERT_DASH",						},
		{ STATE_CHANGE_TYPE["SCT_AI_JUMP"],					"WALLY_9TH_EXPERT_JUMP_UP",					},
		{ STATE_CHANGE_TYPE["SCT_AI_JUMP_DIR"],				"WALLY_9TH_EXPERT_JUMP_UP_DIR",				},
		{ STATE_CHANGE_TYPE["SCT_AI_DOWN"],					"WALLY_9TH_EXPERT_JUMP_DOWN",					},
		{ STATE_CHANGE_TYPE["SCT_AI_DOWN_DIR"],				"WALLY_9TH_EXPERT_JUMP_DOWN_DIR",				},

	},
	
	CT_WALLY_9TH_EXPERT_ATTACKB = 
	{
		EVENT_INTERVAL_ID			= 0,
		DISTANCE_TO_TARGET_NEAR		= 300,
		RATE						= 30,
	},
	
	CT_WALLY_9TH_EXPERT_COMBO =
	{
		EVENT_INTERVAL_ID			= 0,
		DISTANCE_TO_TARGET_NEAR		= 300,
		RATE						= 20,
	},
	
	CT_WALLY_9TH_EXPERT_DASH_ATTACK =
	{
		EVENT_INTERVAL_ID			= 0,
		DISTANCE_TO_TARGET_NEAR		= 500,
		RATE						= 30,
	},


	CT_WALLY_9TH_EXPERT_BARRIER =
	{
		EVENT_INTERVAL_ID			= 0,
		DISTANCE_TO_TARGET_NEAR		= 500,
 		RATE						= 30,
	},		
	CT_WALLY_9TH_EXPERT_JUMP_ATTACK = 
	{
		EVENT_INTERVAL_ID			= 0,
		DISTANCE_TO_TARGET_NEAR		= 300,
		RATE						= 40,
	},

	CT_WALLY_9TH_EXPERT_LASER_ATTACK = 
	{
		EVENT_INTERVAL_ID			= 0,
		DISTANCE_OVER_TARGET_NEAR	= 600,
		RATE						= 20,  
	},
	
	CT_WALLY_9TH_EXPERT_SP_RAMPAGE =
	{
		EVENT_INTERVAL_ID			= 0,
		DISTANCE_TO_TARGET_NEAR		= 500,
		MY_MP_MORE_THAN_PERCENT		= 100,
		RATE						= 30, 
	},
	
	


	TALK_BOX =
	{
		EVENT_INTERVAL_ID		= 1,
		{ RATE = 10, MESSAGE = STR_ID_1438 },
		{ RATE = 10, MESSAGE = STR_ID_1551 },
 	}
}



WALLY_9TH_EXPERT_DASH =
{
	ANIM_NAME					= "Dash",
	PLAY_TYPE					= XSKIN_ANIM_PLAYTYPE["XAP_LOOP"],
	TRANSITION					= FALSE,
	LAND_CONNECT				= FALSE,
	
	CAN_PUSH_UNIT				= TRUE,
	CAN_PASS_UNIT				= FALSE,
	--SUPER_ARMOR					= TRUE,

	PASSIVE_SPEED_X				= INIT_PHYSIC["RUN_SPEED"],
	

	IMMADIATE_PACKET_SEND		= TRUE,
	ALLOW_DIR_CHANGE			= FALSE,
	
	EVENT_INTERVAL_TIME0		= 1,
	EVENT_INTERVAL_TIME1		= 3,
	
	EVENT_PROCESS = 
	{		

		{ STATE_CHANGE_TYPE["SCT_CONDITION_FUNCTION"],		"WALLY_9TH_EXPERT_WIN",						"CF_WALLY_9TH_EXPERT_WIN",					},
		{ STATE_CHANGE_TYPE["SCT_FOOT_ON_LINE_FALSE_DOWN"],	"WALLY_9TH_EXPERT_JUMP_DOWN_DIR",				},


		{ STATE_CHANGE_TYPE["SCT_CONDITION_TABLE"],			"WALLY_9TH_EXPERT_DASH_ATTACK",				"CT_WALLY_9TH_EXPERT_DASH_ATTACK",			},
		{ STATE_CHANGE_TYPE["SCT_CONDITION_TABLE"],			"WALLY_9TH_EXPERT_SP_RAMPAGE",					"CT_WALLY_9TH_EXPERT_SP_RAMPAGE",			},
		{ STATE_CHANGE_TYPE["SCT_CONDITION_TABLE"],			"WALLY_9TH_EXPERT_ATTACKB",					"CT_WALLY_9TH_EXPERT_ATTACKB",				},
		{ STATE_CHANGE_TYPE["SCT_CONDITION_TABLE"],			"WALLY_9TH_EXPERT_COMBO",						"CT_WALLY_9TH_EXPERT_COMBO",				},
		{ STATE_CHANGE_TYPE["SCT_CONDITION_TABLE"],			"WALLY_9TH_EXPERT_BARRIER",					"CT_WALLY_9TH_EXPERT_BARRIER",				},
		{ STATE_CHANGE_TYPE["SCT_CONDITION_TABLE"],			"WALLY_9TH_EXPERT_JUMP_UP_DIR_FOR_ATTACK",		"CT_WALLY_9TH_EXPERT_JUMP_ATTACK",			},
		{ STATE_CHANGE_TYPE["SCT_CONDITION_TABLE"],			"WALLY_9TH_EXPERT_LASER_ATTACK",				"CT_WALLY_9TH_EXPERT_LASER_ATTACK",		},		

		
		{ STATE_CHANGE_TYPE["SCT_AI_WAIT"],					"WALLY_9TH_EXPERT_WAIT",						},
		{ STATE_CHANGE_TYPE["SCT_AI_WALK"],					"WALLY_9TH_EXPERT_WALK",						}, 
		{ STATE_CHANGE_TYPE["SCT_AI_JUMP"],					"WALLY_9TH_EXPERT_JUMP_UP",					},
		{ STATE_CHANGE_TYPE["SCT_AI_JUMP_DIR"],				"WALLY_9TH_EXPERT_JUMP_UP_DIR",				},
		{ STATE_CHANGE_TYPE["SCT_AI_DOWN"],					"WALLY_9TH_EXPERT_JUMP_DOWN",					},
		{ STATE_CHANGE_TYPE["SCT_AI_DOWN_DIR"],				"WALLY_9TH_EXPERT_JUMP_DOWN_DIR",				},

	},
	
	CT_WALLY_9TH_EXPERT_ATTACKB = 
	{
		EVENT_INTERVAL_ID			= 0,
		DISTANCE_TO_TARGET_NEAR		= 300,
		RATE						= 30,
	},
	
	CT_WALLY_9TH_EXPERT_COMBO =
	{
		EVENT_INTERVAL_ID			= 0,
		DISTANCE_TO_TARGET_NEAR		= 300,
		RATE						= 10,
	},
	
	CT_WALLY_9TH_EXPERT_DASH_ATTACK =
	{
		EVENT_INTERVAL_ID			= 0,
		DISTANCE_TO_TARGET_NEAR		= 700,
		RATE						= 60,
	},
	
	CT_WALLY_9TH_EXPERT_BARRIER =
	{
		EVENT_INTERVAL_ID			= 0,
		DISTANCE_TO_TARGET_NEAR		= 500,
		RATE						= 30, 
	},
	
	
	CT_WALLY_9TH_EXPERT_JUMP_ATTACK = 
	{
		EVENT_INTERVAL_ID			= 0,
		DISTANCE_TO_TARGET_NEAR		= 300,
		RATE						= 40,
	},

	CT_WALLY_9TH_EXPERT_LASER_ATTACK = 
	{
		EVENT_INTERVAL_ID			= 0,
		DISTANCE_OVER_TARGET_NEAR	= 600,
		RATE						= 20,  
	},
	
	CT_WALLY_9TH_EXPERT_SP_RAMPAGE =
	{
		EVENT_INTERVAL_ID			= 0,
		DISTANCE_TO_TARGET_NEAR		= 400,
		MY_MP_MORE_THAN_PERCENT		= 100,
		RATE						= 30, 
	},
	
	

	TALK_BOX =
	{
		{ RATE = 15, MESSAGE = STR_ID_1552 },
		{ RATE = 15, MESSAGE = STR_ID_1456 },
 	},

}


WALLY_9TH_EXPERT_DASH_END = 
{
	ANIM_NAME					= "DashEnd",
	PLAY_TYPE					= XSKIN_ANIM_PLAYTYPE["XAP_ONE_WAIT"],
	TRANSITION					= FALSE,
	
	CAN_PUSH_UNIT				= TRUE,
	CAN_PASS_UNIT				= FALSE,

	SOUND_PLAY0			= { 0.189, "Wally9_DashEnd.ogg" },
 	
	SPEED_X						= INIT_PHYSIC["RUN_SPEED"],
	
	IMMADIATE_PACKET_SEND		= TRUE,
	
	EVENT_PROCESS = 
	{		
		{ STATE_CHANGE_TYPE["SCT_FOOT_ON_LINE_FALSE_DOWN"],	"WALLY_9TH_EXPERT_JUMP_DOWN_DIR",				},
		{ STATE_CHANGE_TYPE["SCT_MOTION_END"],				"WALLY_9TH_EXPERT_WAIT",						},
	},
}


WALLY_9TH_EXPERT_JUMP_UP_DIR_FOR_ATTACK =
{
	ANIM_NAME					= "JumpUp",
	PLAY_TYPE					= XSKIN_ANIM_PLAYTYPE["XAP_LOOP"],
	TRANSITION					= TRUE,
	LAND_CONNECT				= FALSE,
	
	CAN_PUSH_UNIT				= TRUE,
	CAN_PASS_UNIT				= FALSE,
	
	PASSIVE_SPEED_X				= INIT_PHYSIC["WALK_SPEED"],
	SPEED_Y						= INIT_PHYSIC["JUMP_SPEED"],
	
	IMMADIATE_PACKET_SEND		= TRUE,
	
	EVENT_PROCESS = 
	{		
		{ STATE_CHANGE_TYPE["SCT_NEGATIVE_Y_SPEED"],			"WALLY_9TH_EXPERT_JUMP_ATTACK",		},
	},
}



WALLY_9TH_EXPERT_JUMP_UP = 
{
	ANIM_NAME					= "JumpUp",
	PLAY_TYPE					= XSKIN_ANIM_PLAYTYPE["XAP_LOOP"],
	TRANSITION					= TRUE,
	LAND_CONNECT				= FALSE,
	
	CAN_PUSH_UNIT				= TRUE,
	CAN_PASS_UNIT				= FALSE,
	
	SPEED_X						= 0,
	SPEED_Y						= INIT_PHYSIC["JUMP_SPEED"],
	ADD_POS_Y					= 45,
	
	IMMADIATE_PACKET_SEND		= TRUE,
	
	EVENT_PROCESS = 
	{		
		{ STATE_CHANGE_TYPE["SCT_CONDITION_TABLE"],			"WALLY_9TH_EXPERT_JUMP_ATTACK",				"CT_WALLY_9TH_EXPERT_JUMP_ATTACK",	},
		{ STATE_CHANGE_TYPE["SCT_NEGATIVE_Y_SPEED"],		"WALLY_9TH_EXPERT_JUMP_DOWN",				},
	},
	
	
	CT_WALLY_9TH_EXPERT_JUMP_ATTACK = 
	{
		DISTANCE_TO_TARGET_NEAR		= 500,
		SMALL_THEN_Y_SPEED			= 0,
		RATE						= 30,
	},	

}


WALLY_9TH_EXPERT_JUMP_DOWN = 
{
	ANIM_NAME					= "JumpDown",
	PLAY_TYPE					= XSKIN_ANIM_PLAYTYPE["XAP_LOOP"],
	TRANSITION					= TRUE,
	LAND_CONNECT				= FALSE,
	
	CAN_PUSH_UNIT				= TRUE,
	CAN_PASS_UNIT				= FALSE,
	
	
	IMMADIATE_PACKET_SEND		= TRUE,
		
	EVENT_PROCESS = 
	{		
		{ STATE_CHANGE_TYPE["SCT_FOOT_ON_LINE_TRUE"],		"WALLY_9TH_EXPERT_JUMP_LANDING",				},
	},
}


WALLY_9TH_EXPERT_JUMP_UP_DIR =
{
	ANIM_NAME					= "JumpUp",
	PLAY_TYPE					= XSKIN_ANIM_PLAYTYPE["XAP_LOOP"],
	TRANSITION					= TRUE,
	LAND_CONNECT				= FALSE,
	
	CAN_PUSH_UNIT				= TRUE,
	CAN_PASS_UNIT				= FALSE,
	
	PASSIVE_SPEED_X				= INIT_PHYSIC["WALK_SPEED"],
	SPEED_Y						= INIT_PHYSIC["JUMP_SPEED"],
	ADD_POS_Y					= 45,
	
	IMMADIATE_PACKET_SEND		= TRUE,
	
	EVENT_PROCESS = 
	{		
		{ STATE_CHANGE_TYPE["SCT_CONDITION_TABLE"],			"WALLY_9TH_EXPERT_JUMP_ATTACK",				"CT_WALLY_9TH_EXPERT_JUMP_ATTACK",	},
		{ STATE_CHANGE_TYPE["SCT_NEGATIVE_Y_SPEED"],		"WALLY_9TH_EXPERT_JUMP_DOWN_DIR",				},
	},


	CT_WALLY_9TH_EXPERT_JUMP_ATTACK = 
	{
		DISTANCE_TO_TARGET_NEAR		= 800,
		SMALL_THEN_Y_SPEED			= 0,
		RATE						= 30,
	},
	
}



WALLY_9TH_EXPERT_JUMP_DOWN_DIR =
{
	ANIM_NAME					= "JumpDown",
	PLAY_TYPE					= XSKIN_ANIM_PLAYTYPE["XAP_LOOP"],
	TRANSITION					= TRUE,
	LAND_CONNECT				= FALSE,
	
	CAN_PUSH_UNIT				= TRUE,
	CAN_PASS_UNIT				= FALSE,
	
	PASSIVE_SPEED_X				= INIT_PHYSIC["WALK_SPEED"],
	
	IMMADIATE_PACKET_SEND		= TRUE,
		
	EVENT_PROCESS = 
	{		
		{ STATE_CHANGE_TYPE["SCT_FOOT_ON_LINE_TRUE"],		"WALLY_9TH_EXPERT_JUMP_LANDING",				},
	},
}



WALLY_9TH_EXPERT_JUMP_LANDING = 
{
	ANIM_NAME					= "JumpLanding",
	PLAY_TYPE					= XSKIN_ANIM_PLAYTYPE["XAP_ONE_WAIT"],
	TRANSITION					= TRUE,
	LAND_CONNECT				= FALSE,
	
	CAN_PUSH_UNIT				= TRUE,
	CAN_PASS_UNIT				= FALSE,
	
	--SUPER_ARMOR                  = TRUE,

	    SOUND_PLAY0			= { 0.130, "Wally9_StepLanding.ogg" },

	SPEED_X						= 0,
	SPEED_Y						= 0,
		
	IMMADIATE_PACKET_SEND		= TRUE,

	EVENT_PROCESS = 
	{		
		{ STATE_CHANGE_TYPE["SCT_FOOT_ON_LINE_FALSE_DOWN"],	"WALLY_9TH_EXPERT_JUMP_DOWN",				},
		{ STATE_CHANGE_TYPE["SCT_MOTION_END"],				"WALLY_9TH_EXPERT_WAIT",					},
	},
}




WALLY_9TH_EXPERT_ATTACKB = 
{
	ANIM_NAME					= "AttackB",
	PLAY_TYPE					= XSKIN_ANIM_PLAYTYPE["XAP_ONE_WAIT"],
	TRANSITION					= FALSE,
	LAND_CONNECT				= FALSE,
	
	CAN_PUSH_UNIT				= TRUE,
	CAN_PASS_UNIT				= FALSE,

    SOUND_PLAY0			= { 0.389, "Wally9_AttackB.ogg" },

	SPEED_X						= 0,
	SPEED_Y						= 0,	
	
	VIEW_TARGET					= TRUE,
	IMMADIATE_PACKET_SEND		= TRUE,
	SUPER_ARMOR					= TRUE,
	
	
	EVENT_PROCESS = 
	{	
		{ STATE_CHANGE_TYPE["SCT_FOOT_ON_LINE_FALSE_DOWN"],	"WALLY_9TH_EXPERT_JUMP_DOWN",							},
		{ STATE_CHANGE_TYPE["SCT_MOTION_END"],				"WALLY_9TH_EXPERT_WAIT",								},	
		
	},
	
	ATTACK_TIME0				= { 1.000, 1.133, }, 
	SLASH_TRACE					= { 0.1, 0.6 },
	SLASH_TRACE0				= { 0.1, 0.6, 1 }, 
	
	DAMAGE_DATA = 
	{
		DAMAGE_TYPE		= DAMAGE_TYPE["DT_PHYSIC"],
		HIT_TYPE		= HIT_TYPE["HT_SWORD_SLASH"],
		REACT_TYPE		= REACT_TYPE["RT_FLY"],
		
		DAMAGE = 
		{
			PHYSIC		= 1.5,
		},
		
		BACK_SPEED_X			= 1000,
		BACK_SPEED_Y			= 1700,
		
		CAMERA_CRASH_GAP		= 5.0,	
		CAMERA_CRASH_TIME		= 0.2,		
	},
}




WALLY_9TH_EXPERT_COMBO =
{
	ANIM_NAME					= "Combo",
	PLAY_TYPE					= XSKIN_ANIM_PLAYTYPE["XAP_ONE_WAIT"],
	TRANSITION					= FALSE,
	LAND_CONNECT				= FALSE,
	
	CAN_PUSH_UNIT				= TRUE,
	CAN_PASS_UNIT				= FALSE,

	SPEED_X						= 0,
	SPEED_Y						= 0,	

    SOUND_PLAY0			= { 0.118, "Wally9_Combo.ogg" },
    SOUND_PLAY1			= { 0.639, "Wally9_Slash.ogg" },
    SOUND_PLAY2			= { 1.130, "Wally9_Slash.ogg" },
    SOUND_PLAY3			= { 1.847, "Wally9_Slash.ogg" },
	
	IMMADIATE_PACKET_SEND		= TRUE,
	SUPER_ARMOR					= TRUE,
		
	EVENT_PROCESS = 
	{		
		{ STATE_CHANGE_TYPE["SCT_FOOT_ON_LINE_FALSE_DOWN"],	"WALLY_9TH_EXPERT_JUMP_DOWN",				},
		{ STATE_CHANGE_TYPE["SCT_MOTION_END"],				"WALLY_9TH_EXPERT_WAIT",					},
	},
	
	ATTACK_TIME0				= { 1.300, 1.405, },
	ATTACK_TIME1				= { 1.805, 1.905, },
	ATTACK_TIME2				= { 2.505, 2.705, },
	
	SLASH_TRACE					= { 0.1, 2.2 },
	SLASH_TRACE0				= { 0.1, 2.2, 1 }, 
	
		
	
	DAMAGE_DATA = 
	{
		DAMAGE_TYPE		= DAMAGE_TYPE["DT_PHYSIC"],
		HIT_TYPE		= HIT_TYPE["HT_SWORD_SLASH"],
		REACT_TYPE		= REACT_TYPE["RT_BIG_DAMAGE"],
		
		DAMAGE = 
		{
			PHYSIC		= 0.5,
		},
		
		BACK_SPEED_X			= 0.0,
		BACK_SPEED_Y			= 0.0,
		
		CAMERA_CRASH_GAP		= 5.0,	
		CAMERA_CRASH_TIME		= 0.2,		
	},
	
	DAMAGE_DATA2 = 
	{
		DAMAGE_TYPE		= DAMAGE_TYPE["DT_PHYSIC"],
		HIT_TYPE		= HIT_TYPE["HT_SWORD_SLASH"],
		REACT_TYPE		= REACT_TYPE["RT_UP"],
		
		DAMAGE = 
		{
			PHYSIC		= 0.5,
		},
		
		BACK_SPEED_X			= 1000,
		BACK_SPEED_Y			= 1700,		
		
		CAMERA_CRASH_GAP		= 5.0,	
		CAMERA_CRASH_TIME		= 0.2,		
	},
	
	DAMAGE_DATA3 = 
	{
		DAMAGE_TYPE		= DAMAGE_TYPE["DT_PHYSIC"],
		HIT_TYPE		= HIT_TYPE["HT_SWORD_SLASH"],
		REACT_TYPE		= REACT_TYPE["RT_SMALL_DAMAGE"],
		
		DAMAGE = 
		{
			PHYSIC		= 0.1,
		},
		
		BACK_SPEED_X			= 0.0,
		BACK_SPEED_Y			= 0.0,
		
		CAMERA_CRASH_GAP		= 5.0,	
		CAMERA_CRASH_TIME		= 0.2,	
		
		RE_ATTACK				= TRUE,		
		HIT_GAP					= 0.1,	
	},
	
	
	DAMAGE_DATA4 = 
	{
		DAMAGE_TYPE		= DAMAGE_TYPE["DT_PHYSIC"],
		HIT_TYPE		= HIT_TYPE["HT_SWORD_SLASH"],
		REACT_TYPE		= REACT_TYPE["RT_DOWN"],
		
		DAMAGE = 
		{
			PHYSIC		= 0.1,
		},
		
		BACK_SPEED_X			= 0.0,
		BACK_SPEED_Y			= 0.0,
		
		CAMERA_CRASH_GAP		= 5.0,	
		CAMERA_CRASH_TIME		= 0.2,		
	},
		
}



WALLY_9TH_EXPERT_DASH_ATTACK =
{
	ANIM_NAME					= "DashAttack",
	PLAY_TYPE					= XSKIN_ANIM_PLAYTYPE["XAP_ONE_WAIT"],
	TRANSITION					= FALSE,
	LAND_CONNECT				= FALSE,
	
	CAN_PUSH_UNIT				= TRUE,
	CAN_PASS_UNIT				= FALSE,

    SOUND_PLAY0			= { 0.504, "Wally9_DashAttack.ogg" },

	
	IMMADIATE_PACKET_SEND		= TRUE,
		
	EVENT_PROCESS = 
	{		
		{ STATE_CHANGE_TYPE["SCT_MOTION_END"],				"WALLY_9TH_EXPERT_WAIT",						},
	},
	
	ATTACK_TIME0				= { 0.46, 0.7, },
	
	
	SLASH_TRACE					= { 0.2, 1.2 },
	SLASH_TRACE0				= { 0.2, 1.2, 1 }, 
	
		
	
	DAMAGE_DATA = 
	{
		DAMAGE_TYPE		= DAMAGE_TYPE["DT_PHYSIC"],
		HIT_TYPE		= HIT_TYPE["HT_SWORD_SLASH"],
		REACT_TYPE		= REACT_TYPE["RT_SMALL_DAMAGE"],
		
		DAMAGE = 
		{
			PHYSIC		= 0.3,
		},
		
		BACK_SPEED_X			= 1000.0,
		BACK_SPEED_Y			= 0.0,
		
		CAMERA_CRASH_GAP		= 5.0,	
		CAMERA_CRASH_TIME		= 0.2,		
	},
	
		
	DAMAGE_DATA2 = 
	{
		DAMAGE_TYPE		= DAMAGE_TYPE["DT_PHYSIC"],
		HIT_TYPE		= HIT_TYPE["HT_SWORD_SLASH"],
		REACT_TYPE		= REACT_TYPE["RT_FLY"],
		
		DAMAGE = 
		{
			PHYSIC		= 0.4,
		},
		
		BACK_SPEED_X			= 1200,
		BACK_SPEED_Y			= 800,
		
		CAMERA_CRASH_GAP		= 5.0,	
		CAMERA_CRASH_TIME		= 0.2,		
	},
	
}


WALLY_9TH_EXPERT_JUMP_ATTACK =
{
	ANIM_NAME					= "JumpAttack",
	PLAY_TYPE					= XSKIN_ANIM_PLAYTYPE["XAP_ONE_WAIT"],
	TRANSITION					= TRUE,
	LAND_CONNECT				= FALSE,
	
	CAN_PUSH_UNIT				= TRUE,
	CAN_PASS_UNIT				= FALSE,

    SOUND_PLAY0			= { 0.200, "Wally9_JumpAttack.ogg" },

	IMMADIATE_PACKET_SEND		= TRUE,
	SUPER_ARMOR					= TRUE,
	
	PASSIVE_SPEED_X				= INIT_PHYSIC["WALK_SPEED"],
	SPEED_Y						= 500.0,
	
	
	EVENT_PROCESS = 
	{		
		{ STATE_CHANGE_TYPE["SCT_FOOT_ON_LINE_TRUE"],		"WALLY_9TH_EXPERT_JUMP_LANDING",				}, 
	},
	
	ATTACK_TIME0				= { 0.14, 0.3, },
	
	SLASH_TRACE					= { 0.1, 0.4 },
	SLASH_TRACE0				= { 0.1, 0.4, 1 }, 
	
		
	
	DAMAGE_DATA = 
	{
		DAMAGE_TYPE		= DAMAGE_TYPE["DT_PHYSIC"],
		HIT_TYPE		= HIT_TYPE["HT_SWORD_SLASH"],
		REACT_TYPE		= REACT_TYPE["RT_DOWN"],
		
		DAMAGE = 
		{
			PHYSIC		= 1.0,
		},
		
		BACK_SPEED_X			= INIT_PHYSIC["WALK_SPEED"],
		BACK_SPEED_Y			= 0.0,
		
		CAMERA_CRASH_GAP		= 5.0,	
		CAMERA_CRASH_TIME		= 0.2,		
	},
}


WALLY_9TH_EXPERT_SP_RAMPAGE = 
{
	ANIM_NAME					= "SP_Rampage",
	PLAY_TYPE					= XSKIN_ANIM_PLAYTYPE["XAP_ONE_WAIT"],
	TRANSITION					= FALSE,
	LAND_CONNECT				= FALSE,
	
	CAN_PUSH_UNIT				= TRUE,
	CAN_PASS_UNIT				= FALSE,

	    SOUND_PLAY0			= { 0.390, "Wally9_Rampage1.ogg" },
	    SOUND_PLAY1			= { 0.948, "Wally9_Rampage2.ogg" },
	    SOUND_PLAY2			= { 1.910, "Wally9_Rampage3.ogg" },
	    SOUND_PLAY3			= { 1.945, "Wally9_HitGround.ogg" },
	    SOUND_PLAY4			= { 1.950, "BreakGround.ogg" },
	    SOUND_PLAY5			= { 3.933, "Wally9_Rampage4.ogg" },

	
	VIEW_TARGET					= TRUE,
	IMMADIATE_PACKET_SEND		= TRUE,
	SUPER_ARMOR					= TRUE,
	
	EVENT_PROCESS = 
	{	
		{ STATE_CHANGE_TYPE["SCT_FOOT_ON_LINE_FALSE_DOWN"],	"WALLY_9TH_EXPERT_JUMP_DOWN",							},
		{ STATE_CHANGE_TYPE["SCT_MOTION_END"],				"WALLY_9TH_EXPERT_WAIT",								},	
	},
	
	ATTACK_TIME0				= { 0.333, 0.4, },
	ATTACK_TIME1				= { 0.9, 1.46, },
	ATTACK_TIME2				= { 1.86, 1.93, },
	ATTACK_TIME3				= { 2.26, 2.33, },
	
	SLASH_TRACE					= { 0.1, 4.0 },
	SLASH_TRACE0				= { 0.1, 4.0, 1 }, 
		
	
	
	DAMAGE_DATA = 
	{
		DAMAGE_TYPE		= DAMAGE_TYPE["DT_PHYSIC"],
		HIT_TYPE		= HIT_TYPE["HT_SWORD_SLASH"],
		REACT_TYPE		= REACT_TYPE["RT_BIG_DAMAGE"],
		
		DAMAGE = 
		{
			PHYSIC		= 0.3,
		},
		
		BACK_SPEED_X			= 300.0,
		BACK_SPEED_Y			= 0.0,
		
		CAMERA_CRASH_GAP		= 5.0,	
		CAMERA_CRASH_TIME		= 0.2,		
	
		RE_ATTACK				= TRUE,		
		HIT_GAP					= 0.05,
	},
	
	DAMAGE_DATA2 = 
	{
		DAMAGE_TYPE		= DAMAGE_TYPE["DT_PHYSIC"],
		HIT_TYPE		= HIT_TYPE["HT_SWORD_SLASH"],
		REACT_TYPE		= REACT_TYPE["RT_UP"],
		
		DAMAGE = 
		{
			PHYSIC		= 0.4,
		},
		
		BACK_SPEED_X			= 1000.0,
		BACK_SPEED_Y			= 1700.0,
		
		CAMERA_CRASH_GAP		= 5.0,	
		CAMERA_CRASH_TIME		= 0.2,		
	},
}








WALLY_9TH_EXPERT_BARRIER = 
{
	ANIM_NAME					= "Barrier",
	PLAY_TYPE					= XSKIN_ANIM_PLAYTYPE["XAP_ONE_WAIT"],
	TRANSITION					= FALSE,
	LAND_CONNECT				= TRUE,
	
	CAN_PUSH_UNIT				= TRUE,
	CAN_PASS_UNIT				= FALSE,

--    SOUND_PLAY0			= { 0.359, "Wally9_Barrier.ogg" },

	VIEW_TARGET					= TRUE,
	IMMADIATE_PACKET_SEND		= TRUE,
	SUPER_ARMOR					= TRUE,
	
	

	PARTICLE_SEQ = 
	{
		--Major, time, Name, weaponBonePos, Pos, StateEndDelete, bTrace, posx, posy, posz, bApplyUnitRotation, rotx, roty, rotz,
		{ TRUE, 0.4, "MonsterAngryWind", FALSE, "", TRUE, FALSE, 0, INIT_SYSTEM["UNIT_HEIGHT"] * 0.5, 0, },
		{ TRUE, 0.4, "Counter_Particle01", FALSE, "", TRUE, FALSE, 0, INIT_SYSTEM["UNIT_HEIGHT"] * 0.5, 0, },
	},

	
	EVENT_PROCESS = 
	{	
		{ STATE_CHANGE_TYPE["SCT_FOOT_ON_LINE_FALSE_DOWN"],	"WALLY_9TH_EXPERT_JUMP_DOWN",							},
		{ STATE_CHANGE_TYPE["SCT_MOTION_END"],				"WALLY_9TH_EXPERT_WAIT",								},	
	},
	
}



WALLY_9TH_EXPERT_LASER_ATTACK = 
{
	ANIM_NAME					= "LazerAttack",
	PLAY_TYPE					= XSKIN_ANIM_PLAYTYPE["XAP_ONE_WAIT"],
	TRANSITION					= FALSE,
	LAND_CONNECT				= FALSE,
	
	CAN_PUSH_UNIT				= TRUE,
	CAN_PASS_UNIT				= FALSE,

	    SOUND_PLAY0			= { 0.359, "Wally9_SwordIn.ogg" },
        SOUND_PLAY1			= { 1.338, "Wally9_SwordOut.ogg" },

	SPEED_X						= 0,
	SPEED_Y						= 0,	
	
	VIEW_TARGET					= TRUE,
	IMMADIATE_PACKET_SEND		= TRUE,
	SUPER_ARMOR					= TRUE,
	
	TALK_BOX = 
	{
		{ RATE = 10, MESSAGE = STR_ID_1547 },
		{ RATE = 10, MESSAGE = STR_ID_1445 },
	},
	
	EVENT_PROCESS = 
	{	
		{ STATE_CHANGE_TYPE["SCT_FOOT_ON_LINE_FALSE_DOWN"],	"WALLY_9TH_EXPERT_JUMP_DOWN",							},
		{ STATE_CHANGE_TYPE["SCT_MOTION_END"],				"WALLY_9TH_EXPERT_WAIT",								},	
	},

}


WALLY_9TH_EXPERT_DAMAGE_SMALL =
{
	ANIM_NAME					= "DamageSmall",
	PLAY_TYPE					= XSKIN_ANIM_PLAYTYPE["XAP_ONE_WAIT"],
	TRANSITION					= TRUE,
	LAND_CONNECT				= FALSE,
	
	CAN_PUSH_UNIT				= TRUE,
	CAN_PASS_UNIT				= FALSE,
	
	EVENT_INTERVAL_TIME0		= 1,
	
	EVENT_PROCESS = 
	{
		{ STATE_CHANGE_TYPE["SCT_FOOT_ON_LINE_FALSE_DOWN"],	"WALLY_9TH_EXPERT_JUMP_DOWN",					},
		{ STATE_CHANGE_TYPE["SCT_MOTION_END"],				"WALLY_9TH_EXPERT_WAIT",						},
	},

	TALK_BOX =
 	{
		{ RATE = 30, MESSAGE = STR_ID_2426 },
	},
}


WALLY_9TH_EXPERT_DAMAGE_BIG = 
{
	ANIM_NAME					= "DamageBig",
	PLAY_TYPE					= XSKIN_ANIM_PLAYTYPE["XAP_ONE_WAIT"],
	TRANSITION					= TRUE,
	LAND_CONNECT				= FALSE,
	
	CAN_PUSH_UNIT				= TRUE,
	CAN_PASS_UNIT				= FALSE,
	
	EVENT_PROCESS = 
	{
		{ STATE_CHANGE_TYPE["SCT_FOOT_ON_LINE_FALSE_DOWN"],		"WALLY_9TH_EXPERT_JUMP_DOWN",				},
		{ STATE_CHANGE_TYPE["SCT_MOTION_END"],					"WALLY_9TH_EXPERT_WAIT",					},
	},
		
	TALK_BOX =
 	{
		{ RATE = 10, MESSAGE = STR_ID_2427 },
	},
}

WALLY_9TH_EXPERT_DAMAGE_DOWN_FRONT = 
{
	ANIM_NAME					= "DamageDownFront",
	PLAY_TYPE					= XSKIN_ANIM_PLAYTYPE["XAP_ONE_WAIT"],
	TRANSITION					= TRUE,
	LAND_CONNECT				= TRUE,

	SUPER_ARMOR					= TRUE,
	DEFENCE						= { 0, 100, 70, },
	
	
	SWAP_UNIT_WIDTH_HEIGHT		= TRUE,
	
	
	CAN_PUSH_UNIT				= TRUE,
	CAN_PASS_UNIT				= FALSE,
	
	SWAP_UNIT_WIDTH_HEIGHT		= TRUE,
	
	EVENT_PROCESS = 
	{
		{ STATE_CHANGE_TYPE["SCT_FOOT_ON_LINE_FALSE_DOWN"],		"WALLY_9TH_EXPERT_DAMAGE_AIR_FALL",			},
		{ STATE_CHANGE_TYPE["SCT_CONDITION_TABLE"],				"WALLY_9TH_EXPERT_STAND_UP_ATTACK_FRONT",	"CT_WALLY_9TH_EXPERT_STAND_UP_ATTACK_FRONT", },
		{ STATE_CHANGE_TYPE["SCT_MOTION_END"],					"WALLY_9TH_EXPERT_STAND_UP_FRONT",			},
	},
	
	CT_WALLY_9TH_EXPERT_STAND_UP_ATTACK_FRONT = 
	{
		ANIM_PLAY_COUNT		= 1,
		RATE				= 20,
	},
	
	TALK_BOX =
 	{
		{ RATE = 30, MESSAGE = STR_ID_2428 },
	},
}

WALLY_9TH_EXPERT_DAMAGE_DOWN_BACK = 
{
	ANIM_NAME					= "DamageDownBack",
	PLAY_TYPE					= XSKIN_ANIM_PLAYTYPE["XAP_ONE_WAIT"],
	TRANSITION					= TRUE,
	LAND_CONNECT				= TRUE,
	
	SUPER_ARMOR					= TRUE,
	DEFENCE						= { 0, 100, 70, },
	
	SWAP_UNIT_WIDTH_HEIGHT		= TRUE,
	
	
	CAN_PUSH_UNIT				= TRUE,
	CAN_PASS_UNIT				= FALSE,
	
	EVENT_PROCESS = 
	{
		{ STATE_CHANGE_TYPE["SCT_FOOT_ON_LINE_FALSE_DOWN"],		"WALLY_9TH_EXPERT_DAMAGE_AIR_FALL",			},
		{ STATE_CHANGE_TYPE["SCT_CONDITION_TABLE"],				"WALLY_9TH_EXPERT_STAND_UP_ATTACK_BACK",	"CT_WALLY_9TH_EXPERT_STAND_UP_ATTACK_BACK", },
		{ STATE_CHANGE_TYPE["SCT_MOTION_END"],					"WALLY_9TH_EXPERT_STAND_UP_BACK",			},
	},
	
	CT_WALLY_9TH_EXPERT_STAND_UP_ATTACK_BACK = 
	{
		ANIM_PLAY_COUNT		= 1,
		RATE				= 20,
	},
	
	TALK_BOX =
 	{
		{ RATE = 30, MESSAGE = STR_ID_2429 },
	},
}




WALLY_9TH_EXPERT_DAMAGE_FLY_FRONT = 
{
	ANIM_NAME					= "DamageBig",
	PLAY_TYPE					= XSKIN_ANIM_PLAYTYPE["XAP_ONE_WAIT"],
	TRANSITION					= FALSE,
	LAND_CONNECT				= FALSE,	
	
	CAN_PUSH_UNIT				= TRUE,
	CAN_PASS_UNIT				= FALSE,
	
	EVENT_PROCESS = 
	{
		{ STATE_CHANGE_TYPE["SCT_FOOT_ON_LINE_TRUE"],			"WALLY_9TH_EXPERT_DAMAGE_DOWN_FRONT",		},
	},
}

WALLY_9TH_EXPERT_DAMAGE_FLY_BACK =
{
	ANIM_NAME					= "DamageBig",
	PLAY_TYPE					= XSKIN_ANIM_PLAYTYPE["XAP_ONE_WAIT"],
	TRANSITION					= FALSE,
	LAND_CONNECT				= FALSE,	
	
	CAN_PUSH_UNIT				= TRUE,
	CAN_PASS_UNIT				= FALSE,
	
	EVENT_PROCESS = 
	{
		{ STATE_CHANGE_TYPE["SCT_FOOT_ON_LINE_TRUE"],			"WALLY_9TH_EXPERT_DAMAGE_DOWN_BACK",		},
	},
}





WALLY_9TH_EXPERT_DAMAGE_AIR = 
{
	ANIM_NAME					= "DamageAirSmall",
	PLAY_TYPE					= XSKIN_ANIM_PLAYTYPE["XAP_ONE_WAIT"],
	TRANSITION					= FALSE,
	LAND_CONNECT				= FALSE,
	
	CAN_PUSH_UNIT				= TRUE,
	CAN_PASS_UNIT				= FALSE,
	
	EVENT_PROCESS = 
	{
		{ STATE_CHANGE_TYPE["SCT_FOOT_ON_LINE_TRUE"],			"WALLY_9TH_EXPERT_WAIT",					},
	},
}



WALLY_9TH_EXPERT_DAMAGE_AIR_UP = 
{
	ANIM_NAME					= "DamageAirUp",
	PLAY_TYPE					= XSKIN_ANIM_PLAYTYPE["XAP_ONE_WAIT"],
	TRANSITION					= FALSE,
	LAND_CONNECT				= FALSE,
	
	CAN_PUSH_UNIT				= TRUE,
	CAN_PASS_UNIT				= FALSE,	
	
	--PASSIVE_SPEED_Y				= -1,
	--SPEED_Y						= INIT_PHYSIC["JUMP_SPEED"] * 0.9,
	
	EVENT_PROCESS = 
	{
		{ STATE_CHANGE_TYPE["SCT_NEGATIVE_Y_SPEED"],		"WALLY_9TH_EXPERT_DAMAGE_AIR_FALL",			},
		{ STATE_CHANGE_TYPE["SCT_FOOT_ON_LINE_TRUE"],		"WALLY_9TH_EXPERT_DAMAGE_AIR_DOWN_LANDING",	},
	},
}


WALLY_9TH_EXPERT_DAMAGE_AIR_DOWN = 
{
	ANIM_NAME					= "DamageAirDown",
	PLAY_TYPE					= XSKIN_ANIM_PLAYTYPE["XAP_ONE_WAIT"],
	TRANSITION					= TRUE,
	LAND_CONNECT				= FALSE,
	
	CAN_PUSH_UNIT				= TRUE,
	CAN_PASS_UNIT				= FALSE,
	
	EVENT_PROCESS = 
	{
		{ STATE_CHANGE_TYPE["SCT_FOOT_ON_LINE_TRUE"],			"WALLY_9TH_EXPERT_DAMAGE_AIR_DOWN_LANDING",	},
	},
}



WALLY_9TH_EXPERT_DAMAGE_AIR_FALL = 
{
	ANIM_NAME					= "DamageAirFall",
	PLAY_TYPE					= XSKIN_ANIM_PLAYTYPE["XAP_ONE_WAIT"],
	TRANSITION					= TRUE,
	LAND_CONNECT				= FALSE,
	
	CAN_PUSH_UNIT				= TRUE,
	CAN_PASS_UNIT				= FALSE,
	
	EVENT_PROCESS = 
	{
		{ STATE_CHANGE_TYPE["SCT_POSITIVE_Y_SPEED"],		"WALLY_9TH_EXPERT_DAMAGE_AIR_UP",			},
		{ STATE_CHANGE_TYPE["SCT_FOOT_ON_LINE_TRUE"],		"WALLY_9TH_EXPERT_DAMAGE_AIR_DOWN_LANDING",	},
	},
}

WALLY_9TH_EXPERT_DAMAGE_AIR_DOWN_LANDING = 
{
	ANIM_NAME					= "DamageAirDownLanding",
	PLAY_TYPE					= XSKIN_ANIM_PLAYTYPE["XAP_ONE_WAIT"],
	TRANSITION					= TRUE,
	LAND_CONNECT				= TRUE,
	
	SUPER_ARMOR					= TRUE,
	DEFENCE						= { 0, 100, 70, },

	
	SWAP_UNIT_WIDTH_HEIGHT		= TRUE,
	
	CAN_PUSH_UNIT				= TRUE,
	CAN_PASS_UNIT				= FALSE,
	
	EVENT_PROCESS = 
	{
		{ STATE_CHANGE_TYPE["SCT_FOOT_ON_LINE_FALSE_DOWN"],	"WALLY_9TH_EXPERT_DAMAGE_AIR_FALL",			},
		{ STATE_CHANGE_TYPE["SCT_CONDITION_TABLE"],			"WALLY_9TH_EXPERT_STAND_UP_ATTACK_FRONT",	"CT_WALLY_9TH_EXPERT_STAND_UP_ATTACK_FRONT", },
		{ STATE_CHANGE_TYPE["SCT_MOTION_END"],				"WALLY_9TH_EXPERT_STAND_UP_FRONT",			},
	},
	
	CT_WALLY_9TH_EXPERT_STAND_UP_ATTACK_FRONT = 
	{
		ANIM_PLAY_COUNT		= 1,
		RATE				= 20,
	},
}

WALLY_9TH_EXPERT_STAND_UP_FRONT = 
{
	ANIM_NAME					= "DamageStandUpFront",
	PLAY_TYPE					= XSKIN_ANIM_PLAYTYPE["XAP_ONE_WAIT"],
	TRANSITION					= FALSE,
	LAND_CONNECT				= FALSE,	
	
	SUPER_ARMOR					= TRUE,
	DEFENCE						= { 0, 100, 70, },
	SWAP_UNIT_WIDTH_HEIGHT		= TRUE,

    SOUND_PLAY0			= { 0.867, "Wally9_StepLanding.ogg" },
    SOUND_PLAY1			= { 1.320, "Wally9_SwordOut.ogg" },
	
	CAN_PUSH_UNIT				= TRUE,
	CAN_PASS_UNIT				= FALSE,


	EVENT_PROCESS = 
	{
		{ STATE_CHANGE_TYPE["SCT_FOOT_ON_LINE_FALSE_DOWN"],	"WALLY_9TH_EXPERT_JUMP_DOWN",			},
		{ STATE_CHANGE_TYPE["SCT_MOTION_END"],				"WALLY_9TH_EXPERT_WAIT",				},
	},
}

----------------------------------------------------------
function WALLY_9TH_EXPERT_STAND_UP_FRONT_FRAME_MOVE( pKTDXApp, pX2Game, pNPCUnit )
	
	if pNPCUnit:GetNowAnimationTime() > 1.5 then
		pNPCUnit:SetSuperArmor(true)
	end	
		
end



WALLY_9TH_EXPERT_STAND_UP_BACK = 
{
	ANIM_NAME					= "DamageStandUpBack",
	PLAY_TYPE					= XSKIN_ANIM_PLAYTYPE["XAP_ONE_WAIT"],
	TRANSITION					= FALSE,
	LAND_CONNECT				= FALSE,
	
	SUPER_ARMOR					= TRUE,
	DEFENCE						= { 0, 100, 70, },
	SWAP_UNIT_WIDTH_HEIGHT		= TRUE,

    SOUND_PLAY0			= { 0.950, "Wally9_StepLanding.ogg" },
    SOUND_PLAY1			= { 1.410, "Wally9_SwordOut.ogg" },

		
	CAN_PUSH_UNIT				= TRUE,
	CAN_PASS_UNIT				= FALSE,
		
	EVENT_PROCESS = 
	{
		{ STATE_CHANGE_TYPE["SCT_FOOT_ON_LINE_FALSE_DOWN"],	"WALLY_9TH_EXPERT_JUMP_DOWN", },
		{ STATE_CHANGE_TYPE["SCT_MOTION_END"],				"WALLY_9TH_EXPERT_WAIT", },
	},		
}

----------------------------------------------------------
function WALLY_9TH_EXPERT_STAND_UP_BACK_FRAME_MOVE( pKTDXApp, pX2Game, pNPCUnit )
	
	if pNPCUnit:GetNowAnimationTime() > 1.5 then
		pNPCUnit:SetSuperArmor(true)
	end	
		
end



WALLY_9TH_EXPERT_STAND_UP_ATTACK_FRONT = 
{
	ANIM_NAME					= "StandUpAttackFront",
	PLAY_TYPE					= XSKIN_ANIM_PLAYTYPE["XAP_ONE_WAIT"],
	TRANSITION					= FALSE,
	LAND_CONNECT				= FALSE,	
	ANIM_WAIT_TIME				= 1,
	MIND_FLAG					= MIND_FLAG["MF_STAND_UP_ATTACK"],
	
	SUPER_ARMOR					= TRUE,
	DEFENCE						= { 0, 100, 70, },
	--SWAP_UNIT_WIDTH_HEIGHT		= TRUE,

    SOUND_PLAY0			= { 0.471, "Wally9_StandUpAttack.ogg" },
    SOUND_PLAY1			= { 1.070 , "Wally9_StepLanding.ogg" },
	
	CAN_PUSH_UNIT				= TRUE,
	CAN_PASS_UNIT				= FALSE,


	EVENT_PROCESS = 
	{
		{ STATE_CHANGE_TYPE["SCT_FOOT_ON_LINE_FALSE_DOWN"],	"WALLY_9TH_EXPERT_JUMP_DOWN",			},
		{ STATE_CHANGE_TYPE["SCT_MOTION_END"],				"WALLY_9TH_EXPERT_WAIT",				},
	},
	
	ATTACK_TIME0				= { 0.4, 0.76 },	
	SLASH_TRACE					= { 0.3, 0.9 },
	SLASH_TRACE0				= { 0.3, 0.9, 1 }, 

	
	
	DAMAGE_DATA = 
	{
		DAMAGE_TYPE		= DAMAGE_TYPE["DT_PHYSIC"],
		HIT_TYPE		= HIT_TYPE["HT_SWORD_SLASH"],
		REACT_TYPE		= REACT_TYPE["RT_FLY"],
		
		DAMAGE = 
		{
			PHYSIC		= 1.0,
			FIRE		= 0.0,
			ICE			= 0.0,
			EARTH		= 0.0,
			LIGHTNING	= 0.0,
			DARK		= 0.0,
			LIGHT		= 0.0,
			UNIVERSAL	= 0.0,
		},
		
		BACK_SPEED_X			= INIT_PHYSIC["RUN_SPEED"],
		BACK_SPEED_Y			= 0.0,
		
		STOP_TIME_ATT			= 0.0,		
		STOP_TIME_DEF			= 0.0,	
		CAMERA_CRASH_GAP		= 5.0,	
		CAMERA_CRASH_TIME		= 0.2,
		CLEAR_SCREEN			= 0.0,	
		CLEAR_SCREEN_COLOR_A	= 0.0,
		CLEAR_SCREEN_COLOR_R	= 1.0,
		CLEAR_SCREEN_COLOR_G	= 1.0,
		CLEAR_SCREEN_COLOR_B	= 1.0,

		RE_ATTACK				= FALSE,		
		HIT_GAP					= 0.0,				
	},	
}

----------------------------------------------------------
function WALLY_9TH_EXPERT_STAND_UP_ATTACK_FRONT_FRAME_MOVE( pKTDXApp, pX2Game, pNPCUnit )
	
	if pNPCUnit:AnimEventTimer_LUA( 0.80 ) then
		pMinorParticle = pX2Game:GetMinorParticle()
		pMinorParticle:GameUnitCreateSequence_LUA( pNPCUnit, "StepSmoke", pNPCUnit:GetLandPosition_LUA(), D3DXVECTOR2(100,100), D3DXVECTOR2(5,-1) )
	end
	
	if pNPCUnit:GetNowAnimationTime() > 1.5 then
		pNPCUnit:SetSuperArmor(true)
	end	
		
end



WALLY_9TH_EXPERT_STAND_UP_ATTACK_BACK = 
{
	ANIM_NAME					= "StandUpAttackBack",
	PLAY_TYPE					= XSKIN_ANIM_PLAYTYPE["XAP_ONE_WAIT"],
	TRANSITION					= FALSE,
	LAND_CONNECT				= FALSE,
	ANIM_WAIT_TIME				= 1,
	MIND_FLAG					= MIND_FLAG["MF_STAND_UP_ATTACK"],
	
	SUPER_ARMOR					= TRUE,
	DEFENCE						= { 0, 100, 70, },
	SWAP_UNIT_WIDTH_HEIGHT		= TRUE,

	
    SOUND_PLAY0			= { 0.589, "Wally9_StandUpAttack.ogg" },
    SOUND_PLAY1			= { 1.134, "Wally9_StepLanding.ogg" },


	CAN_PUSH_UNIT				= TRUE,
	CAN_PASS_UNIT				= FALSE,

	
	FLIP_DIR_END				= TRUE,
	
	EVENT_PROCESS = 
	{
		{ STATE_CHANGE_TYPE["SCT_FOOT_ON_LINE_FALSE_DOWN"],	"WALLY_9TH_EXPERT_JUMP_DOWN", },
		{ STATE_CHANGE_TYPE["SCT_MOTION_END"],				"WALLY_9TH_EXPERT_WAIT", },
	},	
	
		
	ATTACK_TIME0				= { 0.46, 0.76 },
	SLASH_TRACE					= { 0.4, 0.9 },
	SLASH_TRACE0				= { 0.4, 0.9, 1 }, 

	
	DAMAGE_DATA = 
	{
		DAMAGE_TYPE		= DAMAGE_TYPE["DT_PHYSIC"],
		HIT_TYPE		= HIT_TYPE["HT_SWORD_SLASH"],
		REACT_TYPE		= REACT_TYPE["RT_DOWN"],
		
		DAMAGE = 
		{
			PHYSIC		= 1.0,
			FIRE		= 0.0,
			ICE			= 0.0,
			EARTH		= 0.0,
			LIGHTNING	= 0.0,
			DARK		= 0.0,
			LIGHT		= 0.0,
			UNIVERSAL	= 0.0,
		},
		
		BACK_SPEED_X			= INIT_PHYSIC["RUN_SPEED"],
		BACK_SPEED_Y			= 0.0,
		
		STOP_TIME_ATT			= 0.0,		
		STOP_TIME_DEF			= 0.0,	
		CAMERA_CRASH_GAP		= 5.0,	
		CAMERA_CRASH_TIME		= 0.2,
		CLEAR_SCREEN			= 0.0,	
		CLEAR_SCREEN_COLOR_A	= 0.0,
		CLEAR_SCREEN_COLOR_R	= 1.0,
		CLEAR_SCREEN_COLOR_G	= 1.0,
		CLEAR_SCREEN_COLOR_B	= 1.0,

		RE_ATTACK				= FALSE,		
		HIT_GAP					= 0.0,				
	},
}

----------------------------------------------------------
function WALLY_9TH_EXPERT_STAND_UP_ATTACK_BACK_FRAME_MOVE( pKTDXApp, pX2Game, pNPCUnit )
	
	if pNPCUnit:AnimEventTimer_LUA( 0.72 ) then
		pMinorParticle = pX2Game:GetMinorParticle()
		pMinorParticle:GameUnitCreateSequence_LUA( pNPCUnit, "StepSmoke", pNPCUnit:GetLandPosition_LUA(), D3DXVECTOR2(100,100), D3DXVECTOR2(5,-1) )
	end
	
	if pNPCUnit:GetNowAnimationTime() > 1.5 then
		pNPCUnit:SetSuperArmor(true)
	end	
		
end





WALLY_9TH_EXPERT_DAMAGE_REVENGE = 
{
	ANIM_NAME					= "DamageBig",
	PLAY_TYPE					= XSKIN_ANIM_PLAYTYPE["XAP_ONE_WAIT"],
	TRANSITION					= FALSE,
	LAND_CONNECT				= FALSE,
	
	STOP_MY_UNIT0				= { 0.2, 0.2, },
	
	CAN_PUSH_UNIT				= TRUE,
	CAN_PASS_UNIT				= FALSE,
	
	EVENT_PROCESS = 
	{
		{ STATE_CHANGE_TYPE["SCT_MOTION_END"],				"WALLY_9TH_EXPERT_WAIT",					},
	},
}



WALLY_9TH_EXPERT_DYING_LAND_FRONT = 
{
	ANIM_NAME					= "DamageDownFront",
	PLAY_TYPE					= XSKIN_ANIM_PLAYTYPE["XAP_ONE_WAIT"],
	TRANSITION					= FALSE,
	LAND_CONNECT				= FALSE,

	INVINCIBLE					= { 0, 100, }, 		

	
	CAN_PUSH_UNIT				= FALSE,
	CAN_PASS_UNIT				= TRUE,
	
	DYING_END					= TRUE,
	IMMADIATE_PACKET_SEND		= TRUE,
}
	
WALLY_9TH_EXPERT_DYING_LAND_BACK = 
{
	ANIM_NAME					= "DamageDownBack",
	PLAY_TYPE					= XSKIN_ANIM_PLAYTYPE["XAP_ONE_WAIT"],
	TRANSITION					= FALSE,
	LAND_CONNECT				= FALSE,
	
	INVINCIBLE					= { 0, 100, }, 		

	
	CAN_PUSH_UNIT				= FALSE,
	CAN_PASS_UNIT				= TRUE,
	
	DYING_END					= TRUE,	
	IMMADIATE_PACKET_SEND		= TRUE,
}

WALLY_9TH_EXPERT_DYING_SKY = 
{
	ANIM_NAME					= "DamageAirDownLanding",
	PLAY_TYPE					= XSKIN_ANIM_PLAYTYPE["XAP_ONE_WAIT"],
	TRANSITION					= FALSE,
	LAND_CONNECT				= FALSE,
	
	INVINCIBLE					= { 0, 100, }, 		
	
	CAN_PUSH_UNIT				= FALSE,
	CAN_PASS_UNIT				= TRUE,
	
	DYING_END					= TRUE,
	IMMADIATE_PACKET_SEND		= TRUE,
}






----------------------------------------------------------
function WALLY_9TH_EXPERT_START_CAMERA_MOVE( pKTDXApp, pX2Game, pNPCUnit )

	pos = pNPCUnit:GetBonePos_LUA("Bip01_Head")	
	camera = pX2Game:GetX2Camera()
	camera:PartsLookDirectCamera_LUA( pNPCUnit, pos, D3DXVECTOR3( 500, -50, -20 ), D3DXVECTOR2( 0,0 ) )

end

----------------------------------------------------------
function CF_WALLY_9TH_EXPERT_WIN( pKTDXApp, pX2Game, pNPCUnit )

	if pX2Game:LiveUserUnitNum() == 0 then
		return true
	else
		return false
	end

end







----------------------------------------------------------
function WALLY_9TH_EXPERT_WALK_STATE_END( pKTDXApp, pX2Game, pNPCUnit )

	pMinorParticle = pX2Game:GetMinorParticle()
	pMinorParticle:GameUnitCreateSequence_LUA( pNPCUnit, "StepSmoke", pNPCUnit:GetLandPosition_LUA(), D3DXVECTOR2(100,100), D3DXVECTOR2(5,-1) )

end





----------------------------------------------------------
function WALLY_9TH_EXPERT_JUMP_DOWN_STATE_END( pKTDXApp, pX2Game, pNPCUnit )

	pMinorParticle = pX2Game:GetMinorParticle()
	pMinorParticle:GameUnitCreateSequence_LUA( pNPCUnit, "StepSmoke", pNPCUnit:GetLandPosition_LUA(), D3DXVECTOR2(100,100), D3DXVECTOR2(5,-1) )

end


----------------------------------------------------------
function WALLY_9TH_EXPERT_JUMP_DOWN_DIR_STATE_END( pKTDXApp, pX2Game, pNPCUnit )

	pMinorParticle = pX2Game:GetMinorParticle()
	pMinorParticle:GameUnitCreateSequence_LUA( pNPCUnit, "StepSmoke", pNPCUnit:GetLandPosition_LUA(), D3DXVECTOR2(100,100), D3DXVECTOR2(5,-1) )

end

----------------------------------------------------------
function WALLY_9TH_EXPERT_JUMP_LANDING_STATE_START( pKTDXApp, pX2Game, pNPCUnit )

	
	
	pX2Game:GetX2Camera():GetCamera():UpDownCrashCameraNoReset( 10.0, 0.3 )
	pMinorParticle = pX2Game:GetMinorParticle()
	pos = pNPCUnit:GetBonePos_LUA( "Bip01_L_Foot" )
	pMinorParticle:GameUnitCreateSequence_LUA( pNPCUnit, "AirDownTick", pos, D3DXVECTOR2(200,200), D3DXVECTOR2(10,-1) )
	
end




----------------------------------------------------------
function WALLY_9TH_EXPERT_DASH_STATE_START( pKTDXApp, pX2Game, pNPCUnit )

	WALLY_9TH_EXPERT_STEP_SMOKE( pX2Game, pNPCUnit, 0.0 )
	
end


----------------------------------------------------------
function WALLY_9TH_EXPERT_DASH_FRAME_MOVE( pKTDXApp, pX2Game, pNPCUnit )

	WALLY_9TH_EXPERT_STEP_SMOKE( pX2Game, pNPCUnit, 0.0 )
	WALLY_9TH_EXPERT_STEP_SMOKE( pX2Game, pNPCUnit, 0.2 )
	WALLY_9TH_EXPERT_STEP_SMOKE( pX2Game, pNPCUnit, 0.4 )
	WALLY_9TH_EXPERT_STEP_SMOKE( pX2Game, pNPCUnit, 0.6 )
	WALLY_9TH_EXPERT_STEP_SMOKE( pX2Game, pNPCUnit, 0.8 )

end

----------------------------------------------------------
function WALLY_9TH_EXPERT_DASH_STATE_END( pKTDXApp, pX2Game, pNPCUnit )

	WALLY_9TH_EXPERT_STEP_SMOKE( pX2Game, pNPCUnit, 0.0 )
	
end



----------------------------------------------------------
function WALLY_9TH_EXPERT_DASH_END_STATE_START( pKTDXApp, pX2Game, pNPCUnit )
	
	WALLY_9TH_EXPERT_STEP_SMOKE( pX2Game, pNPCUnit, 0.0 )
	
end





----------------------------------------------------------
function WALLY_9TH_EXPERT_DAMAGE_SMALL_FRAME_MOVE( pKTDXApp, pX2Game, pNPCUnit )

	if pNPCUnit:AnimEventTimer_LUA( 0.15 ) then
	
		pMinorParticle = pX2Game:GetMinorParticle()
		pMinorParticle:GameUnitCreateSequence_LUA( pNPCUnit, "StepSmoke", pNPCUnit:GetLandPosition_LUA(), D3DXVECTOR2(100,100), D3DXVECTOR2(5,-1) )
	end
	
end


----------------------------------------------------------
function WALLY_9TH_EXPERT_DAMAGE_BIG_FRAME_MOVE( pKTDXApp, pX2Game, pNPCUnit )


	if pNPCUnit:AnimEventTimer_LUA( 0.1 ) then
	
		pMinorParticle = pX2Game:GetMinorParticle()
		pMinorParticle:GameUnitCreateSequence_LUA( pNPCUnit, "StepSmoke", pNPCUnit:GetLandPosition_LUA(), D3DXVECTOR2(100,100), D3DXVECTOR2(5,-1) )
	end

end




----------------------------------------------------------
function WALLY_9TH_EXPERT_DAMAGE_DOWN_FRONT_FRAME_MOVE( pKTDXApp, pX2Game, pNPCUnit )

	if pNPCUnit:AnimEventTimer_LUA( 0.34 ) then
	
		pNPCUnit:PlaySound_LUA( "Down.ogg" )
		pMinorParticle = pX2Game:GetMinorParticle()
		pMinorParticle:GameUnitCreateSequence_LUA( pNPCUnit, "DownSmoke", pNPCUnit:GetLandPosition_LUA(), D3DXVECTOR2(100,100), D3DXVECTOR2(7,-1) )
		pX2Game:GetX2Camera():GetCamera():UpDownCrashCameraNoReset( 10.0, 0.2 )
	
	end
	
	if pNPCUnit:AnimEventTimer_LUA( 0.56 ) then
	
		pMinorParticle = pX2Game:GetMinorParticle()
		pos = pNPCUnit:GetBonePos_LUA( "Bip01_L_Calf" )		
		pMinorParticle:GameUnitCreateSequence_LUA( pNPCUnit, "WALLY_9TH_Spark", pos, D3DXVECTOR2(-1,-1), D3DXVECTOR2(-1,-1) )
		pos = pNPCUnit:GetBonePos_LUA( "Bip01_Neck" )		
		pMinorParticle:GameUnitCreateSequence_LUA( pNPCUnit, "WALLY_9TH_Spark", pos, D3DXVECTOR2(-1,-1), D3DXVECTOR2(-1,-1) )
		pos = pNPCUnit:GetBonePos_LUA( "Bip01_R_UpperArm" )		
		pMinorParticle:GameUnitCreateSequence_LUA( pNPCUnit, "WALLY_9TH_Spark", pos, D3DXVECTOR2(-1,-1), D3DXVECTOR2(-1,-1) )
	
	end

end



----------------------------------------------------------
function WALLY_9TH_EXPERT_DAMAGE_DOWN_BACK_FRAME_MOVE( pKTDXApp, pX2Game, pNPCUnit )

	if pNPCUnit:AnimEventTimer_LUA( 0.24 ) then
	
		pNPCUnit:PlaySound_LUA( "Down.ogg" )
		pMinorParticle = pX2Game:GetMinorParticle()
		pMinorParticle:GameUnitCreateSequence_LUA( pNPCUnit, "DownSmoke", pNPCUnit:GetLandPosition_LUA(), D3DXVECTOR2(100,100), D3DXVECTOR2(7,-1) )
		pX2Game:GetX2Camera():GetCamera():UpDownCrashCameraNoReset( 10.0, 0.2 )
		
	end
	
	if pNPCUnit:AnimEventTimer_LUA( 0.85 ) then
	
		pMinorParticle = pX2Game:GetMinorParticle()
		pos = pNPCUnit:GetBonePos_LUA( "Bip01_L_Calf" )		
		pMinorParticle:GameUnitCreateSequence_LUA( pNPCUnit, "WALLY_9TH_Spark", pos, D3DXVECTOR2(-1,-1), D3DXVECTOR2(-1,-1) )
		pos = pNPCUnit:GetBonePos_LUA( "Bip01_Neck" )		
		pMinorParticle:GameUnitCreateSequence_LUA( pNPCUnit, "WALLY_9TH_Spark", pos, D3DXVECTOR2(-1,-1), D3DXVECTOR2(-1,-1) )
		pos = pNPCUnit:GetBonePos_LUA( "Bip01_R_UpperArm" )		
		pMinorParticle:GameUnitCreateSequence_LUA( pNPCUnit, "WALLY_9TH_Spark", pos, D3DXVECTOR2(-1,-1), D3DXVECTOR2(-1,-1) )
	
	end

end





----------------------------------------------------------
function WALLY_9TH_EXPERT_DAMAGE_AIR_DOWN_LANDING_FRAME_MOVE( pKTDXApp, pX2Game, pNPCUnit )

	if pNPCUnit:AnimEventTimer_LUA( 0.01 ) then
		pNPCUnit:PlaySound_LUA( "Down.ogg" )
		pMinorParticle = pX2Game:GetMinorParticle()
		pos = pNPCUnit:GetLandPosition_LUA()
		pMinorParticle:GameUnitCreateSequence_LUA( pNPCUnit, "DownSmoke", pos, D3DXVECTOR2(100,100), D3DXVECTOR2(7,-1) )
		pos.y = pos.y + 5
		pMinorParticle:GameUnitCreateSequence_LUA( pNPCUnit, "GroundShockWave", pos, D3DXVECTOR2(100,100), D3DXVECTOR2(1,-1) )
		pParticle = pMinorParticle:GameUnitCreateSequence_LUA( pNPCUnit, "AirDownTick", pNPCUnit:GetPos(), D3DXVECTOR2(200,200), D3DXVECTOR2(10,-1) )
		if pParticle ~= nil then 
			pParticle:SetLandPosition( pos.y - 5 )
		end
		
		if GetDistance_LUA( pNPCUnit:GetPos(), pX2Game:GetFocusUnitPos_LUA() ) < 500 then
			pX2Game:GetX2Camera():GetCamera():UpDownCrashCameraNoReset( 10.0, 0.1 )
		end		
			
		pMinorParticle = pX2Game:GetMinorParticle()
		pos = pNPCUnit:GetBonePos_LUA( "Bip01_L_Calf" )		
		pMinorParticle:GameUnitCreateSequence_LUA( pNPCUnit, "WALLY_9TH_Spark", pos, D3DXVECTOR2(-1,-1), D3DXVECTOR2(-1,-1) )
		pos = pNPCUnit:GetBonePos_LUA( "Bip01_Neck" )		
		pMinorParticle:GameUnitCreateSequence_LUA( pNPCUnit, "WALLY_9TH_Spark", pos, D3DXVECTOR2(-1,-1), D3DXVECTOR2(-1,-1) )
		pos = pNPCUnit:GetBonePos_LUA( "Bip01_R_UpperArm" )		
		pMinorParticle:GameUnitCreateSequence_LUA( pNPCUnit, "WALLY_9TH_Spark", pos, D3DXVECTOR2(-1,-1), D3DXVECTOR2(-1,-1) )
				
	elseif pNPCUnit:AnimEventTimer_LUA( 0.44 ) then
		pNPCUnit:PlaySound_LUA( "Down.ogg" )
		pMinorParticle = pX2Game:GetMinorParticle()
		pMinorParticle:GameUnitCreateSequence_LUA( pNPCUnit, "DownSmoke", pNPCUnit:GetLandPosition_LUA(), D3DXVECTOR2(100,100), D3DXVECTOR2(7,-1) )
	end
	
end





----------------------------------------------------------
function WALLY_9TH_EXPERT_COMBO_FRAME_MOVE( pKTDXApp, pX2Game, pNPCUnit )
			
	if pNPCUnit:AnimEventTimer_LUA( 1.5 ) then
		pNPCUnit:ClearHitUnitList_LUA()
		pNPCUnit:SetDamageData_LUA( "DAMAGE_DATA2" )
	end
	

	if pNPCUnit:AnimEventTimer_LUA( 1.8 ) then
		pNPCUnit:ClearHitUnitList_LUA()
		pNPCUnit:SetDamageData_LUA( "DAMAGE_DATA3" )
	end
		
	if pNPCUnit:AnimEventTimer_LUA( 2.5 ) then
		pNPCUnit:ClearHitUnitList_LUA()
		pNPCUnit:SetDamageData_LUA( "DAMAGE_DATA4" )
	end
	
end




----------------------------------------------------------
function WALLY_9TH_EXPERT_SP_RAMPAGE_FRAME_MOVE( pKTDXApp, pX2Game, pNPCUnit )

	
	if pNPCUnit:AnimEventTimer_LUA( 2.0 ) then
		pNPCUnit:ClearHitUnitList_LUA()
		pNPCUnit:SetDamageData_LUA( "DAMAGE_DATA2" )
	end
	
		
	if pNPCUnit:AnimEventTimer_LUA( 2.66 ) then
		pNPCUnit:PlaySound_LUA( "Wally9_LaserAttack.ogg" )
		pDamageEffect = pX2Game:GetDamageEffect()
		pos = pNPCUnit:GetLandPosition_LUA()		
		pEffect = pDamageEffect:CreateInstance_LUA( pNPCUnit, "WALLY_9TH_RAMPAGE_LAZER_ATTACK", pNPCUnit:GetBonePos_LUA( "Dummy3_Eye" ), pos.y )	
		
		pNPCUnit:SetNowMP( 0 )
		
	end
	
	
		
	if pNPCUnit:AnimEventTimer_LUA( 1.85 ) then
	
		pMinorParticle = pX2Game:GetMinorParticle()
		vPos = pNPCUnit:GetPos()
		
		bIsRight = pNPCUnit:GetIsRight()
		vDirVector = pNPCUnit:GetDirVector()
		
		if bIsRight == false then
			vPos = MovePos( vPos, vDirVector, -250 )
		else
			vPos = MovePos( vPos, vDirVector, 250 )
		end

		pMinorParticle:GameUnitCreateSequence_LUA( pNPCUnit, "Stone_Nasod_MinerFat_Attack",	vPos, D3DXVECTOR2(-1,-1), D3DXVECTOR2(-1,-1) )
		
	end


		
	if pNPCUnit:AnimEventTimer_LUA( 1.93 ) then
	
		pMajorParticle = pX2Game:GetMajorParticle()
		vPos = pNPCUnit:GetPos()
		
		bIsRight = pNPCUnit:GetIsRight()
		vDirVector = pNPCUnit:GetDirVector()
		
		if bIsRight == false then
			vPos = MovePos( vPos, vDirVector, -250 )
		else
			vPos = MovePos( vPos, vDirVector, 250 )
		end

		pMajorParticle:GameUnitCreateSequence_LUA( pNPCUnit, "Wally9th_Rampage_Stone01",	vPos, D3DXVECTOR2(-1,-1), D3DXVECTOR2(-1,-1) )
		pMajorParticle:GameUnitCreateSequence_LUA( pNPCUnit, "Wally9th_Rampage_Stone02",	vPos, D3DXVECTOR2(-1,-1), D3DXVECTOR2(-1,-1) )
		
	end

end




----------------------------------------------------------
function WALLY_9TH_EXPERT_BARRIER_FRAME_MOVE( pKTDXApp, pX2Game, pNPCUnit )
	
	if pNPCUnit:AnimEventTimer_LUA( 0.5 ) then
     	pNPCUnit:PlaySound_LUA( "Wally9_Barrier.ogg" )
		pNPCUnit:SetRageForce( 5.0 )
		
	end

end




----------------------------------------------------------
function WALLY_9TH_EXPERT_LASER_ATTACK_FRAME_MOVE( pKTDXApp, pX2Game, pNPCUnit )

	--pX2Game:SetWorldColor_LUA( D3DXCOLOR( 1.0, 0.1, 0.1, 1 ) )

	
	if pNPCUnit:AnimEventTimer_LUA( 1.258 ) then
		pNPCUnit:PlaySound_LUA( "Wally9_LaserAttack.ogg" )
		pDamageEffect = pX2Game:GetDamageEffect()
		pos = pNPCUnit:GetLandPosition_LUA()		
		pEffect = pDamageEffect:CreateInstance_LUA( pNPCUnit, "WALLY_9TH_LAZER_ATTACK", pNPCUnit:GetBonePos_LUA( "Dummy3_Eye" ), pos.y )	
		                                          
		pNPCUnit:SetDamageEffect_LUA( 0, pEffect )
		
		pNPCUnit:SetNowMP( 0 )
		
	end
	
	
	
	if pNPCUnit:GetNowAnimationTime() > 0.3 and pNPCUnit:GetNowAnimationTime() < 1.0 then
	
		pEffect = pNPCUnit:GetDamageEffect_LUA( 0 )
		if pEffect ~= nil then
		
			pDamageEffect = pX2Game:GetDamageEffect()
			if pDamageEffect:IsLiveInstance( pEffect ) == true then 
			
				pMainMeshPlayer = pEffect:GetMainEffect()
				if pMainMeshPlayer ~= nil then 
				
					vBonePos = pNPCUnit:GetBonePos_LUA( "Dummy3_Eye" )
					vRot = pNPCUnit:GetRotateDegree()
					pMainMeshPlayer:SetPos( vBonePos )
					pMainMeshPlayer:SetRotateDegree( vRot )
				
				end
				
			else
			
				pNPCUnit:ClearDamageEffect_LUA( 0 )
				
			end
		end
		
	end
		
	
end





-----------------------------------------------------------------------
function WALLY_9TH_EXPERT_LASER_ATTACK_STATE_END( pKTDXApp, pX2Game, pNPCUnit )

	pEffect = pNPCUnit:GetDamageEffect_LUA( 0 )
	if pEffect ~= nil then
	
		pDamageEffect = pX2Game:GetDamageEffect()
		pDamageEffect:DestroyInstance( pEffect )
		
	end
	
	pNPCUnit:ClearDamageEffect_LUA( 0 )

end



----------------------------------------------------------
function WALLY_9TH_EXPERT_DASH_ATTACK_FRAME_MOVE( pKTDXApp, pX2Game, pNPCUnit )

	if pNPCUnit:AnimEventTimer_LUA( 0.52 ) then
		pNPCUnit:ClearHitUnitList_LUA()
	end

	if pNPCUnit:AnimEventTimer_LUA( 0.6 ) then
		pNPCUnit:ClearHitUnitList_LUA()
		pNPCUnit:SetDamageData_LUA( "DAMAGE_DATA2" )
	end

end






----------------------------------------------------------
function WALLY_9TH_EXPERT_DYING_LAND_STATE_START( pKTDXApp, pX2Game, pNPCUnit )
	
	pos = pNPCUnit:GetPos()
	pos.y = pos.y + 100.0
	GetMinorParticle = pX2Game:GetMinorParticle()
	
	pSeq = GetMinorParticle:GameUnitCreateSequence_LUA( pNPCUnit, "DieLight",		pos, D3DXVECTOR2(-1,-1), D3DXVECTOR2(3,-1) )
	if pSeq ~= nil then
	
		pSeq:SetLandPosition( pNPCUnit:GetLandPosition_LUA().y )
		pNPCUnit:SetDieSeq( pSeq:GetHandle() )
	
	end
	pNPCUnit:PlaySound_LUA( "DieLight.ogg" )
	
end

















-- UTILITY FUNCTIONS ---------------------------------------

----------------------------------------------------------
function WALLY_9TH_EXPERT_DOWN_SMOKE( pX2Game, pNPCUnit, fAnimEventTime )

	if 0.0 == fAnimEventTime then 
		
		pNPCUnit:PlaySound_LUA( "Down.ogg" )
		pMinorParticle = pX2Game:GetMinorParticle()
		pMinorParticle:GameUnitCreateSequence_LUA( pNPCUnit, "Wally8thBoostSmoke", pNPCUnit:GetLandPosition_LUA(), D3DXVECTOR2(100,100), D3DXVECTOR2(5,-1) )
	
	elseif pNPCUnit:AnimEventTimer_LUA( fAnimEventTime ) then
	
		pNPCUnit:PlaySound_LUA( "Down.ogg" )
		pMinorParticle = pX2Game:GetMinorParticle()
		pMinorParticle:GameUnitCreateSequence_LUA( pNPCUnit, "Wally8thBoostSmoke", pNPCUnit:GetLandPosition_LUA(), D3DXVECTOR2(100,100), D3DXVECTOR2(5,-1) )
		
	end
	
end




----------------------------------------------------------
function WALLY_9TH_EXPERT_STEP_SMOKE( pX2Game, pNPCUnit, fAnimEventTime )

	if pNPCUnit:AnimEventTimer_LUA( fAnimEventTime ) then
	
		pMinorParticle = pX2Game:GetMinorParticle()
		pMinorParticle:GameUnitCreateSequence_LUA( pNPCUnit, "StepSmoke", pNPCUnit:GetLandPosition_LUA(), D3DXVECTOR2(100,100), D3DXVECTOR2(10,-1) )
		
	end	

end





------------------------------------------------------------------------------
function MovePos( pos, dirvector, dist )
	
	pos.x = pos.x + dist * dirvector.x
	pos.y = pos.y + dist * dirvector.y
	pos.z = pos.z + dist * dirvector.z
	
	return pos
	
end
